### ISSUE TITLE
ND support for all layer types

### ISSUE THREAD

**Issue by royerloic** [napari/napari#10]
All layer types must/should support arbitrary n-dimensions.
Let's look at how hard that can be:

i)   list of points: trivial (x0, ...xn)
ii)  list of lines: trivial  ((x0, ...xn), (y0, ...yn))
iii) list of boxes: trivial ((x0, ...xn), (y0, ...yn))
iv) list of triangles: trivial ((x0, ...xn), (y0, ...yn), (z0, ...zn))
v)  list of n-dim simplices

It seems that lists of simplices (simplex is n-tuple of n-dim points) is a generic
representation for all these objects. 
We also want to provide a 'value' per point, a lut per layer, and a 'radius' per point,
which extends to lines, etc.. as thickness. 

Is there anything that is hard to represent(unlikely), or draw(more likely) 
for arbitrary n-dim ? @sofroniewn ?

**Comment by jni** [comment]
There is perhaps some room to use GeoPandas or similar here: one column is the polygons/points, and other columns are attributes of those polygons. We can then map visual attributes (size, colour) to actual attributes, which could be anything: strength of a synapse, neurotransmitter used, human-annotated vs automatic algorithm, etc.

GeoPandas is a library that holds this kind of data well, but it might be too specialised — I haven't looked into it in detail. But the point is that we should separate the data attributes, and the mapping of those attributes to visual features.

**Comment by sofroniewn** [comment]
@royerloic that list looks comprehensive to me. I havn't used GeoPandas nor looked at it in much depth either. Agreed it might be too specialized to use directly, but could provide a useful starting point. I can take another look at it too.

**Comment by sofroniewn** [comment]
We now have sliced nD support for all our supported layer types - `Image`, `Pyramid`, `Labels`, `Points`, `Vectors`, and `Shapes`
