### ISSUE TITLE
Add napari to pyviz.org

### ISSUE THREAD

**Issue by HagaiHargil** [napari/napari#1000]
## ❓ Questions and Help

[PyViz](https://pyviz.org/) is a comprehensive aggregator of visualization tools for Python. napari isn't in it, currently, I believe. What are your thoughts on asking them via an issue or PR to mention napari in their mind maps and other texts?

**Comment by sofroniewn** [comment]
Good idea, I can get that done soon if @jni agrees?

**Comment by HagaiHargil** [comment]
On the same note, is it cool if I'll send a hint to Python Bytes regarding napari?

**Comment by sofroniewn** [comment]
@napari/core-devs I am going to submit to napari to pyviz.org now under "Native GUI" tools - see here https://pyviz.org/tools.html. This involves a PR as described here https://github.com/pyviz/pyviz.org/blob/master/tools/README.md

@HagaiHargil I'm not familiar with Python Bytes, but by all means reach out to them. I assume this is who you mean https://pythonbytes.fm/ do let us know if they want more info or to talk. Thanks!!

**Comment by sofroniewn** [comment]
I have made a PR to pyviz now here https://github.com/pyviz/pyviz.org/pull/63

**Comment by sofroniewn** [comment]
We're up on the site now:

![image](https://user-images.githubusercontent.com/6531703/76130344-56549f00-5fbf-11ea-93f6-2cf54ff71416.png)

Not sure if we have the ability to have any conda downloads, so maybe I shouldn't have put `conda` here https://github.com/pyviz/pyviz.org/pull/63/files#diff-b01fe052bd1b11bf615f43220b43c42aR127, I can quickly fix with a follow-up PR if @jni can advise

Also not sure why our stars aren't showing, seems like a cacheing thing

**Comment by tlambert03** [comment]
i think you're right, based on the image URL, it looks like pyviz is doing their own badge cacheing.  I'd give it a week or so and then recheck.  I also wouldn't worry about the conda badge just yet, the download count is increasing (at [48 now](https://anaconda.org/conda-forge/napari/files)), so the monthly count probably takes refreshes slowly as well

**Comment by sofroniewn** [comment]
Ok great, thanks @tlambert03 I will close this now as the main objective is done. As mentioned about to @HagaiHargil we'd love it if you continue to spread word of napari to people in the python community and feel free to open a new issue if there are more groups we could be talking too or that want to talk to us!! Thanks again for suggesting this, it really is great to see napari up there with so many other great tools on pyviz.org :-)
