### ISSUE TITLE
Support visualization of lazy ndarrays

### ISSUE THREAD

**Issue by d-v-b** [napari/napari#103]
## 🚀 Feature
Natively support lazily-defined arrays, e.g. memory-mapped arrays, distributed dask arrays, etc.

## Motivation
For large arrays that don't fit in memory (e.g., light sheet microscopy data), it's very convenient to use an interface that represents the data _as if_ it were an in-memory array. In python: numpy arrays via `np.memmap` or `dask.array`, hdf5 files via `h5py`; imagej has virtual stacks for the same application. 

It would be awesome for a python-native array visualization tool like Napari to recognize and support this kind of data / interface.

Disclaimer: I don't know the napari internals at all, so you might already have this functionally baked in, or it's on your roadmap. But I didn't see a public discussion about this topic, and I haven't seen such a discussion anywhere else, so this seemed the best place to start it :)

## Pitch
Suppose I have a 4D `dask` array distributed along axis 0 (a typical scheme for volumetric microscopy data, which might be stored 1 file : 1 3D timepoint ) and  I want to visualize 2D slices from this dataset. I would like to run code like this:
```python
viewer = win.viewer
layer = viewer.add_image(dask_array, meta) 
```
...and adjust sliders to see different planes and different timepoints, _all without having to load the entire dataset into memory_. In my example the data happens to be distributed along the 0th (time) axis, so seeking through time involves loading data from disk, while seeking through space (axes 1,2,3) involves displaying data that are already in memory. Alternatively, each image might be really really big and thus chunked in space AND time (i.e., all axes are distributed), and so just displaying a full plane for a single timepoint requires loading multiple chunks of data from disk. 

Working with lazy, distributed data adds lots of new complications: to reduce latency, the display software might asynchronously cache data along the distributed axis; the display code will need to know about the data's chunking scheme, the display code may need gui elements to indicate distributed vs local axes of the data, etc. 

I know that this scheme is standard for visualization of EM data; but for EM data, most interactive operations (like tracing neurites) are _local_, in that only a single, small, contiguous block of data needs to be in memory (i.e., displayable at low latency). But for live imaging data -- data with a temporal dimension -- analysts often want the entire temporal context of multiple spatial regions, and the ability to quickly "span" the dataset from start to stop, and the ability to visualize a post-processed version of the data, and a lot of other things that analysts working with dead tissues rarely, if ever, need to do. 

So... it would be cool if napari could support this! Since things are early, maybe it's possible include features in the API such that distributed / lazy datasets have a native interface.

**Comment by jni** [comment]
:wave: @d-v-b! =)

Just fyi this is 100% on our roadmap in our brains, but thank you for making it visible to the outside world. =) dask arrays should be first-class citizens in Napari in the future.

**Comment by sofroniewn** [comment]
@d-v-b yup, thanks for highlighting - and writing a great issue! We'll be working to improve the public roadmap over the next month - and we definitely see this as a major value add for Napari.

**Comment by sofroniewn** [comment]
also @ambrosejcarr might be interested to weigh in here. Will be important to collect a couple user stories - I see EM, large stitched confocal, time-lapse light-sheet, as a couple - and understand the types of interactivity that people need for each one

**Comment by ambrosejcarr** [comment]
I would certainly be excited to be able to use Napari for large stitched confocal. Laziness across each dimension would be helpful (in my case, `time, channel, z, y, x`). I'd want the ability to pan and zoom, as implemented currently.

**Comment by jni** [comment]
Very happy to see the community interest here.

Thinking about this some more: initially, it would be close to trivial to do similar things as we do for NumPy, but just call `compute()` at the last minute before sending to the viewer. But, when doing lazy computation over a very large volume, we'll need two things:

- caching of recently-accessed strides. There'll necessarily be latency when loading volumes from disk or (worse) the network, and it would be best to minimise this when going back and forth over a small part of the volume. I think the recently added (Py3.5 I think?) `functools.lru_cache`, combined with dask.array, might get us very far very quickly.
- multiscale representations — we don't want to load 100TB when we zoom out. This might be trickier to do with existing tools, but suggestions are very welcome!

**Comment by sofroniewn** [comment]
I think we'd only want to support the multiscale representations for formats that provided hierarchies to us so we knew what to load and display at different zooms. I think both zarr and n5 support this. Probably worth test casing with some formats like that.

**Comment by kne42** [comment]
Zooming won't work with dynamic access how you think. Effectively we upload the entire slice to the GPU and the camera, in actuality, is a transformation we apply to the root node.

**Comment by sofroniewn** [comment]
Hmm yeah, we'd have to really hack into vispy zooms system to do something like once you've zoomed out / in far enough, intercept and reload the next chunk of data, (maybe cache the old chunk), and then return to the normal vispy zoom / pan. Not sure how feasible it is (I may still be thinking about it wrong) and what sort of performance lags we'd incur but it would be better than nothing and sort of like how google maps works (I think??) where if you do zoom to other parts of the map you have to wait a little for the data to arrive.

**Comment by jakirkham** [comment]
So Dask Arrays are now supported with PR ( https://github.com/napari/napari/pull/188 ) (example included). Caching is not currently handled.

**Comment by sofroniewn** [comment]
Following more nice work from @jakirkham exploring in memory zarr arrays PR #191, after the merge of PR #205 will we be able to support fast interactive browsing of very large zarr files via dask (where each 2D image to be displayed is still quite small).

Here is an example browsing an 100GB zarr file that is stored locally on my machine:

![zarr_data3](https://user-images.githubusercontent.com/6531703/55664956-c96ff700-57eb-11e9-84e7-5d6d05406e92.gif)


The data is volumetric timeseries off a lattice lightsheet from Gokul Upadhyayula. The raw data is `[199, 201, 1024, 768]` pixels in `[t, z, y, x]` that was stored as 199 `.tif` files (total ~125GB) each containing a whole volume at a single timepoint. I converted the tifs to a 100GB `zarr` file with a `[4, 4, 1024, 768]` chunking - leading to about 2500 chunks each about 40MB.

Unfortunately in the demo gif the axis coordinates in the status bar aren't updating as I move the dimensions sliders. We need to fix that so you can see the coordinates as we browse the images.

Curious if this sort of performance / workflow will meet the needs of @d-v-b or if he'd want different file formats supported. I didn't try making a dask array directly from the raw tiffs, but it might not work so well as each tiff is 600MB. This could be necessary though if we were doing 3D rendering of this data.

I think we are now looking good on the case where we've got volumetric timeseries data and each volume isn't too large. We still havn't tackled the case of 2D data that is bigger than 16,000 x 16,000 - for that case we'd probably need to use image pyramids - which we did not need to for this example here. Similarly we havn't looked at really big 3D like electron microscopy - curious what @perlman might be interested in for this use case.

Finally we havn't looked at remote loading of zarr files using dask, but that could be an interesting use case to explore next. We also havn't looked at loading tileDB files yet, but should do that too.

**Comment by perlman** [comment]
This looks great. I suspect we could use this, without modification, to pan through any of the large EM volumes stored as n5, including segmentation layers (as labels). [h/t to @jakirkham for integrating n5 support into zarr.]

Mipmaps will be needed for any useful navigation (zoom in/out).

**Comment by d-v-b** [comment]
That looks awesome! We typically store our data in chunked hdf5 files, each containing ~180 MB of data. Our chunking is pretty arbitrary, so it's absolutely something we could adjust if needed. In the coming days I'll play around with viewing our data with Napari; hopefully I get something as good as that .gif

**Comment by sofroniewn** [comment]
@perlman can you give me a little more detail on some example EM datasets that you might want to view. What size files? What total shape in pixels? What is the size of each chunk? How have you done the mipmaps? Are the segmentation layers stored as a different file or in the same file? Do they have the same pixel shape but are now integer labels with 0 background? How many labels are there?

Are you always accessing the data remotely or do you ever have a copy locally?

Maybe most easily, do you have an example dataset that you can share with us that has some of these properties? Ideally in the 100GB range so I can download it to my machine, and ideally with any of the mipmap stuff precomputed.

As I mentioned above right now we don't have any support for large 2D planes (i.e. bigger than 16,000 x 16,000 pixels) nor do we have support for many 2D chunks that are tiled next to each other, nor do we have support for any mipmap stuff.

@d-v-b that's great. Once we get #205 merged it should be ready to try. With #205 you are able to pass a `clim_range` argument to the `add_image` function which prevents a `min` and `max` operation from being applied to the data, which is important for these large datasets. For the chunking, you just want to make sure that the entire [X, Y] field is in one chunk and then I'd take a couple of Z slices and a couple of T slices and give that a go - maybe targeting a chunk size of < 40MB. Let us know how it goes!

**Comment by mrocklin** [comment]
It's very cool to see everything come together.  

@sofroniewn from the gif it looks like everything is pretty smooth.  However, I wouldn't be surprised if it felt a bit slower than an in-memory solution.  Is this the case?  I would be curious to know the response time you're getting.

You might consider looking at Dask's [opportunistic caching](https://docs.dask.org/en/latest/caching.html), which would hold frequently requested data in a fixed amount of memory.  

For larger images you might also want to take a look at the [coarsen](http://docs.dask.org/en/latest/array-api.html#dask.array.coarsen) function.  

I'm not sure, but it may be that the combination of `coarsen` along with opportunistic caching would end up building the image pyramid naturally.  Once you moved around a bit I suspect that the caching heuristics would preferentially hold onto the lower-resolution images more strongly than the higher resolution ones.

**Comment by jni** [comment]
> You might consider looking at Dask's opportunistic caching, which would hold frequently requested data in a fixed amount of memory.

🤯

**Comment by jni** [comment]
@JohSchoeneberg ☝️

**Comment by oeway** [comment]
Looks awesome! 
I am mostly interested in accessing Zarr arrays stored remotely (e.g. S3)-- in many cases it would not be realistic to pull 1TB images to a laptop.

**Comment by sofroniewn** [comment]
@mrocklin my initial impression was that it might feel a tiny bit slower, but was hard to tell. Unsurprisingly it depended on the chunk size. I plan to do some systematic profiling comparing in memory, local data, and remote data with different chunk sizes and can evaluation opportunistic caching at the same time. I will let you know what I find!

Thanks for the tip about `coarsen` + opportunistic caching - this could be a really interesting. I will give that some exploration too and report back.

**Comment by sofroniewn** [comment]
@mrocklin I've done some initial benchmarking using different chunk sizes and opportunistic caching for the example of a 2D timeseries dataset represented by `TxYxX` pixels where you only ever want to look at 2D slices of `YxX`. To do the benchmarking I created local zarr files of `np.random.rand` numbers of the appropriate shape and chunking scheme and loaded them in napari using dask and either enabled or disabled opportunistic caching. For the `in-memory` examples I called `np.asarray` on the dask array before passing it to napari. The measured times include the time to grab the data and use vispy to render it on the screen. As a rough guide, times > 30ms will lead to lag on a 30 Hz display and start being perceptible.

**tl/dr: opportunistic caching works great and each 2D slice should just be its own chunk**

Here are some plots from the benchmarking:
![image](https://user-images.githubusercontent.com/6531703/55690956-f556be00-594c-11e9-821e-01b024651926.png)
In this case the arrary was `TxNxN` where `N` is the value on the x-axis and the zarr chunk scheme was `(1, None, None)`. Moving to a new chunk is slower when using dask then when data is `in-memory` and using opportunistic caching incurs some overhead **but** for a `1024x1024` image the time is <10 ms, which leads to very good interactive performance.

![image](https://user-images.githubusercontent.com/6531703/55691016-be34dc80-594d-11e9-8f06-082a7c25aa9e.png)
This is the same array as above, but now measuring the time to return to a previously visited slice. Here opportunistic caching shows its benefits.

One thing that initially caught me off guard was that I thought the chunking scheme might be more import / interact more with the opportunistic caching. For example I thought that chunking the timeseries so that each chuck contained multiple adjacent timepoints might lead to speed-ups when viewing different timepoints within the same chunk. This however does not seem to be the case, instead you just occur an extra time delay by virtue of having to load in multiple timepoints when you only want to look at one.

![image](https://user-images.githubusercontent.com/6531703/55691049-559a2f80-594e-11e9-9cc3-acccd41c0c00.png)
In this case the arrary was `Tx2048x2048` the zarr chunk scheme was `(C, None, None)` where `C` is the x-axis. The time reported is for moving to a new slice within the same chunk (except for `C`=1 when the move had to be to a new chunk). Note that things only got slower as chunk size increased and that opportunistic caching did not help.

Looking at the docs for [opportunistic caching](https://docs.dask.org/en/latest/caching.html) more yields the following:

> We don’t explicitly cache the column ... Instead, we cache the hundreds of small pieces of that column that form the dask graph. It could be that we end up caching only a fraction of the column.

Now the behavior observed makes sense, the entire chunk is not cached even though it is loaded. Only the part that we used is cached. There could be use cases where we would want to cache the entire chunk - i.e. if we expected people to spend most time browsing the data somewhat locally. We might want to look into that in the future. I plan to do some similar benchmarking with zarr files on S3 and we might want to explore more caching or look-ahead like options there too (i.e. preemptively grab the next timechunk, under the assumption we will probably want that one next).

All in all though for the case of looking at 2D slice data it seems like the optimal chunking is just to have each 2D slice be its own chunk, so for `TxYxX` data chunk `(1, None, None)` and for `TxZxYxX` data chunk `(1, 1, None, None)`. If only looking at 3D renderings of volumetric timeseries the best chunking may be `(1, None, None, None)`. If sometimes looking at XY, YZ, XZ, or XYZ views then some more complex chunking may be more appropriate.

**Comment by jakirkham** [comment]
Given as you are only looking at accessing the data, would try using Zarr's [`LRUStoreCache`]( https://zarr.readthedocs.io/en/stable/api/storage.html#zarr.storage.LRUStoreCache ).

**Comment by mrocklin** [comment]
> Now the behavior observed makes sense, the entire chunk is not cached even though it is loaded. Only the part that we used is cached. There could be use cases where we would want to cache the entire chunk 

At some point we might experiment with turning off graph optimization and task fusion in particular, which tries hard to remove intermediate results.  These optimizations are good in the common case, but don't let other plugins like opportunistic caching see all of the intermediates.

**Comment by perlman** [comment]
It is nice to learn to about Zarr's caching behaviors, and to see the initial pyramid support (#211).

> @perlman can you give me a little more detail on some example EM datasets that you might want to view. What size files? What total shape in pixels? What is the size of each chunk? How have you done the mipmaps? Are the segmentation layers stored as a different file or in the same file? Do they have the same pixel shape but are now integer labels with 0 background? How many labels are there?


The short answer here is that EM datasets are somewhat arbitrarily large (FAFB was ~50TB, the MICrONS  volume is ~2PB). FAFB dimensions are 248832x134144x7063.

Mipmaps are generally done as powers of 2 in 3D and/or 2D. (For example, the neuroglancer version uses 3D (cubic) downsampling, but we use 2D for CATMAID as that's the primary way the data are used.)

Labels are generally handled as a separate data source with the same dimensions, though that could be a different object in the same container (hdf5, zarr, etc.)
0 is typically used to indicate background, but I have seen white and negative values used as well.
Millions of labels would not be uncommon for a large EM volume. 

> Are you always accessing the data remotely or do you ever have a copy locally?

Both, which is the beauty of using a format like zarr.

> Maybe most easily, do you have an example dataset that you can share with us that has some of these properties? Ideally in the 100GB range so I can download it to my machine, and ideally with any of the mipmap stuff precomputed.

Not immediately, though I can probably crop something from [Li19](https://www.biorxiv.org/content/biorxiv/early/2019/04/11/605634.full.pdf) when the data are made public.

> As I mentioned above right now we don't have any support for large 2D planes (i.e. bigger than 16,000 x 16,000 pixels) nor do we have support for many 2D chunks that are tiled next to each other, nor do we have support for any mipmap stuff.`

A few of the datasets in [Gao2019](https://science.sciencemag.org/content/363/6424/eaau8302) are larger than that. It's not just EM.

**Comment by sofroniewn** [comment]
I'm going to close this with the merging of #295, there will likely be more issues related to "big" data or "remote" data that come up in the future, but we've come a long way since the initial ask, now supporting `dask` and `zarr`, for large `nD` arrays and `2D` image pyramids.
