### ISSUE TITLE
Points / shapes highlight color settable by theme

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#1035]
## 🐛 Bug

As noted in https://github.com/napari/napari/pull/1033#discussion_r389383586 the highlight color for `Shapes` and `Points` should be inherited from our `theme` rather than being hardcoded in the `vispy_*.py` files

**Comment by psobolewskiPhD** [comment]
I think the highlight color is too close to the data to be set by the theme? Having it be in the settings along side the highlight width would be better? 
I say this as someone who always changes the highlight width +1 first thing with fresh napari, and I would change the color too to provide better contrast with some datasets.

**Comment by Czaki** [comment]
I think it is ok.

**Comment by dalthviz** [comment]
So, did a rough implementation and this is what I got:

![highlight](https://github.com/napari/napari/assets/16781833/83ffcd15-35b0-44ab-8a58-f5ae2a8bc023)

Branch with the code in case you want to check it locally: https://github.com/napari/napari/compare/main...dalthviz:napari:issue_1035

**Comment by psobolewskiPhD** [comment]
Looks good to me, works really nice and i'm pleasantly surprised how few changes in the vispy side were needed.
