### ISSUE TITLE
Label painting modifies the input array in-place

### ISSUE THREAD

**Issue by jni** [napari/napari#1041]
## 📚 Documentation

It was brought to my attention by @VolkerH that not everyone will expect that painting/editing labels will modify the input array in-place. It might be worth documenting this fact and also suggesting that an array copy should be made if this behaviour is not desired (e.g. `viewer.add_labels(segmentation.copy())`).

**Comment by BhavyaC16** [comment]
Hi, I am interested in working on this issue. Shall I add this documentation to the docstring of `add_labels` method in the file [napari/components/add_layers_mixin.py](https://github.com/napari/napari/blob/e07158c3c850f79d08671a806c3bc2258f280479/napari/components/add_layers_mixin.py#L376) as follows:

```
Modifies the input array in-place. 

Notes
-----
Pass a deep copy of the input array as a parameter to avoid this modification. 

For example, call add_labels as follows::
viewer.add_labels(data.copy())
where data is the input array.
```
