### ISSUE TITLE
Feature Request: Load images from non-image files via CLI

### ISSUE THREAD

**Issue by hectormz** [napari/napari#1045]
## 🚀 Feature

It would be useful to load images from non-image files such as `Matlab`'s `.mat` files.

## Motivation

I go back and forth between `Python` and `Matlab` and store images as matrices in `.mat` files, especially if they are floats/doubles. I'd love to be able to inspect images in these files which can be loaded as `numpy.ndarray`s via `scipy.io.loadmat` using `napari`'s command line interface. I'm sure that there are other file formats that others would be interested in.

## Pitch

I think `magic_imread` can be modified to load `.mat` files using `scipy.io.loadmat`. These files can presumably be a collection of many variable types. 

At worst, the simplest option would be to load any 2D/3D/4D etc matrix as a layer, without any additional arguments needed. A nicer approach would be to provide a list of variable names/layers to load, where providing none will load all images. 

This would be a great, fast feature that I can't even do with `FIJI`. But I am sensitive to not adding another argument to `__main__.py` for list of images to load from the files.

If implemented, perhaps reading from non-standard-image types could be handled by a separate function (called by `magic_imread` which could grow as other file types are desired.

**Comment by tlambert03** [comment]
You're in luck!  With #937 having just merged (but not yet in the release), it is now extremely to do this sort of thing with reader plugins.  Under the hood, the napari CLI now calls `napari.view_path` which hands the data to plugins.  If you have a function that can accept a filepath and return a numpy array, you can use it to create a plugin to load data into napari.   (`scipy.io.loadmat` is almost there, you would just need to extract some data from the return `mat_dict`),  Documentation for plugins is still in the works, but if you'd like to read about how to , you can look at the rst files in #1030 such as [this one](https://github.com/napari/napari/blob/fd6a67543b2a77ab2c56cb5734a2fcb6b1760b2d/docs/source/plugins/for_plugin_developers.rst).  Plugins modules can be really quite simple, and if they are named `napari_<your-plugin-name-here>.py` and are somewhere on your `sys.path`, they will be autodetected by `napari`.  For an example of implementing a plugin based on `imageio.imread`, see: https://github.com/napari/napari/blob/master/examples/reader_plugin.py

**Comment by hectormz** [comment]
@tlambert03 awesome, and I appreciate the `cookiecutter` setup! I'm glad you tipped me off to #937. I thought about this last week and could have sworn there were different CLI arguments like `--layers`, but couldn't find them in the project anymore. I thought I was crazy, but didn't look at recent commits. I'll come back with any questions, but would be happy to create a plugin

**Comment by hectormz** [comment]
@tlambert03 Are the `napari.plugins` imports:
```python
from napari.plugins import hookimpl
from napari.plugins.hookspecs import LayerData, ReaderFunction, Optional, List
```
relating to a version ahead of `master` branch of napari on Github, or is the `cookiecutter` template outdated?

**Comment by tlambert03** [comment]
Ah, the cookie cutter needs updating!  Thanks for reminding me.  We changed all usages of “hookimpl” to “hook_implementation” and “hookspec” to “hook_specification”

**Comment by hectormz** [comment]
Got it, thanks! I had to use:
```python
from napari.plugins import napari_hook_implementation
from napari.plugins.hook_specifications import LayerData, ReaderFunction, Optional, List
```

**Comment by tlambert03** [comment]
Yeah, that's correct for napari 0.2.12 ... but in the next release (and in master since #937), note that the types `LayerData` and `ReaderFunction` have moved to `napari.types`.  I am, at this moment, updating [napari-cookiecutter](https://github.com/napari/cookiecutter-napari-plugin) to reflect these changes...

I'll also note (and will mark this in the updated cookiecutter) that we have made it so that you don't need to import napari _at all_ in order to create a plugin file.  The hook_implementation decorator is probably best imported from `pluggy` (a much more minimal dependency):

```python
# instead of 
from napari.plugins import napari_hook_implementation
# you can use
from pluggy import HookimplMarker
napari_hook_implementation = HookimplMarker("napari")
```

and the types `LayerData` and `ReaderFunction` are only required if you want to provide type hints in your plugin function signatures

with type hints:
```python
from napari.types import LayerData, ReaderFunction
from typing import List, Optional, Union

@napari_hook_implementation
def napari_get_reader(path: Union[str, List[str]]) -> Optional[ReaderFunction]:
    ...
```
without type hints:

```python
@napari_hook_implementation
def napari_get_reader(path):
    ...
```

also, just in case it isn't obvious: until the next napari release, plugins will be detected, but _will not do anything_... so if you actually want to test out the functionality of a plugin, you'll need to do so using the current master branch on napari, and not the 0.2.12 release

**Comment by hectormz** [comment]
Thanks @tlambert03 !

I've been working a plugin that's starting to do what I want:
https://github.com/hectormz/napari-mat-images

I may come back with some more advice and tips about crafting my plugin.

**Comment by psobolewskiPhD** [comment]
I'm going to close, I think with the plugin ecosystem we can consider this issue out-dated and solved.
