### ISSUE TITLE
Docs locations and format

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#1049]
I think we could use some more discussion on exactly where our docs go, and what format they are in.

I agree with @sofroniew's https://github.com/napari/napari/issues/1026#issuecomment-598867558 that it would be nice to have a place to put some "troubleshooting" notes.  At the moment, the pattern is to (probably) make another markdown file in `docs/developers`...  
That worked pretty well when the docs were mostly viewed on github, and the sphinxdocs were strictly the autogenerated API docs, but it's really not ideal for lots of documentation (the readme has to basically become the table of contents for the dev docs, and integration with sphinxdocs becomes clunky)

It would be pretty easy make a "troubleshooting" section on our main [sphinx docs](https://napari.org/docs/) page, but the best place for that is really in `docs/source`, and _probably_ in `.rst` format as long as we're going with sphinx.  I personally prefer markdown in general, but resign myself to using rst when working with sphinx.

Anyway, therein lies the conflict... we have a handful of ever-growing markdown files that _can_ be integrated into the sphinx docs as is being done in #967, but I kinda saw that more as a "stop-gap" way to put our existing markdown docs somewhere visible in sphinx... rather than a sustainable long-term plan for expansion of docs.

thoughts?

**Comment by will-moore** [comment]
I only found https://github.com/napari/napari/blob/master/docs/source/plugins/for_plugin_developers.rst by searching for "plugin" in the source code. Don't know if I missed an easier way to find it?
But the page itself was great. Ended up creating https://github.com/will-moore/napari-idr (very work-in-progress).

**Comment by tlambert03** [comment]
Hi @will-moore, our docs are served at https://napari.org/docs/
(and that specific page is [here](https://napari.org/docs/plugins/for_plugin_developers.html))

glad you found it helpful!  Definitely will be watching napari-idr with interest!

**Comment by tlambert03** [comment]
by the way ... I _just about an hour ago_ updated the [cookiecutter](https://github.com/napari/cookiecutter-napari-plugin) significantly (and added a lot of info to the readme there) ... now with auto-deployment and testing using github actions, and version control based on git tags.  If you want to try the cookiecutter again, hopefully it won't be too much to move the code you did write into it, to benefit from all the new stuff.

**Comment by will-moore** [comment]
Thanks for the update.
We've actually moved the napari plugin code to https://github.com/ome/ome-zarr-py which will be more general-purpose.

**Comment by jni** [comment]
There's been a bit of discussion about this in #1365. We're still a bit torn within the team about using markdown vs RST. My current intuition is that the advantages of writing in Markdown and [MyST](https://twitter.com/choldgraf/status/1272633413132943360) outweigh the pitfalls, and we should just embrace using markdown docs with sphinx.

**Comment by tlambert03** [comment]
that's fine with me.  but just wanted to make sure you saw https://github.com/napari/napari/issues/1365#issuecomment-645481435

in other words, we _still_ have to use rst in docstrings.  so devs still need to have a little contextual awareness and rst chops.

**Comment by jni** [comment]
Yes, I don't want to change docstring format, as that is very standard in the ecosystem. For me, docstrings are their own thing and the context switch is pretty easy.

**Comment by tlambert03** [comment]
k, like i said that works for me.  Maybe when we add MyST, we can also go through and remove all the markdown from our docs?

**Comment by sofroniewn** [comment]
> Maybe when we add MyST, we can also go through and remove all the markdown from our docs?

Makes sense to me, we should then add somewhere to our docs a new section on docs with this policy :-)

**Comment by liaprins-czi** [comment]
Is this issue still relevant after the switches @kne42 made when moving to the current (temporary) Sphinx template? If it is then maybe relevant for @melissawm ? Otherwise it can be closed?

**Comment by chili-chiu** [comment]
> Is this issue still relevant after the switches @kne42 made when moving to the current (temporary) Sphinx template? If it is then maybe relevant for @melissawm ? Otherwise it can be closed?

@tlambert03 wondering if there are still items that are not addressed by the sphinx theme?
