### ISSUE TITLE
Block saving with a context manager

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#1065]
## 🐛 Bug

As noted in https://github.com/napari/napari/pull/1010#discussion_r394962872 the `block_saving` in the labels layer should probably done by a context manager. @jni @kne42

**Comment by psobolewskiPhD** [comment]
I *think* this was addressed or made irrelevant by https://github.com/napari/napari/pull/4702
Can we close cc: @DragaDoncila

**Comment by DragaDoncila** [comment]
@psobolewskiPhD yep, I think this should be closed. If folks experience any issues or have feature requests related to labels layer paint events, they should open a separate issue 😊
