### ISSUE TITLE
Extract viewer features to separate package

### ISSUE THREAD

**Issue by Czaki** [napari/napari#1071]
## 🚀 Feature
Extract napari viewer (and maybe some other features) to separate package (napari-core, napari-viewer) with reduced dependencies and exposed Qt widgets.

## Motivation

I would like use power of napari viewer (multiple layers) in my project but in current configuration it have many dependencies which may be not needed in given project.

Splitting on subpackage may simplify usage of declarative dependencies in metapackages. 

## Pitch

Simplify of embedding viewer in another applications. 

## Remarks

I can support such work with code contribution.

**Comment by sofroniewn** [comment]
Hi @Czaki, thanks for raising this issue. We're definitely committed to making sure other people can build on top of the work we're doing at napari as easily as possible, but I'm also a little hesitant to splitting things out too much due to the potential added complexity.

Can you describe a little more about exactly what you'd like separated out and why?

I saw you contribution in #1059 which was great as having that flexibility around PySide2 vs PyQt5 makes lots of sense.

I've also seen your contribution in #1061, which we need to think through, but certainly has appeal too. Apologies no one has responded to that yet, I will now.

Given those two works in progress, could you explain which additional dependencies you'd like to avoid and which parts of napari you'd like to use?

We have at times thought about what would it be like to make our rendering engine swappable, so instead of using vispy someone could use another tool inside a canvas, say based on VTK. Is this what you're interested in?

We have also at times thought about what would it be like to make our whole front-end interchangeable, so dropping Qt entirely, potentially for a javascript based tool or a Dash based tool (cc @emmanuelle). Is this what you're interested in?

I think that while we see both of those two use cases as things that we might want to eventually be possible, given that we're still working on so much of the basic models, splitting out now had felt premature. But I'd certainly love to lean more about what your needs are.

**Comment by jni** [comment]
@Czaki @sofroniewn it's worth noting that we did start out as separate packages and eventually came to the conclusion that the overhead wasn't worthwhile. I think while we remain in alpha, this will remain true. A possible middle ground is to make some dependencies optional. For example, now that the console loading is lazy, we could potentially make our ipython/jupyter stack dependencies optional.

As @sofroniewn indicated, we're happy to work with you to make your work easier, but the best course of action will depend on your exact use case, so do let us know. Thank you for all your efforts so far!

**Comment by Czaki** [comment]
My case is that I create tool for biologist for quantitative analysis (mainly concentrated around cell nucleus analysis -  https://github.com/4dnucleome/PartSeg). I create own viewer, but it is worst than napari and I prefer to use one which is developed with more experienced people.  

Because it is addressed to mainly biologist, not bioinformatics it is important to provide it in exec form, not only as python package. Some dependencies create problem or increase size of package (eg. matplotlib) 

Maybe splitting on several package is not needed. But in this moment napari have dependecies which is nice when it is used as stand-alone gui but not need when embeding. Like:

* skimage, matplotlib (#1061)
* PySide2 (#1059 fix it partially, because still need two steps installation see https://github.com/napari/tutorials/pull/61#discussion_r395479073)
* qtconsole 
* ipykernel

Other solution is that `pip install napari` will not install whole napari dependencies  but only core one and users need to change their dependencies to `pip install napari[default]` Then maybe also PySide2 will be not installed by default.

**Comment by sofroniewn** [comment]
@Czaki thanks for the extra info about your use case and for the link to the your segmentation tool, it looks very cool, and we'd love to make it possible for you to use napari inside it.

I see your work is part of the 4D nucleome project, and that makes me wonder if you know @strambc (Caterina Strambio De Castillia) from UMMS as she is funded by the organization I work for as a [CZI imaging scientist](https://go.chanzuckerberg.com/imaging) and I know does a lot with the 4D nucleome too.

> Because it is addressed to mainly biologist, not bioinformatics it is important to provide it in exec form, not only as python package. Some dependencies create problem or increase size of package (eg. matplotlib)

Absolutely, that makes sense. We're also planning to make napari available as an exec (see #496 for progress) as we also want the tool to be used by non-coding biologists, so we have the same values there. We'll actually also be working on plugin infrastructure to allow people to more easily integrate analysis and build domain specific tools on top of napari too, but that is still a work in progress. You can read more about our approach to all of this on our [mission and values page](https://napari.org/docs/developers/MISSION_AND_VALUES.html), which I recommend looking at if you havn't seen it yet.

> Maybe splitting on several package is not needed. But in this moment napari have dependecies which is nice when it is used as stand-alone gui but not need when embeding. Like:
>
> - skimage, matplotlib (#1061)
> - PySide2 (#1059 fix it partially, because still need two steps installation see napari/tutorials#61 (comment))
> - qtconsole
> - ipykernel

Yes, looking at this list now, if we are able to finish up the work around #1059, and get #1061 in, then I feel like the main thing holding you back is our console. I'd like to know how much of a burden bringing the console down too is (for example what % of the napari install size is consumed by the console after we fix the other things) and is there a dependency conflict / management burden of having the console there too? 

Now that we've made the console imports lazy in #1055 it actually wouldn't be that hard to go one step further and make it optional (though I'm curious if even for your tool @Czaki it might be nice to have the console be available as I have found that even for primarily non-coding users who might be able to do a tiny bit of scripting the console can be quite nice).

> Other solution is that pip install napari will not install whole napari dependencies but only core one and users need to change their dependencies to pip install napari[default] Then maybe also PySide2 will be not installed by default.

I think we will always want `pip install napari` to bring down the things we think users need to be successful, but we could have a `pip install napari_base` etc. that developers could use to bring down minimal parts that they could build off of.

I look forward to interacting more! And please keep making issues and PRs as you work on integrating napari into your tool. I will reiterate again, that we're still quite early so there will likely be breaking changes from time to time, but hopefully we'll do a good job communicating them and how to fix them as part of our release process.

**Comment by Czaki** [comment]
@sofroniewn 
> I see your work is part of the 4D nucleome project, and that makes me wonder if you know @strambc (Caterina Strambio De Castillia) from UMMS as she is funded by the organization I work for as a [CZI imaging scientist](https://go.chanzuckerberg.com/imaging) and I know does a lot with the 4D nucleome too.

I do not know her but I'm only PhD student. Maybe she know my PI (Dariusz Plewczyński) 

> Absolutely, that makes sense. We're also planning to make napari available as an exec (see #496 for progress) as we also want the tool to be used by non-coding biologists, so we have the same values there. We'll actually also be working on plugin infrastructure to allow people to more easily integrate analysis and build domain specific tools on top of napari too, but that is still a work in progress. You can read more about our approach to all of this on our [mission and values page](https://napari.org/docs/developers/MISSION_AND_VALUES.html), which I recommend looking at if you havn't seen it yet.

As you see I create #1082 with comes from my experience with PyInstaller in PartSeg. Again I see that PyInstaller better work with PyQt5 
 
> I look forward to interacting more! And please keep making issues and PRs as you work on integrating napari into your tool. I will reiterate again, that we're still quite early so there will likely be breaking changes from time to time, but hopefully we'll do a good job communicating them and how to fix them as part of our release process.

I will. 

What do you think about move module `_qt` to `qt` (with keep possibility to import form `napari._qt`)?

**Comment by tlambert03** [comment]
> Again I see that PyInstaller better work with PyQt5 

you've mentioned this a number of times, so I wanted to just point out that the reason we're trying to work with pyside2 instead of pyqt5 is related to licensing. ([see side discussion](https://napari.zulipchat.com/#narrow/stream/212875-general/topic/qt.2C.20bundled.20apps.2C.20.26.20licensing)) It's not completely out of the question to bundle with pyqt5, but we have a slight preference for pyside2 and its LGPL.  It's true that PyQt5 works immediately, but pyside2 is definitely doable: I pushed my changes to https://github.com/napari/napari/pull/496 with pyside2 working (only tested mac for now).  In the past I had them all working and need to just dedicate some time again for windows and linux.

**Comment by Czaki** [comment]
> you've mentioned this a number of times, so I wanted to just point out that the reason we're trying to work with pyside2 instead of pyqt5 is related to licensing

I always have a problem when taking with peoples in different threads if repeat same information, to lower entry level for people who do not read all threads, or reduce information to only unique. 

This time I choose first approach. I understand that you prefer second one so I try to reduce repetition in future. 

I agree that it is doable with `PySide2` and it should be enough to write own hooks for missed modules and some move function for this which are wrong placed. But this increase maintenance cost. Because need to trace  changes in PyInstaler and PySide2 inner organization.

**Comment by tlambert03** [comment]
it's ok! :) I definitely don't prefer the second approach.  (my comment wasn't trying to prevent repetition, it was just for your edification).  we've been discussing issues around bundling for many months here, so was just trying to point out some motivations that may not be immediately obvious.

**Comment by Czaki** [comment]
I also go through using PySide2 in my project (PartSeg) because of license but finally decide to create bundle base on  PyQt5 because PySide2 based consumes to many time. But napari team is bigger.

**Comment by Czaki** [comment]
In my project I need to synchronize at least two viewers (Data comparission). If it is possible currently (but undocmented), or I need Create PR with such feature. And If PR then changes should be done in `ViewerModel` or `QtViewer`? 

More generic, Viewer should be possible to control from code, not only by mouse.

**Comment by tlambert03** [comment]
Can you provide a little more detail on what exactly you want to synchronize?  And also what specific properties of the viewer you feel like you can’t control with code?

**Comment by Czaki** [comment]
I would like to allow user for simple pixel-wise compare result of different method on same data. Currently I allow user to synchronize layer, position of viewer centre (x,y) and current layer. so user can see exactly the same area on both viewers. 

So I would like to control x,y position, zoom level and current layer (z-stack, time etc)

**Comment by tlambert03** [comment]
ah, then it sounds like you'll want to read up on the [vispy camera object](http://vispy.org/scene.html#module-vispy.scene.cameras).
it lives at `viewer.window.qt_viewer.view.camera`.  There are a lot of good examples of controling camera state programmatically in https://github.com/guiwitz/naparimovie

current layer can be controlled by modifying the `LayerList` object at viewer.layers. (e.g. `viewer.layers[0].selected = True`)

the dims sliders (z-stack and time) can be controlled by modifying `viewer.dims`.  For instance `viewer.dims.set_point(0, 10)` will change the zeroth axis to the 10th position.

**Comment by Czaki** [comment]
Other question. Why in docs there is using `array` instead of `np.ndarray`. Like in 'AddLayersMixin.add_image`. This produce warning in PyCharm. There is some reason for this, or may be changed?

**Comment by tlambert03** [comment]
don't use pycharm and not sure what they do when parsing docstrings.  @jni

**Comment by Czaki** [comment]
I add example warning message:

![Zrzut ekranu z 2020-04-23 15-38-15](https://user-images.githubusercontent.com/3826210/80105371-cff91a00-8578-11ea-974b-ba9aade37383.png)

**Comment by sofroniewn** [comment]
> Other question. Why in docs there is using array instead of np.ndarray. Like in 'AddLayersMixin.add_image`. This produce warning in PyCharm. There is some reason for this, or may be changed?

If defer to @jni here too. This was not intentional on my part

**Comment by jni** [comment]
I mean, honestly, I think this is PyCharm being too smart for its own good. Docstrings are not meant to be interpreted as strict typing information, but rather as English-language typing information. In this case, we use "array" because it can be any kind of array, including not just a numpy array but also a dask array and a zarr array. So np.ndarray would be an excessively precise type specification.

Once we improve typing with an Array protocol, we can make this better. For now, I think there is probably a setting in PyCharm "extract type information from docstrings" that you can turn off. Ideally, you should be able to ignore just this one type annotation, but I doubt that exists. It might be worth raising an issue with PyCharm.

**Comment by Czaki** [comment]
> I mean, honestly, I think this is PyCharm being too smart for its own good. Docstrings are not meant to be interpreted as strict typing information, but rather as English-language typing information. In this case, we use "array" because it can be any kind of array, including not just a numpy array but also a dask array and a zarr array. So np.ndarray would be an excessively precise type specification.

I look to numpy docstring type specification https://numpydoc.readthedocs.io/en/latest/format.html and this part is defined as type definition. So PyCharm works as expected. I like extraction type from docstring. It simplify and speedup code writing when IDE support this. (For python 2.7 types in comment was only way to introduce typing information, and for part of them there are still no type annotation)

> Once we improve typing with an Array protocol, we can make this better. For now, I think there is probably a setting in PyCharm "extract type information from docstrings" that you can turn off. Ideally, you should be able to ignore just this one type annotation, but I doubt that exists. It might be worth raising an issue with PyCharm.

So I think twat I will create such PR. But what you think about type annotation in function signature (Wider support in IDE)?

**Comment by psobolewskiPhD** [comment]
I think this issue is largely replaced by https://github.com/napari/napari/issues/5940
@czaki you happen to be the OP, what do you think?

**Comment by jni** [comment]
Yes I would agree with closing this in favour of #5940. But it's fun taking a trip down memory lane. 😃 Let's close this and continue the discussion about untangling things there.
