### ISSUE TITLE
Main imshow api

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#108]
## ❓ Questions and Help

Our main `imshow` api has changed since our last release. Now `imshow` returns a `window` which contains a `viewer` which contains the `layers` - which is what I think most people will want to interact with most of the time
```python
from napari_gui import imshow
window = imshow(data)
window.viewer.layers
```
whereas previously `imshow` returned a `viewer` which contained both a `window` and the `layers`
```python
from napari_gui import imshow
viewer = imshow(data)
viewer.layers
viewer.window
```
while from a hierarchical organisation sense this was less clean it made it a little easier for the user to access the `layers` that they were interested in.

Do we feel we've made the right choice with the new version? Is there a third option we should be considering like having `imshow` return the layers?

The other major access pattern we have is 
```python
from napari_gui import Window, Viewer
viewer = Viewer()
window = Window(viewer)
viewer.add_image(data, {})
```
Is this preferable? Do we want to force users to do this? (I think there the answer is no and we want to allow for `imshow` for convenience and keep this functionality for power users).
Any thoughts / comments appreciated!! I think it would be good to get an answer to this before our next release, see issue #106

**Comment by jni** [comment]
I think `viewer` is more natural and more closely corresponds to how `matplotlib.pyplot.imshow` returns an `AxesImage`, not a `Figure` (not to mention the actually application window with the toolbar and everything). I think we should provide a way to grab the window and everything else, but *that* should be work, not adding layers etc.

**Comment by sofroniewn** [comment]
If `imshow` returns a viewer does that mean we need to append the window to the viewer or provide a get window method. A little trickier maybe once we more to a model where the same window could contain multiple viewers but in different tabs.

I do tend to agree with you, I dislike the extra difficultly in accessing the `viewer` and the actual `layers` object. Maybe we find a way to switch things back, at least for when we push our next release so that things aren't breaking unnecessarily.

**Comment by jni** [comment]
@sofroniewn 

>  A little trickier maybe once we more to a model where the same window could contain multiple viewers but in different tabs.

This is ok, in the same way that a mpl Figure can have many axes. There are ways to get at the different axes from the figure, and at the figure from the axes.

**Comment by jni** [comment]
And yes, I do suggest switching back for the upcoming release.

**Comment by AhmetCanSolak** [comment]
I know we want to provide more ease of use but I really dont like accessing to window from viewer as in previous version. I am not sure if it will be still useful if we prevent access to window from returned viewer. Love to hear ideas on this.

Also, I strongly believe that we should keep `viewer.add_image()`, since in scripting way it is the cleanest one.

**Comment by sofroniewn** [comment]
Unfortunately if I remove the `window` property from `viewer` but have imshow return just the viewer the `window` gets garbage collected and disappears. I can see why having window on viewer is unpleasant but it is how matplotlib approached the problem

**Comment by sofroniewn** [comment]
@AhmetCanSolak thanks to some tips from @kne42 I have changed the code so that you can no longer access the viewer from the window, but the window doesn't get garbage collected. Hopefully this addresses some of your concerns

**Comment by AhmetCanSolak** [comment]
@sofroniewn thank you, but just to clarify. access to viewer from window or to window from viewer? :D

**Comment by sofroniewn** [comment]
my mistake!! access the window from the viewer (i.e. go back up the hierarchy) - good catch :-)

**Comment by jni** [comment]
@AhmetCanSolak can you provide some concrete examples where going up the hierarchy is bad? I am very sympathetic to questions of "taste" and can definitely recognise that it's bad when something smells bad, but essentially a doubly-linked hierarchy tree doesn't smell bad to me (probably because Matplotlib has gotten me used to that smell ;), so I'm trying to get a sense of why you think it's bad.

Another solution regarding the garbage collection would be a global registry of Napari windows. But globals also smell bad. ;)

**Comment by jni** [comment]
Oh never mind I just saw that we are using the global registry now. :joy: 

Q: does the window class delete itself from the list when it's closed?

**Comment by sofroniewn** [comment]
@jni no, there is no deletion on closing - probably worth adding right? The global registry only gets used when using the `imshow` api - it doesn't get used otherwise

**Comment by jni** [comment]
> probably worth adding right?

It certainly makes sense to me!

**Comment by sofroniewn** [comment]
I'm not sure how to do this - maybe @kne42 has an idea? Could maybe also wait to fix in a follow-up PR.

**Comment by sofroniewn** [comment]
We have now merged the existing PR, but I'll keep this issue open so that we can revisit the deleting of the reference on closing

**Comment by kne42** [comment]
Since the viewer is the "main" object being passed around I think it would make the most sense to include a `_refs` attribute on it which holds strong references to anything which attaches itself to the viewer including windows and the Qt component. In this sense, the viewer is still effectively agnostic to these objects while preventing them from getting garbage collected.

**Comment by royerloic** [comment]
Just a note here: globals are bad for sure, viewer should hold everything that it contains, ideally in a recursive fashion (tree). Garbage collection should do its work unless we really don't need something anymore (remove layer).

**Comment by sofroniewn** [comment]
@royerloic the problem that gets us into then is that `viewer` would have `window` appended onto it, but we wanted to make `viewer` independent of the `window` (which is the top level object, but which we don't want to return as it is less useful than `viewer`).

**Comment by sofroniewn** [comment]
The main imshow API has been removed in #143 and we will proceed with the API design laid out in #146
