### ISSUE TITLE
Changing points color via API doesn't work in add mode

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#1085]
## 🐛 Bug

Following up on https://github.com/napari/napari/pull/898#issuecomment-604011240 it seems like changing color of the points fails via the API when in add mode. I think it used to be that you couldn't select points in add mode, but then that changed in #972, and so now the points get highlighted, which makes one think they should be able to edit the properties I think. Thoughts @kevinyamauchi?  

Run `examples/add_points.py`
Open console
Run
```python
viewer.layers[-1].selected_data = [0, 1]
viewer.layers[-1].current_face_color = 'blue'
```
The points should turn blue. Note the reason this fails is because the layer is in `add` mode

**Comment by kevinyamauchi** [comment]
Thanks for flagging this, @sofroniewn! We had changed the selection behavior to this when we allowed selections to persist across modes in #907 (see [this comment](https://github.com/napari/napari/pull/907#issuecomment-580358966)). I believe the rationale was to prevent previously-selected points from accidentally being modified when switching to "add" mode and then changing the properties in the UI (with the intention of setting the properties for the new points). After using it, do you think that still makes sense?

**Comment by sofroniewn** [comment]
I found the current behaviour non-intuitive. One option might be to have no ability to have selected points in `add` mode, i.e. `selected_data` always return the empty set, even if someone tries to select points via the API in add mode. Or maybe better, if you modify the `selected_data` property then inside the setter we force you into `select` mode. Maybe that is best? Thoughts @kevinyamauchi?

**Comment by sofroniewn** [comment]
Hi @kevinyamauchi we're going through some of our old bug issues, trying to bring the number down, curious what your thoughts on this one are. Is it still like this? Should we change this? Would this change when we do the color manager stuff?

**Comment by kevinyamauchi** [comment]
Hey! Sorry, @sofroniewn , I lost track of this one. I think we can patch this before we do `ColorManager`. The implementation might change a bit with `ColorManager`, but I think the heart of this is choosing what we want the behavior should be.

From your previous comment that I accidentally ignored (sorry again!) it sounds like you're advocating to switch to `select` mode when the `Shapes.selected_data` setter is used. I think that is a reasonable approach. Do you think we should emit a a warning when we automatically switch modes? The only real indication of a change would be the little mode buttons in the layer controls and if somebody is in the command line or scripting, they probably wouldn't see that.

**Comment by psobolewskiPhD** [comment]
@sofroniewn @kevinyamauchi 
Is this still an issue? Using the instructions in OP, I get 2 of the `+` turning blue. If I modify to `viewer.layers[-1].selected_data = [0, 1, 2]` then all three turn blue.

**Comment by psobolewskiPhD** [comment]
Selecting while in add mode works via the A and Shift-A keybindings, plus using `viewer.layers[-1].selected_data = [.....]`
Closing. If there is something related to points selection still, then can make a new issue with details.
