### ISSUE TITLE
ListModel.append does not check type

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#1086]
## 🐛 Bug
in working on layer groups, I found a strange lack of type checking when appending to a `ListModel` (which inherits from `TypedList`).  [`ListModel.append`](https://github.com/napari/napari/blob/59ed366e9d492a2389c451468fd8b9f96508b4e2/napari/utils/list/_model.py#L59)  jumps right over `TypedList.append`
https://github.com/napari/napari/blob/59ed366e9d492a2389c451468fd8b9f96508b4e2/napari/utils/list/_model.py#L58-L60

... and if you try to something that is not a `Layer` to a `LayerList`, it works fine up until throwing an error (unrelated to typing) in `components.layerlist._add`.  Is that supposed to be `TypedList.append(self, obj)`?  or was that intentional?

**Comment by sofroniewn** [comment]
Maybe @kne42 can comment on this one?
