### ISSUE TITLE
Clarification in interactive_scripting.py

### ISSUE THREAD

**Issue by AndrewGYork** [napari/napari#1101]
The following lines confuse me:

https://github.com/napari/napari/blob/cfadbdb778fbc8f44a9227622da0f1112e77ab95/examples/interactive_scripting.py#L21-L23

If I understand correctly, layer.data is a numpy array of random floats, and layer.data.all() returns a single Bool, which is almost certainly True; the same is true for 'dat'. If I'm correct, the while loop never triggers. If it did, what effect would an additional assignment have?

**Comment by AhmetCanSolak** [comment]
Hi @AndrewGYork ! Thanks for reaching out!

numpy.ndarray.all is `True` if all elements evaluates True.
Assuming everything works smoothly, you are correct, this while loop never triggers. In case assignment somehow blocked or something else this while loop would be triggered.

If you happen to use some lazy loading numpy compatible libraries you might want to keep such while loop around to verify assignment of the attribute.

Please let me know if you have further questions and/or my explanation is not satisfying enough.

**Comment by AndrewGYork** [comment]
Thanks, Ahmet!

**Comment by jni** [comment]
@AndrewGYork @AhmetCanSolak for context, the history of that while-statement is that @bryantChhun once upon a time was finding that `layer.data = dat` did *not*, in fact, update the whole data synchronously, which is still puzzling to me and might have been a red herring. See #465. But as written it is indeed a bug/nonsensical, and is meant to be:

```python
while not np.all(layer.data == dat): 
     layer.data = dat
```

Again, I suspect we were somehow misreading the situation and actually the whole loop can be removed from the example.
