### ISSUE TITLE
Functions to split/combine multiple layers along an axis

### ISSUE THREAD

**Issue by GenevieveBuckley** [napari/napari#1103]
## 🚀 Feature

Juan suggested on zulip that it would be a good idea to have:
1. A function to split an image axis into separate layers
2. A function to combine multiple layers into a single layer along a new axis.

## Motivation

This would allow users to more easily work with multichannel images, etc. since they may be saved as a single file and imported into napari as a single layer.

**Comment by cwood1967** [comment]
Hi. Is anyone currently working on this? If not, I would like to see what I can to do contribute, and this seems like a good first issue. Splitting/combining layers is straight forward, but where to put the function isn't clear to me. 

Thanks for any suggestions,
Chris

**Comment by GenevieveBuckley** [comment]
It's open, go and take a shot at it @cwood1967 

It's totally fine to get a working function together first, and then we can work out where's best to put it.

**Comment by sofroniewn** [comment]
Closed by #1322!
