### ISSUE TITLE
Screenshots taken during a pytest run appear entirely black

### ISSUE THREAD

**Issue by GenevieveBuckley** [napari/napari#1105]
## 🐛 Bug

Screenshots taken during a pytest run appear entirely black.

## To Reproduce

1. In pytest (this test produces an AssertionError when it should not)

```python
import numpy as np
from skimage.data import camera


def test_screenshot_introspection(viewer_factory):
    view, viewer = viewer_factory()

    layer = viewer.add_image(camera())
    screenshot = viewer.screenshot()
    # the screenshot should NOT be completely black
    assert not (screenshot == np.array([0, 0, 0, 255])).all()
```

2. With python (this script does not produce an AssertionError, which is good and what we expect)

```
import napari
import numpy as np
from skimage.data import camera


with napari.gui_qt():
    viewer = napari.Viewer()
    layer = viewer.add_image(camera())
    screenshot = viewer.screenshot()
    # the screenshot should NOT be completely black
    assert not (screenshot == np.array([0, 0, 0, 255])).all()

```

## Expected behavior

I expected the contents of a screenshot acquired during a pytest run to look the same as a screenshot taken when running napari normally.

## Environment

 - Please copy and paste the information at napari info option in help menubar here:

I'm running napari using the current master branch:

napari: 0.2.12+37.g7a831db.dirty
Platform: Windows-10-10.0.17134-SP0
Python: 3.8.1 (default, Mar 2 2020, 13:06:26) [MSC v.1916 64 bit (AMD64)]
Qt: 5.14.1
PySide2: 5.14.1
VisPy: 0.6.4
NumPy: 1.18.2
SciPy: 1.4.1
scikit-image: 0.16.2
Dask: 2.12.0

GL version: 4.4.0 - Build 20.19.15.5058
MAX_TEXTURE_SIZE: 16384

 - Any other relevant information:

## Additional context

We talked about using screenshot introspection to write some tests for https://github.com/napari/napari/pull/1053 (that PR addresses issue https://github.com/napari/napari/issues/1050). Screenshot introspection is a better idea than `pytest-mpl` because then we won't clog up the repository with lots of big files with benchmark images.

**Comment by GenevieveBuckley** [comment]
@tlambert03 do you think this could have something to do with the way `viewer_factory` works during pytest runs?

**Comment by tlambert03** [comment]
I wouldn’t expect this to have anything to do with the viewer factory... (that is mostly just than a context manager that makes sure the viewer is closed at the end of the test).
My main questions would be:
- is this on CI or on your local computer?  Issues are GL contexts and display buffers are the first thing I think about here.
- if local, what version of pillow are you using?  There were some recent issues there with 7.1.0 (and could conceivably be in 7.1.1)

**Comment by GenevieveBuckley** [comment]
I ran pytest on my local computer. I haven't tried running it on a CI service, but I could try it if you think that will help gather information?

**Comment by GenevieveBuckley** [comment]
My version of pillow is 7.0.0

**Comment by tlambert03** [comment]
Ok, I’ll try to take a look later today.  No need to try on CI yet.

**Comment by tlambert03** [comment]
Oh! What happens if you do Viewer(show=False) in python?  Alternatively you can pass show=True to the viewer factory in pytest (where the default is False)

**Comment by tlambert03** [comment]
yep, that's it...  this should work for you in pytest:
```python
def test_screenshot_introspection(viewer_factory):
    view, viewer = viewer_factory(show=True)

    _ = viewer.add_image(camera())
    screenshot = viewer.screenshot()
    # the screenshot should NOT be completely black
    assert not (screenshot == np.array([0, 0, 0, 255])).all()
```
sorry... I guess that _was_ an issue with `viewer_factory`! 😅 it defaults to `show=False` unlike the main `napari.Viewer()`

it might be interesting to look into an [offscreen buffer](https://github.com/vispy/vispy/blob/490cf300581b8112861be418ba8ead8785fef730/examples/demo/gloo/offscreen.py) for our tests...  We might want to emulate what vispy does with their [TestingCanvas](https://github.com/vispy/vispy/blob/8387ea1aac961224488657ff57d1794f4e68ab32/vispy/testing/_testing.py#L355).  Here is an [example test](https://github.com/vispy/vispy/blob/8387ea1aac961224488657ff57d1794f4e68ab32/vispy/visuals/tests/test_image.py#L29-L36) where vispy uses TestingCanvas.render() to look at an image buffer without showing it.

**Comment by GenevieveBuckley** [comment]
I'm not sure if that counts as an issue with `viewer_factory`, more just an issue with my understanding of it 😄

**Comment by tlambert03** [comment]
if it's helpful to see the code, here's what it does:
https://github.com/napari/napari/blob/dbf88f269414bdc969cdd872ebc273807f3263fd/napari/conftest.py#L43-L59

**Comment by GenevieveBuckley** [comment]
I looked at the `viewer_factory` code, thought "yeah that seems right, but maybe Talley will know how to steer me in the right direction". I did not dig into what the `model_kwargs` could be, so I didn't think to try `show=True`. So thank you! 

I'm very happy to have learned this today 😄

**Comment by sofroniewn** [comment]
Maybe we could add a comment to our [writing tests guide](https://github.com/napari/napari/blob/master/docs/developers/CONTRIBUTING.md#writing-tests) on how to write a test with a screenshot?

**Comment by tlambert03** [comment]
hmmm ... perhaps, though I'd really rather not "codify" the workaround of showing the viewer, until we give up on the better `canvas.render()` approach.  (alternatively, we could skip screenshot tests on everything but mac CI, where they seem to work).

**Comment by sofroniewn** [comment]
That's fine

**Comment by sofroniewn** [comment]
We now use screenshots in a number of our tests with the `show=True` setting. Given this is working I'm going to close now, but anyone should feel free to reopen if further discussion is warranted. Thanks!!
