### ISSUE TITLE
Feature request: add_path() should accept kwargs like 'name', 'metadata', etc.

### ISSUE THREAD

**Issue by GenevieveBuckley** [napari/napari#1107]
## 🚀 Feature

I would like the `add_path()` function to accept keyword arguments like `name`, `metadata`, etc.

## Motivation

I think the behaviour of `add_path()` should be as similar as possible to the other `add_` methods (`add_image()`, `add_points()`, `add_labels()`, etc.)

What do you think @tlambert03?

**Comment by tlambert03** [comment]
Yeah that sounds good.  Since those are passed to plugins though, we’ll have to deal with conflicts between what the user entered and the second item in the tuple returned by the plugin... and also the fact that it can be any type of layer.
