### ISSUE TITLE
Folder structure refactoring

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#111]
## ❓ Questions and Help

@kne42 and I have been looking into moving forward with our refactoring - and one issue that is coming up is around separating out the "model", "view", and "controller" parts of our components. Right now we have a loose separation of "model" and "view" with our non-UI and UI peer classes, see discussion in #92 for some more info. The "view" parts live inside a folder called `qt` and the "model" parts live in the main folder. This is nice because it keeps all the qt stuff in one place, but it is less desirable as it splits up parts of the same component into different places, makes it harder to have component specific auxiliary files (where should they live?) and may make it more confusing to add new components (as files have to get added in multiple places). These comments apply to both our layer components (`image` / `markers` / `shapes`) and our main components (`viewer`, `dimensions`, `control_bars`).

Instead here is a proposal to reorganize our files by component instead. The folder structure would now look like the following
`elements/viewer/viewer.py`
`elements/viewer/viewer_qt.py`
`elements/dimensions/dimensions.py`
`elements/dimensions/dimensions_qt.py`
etc.
and 
`layers/base_layer/base_layer.py`
`layers/base_layer/base_layer_qt.py`
`layers/image_layer/image_layer.py`
`layers/image_layer/image_layer_qt.py`
etc.

OR
another way to do it would be 
`elements/viewer/model.py`
`elements/viewer/view.py`
`elements/dimensions/model.py`
`elements/dimensions/view.py`
etc.
and 
`layers/base_layer/model.py`
`layers/base_layer/view.py`
`layers/image_layer/model.py`
`layers/image_layer/view.py`
etc.
(or some other similarly generic words - I can see pros/cons to either or those two approaches, but lean towards the later)

We would then use `__init__.py` to make all the importing nice and work as before.
What I like about this approach is that say for the shapes layer I have some crazy triangle calculating function that can live inside the shapes_layer folder but in a different file from all the model code (i.e. `utils`). If we want to add a separate `controller.py` class to use a real MVC like approach we can now do this too. It makes it particularly clear what to do to add new layer types - add a new folder that has all the necessary stuff in it. Also it seems like we might be moving towards allowing a layer to define multiple views - one for the layer properties boxes on the right, and one for the control_bars space on the left (see #107 for discussion). This would allow both those files to live in the same folder `properties_view` and `controls_view` for example. Whereas now they'd all live jumbled up in the "qt" folder.

This is a pretty major refactor so want to get some input before going ahead!

**Comment by jni** [comment]
I don't have the time to think about this in depth at the moment but I think we really need to clarify the space that we want the model to live in. For example, the dimensions sliders depend on the image layers that are present, so should they be independent "models" and "views" in a different part of the layout?

I think this is somewhat related to our ability to display objects of different dimensionality in the same space, which I still find weird but @royerloic assures me makes sense. =P And no, I get it, you can have markers in some global, time-static space and have some time-varying thing happening relative to those. But I still think we need to come up with some global "model" concept that might help sort out the right hierarchy for our modules.

**Comment by sofroniewn** [comment]
yeah, i think it's still a little unclear to me if we are making the right choice separating out the dimensions, and whether control bars will really be significant enough to be it's own thing if layers are defining what they want displayed there. I think though that the reorganization will help make things more clear - but would love for @AhmetCanSolak and @royerloic to weigh in too.

**Comment by sofroniewn** [comment]
We have moved in this direction with PR #113 though as discussed in the PR the refactoring is still not complete
