### ISSUE TITLE
Should escape key on shapes draw one more vertex?

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#1116]
## 🐛 Bug
behaviorally, i find it a little strange that, when drawing shapes, the escape key actually draws an additional vertex at the current position before finishing.  I expect escape to "get me out of here", not "do one more thing then get me out of here"...

**Comment by sofroniewn** [comment]
Agreed @tlambert03 - I may have changed this in #1051 (which still needs to be reviewed by @jni). If not I can certainly change it there, or in it's own PR

**Comment by sofroniewn** [comment]
Yes @tlambert03 this is changed in #1051, confirmed

**Comment by sofroniewn** [comment]
We should try and get that in for 0.3.0 too

**Comment by tlambert03** [comment]
awesome!

**Comment by sofroniewn** [comment]
Fine to leave open till #1051 merges, hopefully soon :-)

**Comment by sofroniewn** [comment]
Closed by #1051
