### ISSUE TITLE
Implicit pyramids will cause AttributeError in add_image(channel_axis=...)

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#1117]
## 🐛 Bug
as @jni pointed out here https://github.com/napari/napari/pull/1092#discussion_r404757426, we have a bug in `Viewer.add_image()`:  If the user passes an implicit pyramid (a `list` of arrays _withouth_ explicitly using `is_pyramid=True`) and tries to use `channel_axis != None`, then there will be an `AttributeError` here, since a `list` does not have `.shape`:
https://github.com/napari/napari/blob/871825e9ca9f570575e0681132d638e03cb39708/napari/components/add_layers_mixin.py#L227

(note, the syntax of of that line changed in #1092, but the potential error was always there).

**Comment by sofroniewn** [comment]
😞 any ideas on how we should fix this? this part of the api has always been prone to a little confusion. there was a time where we had a separate `add_pyramid` method but so much code was duplicated and it was unclear how to achieve parity with the labels layer. `add_pyramid_labels` felt like a bit much
