### ISSUE TITLE
Minor improvement to the image layer icon

### ISSUE THREAD

**Issue by justinelarsen** [napari/napari#1123]
## 🚀 Feature
The image icon in the layer menu is confusing. It looks like a checkbox and users may try to check/uncheck it, but nothing happens.

![image_layer_icon](https://user-images.githubusercontent.com/57509887/78950481-bb4e5980-7a83-11ea-8070-7e03b19d5cb8.png)

## Pitch

I recommend using a different icon that represents an image

**Comment by jni** [comment]
Yeah I was looking at that during the meeting and twitching internally. =P We could use something like the WhatsApp iOS "picture" icon?

![IMG_4138](https://user-images.githubusercontent.com/492549/78952135-e1253e00-7b17-11ea-812e-965531dbd1f3.jpeg)

**Comment by sofroniewn** [comment]
@tlambert03 also suggested we look at [octicons](https://octicons.github.com) from github - this one could be good https://octicons.github.com/icon/file-media/

![image](https://user-images.githubusercontent.com/6531703/78956638-bdbaae80-7a97-11ea-9b34-0a83737421c8.png)

but maybe it looks too much like a file

**Comment by tlambert03** [comment]
i have a slight preference for the aspect ratio of the ios version, and the circular "sun".  It would be easy enough to make our own SVG for this

**Comment by jni** [comment]
Yeah, even though I generally like octicons, I find this particular one deeeeeesgusting! 😂 Google yields lots of alternatives too, e.g. https://www.flaticon.com/free-icon/insert-picture-icon_16410

**Comment by tlambert03** [comment]
here, just made one:
https://www.dropbox.com/s/c1l3qax7yr58fng/image.svg?dl=1

**Comment by jni** [comment]
It's super cute!

**Comment by sofroniewn** [comment]
love it! want to quickly make a PR @tlambert03 wouldn't hurt to get it in for 0.3.0

[edit] *make a quick :-)

**Comment by tlambert03** [comment]
sure.  tomorrow ok?
