### ISSUE TITLE
Different interpolation methods for 3D viewer

### ISSUE THREAD

**Issue by david-hoffman** [napari/napari#1125]
## 🚀 Feature
Just like for the 2d viewer it'd be nice to be able to choose interpolation methods for the 3d version

**Comment by tlambert03** [comment]
Hi @david-hoffman!
funny, @sofroniewn made this possible back in #841, and it is the default mode for "labels" layers, but it looks like it didn't get exposed as an option for images.  You _can_ actually set image volumes to nearest neighbor interpolation, but it looks like we need to expose that option in the gui.  it's a bit circuitous, but here's a short-term workaround:
```python
import napari
import numpy as np
viewer = napari.Viewer(ndisplay=3)
layer = viewer.add_image(np.random.rand(20,20,20))
# grab the vispy visual for the layer
visual = viewer.window.qt_viewer.layer_to_visual[layer]
# change the interpolation on the visual (only nearest & linear are valid)
visual.node.interpolation = 'nearest' 
```
unfortunately, that changes back everytime you switch between 2D/3D, but we should be able add this relatively easily.
