### ISSUE TITLE
Cannot open .tif files after #1061

### ISSUE THREAD

**Issue by hectormz** [napari/napari#1129]
## 🐛 Bug

I believe after delaying the loading of image reading library(ies) in #1061, you can no longer drag and drop .tifs into `napari`, when launching the GUI from the command line. It also doesn't seem to work loading the image from "Open image(s):" and get error:

```
No plugin found capable of reading XXX.tif.
```

## To Reproduce

1. Drag `.tif` into `Napari`
1. Open `.tif` in File menu

## Expected behavior

Switching back to commit `434d54e` fixes the problem

@jni @sofroniewn @Czaki

**Comment by tlambert03** [comment]
hmmm, I can't reproduce this.  Can you maybe provide the tiff you're using and the exact git hash you're on?

**Comment by sofroniewn** [comment]
This likely relates to https://github.com/napari/napari/pull/1061#issuecomment-612061394

**Comment by tlambert03** [comment]
you might also be able to go into `Plugins > Plugin Errors...`, select "builtins" from the dropdown, hit the button at the top right corner to copy the traceback and paste it here

**Comment by hectormz** [comment]
Ah, sorry everyone.  I'm on `391cfd572`, but the issue is that I did not update the dependencies after updating to the latest commit, namely `tifffile` wasn't actually installed. All good now! I hate when that happens when installed in developer mode.

**Comment by hungyiwu** [comment]
Hi, I'm getting this same issue while using the freshly installed napari just now. I installed napari using conda and noticed that `tifffile` wasn't installed along with it. Is this a normal behavior and I have to install `tifffile` manually?

**Comment by sofroniewn** [comment]
This should not have happened, you should have gotten tifffile too. Can you give some more detail on your system, i.e. by typing `napari --info` on the CLI

Mine looks like
```
napari --info
napari: 0.3.1+15.g665d2034
Platform: Darwin-19.4.0-x86_64-i386-64bit
Python: 3.7.4 (default, Aug 13 2019, 15:17:50)  [Clang 4.0.1 (tags/RELEASE_401/final)]
Qt: 5.14.1
PySide2: 5.14.1
NumPy: 1.18.1
SciPy: 1.4.1
Dask: 2.15.0
VisPy: 0.6.5.dev2+g9e0822db

GL version:  2.1 INTEL-14.5.22
MAX_TEXTURE_SIZE: 16384

Plugins:
  - dv_reader: 0.2.2
  - io-test: 0.0.1
  - napari-classification: 0.0.0
  - napari-denoising: 0.0.0
  - napari-detection: 0.0.0
  - napari-io: 0.0.0
  - napari-plugin-engine: 0.1.5
  - napari-plugins: 0.1.0
  - napari-registration: 0.0.0
  - napari-segmentation: 0.0.1
  - napari-tracking: 0.0.0
  - svg: 0.1.2
```

Maybe then @tlambert03 or @jni might have some ideas on how to help

**Comment by tlambert03** [comment]
if you have a development environment that you've been using for a while, you might just need to run `pip install -r requirements.txt -U` again?

**Comment by tlambert03** [comment]
oh... very sorry, just reread your comment!  ... need to take another look at the conda recipe

**Comment by tlambert03** [comment]
yeah, might we need to add tifffile to the conda recipe?
https://github.com/conda-forge/napari-feedstock/blob/master/recipe/meta.yaml

@jni?  @kne42?

**Comment by hungyiwu** [comment]
@sofroniewn Here's what I got when running `napari --info`:

```
napari: 0.3.1
Platform: Linux-5.4.0-7629-generic-x86_64-with-debian-bullseye-sid
Python: 3.7.7 (default, Mar 26 2020, 15:48:22)  [GCC 7.3.0]
Qt: 5.12.5
PyQt5: 5.12.3
NumPy: 1.18.1
SciPy: 1.4.1
Dask: 2.16.0
VisPy: 0.6.4

GL version:  4.6 (Compatibility Profile) Mesa 20.0.4
MAX_TEXTURE_SIZE: 16384

Plugins:
  - napari-plugin-engine: 0.1.5
  - svg: 0.1.2
```

**Comment by sofroniewn** [comment]
Thanks @hywu0110 - looks like @tlambert03 might have identified the issue here https://github.com/napari/napari/issues/1129#issuecomment-633772534 which we can work to fix

**Comment by jni** [comment]
> yeah, might we need to add tifffile to the conda recipe?

I'll update it now, but there is an issue: there's no imagecodecs in conda-forge yet. It looks pretty thorny:

https://github.com/conda-forge/staged-recipes/pull/10331

So, this means that on conda-forge we can read tiff with zlib and one more compression scheme (I forget which), but not any of the fancier compression schemes found in the wild. I honestly have little idea how much of a problem this is! 🤞 

However we'll still be able to direct users to pip install imagecodecs.

**Comment by jni** [comment]
The latest napari build on conda-forge depends on tifffile. Hopefully that is enough to fix your problem @hywu0110! btw, if your tiffs aren't supported by that version, you can either:

- `pip install imagecodecs`, or
- `conda install -c conda-forge tiffffile=2019.7.26.2`, ie get an earlier version of tifffile, see https://github.com/conda-forge/tifffile-feedstock/issues/39. The earlier version should still have built-in support for most common codecs.

**Comment by jni** [comment]
(And thanks @tlambert03 for spotting that!)

**Comment by hungyiwu** [comment]
It worked like a charm! Thank you all for the fast fix! 

Just to leave a note for people like me: `conda update --all` doesn't seem to bring the latest build, do `conda remove napari && conda install -y -c conda-forge napari` instead.

**Comment by YounessAzimzade** [comment]
Hi,

I am trying to visualize a few markers on IMC data using Napari. I have fullstack.tiff but when i import them, they look really black. I can make it better but not that much. 
 



![UntitledNap](https://github.com/napari/napari/assets/92576728/1bd18c9e-75f2-497d-b8e1-5db36c87833f)



More importantly, the IMC plugin doesn't detect any channel which i want to visualize.

**Comment by psobolewskiPhD** [comment]
@YounessAzimzade 
Sorry missed your comment here. Can you clarify which plugin you are using?
can you post the output of `napari --info`?
It's hard to say if this is a napari problem or something related to the plugin.
Can you share the file you are using?
You may consider making a thread on image.sc or perhaps an issue on the plugin GitHub as well.

**Comment by Czaki** [comment]
Could you provide the size of image? Does right click on contrast limits and click reset range helps?
