### ISSUE TITLE
Inconsistent behavior when image has a dimension of size of 1.

### ISSUE THREAD

**Issue by li-li-github** [napari/napari#1131]
## To Reproduce
Create a tif file

1. Create a tif image that has a dimension with size of 1.
e.g. `tifffile.imsave('test.tif', numpy.zeros((1, 100, 100))`
2. Open napari and drag & drop `test.tif` into napari.
3. Click the 2nd icon from left bottom that has a label of "Toggle of number of displayed dimensions" twice.
4. A slider now appears. 

## Expected behavior
It is not really a bug but maybe napari can ignore the dimension of size 1 because it doesn't seem to make much sense to display a slider for this dimension. This could be annoying when the image data somehow has many dimensions of size of 1.

## Environment
napari: 0.2.12
Platform: Darwin-18.7.0-x86_64-i386-64bit
Python: 3.7.6 | packaged by conda-forge | (default, Mar 23 2020, 22:45:16) [Clang 9.0.1 ]
Qt: 5.14.2
PySide2: 5.14.2
VisPy: 0.6.4
NumPy: 1.18.2
SciPy: 1.4.1
scikit-image: 0.16.2
Dask: 2.13.0

GL version: 2.1 ATI-2.11.21
MAX_TEXTURE_SIZE: 16384
 - Please copy and paste the information at napari info option in help menubar here:

 - Any other relevant information:

**Comment by jni** [comment]
@li-li-github thank you for the report! I agree that this is inconsistent and undesired behaviour. Hopefully this shouldn't be too hard to track down!

**Comment by sofroniewn** [comment]
Closed by #1196
