### ISSUE TITLE
Minor improvement: Guide the user on how to open images

### ISSUE THREAD

**Issue by justinelarsen** [napari/napari#1132]
## 🚀 Feature
Improve the user experience for new users when there's an empty canvas. Provide instructions on how to open images or even a quick message for how to get started.

## Motivation

It's not totally clear that I can drag images to the canvas to open them. A clear message would help the user to get started quicker.

## Pitch

I recommend having a message on the canvas when I first open napari with an empty canvas that says something like “Drag image(s) here to open or use the menu: File > Open image(s)”
![empty_canvas_message](https://user-images.githubusercontent.com/57509887/79029991-c4a2f900-7b4b-11ea-94bd-e74341754996.png)

**Comment by sofroniewn** [comment]
Yes this would be really nice, probably best to just create a special http://vispy.org/visuals.html#vispy.visuals.TextVisual with that message and then we detect that no layers are present in the layers list show it and then hide it otherwise. This could be triggered from our model file here https://github.com/napari/napari/blob/ff22470b8ecb6c54a25925b126be21467157de20/napari/components/viewer_model.py#L454
The text visual would get added here https://github.com/napari/napari/blob/ff22470b8ecb6c54a25925b126be21467157de20/napari/_qt/qt_viewer.py#L142 probably after being created as inside it's own dedicated `_vispy/vispy_canvas_text.py` file

[EDIT] See discussion below that there is no need to use a vispy text visual in the canvas here, instead we can just use a Qt widget. Though the point at which that display gets triggered from the model file remains the same.

**Comment by tlambert03** [comment]
that would certainly work, but it's not immediately obvious to me that we want to do this with GL, or that it actually needs to be a vispy visual that gets added to the scene canvas (even though it would be shown in the same general area).  I'm not sure whether GL will render text (with all the anti-aliasing considerations that platforms handle) as "naturally" as a Qt widget?

**Comment by tlambert03** [comment]
I'll also just put a screenshot here of the vscode info placeholder, which I've always liked:

<img width="607" alt="Screen Shot 2020-04-12 at 12 23 07 PM" src="https://user-images.githubusercontent.com/1609449/79074095-6fd0c100-7cb8-11ea-9c33-34f90d9ea110.png">

**Comment by sofroniewn** [comment]
> but it's not immediately obvious to me that we want to do this with GL, or that it actually needs to be a vispy visual that gets added to the scene canvas (even though it would be shown in the same general area).

Oh right - we could just "do this with Qt" instead by showing a different widget instead of the canvas right and not using vispy? That would be much much simpler - I like what you're showing there from vscode!!

**Comment by tlambert03** [comment]
yeah, that's what I was thinking.  it could even be a transparent widget that sits on top of the canvas area that disappears when `len(layers) > 0`... so we wouldn't need to change anything about the canvas.

**Comment by justinelarsen** [comment]
What do you think about something like this?
![napari_blank_canvas_mockup](https://user-images.githubusercontent.com/57509887/79295889-bd068b80-7e8e-11ea-9399-0108537627c5.png)

**Comment by sofroniewn** [comment]
Beautiful @justinelarsen - looks like time for your first napari PR :-)

**Comment by justinelarsen** [comment]
I started working on this but hit a snag. 

I created a new QtCanvas class which is instantiated within the QtViewer to contain both the existing VisPy canvas and a new widget for an empty canvas. The idea is to show only one at a time based on if there are layers or not. I created a diagram that I thought would help to explain. 

As I started implementing though, I realized that there are a lot of methods within QtViewer that use/set canvas properties or call on canvas methods. Also, there are a lot of mouse event methods in QtViewer that would need to be moved with the SceneCanvas as those methods get connected to the canvas.

This seems like a lot of work and potential to create bugs for something that I feel shouldn't be so complicated so I wanted to stop and get others' opinions. I could just leave everything in QtViewer and not create a new class for QtCanvas and then just add the new widgets to QtViewer. I'm not sure if this is bulking the QtViewer class too much though. Thoughts?

![napari emptyCanvas Implementation](https://user-images.githubusercontent.com/57509887/80761862-3984a580-8af0-11ea-9115-ea6e79c0589d.jpg)

**Comment by sofroniewn** [comment]
Hmm, I would try making QtCanvas not a QStackWidget, but just a QWidget (potentially subclassing, or at least containing) the SceneCanvas. This will then make the swapping out much easier. As you said many of the mouse events/ methods would have to move, but it could actually consolidate a lot of our vispy code - see this proposal from a while back https://github.com/napari/napari/issues/855

QtViewer would still need QStackWidget, but this could maybe just be created directly there and there would just be minimal logic inside the QtViewer to decide which widget is being shown. If it becomes too much, you could also add another new class that subclassed the QStackWidget and was very light weight and add that to QtViewer.
