### ISSUE TITLE
developer resources have disappeared from website

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#1134]
## 🐛 Bug

Developer resources have disappeared from website

![image](https://user-images.githubusercontent.com/6531703/79048229-784dcc80-7bd0-11ea-9eaa-0bfbd16cc329.png)

**Comment by tlambert03** [comment]
it seems to be due to the recent sphinx update.  sphinx 2.4.4 works, sphinx 3.0.0 throws _tons_ of errors (regardless of #1113)

**Comment by tlambert03** [comment]
relatedly... while it makes sense to be permissive about our requirements for napari proper (using `>=` whenever possible).  For websites with dependencies it's common practice to pin dependencies to exact versions... so I think we should do that here as well (since we're the only ones "consuming" our docs-building source code).

**Comment by sofroniewn** [comment]
> For websites with dependencies it's common practice to pin dependencies to exact versions... so I think we should do that here as well (since we're the only ones "consuming" our docs-building source code).

That is fine with me, I see these as quite different use cases

**Comment by jni** [comment]
I'm ok with it. Ideally we would keep up with sphinx development, but we are already have too much on our plates, so let's pick our battles. =)

**Comment by tlambert03** [comment]
I don't see it as incompatible with keeping up with sphinx... more like not being surprised by an update that leaves your public facing docs broken.  at FPbase, I have a couple dozen dependencies that are all pinned, and i go through every month or two, update them all, see if anything is broken, then release.  (That was only after having lots of breakages).  I do think we should keep up to date as well.
