### ISSUE TITLE
Uncovered lines in points properties code

### ISSUE THREAD

**Issue by jni** [napari/napari#1136]
In this code report:

https://codecov.io/gh/napari/napari/pull/1069/diff

these lines are not covered:

https://github.com/napari/napari/blob/6ea95a9fa2f9150a4dbb5ec1286b8ff2020c3957/napari/layers/points/points.py#L565-L575

and

https://github.com/napari/napari/blob/6ea95a9fa2f9150a4dbb5ec1286b8ff2020c3957/napari/layers/points/points.py#L606-L608

(The "ifs" are executed but never evaluate to True in tests.) It's possible that the second one in particular will *never* be hit, since we automatically convert input to arrays. So the code could possibly be removed.

**Comment by kevinyamauchi** [comment]
Thanks for making the issue @jni! I will add these soon.
