### ISSUE TITLE
some plugin usability points

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#1137]
## 🐛 Bug

i have a couple feedback points on the plugins that i've noted from my work on #1104 but are more general that plugin writers.

- [ ] I love the plugin errors dialog, but it would also be nice to see errors directly in the console when calling code in the console. We can wait till #1090 for that, but wanted to note it here too. There were a few times when I'd run the `save_layers`, and things would fail, but i wouldn't realize until going to the error dialog.

- [ ] I have a hard time reading the `blue` text in the error messages in the plugin dialog.

- [ ] The plugin sorter should be a singleton - right now I can add multiple copies of it 
![image](https://user-images.githubusercontent.com/6531703/79143373-f85f6800-7d71-11ea-9f15-3deb9792eccd.png)

**Comment by psobolewskiPhD** [comment]
There is no Plugin Sorter any more and error message formatting is much improved by https://github.com/napari/napari/pull/4414
I'm going to close this as out-dated.
