### ISSUE TITLE
Increment dimensions slider with ctrl + mouse scroll

### ISSUE THREAD

**Issue by hectormz** [napari/napari#1141]
## 🚀 Feature

I'd like to enable scrolling through an image stack using `ctrl + scroll`

## Motivation

My standard image is usually a stack of several thousand slices that I want to look through quickly. To navigate through the stack, I either manipulate the scroller on the bottom, or use the left/right arrow keys. Using the scroll would be more convenient for me.

## Pitch

In `napari` the mouse scroll is used for zoom, but `ctrl + scroll` could be used to scroll the image dimensions in addition to the arrow keys.

As an aside (or future issue if it doesn't exist), sometimes I scroll through stacks way more often than zooming into an image, and it would be great to rearrange or change key bindings (like in `Image J`) so I could choose to make mouse scrolling for dimension scrolling instead of zooming. These settings could be saved in `~/.naparirc` or similar.

**Comment by sofroniewn** [comment]
Yes, that makes a lot of sense - this functionality would be enabled by the proposed changes in #1048 (cc @kne42). Thanks for the feature request!!

**Comment by hectormz** [comment]
@sofroniewn awesome, I'll loop back to this after #1048 then

**Comment by jni** [comment]
As I was reading through the issues, it occurred to me that horizontal scrolling does nothing right now and could also be used to move through a stack. Horizontal scrolling is very easy and natural on Mac trackpads.

**Comment by hectormz** [comment]
Is horizontal scrolling on Mac trackpad simply swiping fingers horizontally? Is that achieved on a Mac with a  mouse by scrolling and holding a key?

**Comment by jni** [comment]
This was closed by #1434! 🎉

**Comment by hectormz** [comment]
Woohoo! Thanks @DragaDoncila !!
