### ISSUE TITLE
Suppress vispy warning

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#116]
## 🚀 Feature
Right now on launch I always recieve the following vispy warning:
```python
/Users/nicholassofroniew/anaconda3/lib/python3.6/site-packages/vispy/visuals/isocurve.py:22: UserWarning: VisPy is not yet compatible with matplotlib 2.2+
  warnings.warn("VisPy is not yet compatible with matplotlib 2.2+")
```

As napari is not using the vispy isocurve functionality can we suppress this warning.

## Motivation

I feel like the warning can be off-putting and confusing to new users, giving the impression something might not work well when in fact everything will be fine.

**Comment by jni** [comment]
👍 for suppressing the warning, but 💯 for bumping the vispy minimum requirement or helping vispy push out a new release: it appears that they [have already removed it](https://github.com/vispy/vispy/blob/8c36fb7ffd7641ba0972808888911d71e48e8fe5/vispy/visuals/isocurve.py) (see the code and the commit message).

**Comment by jni** [comment]
... Bahahaha and I just saw that they also added mpl colormap support recently! 🤦‍♂️ 

https://github.com/vispy/vispy/pull/1489

We really should interact more with that community!

**Comment by sofroniewn** [comment]
@jni interacting more with the vispy community sounds good - maybe you want to reach out if you know any of the current maintainers? If you end up having a phone call I'm happy to join. I"m not sure about their release schedule, but it looks like it has been a while since their last one. Maybe @kne42 knows as she has interacted more with them.

**Comment by sofroniewn** [comment]
PR has been merged, we will also coordinate reaching out to the vispy team to learn more about their release schedule
