### ISSUE TITLE
Consistent behavior when deleting points with hotkeys

### ISSUE THREAD

**Issue by justinelarsen** [napari/napari#1161]
## 🚀 Feature
When adding points, it would be nice to be able to use the 'delete' key to delete points. 

Behavior should be consistent. Current behavior when on a points layer:
- Selecting a point and using the delete(mac) or backspace(windows), deletes the selected point.
- If a point is selected and I click the 'Delete selected points' button (x), the selected point is deleted.

However, if I am in the adding points mode and I use the delete/backspace key, nothing happens even though the last created point is selected.

## Pitch

The last created point should be deleted after pressing the delete/backspace key.

**Comment by kevinyamauchi** [comment]
I think this is a good call, @justinelarsen . Do we want this in 0.3.0? It's a real quick one. I _think_ we just need to add `Mode.ADD` to line 65 below.

https://github.com/napari/napari/blob/cfd4eaf85114690161c197e920bb1574157e5671/napari/layers/points/_points_key_bindings.py#L62-L66

**Comment by jni** [comment]
@kevinyamauchi i don’t think it’s urgent but if it’s a simple fix it would be great to get this in!
