### ISSUE TITLE
Better autogenerated docs

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#1166]
## 📚 Documentation

we currently use `sphinx-apidoc` to autogenerate docs, but it leaves a little to be desired in the way of organization... but it also doesn't provide a ton of options (beyond templates) to configure it.  This issue is just to remind us to look into autogenerating our own API docs to look just as we want them.

**Comment by neuromusic** [comment]
closing this b/c it looks like we are now using `autosummary`, which fixes many of the issues with `apidoc`
