### ISSUE TITLE
layer_to_visual prevent custom Layer subclasses

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#1176]
### :bug: Bug
Was just playing around with making some layer subclasses with some method overrides as an example for someone, and found that it was _very_ difficult to add a subclassed `Layer` to the viewer with our `layer_to_visual` pattern.

when you try `viewer.add_layer(MyLayerSubclass(data))` ... it will throw a `KeyError` in both the `_vispy`  `visual = layer_to_visual[type(layer)](layer)` function (same with `_qt` `layer_to_controls`), because those dicts only know about our builtin layer types.

Just wanted to mention that somewhere so it's on the radar.

**Comment by jni** [comment]
I definitely think that's a bug, and we do want to allow custom layers. Thanks for flagging!

**Comment by sofroniewn** [comment]
Agreed - getting rid of the `layer_to_visual` approach would be good

**Comment by sofroniewn** [comment]
This was closed by #1528
