### ISSUE TITLE
Broken links in the governance section of main README

### ISSUE THREAD

**Issue by pwinston** [napari/napari#1190]
## 📚 Documentation

In the governance section of the main README the links to @napari/steering-council and @napari/core-devs are 404.

The links are:
https://github.com/orgs/napari/teams/steering-council
https://github.com/orgs/napari/teams/core-devs

**Comment by sofroniewn** [comment]
Thanks for flagging @pwinston! @GenevieveBuckley had actually caught this back in #816, but we never got around to fixing it!! We should do so promptly though. Those links unfortunately only work if you are in the napari GitHub organization, so either we could drop them entirely or just point to a dedicated page.

I lean towards a dedicated page which would be its own md file in the repo and could include a little more about each of the core-devs if they wanted. Maybe `about-us.md`? Could be part of the website improvements too under `developer-resources` @kne42.

Thoughts @jni?

**Comment by jni** [comment]
Yeah I think that would be nice. The nice thing about the github links is that they are up to date. But anyway I think having a separate page is a good idea.
