### ISSUE TITLE
Dask cache tuning

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#1205]
## 🐛 Tune dask cache

Chatting with @jni about the dask cache... we need to do a few things to tune performance:

- **think more about what the default size should be.**  If the cache is large, but still not as large as the dataset, then looping a dataset with the play button will just continuously swap the cache, and potentially cause more overhead than if it was off altogether
- **don't resize after created**: If a user creates a Layer with a dask array, the cache is created... if they then resize with `resize_dask_cache(100)`, it works, but if they create a new `Layer`, I think the cache will go back to the default size.  which it should not
- **possibly modify scoring algorithm**: [cachey](https://github.com/dask/cachey) lets you modify the scoring algorithm for cache eviction.  by default, it's `score += compute_time / num_bytes * (1 + eps) ** tick_time`.

**Comment by jni** [comment]
I just want to add that (1) is definitely a problem I'm encountering now. A small or disabled cache makes play much much smoother than the default 1/2RAM cache, for a 15GB dataset (200 x 75MB timepoints).

**Comment by tlambert03** [comment]
and just to be explicit (in case someone stumbles on to this), if you'd like to disable the cache, for now, you need to do it _after_ you add a layer with a dask array, and probably each time:

```python
import napari
from napari.utils import resize_dask_cache

napari.view_image(big_dask_array)
resize_dask_cache(0)
```

**Comment by sofroniewn** [comment]
As noted in #1206 by @tlambert03 

> Let's maybe leave #1205 open for input on tuning the default cache size (which this PR does not change)

**Comment by tlambert03** [comment]
let's maybe close it now :joy:
