### ISSUE TITLE
Creating wheel breaks #1059

### ISSUE THREAD

**Issue by Czaki** [napari/napari#1212]
## 🐛 Bug

Creating and upload wheel to pypi.org breaks options to ommit install PySide2 if PyQt5 is installed introduced in #1059

## To Reproduce

1. `pip install PyQt5´
2. ´pip install napari´
3. PySide2 visible in ´pip freeze´ output

## Expected behavior

No PySide2 instalation

## Additional context

 

During instalation of package distributted as wheel there is no ´setup.py´ execution. 

Please remove wheel file (*.whl) from pypi.org

**Comment by jni** [comment]
Oops! I wondered why that wasn't working for me! Thanks for the report @Czaki. I've removed the wheel. I'll leave this open because we need to update our GitHub actions, but 0.3.0 should work now.
