### ISSUE TITLE
Add properties attribute to Labels layers

### ISSUE THREAD

**Issue by DragaDoncila** [napari/napari#1214]
## 🚀 Feature
As is the case with Points layers, it would be nice to have the option to add properties to Labels e.g. the class the label belongs to.

## Motivation

When viewing labels layers it's common for each label to have a classification and it would be great to see this information when hovering over a pixel without referring to an external source. You could also display associated information such as the confidence of the classifier for that point. This would make the editing labels process even smoother.

**Comment by kevinyamauchi** [comment]
Thank you for the feature request, @DragaDoncila ! I have a clarifying question to make sure I understand your proposal. For the `Labels` layer properties, do you want to be able to assign properties to each pixel in the label image or each class of pixel?

**Comment by jni** [comment]
each class. The use case is a satellite image that is segmented into integer classes, where each class is something like "forest", "agricultural", "water", "urban", etc. But it's hard to figure out with labels right now.

**Comment by kevinyamauchi** [comment]
Got it, thanks! That makes sense to me!

**Comment by sofroniewn** [comment]
@constantinpape just want to flag this issue for you too - I imagine this is something you might want to use? In which case I can also bump it up the priority list for next week. Let us know if there is anything additional you'd like from this feature too

**Comment by constantinpape** [comment]
Thanks for bringing this to my attention @sofroniewn. I think this is in general very useful, but I don't need it for the annotation tool right now.
The class label is now associated with a property of the points layer and this works for me.

**Comment by sofroniewn** [comment]
Ok good to know not an immediate need @constantinpape, but I do think that how we consider this functionality might relate to how we think about implementing https://github.com/napari/napari/issues/716#issuecomment-633288362 in the long run, so I want to have some discussion about this now, curious what @jni and @kevinyamauchi will make of this.

In general I'd love our approach to properties here to be as close to our approach to properties in the points layer as possible, but there might be some key differences.

I see the big split in approach here as if we want to use lists which implicitly share the same index as our labels. This would be nice as we could reuse things from the points layer, and synchronization with the points layer would be very natural if we have a correspondence between them (say centroids in points, one per labels in labels).

One problem though is that for people who use labels "sparsely" this could lead to some very long lists. Right now someone could use labels 1-10 for one thing and 100-110 for another, and if we used lists we'd have to somewhat awkwardly think about what to do for labels 11-99. The alternative would be some for of dictionary mapping when the keys of the dictionary correspond to indices of labels.

Very open to ideas here

**Comment by jni** [comment]
@sofroniewn I think it's critical that we are able to support arbitrary label numbers, so the bare list approach won't work. dict of labels -> properties is "row oriented" and won't rhyme at all with the points properties. A middle ground is columns (like in points) *and* a dictionary index mapping labels to rows. That should work although we are getting dangerously close to reimplementing pandas from scratch. =P

**Comment by sofroniewn** [comment]
> @sofroniewn I think it's critical that we are able to support arbitrary label numbers, so the bare list approach won't work.

Agreed

>  dict of labels -> properties is "row oriented" and won't rhyme at all with the points properties. 

I think I follow

> A middle ground is columns (like in points) and a dictionary index mapping labels to rows.

I think I like this idea, but just want to make sure I get it. We'd have `properties` dict which is the same as is in `points`, but then we'd also have an (optional?) index dict which mapped labels to rows (if not provided, could just assume a 1-1 mapping)

```python
properties = {'class': ['background', 'cytoplasm', 'nucleus']}
index = {0: 0, 10: 1, 11: 1, 100: 2}
```
where here the `0` label would map to `background`, the `10` and `11` labels would both map to `cytoplasm` and then `100` label would map to `nucleus`.

Does that sound about right?

If `index=None` then we'd just map `0` -> `0`, `1` -> `1`, ... acting as a cycle when exceeding the length of the properties list or throwing an index error when that happens.

This could allow a best of both worlds, where we can handle arbitrary labels, but we do the sensible thing for people that know they just have 3 labels and are fine calling them `0`, `1`, and `2`.

Is that what you had in mind @jni? 

> That should work although we are getting dangerously close to reimplementing pandas from scratch. =P

If we need to add pandas at some time we can :-)

**Comment by DragaDoncila** [comment]
> I think I like this idea, but just want to make sure I get it. We'd have properties dict which is the same as is in points, but then we'd also have an (optional?) index dict which mapped labels to rows (if not provided, could just assume a 1-1 mapping)
> 
> ``` properties = {'class': ['background', 'cytoplasm', 'nucleus']} ```
> ``` index = {0: 0, 10: 1, 11: 1, 100: 2} ```
> where here the 0 label would map to background, the 10 and 11 labels would both map to cytoplasm and then 100 label would map to nucleus.

I think this makes sense when you've only got the one key-value pair in the properties dictionary, but what if you wanted to have say,

```
properties = {
'class': ['background', 'cytoplasm', 'nucleus'],
 'label_confidence' = ['strong', 'medium', 'weak']
}
```

Would your index mapping now be a dictionary also e.g.
```
properties = {
  'class': ['background', 'cytoplasm', 'nucleus'],
  'label_confidence' = ['strong', 'medium', 'weak']
}
index = {
   0: {'class':0, 'label_confidence':0},
   10: {'class':1, 'label_confidence':1}
}
```
Also what if your label confidence was a float range? Is that something we want to support? Is that a use for the properties attribute?

**Comment by jni** [comment]
@DragaDoncila your objection is totally correct.

@sofroniewn close, but each label must map to exactly one row — this might mean that 'cytoplasm' is repeated, but that's fine. The analogy with points is one label corresponds to one point.

**Comment by sofroniewn** [comment]
> I think this makes sense when you've only got the one key-value pair in the properties dictionary, but what if you wanted to have say,
>
> properties = {
'class': ['background', 'cytoplasm', 'nucleus'],
 'label_confidence' = ['strong', 'medium', 'weak']
}

I think here i'd still have the `index` dictionary be `index = {0: 0, 10: 1, 11: 1, 100: 2}` and each label map to one index across all properties.

> Also what if your label confidence was a float range? Is that something we want to support?

This wouldn't be supported. Not sure how to do that.

> @sofroniewn close, but each label must map to exactly one row — this might mean that 'cytoplasm' is repeated, but that's fine. The analogy with points is one label corresponds to one point.

I'm fine with this, I guess it makes it simpler. Have to think through what happens if someone picks a new label and starts painting with it. I guess we need to use defaults like we did in points too
