### ISSUE TITLE
Need consensus on options for delivering icons & resources

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#1221]
## ❓ Question

As shown in #1209, it looks like the strategy of building icons after installation is not going to work in every case.  Even though I tried to put in three levels of "fallback" behavior, in case of permissions errors and stuff, I think it's probably safer to ship a default resources file that is checked into source (or built just prior to uploading our package to PyPI)... 

This brings us back to cross pyside/pyqt resource compatibility and compatibility of resources built with various rcc versions.  I just tested a crapload of combinations of `_qt_resources.py` files built with various versions of `pyside2-rcc` or `pyrcc5`, and tested them on various installs of napari using pyside2 and qt5 installed with both pip and conda.

## tldr;
resources built with the `pyrcc5` binary from `pyqt5` have much broader compatibility than those built with `pyside2-rcc`.  So if we pre-build using the latest `pyrcc5`, we should be able to expect it to be supported on all version of pyside2 and pyqt5 available on either pip or conda.  (that is not the case with `pyside2-rcc`)

<details>
<summary>exact combinations I tested</summary>

### using pip to install pyside2/pyqt5

>PySide2==5.11.2 -> 'Shiboken.ObjectType' object is not iterable
>PySide2==5.12.6 -> 'Shiboken.ObjectType' object is not iterable
>PySide2==5.13.2 -> 'Shiboken.ObjectType' object is not iterable

PySide2==5.14.0 -> **works**
PySide2==5.14.2.1 -> **works**

(PyQt5 < 5.11.3 -> uninstallable on pip due to sip)
PyQt5==5.11.3 -> no icons
PyQt5==5.12.3 -> no icons
PyQt5==5.13.2 -> **works**
PyQt5==5.14.2 -> **works**

### using conda to install pyside2/pyqt5

pyside2=5.12.4.py37h9cca949_0      conda-forge -> no icons
pyside2=5.13.2.py37ha8f7116_2     conda-forge -> no icons
pyqt=5.9.2.py37h2a560b1_4      conda-forge -> no icons
pyqt=5.12.3.py37ha62fc16_3      conda-forge -> no icons

### using pip to install pyside2/pyqt5

PySide2==5.14.2.1 -> **works**
PyQt5==5.11.3 -> **works**
PyQt5==5.12.3 -> **works**
PyQt5==5.13.2 -> **works**
PyQt5==5.14.2 -> **works**

### using conda to install pyside2/pyqt5

pyside2=5.12.4.py37h9cca949_0      conda-forge -> **works**
pyside2=5.13.2.py37ha8f7116_2      conda-forge -> **works**
pyqt=5.9.2.py37h2a560b1_4      conda-forge -> **works**
pyqt=5.12.3.py37ha62fc16_3      conda-forge -> **works**

</details>

### question for @napari/core-devs 
I think we should bundle resources built with `pyrcc5`, rather than building them after install. (though end-users could still be able to rebuild icons using `python -m napari.resources.build_icons`).  How best to do this?
- Just have someone manually build it and check it into source whenever it needs updating?  making sure they are building with `pyrcc5` instead of `pyside2-rcc` (testing for this is possible)... 
- not check into source, and have it built on github actions prior to deployment, by installing `pyqt5` prior to running `setup.py`. This is made complicated by the fact that we actually check to see which backend is installed when writing our requirements.  So we'd basically have to pip install pyqt5, build the icons, uninstall, pip install pyside2, run setup.py... 🙄

**Comment by jni** [comment]
Just to recapitulate some discussion for the meeting: we decided to dig a bit deeper into why autogeneration would fail, rather than go to bundling straight away. If we're still stuck in 1-2 weeks we can revisit the bundling idea.
