### ISSUE TITLE
Documentation for stable release

### ISSUE THREAD

**Issue by Czaki** [napari/napari#1226]
## 📚 Documentation
The documentation under the address https://napari.org/docs/ is current development release. It should be last stable release. 

Maybe best approach is to have current development, current stable and links to older ones?

**Comment by jni** [comment]
Yes, it is our plan to have versioned docs, we just haven’t gotten around to it yet. Thanks for raising the issue!

btw, we are planning to release ~every two weeks, so the docs should always be close to accurate for the latest stable, until we come up with a better site.

**Comment by sofroniewn** [comment]
This was closed by #1638
