### ISSUE TITLE
Handling of unexpected layer kwargs from plugins

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#1227]
## 🐛 How to handle mismatched kwargs from plugins?
When we introduced the option to force `viewer.open` to interpret layers as a specific type with the `layer_type` options, we had decided it would be an error if the user specified a specific layer type, but a plugin returned kwargs incompatible with that type.  So for instance:

if the user asks:  `viewer.open('path/to/image.tif', layer_type='labels')` and the plugin returns layer data of `[(data, {'rgb': False}, 'image')]` then we raise a `TypeError` because the `add_labels` method has no keyword `rgb`.  The plugin wasn't wrong, it just couldn't possibly anticipate what the user was going to do.

Yesterday, tifffile released version `2020.5.7`, which includes a tentative napari reader plugin (🎉), and before #1222 merged, it was causing an error in our `test_viewer_labels_io.test_open_labels` for exactly the scenario mentioned above.

1. modify where we apply the `prune_kwargs` logic, such that we simply strip any invalid kwargs returned from the plugins.  in other words "yes, that was a valid kwarg for the layer type you _thought_ you were returning, but the user has requested that we go in a different direction with this"...
2. pass the user-supplied `layer_type` argument to the plugins and make them deal with it (I dislike this option a lot... we shouldn't put that burden on the plugins)

if we go with 1... we might want to _only_ strip invalid kwargs when the user has specified `viewer.open(path, layer_type=...)`, and keep it as an error otherwise (for instance, if the plugin mistakenly returned a key in their `meta` dict that didn't match the `layer_type` that *they* specified.)

**Comment by sofroniewn** [comment]
> 1. modify where we apply the prune_kwargs logic, such that we simply strip any invalid kwargs returned from the plugins. in other words "yes, that was a valid kwarg for the layer type you thought you were returning, but the user has requested that we go in a different direction with this"...

I like this option - we shouldn't break with `rgb=False` for `labels` especially because it is a kwarg that is for `image` and is basically just hard coded for `labels`.
