### ISSUE TITLE
Update how we demo and test code

### ISSUE THREAD

**Issue by jni** [napari/napari#123]
Closely related to #84.

As I noted in #114, I'm frustrated that I have to launch a notebook to test all the code coming in to a new PR. And, that `layers.ipynb` notebook is just insanely big at this point, demonstrating so many different things.

My suggestion is that the examples directory should contain a bunch of single-purpose demonstration scripts. Essentially every separate cell or group of cells in `layers.ipynb` should be its own script, *and*, when an interactive feature is being demonstrated, the module docstring for that file (a single triple-quoted block of text at the very top of the file) should describe what interactions you should try and what is expected to happen. (This was even the goal for the notebook originally but those notes all appear to have fallen by the wayside! Partly because diffing notebooks is so hard so I tend to ignore the whole diff of the notebook.) Eventually these guides could result in some automated testing by people who know more about running GUI tests than I do. =P They might also result in a gallery if we figure out automated screenshot-taking.

@bryantChhun expressed a similar wish in #84.

**Comment by AhmetCanSolak** [comment]
Strongly agree. I'd been addressing these issues and need to script as the primary tests ever since. Also @jni i believe that it maybe useful to build UI testing part of project as you suggest.

**Comment by sofroniewn** [comment]
@jni agreed this will move us in a better direction, and will make it easier as new features get added to add new example scripts. I like the idea that each example tests a very narrow portion of the functionality (like pan/zoom, change dimensions, reorder the layers, adjust clims, add a markers layer etc.).

Makes sense to me that we first just focus on making example scripts and then we can turn these into automated tests and screenshoting in the future. This will really help ensure the robustness of the code base, and can provide a way for people to understand how to use Napari.

My major question then is how should this relate to #67? Should we actually get rid of the notebooks entirely from the repo at this point (and not use jupytext at all) and just have all these examples be scripts? We could always add notebooks back in at a later stage as tutorials, but that's not really the function that we need right now. I know I was resisting this decision before, but I think having lots of small example scripts might be the way forward now.

**Comment by bryantChhun** [comment]
I plan to submit quite a few extra examples (all scripts) and tests as soon as I have my vector layer up to speed.

my two cents:  there is great value in having both the notebooks and the examples.  Perhaps we can think about how they are packaged?  Is the concern that, going forward, we will be asking developers to write all three of test script, example script, and notebook usage?

**Comment by sofroniewn** [comment]
I see some differences in how "test script, example script, and notebook" will all be used. I think notebooks are great for tutorials and more complex demos - when they have lots of comments about what and why we are doing what we are doing. I think right now though our needs are more around basic examples and really tests that utilize the API and will make feature development and refactoring easier and more robust.

I've add a bunch of new small example scripts (with one very simple example notebook) in #128 - curious what everyone thinks

**Comment by sofroniewn** [comment]
Now that we have merged #128, how to people think we should create tests from our examples?

**Comment by sofroniewn** [comment]
As discussed in our meeting today we want to both test the examples (to ensure they run) and test core internal aspects of the code standalone. @AhmetCanSolak will investigate this further using pytest. When we run an example if we have a keyboard shortcut - say cmd+q to close the app - we are able to test the example in an automated way cross platform.

In the future we can think about adding interactivity tests (simulating button clicking, mouse moves etc) and think about tests that compare screenshots to stored images at a pixel-wise level, but we are not ready for that yet

**Comment by sofroniewn** [comment]
We've come a long way since this issue was create - converting all our examples to executable scripts that get run during testing, and separating out our model and view files so that we can separately test non-qt and qt files. We still havn't got full interactive testing simulating button clicks on the gui and screenshots, but that can be discussed in another issue, so I am closing this one.
