### ISSUE TITLE
plugin discovery and installation

### ISSUE THREAD

**Issue by pwinston** [napari/napari#1238]
## 🚀 Feature

Napari should no longer automatically discover and install plugins. Instead we should have a "install plugin" command. The command should present a list of plugins found in the environment. It should show which ones are already installed, and let the user select any of the other ones for installation.

## Motivation

In #1123 the tifffile project added a napari plugin. Napari automatically discovered and used that plugin which broke some tests. So far we assumed if you pip installed a plugin that you wanted to start using it. Now that seems too automatic, sometimes you might not even realize a plugin was pip installed, much less want to start using it.

This was discussed on Zulip:
https://napari.zulipchat.com/#narrow/stream/212875-general/topic/skimage.200.2E17

@pwinston and @tlambert03 mentioned 3 approaches:
1. Automatic discovery and installation (what we have today)
2. Automatic discovery on startup, opt-in to install.
3. Explicit "install plugin" command does discovery, opt-in to install.

Both 2 and 3 address the problem. They are both reasonable solutions, but 3 seems slightly better. The advantage is that 3 is **very** explicit, if you never run the "install" command you know for sure you haven't installed any plugins. If you do run that command, presumably you are taking on the responsibility to install the plugins you want.

Also 3 avoids nagging if you new plugins are trickling in. Also 3 would work with an online registry of plugins, clearly we don't want napari nagging us every time a new plugin is added to the registry.

Finally 3 is how VS Code Extensions work. That does not necessarily mean it's right for napari, but they do have a robust extension ecosystem and it seems to work for them.

**Comment by jni** [comment]
I like 3 well enough. Of course then we'll have to decide what to do with svg. ;)

The nice thing about 3 is that we should be able to have a UI that shows "installed plugins", "enabled plugins", and "available plugins" from PyPI. Note @tlambert03 mentioned that we would need to get a Trove classifier for napari, honestly I think we are there now and we should be able to request it. When I spoke to the PyPI folks at the EOSS meeting they suggested that even making the case from the buzz than napari is generating could be enough. Now we actually have several plugins including from a major IO library, so I think it's a no-brainer.

**Comment by neuromusic** [comment]
"[Explicit is better than implicit](https://www.python.org/dev/peps/pep-0020/)" 😄

**Comment by tlambert03** [comment]
See #1357

**Comment by psobolewskiPhD** [comment]
So the plugin ecosystem has changed **a lot** in the past 3 years.
1. there is a plugin install gui now—soon to be improved via https://github.com/napari/napari-plugin-manager
2. there is the napari-hub with extensive info about plugins.
But pip installed plugins still get auto-used as far as I can tell, which is a nice shortcut for a power user.

That said, I can see an arguement for confirming in napari that the pip installed plugin should be active. So maybe there should be a distinction between `installed` (in the env) and `activated` (in napari)?

**Comment by psobolewskiPhD** [comment]
Other than the current bug (see #7135) I think this issue can be closed.
The current behavior is that plugins are auto-discovered if installed by conda/pip, which is how many plugins give install instructions. I think this would be the expected behavior, since you could do:
`pip/conda install napari napari-ome-zarr` and as an end user want and expect the plugin to work.
**However** we have the plugin manager that lets a user *disable* a plugin and that will be respected for future launches, because it's written out to the settings. So this way a plugin can be installed, but deactivated.

IMO once #7135 is closed, this can be considered closed?
