### ISSUE TITLE
Update layer selection mechanism

### ISSUE THREAD

**Issue by jni** [napari/napari#124]
## 🚀 Feature
Currently, if I click on the name of a layer that is unselected, it goes into text edit mode without selecting it. It would be nice if (a) it would select the layer, and/or (b) it wouldn't go into text editing mode until after the selection. This is analogous to e.g. file browsers like Finder, and it means that one can click and drag anywhere on the layer tile. Currently you can't click and drag if your click is on the layer name.

**Comment by sofroniewn** [comment]
Agreed this should get fixed, I'm leaning towards (b) - a first click anywhere selects the whole box, and dragging can start from anywhere, and edit mode is only entered on release or a second click

**Comment by sofroniewn** [comment]
this has been fixed in #196
