### ISSUE TITLE
"Toggle menubar visibility" trap

### ISSUE THREAD

**Issue by d-v-b** [napari/napari#1252]
## 🐛 Bug

After turning off the menubar by selecting "toggle menubar visibility" from the "view" dropdown menu, there are no longer any GUI elements to reverse this change. This feels like a trap (the only way out is is to memorize a keyboard shortcut). Users who do not memorize the shortcut will be forced to kill + restart napari if they want the menubar back.

## Environment

 - Please copy and paste the information at napari info option in help menubar here:
```
napari: 0.3.1+2.g96e9722
Platform: Linux-5.3.0-51-generic-x86_64-with-glibc2.10
Python: 3.8.2 (default, Mar 26 2020, 15:53:00) [GCC 7.3.0]
Qt: 5.12.5
PyQt5: 5.12.3
NumPy: 1.18.1
SciPy: 1.4.1
Dask: 2.16.0
VisPy: 0.6.4

GL version: 4.6.0 NVIDIA 435.21
MAX_TEXTURE_SIZE: 32768

Plugins:
- napari-plugin-engine: 0.1.5
- svg: 0.1.2
```

What is the use case is for the "toggle menubar visibility" option anyway? I would think that by definition the menubar contains actions / settings that affect the entire napari app, and thus this is the one UI element that should always be accessible. But maybe there is some usage I'm not considering.

**Comment by tlambert03** [comment]
![source](https://user-images.githubusercontent.com/1609449/81972087-1548be80-95f0-11ea-81bc-146b4147cc1e.gif)

**Comment by Svidro** [comment]
I managed to do this during the Neubias presentation this morning . :)

**Comment by jni** [comment]
> I managed to do this during the Neubias presentation this morning . :)

😬 

> What is the use case is for the "toggle menubar visibility" option anyway? I would think that by definition the menubar contains actions / settings that affect the entire napari app, and thus this is the one UI element that should always be accessible. But maybe there is some usage I'm not considering.

This dates from the first time we added a menubar. A menubar seemed redundant and an annoying waste of screen real-estate for those that are only using the viewer from Python (such as myself). So I wanted a way to get rid of it. Originally I detected whether napari was being run from the command-line and only put a menubar then, but @sofroniewn worried about the consistency of the experience. I *still* think the menubar is redundant and annoying on non-Mac platforms when not using the app, but I've gotten used to it and don't compulsively press Ctrl-M anymore. Additionally, the amount of useful stuff in the menubar keeps growing. So one option is to just remove it.

*But* I wouldn't mind if we thought a bit about solutions that involved not having the menubar there when using Python. OR, maybe we don't show the remove menubar option if launching from the command-line or an eventual bundle. Or maybe even add a visual way to get the menubar back...!

**Comment by Svidro** [comment]
I would say something like a small, but very obviously bright Plus (+) symbol you could click on in one of the corners would work (Act as an undo from the time of the toggle?). Give it a small square background of opposing color just in case of weird image coloration issues? I know nothing about Python UI coding so I don't know how hard that would be.

**Comment by psobolewskiPhD** [comment]
I use macOS so this bug is pre-prevented for me, but I'd be a strong proponent of just removing this "feature". The utility is what, 10–20 pixel saved?—I don't say this lightly as I use a 13" monitor—while the consequences are 😬
I've asked around Windows users and apps without menus are not the norm and rather a troubling symptom of non-native UIs.
Not sure the situation on Linux, so we could just hide this on windows in addition to the current macOS protection.

**Comment by Czaki** [comment]
Firefox on Linux and Windows hide the menu (press Alt to show it). But provides a hamburger menu to provide access to the most important functions.

**Comment by jni** [comment]
What @Czaki said. 😃 It's a "hidden" feature of many apps but it's not non-standard behaviour. tbh the rationale here is that in some situations, we don't want a menu bar. Just like a matplotlib plot doesn't have a menubar, there's an argument for an "as full-screen as possible" viewer in many situations, especially when working from Python. So, one idea might be to disable this in the bundle? Or, preferably, to add a more obvious way to bring it back, e.g. with a hamburger menu.

**Comment by Czaki** [comment]
Or remove it from view menu and left only as keyboard shortcut?

**Comment by psobolewskiPhD** [comment]
> Or remove it from view menu and left only as keyboard shortcut?

That would work right? someone needs to know the command to trigger it, so then they'd know how to undo, avoiding the trap?
and if they accidentally do it by keybind, then they can't undo it anyways, so nothing is harmed vs. current state.

**Comment by dalthviz** [comment]
Hi, just another idea, maybe making the menu to be visible "on hover" when the toggle menubar action is triggered could be interesting? So something like:

![menubar](https://github.com/napari/napari/assets/16781833/548d3d19-2bb8-40ae-a29b-6a93b7a5bdde)

If that sounds interesting, the implementation can be done using an `eventFilter` so something like this: https://stackoverflow.com/a/21998916

Also, here a branch with an initial implementation based on the SO post above: https://github.com/napari/napari/compare/main...dalthviz:napari:issue_1252
