### ISSUE TITLE
axis slice label slightly cut off

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#1253]
## 🐛 Bug

See https://twitter.com/pskeshu/status/1260974224677560320 and 

![image](https://user-images.githubusercontent.com/6531703/81983618-897f6400-95e8-11ea-9ea0-4ac638d596e4.png)

**Comment by tlambert03** [comment]
oh man... I have tried so hard to fix that in a cross-platform way...  would love to have someone else take a whack at it (but definitely test on windows, mac, and linux)

**Comment by tlambert03** [comment]
@czaki has completely cleaned up this area in #1415, #1439, and #1440!
