### ISSUE TITLE
Add `nbscreenshot` function or similar that will embed the current state of the viewer in screenshot

### ISSUE THREAD

**Issue by jni** [napari/napari#1267]
## 🚀 Feature

When using napari in notebooks, the recorded notebook becomes a sad shadow of all that went on in that notebook, because none of the napari windows or interactions are visible. It would be great to have some way of embedding the current viewer as a screenshot in the notebook. (see aside in #1237.) I proposed doing this implicitly in #756 but we dismissed that idea as too confusing. If made explicit though, it could be a powerful way to record interactions. For example, if nbscreenshot returns an object with a `_repr_png_` method, we could do:

```python
# cell 1
import napari

v = napari.Viewer()
v.add_image(my_data)
pts = v.add_points()
pts.mode = 'add'
# annotate
```

Then
```python
# cell 2
nbscreenshot(v)
```

would show the viewer with the annotated points. Then the notebook would continue with the analysis.

Taking it further, if you look at the IPython display documentation:

https://ipython.readthedocs.io/en/stable/api/generated/IPython.display.html

there's also the ability to display a video. So it would even be possible to do e.g. `napari.record(True)`, then `nbrecording(v)` would embed a video of the viewer's interactions.

I would make this a stretch goal though, the screenshot bit is easy-ish and important.

**Comment by sofroniewn** [comment]
The screenshot functionality be provided by #1269. 
 
I think the video/ record functionality should wait for further progress with #780, though one could also have a very simple record that just took screenshots every `x` ms for `n` seconds. Data might get big :-)
