### ISSUE TITLE
Use magic name guessing for colormap names

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#1278]
## 🚀 Feature
We should use the magic name guessing that @kne42 implemented in #1008 for layer names for colormap names so that in an example like this one https://github.com/hci-unihd/covid-if-annotations/issues/6#issuecomment-633295497 the colormap would be named `custom` by default, instead of `[unnamed colormap]`.

**Comment by sebgoti** [comment]
Hi! May I take over this issue?

**Comment by tlambert03** [comment]
sure! ... however, now that I'm looking at this again.  I'm not sure I agree that stack inspection and magic name guessing is the right approach here.  Seems like simply adding a `name` attribute to `Colormap` might be a less error-prone and more direct approach?  @sofroniewn?

**Comment by sofroniewn** [comment]
> Seems like simply adding a name attribute to Colormap might be a less error-prone and more direct approach? @sofroniewn?

Colormap already has a `name` option. I guess the thought was that like how `layer` has a name option but if not provided we'd guess it then we should do the same thing here, but if you think that's too magical then maybe we should just close this issue before @sebgoti get's too far.

It has been a while since this issue was created, and I think over that time we have moved away from certain magic guessing as it can be error probe. Maybe @jni wants to weigh in too and then we can decide? I don't have strong feelings here, but want to make sure we don't waste anyone's time!

**Comment by tlambert03** [comment]
yeah, after running into issues with magic_name in the recent multiscales API PR, I personally would vote to minimize its usage.  I do really like that it works for layer names, but I wouldn't want to see it proliferate.  One of the main differences between `colormap` and `data` is that `data` generally is coming in as a numpy array that itself doesn't have a `name` attribute.  with `Colormap` in the [motivating example](https://github.com/hci-unihd/covid-if-annotations/issues/6#issuecomment-633295497), we don't have that limitation

**Comment by sofroniewn** [comment]
> One of the main differences between colormap and data is that data generally is coming in as a numpy array that itself doesn't have a name attribute. with Colormap in the motivating example, we don't have that limitation

Ok, agreed - that example is out of date as it uses to old vispy colormap, and now we have our own colormap the new code should be

```python
import numpy as np
import napari

data = np.random.randint(4, size=(10, 10))
custom = napari.utils.Colormap([
        [0., 0., 0., 0.],  # label 0 is fully transparent
        [1., 0., 0., 1.],  # label 1 is red
        [0., 1., 1., 1.],  # label 2 is cyan
        [1., 1., 0., 1.],  # label 3 is yellow
    ],
    name='my custom name',
)

viewer = napari.view_image(data, colormap=custom, contrast_limits=[0, 3])
napari.run()
```

Will this meet your needs @sebgoti? We can help you find another good first issue too if you were interested in making a contribution. Sorry that this one got out of date. I agree we should close it though

**Comment by tlambert03** [comment]
> We can help you find another good first issue too if you were interested in making a contribution.

yes please!  didn't mean to run you off @sebgoti :)

**Comment by sebgoti** [comment]
Thank you both @tlambert03 and @sofroniewn very much for your replies. I think I will then search for another good first issue but any suggestions are very well appreciated too 😄

**Comment by tlambert03** [comment]
In addition to code, we always love PRs to our documentation!  So if there was anything you found missing or confusing in the docs as you were picking up napari, that's also an option!

**Comment by sofroniewn** [comment]
> I think I will then search for another good first issue but any suggestions are very well appreciated too 😄

Ok, great - thanks! One that might be good to look at is #2569 around adding a more clear error message!

I will close this issue though as we won't be implementing this feature
