### ISSUE TITLE
Switching to pan mode via space works poorly

### ISSUE THREAD

**Issue by constantinpape** [napari/napari#1282]
## 🐛 Bug

Switching to the pan mode via holding `space` in the points layer works only poorly.
It switches to the pan mode when I hold space, but as soon as I do any action, e.g. zooming, it goes back to the previously selected mode.

**Edit:** The problem is not performing an action, but that the mode flips back to the selection mode  
after a second (while I still hold done space). I tried with two different keyboards, so I don't think it's a keyboard problem.

## To Reproduce

- open an image in napari
- add a points layer and some points
- go to the selection mode
- hold space and try to navigate the image

## Expected behavior

Holding space activates the pan mode and it's only deactivated when releasing the key.

## Environment

 - Please copy and paste the information at napari info option in help menubar here:
```
napari: 0.3.1
Platform: Linux-5.3.0-51-generic-x86_64-with-glibc2.10
Python: 3.8.2 | packaged by conda-forge | (default, Apr 24 2020, 08:20:52) [GCC 7.3.0]
Qt: 5.12.5
PyQt5: 5.12.3
NumPy: 1.18.4
SciPy: 1.4.1
Dask: 2.16.0
VisPy: 0.6.4

GL version: 3.0 Mesa 19.2.8
MAX_TEXTURE_SIZE: 16384

Plugins:
- covid-if-annotations: 0.1.dev2+gfeab50b.d20200522
- napari-plugin-engine: 0.1.5
- svg: 0.1.2
```

 - Any other relevant information:
- Napari was installed from conda-forge
- used inside of this tool: https://github.com/hci-unihd/covid-if-annotations

**Comment by sofroniewn** [comment]
For better or for worse this is a duplicate of #133 I think. Unfortunately I don't have access to a linux machine and this does seem to be platform specific. I'm not sure where the bug really comes from see code for space press here https://github.com/napari/napari/blob/master/napari/layers/points/_points_key_bindings.py#L5

Any help debugging from @kne42 @jni @tlambert03 or others would be appreciated

**Comment by constantinpape** [comment]
> For better or for worse this is a duplicate of #133 I think.

True, it's a duplicate.
I am going to close this.
