### ISSUE TITLE
Ideas about active layer

### ISSUE THREAD

**Issue by constantinpape** [napari/napari#1283]
When I looked at our napari proofreading tool yesterday with @akreshuk, we had two ideas / comments on the active layer design:
- The highlighting of the active layer is very subtle and can easily be overlooked by new users. Maybe change the color or shading instead of just adding an outline.
- I think it would be quite natural to change the active layer with `tab` instead of just switching to the next gui element, which I don't find particularly useful.

(I removed the issue template; this is more a discussion than an actual feature request.)

**Comment by sofroniewn** [comment]
> The highlighting of the active layer is very subtle and can easily be overlooked by new users. Maybe change the color or shading instead of just adding an outline.

Agreed, the outline is really thin right now. I think changing the shading could be nice, maybe making it a little lighter - maybe using `primary` color? What do you think @tlambert03

<img width="1200" alt="Screen Shot 2020-05-25 at 9 28 37 AM" src="https://user-images.githubusercontent.com/6531703/82830423-8f880700-9e6a-11ea-8954-bb9d6a29d989.png">

> I think it would be quite natural to change the active layer with tab instead of just switching to the next gui element, which I don't find particularly useful.

You can change with `up` and `down` arrows, not sure if that was clearly documented anywhere. Let me know if that is sufficient or if you'd like `tab` as well / or instead. (I'm very open to all these ideas, to me this is stuff that can be decided by user experience testing which we havn't done a lot of yet)

**Comment by sofroniewn** [comment]
@tlambert03 I'm trying to make this change, but running into some unexpected problems with the coloring of QLineEdit box not refreshing properly when the `selected` state of the `QtLayerWidget` changes. If you had time to make a quick PR for this that would be great, otherwise I can look into it more, or make a PR with my (minimal) progress so far

**Comment by constantinpape** [comment]
> Agreed, the outline is really thin right now. I think changing the shading could be nice, maybe making it a little lighter - maybe using `primary` color?

Sounds good. I also think changing the shading would work well.

> You can change with `up` and `down` arrows, not sure if that was clearly documented anywhere. Let me know if that is sufficient or if you'd like `tab` as well / or instead. (I'm very open to all these ideas, to me this is stuff that can be decided by user experience testing which we havn't done a lot of yet)

Oh, I see. I think `up` and `down` also works fine.
I am a bit biased towards `tab`, because this is what `paintera` uses for this functionality.
In the end I would also think that for this a bit of a wider user survey would be the right way to go.

**Comment by tlambert03** [comment]
> @tlambert03 I'm trying to make this change, but running into some unexpected problems with the coloring of QLineEdit box not refreshing properly when the `selected` state of the `QtLayerWidget` changes. If you had time to make a quick PR for this that would be great, otherwise I can look into it more, or make a PR with my (minimal) progress so far

does this work?

<img width="239" alt="Screen Shot 2020-05-25 at 2 51 47 PM" src="https://user-images.githubusercontent.com/1609449/82837552-692c9080-9e97-11ea-8113-105976024516.png">

**Comment by sofroniewn** [comment]
Looks beautiful to me!!

**Comment by tlambert03** [comment]
k will submit

**Comment by constantinpape** [comment]
Yes, looks much better!

**Comment by sofroniewn** [comment]
Closed by #1284
