### ISSUE TITLE
GUI Style

### ISSUE THREAD

**Issue by AhmetCanSolak** [napari/napari#13]
I am having some experiments with pyqt5 and observed that same code can easily generate different styles for different operating systems. To prevent that there is a style plugin for qt5 called `fusion`. Do we have concerns on consistency of gui style and behavior across various operating systems? I guess we do. Let me know your thoughts on this issue and maybe discuss this in the next meeting?

**Comment by jni** [comment]
@AhmetCanSolak can you elaborate, maybe with screenshots? I think the right thing to do is to have native-looking styles for each OS. An app should look like a Mac app on Mac, a Windows app on Windows, and a Linux app on Linux. If I remember correctly, Qt does this by default?

**Comment by AhmetCanSolak** [comment]
Sure!

I want to redirect you to this [link](https://doc-snapshots.qt.io/qt5-5.12/gallery.html)
Examples in the link is not dramatic enough maybe, so let me share [this](https://stackoverflow.com/questions/46051480/pyqt5-different-view-on-os-and-linux) too.

Qt by default provide native-looking styles and the variation between operating systems can go crazy. 
That's why, I suggested to have a common style for all operating systems.

**Comment by jni** [comment]
@AhmetCanSolak even with the second link, I still prefer the different styles, which are, as far as I can tell, all functional and all consistent with the respective OS, if inconsistent with each other. In contrast, the Fusion style looks somewhere between "meh" and "really off" in every OS.

**Comment by royerloic** [comment]
We will see how it goes, if there is a problem with the style we will solve it... One thing that could happen is that we might have trouble having a consistent layout. Time will tell.

**Comment by AhmetCanSolak** [comment]
Thank you @jni for your comment. As also @royerloic said then we can go without styling for now and decide in time, especially if we face any issue regarding this.

**Comment by sofroniewn** [comment]
I think it might be time to revisit our GUI styles, right now we have an awkward mix of defaults and some custom css, where the custom css has been coded to look OSX native. This will probably give horrible results on windows and linux. I suggest we move to a world of entirely custom CSS that gives us complete control of all the stylings and then looks the same cross platform.

I know @freeman-lab is eager to do this, and I am happy to help point him to where the CSS needs to be inserted. I think now is a good time to do this as the `Viewer` has reached a certain level of complexity where we think some major functionality is represented, but it is not so large yet that this will be too hard.

**Comment by jni** [comment]
@sofroniewn 
> looks the same cross platform

as expressed above, I don't think that this is a worthy goal. Things should look native, not the same across platforms. Many design gurus rightly give Google flak for designing their iOS apps to look like Android apps. In contrast, Apple's forays into Android look native there.

> some custom css

Where is this and why?

**Comment by royerloic** [comment]
That's great. Please hold off on major code right now as I have a monster PR on the way that will lead to some unpleasant conflicts...

**Comment by sofroniewn** [comment]
Waiting for refactoring is fine @royerloic, but probably good to start discussing this.

@jni - we have some custom css in the layer properties (see [here](https://github.com/napari/napari/blob/4d713575eae0de2d4f14bb86b6a09ea7b3278f29/napari/layers/_base_layer/view/properties.py#L13)) and the buttons. More significant is our range slider which is entirely custom styling and would be some effort to make appear native cross platform (though could certainly be done). As a side note we should switch out all the default sliders with our range sliders (for example in the dims refactor @royerloic is doing right now).

I'm also not sure that I agree that native is the way to go (if I understand this correctly). I think of applications like photoshop and illustrator and don't think they look native, but that they look highly professional, which is something we want I think. @freeman-lab want to weigh in?

**Comment by royerloic** [comment]
I agree, linux native looks, unfortunately, often like very amateurish. I have no clue about CSS, and I am not sure i want to learn it, but I trust that some among us have the skills to tackle that.

In any case, I would recommend that we isolate the CSS styling and custom widget styling and design from the rest of the UI code. So we should have a special package with our generic widgets, and then use them within the Napari component views...

**Comment by freeman-lab** [comment]
good discussion! 

think i agree with @sofroniewn that we want to do CSS styling and ensure a consistent look across platforms -- part of it is looking "professional", but it's also that a consistent cross-platform design becomes key to the app's "brand", like a visual anchor, and that's especially important for a highly visual app like this one. 

that said, there's definitely a middle ground where a few key platform-specific elements are done in accordance with each platform's design guides. but even then, using custom CSS throughout, and removing any reliance on platform defaults, is probably the cleanest way to achieve that level of precision and customization.

i've done lots of CSS design and am happy to bootstrap our efforts there (though i'm no means a professional designer, and at some point we might want that!)

also agree with @royerloic that we want to isolate, modularize, and nicely organize our CSS, i know how to do that in web design settings pretty well and am happy to weigh in here once ready!

**Comment by kne42** [comment]
Would also like the chime in that I have some experience with CSS and would love to help both design it and create a system with which it is easy to implement these designs :)

**Comment by sofroniewn** [comment]
This issue has now been superseded by #202 for discussion and #236 and #253 for implementations
