### ISSUE TITLE
min-max slider does not do anything for RGB layers

### ISSUE THREAD

**Issue by royerloic** [napari/napari#130]
## 🐛 Bug

In example: 'imshow_colors.py'  the displayed RGB layer is always displayed in the same manner independently of how the min-max slider is set (vertical double knob slider on the left).
Instead, we should be able to apply the same affine transformation to the RGB values as we do 
for single channel images. 

## To Reproduce

1. run 'imshow_colors.py'
2. move knobs of slider
3. see that the images remains the same.

## Expected behavior

Should behave just as the for the single channel images.

## Environment

 - napari-gui Version (e.g., 1.0): master
 - OS (e.g., Linux): any
 - Python version: 3.7
 - Any other relevant information: none

## Additional context

None

**Comment by sofroniewn** [comment]
Yup, the reason for this I think was that vispy doesn't support adjusting the clims for rgb images. Probably best would be to add this feature on the vispy end and then we would get it "for free".

**Comment by royerloic** [comment]
Got it. I see.

**Comment by sofroniewn** [comment]
Given that we're considering dropping RGB in #481 - this may no longer be an issue. bumping to `0.2` regardless

**Comment by sofroniewn** [comment]
@tlambert03 I saw you digging into some of the vispy clim / rgb stuff in https://github.com/vispy/vispy/pull/1844 does that give you ideas for how to fix this issue? Can you see how to make a nice PR to vispy to address this?

**Comment by tlambert03** [comment]
oh yeah, forgot to mention that... those PRs fix this too!

**Comment by sofroniewn** [comment]
Amazing, ahead of the game @tlambert03 - do those PRs also enable RGB is 3D rendering? I think that hasn't been possible either (I couldn't find a dedicated issue, but seem to remember it), or is that different?

**Comment by tlambert03** [comment]
I think that would require some more doing.  the [VolumeVisual](https://github.com/vispy/vispy/blob/cf244a266fe71a5b306ef518f0f8a05040502939/vispy/visuals/volume.py#L378-L379) doesn't accept a `MxNx4` array like the [ImageVisual does](https://github.com/vispy/vispy/blob/cf244a266fe71a5b306ef518f0f8a05040502939/vispy/visuals/image.py#L106).  I have a sense for how it would be accomplished now if it's something that has been requested...

**Comment by tlambert03** [comment]
btw, if you're curious.  The reason clims hasn't previously worked for RGB data is [this line right here](https://github.com/vispy/vispy/blob/cf244a266fe71a5b306ef518f0f8a05040502939/vispy/visuals/image.py#L399), where they skip the rescaling step for RGB-like data.  after vispy/vispy#1844, it (still) makes the assumption that RGB data has been pre-normalized to 0-1 before giving the data to the ImageVisual, but the shader will then further scale it with our sliders.

**Comment by sofroniewn** [comment]
> I think that would require some more doing. the VolumeVisual doesn't accept a MxNx4 array like the ImageVisual does. I have a sense for how it would be accomplished now if it's something that has been requested...

It has been requested. I couldn't find the place yet, only briefly looked, but I think it would be nice to support if not too much trouble

**Comment by sofroniewn** [comment]
This has been supported by #1456
