### ISSUE TITLE
If image fails to open we should show a visible error in the viewer

### ISSUE THREAD

**Issue by GenevieveBuckley** [napari/napari#1301]
## 🐛 Bug

I think this is more of a "user experience" bug, rather than a technical problem. If you try to open an unsupported image type in napari & all plugins fail, I'd like to see a visible error message in the viewer.

Right now, the only places the error message is visible is the terminal napari was launched from (which we can't rely on users being able to see now we're bundling apps), and also in the plugin errors GUI (which takes three different clicks to open, assuming you know it exists and where to look for it).

## To Reproduce

1. Open napari
2. Attempt to drag and drop an unsupported image type into napari, or using File > Open
    Eg: Drag and drop the example file [toxo.dv](https://github.com/tlambert03/napari-dv/blob/master/toxo.dv), if you don't have `napari-dv` or another plugin that handles deltavision files installed)
3. Observe the image failing to open, and there is no visible clue about why in either the napari viewer or integrated ipython console.
    * There is an error message printed in the terminal napari was launched from. 
    * You can also find the error message buried in the plugins error GUI, but even if you know it's there it still takes three clicks to open - so not exactly low-effort.
    Plugins > Plugin errors, then change the dropdown from "select a plugin" to "builtins".

## Additional context

I know as a general rule we want to be anti-popup, which is a good thing. But I think image opening is important enough that we should have some visible way to tell users (1) something went wrong, and (2) you should try installing another plugin to fix it.

**Comment by tlambert03** [comment]
#794 was a proposal to handle this sort of thing in a general way (I.e. without having to specifically create a pop up for each error case).  Maybe people want to weigh in on that proposal again?

**Comment by liaprins-czi** [comment]
We now have an error message that shows up in the viewer when user tries to open an unsupported filetype:
<img width="1220" alt="Screen Shot 2021-08-31 at 11 15 35 AM" src="https://user-images.githubusercontent.com/53277128/131555028-fbd420f5-33ce-4bfe-822e-dca07c887902.png">

So should this issue be closed?

That's not to say that this workflow cannot be improved, e.g. to eventually suggest plugins that _can_ open the file as I think @tlambert03 has brought up in a different issue (or perhaps in the meantime link to hub with search prepopulated with the name fo the filetype or extension). I make a separate design issue for improving the experience.

**Comment by tlambert03** [comment]
yep, can close, thanks!
