### ISSUE TITLE
Increase hieght of GUI listing all installed plugins

### ISSUE THREAD

**Issue by GenevieveBuckley** [napari/napari#1302]
## 🚀 Feature

The height of the "List installed plugins" window in napari is too short, even when you first start napari and only two plugins are installed by default.

This window can be opened in napari from the "Plugins" menu, by clicking "List installed Plugins..."

## Motivation

I find it super annoying to have to resize the window every time I open it. I'd be a lot happier if there was space to see three or four plugins in the list without scrolling.

**Comment by goanpeca** [comment]
That entry is no longer there

<img width="209" alt="Screen Shot 2021-08-31 at 4 21 25 PM" src="https://user-images.githubusercontent.com/3627835/131577470-70e4881f-ef43-43cd-ac6a-1c1fd8f46d9c.png">

Does this issue still apply @liaprins-czi ?

**Comment by tlambert03** [comment]
This referred to the original plugin table that is now long gone

**Comment by tlambert03** [comment]
it looked like this:
<img width="1392" alt="Untitled" src="https://user-images.githubusercontent.com/1609449/131579075-b24024e9-f17c-46e8-adbc-2839ce39ba12.png">
