### ISSUE TITLE
Test on github actions?

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#1307]
## 🐙😸 Test on github actions?
This definitely falls under the category of "low priority" and "if it ain't broke..."
but I just wanted to show an example of our full test suite [running on github actions](https://github.com/tlambert03/napari/actions/runs/118097110) (branch diff [here](https://github.com/napari/napari/compare/master...tlambert03:feature/github-tests))

this is testing linux36,37,38 with pyqt/pyside, mac38 with pyqt/pyside, and windows38 with pyside only (vm failed with pyqt as it does on cirrus)
 
I'm not making a PR at the moment, because I also took the opportunity to learn/try other things there, including:
- using `tox.ini` to define environments
   - i like! ... note, you can `pip install tox-conda` to use with conda envs locally... and it still doesn't prevent you from running `pytest` in your current environment... but does make it easier to define broad dependency matrices (like python version, qt, etc...)
- move the vast majority of our `setup.py` stuff into `setup.cfg` (like #1228)

but it's here for people to evaluate in case we ever want to move in that direction...

## Motivation

just always reconsidering best practices. sometimes cirrus throws strange errors (but is mostly reliable!).  And there's a growing community of examples and actions for github

## Alternatives

just stick with what we've got!

**Comment by fkorotkov** [comment]
@tlambert03 what kind of strange errors do you see on Cirrus?

**Comment by tlambert03** [comment]
eek.  you mean I have to defend my bold & baseless claims 😅!??
well, as mentioned, it's mostly been very reliable (and the support is good!), but here are a few of the runs we've had recently where I don't understand what's going wrong, (also absolutely acknowledging that this may be our own issues!)

recently been seeing an uptick in connectivity problems like this one:
https://cirrus-ci.com/task/5756071266484224

and an uptick in tests that seem to hang which we force restart after ~30-40 mins (and then they pass) 
https://cirrus-ci.com/task/5080628334952448
https://cirrus-ci.com/task/6072148848541696

anyway,  definitely not trying to throw anyone under the bus... mostly just wanting to learn all of the available CI options out there.

**Comment by fkorotkov** [comment]
Hm. Interesting. Not suer about the SSL errors but will take a look into the hanging cache uploads. 👌

**Comment by tlambert03** [comment]
thanks as always!

**Comment by sofroniewn** [comment]
Our windows tests are failing again on CI. The failure happens during our test suite, but didn't appear to get triggered by any specific code change in napari. I.e. some old PRs that had passed then failed when I triggered them to rerun. It might be interesting to see @tlambert03 if it fails on github actions now too

**Comment by sofroniewn** [comment]
Failures started about 2-3 days ago

**Comment by tlambert03** [comment]
not entirely sure why, but I'm pretty confident at this point that this is due to the 1.4.0 release in [pytest-timeout](https://github.com/pytest-dev/pytest-timeout/releases) a couple days ago.

**Comment by sofroniewn** [comment]
Closed by #2051
