### ISSUE TITLE
Uint8 not displayed properly

### ISSUE THREAD

**Issue by Czaki** [napari/napari#1311]
## 🐛 Bug

Different handling `uint8` that `uint16`, `uint32`
In case of `uint8` napari treats that brightness is from range 0, 255, for biger types its calculate range from data.

## To Reproduce

1. Save same, low value date as uint8 and uint16
2. Load it in napari. 
3. See that the are not properly handled. 

This code prepare data:
```
import numpy as np
import napari

data = np.zeros((50, 50), dtype=np.uint8)
data[10:-10, 10:-10] = 1

with napari.gui_qt():
    viewer = napari.Viewer()
    viewer.add_image(data)
    viewer.add_image(data.astype(np.uint16))
    viewer.add_image(data*255)
```

## Expected behavior
When loading data in uint8 it should be displayed as uint16 

## Environment

 - Please copy and paste the information at napari info option in help menubar here:
```
napari: 0.3.2+2.gc04484fc
Platform: Linux-5.3.0-55-generic-x86_64-with-debian-buster-sid
Python: 3.7.2 (default, Aug 1 2019, 23:29:28) [GCC 8.3.0]
Qt: 5.14.1
PySide2: 5.14.1
NumPy: 1.18.2
SciPy: 1.4.1
Dask: 2.12.0
VisPy: 0.6.4

GL version: 4.6.0 NVIDIA 390.132
MAX_TEXTURE_SIZE: 32768

Plugins:
- napari-plugin-engine: 0.1.5
- napari-plugins: 0.1.0
- svg: 0.1.2
```
 - Any other relevant information:

**Comment by sofroniewn** [comment]
> In case of uint8 napari treats that brightness is from range 0, 255, for biger types its calculate range from data.

This was an intentional choice here https://github.com/napari/napari/blob/master/napari/layers/utils/layer_utils.py#L25 as we heard from people that they expected unit8 data to be viewed on a `[0, 255]` range by default.

**Comment by Czaki** [comment]
From my experience is not best choice. I meet images from deconvolution software which brightnes was bellow 128. 

From other hand I see benefits of this decision. But I think that at least this doc string should be changed with add information that uint8 is handled differently. 

https://github.com/napari/napari/blob/64eed84fbaee98cbf7410f05deb0fc3f2831bdc3/napari/layers/image/image.py#L38-L41

**Comment by tlambert03** [comment]
But how often does decon software output 8 bit images?  (I.e. The max value may be well below 255, but I’ve never seen it output as 8 bits, unless the user intentionally down-converted it)

I think updating docs is a good idea though

**Comment by Czaki** [comment]
> But how often does decon software output 8 bit images? (I.e. The max value may be well below 255, but I’ve never seen it output as 8 bits, unless the user intentionally down-converted it)

I do not do this deconvolution, but only got this files (original was in 16-bits). So I'm not an expert here.

**Comment by jni** [comment]
@Czaki honestly I think whoever did the 16-bit -> 8-bit processing in your case did something sub-optimal. The rationale is that [0-255] is already a pretty compressed range, and anyway it's easy enough to increase the contrast in this case. (It is more difficult for uint16's full range because then the slider is not big enough to get fine-grained control.)

At any rate, I agree that we should add a message to the docstring to specify this behaviour. Thanks for pointing out this inconsistency.

**Comment by Czaki** [comment]
I meet this problem, because current implementation of `label` does not allow to control colours for each label so I mimic labels using image with custom colormap. And I have problem why when changed data type to uint8 it stop displaying. 

Also current implementation of reader read uint8 files as images (and I do not found option to convert it to lables). So I cannot use pure napari as preview of labels saved in tiff (which I meet in few cases), because normal user will see: "Oh nothing loaded".

**Comment by tlambert03** [comment]
> I meet this problem, because current implementation of label does not allow to control colours for each label so I mimic labels using image with custom colormap. And I have problem why when changed data type to uint8 it stop displaying.

what values did you use for your colormap?  as long as you have a uint8 image, and _assume_ it will be rendered with contrast limits from 0-255, then you can create a colormap that would work fine, no?

> Also current implementation of reader read uint8 files as images 

how are you reading in the image?  you can use a number of methods to force it to be interpreted as labels:
- `viewer.add_labels` will always add a labels layer
- `viewer.open( ..., layer_type='labels')` will force the file to be interpreted as labels.
- you can create your own plugin that returns layer data with `labels` as the layer type, such as `[(array, metadata, 'labels'), ...]` ([see docs](https://napari.org/docs/plugins/for_plugin_developers.html#step-1-choose-a-hook-specification-to-implement)).  And if you want it to be chosen for drag-and-drop behavior, then use the plugin argument, or the sorting strategies that we discussed the other day on zulip.

**Comment by Czaki** [comment]
> what values did you use for your colormap? as long as you have a uint8 image, and assume it will be rendered with contrast limits from 0-255, then you can create a colormap that would work fine, no?

I can also set `contrast_limits`. There are many workarounds  

https://github.com/4DNucleome/PartSeg/blob/c932ebf13882857aba2e4095541262840c65dbc6/package/PartSeg/common_gui/napari_image_view.py#L376

> how are you reading in the image? you can use a number of methods to force it to be interpreted as labels:

I think about opening image from menubar. I know that from programmatically interface I can do it simple. 

In previous comment I try to show what scenario of usages users may expect. In case when I embed viewer I can modify and handle multiple things. 

> you can create your own plugin that returns layer data with `labels` as the layer type, such as `[(array, metadata, 'labels'), ...]` ([see docs](https://napari.org/docs/plugins/for_plugin_developers.html#step-1-choose-a-hook-specification-to-implement)). And if you want it to be chosen for drag-and-drop behavior, then use the plugin argument, or the sorting strategies that we discussed the other day on zulip.

I do not know how to distinguish image from layers without information form user. Maybe there should be an option to convert image <-> labels. 

From my side this Issue may be closed, and main fix is to add missing information to documentation.

**Comment by sofroniewn** [comment]
> Maybe there should be an option to convert image <-> labels.

I like this idea, we should enable this when it makes sense

**Comment by jni** [comment]
I think we can close this, given that we have image <> labels conversion, and many more options for contrast limits adjustment (including continuous automatic adjustment). @Czaki please reopen if you disagree.
