### ISSUE TITLE
tooltips on QtControl labels

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#1315]
## 🚀 Feature
specifically, I'd like a tooltip on the "n-dim" checkbox label on the Labels layer... I can never remember what that's supposed to do.
But while we're at it... maybe we should add tooltips as a rule to all of the QControl labels?

**Comment by hectormz** [comment]
Currently when hovering over the checkbox it says "n-dimensional editing". What do you think it should say that would get the point across?

Most docstrings say:
>If True, renders points not just in central plane but also in all n-dimensions according to specified point marker size.

the `labels.py` docstring says:
>If `True`, paint and fill edit labels across all dimensions.

**Comment by tlambert03** [comment]
seems like it should say "edit **all** dimensions" or something using the word "all" rather than "n" maybe?
