### ISSUE TITLE
Remove buggy interpolation modes

### ISSUE THREAD

**Issue by royerloic** [napari/napari#132]
## 🐛 Bug

Some of Vispy interpolation modes for images are very buggy and lead to unsightly
visual artefacts such as black or white vertical lines.
Here is a list of buggy interpolation modes:

- quadric (white lines, sometimes fails entirely)
- sinc (black lines)

We should remove any buggy interpolation scheme,
we are more interpolation than is healthy to have.

## To Reproduce

1. run 'add_images.py'
2. change interpolation schemes and check eac one.

![image](https://user-images.githubusercontent.com/1870994/53631647-dfc0dc80-3bc7-11e9-8bdc-6016a7802fb2.png)

For quadric, the white lines are faint but there:
![image](https://user-images.githubusercontent.com/1870994/53631716-07b04000-3bc8-11e9-99fe-8ac5a6e8e850.png)

## Expected behavior

no weird lines.

## Environment

 - napari-gui Version (e.g., 1.0): master
 - OS (e.g., Linux): OSX
 - Python version: 3.7
 - Any other relevant information: None

## Additional context

None

**Comment by sofroniewn** [comment]
Yup, removing sounds good. I think @kne42 or @jni might have added them originally, maybe assign to them?

**Comment by jni** [comment]
@kne42 added them at my grumpy request. =P Though I only really wanted nearest neighbor :joy: And I guess @kne42 was like, you want more interpolation modes, here's a whole friggin pile of them! =P

**Comment by royerloic** [comment]
Actually, I think I had removed it already in the first version of napari... I should be the one to be grumpy here ;-)
