### ISSUE TITLE
proposal: reducing complexity of models

### ISSUE THREAD

**Issue by kne42** [napari/napari#1325]
## 🚀 Feature
Reduce complexity of current model code by factoring out user-facing API as a view, business logic as a controller, and data structures as a model.

## Motivation

Model code is getting excessively complex. Files are typically over 1000 lines long and difficult to parse/keep track of what's going on. Currently, our models are dealing with data management, presentation logic (i.e. Python magic & data conversion to make it better for users), and business logic.

Right now I feel like we have to make tradeoffs between nice UX and maintainability for the API and separating these components makes it easier to maintain without sacrificing our nice API. Take for example how we handle private variables: either they go without any documentation and can be confusing to the developer or they wind up awkwardly in the public-facing documentation where it doesn't really belong and confuses the user.

Furthermore, I think that the current user-facing API functions more like a view since we do a lot of input/output conversions and use custom Python syntax for a nicer user experience. Perhaps the best example of this is the LayerList.

## Pitch

I want to split out the current model code into model, view, and controller classes.

### Model
The model would be a simple data class that notifies when its fields are changed.

```python
from dataclasses import dataclass

@dataclass
class PointsLayerModel(BaseLayerModel):
    data: Array = notifier()
    mode: Mode = notifier()
    ...
```

This makes it easy to keep track of all relevant information pertaining to the state. You can even easily convert this state into a dictionary for saving and sharing with `dataclasses.asdict`. Keeping this class simple may also make it easier to handle settings and create autogenerated code from the state.

### View
The view would be a simple shell that mimics what you can do with the GUI. It emits events when a user interacts with it and may clean the input before handing it off to the controller.

```python
class Points(Layer):
    @property
    def mode(self):
        return str(self._model.mode)

    @mode.setter
    def mode(self, mode):
        self.events.mode(value=Mode(mode))
```

### Controller
The controller handles the business logic, connects the model to the view, and modifies the model. In a lot of cases it will be a simple event handler that prevents setters from being called multiple times (this can be autogenerated).

```python
class PointsLayerController(BaseLayerController):
    def on_mode_change(self, event):
         with event.source.events.mode.blocker():
             self.model.mode = event.value

    def on_data_change(self, event):
         data = event.value
         data_view = ...
         # calculation of data view goes here
         self.model.data_view = data_view
```

## Alternatives

We could factor out the view without separating the model and the controller and it wouldn't be too big of an issue, but I believe that it would make it easiest to maintain in the future.

## Additional context

Flow of current structure (diagram by @shanaxel42):
![](https://user-images.githubusercontent.com/6810854/75410301-4f979f00-58d0-11ea-9487-9032fd2dd593.png)

Flow of structure in #1040 (diagram by @shanaxel42): 
![](https://user-images.githubusercontent.com/6810854/76366034-0e4aba80-62e6-11ea-81f0-27a368281851.png)

Flow of proposed structure:
<img width="818" alt="Screen Shot 2020-06-01 at 9 05 53 PM" src="https://user-images.githubusercontent.com/29165011/83478847-c605e900-a44b-11ea-9fb9-96cab1c8ff56.png">

**Comment by jni** [comment]
@kne42 Thanks for writing this up! I see where you're coming from, and I'm a fan of dataclasses! I also think that our API is getting quite bloated and needs to go on a diet. :joy: 

The big question for me with this design, which was neatly solved by #1040, is how you prevent an infinite loop between a view and the model. There's the blocker pattern, which results in a lot of boilerplate everywhere, and there's checking whether the notification data is any different from the existing data, but that can be expensive, or doesn't really work with in-place modifications e.g. of numpy arrays.

I also quite strongly dislike having the API view be different from the model. The model *should* be the API, in my opinion. The Pythonic way is to have direct access to the data. In other words, `from napari.layers import Image` should be the model *and* the preferred way to interact with said model. It's unclear to me whether in your diagram, that import would give me the API View, the Model, or the API view but also instantiate the Controller and the Model.

Thoughts?

**Comment by kne42** [comment]
> There's the blocker pattern, which results in a lot of boilerplate everywhere, and there's checking whether the notification data is any different from the existing data, but that can be expensive, or doesn't really work with in-place modifications e.g. of numpy arrays.

The blocker pattern isn't too bad if you use autogenerated code to aid with the boilerplate. We can also do what #1040 was doing with separate setters where one emits an event and another does not.

> The model should be the API, in my opinion.

I agree, in an ideal world. But I think that we're getting to the point where the code is so messy that we can no longer stick to our ideals. It is much more pragmatic to improve maintainability, especially if nothing changes on the user end. Furthermore, separating out these aspects of the program will make it much easier to fool-proof the API if we wish, in the event that we no longer want to take a "garbage in garbage out" approach.

> In other words, `from napari.layers import Image` should be the model *and* the preferred way to interact with said model.

I disagree. The preferred way to instantiate and interact with layers should be via `Viewer.add_*` calls. Within those calls, the Controller and Model will be created with the Views and connected to each other.

**Comment by sofroniewn** [comment]
This is very interesting, and I'll need to spend more time thinking about it before weighing in, but one think I want to add now, is that at this point any major redesign should really put ideas for our plugin interface and headless mode at the front and center too.

> The preferred way to instantiate and interact with layers should be via Viewer.add_* calls. Within those calls, the Controller and Model will be created with the Views and connected to each other.

I think here we need to be careful and really think about what plugins will be doing when there is no viewer and how everything will keep on working seamlessly. See #1272 for some discussion already.

More feedback to come, and thanks for writing it up so clearly and providing a diagram, it really helps me to understand!!

**Comment by 0x00b1** [comment]
> I also quite strongly dislike having the API view be different from the model. The model should be the API, in my opinion. The Pythonic way is to have direct access to the data. In other words, from napari.layers import Image should be the model and the preferred way to interact with said model. It's unclear to me whether in your diagram, that import would give me the API View, the Model, or the API view but also instantiate the Controller and the Model.

💯 

> I agree, in an ideal world. But I think that we're getting to the point where the code is so messy that we can no longer stick to our ideals. It is much more pragmatic to improve maintainability, especially if nothing changes on the user end. Furthermore, separating out these aspects of the program will make it much easier to fool-proof the API if we wish, in the event that we no longer want to take a "garbage in garbage out" approach.

Napari hasn’t reached a 1.0 release, there’s no Napari publication, and (as far as I know) there’re few Napari users. From a maintenance perspective, publicizing classes like `napari.layers.Image` (and encouraging their use) will help ensure Napari’s fundamental data structures remain (or, depending on your perspective, become) ergonomic, tested, and documented.

**Comment by 0x00b1** [comment]
> This is very interesting, and I'll need to spend more time thinking about it before weighing in, but one think I want to add now, is that at this point any major redesign should really put ideas for our plugin interface and headless mode at the front and center too.

In my opinion, the plug-in interface _shouldn’t_ make any assumptions about the user interface (or even the _existence_ of a user interface). As a teenager in the late-90s, I have endearing, nostalgic memories of [insane VST plug-in interfaces](http://www.vst4free.com/), but that’s not something I want to revisit!

**Comment by 0x00b1** [comment]
@kne42 I love the diagram. My suggestion:

![image](https://user-images.githubusercontent.com/315821/83685587-e43c2800-a5b6-11ea-916c-6745caf79475.png)

I think this has the benefit of making it orthogonal to plug-in discussions.

**Comment by shanaxel42** [comment]
Hello! First off I know I've been super out of the loop on things so my opinions here may not be up to data with the current discussions. But wanted to give some input. Thanks @kne42  for writing this up, and especially for making the diagrams. 

So what I like about this proposal is the addition of the "controller" as the place where you cleanup data before updating the model or add other logic. It seems like the main issue around the model files getting bloated could be solved by just adding this layer. 

I see the appeal of wanting to make the separate view file for interacting with the model but I'm with @jni that "The model should be the API". At lest for the developer use case. 

I would also strongly discourage moving in any direction that continues to use the blocker pattern, it just creates a high likelihood of infinite loops or repeat calls and was one of the main things I was trying to eliminate in my original proposal. 

Napari is unique in that it supports interfacing with the data from both the GUI and the data directly. And now a third use case - plugins. If you wanted to incorporate the addition of controllers my suggestion would be to have any use case _besides_ direct data manipulation go through the controller. So what this looks like for each use case: 

- **Developer Scenario** a user wants to interact with the data directly. They should be able to directly update the models which emit an event that the event handler picks up to update the views. 

- **GUI user scenario** a user interacts with the data though the GIU, an event is emitted, the event handler picks it up and calls the controller's update method which then updates the data model

- **Plugin Scenario** A plugin interacts with the models by calling update methods defined in the controller. This also has the advantage of more control over what a plugin can/cannot do with models.

Anyway my 2 cents, thanks @kne42 for all your hard work on this!

**Comment by sofroniewn** [comment]
Thanks @0x00b1 @shanaxel42 for weighing in, and great stuff @kne42 putting this together.

Echoing a lot of what has been said, I really like the idea of our models now becoming very simple and clean.

I actually think our layer models should have no concept of slicing/ dims/ cursor position/ viewed_data/ UI properties (like selected) and all these things that are on them now because we never had a controller. I could even more a lot of the crazy mesh stuff in layers like shapes/ vectors out of there too. I'd just like our models to have the full nD data and the "meta" properties associated with each layer type (i.e. the `layer._get_state()` dictionary) as much as possible, and to emit events when those things are changed.

Having the controller will really enable this and so sounds like a good idea.

If we want both model <==> API and to avoid blockers or diffing though, then I think we need to take the #1040 approach and have two setters and `from napari.layers import Image`.

Does this mean we need an event handler AND a controller, which have different functionality, the event handler ensures we avoid blockers, the controller does this additional functionality above? 

![image](https://user-images.githubusercontent.com/6531703/83696989-a89f5f00-a5b2-11ea-893f-09cba16a2563.png)

I guess in that case I'd keep us moving down the #1040 path, and then maybe add in the controller afterwards.

**Comment by sofroniewn** [comment]
Oh one thing we should also resolve at this point is how we deal with properties on our layer model that are list like - should they be tuples, or do we need dedicated set methods, as right now with our setters events don't get emitted when we change them in place (i.e. `layer.contrast_limits[1] = 10` won't trigger an update, which is confusing if we imagine we have a python api that enables this. I know this has been discussed by most of us before, but now also seems like a good time to address that if we can (at least conceptually, PRs can happen much later).

**Comment by 0x00b1** [comment]
@shanaxel42 For sure. I think controllers will resolve most of the issues.

**Comment by 0x00b1** [comment]
@kne42 I don’t want to step on your toes but I’d be more than happy to work on this with you. Let me know.

**Comment by kne42** [comment]
Thanks to everyone for weighing in! It seems that there is pretty strong consensus towards keeping the public API a model, so I'll ditch API View idea, but I'm glad that people are considering the use of a controller (no surprise from @shanaxel42 tho since she was the one who first proposed it :P). Maybe we can use this issue to work out what belongs in the controllers vs everything else.

@0x00b1 I'd love to work on this with you! I don't have any experience in architecture/other stuff so I would really appreciate your knowledge on what to do :)

> right now with our setters events don't get emitted when we change them in place (i.e. `layer.contrast_limits[1] = 10` won't trigger an update, which is confusing if we imagine we have a python api that enables this

@sofroniewn you'll need to create custom classes that mimic python data structures like what we did with `LayerList`. However, I'm not sure how much @jni would be a fan of this :P

**Comment by liu-ziyang** [comment]
with our work around pydantic data classes, I think we can close this issue?

**Comment by kne42** [comment]
Probably? I haven't been active on this repo in a while, can you catch me up to speed on what we're doing with those?

**Comment by sofroniewn** [comment]
The main thing we've done is turn things into pydantic evented models - see here https://github.com/napari/napari/blob/978dd9e8108a3cd243c2266013eed4b3d2a604fc/napari/utils/events/evented_model.py#L158 (though we havn't done this for layers yet)

**Comment by jni** [comment]
I certainly think the specifics of how we would reduce complexity now are different from mid-2020, so perhaps a new issue is warranted.
