### ISSUE TITLE
Holding space to pan and zoom doesn't work correctly on Linux

### ISSUE THREAD

**Issue by jni** [napari/napari#133]
## 🐛 Bug

In Ubuntu 18.04, "hold space to pan and zoom" while in annotation mode for a markers layer (or in object or vertex selection mode for shapes ­— this is where I first noticed it while reviewing #100) only works for the first drag. After mouse release, despite continuing to hold space, it switches back to annotation mode. I have to release space and press space again for it to work.

Zoom is even worse, as it appears to "deactivate" space e.g. when changing the scroll speed. So it only works for a fraction of a second before having to press space again.

## To Reproduce

1. Run `python examples/add_markers.py`
2. Select the markers layer and turn on annotation (A) mode
3. Hold down spacebar, click and drag, then attempt to click and drag again without releasing space. (the second click will insert a new marker)

## Expected behavior

The second click and drag should also pan. This matches the behaviour in macOS.

## Environment

 - napari-gui Version (e.g., 1.0): master / #100 
 - OS (e.g., Linux): Ubuntu 18.04
 - Python version: 3.6

**Comment by sofroniewn** [comment]
Hmm ok this is strange (I only have a macOS right now where everything still works fine) but we can get a Linux machine at CZI for testing and figure out what events are getting triggered / when and how it relates to our detection and processing of keypress / click vs PyQt native vs vispy.

**Comment by sofroniewn** [comment]
@jni do we know if this is still an issue? can you confirm it is still a problem with master and then we should look into fixing as this seems like important functionality to have working

**Comment by jni** [comment]
Indeed it still is an issue for me, and very frustrating when using napari's annotation tools...

**Comment by sofroniewn** [comment]
@jni do i remember you saying this has been resolved or is it still an issue?

**Comment by jni** [comment]
No, still an issue, what's resolved is the tearing when moving quickly...

**Comment by constantinpape** [comment]
I also just encountered this on 18.04.

**Comment by sofroniewn** [comment]
One place to look in the code is where the `repeat` press is being handled https://github.com/napari/napari/blob/d52ddf87d90328a8a2c1757d43e3075bb672732f/napari/_qt/qt_viewer.py#L555

**Comment by sofroniewn** [comment]
This has been closed by #1350
