### ISSUE TITLE
napari CLI script-runner

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#1333]
## 🚀 Feature

In the last meeting and in https://github.com/napari/tutorials/issues/70, we discussed the idea of being able to run a napari script from the command line *regardless* of whether it contained `napari.gui_qt()`.  Something like:
```sh
napari path/to/script.py
```

The question here is whether we want to just hijack the positional "images" (paths) argument in the existing CLI, look for something ending with `.py`, and run it as a script if so (as done in https://github.com/napari/tutorials/issues/70#issuecomment-635691269) ... Or if we should consider moving to subparsers like `napari open image.tif` and `napari run script.py`.
While it _is_ possible to arrange it such that `napari image.tif` _still_ opens a file... it gets more complicated to do it in a "clean" way such that we see the same help menu for both `napari open --help` and `napari --help`.  

## Options

1. **Do** use subparsers (`open` and `run`), where `open` is the default... and live with the fact that `napari --help` will look like this:
```sh
$ napari --help
napari command line viewer.

positional arguments:
  {open,run}

optional arguments:
  -h, --help  show this help message and exit
  --version   show program's version number and exit
  --info      show system information and exit
  --citation  show citation information and exit
```
and `napari open --help` has all the useful options, _even though_ they also apply even if you didn't use `napari open`

```sh
$ napari open --help
positional arguments:
  images             image(s) to view.

optional arguments:
  -h, --help         show this help message and exit
  -v, --verbose      increase output verbosity
  --stack            concatenate multiple input files into a single stack.
  --plugin PLUGIN    specify plugin name when opening a file
  --layer-type TYPE  force file to be interpreted as a specific layer type.
                     one of {'shapes', 'points', 'vectors', 'labels',
                     'image', 'surface'}
```
2. **Don't** use subparsers, and simply inspect the list of paths passed, and if any (?) of them is a `.py` file, run it as a script (and ignore any other position args?)... 

3. **Don't** use subparsers, but require that the first positional argument be the string "run". 
 This will work for `napari run path/to/script.py` but not for `napari path/to/script.py` ... and "`run`" merely "looks" like an actual subcommand... but it's not, and doesn't come with any of its own help.

4. don't give up on subparsers (option #1) ... but allow for the fact that `napari.__main__` may need to get more complicated to achieve the desired subcommand & help behavior we're after.

@GenevieveBuckley, @jni?

**Comment by sofroniewn** [comment]
Is option 0 we just drop support for `napari image.tif` and require `napari open image.tif`?

That doesn't bother me, but I guess I never use this part of the API, otherwise I lean towards option 1. I will use `napari run my_script.py` all the time though :-)

**Comment by tlambert03** [comment]
> Is option 0 we just drop support for `napari image.tif` and require `napari open image.tif`

that would be the simplest approach, but anticipating some desire to be able to keep `napari image.tif`, I was able to get it such that `napari ...` without a subcommand is the same as `napari open ...` but it becomes hard to keep the help menus consistent while also keeping the code reasonably simple.

**Comment by GenevieveBuckley** [comment]
I am in favour of `napari open image.tif` and `napari run script.py`. Dropping `napari image.tif` is fine with me!

**Comment by jni** [comment]
Sorry to be the spanner in the works, but I *love* napari /path/to/image.tif and I use it all the friggin time! I will cry if we drop it. I *also* think that it's unnecessary to have subparsers — `napari path/to/script.py` is completely unambiguous as far as I'm concerned. So I would prefer option 2. Also, anything *other* than a single .py file would be an error.

**Comment by sofroniewn** [comment]
> Don't use subparsers, and simply inspect the list of paths passed, and if any (?) of them is a .py file, run it as a script (and ignore any other position args?)...

I'm open to option 2 with this approach from @jni. Any arguments against it @tlambert03?

**Comment by tlambert03** [comment]
Nope, I think that’s my preference too
