### ISSUE TITLE
Range slider does not render in proper place in multi monitor environment on linux

### ISSUE THREAD

**Issue by Czaki** [napari/napari#1337]
## 🐛 Bug

![20200604_165422_HDR](https://user-images.githubusercontent.com/3826210/83773561-f6849780-a684-11ea-959e-9ddec2d620bd.jpg)

On my system (Ubuntu 19.10 with gnome shell and nvidia drivers) when napari is not on the most left screen then range slider is not rendered in proper place. 

## To Reproduce

Steps to reproduce the behaviour:

1. Start napari on mulit screeen computer
2. Move window from left screen
3. Click right on range small slider to open big

## Expected behavior
Slider should be placed properly (inside napari window)

## Environment
napari: 0.3.5.dev3+ge9df14f6
Platform: Linux-5.3.0-55-generic-x86_64-with-debian-buster-sid
Python: 3.7.2 (default, Aug 1 2019, 23:29:28) [GCC 8.3.0]
Qt: 5.14.2
PySide2: 5.14.2.2
NumPy: 1.18.2
SciPy: 1.4.1
Dask: 2.12.0
VisPy: 0.6.4

GL version: 4.6.0 NVIDIA 390.132
MAX_TEXTURE_SIZE: 32768

Plugins:
- napari-plugin-engine: 0.1.5
- napari-plugins: 0.1.0
- svg: 0.1.3
 - Please copy and paste the information at napari info option in help menubar here:

 - Any other relevant information:

Ubuntu 19.10, Gnome Shell with nvidia drivers on 3 screen configuration (FullHD, WQHD, FullHD)  

## Additional context

Opening this view for range slider block print screen.

**Comment by Czaki** [comment]
Same on two monitor Linux configuration (Ubuntu 18.04 with gnome shell).

**Comment by tlambert03** [comment]
thanks @Czaki, that does look bad.  Very hard for me to test as I don't have that setup... We would be very grateful for any debugging and/or PRs you can submit on this

**Comment by Czaki** [comment]
@tlambert03 I will be happy to create PR, but If you can provide any suggestion where in the code this slider is created and where have position calculated. It go through napari event system so it is hard to trace.

**Comment by tlambert03** [comment]
Sure, the handling of the right-click event on the clims slider starts here:

https://github.com/napari/napari/blob/e9df14f6c6f09641faa0e2b41f57a0d55632f7f0/napari/_qt/layers/qt_image_base_layer.py#L107-L116

the `self.clim_pop` object is an instance of [`QRangeSliderPopup`](https://github.com/napari/napari/blob/master/napari/_qt/qt_range_slider_popup.py#L89), which is subclassed from [`QtPopup`](https://github.com/napari/napari/blob/e9df14f6c6f09641faa0e2b41f57a0d55632f7f0/napari/_qt/qt_modal.py#L6)... and the `self.clim_pop.show_at()` call at the bottom of that code block is the key part.  The `show_at` method is [in `QtPopup`](https://github.com/napari/napari/blob/e9df14f6c6f09641faa0e2b41f57a0d55632f7f0/napari/_qt/qt_modal.py#L62).  What you will likely need to fix is the logic in these lines:

https://github.com/napari/napari/blob/e9df14f6c6f09641faa0e2b41f57a0d55632f7f0/napari/_qt/qt_modal.py#L125-L134

**Comment by Czaki** [comment]
Thanks, I can also confirm this bug on macos 10.14
And looking on code this should happen on any multi monitor system. I will work to fix this.

**Comment by Czaki** [comment]
@tlambert03 
Why this logic is introduced? Range slider is aligned to napari window. (on first screen). So what is the motivation to move it? User can move window.

**Comment by tlambert03** [comment]
the discussion was around how to handle an undocked layer control panel.  which may or may not be on the same monitor as the viewer... see https://github.com/napari/napari/pull/869 for discussion.
(sorry, I should have linked that the first time... couldn't find it at first!)

**Comment by tlambert03** [comment]
feel free to change any logic you need, the main _behavior_ we were after is:
1. If the layer control is docked (has a parent), then it should be shown relative to the parent window.
2. if the layer control is undocked, it should be shown relative to the undocked window.
3. it should always be some minimum width (650 here), even if the parent window is narrower.
4. if a (narrow) undocked control panel is close enough to the edge of the screen such that centering the popup on parent would make some of the widget go off the screen, then it should be pinned to the edge of the screen.
