### ISSUE TITLE
Double click for layer control

### ISSUE THREAD

**Issue by Svidro** [napari/napari#1338]
## 🚀 Feature
To make handling large numbers of layers a bit quicker through the GUI, it would be nice if double clicking on a single layer's "eye" caused all other layers to be "off." Similarly, if you then double click on the eye again, it would turn all other layers back on (if all other layers are off). May or may not want some logic to check "are all other layers off," since I could see either a "toggle all other layers" or "all off" vs "all on" when double clicking.

## Motivation

Improve handling of visualization of layers in the GUI.

## Pitch

Implementation of double clicking for more layer visualization control.

**Comment by kevinyamauchi** [comment]
Thanks for the feature request @Svidro ! I think this could be a good idea. This may have been what you were getting at at the end of your description, but say we have multiple layers and some of them are set visible and others are not. We double click a layer to make it the only one visible. When you double click it again, should all layers now be visible or should it go back to the initial state (i.e., remember which layers were visible and not visible)?

**Comment by Svidro** [comment]
I wasn't really sure, so I left it a bit open. If you wanted to go all out...
I'd say have the double click toggle all non-double clicked layers.
Would it be possible to shift+mouseclick and/or CTRL+mouseclick to select multiple layers and press spacebar or enter to toggle selected layers? Not sure if I'm going off into crazyland since I have 0 experience with Python GUIs.

**Comment by kevinyamauchi** [comment]
Thanks for the quick feedback!

One think you can do for now is select the layers you want to toggle (shift + click to select a range and ctrl/cmd + click to select specific layers - same as most file browsers) and then press the `v` key to toggle.

**Comment by Svidro** [comment]
Oh, ok, as long as that is possible, I'd say just toggle everything off or on based on the double click. That's the quickest way to select a single channel, or turn them all back on.

**Comment by psobolewskiPhD** [comment]
While it doesn't use double-click, I think https://github.com/napari/napari/pull/5618 which uses alt-click (mimics photoshop) instead closes this issue. Plus, it has logic to store and restore the layer state.
Just need 0.5.0 for it to be released!
