### ISSUE TITLE
pip install napari[all] failing on Windows 10/py3.8 due to pip install vispy failure

### ISSUE THREAD

**Issue by AndrewGYork** [napari/napari#1340]
## To Reproduce

1. Install python 3.8 from python.org on a fresh Windows 10 PC
2. pip install napari[all]
3. Installation of vispy (and therefore napari) fails due to this issue:
https://www.reddit.com/r/Python/comments/f1tt4h/noob_cant_install_vispy_using_pip/fh8j2wp/

> The problem is that PyPI does not yet have a pre-built package for vispy (a "wheel") that matches your installation: https://pypi.org/project/vispy/#files. It only has versions up to Python 3.7 (vispy-0.6.4-cp37-cp37m-win32.whl).

The resulting error message contains enough information to fix the problem: 

> error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/

...but it's surrounded by a huge amount of other error messages, and easy to miss. Also, the "build tools" are a multi-GB download, and the resulting installation has many options, only a few of which are helpful/relevant.

I'm guessing most napari devs already have msvc build tools on their machine, or don't use Windows, so the issue might not crop up.

I'm not sure what the right fix is. Fix pip install vispy on py3.8/Windows? Try to make the resulting error message harder to misunderstand? Document the (potential) problem in the installation tutorial?

## Expected behavior

To install napari

## Environment

Fresh install of python 3.8 on fresh install of Windows 10.

## Additional context

Hope this was useful/appropriate. Thanks as always for napari, keep up the good work!

**Comment by tlambert03** [comment]
someone else just mentioned this to me this morning... they also didn't have the build tools required for vispy on windows (which I'm sure is going to be relatively common!).
I would love to be able to show a nicer error message, but since that's basically pip failing to install vispy, I don't think we can really modify that...

For what it's worth, that person who tried it earlier _was_ able to install with `conda install napari` ... (since vispy does provide [win64-py38 binaries on conda](https://anaconda.org/conda-forge/vispy/files))... and @djhoese said [here](https://github.com/vispy/vispy/issues/1856#issuecomment-623189473) that py38 wheels will be coming for vispy 0.7... so this will eventually go away.

for now, it's either install with conda ... or (and we'll see whether this comes before vispy ships py38 wheels 😄) use a bundled napari app #1289.

**Comment by AndrewGYork** [comment]
Yeah, that makes sense. Is it worth noting the issue in the installation tutorial in the meantime? I guess at the very least, this issue might show up in relevant Google searches :-)

**Comment by AndrewGYork** [comment]
Would it be helpful if I wrote a pull request for the installation tutorial, or better to leave it as is?

**Comment by djhoese** [comment]
Thanks for pointing out the vispy wheel issue. I hope to get working on a vispy release soon but underestimated how much needed to be done around my house before my paternity leave starts in a week :fearful:

Sorry for the delay. Hopefully with the CZI funding for VisPy we can get more maintainers in place for vispy so releases won't depend on my available time (napari team, let me know if you're interested).

**Comment by tlambert03** [comment]
no problems at all @djhoese!  certainly wasn't trying to rush you.  The conda workaround is available, so no one is blocked! 

@AndrewGYork, I think I'll leave the decision as to whether that should be put in the readme/tutorials to @sofroniewn

**Comment by sofroniewn** [comment]
We should probably add a "known issues" or "troubleshooting" section to our installation guide, can go just above bug reporting here https://github.com/napari/tutorials/blob/master/fundamentals/installation.md#bug-reports and then include some minimal information plus a link to the relevant issues so people can quickly see where to look next

@AndrewGYork if you'd like to add that then and link to this issue, then I think that makes sense. 

@tlambert03 could also be a good place to address this https://forum.image.sc/t/running-napari-from-a-jupyter-notebook-on-a-remote-host/38599/3?u=sofroniewn and make very clear about remote jupyter installation too

**Comment by sofroniewn** [comment]
These additional windows installation details were added by @ziyangczi in #1758. This can now be closed, but people should feel free to continue to improve the installation instructions as needed. Thanks!!
