### ISSUE TITLE
Perfmon: SystemError on exit with perfmon and PyQt5

### ISSUE THREAD

**Issue by pwinston** [napari/napari#1349]
## 🐛 Bug

When using perfmon and PyQt5 there are errors on exit. There are no errors with PySide2.

## To Reproduce

Using PyQt5 run napari from command line with NAPARI_PERFMON=1 and exit. Console has these messages:

```
WARNING: StopIteration

The above exception was the direct cause of the following exception:

SystemError: <class 'PyQt5.QtWidgets.QWidget'> returned a result with an error set
09:08:04 WARNING StopIteration

The above exception was the direct cause of the following exception:

SystemError: <class 'PyQt5.QtWidgets.QWidget'> returned a result with an error set
[1]    87987 abort      nap.py small
/Users/pbw/miniconda3/envs/new-base/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 3 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

## Expected behavior

Napari should exit cleanly and normally even when running with NAPARI_PERFMON=1.

## Additional context

We merged #1262 knowing about this bug. Perfmon is an internal tool and is useful despite these errors, but we should fix this. It looks  bad and it might mean we are doing something wrong that could have other consequences.

@tlambert03 found a [warning about overrding notify() in the C++ Qt docs](https://doc.qt.io/qt-5/qcoreapplication.html#notify):

> Warning: If you override this function, you must ensure all threads that
> process events stop doing so before your application object begins destruction.
> This includes threads started by other libraries that you may be using, but does
> not apply to Qt's own threads.

For perfmon we do have our own `QApplicationWithTiming` that overrides `notify`. There are ~20 other threads running and don't know where they are from or what they are doing. But we have no reason to believe they are "processing Qt events".

## Possible Solutions

1. Stop other threads before our QApplicationWithTiming is deleted.
2. Find a way to time Qt Events without overriding `notify()`.
3. Intervene during exit and shut things down differently (harsher?) if using perfmon.

Other ideas?

****

**Comment by sofroniewn** [comment]
Just looking back over some old bugs @pwinston - any chance this is related to what you're digging into in #1811. I know it's about perfmon but the following caught my eye

> When using perfmon and PyQt5 there are errors on exit. There are no errors with PySide2.

**Comment by pwinston** [comment]
Possibly related yeah. But hard to say.

The fix for #1811 might directly fix other problems. Or just as helpfully the fix might teach us something about proper Qt/Vispy usage that we can apply to other situations. But just don't know.

**Comment by psobolewskiPhD** [comment]
I can't reproduce with conda-forge napari 0.4.18 and pyqt 5.15.9
I do get a Warning:
```
/Users/piotrsobolewski/Dev/miniforge3/envs/napari-418/lib/python3.10/site-packages/napari/_qt/qt_main_window.py:543: UserWarning: Using NAPARI_PERFMON with an already-running QtApp (--gui qt?) is not supported.
  qapp = get_app()
```
Which is a bit odd, because I am launching as required by the PR that implemented that warning:
https://github.com/napari/napari/pull/3171
But everything seems to work fine.

**Comment by jni** [comment]
I think we can probably close this, open again if anyone complains. Thanks for trawling through these old issues @psobolewskiPhD! 🙏
