### ISSUE TITLE
Layers Marker should not depend on image layers and their bounds

### ISSUE THREAD

**Issue by royerloic** [napari/napari#135]
## 🐛 Bug

Right now, when adding markers layers to a viewer that does not
have image layers, the markers layer gets initialised with some bounding box.
Adding markers interactively leads to some arbitrary 'clipping' to some
bounding box (not clear where it comes from).
This prevents marker layers to exist independently from images, which
is probably not ideal. One way to think about it is that there is one coordinate
system and layers can be laid up in that space. Markers should be able to
be placed at arbitrary positions in that space, independently of other layers.

This is probbaly why there are some exceptions when removing all images
from a viewer and then adding a markers layer (with the + button).

It might still be usefull to 'clip' one layer based on another.
But this should be done explicitely, as this establishes a link between
two layers, something that is not desirable by default.

Possible syntax:

`
image_layer = viewer.add_image(....)
markers_layer = viewer.add_markers(....)
markers_layer.add_clip(image_layer)
`

Incidentally, it would be usefull to define an optional bounding box per layer,
in that case, the above code would simply take the bounding box for the
image layer and set it for the markers layer. A more explicit syntax could then
also be:

`
image_layer = viewer.add_image(....)
markers_layer = viewer.add_markers(....)
markers_layer.bounds = image_layer.bounds
`
Images have well defined bounding box by default,
layers don't. Unless, you explicitly give a bounding box to
a markers layer. If you provide a bounding box to a layer,
this prevents from adding markers outside of the bounds
in interactive mode, and possibly also when providing the
coordinates directly.

## Environment

 - napari-gui Version (e.g., 1.0): master
 - OS (e.g., Linux): OSX
 - Python version: 3.7
 - Any other relevant information: None

## Additional context

None

**Comment by sofroniewn** [comment]
Thanks for flagging. These problems are somewhat opaquely referenced in #91. I don't like the explicit "add_clip" but I think there are ways to achieve this functionality with input arguments to markers, and we should remove the weird coupling that you noted. The main problem right now is that every layer is required to have a shape, but if you have no markers present then what does your shape default to? Maybe [0, 0]? But we just need to make sure that it all works fine. I can make a new PR to address this.

**Comment by sofroniewn** [comment]
This has now been resolved with #249. The markers layer no longer does any clipping and does not depend on the image layer in any way. The shape of the markers layer is now calculated based on the markers inside the layer.
