### ISSUE TITLE
Bring back keyboard shortcut for Fullscreen mode

### ISSUE THREAD

**Issue by royerloic** [napari/napari#136]
## 🚀 Feature

Bring back keyboard shortcut for Fullscreen mode.
Press 'F' and you enter fullscreen. 'ESC' or 'F' again to leave fullscreen.

## Motivation

It's the best feature. So good. 

## Pitch

I just explained that this is the best feature.
People tell me they love this feature --  it is true.

## Alternatives

None. 

## Additional context

Fullscreen is all there is to see.

**Comment by sofroniewn** [comment]
Ah I had not realized this had disappeared but I will look into it (I have an idea why). Maybe it's also time to add ctrl+W, ctrl+Q to close / quit? Need to think about where these live. Do they go on window or do the go on viewer or do they live somewhere else? My thoughts are on Window right now.

**Comment by jni** [comment]
I think it disappeared in a very early refactor. I agree that shortcuts should go on the window, (w in ctrl-w is for window), but f is possibly for the viewer.

**Comment by sofroniewn** [comment]
fixed by #472
