### ISSUE TITLE
Security on GitHub

### ISSUE THREAD

**Issue by jni** [napari/napari#137]
We all like the idea of GitHub repositories as plugins. However, GitHub has a dramatic security flaw, which is that deleted usernames can immediately be reclaimed by anyone on the internet. (!) This means that if a developer of a trusted plugin closes their account, there is nothing to stop someone from replacing the plugin with the plugin + a bitcoin mining bot, or worse.

None of us are security experts at the moment but this is a big hole, and I wonder if there is anything significant to be done here to address this. (e.g. is there some metadata accessible in the GitHub API that would make this attack not work?)

https://www.theregister.co.uk/2018/02/10/github_account_name_reuse/

**Comment by AhmetCanSolak** [comment]
I do not think usernames are the only unique identifiers to authenticate people. Here what github user APIv3 returns:
```json
{
  "login": "octocat",
  "id": 1,
  "node_id": "MDQ6VXNlcjE=",
  "avatar_url": "https://github.com/images/error/octocat_happy.gif",
  "gravatar_id": "",
  "url": "https://api.github.com/users/octocat",
  "html_url": "https://github.com/octocat",
  "followers_url": "https://api.github.com/users/octocat/followers",
  "following_url": "https://api.github.com/users/octocat/following{/other_user}",
  "gists_url": "https://api.github.com/users/octocat/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/octocat/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/octocat/subscriptions",
  "organizations_url": "https://api.github.com/users/octocat/orgs",
  "repos_url": "https://api.github.com/users/octocat/repos",
  "events_url": "https://api.github.com/users/octocat/events{/privacy}",
  "received_events_url": "https://api.github.com/users/octocat/received_events",
  "type": "User",
  "site_admin": false,
  "name": "monalisa octocat",
  "company": "GitHub",
  "blog": "https://github.com/blog",
  "location": "San Francisco",
  "email": "octocat@github.com",
  "hireable": false,
  "bio": "There once was...",
  "public_repos": 2,
  "public_gists": 1,
  "followers": 20,
  "following": 0,
  "created_at": "2008-01-14T04:33:35Z",
  "updated_at": "2008-01-14T04:33:35Z"
}
```
As far as i know id field is unique per user. Maybe node_id field as well, don't know needs check. email field also worth to look at. I think for their own business interest they must been addressed this issue already.

**Comment by jni** [comment]
> I think the concern here is delivering the best quality software we can in terms of security.

Exactly. I am not a security researcher so I know I can't make Napari bulletproof, but I can still take care and try to avoid super-stupid stuff.

> That still does not cover the case in which an install is done from scratch (unless you want to include a lock file).

We could have some sort of online listing for this. Like haveibeenpwnd for github repos. =P

**Comment by neuromusic** [comment]
> Might be nice to present plugins in a marketplace where users can check the details.

@AhmetCanSolak +1

**Comment by goanpeca** [comment]
With all the work taking place in napari-hub, is this still a concern @jni?

**Comment by jni** [comment]
I had to do a double take on that issue number @goanpeca! 😂

Anyway, the answer is I don't know. Perhaps the issue should be transferred to that repo.

**Comment by neuromusic** [comment]
Its worth noting that the napari community has refined its thinking on plugin distribution significantly in the 2+ years since this issue was created and PyPI is now the preferred means of plugin distribution.

Because of this decision by the napari community, the napari hub relies on pypi for the actual plugin and only looks to github for supplemental metadata, so I don't think specific concern is a risk for us any time soon.

Any major change to this distribution architecture for the napari hub (such as indexing and sourcing plugins from Github directly in addition to PyPI) would necessitate that our team goes through an internal legal and security review, where this risk could be surfaced.

**Comment by neuromusic** [comment]
Which is to say... I think its safe to close this issue and creating a new issue on the hub repo is not necessary
