### ISSUE TITLE
layerlist doesn't always behave like a list, not always synced with viewer

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#1380]
## 🐛 Bug
our `LayerList` inherits from python List, and has various methods (append, pop, etc...) that are list like, but not all list methods work in synchrony with the viewer:

```python
In [3]:viewer.layers.clear()

In [4]:viewer.layers
Out[4]: []
# but all the layers are still in the viewer
```

I feel like I've seen others in the past, but can't remember at the moment.

## Expected behavior

LayerList methods should propagate to the current layers in the viewer.  and viewer.layers should always match what's in the viewer.

**Comment by sofroniewn** [comment]
I think this comes down to the events not emitting as expected. We use the `added`, `removed`, `reordered` events in the `qt_layerlist` here https://github.com/napari/napari/blob/master/napari/_qt/qt_layerlist.py#L64-L66 and the `qt_viewer` here https://github.com/napari/napari/blob/master/napari/_qt/qt_viewer.py#L185-L187 and the  `changed` event in the `viewer_model` here https://github.com/napari/napari/blob/master/napari/components/viewer_model.py#L87-L89.

My guess is that the event emission isn't happening as expected for all methods and that is what is causing problems. (i.e. if we test all the events always emit right then we should be ok).

There was another layer list bug and to do list while back in #312 which still needs to be addressed.

**Comment by tlambert03** [comment]
thanks @sofroniewn, makes sense.  Since the main thing I was trying to do is clear the viewer, I'll add a couple more potential "gotchas" in case anyone finds this.  These are related to problems with iterating through a list that you are altering:

doesn't work:
```python
for layer in viewer.layers:
    viewer.layers.remove(layer)
```
```pytb
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    for layer in viewer.layers:
  File "/napari/napari/utils/list/_base.py", line 25, in __iter__
    yield self[i]
  File "/napari/napari/utils/list/_base.py", line 28, in __getitem__
    indices = self.__prsitem__(key)
  File "/napari/napari/utils/list/_multi.py", line 11, in __prsitem__
    return super().__prsitem__(keys)
  File "/napari/napari/utils/list/_base.py", line 80, in __prsitem__
    return self.__locitem__(key)
  File "/napari/napari/utils/list/_typed.py", line 37, in __locitem__
    return super().__locitem__(key)
  File "/napari/napari/utils/list/_base.py", line 111, in __locitem__
    raise IndexError(
IndexError: expected index to be in [0, 1); got 2
```

but this does:
```python
for layer in list(viewer.layers):
    viewer.layers.remove(layer)
```

this also works:
```python
    for i in range(len(viewer.layers)):
        viewer.layers.pop(0)
```

but this doesn't:
```python
    for i, l in enumerate(viewer.layers):
        viewer.layers.pop(0)
```

what is your "go to" approach for clearing the viewer?  Or is it not something you do much?

**Comment by sofroniewn** [comment]
> what is your "go to" approach for clearing the viewer? Or is it not something you do much?

I use one of our "custom methods" as I know it works, maybe because I had problems like you did in the past, but this is maybe not the best

```python
viewer.layers.select_all()
viewer.layers.remove_selected()
```

**Comment by sofroniewn** [comment]
Now that #1504 is closed I am closing this as the `clear` works as expected. We've still got some other problems related to the append method and adding/ removing layers, see #1846 and #1850, but they can be tracked over there and use the new list object
