### ISSUE TITLE
Create a napari-tifffile plugin

### ISSUE THREAD

**Issue by jni** [napari/napari#1384]
## 🚀 Feature

For a brief, glorious moment, there was a napari IO plugin baked into tifffile. It has since been pulled out. It would be nice to make an independent plugin that would read tiff metadata into napari.

The code for the pulled out implementation is available here:

https://github.com/cgohlke/tifffile/commit/3998ad576cfbb05c1d5a2a4c1cd1d77536669c74?diff=unified

Hooray for git!

**Comment by GenevieveBuckley** [comment]
Wonder why that glorious moment was so brief? I've made a start [here](https://github.com/GenevieveBuckley/napari-tifffile), still need to add tests and a few other things...

**Comment by jni** [comment]
> Wonder why that glorious moment was so brief?

Well, it turned out to break our tests, which was fun, and I expect Christoph did not want to take on the maintenance burden. Very exciting that you've started it!

**Comment by GenevieveBuckley** [comment]
Wait, how did it break *your* tests?

**Comment by jni** [comment]
Because we autodiscover plugins and we depend on tifffile, so now instead of "plainly" opening tiffs, metadata was getting added and changing how the viewer ended up.

**Comment by GenevieveBuckley** [comment]
I'm running into problems trying to upload a release candidate to PyPI - it's giving me the same error as if the `napari-tifffile` project name has already been claimed (even though searching for `napari-tifffile` on PyPI turns up zero exact matches). See [the github actions log for the failed deployment here](https://github.com/GenevieveBuckley/napari-tifffile/runs/810686481?check_suite_focus=true).

@kne42 is it possibly related to the early start you made on a napari-tifffile plugin here: https://github.com/kne42/napari-tifffile
I'm very happy to transfer ownership of the repo across to you if we need, that's fine by me.

**Comment by Czaki** [comment]
some handling metadata also for oif and czi file (using other cgholke packages) can be found here https://github.com/4DNucleome/PartSeg/blob/develop/package/PartSegImage/image_reader.py (when writing this I mainly test it on confocal microscopy images) 

This what I see at first is that current code does not check units in scale. And napari does not work well with samm values (eg 210 nm as 210*10**-9). Also imgeJ may use different units in z and XY (different tags) 

Second thing, how napari will handle colormaps passed as arrays not name?

And I'm not sure if it reads TIFF-OME metadata (my code read it partially)

There are still plenty of TIFF metadata format for which I do not have examples so I do not know how to handle its.

**Comment by jni** [comment]
> Second thing, how napari will handle colormaps passed as arrays not name?

You can see how ome-zarr does it here:

https://github.com/ome/ome-zarr-py/blob/5a937f844d5c7548e93c3e1e683d1ac85464033d/ome_zarr.py#L105-L117

The only thing is that they are not named. But you *can* pass in a (name, Colormap) tuple. 

> There are still plenty of TIFF metadata format for which I do not have examples so I do not know how to handle its.

Absolutely. We would aim for progressive support here, covering examples as they get requested.

**Comment by Czaki** [comment]
> You can see how ome-zarr does it here:

Thanks, I do not expected that GUI handle also not named colormaps. This is nice feature. 



> Absolutely. We would aim for progressive support here, covering examples as they get requested.

I can support with reading metadata from OME-TIFF

**Comment by GenevieveBuckley** [comment]
Rather than try and work out why the naming was a problem, I've just renamed it & that seems to have helped: https://pypi.org/project/napari-tifffile-reader/

**Comment by nvladimus** [comment]
I tried the `napari-tifffile-reader` plugin, it works great. Correctly parses channels and voxel dimensions, a must-have! Many thanks!

**Comment by GenevieveBuckley** [comment]
Glad to hear that @nvladimus 
And if you work with (or are interested in) pyramidal OME-TIFFs, there's a good first issue for that here https://github.com/GenevieveBuckley/napari-tifffile-reader/issues/9
