### ISSUE TITLE
Idea: use namespace packages in conjunction with plugins

### ISSUE THREAD

**Issue by kne42** [napari/napari#139]
# Introduction
As discussed in our last meeting, [namespace packages](https://packaging.python.org/guides/packaging-namespace-packages/) could be a handy way to ship useful core modules separately for use as standalone packages. This could be extended to all plugins that could be useful outside of the broader Napari ecosystem, such as [`napari-gui`](https://github.com/Napari/napari-gui).

This would provide consistency in `import` statements regardless of how a plugin is installed, as well as allow `pip`-installable plugins to once again reference themselves in absolute imports instead of requiring all imports to be relative.

## What are namespace packages?
Namespace packages are best explained by a simple use-case. Imagine two packages `foo.a` and `foo.b`. `foo.a` and `foo.b` are independent and can be shipped separately. In this case, `foo` would be considered a namespace package. To achieve this, we have the following structure:

```
pkg-foo-a/
    foo/
        a/
            __init__.py
            ...
pkg-foo-b/
    foo/
        b/
            __init__.py
            ...
```

These are known as implicit namespace packages and they were introduced in [PEP 420](https://www.python.org/dev/peps/pep-0420/) (available in Python 3.3+).

In Python <3.3, namespace packages were created using the `pkgutil.extend_path` function under each namespace's `__init__.py`:
```python
# foo/__init__.py
__path__ = __import__('pkgutil').extend_path(__path__, __name__)
```

**`pkgutil`-style namespace packages** shall henceforth be referred to as **pseudo-namespace packages**.

# Proposal
Implementation of this structure would require two main changes:
- all plugins will fall under the top-level `napari` namespace (as @freeman-lab suggested)
- the [plugin import inception setup](https://github.com/Napari/napari-core/blob/b7e07813322e68cc49a5c5e4cf53dee599fbb792/napari/plugins/__init__.py) will be moved to `napari/__init__/py`

## Refactoring existing plugins
Plugins will no longer be importable under `napari.plugins.<name>` but under `napari.<name>` itself. If installed from `pip`, it will also be importable under `napari.<name>`.

For example, the `napari-gui` repository structure will look like so:
```
napari-gui/
    napari.yml
    napari/
        gui/
            __init__.py
            ...
    ...
```

Its specification will change to:
```
# napari.yml
plugin_info:
  plugin_name: gui
  path: napari/gui/__init__.py
  ...
...
```

Plugins using `setuptools.find_packages()` in their `setup.py`s will find that it no longer works. This can be fixed with a simple list comprehension:
```python
# setup.py
from setuptools import setup, find_packages

setup(
    name='napari-<name>',
    ...
    packages=[f'napari.{pkg}' for pkg in find_packages('napari')]
)
```

Plugins that do not need to be served as independent `pip` packages should not place their code under a `napari/<name>` directory.

## Implementation
Only a few functions need to be changed, such as `napari/plugins/machinery/_load:get_plugin_namespace`.

The contents of `napari/plugins/__init__.py` will be moved to `napari/__init__.py` **for use with the `plugins` package only**. It will be a pseudo-namespace package, but will only work if **no other namespace package specifies `napari/__init__.py`**:

```python
# napari/__init__.py
import sys
import pkgutil


class NapariPluginImporter:
    """MetaPathFinder for Napari plugin imports."""
    @classmethod
    def find_spec(cls, fullname, path=None, target=None):
        ...


sys.meta_path.append(NapariPluginImporter)
__path__ = pkgutil.extend_path(__path__, __name__)
del sys, pkgutil
```

Whether `pip`-installed versions or plugin-installed versions have priority is a matter of inserting the importer into the end or the beginning of `sys.meta_path`, respectfully.

According to the [PEP 420 specification](https://www.python.org/dev/peps/pep-0420/#specification):
> While looking for a module or package named "foo", for each
> directory in the parent path:
> 
> * If ``<directory>/foo/__init__.py`` is found, a regular package is
>   imported and returned.
> 
> * If not, but ``<directory>/foo.{py,pyc,so,pyd}`` is found, a module
>   is imported and returned.  The exact list of extension varies by
>   platform and whether the -O flag is specified.  The list here is
>   representative.
> 
> * If not, but ``<directory>/foo`` is found and is a directory, it is
>   recorded and the scan continues with the next directory in the
>   parent path.
> 
> * Otherwise the scan continues with the next directory in the parent
>   path.
> 
> If the scan completes without returning a module or package, and at least one directory was recorded, then a namespace package is created. 

This means that if an implicit namespace package is found during the scan before a normal package, the import system will not opt to automatically create the namespace package, but will continue iterating through all candidates until it encounters a valid package, otherwise finally creating the namespace package.

Due to this, implicit namespace packages will never be created if a pseudo-namespace package (which is considered as a normal package by the import system) is present. The code within the package extending its path will be executed, acting it to behave as a namespace package.

Within the import system, parent packages are resolved and executed before child packages. For example, in the statement `import foo.bar`, first `foo` will be resolved and executed, then `bar` will be resolved and executed.

Therefore the plugin core's `napari/__init__.py` will always be executed before subpackages are loaded, allowing it to load all plugin and `pip`-installed packages.

# Limitations
1. no other namespace package may define `napari/__init__.py`
2. due to this implementation, [dynamic path computation](https://www.python.org/dev/peps/pep-0420/#id3) will [no longer be available](https://www.python.org/dev/peps/pep-0420/#migrating-from-legacy-namespace-packages)

(1) can be resolved if other namespace packages insert similar code in their `napari/__init__.py`

(2) can be resolved by copying the functionality introduced in the `importlib` standard library, which provides a special `_NamespacePath` class that provides this feature

**Comment by AhmetCanSolak** [comment]
I like namespaces. I support in general for `napari` environment. However, second limitation is an important one. If we do not implement a solution to that there will be several issues on Windows.

**Comment by goanpeca** [comment]
It seems this will no longer be pursued? Could we close it @sofroniewn, @kne42 ?

**Comment by sofroniewn** [comment]
Yes, we can close this as we won't be following this approach
