### ISSUE TITLE
Default value for attenuation in attenuated-MIP rendering should be lower

### ISSUE THREAD

**Issue by jni** [napari/napari#1392]
## 🐛 Bug

I'm not sure if it's my data or a general feature, but I have always found that the attenuation value for 3D rendering is way too high for most volumes I look at. I invariably end up reducing it to just above the minimum value of the slider. So we should probably revisit that default value.

**Comment by sofroniewn** [comment]
Interesting, might be good to think why that is/ if more normalization is needed or if the value is just too high!

**Comment by AdvancedImagingUTSW** [comment]
The fix worked beautifully!  As you know, I used an attenuation value of .04 for this dataset.  However, I'm going to test a couple of different datasets out with the attenuated MIP setting and I'll get back to you as soon as possible on the range of values I find useful.  Thanks again, I really appreciate your work and I think you are building the foundation of something potentially transformative.  

Best,
Kevin

<img width="1002" alt="image" src="https://user-images.githubusercontent.com/42547789/87490975-98948980-c60c-11ea-98b8-425d4a7a4a25.png">

**Comment by tlambert03** [comment]
a while back we had (on slack) talked about, and rejected using a nonlinear $cmap function in the shader.... pasting that code here again in case we want to play with it:

```python
ATTENUATED_MIP_SNIPPETS = dict(
    before_loop="""
        float maxval = -99999.0; // The maximum encountered value
        float minval = 99999.0; // The minimum encountered value
        float sumval = 0.0; // The sum of the encountered values
        float scaled = 0.0; // The scaled value
        int maxi = 0;  // Where the maximum value was encountered
        vec3 maxloc = vec3(0.0);  // Location where the maximum value was encountered
        """,
    in_loop="""
        sumval = sumval + val;
        scaled = val * exp(-u_threshold * sumval / u_relative_step_size);
        if( scaled > maxval ) {
            maxval = scaled;
            maxi = iter;
            maxloc = loc;
        }
        if( val < minval ) {
            minval = val;
        }
        """,
    after_loop="""
        gl_FragColor = $cmap((maxval - minval) * (1 + pow(u_threshold, .5)));
        """,
)
```

**Comment by sofroniewn** [comment]
Linking to this comment with great images, examples https://github.com/napari/napari/issues/1399#issuecomment-658866839

Seems like values there are 0.02, 0.06, 0.04.

How about we bring the slider range down to `(0, 0.2)` with a default of `0.1`. I can do that now
