### ISSUE TITLE
Attenuated MIP Initialization Error

### ISSUE THREAD

**Issue by AdvancedImagingUTSW** [napari/napari#1399]
## 🐛 Bug

The viewer is not programmatically updating the attenuation value for an 'attenuated_mip' rendering.  
Full discussion can be found here: https://forum.image.sc/t/attenuated-mip-refresh/39884/9

## To Reproduce

1.  Launch a simple script with a 3D image.
2. Try various attenuation values.
3. In general, it seems as if it is automatically showing an attenuation value of 0 regardless of what I provide in the viewer.add_image function.

`
import napari
import numpy as np
from tifffile import imread
import os

data_location = '/archive/bioinformatics/Danuser_lab/Fiolka/MicroscopeDevelopment/OPM/Drosophila/GAP43-mcherry/200703/Cell1'
membrane = imread(os.path.join(data_location, f'1_CH00_{1:06}.tif'))
membrane = np.array(membrane)

with napari.gui_qt():
    viewer = napari.Viewer(ndisplay=3)
    layer = viewer.add_image(data=membrane, rendering='attenuated_mip', attenuation=1)
`

## Expected behavior
I would expect the attenuation value, which is accurately reflected in the slider position to also be shown in the image.  

## Environment

 napari: 0.3.6.dev11+ge43f730
Platform: Linux-3.10.0-957.el7.x86_64-x86_64-with-redhat-7.6-Maipo
Python: 3.6.10 | packaged by conda-forge | (default, Apr 24 2020, 16:44:11) [GCC 7.3.0]
Qt: 5.14.2
PyQt5: 5.14.2
NumPy: 1.18.4
SciPy: 1.4.1
Dask: 2.17.2
VisPy: 0.6.4

GL version: 2.1 Mesa 18.3.4
MAX_TEXTURE_SIZE: 8192

Plugins:

napari-plugin-engine: 0.1.5
napari_volume
svg: 0.1.3

 - Linux OS

## Additional context
Nicholas Sofroniew identified the problem: 
...it comes from this line in vispy https://github.com/vispy/vispy/blob/caed4f0326dc9c0804b254339c4d89f66e6a01b6/vispy/visuals/volume.py#L598 and the fact that on startup the u_threshold is not in the shared_program. It seems to get added once things have appeared on screen, hence why things only start working when you move a slider.

I need to think about the best fix. It would be nice to fix on the vispy side, though presumably they had that line there for a reason. If we bypass that line by doing

self.node._threshold = float(attenuation)
self.node.shared_program['u_threshold'] = self.node._threshold
self.node.update()
ourselves inside here https://github.com/napari/napari/blob/e43f730170aab1e011c42060c65ba44133f6f18f/napari/_vispy/vispy_image_layer.py#L225 then it works fine. Curious what @talley thinks we should do. We can probably move this convo to github as it’s a pretty clear bug at this point.

**Comment by AdvancedImagingUTSW** [comment]
@sofroniewn - I see that you have a pull request that will close this bug.  Any chance I would be able to test it out?  Thank you, Kevin.

**Comment by sofroniewn** [comment]
Hi @AdvancedImagingUTSW, yes if you could test out #1454 that would be great!! I left another question in there for you asking about range of values/ default value for the attenuation parameter. Would love to hear feedback on that.

[Note that #1403 was an out of date approach to fixing so no need to test that one]

Thanks!!

**Comment by sofroniewn** [comment]
@AdvancedImagingUTSW this fix has now been merged into master so you can test it there, do let us know about if it works on not (can just comment on this issue even though it is closed).

Also feel free to weigh in on #1392 about recommended default values/ range!! Thanks!!

**Comment by AdvancedImagingUTSW** [comment]
@sofroniewn and @jni,

I quickly tested a couple different datasets, from different types of microscopes.  

2/3-photon, attenuation value = 0.02
![image](https://user-images.githubusercontent.com/42547789/87568678-a6d5ba80-c68b-11ea-9a57-6ce00110367a.png)

Lower SNR ASLM, attenuation value = 0.02
![image](https://user-images.githubusercontent.com/42547789/87569291-822e1280-c68c-11ea-8d13-20ce216d8dde.png)

Higher SNR ctASLM, attenuation value = 0.06
![image](https://user-images.githubusercontent.com/42547789/87570661-94a94b80-c68e-11ea-8e9d-2387ab275cda.png)

So, it looks like I am really hovering near the lower attenuation values.  Hope that helps.

Best,
Kevin
