### ISSUE TITLE
2+2+1 Major usage modes for Napari

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#141]
## Description
Based on conversations / discussions on other issues and PRs (like https://github.com/Napari/napari-gui/pull/126) I wanted to create an issue with some of the major potential usage modes of napari. These ideas are very much up for further debate and we might end-up somewhere quite far from this initial post.

1. Use napari viewer and napari plugins from jupyter notebooks or python scripts. These users are likely to be relatively proficient in python, understand the basics of python module imports, dependency management. These users might develop their own plugins. They want to be able to do things like  `from napari.gui import Viewer` and `from napari.plugins import ExamplePlugin` or just `import ExamplePlugin` and run `viewer.add_plugin(ExamplePlugin())` to just add this plugin to the viewer - though see https://github.com/Napari/napari-gui/pull/126 for alternative approaches. The key value add for them in the notebook is being able to interactively do data analysis on images, getting annotations etc back from the viewer to the notebook and then update the viewer from the notebook. For these users flexibility, customizability, and conformation to the norms of python are key. I expect these users to be high-value users of Napari as they are likely to build Napari plugins and evangelize the ecosystem if they have a good experience and see value in it. 

2. Use the napari application. These users may have no experience with python and have no understanding of dependency management or versioning. They will open the napari application from a desktop application and then add images and plugins from the dropdown menu. Once a plugin has been installed into the application it will be permanently installed (until removed). They are able to run update scripts to ensure they have the latest versions of the viewer and plugins, but if things break they will have no recourse to fix them. For this use case we might need to consider things like sandboxing of plugins / resolving dependency conflicts etc to ensure the app is robust to "third party" plugins, but we'll also need to ensure performance and interactivity remains high. These users may ultimately represent the majority of Napari users if we achieve high-penetrance in communities doing lots of image analysis but with less python experience (such as biology), but I think we can focus our initial development on our first use case before biting off too large an engineering challenge prematurely.

3. These users are the same as in (1 - scripts / notebooks) - but now the datasets are remote, i.e. on big gpu machines or cloud computing environments for training ML models. This use case could be a major one for us and I think is a high priority to support. It might relate to how we think about sandboxing plugins for dependency management in the application use case or how we deal with slow plugins (i.e. with long computation times that we don't want to block the gui thread) in all use cases.

4. These users are the same as in (2 - fully managed application) - but they also have datasets that are remote and want to do things like train ML models. This use case could be more complex, but also valuable.

5. Use the napari viewer embedded in their own applications. These users are likely to be developers that are highly proficient in python / PyQt. Use cases for this include building highly custom domain specific that have a need for different views and interactivity not provided by the plugin ecosystem. For this usage people will do something like `from napari.gui import Viewer` and then pretty much be on their own to add the PyQt elements into their application. I see this as a relatively low priority use case for us to support, but that could change as we get a better sense of what people want.

**Comment by jni** [comment]
@sofroniewn All the use cases you describe are valuable imho. In terms of the order in which we should pursue them, I think you have them approximately in the right order, except for the last one, which should just "fall out" of nice API design, and the API refactor we are planning in #146.

Remote datasets should come after use cases 1 and 2 are addressed. They are related to delayed/out-of-core data support with dask arrays, and imho should be bolted on later, as they require a new extra caching layer on top of what we have now.

Finally, in all cases, let's not forget that we want Napari operations to be recorded as Python somehow. This is currently nowhere in the roadmap and I'm concerned that (a) it's going to be much harder than expected, and (b) we are making design decisions that will hinder that.

**Comment by sofroniewn** [comment]
Agreed on all fronts. I think you last comment may warrant a new major usage mode:

6. For both users 1 and users 2, after interactively developing an image analysis pipeline built using napari plugins through parameter tuning and visually inspecting results on a subset of images they want to then run that pipeline on an enormous number of images that may be stored locally or remotely without looking at the results until the whole thing is done.

We have often said "napari headless is just python" and I think that goal will be critical to ensuring that this workflow is supported. Looking forward to discussing more.

**Comment by royerloic** [comment]
Great, some comments:

1. I think this is a great usage mode, and we should support this long term. It fits nicely with the existing python ecosystem around jupyter, ipython, etc.. However, there is currently a major roadblock: many jupyter users use remotely served jupyter notebooks. Currently we can't open a local napari viewer and access data on a remote jupyter server. I discussed with @jni about a possible straightforward solution involving some basic RPC array slicing api possibly leveraging dask. I think this should be pretty high on the priority list, after the viewer has matured enough, but before we dwelve into the app itself.

2. This is one of the main, ultimate and desired goals, but it will take some time to get there. I agree that the key criteria here are: performance, ergonomics, extensibility, and overall great UI design. 

3. We have to distinguish between two main 'remote' use cases: being able to 'see' remote data, and being able to 'operate' on remote data. The first is much easier to achieve as the rpc only needs to view slice of arrays, in that case computation can continue happening on the notebook that is hosted on the remote machine. The second use case is more tricky, and might require a full fledged RPC for running any plugin remotely. One approach would be to be able to spawn a headless napari on a server, have its plugins synced, and then translate any local calls into remote calls. Data would be remote and thus we need efficient on-demand array slicing for visualisation as in the first use case.

4.  I see this as relying on the same underlying tech as 3 but offering it in a more user friendly way, fundamentally, the underlying machinery should be the same... 

5. This will be a very powerfull use case that will allow for example to design special purpose apps with a great image viewer. Something that is complementary to the main app and its plugin infrastructure.

**Comment by jni** [comment]
Regarding remote notebooks, I think this, again, can come much later. Napari's use case is a local viewer, and for remote notebooks you have all the in-notebook viewers such as ipyvolume. The point of remote notebooks is usually not needing to set up a local environment, so I think the overlap of "people running remote notebooks" and "people wanting to see ndarrays displayed on a local app" is small.

**Comment by sofroniewn** [comment]
Hmm, I'm not sure @jni that there won't be quite a lot of overlap between "remote notebooks" and "people wanting to see ndarrays displayed on a local app", for example I'm thinking about @batson at the biohub who is training neural nets on the office GPU box, but running a "remote notebook" on his laptop and wants to be able to browse through that data easily, and see updates from his model as it trains. Do if I have this right?

**Comment by jni** [comment]
Sure but I think that it is cleaner in this use case to open an HTML-based viewer within those notebooks than it is to e.g. get a URL/port combination from the notebook and open those in a local napari instance, *especially* if that instance isn't the standard application (ie if you need to point to a specific Python).

With an application you could create a special file type that you could associate with Napari at the OS level, and when you click on such a file in the browser the application opens. But before the app, I don't think this is clean or easy, especially compared to the web-based alternatives.

**Comment by royerloic** [comment]
@sofroniewn I would love that... I also use remote notebooks all the time...

**Comment by kevinyamauchi** [comment]
I think the list does a good job of encapsulating the common use cases! I have a few comments below.

- I think the initial focus should be on use case 1 (Napari + local jupyter notebooks/python scripts). I think focusing on one usage mode up front (while being careful not to make decisions that block other modes in the future) is important to concentrate effort and I think it helps make it clear to the community when/how to (initially) use Napari.
- I think use case 6 (Napari generates a script of the operations performed) should be high priority, as I think it is a very common usage pattern (this is roughly how I use Napari currently) and I agree with @jni about the potential difficulty of the recording feature.
- I'd like to add a +1 to supporting remote notebooks. I use remote notebooks regularly and plt.imshow() is pretty painful for anything more than 2D.
- I think a standalone application is a great goal, but I think it should be lower priority, as it comes with a lot of extra overhead (e.g., extra UI/UX, potential app store issues) and there is a ton of value to add to the community with a polished viewer + notebook/script usage mode.

**Comment by d-v-b** [comment]
To add some potential-user data (I work with large functional imaging datasets):

My ordinary usage would be a mix of modes 1 and 3: 
Currently, I work with very large spatiotemporal arrays exclusively with remote notebooks (i.e., the notebook server is on the compute cluster, and I access it via my laptop). Crucially, I start my notebook server in a remote desktop environment (NoMachine); gui apps created by my python session are displayed in the remote desktop, and NoMachine handles the (tricky) compression of the video stream. My actual code will look something like this, especially if I'm prototyping an analysis / visualization:

```python
# generate 1 - 100 GB result image
result_3d = run_big_computation(dataset, params)

# generate a viewer window in the (remote) desktop
viewer = visualize(result_3d)

# after I hand-draw some rois in the viewer window, I want the mean of the pixels in each roi
rois = [r.get_mean() for r in viewer.rois] 

# display the traces in the notebook, using matplotlib
plt.plot(rois)
...
```
I seriously doubt piping a huge result, or slices of the result, through the notebook server for local viz will be as performant as remote viz + the compression built into the remote desktop.

As for mode 2, I see a lot of people using FIJI / ICY to view images that have just been acquired from a microscope. Images / folders are drag + dropped into the app for quick quality-control. If you have a biological sample with a shelf-life measured in hours, you want to make decisions quickly about how to adjust your imaging. Drag + drop is pretty key here, because microscope software can generate long, ugly file/directory names that are very similar to each other and thus annoying to type out in the command line. For ordinary FIJI / ICY users, I would guess that a huge fraction of the data entering the software does so via a drag + drop interface.

**Comment by sofroniewn** [comment]
We've come a decent way since this initial discussion. We now have one main napari repo that will provide the main app the will be ultimately be installable with pyinstaller, meeting needs of both user type 1 and 2. We've also got other issues discussing remote access, which has been added to our `0.3` roadmap for users type 3 and 4, and we've also achieved some separation of out qt elements and model to enable some usage by a user of type 5.

**Comment by neuromusic** [comment]
I know this issue is closed, but...

One variant on "6" that we've seen with some starfish users: Sometimes a scientist wants the pipeline to be evaluated "lazily", with steps in the processing running as the data is available. Example: for an experimental design where there are multiple rounds of acquisition, they want to run the image processing for the first round immediately and inspect the results for QC, repeating that round at a later time if needed, then running the steps of the pipeline that need all of the rounds once they are available.

This is more of an issue with the design of an "off napari" workflow runner. You start running into UI challenges, as there is now a human "in the loop", deciding whether a given edge of the DAG should or should not proceed.
