### ISSUE TITLE
list installed plugins doesn't find all installed plugins

### ISSUE THREAD

**Issue by jni** [napari/napari#1413]
## 🐛 Bug

Clicking on plugins -> list installed plugins (a) lists napari-plugin-engine as a plugin, which is a bit weird, and (b) misses my installed *and* properly detected napari-sentinel-zip plugin, which I can verify is installed both by using it (`napari path/to/sentinel-data` works) and by opening the plugin sorter, where it appears.

<img width="1084" alt="Screen Shot 2020-07-09 at 7 12 27 pm" src="https://user-images.githubusercontent.com/492549/87021425-8d121e80-c218-11ea-80cf-f87259a16cc3.png">

<img width="1200" alt="Screen Shot 2020-07-09 at 7 12 41 pm" src="https://user-images.githubusercontent.com/492549/87021432-900d0f00-c218-11ea-88e8-582d77d0380d.png">

**Comment by tlambert03** [comment]
I think that’s all fixed in #1357 , which would replace the plugin list here

**Comment by tlambert03** [comment]
The sentinel zip plugin issue is related to the bug with delayed decorated functions being in the module... and will be fixed in the next release of npe

**Comment by sofroniewn** [comment]
This has been closed by #1357. Feel free to reopen @jni or make new issues if it has persisted

**Comment by jni** [comment]
fwiw @DragaDoncila and I seemed to observe this again with a user yesterday, but I can't reproduce locally, so let's leave this closed and reopen if we spot it again.

**Comment by DragaDoncila** [comment]
@jni wasn't our issue last night that the user hadn't actually installed the plugins?

**Comment by jni** [comment]
It's entirely possible that I got confused! You have the recording so you can check. :blush: But I thought ome_zarr *was* installed?

**Comment by DragaDoncila** [comment]
Good point lol. Just checked back and they didn't have the packages installed, so all good!
