### ISSUE TITLE
Allow scaling of font to accommodate hidpi systems

### ISSUE THREAD

**Issue by stefanv** [napari/napari#1417]
On my hidpi system, Napari's fonts are very small.

Ideally, one would be able to zoom the interface by typing, e.g., Ctrl-+, but that is not currently implemented.

As a start, I would like to ask whether we can replace absolute font-sizes (and perhaps other sizes) in the .qss files with relative sizes (`em` instead of `pt` or `px`).  With this in place, I'd only have to add a single specifier to `02_custom.qss` to increase app-wide font-size.

There is a note in `00_base.qss` already saying:

> might be possible to convert px to em by 1px = 0.0625em

but I'm not sure where that came from.

If you think this is a reasonable request, I can poke around and see if I can make it work.

**Comment by tlambert03** [comment]
Hi @stefanv!  Thanks for raising this.  a couple comments:

First, we learned & changed a couple things in #820 about high DPI scaling.  If you're creating the napari viewer from within an IPython session (having used `%gui qt` or `--gui qt`) rather than directly from the command line, then can you check which version of IPython you're on?  I made a PR to IPython (https://github.com/ipython/ipython/pull/12314) that should fix high DPI scaling when IPython has created the Qt app.  (I'm not quite sure how the IPython backports work... but it's something to check).  Napari >= 0.3.2 should scale well.

(All that said, it's possible that the high DPI scaling _is_ working, but you still just would like to be able to scale the fonts.  The full on ctrl +/- zooming would be amazing, but I suspect we've got a lot of work to do on our styles to be able to do that).

Second, I did play with this briefly [in a previous PR](https://github.com/napari/napari/pull/1017#issuecomment-593449227), and I think that's where the comment came from.  But it was left as an experiment for a later date.  If you can confirm that you're on either the newer IPython (or running a newer version of napari directly) it be awesome if you had time to play around with it!

**Comment by stefanv** [comment]
@tlambert03 Thanks for the quick response.  No, I'm not running from within IPython, just a script that invokes Napari (latest master).

**Comment by tlambert03** [comment]
ok thanks.  I'm not 100% sure what that [`Qt.AA_EnableHighDpiScaling`](https://doc.qt.io/qt-5/highdpi.html#high-dpi-support-in-qt) setting is doing under the hood, but from the docs:

> Enables high-DPI scaling in Qt on supported platforms (see also High DPI Displays). Supported platforms are X11, Windows and Android. Enabling makes Qt scale the main (device independent) coordinate system according to display scale factors provided by the operating system. This corresponds to setting the QT_AUTO_SCREEN​_SCALE_FACTOR environment variable to 1.

Would be curious to know what platform you're on (and maybe see a screenshot).  Are all the widgets and sliders sized nicely?  Just not the fonts?  In any case, to respond to your original question, if we're not hitting the right scaling on all displays, then this is absolutely a reasonable request and I'd love to hear what you learn if you have time to play with relative style units.

**Comment by tlambert03** [comment]
QSS is definitely not a full CSS implementation... so there are limitations for sure.  somewhat confusingly, the [Qt docs here](https://doc.qt.io/qt-5/stylesheet-reference.html#list-of-property-types) state that "Font Size" is of type "`Length`"   Which then says:
>The supported units are:
>  **px**: pixels
>  **pt**: the size of one point (i.e., 1/72 of an inch)
>  **em**: the em width of the font (i.e., the width of 'M')
>  **ex**: the ex width of the font (i.e., the height of 'x')
>
>  However, Qt is limited to font sizes in pt and px and any other size must be in px, em or ex.

seems to contradict itself 🤔

**Comment by stefanv** [comment]
Ah, right---I read that in the docs but didn't click that that would invalidate my suggestion.

OK, so you put me on the right track.  I remembered having had the same qt font issue with krita, and sure enough launching with:

```
QT_SCALE_FACTOR=1.3 python ...
```

Rescales everything nicely.  Thanks!

**Comment by stefanv** [comment]
OK, not perfectly ;)  But much better!  (This is with 1.5 scale factor.)

![2020-07-10_16:35:55](https://user-images.githubusercontent.com/45071/87166376-58d24880-c280-11ea-9bc6-0fec891737ad.png)
![2020-07-10_16:37:47](https://user-images.githubusercontent.com/45071/87166383-5a9c0c00-c280-11ea-81a1-de00497f4a3c.png)

**Comment by tlambert03** [comment]
ahh, interesting.  now I have questions!  Is this because the `Qt.AA_EnableHighDpiScaling` can only use integer ratios or something and/or do you have a slightly unusual system scale factor?  Can you see a way in which we could make setting this easier for users?

**Comment by tlambert03** [comment]
also curious, how do other python qt apps look on your system like Spyder or something

**Comment by stefanv** [comment]
I think the scale factor can be a float.

This should become easier in the latest Qt:

> Added the QT_ENABLE_HIGHDPI_SCALING environment variable, enabling high-DPI scaling based on display DPI. This replaces QT_AUTO_SCREEN_SCALE_FACTOR (now deprecated), and corresponds to the Qt::AA_EnableHighDpiScaling application attribute.

Neither QT_AUTO_SCREEN_SCALE_FACTOR nor QT_ENABLE_HIGHDPI_SCALING change things on my system, though.

**Comment by stefanv** [comment]
> also curious, how do other python qt apps look on your system like Spyder or something

I don't have any others installed, but as mentioned I see the same with Krita.

**Comment by jni** [comment]
Also curious @stefanv, it seems that the your `QT_SCALE_FACTOR=1.3` fix changes the cropping on Chelsea for some reason??? Is that real?

**Comment by stefanv** [comment]
![2020-07-11_18:24:42](https://user-images.githubusercontent.com/45071/87228798-61964d80-c358-11ea-9415-2ea390ae14af.png)

With scaling factor 1.8.

**Comment by liaprins-czi** [comment]
Would it make sense or be simpler to have this functionality (essentially zooming the UI, including both fonts and buttons, icons, width of panel, etc) to be a setting in the Preferences pane?

**Comment by lagru** [comment]
Just adding information: I think I encountered the same or a very similar issue concerning the cropped viewport as well (see https://github.com/scipy-2023-image-analysis/tutorial/pull/10#discussion_r1253658356). I didn't manage to fix the viewport cropping on Plasma / X11 while scaling by 150%. Though it works on Wayland with 150% scaling. 

<details>

```
napari: 0.4.18rc2
Platform: Linux-6.3.9-arch1-1-x86_64-with-glibc2.37
System: Arch Linux
Python: 3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:40:32) [GCC 12.3.0]
Qt: 5.15.6
PyQt5: 5.15.7
NumPy: 1.25.0
SciPy: 1.11.1
Dask: 2023.6.1
VisPy: 0.12.2
magicgui: 0.7.2
superqt: unknown
in-n-out: 0.1.7
app-model: 0.1.4
npe2: 0.7.0

OpenGL:
- GL version: 4.6 (Compatibility Profile) Mesa 23.1.3
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1707x960, scale 1.5

Settings path:
- /home/lg/.config/napari/image-analysis-23_7f0765db03aaec75ab3cdd8b32a00191e1ef37d1/settings.yaml
```

</details>

**Comment by jni** [comment]
This is concerning @lagru! As you can see from the backlinks we kinda sorta have a fix for fonts but we absolutely don't have a fix for the viewport cropping... I suggest that will need some deeper work in vispy...

**Comment by lagru** [comment]
I just tested for the viewport cropping issue on Napari's current `main` (e62c9dd3). The issue seems to persist. But maybe you want to open a second more specific issue for that and keep this one closed?

<details>
```
napari: 0.5.0a2.dev261+ge62c9dd3
Platform: Linux-6.4.7-arch1-1-x86_64-with-glibc2.37
System: Arch Linux
Python: 3.11.3 (main, Jun 5 2023, 09:32:32) [GCC 13.1.1 20230429]
Qt: 5.15.2
PyQt5: 5.15.9
NumPy: 1.25.2
SciPy: 1.11.1
Dask: 2023.7.1
VisPy: 0.13.0
magicgui: 0.7.2
superqt: unknown
in-n-out: 0.1.8
app-model: 0.2.0
npe2: 0.7.2

OpenGL:
- GL version: 4.6 (Compatibility Profile) Mesa 23.1.4
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1707x960, scale 1.5

Settings path:
- /home/lg/.config/napari/test-napari-issue-1417_36e0f04e33614c1007ee07cfb6046adbc8f23f51/settings.yaml
```

</details>

**Comment by psobolewskiPhD** [comment]
@lagru Yeah I think the cropping/viewport issue should be a new issue. Does it only occur with 150% scaling and not 200%?
