### ISSUE TITLE
Make labels painting brush a circle

### ISSUE THREAD

**Issue by kevinyamauchi** [napari/napari#1418]
## 🚀 Feature
As proposed in https://github.com/napari/napari/issues/1142#issuecomment-649548968: change the labels brush shape to a circle (as requested on image.sc): https://forum.image.sc/t/pixel-is-not-a-square/39455

## Motivation

As described in  https://forum.image.sc/t/pixel-is-not-a-square/39455, labeling round structures is challenging with a square brush.

## Pitch

From @sofroniewn in https://github.com/napari/napari/issues/1142#issuecomment-649645267

Should be very doable. Might take a tiny hit on performance, but shouldn't be too bad. Basically these two slice calls https://github.com/napari/napari/blob/master/napari/layers/labels/labels.py#L689-L697 and https://github.com/napari/napari/blob/master/napari/layers/labels/labels.py#L704 will now need to be optionally done based on a center radius instead of center bounding box (we should be able to find away to just have one call to this new method too probably) and we'll need to make a new `circle_pixmap` for the cursor, like our `square_pixmap` here https://github.com/napari/napari/blob/f706a4157cf80e6e0b0d3f21adc0a1c3f7c3b410/napari/_qt/utils.py#L75-L85 which then get's used here https://github.com/napari/napari/blob/master/napari/_qt/qt_viewer.py#L430

**Comment by hectormz** [comment]
I'm currently working on this during the SciPy Sprint

**Comment by hectormz** [comment]
With n-dim checked, does painting apply to all dimensions possible? It paints on a 3d image, but does it paint on all dimensions of 4D image?

**Comment by sofroniewn** [comment]
> With n-dim checked, does painting apply to all dimensions possible? It paints on a 3d image, but does it paint on all dimensions of 4D image?

From Zulip:

> Nicholas Sofroniew: It does all nD right now, I think with no scaling, but it might be nice to add anisotropic scaling of the brush (so you could have the thicker/ thinner brush in the other dims).
>
>Nicholas Sofroniew: I'd say for now let's keep circle brush in full nD for symmetry with rectangle brush, but we might want to revisit that behaviour for both of them in new a PR if it makes sense!
>
>Hector Munoz: Hmmm right. Certainly different potential use cases/expectations
