### ISSUE TITLE
Colormap name still says "hot" by default, even though magma is selected

### ISSUE THREAD

**Issue by jni** [napari/napari#142]
## 🐛 Bug

When launching a new viewer window with a grayscale image, the magma colormap is used (pats own back), but when you double click on the layer to get the properties, it shows "hot" as the selected colormap (whips own back). =P

## Expected behavior

The selected colormap in that drop-down should be magma.

![cmap-selected](https://user-images.githubusercontent.com/492549/53676204-2d863380-3cf3-11e9-8eb9-de6ddcf59fb2.png)

**Comment by sofroniewn** [comment]
This is because #95 has not been implemented yet. I can change the hard coding, but a real solution will require an implementation of #95
