### ISSUE TITLE
Try out the pydata-sphinx-theme

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#1422]
## 🚀 Feature
One of the pandas talks at SciPy2020 pointed out the very lovely newish [`pydata-sphinx-theme`](https://github.com/pandas-dev/pydata-sphinx-theme) now used for pandas and bokeh docs (among others).  Would be nice to see how our docs and API reference docs look with that skin.

**Comment by willingc** [comment]
We're using this on a number of Jupyter projects. This is the [requirements doc](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/doc/doc-requirements.txt) that we have used. Linking here since we found order mattered in listing dependencies. We've been very happy with the theme.

**Comment by tlambert03** [comment]
good to know!  thanks!

**Comment by melissawm** [comment]
I am closing this as we are now using the [napari-sphinx-theme](https://github.com/napari/napari-sphinx-theme).
