### ISSUE TITLE
Switching between monitors shrinks napari viewing window

### ISSUE THREAD

**Issue by hhelmbre** [napari/napari#1423]
## 🐛 Bug

When I open the napari GUI on my second monitor (Dell P2719H) and switch to my mac book pro, the viewing window within the napari GuI for my image shrinks to the bottom left corner - still works as normal with a much smaller area.

## To Reproduce

1. Open a GuI on second monitor
2. Insert Image with view_image in jupyter notebook
3. Move the viewer window from second monitor to mac book

## Expected behavior

Expected the viewer to remain the same between monitors

**Comment by tlambert03** [comment]
Thanks Hawley.  I think what might be happening here is that the Dell P2719H has 1920 x 1080 native resolution, whereas a [macbook pro](https://support.apple.com/en-us/HT202471#:~:text=13%2Dinch%20MacBook%20Pro%20models,Support%20for%20millions%20of%20colors.) 15" has 2880 x 1800 native resolution (and the 16" has 3072 x 1920).  So Qt must be scaling for whatever the main monitor is when starting the program (and unable to switch scaling after launching the viewer?).  is it possible for you to test this in the other direction?  Starting on macbook pro, then moving to the monitor?

**Comment by hhelmbre** [comment]
Yep! No problem the other way around.

**Comment by tlambert03** [comment]
oh now that's fascinating

**Comment by tlambert03** [comment]
will try to recreate

**Comment by sofroniewn** [comment]
This may be related to #566, though behavior described is slightly different.

**Comment by sofroniewn** [comment]
#1729 has now been merged and so this may likely be fixed! Let us know @hhelmbre if you're able to verify, otherwise I'll leave this open for a little bit longer and then close.

**Comment by sofroniewn** [comment]
All indications are that this was fixed by #1729 which has merged, and so I will close this. If it turns out that this issue remains we can always reopen. Thanks all!
