### ISSUE TITLE
Base EventedModel proposal

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#1436]
## 🚀 Feature
I've been playing around with an idea for a generic model base class that would ultimately reduce a lot of our model code to something like this:

```python
class Layer(EventedModel):
    name: str
    x: int = 3
```
Where `EventedModel` provides the following features:

- type validation/coersion: on class instantiation _and_ on attribute assignment, the type will be validated and coerced if possible (this would also work for Enums and stuff).  ensuring that the model state is always valid, or an exception gets raised. 
- event emission after successful attribute assignment.
- Those two things cover the majority of our boilerplate model code, but it would still possible to override complex setter behavior, by adding an explicit setter method (called `_on_<attr_name>_set` in the example below)

Each characteristic is optional... the type checking and coercion could be provided by [pydantic](https://pydantic-docs.helpmanual.io/) (a very cool package I have used in other projects like [ome-types](https://github.com/tlambert03/ome-types)).  Custom type validation is possible (for instance, make sure it's a M x N array, etc...) and [this blog post](https://www.madelyneriksen.com/blog/validated-container-types-python-pydantic) provides a good overview on that.  However, the whole type checking is optional, and does add slight overhead.  The auto event emission and `dataclass` style syntax would be possible independently.

Here's a working prototype (need to `pip install pydantic`):

```python
from pydantic import BaseModel
from napari.utils.event import EmitterGroup


# BaseModel is a dataclass-like class from pydantic
# they also provide @dataclass, but don't yet know how to use it with additional methods
class EventedModel(BaseModel):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.events = EmitterGroup(
            source=self,
            auto_connect=False,
            **{name: None for name in self.__fields__},
        )

    class Config:
        extra = 'allow'
        validate_assignment = True  # validate types on assignment as well

    def __setattr__(self, name, value):
        super().__setattr__(name, value)  # set with type coercion
        value = getattr(self, name)  # get the validated value
        # if custom set method `_on_<name>_set` exists, call it
        setter_method = getattr(self, f'_on_{name}_set', None)  # 
        if callable(setter_method):
            # the method can return True, if it wants to handle its own events
            if setter_method(value):
                return
        # otherwise, we emit this event
        if name in self.events:
            getattr(self.events, name)(value=getattr(self, name))



class Layer(EventedModel):
    name: str
    x: int = 3


layer = Layer(name='hi')
layer.events.connect(
    lambda e: print(
        f"You changed {e.source.__class__.__name__}.{e.type} to {e.value!r}"
    )
)
layer.x = '123'
# "You changed Layer.x to 123" is printed to the console

# not the type coercion
assert isinstance(layer.x, int)

try:
    layer.x = 'not an int'
except Exception as e:
    print(e)
    """
    1 validation error for Layer
    x
      value is not a valid integer (type=type_error.integer)
    """
```

thoughts @napari/core-devs ?

**Comment by sofroniewn** [comment]
I like the general direction - it has elements of #1325 which I like in it (where @kne42 proposed the model being a dataclass).

I also like that the proposal will just clean up our model files (as opposed to also trying to fix the flow of all the events etc etc). It seems like here we could have a backwards compatible PR were no tests have to change (which is one thing I liked about #1376), but where also no view code has to change either, right?

Can you expand the example a tiny bit to include what the sytanx looks like on the `Layer` class where we have a custom setter

**Comment by tlambert03** [comment]
Yep, I like the purity of the dataclass too.  This could be implemented with a dataclass-like decorator as well, and here's what a custom setter would look like: 

```python
@evented_model
class Layer:
    name: str
    x: int = 3

    def _on_name_set(self, value):
        if value.startswith("Talley"):
            print("That's not a real name, I refuse to emit an event"):
            return True  # any truthy value will prevent the default event emission.
        else:
            # ... any logic
            self.name = 'another thing'  # can modify before event is emitted.
```

if we _really_ wanted to keep the model separate from the business logic, one could even do something like this:

```python
@evented_model
class LayerModel:
    """Just the attributes, types, and docstring... like a specification."""
    name: str
    x: int = 3

class Layer(LayerModel):
    """Business logic."""

    def _on_name_set(self, value):
        if value.startswith("Talley"):
            print("That's not a real name, I refuse to emit an event"):
            return True  # any truthy value will prevent the default event emission.
        else:
            # ... any logic
            self.name = 'another thing'  # can modify before event is emitted.
```

**Comment by tlambert03** [comment]
and you're right, it's extremely like @kne42's proposal in #1325, just a different way of implementing the `notifier()` logic

**Comment by sofroniewn** [comment]
> if we really wanted to keep the model separate from the business logic, one could even do something like this:

I don't need that - top option `class Layer` works for me!

> Yep, I like the purity of the dataclass too. This could be implemented with a dataclass-like decorator as well,

If we didn't use `pydantic` and gave up on the type checking could we make an evented dataclass as a "drop-in-replacement" that could move to `pydantic` one day, or are we getting more from `pydantic`?

**Comment by tlambert03** [comment]
the only thing we're getting from pydantic is runtime enforcing of type hints (with nice error messages).  So this is all very much possible without pydantic.  If we implemented this thoroughly with pydantic, we'd have a rock solid model that was nearly guaranteed to be consistent. So I include it mostly as a complete picture, but not necessary.  It could also be progressive (some things could be strict while others are not).

It's more or less a "drop-in replacement", but one that would probably require some refactoring here and there (more because of things that we probably _should_ be fixing anyway.  If people generally like the idea, I'd try to get an example implementation working.

**Comment by sofroniewn** [comment]
> If people generally like the idea, I'd try to get an example implementation working.

I'm on board with the idea, but might lean towards an initial implementation that was pydantic free and then add in pydantic later - will be a little be easier for everyone to then see exactly how everything works and have complete confidence in it all

**Comment by tlambert03** [comment]
Here’s a downside of dataclasses. Since the attribute `instance.name` returns the literal value, instead of a property descriptor as we currently do, then you can’t actually get docs on that attribute in IPython for instance with `instance.name?`. (If `name` is a string, you get the docs for `str`).  I consider that a pretty big bummer, right?   So if we still like the “look and feel” of the dataclass syntax (I do), then I think it would still be possible to use properties behind the scenes, and pull the property docstring from the class docstring.  I think that could be kinda nice actually.  Curious whether you think we’re starting to be too magical here though. @jni, @sofroniewn

**Comment by sofroniewn** [comment]
> Then I think it would still be possible to use properties behind the scenes

I'm a little worried about this, I feel like we're already re-implementing a fundamental Python object a List in a special way, and don't want to keep that trend going too far (though that list behaviour is amazing!). I guess it depends a little bit how invasive/ major this change is.

> I consider that a pretty big bummer, right?

Not for so much me, but I guess for some. On the one hand I think considerations like this are important, but on the other I worry about increasing complexity of the codebase to accommodate issues like this - it reminds me of the pycharm doc string stuff, but maybe a little more serious.

Curious what @jni thinks - I'll admit this is outside my knowledge area

**Comment by jni** [comment]
> Not for so much me, but I guess for some.

At first I was inclined to agree with Nick, but then I realised that @tlambert03 picked the worst possible example — who needs to know what `.name` means? But `.interpolation` or `.properties` are another thing entirely. There, explanations would be super handy.

On the other hand, if we keep or objects clean and lean, `instance?` would work fine, no? 

@tlambert03 how exactly do you propose to implement this magical behaviour?

**Comment by sofroniewn** [comment]
> Here’s a downside of dataclasses. 

Also is this true for all dataclasses, all our attributes, or is it special to our use case / just for some properties?

**Comment by tlambert03** [comment]
> Also is this true for all dataclasses, all our attributes, or is it special to our use case / just for some properties?

This is true for _any_ class attribute (all dataclasses, but not just dataclasses) that is not a [property descriptor](https://docs.python.org/3/howto/descriptor.html#properties):
```python

class ObjA:
    x = 1

obj = ObjA()
obj.x  # this returns the literal "1"


class ObjB:
    @property
    def x():
        """I can put a docstring here."""
        return 1

obj = ObjB()
obj.x  # this returns a pointer to a "data descriptor"
```

this brings me to

> @tlambert03 how exactly do you propose to implement this magical behaviour?

The key lies in 
1. the [definition of `@dataclass`](https://docs.python.org/3/library/dataclasses.html#module-level-decorators-classes-and-functions)... which says: 
   > This function is a decorator that is used to add generated special methods to classes, as described below.
   The dataclass() decorator examines the class to find fields. A field is defined as class variable that has a type annotation.
2. perusing the [source for the dataclass function](https://github.com/python/cpython/blob/master/Lib/dataclasses.py) which shows that dataclass basically does this:

   ```python
   def dataclass(cls, ...):
        ...
        fields = [name for name in cls.__dict__.get('__annotations__', {})]
        ...
        # then a whole bunch of setattr of special methods
        setattr(cls, '__init__', special_dataclass_init_func)
        etc...
    ```
So the magical behavior would just be an extension of that decorator that says something like
```python
for field, default in fields.items():
    setattr(cls, f"_{field}", default)  # the new actual field
    setattr(cls, field, descriptor_for_field)  # the property descriptor that controls f"_{field}"
```

**Comment by sofroniewn** [comment]
Thanks for the detailed explanation @tlambert03! I guess given the `true for any class attribute` nature of this I'd probably prefer we implement the first PR without this so that it as easy to understand and merge that PR as possible and then we maybe add this in a later date, particularly if people are bothered by the behaviour without it.

**Comment by sofroniewn** [comment]
With the merge of #1475 we have taken the first step in this direction. There is still much work to be done to actually move our models over, but given the merge of #1475 I will close this issue, and we can use new issues to discuss individual object refactors as they arise.
