### ISSUE TITLE
Tearing when panning quickly

### ISSUE THREAD

**Issue by jni** [napari/napari#144]
## 🐛 Bug

I noticed that when panning an image quickly you can introduce some tearing in the image. @royerloic says this might be avoided by changing vsync settings in vispy. 

## To Reproduce

1. Display the astronaut image
2. Click and hold
3. Move mouse around rapidly

## Expected behavior

Panning should be smooth.

## Environment

 - napari-gui Version (e.g., 1.0): master
 - OS (e.g., Linux): Ubuntu 18.04
 - Python version: 3.6
 - Any other relevant information: Intel Core i5 (8th gen), integrated graphics.

**Comment by sofroniewn** [comment]
@jni do we know if this is still an issue / can you provide some more info - I don't think I've seen anything like this on my mac or maybe i just havn't noticed / it hasn't bothered me.

**Comment by jni** [comment]
Honestly, it happens on *firefox* webpage rendering on my laptop, so I think it's just Linux interacting badly with OpenGL. Probably not an issue with napari but with my graphics drivers. I'll close for now.
