### ISSUE TITLE
Functionality to convert image layer to labels layer and vice versa

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#1442]
## 🚀 Feature
See [tweet](https://twitter.com/sofroniewn/status/1281652346980757504) (copied below) and discussion with @adamltyson for additional context.

> Hmm, I worry it might get a little too magical. Maybe a better approach at this point would be a simple function/ GUI call to convert an image to labels and visa versa. You'd have to make another click, but it would be much more robust/ transparent and good functionality to have

Would be helpful following drag/drop when labels guessing gets it wrong. Would likely be integrated in a layer popup box that would also have merge/ split functionality like in #1322 depending on what is selected

**Comment by sofroniewn** [comment]
This should then have keyboard shortcut/ GUI button support too - see #1543

**Comment by liaprins-czi** [comment]
@sofroniewn Can you explain the contexts from users POV of when they'd need this functionality? I was reading the tweet thread but I'm not seeing where it really describes the main issue.

**Comment by sofroniewn** [comment]
Many file formats for saving data don't have a concept of whether data should be an image or labels - i.e. a png or tiff is just a bunch of pixels, possibly with values from 0-255. When we load that data we might think that it is an image, but a user might actually want to interact with it like labels (i.e. add to it using a paintbrush etc), so we should offer a version to convert from image to labels.

Converting from labels to image is probably a less common a need, though one might want to do it if you wanted to use a highly custom colormap and never edit your labels

**Comment by liaprins-czi** [comment]
Thanks @sofroniewn ! So is the only time this would be relevant when a user is loading a file? Just curious if there are other times, because it would affect the design options.

**Comment by tlambert03** [comment]
We have this now on the layer context menu, right?

**Comment by jni** [comment]
We do and it is beautiful! Thanks @tlambert03! 😊 I suggest we close this and create a dedicated design issue if needed. (e.g. might be good to have a "Layers" menu on the menubar?)

**Comment by sofroniewn** [comment]
> So is the only time this would be relevant when a user is loading a file? Just curious if there are other times, because it would affect the design options.

I think that's the most common time, but i could imagine someone wanting to convert back after converting to an image too - i.e. if you can go labels -> image you should also be able to go back

> I suggest we close this and create a dedicated design issue if needed.

Yes, agreed we can close this. It should have been closed when the functionality was added in #2556, but we missed it. @liaprins-czi has created #3295 to track any additional design work.

Here are screenshots

<img width="1190" alt="Screen Shot 2021-08-30 at 8 49 53 PM" src="https://user-images.githubusercontent.com/6531703/131438817-29924a56-9365-4ae1-8818-1f034b71643e.png">

<img width="1190" alt="Screen Shot 2021-08-30 at 8 58 04 PM" src="https://user-images.githubusercontent.com/6531703/131439469-d76c16fc-d488-4d3b-b915-4a186db4fb09.png">

Note neither of these are in 0.4.10, they will both be new in 0.4.11
