### ISSUE TITLE
Undo doesn't reverse changes to other slices due to n-dim

### ISSUE THREAD

**Issue by moloney** [napari/napari#1448]
## 🐛 Bug

When using the n-dim option to modify labels in multiple slices, the undo operation only affects the current slice.

## To Reproduce

1. Create label image
2. Check n-dim option and draw some shape
3. Press ctrl-z to undo, which works on the current slice
4. Move to adjacent slices where the label is still present

## Expected behavior

Undo should reverse changes to all slices.

## Environment

 napari: 0.3.5
Platform: Linux-4.15.0-106-generic-x86_64-with-debian-buster-sid
Python: 3.7.2 (default, Feb 6 2019, 12:58:45) [GCC 7.3.0]
Qt: 5.14.2
PyQt5: 5.14.2
NumPy: 1.19.0
SciPy: 1.5.1
Dask: 2.20.0
VisPy: 0.6.4

GL version: 3.0 Mesa 19.2.8
MAX_TEXTURE_SIZE: 16384

Plugins:
- napari-plugin-engine: 0.1.6
- svg: 0.1.3

**Comment by sofroniewn** [comment]
> When using the n-dim option to modify labels in multiple slices, the undo operation only affects the current slice.

Indeed, we restricted undo to the current slice, and as soon as you change slices we wipe the history so you can't undo anymore. While this definitely is not acceptable behaviour long term, it was a compromise that allowed a simple undo/ redo machinery for "2D" labels data before we implemented a more fully featured undo/ redo that would work for all actions in the GUI.

We can revisit this, either in the short term, implementing a full undo/redo for nD painting, or thinking about revisiting our full ideas for an undo/ redo framework that was last discussed in #474

**Comment by Czaki** [comment]
> Indeed, we restricted undo to the current slice, and as soon as you change slices we wipe

But currently undo only partially revert changes. So it should be fixed or disabled undo action which are done on multiple layers.

**Comment by sofroniewn** [comment]
This has now been fixed and a test was added by @jni in #2339 and so I will close. If something isn't working as expected though please feel free to reopen!
