### ISSUE TITLE
consider restricting the auto RGB guessing even more?

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#1449]
## 🐛 Bug
@adamltyson had an unexpected result ([posted in image.sc](https://forum.image.sc/t/napari-issue-opening-float32-image/40281/4)) in which an image with a trailing singleton dimension was interpreted as RGB, and let to strange results. We might want to further restrict our "RGB guessing" to with `shape[-1] in (3, 4)`

**Comment by jni** [comment]
Yep, absolutely +1

**Comment by lucyleeow** [comment]
I think this has been done:

https://github.com/napari/napari/blob/5c10022337601f350ad64ce56eddf6664306e40e/napari/layers/image/_image_utils.py#L30

so closing.
