### ISSUE TITLE
Ability to run all tests on local Windows installs

### ISSUE THREAD

**Issue by jni** [napari/napari#1455]
## 🚀 Feature

In #1372, we started to use the 'CI' environment variable to run our windowed tests on CI only. We can run them locally by setting CI=1 *except* when running locally in a Windows box, in which case, you have absolutely no way to run those tests.

Here's the marker we use:

```python
@pytest.mark.skipif(
     sys.platform.startswith('win') or not os.getenv("CI"),
     reason='Screenshot tests are not supported on napari windows CI.',
 )
```

Reading the reason description, I expect the condition to read `sys.platform.startswith('win') and os.getenv('CI')`. I think the point is that we are making the CI variable do double duty, and we should add our own variable:

```python
@pytest.mark.skipif(
     sys.platform.startswith('win') and os.getenv("CI"),
     reason='Screenshot tests are not supported on napari windows CI.',
 )
@pytest.mark.skipif(
    not os.getenv('NAPARI_POPUP_TESTS'),
    reason='Tests requiring pop-up napari windows are skipped by default.',
)
```

Thoughts @sofroniewn @tlambert03?

**Comment by tlambert03** [comment]
the skip on platform windows was old behavior, from before #1372... right?  That is, we've never been running those tests on windows locally.  Basically, we never wanted to run them on windows because whatever virtualization was happening on CI wasn't working for windows, so they got skipped (but might be worth revisiting that).  As briefly discussed in https://github.com/napari/napari/pull/1372#issuecomment-646154900, I'm a little hesitant to make up our own env var that we have to make sure to use in our CI workflows, since `CI` is such a common environment variable across all CI providers.
so I think I'd probably prefer to just make an alias:
```python
# skip when running locally or running remotely on window.
# opt in with CI
WIN_CI = sys.platform.startswith('win') and os.getenv("CI")
@pytest.mark.skipif(WIN_CI or not os.getenv("CI"))
```

**Comment by jni** [comment]
@tlambert03 

> we have to make sure to use in our CI workflows

We don't have to make sure to use it. If you don't use it, things work as they do now. The way I see it, doing "CI=1" locally is a hack that doesn't actually reflect the intent of the env var. And having two skipif marks allows you to specify the actual reason that a test was skipped.

**Comment by tlambert03** [comment]
> doing "CI=1" locally is a hack that doesn't actually reflect the intent of the env var. And having two skipif marks allows you to specify the actual reason that a test was skipped.

Both make sense to me but I’d still rather have CI what we use on CI, so perhaps We create another alias for `CI or NAPARI_POPUP_TESTS`

**Comment by tlambert03** [comment]
> We don't have to make sure to use it.

Wait, wouldn’t we have to set NAPARI_POPUP_TESTS in CI to not skip those tests?

**Comment by jni** [comment]
@tlambert03 

aaaah, you're right, sorry, I got confused with the double negatives. Here's the modified version:

```python
@pytest.mark.skipif(
    sys.platform.startswith('win') and os.getenv('CI'),
    reason='Screenshot tests are not supported on napari windows CI.',
)
@pytest.mark.skipif(
    not os.getenv('CI') and not os.getenv('NAPARI_POPUP_TESTS'),
    reason='Tests requiring pop-up napari windows are skipped locally by default.',
)
```

**Comment by tlambert03** [comment]
yep, that works for me!  we could set some root level constants WIN, LINUX, MACOS, CI, etc... to make it all a little cleaner.  but I'm all for this change
