### ISSUE TITLE
Shapes color swatches not updating when selecting different points

### ISSUE THREAD

**Issue by kevinyamauchi** [napari/napari#1461]
## 🐛 Bug

As reported by @sofroniewn in #1374 , the color swatches in the points layer are not updating to reflect the currently selected points. I haven't had a chance to investigate, but I think this is likely just a missing event connection in the `Shapes` qt layer controls.

## To Reproduce

1. Run examples/add_shapes.py
2. Enter selection mode
3. Click different shapes
4. The colors in the layer controls should update to reflect the selected point, but they don't.

## Expected behavior

When a point is selected, the color swatches in the layer controls should update to match the colors of the selected point.

## Environment

napari: 0.3.5.dev14+g02d296b.d20200614
Platform: Darwin-18.7.0-x86_64-i386-64bit
Python: 3.7.7 (default, Mar 10 2020, 15:43:03) [Clang 11.0.0 (clang-1100.0.33.17)]
Qt: 5.14.1
PySide2: 5.14.1
NumPy: 1.18.1
SciPy: 1.4.1
Dask: 2.12.0
VisPy: 0.6.4

GL version: 2.1 INTEL-12.10.19
MAX_TEXTURE_SIZE: 16384

Plugins:
- napari-plugin-engine: 0.1.5
- napari-plugins: 0.1.0
- svg: 0.1.3

## Additional context

This can likely be fixed by copying the events and callback functions related to edge color from the [Points layer controls qt file](https://github.com/napari/napari/blob/master/napari/_qt/layers/qt_points_layer.py) to the [Shapes layer controls qt file](https://github.com/napari/napari/blob/master/napari/_qt/layers/qt_shapes_layer.py).

**Comment by sofroniewn** [comment]
Looks like in `0.3.5` this was working for face color but not edge color. Same is true now - it looks like the fail is edge color swatch specific, face color changes fine. Seems like problem has always been there for edge color

**Comment by ViriatoII** [comment]
The same thing happens to me still. I can change point shapes in the GUI but not their size or face color


> napari: 0.4.13
> Platform: Windows-10-10.0.19043-SP0
> Python: 3.9.10 (tags/v3.9.10:f2f3f53, Jan 17 2022, 15:14:21) [MSC v.1929 64 bit (AMD64)]
> Qt: 5.15.2
> PyQt5: 5.15.5
> NumPy: 1.21.2
> SciPy: 1.7.1
> Dask: 2021.10.0
> VisPy: 0.9.4
> 
> OpenGL:
> - GL version: 4.6.0 - Build 30.0.100.9864
> - MAX_TEXTURE_SIZE: 16384
> 
> Screens:
> - screen 1: resolution 1920x1080, scale 1.0
> - screen 2: resolution 1920x1080, scale 1.0
> 
> Plugins:
> - console: 0.0.4
> - scikit-image: 0.4.13
> - svg: 0.1.5

**Comment by sofroniewn** [comment]
> The same thing happens to me still. I can change point shapes in the GUI but not their size or face color

@ViriatoII have you selected the points? It's a little confusing unfortunatley that the points must be selected before you can change their color, but their symbol can be changed at any moment (and all the points change symbol at the same time).

See this video where points get selected first: 

https://user-images.githubusercontent.com/6531703/151219071-2191c446-aa2e-424c-8189-8229f5a1e406.mov

Maybe @chili-chiu can follow up if it still doesn't work for you, and maybe @chili-chiu we should update our documentation to make this more clear

**Comment by chili-chiu** [comment]
see also https://github.com/napari/napari/issues/2353

**Comment by ViriatoII** [comment]
@sofroniewn  and @chili-chiu , that's it, thank you. The proposed "select all points" button should help. At the moment zooming out to manually select all points is impractical.
