### ISSUE TITLE
ipython console doesn't open when the button is pushed, but opens from menu

### ISSUE THREAD

**Issue by kevinyamauchi** [napari/napari#1465]
## 🐛 Bug

On master, the button for the ipython console doesn't do anything. However, the console can be opened via the Window menu.

## To Reproduce

1. Run the add_image.py example from master
2. Click the terminal button. Nothing happens and no errors printed to the terminal
3. From the "Window" menu, click "console" and the ipython console opens

## Expected behavior

The terminal should open when pressing the terminal icon.

## Environment

napari: 0.3.5.dev87+g2e992bf.d20200716
Platform: Darwin-18.7.0-x86_64-i386-64bit
Python: 3.7.7 (default, Mar 10 2020, 15:43:03) [Clang 11.0.0 (clang-1100.0.33.17)]
Qt: 5.15.0
PyQt5: 5.15.0
NumPy: 1.19.0
SciPy: 1.5.1
Dask: 2.20.0
VisPy: 0.6.4

GL version: 2.1 INTEL-12.10.19
MAX_TEXTURE_SIZE: 16384

Plugins:
- napari-plugin-engine: 0.1.6
- svg: 0.1.3

## Additional context

ipython version: 7.16.1

**Comment by tlambert03** [comment]
You’ve got Qt 5.15.0, which is known to be broken for the buttons

**Comment by kevinyamauchi** [comment]
Ah got it! Thanks!

**Comment by tlambert03** [comment]
linking #1312
