### ISSUE TITLE
Terminal errors when I try to install Napari (... I'd had an earlier version installed prior)

### ISSUE THREAD

**Issue by liaprins-czi** [napari/napari#1474]
## 🐛 Bug

I had a very old version of napari installed (from last fall) and I tried to follow the [napari installation tutorial](https://napari.org/tutorials/fundamentals/installation) instructions for how to upgrade to the newest version, but that didn't work. So I moved the folder I had napari in to the trash and then I followed the virtual environment installation directions in the [napari installation tutorial](https://napari.org/tutorials/fundamentals/installation), which told me to do these steps:

`conda create -y -n napari-env python=3.7.4` (note: I found out my Python version and used it in this line)
`conda activate napari-env`
`pip install napari[all]`

But my terminal gave me red error messages, and when I tried to run the `napari` command to check if napari would open, it wouldn't. Nick also helped me over Zoom, and had me try just the `pip install napari[all]` after uninstalling vispy, but I still got the same errors (see below).

## To Reproduce

I think this is due to my particular set up and/or the fact that I had had an older version of napari installed previously, so I doubt it could be reproduced by others following what I did (see above).

### Here is the error message I get in my terminal:

ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/4l/6pd0h1ws2ll2516v4680dh3w0000gq/T/pip-install-te2ndemv/psutil/setup.py'"'"'; __file__='"'"'/private/var/folders/4l/6pd0h1ws2ll2516v4680dh3w0000gq/T/pip-install-te2ndemv/psutil/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/4l/6pd0h1ws2ll2516v4680dh3w0000gq/T/pip-record-3jjci7lf/install-record.txt --single-version-externally-managed --compile --install-headers /Library/Frameworks/Python.framework/Versions/3.7/include/python3.7m/psutil
         cwd: /private/var/folders/4l/6pd0h1ws2ll2516v4680dh3w0000gq/T/pip-install-te2ndemv/psutil/
    Complete output (44 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.9-x86_64-3.7
    creating build/lib.macosx-10.9-x86_64-3.7/psutil
    copying psutil/_pswindows.py -> build/lib.macosx-10.9-x86_64-3.7/psutil
    copying psutil/_common.py -> build/lib.macosx-10.9-x86_64-3.7/psutil
    copying psutil/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/psutil
    copying psutil/_psosx.py -> build/lib.macosx-10.9-x86_64-3.7/psutil
    copying psutil/_psbsd.py -> build/lib.macosx-10.9-x86_64-3.7/psutil
    copying psutil/_psaix.py -> build/lib.macosx-10.9-x86_64-3.7/psutil
    copying psutil/_pslinux.py -> build/lib.macosx-10.9-x86_64-3.7/psutil
    copying psutil/_compat.py -> build/lib.macosx-10.9-x86_64-3.7/psutil
    copying psutil/_psposix.py -> build/lib.macosx-10.9-x86_64-3.7/psutil
    copying psutil/_pssunos.py -> build/lib.macosx-10.9-x86_64-3.7/psutil
    creating build/lib.macosx-10.9-x86_64-3.7/psutil/tests
    copying psutil/tests/test_contracts.py -> build/lib.macosx-10.9-x86_64-3.7/psutil/tests
    copying psutil/tests/test_connections.py -> build/lib.macosx-10.9-x86_64-3.7/psutil/tests
    copying psutil/tests/runner.py -> build/lib.macosx-10.9-x86_64-3.7/psutil/tests
    copying psutil/tests/test_unicode.py -> build/lib.macosx-10.9-x86_64-3.7/psutil/tests
    copying psutil/tests/test_misc.py -> build/lib.macosx-10.9-x86_64-3.7/psutil/tests
    copying psutil/tests/test_posix.py -> build/lib.macosx-10.9-x86_64-3.7/psutil/tests
    copying psutil/tests/test_linux.py -> build/lib.macosx-10.9-x86_64-3.7/psutil/tests
    copying psutil/tests/test_sunos.py -> build/lib.macosx-10.9-x86_64-3.7/psutil/tests
    copying psutil/tests/__init__.py -> build/lib.macosx-10.9-x86_64-3.7/psutil/tests
    copying psutil/tests/test_aix.py -> build/lib.macosx-10.9-x86_64-3.7/psutil/tests
    copying psutil/tests/test_process.py -> build/lib.macosx-10.9-x86_64-3.7/psutil/tests
    copying psutil/tests/test_bsd.py -> build/lib.macosx-10.9-x86_64-3.7/psutil/tests
    copying psutil/tests/test_system.py -> build/lib.macosx-10.9-x86_64-3.7/psutil/tests
    copying psutil/tests/test_osx.py -> build/lib.macosx-10.9-x86_64-3.7/psutil/tests
    copying psutil/tests/test_memleaks.py -> build/lib.macosx-10.9-x86_64-3.7/psutil/tests
    copying psutil/tests/test_windows.py -> build/lib.macosx-10.9-x86_64-3.7/psutil/tests
    copying psutil/tests/__main__.py -> build/lib.macosx-10.9-x86_64-3.7/psutil/tests
    copying psutil/tests/test_testutils.py -> build/lib.macosx-10.9-x86_64-3.7/psutil/tests
    running build_ext
    building 'psutil._psutil_osx' extension
    creating build/temp.macosx-10.9-x86_64-3.7
    creating build/temp.macosx-10.9-x86_64-3.7/psutil
    creating build/temp.macosx-10.9-x86_64-3.7/psutil/arch
    creating build/temp.macosx-10.9-x86_64-3.7/psutil/arch/osx
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch x86_64 -g -DPSUTIL_POSIX=1 -DPSUTIL_SIZEOF_PID_T=4 -DPSUTIL_VERSION=572 -DPSUTIL_OSX=1 -I/Library/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c psutil/_psutil_common.c -o build/temp.macosx-10.9-x86_64-3.7/psutil/_psutil_common.o
    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/4l/6pd0h1ws2ll2516v4680dh3w0000gq/T/pip-install-te2ndemv/psutil/setup.py'"'"'; __file__='"'"'/private/var/folders/4l/6pd0h1ws2ll2516v4680dh3w0000gq/T/pip-install-te2ndemv/psutil/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/4l/6pd0h1ws2ll2516v4680dh3w0000gq/T/pip-record-3jjci7lf/install-record.txt --single-version-externally-managed --compile --install-headers /Library/Frameworks/Python.framework/Versions/3.7/include/python3.7m/psutil Check the logs for full command output.

## Environment

MacBook Pro running MacOS Catalina 10.15.5

**Comment by tlambert03** [comment]
hmm, looks like it's trying to compile a package (psutil) and you don't have the necessary build tools installed.  We definitely don't _want_ the end-users to have to install any special stuff to be able to pip install, but in certain cases (like some recent issues with vispy and windows: https://github.com/napari/napari/issues/1340), we're dependent on third parties to distribute pre-compiled "wheels" for us.  Two thoughts:

first: maybe you can just try installing from conda, which might avoid all this:
```bash
# sidenote, it doesn't matter what local python you have
# conda will install a new version of whatever python you ask for
conda create -y -n napari-env python=3.8
conda activate napari-env
conda install napari  # instead of pip install
```

second: it _does_ look like `psutil` provides one macOS wheel (`psutil-5.7.1`) ... and it even looks like @Czaki, a napari contributor, helped make that possible in https://github.com/giampaolo/psutil/pull/1758.  @Czaki, maybe you can shed more light here?  Should a mac user be able to `pip install psutil` without having any dev tools yet?

**Comment by Czaki** [comment]
there is also second PR https://github.com/giampaolo/psutil/pull/1762
Both finally allow to create wheel for macos and manylinux2014. @giampaolo strongly prefer to publis wheel for manylinux2010 (there is problem with rlimit on centos6 if I good remeber. 
There is also some problem with windows (segfault on windows) because newer compiler. 

Base discussion wwere here:
https://github.com/giampaolo/psutil/issues/1550

I see that wheels are build on github actions. You can even download them https://github.com/giampaolo/psutil/actions/runs/170060074, you can manually extract macos wheel from archive,

But I do not know when @giampaolo will publish wheel on pypi.

**Comment by tlambert03** [comment]
ok thanks @Czaki!
@liaprins-czi, I think that means your safest bet is to try the conda install mentioned above. (I know... doesn't look great for our install instructions ... but dependencies are tough!)

**Comment by liaprins-czi** [comment]
Great, I will try that; thanks @tlambert03 and @Czaki !

**Comment by liaprins-czi** [comment]
Update: I tried installing from conda just like @tlambert03 suggested above, but I still get a (different) terminal error, telling me the napari package is not available from the current channels... **Here is everything on my terminal from `conda activate napari-env` and after:**



(napari-env) CZIRWC1MACOS2226:~ lprins$ conda activate napari-env
(napari-env) CZIRWC1MACOS2226:~ lprins$ conda install napari
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - napari

Current channels:

  - https://conda.anaconda.org/bioconda/osx-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by tlambert03** [comment]
agh... forgot the "conda-forge" channel.  This is one of those things that almost everyone has in their settings, so it's easy to forget, but we should absolutely have it listed for our conda install directions (which, come to think of it, aren't even listed explicitly in the install instructions, sorry!)

```
conda config --add channels conda-forge
conda install napari
```

**Comment by liaprins-czi** [comment]
Great, that worked! Thanks so much @tlambert03 !
