### ISSUE TITLE
Document conda install with conda-forge

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#1477]
## 📚 Documentation
installing from conda is a nice way to get around some of the wheel issues on vispy (https://github.com/napari/napari/issues/1340) and psutil (https://github.com/napari/napari/issues/1474)
but we don't have it documented... and someone with a fresh conda environment might also not have conda-forge in their channels (https://github.com/napari/napari/issues/1474#issuecomment-660332049).  This should be documented in the readme and at napari.org

**Comment by jni** [comment]
fwiw I prefer the form:

```python
conda install -c conda-forge napari
```

than advising users to change their config.

**Comment by jni** [comment]
I think we can probably close this? Installing from conda is included in:

https://napari.org/tutorials/fundamentals/installation

**Comment by sofroniewn** [comment]
> I think we can probably close this? Installing from conda is included in:
>
> https://napari.org/tutorials/fundamentals/installation

Yes looks like it
