### ISSUE TITLE
Error with builtins plugin when opening files

### ISSUE THREAD

**Issue by megturn** [napari/napari#1480]
Hi,
I pip installed napari[all] and the GUI opens fine, but when I try to open any images I get an error message. I shared the file with other members of our group who have napari installed on their computers and they were able to open the exact same files I was trying to open.
What does this error mean? Am I missing something I need to install separately?
Thanks!

=========================== Errors for plugin 'builtins' ===========================

  napari version: 0.3.5
  plugin package: napari
         version: 0.3.5
          module: <module 'napari.plugins._builtins' from 'c:\\users\\shahv\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\napari\\plugins\\_builtins.py'>

ERROR #1:  Error in plugin 'builtins', hook 'napari_get_reader': array is too big; `arr.size * arr.dtype.itemsize` is larger than the maximum possible size. 

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
c:\users\shahv\appdata\local\programs\python\python38-32\lib\site-packages\napari\plugins\io.py in read_data_with_plugins(path=r'C:\Users\shahv\Pictures\2020_06_17__8256-Image E...06_17__8256-Image Export-01_s1_TL Brightfield.tif', plugin=None, plugin_manager=<napari_plugin_engine.manager.PluginManager object>)
     87         try:
---> 88             layer_data = reader(path)  # try to read data
        layer_data = None
        reader = None
        path = 'C:\\Users\\shahv\\Pictures\\2020_06_17__8256-Image Export-01\\2020_06_17__8256-Image Export-01_s1_TL Brightfield.tif'
     89             if layer_data:

c:\users\shahv\appdata\local\programs\python\python38-32\lib\site-packages\napari\types.py in reader_function(*args=(r'C:\Users\shahv\Pictures\2020_06_17__8256-Image E...06_17__8256-Image Export-01_s1_TL Brightfield.tif',), **kwargs={})
     60     def reader_function(*args, **kwargs) -> List[LayerData]:
---> 61         result = func(*args, **kwargs)
        result = undefined
        global func = undefined
        args = ('C:\\Users\\shahv\\Pictures\\2020_06_17__8256-Image Export-01\\2020_06_17__8256-Image Export-01_s1_TL Brightfield.tif',)
        kwargs = {}
     62         return [(result,)]

c:\users\shahv\appdata\local\programs\python\python38-32\lib\site-packages\napari\utils\io.py in magic_imread(filenames=[r'C:\Users\shahv\Pictures\2020_06_17__8256-Image E...06_17__8256-Image Export-01_s1_TL Brightfield.tif'], use_dask=False, stack=True)
    209             if shape is None:
--> 210                 image = imread(filename)
        image = undefined
        global imread = <function imread at 0x2A230850>
        filename = 'C:\\Users\\shahv\\Pictures\\2020_06_17__8256-Image Export-01\\2020_06_17__8256-Image Export-01_s1_TL Brightfield.tif'
    211                 shape = image.shape

c:\users\shahv\appdata\local\programs\python\python38-32\lib\site-packages\napari\utils\io.py in imread(filename=r'C:\Users\shahv\Pictures\2020_06_17__8256-Image E...06_17__8256-Image Export-01_s1_TL Brightfield.tif')
    107 
--> 108         return tifffile.imread(filename)
        tifffile.imread = <function imread at 0x3B209DF0>
        filename = 'C:\\Users\\shahv\\Pictures\\2020_06_17__8256-Image Export-01\\2020_06_17__8256-Image Export-01_s1_TL Brightfield.tif'
    109     else:

c:\users\shahv\appdata\local\programs\python\python38-32\lib\site-packages\tifffile\tifffile.py in imread(files=r'C:\Users\shahv\Pictures\2020_06_17__8256-Image E...06_17__8256-Image Export-01_s1_TL Brightfield.tif', **kwargs={})
    676             with TiffFile(files, **kwargs_file) as tif:
--> 677                 return tif.asarray(**kwargs)
        tif.asarray = <bound method TiffFile.asarray of <tifffile.tifffile.TiffFile object at 0x2EBEFFE8>>
        kwargs = {}
    678 

c:\users\shahv\appdata\local\programs\python\python38-32\lib\site-packages\tifffile\tifffile.py in asarray(self=<tifffile.tifffile.TiffFile object>, key=None, series=<tifffile.tifffile.TiffPageSeries object>, level=None, out=None, maxworkers=None)
   2471         elif len(pages) == 1:
-> 2472             result = pages[0].asarray(out=out, maxworkers=maxworkers)
        result = undefined
        global pages.asarray = undefined
        out = None
        maxworkers = None
   2473         else:

c:\users\shahv\appdata\local\programs\python\python38-32\lib\site-packages\tifffile\tifffile.py in asarray(self=<tifffile.tifffile.TiffPage object>, out=None, squeeze=True, lock=<tifffile.tifffile.NullContext object>, reopen=True, maxworkers=None)
   5175             # decode individual strips or tiles
-> 5176             result = create_output(out, keyframe.shaped, keyframe._dtype)
        result = undefined
        global create_output = <function create_output at 0x2E0F77C0>
        out = None
        keyframe.shaped = (1, 1, 1, 73600, 56329, 3)
        keyframe._dtype = dtype('uint8')
   5177             out = result[0]

c:\users\shahv\appdata\local\programs\python\python38-32\lib\site-packages\tifffile\tifffile.py in create_output(out=None, shape=(1, 1, 1, 73600, 56329, 3), dtype=dtype('uint8'), mode='w+', suffix=None)
  11997     if out is None:
> 11998         return numpy.zeros(shape, dtype)
        global numpy.zeros = <built-in function zeros>
        shape = (1, 1, 1, 73600, 56329, 3)
        dtype = dtype('uint8')
  11999     if isinstance(out, str) and out[:6] == 'memmap':

ValueError: array is too big; `arr.size * arr.dtype.itemsize` is larger than the maximum possible size.

The above exception was the direct cause of the following exception:

PluginCallError                           Traceback (most recent call last)
PluginCallError: Error in plugin 'builtins', hook 'napari_get_reader': array is too big; `arr.size * arr.dtype.itemsize` is larger than the maximum possible size.
================================================================================

**Comment by tlambert03** [comment]
Kinda looks like a memory error.  how much RAM do you have on this computer?

**Comment by cgohlke** [comment]
> `python38-32`

That's 32-bit Python, which is limited to <2 GB arrays.

**Comment by tlambert03** [comment]
Ah sharp eye! Thanks as always @cgohlke!

**Comment by megturn** [comment]
Thanks so much!
