### ISSUE TITLE
Error handling design

### ISSUE THREAD

**Issue by liaprins-czi** [napari/napari#1501]
napari needs consistent way(s) to surface various error types to the user. This issue relates to #1395 and #1090 

There are a few different categories errors can fall into that should be considered:

### Severity levels
**Critical error** = (How would we define critical? For MVP we might not worry about distinguishing between critical and non-critical.)

**Non-critical error** = Not critical, but still a problem

**Informational alert** = (Out of scope for now because these are not actually errors, but can be good to keep in mind when designing error messages.) Not causing a problem, but something for user to be aware of. E.g. we may want to warn them that an action they are seeking to take is destructive and cannot be undone; ideally however we'd always allow undoing

### Cause
**Unanticipated** = Caused by unforeseen bug in code, for example

**Anticipated** = Caused by user action; user trying to do something not possible or not allowed

### “Origin”
**napari UI** = Inherent to actions/functionality available from within the core napari GUI

**napari console** = Inherent to actions/functionality in the napari console, and related to core napari itself

**Plugin UI** = Inherent to actions/functionality available from within the plugin’s GUI. (Not sure if plugins are in scope for this work, but if we have control over their error messages, ideally they'd fit into similar visual patterns we use for the napari core error messages.)

**Plugin console** = Inherent to actions/functionality in the napari console, and related to the plugin (not to core napari)

### Error type permutations
Based on combining the above categories, I started to identify what we should surface to the user for each possible combination of error types (e.g. critical x unantipated x napari UI) as well as preliminary ideas for how to message the user about the error visually. The following screenshots show tables holding this analysis, and can be viewed as a PDF:
[Error handling.pdf](https://github.com/napari/napari/files/4973666/Error.handling.pdf)

Something that would greatly help to design a holistic error handling system long-term would be to have documented errors for each of these error type permutations (in the tables below most are empty because I don't know of very many yet).

![Error handling-2](https://user-images.githubusercontent.com/53277128/88422926-d1b4c280-cd9f-11ea-922a-3093d03bf0b0.png)
![Error handling-3](https://user-images.githubusercontent.com/53277128/88422930-d37e8600-cd9f-11ea-897c-36054be4e0e8.png)
![Error handling-4](https://user-images.githubusercontent.com/53277128/88422932-d4afb300-cd9f-11ea-983c-befde6ef3256.png)
![Error handling-5](https://user-images.githubusercontent.com/53277128/88422934-d4afb300-cd9f-11ea-83fa-2401b8632e16.png)
![Error handling-6](https://user-images.githubusercontent.com/53277128/88422937-d5484980-cd9f-11ea-8298-be66e9eb5cc1.png)
![Error handling-7](https://user-images.githubusercontent.com/53277128/88422938-d5e0e000-cd9f-11ea-8694-24e4cf3df548.png)
![Error handling-8](https://user-images.githubusercontent.com/53277128/88422940-d5e0e000-cd9f-11ea-91d2-53d45dec82c2.png)
![Error handling-9](https://user-images.githubusercontent.com/53277128/88422942-d6797680-cd9f-11ea-9025-cedfd8ba4108.png)

### Messaging types
The above error type permuation analysis helped me to determines which slices could benefit from similar messaging types. These message types can be applied as templates across multiple error type permutations that have certain things in common (e.g. where user's focus is when error occurs: console vs general UI, etc). The below screenshots show my current thinking around which error types should map to which message types.

Note: Having concrete examples of each error type permutation would help to validate those I think don't/shouldn't even exist, and would also help to develop the message templates and what sort of information we'd be able to pull in when communicating about the error with the user.

![Screen Shot 2020-07-24 at 11 12 32 AM](https://user-images.githubusercontent.com/53277128/88423517-bdbd9080-cda0-11ea-93a2-2b976a70548c.png)
![Screen Shot 2020-07-24 at 11 12 46 AM](https://user-images.githubusercontent.com/53277128/88423522-beeebd80-cda0-11ea-96fd-250d0701846f.png)

### Questions
There are several questions noted in the [Error handling.pdf](https://github.com/napari/napari/files/4973666/Error.handling.pdf) document (and in the "Questions/comments" sections of the tables in the screenshots above) which would help to paint a more complete picture of the current error scene in napari, as well as what we have control over, etc, and would in turn help to design a more complete and considered experience. However, the following are the most important for developing a shorter term MVP:
- What constitutes critical? 
- Will we be able to tell if an unanticipated error meets our criteria for critical, or does the fact that it’s unanticipated mean we know nothing about it?
- Should we even have critical vs non-critical error levels, or just one level? _For now, I am assuming one level of error._
- How much can we know about errors caused by an external plugin? _For now, I am just designing messaging for napari-core errors, but ideally plugin errors could fit into similar template(s)._

### Next steps
- [x] Iterate designs per messaging group type
- [x] Get feedback
- [x] Finalize designs
- [x] Document final designs

**Comment by liaprins-czi** [comment]
Update: Here's a link to my latest Figma explorations:
https://www.figma.com/file/Aq1PhG2tVTodGZnSBe0nui/Error-Handling?node-id=0%3A1

I tried several locations for where errors could appear, and added some comments about my initial thoughts. (You can press the "c" key to see the comments or add your own.) It'd be great to get any feedback via the Figma comments or if it's easier can add them to this issue.

I will probably make a new Figma page and narrow down options after I've let the ideas settle in my mind over the weekend, and hopefully can get some feedback from others to incorporate as well. Thanks!

**Comment by liaprins-czi** [comment]
Here's a link to the Figma page where I've narrowed down some of the designs:https://www.figma.com/file/Aq1PhG2tVTodGZnSBe0nui/Error-Handling?node-id=0%3A1

And here's a link to a prototype of how the error message for anticipated errors (e.g. user drags wrong file type onto canvas) could appear and act:
https://www.figma.com/proto/Aq1PhG2tVTodGZnSBe0nui/Error-Handling?node-id=22%3A36&viewport=-1934%2C203%2C2&scaling=min-zoom
And lastly a prototype showing how we could prompt users to submit a GH issue to napari's GH if an unanticipated error occurs:
https://www.figma.com/proto/Aq1PhG2tVTodGZnSBe0nui/Error-Handling?node-id=22%3A111&viewport=-3971%2C429%2C1&scaling=min-zoom

I still have some questions though in terms of what specific content we will be able to surface to the user about the error (if anything, and if so, would it be useful to?), as well as what our limitations are for the GH issue submission and what content that pane would need (do we need to have a user log into the GH account first? How would that work? Any other important information I am missing?).

**Comment by sofroniewn** [comment]
These are so beautiful @liaprins-czi!!!

For the github submission right now our error dialog looks like this and then clicking on github opens it like this if i am logged in. i'm pretty sure you get sent to a signup / login page if you aren't logged in.

![image](https://user-images.githubusercontent.com/6531703/88584567-ab449080-d006-11ea-877c-284fef5876db.png)

and

![image](https://user-images.githubusercontent.com/6531703/88584590-b697bc00-d006-11ea-9996-ab29c54cc205.png)

we might want to include some more of the information in the napari info panel, especially if automatically done, but we might not want to overwhelm people either!!
 
<img src="https://user-images.githubusercontent.com/6531703/88584643-cfa06d00-d006-11ea-9452-3da018132976.png" height="512">

We might want to include that system info/ extension info in an explicit opt-in fashion - see the bottom left in this VScode dialog

<img src="https://user-images.githubusercontent.com/6531703/88584768-05ddec80-d007-11ea-9099-28ad38226db6.png" height="512">

Maybe @tlambert03 has further ideas here as he created that initial report on github dialog.

**Comment by sofroniewn** [comment]
Also @tlambert03 what was the Qt element you were thinking for this display in the bottom right? 
![image](https://user-images.githubusercontent.com/6531703/88585028-679e5680-d007-11ea-9699-0540d7e0c1ad.png)

can you link to it?

**Comment by tlambert03** [comment]
> do we need to have a user log into the GH account first?

there is a slight issue here.  Since we are encoding the message in the URL there, there is a character limit (5910 chars) to the body of the bug report if the user is not logged in.  So, in _some_ cases, they will have to re-submit after logging in.  Otherwise it will forward them correctly to the page (with bug report intact) after login.  see https://github.com/napari/napari/pull/1024#issuecomment-598262057 for original discussion.

> Also @tlambert03 what was the Qt element you were thinking for this display in the bottom right?

I was mentioning the [`Qt::Sheet` window flag](https://doc.qt.io/qt-5/qt.html#WindowType-enum) which provides a lovely slide-in animation.  However, as mentioned it's macOS only... and it also implies a modal dialog.  So it's probably not worth looking into, and we may instead want to spend some time rolling our own custom dialog that slides in using [`QPropertyAnimation`](https://doc.qt.io/qt-5/qpropertyanimation.html) and fades out on a timer.
