### ISSUE TITLE
Multiple viewers on a layer: tracebacks when closing a viewer

### ISSUE THREAD

**Issue by jni** [napari/napari#1503]
## 🐛 Bug

It's unclear whether this should be an officially supported feature, but probably it should be!

Creating a layer outside of the viewer, and then adding it to *two different* viewers seems to work fine. The layer attributes are perfectly synchronised, and changing e.g. the colormap on one viewer changes it in both. Which is excellent!

However, when one of the viewers is closed, I start to get tracebacks. I *think* it's because we don't *un*subscribe the events for the deleted viewer — if so, could be an easy fix! (And might tie into #1500.)

## To Reproduce

```python
from skimage import data
import napari

image = data.camera()
imlayer = napari.layers.Image(image)

with napari.gui_qt():
    v1 = napari.Viewer()
    v1.add_layer(imlayer)
    v2 = napari.Viewer()
    v2.add_layer(imlayer)
```

**Comment by sofroniewn** [comment]
While this is not address in #1955 it could be solved in a follow-up. That PR will allow you to remove and add layers to the same viewer. Removing the layer will cause all events to get disconnected.

The next step would instead be to specifically remove every single event that we add and no more. That would be a good goal, but I think should come in a new PR. At the point, when combined with #1500 we should have this fixed
