### ISSUE TITLE
Label editing and creation with scale keyword

### ISSUE THREAD

**Issue by kapoorlab** [napari/napari#1508]
## 🐛 Bug

When trying to edit the labels in Napari setting scale attribute in view_image prohibits editing and drawing of the labels.

## To Reproduce

1.  You can open an example image with its labels and then use this code 

`      
scaleZ = 1
scaleX = 0.16
scaleY = 0.16                  
with napari.gui_qt():

                            viewer = napari.view_image(image, name='Raw', rgb=False, scale=[scaleZ, scaleX, scaleY]) 
                            label_layer = viewer.add_labels(labels, name='Label', scale=[scaleZ, scaleX, scaleY]) `
## Expected behavior

Editing and drawing with scaled co ordinates.

## Environment

`
napari: 0.3.6
Platform: Darwin-18.7.0-x86_64-i386-64bit
Python: 3.7.3 (default, Mar 27 2019, 16:54:48)  [Clang 4.0.1 (tags/RELEASE_401/final)]
Qt: 5.14.2
PyQt5: 5.14.2
NumPy: 1.19.1
SciPy: 1.5.2
Dask: 2.21.0
VisPy: 0.6.4

GL version:  2.1 INTEL-12.10.12
MAX_TEXTURE_SIZE: 16384

Plugins:
  - napari-plugin-engine: 0.1.6
  - svg: 0.1.3
`

**Comment by sofroniewn** [comment]
Thanks for flagging this, we will look in soon!

**Comment by sofroniewn** [comment]
Hi @kapoorlab, sorry it's taken so long to get back to you on this one! I can confirm that this is still a bug, easy to reproduce with the following code:

```python
with napari.gui_qt():
    image = np.random.random((5, 128, 128))
    labels = np.zeros((5, 128, 128))
    scale = [1, 0.16, 0.16]
    viewer = napari.view_image(image, name='Raw', rgb=False, scale=scale) 
    label_layer = viewer.add_labels(labels, name='Label', scale=scale)
```

We're doing a lot right now to clean up our world coordinate system ahead of our `0.4.0` release, and I will get to this as soon as #854 has merged. We should have it fixed soon. Thanks for your patience!!
