### ISSUE TITLE
napari.utils.list could use better documentation

### ISSUE THREAD

**Issue by pwinston** [napari/napari#1512]
## 📚 Documentation

All the files in `napari.utils.list` are pretty sparsely documented. See for example `TypedList.index` where there is no doc string and it's not easy to understand what it even does:
https://github.com/napari/napari/blob/master/napari/utils/list/_typed.py#L59-L84

Also the variable names could be clearer, the last line of the method is: `q = e`.

The class docstring is not very clear either, I'm not sure what "allow indexing with their unique properties" really means.

**Comment by tlambert03** [comment]
agreed.
for what it's worth... that whole folder will hopefully be replaced by #1444 ... so if you're using `TypedList` as a component in a new class, you might consider trying to use `TypedEventedList` from #1444.  It too probably needs a bit more documentation before merge.

> I'm not sure what "allow indexing with their unique properties" really means.

also agreed.  I know your point here was not to ask "what does it mean?", but rather to say we should have this in the docstring of the class.  But to answer the question anyway, it means that you can provide a `lookup` function that lets you index into the list using something other than a number.  This is the mechanism behind indexing the LayerList with the `str` layer name `viewer.layers['layer name']`.

**Comment by sofroniewn** [comment]
This class was removed in #1859
