### ISSUE TITLE
Button to open console shouldn't exist if viewer launched from IPython

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#1531]
## 🐛 Bug

As noted in https://github.com/napari/napari/issues/787#issuecomment-564829450 the button to open the console should not exist if the viewer is launched from IPython as the console is not supported there (there is no need for it as the IPython terminal functions as the console).

We could consider blocking the console and disabling the button from Jupyter too.

**Comment by andy-sweet** [comment]
Hiding the console button when launching from IPython is easy enough, given the logic we have in `QtConsole.__init__` to detect the type of console works. If we do hide the button, I also expect to hide the console on initialization if it is showing from the last session.

Should we also disable the keyboard shortcut (by default `Ctrl + Shift + C`)? 
If so, is it sufficient to call `action_manager.unbind_shortcut('napari:toggle_console_visibility')` to do that? Or should we keep the binding, but find some way to disable its behavior?

**Comment by sofroniewn** [comment]
> Should we also disable the keyboard shortcut (by default Ctrl + Shift + C)?

Yes i think so.

@jni is a big ipython user and I think has wanted this for a long time
