### ISSUE TITLE
RuntimeWarning when creating empty points

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#1536]
## 🐛 Bug
not a bug exactly, but a runtime warning that users will now see when creating empty points after #1360 

```python
In [1]: viewer = napari.Viewer()     

In [2]: viewer.add_points()    
napari/napari/components/layerlist.py:209: RuntimeWarning: All-NaN axis encountered
  min_v = np.nanmin(
napari/napari/components/layerlist.py:212: RuntimeWarning: All-NaN axis encountered
  max_v = np.nanmax(
```

@sofroniewn, would it be possible to catch the all-NaN cases before running np.nanmax/min here?

https://github.com/napari/napari/blob/2315443d9bd4fb6b8cc30967cf433d017f7c8ca2/napari/components/layerlist.py#L209-L214

**Comment by sofroniewn** [comment]
Yup, that shouldn't have happened. I'll look into fixing. Thanks for the catch.
