### ISSUE TITLE
Colormap dropdown should be disabled for rgb images

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#1542]
## 🚀 Feature
The colormap dropdown in the top left corner should be disabled/ hidden for rgb images. Now it just shows `gray` which is not accurate

![image](https://user-images.githubusercontent.com/6531703/89918784-52046180-dbaf-11ea-8455-ec2a843d8b30.png)

## Additional context

napari 0.3.6

**Comment by ekdnam** [comment]
Can I work on this?

**Comment by sofroniewn** [comment]
> Can I work on this?

Yes, that would be great, a PR would be very welcome. Feel free to checkout out our [contributing guide](https://napari.org/docs/developers/CONTRIBUTING.html) if you havn't already.

**Comment by ekdnam** [comment]
Okay sure

**Comment by ekdnam** [comment]
Okay sure!

**Comment by ekdnam** [comment]
how can the parameters of the `view_image` function be modified? and also the colormap dropdown menu? in the `view_layers.py` script, it is said that the `view_image` function is auto-generated

**Comment by sofroniewn** [comment]
Hi @ekdnam you shouldn't need to modify view_image. Instead you could just add an if statement looking at the `layer.rgb` and if `True` not add the colormap widget to the qt controls for the image layer here https://github.com/napari/napari/blob/master/napari/_qt/layer_controls/qt_image_controls.py#L101-L102.

You could then add a test in a new file called `test_qt_image_layer.py`, similar to this file that tests that when an image is rgb the colormap dropdown has not been added. https://github.com/napari/napari/blob/master/napari/_qt/layer_controls/_tests/test_qt_image_base_layer_.py

I think having the dropdown not even get added is probably better than having it disabled, but you might want to try both to see

**Comment by ekdnam** [comment]
Okay. Will do so. Thanks

**Comment by ekdnam** [comment]
Hi @sofroniewn . I have removed the dropdown as well as the 'Colormap' label. But can't remove this ->
![napari-colormap-dropdown](https://user-images.githubusercontent.com/40426312/91309155-e258be00-e7cd-11ea-8c6f-410658a48bcc.jpg)

Which function / statement controls this icon? I declared the `colormapLayout` object such that it gets created only when `layer.rgb == False`, but then the icon gets shifted to the top layout corner. Sorry if I am needing a lot of help, I am new to GUI development and testing :)

**Comment by sofroniewn** [comment]
That object is the colorbarLabel, here https://github.com/napari/napari/blob/master/napari/_qt/layer_controls/qt_image_controls.py#L89. Preventing adding the colormap_layout should prevent adding both the dropdown and the colorbar. Do you want to make a pull request with what you have so far and then I can give you more detailed help on the PR

**Comment by ekdnam** [comment]
Okay sure will create a  PR

**Comment by sofroniewn** [comment]
Close by #1586
