### ISSUE TITLE
Add split layer/ group layers shortcuts/ button 

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#1543]
## 🚀 Feature
Following #1322 we should add some GUI button or keyboard short cuts to split/ combine layers

**Comment by psobolewskiPhD** [comment]
@sofroniewn 
Split Stack and Merge Stack are both available in the layer contextual menu.
https://github.com/napari/napari/pull/2556
Does that resolve this issue?

**Comment by psobolewskiPhD** [comment]
These are now also pretty well documented, see: 
https://napari.org/stable/tutorials/fundamentals/viewer.html#right-click-menu

So I'm going to close.
