### ISSUE TITLE
Wrong intensity values in status bar for automatically down-sampled images.

### ISSUE THREAD

**Issue by MaksHess** [napari/napari#1557]
## 🐛 Bug

When displaying a 2D image larger than 'GL_MAX_TEXTURE_SIZE', it is automatically downsampled. While the coordinate values displayed in the status bar are correct, the intensity values that are shown don't take the downsampling into account.

## To Reproduce

1. Create a 2D image larger than 'GL_MAX_TEXTURE_SIZE'.
2. Hover over the image and notice that the intensity values displayed in the status bar correspond to a 'larger' image than the one displayed (i. e. are not taking the downsampling into account).

```Python
gl_max_texture_size = 16384 # insert hardware specific gl_max_texture_size
img = np.zeros((gl_max_texture_size*2, gl_max_texture_size*2), dtype=np.uint16) # create an empty image twice as large
img[img.shape[0]//2:, img.shape[1]//2:] = 1 # set the bottom right corner to 1

with napari.gui_qt():
    viewer = napari.Viewer()
    viewer.add_image(img, colormap='viridis')
```
## Expected behavior

Intensity values displayed in the status bar should correspond to the image on display.

## Environment

napari: 0.3.6
Platform: Windows-10-10.0.18362-SP0
Python: 3.7.6 | packaged by conda-forge | (default, Mar 23 2020, 22:22:21) [MSC v.1916 64 bit (AMD64)]
Qt: 5.14.2
PyQt5: 5.14.2
NumPy: 1.18.3
SciPy: 1.4.1
Dask: 2.15.0
VisPy: 0.6.4

GL version: 4.6.0 - Build 26.20.100.7812
MAX_TEXTURE_SIZE: 16384

Plugins:
- napari-plugin-engine: 0.1.5
- napari_bug
- svg: 0.1.3

## Additional context

While creating a reproducible example I noticed that if I use `dtype=np.uint8` with that same example there seems to be a display bug _in addition_ to the bug in the status bar (i. e. the whole image is displayed as 0).

**Comment by sofroniewn** [comment]
Thanks for this report, this does sound like a bug! We will look into it promptly

**Comment by MaksHess** [comment]
Hi Nicholas,

I had some time to further look into the bug today. I found a simple fix by changing one line in `napari.layers.image.image.Image._get_value` :

```Python
coord = np.round(self.coordinates).astype(int) #old
coord = np.round(self._transforms(self.coordinates)).astype(int) #new
```

Piping the coordinates through the layer transforms seemed to do the trick. There might be similar bugs in other layers that override `_get_value`.

Cheers Maks

**Comment by sofroniewn** [comment]
> Piping the coordinates through the layer transforms seemed to do the trick. There might be similar bugs in other layers that override _get_value.

That makes sense to me, thanks for digging in! We'd love a PR with a fix for this bug and a test to check it.

You could start with just one for the Image layer, but you might want to look at those other layers too.

Thanks!!
