### ISSUE TITLE
add timeout option to thread_worker

### ISSUE THREAD

**Issue by quantumjot** [napari/napari#1559]
## 🚀 Feature
Add a timeout to the thread_worker decorator

## Motivation

Some computations do not have a guaranteed run time (e.g. optimization problems), and can consume all available compute. Running this inside of a thread worker can lead to the GUI becoming unresponsive. It would be really useful to have the option to set an upper limit on acceptable duration, before the thread gracefully(?) terminates. 

As a concrete example, performing optimization (using `cvxopt`) with a poor guess at initial bounds can take hours to complete, where it should take a few seconds. During that time, the GUI is totally unresponsive. It would be useful to have the option to hand back to the user in the former case.

## Pitch

Add a keyword argument that describes the maximum time allocated to this thread to complete the computation, e.g.
```python
@thread_worker(timeout=60)
def some_optimization_function():
    ...

worker = some_optimization_function()
worker.timeout.connect(feedback_to_user)
```
## Alternatives

I can get around this problem by launching a separate process with a timeout, but this solution may not work for all problems.

**Comment by sofroniewn** [comment]
This seems like a very reasonable request. @AhmetCanSolak @Czaki have done a fair amount with threads in napari, I'm curious if they have any additional input on this?

@quantumjot sounds this should like it should be a fairly self contained addition to [our qthreading code](https://github.com/napari/napari/blob/3297bfabe36ab7b526d41aefc80ef503bf81450c/napari/_qt/qthreading.py), is it something that you want to make a PR for? Would you need help getting started?

**Comment by Czaki** [comment]
hmm. 
Any calculation which is running in non main thread should not block GUI. 
But it sometimes happen. I meet such behavior when running C++ code when execution stuck in C++ code. In my case it looks like GIL is locked and no Python code could be executed. So python solution which should kill calculation will not work. 

I hope I'm wrong but all solution should be carefully tested. 

I wish this could be done.

One option which I see is to implement this is to create separate process (using multiprocessing) which will sent signals (but still not sure what with GIL).

**Comment by quantumjot** [comment]
@Czaki - that's exactly the situation I'm running in to, and I also think the GIL is the problem. Spawning a separate process (using multiprocessing) works and does not block, but I have a feeling that this may be a huge can of worms...

**Comment by Czaki** [comment]
So I modify my c++ code to add limitations in it and get fast stop. 

You could Check QThread interface, but I do not found timeout option for it. And GIL probably will block python code which could kill such thread.

**Comment by quantumjot** [comment]
I took a look at both QThread and QRunnable, there's no timeout for either. I've seen a few implementations of a timeout method that uses a separate QTimer object, but I don't like these options very much.

I agree that the best option is to not have code that blocks in the first place. In this case I was having difficulty with third-party libraries (like `GLPK`) - however, I notice the python bindings now expose solver options (including a timeout!) - so I'm not sure this is strictly necessary now, since the solver can timeout after a couple of minutes. It still blocks the GUI during that time though.

I feel like the pain of implementing this may out-weigh the benefit.  Curious if anyone else has experience/ input on this, or thinks this would be a useful feature.

**Comment by Czaki** [comment]
But GLPK could be easy move to separate process? If I good remember its result is single float?

**Comment by quantumjot** [comment]
> But GLPK could be easy move to separate process?

Yes, I can spawn a separate process, and use the solver's own timeout - everything works as expected then.

@sofroniewn - I don't know if it's worth putting time in to this atm, given the complexity/payoff. Happy for it to be closed unless others feel strongly that it is useful.

**Comment by sofroniewn** [comment]
> @sofroniewn - I don't know if it's worth putting time in to this atm, given the complexity/payoff. Happy for it to be closed unless others feel strongly that it is useful.

Ok, sounds good. I will leave this open for a little in case anyone else wants to comment, and then if it gets no comments we can close and always reopen if people want, but thanks @quantumjot for putting it out there and thanks @Czaki for diving in with some comments!

**Comment by Czaki** [comment]
@sofroniewn qthreading is created to simplify run calculation in thread. So maybe it is good idea to create such simple interface for multiprocessing where thread will wait on on result and then call signals?

**Comment by AhmetCanSolak** [comment]
Hi everyone, I followed the discussion and I don't see any other solution than going for a multiprocessing implementation for the stuck code which locks GIL. 

For the non-stucking thread code this suggestion still can make sense. If there is interest maybe we can consider.

**Comment by AhmetCanSolak** [comment]
Hi everyone, little late to party. I followed the discussion and I do not have any better solution for the stuck code in separate thread which locks GIL. As you folks discussed I would go for a multiprocessing implementation for such problem.
