### ISSUE TITLE
napari cannot be run interactively in nbclient

### ISSUE THREAD

**Issue by jni** [napari/napari#1568]
## 🐛 Bug

This isn't a napari specific thing, but it could be a blocker for our docs, so I'm creating an issue here so we can track it.

I have been experimenting with [Jupyter Book](https://jupyterbook.org/intro.html) for the scikit-image tutorials. It's pretty cool, you can write materials in a bunch of formats (Jupyter notebooks, Jupytext, markdown, MyST...), and Book compiles them all into a single website. Even better, you can hide certain input/output cells or even remove them altogether (ie have the code not appear on the page, only the output). So I think it's actually a great thing for reproducible napari demos because you can do:

Cell 1:

```python
v = napari.Viewer()
layer = v.add_image(data)
```

(Narrative text telling user to annotate points interactively.)

Cell 2 (hidden or removed):

```
pts = np.array([[...]])
v.add_points(pts)
v.dims.set_point(<some interesting coordinate>)
napari.nbscreenshot(v)
```

However, it's currently impossible to do this because nbclient doesn't work with notebooks that have `%gui qt`. See these issues:

https://github.com/executablebooks/jupyter-book/issues/840
https://github.com/jupyter/nbclient/issues/97

I think this is a critical part of our ecosystem to fix, because having this working would make it easy to produce very high quality docs automatically with our CI.

I have *not* yet tried to see whether using `napari.gui_qt()` instead of the magic would work, but it wouldn't be ideal, because then our notebooks would differ from real-world usage. If it *does* work and the above problems with nbclient turn out to be intractable, an alternative could be to create a sphinx post-processor that adds `%gui qt` to the top of a notebook and removes and unindents all `gui_qt()` blocks...

**Comment by liu-ziyang** [comment]
fwiw, I tried using the `with napari.gui_qt()` context manager approach and works fine in the jupyter 

However I did not manage to reproduce the nbclient issue, when I try to run the example with magic like this: 
```
%gui qt

from skimage import data
import napari

v = napari.Viewer()
layer = v.add_image(data.astronaut())
```
I still see the same error as if I didn't add the magic: 
```
RuntimeError: napari requires a Qt event loop to run. To create one, try one of the following: 
  - use the `napari.gui_qt()` context manager. See https://github.com/napari/napari/tree/master/examples for usage examples.
  - In IPython or a local Jupyter instance, use the `%gui qt` magic command.
  - Launch IPython with the option `--gui=qt`.
  - (recommended) in your IPython configuration file, add or uncomment the line `c.TerminalIPythonApp.gui = 'qt'`. Then, restart IPython.
```

can you please maybe share your setup so I can reproduce from there?

**Comment by GenevieveBuckley** [comment]
I would have thought this would work, but it didn't :(

```
from ipykernel.kernelapp import IPKernelApp
kernel = IPKernelApp.instance()
kernel.initialize(['python', '--gui=qt'])

>python
Python 3.7.9 (default, Aug 31 2020, 17:10:11) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from ipykernel.kernelapp import IPKernelApp
>>> kernel = IPKernelApp.instance()
>>> kernel.initialize(['python', '--gui=qt'])
NOTE: When using the `ipython kernel` entry point, Ctrl-C will not work.

To exit, you will have to explicitly quit this process, by either sending
"quit" from a client, or using Ctrl-\ in UNIX-like environments.

To read more about this, see https://github.com/ipython/ipython/issues/2049


To connect another client to this kernel, use:
    --existing kernel-66600.json
In : import napari
In : viewer = napari.Viewer()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\users\genevieve\documents\github\napari\napari\viewer.py", line 68, in __init__
    raise RuntimeError(message)
RuntimeError: napari requires a Qt event loop to run. To create one, try one of the following:
  - use the `napari.gui_qt()` context manager. See https://github.com/napari/napari/tree/master/examples for usage examples.
  - In IPython or a local Jupyter instance, use the `%gui qt` magic command.
  - Launch IPython with the option `--gui=qt`.
  - (recommended) in your IPython configuration file, add or uncomment the line `c.TerminalIPythonApp.gui = 'qt'`. Then, restart IPython.
In :

```

**Comment by GenevieveBuckley** [comment]
It's possible we might also run into this problem with PySide2 and environment variables: https://github.com/ipython/ipykernel/issues/398
If we do, there is a PR attempting to address it here: https://github.com/ipython/ipykernel/pull/444

**Comment by GenevieveBuckley** [comment]
Exciting news! If we use [runipy](https://github.com/paulgb/runipy)* to execute jupyter notebooks we can finally run them with the `%gui qt` magic. (See the discussion [here](https://github.com/jupyter/nbclient/issues/97#issuecomment-716366259) for more details) 🚀 🚀 🚀 

*Note: runipy is no longer maintained, but it's very small so we could potentially maintain a fork of it in the napari org. I'd say the benefits would be worth it.

```
pip install runipy
runipy example-notebook.ipynb
```

```python
# cell 1
%gui qt

# cell 2 - this MUST be in a separate cell after the qt magic above, you can't combine these two into one cell
import time
time.sleep(5)

# cell 3
import napari
viewer = napari.Viewer()
```

**Comment by GenevieveBuckley** [comment]
I think I tried runipy earlier, but wasn't vigilant about always having `time.sleep` in a separate cell. This part is important!

**Comment by GenevieveBuckley** [comment]
Related discussion:
* https://github.com/napari/napari/issues/1387
* https://github.com/napari/tutorials/issues/70

**Comment by GenevieveBuckley** [comment]
So the problem with nbclient is that we need a separate `time.sleep(1)` cell, that comes *after* the cell with the `%gui qt` magic, and *before* the cell where we import napari. The magic is an asynchronous process, and for reasons that remain mysterious to me you can't put the sleep in the same cell as the magic.

This works:
```python
# cell 1
%gui qt

# cell 2
import time
time.sleep(1)

# cell 3
import napari
from napari.utils import nbscreenshot
viewer = napari.Viewer()
nbscreenshot(viewer)

# final cell
viewer.close()
```

We can hide cells 1 and 2 in our docs if we like, that's what I've done in the template notebook included here:
https://github.com/napari/tutorials/pull/95
