### ISSUE TITLE
Plugin Errors not work in develop 

### ISSUE THREAD

**Issue by Czaki** [napari/napari#1569]
## 🐛 Bug

$ NAPARI_CATCH_ERRORS=0 python -m napari
16:11:17 ERROR Unhandled exception:
Traceback (most recent call last):
  File "/home/czaki/Dokumenty/projekty/napari/napari/_qt/qt_main_window.py", line 300, in _show_plugin_err_reporter
    plugin_sorter = QtPluginErrReporter(parent=self._qt_window)
  File "/home/czaki/Dokumenty/projekty/napari/napari/_qt/dialogs/qt_plugin_report.py", line 62, in __init__
    from ..plugins import plugin_manager as _pm
ModuleNotFoundError: No module named 'napari._qt.plugins'

## To Reproduce

1. install last napari from github
2. try open "Plugin Errors" dialog

## Environment

 - Please copy and paste the information at napari info option in help menubar here:

napari: 0.3.7.dev30+gf101ef7
Platform: Linux-4.15.0-112-generic-x86_64-with-debian-buster-sid
Python: 3.7.6 (default, Feb 20 2020, 10:04:45) [GCC 7.4.0]
Qt: 5.14.2
PyQt5: 5.14.2
NumPy: 1.18.5
SciPy: 1.4.1
Dask: 2.17.2
VisPy: 0.6.4

GL version: 4.6.0 NVIDIA 440.100
MAX_TEXTURE_SIZE: 32768

Plugins:
- napari-plugin-engine: 0.1.5
- svg: 0.1.3

 - Any other relevant information:

## Additional context

@sofroniewn @jni

**Comment by sofroniewn** [comment]
Looks like this relates to a reorg of the qt files in #1431 and some additional nesting. Should be an easy fix to `from ...plugins import plugin_manager as _pm` but I'd want to check first. A PR with a test would be very welcome @Czaki, sorry about the bug!

**Comment by Czaki** [comment]
I found it by accident. I'm not sure if I found time for PR before Monday. And You have plan to create next release in short time, where such bug should not appear. 

So If no one fix it earlier I will probably fix in in next week.

**Comment by sofroniewn** [comment]
> I found it by accident. I'm not sure if I found time for PR before Monday. And You have plan to create next release in short time, where such bug should not appear.
>
> So If no one fix it earlier I will probably fix in in next week.

Sounds good, thanks for letting me know!! I may quickly fix it before release. If it's still there next week, then PR welcome :-)
