### ISSUE TITLE
Defocus from axis label field on slider

### ISSUE THREAD

**Issue by d-v-b** [napari/napari#1571]
## 🐛 Bug

After selecting the axis label field to the left of an axis slider, clicking outside the text entry area does not reliably break the focus of that UI element. Clicking on the image canvas does break the focus, but adjusting the slider itself, opening the console, etc does not.

## To Reproduce

1. look at a 3d image
2. click on the axis label text entry field
3. try to break focus of the axis label field.

## Expected behavior

focus should break whenever the user clicks anywhere outside that text field.

## Environment

napari: 0.3.7.dev30+gf101ef7
Platform: macOS-10.15.5-x86_64-i386-64bit
Python: 3.8.2 (default, May 6 2020, 02:49:43) [Clang 4.0.1 (tags/RELEASE_401/final)]
Qt: 5.12.5
PyQt5: 5.12.3
NumPy: 1.18.5
SciPy: 1.4.1
Dask: 2.20.0
VisPy: 0.6.4

GL version: 2.1 ATI-3.9.15
MAX_TEXTURE_SIZE: 16384

Plugins:
- napari-plugin-engine: 0.1.5
- svg: 0.1.3

**Comment by sofroniewn** [comment]
Thanks for flagging @d-v-b, we will look into this!

**Comment by dalthviz** [comment]
Hi, I gave this a check and I was able to reproduce the issue:

![focus_before](https://user-images.githubusercontent.com/16781833/231851445-3812b1db-4901-4697-94a5-94262ff3401d.gif)

I think the focus policy for the `_QtMainWindow` needs to be set to `Qt.FocusPolicy.StrongFocus`. Adding something like `self.setFocusPolicy(Qt.FocusPolicy.StrongFocus)` at the `_QtMainWindow.__init__` makes the axis label line edit widget to loss focus when clicking outside:

![focus_after](https://user-images.githubusercontent.com/16781833/231850662-73d9c265-725d-44ef-8b6b-3d3f2c97f292.gif)

**Comment by psobolewskiPhD** [comment]
I can confirm the buggy behavior in 0.4.17
Given that that text field does not make clear it's the axis label and not the frame/slider position, it's even more confusing!

> Adding something like `self.setFocusPolicy(Qt.FocusPolicy.StrongFocus)` at the `_QtMainWindow.__init__` makes the axis label line edit widget to loss focus when clicking outside

I can also confirm this. @dalthviz do you have time to make a PR? Or would you rather I give it a shot? 
❤️

**Comment by dalthviz** [comment]
> I can also confirm this. @dalthviz do you have time to make a PR? Or would you rather I give it a shot?

I think I could open a PR until monday so, if the idea is correct, sure go ahead and do the PR :+1:  Thanks for giving this a check @psobolewskiPhD !
