### ISSUE TITLE
interaction between visibility and contrast limits

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#1585]
## 🐛 Bug

I've just found a funny bug where there appears to be an interaction between the visibility and contrast limits

## To Reproduce

1.  napari.view_image(np.random.random((200, 200)), contrast_limits=[0, 10])
2. move clim slider to be [0, 2]
3. toggle visibility off/ on
4. notice that after toggle image is very saturated. adjusting slider a tiny bit causes image to look good again

![clim_bug](https://user-images.githubusercontent.com/6531703/91382297-4be0c880-e7de-11ea-9812-9a82e3c92a65.gif)

## Environment

last commit https://github.com/napari/napari/commit/62a046de2e5009f0c9137e3fd3999fbf902928ca

**Comment by djhoese** [comment]
How do you control visibility on the vispy level? Does anything change on the underlying ImageVisual object?

**Comment by sofroniewn** [comment]
> How do you control visibility on the vispy level? Does anything change on the underlying ImageVisual object?

Just with the setting the `visible` property - see here https://github.com/napari/napari/blob/master/napari/_vispy/vispy_base_layer.py#L142 where `node` is the `ImageVisual`

Not sure if it affects both `ImageVisual` and `VolumeVisual`, need to check.

If I had to guess, I'd guess with > 90% confidence this problem would reproduce in vispy alone just by toggling visibility too
