### ISSUE TITLE
behavior of translate in view_image

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#1588]
## 🐛 Bug/Question

it's possible that I just don't understand how I should be using translate in `view_image`, but after #1360, using `translate` in `view_image` (when viewing a single volume) no longer shifts the image relative to the camera.  It _may_ be a strange case of my particular dataset that the image needed to be translated at all, but I always needed to use `translate` to get the dask map_blocks example to be centered in the frame.  Now, using translate no longer does that (see two examples below).  Lemme know if I should just be doing something different with this particular dataset, or whether translate should _always_ shift the image relative to the camera

<img width="633" alt="Screen Shot 2020-08-27 at 4 01 51 PM" src="https://user-images.githubusercontent.com/1609449/91489665-2a83e900-e87f-11ea-8698-bb22903ea473.png">
<img width="699" alt="Screen Shot 2020-08-27 at 4 02 46 PM" src="https://user-images.githubusercontent.com/1609449/91489668-2bb51600-e87f-11ea-81e6-6a7a4470de0a.png">

**Comment by jni** [comment]
Incidentally, it's interesting that the layer list doesn't appear in the screenshot!

Other than that this is pretty concerning. 😅 Do the coordinates under the cursor make sense in both cases? That might tell us whether this is more of a camera issue or a data issue...

**Comment by tlambert03** [comment]
ok, turns out the main thing I was seeing here was due to me incorrectly updating chunk size while chaining dask `map_blocks` calls that actually modify the shape of the underlying data.  Since dask calculates the `shape` of the array based on those chunks, it resulted in a dask array that reported an incorrect shape.  It's (kinda) interesting that it all still works "fine" in napari... that is, the computed numpy array still renders correctly, but because it's not the shape that the dask array was reporting, it just gets rendered off center (in all three axes).

So, I don't think we need to change anything in napari... but it's worth "remembering" that this kind of thing can happen if the end-user is not careful about updating chunks/shape when mapping shape-modifying functions. 

here was the necessary update to the dask-napari notebook [notebook](https://github.com/tlambert03/napari-dask-example/blob/master/dask_napari.ipynb)
```python
# map and chain those functions across all dask blocks
deskewed = dask_stack.map_blocks(deskew, dtype="uint16", chunks=(1,65,256,533))
deconvolved = deskewed.map_blocks(deconv, dtype="float32", chunks=(1,64,256,525))
cropped = deconvolved.map_blocks(crop, dtype="float32", chunks=(1,62,226,500))
```
