### ISSUE TITLE
nbscreenshot not always showing layerlist

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#1596]
## 🐛 Bug
as [jni noted](https://github.com/napari/napari/issues/1588#issuecomment-682233015) from my screenshot in #1588 (shown below) ... `nbscreenshot` is sometimes not showing the layer list... and possible other inconsistencies with the viewer? 
(cropped is a dask array in this case)
<img width="699" alt="91489668-2bb51600-e87f-11ea-81e6-6a7a4470de0a" src="https://user-images.githubusercontent.com/1609449/91723832-61e9e280-eb6a-11ea-8159-84e6ebb6c652.png">

**Comment by tlambert03** [comment]
i think there's some sort of race condition, cause if I simply re-run that cell above, commenting out the new viewer, then the screenshot is correct the second time that it gets run

**Comment by sofroniewn** [comment]
@tlambert03 I have noticed this too. A race condition seems likely

**Comment by tlambert03** [comment]
just want to bump this issue again.  I was starting to create some magicgui docs, showing the result of adding a widget and layers, but it's not very helpful at the moment, since the layers don't appear (and actually I don't think added dock widgets do either?)

**Comment by sofroniewn** [comment]
For the layer list i wonder if it is because it's our own custom qscrollarea. if we used a listview it might be better. not sure if that change is worth it before the coming layer groups though.

i'm not quite sure what to do if the issue is more general. i don't have any leads right now, but i've seen this too

**Comment by tlambert03** [comment]
ahh.. it's the gd event loop (it's _always_ the gd event loop :).  This is conceptually somewhat like https://github.com/napari/napari/issues/2029 actually.

If you do something like this:
```python
viewer = napari.Viewer()
viewer.add_points(None)
viewer.window.add_dock_widget(my_widget)
nbscreenshot(viewer)
```

then at the moment that nbscreenshot is called, none of the events that have been "queued up" by lines 2 and 3 have actually been triggered... since there _is no_ event loop until `napari.run` is called.

I think we can fix it just be forcing the event loop to process with `get_app().processEvents()` inside of `_repr_png_`.  That unfortunately requires a qt import outside of the qt folder... but I think that's the compromise we have to make at the moment for the fact that we rely on qt for our entire event loop.
