### ISSUE TITLE
Add napari to the briefcase packaging success stories page

### ISSUE THREAD

**Issue by GenevieveBuckley** [napari/napari#1600]
After the napari 0.3.7 release (which includes pre-built bundled apps for Mac & Windows), we might consider adding napari to the list of "briefcase success stories" at https://briefcase.readthedocs.io/en/latest/background/success.html (as suggested by Russell).

Thoughts?

**Comment by GenevieveBuckley** [comment]
I should add, I feel relatively confident that we can sort out the issue we're having with the latest briefcase version (see https://github.com/napari/napari/pull/1599 for details)

**Comment by sofroniewn** [comment]
Yes, I'm supportive of this!! Thanks for suggesting @GenevieveBuckley

**Comment by GenevieveBuckley** [comment]
Ok, I've opened https://github.com/beeware/briefcase/pull/518 to do that.
