### ISSUE TITLE
Add testing optional extras to napari setup.cfg

### ISSUE THREAD

**Issue by jni** [napari/napari#1602]
## 🚀 Feature

When testing a release candidate, I always have to install extras from the repo, including testing extras. It would be excellent to be able to install them with `pip install napari[all,testing]`.

The relevant lines are here:

https://github.com/napari/napari/blob/42d26d66a82fbd00b9db3515c0d10e16f76a284f/setup.cfg#L70-L78

**Comment by tlambert03** [comment]
that was originally part of #1324, see [e1f3c47](https://github.com/napari/napari/commit/e1f3c477462141edb9b9a03f257c1992bf625bae#diff-380c6a8ebbbce17d55d50ef17d3cf906R66) (and the change was inspired by [this post](https://caremad.io/posts/2013/07/setup-vs-requirement/)) ... but in review it was requested to return to the `requirements/test.txt` and other requirements files.
Shall we just return to definind all the extras in `setup.cfg`?  or just the tests, but leave out `[dev]`?

**Comment by sofroniewn** [comment]
> that was originally part of #1324, see e1f3c47 (and the change was inspired by this post) ... but in review it was requested to return to the requirements/test.txt and other requirements files.
Shall we just return to definind all the extras in setup.cfg? or just the tests, but leave out [dev]?

I'm open to this suggestion, I don't have a strong opinion, but defer to others

**Comment by sofroniewn** [comment]
Reading this link that @tlambert03 posted above, it makes a lot of good points - for example

> While a library tends to want to have wide open ended version specifiers an application wants very specific dependencies. It may not have mattered up front what version of requests was installed but you want the same version to install in production as you developed and tested with locally.

but, also

> The “Library” and “Application” distinction is all well and good, but whenever you’re developing a Library, in a way it becomes your application. 

We certainly straddle this with the pip installable vs bundled app versions of napari!

> Shall we just return to definind all the extras in setup.cfg? or just the tests, but leave out [dev]?

I'd probably move everything over, especially if you feel that is most in the spirit of that post. @tlambert03 if you still feel this is the best way forward and wanted to make these changes for the `0.4.3` release I'd be supportive!!
