### ISSUE TITLE
Make color mode for label layers more informative

### ISSUE THREAD

**Issue by Czaki** [napari/napari#1603]
## 🐛 Bug

Current implementation of color mode does not provide user enough information what he should expect after change this option. 
It allow to select `direct` when user does not provide mapping dict.
With current implementation also order of changing properties produce different result in viewer which will introduce problem with  #1584 and simple screenshot of layer control widget is not enough to reproduce view settings. 

## To Reproduce

1. select `auto`
2. select `selected`
3. select `direct` 
4. select `selected` 
![napari](https://user-images.githubusercontent.com/3826210/91966470-2c7ff900-ed12-11ea-9278-b91dda298d74.gif)
 

## Expected behavior
Rendering labels layer should not depend on history

## Environment
napari 0.3.7rc1
 - Please copy and paste the information at napari info option in help menubar here:

 - Any other relevant information:

## Additional context
First information on zulip
https://napari.zulipchat.com/#narrow/stream/215289-release/topic/0.2E3.2E7/near/208787455

My suggestion is to split this widget on two. One for control selection and one for colormap. 
Or make 4 positions in this widget. 4-th one should be `select with direct`

**Comment by sofroniewn** [comment]
This is being addressed at least in part by #1762 I think, right @DragaDoncila?

**Comment by DragaDoncila** [comment]
That's right, at least the most confusing part - the `selected` mode, will be removed in favour of the checkbox

**Comment by sofroniewn** [comment]
This has been fixed by #1762 I think @Czaki and so I will close, but feel free to reopen if not fully addressed or make a new issue for the remaining parts. Thanks!!
