### ISSUE TITLE
Retrieve mouse global coordinates

### ISSUE THREAD

**Issue by horsto** [napari/napari#1614]
## 🚀 Feature
It would be great if mouse coordinates could be returned independent of the currently active layer, i.e. "globally" in respect to the displayed data. 

## Motivation

Currently mouse coordinates can be retrieved from individual layers (`layer.coordinates`) when they are active, but it is sometimes desirable to return coordinates no matter what layer is active and tie for example a `mouse_move_callback` to the whole viewer instead of individual layers. 

## Pitch

In parallel to `layer.coordinates` there could be `viewer.coordinates` or something nested within for the central canvas that returns mouse position in respect to the displayed data. 

## Alternatives

In principle right now, coordinates can be extracted from the `viewer.status` string, which contains a list `[x,y,z]` of mouse position (I am using a regex for that currently). I didn't find a more elegant alternative for that.

**Comment by sofroniewn** [comment]
Thanks for raising this issue @horsto, this is top on my priority list for our next release. I should be able to work on this over the next two weeks and will link PRs

**Comment by sofroniewn** [comment]
We're now well on our way to achieving this with the merging on #1673. `layer.position` now represents the cursor position in the global world coordinates space. We'll still want to add this to the `viewer`, but at this point it should be very easy and something that we can get in for `0.4.0`. I'll keep this updated as we get closer

**Comment by sofroniewn** [comment]
Ok, we've done this now!! Here is a description of the current API, we can continue to improve this with time

```python
viewer.cursor.position #position of cursor in world coordinates
layer.position #position of cursor in world coordinates, identical to viewer.cursor.position, gets updated whenever that changes
layer.coordinates #position of cursor in data coordinates, computed from layer.position based on transforms
```

Note if no transforms exist then data and world coordinates are identical

**Comment by horsto** [comment]
This is great, thanks so much for implementing this!
