### ISSUE TITLE
New point color off

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#1621]
## 🐛 Bug

Changing color before adding the first point to a layer doesn't cause new point to have new color 

## To Reproduce

1. Run `python examples/add_image.py`
2. Click the new points layer
3. Change the face color from white to red - see color icon change
4. Click in Add mode and add point. Point is white and color icon is now white too

## Expected behavior

Point would be red. Note that changing color to red and then adding more points give red points, this seems to affect only the first point added.

## Environment

napari 0.3.7

**Comment by sofroniewn** [comment]
@kevinyamauchi @ziyangczi @jni just flagging, this one needs to be reproduced but looks probably pretty simiple. Would be great to get it in for the 0.3.8 release which I think we'd like to do soon (will be a small bug fix release and likely our last python 3.6 release)

**Comment by kevinyamauchi** [comment]
I can take a look tomorrow!

**Comment by sofroniewn** [comment]
> I can take a look tomorrow!

Thanks @kevinyamauchi!! I think @ziyangczi might be looking into this afternoon, so look out if there is a PR first, but that would be great. PR or tips in the right direction would be appreciated. Also @ziyangczi if you run into questions looking into today it you could ask @kevinyamauchi

**Comment by liu-ziyang** [comment]
I am planning to dig into this tomorrow as well, but happy to see more people able to reproduce it!

**Comment by jni** [comment]
To clarify the symptoms, when you start adding points, they *alternate* between white and red, and the little face_color box alternates as well. It's really quite fun and hilarious! 😂 

<img width="1200" alt="Screen-Shot-2020-09-22-at-12 08 19-pm" src="https://user-images.githubusercontent.com/492549/93838625-ae3dc380-fccd-11ea-8f34-6650b8bd5323.png">

#1623 does **not** fix the issue, in case anyone's wondering.

**Comment by kevinyamauchi** [comment]
> Thanks @kevinyamauchi!! I think @ziyangczi might be looking into this afternoon, so look out if there is a PR first, but that would be great. PR or tips in the right direction would be appreciated. Also @ziyangczi if you run into questions looking into today it you could ask @kevinyamauchi

> I am planning to dig into this tomorrow as well, but happy to see more people able to reproduce it!

Okay, sounds good! Thanks, @ziyangczi !

**Comment by sofroniewn** [comment]
Closed by #1643
