### ISSUE TITLE
noise2self: threads and processes

### ISSUE THREAD

**Issue by pwinston** [napari/napari#1628]
## 📚 Documentation

* The `DelayQueue` fixes the Jupyter/Torch example.
* Processes are not needed, threads work.
* Threads work in Jupyter itself or in the stand-alone script.
   * Processes did not work inside Jupyter

## Details

Previously we concluded that processes (rather than threads) were needed for the [noise2self Jupyter notebook](https://github.com/jni/noise2self). This actually not true. I ran noise2self example on latest async PR #1625 and it worked fine with threads. 

On a hunch I disabled the `DelayQueue` and performance tanked. With no `DelayQueue` we end up continuously running 6 copies of the Torch computation in the background. With a `DelayQueue` when scrolling around we run nothing in the background. Back when we decided processes were the answer we did not yet have a `DelayQueue`. We added it later to prevent spamming remote servers with request for slices we don't actually need, but it works strongly to our benefit here as well.

I believe that there **is** contention with running Torch in the background. But if you run zero copies instead of 6 that contention is zero!

Since it works with threads, we can run this in Jupyter itself. The version using processes did not run in Jupyter, only in the [stand-alone script version](https://github.com/pwinston/napari-pwinston/blob/master/noise2self/noise2self_script.py). You would need to modify the the Jupyter version to load the tiny `MNIST` datasets fully into memory.

If you don't do that it still lets you scroll freely, which is nice, but you can't see any of the data until you stop. If you loads those two into memory it works identically to the old version with processes. You see the two all the time, and then the Torch results pops in later. Actually the threads version with `DelayQueue` should perform better, because a worker is always available.

This means we have not yet encountered a case where we need to use processes. We could leave process support out entirely. Or we could include it, it's only a few lines, in the experimental part, and decide about exposing it later.

## Traces

Here it is with threads with no `DelayQueue`, it's running 6 copies of the Torch computation in the background at all times. The draws are happening only every 250ms or so:

<img width="1026" alt="torch-no-delay" src="https://user-images.githubusercontent.com/4163446/92663850-78154280-f2d0-11ea-9e20-e85519048ae1.png">

Here it is with threads and a 100ms `DelayQueue`, nothing is running in the background so the frame rate is 30Hz or so, then it does the one load (Torch computation) at the end:

<img width="1103" alt="torch-100ms-delay" src="https://user-images.githubusercontent.com/4163446/92663880-8a8f7c00-f2d0-11ea-9ac9-079c8d57d8b2.png">

## Conclusion

When we originally saw this problem we said "there is contention, how can we eliminate that contention?" and we eliminated it by switching from threads to processes. Instead the `DelayQueue` solution is to eliminate the contention by running nothing in the background.

It might seem like we did the wrong thing at first, but actually [the delay queue](https://github.com/pwinston/napari/blob/async/napari/components/chunk/_delay_queue.py) was a bit tricky, while switching to processes was mostly a matter of just calling `ProcessPoolExecutor` instead of `ThreadPoolExecutor`. At any rate we have both solutions now and they both work.

**Comment by sofroniewn** [comment]
This was implemented in #1704 and the situation resolved and so can be closed for now. If the need for further discussion arises then we can reopen
