### ISSUE TITLE
Move async into experimental and merge it

### ISSUE THREAD

**Issue by pwinston** [napari/napari#1629]
## Task
We need all async functionality to be in the `experimental.*` namespace before merge

## Motivation

Not sure if this belongs in an "issue". But since the feature is spread out over so many PRs and those PRs seem to come and go, I think we need some permanent home that documents and tracks the state of things. This issue will be that home, unless there is a better place.

## GitHub Project

@pwinston's [Napari Rendering](https://github.com/users/pwinston/projects/1) GitHub Project has links to all the PRs.

## Merged

These PRs were already merged:

* `async-1` - Stub `ChunkLoader`
* `async-2` - `ChunkLoader` thread pool
* `async-2.5` - Vispy changes

## Next Steps

The next PR `async-3` adds the `ChunkCache`, but we want to pause now and get everything into `experimental` namespaces, including the vendored dependencies. This might result in changes to `async-3` through `async-12` or maybe some new PRs as well.

The goal is that everything async specific is in `experimental` namespaces so that it's clear it is opt-in non-final code. Anything not in `experimental` must be final and reviewed like any other code.

**Comment by sofroniewn** [comment]
This was closed by #1659 async-2.6 which moved the async code to experimental
