### ISSUE TITLE
napari.utils.naming.magic_name should return a default name on exception

### ISSUE THREAD

**Issue by mkitti** [napari/napari#1630]
## To Reproduce

1. Execute https://gist.github.com/mkitti/2f7c5fc3d3f8b0d15dd13f6d67b0e73d in Julia
2. On executing `napari.view_image(astronaut)`  the following error stack trace occurs

```python
AttributeError("'NoneType' object has no attribute 'f_code'")
  File "C:\Users\asdf\.julia\conda\3\lib\site-packages\napari\components\add_layers_mixin.py", line 225, in add_image
    return self.add_layer(layers.Image(data, **kwargs))
  File "C:\Users\asdf\.julia\conda\3\lib\site-packages\napari\layers\image\image.py", line 177, in __init__
    super().__init__(
  File "C:\Users\asdf\.julia\conda\3\lib\site-packages\napari\layers\intensity_mixin.py", line 22, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\asdf\.julia\conda\3\lib\site-packages\napari\layers\base\base.py", line 138, in __init__
    name = magic_name(data, path_prefix=ROOT_DIR)
  File "C:\Users\asdf\.julia\conda\3\lib\site-packages\napari\utils\naming.py", line 70, in magic_name
    code = frame.f_code
```

## Expected behavior

The astronaut image should appear in the Napari viewer.

## Environment

napari: 0.3.6
Platform: Windows-10-10.0.18362-SP0
Python: 3.8.3 (default, May 19 2020, 06:50:17) [MSC v.1916 64 bit (AMD64)]
Qt: 5.12.5
PyQt5: 5.12.3
NumPy: 1.19.1
SciPy: 1.5.0
Dask: 2.26.0
VisPy: 0.6.4

GL version: 4.6.0 - Build 26.20.100.7985
MAX_TEXTURE_SIZE: 16384

Plugins:
- napari_plugin_engine: 0.1.7
- svg: 0.1.3

I'm calling Napari from Julia. I installed Napari via conda-forge.

## Additional context

https://github.com/napari/napari/blob/ce6f226720e782e224408ad1f5471b364662591e/napari/utils/naming.py#L64-L69

## Workaround

`napari.view_image(astronaut,name="astronaut")` works

## Problem

The function `magic_name` uses the `inspect` package to navigate stack frames. However, it is possible that one of the stack frames could be `None`. This is not checked for nor is a possible exception caught. Is this case, `frame.f_back` may eventually be `None` and thus not have a `f_code` field.

https://github.com/napari/napari/blob/master/napari/utils/naming.py#L64-L69

https://docs.python.org/3/library/inspect.html#inspect.currentframe

<blockquote>
inspect.currentframe()
Return the frame object for the caller’s stack frame.

CPython implementation detail: This function relies on Python stack frame support in the interpreter, which isn’t guaranteed to exist in all implementations of Python. If running in an implementation without Python stack frame support this function returns None.
</blockquote>

## Possible solutions

1. Add exception handling and return a default name if one could not be found.
2. When iterating frames, check if each frame is `None`
3. Catch exception at a higher level and recommend the use of the `name` keyword argument if `magic_name` fails.

**Comment by mkitti** [comment]
Here is the Julia version information:

```julia
julia> versioninfo()
Julia Version 1.5.0
Commit 96786e22cc (2020-08-01 23:44 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)

(@v1.5) pkg> st PyCall
Status `C:\Users\asdf\.julia\environments\v1.5\Project.toml`
  [438e738f] PyCall v1.91.4

(@v1.5) pkg> st Conda
Status `C:\Users\asdf\.julia\environments\v1.5\Project.toml`
  [8f4d0f93] Conda v1.4.1
```

**Comment by jni** [comment]
Thanks for the detailed report @mkitti! It makes things very easy on our end. =) I like either option 1 or 2, and would definitely welcome a PR that fixes things! Originally we just named things after the layer type so that is a sensible default.

If you don't have time for a PR, don't worry, we'll get to it. =)
