### ISSUE TITLE
Layer._get_state(), or something like it, should be public

### ISSUE THREAD

**Issue by jni** [napari/napari#1636]
## 🐛 Bug

The `napari_get_writer` [hookspec docs](https://napari.org/docs/plugins/hook_specifications.html#napari.plugins.hook_specifications.napari_get_writer) say:

> If `path` is a recognized format, this function should return a function that accepts the same path, and a list of tuples containing the data for each layer being saved in the form of `(Layer.data, Layer._get_state(), Layer._type_string)`

Unfortunately, `Layer._get_state()` is a private method, which should raise alarm bells, and as a consequence it is not even documented in our API docs (see e.g. for [`Image`](https://napari.org/docs/api/napari.layers.image.html)). So, to write a writer plugin, one needs to go fish around in the image layer source code!

Note: we might need to version the `get_state` API, but this should not be too hard.

**Comment by sofroniewn** [comment]
I agree with this proposal, I think there was some discussion in #1584 about API around this method - we should have one function call to return something serializable, we should have another function call that returns our simple objects that plugins could use. The only place where there would be a difference right now is the `colormap` object.

**Comment by adamltyson** [comment]
Resurrecting this. I'm developing a writer plugin that uses `Layer._get_state()` to work out how to write the data. Making some version of this public would be great, it feels fragile ATM.

**Comment by sofroniewn** [comment]
@alisterburt and I were just talking about this on the napari-animation repo. The future direction for this will be to get the layers to be our pydantic evented models, and then we'll get `layer.dict()` and `layer.json()` methods on them for free. We've done that now for the `viewer`, but havn't make it for the layers yet. We could push on this soon. Maybe as soon as we get the `LayerGroup` stuff in from @tlambert03 we can do this? Or maybe we do it ahead of that to make that transition easier. Curious what @tlambert03 recommends the order should be. I don't think we need to wait to get slicing off the layer, that is separate.

**Comment by tlambert03** [comment]
I'm not 100% sure what the order should be... That's going to be a very important and useful public API once it "settles", so I'm not sure I want to be in a hurry to "settle it"... or decide right now what order is best.  That _may_ mean that you should just use `_get_state()`  for now.  It's true it's a bit brittle... but rest assured we agree it's an important thing to make public soonish?

**Comment by adamltyson** [comment]
Sounds good. I'm happy using `_get_state()` for now. At least now I'll get a notification when this changes :)

**Comment by andy-sweet** [comment]
Not sure if I'm letting a proverbial cat of a bag somewhere, but we do have the public (though undocumented) `Layer.as_layer_data_tuple` which effectively exposes `Layer._get_state`. So I wonder if this can be closed?

**Comment by Czaki** [comment]
Also think that this may be closed

**Comment by jni** [comment]
Yup, good point. If anyone needs anything different from `_get_state`, we can reopen!
