### ISSUE TITLE
Add metadata to layers

### ISSUE THREAD

**Issue by Czaki** [napari/napari#1646]
## 🚀 Feature

Add to layer metadata parameter which allow programmer to store some domain knowledge description of given layer.
## Motivation
In my tool I have saving project utility which allow to simple session restore. I would like to use napari for manual annotation or manual correction of some algorithm prepared annotation. But without information about file which is annotated I need to use two steep loading, or manually fix save files. If I could storage information about base file during create annotation thn simple save layer plugin could prepare proper file (if adding labels layer propagate some metadata from base file). 

## Pitch
Allow to storage project specify information in layers with dict similar structure

For me such information could be: 

* File path 
* Channel number 
* Source (from file/modified with filter/etc)
* units (used for interpret spacing) 

## Alternatives
Build external structure to sore such data, easy when using napari as viewer to own tool. Hard when would like to use napari with plugins as standalone one.  

Save/load plugins could also operate not only on layers but also some global state. 

## Additional context
It may also help with #1605 because tools colud store some additional data in layer to distinguish them.

I could implement this If in the discussion there is decision how it should be done.

**Comment by sofroniewn** [comment]
Hi @Czaki, right now you can pass an arbitrary dictionary to the `metadata` keyword arg for any of our `add_*` methods to add a layer, see here on the base layer https://github.com/napari/napari/blob/master/napari/layers/base/base.py#L27-L28 for its doc string.

Right now though that metadata dict could be arbitrary and non-standard. Is your proposal to try and standardize it, or could you start using that right away? Are you already using it?

Looking forward to discussing more.

**Comment by Czaki** [comment]
Oh I missed this.

But If I good understand still if one create new labels with button its metadata is empty dict?

**Comment by sofroniewn** [comment]
> But If I good understand still if one create new labels with button its metadata is empty dict?

Yes that would be correct. If you create a reader plugin then you could populate the `metadata` with your custom information, so it would be there if people did drag and drop etc.

**Comment by Czaki** [comment]
And what You think about add `origin` section in metadata for label layer (if created with button) with some list of layer based on which new layer is created? 



> Yes that would be correct. If you create a reader plugin then you could populate the `metadata` with your custom information, so it would be there if people did drag and drop etc.

I will add this to my plugin

**Comment by sofroniewn** [comment]
> And what You think about add origin section in metadata for label layer (if created with button) with some list of layer based on which new layer is created?

I could imagine many people wanting different metadata in layers created by buttons, so rather than pick one to give to everyone maybe we try and think about an easy way so that you could pass your own via your tool?

**Comment by Czaki** [comment]
My current workflow is to use my own tool for automated segmentation and napari for automated one. There is any documentation to create dockable widget plugin for napari? Or I should subclass `Viewer` class?

**Comment by sofroniewn** [comment]
> There is any documentation to create dockable widget plugin for napari? 

The last discussion of that was in #1327. I think the conversation there has reach consensus that we would add a viewer dock widget hookspec as described in the original post under an `experimental` namespace, but we havn't started work on an implementation yet.

**Comment by dstansby** [comment]
Just looking into some metadata stuff, and it seems like this issue can be closed since it's possible to use the `.metadata` layer attribute?

**Comment by Czaki** [comment]
Yes but I cannot do this from mobile app.
