### ISSUE TITLE
failing dask test

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#1656]
## 🐛 Bug

Looks like some of our tests are now failing on master possibly due to a new dask release. I will look into and post more detail here when available.

**Comment by sofroniewn** [comment]
See the CI report here, looks like it is only python3.8 macos https://cirrus-ci.com/task/5702782638358528 right now ...

**Comment by sofroniewn** [comment]
Looks like the failings are timeout related. I notice that `pytest napari/layers/image/_tests/test_big_image_timing.py` is much slower with dask `2.28.0` compared to `2.27.0` and I think we're now passing our 2sec timeouts.

This could relate to https://github.com/dask/dask/pull/6665 and discussions around [efficiency](https://docs.dask.org/en/latest/array-slicing.html#array-slicing-efficiency) here. I think we might now be hitting some of the "interactive overhead of a second or two".

It could also relate to our dask config which might now need updating see, https://github.com/napari/napari/blob/master/napari/utils/dask_utils.py#L121.

We might want to now adjust `dask.config.set({"array.slicing.split_large_chunks": True})`.

Thanks @jni for some tips, I'll play around some more.

**Comment by sofroniewn** [comment]
I've tried
```python
        def dask_optimized_slicing():
            with dask.config.set{"optimization.fuse.active": False, "array.slicing.split-large-chunks": False}) as cfg:
                yield cfg
```
which I think should have reverted to the behavior before `2.28.0` is released, but it doesn't seem to have. The config might not be getting set as i expect though ...

**Comment by sofroniewn** [comment]
It seems like multiscale performance with dask is actually much worse on `2.28.0` too, so this isn't just making our tests worse, it's making the actual performance worse too (panning and zooming with one of my pathology slide examples is slower). Maybe one of our dask experts @jakirkham @GenevieveBuckley has ideas on this one? We might want to pin `<2.28.0` until we figure it out. Thoughts @jni?

**Comment by GenevieveBuckley** [comment]
I support pinning until we work it out.

I don't have an idea about what's happened, though. It might be worth mentioning that in a dask issue, or maybe over on the dask gitter. Other people might have a better idea of what the most recent changes were.

I found https://github.com/dask/dask-benchmarks but it doesn't seem to be especially active? I'm not sure if those benchmarks are run regularly. There are [some array benchmarks](https://github.com/dask/dask-benchmarks/blob/master/dask/benchmarks/array.py) included, we could try running this with dask `2.27.x` and `2.28.0` (or maybe even git bisect the bits in between) to see if that gives us a better clue where to look for the problem. @jni might know how to use `asv`, scikit-image uses it to do benchmarking too.

**Comment by jakirkham** [comment]
If we can come up with a minimal example and share that on the Dask issue tracker, I think that will help narrow things down.

**Comment by sofroniewn** [comment]
Ok, thanks @GenevieveBuckley and @jakirkham. A starting point for a minimal example can be the following, which captures one of the [failing tests](https://github.com/napari/napari/blob/master/napari/layers/utils/_tests/test_layer_utils.py#L69-L72) with for a [function defined in napari](https://github.com/napari/napari/blob/master/napari/layers/utils/layer_utils.py#L8-L48). We can probably simplify it before posting, but I want to start with the full thing to make sure we're capturing the problem.

```python
import dask.array as da
import numpy as np
import time


def calc_data_range(data):
    """Calculate range of data values. If all values are equal return [0, 1].

    Parameters
    ----------
    data : array
        Data to calculate range of values over.

    Returns
    -------
    values : list of float
        Range of values.

    Notes
    -----
    If the data type is uint8, no calculation is performed, and 0-255 is
    returned.
    """
    if data.dtype == np.uint8:
        return [0, 255]
    if np.prod(data.shape) > 1e6:
        # If data is very large take the average of the top, bottom, and
        # middle slices
        bottom_plane_idx = (0,) * (data.ndim - 2)
        middle_plane_idx = tuple(s // 2 for s in data.shape[:-2])
        top_plane_idx = tuple(s - 1 for s in data.shape[:-2])
        idxs = [bottom_plane_idx, middle_plane_idx, top_plane_idx]
        reduced_data = [
            [np.max(data[idx]) for idx in idxs],
            [np.min(data[idx]) for idx in idxs],
        ]
    else:
        reduced_data = data

    min_val = np.min(reduced_data)
    max_val = np.max(reduced_data)

    if min_val == max_val:
        min_val = 0
        max_val = 1
    return [float(min_val), float(max_val)]


data = da.random.random(
    size=(100_000, 1000, 1000), chunks=(1, 1000, 1000)
)

t0 = time.time()
val = calc_data_range(data)
t1 = time.time()
print(t1 - t0)
```

Which with dask `2.27.0` takes ~0.5 seconds and with dask `2.28.0` takes ~15 seconds. Our test has a 2 second timeout which causes it to now fail.

I'll see if I can clean this up/ simplify it a bit too

**Comment by sofroniewn** [comment]
Ok, this much simpler example still captures the difference

```python
import dask.array as da
import numpy as np
import time


data = da.random.random(
    size=(100_000, 1000, 1000), chunks=(1, 1000, 1000)
)

idxs = [(0,), (50_000,), (99_999,)]

t0 = time.time()
reduced_data = np.min([np.min(data[idx]) for idx in idxs])
t1 = time.time()
print(t1 - t0)
```
Which is `0.13` seconds for `2.27.0` and `4.3` seconds for `2.28.0`, which is quite difference. I will look into changing the config settings and then will post of the dask issue tracker

**Comment by sofroniewn** [comment]
I will add that changing the dask config as follows yields little difference for the True/ False case, but it's not clear to me I am using the config right. I'll take this to the dask issue tracker

```python
import dask
import dask.array as da
import numpy as np
import time

with dask.config.set({"array.slicing.split-large-chunks": False}):

    data = da.random.random(
        size=(100_000, 1000, 1000), chunks=(1, 1000, 1000)
    )
    
    idxs = [(0,), (50_000,), (99_999,)]

    t0 = time.time()
    reduced_data = np.min([np.min(data[idx]) for idx in idxs])
    t1 = time.time()
    print(t1 - t0)
```

**Comment by sofroniewn** [comment]
Dask issue made here https://github.com/dask/dask/issues/6694

**Comment by sofroniewn** [comment]
Dask `2.29.0` has now been released and our tests passing again so I will close this. Looks like dask reverted that particular change and will be fixing it for the next release. We can always re-open this of create a new issue if it arises again. Thanks to the dask team for being on this so promptly!!
