### ISSUE TITLE
Change napari's rotation convention so positive rotation angles cause an anti-clockwise rotation

### ISSUE THREAD

**Issue by GenevieveBuckley** [napari/napari#1658]
## 🚀 Feature

We would like to change napari's rotation convention so that positive rotation angles cause an anti-clockwise (sometimes known as counter-clockwise) rotation. 

## Motivation
This convention is the most widely used in mathematics and also other python libraries like scikit-image. Having different conventions makes things unintuitive and very easily leads people to make mistakes.

## Pitch
Nick suggests this change here https://github.com/napari/napari/pull/1616#issuecomment-700146465

> A positive angle rotates an image in napari in the clockwise direction, whereas most mathematics (and apparently skimage) would have a positive angle rotate in a counter-clockwise direction by convention.
>
> Unfortunately I think the reason we have that our convention is wrong is not because we construct the transform matrices wrong but because we "right apply" them instead of "left apply" them. See this line
>
> ```python
> return np.atleast_1d(np.squeeze(coords @ linear_matrix + translate))
> ```
>
> and note that linear_matrix is on the "right" instead of the "left" of the coords. This was done because of the broadcasting rules of numpy make it simpler, and I thought it would be ok, with the necessary precautions, but it actually makes lots of things strange and counter-intuitive, leading to mistakes like this one. I think I should go back and fix that, and my guess is we won't need the extra `-` sign anymore.

**Comment by sofroniewn** [comment]
This convention is now followed in the latest version of #1616 and will not change, so I will close. Thanks for making the issue!!
