### ISSUE TITLE
Clean up our pytest configuration so others can use it

### ISSUE THREAD

**Issue by jni** [napari/napari#1661]
## 🐛 Bug

[On Zulip](https://napari.zulipchat.com/#narrow/stream/212875-general/topic/napari-omero/near/211657066), @perlman reports:

> [the ome-zarr plugin] registers a pytest hook ( `"pytest11": ["napari-conftest = napari.conftest"]`) which is preventing me from using pytest in environments where I have ome-zarr but NOT napari installed.
> 
> Is there a reason this pytest plugin needs to be installed globally, especially when napari is not an actual requirement of ome-zarr?

The reason ome-zarr-py adds that hook is so that they can use our test fixtures, which they wanted to do to test their plugin. But, since there's no way for them to *conditionally* add an entry point, they are stuck depending on napari for testing.

I think the clean solution is to create a new, separate package with our conftest, eg `napari-pytest`, and have both us and `ome-zarr-py` depend on it *as a test dependency only*, not a runtime dependency.

See also #1602.

## To Reproduce

1. Create a new environment
2. `pip install pytest ome-zarr`
3. Run pytest

## Expected behavior

Installing packages in the napari ecosystem *without* napari should not break pytest.

**Comment by Czaki** [comment]
Hm. I go through pytest documentation (for prepare classes) and found nice fixture (`pytestconfig`) which may be solution for this problem, https://docs.pytest.org/en/stable/reference.html#pytest.config.PytestPluginManager.register.

So to check it I download `ome-zarr` code, remove `"pytest11": ["napari-conftest = napari.conftest"]` line from `setup.py` then install and try to run test. Everything pass. 

So it looks like this line is obsolete and I do not have idea which project could be used for test something like

```python
@pytest.fixture(autouse=True, scope="session")
def load_napari_conftest(pytestconfig):
    from napari import conftest
    pytestconfig,register(conftest, "napari-conftest")
```

and put `napari` in a test dependecies.

**Comment by jni** [comment]
@Czaki I'm sorry, could you explain the steps in more detail? I'm 95% sure that the ome-zarr folks added that entrypoint *precisely* because they couldn't use our fixtures without it...! CC @joshmoore @will-moore

**Comment by joshmoore** [comment]
Wow, thanks @Czaki! I've opened https://github.com/ome/ome-zarr-py/pull/51 with:
```
@pytest.fixture(autouse=True, scope="session")
def load_napari_conftest(pytestconfig):
    from napari import conftest

    pytestconfig.pluginmanager.register(conftest, "napari-conftest")
```

This looks to work. (The first run without a new call to `pip install` fails with a double registration of the plugin)

That block of code would need to be hard-coded by anyone wanting to re-use napari's conftest. If there were a way to make that simpler, this issue might still have some value. But from my side, I think @perlman's issue should be fixed with PR 51.

**Comment by Czaki** [comment]
@joshmoore pleas check it detailed. I already created empty virtualenv and install `ome-zarr`. Then install test dependecies (`pytest`, `scikit-imge`, `scipy`) and run test. Everything works in environment without napari. 

```
╰─$ pytest                        
============================================================= test session starts ==============================================================
platform linux -- Python 3.7.7, pytest-6.1.0, py-1.9.0, pluggy-0.13.1
rootdir: /home/czaki/Projekty/ome-zarr-py, configfile: pytest.ini
collected 32 items                                                                                                                             

ome_zarr/conversions.py ...                                                                                                              [  9%]
ome_zarr/data.py .                                                                                                                       [ 12%]
ome_zarr/io.py ..                                                                                                                        [ 18%]
ome_zarr/scale.py .                                                                                                                      [ 21%]
ome_zarr/utils.py .                                                                                                                      [ 25%]
tests/test_cli.py .....                                                                                                                  [ 40%]
tests/test_napari.py ...s                                                                                                                [ 53%]
tests/test_node.py ...                                                                                                                   [ 62%]
tests/test_ome_zarr.py ......                                                                                                            [ 81%]
tests/test_reader.py ...                                                                                                                 [ 90%]
tests/test_starting_points.py ...                                                                                                        [100%]
```

**Comment by joshmoore** [comment]
Ah, you're saying that the current code is (without the PR 51) works as expected? Then I'd defer to @perlman man. From my side, the change isn't particularly onerous so if it helps, happy to see it go in.

**Comment by Czaki** [comment]
> Ah, you're saying that the current code is (without the PR 51) works as expected? Then I'd defer to @PERMAN. From my side, the change isn't particularly onerous so if it helps, happy to see it go in.

I run my test on revisions db60b8272e0fe005920f8a296d4828b7a32e663e (With removed "pytest11": ["napari-conftest = napari.conftest"] from `setup.py`).
Fro my test it looks like yesterday, developer version of `ome-zarr` test set does not dependent on `napari.conftest`. Maybe previous one does this.

**Comment by perlman** [comment]
https://github.com/ome/ome-zarr-py/pull/51 works for me in the context of my other pytest tests running without needing to disable napari-conftest.

**Comment by liu-ziyang** [comment]
is there any remaining actions needs to be done for this issue? it looks like we can close this one?

**Comment by sofroniewn** [comment]
I guess @ziyangczi it would be to follow up on @jni comment

> The reason ome-zarr-py adds that hook is so that they can use our test fixtures, which they wanted to do to test their plugin. But, since there's no way for them to conditionally add an entry point, they are stuck depending on napari for testing.
>
> I think the clean solution is to create a new, separate package with our conftest, eg napari-pytest, and have both us and ome-zarr-py depend on it as a test dependency only, not a runtime dependency.

To prevent this from happening again, and maybe https://github.com/napari/napari/issues/1602 too

**Comment by sofroniewn** [comment]
Not sure what the status of that one is

**Comment by liu-ziyang** [comment]
> I guess @ziyangczi it would be to follow up on @jni comment
> 
> > The reason ome-zarr-py adds that hook is so that they can use our test fixtures, which they wanted to do to test their plugin. But, since there's no way for them to conditionally add an entry point, they are stuck depending on napari for testing.
> > I think the clean solution is to create a new, separate package with our conftest, eg napari-pytest, and have both us and ome-zarr-py depend on it as a test dependency only, not a runtime dependency.
> 
> To prevent this from happening again, and maybe #1602 too

@jni are you still leaning towards separating out conftest to napari-pytest? It sounds like an API change to the plugin developers, I can look into the separation now if this is still desired

**Comment by Czaki** [comment]
> @jni are you still leaning towards separating out conftest to napari-pytest? It sounds like an API change to the plugin developers, I can look into the separation now if this is still desired

I do not think that it is a good idea. If you would like something like this, then you should first stop overwrite `pytest-qt` elements like `qtbot` 

What is wrong with my proposed solution which uses `pytestconfig.pluginmanager.register`?

**Comment by liu-ziyang** [comment]
> > @jni are you still leaning towards separating out conftest to napari-pytest? It sounds like an API change to the plugin developers, I can look into the separation now if this is still desired
> 
> I do not think that it is a good idea. If you would like something like this, then you should first stop overwrite `pytest-qt` elements like `qtbot`
> 
> What is wrong with my proposed solution which uses `pytestconfig.pluginmanager.register`?

even though I don't have a comprehensive understanding of the benefit of the separation, I second @Czaki's solution 😄

**Comment by jni** [comment]
Yeah I don't really understand this interaction either but it looks like https://github.com/ome/ome-zarr-py/pull/51 is stuck with failing test config, so I'd like to keep this open until that is resolved.

**Comment by Czaki** [comment]
there are no changes in ome/ome-zarr-py#51 from long time. And tests fail because They have installed both PySide2 and PyQt5 in the test environment. 

@joshmoore There are any plans to push this PR?

**Comment by joshmoore** [comment]
Sorry, @Czaki. I dropped the ball on that. Hopefully can get to it once I2K is over and before EOSS starts ...  but yes, my understanding is that there's a path forward, certainly for ome-zarr-py. Happy to make use of whatever the official solution is.

**Comment by joshmoore** [comment]
I failed to notice in https://github.com/napari/napari/issues/1661#issuecomment-701959175 that @Czaki's test run was skipped:
```
tests/test_napari.py ...s                                                                                                                [ 53%]
```
I'm currently struggling with
```
___________________________________________________ ERROR at setup of TestNapari.test_viewer ___________________________________________________
file /opt/ome-zarr-py/tests/test_napari.py, line 65
      def test_viewer(self, make_test_viewer):
E       fixture 'make_test_viewer' not found
>       available fixtures: add_implementation, add_specification, cache, caller_from_implementation, capfd, capfdbinary, caplog, capsys, capsysbinary, cov, doctest_namespace, initdir, load_napari_conftest, monkeypatch, no_cover, pytestconfig, qapp, qapp_args, qtbot, qtlog, qtmodeltester, record_property, record_testsuite_property, record_xml_attribute, recwarn, temporary_hookimpl, test_plugin_manager, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.
```
but will keep looking.

**Comment by Czaki** [comment]
could you point me to which version (branch) you test now?

**Comment by joshmoore** [comment]
Just pushed https://github.com/ome/ome-zarr-py/pull/51/commits/8f6d31d55717432ac6d9f921ed736c2d1e849ddd

**Comment by joshmoore** [comment]
@Czaki : let me know what you think of https://github.com/ome/ome-zarr-py/pull/51/commits/be56babf8cac86742305ac6e24510809482a1198 it seems to fix the issue. So a pytest scoping issue ?

**Comment by joshmoore** [comment]
Nope. It fixed the issue locally, but the GHAs are less than happy.

**Comment by Czaki** [comment]
I have created https://github.com/ome/ome-zarr-py/pull/67

**Comment by joshmoore** [comment]
Especial thanks to @Czaki for all the help with ome/ome-zarr-py#51. Short summary from https://github.com/ome/ome-zarr-py/pull/51#issuecomment-738788825 as relevant to this issue:

👉  `napari.conftest` currently requires the [registration block above](https://github.com/napari/napari/issues/1661#issuecomment-701725443) and importing `make_test_viewer` for use elsewhere. A working example would apply a patch like this:

```#patch
  import numpy as np
  import pytest
+ from napari.conftest import make_test_viewer  # noqa

  from ome_zarr.data import astronaut, create_zarr
  from ome_zarr.napari import napari_get_reader


+ @pytest.fixture(autouse=True, scope="session")
+ def load_napari_conftest(pytestconfig):
+     from napari import conftest
+
+     pytestconfig.pluginmanager.register(conftest, "napari-conftest")

```

**Comment by liu-ziyang** [comment]
big thanks to @joshmoore and @Czaki! closing this issue now

**Comment by perlman** [comment]
Thanks to everyone for fixing this, especially @jni for tolerating my poking in Zulip. :)
