### ISSUE TITLE
Skip roll over 1 size axis 

### ISSUE THREAD

**Issue by Czaki** [napari/napari#1664]
## 🚀 Feature

Ignore empty dimension on "Roll Dimension"
## Motivation

To have consistency of coordinates between different data I normalize axis order and input single dimension axes.
napari does not show slider for such dimension, but when using "Roll dimensions order" this axes could be set as visible, which produce black screen. 

## Pitch

When do roll over dimension skip this combination which contains axes which size is 1. 

## Alternatives
Add separate button/combo box for side view (`zx` and `zy`)
or  even drag'n' drop mechanism for manually modify order of axes (with mnemonic names)

**Comment by sofroniewn** [comment]
Nice catch, fixing this makes sense. It should be a relatively simple change to the logic here https://github.com/napari/napari/blob/master/napari/components/dims.py#L399-L401

If you'd like to make a PR @Czaki I'd happily review

**Comment by Czaki** [comment]
Created, but I stil think that there should be separated option for side view (this will not provide side view for 3d time data for example). Maybe using affinity from #1616,

**Comment by sofroniewn** [comment]
> Created, but I stil think that there should be separated option for side view (this will not provide side view for 3d time data for example). Maybe using affinity from #1616,

Can you explain this a bit more? I'm not sure I understand

**Comment by Czaki** [comment]
> Can you explain this a bit more? I'm not sure I understand

It is common to to view data not only in xy but also in zy and zx. 
But if there is and image with `tzyx` axis order (all axis with more than 1 step) then using roll operation user could see: `yx`, `zy`, `tz`, `xt` planes. So no view on `zx` (and for 3d data this operation will produce view in `xz` not `zx`)

It may be done with changing order, or in future using afinity. I'm not sure which option is better. (mixing such option with roll may produce unexpected order)

**Comment by sofroniewn** [comment]
Ah ok yes, I see -  we should probably fix that in a new PR, and maybe make a new issue specifically for that as it is unrelated to this issue. We do have the option to do a transpose, which could be combined with a roll to achieve what you want, but not in a simple way!!

**Comment by sofroniewn** [comment]
This has been closed by #1665.
