### ISSUE TITLE
Add ability to query highest resolution coordinates for multiscale images

### ISSUE THREAD

**Issue by DragaDoncila** [napari/napari#1667]
## 🚀 Feature
Add function or property which returns coordinates of layer from highest resolution and/or current level of multiscale pyramid.

## Motivation
Currently, adding a click callback to the layer which prints coordinates displays different coordinates when the user clicks on the same spot of the image, depending on the pyramid level currently displayed and the zoom level.

For example,

```
import napari
import dask.array as da
import numpy as np

with napari.gui_qt():
    v = napari.view_image(
        [da.random.random((10000, 10000)), da.random.random((5000, 5000))]
    )
    layer = v.layers[0]

    @layer.mouse_drag_callbacks.append
    def update_intensity(layer, event):
        print(layer.coordinates)
```
If you click on the bottom right hand corner when the image is fully zoomed out, you get roughly (5000, 5000). If you zoom in to the bottom right hand corner and click in the same spot, the coordinates get smaller as you zoom in, and become relative to the top left of the canvas, rather than the image itself.

This might be the desired behaviour for some applications, but some might require the "true coordinates" i.e. the corresponding coordinates in the full resolution level of the pyramid.

## Pitch

A function or property should be added to layers which returns coordinates relative to the top left corner of the full resolution image e.g. `layer.global_coordinates` although global is probably not the right word. 

This maybe should be the default? It's not clear that clicking on the same 'spot' should return different values depending on zoom level.

## Alternatives

Keep current behaviour and provide public interface to transforms which can give back the full resolution coordinates.

**Comment by sofroniewn** [comment]
Note that
```python
        print(layer._transforms.simplified(layer.coordinates))
        print(layer._transforms['tile2data'](layer.coordinates))
```
give the desired values, but we still need to think about how to expose them. I'll likely think about this in the context of some clean-up to the cursor code

**Comment by sofroniewn** [comment]
Following #1673 the `layer.coordinates` is now in the highest resolution for multiscale data
