### ISSUE TITLE
Autogenerate add_* methods (revert #303)

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#1677]
## Refactor

In #303 we decided to explicitly put our `add_*` methods onto the viewer and no longer use the very nice `add_to_viewer` decorator that @kne42 had made.

As @kne42 noted at the time

> Ideally we shouldn't have to do anything; this is PyCharm's fault for statically providing completions and documentation in a dynamic language 🙄.
>
> I feel like every situation here is a loss, so I'll just go with whatever is best for the user and I think that's this PR, but with the signatures/docstrings properly copied from their respective classes, not the whole "please see X documentation."

I think now experiences like #1616 where i add a keyword arg to the base layer and have to add 14 copies of the doc string, make me thing we might want to revert this change.

For all our layers apart from `Image` it should be very simple. For `Image` we have some additional complexity around the splitting of axes channels, but that can maybe be addressed separately. 

@jni @kne42 do either of you have additional thoughts on this or a recommendation?

**Comment by jni** [comment]
Yeah I'm into it! We could have code that autogenerates *unless that function already exists*, in which case (add_image), it would not autogenerate, but it would autogenerate any docstring arguments that were missing (everything except "channel axis").

**Comment by sofroniewn** [comment]
> Yeah I'm into it! We could have code that autogenerates unless that function already exists, in which case (add_image), it would not autogenerate, but it would autogenerate any docstring arguments that were missing (everything except "channel axis").

@jni so not going with the explicit `add_to_viewer` decorator on the layers? Can you maybe make that proposal more clear, would have a function that adds them all to the `Viewer` when/ after the viewer gets instantiated? I like this because we wouldn't need to change any of the code in our layer models, and our layer models wouldn't need to know about concepts like adding to the viewer

**Comment by jni** [comment]
@sofroniewn I'm not sure about the implementation, I'm just saying, we can go with `add_to_viewer`, but it would check whether Viewer already has that `add_*` method, and if it does, it wouldn't add the implementation but it would update its docstring. Does that make sense?
