### ISSUE TITLE
Async To Dos

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#1695]
## 🚀 Feature
Making this issue to keep track of some async to do's as we merge PRs. This is fairly raw right now @pwinston but I'll update it as we go!

1. Improve flickering to black during async loading.
2. Add ability to force refresh data / not pull from cache, particularly in cases where data.
3. More comprehensive async tests, see https://github.com/napari/napari/pull/1685#issuecomment-703809019

**Comment by pwinston** [comment]
Open items:
- [ ] Pass through original rendering doc 
- [ ] New "Guides" doc for rendering
- [ ] File fresh issue for Dask level 0 performance (#2012)
- [ ] Try to fix the pixel shift on load
