### ISSUE TITLE
Error when using pandas dataframe for properties on Tracks layer

### ISSUE THREAD

**Issue by quantumjot** [napari/napari#1706]
## 🐛 Bug

Error when using pandas dataframe for properties on Tracks layer.

## To Reproduce

The `Tracks` layer throws an error when passing a dataframe for the properties kwarg:

```
Traceback (most recent call last):
  File "/home/quantumjot/napari/napari/_qt/event_loop.py", line 79, in gui_qt
    yield app
  File "<ipython-input-15-fdca00748db9>", line 4, in <module>
    viewer.add_tracks(data, properties=properties)
  File "/home/quantumjot/napari/napari/components/add_layers_mixin.py", line 854, in add_tracks
    layer = layers.Tracks(
  File "/home/quantumjot/napari/napari/layers/tracks/tracks.py", line 144, in __init__
    self.properties = properties or {}
  File "/home/quantumjot/anaconda3/envs/trackpy/lib/python3.8/site-packages/pandas/core/generic.py", line 1326, in __nonzero__
    raise ValueError(
ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
```

## Expected behavior

Tracks layer should accept the dataframe.

## Environment

```
napari: 0.3.9.dev31+g647d918
Platform: Linux-4.15.0-1097-oem-x86_64-with-glibc2.10
Python: 3.8.5 (default, Sep 4 2020, 07:30:14) [GCC 7.3.0]
Qt: 5.14.2
PyQt5: 5.14.2
NumPy: 1.19.1
SciPy: 1.5.2
Dask: 2.29.0
VisPy: 0.6.5
GL version: 4.6.0 NVIDIA 450.80.02
MAX_TEXTURE_SIZE: 32768
```

**Comment by kevinyamauchi** [comment]
Thanks flagging this, @quantumjot ! I can take a look over the next couple of days.

edit: if you want to make a PR that's great too!

**Comment by kevinyamauchi** [comment]
Notes from @quantumjot in [this comment](https://github.com/napari/napari/pull/1705#issuecomment-704930599):

> This is the offending line:
https://github.com/napari/napari/blob/647d9182a6dc3542521cbc99b8b59beb4f2ba901/napari/layers/tracks/tracks.py#L144

**Comment by quantumjot** [comment]
> edit: if you want to make a PR that's great too! 

@kevinyamauchi - Done!
