### ISSUE TITLE
Tracks color_by not handled correctly

### ISSUE THREAD

**Issue by VolkerH** [napari/napari#1722]
## 🐛 Bug

Two issues with `color_by`:

1. When creating a tracks layer with multiple properties and specifying a specific property name using `color_by`, the property is not selected for coloring (it always seems to default to the same property). Color_by always seems to default to the first dictionary key. ![image](https://user-images.githubusercontent.com/2210044/95926667-8f33dc80-0e08-11eb-85a0-12a9d40b612a.png)
Looking at the Track `__init__` method I don't really see why that happens, as the property seems to be initialized [here](https://github.com/napari/napari/blob/5fff516d237a8786572474a36b41024dfb3267cc/napari/layers/tracks/tracks.py#L136) and [here](https://github.com/napari/napari/blob/5fff516d237a8786572474a36b41024dfb3267cc/napari/layers/tracks/tracks.py#L154).

1. The second issue is a silent failure when specifying a property name that does not exist as a dictionary key: https://github.com/napari/napari/blob/5fff516d237a8786572474a36b41024dfb3267cc/napari/layers/tracks/tracks.py#L426  I think the user should be notified. Not sure about the best method to do this but maybe just throw a `ValueError` ?
   

## To Reproduce

1. Create a track layer with a properties dictionary that contains multiple keys. 
2. Try different keys for `color_by`.

Apologies that I'm only showing a screenshot above. Need to generate some fake tracking data to make
a share-able code snippet.

## Expected behavior

The track should be colored by the property corresponding to the specified `color_by` key.

## Environment

```
napari: 0.3.9.dev40+gd3511ee
Platform: Linux-5.4.0-48-generic-x86_64-with-debian-bullseye-sid
Python: 3.7.7 (default, May 7 2020, 21:25:33) [GCC 7.3.0]
Qt: 5.14.2
PyQt5: 5.14.2
NumPy: 1.19.1
SciPy: 1.5.2
Dask: 2.25.0
VisPy: 0.6.4

GL version: 4.6.0 NVIDIA 450.66
MAX_TEXTURE_SIZE: 32768

Plugins:
- napari_plugin_engine: 0.1.7
- svg: 0.1.4
```

 

## Additional context

@quantumjot

**Comment by jni** [comment]
@VolkerH fyi the examples directory contains an example with synthetic data:

https://github.com/napari/napari/blob/d3511ee050eacdb00db9cbc119f346c0d13b24af/examples/tracks_3d.py

**Comment by sofroniewn** [comment]
Thanks for the report! @kevinyamauchi might have ideas too

**Comment by VolkerH** [comment]
Thanks @jni 

I modified `tracks_3d.py` to create a reproducible example:
https://github.com/VolkerH/napari/blob/tracks_color_by.py/examples/tracks_3d.py

```
    speedlayer = viewer.add_tracks(tracks, properties=properties, name='tracks', color_by='speed')
    print(f"Speed layer color_by is: {speedlayer.color_by}.")
    distancelayer = viewer.add_tracks(tracks, properties=properties, name='tracks', color_by='distance')
    print(f"Distance layer color_by is: {distancelayer.color_by}")
```

produces:


```
volker@gpubox:~/Github/napari/examples$ python tracks_3d.py 
Speed layer color_by is: time.
Distance layer color_by is: time
```

**Comment by VolkerH** [comment]
I added a test in a branch https://github.com/VolkerH/napari/blob/tracks_tests/napari/layers/tracks/_tests/test_tracks.py

```
properties_dict = {'time': np.arange(100), 'other': np.arange(100)}
properties_df = pd.DataFrame(properties_dict)

def test_track_layer_color_by():
    """Test color_by selects specified property."""
    data = np.zeros((100, 4))
    data[:, 1] = np.arange(100)
    for key in properties_dict.keys():
        layer = Tracks(data, properties=properties_dict, name = key, color_by=key)
        print(layer.color_by, key)
        assert layer.color_by==key
```

The test passes. So it appears not to be an issue when `Track` is used, but an issue when `v.add_tracks(...)` is used.
But I don't know enough about how `add_tracks()` is dynamically generated:
![image](https://user-images.githubusercontent.com/2210044/95946775-f5d0ee80-0e38-11eb-97c5-4cd02bb5f76a.png)

**Comment by VolkerH** [comment]
Ok, so I suspect this error must be happening somewhere in
https://github.com/napari/napari/blob/be9196a02c08e3d6e38704ecc00beb170323f563/napari/components/add_layers_mixin.py

maybe around here ???:   
https://github.com/napari/napari/blob/be9196a02c08e3d6e38704ecc00beb170323f563/napari/components/add_layers_mixin.py#L448

**Comment by quantumjot** [comment]
My guess is that this originates from the `color_by` Qt events when the layer controls are built.

**Comment by kevinyamauchi** [comment]
> My guess is that this originates from the color_by Qt events when the layer controls are built.

I think this is a good guess. I will take a look this afternoon before the dev meeting.

**Comment by kevinyamauchi** [comment]
@VolkerH , I think I have tracked down the issue. When you have time, would you mind taking #1725 for a spin and confirming it fixes things for your use case?

**Comment by VolkerH** [comment]
Hi @kevinyamauchi, @quantumjot, thanks for fixing this so quickly.
I no longer see the incorrect initialization for my small test case above: 

```
volker@gpubox:~/Github/napari$ python examples/tracks_3d.py 
Speed layer color_by is: speed.
Distance layer color_by is: distance
```

The separate problem I flagged (I should have opened a separate issue) 
is dealing with property names passed as `color_by` that don't exist as keys in
the `properties`. How should that behandled, raise a `ValueError` (I'd be happy to the PR) 
or just issue a warning?
