### ISSUE TITLE
Isolevel rendering has weird spots/artifacts at the edge of a volume

### ISSUE THREAD

**Issue by jni** [napari/napari#1724]
## 🐛 Bug

When using isorendering for volumes that have objects touching the volume edge, weird little green spots appear at those interfaces:

<img width="1200" alt="Screen Shot 2020-10-14 at 8 49 24 pm" src="https://user-images.githubusercontent.com/492549/95973102-f7151200-0e5e-11eb-9745-d6af8dafd1c4.png">

## To Reproduce

1. Run `python examples/add_volume.py`
2. Switch rendering mode to `iso`.

**Comment by VolkerH** [comment]
Can't reproduce on my linux box. 

![image](https://user-images.githubusercontent.com/2210044/95974402-a7cfe100-0e60-11eb-896d-327c5a2d897f.png)

Potentially an OpenGL driver issue? 

I previously saw similar artefacts in other contexts when the GPU on my laptop was overheating and also when a 2080 Ti card in a workstation was starting to die.

However, the fact that this pixels seem to show up in locations where the volume intersects the edge of the frame would not be consisten with hardware issues.

**Comment by VolkerH** [comment]
These are the artefacts that appeared in the [Unigine Heaven benchmark](https://benchmark.unigine.com/heaven) on our 2080 Ti.
Looks quite similar:
![image](https://user-images.githubusercontent.com/2210044/95975347-c4b8e400-0e61-11eb-8347-401f6bf7c24e.png)

**Comment by jni** [comment]
Thanks for the info, @VolkerH! Given that these artifacts happen on very specific parts of the volume for me, I think they have the same source (invalid data), but the reason for the source might be different, corrupted memory vs something wrong with a computation.

And it's very useful to know that this is hardware/driver specific. Annoying, but useful. 😂

**Comment by jni** [comment]
Just confirmed that @joshmoore sees this in his 16" MBP as well. Would be good to hear from other Mac users here including @tlambert03 @AbigailMcGovern and @sofroniewn. I'm particularly curious whether it's an Apple OpenGL driver thing, an AMD thing, or a Catalina thing.

**Comment by tlambert03** [comment]
I see it on a 16" MBP running big sur (radeon pro 5500m) and a desktop running catalina, (with AMD rt 5700 xt).
more interestingly, the desktop can triple boot, and I also see it there in windows 10 (but it's a delightful purple, image below), but _not_ on ubuntu 20 (where it looks like what @VolkerH saw):

<img width="1088" alt="Capture" src="https://user-images.githubusercontent.com/1609449/101552285-9991d300-3980-11eb-8cc1-d848fd1ab068.PNG">

**Comment by jni** [comment]
@tlambert03 well now I'm curious about your hackintosh with an nvidia card. ;) I'm also curious about your Big Sur env! Can I upgrade yet?? =D

Thanks for all the checks!!!

**Comment by tlambert03** [comment]
I'm afraid my nvidia-hack has turned into the 5700xt that I mentioned above (got tired of being on high sierra).  I do still have an older MBP running an nvidia card though!  lemme try that

edit (oh, it's at work... will try tomorrow)

**Comment by tlambert03** [comment]
> I'm also curious about your Big Sur env! Can I upgrade yet?? =D

yeah it's pretty much ok for napari now since #1894 and vispy 0.6.6.  you do still need python 3.9 though.

**Comment by jni** [comment]
> yeah it's pretty much ok for napari now since #1894 and vispy 0.6.6. you do still need python 3.9 though.

I'm specifically wondering whether there's other bits of the scientific Python stack that you might have struggled with, but I guess not!? 🎉

**Comment by VolkerH** [comment]
just for completeness, my linux box referred to above runs Ubuntu 20.04 with a RTX 2060 GPU. 

Also wanted to add that many years back, I remember people having similar issues with Imaris on specific graphics cards. Bitplane used to have a list of tested cards, presumably because of such issues (they probably still do, but I'm too lazy to check).
But more likely than the actual hardware is probably the specific driver, given that Talley sees differences between OS.

**Comment by psobolewskiPhD** [comment]
@jni I can't reproduce this on my arm64 macOS12.6—the example is gone, so I just used the binary blobs 3D. Is this still an issue?

**Comment by psobolewskiPhD** [comment]
Anyone still got a AMD GPU in a Mac to test this?
Or how about someone with an Intel one, which would be more recent, but not arm64.
Seems like something we can't really fix thought...

**Comment by jni** [comment]
I suggest we close since we haven't seen this in a while and it seems to be an OpenGL driver issue, which we can't fix. But if anyone else sees these artifacts and comes across this issue, please comment and/or open a new issue!
