### ISSUE TITLE
Allow rolling to be toggleable for each axis

### ISSUE THREAD

**Issue by kevinyamauchi** [napari/napari#1728]
## 🚀 Feature
@Czaki mentioned in the euro dev meeting today the concept of allowing axis rolling to be turned on/off for specific axes (e.g., if an axis is a time axis). 

## Motivation

Currently, the only axes that aren't rolled are the axes with a length of 1. There are other instances where a user would want to prevent a specific axis from being rolled (e.g., the axis is time).

## Pitch

We add a property (e.g., 'Dims.rollable") that is a boolean D x 1 boolean array to our `Dims` model (each index is an axis and the value specifies if that axis can be rolled). is checked when applying `Dims._roll()`.

**Comment by psobolewskiPhD** [comment]
Closed by https://github.com/napari/napari/pull/5986
