### ISSUE TITLE
Labels layer / paint brush style annotation

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#173]
## 🚀 Feature

In #100 @jni mentions

> in the context of a labels layer I'm working on

I've made this issue to discuss this labels layer, and a possible paint brush annotation layer (which could or could not be related).

I'm curious @jni what you have planned for a labels layer. I've been thinking about a "paintbrush" layer where you can paint pixels either `True` or `False`, or one of N labels (depending on "color" of brush). Imagine you want to annotate foreground / background pixels, or background / cytoplasm / nucleus (say). The underlying data type would be an array though (often the same size as a corresponding image that you are painting over). You would also be able to change the size and shape of the brush, and have an eraser where you set pixels back to `False` or `0` (at which point they are no longer visible). Does this relate to how you are imaging the `labels layer` or would this be different?

**Comment by jni** [comment]
@sofroniewn absolutely! My initial work will just be for displaying, but painting would totally work in the context of this layer. What I'm working on is more for segmentations but should be general enough for sparse labeling. Specifically, the value 0 will always be transparent.

So, in terms of interactivity, we can have "paint", and we can have "merge/split segments". Whether they belong in the same layer type or in subclasses is a question for a later time. =)

**Comment by sofroniewn** [comment]
This sounds great!! I'd say get basics working as a static layer with no interactivity, and then we can see what makes the most sense.

I'd probably lean towards just having this as the same layer type and that we have different modes determined by buttons on the left hand side - like in the shapes layer, but now with things like "paint", "erase", "merge", "split" etc.

**Comment by jni** [comment]
@sofroniewn one issue I'm handling now is that from what I can tell vispy colormaps have to be in [0, 1], so integer labels need to map to float and vice versa, in which case, it might be tricky to add arbitrary labels after the fact. On the other hand, the colormap could get updated dynamically, so I don't think it's a blocker, just perhaps more convoluted than it needs to be.

**Comment by sofroniewn** [comment]
Hmm, that doesn't sound so desirable. I'm surprised vispy doesn't have support for more "categorical" colormaps. I can poke around too.

**Comment by sofroniewn** [comment]
merged in #195
