### ISSUE TITLE
Tracks should give informative error/warning when color_by is invalid

### ISSUE THREAD

**Issue by kevinyamauchi** [napari/napari#1733]
## 🐛 Bug

As reported by @volkerh in #1722: 

> The separate problem I flagged (I should have opened a separate issue)
is dealing with property names passed as color_by that don't exist as keys in
the properties. How should that behandled, raise a ValueError (I'd be happy to the PR)
or just issue a warning?

## To Reproduce

```python

viewer = napari.view_image(np.random.random((100, 100))

tracks_data = [
    [0, 0, 10, 10, 10],
    [0, 1, 10, 10, 20],
    [1, 0, 5, 8, 10],
    [1, 1, 10, 8, 7]
]
tracks_props = {
    'class': ['A', 'A', 'B', 'B']
}
viewer.add_tracks(tracks_data, properties=tracks_props, color_by='not_a_key')

```

## Expected behavior

We should give an informative error message.

I think there are two scenarios we need to handle:
1. the user passes a key to `color_by` that doesn't exist in properties. In this case, I think we should raise a `ValueError` (as @volkerh suggested).
2. the user changes the properties dictionary and the key in `color_by`, which was previously valid, no longer exists. In this case, I think we should take the "first" key in the new properties dictionary and issue a warning

I think both cases could be handled in the setter methods for the `Tracks.color_by` and `Tracks.properties`.

## Environment
napari: 0.3.9.dev40+gd3511ee
Platform: Linux-5.4.0-48-generic-x86_64-with-debian-bullseye-sid
Python: 3.7.7 (default, May 7 2020, 21:25:33) [GCC 7.3.0]
Qt: 5.14.2
PyQt5: 5.14.2
NumPy: 1.19.1
SciPy: 1.5.2
Dask: 2.25.0
VisPy: 0.6.4

GL version: 4.6.0 NVIDIA 450.66
MAX_TEXTURE_SIZE: 32768

Plugins:
- napari_plugin_engine: 0.1.7
- svg: 0.1.4

**Comment by kevinyamauchi** [comment]
Hey, @volkerh! Sorry I missed this second issue in #1722! I have moved it here. If you're still interested, a PR would be greatly appreciated! Please let us know if you have any questions or comments.

edit: I have added my thoughts on how I think the behavior should be in the "Expected behavior" section

**Comment by VolkerH** [comment]
Thanks for moving this into a separate issue. Will start on a PR to address this.
