### ISSUE TITLE
Change name of clims

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#174]
From @jni in #172

> Side note, clims needs a name change

Can you elaborate here / do you have ideas on what name should be?

**Comment by jni** [comment]
clim means literally nothing to someone not already familiar with the terminology and/or our software.

Not sure what the best option is, but something along the lines of `brightness_range` or `displayed_data_range`.

**Comment by sofroniewn** [comment]
Agreed we should have a more intuitive name. `look_up_table_range` is something some communities might understand, but maybe is a little jargony. How about `display_range`?

**Comment by sofroniewn** [comment]
Looking into this more - the same functionality in matplotlib is called `clim` - see [here](https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.clim.html#matplotlib.pyplot.clim) which makes me lean towards keeping. If we are going to change though, I'd like to do it now so that things on the repo can be more stable as we move forward. Thoughts @jni @royerloic?

**Comment by jni** [comment]
I think #310 is more urgent, but anyway. =P

matplotlib itself has a lot of historical baggage, so in terms of API it's not necessarily the best model to move forward with. It's unclear that they would keep it if they were starting anew.

Currently I'm thinking that the middle road is the best one: use `clim` but being more explicit: `contrast_limits`.

**Comment by royerloic** [comment]
I think explicit is better, I thought that clim meant 'color-limits' and I thought it was bad.
'contrast-limits' is a bit better, but technically it is wrong, since both brightness (offset) and contrast(slope) are affected by changing any of the two clim values...  So unless we find 
something better than 'contrast-limits' that's fine. Any ideas?

**Comment by jni** [comment]
"saturation_range", "saturation_limits", "saturation_points"? But I think "contrast_limits" is clear enough, despite your reservations...

**Comment by sofroniewn** [comment]
I'm think `contrast_limits` is fine, agreed it's not strictly correct, but it is clear enough not to be confusing for most people (beginners in particular, whom might have heard of `clim` before in matplotlib and can recognize the similarity)
