### ISSUE TITLE
Lagging/ jerky movement paint brush tool 

### ISSUE THREAD

**Issue by phoenixAja** [napari/napari#1759]
## 🐛 Bug

Hello, I'm relatively new to napari and am trying to build a tool to annotate some high resolution tif H&E stain images. However i'm having some issues with the paintbrush tool, it's acting very laggy and moves sporadically when i try to draw on a label layer, hopefully someone can help provide some insight on how i can fix this issue

## To Reproduce

1. load in image to napari ( my image shape is (3000, 4096, 3) and size is 36M):
`viewer.add_image(image, name="test")`

2. create an empty label layer on top: 
```
    viewer.add_labels(
        np.zeros((3000, 4096), dtype=int),
        name="cell annotations",
)
```

3. select paint brush tool and draw on image.

## Expected behavior
no laggy paintbrush :(

## Environment

```
napari: 0.3.8
Platform: Darwin-19.6.0-x86_64-i386-64bit
Python: 3.7.8 | packaged by conda-forge | (default, Jul 31 2020, 02:37:09)  [Clang 10.0.1 ]
Qt: 5.14.2
PyQt5: 5.14.2
NumPy: 1.19.1
SciPy: 1.2.1
Dask: 2.30.0
VisPy: 0.6.5

GL version:  2.1 ATI-3.10.18
MAX_TEXTURE_SIZE: 16384

Plugins:
  - napari_plugin_engine: 0.1.8
  - svg: 0.1.4
```

## Additional context
Here's a screenshot of the issue:
![laggy_paintbrush](https://user-images.githubusercontent.com/13052132/96930047-ee7c9700-146f-11eb-9bd5-2a92723212d0.gif)

I tried loading the images with `dask_image.imread` but the paintbrush tool was still very laggy. 

I also tried loading the `data.astronaut()` image, creating a label layer, and painting on the image and did not have the same laggy paint brush issue. Is this because my image is just too big? Are there any other workarounds i can try?

**Comment by sofroniewn** [comment]
> Is this because my image is just too big?

Hi @phoenixAja unfortunately we're slow for big images right now - I think 1024x1024 is still ok, but any larger starts to get laggy. We definitely want to speed this up. There was some investigation in #713 and discussion in #204, and right now it looks like we have to make some improvements in the underlying rendering library. @jni do you have any update or ideas on how to move forward here?

**Comment by jni** [comment]
@sofroniewn there's two wonderful open PRs from @djhoese in vispy, https://github.com/vispy/vispy/pull/1912 and https://github.com/vispy/vispy/pull/1920, that will allow us to directly send label ([u]int32) data to the GPU for rendering. That's really The Right Way to do this, everything else was just a hack, so we should help review those and push those along. I think the current status is that https://github.com/vispy/vispy/pull/1912 is waiting on https://github.com/vispy/vispy/pull/1920 to make sure that the APIs are consistent, and https://github.com/vispy/vispy/pull/1920 is waiting on review. I had a very quick look and on first pass it looks great!

**Comment by sofroniewn** [comment]
Ok, thanks @jni I can give those some review this weekend! Very exciting!!

**Comment by djhoese** [comment]
Thanks @jni for bringing this up. I've meant to put more work into the ImageVisual PR (but yes it still needs review), but got distracted trying to rewrite the whole website (then excuse, excuse, excuse). I appreciate any looking over those PRs can get. I know there are at least some things from the ImageVisual PR that need to be used in the VolumeVisual after I learned some new things about how the textures were being represented in the shader.

**Comment by psobolewskiPhD** [comment]
Using some 7Kx5K images of my own, this is still an issue on 0.4.17, but on main bd69fd21a5b2a2112ff13b78ee88e96e13064ee7 it's smooth as butter.
I assume https://github.com/napari/napari/pull/5732 solved this.

**Comment by jni** [comment]
I agree @psobolewskiPhD, we can close this. Finally! 😅
