### ISSUE TITLE
[Feature] Create a keyboard shortcut or a button to select all points loaded in napari GUI

### ISSUE THREAD

**Issue by rdbcasillas** [napari/napari#1760]
## 🚀 Feature
Create a keyboard shortcut to select all points loaded in napari GUI

## Motivation
I am using cellfinder-napari which allows visualization and annotation of cells within 2d brain images. Using napari GUI, I can only select specific points within a specific plane. I cannot generalize my modifications to all the points in all the planes. 
Following snapshot shows few points selected after clicking on "select points"

![image](https://user-images.githubusercontent.com/9725334/96947144-fd7f3b80-14a7-11eb-9a87-e393fcae7805.png)

But notice at the bottom right corner that this is for 131st (out of 549) plane. Any modifications I make to these points will not be reflected in the points that show up in any other plane (once I start going from left to right). So It can be frustration to individually select points again and again and make modification for each selection. 

## Pitch
A keyboard shortcut or a button that selects every single point so that the modifications (increase/decrease point size, change color, change shape) can be applied to everything and not just few selected points. 

## Alternatives

@sofroniewn has mentioned [here](https://github.com/brainglobe/cellfinder/issues/103#issuecomment-713703809) that this can be done via CLI using: 

```layer.selected_data = list(range(len(layer.data)))```

But I am not sure if I can use this technique as I am using an existing plugin. I haven't yet looked into writing a plugin myself but if this feature is hard to implement at the moment, then I will definitely look into it.

**Comment by jni** [comment]
A great suggestion, thanks for raising it @rdbcasillas!

One thing to consider is whether user would want to also have a shortcut to select all *visible* points. So we could do e.g. "ctrl-a" - select all visible points, "ctrl-shift-a" select all points in the data. (Or vice versa).

A potentially useful reference is Gmail: select all selects the current page of emails, with a message asking whether you want to select all emails matching the current filter. Probably we have to up our messaging game in our UI before we can be this sophisticated, though. 😬 We'll get there!

**Comment by sofroniewn** [comment]
> One thing to consider is whether user would want to also have a shortcut to select all visible points. 

All points in the current slice is `A` https://github.com/napari/napari/blob/v0.3.8/napari/layers/points/_points_key_bindings.py#L54-L59

**Comment by psobolewskiPhD** [comment]
I think https://github.com/napari/napari/pull/4809 closes this?
It implemented the ability to select all points in a layer vs. just the ones in a current view:
<img width="831" alt="image" src="https://github.com/napari/napari/assets/76622105/b89abcab-4041-4c46-972f-35ff236386c6">

Works in 3D mode too!

**Comment by jni** [comment]
@psobolewskiPhD one thing I would like us to add before closing is an "Edit" menu with a "select all" option.

**Comment by psobolewskiPhD** [comment]
I'm all for an edit menu:

https://github.com/napari/napari/issues/5080

**Comment by jni** [comment]
haha very good, I guess we can close this then?

**Comment by psobolewskiPhD** [comment]
I think so, I mean the OP asks for keyboard shortcuts, which do exist.
I think we should probably look into better documentation for 1. existing shortcuts and 2. the ability to change them.
https://github.com/napari/docs/issues/13
