### ISSUE TITLE
[Enhancement] Add checkbox for toggling SELECTED label color mode

### ISSUE THREAD

**Issue by DragaDoncila** [napari/napari#1761]
## 🚀 Feature
Add a checkbox to toggle between SELECTED color mode and previous color mode for labels layers.

![selected_checkbox](https://user-images.githubusercontent.com/17995243/96948952-880c7d00-1532-11eb-887f-decc09e22a41.gif)

## Motivation

During user feedback session, users were expecting the label selection spinbox to cycle through the displayed labels, and were confused by having to change color mode to SELECTED to achieve that functionality. A checkbox next to the spinbox would maybe be more intuitive, and also faster when needing to toggle frequently.

I don't necessarily think we should remove the option of selecting it from the drop down, but this may provide the best of both worlds. Happy to hear other suggestions of making the SELECTED color mode more discoverable.

**Comment by jni** [comment]
I love this! I think actually that we *should* remove "selected" from the menu, I think that's part of the confusion. I think @Czaki already mentioned that it was suboptimal that the "selected" mode got the colormap from the last selection of "auto" or "direct". Now it doesn't have to be history dependent: the colormap is either auto or direct, and "selected" is a tick box on how the colormap is displayed.

**Comment by sofroniewn** [comment]
> I love this! I think actually that we should remove "selected" from the menu, I think that's part of the confusion. I think @Czaki already mentioned that it was suboptimal that the "selected" mode got the colormap from the last selection of "auto" or "direct". Now it doesn't have to be history dependent: the colormap is either auto or direct, and "selected" is a tick box on how the colormap is displayed.

Yes, I think we should drop this from the drop-down and not have two places where you can change the same functionality

**Comment by Czaki** [comment]
@sofroniewn @DragaDoncila I would like to show how I solve this in my tool in the case where I need a selection of components:

![napari-selection](https://user-images.githubusercontent.com/3826210/96971139-fc382800-1514-11eb-9dc8-e5e1c6e15481.gif)

This what is symilar to the selected mode in napari is hilight when mouse is over checklbox which representing component (implemented using adding small layer). 

And showing selection allows user to see whole group of selected components. So it is possible to hilight one object, but also fast chcek if all objects from one group is marked. Currently, this is implemented by manipulating colormap.  

For me selected means that I could select more than one component. Currently, it looks rather like hilight. For me `napari` should support selecting multiple components as part of core functionality.

**Comment by sofroniewn** [comment]
This has been closed by #1762. We might want to allow selection of multiple labels at some point in time, but we can open a new issue to discuss that when ready.
