### ISSUE TITLE
bundled napari install failure

### ISSUE THREAD

**Issue by berl** [napari/napari#1766]
I tried out the napari 0.3.8 bundle on a Windows 10 system and the installer fails with errors 2503 and 2502. 

Full disclosure, this is the same system that has had [problems with napari install due to vispy's freetype-py dependency](https://forum.image.sc/t/error-freetype-library-not-found-during-adding-points/41742/12)

I have a feeling there may be some background security processes blocking some types of installation on this machine, so this is likely a low-priority / edge case issue.

**Comment by liu-ziyang** [comment]
a shot in the dark: the Microsoft C++ build tool might need to be preinstalled for vispy to work, (see https://github.com/napari/napari/issues/1340):  https://visualstudio.microsoft.com/downloads/
however I am not 100% sure because it sounds like freetype is the problem

**Comment by berl** [comment]
@ziyangczi `napari` installation via `pip` does work on this machine (provided I do the freetype workaround mentioned over on imagesc)

**Comment by liu-ziyang** [comment]
fwiw I have been trying on my machine (fresh windows installation) for past few days, tracks layer have been working for me, so I am working on getting more data samples from more machines, would be great if you have any additional information on the environment, particularly if there is any warning on this missing dll during installation etc, and can you also verify freetype-py ver 2.2.0 is in your python virtual environment?

**Comment by liu-ziyang** [comment]
can you please try 0.4.0 release and see if the problem persists? I am semi convinced that vc++ is required to run on windows, you can get the distribute instead of the full VisualStudio: https://aka.ms/vs/16/release/VC_redist.x64.exe

**Comment by berl** [comment]
0.4.0 bundled install works on one of my Windows machines- thanks!
a bit more detail  [here in a related issue](https://github.com/napari/napari/issues/1825#issuecomment-726958194)

@ziyangczi  I'm going to close this out since it's specifically about the bundled install and 0.4.0 install works (on a normal-ish Windows machine)
