### ISSUE TITLE
Lots of warnings on bundle build process

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#1767]
## 🐛 Bug

I just got a lot of warnings around our bundle build process, which might be something we need to look into before the 0.4.0 release. It looks GitHub actions related, but I havn't looked at it yet. Maybe @ziyangczi you can check it out quickly, thanks!!

https://github.com/napari/napari/actions/runs/271068453

cc @jni

**Comment by liu-ziyang** [comment]
Because our macos build failed for 0.3.8 so I attempted to rebuild it, which triggered the warnings it seems, I am going to take a look and update the https://github.com/napari/napari/issues/1768

**Comment by liu-ziyang** [comment]
this is related to https://github.com/napari/napari/issues/1611, going to close this issue
