### ISSUE TITLE
export to svg

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#178]
## 🚀 Feature
Add support for export to svg

From @freeman-lab, mentioned in #100: 

> High-level agreement with @jni that this [napari] need not become illustrator :) with my user hat on, if we eventually have “export to svg” then I can do all fine tuning in other programs, making many features overkill to do within Napari. But without that, I may end up reproducing in Matplotlib what I already have in Napari just to fine tune the plot and/or get that SVG — not a dealbreaker but nice to avoid if possible.

**Comment by freeman-lab** [comment]
this library might prove useful https://github.com/mozman/svgwrite

possible solution: programmatically assemble the SVG object using this library given the image layer contents (represented as an `Image` element) and all of the shape data (built using `Polyline`, `Polygon`, etc.), and dump the whole thing to an SVG file alongside a PNG linked to in the `Image` field

**Comment by royerloic** [comment]
From Slack:
One approach is to have each layer know how to export itself as svg. The viewer can then ask each layer to produce a SVG group. Actually, we could have a SVG view for each layer type that takes a layer type and produces a SVG group. That would be a continuation of the Model-View paradigm.
