### ISSUE TITLE
Scale bar and axes are not scaled properly on init

### ISSUE THREAD

**Issue by kevinyamauchi** [napari/napari#1789]
## 🐛 Bug

When I make the scale bar and/or the axes visible via the GUI, they initially show up super tiny. Then when I zoom a bit (one "click" on my mouse wheel), they become normally sized.

## To Reproduce

1. Open the `nD_labeyls.py` example
2. From menus make the axes and scale bar visible (View -> Axes / Scale bar-> Visible). They now visible, but tiny in the upper left hand and lower right hand corners, respectively.
![axes](https://user-images.githubusercontent.com/1120672/97414310-1ce0f300-1904-11eb-98a3-995f31a02c89.png)

3. Change the zoom. The axes and scale bar are now "normally" sized. If I return to the original zoom level, they maintain their size.
![axes_2](https://user-images.githubusercontent.com/1120672/97414337-266a5b00-1904-11eb-8a50-2aefa321adaf.png)

## Expected behavior
They are initialized with the correct size.

## Environment

napari: 0.3.9.dev27+g52cc6cd.d20201006
Platform: Linux-5.4.0-52-generic-x86_64-with-debian-bullseye-sid
Python: 3.7.7 (default, May 7 2020, 21:25:33) [GCC 7.3.0]
Qt: 5.14.2
PyQt5: 5.14.2
NumPy: 1.19.1
SciPy: 1.5.2
Dask: 2.24.0
VisPy: 0.6.4

GL version: 4.6.0 NVIDIA 450.66
MAX_TEXTURE_SIZE: 32768

Plugins:
- napari_plugin_engine: 0.1.7
- svg: 0.1.4

**Comment by jni** [comment]
I can confirm this. It's so CUTE! 😜

**Comment by jni** [comment]
Playing around locally, I can semi-trivially fix this by calling `_on_zoom_change` from `_on_visible_change` [here](https://github.com/napari/napari/blob/b576203c58fc71d06460811a6a0eff8fb7191061/napari/_vispy/vispy_axes_visual.py#L120-L134) (respectively [here](https://github.com/napari/napari/blob/b576203c58fc71d06460811a6a0eff8fb7191061/napari/_vispy/vispy_scale_bar_visual.py#L114-L117)), or connecting visible events to `_on_zoom_change`, but I don't know if that's the "right" way to fix this...

**Comment by sofroniewn** [comment]
Lol, thanks for the report @kevinyamauchi and suggestion for fix @jni. I can give that a go today, and see if we can get it done for this release!

**Comment by sofroniewn** [comment]
> Playing around locally, I can semi-trivially fix this by calling _on_zoom_change from _on_visible_change here (respectively here), or connecting visible events to _on_zoom_change, but I don't know if that's the "right" way to fix this...

Yes that is the "right" fix as we return when visible False inside that method, so we need to recall when set true
