### ISSUE TITLE
Napari IO plugin refactor

### ISSUE THREAD

**Issue by Czaki** [napari/napari#1790]
## 🚀 Feature
Currently, the user who would like to save some data needs to exactly know extension what he would like to use and be sure that the plugin order is proper. 

Also when thinking about the reading plugin. There should be some options to select which one user uses without go to the plugin widget to control the plugin order. 

As an example currently napari provide only a simple tiff reading utility which read it to numpy ndarray. I have my plugin which read metadata from image and loads it as a separate image layer for each channel in an image. I mostly prefer to use my plugin (because of the current workflow), but there are cases when I prefer to load it using the builtin plugin. Both accept `*.tif` extension. 

For me save plugins should provide information about file format which support and human-readable name to allow user simple save method selection. 

I propose to use class like interface:

```python
class SaveBase(ABC):
	@staticmethod
	@abstractmethod
	def could_save(file_path: str,  layer_types: List[str]) -> bool:
		"""check if plugin could save data napari_get_writer"""

	@staticmethod
	@abstractmethod
	def save(file_path: str,  layer_data: List[Tuple[Any, Dict, str]]) -> bool:
		"""check if plugin could save data napari_get_writer"""

	@staticmethod
	def get_layer_type() -> str:
		"""information if method is for save single layer type is support Single Layers IO"""
		return "all"
	
	@staticmethod
	@abstractmethod
	def get_name_filter():
		"""return name filter for use in QFileDialog https://doc.qt.io/qt-5/qfiledialog.html#setNameFilters"""
```

```python
class LoadBase(ABC):
	@staticmethod
	@abstractmethod
	def could_load(file_path: Union[str, List[str]]) -> bool:
		"""check if plugin could save data napari_get_reader"""

	@staticmethod
	@abstractmethod
	def load(file_path: Union[str, List[str]]) -> List[Union[Tuple[Any], Tuple[Any, Dict], Tuple[Any, Dict, str]]]:
		"""check if plugin could save data napari_get_writer"""
	
	@staticmethod
	@abstractmethod
	def get_name_filter():
		"""return name filter for use in QFileDialog https://doc.qt.io/qt-5/qfiledialog.html#setNameFilters"""
```

`could_save` and `could_load` method allow using `Auto discover(*.*)` name filter which is current behavior and drag and drop mechanism.  

I think that people may want to create their own save plugin to add save project utility for their case.

If using class base plugins then backward compatibility could be easy to do for `Auto discover(*.*)` by using `isinstance`.

**Comment by neuromusic** [comment]
> There should be some options to select which one user uses withou go to the plugin widget to control the plugin order.

I know this issue is focused on the implementation, but there are two workflows that come to mind when thinking of ways to give the user simple defaults while still allowing them some flexibility.

The first is how Android handles letting the user decide which App to use for a given action that many Apps support (like taking a picture or making a phone call): the first time, they are asked which App they want to use, then that becomes the default until they clear it in the App's settings.

The second is how MacOS handles file opening... each filetype (based on MIME types, iirc) gets assigned a default program to open it, but the user can right click to open it with a different program. That context menu also has a link to change the settings for default assignment.

**Comment by Czaki** [comment]
> The first is how Android handles letting the user decide which App to use for a given action that many Apps support (like taking a picture or making a phone call): the first time, they are asked which App they want to use, then that becomes the default until they clear it in the App's settings.

This could be mimic by remember of selected name filter in previous use of widget (this may need #1183) 
 
> The second is how MacOS handles file opening... each filetype (based on MIME types, iirc) gets assigned a default program to open it, but the user can right click to open it with a different program. That context menu also has a link to change the settings for default assignment.

This is same as usage `Auto discover (*.*)` name filter.

**Comment by jni** [comment]
I'm open to this, but I would like us to explore the possibility of providing this functionality using the current hookspec implementation. e.g. existing plugins could provide a file filter hookspec? In short, it would be great if we could provide file filters *without* deprecating all the plugins already out there.

Also, related discussion is happening right now at imageio/imageio#562.

**Comment by Czaki** [comment]
> I'm open to this, but I would like us to explore the possibility of providing this functionality using the current hookspec implementation. e.g. existing plugins could provide a file filter hookspec? In short, it would be great if we could provide file filters _without_ deprecating all the plugins already out there.

Does this not address your concerns?

> If using class base plugins then backward compatibility could be easy to do for Auto discover(*.*) by using `isinstance`.

**Comment by jni** [comment]
> If using class base plugins then backward compatibility could be easy to do for Auto discover(.) by using isinstance.

I'm confused about what this means. Are you saying we build a class internally for existing plugins? Existing plugins don't use classes?

**Comment by Czaki** [comment]
> I'm confused about what this means. Are you saying we build a class internally for existing plugins? Existing plugins don't use classes?

The current napari plugin ecosystem is function-based. So if we introduce a new version of plugin specification we could give support to old plugins by simple if:

```python
if isinstance(plugin, SaveBase):
	new_method()
else:
	old_method()
```

For simplifying this there may be some base class for all plugins (also future one).

I found now one additional argument to switch to class like approach. 

Two weeks ago at the meeting, there was a discussion about future support of the data processing pipeline. Such a pipeline should allow performing io operation. And Pipeline behavior should not depend on the current configuration (plugin order) in the program. Then the user needs to have the possibility to precise select io method. There may be need to add some additional methods to the proper render widget for it. In my code I have `AlgorithmDescribeBase` class which is base of all operations https://github.com/4DNucleome/PartSeg/blob/dc5ce1aeac80018f1e78dc49d7fa559090d52ce9/package/PartSegCore/algorithm_describe_base.py#L65. It may be good idea to start a discusion, but I'm not sure if it could address all napari requirements.


I add `get_layer_type` function to `SaveBase` for support SingleLayerIo. 

I look at imageio/imageio#562 and I see one problem. During yesterday meeting people from zarr told that they are not enthusiastic about extension base discover system. Or even single file. Some of data are stored in multiple files and may need to chcekc its existence and their headers until decide if its supported.

**Comment by tlambert03** [comment]
I completely agree there's a need for plugins to be able to indicate what extensions they can handle without having to actually call the function.  This came up early on in the plugin meetings, and we just never got around to adding it.  Essentially, this amounts to providing a little bit more metadata along with the hook implementation, and I think there are a number of ways this could be implemented (both using classes and not using classes).

---
### namespace classes

@Czaki's suggestion here could work, but I'd like to point out that this isn't exactly a class (that must be subclassed ... in the traditional sense) as much as it is a namespace.  All of the proposed methods are static methods... so if you go in this direction, I would _not_ suggest using an abstract base class with `@abstractmethods` that a user must import from napari.  (Not requiring the developer to import napari and subclass something to make a plugin was an early design goal, and I think it's worth maintaining that if possible).  However, you could achieve the same runtime checking using `typing.Protocol`, and the presence/absence of various methods could be asserted during plugin registration:

```python
from typing import Protocol, runtime_checkable

@runtime_checkable
class LoadPlugin(Protocol):
    def get_reader(path): ...
    def get_name_filter(): ...


# then the plugin looks like:

@napari_hook_implementation
class MyReaderPlugin:
    def get_reader(path):
        ...
    def get_name_filter():
        ...

# and you can still use isinstance if you want to:
isinstance(MyReaderPlugin, LoadPlugin)  # True
```

The complete implementation of this solution, however, will require a good amount of work in [napari-plugin-engine](https://github.com/napari/napari-plugin-engine) and also in the napari `PluginManager` object to accommodate registration of namespaces that _contain_ callables (rather than directly registering the callable itself).

### `metadata` in the decorator

An alternative method for associating additional information with a specific `hook_implementation` would be to add a `metadata` parameter to the `@napari_hook_implementation` decorator, which would be used as follows:

```python

@napari_hook_implementation(metadata={'extensions': ['.tif', '.tiff']})
def napari_get_reader(path):
    ...
```

This would be very easy to implement in `napari-plugin-engine` and then we could make it so that registered extensions could be queried something like this: `plugin_manager.hooks.napari_get_reader.metadata.get('extensions')`

----

personally, I think unless we can think of specific use cases where we need to allow a plugin to actually maintain and share state _between_ calls to its various methods, we should stick with the simpler pure functional API for now.  It _may_ be necessary to do something with classes in the future, but I'm not convinced this is the perfect application.

**Comment by Czaki** [comment]
Yes. I forget to add Protocol to proposition. 

`extension` metadata still does not allow to create drop down list which clearly inform user about supported extensions and name of saving method. So user cannot deterministically chose saving method (which means that if this method fail he got error information instead of try next method) 

For me collecting metadata in class (using classmethod and staticmethod) allow to reuse same code in other places. If metadata are passed as arguments to `napari_hook_implementation` then it is harder and force information duplication.

**Comment by tlambert03** [comment]
> `extension` metadata still does not allow to create drop down list which clearly inform user about supported extensions and name of saving method.

Why doesn't it?

> If metadata are passed as arguments to `napari_hook_implementation` then it is harder and force information duplication. 

also disagree... code deduplication could be accomplished equally in both cases (by passing functions as variables and/or using variables for filters).  let me know if you'd like an example.  Again, the _only_ thing that I can think of that can't be achieved simply without classes is maintenance of state between calls _while_ maintaining inheritance

**Comment by Czaki** [comment]
> Why doesn't it?

There could be more than one method that save Tiff. Ex one for Imagej tiff and ome-tiff. Which cannot be selected by extension. 


> also disagree... code deduplication could be accomplished equally in both cases (by passing functions as variables and/or using variables for filters). let me know if you'd like an example. Again, the _only_ thing that I can think of that can't be achieved simply without classes is maintenance of state between calls _while_ maintaining inheritance

When creating a plugin to read "project" information I want to get information about why loading file of a given type fails. Not get None information. Class like interface provide two methods. One for chceking if file could be loaded and second to load. Functional combine it into one and does not allow to call load method directly.

**Comment by tlambert03** [comment]
> There could be more than one method that save Tiff. Ex one for Imagej tiff and ome-tiff. Which cannot be selected by extension.

yes, but we'll still know exactly which methods they are... I'm just not following, can you provide an example?

> Functional combine it into one and does not allow to call load method directly.

this is just an implementation detail of the napari `plugin_manager`, not the hookspec itself. it would be trivial to allow users to call the `napari_get_reader` directly without immediately calling the reader function afterwards, which would act exactly as your `could_load` method.  Furthermore, the functional method allows you to return different readers depending on characteristics of the file (which `could_load() -> bool` does not).

**Comment by Czaki** [comment]
> yes, but we'll still know exactly which methods they are... I'm just not following, can you provide an example?

From the user interface? 

> this is just an implementation detail of the napari `plugin_manager`, not the hookspec itself. it would be trivial to allow users to call the `napari_get_reader` directly without immediately calling the reader function afterwards, which would act exactly as your `could_load` method. Furthermore, the functional method allows you to return different readers depending on characteristics of the file (which `could_load() -> bool` does not).

Ok. I call `napari_get_reader` and got `None`. How I could debug why there is no reader. 

But I even think about the simpler case. 
I would like to create some loader for project (for example described with json). Then I know that data are stored in zarr file. Then best is to use ome-zarr plugin (to have properly formatted output). If I call `napari_get_reader` from `ome-zarr` I could got `None` return without information why loader cannot handle this data. Of course, I could directly call the method used in the implementation, but there is no guarantee of api stability. I could use the public API of ome-zarr package, but this is a repetition of work that is already done.

**Comment by tlambert03** [comment]
> From the user interface?

As I said in my first comment, we all agree (and have always intended) that there be a better way to provide a file filter in the `QtFileDialog` when opening a file from the UI.  The current GUI is definitely in need of further development ... I just don't see why the class approach in the plugin hookspec is necessary for that over the `metadata` approach.

> Ok. I call `napari_get_reader` and got None. How I could debug why there is no reader.

The same way you'd debug it if you got `False` returned from your `could_load` function!
Are you perhaps thinking about a case where the plugin developer made an error such that their `could_load` function returned `False` when in fact their `load` function _was_ able to read it?  If so, then we're essentially talking about a broken plugin... and yes, at that point, if someone were trying to debug a broken plugin, I _would_ encourage them to look directly at the plugin implementation.

**Comment by Czaki** [comment]
> The same way you'd debug it if you got `False` returned from your `could_load` function!
> Are you perhaps thinking about a case where the plugin developer made an error such that their `could_load` function returned `False` when in fact their `load` function _was_ able to read it? If so, then we're essentially talking about a broken plugin... and yes, at that point, if someone were trying to debug a broken plugin, I _would_ encourage them to look directly at the plugin implementation.

I think rather about feedback from user. I think that better will be to got feedback. "I cannot read data, here stacktrace" than "I cannot load data and there is no message". 

In my solution plugin creator could directly call load method of other plugin. and `could_load` is designed for plugin auto selection. 

For fixing, of course the best is to check implementation of used plugin.

**Comment by tlambert03** [comment]
I mentioned this above, but I'll point it out again: in the current model, a plugin needn't be restricted to a _single_ reader function.  `napari_get_reader` can return any number of different functions.  So your `LoadBase.load` proposal is restricting the scope of what a plugin can do.

Think of a potential bioformats plugin... with your model, that plugin would need to provide us with hundreds of different `LoadBase` classes, and it would be registered as hundreds of reader plugins `bioformats-tiff`, `bioformats-dv`, `bioformats-nd2`, etc...  With the current model, then can provide a single `napari_get_reader` hook (a single `bioformats` plugin) that could return the appropriate function depending on the file format.  If you wanted to get to the actual reader function itself in napari, you would do this:
```python
reader = napari.plugins.plugin_manager.hooks.napari_get_reader(path='path.ext', _plugin='bioformats')
```
if `reader` is `None` it means that the plugin didn't think it had _any_ functions that could read `path.ext`... if a third plugin creator _still_ wanted to directly call some specific load method of the bioformats plugin (even though the bioformats plugin itself didn't think it had one), then yes, the plugin creator would have to look at the bioformats plugin source code.  I think that's a decent compromise for the power gained by the current flexible model.

**Comment by Czaki** [comment]
> I mentioned this above, but I'll point it out again: in the current model, a plugin needn't be restricted to a _single_ reader function. `napari_get_reader` can return any number of different functions. So your `LoadBase.load` proposal is restricting the scope of what a plugin can do.

I do not understand. Why `load` method cannot do the same selection of inner method as is done currently in the functional approach, but end with the exception on failing instead of return None?

**Comment by tlambert03** [comment]
we could... but I'm dubious about how that improves the napari plugin architecture.  It appears that what you're most concerned with is a way to get at the actual reader function that would have been returned by `napari_get_reader` even if the plugin's `napari_get_reader` implementation didn't want to return that function (i.e. even if the plugin thought that it couldn't read the file).  is that correct?  If so, why don't you want to just import it from the plugin directly?

**Comment by Czaki** [comment]
During euro dev meeting it was mentioned that, in the future,napari should also be accessible by nonprograming persons (ex. biologist). Then silent fail (or "file load failed" dialog) is a really bad idea. 

My idea allows for keeping auto-discover using `could_save` and got an error message when the user selects the loading method.

**Comment by tlambert03** [comment]
The degree to which exceptions are visible in the GUI or not is a totally different conversation, no? ... I fully agree that we should continue to improve the presentation of error messages in the GUI.  It was never the plan or idea that it should fail silently! Just something that no one's gotten around to yet.  With the addition of the notification system we have the groundwork for transitioning error notifications from the console to the GUI, but that has always been, and continues to be a work in progress.  But I'm still missing how your class-based proposal somehow lets us give an error message in a way that the function-based hookspecs don't?

**Comment by tlambert03** [comment]
> My idea allows for keeping auto-discover using could_save and got an error message when the user selects the loading method.

are you maybe getting distracted by the fact that we currently use `firstresult=True` when calling `napari_get_writer`?  If I'm understanding you correctly, what you're proposing can also be achieved in the current system by calling `napari_get_writer/reader` _without_ `firstresult` being True, in which case it will return to you a list of plugin reader functions that are compatible with the request.  The user could then select the specific one they wanted.  To me, this seems nearly identical to calling `could_save` on all of the plugins, then calling `save` once the user picks a specific one

**Comment by Czaki** [comment]
Current hookspecs does not allow to provide information about why this plugin cannot load the given file. 

And if you do not want to go to desk of non programing user to check what happens there should be such possibility.

**Comment by tlambert03** [comment]
> Current hookspecs does not allow to provide information about why this plugin cannot load the given file.

how does `could_load() -> False` provide more information?

**Comment by Czaki** [comment]
direct call of load should provide. But maybe it should return somethin more detailed.

**Comment by jni** [comment]
I must say I'm not seeing the rationale here either @Czaki... Currently we have:

* From napari:
  - napari_get_reader(path) -> can't load -> None
  - napari_get_reader(path) -> falsely think I can load -> function -> called -> Error

* From Python:
   - `reader = napari.plugins.plugin_manager.hooks.napari_get_reader(path='path.ext', _plugin='bioformats')`, as pointed by @tlambert03 above. This is a bit cumbersome but we can certainly make it easier, and anyway with a class based system, it would be equally cumbersome to pick out individual plugins. And, as @tlambert03 mentions, you can load the plugin *directly* from Python. tbh that is the principal goal for me, to blur the line as much as possible between plugins and pure Python packages.

With the class, from napari, we can do... Exactly the same, right? You say we can check *why* it can't load, but as far as I can tell, that is by calling it *from Python*, which we can do with the current plugins also? If the `can_load` function itself needs to provide more info, then that is still a problem with the class based system... We would need a signature like `can_load -> bool, str`. Which feels clunky. Something like a log is more natural here.

It seems to me that the two methods are fundamentally equivalent on some level, with the namespacing that @tlambert03 proposed...

Whether one is more intuitive than another is another question. One thing we could try to aim for is to *not* make a different protocol from others, and work with the community for a common format. See e.g. https://blog.danallan.com/posts/2020-03-07-reader-protocol/

**Comment by Czaki** [comment]
Every other data load system allows for the direct call load method and got stacktrace on fail which allows debugging this case without the need to access to the computer with data. 

There are two questions:

1) If napari should be only for programer, or there is a plan to make it available for nonprogramming user? 

If first then is not a problem and the whole discussion is obsolete. A programming person could always debug. If second then fail "Fail" is a really bad idea for me. There should be some method to inform the user why load fails. I do not persis that my proposition solves this, but I think that it could be easier to introduce something like this using a class-based reader which could have one method to check if the file could be loaded and a second one to inform what is missed. 

There is also the possibility to return some specific object with such information instead of `None` from the function 

2) If there are plans to support the loading/saving method which need additional user input (like the selection if use relative path). 

In general, I have a bad experience with a report from a non-programming person. They rather stop using the tool than investigating time to provide information about the failure. Maybe, because of this, I'm focused on debug information.  

I agree that the same effect could be reached by optional arguments in hook register function. For Me, the class-based interface is cleaner. I like pythonic flexibility, but in such basic features, I like strong typing. 

I'm not sure If I could better explain my point of view without some meeting.

**Comment by jni** [comment]
> If napari should be only for programer, or there is a plan to make it available for nonprogramming user?

both

> If second then fail "Fail" is a really bad idea for me. There should be some method to inform the user why load fails.

We don't have such a policy. It's something we are aiming to fix, but this is a completely different issue from this one and is discussed in #1395, #1145, #1090, and #1501 (now closed but I don't really know why). In short: we are in complete agreement that not being able to see the plugin errors is a huge problem! But fixing it does not require a refactor of plugins, but rather of napari's error handling.

> There is also the possibility to return some specific object with such information instead of None from the function

Yep, this is also something we can consider. We could have it return a string if it wants to provide a reason why it won't read. But this does not require a complete refactor, rather than a slight modification of the hookspec, or the addition of a new hookspec.

> If there are plans to support the loading/saving method which need additional user input (like the selection if use relative path).

Yes, @sofroniewn got started with this in #616 and see discussion in #604, but the work stalled and wasn't revisited. We'd definitely love for this to be picked up again!

> For Me, the class-based interface is cleaner. I like pythonic flexibility, but in such basic features, I like strong typing.

I think this is subjective. I personally prefer the get_reader pattern. I don't think it's incompatible with strong typing — in fact the type signature of the function is required, which is a much stronger check than usually seen in Python. For me, I find classes and class hierarchies complicated and difficult to navigate.

Sorry, I don't think my subjective preference is any more valid than yours. I just think that refactoring an already successful system needs to meet a high bar of necessity. From what I can tell in the above discussion, your major concerns can be addressed within the current framework, so my opinion is that we should try to address them in that way... We can definitely revisit this idea. If enough people think it's more intuitive, maybe we could also provide e.g. `napari_class_reader` as a new hookspec, while still keeping the existing functional one...

**Comment by Czaki** [comment]
> We don't have such a policy. It's something we are aiming to fix, but this is a completely different issue from this one and is discussed in #1395, #1145, #1090, and #1501 (now closed but I don't really know why). In short: we are in complete agreement that not being able to see the plugin errors is a huge problem! But fixing it does not require a refactor of plugins, but rather of napari's error handling.

No. Current approach allows plugin silent fail. I select a plugin that should support reading some type of file it could return `None` without information as why there is no reader for this file. And this produces silent fails without the possibility to report information to the user. And this is built int in the current plugin architecture and cannot be changed without change specification. 

Let's see the example of `tifffile`. To read LZW compressed files it needs the `imagecodecs` package. I could imagine a reader that checks not an only extension but also check the header of the file and see that it is compressed with LZW and package `imagecodecs` is not installed then this function returns `None` (`imagecodecs` package is not available on non x86 architectures). And how, base on `None` return, you want to build meesge for the user? 

I do not insist that there is need to swich to class based architecture. The current one is great for autodiscover which plugin could read given file, but I see no option te report some fails to user if user may have the possibility to select which plugins he would like to use to read given file.

**Comment by tlambert03** [comment]
> Let's see the example of tifffile. To read LZW compressed files it needs the imagecodecs package. I could imagine a reader that checks not an only extension but also check the header of the file and see that it is compressed with LZW and package imagecodecs is not installed then this function return 

If the file ended in `.tiff` but required LZW, then `napari_get_reader` would return a reader function (not `None`), that function would fail [here](https://github.com/napari/napari/blob/ed34af845176adf9183d77b0e21c7a53e1a0f322/napari/plugins/io.py#L88) (raising an exception) and then in napari (and here's the implementation detail we all agree needs work) that exception would be [caught in `read_data_with_plugins`](https://github.com/napari/napari/blob/ed34af845176adf9183d77b0e21c7a53e1a0f322/napari/plugins/io.py#L91) and stored as a `PluginCallError` that can later be reviewed in the "Plugins > Plugin Errors..." menu.

**Nobody is arguing that this is a good, user-friendly design!**. It was designed _before_ we had the notification system introduced in #1511 and before we introduced the `sys.excepthook` in #1476 (previously, an error in a plugin would have simply crashed the whole program).  What needs to happen (now that we have those systems in place) is to go back [let that exception be raised](https://github.com/napari/napari/blob/ed34af845176adf9183d77b0e21c7a53e1a0f322/napari/plugins/io.py#L91), handled by our ExceptionHandler, and display a useful error message to the user in the GUI.

**Comment by tlambert03** [comment]
if... on the other hand, you're talking about a "broken plugin" scenario in which `napari_get_reader` itself raises an exception, (which, I guess would be the same as your `could_load` function raising an exception), that too is [caught and stored as `PluginCallError`](https://github.com/napari/napari-plugin-engine/blob/480de20160f51d9963eb3d0a8d404eb936c1d365/napari_plugin_engine/callers.py#L197). There too, we have the information and full exception stored and visible in the Plugin Errors window... we just need to go the last mile and alert the GUI-only user with the new notification system

**Comment by Czaki** [comment]
> If the file ended in `.tiff` but required LZW, then `napari_get_reader` would return a reader function (not `None`), that function would fail [here](https://github.com/napari/napari/blob/ed34af845176adf9183d77b0e21c7a53e1a0f322/napari/plugins/io.py#L88) (raising an exception) and then in napari (and here's the implementation detail we all agree needs work) that exception would be [caught in `read_data_with_plugins`](https://github.com/napari/napari/blob/ed34af845176adf9183d77b0e21c7a53e1a0f322/napari/plugins/io.py#L91) and stored as a `PluginCallError` that can later be reviewed in the "Plugins > Plugin Errors..." menu.

No. You write about the current implementation of the builtin reader plugin. It does not mean that all implementation of tiff file reading bahave symilar. There are many scenario when someone would like to create own plugin for read tiff file (like handling metadata). Current specyfication of io-plugin allows for presented behaviour.

I also use tifffile as example because it should be known to most persons in this discussion. 

It was already mentioned that there are plugins that check existence of some files before return reader function. So if some file is missed there will be no information why load fail. 

I do not know how `napari_get_reader` could know why all plugins return None.

**Comment by tlambert03** [comment]
> No. You write about the current implementation of the builtin reader plugin.

erm... are you sure? having written a large part of the plugin system, I'm relatively confident that I'm talking about the implementation of how napari runs third-party plugins (and not the built-in reader plugin). did you follow my links?  I'm definitely open to being proven wrong here, but I'd like to at least feel like you're looking closely at my responses before telling me I'm wrong.

**Comment by Czaki** [comment]
> If the file ended in `.tiff` but required LZW, then `napari_get_reader` would return a reader function (not `None`), that function would fail [here](https://github.com/napari/napari/blob/ed34af845176adf9183d77b0e21c7a53e1a0f322/napari/plugins/io.py#L88) (raising an exception) and then in napari (and here's the implementation detail we all agree needs work) that exception would be [caught in `read_data_with_plugins`](https://github.com/napari/napari/blob/ed34af845176adf9183d77b0e21c7a53e1a0f322/napari/plugins/io.py#L91) and stored as a `PluginCallError` that can later be reviewed in the "Plugins > Plugin Errors..." menu.

Here. 
Or this text is about current one system with autodiscovery plugin. 

I talk about the situation when the user could precisely select which plugin use to load data. Why this is needed. 

Tiff could be loaded:

1. As it is, with axis order the same as in tiff (current default). 
2. Load axes in the deterministic order.
3. Load all data to a single layer.
4. Load data as separate channels 
5. Support som rare metadata format (currently reader does not read metadata of file)

So loading the same file using different plugins may produce different results in the viewer. 
So the problem is not only failure of load file but also use wrong method which produces an unexpected result.

**Comment by tlambert03** [comment]
> Or this text is about current one system with autodiscovery plugin.

yes, I was continuing with [your thought experiment](https://github.com/napari/napari/issues/1790#issuecomment-721719750) of a third-party "`tifffile`" plugin found with autodiscovery.

> So loading the same file using different plugins may produce different results in the viewer.

expected, no?

> So the problem is not only failure of load file but also use wrong method which produces an unexpected result.

Definitely agree we should add some utilities to make it easier for a user who has multiple plugins installed (that all read the same format) to know exactly which plugin "claimed" it (maybe drop a file into the plugin sorter and it will tell you which one claims it?).  Again: the framework is already in place to do so... just need to expose it in the GUI.

**Comment by Czaki** [comment]
But I'm talking about a case when a user selects precisely plugin. And the whole issue I start to better support user selection of plugin which use to load data (different than reorder/disable plugin)

**Comment by tlambert03** [comment]
you know a user can select a precise plugin with `viewer.open('path.ext', plugin='plugin_name')` right?

**Comment by Czaki** [comment]
> you know a user can select a precise plugin with `viewer.open('path.ext', plugin='plugin_name')` right?

And what happens if plugins return `None` instead of a reader?

**Comment by tlambert03** [comment]
if the user requests a specific plugin, and that plugin's `napari_get_reader` returns `None`, then you get an `ValueError`:

```python
v = napari.Viewer()

In [7]: v.open('droso.tif', plugin='dv_reader')
...
ValueError: Plugin 'dv_reader' does not support file droso.tif
```

**Comment by Czaki** [comment]
So plugin creator should avoid almost all checking and move it to reader instance? So why allow other checks than extension?

I think that message should be something like 

`ValueError: Plugin 'dv_reader' does not support file extenison .tif for file droso.tif`

or 

`ValueError: Plugin 'dv_reader' needs droso.data file to read file droso.tif`

and modify hook specifications to allow plugins to return such information.

**Comment by jni** [comment]
@Czaki @tlambert03 I proposed that we could write a new hookspec where that returns either a reader function or a "reason" str. That would be sufficient here, right?

**Comment by tlambert03** [comment]
string would be fine... we could also have them raise an exception... (it's already called in a try catch).  might be more "pythonic"?

**Comment by jni** [comment]
It depends on the reason. Exceptions are for exceptional circumstances. =) Also, exceptions are expensive, and the whole point of returning None was for fast checking, right? So things that fail should fail fast. But now they can tell us why they failed.

**Comment by tlambert03** [comment]
ah... i didn't realize exceptions were expensive.  sure, a string would work.
I'll note though, currently, this string would _only_ be shown to a terminal user who called `viewer.open` with a specific plugin whose `napari_get_reader` didn't return a callable.  I do kinda wonder how often plugin developers are going to return a string other than "this plugin couldn't read this file"... ?

**Comment by jni** [comment]
We can make it an optional string. =) And it's not about "currently", but about what we could engineer around it. e.g. a file->open dialog in which you can select a plugin, select a file, and if you hover over the grayed out "Open" button, it tells you why it's grayed out.

For example? :shrug:

**Comment by tlambert03** [comment]
yep, I get that... I'm totally fine with having it return a string.

**Comment by goanpeca** [comment]
Ok, this issue was longer to read than I hoped to 😆, thanks for pointing to it @tlambert03 👀 

We are looking into this issue https://github.com/napari/product-heuristics-2020/issues/31 with @ppwadhwa and it seems there should be a way to not only get an extension a plugin supports (for IO plugins) but an actual text for it (localization)

>

```python
@napari_hook_implementation(metadata={'extensions': ['.tif', '.tiff']})
def napari_get_reader(path):
    ...
```

This feels a bit clunky, but even if it fixes it, it seems it should me more enforceable, since it is importante information.

Also it should provide tuples so that there is a readable name for formats that make are readable.

```python
{
'extensions': [
            trans._('Specialized image format name with a human readable string'): ["tiff", "tif"],
            trans._('Some other Specialized image format name with a human readable string'): ["foo", "bar"]
   ]
}
```

It feels more natural that the reader that gets returned should provide the information, so any callable that is returned should probably be a "smarter" class that defines the needed extra information and implements the `__call__` and also provides all the additional information. I understand the idea to keep hookspecs as simple as possible, but if we start returning strings or None or a callable or a tuple, then we might ran out of things. It will not scale as plugins need to provide more options or information.

Why isn't the reader that gets returned a class that needs to provides the extra information? Is this what @Czaki was proposing and is this option 1 @tlambert03 proposed? I think option 1 will scale as needed and is easier to enforce since all those methods would need to be defined for it to work. 

```python
class Writer:

    def is_compatible(self):
        return True # or False

    def get_name_filters(self):
        return = [
            trans._('Specialized image format name with a human readable string'): ["tiff", "tif"],
            trans._('Some other Specialized image format name with a human readable string'): ["foo", "bar"]
       ]

    def __call__(path, layer_data):
        """Something something..."""
```

Also I may be understanding things wrong:

>I proposed that we could write a new hookspec where that returns either a reader function or a "reason" str. That would be sufficient here, right?

That feels like it does not scale, as some more things may be needed in the future.

Thoughts @napari/core-devs, @ppwadhwa , @Carreau  ?

**Comment by tlambert03** [comment]
This whole thing feels rather bike-sheddy to me.  I really can't see how it matters _that_ much whether it's a class, or a function that returns a tuple, or a single function along with metadata... in every case we _still_ have to receive what is given to us (via the hook implementation decorator), and validate it.  If it's a class, we have to make sure the appropriate methods are there (since we _don't_ yet want to force them to import napari and inherit from some abc), if it's a tuple of callables, we have to make sure the methods are there, if it's a single function with metadata, we have to make sure the metadata is there ... and on and on ...

This thread got so derailed in comparatively insignificant implementation details, that we didn't end up actually doing anything.  so i'd be grateful at this point for _any_ action.

whether the thing returned is itself callable or not is _also_ not even that critical.  At the end of the day, plugins work like this:

1.  the `napari.plugin` entry point points to a namespace or module that should be inspected for implementations.
2. that namespace is searched for objects decorated with `@hookimplementation` using `iter_implementations` [here](https://github.com/napari/napari-plugin-engine/blob/d31d2aeb822c0ec1143e33747eb8d3422a70974a/napari_plugin_engine/manager.py#L360-L375)
3. each implementation then gets [attached](https://github.com/napari/napari-plugin-engine/blob/d31d2aeb822c0ec1143e33747eb8d3422a70974a/napari_plugin_engine/manager.py#L374) to the `HookCaller` of the corresponding hook specification name.
4. "normally", to actually use the plugin, the hookcaller object itself (e.g. `plugin_manager.hooks.napari_get_writer`) can be called, and it will in turn call each implementation ... (this is why implementations are _usually_ callables).  **but**: this is not a strict requirement... if this scenario requires: we just use the `@hookimpl` decorator to mark some object for discovery, and then register and call it however want to internally (which is not dissimilar to the `napari_provide_x` hookspecs we have like dock widgets and samples).

I know that was a bit of a sideways answer to your questions here... but I'd be more than happy to receive any PR that moves us forward here such that we can simply present a dialog that says "here are the ways you can save the currently selected layers".

**Comment by Czaki** [comment]
> , we have to make sure the methods are there, if it's a single function with metadata, we have to make sure the metadata is there

We could define runtime checkable protocol class. This allow to check if all methods are defined using `isinstance`.

**Comment by tlambert03** [comment]
bikeshed :)

**Comment by goanpeca** [comment]
>This whole thing feels rather bike-sheddy to me. I really can't see how it matters that much whether it's a class, or a function that returns a tuple, or a single function along with metadata... in every case we still have to receive what is given to us (via the hook implementation decorator), and validate it. If it's a class, we have to make sure the appropriate methods are there (since we don't yet want to force them to import napari and inherit from some abc), if it's a tuple of callables, we have to make sure the methods are there, if it's a single function with metadata, we have to make sure the metadata is there ... and on and on ...

This is precisely the issue. Having to support all these different things already defeats the purpose of a "simple" hookspec that returns a "simple" thing.

>we don't yet want to force them to import napari and inherit from some abc)

It seems these classes should live in `napari-plugin-engine` and not `napari`, so I do not understand. All additional validation should live there anyway, no?

>if it's a tuple of callables, we have to make sure the methods are there, if it's a single function with metadata,

Ahhh... 😞  I already have a headache... why provide so many options in return type in the first place?

**Comment by sofroniewn** [comment]
> It seems these classes should live in napari-plugin-engine and not napari, so I do not understand. All additional validation should live there anyway, no?

Right now `napari-plugin-engine` is actually napari agnostic. We could put them there, or more to having another imaging specific interface package - see discussion here https://github.com/napari/napari-plugin-engine/issues/24#issuecomment-825044336

**Comment by goanpeca** [comment]
> is actually napari agnostic. 

Indeed.

Need to think harder about the general problem before I can suggest a path forward. Thanks for all the pointers @tlambert03

**Comment by tlambert03** [comment]
closing this, will be a bit less relevant in npe2, where static metadata is more readily available.  thanks for the discussion!
