### ISSUE TITLE
Welcome screen contrast too low, text is unreadable

### ISSUE THREAD

**Issue by GenevieveBuckley** [napari/napari#1794]
## 🐛 Bug

The napari welcome screen text is extremely low contrast and unreadable.

## To Reproduce

1. Launch napari & look at the welcome screen

It's very bad on Windows, slightly better on Mac (though even there I can't read it easily at all). This isn't readable.

Screenshot from Windows:
![napari-screenshot](https://user-images.githubusercontent.com/30920819/97653015-e6e27100-1ab3-11eb-86f8-daac7a01ab14.png)

Juan's screenshot (https://github.com/napari/napari/pull/1788#issuecomment-717671230):
![napari-welcome-pr](https://user-images.githubusercontent.com/492549/97387014-21c18a80-18a3-11eb-8407-b74220089662.png)

## Expected behavior
I expected contrast sufficient to be able to read the text, without squinting or concentrating on it.

## Environment
napari master branch

**Comment by GenevieveBuckley** [comment]
Previous conversations:
* https://github.com/napari/napari/issues/1787
* https://github.com/napari/napari/pull/1788

**Comment by sofroniewn** [comment]
@GenevieveBuckley agreed - we should fix this. You'll see in the convo we ran into some problems with the mac version in particular, and things are weirdly different for reasons we don't understand between windows and mac, but regardless we should fix

I like the idea of using a contrast checker like this one https://webaim.org/resources/contrastchecker/ to help us make an informed choice here.

When I paste both screenshots above into adobe illustrator and use the color picker I get
- background `[0, 0, 0]`
- text `[31, 36, 40]`

Using these values we fail quite significantly on accessibility
![image](https://user-images.githubusercontent.com/6531703/97656785-8573c100-1a25-11eb-9b7e-cff638b26612.png)

The minimum passable values for large text would be more like `[92, 92, 92]`

![image](https://user-images.githubusercontent.com/6531703/97656928-df748680-1a25-11eb-8c74-d17fe9ad41c4.png)

We can fix this for the next release

**Comment by sofroniewn** [comment]
This was closed by #1863
