### ISSUE TITLE
Layer types needed for 0.1

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#180]
## ❓ Questions and Help

I'm creating this issue to discuss which layer types we think are needed for our MVP (and what are some of their core features that may be missing right now).

Here are some or existing / in-progress / planned layer types:

1. Image layer (merged). This is our core layer supporting visualization of nD arrays. This layer does not support drawing / editing from the GUI. To do: support named axes
2. Markers layer (merged). This layer supports visualization and editing of nD points (could rename to Points). It allows for point addition / deletion and moving. To do: think about coloring individual points / selection mechanism for individual points and making sure there is consistency with the shapes layer
3. Vectors layer (in progress). This layer supports visualization of 2D lines (passed as list of starting / ending coordinates or passed as arrays of line components, could rename Lines). This layer does not support drawing / editing from the GUI. To do: generalize to nD lines and make sure API is consistent with shapes layer.
4. Shapes layer (in progress). This layer supports visualization of and editing of 2D shapes (lines, paths, polygons, rectangles, ellipses). There are no plans to make it nD. To do: basic improvements and make sure API is consistent with Markers and Vectors.
5. Labels layer (early in progress). This layer will support visualization and editing of nD labeled images, where each integer label gets assigned a color (could be random) and the background label (`0` gets assigned to be transparent). To do: get basic static implementation working, then add interactivity - including "paintbrush" style drawing, "fill" style flood fills. "erase". "Merge / split" labels.
6. Big image layer (not started). This layer will support visualization of large nD arrays that are so big they cannot fit in memory. It will take some x-array / dask / zarr / n5 like object that knows where the data is located on disk and then dynamically load data as needed by the vispy pan / zoom system.

Are there other layer types we should be considering? Are there other core features of these layer types that are note mentioned. I havn't included here any discussion of our planned improvements to the `Dims` object (around slicing / max projection etc.) but that will intersect these layer types too.

**Comment by sofroniewn** [comment]
After our discussion today a couple follow up notes:

After vectors / shapes get merged we will look at unifying code under-the-hood and unifying the API (i.e. we might now use triangles to render lines for the vectors layer too)

The big image layer will support both the case of a small 2D view but a long movie (i.e. a 512x512x1e12) timeseries where only the slicing needs to be dynamically loaded - and an enormous 2D image (i.e. 1e12x1e12) that needs the pan-zoom coupling to dynamically load tiles and image pyramids

The shapes layer should support stacks of 2D shapes where each polygon is 2D, but there are different 2D polygons for each z-slice. This can come as a future PR.

We should add a fully nD rectangles layer which behaves as expected

**Comment by jni** [comment]
Brief reminder that the movie would be 1e12x512x512 in NumPy-land.

**Comment by sofroniewn** [comment]
We're making good progress on our core layer types which are all merged - here is an update: 

1. **Image Layer** Now has some support for big datasets loaded using zarr / dask. Need to investigate latencies for remote data (e.g. on s3). Support for browsing collections of irregularly shaped images loaded with `dask-image` is also on the way with #216. Need to make sure big data works for labels layer too.

2. **Pyramid Layer** (not yet merged). Support for image pyramids and tiling is partially implemented in #211. The image pyramids layer does not yet have a "minimap" could investigate adding, but require a second vispy canvas with a linked camera. Need to make sure it works in nD. Need to make sure pyramids works for labels layer too.

3. **Markers Layer** To do: could support each marker having a different color, could allow for editing of individual marker properties in GUI or allow for select / highlight of markers like in shapes layer.

4. **Labels Layer** Now supports paintbrush / fill / colorpicker. To do: allow setting a custom colorlists. Improve colormap as described in #204 (and fix color picking error). Could add a to-polygon option that returns list of polygons to use in a shapes layer.

5. **Shapes Layer** To do: Support a "n.5D" option with different shapes at different "planes". Support tagging shapes with labels / tagging them with full text. Could even then add a “next button / keybinding” that allowed you to click through annotations, if camera position has been recorded with annotation. Add a to svg option and to png option. Merge the to labels / to markers functionality #197.

6. **Vectors Layer** To do: Add support for nD. Add arrowheads option (toggleable). Could make averaging keep the same number of vectors displayed or not as an option.

7. **Box layer** - Not yet implemented. Could support nD boxes (drawing / moving / editing), only axis aligned allowed. Going to wait until 3D viewing is implemented to work on this.

Finally some notes about our base layer - we should do some refactoring to put more of the transforms for getting image coordinates / rescale factor into base layer as they are currently almost identically implemented in each layer type

**Comment by sofroniewn** [comment]
This discussion has been re-branded as layer specific features needed for `0.1`, and includes some of what was discussed above - but out of scope is anything related to `3D` rendering or multiple axes.

For ease of discussion I'm going to close this issue and focus discussion on #61
