### ISSUE TITLE
If a list of length one is passed to add_vectors as length, strange things happen

### ISSUE THREAD

**Issue by brisvag** [napari/napari#1801]
## 🐛 Bug

Passing something like `[1]` as length to `viewer.add_vectors()` leads to random windows opening.

## To Reproduce

```
viewer.add_vectors(np.random.rand(1,2,3), length=[1])
```
we get a reasonable error:
```
TypeError: setValue(self, float): argument 1 has unexpected type 'list'
```
but at the same time, these 2 windows open:
![image](https://user-images.githubusercontent.com/23482191/97780816-36de3800-1b87-11eb-8e02-f5698f126075.png)

Other non-number values give a range of errors that are hard to interpret, making it hard to debug in case something other than a number ended up there. For example:
```
UFuncTypeError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('<U32'), dtype('<U32')) -> dtype('<U32')
```
to an unexperienced user like me would not suggest that `length` was a string.

## Expected behavior

No windows should open. Type checking should give more informative error messages.

## Environment

```
napari: 0.4.0
Platform: Linux-5.9.1-arch1-1-x86_64-with-glibc2.2.5
Python: 3.8.6 (default, Sep 30 2020, 04:00:38) [GCC 10.2.0]
Qt: 5.15.1
PyQt5: 5.15.1
NumPy: 1.19.2
SciPy: 1.5.3
Dask: 2.30.0
VisPy: 0.6.5

GL version: 4.6 (Compatibility Profile) Mesa 20.2.1
MAX_TEXTURE_SIZE: 16384

Plugins:
- napari_plugin_engine: 0.1.8
- svg: 0.1.4
```

**Comment by sofroniewn** [comment]
Thanks for reporting this! Right now length for vectors must be a single scalar, but I could imaging a length D vector makes sense if the vectors are in D dimensions. We should also handle the failure more gracefully!
