### ISSUE TITLE
Viewer screenshot method returns only the first layer.

### ISSUE THREAD

**Issue by mattersoflight** [napari/napari#181]
## 🐛 Bug
When screenshot method is used on a viewer with multiple layers, only the first layer is returned.

## To Reproduce

1. import

%gui qt5 
from napari import ViewerApp
import vispy.io as io

2. Use ViewerApp() and display multiple layers.

3. save screenshot of current view.

screen=viewer2D.screenshot()
io.write_png('vectorexport.png',screen)

![vectorexport](https://user-images.githubusercontent.com/2934183/54791053-84e23a00-4bf5-11e9-9657-6fe25981ef9d.png)

## Expected behavior
Return an RGB image of the current view a numpy array.
![image (2)](https://user-images.githubusercontent.com/2934183/54791008-62502100-4bf5-11e9-8c41-598d438535a1.png)

## Environment

 - napari Version (e.g., 1.0): vector branch, March 20, 2019
 - OS (e.g., Linux): Mac OS Mojave 10.4
 - Python version: 3.7
 - Any other relevant information:

**Comment by sofroniewn** [comment]
I had a quick poke around this one, and it seems like the ordering and opacities are wrong and improving the situation for the screenshot makes the situation for the main display worse. I think this may relate to the issue @kne42 identified in #22 but I am unable to see how to fix it and the things I tried did not work
