### ISSUE TITLE
Qt plugin dialog inconsistency

### ISSUE THREAD

**Issue by Czaki** [napari/napari#1819]
## 🐛 Bug

New plugin dialog (from #1357) provides inconsistency when reporting plugin which contains multiple hooks. As on the screenshot, my program adds multiple plugins. Each is reported as separate entry on list. Each contains a remove button which uninstall not only this one but will remove all plugins from this package. I think that the interface should have grupping entry from one package with only one "remove" button on top. 

![Zrzut ekranu z 2020-11-02 12-58-29](https://user-images.githubusercontent.com/3826210/97865874-3078c900-1d0b-11eb-8470-4a3b7e36464c.png)

Also when using a freezed environment (Pyinstaller) there hown two additional problem:

![Zrzut ekranu z 2020-11-02 13-19-12](https://user-images.githubusercontent.com/3826210/97867394-168cb580-1d0e-11eb-971f-89bdfddebc91.png)

There is no list of installed plugins even when theyt are active (small problem). 

There is no check of avaliablity of pip in current envronment (there are other cases wheter `pip` could be missed in active envronment) which may produce multiple problems and hard to understand issue reports. 

There also happens duplication of entries after use update package. 
![Zrzut ekranu z 2020-11-02 13-29-22](https://user-images.githubusercontent.com/3826210/97868132-76379080-1d0f-11eb-8959-58ad761d526e.png)

## To Reproduce

1. iunstall PartSeg in napari environment
2. open plugin dialog
3.

## Environment

 - Please copy and paste the information at napari info option in help menubar here:

 - Any other relevant information:

## Additional context

Sorry for dellay of this check. I should do this before merge of PR. 

Few qustions. 
Is there plan to discover plugins whichj are not starting from `napari-` (ex. using trove clasifier?) Or I should provide dummy package `napari-partseg` to allow installation from dialog? 

@tlambert03

**Comment by tlambert03** [comment]
Yeah; I left it showing multiple plugins from a single package intentionally, but would not be opposed to a PR that change that if you're interested. 

We don't support installing plugins in a pyinstaller frozen environment (plugin installation was the whole reason we went with briefcase).  Best I would offer there is probably just to provide a message saying as much.

Yes trove classifier discovery should be added (currently it would only find 3 plugins, so I wouldn't switch to it exclusively at this point).  But it already looks for plugins that don't start with napari (see ome-zarr-py as an example)

**Comment by Czaki** [comment]
> Yeah; I left it showing multiple plugins from a single package intentionally, but would not be opposed to a PR that change that if you're interested.

Ok

> We don't support installing plugins in a pyinstaller frozen environment (plugin installation was the whole reason we went with briefcase). Best I would offer there is probably just to provide a message saying as much.

I know this, but currently, I cannot switch to briefcase because of bugs. For me, the only thing to be done is the disable install button (plugins are still visible in Show Sorter) when there is no pip available in the environment. 

> Yes trove classifier discovery should be added (currently it would only find 3 plugins, so I wouldn't switch to it exclusively at this point). But it already looks for plugins that don't start with napari (see ome-zarr-py as an example)

Ok. I see that I need to add napari and plugin to the readme. Now PartSeg is visible.
