### ISSUE TITLE
renaming EmitterGroup

### ISSUE THREAD

**Issue by bryantChhun** [napari/napari#182]
## ❓ layers._base_layer._visual_wrapper has an EmitterGroup defined, but it's assigned to "self.events".  Can we rename it something appropriate like "self.emitters"?

Please correct me if i'm wrong, but I thought the EmitterGroup defines objects that emit events, not the events themselves.  Renaming as above would clarify which objects are sending and which are receiving.

**Comment by sofroniewn** [comment]
@kne42 and I had been talking about some of this recently - in some places in the code base `self.changed` was used for something similar I think. Good to highlight for when are doing the refactoring. Thanks!

**Comment by bryantChhun** [comment]
ok well, i dug a little deeper.  If we were consistent with Vispy's documentation, they explicitly say

"EmitterGroup instances are usually stored as an 'events' attribute on objects that use multiple emitters."

https://github.com/vispy/vispy/blob/master/vispy/util/event.py
