### ISSUE TITLE
add_points does not apply requested opacity

### ISSUE THREAD

**Issue by nicost** [napari/napari#1822]
## 🐛 Buglet

When programmatically adding points to the viewer object, the requested opacity sets the position of the opacity slider, but not the opacity of the layer in the viewer.

## To Reproduce

```
from skimage import data
import napari

viewer = napari.view_image(data.astronaut(), rgb=True)
points = np.array([[100, 100], [200, 200], [300, 100]])
viewer.add_points(points, size=30, opacity=0.5)
```
Note that the opacity slider is set to 0.5 (expected) but the opacity in the display is 1.0.  Touching the slider sets it correctly.

## Environment

napari: 0.4.0
Platform: Windows-10-10.0.18362-SP0
Python: 3.7.9 (default, Aug 31 2020, 17:10:11) [MSC v.1916 64 bit (AMD64)]
Qt: 5.15.1
PyQt5: 5.15.1
NumPy: 1.19.2
SciPy: 1.5.2
Dask: 2.30.0
VisPy: 0.6.5

GL version: 4.6.0 - Build 26.20.100.8142
MAX_TEXTURE_SIZE: 16384

Plugins:
- napari_plugin_engine: 0.1.8
- svg: 0.1.4

**Comment by sofroniewn** [comment]
Sorry about this @nicost! I'm able to reproduce this. I think it's a regression from some of our recent changes.

There's a missing `self._reset_base()` call here https://github.com/napari/napari/blob/v0.4.0/napari/_vispy/vispy_points_layer.py#L31

See equivalent line in `vispy_vectors_layer.py` https://github.com/napari/napari/blob/v0.4.0/napari/_vispy/vispy_vectors_layer.py#L13-L14

Should be a one line fix. We can add a simple test too without too much difficulty too. We should check if there are other places where this is missing too. It doesn't look like it though.

**Comment by nicost** [comment]
No worries!  Suspected that it was a straight forward issue.  And thanks!  Really like the workflow with napari now that I have things set up.

**Comment by nicost** [comment]
Just discovered the same phenotype with add_image and gamma:
`viewer = napari.view_image(data.astronaut(), rgb=True, gamma=0.2))`
Let me know if you'd prefer this in a separate issue.

**Comment by sofroniewn** [comment]
Nice, I'm ok with keeping it all in here, I worry there might be one or two more even!

**Comment by sofroniewn** [comment]
The points opacity bug has now been fixed, but I think the gamma bug is proving more challenging. @kevinyamauchi was looking in. We might need to now make a new issue for that and then close this one

**Comment by kevinyamauchi** [comment]
I agree that we should make a new issue for the gamma bug. I will do so and close this one.
