### ISSUE TITLE
Tracks layer is not displayed on Windows 10

### ISSUE THREAD

**Issue by amichaut** [napari/napari#1825]
## 🐛 Bug

The tracks layer is not displayed on Windows 10. A RuntimeError is returned: 
`RuntimeError: Freetype library not found`

## To Reproduce

1. Run tracks_3d.py from the example directory

The  `RuntimeError: Freetype library not found` is returned
and no tracks are displayed, only the points layer is displayed.

## Expected behavior

I have run the same code on MacOS Mojave and had the expected behavior [from the tutorial](https://napari.org/tutorials/fundamentals/tracks) 

## Environment

napari: 0.4.0
Platform: Windows-10-10.0.18362-SP0
Python: 3.8.3 (default, May 19 2020, 06:50:17) [MSC v.1916 64 bit (AMD64)]
Qt: 5.14.2
PyQt5: 5.14.2
NumPy: 1.19.1
SciPy: 1.5.0
Dask: 2.30.0
VisPy: 0.6.5

GL version: 4.5.0 NVIDIA 353.62
MAX_TEXTURE_SIZE: 16384

Plugins:
- napari_plugin_engine: 0.1.8
- svg: 0.1.4

**Comment by sofroniewn** [comment]
Hi @amichaut, sorry you're running into this problem. It looks like a duplicate of the freetype issues mentioned here https://forum.image.sc/t/error-freetype-library-not-found-during-adding-points/41742/7?u=sofroniewn from @berl also noted in #1766 for the bundled app.

It sounds like there are a couple of manual steps that can be done to overcome this, but maybe @ziyangczi can take a deeper look at this and add some troubleshooting steps to our installation guide https://napari.org/tutorials/fundamentals/installation

(it also looks @ziyangczi like some of the windows specific visual studio instructions added in #1758 might need to be added to that doc as well which is in our tutorials repo https://github.com/napari/tutorials/blob/master/fundamentals/installation.md)

**Comment by amichaut** [comment]
Thanks! Yes I had seen this issue too but no easy bug fix was given, so I was hoping there was something specific to the tracks layer that could be solved here.

**Comment by liu-ziyang** [comment]
fwiw I have been trying on my machine (fresh windows installation) for past few days, tracks layer have been working for me, so I am working on getting more data samples from more machines, would be great if you have any additional information on the environment, particularly if there is any warning on this missing dll during installation etc, and can you also verify freetype-py ver 2.2.0 is in your python virtual environment?

**Comment by liu-ziyang** [comment]
I am semi convinced that vc++ is required to run on windows, you can get the distribute instead of the full VisualStudio: https://aka.ms/vs/16/release/VC_redist.x64.exe, can you please reinstall 0.4.0 bundled app after installing the vc tool and see if the problem persists?

**Comment by berl** [comment]
@ziyangczi  well on Machine 1 I'm still getting errors on the 0.3.8, the 0.4.0 bundled install  ...  and the redistributable VC install! so let's disregard that one for now
on Machine 2, I was able to install the 0.4.0 bundle and successfully ran the code from tracks_3d.py by copy-pasting it into the napari console

**Comment by liu-ziyang** [comment]
sounds good! I am going to close this issue for now, there is a similar discussion in #1766 as well

If anyone have the same issue and cannot run tracks layer on 0.4.0 after installing VC++, or have more related context feel free to reopen the issue
