### ISSUE TITLE
Setting transforms on existing layer not pure

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#1826]
## 🐛 Bug

I'm not sure if this is by design, or a bug... but setting `layer.shear` with a full shear matrix is impure: calling it with the same value repeatedly gives you different results.

## To Reproduce

```python
import napari
import numpy as np

viewer = napari.Viewer()
layer = viewer.add_image(np.random.rand(64,64,64))

mat = np.eye(3)
mat[2,0] = 0.5
layer.shear = mat
layer.shear  # array([-0. ,  0.4,  0. ])
layer.shear = mat
layer.shear  # array([-0.        ,  0.27586207,  0.        ])
layer.shear = mat
layer.shear  # array([-0.        ,  0.21253985,  0.        ])
```

yes, warnings are provided when I set those, but it's not clear from the warnings (until you look at the source code for the shear setter showing the decomposition and recomposition of the full matrix) why setting shear with the same value yields a different result.

```ipytb
UserWarning: Non upper diagonal shear matrix passed so reseting rotate to the identity.
UserWarning: Non-orthogonal slicing is being requested, but is not fully supported. Data is displayed without applying an out-of-slice rotation or shear component.
```

## Expected behavior

setting a layer attribute should not depend on previous state.  If the intention was to _apply_ shear to whatever the current matrix is, then I would have expected it to be a method (like `apply_shear`) rather setting an attribute `layer.shear = ...`

**Comment by sofroniewn** [comment]
> I'm not sure if this is by design, or a bug... but setting layer.shear with a full shear matrix is impure: calling it with the same value repeatedly gives you different results.

Yeah, agreed we should fix. Maybe rather than emit "UserWarning: Non upper diagonal shear matrix passed so reseting rotate to the identity." I should have just thrown an error but I didn't actually realize it would be this bad with that example (I would have thought it would be stable, but you'd loose any additional rotation information each time), so maybe more is going wrong that I thought.

The issue is that our shear decomposition always goes to an upper triangular matrix, but you're passing in a full shear matrix that is lower triangular, so something's got to give, but it should be stable.

**Comment by tlambert03** [comment]
> I should have just thrown an error but I didn't actually realize it would be this bad with that example ... The issue is that our shear decomposition always goes to an upper triangular matrix, but you're passing in a full shear matrix that is lower triangular

fwiw, I noticed this first with `shear_matrix_from_angle` ... since that also creates a lower triangular matrix.  so setting `layer.shear = shear_matrix_from_angle(31)` has the same outcome

**Comment by sofroniewn** [comment]
Just did some more looking into this, one fix would be to add `scale = np.ones(len(scale))` here https://github.com/napari/napari/blob/master/napari/utils/transforms/transforms.py#L378-L383

This would then fix the above issue and setting shear would be stateless. We could do this as a quick fix for 
`layer.shear = shear_matrix_from_angle(31)` but there's a deeper issue that our reduced representation is upper triangular and so we're not really able to have a nice round trip with a lower triangular input :-( Very curious what you'd recommend here, I'd love to see this fixed

**Comment by sofroniewn** [comment]
If user passes a full matrix to shear we should detect if lower triangular/ upper triangular and decompose as appropriate. This would prevent the above bug. We can keep track of this and return the decomposition as appropriate.

We should also add a `homogeneous` keyword to `shear_matrix_from_angle`.

Thanks @jni and @tlambert03 for help figuring this out!!!!
