### ISSUE TITLE
Affine matrix composition order 

### ISSUE THREAD

**Issue by zeroth** [napari/napari#1841]
## 🐛 Bug

As per my understanding affine matrix composition order [here](https://github.com/napari/napari/blob/master/napari/utils/transforms/transform_utils.py#L95) should be `full_rotate @ full_shear @full_scale`
here are few links to confirming my theory 
 https://people.cs.clemson.edu/~dhouse/courses/401/notes/affines-matrices.pdf and this https://gamedev.stackexchange.com/questions/29260/transform-matrix-multiplication-order

## To Reproduce
download two LLSM sample files from [here](https://drive.google.com/drive/folders/1MwpgwzLBYI7L2Q4880CKUETcjgjBE0Pb?usp=sharing) `test2.tif` is non-deskewed file and `test2_deskew.tif` is a deskewed version of the `test2.tif`, Add these two images to napari and apply affine transform on a non-deskewed image so that both overlaps.
something like 
```
import numpy as np
import napari
from napari.utils.transforms import Affine, shear_matrix_from_angle
import tifffile

angle = 31.8
dx = 0.104 # um
dz = 0.4 # step size um


shear = shear_matrix_from_angle(31.8)
scale = [np.sin(np.deg2rad(angle))* dz, dx, dx]


with napari.gui_qt():
    viewer = napari.Viewer(ndisplay=3)

    image2_deskew = tifffile.imread("./test2_deskew.tif")
    image2 = tifffile.imread("./test2.tif")
    viewer.add_image(image2, name='shear 2', colormap='bop orange', 
                         scale=scale, shear=shear, blending="additive") 
    viewer.add_image(image2_deskew, name='deskewed 2', colormap='bop purple', 
                    scale=scale, blending="additive")
```

we can also verify the above bug by constructing the affine matrix from scratch something like
```
angle = 31.8
dx = 0.104 # um
dz = 0.4 # step size um

shear = np.array([[ 1.,  0., 0.,  0.],
                [ 0.,  1.,  0.,  0.],
                [ np.tan(np.deg2rad(90-angle)),  0,  1.,  0.],
                [ 0.,  0.,  0.,  1.]])

scale = np.array([[ np.sin(np.deg2rad(angle))* dz,  0., 0.,  0.],
                [ 0.,  dx,  0.,  0.],
                [ 0.,  0,  dx,  0.],
                [ 0.,  0.,  0.,  1.]])


with napari.gui_qt():
    viewer = napari.Viewer(ndisplay=3)

    image2_deskew = tifffile.imread("./test2_deskew.tif")
    image2 = tifffile.imread("./test2.tif")

    affine = shear @ scale
    viewer.add_image(image2, name='shear 2', colormap='bop orange', 
                         affine=affine, blending="additive") 
    viewer.add_image(image2_deskew, name='deskewed 2', colormap='bop purple', 
                    scale=[np.sin(np.deg2rad(angle))* dz, dx, dx], blending="additive")
```

output looks like
![failed](https://user-images.githubusercontent.com/17413/98301837-88ffdd00-200f-11eb-86be-83ce3f9995a0.png)

## Expected behavior
I am expecting 
![success](https://user-images.githubusercontent.com/17413/98301864-95843580-200f-11eb-9ed1-1355645a4c59.png)

## Environment

napari: 0.4.1.dev15+gbc3298b
Platform: Windows-10-10.0.19041-SP0
Python: 3.8.1 (default, Mar 2 2020, 13:06:26) [MSC v.1916 64 bit (AMD64)]
Qt: 5.12.9
PySide2: 5.13.2
NumPy: 1.18.1
SciPy: 1.5.3
Dask: 2.30.0
VisPy: 0.6.5

GL version: 4.6.0 NVIDIA 457.09
MAX_TEXTURE_SIZE: 32768

Plugins:
- napari_plugin_engine: 0.1.8
- svg: 0.1.4

**Comment by sofroniewn** [comment]
> As per my understanding affine matrix composition order here should be `full_rotate @ full_shear @full_scale`

Hmm, I see the recommendation is to scale first and then shear/ rotate whereas we're doing `full_rotate @ full_scale @full_shear` right now, which is a little odd.

I guess scaling first does make sense as otherwise you'd have non-uniform scaling. Curious if @tlambert03 has thoughts or a recommendation here?

I'd be happy to change the composition order, but then we also need to change something in our decomposition code as those always need to match each other. I'll take a look now. Thanks for raising.
