### ISSUE TITLE
Removing and re-adding layer objects to the viewer list raises qt runtime errors

### ISSUE THREAD

**Issue by brisvag** [napari/napari#1850]
## 🐛 Bug

It appears that removing layers from the viewer layer list deletes a few associated qt widgets, but appending them does not re-create the missing widgets. Instead, a `RuntimeError` is raised.

## To Reproduce

```
import napari
v = napari.Viewer()
l = v.add_points([0,0])
v.layers[0].remove(l)
v.layers[0].append(l)
```
This will raise `RuntimeError`s about missing `QLabel`s.
The layers are still added "correctly", but if interacted with from the viewer (such as making them visible/invisibile, dragndropping them...) they raise additional errors about missing qt objects.

## Expected behavior

Re-adding layers should be seamlessly recreating missing qt objects.

## Environment

```
napari: 0.4.0
Platform: Linux-5.9.4-arch1-1-x86_64-with-glibc2.2.5
Python: 3.8.6 (default, Sep 30 2020, 04:00:38) [GCC 10.2.0]
Qt: 5.14.2
PyQt5: 5.14.2
NumPy: 1.19.4
SciPy: 1.5.4
Dask: 2.30.0
VisPy: 0.6.5

GL version: 4.6.0 NVIDIA 455.38
MAX_TEXTURE_SIZE: 16384

Plugins:
- mrcfile-reader: 0.1.2
- napari_plugin_engine: 0.1.8
- svg: 0.1.4
```

**Comment by sofroniewn** [comment]
Thanks for raising this, I want to link to #1846 which is related. If you did `viewer.add_layer` it might be better, but we do need to fix this. We should probably wait until after #1504 has merged and then do a fix
