### ISSUE TITLE
GUI package installer shows each package twice after installation

### ISSUE THREAD

**Issue by DragaDoncila** [napari/napari#1852]
## 🐛 Bug

The installed packages list in the GUI displays each installed plugin twice, including the built in SVG.

![image](https://user-images.githubusercontent.com/17995243/98755453-b20fdb80-241c-11eb-9b21-006e18e44028.png)

Removing one of the plugins removes both instances from the list.

## To Reproduce

1. Install latest version of napari from master
2. Install some plugins, whether through GUI or command line (behaviour is the same)
3. Click Plugins>Install/Uninstall Package(s)...

## Expected behavior

Each plugin only shows up once when installed.

## Environment

 ```
napari: 0.4.1a1
Platform: Windows-10-10.0.18362-SP0
Python: 3.8.5 (default, Sep 3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]
Qt: 5.15.1
PySide2: 5.15.1
NumPy: 1.19.4
SciPy: 1.5.4
Dask: 2.30.0
VisPy: 0.6.5

GL version: 4.6.0 - Build 26.20.100.7870
MAX_TEXTURE_SIZE: 16384

Plugins:
- napari_plugin_engine: 0.1.8
- nd2-reader: 0.0.3
- svg: 0.1.4
- tracks: 0.0.1
```

 - I've reproduced this in three fresh conda environments on Windows

**Comment by Czaki** [comment]
Also reported in #1819.

**Comment by tlambert03** [comment]
@Czaki, was yours also on windows?  I’ve never seen this before...

**Comment by Czaki** [comment]
I have this on linux. I could verify its today (but later)

**Comment by sofroniewn** [comment]
I don't see this on my mac either.

<img width="1192" alt="Screen Shot 2020-11-16 at 9 10 22 AM" src="https://user-images.githubusercontent.com/6531703/99284844-9e34f280-27eb-11eb-8735-215615793078.png">

Not sure @tlambert03 if you have any ideas about what's going wrong here, but it might be nice to fix before the `0.4.1` release if possible (which will be first release with #1357 in). I'm hoping we can make a release candidate by the end of this week and then make an actual release early next week.

**Comment by Czaki** [comment]
I also cannot reproduce it now on ubuntu.

**Comment by tlambert03** [comment]
was able to repeat on windows (only).  I found a quick fix in napari_plugin_engine... but want to figure out why it's happening on windows
