### ISSUE TITLE
"point property changed" event

### ISSUE THREAD

**Issue by brisvag** [napari/napari#1888]
## 🚀 Feature
Currently, changing the `properties` of a point layer does not trigger any layer event. It would be nice if it triggered either a `layer.events.data` signal or a specific property signal.

## Motivation

I'm currently working with a system that keeps data in a backend, and provides it to napari depending on how I want to display it. I want to be able to apply changes in napari, and automatically run some calculations on the data in my backend based on what was changed. Currently, I can do this with `Points.data` changes, but not with `Points.properties`.

## Pitch
```py
pl = Points([0,0], properties={'a': [1]})
pl.properties = {'a': 2}
# or
pl.properties['a'] = [2]
# `Points.events.data`, `Points.events.properties` or something else is fired
```

The second case probably requires to set up a special `dict` subclass... Which may be useful for other purposes anyways, since currently
```py
pl.properties = {'a': [1,2,3,4,5]}
```
complains with:
```py
ValueError: the number of properties must equal the number of points
```
while
```py
pl.properties['a'] = [1,2,3,4,5]
```
does not.

**Comment by kevinyamauchi** [comment]
Thanks, @brisvag ! As I mentioned in [the zulip thread](https://napari.zulipchat.com/#narrow/stream/212875-general/topic/layer.20events.20on.20data.20changes), I am open to adding a properties event. In short, we would have to add a `properties` event [here](https://github.com/napari/napari/blob/794b14f06eb502197eba4f0dc07085f40c069b99/napari/layers/points/points.py#L292-L304) and then call it at the end of the properties setter [here](https://github.com/napari/napari/blob/794b14f06eb502197eba4f0dc07085f40c069b99/napari/layers/points/points.py#L596-L618).

We would probably want to do this for all layers with properties (e.g., Shapes, Vectors).

As you mentioned, catching when the user directly modifies the properties dictionary would require a custom class or some other magic. Given that, my first instinct is to hold off on that. Of course, I am open to discussing it if there is a strong nee!

**Comment by sofroniewn** [comment]
> The second case probably requires to set up a special dict subclass... Which may be useful for other purposes anyways, since currently

This would be analogous to our EventedList class #1444. Not sure we want to do that right away, but an interesting idea

**Comment by kevinyamauchi** [comment]
> This would be analogous to our EventedList class #1444. Not sure we want to do that right away, but an interesting idea

I agree.

I could make a quick PR to add the properties event to the relevant layers. I wouldn't hook it up to anything inside of napari, but I can see how it would be useful for folks developing things around napari. Perhaps we could sneak it into forthcoming the `0.4.1` release. Thoughts @sofroniewn ?

**Comment by sofroniewn** [comment]
> I could make a quick PR to add the properties event to the relevant layers. I wouldn't hook it up to anything inside of napari, but I can see how it would be useful for folks developing things around napari. Perhaps we could sneak it into forthcoming the 0.4.1 release. Thoughts @sofroniewn ?

Yeah that's fine, go for it. I'm happy to review/ merge. Something we want to do eventually.

**Comment by sofroniewn** [comment]
I'm going to close this now that #1896 has merged. We can open up a new issue for evented dicts if we want to go down that path in the future. Thanks all!!
