### ISSUE TITLE
Transform a Shapes layer into a Label layer

### ISSUE THREAD

**Issue by kevinyamauchi** [napari/napari#189]
## 🚀 Feature
It would be nice to have a function to turn the shapes from a `Shapes` layer into a `Labels` layer.

## Motivation
The `Shapes` layer is a great tool for annotating data and users will likely want to be able to generate a labels mask from the shapes.

## Pitch
We could add a `Shapes.rasterize()` method that returns a `Labels` layer. In a simple implementation, we could make all shapes in a given layer returned as the same class. We could also have each shape color as a different class.

**Comment by sofroniewn** [comment]
This has been in #197
