### ISSUE TITLE
Using observer pattern to update rendering

### ISSUE THREAD

**Issue by AhmetCanSolak** [napari/napari#19]
We are needed to provide a way to automatically update the rendering in case of a change in the data array we have load. To provide a smooth experience, we could(and probably should) use observer pattern listener to keep container/viewer notified about possible changes.

In the link below you can find a simple demonstration of this pattern, which we can adapt later to our layer and viewer classes in the project.
https://gist.github.com/AhmetCanSolak/6340d5d74e5152468b68f6ae895e3bc5

**Comment by kne42** [comment]
this doesn't work so well in the event of a mutation

ie `im.data[0] = 42` would not trigger a notification

**Comment by AhmetCanSolak** [comment]
yes, it is not working well with mutation, but it is python huh, that's why we should test accordingly.

**Comment by sofroniewn** [comment]
This has been closed by #155 and #158, where we now use our own copy of the vispy event system
