### ISSUE TITLE
Add "painting" to Labels layers

### ISSUE THREAD

**Issue by kevinyamauchi** [napari/napari#190]
## 🚀 Feature
There should be a mode to label pixels in the Label layer by dragging the mouse over the image (i.e., "painting").

## Motivation
This feature is a useful way to do pixel-wise annotation of images.

## Pitch
We can have a toggle-able mode that catches mouse events and adds the appropriate label to `Labels._image()`.

A nice-to-have: it would be nice to have support for drawing with Wacom tablets (e.g.,[QTabletEvent](https://doc.qt.io/qt-5/qtabletevent.html))

**Comment by donovanr** [comment]
This would be super useful to me. Additionally, it would be great to be able to convert a polygon annotation to a painted/rastered version/layer – that might be its own issue/feature though.

**Comment by jni** [comment]
@donovanr 

> that might be its own issue/feature though

it literally is! #197 =D

**Comment by sofroniewn** [comment]
This has been addressed with #195 and #197. Support for tablets is being addressed in #166
