### ISSUE TITLE
Painting error on linux 

### ISSUE THREAD

**Issue by Czaki** [napari/napari#1903]
## 🐛 Bug

When drawing I sometimes got this error (which ends program with SIGSEGV): 

```
WARNING: Error drawing visual <Image at 0x7f589a273be0>
13:02:05 WARNING Error drawing visual <Image at 0x7f589a273be0>
13:02:05 ERROR Unhandled exception:
Traceback (most recent call last):
  File "/home/czaki/.pyenv/versions/napari/lib/python3.8/site-packages/vispy/app/backends/_qt.py", line 825, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "/home/czaki/.pyenv/versions/napari/lib/python3.8/site-packages/vispy/util/event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "/home/czaki/.pyenv/versions/napari/lib/python3.8/site-packages/vispy/util/event.py", line 473, in _invoke_callback
    _handle_exception(self.ignore_callback_errors,
  File "/home/czaki/.pyenv/versions/napari/lib/python3.8/site-packages/vispy/util/event.py", line 471, in _invoke_callback
    cb(event)
  File "/home/czaki/.pyenv/versions/napari/lib/python3.8/site-packages/vispy/scene/canvas.py", line 217, in on_draw
    self._draw_scene()
  File "/home/czaki/.pyenv/versions/napari/lib/python3.8/site-packages/vispy/scene/canvas.py", line 266, in _draw_scene
    self.draw_visual(self.scene)
  File "/home/czaki/.pyenv/versions/napari/lib/python3.8/site-packages/vispy/scene/canvas.py", line 304, in draw_visual
    node.draw()
  File "/home/czaki/.pyenv/versions/napari/lib/python3.8/site-packages/vispy/scene/visuals.py", line 99, in draw
    self._visual_superclass.draw(self)
  File "/home/czaki/.pyenv/versions/napari/lib/python3.8/site-packages/vispy/visuals/visual.py", line 442, in draw
    self._program.draw(self._vshare.draw_mode,
  File "/home/czaki/.pyenv/versions/napari/lib/python3.8/site-packages/vispy/visuals/shaders/program.py", line 101, in draw
    Program.draw(self, *args, **kwargs)
  File "/home/czaki/.pyenv/versions/napari/lib/python3.8/site-packages/vispy/gloo/program.py", line 533, in draw
    canvas.context.flush_commands()
  File "/home/czaki/.pyenv/versions/napari/lib/python3.8/site-packages/vispy/gloo/context.py", line 176, in flush_commands
    self.glir.flush(self.shared.parser)
  File "/home/czaki/.pyenv/versions/napari/lib/python3.8/site-packages/vispy/gloo/glir.py", line 572, in flush
    self._shared.flush(parser)
  File "/home/czaki/.pyenv/versions/napari/lib/python3.8/site-packages/vispy/gloo/glir.py", line 494, in flush
    parser.parse(self._filter(self.clear(), parser))
  File "/home/czaki/.pyenv/versions/napari/lib/python3.8/site-packages/vispy/gloo/glir.py", line 819, in parse
    self._parse(command)
  File "/home/czaki/.pyenv/versions/napari/lib/python3.8/site-packages/vispy/gloo/glir.py", line 787, in _parse
    ob.set_data(*args)
  File "/home/czaki/.pyenv/versions/napari/lib/python3.8/site-packages/vispy/gloo/glir.py", line 929, in set_data
    raise RuntimeError("Shader compilation error in %s:\n%s" %
RuntimeError: Shader compilation error in GL_VERTEX_SHADER:
```

## To Reproduce

1. load image 
2. add label layer
2. try paint
3. repeat 

## Expected behavior
Not end with 
```
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
```

## Environment

napari: 0.4.1rc1
Platform: Linux-5.4.0-53-generic-x86_64-with-glibc2.2.5
Python: 3.8.3 (default, Jun 26 2020, 19:57:39) [GCC 9.3.0]
Qt: 5.15.1
PyQt5: 5.15.1
NumPy: 1.19.0
SciPy: 1.5.1
Dask: 2.1.0
VisPy: 0.6.5

GL version: 4.6.0 NVIDIA 390.138
MAX_TEXTURE_SIZE: 32768

Plugins:
- napari_plugin_engine: 0.1.8
- ome_zarr: 0.0.14
- svg: 0.1.4

 - Please copy and paste the information at napari info option in help menubar here:

 - Any other relevant information:

## Additional context

Any suggestion for debug?

**Comment by sofroniewn** [comment]
Uh oh! Is this new? I assume it didn't used to happen? Do we know if it is related to any of our recent changes like the welcome visual, the axes visual or the scale bar? I wonder if you comment those out / disable them entirely if you still get crashes? I've found the text node in particular can lead to crashes

**Comment by sofroniewn** [comment]
I don't see this on my mac. I wonder if you see this with PySide2? We've had a bunch of PyQty5 specific crash reports lately

**Comment by Czaki** [comment]
I do not remember this earlier. I got sometimes crash, but not such deterministic. 
I cannot reproduce this on PySide2. 

I could reproduce this on PyQt5.14.2 and 5.15.1. 

On the other hand, I remember some fuckups with signal and PySide. Both wrappers have their problems.

**Comment by sofroniewn** [comment]
> I do not remember this earlier. I got sometimes crash, but not such deterministic.

Hmm, this isn't great.

If you comment out this line and don't add the additional visuals do you still get crashes https://github.com/napari/napari/blob/master/napari/_qt/qt_viewer.py#L207?

```python
        # Add axes, scale bar and welcome visuals.
        #self._add_visuals(welcome)
```

**Comment by Czaki** [comment]
No crash after comment, 
Also when code change to `self._add_visuals(False)` there is no crash

**Comment by sofroniewn** [comment]
> Also when code change to self._add_visuals(False) there is no crash

Ok wow, so it really is that welcome visual! I'm pretty confident then that it is caused by https://github.com/napari/napari/blob/master/napari/_vispy/vispy_welcome_visual.py#L35-L37
i.e. if you dropped the `TextNode` then everything would be fine (I saw that in what is likely a related crash).

This has been causing a lot of crashes for people. I think it would be good to figure out why, as it doesn't seem like we're doing anything that strange here, but if we needed to think of alternatives we could (like using native Qt and not vispy to show the welcome visual)

**Comment by Czaki** [comment]
>  i.e. if you dropped the `TextNode` then everything would be fine (I saw that in what is likely a related crash).

Many places to comment out but I could confirm. 
This is strange because I have already loaded the image, so welcome visuals should not be visible. 

If it causes crashes maybe should be disabled for this release to find what is done wrong?

**Comment by sofroniewn** [comment]
> If it causes crashes maybe should be disabled for this release to find what is done wrong?

Maybe

Does `method='cpu'` help for you in the `Text` constructor? It didn't for me, but I'm curious none the less

**Comment by Czaki** [comment]
> Does `method='cpu'` help for you in the `Text` constructor? It didn't for me, but I'm curious none the less

No

Did You already meet `RuntimeError: Program validation error:` when switching onto 3d view? Or I should open the second issue?

**Comment by sofroniewn** [comment]
> Did You already meet RuntimeError: Program validation error: when switching onto 3d view? Or I should open the second issue?

Nope, does it also get fixed by disabling welcome visual? If yes fine to leave here, if no then new issue is best

**Comment by Czaki** [comment]
> > Did You already meet RuntimeError: Program validation error: when switching onto 3d view? Or I should open the second issue?
> 
> Nope, does it also get fixed by disabling welcome visual? If yes fine to leave here, if no then new issue is best

Unfortunately no.  see #1905

**Comment by sofroniewn** [comment]
> Unfortunately no. see #1905

:-(

**Comment by andy-sweet** [comment]
@Czaki : if you close https://github.com/napari/napari/issues/1905 , maybe this should be closed too? Looking through the comments here, it's a little unclear how connected these are. I think it would be OK to leave this open, though I'm not sure what immediate action we could take.

**Comment by Czaki** [comment]
I need to review last CI fails.

**Comment by psobolewskiPhD** [comment]
@Czaki Do you still get this issue with latest labels changes and more recent pyqt5? Does anyone else on Linux see this?

**Comment by Czaki** [comment]
Since this time, we have rewritten shader codes a few times, so I think this may be closed.
