### ISSUE TITLE
Feature request: Rotation button on napari viewer

### ISSUE THREAD

**Issue by adamltyson** [napari/napari#1929]
Apologies if this has been discussed before, but I couldn't find it...

## 🚀 Feature
A rotation button in the napari viewer along with roll dimensions etc

## Motivation
We acquire a lot of data with samples that are rotated compared to convention (just so they fit next to each other and take up less room in an automated microscope). napari is excellent for viewing this raw data, but multiple users have asked me if they can rotate the data into the "standard" neuroanatomical orientation. 

This is easy to do with a script, but there doesn't seem to be a way to do simple in-plane 90 degree rotations from the GUI (other than transpose which isn't always the correct rotation).

## Pitch

An extra button in the bottom left to rotate the image view by 90 degrees. 

## Alternatives

Writing a custom qt widget with this functionality, but that sort of defeats the point of being able to drag and drop into napari with plugins.

**Comment by sofroniewn** [comment]
> A rotation button in the napari viewer along with roll dimensions etc

Makes sense to me!

**Comment by psobolewskiPhD** [comment]
Image Layers can be rotated using the `transform` mode (keybind `2`), but there isn't an easy way to get exactly 90 degrees yet. A button would make it easier, but maybe it could be right-click on the Transpose button?

**Comment by jni** [comment]
The usual affordance here is holding shift to snap to 45, 90, 135 etc degrees of rotation...

**Comment by psobolewskiPhD** [comment]
Yeah, that's should be added to the layer transform mode. 
But still being able to have just rotate Right rotate Left somewhere -- button or menu whatever -- would be a usability boon.
