### ISSUE TITLE
Labels layer controls text cut off

### ISSUE THREAD

**Issue by kevinyamauchi** [napari/napari#1934]
## 🐛 Bug
When I run the nD_labels.py example on master on my computer, the text labels for the labels layer checkboxes are cut off. I believe this is due to the fixed width of the layer controls widget.

![cutoff_labels](https://user-images.githubusercontent.com/1120672/100061879-00ff3d00-2e2f-11eb-925c-a18cd3dd88bc.png)

https://github.com/napari/napari/blob/c3667ff5fbe21d98e5985144d6501cc5954ce615/napari/_qt/qt_viewer.py#L313-L324

## To Reproduce

1. Open the `/examples/nD_labels.py` example

## Expected behavior

Text in the labels layer controls should all be fully visible

## Environment
```
napari: 0.3.9.dev27+g52cc6cd.d20201006
Platform: Linux-5.4.0-53-generic-x86_64-with-debian-bullseye-sid
Python: 3.7.7 (default, May 7 2020, 21:25:33) [GCC 7.3.0]
Qt: 5.14.2
PyQt5: 5.14.2
NumPy: 1.19.1
SciPy: 1.5.2
Dask: 2.24.0
VisPy: 0.6.4

GL version: 4.6.0 NVIDIA 450.66
MAX_TEXTURE_SIZE: 32768

Plugins:
- napari_plugin_engine: 0.1.7
- svg: 0.1.4
```

**Comment by Czaki** [comment]
Resolution? Some screen scaling set?

**Comment by liaprins-czi** [comment]
Related: #2470 and #2337 

@kevinyamauchi Is this issue still happening for you? If so, what operating system (your screenshot looks very much if not identical to the issue in #2337 for Linux specifically). If this is still an issue that can't be solved by enginerring, I will cosnider it as a UI bug and work on a more flexible design solution!

**Comment by kevinyamauchi** [comment]
Hello @liaprins-czi ! I am sorry, I forgot to close this when we merged https://github.com/napari/napari/pull/3046. This issue is fixed when I test on my computer.

<img width="1059" alt="Screenshot 2021-09-01 at 10 28 45" src="https://user-images.githubusercontent.com/1120672/131638794-ed2be8b7-c790-4789-9993-19456b59eab8.png">


```
napari: 0.4.11rc3
Platform: macOS-10.15.7-x86_64-i386-64bit
System: MacOS 10.15.7
Python: 3.8.11 (default, Aug 6 2021, 08:56:27) [Clang 10.0.0 ]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.21.2
SciPy: 1.7.1
Dask: 2021.08.1
VisPy: 0.7.0

OpenGL:
- GL version: 2.1 INTEL-14.7.17
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1440x900, scale 2.0

Plugins:
- console: 0.0.4
- scikit-image: 0.4.11rc3
- svg: 0.1.5
```

**Comment by kevinyamauchi** [comment]
I will close this issue for now. Please feel free to re-open if we haven't fixed it on your system.
