### ISSUE TITLE
SSL configuration error for docs

### ISSUE THREAD

**Issue by neuromusic** [napari/napari#1947]
Got a security warning from Chrome when trying to access napari.org

Appears to be an SSL configuration problem.

![Screenshot_20201126-091348](https://user-images.githubusercontent.com/1245615/100373380-ee6c3b80-2fc7-11eb-85e1-119e0ccf4bf5.png)

**Comment by sofroniewn** [comment]
That's no good! Definitely something that needs to be fixed asap. I havn't seen that before.

**Comment by Czaki** [comment]
@neuromusic Could you provide more details (device, system version, browser)?

**Comment by adamltyson** [comment]
I see the same thing on Firefox & Chrome on Ubuntu 18.04.

**Comment by Czaki** [comment]
**napari.org** shows proper certificate, 
but **www.napari.org** return GitHub certificate. And this is the reason for this bug. 

So there should be redirection from www.napari.org or created a separate certificate for www.napari.org and serve it.

(sorry for Polish description of fields, this is my system language)

![Zrzut ekranu z 2020-11-27 12-42-33](https://user-images.githubusercontent.com/3826210/100445913-2b126280-30ae-11eb-99f1-e20f7b8d0e1c.png)

**Comment by Czaki** [comment]
Looks like someone fix the configuration. Could anyone else check?

**Comment by adamltyson** [comment]
Yep, fine for me now.

**Comment by sofroniewn** [comment]
That's great, thanks all for the help debugging. I'm curious did @jni or someone else on our end fix or was it a fix on the GitHub end?

**Comment by sofroniewn** [comment]
I didn't change anything

**Comment by sofroniewn** [comment]
Closing as fixed, but would be good to understand how it got fixed at some point!!
