### ISSUE TITLE
Adding points on heavily-scaled data slices them on the wrong plane

### ISSUE THREAD

**Issue by jni** [napari/napari#1967]
## 🐛 Bug

```python
import napari
from skimage import data

image = data.binary_blobs(128, n_dim=3)[:60]

with napari.gui_qt():
    v = napari.view_image(image, scale=[0.29, 0.26, 0.26])
    pts = v.add_points(name='interactive', size=1, ndim=3)
    pts.mode = 'add'
    v.dims.set_point(0, 30 * 0.29)  # middle plane
```

Clicking on points adds them on the right plane, but they are not shown. One must slice several planes lower to see them. When you switch to 3D mode, they appear in the middle plane correctly.

**Comment by sofroniewn** [comment]
That doesn't sound good. I'll check this out later, but curious if the following would behave better

```python
from skimage import data

image = data.binary_blobs(128, n_dim=3)[:60]

with napari.gui_qt():
    v = napari.view_image(image, scale=[0.29, 0.26, 0.26])
    pts = v.add_points(name='interactive', size=1, ndim=3, scale=[0.29, 0.26, 0.26])
    pts.mode = 'add'
    v.dims.set_point(0, 30 * 0.29)  # middle plane
```

**Comment by brisvag** [comment]
I have a similar poblem with non-rescaled data, but I never got around to test or make an issue. If you have a 3D points layer only and add points to some 2D slice, sometimes after adding 2 or 3 points they stop appearing. However, switching to 3D reveals that they were added correctly. I could not tell when or why this happened.

**Comment by ziyangczi** [comment]
I did observe that after explicitly setting the scale in add_points, the behavior is corrected. So my naive approach would be having the viewer to manage the scale of all layers consistently, I am not sure what side effect this can bring though

**Comment by liu-ziyang** [comment]
I think I found the issue: the discrepancy happens when we compressing, in this particular example (0.29, 0.26. 0.26), the data is sliced at 9 while indices are sliced at 8 for plane 30, and data is sliced at 8 for plane 26, 27, 28, and 29, hence the mismatch.

code related: https://github.com/napari/napari/blob/1d784cf8373495d9591594b6dd6ac479d5566ed1/napari/layers/base/base.py#L628-L629

I am looking into

**Comment by liu-ziyang** [comment]
one potential partial solution: https://github.com/napari/napari/blob/1d784cf8373495d9591594b6dd6ac479d5566ed1/napari/layers/points/points.py#L1523-L1525

Change the assignment to also use np round: `data = np.round(self.data[:, not_disp]).astype('int')`
This would make sure that the points are displayed when they should be displayed, however, this does not address the issue where points are displayed when they are not supposed to (coordinates compressed to match multiple planes)
