### ISSUE TITLE
"undo"

### ISSUE THREAD

**Issue by gregjohnso** [napari/napari#199]
## 🚀 Feature
Add "undo" feature

## Motivation

Sometimes I add a marker and can't figure out how to delete it. Or deleted a layer on accident 

## Pitch

Press the "undo" button or "ctrl+z" and the viewer is set to the previous state.

**Comment by sofroniewn** [comment]
Yup, we're planning to implement some form of history feature. i feel like i may know the answer already, but curious how important to you is it to have arbitrarily many "undos" vs just being able to do one?

And any thoughts on how we should think about "undos" once we get to a stage where plugins can do some pretty intense analysis that either generates large copies of data or takes a long time.

I could imagine that for some simple things like shape editing / drawing markers we could support many undos, but for loading / deleting / manipulating images we might have to have a cap

**Comment by sofroniewn** [comment]
This has been partially addressed with the merge of #533 where we add an undo / redo button to the labels layer. We have a plan for a more comprehensive undo / redo system laid out in #474 so I am closing this issue in favor of that one.
