### ISSUE TITLE
Layer's events / signals  are not getting emitted properly.

### ISSUE THREAD

**Issue by zeroth** [napari/napari#1996]
## 🐛 Bug

I had a code which was using magicgui to manipulate the layers in napari.  Using magicgui, it was showing a ComboBox with all The available layers, and it used to get updated as soon as there are new layers.
I was using the connection `viewer.layers.events.changed.connect(lambda x: gui.refresh_choices())` to update the ComboBox with new layers.

After updating napari to version 0.4.2, this connection is not working. 

## To Reproduce

Steps to reproduce the behaviour:

1. create a new conda env `conda create -n nptest042 python=3.8
2. install NumPy `conda install numpy==1.16.*` (this is because latest NumPy has some bug)
3. install napari  `pip install napari[PySide2]`
4. install magicgui `pip install magicgui.`
5. run this magicgui example https://github.com/napari/magicgui/blob/master/examples/napari_image_arithmetic.py
6. add any new layer Shape, or open a new image in the running example.

## Expected behaviour

One should see new layers being related in the ComboBoxes.

## Environment

napari: 0.4.2
Platform: Windows-10-10.0.19041-SP0
Python: 3.8.6 | packaged by conda-forge | (default, Nov 27 2020, 18:58:29) [MSC v.1916 64 bit (AMD64)]
Qt: 5.15.2
PySide2: 5.15.2
NumPy: 1.16.5
SciPy: 1.5.4
Dask: 2.30.0
VisPy: 0.6.6

GL version: 4.6.0 NVIDIA 457.09
MAX_TEXTURE_SIZE: 32768

Plugins:
- napari_plugin_engine: 0.1.8
- svg: 0.1.4

## Additional context

I tested this with older version 0.4.0 everything works. 
In the new version, I notice the event system has changed.

**Comment by sofroniewn** [comment]
Yes, sorry the layer events changed when we started using the evented list and we must have missed a deprecation warning here. Try just `viewer.layers.events.connect(lambda x: gui.refresh_choices())` instead, dropping the `changed`

**Comment by zeroth** [comment]
Oh, I didn't know that thanks. I guess the documentation is still on 0.4.0.

**Comment by jni** [comment]
Yeah to get the latest documentation use https://napari.org/docs/dev/. Unfortunately new versions are not getting added right now, see https://github.com/napari/docs/issues/1

I'll close this issue, @zeroth please reopen if you encounter any issues with @sofroniewn's recommendation.
