### ISSUE TITLE
Implement min/max/gamma filtration

### ISSUE THREAD

**Issue by kne42** [napari/napari#2]
- [x] Add basic double-slider for existing min and max adjustment (clim) to the GUI

- [x] Add support for CPU-based gamma adjustment

- [ ] Implement min,max, and gamma in the shader as an optimised option (bool flag)

**Comment by sofroniewn** [comment]
Basic clims was implemented in #82 and #85

**Comment by sofroniewn** [comment]
This has been largely implemented by #610. There is still stuff we could do to push some of the gamma calculation to the graphics card, but things are pretty good now, so I am closing this issue
