### ISSUE TITLE
Allow for users to define keys or actions to execute user-defined functions

### ISSUE THREAD

**Issue by gregjohnso** [napari/napari#200]
## 🚀 Feature
Allow for users to define keys or actions to execute user-defined functions

## Motivation

I want to be able to "pipeline" my image processing tasks without having to click around. If I can define a dictionary of key commands and corresponding functions, I could do some neat stuff.

## Pitch

Add an argument to add key bindings that execute an arbitrary function. Something like this:

```
viewer = ViewerApp()


def good_image():
    print('this is a good image')
    next()
    
def bad_image():
   print('this is a bad image')
   next()

def next():
    #pop off the zeroth layer and replace it with a new one
    viewer.layers.pop(viewer.layers[0].name)

    blobs = np.stack(data.binary_blobs(length=128, blob_size_fraction=0.1, n_dim=2), axis=-1)
    viewer.add_image(blobs.astype(float))

def exit():
    #serialize the viewer data to disk, and close the viewer
    pickle.dump( viewer.data, open( "save.p", "wb" ) )
    viewer.exit() 

my_key_bindings = {'a':good_image, 'z':bad_image, 'x':exit}

viewer.add_image(blobs.astype(float))
viewer.set_key_bindings(my_key_bindings)
```

Then when I press the 'a' button, "this is a good image" prints to console and a new image appears, etc. When I press 'x' the data serializes to disk and closes the app.

**Comment by jni** [comment]
Yes! The auto-advance stuff is so powerful, I once did a "find the ROI in each image" little app like this and it was insanely fast to work with. We definitely want to be able to support this with napari.

**Comment by sofroniewn** [comment]
This has been supported with #232
