### ISSUE TITLE
Add text in title bar

### ISSUE THREAD

**Issue by gregjohnso** [napari/napari#201]
## 🚀 Feature
Add function to set title-bar text. 

## Motivation

Sometimes I forget what I'm doing, and need to be reminded. 

## Pitch

```viewer.add_title('click all the cells')```

## Additional context

![Screen Shot 2019-04-03 at 4 44 25 PM](https://user-images.githubusercontent.com/17319655/55520186-fb3c5e80-562f-11e9-9964-9f9a5c454389.png)

**Comment by sofroniewn** [comment]
This feature has been added with #237
