### ISSUE TITLE
Running Napari within a docker container: libGL error

### ISSUE THREAD

**Issue by gletreut** [napari/napari#2014]
## 🐛 Bug

Hello,

I am experiencing an issue when trying to run napari from within a ubuntu docker image on Mac OS. I have checked a related [issue](https://github.com/napari/napari/issues/1457), which I was able to fix by adding the additional packages `libxcb-*` and `libxkbcommon-*` to the [Dockerfile](https://github.com/napari/napari/blob/master/dockerfile) available in this repository.

However, when running Napari from the container, after Napari launches I obtain a blank window and cannot therefore access to the UI. The error obtained is:
```
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
```

Any idea on how to solve this issue?

I am attaching a `Dockerfile` and a `docker-compose.yml` to reproduce the behavior.

## To Reproduce

1. Configure XQuartz on Mac OS [[link](https://sourabhbajaj.com/blog/2017/02/07/gui-applications-docker-mac/)].
2. `cd test/`
3. `docker-compose build`
4. `xterm`
5. `docker-compose up`

## Environment
I provided a `test` folder containing the following files:
```
.
├── Dockerfile
└── docker-compose.yml
```
[test.zip](https://github.com/napari/napari/files/5691508/test.zip)

**Comment by sofroniewn** [comment]
Thanks for reporting this. @ziyangczi can you take a look at this. Thanks!!

**Comment by liu-ziyang** [comment]
I believe you have to mount the graphical driver into the container for the libGL to pick up, however this would be tricky to do since the container is built on a ubuntu environment but you would have a macOS as host. You may need to install the ubuntu driver during the installation while mount the graphical card resource into the container.

I found similar issues when I started the docker work, I found that having to manage different host * graphical driver options quite exhausting to manage, I have yet to find a universal solution that would work outside of ubuntu host yet

**Comment by liu-ziyang** [comment]
Not sure if this helps, but napari does offer a bundled app alternative if you want to skip the installation process: https://github.com/napari/napari/releases/download/v0.4.2/napari-0.4.2-macOS.zip

**Comment by liu-ziyang** [comment]
more thoughts on this: the graphs driver is required because of one dependency: vispy (which renders our main canvas) in turn depends heavily on openGL: https://github.com/vispy/vispy/issues/1344.

A valuable workaround solution unfortunately only works for nvidia cards..: https://github.com/NVIDIA/nvidia-docker which allows running docker in a special mode which renders inside container

**Comment by gletreut** [comment]
Thanks for looking into this.

Regarding the docker solution, do you have a working example (Dockerfile maybe?) to check this out? I don't have a dedicated graphic card on the machine I want to use with Napari (laptop), so the NVIDIA-docker alternative would not work for me.

Thank you for the bundled app alternative. Maybe I am missing something, but would you mind giving some steps for a working example? The GUI doesn't contain much, and I cannot open any file (see screenshot attached). For instance, since napari wasn't installed as a Python package, how would you run [this example](https://napari.org)?

![Screen Shot 2020-12-15 at 11 15 21 AM](https://user-images.githubusercontent.com/26467466/102261929-3bf10f80-3ec7-11eb-96e1-23771207e5cd.png)

In the end I am simply trying to find a a way to run napari on Mac OS Big Sur, since I haven't found a working solution to the [OpenGL issue](https://github.com/napari/napari/issues/1393).

**Comment by liu-ziyang** [comment]
Hi there, I am not sure if we support big sur for any installation yet 😢,  I have not yet tried it myself and would consult others on the compatibility issue there. 

Regarding running the example in the bundled app: after the bundled app launches, you can open the built in console to execute python code, for example you can then import skimage, and do viewer.add_image(), etc.

I am going to try get my hands on some big sur machine and try that, let me get back to you a bit later on this

**Comment by liu-ziyang** [comment]
bad news: I tried napari on the big sur, and I can confirm that the bundled app is *NOT* working as intended, the 0.4.2 release works normally on Catalina but not on the big sur as of writing. The symptom is the same as the screen reported above.

**Comment by jni** [comment]
Thanks for testing @ziyangczi! I mean I totally expected this based on the thread above, but it's "good" to have confirmation.

**Comment by gletreut** [comment]
Thanks for confirming the issue, that's unfortunate 😢

**Comment by tlambert03** [comment]
> bad news: I tried napari on the big sur, and I can confirm that the bundled app is NOT working as intended, the 0.4.2 release works normally on Catalina but not on the big sur as of writing. The symptom is the same as the screen reported above.

the bundle won't work on Big Sur until it ships with python 3.9.0 ... see #1393

**Comment by jaimergp** [comment]
Following :)

**Comment by liu-ziyang** [comment]
> Following :)

I updated the docker images a while back, I wonder if people have more success using the images currently available on docker hub?

**Comment by jaimergp** [comment]
I've been experimenting a bit with different headless options, and will soon submit a PR gathering all the possibilities, depending on the configuration of the host. For now, suffice to say that I FINALLY found out how to get the astronaut to show up on a browser tab served from a Docker image!

![image](https://user-images.githubusercontent.com/2559438/173633335-17b6e734-d6c2-4cda-a00a-d0e173f2e935.png)


The solution is [Xpra](https://xpra.org/). I don't know why [this specific configuration](https://hub.docker.com/r/tswetnam/xpra) works on my machine but [`x11vnc`+`novnc`](https://github.com/gitpod-io/workspace-images/blob/main/legacy/full-vnc/Dockerfile) doesn't (GUI does show up, but the OpenGL parts are black with x11vnc in my setup).

Anyway, I'll keep you posted in the subsequent PRs.
