### ISSUE TITLE
>2000 shapes in Shapes layer degrades performance

### ISSUE THREAD

**Issue by ahnsws** [napari/napari#2015]
## 🐛 Bug

Adding more than a few thousand polygons causes the UI to become sluggish, and the more polygons, the slower the UI gets. The use case for this is to view the nucleus segmentation results of a whole pathology slide, which may contain more than a million nuclei.

## To Reproduce

Code to view some circles:

```python
import napari
import numpy as np

np.random.seed(0)

n_points = 20
radius = 10
n_circles = 1500  # adjust this
span = 1000

angles = np.linspace(0, 2 * np.pi, n_points, endpoint=False)
deltas = radius * np.stack([np.cos(angles), np.sin(angles)])
centers = np.random.randint(0, span, size=(n_circles, 2))
circles = centers[..., np.newaxis] + deltas[np.newaxis, ...]

with napari.gui_qt():
    viewer = napari.Viewer()
    viewer.add_shapes(
        [circles[i, ...].T for i in range(n_circles)],
        shape_type="polygon",
        edge_width=2,
        edge_color="coral",
        face_color="royalblue",
    )

```

## Expected behavior

Ability to view more polygons. This sounds like it can be done, but I'm just not sure where to start looking. Being able to do this would be incredible, since we could apply colormaps to this layer to visualize patterns across an entire specimen.

## Environment

```
napari: 0.4.2
Platform: Windows-10-10.0.19041-SP0
Python: 3.8.6 | packaged by conda-forge | (default, Nov 27 2020, 18:58:29) [MSC v.1916 64 bit (AMD64)]
Qt: 5.12.9
PySide2: 5.13.2
NumPy: 1.19.3
SciPy: 1.5.3
Dask: 2.30.0
VisPy: 0.6.6

GL version: 4.6.0 NVIDIA 452.57
MAX_TEXTURE_SIZE: 32768

Plugins:
- napari_plugin_engine: 0.1.8
- svg: 0.1.4
```

**Comment by sofroniewn** [comment]
Thanks for this feedback

> Ability to view more polygons. This sounds like it can be done, but I'm just not sure where to start looking. Being able to do this would be incredible, since we could apply colormaps to this layer to visualize patterns across an entire specimen.

One question - do you just need to view the polygons and is that slow? Or do you also want to be able to draw them, edit them in the GUI?

Right now we don't have any concept of "multiscale" for our shapes layer, but in the context of whole slide pathology images this may be essential for us to add. There has been limited discussion of this here #1019 and #1639

**Comment by ahnsws** [comment]
We would just like to view the results, and that step does get slow above a few thousand polygons. For our use case, we don't need to draw/edit them at that scale, but maybe others might, e.g. for ML-assisted labeling, or for labeling many unusual cell shapes. For some context, these polygons are the direct output from [stardist](https://github.com/mpicbg-csbd/stardist).

The only things we would edit are polygons but in a separate layer containing at most a few dozen polygons, which is already supported well.

**Comment by psobolewskiPhD** [comment]
@wooahn I've updated your snippet from the OP:
```
import napari
import numpy as np
np.random.seed(0)
n_points = 20
radius = 10
n_circles = 5000  # adjust this
span = 1000

angles = np.linspace(0, 2 * np.pi, n_points, endpoint=False)
deltas = radius * np.stack([np.cos(angles), np.sin(angles)])
centers = np.random.randint(0, span, size=(n_circles, 2))
circles = centers[..., np.newaxis] + deltas[np.newaxis, ...]

viewer = napari.Viewer()
viewer.add_shapes(
                [circles[i, ...].T for i in range(n_circles)],
                shape_type="polygon",
                edge_width=2,
                edge_color="coral",
                face_color="royalblue",
)
```
With n_circles = 5000 and 15000—the later takes a bit to launch—I don't see any issues with the UI responsiveness. Just that making the layer takes a bit of time (~40s for 15k circles). With 15k circles selecting a specific one is tricky, but seems responsive and fine to me.
Perhaps this has been solved by https://github.com/napari/napari/pull/3867 ?

**Comment by psobolewskiPhD** [comment]
I tested this again because @Czaki has done more work with Shapes performance.
Making a 50K shapes layer with the script above is pretty fast, 20s maybe? less than a minute for sure -- and that's with launching the viewer, etc.
Pan, zoom both super smooth, moving a shape is a bit sluggish?
Going to close. There may be Shapes performance issues, but they are not this issue.
🎉
