### ISSUE TITLE
Allow text coloring and add edge to text

### ISSUE THREAD

**Issue by giovp** [napari/napari#2019]
## 🚀 Feature
- [ ] Ability to pass color array to text (to color each text label differently)
- [ ] Ability to set an edge (color and thickness) to text

## Motivation

We'd like to plot text color according to some values. Also, and edge around the text would be useful

## Pitch

We are working toward interfacing anndata https://github.com/theislab/anndata with napari for sptial transcriptomics data, and would like to get text visualized like this (color correspond to cluster coloring):
![image](https://user-images.githubusercontent.com/25887487/102333535-db78d580-3f8d-11eb-86d6-2764c4634295.png)

## Alternatives
For now, it only uses the first color of the array, if an array is passed to text:
```python
_text_color
# array([[0.        , 0.        , 0.        ],
#       [0.        , 0.        , 0.        ],
#       [0.        , 0.        , 0.        ],
#       ...,
#       [0.        , 0.        , 0.        ],
#       [0.15294118, 0.61960784, 0.40784314],
#       [0.        , 0.        , 0.        ]])
text = {
	"text": "{clusters}",
	"size": 24,
	"color": _text_color,  
	"anchor": "center",
	"blending": "translucent",
}
```
![image](https://user-images.githubusercontent.com/25887487/102335086-be450680-3f8f-11eb-911d-6e57a003c2d1.png)

## Additional context

There is a quick fix wrt coloring (see PR) but would be happy to have inputs on whether it would be possible to also have an edge for the text

pinging @michalk8 with whom we are working on this.

Thank you!

**Comment by kevinyamauchi** [comment]
Thank you for making this issue and for the PR, @giovp ! I think these are both interesting features. I have put some thoughts below and I am curious what others think.

Also, thank you for the screen shots - they look super cool. I look forward to seeing what you're building.

### coloring text elements independently
I think this is a good idea and something I definitely think we should add.  Thank you for the PR! I think it is a step in the right direction. I understand it was intended as a quick patch, but to make it complete, we would have to add some code to manage the colors for text that is added after the layer is initialized (e.g,. a user adds a point/shape through the GUI). As is, when a user adds a point, a corresponding color value isn't added to `TextManager.color`. Also, I think we would ideally bring the coloring behavior in line with the other annotations and allows colors to be mapped to layer property values.

I am currently working on a `ColorManager` class that can be added to data classes (e.g., layers and `TextManager`) to control color setting/getting (see #1940 ). Once `ColorManager` is completed, I think it should be relatively straightforward to integrate  it into `TextManager` to give allow text to be colored independently (and settable by properties).  I think I should complete the `ColorManager` PR this week and hopefully we can merge soon after (review will likely be slower than usual - it's a big PR and the holidays).

In the meantime, I think you can use the pattern below, but given the screenshot above, I suspect you have already discovered it. Please note this is a bit of a hack and not an officially supported behavior at this time. Also, it doesn't add text colors properly when adding next data to the layer. Does this unblock you for now? If not, I am happy to discuss if there's a way we can get a patch in that meets your needs and has good behavior for other use cases as well.

```python
points_layer = viewer.add_points(data, properties=props, text=text)

# this avoids the code in __init__ and the setter that removes the other elements of the array
points_layer ._text._color = color_array

# i think you need to call the color event to force the layer to redraw
points_layer._text.events.color()
```

### adding a border to text
I think this is also a nice idea. We use the [vispy `TextVisual`](https://vispy.org/visuals.html#vispy.visuals.TextVisual) to render the text. Unfortunately, they do not currently support text borders. Eventually, it could be cool to see about contributing something to add text outlines back up to vispy. Short of that, there may be some things we can do to get part of the way there.

Are you interested in text outlines to improve the visibility of the text? If so, maybe one of these ideas could potentially be useful (I haven't tried any of them - just brainstorming):

- Add two text elements in the same location with different sizes  (the bigger one behind to act as the border). This would require two separate layers and I am not sure if the fonts scale in a way that would make this work. _edit: I just tried this and the font scaling makes it a mess_ 🤦 
- Put the text annotations in a `Shapes` or `Points` layer and anchor the text to the center of the shape/marker. You could then use the shape/marker as a "background" for the text that provides contrast. You can set the `anchor = 'center'` to center the text on the shape/marker (see [the tutorial](https://napari.org/tutorials/applications/annotate_segmentation)). My recollection is the size of the text will stay a fixed size as you zoom in/out, so this may cause weird behavior.

Thanks again and I am looking forward to hearing your thoughts.

**Comment by giovp** [comment]
Hi @kevinyamauchi !
Thanks a lot for the prompt reply and the very detailed explanation! 
I figured indeed that the issue was wrt to new points being added (we don't really use that feature for these layers as we set `layer.editable = False`).

I'll reply more extensively in #2020 but we'd be totally fine wrt to waiting for #1940 being merged and use `ColorManager`.
Thank you again.

**Comment by kevinyamauchi** [comment]
Hey @giovp ! 

> Thanks a lot for the prompt reply and the very detailed explanation!

No problem!

> we'd be totally fine wrt to waiting for #1940 being merged and use ColorManager.
Thank you again.

Sounds good!
