### ISSUE TITLE
styling

### ISSUE THREAD

**Issue by freeman-lab** [napari/napari#202]
## ❓ Questions and Help

During an in-person sprint I did some design mock work on potential refresh to the UI / UX.

### Phase 1

First is a proposed new design that captures current functionality. It's only a proposal for aesthetic changes (hopefully improvements!)

<img width="633" alt="Screen Shot 2019-04-03 at 5 27 14 PM" src="https://user-images.githubusercontent.com/3387500/55521481-c0d5c000-5635-11e9-9ef1-cc393fde1c92.png">

Broad intentions were to darken the UI (because most images are dark and look better on a dark background) and keep it clean and minimal and inviting.

If people like it, we could get implementing pretty quickly!

### Phase 2

Second is a mock for how we could incorporate some future-looking functionality that the team has discussed at various times.

<img width="841" alt="Screen Shot 2019-04-03 at 5 27 19 PM" src="https://user-images.githubusercontent.com/3387500/55521487-c501dd80-5635-11e9-98fc-291a2fdbf9c0.png">

In particular, this captures
- the future addition of a console running the Python kernel in the bottom
- the future addition of plugins as drawers on the right
- a *proposed* movement of object specific parameters (e.g. line width, color) to a drawer on the left ("Inspector"), suggested by @kevinyamauchi 's desire to have those properties closer to the drawing tools and @jni 's experience using and liking a similar UI in keynote

The above is likely to inspire discussion on the underlying feature additions, which is probably best left to other issues / PRs, but comments welcome here too, especially on how the UI would expose them.

**Comment by kevinyamauchi** [comment]
This is awesome! In particular, I like the darker UI and the rectangular slider bars. I'd say go for phase 1!

Minor nitpick: I think the font should be the same for the left and right sides of the message bar at the bottom of the viewer.

While on the topic of fonts, can we include our own font or do we have to choose something safe that will be on all platforms?

In terms of phase 2, I think it would be pretty great if the "+" tab under the plugin drawers expanded to a list of the registered plugins with a search bar on top.

**Comment by jni** [comment]
> I think it would be pretty great if the "+" tab under the plugin drawers expanded to a list of the registered plugins with a search bar on top.

GENIUS! 👏 

My comments:

- phase 1:
 * I'd keep the eye icon for "visible", as stylised as necessary but I think it is more intuitive (if less stylish) than a bare tick box. (and hidden should have a crossed-out eye)
 * still fishing for ideas for the bottom-left corner! My proposal: 2d/3d switcher, or sliders mode switch (display/slice/project), or similar. 

- phase 2:
 * regarding the console, again, it would be great if we could "attach" to the current IPython kernel. I don't know how easy or hard this is but I bet there's people in the bay area who know very well. =P But the idea would be that if you launch Napari from IPython, you have access to the full history with up-arrow here. ie we simply embed an IPython console attached to the same kernel that launched Napari. In scripts etc this might be more complicated, dunno. But maybe we can say that this is for interactive mode only.
 * we need some space for the [variable explorer](https://docs.spyder-ide.org/variableexplorer.html), though personally I don't mind if it's floating.

**Comment by sofroniewn** [comment]
I really like the direction - I'd say we press on with phase 1 and think about phase 2 as we go and add new features.

One thing mentioned by @d-v-b was the request for an intensity histogram. people have remarked that it could be on the left oriented vertically and aligned with the clims slider in a `QSplitter` so that it is possible to pull in / out

**Comment by sofroniewn** [comment]
Phase 1) of our stylings improvement has been merged in #236

**Comment by jni** [comment]
Following the discussion in https://github.com/napari/napari/pull/236#issuecomment-488040626

@freeman-lab if you look at range slider implementations "in the wild", they almost all have some form of separation between the handles and the range (search for "range slider" on Google images). In the rare exceptions that I could find, the handles are much bigger than the thickness of the interval, so they still stand out as separate objects.

**Comment by jni** [comment]
> For margins, I spent a fair bit of time playing with it, hear your concerns, but have some justifications :) Right margin is slightly bigger to give space for the scroll bar, left and right have more space than I'd like visually to give room for the splitter handles, and then top is set to match the others. In fact, with left and right panels collapsed, the spacing is equal and pretty minimal on all sides. I'd say, if/when we get rid of the splitters, we revisit tightening the margins up?

It's a pretty massive space for a scrollbar by modern standards! By way of comparison, text editing boxes on the web (such as the one I am seeing right now) are just a few pixels wide and then expand temporarily upon mouse hover.

I agree that the space in the margins should match the splitter spacing, but the splitter spacing is way too big right now. Again, splitters only need to be a few pixels wide (as found on i3wm ;).

**Comment by sofroniewn** [comment]
Phase 1 of stylings has been implemented with #236 and a couple follow-up PRs like #324 which completes our styling needs for `0.1`. I'm leaving this issue open because it contain an interesting example and discussion around phase 2 - which could meet our styling needs for the full blown app

**Comment by sofroniewn** [comment]
with the merging of #536 and the design audit discussion in #469 i'm closing this issue
