### ISSUE TITLE
Windows bundled app doesn't start up

### ISSUE THREAD

**Issue by haesleinhuepf** [napari/napari#2022]
## 🐛 Bug

Hi all,

I just downloaded napari-0.4.2=Windows.zip and installed it. It doesn't start from the Windows start menu. This issue is related to [this one](https://developercommunity.visualstudio.com/content/problem/1207405/fmod-after-an-update-to-windows-2004-is-causing-a.html) (thanks to @jni for providing this link) and could be resolved by using `numpy==1.19.3` [see also](https://github.com/clEsperanto/pyclesperanto_prototype/issues/36) and the workaround on the very bottom of this github issue.

## To Reproduce

1. Download and install [napari-0.4.2-Windows.zip](https://github.com/napari/napari/releases/download/v0.4.2/napari-0.4.2-Windows.zip)
2. Enter your username in this line and execute it:
```
C:\Users\<username>\AppData\Local\Programs\napari\python\python.exe -m napari
```

Result
```
C:\Users\rober>C:\Users\rober\AppData\Local\Programs\napari\python\python.exe -m napari
 ** On entry to DGEBAL parameter number  3 had an illegal value
 ** On entry to DGEHRD  parameter number  2 had an illegal value
 ** On entry to DORGHR DORGQR parameter number  2 had an illegal value
 ** On entry to DHSEQR parameter number  4 had an illegal value
 ** On entry to DGEBAL parameter number  3 had an illegal value
 ** On entry to DGEHRD  parameter number  2 had an illegal value
 ** On entry to DORGHR DORGQR parameter number  2 had an illegal value
 ** On entry to DHSEQR parameter number  4 had an illegal value
Traceback (most recent call last):
  File "runpy.py", line 185, in _run_module_as_main
  File "runpy.py", line 144, in _get_module_details
  File "runpy.py", line 111, in _get_module_details
  File "C:\Users\rober\AppData\Local\Programs\napari\\app\napari\__init__.py", line 48, in <module>
    from vispy import app
  File "C:\Users\rober\AppData\Local\Programs\napari\\app_packages\vispy\__init__.py", line 30, in <module>
    from .util import config, set_log_level, keys, sys_info  # noqa
  File "C:\Users\rober\AppData\Local\Programs\napari\\app_packages\vispy\util\__init__.py", line 9, in <module>
    from .logs import logger, set_log_level, use_log_level  # noqa
  File "C:\Users\rober\AppData\Local\Programs\napari\\app_packages\vispy\util\logs.py", line 14, in <module>
    import numpy as np
  File "C:\Users\rober\AppData\Local\Programs\napari\\app_packages\numpy\__init__.py", line 305, in <module>
    _win_os_check()
  File "C:\Users\rober\AppData\Local\Programs\napari\\app_packages\numpy\__init__.py", line 302, in _win_os_check
    raise RuntimeError(msg.format(__file__)) from None
RuntimeError: The current Numpy installation ('C:\\Users\\rober\\AppData\\Local\\Programs\\napari\\\\app_packages\\numpy\\__init__.py') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86
```

## Expected behavior

napari starts up and looks awesome.

## Environment

This is a windows specific issue. 
I didn't install anything else in the python installation napari 0.4.2 delivers.

## Additional context

The bug can be fixed by entering your username in the following line and calling it from the command line:
```
C:\Users\<username>\AppData\Local\Programs\napari\python\python.exe -m pip install numpy==1.19.3
```

Cheers,
Robert

**Comment by Czaki** [comment]
Confirm.

**Comment by sofroniewn** [comment]
@jni @tlambert03 do we need to adjust something to the bundle build before the `0.4.3` release to fix this?

**Comment by tlambert03** [comment]
I think doing what @haesleinhuepf proposed, pinning numpy in bundle.py, is probably a good thing to start with!

**Comment by sofroniewn** [comment]
Nice, yeah let's do that!

**Comment by haesleinhuepf** [comment]
@tlambert03 

> pinning numpy in bundle.py, is probably a good thing to start with!

I just tried that but received an error when running `python bundle.py`:
```
ERROR: Double requirement given: numpy==1.19.3 (already in numpy>=1.16.5, name='numpy')
```

It does work though if I change [this line in setup.cfg](https://github.com/napari/napari/blob/master/setup.cfg#L50) to:
```
numpy>=1.16.5,!=1.19.4
```

If that's ok, I'm happy to submit this change as PR.

**Comment by tlambert03** [comment]
we shouldn't do that in setup.cfg, since we know numpy 1.19.4 works fine in many cases ([including on windows](https://cirrus-ci.com/task/5301716419608576?command=install#L96)), so I think we need to fix the logic that should be preventing the double up here:
https://github.com/napari/napari/blob/ed4a303d768d67a915c0188d5a3baf07aa556761/bundle.py#L59-L67

**Comment by tlambert03** [comment]
oh, actually... that logic is working fine, we just need to _use_ it by changing the line in `make_bundle.yml`:

https://github.com/napari/napari/blob/ed4a303d768d67a915c0188d5a3baf07aa556761/.github/workflows/make_bundle.yml#L59

to `python -m bundle --add numpy==1.19.3`

**Comment by tlambert03** [comment]
or, probably even better, we can change the part of `bundle.py` that says:
```python
 if '--add' in sys.argv: 
     for item in sys.argv[sys.argv.index('--add') + 1 :]: 
```
to make sure that all `EXTRA_REQS` defined in bundle.py also overwrite corresponding setup.cfg.  (if you want me to just take this one let me know)

**Comment by haesleinhuepf** [comment]
> (if you want me to just take this one let me know)

Yes, if you could take this one over, that would be great. I hardly understand what you're pointing at 😅 I'm learning though. so thanks for sharing your thoughts!

**Comment by tlambert03** [comment]
hey @haesleinhuepf, or anyone else who has seen this windows bundle problem... can you try this windows bundle?
~https://github.com/tlambert03/napari/suites/1753551085/artifacts/33354904~

**edit:** actually hold off for a minute

**Comment by tlambert03** [comment]
ok, take2: try the bundles available once done building here: https://github.com/tlambert03/napari/actions/runs/456918742

**Comment by haesleinhuepf** [comment]
Hey @tlambert03 ,

awesome, it works! 🥳 

Unusual was just; The zip file contains a zip file...

**Comment by tlambert03** [comment]
Great thanks.  Yeah that's just due to downloading the artifact directly. I don't think it will be that way on the release page

**Comment by haesleinhuepf** [comment]
Hey @tlambert03 ,

I just noticed that numpy 1.19.5 was released which runs fine again on Windows. Shall we write something like `numpy!=1.19.4`. [here?](https://github.com/napari/napari/blob/master/bundle.py#L28)
