### ISSUE TITLE
register `LayerData` or purpose-specific type instead of `napari.layers.Image` as return type with magicgui.

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#2028]
## 🐛 Bug

the trick of using `napari.layers.Image` as a return annotation to automatically add the result of a function to the current napari viewer "works" fine (and feels quite magical! :joy:) ... but it breaks linters, and is a technically incorrect type annotation, since the return type is _not_ a `napari.layers.Layer` ... but rather just a plain numpy array, or a layerdata tuple.

We should register some type or string specific for the task (like `napari.types.LayerData` or `napari.types.MagicLayer`)

**Comment by sofroniewn** [comment]
Agreed, I remember being confused by that the first time too.

I kinda like `napari.types.LayerData` as a type which includes the `layerdata tuple` and where a plain numpy array is interpreted as a singleton of the layerdata tuple which defaults to image.

Would be open to other ideas, have to think about it more maybe

**Comment by sofroniewn** [comment]
Was this done on the magicgui side? Is this something for `0.2.1`? Just wondering where this stands

**Comment by sofroniewn** [comment]
I guess actually it has to be on the napari side? Maybe something we get in for #1856?

**Comment by tlambert03** [comment]
Yeah, needs to change in utils._magicgui. 
It's a breaking change so will require some extra deprecation code too

**Comment by sofroniewn** [comment]
I'm trying on `0.2.1rc1` right now with #1856 and if I do this

```python
def image_arithmetic(layerA: 'napari.layers.Image', operation: Operation, layerB: 'napari.layers.Image') -> napari.layers.Image:
```

everything works fine, but if I do
```python
def image_arithmetic(layerA: 'napari.layers.Image', operation: Operation, layerB: 'napari.layers.Image') -> 'napari.layers.Image':
```

then when I click "execute" nothing appears. Is that expected, or do we need to fix this to enable that?

**Comment by sofroniewn** [comment]
Similarly there is no output layer with

```python
def gaussian_blur(layer: 'napari.layers.Image', sigma: float = 1.0, mode="nearest") -> 'napari.layers.Image':
```

**Comment by sofroniewn** [comment]
So the above issue with the forward references has now been fixed in magicgui but the original issue remains. From the sounds of discussion with @tlambert03 though this will require more discussion though and so is fine to come after the `0.4.3` release
