### ISSUE TITLE
Render labels using a shader based on hash(label, salt)

### ISSUE THREAD

**Issue by perlman** [napari/napari#204]
## 🚀 Feature
Implement the rendering of label layers as a gl shader. Use a hash based on the label value and a salt to pick a color at random.

## Motivation

The shader generated by vispy.color.colormap for a colormap with a large number of intervals would fail to compile due to an excessive code size. This is not an issue with the shaders for linear colormaps, but those do not clearly differentiate labels with close values.

By using a hash, _any_ label value an be mapped to a random color. A salt is added to shuffle where labels hash to. Also, this allows display of arbitrary labels with complete disregard for the set of global labels.

## Alternatives

We have already implemented a quick-fix to render labels with a large number of segments (#203) by mapping colors to a random label that is mapped to a random color. One downside of the current approach is two label values that map to very close each other will be assigned the same color

## Additional context

An example implementation of using a shader for colorization is in [this branch](https://github.com/perlman/napari/tree/eric-label-hash).

Neuroglancer uses this hashing approach to [assign segment colors](https://github.com/google/neuroglancer/blob/master/src/neuroglancer/segment_color.ts).

Predefined color maps, loaded as textures, could be used to provide discrete sets of colors for the random colors to be drawn from.

**Comment by sofroniewn** [comment]
@perlman @jni - to follow on here there are a couple problems with the current fix.

The first one is that sometimes there can be a discrepancy between the displayed color and the color returned from `label_color` - these are likely do to in-precisions with floating points. For example if you run the `labels-2d.py` example and then set the labels layer to `0` I get a slightly off-green color, that is the color generated by passing `0.00001` to the colormap. Similarly the color corresponding to label `2` appears on the screen as a dark gray - but gives an orange when passed to the function. 

One side question I have about the layer in general is where does the colormap actually get passed to the vispy node? i.e. I am expecting a line like `self._node.cmap=colormap`, but all I can find is `self.colormap = colormap`

Finally the interactivity in the paintbrush in #195 is now very slow. If you use a simple colormap or set `num_colors=10` it becomes fast again.

**Comment by sofroniewn** [comment]
I have been trying about visualizing some labeled EM data from [CREMI](https://cremi.org/data/) - one of the unpadded training sets - and have noticed that switching z-planes is very slow even when the data is fully loaded in memory. See the example gif below.
 
![CREMI](https://user-images.githubusercontent.com/6531703/56714678-6686c700-66ea-11e9-9cbc-be1a36ea45d0.gif)

After using `cProfile`, it is clear that the slow down is caused by our [conversion from integers to floats](https://github.com/napari/napari/blob/81f7473ad730b1a6a588a068dfd94e2c5e6624d1/napari/util/colormaps/colormaps.py#L69), which now happens every time the z-plane changes as it is no longer precomputed once up front. This change was made to handle lazy loading of large images, but the conversion is too slow for good interactivity, taking about 100ms for a 1250x1250 image.

@perlman do you have any thoughts on how to improve this?

Here are the results from `cProfile`:
```
Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.109    0.109    0.112    0.112 colormaps.py:69(_low_discrepancy_image)
        1    0.004    0.004    0.119    0.119 model.py:87(raw_to_displayed)
        1    0.003    0.003    0.003    0.003 {built-in method numpy.where}
        1    0.003    0.003    0.003    0.003 {method 'clip' of 'numpy.ndarray' objects}
        3    0.001    0.000    0.001    0.000 frozen.py:12(__setattr__)
        1    0.000    0.000    0.121    0.121 {built-in method builtins.exec}
        1    0.000    0.000    0.000    0.000 {method 'connect' of 'PyQt5.QtCore.pyqtBoundSignal' objects}
        1    0.000    0.000    0.000    0.000 event.py:442(__call__)
        1    0.000    0.000    0.000    0.000 view.py:35(update_slider)
        1    0.000    0.000    0.000    0.000 event.py:405(__call__)
        1    0.000    0.000    0.001    0.001 image.py:227(set_data)
        1    0.000    0.000    0.121    0.121 model.py:365(_set_view_slice)
      2/1    0.000    0.000    0.121    0.121 model.py:276(_update)
        1    0.000    0.000    0.119    0.119 model.py:340(_slice_image)
        1    0.000    0.000    0.000    0.000 model.py:65(_update_sliders)
        1    0.000    0.000    0.000    0.000 model.py:312(_get_indices)
        4    0.000    0.000    0.000    0.000 _base.py:22(__iter__)
        2    0.000    0.000    0.000    0.000 _base.py:26(__getitem__)
        5    0.000    0.000    0.000    0.000 {built-in method builtins.getattr}
        1    0.000    0.000    0.003    0.003 fromnumeric.py:54(_wrapfunc)
        1    0.000    0.000    0.000    0.000 node.py:325(update)
        1    0.000    0.000    0.000    0.000 {built-in method itemAt}
        1    0.000    0.000    0.000    0.000 {built-in method update}
        2    0.000    0.000    0.000    0.000 _multi.py:8(__prsitem__)
      2/1    0.000    0.000    0.000    0.000 model.py:120(_update)
        1    0.000    0.000    0.003    0.003 fromnumeric.py:1903(clip)
        1    0.000    0.000    0.000    0.000 event.py:477(_prepare_event)
        2    0.000    0.000    0.000    0.000 abc.py:180(__instancecheck__)
        1    0.000    0.000    0.000    0.000 event.py:510(_prepare_event)
        1    0.000    0.000    0.000    0.000 _qt.py:351(_vispy_update)
        1    0.000    0.000    0.000    0.000 model.py:93(_calc_max_dims)
        1    0.000    0.000    0.000    0.000 misc.py:101(compute_max_shape)
        1    0.000    0.000    0.000    0.000 event.py:51(__init__)
       13    0.000    0.000    0.000    0.000 {built-in method builtins.isinstance}
        4    0.000    0.000    0.000    0.000 _weakrefset.py:70(__contains__)
        2    0.000    0.000    0.000    0.000 {built-in method numpy.array}
        1    0.000    0.000    0.000    0.000 canvas.py:182(update)
        1    0.000    0.000    0.000    0.000 model.py:108(_calc_max_shape)
        3    0.000    0.000    0.000    0.000 {built-in method builtins.setattr}
        2    0.000    0.000    0.000    0.000 numeric.py:469(asarray)
        1    0.000    0.000    0.000    0.000 {built-in method layout}
        1    0.000    0.000    0.000    0.000 event.py:89(__init__)
        1    0.000    0.000    0.000    0.000 canvas.py:433(update)
        3    0.000    0.000    0.000    0.000 model.py:120(shape)
        7    0.000    0.000    0.000    0.000 model.py:116(image)
        3    0.000    0.000    0.000    0.000 model.py:273(_get_shape)
        2    0.000    0.000    0.000    0.000 _base.py:41(__prsitem__)
        2    0.000    0.000    0.000    0.000 _typed.py:32(__locitem__)
        1    0.000    0.000    0.121    0.121 <string>:1(<module>)
        2    0.000    0.000    0.000    0.000 {method 'pop' of 'list' objects}
        3    0.000    0.000    0.000    0.000 {method 'get' of 'dict' objects}
        2    0.000    0.000    0.000    0.000 {method 'items' of 'dict' objects}
        2    0.000    0.000    0.000    0.000 {method 'update' of 'dict' objects}
       10    0.000    0.000    0.000    0.000 {built-in method builtins.len}
        1    0.000    0.000    0.000    0.000 {built-in method setMaximum}
        1    0.000    0.000    0.000    0.000 {built-in method setFixedHeight}
        1    0.000    0.000    0.000    0.000 event.py:114(_push_source)
        1    0.000    0.000    0.000    0.000 event.py:117(_pop_source)
        1    0.000    0.000    0.000    0.000 event.py:502(_invoke_callback)
        1    0.000    0.000    0.000    0.000 event.py:76(_push_source)
        1    0.000    0.000    0.000    0.000 event.py:79(_pop_source)
        2    0.000    0.000    0.000    0.000 event.py:253(source)
        2    0.000    0.000    0.000    0.000 model.py:114(ndim)
        3    0.000    0.000    0.000    0.000 model.py:143(viewer)
        1    0.000    0.000    0.121    0.121 model.py:253(refresh)
        1    0.000    0.000    0.121    0.121 model.py:292(_refresh)
        2    0.000    0.000    0.000    0.000 _base.py:79(__locitem__)
        2    0.000    0.000    0.000    0.000 model.py:111(<genexpr>)
        1    0.000    0.000    0.000    0.000 view.py:20(_axis_to_row)
        2    0.000    0.000    0.000    0.000 {method 'copy' of 'dict' objects}
        3    0.000    0.000    0.000    0.000 {built-in method builtins.hasattr}
        1    0.000    0.000    0.000    0.000 {built-in method widget}
        2    0.000    0.000    0.000    0.000 event.py:290(source)
        1    0.000    0.000    0.000    0.000 node.py:254(canvas)
        2    0.000    0.000    0.000    0.000 model.py:53(max_dims)
        2    0.000    0.000    0.000    0.000 {function List.__getitem__ at 0x1146eb400}
        2    0.000    0.000    0.000    0.000 {method 'append' of 'list' objects}
        1    0.000    0.000    0.000    0.000 {method 'extend' of 'list' objects}
        1    0.000    0.000    0.000    0.000 event.py:144(blocked)
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}
        1    0.000    0.000    0.000    0.000 model.py:59(max_shape)
```

**Comment by jni** [comment]
@sofroniewn I think @perlman's answer is right in the title of this issue. In Neuroglancer, there is no conversion at all, and the color is generated in a shader rather than using a float colormap. The image fed to the shader is not cast as float or converted in any way, but rather the raw uint32 bytes are sent to the GPU as if they were float32 bytes. These are nonsensical numerically but it does not matter to the hashing function. In NumPy, this would be done with `.view(np.float32)` for uint32 labels, and `.view(np.float64)` for uint64 labels.

**Comment by sofroniewn** [comment]
Note also that @stefanv has reported in #467 

> - our labels colormap shuffle doesn't reliably separate nearby labels.

likely due to `num_colors` being small by default. We should monitor this as we make any improvements here
