### ISSUE TITLE
segfault on OSX 10.12.6

### ISSUE THREAD

**Issue by d-v-b** [napari/napari#206]
## 🐛 Bug

attempting to use an `app_context` as a context manager crashes python. Seems like the issue is something fonty.

## To Reproduce
```python
Python 3.6.8 |Anaconda custom (64-bit)| (default, Dec 29 2018, 19:04:46)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.2.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from napari.util import app_context

In [2]: a = app_context()

In [3]: with app_context() as a:
   ...:     print('ops')
   ...:
WARNING: PasteBoard: Error creating pasteboard: com.apple.pasteboard.clipboard [-4960]
WARNING: PasteBoard: Error creating pasteboard: com.apple.pasteboard.find [-4960]
2019-04-06 11:49:55.798 python[10787:85476930] XType: failed to connect - Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service named com.apple.fonts was invalidated." UserInfo={NSDebugDescription=The connection to service named com.apple.fonts was invalidated.}
2019-04-06 11:49:55.798 python[10787:85476930] Font server protocol version mismatch (expected:5 got:0), falling back to local fonts
2019-04-06 11:49:55.798 python[10787:85476930] XType: unable to make a connection to the font daemon!
2019-04-06 11:49:55.798 python[10787:85476930] registering /System/Library/Fonts/*, /System/Library/Fonts/Base/*, and /Library/Fonts/* locally
2019-04-06 11:49:57.646 python[10787:85476930] *** CFMessagePort: bootstrap_register(): failed 141 (0x8d) 'unknown error code', port = 0x6bf, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.
Segmentation fault: 11
```
## Expected behavior

not a segfault

## Environment

 - napari Version: 0.0.6+15.g16686b6
 - OSX: 10.12.6
 - Python version: 3.6.8

**Comment by sofroniewn** [comment]
Hmm interesting, thanks for flagging, I do not get that error when I try it on my laptop.

One thing to note though, and maybe we need to update our readme to reflect make this more clear, is that you do not need to use the `app_context` when using ipython.

Using the gui magic, like in the notebook is sufficient, so the following code should launch an image viewer just fine

```python
 %gui qt
from skimage import data
from skimage.color import rgb2gray
from napari import ViewerApp
viewer = ViewerApp(astronaut=rgb2gray(data.astronaut()))
```

**Comment by d-v-b** [comment]
When I run that code snippet, I get this:
```python
In [3]:  %gui qt
   ...: from skimage import data
   ...: from skimage.color import rgb2gray
   ...: from napari import ViewerApp
   ...: viewer = ViewerApp(astronaut=rgb2gray(data.astronaut()))
WARNING: QWidget: Must construct a QApplication before a QWidget
Abort trap: 6
```

**Comment by sofroniewn** [comment]
Try opening a new ipython terminal, just running `%gui qt` waiting a couple seconds for the qt stuff to instantiate (I see a new icon add to my dock on the mac), and then run the rest of the code.

unfortunately what happens in the above case occurs if the ViewerApp starts before the gui magic has finished getting everything ready. We should think about ways to make this easier

**Comment by d-v-b** [comment]
I'm not sure what you could do about that issue with the magic, maybe get the `ipython` people involved? the magic should probably block until the `QtApp` is satisfied with its existence. 

Regarding the app_context-makes-a-segfault thing, all the examples now use the context manager approach, so I figured it was the new default :)

**Comment by sofroniewn** [comment]
Yeah, you only need the `app_context` when launching the viewer from a normal python script - we should make that more clear though

**Comment by jni** [comment]
You can add the Qt gui to your IPython config so it is launched by default. 

https://github.com/jni/ipython-config/blob/master/ipython_config.py#L101

I'm not sure whether there is a more general config setting than `.matplotlib`, but that's what I have and napari Just Works ™️. On mac, though, it is apparently impossible to get rid of the bouncy python icon that steals focus from the terminal.

**Comment by sofroniewn** [comment]
Instructions have been added to [installation tutorial](https://napari.github.io/napari-tutorials/tutorials/installation.html) to make this more clear

**Comment by sofroniewn** [comment]
link should be [getting started tutorial](https://napari.github.io/napari-tutorials/tutorials/getting_started.html)
