### ISSUE TITLE
WSL2 Ubuntu napari failure to launch properly

### ISSUE THREAD

**Issue by Sh4zKh4n** [napari/napari#2069]
## 🐛 Bug

Since linux distros have better support I have been trying out WSL with ubuntu as my distro. I have cuda up and running with cupy. I have followed the intructions from:

https://techcommunity.microsoft.com/t5/windows-dev-appconsult/running-wsl-gui-apps-on-windows-10/ba-p/1493242

to be able to launch GUI's from the linux enviroment but it appears that theres some failure. I get a GUI appear but nothing is in the gui. 

in the linux terminal i find that the following error is showing up

```
WARNING: QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-ouetis_khan'
15:15:19 WARNING QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-ouetis_khan'
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
WARNING: QOpenGLWidget: Failed to make context current
15:15:52 WARNING QOpenGLWidget: Failed to make context current
WARNING: QOpenGLWidget: Failed to make context current
15:15:52 WARNING QOpenGLWidget: Failed to make context current
WARNING: composeAndFlush: makeCurrent() failed
15:15:52 WARNING composeAndFlush: makeCurrent() failed
WARNING: composeAndFlush: makeCurrent() failed
15:15:52 WARNING composeAndFlush: makeCurrent() failed
WARNING: QOpenGLWidget: Failed to make context current
15:15:53 WARNING QOpenGLWidget: Failed to make context current
WARNING: composeAndFlush: makeCurrent() failed
15:15:53 WARNING composeAndFlush: makeCurrent() failed
WARNING: composeAndFlush: makeCurrent() failed
15:15:53 WARNING composeAndFlush: makeCurrent() failed
```

WSL2 with CUDA is a very early stage and you might not have thought about it but given the fact that many of the pushes for image analysis are  with cupy and numba. I wonder  if it's worth you knowing about. It's not so much of an issue because I can process in my wsl enviroment and then use my windows napari implementation to view the processed data. I thought it may be worth noting.

**Comment by tlambert03** [comment]
Hi @Sh4zKh4n and thanks for your note.  I have actually played with WSL2 Ubuntu recently, and stumbled onto the same post that you linked above.  The real challenge here (and what probably makes this different from other basic GUI apps like in that post) is likely on the OpenGL/vispy side.  I _think_ that something like [VirtualGL](https://www.virtualgl.org/) would be required here to redirect the OpenGL commands.  If you're interested in taking a stab at it, the basic idea is outline [here](https://virtualgl.org/About/Introduction), with a full user guide [here](https://cdn.rawgit.com/VirtualGL/virtualgl/2.6.5/doc/index.html) ... and perhaps a useful tip [here](https://superuser.com/questions/1487555/how-to-troubleshoot-opengl-on-ubuntu-under-windows-10-wsl)

**Comment by Sh4zKh4n** [comment]
@tlambert03 might be a little bit beyond my means this one! I think maybe it's one of those to wait till they release the native GUI support in April/May for WSL2. I can still work around it with having napari in the windows enviroment and launching it to view from the shared drives. Thanks for acknowledging! 

Though out of interest, did you also find the memory cut in half? I have gotten Dask_cuda to work on my laptop but found that the wsl2 was cutting my memory in half. found a little config file that lets you change it. Just wondered if you have found a similar issue?

**Comment by tlambert03** [comment]
> maybe it's one of those to wait till they release the native GUI support in April/May for WSL2

oh!  that wasn't on my radar!  Yes that does sound like a good time to pick this up again :)  I hear ya... it's not for the faint of heart, I gave up too :)

>  did you also find the memory cut in half?

I hadn't noticed that... but I also wasn't looking.  Good to know about though!

**Comment by Sh4zKh4n** [comment]
I created a file as the inbstructions suggest and added the following:

[wsl2]
memory=12GB   # Limits VM memory in WSL 2 up to 13GB
processors=3 # Makes the WSL 2 VM use 3 virtual processors (1 core left for windows)
swap=200GB
swapFile=E:\\temp\\swap.vhdx
localhostForwarding=true

That seems to do the trick. When I run a dask.distributed client I now have 12.6Gb vs my previous 8GB in wsl2. So thats an improvement. Cupy is working, unfortunately cant get cupyimg to work but Ill leave that till another day....or when they get those as a part of cupyimg. At least I can use a local dask cuda cluster as i have two (not very good but better than nothing Nvidia GPUs 1060 (embedded) and a eGPU with 1066). So 6Gb on each and 13Gb of ram to play with it. Will let you know how it goes. Right now I have a 4 yr old telling to cook food!
