### ISSUE TITLE
pip install napari[all] does not work with zsh

### ISSUE THREAD

**Issue by pwinston** [napari/napari#2081]
## 📚 Documentation

The homepage says run `pip install napari[all]` but with `zsh` this doesn't work:
```
(napari39) ➜  pip install napari[all]
zsh: no matches found: napari[all]
```
You have to type `pip install napari\[all\]` if using `zsh` with defaults.

On the one hand, the instructions will get messy if we try to walk people through every single possible situation. On the other hand, `zsh` is the default shell on MacOS for new users. For example, here are people hitting that exact problem trying to pip install various other things with brackets in the names:

https://stackoverflow.com/questions/30539798/zsh-no-matches-found-requestssecurity
https://stackoverflow.com/questions/56037311/unable-to-install-a-python-package-on-zsh-but-successful-on-bash
https://stackoverflow.com/questions/39565867/zshell-pip-cant-find-package-autobahnserialization
https://medium.com/@grepLeigh/zsh-no-matches-found-ea5bdc551ff1

So I'm not sure what the right fix is here. But I thought it was worth mentioning.

**Comment by tlambert03** [comment]
interesting, I hadn't noticed this... looks like it gets fixed by the [pip plugin for oh-my-zsh](https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/pip).

just to point out, you can also do `pip install 'napari[all]'`, instead of escaping each bad character.  I've had to do that when using version specifiers like `pip install 'package<=x.y'`

I always struggle with what to do here, since I don't think our docs necessarily need to cover every edge case that a terminal user runs into...  but I guess it's true that if we want a new mac user who's never touched a terminal to be able to follow our docs and get up and running, they'd have an issue.

**Comment by pwinston** [comment]
If the quotes are harmless to all the other shells/OS's, could we just write it that way, and not actually mention the zsh/quoting issue? Just have the quoted way be the only way? Because if we show it the "wrong" way and have note below for zsh users, I think many people will not read the note.

It's not ideal to have brackets at all. I'm not sure I've encountered many other pip packages that require brackets for vanilla installs. That's a different and bigger issue. But I see that a lot where you veer of the main path for a good reason, but then it bites you later on for some unrelated reason.

**Comment by tlambert03** [comment]
> It's not ideal to have brackets at all. I'm not sure I've encountered many other pip packages that require brackets for vanilla installs. That's a different and bigger issue. But I see that a lot where you veer of the main path for a good reason, but then it bites you later on for some unrelated reason.

That's been discussed [ad nauseum](https://github.com/napari/napari/issues/704) ... and after asking [directly asking the python packaging authority](https://discuss.python.org/t/conditional-package-install-depending-on-other-packages-in-environment/4140) the question of how to support multiple backends without demanding a specific one always be installed, that's the approach they suggested.  So, i don't think it's fair to call it off the main path.

There are a couple of open issues: (https://github.com/pypa/packaging-problems/issues/214, https://github.com/pypa/setuptools/issues/1139) that might help us not have to use `napari[all]` (while still allowing people to choose their own backend).  But for better or worse, this is the "officially recommended" approach to achieve what we're after for now

**Comment by pwinston** [comment]
I've not followed any of the discussion. Most packages I install don't seem to need brackets. But definitely, if we need them then we need them. So then yeah, the issue is just how to document it.

**Comment by jni** [comment]
Agreed on ~all points above: not ideal, standard-but-not-common situation, probably the best we can do currently. (We also had the same discussion with scikit-image[data] recently.) I think @pwinston's suggestion that we always write `pip install 'napari[all]'` is pretty good.

One can only curse Apple so many times... =P

**Comment by GenevieveBuckley** [comment]
I agree, let's put `pip install 'napari[all]'` in the docs if that's what reliably works everywhere.
