### ISSUE TITLE
Layer `_coerce_name` strategy breaks magicgui `reset_choices`

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#2086]
## 🐛 Bug
The strategy we currently use of enforcing uniqueness in the layerlist doesn't work with the way we autopopulate the layer list in a magicgui widget.  The problem is that there is a brief moment _after_ the layerlist has emitted the `inserted` event, but before it has called [`viewer._on_add_layer`](https://github.com/napari/napari/blob/7dbebffa3f60779dac6de762c753b054871447ad/napari/components/viewer_model.py#L549) (which calls `self.layers._coerce_name(layer.name, layer)`)... when magicgui queries the names, they are not yet unique. 

I think the solution here is to enforce the uniqueness before even inserting into the layerlist.  I'll submit a PR shortly

**Comment by sofroniewn** [comment]
> I think the solution here is to enforce the uniqueness before even inserting into the layerlist. I'll submit a PR shortly

Sounds reasonable, that part of the code has always been a little shakey I think. I actually played with some stuff in #2021 that I thought was quite nice which allowed you to subclass the `insert` and `__del_item__` methods in `LayerList` see https://github.com/napari/napari/pull/2021/files#diff-acfb43cfe7047ea39e1d0f252aa2225d6a7f3f2f1fd59e11efb7851c219427d1R43-R51 (you also need the changes in https://github.com/napari/napari/pull/2021/files#diff-3fba57151711ece29ec42ddd749350fed98ecaf5c479526a7a54990cb2c7ddbcR171-R231). As that could provide an elegant way to do this enforcement.

**Comment by tlambert03** [comment]
yeah I also think the solution is just to reimplement `insert()` and do the checking there before calling _super()_

**Comment by sofroniewn** [comment]
> yeah I also think the solution is just to reimplement insert() and do the checking there before calling super()

Nice. I made the additional changes in `EventedList` to prevent `insert` from getting called when reordering the list (setting the private `_list` directly instead). While it's not terrible to call `insert` again, I think it makes for overall cleaner flow as there's no need to do things like recheck uniqueness when adding reordering.

This change would also let us move more event wiring into the layerlist directly too, which might be nice long term
