### ISSUE TITLE
Widgets added with `add_plugin_function_widget` not fully cleaned up on exit.

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#2089]
## 🐛 Bug
Minor issue discovered when writing tests for #2080.  (minor enough that it can wait... just don't want to forget)

Adding plugin function widgets (but _not_ plugin Dock Widgets), leaves some "leaked widgets" after triggering "Remove Dock Widgets"

```python
# from napari._qt._tests.test_plugin_widgets
def test_clear_all_plugin_widgets(test_plugin_widgets, make_test_viewer):
    viewer = make_test_viewer()
    actions = viewer.window._plugin_dock_widget_menu.actions()
    actions[2].trigger()
    clear_action = next(
        a
        for a in viewer.window.window_menu.actions()
        if a.text().startswith("Remove Dock Widgets")
    )
    clear_action.trigger()
    assert len(viewer.window._dock_widgets) == 0
```

```pytb
AssertionError: Widgets leaked!: {<PyQt5.QtWidgets.QFrame object at 0x7fbd297a3700>, <PyQt5.QtWidgets.QWidget object at 0x7fbd49626670>}
```

**Comment by sofroniewn** [comment]
Yes, I had noticed cleanup/ removal wasn't working quite right for my `napari-console` plugin, not sure if related, but i'm happy waiting on this till `0.4.4` unless you find something urgent

**Comment by sofroniewn** [comment]
Just wondering if after #2397 we still see this or if there is an opportunity to fix more cleanly now too. #2360 might also have helped - cc @tlambert03 @goanpeca ?

**Comment by goanpeca** [comment]
> we still see this or if there is an opportunity to fix more cleanly now too.

Not sure :)

**Comment by lucyleeow** [comment]
AFAICT we have [`remove_dock_widget`](https://github.com/napari/napari/blob/7648fdce08af9249cd36eea61b0a38aad5b29c8b/napari/_qt/qt_main_window.py#L1256), which seems to clean up dock widgets when we close them. So getting to the root of this issue, I think we do clean up widgets now. 

Closing but please re-open if this is not right.
