### ISSUE TITLE
Valid magic kwargs check too strict?

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#2098]
## 🐛 Bug

I think the valid magic kwargs check from our plugins added in #2080 is too strict here https://github.com/napari/napari/blob/b3dd593ea1b29e48e38ef3729bced196ab6aab6d/napari/plugins/__init__.py#L136-L142

For example if I have 

```python
def gaussian_blur(
    layer: 'napari.layers.Image', sigma: float = 1.0, mode="nearest"
) -> 'napari.layers.Image':
    """Apply a gaussian blur to ``layer``."""
    if layer:
        return skimage.filters.gaussian(layer.data, sigma=sigma, mode=mode)


# Define our magic. The function will be automatically called when the
# input values are changed
magic_gaussian_blur = {
    'auto_call': True,
    'sigma': {"widget_type": "FloatSlider", "max": 6},
    'mode': {"choices": ["reflect", "constant", "nearest", "mirror", "wrap"]},
}
```

then I'm getting a warning

```python-traceback
/Users/nsofroniew/GitHub/napari/napari/plugins/__init__.py:138: UserWarning: Plugin 'io-test' provided invalid magicgui kwargs to `napari_experimental_provide_function_widget` for function 'gaussian_blur': {'mode', 'sigma'}. Widget ignored.
  f'Plugin {plugin_name!r} provided invalid magicgui kwargs '
```

Unless we decided those sorts of annotations shouldn't be possible, but then we should drop them from our example https://github.com/napari/napari/blob/b3dd593ea1b29e48e38ef3729bced196ab6aab6d/examples/magic_parameter_sweep.py#L29-L33

Thoughts @tlambert03?

**Comment by jni** [comment]
I agree that the check is too strict. This should definitely be allowed, imho.

**Comment by tlambert03** [comment]
Oh yeah, that’s just incorrect!  Sorry about that.  I’ll submit a fix.
