### ISSUE TITLE
Unified framework for keybindings

### ISSUE THREAD

**Issue by jni** [napari/napari#210]
Currently, keybindings are implemented as a hodgepodge of handcrafted if-else statements, see e.g. https://github.com/napari/napari/pull/195/files#diff-347152977a8bc6500ffce60fc0e90a0dR653

What I envision is a yaml config file that maps keys to functions, as well as a description. Each layer comes with its own file, as well as the base viewer. When a layer is selected, its keybindings override base layer keybindings. I think probably viewer keybindings should be universal and not allowed to be overwritten, but that can be discussed. We should *not* allow multiple keybindings. mpl does this and gives no indication about what is happening (the keybinding triggers *all* associated events!).

When the keybinding '?' is pressed, we use some kind of temporary, transparent popup display of the keybindings, with the layer keybindings on top and other keybindings following it. The popup displays each bound key and its description from the config file.

Config files can be customised. Custom copies live in .config/napari and are loaded *after* the default copy.

**Comment by sofroniewn** [comment]
Hopefully this will then make it easier to support #200

**Comment by gregjohnso** [comment]
> Hopefully this will then make it easier to support #200

and #212

**Comment by sofroniewn** [comment]
Yes our framework should also allow attaching custom functions for mouse click, mouse press, mouse release, and mouse doubleclick

**Comment by kevinyamauchi** [comment]
@jni , I think this is a great idea. In terms of features, I think this is a pretty high priority after #171 lands. I would even propose this is one of the last feature to add before circling back for testing/clean up of all of the awesome features that have been added thus far.

I like the idea of a mapping between events and functions. Were you thinking the main `Viewer` and each layer would have a dictionary where the keys are events and the values are the associated function? If we want to prevent overriding of the base `Viewer` key/event bindings, we can just check the `Viewer` dictionary first. We can also check for conflicts upon loading layers.

Do you think it's useful to allow the user to add/remove keybindings at run time (e.g., `Layer.add_binding()`? One potential use case is if the user wants to add behavior around a common layer for a specific task (e.g., painting labels on data) and does not want to write over the layer key bindings config file. If we store the keybinding/function mapping in a dictionary, it should be fairly straightforward to add/change bindings. Of course the challenge is validating them.

**Comment by sofroniewn** [comment]
@kevinyamauchi i think you mean #171 not #115 (also named dims refactor ...)

I really like the `add_binding` idea where a custom dictionary is passed - I think it is similar to the proposal from @gregjohnso described in #200

**Comment by kevinyamauchi** [comment]
Ah yes, correct on both fronts, @sofroniewn ! This particular feature would be pretty useful for me, so let me know if I can help in any way. Looking forward to this!

**Comment by sofroniewn** [comment]
This is close to completion - we now have a standard framework - but still need to move our own internal functions over to using it. Maybe @kne42 can address this next

**Comment by sofroniewn** [comment]
with #444 we're now using the new keybinding system for our internal keybindings too
