### ISSUE TITLE
DoubleClick to 2x zoom

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#212]
## 🚀 Feature
As requested by @jni in #211 - it can be very nice to double click on a point to zoom 2x instead of having to scroll in. The idea was that this feature should apply whenever pan/zoom is enabled on any layer type.

**Comment by hectormz** [comment]
@sofroniewn is this still valid issue? What challenge does this face? Do we need to define a double click ourselves?

**Comment by sofroniewn** [comment]
Yeah, we have a proposal in #1048 to improve our double click handling, so this is likely waiting on that
