### ISSUE TITLE
new hookspecs not in documentation

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#2126]
## 📚 Documentation

The new hook specifications need to be added to `hook_specifications.rst` in `/doc/source/plugins` in order to show up in the docs.

(This is one of those tricky tradeoffs between spending time making sure that they are always automatically added while also looking good... vs just manually updating periodically.  I don't really have a strong opinion)

**Comment by sofroniewn** [comment]
oops! Good catch!! I think manually updating is fine, we just need to remember!!

**Comment by sofroniewn** [comment]
could also add a test that checks they are there? not sure if people like that idea

**Comment by sofroniewn** [comment]
closed by #2158
