### ISSUE TITLE
IPython embeded console: exit() raises an error

### ISSUE THREAD

**Issue by Carreau** [napari/napari#2133]
## 🐛 Bug

It seem like InProcessKernel has a bug an try to access a field that does not exists on this specific subclass

## To Reproduce

1. open napari
2. open the console
3. type exit()

EDIT: it doesn't crash now, and exit is just no-op. Maybe it should print a warning ? 

```
In[1]: exit()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-e828459ebe2b> in <module>
----> 1 exit()

~/miniconda3/envs/napari/lib/python3.8/site-packages/IPython/core/autocall.py in __call__(self, keep_kernel)
     68     def __call__(self, keep_kernel=False):
     69         self._ip.keepkernel_on_exit = keep_kernel
---> 70         self._ip.ask_exit()

~/miniconda3/envs/napari/lib/python3.8/site-packages/ipykernel/zmqshell.py in ask_exit(self)
    528     def ask_exit(self):
    529         """Engage the exit actions."""
--> 530         self.exit_now = (not self.keepkernel_on_exit)
    531         payload = dict(
    532             source='ask_exit',

~/miniconda3/envs/napari/lib/python3.8/site-packages/traitlets/traitlets.py in __set__(self, obj, value)
    602             raise TraitError('The "%s" trait is read-only.' % self.name)
    603         else:
--> 604             self.set(obj, value)
    605 
    606     def _validate(self, obj, value):

~/miniconda3/envs/napari/lib/python3.8/site-packages/traitlets/traitlets.py in set(self, obj, value)
    591             # we explicitly compare silent to True just in case the equality
    592             # comparison above returns something other than True/False
--> 593             obj._notify_trait(self.name, old_value, new_value)
    594 
    595     def __set__(self, obj, value):

~/miniconda3/envs/napari/lib/python3.8/site-packages/traitlets/traitlets.py in _notify_trait(self, name, old_value, new_value)
   1215 
   1216     def _notify_trait(self, name, old_value, new_value):
-> 1217         self.notify_change(Bunch(
   1218             name=name,
   1219             old=old_value,

~/miniconda3/envs/napari/lib/python3.8/site-packages/traitlets/traitlets.py in notify_change(self, change)
   1225     def notify_change(self, change):
   1226         """Notify observers of a change event"""
-> 1227         return self._notify_observers(change)
   1228 
   1229     def _notify_observers(self, event):

~/miniconda3/envs/napari/lib/python3.8/site-packages/traitlets/traitlets.py in _notify_observers(self, event)
   1262                 c = getattr(self, c.name)
   1263 
-> 1264             c(event)
   1265 
   1266     def _add_notifiers(self, handler, name, type):

~/miniconda3/envs/napari/lib/python3.8/site-packages/ipykernel/zmqshell.py in _update_exit_now(self, change)
    472         """stop eventloop when exit_now fires"""
    473         if change['new']:
--> 474             loop = self.kernel.io_loop
    475             loop.call_later(0.1, loop.stop)
    476             if self.kernel.eventloop:

AttributeError: 'InProcessKernel' object has no attribute 'io_loop'
```
## Expected behavior

Unclear but not a traceback; My guess is we want to close the console; not quit napari, which is likely to happend if I fix the bug in ipykernel.

## Additional context

Need to open corresponding issue on ipykernel to fix; but a workaround is likely possible in napari that register `exit()` as close console , or no-op.

**Comment by sofroniewn** [comment]
Just adding note here too that we might want to fix this in the new https://github.com/napari/napari-console repo, see #2118 which would switch us over to using that

**Comment by psobolewskiPhD** [comment]
@Carreau I'm not getting an error using the instructions from the OP. Instead `exit()` is just ignored:
<img width="1214" alt="image" src="https://user-images.githubusercontent.com/76622105/196781619-79a671d5-c96e-4751-aca5-fb0145ead30e.png">

I'm not sure what the expected behavior should be, so I'm sort of OK with ignoring it? I'd rather it not kill the console so it can't be reopened and for sure not kill napari...

**Comment by Carreau** [comment]
Yeah, it does not crash anymore. The question is 1) should it just do nothing, or print a warning ? "hey we think this is a mistake, you might not be trying to exit napari". I remove the "bug" and happy to get it closed.

**Comment by psobolewskiPhD** [comment]
Hmm, that's a very good question.
I guess I can see a user using the console and hoping to use a text command to quit/close napari, despite the presence of shortcuts for that, so such a warning makes sense. Alternately, it could be the user wants to close the console...
I think I'd vote to close this and make that a new issue—should it be in the napari-console repo?—because the bug is solved and it's not clear what the better path forward is.

**Comment by Czaki** [comment]
the default call `exit()` is raising `SystemExit` exception. 

(This is a technical comment).

**Comment by psobolewskiPhD** [comment]
I made an issue to track possible effects of `exit()` in the console, so closing this because the error is no more.
