### ISSUE TITLE
User Experience: Corresponding Keyboard shortcut in buttons tooltips.

### ISSUE THREAD

**Issue by Carreau** [napari/napari#2135]
## 🚀 Feature

Discoverability in shortcut is important; one of the place they could be added is in the tool tips buttons, to make them more easily discoverable.

## Motivation

Many users will not go out of their way to find the keyboard shortcut in the shortcut dialog, as it requires to interrupt one flow and find the same action in a different place. Having Kbd shortcut as part of the usual flow make it simpler to find them and learn them passively. 

## Pitch

Turn this
<img width="301" alt="Screen Shot 2021-01-19 at 2 25 45 PM" src="https://user-images.githubusercontent.com/335567/105101200-59d00800-5a63-11eb-8d92-a43fffc992a2.png">

into 

<img width="317" alt="Screen Shot 2021-01-19 at 2 27 38 PM" src="https://user-images.githubusercontent.com/335567/105101224-5f2d5280-5a63-11eb-9330-f4200e2b764a.png">

I'm assuming the action (callbacks) are separated from their shortcuts on buttons, but it should be possible for a given callback to find the corresponding shortcut, and not hardcode those in tooltips.

## Alternatives

- Leave things as is.
- make the shortcut even more visible in the UI

## Additional context

Side note, on Mac, shortcut text tends to not be separated by `-`, or `+`, that is to say a native mac menu will show `⌘Y`, not `⌘-Y` or `⌘+Y` (note ⌘<- cmd symbol on mac for users that don't have the font). 

When a command is associated with a icon (like here a cube/square), it could be visually helpful to list those in the keybinding window.

**Comment by sofroniewn** [comment]
Love this idea!

**Comment by sofroniewn** [comment]
This will be closed by #2284 I think

**Comment by sofroniewn** [comment]
Now that #2612 has merged can we close this?
