### ISSUE TITLE
Cannot import Napari

### ISSUE THREAD

**Issue by FiReTiTi** [napari/napari#2149]
Hi,
it seems that there is an issue with my Napari installation.

## To Reproduce
I installed Napari using pip: sudo pip install napari[all].
Then I started python and tried `import napari`, but I got the following error:

## Expected behavior

    >>>import napari
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/napari/__init__.py", line 16, in <module>
        from ._event_loop import gui_qt, run
      File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/napari/_event_loop.py", line 2, in <module>
        from ._qt.qt_event_loop import gui_qt, run
      File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/napari/_qt/__init__.py", line 45, in <module>
        path, loader = import_resources()
      File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/napari/_qt/qt_resources/__init__.py", line 122, in import_resources
        respath = build_pyqt_resources(fspath(target_file), overwrite=overwrite)
      File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/napari/_qt/qt_resources/build_icons.py", line 226, in build_pyqt_resources
        for name in _find_rcc_or_raise():
      File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/napari/_qt/qt_resources/build_icons.py", line 177, in _find_rcc_or_raise
        raise FileNotFoundError(
    FileNotFoundError: Unable to find an executable to build Qt resources (icons).
    Tried: 'pyrcc5.bat', 'pyrcc5', 'pyside2-rcc'.
    Please open issue at https://github.com/napari/napari/issues/.

## Environment

MacOSX 10.15.7
Python 3.8.7 installed using MacPort, (default, Dec 24 2020, 16:36:45) [Clang 11.0.3 (clang-1103.0.32.62)] on darwin
Pip 20.3.3 installed using MacPort
Napari installed PyQt5 5.15.2 and PyQt5-sip 12.8.1

## pip freeze
alabaster==0.7.12
anyio==2.0.2
appdirs==1.4.4
appnope==0.1.2
argon2-cffi==20.1.0
astroid==2.4.2
async-generator==1.10
attrs==20.3.0
Babel==2.9.0
backcall==0.2.0
Beaker==1.11.0
bleach==3.2.2
bokeh==2.2.3
cachey==0.2.1
cellpose==0.6
certifi==2020.12.5
cffi==1.14.4
chardet==4.0.0
colorcet==2.0.6
cycler==0.10.0
dask==2021.1.0
decorator==4.4.2
defusedxml==0.6.0
docutils==0.16
entrypoints==0.3
freetype-py==2.2.0
h5py==3.1.0
HeapDict==1.0.1
holoviews==1.14.1
horology==1.1.0
idna==2.10
imageio==2.9.0
imagesize==1.2.0
ipykernel==5.4.3
ipython==7.19.0
ipython-genutils==0.2.0
isort==5.6.4
jedi==0.18.0
Jinja2==2.11.2
joblib==1.0.0
json5==0.9.5
jsonschema==3.2.0
jupyter-client==6.1.11
jupyter-core==4.7.0
jupyter-server==1.2.2
jupyterlab==3.0.5
jupyterlab-pygments==0.1.2
jupyterlab-server==2.1.2
kiwisolver==1.3.1
lazy-object-proxy==1.4.3
llvmlite==0.35.0
magicgui==0.2.5
Mako==1.1.4
Markdown==3.3.3
MarkupSafe==1.1.1
matplotlib==3.3.3
mccabe==0.6.1
mistune==0.8.4
napari==0.4.3
napari-plugin-engine==0.1.9
napari-svg==0.1.4
natsort==7.1.0
nbclassic==0.2.6
nbclient==0.5.1
nbconvert==6.0.7
nbformat==5.1.2
nest-asyncio==1.4.3
networkx==2.5
notebook==6.2.0
numba==0.52.0
numpy==1.19.5
numpydoc==1.1.0
opencv-python-headless==4.5.1.48
packaging==20.8
pandas==1.2.1
pandocfilters==1.4.3
panel==0.10.3
param==1.10.1
parso==0.8.1
pexpect==4.8.0
pickleshare==0.7.5
Pillow==8.1.0
prometheus-client==0.9.0
prompt-toolkit==3.0.11
psutil==5.8.0
ptyprocess==0.7.0
pycparser==2.20
pyct==0.4.8
Pygments==2.7.4
pylint==2.6.0
PyOpenGL==3.1.5
pyparsing==2.4.7
PyQt5==5.15.2
PyQt5-sip==12.8.1
pyrsistent==0.17.3
python-dateutil==2.8.1
pytz==2020.5
pyviz-comms==2.0.1
PyWavelets==1.1.1
PyYAML==5.4.1
pyzmq==21.0.1
qtconsole==5.0.1
QtPy==1.9.0
requests==2.25.1
scikit-image==0.18.1
scikit-learn==0.24.1
scipy==1.6.0
Send2Trash==1.5.0
six==1.15.0
sniffio==1.2.0
snowballstemmer==2.0.0
Sphinx==3.4.3
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==1.0.3
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.4
tabulate==0.8.7
terminado==0.9.2
testpath==0.4.4
threadpoolctl==2.1.0
tifffile==2021.1.14
toml==0.10.2
toolz==0.11.1
torch==1.7.1
torchaudio==0.7.2
torchvision==0.8.2
tornado==6.1
tqdm==4.56.0
traitlets==5.0.5
typing-extensions==3.7.4.3
urllib3==1.26.2
vispy==0.6.6
wcwidth==0.2.5
webencodings==0.5.1
wrapt==1.12.1

What am I missing?

**Comment by tlambert03** [comment]
Hi @FiReTiTi, sorry you're having this issue.

most often this occurs because of some environment issue.  It looks like you're installing into a global python environment, and some previously installed stuff _might_ be conflicting.  In the vast majority of cases, this may be fixed by creating a new "virtual environment" in which to install and run your programs.  This is one of the reasons we give this little bit of advice in our readme:


> Note: while not strictly required, it is highly recommended to
> install napari into a clean virtual environment using an environment
> manager like [conda](https://docs.conda.io/en/latest/miniconda.html). 
> For example, with conda:
>```
>conda create -y -n napari-env python=3.8
>conda activate napari-env
>pip install napari[all]
>```

If you want to post the output of `pip freeze` here, we can try to help debug your environment, but you might be better off in the long run going with a virtual environment manager like conda.

**Comment by FiReTiTi** [comment]
Thank you for your answer. I don't have multiple programs and libraries to use, this is why I didn't create a specific environment.
I've updated my original post with the `pip freeze` results.

**Comment by tlambert03** [comment]
thanks for the update.  If you just run `which pyrcc5` on the command line, does it give you anything?

**Comment by FiReTiTi** [comment]
Nothing found :-(
I tried to do `pip search pyrcc5`, but got an error:

pip search pyrcc5                                                                                                                                                                                                             13:20:53 
ERROR: Exception:
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 224, in _main
    status = self.run(options, args)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip/_internal/commands/search.py", line 62, in run
    pypi_hits = self.search(query, options)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip/_internal/commands/search.py", line 82, in search
    hits = pypi.search({'name': query, 'summary': query}, 'or')
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/xmlrpc/client.py", line 1109, in __call__
    return self.__send(self.__name, args)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/xmlrpc/client.py", line 1450, in __request
    response = self.__transport.request(
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip/_internal/network/xmlrpc.py", line 46, in request
    return self.parse_response(response.raw)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/xmlrpc/client.py", line 1341, in parse_response
    return u.close()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/xmlrpc/client.py", line 655, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault -32500: "RuntimeError: PyPI's XMLRPC API has been temporarily disabled due to unmanageable load and will be deprecated in the near future. See https://status.python.org/ for more information.">

**Comment by tlambert03** [comment]
`pyrrc` _should_ have been installed when you got PyQt5... so that's what we need to figure out here.  you can try to do `pip uninstall -y PyQt5` and then `pip install PyQt5`, but the other possibility is that the `pyrrc` script _did_ get installed, but to some location that's not on your PATH for some reason.  Based on your stack traces, I would have expected `pyrrc5` to have been put in `/opt/local/Library/Frameworks/Python.framework/Versions/3.8/bin`.  Can you look in there?  or maybe run the following and see if it got put anywhere?

```sh
find /opt/local/Library/Frameworks/Python.framework/Versions/3.8/ -name pyrcc5
```

and if that _still_ gives nothing try:

```sh
find /opt/local/Library/Frameworks/Python.framework/Versions/3.8/ -name 'pyrcc*'
```

**Comment by FiReTiTi** [comment]
Good catch.
`pyrcc5`was installed in `/opt/local/Library/Frameworks/Python.framework/Versions/3.8/bin`, and this directory was added to `PYTHONPATH`, but not to the `PATH`, so I added `PYTHONPATH` to `PATH`.
I tried to import Napari and it's now working.
Thanks a lot for your help.

**Comment by tlambert03** [comment]
great news!  thanks for helping us track that down, will be useful to have here for others.
