### ISSUE TITLE
Consider dropping support for plugin discovery by naming convention

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#2151]
I just spent some time trying to figure out why one of my examples in magicgui (`napari_forward_refs`) was getting "magically" run every time I ran one of the other napari examples.  Turns out the reason was that, by default, we consider any module starting with the word "napari" to be a potential plugin, and because python considers the current directory to be in PYTHONPATH, that means that if you import napari in one thing, they _all_ get imported.  I could of course just rename all those things, but in many "examples" cases, you don't want to rename them!  So, I propose that we _require_ plugins to announce themselves using `entry_points`, rather than just blindly importing and searching every module in PYTHONPATH that starts with "`napari_`"

**Comment by jni** [comment]
I'm 100% +1 on this. As you know I dislike naming convention as a way to signal things.

**Comment by sofroniewn** [comment]
I'm supportive too, will review PR now. Thanks!!
