### ISSUE TITLE
Resimplify the image slice/view logic

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#2156]
## 🚀 Feature

Just want to open up a discussion about the possibility of re-simplifying some of the chain of objects introduced into the `image.py` rendering logic.  In debugging #2155, it took me a quite a while to figure out what is happening, (starting at `_set_view_slice`), even though I've gone through that chain before at least 2 or 3 times now.  I of course don't want to lose the possibility of having asynchronous loading in the future, which is obviously very high value, but I fear we have a situation now where one of the most important parts of the codebase (how a slice gets extracted from data) might be a bit opaque and therefore neglected ... where it should really be one of the most heavily "inspected" parts of the codebase.

**Comment by sofroniewn** [comment]
I agree that the current state needs to be improved. My hope was that things like #1775 would have moved along faster where we'd drop slicing from the layer entirely - which I think we all want - and would clean this up for free. Given how long that's taking it's fair to ask if we should do some additional clean up before then. I'd like to look through #2155 and see what needs to be done to fix that, if it's quick then maybe we can just get that done and press on with #1775, if it seems like it needs more work then maybe we do some intermediate clean up first

**Comment by tlambert03** [comment]
I'm gonna close this.  I think the general goal here is fully in our collective consciousness, and @andy-sweet will probably improve the state of things here gradually in the slicing work
