### ISSUE TITLE
Allow zoom but not pan while in points layer selection mode

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#2159]
## 🚀 Feature
In #2148 @jni requested the following for Points layers

> The only thing that I would like is for zoom to work during selection, but that can come in a later PR.

cc @VolkerH 

## Motivation

Much easier moving around in selection mode

## Additional context

This will actually be tricky as right now we have a single `interactive` flag that disables ALL the camera interactivity, we could make two flags one for pan and one for zoom, and then interactive could be derived from them/ used to set them both, but it might require some changes on the vispy end or some larger changes on the napari end. We'll have to think about it

**Comment by sofroniewn** [comment]
I do want to add in case people have forgotten that holding spacebar will temporarily reanable pan/zoom. Not ideal, but also not the worst

**Comment by VolkerH** [comment]
My personal preference would  be to fully enable both pan/zoom in selection mode as well.

Single click still selects, dragging pans. To drag open a selection rectangle use a modifier key or right mouse button. Status bar could mention _hold SHIFT for rectangular selection_, so that the feature can be discovered by the user. 

I argue that it would feel more natural and consistent moving around the canvas. Holding SHIFT or CTRL keys to modify selection behaviour to enable multiple selections is a very common UX pattern, including in file managers.

**Comment by sofroniewn** [comment]
> My personal preference would be to fully enable both pan/zoom in selection mode as well.

@VolkerH if we did this (which I'm open to) would we actually still need `select` mode vs `pan/zoom` mode or could we just have the one mode? I'm not sure, I'd probably still see the value of having them be separate but I'm less sure and so want to ask

**Comment by VolkerH** [comment]
I'm not sure I have a good answer. 

In a sense almost everything could go into a single mode, adding, selecting and zoom/pan.
The distinction between selecting and adding would simply be made whether on clicks into empty space or onto an existing point. 
However, that brings new problems, such as "how close to an existing point is considered clicking on that point".

So in a sense having a dedicated mode makes it more explicit that one is selection, so my gut feeling is to keep selection mode.
Again, I am not a UX expert. I reckon different users will have different preferences, e.g. based on whether they often need to place 100's of points or occasionaly just 3 or 4.

**Comment by psobolewskiPhD** [comment]
Zoom now works in selection mode, thanks to https://github.com/napari/napari/pull/5701
Drag permits multiple point selection, so one must use space to toggle pan as needed.
I think this is pretty intuitive overall.
@jni can we consider this issue closed?
