### ISSUE TITLE
Maybe add DockWidget > should (re)show a hidden widget.

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#2162]
## 🐛 Bug
If someone adds a widget with  `Add Dock Widget >` and then clicks on the `x` to close the widget, they may well have no idea that a new menu item has been added to the `Window` menu... and then when they try create a new "instance" with Dock Widget, all that happens is they get a "Dock widget already added" warning.

That's a bit confusing, I think we all liked the window menu item, but would be great if that plugins menu action could re-show a hidden widget (or, at the very least, tell them where they now have to go to show it again)

**Comment by sofroniewn** [comment]
yeah, i have found this pattern a little odd too in actual usage! I've by mistake gone back and clicked on that other one. As we said at the time though this is easy to change. I like the solution that we just `re-show` the hidden widget. Should be a simple enough fix.

**Comment by kevinyamauchi** [comment]
I agree that it is a bit confusing if the main way to reopen a widget is via a menu item that is added automatically. How does the user delete an instance of a running plugin? I think depending on whether the user is used to Mac OS or Windows may influence the behavior they expect when clicking the `x` (i.e., Mac OS often leaves apps running when closing the window with the `x`)

edit: sorry, accidentally closed the issue!

**Comment by jni** [comment]
I agree with Talley's proposed fix. As a general rule, no-ops when "the machine" knows exactly what *should* be done are super frustrating! Just do the thing! 😂 Even if the message says "btw, there's a shortcut for you in the Window menu!"
