### ISSUE TITLE
Use JSON schema to define settings that need persistence

### ISSUE THREAD

**Issue by goanpeca** [napari/napari#2174]
## Motivation

Splitting from https://github.com/napari/napari/issues/992

We need a way to describe options/settings that need to be stored in a persistent manner for different sessions of Napari (opening, closing).

## Pitch

JSON Schema is language agnostic and a well defined standard that can be used to define settings and properties.

https://json-schema.org/understanding-json-schema/

We could use Python specific libraries that handle many things, but using a standard well used and stable format grants us more flexibility and the ability to use different libraries on different languages depending on the needs of the current frontend, and future ones.

### Omegaconf

From @jni 
>I just came across omegaconf. Not that we need any more choices for napari config management, but I think part of the reason we haven't got this done is that nothing felt "satisfying", and OmegaConf kinda does! See the "creating" part of the user guide, lots of nice stuff in there.

>It is a young project, which might be reason enough to avoid it, but I still thought it was worth considering.

## Additional context

This is how it looks (taken from JLab)

```json
{
  "jupyter.lab.setting-icon-label": "Sidebar",
  "title": "Sidebar",
  "description": "Sidebar layout settings.",
  "properties": {
    "overrides": {
      "type": "object",
      "title": "Overrides",
      "default": {},
      "description": "Overrides for where to show sidebar items\ne.g., {\"tab-manager\": \"right\"}",
      "properties": {},
      "additionalProperties": {
        "type": "string",
        "enum": ["left", "right"]
      }
    }
  },
  "additionalProperties": false,
  "type": "object"
}
```

```json
{
  "title": "Application ",
  "description": "Main JupyterLab application settings.",
  "jupyter.lab.setting-icon-label": "Application",
  "jupyter.lab.shortcuts": [
    {
      "command": "application:activate-next-tab",
      "keys": ["Ctrl Shift ]"],
      "selector": "body"
    },
    {
      "command": "application:activate-previous-tab",
      "keys": ["Ctrl Shift ["],
      "selector": "body"
    },
    {
      "command": "application:activate-next-tab-bar",
      "keys": ["Ctrl Shift ."],
      "selector": "body"
    },
    {
      "command": "application:activate-previous-tab-bar",
      "keys": ["Ctrl Shift ,"],
      "selector": "body"
    },
    {
      "command": "application:close",
      "keys": ["Alt W"],
      "selector": ".jp-Activity"
    },
    {
      "command": "application:toggle-mode",
      "keys": ["Accel Shift D"],
      "selector": "body"
    },
    {
      "command": "application:toggle-left-area",
      "keys": ["Accel B"],
      "selector": "body"
    },
    {
      "command": "application:toggle-right-area",
      "keys": [""],
      "selector": "body"
    },
    {
      "command": "application:toggle-presentation-mode",
      "keys": [""],
      "selector": "body"
    }
  ],
  "properties": {},
  "additionalProperties": false,
  "type": "object"
}
```

**Comment by sofroniewn** [comment]
We have gone with this approach using #2212 and #2211
