### ISSUE TITLE
Persistence format for settings and configuration

### ISSUE THREAD

**Issue by goanpeca** [napari/napari#2176]
## 🚀 Feature

Splitting from https://github.com/napari/napari/issues/992

## Motivation

We need some human readable format to store settings for different configuration options in the napari core application and plugins.

## Pitch

We need this to be human readable, and hopefully clear and concise

## Alternatives

- YAML
- JSON
- TOML
- INI (no, but included for completeness)

## Additional context

How to handle plugin "state" for a broad definition of state this could include how the UI looks and Qt offers ways of saving./loading this information with a hex string. 

What about `state`. of variables on plugins? This might require a separate binary format, depending on the plugin?

**Comment by sofroniewn** [comment]
I think we can close this now that #2212 has merged and we went with YAML, right @goanpeca?

**Comment by goanpeca** [comment]
Agreed! Closing
