### ISSUE TITLE
Napari plugin does not show in add docker widget menu until closed and reopen

### ISSUE THREAD

**Issue by liu-ziyang** [napari/napari#2178]
## 🐛 Bug

Napari plugin does not show in add docker widget menu until closed and reopen

## To Reproduce

1. open napari and install napari-demo plugin
2. open `add dock widget` menu and there is nothing immediately after installation
3. close and reopen napari, napari-demo should appear in `add docker widget` menu now

## Expected behavior

`add dock widget` should discover the plugin after installation without reopening

## Environment

running against latest master: https://github.com/napari/napari/commit/e61fb64c85e1dfd7213a78f7b420c9fc8e071cbe

the plugin does not work for 0.4.3 release due to API update in latest master version

**Comment by sofroniewn** [comment]
Note this is the case when installing directly from the "Install Packages" dialog - agreed it would be nice to discover plugin right after install without restart. We could also temporarily add a message that said something like "restart to see plugin"

**Comment by tlambert03** [comment]
easy to do without restart, thanks for noting it
