### ISSUE TITLE
Add a restart option on the file menu

### ISSUE THREAD

**Issue by goanpeca** [napari/napari#2181]
## 🚀 Feature

Add a restart method to the main application and add it to the corresponding menu.

## Motivation

Some configuration options will need a restart so we need to provide a a way to restart

## Pitch

N.A.

## Alternatives

N.A.

## Additional context

This is part of the configuration/settings work.

**Comment by sofroniewn** [comment]
+1 to this functionality, thanks for making an issue to track!!
