### ISSUE TITLE
"Extended Summary" is not a section header in numpydoc.

### ISSUE THREAD

**Issue by Carreau** [napari/napari#2192]
## 📚 Documentation

There seem to be a few use case of the "Extended Summary" header in napari:

```
$ rg 'Extended Summ'| wc -l
      10
```

This is likely a miss-interpretation of the numpydoc format. 

what is called the "Extended summary" is the multiline section that directly follows the one-line summary.

```
"""
This is the summary

This is the "Extended Summary which is directly after the 
summary but can be more than one line it does not have a section delimitation
"""
```

Using the header "Extended Summary" does not fail but numpydoc get confused on so does sphinx that start to merge the values of "Extended Summary" with parameters.

<img width="691" alt="Screen Shot 2021-01-28 at 22 18 23" src="https://user-images.githubusercontent.com/335567/106239304-3ae61a00-61b7-11eb-949e-287e5fcba5cc.png">

From a quick look, in a few cases what is meant is likely the "Attributes" section.

**Comment by sofroniewn** [comment]
Ok, thanks for flagging - we can gradually work to remove them.

> From a quick look, in a few cases what is meant is likely the "Attributes" section.

I think most of these are "private" attributes and methods, and we took guidance from https://numpydoc.readthedocs.io/en/latest/format.html#class-docstring 

```
If it is necessary to explain a private method (use with care!),
it can be referred to in the Extended Summary or the Notes section.
Do not list private methods in the methods section.
```

It's not quite clear to me how to proceed. Maybe we just shouldn't include doc strings for these private methods/ attributes? What do you recommend @Carreau?

**Comment by Carreau** [comment]
I have no particular preferences; I'm used to the "responsible user" that know that if it start with a `_` it should be used with care. It can be a case-by-case basis, but I'm tempted to think that `Notes` is likely to be more toward the end and will not be prominently visible for users.

Nothing prevent us also from suggesting changes to numpydoc; for example there is no guidance on how to document `*args` and `**kwargs`... should the name in the `Parameters` section have leading `*`, `**` or not ? we can also add a note to numpydoc format that "Extended Summary" is not a valid section name...

**Comment by sofroniewn** [comment]
If there were to be a change to numpydoc one option would be a new section like `Private Attributes`, where people could then include them if they wanted too when writing code and doc renderers could then decide to show them or not depending on some setting.

Alternatively, maybe they can all go inside `Attributes`, but just be listed at the bottom of that section and a doc renderer could then decide to show them or not depending on some setting, I'm not sure if that's possible now or not, but that might be the cleanest.

@jni / @tlambert03 do you have any preferences here? We could also just drop them too, I suspect many have not been kept up to date and aren't that important.

**Comment by tlambert03** [comment]
> @jni / @tlambert03 do you have any preferences here? We could also just drop them too, I suspect many have not been kept up to date and aren't that important.

I'd just drop them, and probably put a `# comment` just above the private method wherever it is created.  I don't think they need to be in the class docstring.

**Comment by sofroniewn** [comment]
> I'd just drop them, and probably put a # comment just above the private method wherever it is created. I don't think they need to be in the class docstring.

Works for me!
