### ISSUE TITLE
Allow reader_function to return empty layer list

### ISSUE THREAD

**Issue by jwindhager** [napari/napari#2201]
## 🚀 Feature
When `reader_function` returns an empty layer list, this should be respected as successful read and prevent further reader plugins from being called. Only when the function returns `None` or throws an exception, the read operation should be considered failed and further read functions should be tried.

## Motivation

In some cases, the user wants to open a file without immediately loading the layers. For example, plugins might provide an intermediate dock widget for selecting the images contained in an archive file to be shown.

## Pitch

Consider `[]` as a valid return value from a reader function provided by `napari_get_reader`

**Comment by sofroniewn** [comment]
> When reader_function returns an empty layer list, this should be respected as successful read and prevent further reader plugins from being called. Only when the function returns None or throws an exception, the read operation should be considered failed and further read functions should be tried.

If we enabled `[]` to be a valid return without supporting something like #2202 then you would just see nothing added to the layer list, which might be undesired if another plugin could do the reading, though might also be the most appropriate thing.

Maybe we wait to see how the discussion in #2202 evolves until we decide what to do in this case

**Comment by jwindhager** [comment]
Hi @sofroniewn,

thanks for considering this. As #2202 may take some time to get resolved, would it be possible to, in the meantime, consider this request? In my opinion, differentiating between `None` and `[]` would be a favorable approach in any case, as some files just may be in empty but readable (for whatever reason - e.g. aborted image acquisitions), in which case the corresponding plugin needs a way of signaling that to napari.

**Comment by jni** [comment]
Maybe the plugin returns the string "This page intentionally left blank"? =P

@sofroniewn I think as long as we document *clearly and prominently* that None means "I can't read this" and [] means "I can read this, and I'm telling you, there's nothing there", I don't see a huge issue with supporting this?

Another possibility is to enforce that empty arrays should come with a layer type. ie we don't allow [] but we do allow `([], 'Image')`?

**Comment by sofroniewn** [comment]
Ok yes, this all sounds very reasonable. @jwindhager would you be willing to submit a PR to make this change, including updating the doc string - we can help you through the process!!
