### ISSUE TITLE
Plugin discovery appears to be broken

### ISSUE THREAD

**Issue by jni** [napari/napari#2207]
## 🐛 Bug

If I go to "Plugins > Install/Uninstall packages", I now see an empty list, and no progress widget:

<img width="1192" alt="Screen Shot 2021-02-04 at 3 15 02 pm" src="https://user-images.githubusercontent.com/492549/106844231-1977b780-66fc-11eb-812b-b3d581d255f9.png">

## Environment

This is using the latest nightly bundle build, but I also experienced it on master.

napari: 0.4.5.dev9+g79ab358
Platform: macOS-10.15.7-x86_64-i386-64bit
System: MacOS 10.15.7
Python: 3.8.7 (default, Jan 2 2021, 04:16:43) [Clang 11.0.0 (clang-1100.0.33.17)]
Qt: 5.15.2
PySide2: 5.15.2
NumPy: 1.19.3
SciPy: 1.6.0
Dask: 2021.01.1
VisPy: 0.6.6

OpenGL:
- GL version: 2.1 ATI-3.10.19
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen #1: resolution 2048x1152, scale 2.0
- screen #2: resolution 1536x960, scale 2.0

Plugins:
- svg: 0.1.4

**Comment by jni** [comment]
Hmm, I take it back, I can't reproduce on master now... =\ But the problem in the bundle persists. 🤔

**Comment by liu-ziyang** [comment]
I can confirm I saw this before, and the reason was that the ssl certificate not valid when napari tries to access the pypi, this is more of a error message not showing up anywhere but the console

**Comment by jni** [comment]
> the reason was that the ssl certificate not valid when napari tries to access the pypi

@ziyangczi I suspected I was missing an error message, but what's the fix?

**Comment by liu-ziyang** [comment]
the error message is something similar to `SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed`, probably not exact, the solution I had is overwriting the SSL certificate in the run environment with the one from certifi: 
see https://stackoverflow.com/questions/44649449/brew-installation-of-python-3-6-1-ssl-certificate-verify-failed-certificate/44649450#44649450

```
find out default cafile:
python -c 'import ssl; print(ssl.get_default_verify_paths().openssl_cafile)'
/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/etc/ssl/cert.pem

find out ca file of certifi
python -c 'import certifi; print(certifi.where())'
'/usr/local/lib/python3.7/site-packages/certifi/cacert.pem'

copy to
sudo cp /usr/local/lib/python3.7/site-packages/certifi/cacert.pem
/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/etc/ssl/certs/cert.pem
```
