### ISSUE TITLE
Canvas resizing trouble when increasing window size.

### ISSUE THREAD

**Issue by royerloic** [napari/napari#221]
## 🐛 Bug

Canvas resizing trouble when increasing window size.

## To Reproduce

1. start add_image example
2. make window bigger
3. Canvas is not getting larger at the bottom (see screenshot below) 

## Expected behavior

Canvas should scale to occupy most of the viewer,
no blank space should grow as the  window is made bigger:

![image](https://user-images.githubusercontent.com/1870994/56461424-adca2c00-6367-11e9-915c-34459a2d65d4.png)

## Environment

 - napari Version (e.g., 1.0): dimslider PR
 - OS (e.g., Linux): OSX
 - Python version: 3.7
 - Any other relevant information:

## Additional context

N/A

**Comment by sofroniewn** [comment]
Ah ok - this is on the `dimslider` PR - not on master - if you find a bug on a PR during PR review can you post it in your review instead of making on issue

**Comment by sofroniewn** [comment]
I have fixed this on the dims PR #171 by directly setting the `QSizePolicy` in the vertical direction to be `Fixed` and pushed a new commit to that PR. I am closing this issue, but further discussion can take place on the PR before it is merged
