### ISSUE TITLE
Inconsist size of Point when rotate in 3d

### ISSUE THREAD

**Issue by Czaki** [napari/napari#2213]
## 🐛 Bug

When having set unequal spacing in 3d (70x70x210) points size change when rotate 

## To Reproduce

![napari-problem](https://user-images.githubusercontent.com/3826210/106953273-79895080-6732-11eb-81ff-1751e88b02c2.gif)

1. load data
2. set a higher scale in z-axis
3. switch to 3d view
4. rotate

## Expected behavior
Same optical size o points 

## Environment

napari: 0.4.4
Platform: Linux-5.8.0-41-generic-x86_64-with-debian-bullseye-sid
System: Ubuntu 20.10
Python: 3.7.7 (default, Dec 5 2020, 23:09:00) [GCC 10.2.0]
Qt: 5.15.2
PyQt5: 5.15.2
NumPy: 1.20.0
SciPy: 1.6.0
Dask: 2021.01.1
VisPy: 0.6.6

OpenGL:
- GL version: 4.6.0 NVIDIA 460.32.03
- MAX_TEXTURE_SIZE: 32768

Screens:
- screen 1: resolution 2560x1440, scale 1.0
- screen 2: resolution 1920x1080, scale 1.0
- screen 3: resolution 1920x1080, scale 1.0

Plugins:
- Copy labels: 0.12.7.dev27+gbbaf425.d20210204
- PartSeg Analysis project: 0.12.7.dev27+gbbaf425.d20210204
- PartSeg Image: 0.12.7.dev27+gbbaf425.d20210204
- PartSeg Mask project save: 0.12.7.dev27+gbbaf425.d20210204
- PartSeg Mask project: 0.12.7.dev27+gbbaf425.d20210204
- PartSeg Masked Tiff: 0.12.7.dev27+gbbaf425.d20210204
- svg: 0.1.4

 - Please copy and paste the information at napari info option in help menubar here:

 - Any other relevant information:

**Comment by sofroniewn** [comment]
Hi @Czaki, sorry about that!! We should definitely fix this. It seems like something unexpected is happening with the anisotropic scaling!!

**Comment by Czaki** [comment]
Could you point part of code which may be responsible for this?

**Comment by sofroniewn** [comment]
@Czaki can you give me an example to reproduce this. I tried the following and everything worked fine. Not sure what's going on/ what I missed

```python
import napari
import numpy as np


with napari.gui_qt():
    v = napari.view_image(np.random.random((10, 20, 20)), scale=(5, 3, 1))
    points = np.array([[10, 10, 0], [8, 12, 5], [4, 11, 2]])
    v.add_points(points, scale=(5, 3, 1))
```

![3D_anisotropic_points](https://user-images.githubusercontent.com/6531703/107107949-40f87e00-67e9-11eb-85de-6f540e792c4e.gif)

**Comment by Czaki** [comment]
This is my view on the result of your code:
![napari-problem2](https://user-images.githubusercontent.com/3826210/107116840-5bc50400-6876-11eb-8462-e1c12a07e0d2.gif)

Here napari information (maybe some differences in libraries)?

napari: 0.4.5.dev16+g9256046e.d20210206
Platform: Linux-5.8.0-41-generic-x86_64-with-glibc2.2.5
System: Ubuntu 20.10
Python: 3.8.3 (default, Dec 6 2020, 00:47:20) [GCC 10.2.0]
Qt: 5.15.2
PyQt5: 5.15.2
NumPy: 1.19.0
SciPy: 1.5.1
Dask: 2.1.0
VisPy: 0.6.5

OpenGL:
- GL version: 4.6.0 NVIDIA 460.32.03
- MAX_TEXTURE_SIZE: 32768

Screens:
- screen 1: resolution 2560x1440, scale 1.0
- screen 2: resolution 1920x1080, scale 1.0
- screen 3: resolution 1920x1080, scale 1.0

Plugins:
- brainreg: 0.2.3
- brainreg_standard: 0.2.3
- svg: 0.1.4

**Comment by jni** [comment]
I also had this issue locally. It's more dramatic with scale=(5, 1, 1) btw. My napari-info:

```
napari: 0.4.5.dev16+g9256046e.d20210206
Platform: macOS-10.15.7-x86_64-i386-64bit
System: MacOS 10.15.7
Python: 3.8.2 (default, Mar 26 2020, 10:43:30) [Clang 4.0.1 (tags/RELEASE_401/final)]
Qt: 5.14.2
PyQt5: 5.14.2
NumPy: 1.19.2
SciPy: 1.5.1
Dask: 2021.01.1
VisPy: 0.6.4

OpenGL:
- GL version: 2.1 ATI-3.10.19
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1536x960, scale 2.0

Plugins:
- affinder: 0.1.dev16+g189efd8
- animation: 0.1.dev78+g5716ec8
- btrack-reader: 0.1.0
- napari-sentinel-zip: 0.2.2
- nd2-reader: 0.0.5
- ome_zarr: 0.0.18.dev0
- s3zarr: 0.0.2
- svg: 0.1.4
- tracks: 0.0.2
```

**Comment by jni** [comment]
I presumed it was a vispy thing...

**Comment by sofroniewn** [comment]
> I presumed it was a vispy thing...

Ok wow weird things going on. I fixed something like this in vispy a while back https://github.com/vispy/vispy/pull/1702 (with isotropic scale), but it seems like I might not have extend support to anisotropic.

I'm not quite sure why my local version is fine. I can test in clean environment etc. Maybe I'm on a vispy branch ...

**Comment by Czaki** [comment]
@sofroniewn Did you test on another vispy version?

How `scale` is handled by vispy layers?

**Comment by JoOkuma** [comment]
Have you guys figures this out? I noticed this problem too.

I think the issue is that every point has the same size and when they lie at different depths on the 3D viewer is resizing them according to the depth while keeping them at the same size. I have the impression, that this isn't an issue when you rotate your points while keeping them (more or less) on a plane orthogonal to the camera.

Since the points' size is a parameter shouldn't it be fixed? However, we might lose the notion of depth.

**Comment by jni** [comment]
I don't think it's to do with depth, but rather, with how vispy computes "effective" size given anisotropic scaling. I think to get this fixed we should try to come up with a vispy-only demonstration and raise the issue there.

**Comment by sofroniewn** [comment]
Yeah, i still don't know how to reproduce locally - does it depend on how "zoomed" in one is? funny things happen when very zoomed in maybe?

**Comment by Czaki** [comment]
@sofroniewn Maybe a short meeting in next week (in this I do not have time) with comparing of environments?

**Comment by DragaDoncila** [comment]
Hey folks, I also just reproduced this on main too, on a "just about brand new" environment.

```
napari: 0.4.16rc2.dev153+g4b809a1a
Platform: Linux-5.13.0-51-generic-x86_64-with-glibc2.31
System: Ubuntu 20.04.4 LTS
Python: 3.9.12 (main, Jun  1 2022, 11:38:51)  [GCC 7.5.0]
Qt: 5.15.2
PyQt5: 5.15.7
NumPy: 1.22.4
SciPy: 1.8.1
Dask: 2022.6.1
VisPy: 0.10.0

OpenGL:
  - GL version:  4.6.0 NVIDIA 510.73.05
  - MAX_TEXTURE_SIZE: 32768

Screens:
  - screen 1: resolution 2560x1600, scale 1.0

Plugins:
  - console: 0.0.4
  - napari-ome-zarr: 0.5.1
  - napari-svg: 0.1.6

```

Does anyone have time to look into this?

**Comment by sofroniewn** [comment]
Maybe @brisvag could take a look as it might be vispy related?

**Comment by brisvag** [comment]
This seems to be quite deep... I took a look, and I *think* it's something caused by how the transform chain in vispy combines with the size determination inside the vertex shader in `Markers`.

**Comment by brisvag** [comment]
Opened vispy/vispy#2357 to track down the problem, with a vispy-only reproducible example.

**Comment by brisvag** [comment]
Found the root of the problem and a fix! vispy/vispy#2359

**Comment by brisvag** [comment]
I still can't explain why @sofroniewn couldn't reproduce, but hopefully this doesn't break on *his* system xD

**Comment by Czaki** [comment]
Would this solution also solve the problem of our vectors whose thickness changes similarly?

**Comment by brisvag** [comment]
I doubt it, the vectors use are a completely different, with meshes. Can you point me to the issue?

**Comment by Czaki** [comment]
There is no issue as I'm not sure if it is a real issue, but A you could observe on attached image the thickness is different along z-axis, and the scale is array([  1.        , 210.        ,  77.52248562,  77.52248562])
![Zrzut ekranu z 2022-07-20 19-09-13](https://user-images.githubusercontent.com/3826210/180042003-ede99b5e-5a08-400e-b792-2f0fa235cef1.png)
 

should I open a separate issue for this?

**Comment by brisvag** [comment]
Ah, I see... Yes, this is a different thing. I guess we need to use the scale when generating the meshes.
