### ISSUE TITLE
Redundant Symbols in markers layer

### ISSUE THREAD

**Issue by royerloic** [napari/napari#222]
## 🐛 Bug

Some symbols in the markers layer are just the sam, or at least I can't make the difference. For example: '|' and 'vbar' appear to be the same, other instances: 'o' and 'disc'.

![image](https://user-images.githubusercontent.com/1870994/56461461-5f695d00-6368-11e9-9240-98ebfb5de386.png)

## To Reproduce

N/A

## Expected behavior

Cleaner list of symbols without duplicates.

## Environment

 - napari Version (e.g., 1.0): latest dimslider PR
 - OS (e.g., Linux): OSX
 - Python version: 3.7
 - Any other relevant information:

## Additional context

N/A

**Comment by sofroniewn** [comment]
yup - we should clean that up. similarly we should clean up all the colors and colormaps. maybe would be good to have config files or `_constants` which list acceptable symbols, colors, and colormaps

**Comment by kne42** [comment]
IMO in an object-oriented approach (which napari is unfortunately forced into due to usage of Qt), it's best to just place constants as attributes of their corresponding classes.

**Comment by royerloic** [comment]
I agree with Kira, it is good practice to keep related things together...
Enums that are related to a class or method should be defined close to that class
or function -- possibly in the same file. Unless, the enum (or constant) is not solely 
attached to one class but is instead something used within some package. 
In that case, it belongs in the package. 
But not in some root package where all constants get dumped.

In general, keep things that are related together, and avoid pulling things far away from
the only code that uses them... One 'test' of the design is: can you just copy paste the package
and use it in another project? Is the package self-contained or is there 'other stuff' that will get
orphaned?

In some cases it can make sense to 'list' things in one place,
but only if the elements of that list (for example enums throughout Napari) have a strong 
connection between them (same type, etc...) or you _really_ need them close to each other. 
Otherwise, you are just making it harder to understand the structure of the project long term...
