### ISSUE TITLE
Newly added point in `Add` mode is selected but not editable

### ISSUE THREAD

**Issue by aseedb** [napari/napari#2234]
## 🐛 Bug

Hi,
Once a point has been drawn I would like to resize it immediately. Currently if I move the point size slider right after adding a new point, point size remains unchanged. I need to use the selection too, and select it and afterwards I can edit its size. So apparently right after creating a new point, the point is not selected, although it is highlighted as if it was selected. Would it be possible to make the point directly size-editable, without having first to select it?
Thanks
Benoit

## To Reproduce

1. Add a point in the graphical user interface.
2. Slide the point size slider --> the point does not get resized
3. Select the newly added point.
4. Slide the point size slider --> the point gets resized

## Expected behavior

The point should get resized at step 2 (in "To reproduce")

## Environment

 - Please copy and paste the information at napari info option in help menubar here:

napari: 0.4.3
Platform: macOS-11.2-x86_64-i386-64bit
Python: 3.9.1 | packaged by conda-forge | (default, Jan 26 2021, 01:32:59) [Clang 11.0.1 ]
Qt: 5.9.7
PyQt5: 5.9.2
NumPy: 1.19.5
SciPy: 1.6.0
Dask: 2021.01.1
VisPy: 0.6.6

OpenGL:
- GL version: 2.1 INTEL-16.1.10
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen #1: resolution 2560x1440, scale 2.0
- screen #2: resolution 1440x900, scale 2.0

Plugins:
- napari_plugin_engine: 0.1.9
- svg: 0.1.4

**Comment by sofroniewn** [comment]
> the point is not selected, although it is highlighted as if it was selected.

This in particular sounds like a bug - if it is highlighted it should be selected. It seems reasonable too that the last added point should be selected by default. Maybe there was a regression somewhere. We should look into it

**Comment by DragaDoncila** [comment]
This is indeed a bug, and it does not just affect point size, but also other properties. The point is correctly selected, and I think we all agree that its selection is desired behavior. This means we need to explicitly update the `current_*` setters to remove the check that we are in `add` mode. 

Tagging this for SciPy sprint this weekend!

**Comment by jamesyan-git** [comment]
I will be working on this today at the napari sprint :)
