### ISSUE TITLE
Less flashy design for shapes in shapes layer

### ISSUE THREAD

**Issue by royerloic** [napari/napari#224]
## 🚀 Feature

Maybe we could make the shapes rendering in Shapes layer a bit less flashy and sleaker.
A few ideas:

- make the lines a bit thiner
- choose less flashy colors (blue and orange defaults...)
- at least make the shapes more transparent

## Motivation

Shapes now have good defaults for development, 
but when it comes to actual usage with real images,
it seems that the shape defaults are now too strong
compared to the data. Having softer colors, more transparency,
and thiner lines could make it more about the data and
annotation, and make it look less than a clone of Keynote or
Illustrator...  

![image](https://user-images.githubusercontent.com/1870994/56461641-0c44d980-636b-11e9-855e-00537b3beb3e.png)

**Comment by sofroniewn** [comment]
These aren't actually the defaults, these are just the colors used in the `add_shapes.py` example. 

Happy to change both the example and the defaults though (which are as follows `edge_width`=1, `edge_color`='black', `face_color`='white', `opacity`=0.7).

In general more "scientific" examples would be a good thing I think

**Comment by AhmetCanSolak** [comment]
@royerloic i agree less flashy shapes are preferable. For transparency im not sure. Current transparency also seems okay at first sight. maybe we can come up with some basic adaptive approach? What do you think?

**Comment by sofroniewn** [comment]
As noted above this example doesn't actually show the defaults, which are less flashy. We've now got more examples and tutorials on how to change this stuff here - http://napari.org/tutorials/shapes.html

We can always improve those examples / make them more scientific as we go
