### ISSUE TITLE
Incorrect color in labels sidebar

### ISSUE THREAD

**Issue by ianhi** [napari/napari#2240]
## 🐛 Bug

When working in a labels layer for some colors when I use the eyedropper the color in the side bar is not correct:

![Peek 2021-02-09 16-48](https://user-images.githubusercontent.com/10111092/107433061-d734e880-6af6-11eb-8215-6a37ad7952b0.gif)

## To Reproduce

I haven't figured out a minimal example but I am definitely running into this semi regularly
## Expected behavior
The color in the side bar is the same as in viewer.

## Environment
napari: 0.4.4
Platform: Linux-5.8.0-7630-generic-x86_64-with-glibc2.10
System: Pop!_OS 20.04 LTS
Python: 3.8.5 (default, Sep 4 2020, 07:30:14) [GCC 7.3.0]
Qt: 5.12.9
PyQt5: 5.12.3
NumPy: 1.19.5
SciPy: 1.6.0
Dask: 2021.02.0
VisPy: 0.6.6

OpenGL:
- GL version: 4.6 (Compatibility Profile) Mesa 20.2.6
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen #1: resolution 1920x1080, scale 1.0
- screen #2: resolution 1920x1200, scale 1.0

Plugins:
- svg: 0.1.4

**Comment by sofroniewn** [comment]
Uh oh! That's not so good. The data to get to a color goes through two different paths to appear on the screen - one is via the CPU and then Qt for the color square on the left, the other is via the GPU and vispy for the label in the canvas. The nature of the colormap for labels is that small differences in input can lead to large differences in color space, which maybe makes the whole system more sensitive for rounding errors/ artifacts.

> I haven't figured out a minimal example but I am definitely running into this semi regularly

Yeah, I think I've seen it too. It would be great to have a minimal example

**Comment by perlman** [comment]
Here's some code to reproduce:
```python
import napari
import numpy as np

viewer = napari.Viewer()
data = np.array([[24, 24],[ 24, 24]])

viewer.add_labels(data, name='labels')
viewer.layers[0].selected_label = 24

napari.run()
```

Notably, both the color picker color and thumbnail disagree with the label rendering.

I suspect this is similar to #4935, but with the random color side of the code.

**Comment by psobolewskiPhD** [comment]
The snippet from above does not result in any disagreement between the the thumbnail, screen, and picker:
<img width="1269" alt="image" src="https://github.com/napari/napari/assets/76622105/0fd29279-6405-49cb-af8b-2128011297a1">

Going to close this as solved. If it pops ups again with a new reproducer we can reopen or make a new issue.
