### ISSUE TITLE
Support left/right keys to move slider pointer

### ISSUE THREAD

**Issue by royerloic** [napari/napari#227]
## 🚀 Feature

Would be good to be able to move the currently focused dim slider with left/right keybindings by one step. Pressing <Shift> would make it 10 steps or so. 

## Motivation

Sometimes one wants to scroll back and forth between two or several slices in a reproducible manner. This is easier by pressing keys.

**Comment by sofroniewn** [comment]
Once we merge #171 and start using our custom `rangeslider` we have to implement this ourselves (it is currently supported on master which uses the built in sliders from PyQt)

**Comment by royerloic** [comment]
I encountered this issue again today while browsing a dataset, 
turns out to be quite useful in practice as we know.
Just adding some weight to this issue here :-)

**Comment by sofroniewn** [comment]
fixed by #472
