### ISSUE TITLE
Docs build broken

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#2272]
## 🐛 Bug

Looks like our docs build is broken, which could be because of the new release of jupyterbook, I'm not sure.

https://github.com/napari/napari/runs/1897828746

cc @kne42 @tlambert03

**Comment by kne42** [comment]
not really sure what's causing this but ill check it out

**Comment by kne42** [comment]
ran it on my machine and it worked. re-ran on CI and it [appears to have resolved itself](https://github.com/napari/napari/runs/1921220803)

**Comment by sofroniewn** [comment]
> ran it on my machine and it worked. re-ran on CI and it appears to have resolved itself

ok nice, maybe they pushed a bug fix! thanks for checking it out :-)
