### ISSUE TITLE
Fix obselete roadmap links in the README

### ISSUE THREAD

**Issue by GenevieveBuckley** [napari/napari#2277]
## 📚 Documentation

We want to have a link to the napari project roadmap in the README, but the filenames keep changing as new napari releases come out and the link becomes obselete/broken.

Originally discussed here: https://github.com/napari/napari/pull/2275#discussion_r575982386

Proposal:
* We use `roadmap_latest` as the filename for whatever the current roadmap is, and link to that in the README.
* When a napari release comes out & a new roadmap is needed, we copy-paste the contents of `roadmap_latest` into an archive named `roadmap_0_4` (or whatever the version number was at that time).

**Comment by sofroniewn** [comment]
Thanks for pulling this out for dedicated discussion @GenevieveBuckley. Looking at our current organization of roadmaps, we'll probably want to move them off the top level of `Developer Resources` too, as we'll just be accumulating many links here for all the different versions

![image](https://user-images.githubusercontent.com/6531703/108010851-b3701780-6fba-11eb-82b5-77f6486c3e0b.png)

We could have this just click to a generic roadmaps page that then had it's own table of contents, and included `0.3`, `0.3 retrospective`, and `0.4`. We could also move some of the "boiler plate" like wording out of the `0.3` and `0.4` roadmaps where it is duplicated like the "about-this-document" section, see https://napari.org/docs/dev/developers/roadmap_0_4.html#about-this-document

We could then link from the main readme to this stable roadmaps index page and not have to worry about updating it anymore. People could then figure out which roadmap they wanted to look at.

One thought is if the roadmaps are so important they should live at the top level alongside things like `Guides`/ `Developer Resources` etc. this would work nicely from a navigation standpoint as we remove one level of nesting, but not sure how critical promoting the roadmaps is like that? I'd be fine with it. `Release Notes` is already at that level, and I see the roadmaps as somewhat similar (maybe slightly less critical).

Thoughts @kne42 @liaprins-czi @jni @GenevieveBuckley ?

**Comment by GenevieveBuckley** [comment]
I'm happy with whatever is easiest to maintain, that is not likely to cause us more problems with broken links

**Comment by liaprins-czi** [comment]
Would it be possible / make sense for the previous release's roadmaps to be accessed via the doc version dropdown? Or am I confusing the two concepts of doc version and releases (I had been thinking they go together but could be wrong)?

Then There could still be one single roadmaps page living within the Community section, but it could be changed to view the older versions of it via the dropdown, like can work for other pages with older versions.

**Comment by GenevieveBuckley** [comment]
> Then There could still be one single roadmaps page living within the Community section, but it could be changed to view the older versions of it via the dropdown, like can work for other pages with older versions.

Will that dropdown auto-populate @liaprins-czi? I'd be happy with that, as long as someone doesn't need to remember to update things.

**Comment by sofroniewn** [comment]
> Would it be possible / make sense for the previous release's roadmaps to be accessed via the doc version dropdown? Or am I confusing the two concepts of doc version and releases (I had been thinking they go together but could be wrong)?

They are actually slightly independent, in the sense that i could update a previous releases roadmap in a new release, but generally i don't expect that to happen.

I think trying a top level "roadmaps" section at the same level as "release notes" might actually work nicely. Thoughts @jni?

I think that will be most transparent to users and developers @GenevieveBuckley and should be easiest to maintain

**Comment by liaprins-czi** [comment]
FYI, I have just updated the site map to show Roadmaps now as its own top-level section within the nav.

Sitemap on LucidChart:
https://lucid.app/lucidchart/192f0dbb-99dc-43e8-b9fb-d023be464658/edit?page=0_0#?folder_id=home&browser=icon

Same exact sitemap on Figma:
https://www.figma.com/file/CCKg8nO8vVcYVIvkVJbW4g/Sitemap?node-id=566%3A2

**Comment by sofroniewn** [comment]
Thanks @liaprins-czi! I think that looks good to me!!

**Comment by sofroniewn** [comment]
We can now have a https://napari.org/roadmaps/index.html that we can link too if needed
