### ISSUE TITLE
Gallery missing images/titles

### ISSUE THREAD

**Issue by ianhi** [napari/napari#2283]
## 📚 Documentation

The images for https://napari.org/tutorials/gallery.html seem to be broken:
![image](https://user-images.githubusercontent.com/10111092/108245152-f26aae00-711d-11eb-9af0-94d63065599a.png)

**Comment by sofroniewn** [comment]
I think that grid may now have been dropped (it was always slow to load!). I now see 

![image](https://user-images.githubusercontent.com/6531703/108315724-b7de3100-7170-11eb-820f-fe8752191c0b.png)

Can you confirm that's what you see now too @ianhi and then we can close this issue?

**Comment by ianhi** [comment]
Yup fixed for me now!
