### ISSUE TITLE
Bundled app won't open on Mac

### ISSUE THREAD

**Issue by liaprins-czi** [napari/napari#2287]
## 🐛 Bug

I have followed the [instructions for installing the napari bundled app on a Mac](https://napari.org/tutorials/fundamentals/installation#installing-as-a-bundled-app) exactly, but unfortunately it does not open for me.

## To Reproduce

Specifically, after I update the Mac system preferences to allow napari to open, when I next go to napari within my Applications folder, and double-click it or right-click and select "Open", nothing happens. I have tried deleting it from Applications and re-installing following the same exact process again as described in the docs, but it doesn't open again.

## Expected behavior

Bundled app installation instructions should enable napari to open.

## Environment

I cannot open napari so I cannot access the napari information from its menu. However, here is my Mac OS version: **Mac OS Big Sur, Version 11.2.1** (running on MacBook Pro 13-inch, 2019, Four Thunderbolt 3 ports)

## Additional context

Furthermore, when i try to install napari via the pip method described on the documentation home page, it doesn't install either, and it seems to not recognize any conda commands. This is strange because it used to work for me perfectly. I have also deleted old instance and retried the pip method but get the same errors. Maybe Conda was deleted from my system somehow. I will try looking into installing Conda and retrying the pip method, but ideally the bundled app method should work.

**Comment by tlambert03** [comment]
sorry, big sur broke a lot of things (#1393) and the bundle isn't working yet on big sur. 

However, as of a few weeks now, it _should_ be working now with the standard install via conda (but note, you will definitely need to use python 3.9):
```python
conda create -y -n napari-env -c conda-forge python=3.9
conda activate napari-env
pip install 'napari[all]'
```

if conda is not working at all for you, let me know what errors you're getting

**Comment by liaprins-czi** [comment]
Okay thanks for your help @tlambert03 ! I have just installed the latest version of Python now (3.9.1), and tried running the command you list above, but after the first command I get the error: `-bash: conda: command not found`

So am wondering if this means conda is not found / not installed anymore...?

**Comment by tlambert03** [comment]
yep looks like it.  
two things to check: if you installed [miniconda](https://docs.conda.io/en/latest/miniconda.html) (or anaconda) via the "normal" install, then you should have a `miniconda3` (or anaconda) folder in your home directory.  If you _don't_, then just reinstall.  
If you _do_ have a folder, then your "conda init" may be broken (you can check for something like `# >>> conda initialize >>>` in your ~/.bash_profile file).  To "fix" that, try this:
```sh
# assuming you have miniconda3 in your home directory
source ~/miniconda3/bin/activate
conda init
```

**Comment by tlambert03** [comment]
> I have just installed the latest version of Python now (3.9.1)

this actually raises another question:  did you install python directly via python.org?  or were you trying to install python using the `conda create` command above and that's when you ran into issues?

**Comment by liaprins-czi** [comment]
I updated/installed Python via [Python.org](https://www.python.org/downloads/mac-osx/) and right after I did I checked the version again in Terminal with `python --version` and it said 3.9.1 (before it was 3.8.2 I think). So I am pretty sure the Python version part is fine.

Now am looking into the conda stuff like you mentioned, I will update here if run into more issues! Thanks for all you quick responses so far!!!

**Comment by tlambert03** [comment]
> did you install python directly via python.org?

I ask, because it's actually not necessary (and honestly, not even advisable really) to install python system-wide from python.org if you're _also_ going to use conda (unless you know specifically that you want to do so).  Conda will install python for you.  When you run `conda create -n envname python=3.9`, the "python 3.9" bit means _install_ python 3.9 ... (not "use" python 3.9).  In some cases, that system wide installation can actually create more confusion than it's worth :)

**Comment by liaprins-czi** [comment]
Okay, I have neither miniconda3 nor anaconda anywhere in my computer at this point. So just to make sure I install it right, I just follow the instructions from the [anaconda docs](https://docs.anaconda.com/anaconda/install/mac-os/)? Or would it be better to do the miniconda version?

**Comment by tlambert03** [comment]
I'd say go for miniconda.  it provides the `conda` program without all the bloat of hundreds of packages you may never use.  follow install here: https://docs.conda.io/en/latest/miniconda.html

**Comment by liaprins-czi** [comment]
Okay great I will do that! Thank you!!!

Also I jsut saw your comment about Python... should I uninstall it before install miniconda?

**Comment by tlambert03** [comment]
>  should I uninstall it before install miniconda?

you can if you want. but it shouldn't be a problem

**Comment by tlambert03** [comment]
![python_environment](https://user-images.githubusercontent.com/1609449/108420718-2c14e500-7202-11eb-8ccd-83f1af522240.png)

:joy:

**Comment by liaprins-czi** [comment]
Great! now everything seems to be back to normal, now the usual `napari` command works to open napari! thank you so much for your help @tlambert03 !

**Comment by jni** [comment]
Just for future reference, I recommend people install miniforge these days in place of miniconda:

https://github.com/conda-forge/miniforge

it's the same thing as miniconda, except it defaults to searching conda-forge instead of the (privately managed) Anaconda defaults.
