### ISSUE TITLE
napari-app / napari-cli

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#229]
## 🚀 Feature
In the past couple team meetings the concept of a napari-cli and napari-app has come up. It has also been discussed in this PR #208.

One proposal has been floated to create two new repos `napari-cli` and `napari-app` that would interact with the rest of the ecosystem as follows

<img src="https://user-images.githubusercontent.com/6531703/56477008-72a62680-6455-11e9-9ba1-9ab9b14856a6.png" width="400">

`napari-cli` would depend on `napari` as a requirement, and additionally depend on a few io libraries and allow for functionality like `napari image.tif` that would launch the napari viewer with that image loaded or `napari *.tif` that would launch a napari viewer with all the images concatenated along the z axis.

`napari-app` would also depend `napari` as a requirement, and additionally depend on a few io libraries, and be a double clickable icon that could open up the napari viewer. Additionally the app would populate menubars, allowing for file opening / saving and allow for adding and running plugins further down the line.

I'd like to propose the following - that for now we just create **one** new repo `napari-app` that will have both functionalities of the double-click app and be able to be launched from the command line either by typing `napari` which just opens an empty viewer or `napari image.tif` which would open the a viewer with that image. Note that now this viewer would have all the functionality of the app including dropdown menus etc. To me this makes much more sense than having the cli version that lacks those features and ultimately we'd probably want to add the ability to launch from the command-line to the app anyway.

<img src="https://user-images.githubusercontent.com/6531703/56477167-51463a00-6457-11e9-9486-0192d689beb8.png" width="100">

From a development standpoint we will have less duplicated code (a lot of the `io` stuff would have appeared in both `napari-cli` and `napari-app`, and it will be much simpler for newcomers to the project to understand. There is `napari` which is just the viewer and `napari-app` which is the the viewer bundled with all the file `io`, plugin-mangement, drop-downmenu stuff. We'd also allow pip install napari[all] to install both the viewer and the app. In the future though we might want to actually rebrand `napari` -> `napari-viewer` and `napari-app` -> `napari`, but we can cross those bridges when we get to it.

What are peoples thoughts?

**Comment by kne42** [comment]
sounds great to me! 👍 👍

**Comment by jni** [comment]
Makes sense. I want to make sure that I can pip install napari[all] and have a napari command, but I think that is doable with this framework.

**Comment by kevinyamauchi** [comment]
I think this is great, @sofroniewn! I like the more simple repo structure. I also totally agree that the napari that is launchable from the command line may as well be `napari-app`.  I am still unsure of the utility of a standalone CLI given that "napari headless is just Python" and the app will come with file IO (seems like unnecessary fragmentation).

**Comment by sofroniewn** [comment]
This discussion has been superseded by #359 and #376  and partially resolved by PR #356. As discussed on those issues and implemented in that PR we have now merged the menubar access and CLI all into this main napari repo - keeping our organization much simpler, removing the need for coordinated development across multiple repos, and ensuring there is just one napari that people can use which is fully functional
