### ISSUE TITLE
Allow to provide list of docked widgets which will be open on viewer start

### ISSUE THREAD

**Issue by Czaki** [napari/napari#2291]
## 🚀 Feature

Add to `Viewer` constructor argument `widgets` or `docked_widgets` with a list of widgets that need to be docked on Viewer start. This could be a list of names or a list of classes (not instances).

## Motivation

When working with the development of plugins this is annoying to all-time open widgets from the main menu. of course it possible to use `add_dock_widget` from `viewer.window` but this is handled differently than widgets from the main menu. 

List of main problems:

1. Widgets added with `add_dock_widget` could be closed without the option to reopen it.
2. When the widget is added with `add_dock_widget` and registered with hook it is possible to have two instances of a given widget.

These two ones are not so hard when developing, but problematic when providing GUI to non programming person.

**Comment by sofroniewn** [comment]
I'm not sure this will be a complete solution to what you request, but I could imagine keeping track of which plugin widgets were open when you last closed the viewer and restarting napari with those plugin widgets displayed. This will at least help our plugin developers and users.

**Comment by Czaki** [comment]
I do not think that it will solve this problem. This base on the previous run, not the context of a current situation.  
Another solution when something like this may be useful is using naprai from a notebook. That you could simply adjust the interface to the current task.

**Comment by tlambert03** [comment]
I'm not sure I'm following what you want to happen.  Is the issue that you want to be able to start napari with a plugin dock widget already open (without manually needing to open it in the menu)?  Is it that you want to be able to have multiple instances of the dock widget?  Is it that you _want_ to be able to close and reopen it, or _don't_ want to be able to close and reopen it?

Would this be solved by us making a better public interface for `_add_plugin_dock_widget`?

**Comment by Czaki** [comment]
I would like to start napari with already docked widgets and without the possibility of multiply instances (which could be done with add_docked_widget). 

> Would this be solved by us making a better public interface for `_add_plugin_dock_widget`?

I think yes.

**Comment by goanpeca** [comment]
This would be saved as part of the geometry saving, we just need to track the list of visible plugins/docks on shutdown. Dockwidgets also need to have a unique and object name assigned

**Comment by Czaki** [comment]
> This would be saved as part of the geometry saving, we just need to track the list of visible plugins/docks on shutdown. Dockwidgets also need to have a unique and object name assigned

This is a nice idea for Viewer used as bundled app. Not for viewer used from a notebook. A different notebook may need a different set of widgets.
