### ISSUE TITLE
Napari syntax error identified in the tutorials docs

### ISSUE THREAD

**Issue by GenevieveBuckley** [napari/napari#2295]
## 🐛 Bug

I've been converting the napari 'fundamentals' tutorials to jupyterbook, and have already found a failure because of a syntax error. We don't want to recommend users do things that don't work, so we should update the docs. Trouble is, I'm not entirely sure what the right way is.

So the [tutorials/fundamentals/viewer](https://napari.org/tutorials/fundamentals/viewer.html) documentation says you can switch the position of layers with:
```python
viewer.layers['astronaut', 'moon'] = viewer.layers['moon', 'astronaut']
```
...but I get an error when I try to do this.

## To Reproduce

Set up the example layers
```python
import napari
from skimage import data

viewer = napari.Viewer()
viewer.add_image(data.astronaut(), name='astronaut')
viewer.add_image(data.moon(), name='moon')
viewer.add_image(data.camera(), name='camera')
```
Now we can try indexing layers
```python
viewer.layers['astronaut']  # ok
viewer.layers['astronaut', 'moon']  # not ok

# This is what the documentation says you can do
# viewer.layers['astronaut', 'moon'] = viewer.layers['moon', 'astronaut']
```

Here's the error message:

```python-traceback
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-521907e98923> in <module>
----> 1 viewer.layers['moon', 'astronaut']

~/GitHub/napari/napari/utils/events/containers/_typed.py in __getitem__(self, key)
    151         else:
    152             _key = key
--> 153         result = self._list[_key]
    154         return self.__newlike__(result) if isinstance(result, list) else result
    155 

TypeError: list indices must be integers or slices, not tuple

In [6]: viewer.layers[['moon', 'astronaut']]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-c45c44b261b5> in <module>
----> 1 viewer.layers[['moon', 'astronaut']]

~/GitHub/napari/napari/utils/events/containers/_typed.py in __getitem__(self, key)
    151         else:
    152             _key = key
--> 153         result = self._list[_key]
    154         return self.__newlike__(result) if isinstance(result, list) else result
    155 

TypeError: list indices must be integers or slices, not list
```

## Environment

 - Please copy and paste the information at napari info option in help menubar here:

```
napari: 0.2.4.dev736+g79ab358
Platform: Linux-5.8.0-43-generic-x86_64-with-debian-bullseye-sid
System: Ubuntu 20.04.2 LTS
Python: 3.7.9 | packaged by conda-forge | (default, Dec 9 2020, 21:08:20) [GCC 9.3.0]
Qt: 5.15.2
PyQt5: 5.15.2
NumPy: 1.20.1
SciPy: 1.6.0
Dask: 2021.02.0
VisPy: 0.6.6

OpenGL:
- GL version: 4.6 (Compatibility Profile) Mesa 20.2.6
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1080, scale 1.0
- screen 2: resolution 1920x1080, scale 1.0

Plugins:
- svg: 0.1.4
```

 - Any other relevant information:

**Comment by tlambert03** [comment]
as mentioned on zulip.  that syntax is no longer supported and that tutorial needs to be updated.  (another exciting reason for moving to dynamic docs eh? :joy:)

I don't have an example immediately ready, but you can move layers using standard python list syntax (tricks like [this SO post](https://stackoverflow.com/questions/3173154/move-an-item-inside-a-list)), or you can use the methods from `EventedList` like `viewer.layers.move` and `viewer.layers.move_multiple`.  I don't have a strong preference or suggestion for what to do with the tutorial... You can either provide a simple example of moving an item in the list using one of those options, or just delete altogether.

**Comment by GenevieveBuckley** [comment]
Thanks a bunch for your thoughts!
You know what? I'm just going to say "you can move layers by clicking and dragging them". I have no idea why this super-obvious solution did not occur to me until just now :rofl:
