### ISSUE TITLE
py37 failing

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#2299]
## 🐛 Bug
looks like #2254 has introduced some incompatibilities and [failing tests](https://github.com/tlambert03/napari/runs/1966542373?check_suite_focus=true#step:9:1796) with py37 with `AttributeError: module 'gettext' has no attribute 'dpgettext'`.  I think the only reason linux is passing is because those tests are getting skipped.

cc @goanpeca

**Comment by tlambert03** [comment]
(btw, @goanpeca ... we don't test all python/OS combinations in PRs... so it might have looked like a linux-specific problem in the PR, but we only test 3.7 on linux in PRs)

**Comment by sofroniewn** [comment]
Good catch @tlambert03, is it also failing locally? We should look into a fix asap

**Comment by tlambert03** [comment]
> is it also failing locally?

yep, try:
```
$ tox -e py37-macos-pyqt -- napari/utils/_tests/test_translations.py
```

**Comment by goanpeca** [comment]
I will add a fix. My bad I looked at the 3.8 docs an not the 3.7 docs. Indeed some methods are not available. 

I need to fix. Working on this now.

Good catch @tlambert03
