### ISSUE TITLE
GUI mockups

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#23]
I have made a mockup of the gui with the addition of range slides & max projection / play button / gamma slider and colorlimits slider and single letter labels of dimensions. Not included in the mockup right now are UI elements to toggle between axes that are displayed in the image and that are displayed as sliders or any UI elements related to different layers. I will try mocking some of these up too, but wanted to paste the intermediate in here first. 

![image](https://user-images.githubusercontent.com/6531703/47622960-9866fa00-dac8-11e8-8c65-0f5d04afd82e.png)

**Comment by royerloic** [comment]
Really cool!
A few comments:

- Let's have min max on the left side of gamma, one cool idea is to have a histogram 'on its side' shown optionally as a 'tray', so that the min and max interval slider matches the, that would be super elegant imo...
- we should have a scale bar overlay, a bit similar to what google maps has...
- layer list on the right with options, I know you have ideas for it...

**Comment by sofroniewn** [comment]
Ok nice, I have updated the mock. Added a histogram on the left. Agreed it would be good if it could toggle in / out. Added a scale bar, would be good if it could be toggled on / off too - probably fine from a drop down menu. Have also added a little dialog like box down at the bottom left where we can select which axes are being displayed in the viewer and which are displayed as sliders. Finally added a layer listing on the right. Has listing of layers with mini-pictures. An on/off visible display, and then a drop-down menu that provides access to other features like colormap / opacity. These would be different for different layer types, i.e. a markers layer would also have a size. Would be good if the layers were also draggable so they could be reordered in the viewer and that would change the z-index.
![image](https://user-images.githubusercontent.com/6531703/47671482-d1f14100-db6c-11e8-8ccf-3b1b93e3dcc3.png)

**Comment by AhmetCanSolak** [comment]
Seems good. Thank you @sofroniewn !
Only, Im not sure about on/off visible displays for colormap, opacity etc.

**Comment by jni** [comment]
@AhmetCanSolak 

> Only, Im not sure about on/off visible displays for colormap, opacity etc.

What do you mean? My interpretation of the above is that it's only when clicking on the "sandwich" menu in the layer that these menus appear? Is that right @sofroniewn?

Anyway, though, these are minor details, this looks absolutely awesome to me!

**Comment by AhmetCanSolak** [comment]
@jni I thought those menus appear as you hover on sandwich menu icon on layer. With click possibly it will be better. As you said these are minor details that we can figure out later.

**Comment by sofroniewn** [comment]
yeah, it was something like clickable dropdown menu on sandwich icon that would contain those extra parameters - agree clickable is better than hover in this context. The visible on/off would also be a clickable checkbox, that i made look eye shaped, but could be whatever. Can discuss at the meeting today, and I imagine we might be constrained by what pyqt offers, but just wanted to get something out there that we can update as we go

**Comment by royerloic** [comment]
Awesome.

Here is the mockup I had drawn that had a proposal for switching between 1D, 2D, 3D viewing and how to pick the dimensions shown...
