### ISSUE TITLE
The Help 'napari info' dialog box does not match the napari theme

### ISSUE THREAD

**Issue by GenevieveBuckley** [napari/napari#2301]
## 🐛 Bug

Somewhere between napari release 0.4.5 and the current master branch, we've lost the theme that should be applied to the `napari info` dialog box from the Help menu.

On napari 0.4.5 I don't see this issue, the theme of the napari info dialog box matches the rest of napari.

## To Reproduce

1. Launch napari from the master branch
2. Click the `Help` menu, then the `napari info` menu item
3. Observe the colour of the dialog box, it doesn't match the rest of the 'dark' theme the way it used to do.

If you follow the same steps, but using a napari 0.4.5 installation, we don't see this issue.

I tried explicitly setting `viewer.theme = 'dark'`, in case napari was remembering a setting from last time or something, but no luck there.

## Expected behavior

I expected the napari info dialog box to match the overall 'look' of the rest of napari. I also expect this will change depending on what theme is currently set in napari.

The 'keybindings' dialog box doesn't have the same weird behaviour.

## Environment

 - Please copy and paste the information at napari info option in help menubar here:
```
napari: 0.4.6.dev22+g02019b9
Platform: Linux-5.8.0-43-generic-x86_64-with-glibc2.10
System: Ubuntu 20.04.2 LTS
Python: 3.8.5 (default, Sep 4 2020, 07:30:14) [GCC 7.3.0]
Qt: 5.15.2
PyQt5: 5.15.2
NumPy: 1.19.2
SciPy: 1.5.2
Dask: 2.30.0
VisPy: 0.6.6

OpenGL:
- GL version: 4.6 (Compatibility Profile) Mesa 20.2.6
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1080, scale 1.0
- screen 2: resolution 1920x1080, scale 1.0

Plugins:
- console: 0.0.3
- svg: 0.1.4
- ```
 - Any other relevant information:

## Additional context

<!-- Add any other context about the problem here. -->

**Comment by GenevieveBuckley** [comment]
Probably a good first step here is using `git bisect` to narrow down on when this was introduced.

**Comment by tlambert03** [comment]
the general refrain that people should try remember about styles in Qt, is that widgets inherit their styles from their parents.  For this reason (and also for widget cleanup reasons), it's important that all widgets be assigned parents if at all possible.  This appears to be one of a few lingering cases of a custom widget not being given a parent, and can be fixed by: 
1) changing the `__init__` of the `QtAbout` dialog to pass a parent to the constructor
   ```python
    class QtAbout(QDialog):
    def __init__(self, parent):
        super().__init__(parent)
   ```
2) Passing the `qt_viewer` argument as the parent in the `showAbout` method:
   ```python
    @staticmethod
    def showAbout(qt_viewer):
        d = QtAbout(qt_viewer)
		# and delete this line
	    # d.setStyleSheet(qt_viewer.styleSheet())
   ```
