### ISSUE TITLE
Napari not working with dask distributed Client

### ISSUE THREAD

**Issue by kpasko** [napari/napari#2304]
**What happened**:

TypeError: can not serialize 'function' object

In distributed/client.py line 2635
futures = self._graph_to_futures

**What you expected to happen**:

successful image viewing

**Minimal Complete Verifiable Example**:

```python
from dask.distributed import Client
import napari
import dask_image.imread as imread

client = Client()
data = imread('./myFiles/*.tif')
napari.view_image(data)
```

**Anything else we need to know?**:
Works fine when not initializing client, i.e. 
```python
import napari
import dask_image.imread as imread

data = imread('./myFiles/*.tif')
napari.view_image(data)
```

works as expected

**Environment**:

- Napari/Dask version:
dask                      2021.2.0           pyhd8ed1ab_0    conda-forge
dask-core                 2021.2.0           pyhd8ed1ab_0    conda-forge
dask-image                0.5.0              pyh44b312d_0    conda-forge
distributed               2021.2.0         py39h6e9494a_0    conda-forge
napari                    0.4.5              pyhd8ed1ab_0    conda-forge
napari-console            0.0.3              pyhd8ed1ab_0    conda-forge
napari-plugin-engine      0.1.9            py39h6e9494a_1    conda-forge
napari-svg                0.1.4                      py_0    conda-forge

- Python version:
python                    3.9.2           h2502468_0_cpython    conda-forge

- Operating System: OS X 11.2.1
- Install method (conda, pip, source): conda

**Comment by kpasko** [comment]
@jrbourbeau

**Comment by tlambert03** [comment]
interesting.  This does appear to be at least partly related to the interplay between napari and `dask-image` itself...  If I directly pass a dask array, I get no error:

```python
from dask.distributed import Client
import napari
import dask.array as da

client = Client()
data = da.ones((64,64))
napari.view_image(data)
```

also, if I cast the dask_image to numpy prior to passing to napari, it also seems to work:

```python
from dask.distributed import Client
import napari
from dask_image.imread import imread
import numpy as np

client = Client()
data = imread('./myFiles/*.tif')
napari.view_image(np.array(data))
```

cc @jakirkham

**Comment by jakirkham** [comment]
Thanks for letting us know. Do we have more details from the exception?

**Comment by jakirkham** [comment]
cc @GenevieveBuckley

**Comment by jrbourbeau** [comment]
Is there a nice way to save a Dask array to `*.tif` files? I'd like to try and run 

```python
from dask.distributed import Client
import napari
from dask_image.imread import imread
import numpy as np

client = Client()
data = imread('./myFiles/*.tif')
napari.view_image(np.array(data))
```

locally

**Comment by tlambert03** [comment]
fwiw, I was able to reproduce just using a plain local `.png` file for `imread`

**Comment by jakirkham** [comment]
Does this happen with an older version of Dask-Image? I think there were some changes to `imread` in the recent release

**Comment by kpasko** [comment]
here's the full trace

![image](https://user-images.githubusercontent.com/167271/109051054-f606b380-768e-11eb-903b-2a9193767078.png)

**Comment by tlambert03** [comment]
another thing we should try is to go back before the async stuff got added to the Image layer in napari (i.e. before #1343 and #1565), and see if it happens there.

**Comment by jakirkham** [comment]
cc-ing @madsbk (as HLG is coming up in the trace though we might need to unpack things further)

**Comment by jakirkham** [comment]
> Does this happen with an older version of Dask-Image? I think there were some changes to `imread` in the recent release

In particular would be good to test 0.4.0 to see if this works there as 0.5.0 started using `da.map_blocks` ( https://github.com/dask/dask-image/pull/165 )

**Comment by GenevieveBuckley** [comment]
> > Does this happen with an older version of Dask-Image? I think there were some changes to `imread` in the recent release
> 
> In particular would be good to test 0.4.0 to see if this works there as 0.5.0 started using `da.map_blocks` ( [dask/dask-image#165](https://github.com/dask/dask-image/pull/165) )

Yes, this is the next step to try. Would you be able to give that a go @kpasko?

**Comment by GenevieveBuckley** [comment]
Can confirm, this problem was introduced with `dask-image` version 0.5.0

You can use either `dask-image` version 0.4.0, or `dask.array.image.imread()` and not see the same problem.

```python
from dask.distributed import Client
import napari
from dask.array.image import imread

client = Client()
data = imread('./myFiles/*.tif')
napari.view_image(data)
```

**Comment by GenevieveBuckley** [comment]
Since this is a clear problem caused by `dask-image`, I'm going to copy this info over to a new issue there.

Head over to https://github.com/dask/dask-image/issues/194 if you want to follow it there

**Comment by jakirkham** [comment]
Just updating this thread, we believe this traces back to a Dask issue that was addressed with PR ( https://github.com/dask/dask/pull/7353 ). It is not yet in a release though. So would need to install from `main` or wait for a release
