### ISSUE TITLE
How to view 3D images in perspective mode?

### ISSUE THREAD

**Issue by colinmarcus** [napari/napari#2320]
I have a large (>4GB) 3D image I am trying to view. It is in numpy array format. I am able to successfully load it into napari viewer, but I have noticed it is rendering in orthographic view, rather than perspective view.

How can I render in perspective view?

Thanks!

**Comment by jni** [comment]
Well, I didn't think it was possible without accessing private APIs, but, the power of open source! I knew we used the VisPy Arcball camera, the source code of which can be found here:

https://github.com/vispy/vispy/blob/48122e63c376d05c76a131911984f323c0eaeb05/vispy/scene/cameras/arcball.py

And there I noticed this comment in the docstring:

    Notes
    -----
    Interaction:
        * LMB: orbits the view around its center point.
        * RMB or scroll: change scale_factor (i.e. zoom level)
        * SHIFT + LMB: translate the center point
        * SHIFT + RMB: change FOV

Sure enough: shift + right mouse button and move the mouse up and down to adjust the perspective!

![perspective](https://user-images.githubusercontent.com/492549/109255739-b5eb3080-7848-11eb-8cd3-6c0f744d4ca3.gif)

@sofroniewn do you think we should add perspective projection to our camera model?

**Comment by sofroniewn** [comment]
> @sofroniewn do you think we should add perspective projection to our camera model?

seems like a pretty reasonable request and we probably should. do they just use fov in degrees, which i guess runs for 0 -> 90 with 0 being orthographic. We could just reuse that same name `fov`? Here is where we hard code it right now https://github.com/napari/napari/blob/3d8f315a74ce53d2e6a784f246b5d405d3951667/napari/_vispy/vispy_camera.py#L32

**Comment by colinmarcus** [comment]
Fantastic! The shift+right mouse button thing works! The only downside, is that it doesn't just scale between ortho and perspective - it keeps going past perspective, into some nightmare super-stretched-perspective view. :)

In any case, if you could add an ortho/perspective menu option in the future, that would be great!

**Comment by colinmarcus** [comment]
In the meantime, is there a way I can set the fov in code? The issue with shift+RMB is that it is too imprecise. I am currently doing something like:

`import napari`
`%gui qt`
`viewer = napari.view_image(data3D_sphericalized)`

Is there a line I could add here that would set the fov=90? This is in Jupyterlab FYI.

**Comment by tlambert03** [comment]
```python
viewer.window.qt_viewer.camera._3D_camera.fov = 45  # or whatever number you like
```

**Comment by psobolewskiPhD** [comment]
There is now a widget to adjust the perspective numerically in the GUI:
https://github.com/napari/napari/pull/2636

This also simplified the programatic approach:
`viewer.camera.perspective = 45`

I added documentation for it to the Viewer tutorial here:
https://github.com/napari/docs/pull/159

As a result, I'm going to close this.
