### ISSUE TITLE
Text overflow in Labels Layer on Linux

### ISSUE THREAD

**Issue by ianhi** [napari/napari#2337]
## 🐛 Bug
The text for some of the options for the labels layer is not displaying correctly:
![image](https://user-images.githubusercontent.com/10111092/109747434-1c53b400-7ba5-11eb-9371-f0d69ee4a9f0.png)

This persists even with window resizing.

## To Reproduce
I just run the layers.py python example and added a labels layer by clicking the button to add one.

## Expected behavior
Text looks good.
## Environment
```
napari: 0.4.7.dev4+geaa5474
Platform: Linux-5.8.0-7630-generic-x86_64-with-glibc2.31
System: Pop!_OS 20.04 LTS
Python: 3.9.1 | packaged by conda-forge | (default, Jan 26 2021, 01:34:10) [GCC 9.3.0]
Qt: 5.15.2
PyQt5: 5.15.2
NumPy: 1.19.5
SciPy: 1.6.0
Dask: 2021.01.1
VisPy: 0.6.6

OpenGL:
- GL version: 4.6 (Compatibility Profile) Mesa 20.2.6
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1080, scale 1.0

Plugins:
- console: 0.0.3
- svg: 0.1.4
```
 - Please copy and paste the information at napari info option in help menubar here:

 - Any other relevant information:

**Comment by liaprins-czi** [comment]
Related: #2470

**Comment by liaprins-czi** [comment]
Related: #1934 

@ianhi Is this issue still happening for you? If so, and if this is still an issue that can't be solved by enginerring, I will cosnider it as a UI bug and work on a more flexible design solution!

**Comment by goanpeca** [comment]
I think this issue is there because are changes in system-wide font resolutions, but we add width constrains to those panels/dock.

**Comment by ianhi** [comment]
> @ianhi Is this issue still happening for you? If so, and if this is still an issue that can't be solved by enginerring, I will cosnider it as a UI bug and work on a more flexible design solution!

@liaprins-czi yup I still experience this with `0.4.10`

**Comment by brisvag** [comment]
@ianhi is this solved after #4368?

**Comment by ianhi** [comment]
@brisvag it is now user-fixable in that I can drag it to be larger so the text doesn't get cut off, but it is still cut off by default when I create a label layer.
![Peek 2022-04-26 11-07](https://user-images.githubusercontent.com/10111092/165332274-e21a64c1-2bbb-4f34-a3e7-5bc01052d802.gif)

**Comment by brisvag** [comment]
Uhm... I think we might be missing some setting/detection of fonts size. It's probably the same issue that caused [this difference between my viewer and @alisterburt's](https://github.com/napari/napari/pull/4195#issuecomment-1108413230).

**Comment by dalthviz** [comment]
Hi, seems like this also happens on Windows (although the overlapping occurs vertically for the `preserve labels` and `show selected` label fields):

![imagen](https://user-images.githubusercontent.com/16781833/208164342-7e2aee97-05a4-474f-992f-ff1b0e146755.png)

Maybe adding scrollbars to the layer controls could help? So something like this:

![scroll_controls](https://user-images.githubusercontent.com/16781833/208470990-3aabc628-5c48-48fa-b4fd-d31069238daa.gif)
