### ISSUE TITLE
Settings broke new theme registerd

### ISSUE THREAD

**Issue by Czaki** [napari/napari#2340]
## 🐛 Bug

#2212 Broke registering a new theme by creating a closed list of the available themes. 

https://github.com/napari/napari/blob/eaa54747e376c9da853a63f3e326b89d49a4f73b/napari/utils/settings/_defaults.py#L19-L23

Test for registering new theme was disabled on CI.

https://github.com/napari/napari/blob/eaa54747e376c9da853a63f3e326b89d49a4f73b/napari/_tests/test_examples.py#L39-L58

**Comment by sofroniewn** [comment]
Sorry about that. We definitely do want to support the addition of new themes.

**Comment by goanpeca** [comment]
Thanks for this @Czaki. Will work on a fix :)

**Comment by goanpeca** [comment]
@Czaki this was fixed as part of this PR https://github.com/napari/napari/pull/2211/files#diff-aed87050aba7a2957ac944a789012175bf594c59dc136e479bed759e677e265dR14

It should be landing soon, right @sofroniewn 🙃 ?

**Comment by sofroniewn** [comment]
> It should be landing soon, right @sofroniewn 🙃 ?

Yes, I just approved it, shouldn't be too long :-) Is there a test for this inside #2211? Apologies if I missed it. If not maybe @ppwadhwa, we can add one. Thanks!!

**Comment by goanpeca** [comment]
I should have added one 😶
