### ISSUE TITLE
Napari hook enum

### ISSUE THREAD

**Issue by Czaki** [napari/napari#2364]
## 🚀 Feature

Add enum (`StringEnum`) with all available hooks and allow to use it in `specname` argument of `napari_hook_implementation` 

## Motivation

This allows the faster discovery of changes of hooks name when the new version of napari is released (the creator does not need to manually verify if the hook is discovered). The main address of this feature are experimental hooks.   

This also will add name hinting and IDE.

**Comment by psobolewskiPhD** [comment]
This is related to npe1, in light of npe2, is this still relevant @Czaki ?

**Comment by Czaki** [comment]
No. It could be closed
