### ISSUE TITLE
Async/ Octree to dos

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#2367]
## 🚀 Feature

Here are some of async/ octree todos, some easier/ harder than others

### Intermediate
- [ ] Get octree working for the labels layer without editing
- [ ] Make it possible to turn Octree and Async on in our settings and preferences without needing a restart
- [ ] Add comprehensive octree and async tests, including unit tests and screenshot tests
- [ ] Clean up slicing from Image layer
- [ ] Look at octree support for >2D data that is sliced, check works as expected
- [ ] Fix clims from going out of sync by removing all CPU data normalization. Will be possible after vispy 0.7 and https://github.com/vispy/vispy/pull/1920
- [ ] **Edit @jni**: [naive 3D loading](https://github.com/napari/napari/issues/2367#issuecomment-792444971)

### Advanced

- [ ] Support for labels & painting with octree
- [x] Octree-like support for chunked data that is not multiscale (i.e. single scale lots of tiles). **Edit: See #2372**
- [ ] Support proper octree for 3D data rendering!
- [ ] Support non-image like layer types, i.e. meshes, points, shapes

**Comment by jni** [comment]
Thanks for creating this to track things, @sofroniewn!

One idea I had for intermediate 3D support is blocked, multiresolution, async loading, with no reference to camera geometry. As one example, for an example lattice dataset, each volume comfortably fits in the Volume node, but it's too big to load "live" with the slider — you lose the interactivity. So we could load the lowest-res pyramid level on slider move, then if the slider stops for a bit, we asynchronously load the higher resolution chunks to get a nicer view of the current volume, up to the max texture size. This doesn't solve the problem for really large 3D images, but it makes interacting with *moderately* large 3D+t images much much nicer than it is now, and it's probably way easier to implement than something that takes the camera geometry into account.

**Comment by liu-ziyang** [comment]
thanks for the tracker! I would like to redirect anyone here to our board tracking our async effort latest: https://github.com/orgs/napari/projects/16
