### ISSUE TITLE
Labels painting setting "ndim" should be an integer, not bool

### ISSUE THREAD

**Issue by jni** [napari/napari#2369]
## 🚀 Feature

Users painting segmentations into a 3D+t labels layer will probably want to paint into 3D volumes but not across time. There are probably other scenarios where users would like to paint into volumes, but not across *all* non-displayed dimensions.

As a first pass, I suggest we allow painting into the last n dimensions. In the future, users could set exactly which dimensions they want to paint into, and this would be integrated with the axis labels.

**Comment by kephale** [comment]
This can be closed now right?

**Comment by psobolewskiPhD** [comment]
I think so? `n edit dim` is a int, and in the GUI.
But you can't choose the dims, so `3` means last 3.
Still, by using the new dims sorter you can change the order if you happen to have ZTYX.
