### ISSUE TITLE
SettingsManager overwriting env var settings

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#2370]
## 🐛 Bug
Pydantic BaseSettings provides a nice way to set settings using [environment variables](https://pydantic-docs.helpmanual.io/usage/settings/#environment-variable-names), but at the moment, the `SettingsManager._load` method is overwriting this:

```python
# test.py
from napari.utils.settings import SETTINGS, CORE_SETTINGS

print("Application Settings:", CORE_SETTINGS[0]().theme)
print("SettingsManager:", SETTINGS.application.theme)
```

```sh
$ NAPARI_THEME=light python test.py
Application Settings: light
SettingsManager: dark
```

In the case where a settings is defined multiple ways, I think we should aim to match the [default field priority](https://pydantic-docs.helpmanual.io/usage/settings/#field-value-priority) in pydantic:

- Arguments passed to the `Settings` class initialiser.
- Environment variables, e.g. `napari_setting`
- Variables loaded from a dotenv (.env) file, (or, in our case, yaml settings) 
- Variables loaded from the secrets directory.
- The default field values for the Settings model.

This does open a bit of a challenge for the concept of persistence, since I think that loading with `NAPARI_THEME=light` would probably then override the yaml file itself on close... which is less desirable (I think it would be nice to be able to use environment variables to override settings at startup, without permanently changing the preferences)

**Comment by tlambert03** [comment]
adding this here in case it's useful.  Pydantic offers a [hook](https://pydantic-docs.helpmanual.io/usage/settings/#customise-settings-sources) in `BaseSettings.config.customise_sources` to know where the settings are coming from... so, for instance:

```python
#napari.utils.settings._defaults

class ApplicationSettings(BaseSettings, EventedModel):
    class Config:
        @classmethod
        def customise_sources(
            cls, init_settings, env_settings, file_secret_settings
        ):
            cls._env_settings = env_settings  # or otherwise save it somehow
            return init_settings, env_settings, file_secret_settings
```

then you can query it as follows, for instance, if I start IPython with `NAPARI_THEME=light ipython`:

```python
In [1]: from napari.utils.settings._defaults import ApplicationSettings

In [2]: s = ApplicationSettings()

In [3]: ApplicationSettings.__config__._env_settings(s)
Out[3]: {'theme': 'light'}
```

**Comment by tlambert03** [comment]
It might also make sense to move the logic from the global `SettingsManager._load` into a custom `customise_sources` method... since pydantic already provides a fair amount of support for the merging of settings from disparate sources, maybe we should just hook into that?

**Comment by tlambert03** [comment]
(should have included this link)... Pydantic actually gives an example of add json file settings source [in their documentation](https://pydantic-docs.helpmanual.io/usage/settings/#adding-sources).  that looks like a great place to import our yaml

**Comment by goanpeca** [comment]
>Pydantic actually gives an example of add json file settings source in their documentation. that looks like a great place to import our yaml

I have been looking into this, and this is not as nice as it should. Currently the load method is doing validation of things and making sure Napari starts even there are problems with the file. By using `customise_sources` we have to assume yaml file is correct. This might not be the case and will result in Napari crashing if errors on the yaml file, like invalid sections, invalid keys or invalid values.

We cannot really use the models now to validate values, since it will enter a recursion, so I am not sure how to go around this.

Having Napari start no matter what the settings file contains seems like a much important thing than having the ability to use these env variables. I can try to make it work in a different way, but using `customise_sources` will not help to make the configuration system robust.

**Comment by goanpeca** [comment]
So I can use this:

```python
#napari.utils.settings._defaults

class ApplicationSettings(BaseSettings, EventedModel):
    class Config:
        @classmethod
        def customise_sources(
            cls, init_settings, env_settings, file_secret_settings
        ):
            cls._env_settings = env_settings  # or otherwise save it somehow
            return init_settings, env_settings, file_secret_settings
```

But keep the loading similar to what we have now. Just taking into account these values

**Comment by tlambert03** [comment]
> Having Napari start no matter what the settings file contains seems like a much important thing than having the ability to use these env variables

absolutely!  sounds good.

**Comment by tlambert03** [comment]
> By using customise_sources we have to assume yaml file is correct. 

actually, I have a question... why is that the case?  From [docs example](https://pydantic-docs.helpmanual.io/usage/settings/#adding-sources)... why can't you just put the same validation logic from SettingsManager._load in the loading function ("`json_config_settings_source`" in their example)?

**Comment by goanpeca** [comment]
Cause to be able to validate I was using the model and catching errors. But doing that inside the custom sources that will also use custom sources when using the model so it will get into a recursion. I tried setting each thing manually with setattr on the model but that dis not work either. Will try again tomorrow morning with fresh eyes

**Comment by sofroniewn** [comment]
Bump for next sprint, we might want to work on this cc @goanpeca @ppwadhwa

**Comment by goanpeca** [comment]
Yes. I could not get a solution that made me happy 🤣.

Need to revisit
