### ISSUE TITLE
slow app load time with pythonw

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#2371]
## 🐛 Bug
Just noticed that our strategy of re-running napari in a subprocess with pythonw (if it is available) is significantly increasing time-to-load, since (to my understanding) `napari.__init__` must be imported to get to `napari.__main__`.  By having our CLI entry point outside of the `napari` package, we shave about a second off load times...

As shown in the traces below, if pythonw is unavailable, the times are comparable regardless of where `__main__.py` is... but if it's available we load ~1.5x slower.

```sh
# __main__.py inside of napari folder with pythonw available.
napari.__INIT__      0.0000
__main__.main        0.7533
__main__._run_pyw    0.7534
napari.__INIT__      1.0260
__main__.main        1.7832
__main__._run        1.7832
viewer.show          2.8128
```
```sh
# __main__.py inside of napari folder no pythonw available
napari.__INIT__      0.0000
__main__.main        0.7777
__main__._run        0.7780
viewer.show          1.7281
```
```sh
# __main__.py outside of napari folder with pythonw available.
__main__.main        0.0000
__main__._run_pyw    0.0067
napari.__INIT__      0.0390
__main__.main        0.9130
__main__._run        0.9131
viewer.show          2.01466
```
```sh
# __main__.py  outside of napari folder no pythonw available
__main__.main        0.0000
__main__._run        0.0070
napari.__INIT__      0.0076
viewer.show          1.7267
```

**Comment by tlambert03** [comment]
not sure what the most desirable solution is here.  We _could_ just have a `napari_cli.py` module that is outside of the napari folder... (that actually would be convenient for many reasons... allowing us to do many CLI things without importing all of napari).  But we'd need to call out to it from `napari.__main__` (or inside of `napari.__init__` :: "`if __name__...`") in order to maintain the `python -m napari` functionality

**Comment by sofroniewn** [comment]
I'm all for shaving this time lower! It's not clear to me if there are any potential downsides of what you are proposing?

**Comment by tlambert03** [comment]
the main downside is that it's a "second" package within our distribution. (for instance, in site-packages, you'd see a `napari` folder and a `napari_cli.py` file).  We'd have to use absolute imports...  I can make up and example PR.  but maybe @jni has thoughts first?

**Comment by sofroniewn** [comment]
Ok, sounds good, let's hear from @jni first before you start. In theory I'm supportive, but want to make sure we don't add a lot of complexity too

**Comment by tlambert03** [comment]
I don't see it as any more or less complex... just different.  The need for something like this has actually came up once before in https://github.com/napari/napari/pull/814.

**Comment by jni** [comment]
Oh right I remember this. Sorry I missed this the first time around. I don't love the idea of a separate module/package. @tlambert03 is it not possible to restructure `napari/__init__.py` to make the pythonw switch earlier? ie rather than have a separate package, front-load the stuff you want in that package into the `__init__`? Or am I missing something?

**Comment by jni** [comment]
ie looking at above:

```
# __main__.py inside of napari folder with pythonw available.
napari.__INIT__      0.0000
__main__.main        0.7533
__main__._run_pyw    0.7534
napari.__INIT__      1.0260
__main__.main        1.7832
__main__._run        1.7832
viewer.show          2.8128
```

Could we not shortcut the first _main and _run_pyw calls?

**Comment by tlambert03** [comment]
with #2662 merged... this is not so much of an issue anymore
