### ISSUE TITLE
Points layer allows panning when in Add mode

### ISSUE THREAD

**Issue by ianhi** [napari/napari#2373]
## 🐛 Bug
When in the `Add Points` mode on a points layer panning is not prevented. This can make it tricky to label a point as you have to hold the mouse perfectly still.

![Peek 2021-03-08 13-26](https://user-images.githubusercontent.com/10111092/110364681-111fde80-8012-11eb-8a22-65e5451c87fd.gif)

In contrast the `pick` mode of a labels layer prevents panning.

## To Reproduce
1. Open napari
2. Add a points layer
3. Move mouse around and then click

Alternatively:
`python examples/nD_points.py`

## Expected behavior
Clicking when in `Add Points` mode will not allow panning, the same as when when in `Pick` mode for a labels layer.

## Environment

```
napari: 0.4.7.dev14+gc473058
Platform: Linux-5.8.0-7630-generic-x86_64-with-glibc2.31
System: Pop!_OS 20.04 LTS
Python: 3.9.1 | packaged by conda-forge | (default, Jan 26 2021, 01:34:10) [GCC 9.3.0]
Qt: 5.15.2
PyQt5: 5.15.2
NumPy: 1.19.5
SciPy: 1.6.0
Dask: 2021.01.1
VisPy: 0.6.6

OpenGL:
- GL version: 4.6 (Compatibility Profile) Mesa 20.2.6
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1080, scale 1.0

Plugins:
- console: 0.0.3
- svg: 0.1.4
```

**Comment by sofroniewn** [comment]
Agreed @ianhi. This was recently added in #2148 after a request in #2146, but the threshold for dragging is too sensitive. We might be able to overwrite the threshold in vispy and increase it? I'm not sure if @VolkerH or @jni have further ideas

**Comment by VolkerH** [comment]
This is what I mentioned in the PR  #2148 as

> One potentially unwanted side effect is that "fly-by" adding of points is no longer possible, i.e. the mouse pointer must
> come to a halt before clicking

As I noticed the potential issue at the time I remember thinking briefly for workarounds, but I would have to dig deeper into the code again and I don't think I have time. The previous behaviour was worse IMO though, when working with images that were substantially larger then the example shown above. I guess it depends what one wants to achieve: accurately marking points on a large canvas or flyby clicking a few points on a smaller canvas (I'm thinking space invaders). Ideally the behaviour would support both.

**Comment by sofroniewn** [comment]
We could adjust the https://doc.qt.io/qt-5/qstylehints.html#startDragVelocity-prop (or https://doc.qt.io/qt-5/qstylehints.html#startDragDistance-prop) to try and find a better value. I wonder if this can be done just for the canvas, or it can only be done at the application level (cc @tlambert03 @goanpeca)
