### ISSUE TITLE
Error Pop Up should  be copypasteable

### ISSUE THREAD

**Issue by ianhi** [napari/napari#2375]
## 🚀 Feature

The toast notification that pops up on an error have selectable text or a button/context menu option to copy the error message.

![Peek 2021-03-08 15-09](https://user-images.githubusercontent.com/10111092/110375699-50552c00-8020-11eb-9187-cd9cae019538.gif)

## Motivation
If you run into an error message that napari consumes and doesn't allow to print the terminal it is very nice to be able to copy paste in order to google.

## Pitch
One or multiple of:
1. Make toast pop up text selectable
2. button to copy the text
3. context menu to copy

## Alternatives
Napari notifies of the error message but also allows it propogate through to the terminal that is running the script.

**Comment by tlambert03** [comment]
Hi @ianhi, the in-app presentation of errors and messages is in active development (see #2205 and related discussions).  We will definitely be providing an easier way to copy/share an error soon.

**Comment by tlambert03** [comment]
on the latest napari release, you may wish to use the environment variable `NAPARI_CATCH_ERRORS=0` to simply avoid the in-app notifications

**Comment by ianhi** [comment]
Thanks for the tip Talley!

The one other issue with I noticed is that line number of the errors are being hidden.

**Comment by tlambert03** [comment]
also being worked on!  thanks!  (that little notification you're showing there will never have extensive error info.  But it will be clearer how you're supposed to see the full traceback)

**Comment by liaprins-czi** [comment]
Just checking on the status of this issue:
Has it (the ability to select the text to copy and paste it) been implemented with any subsequent releases?
If not, is it possible to make the text selectable for (copy-paste purposes) or is there some technical reason preventing this or making it less than feasible?
If it's not feasible to make the text selectable, I can work on a design for ability to "copy" via a button or similar
