### ISSUE TITLE
Idea to speed up labels rendering

### ISSUE THREAD

**Issue by jni** [napari/napari#2380]
## 🚀 Feature

One reason why labels rendering is slow is that every time we update `data`, we run the *whole* image through [`napari.utils.colormaps.colormap_utils.low_discrepancy_image`]()

In fact, we can do better in two ways:

(1) if we know all the values in the array, we can run only those values, and use numpy indexing to speed up rendering about 2x:

```python
In [6]: from napari.utils.colormaps import colormap_utils as cu

In [7]: image = np.random.randint(0, 5, size=(2048, 2048))

In [8]: %timeit cu.low_discrepancy_image(image)
136 ms ± 17.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [9]: %timeit cu.low_discrepancy_image(np.arange(5))
41.5 µs ± 1.97 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)

In [10]: colors = cu.low_discrepancy_image(np.arange(5))

In [11]: %timeit colors[image]
68 ms ± 3.8 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

This is very useful e.g. for sparse arrays, CC @DragaDoncila. ~~Note we can also use [`skimage.util.map_array`](https://scikit-image.org/docs/dev/api/skimage.util.html#skimage.util.map_array) for this purpose.~~ **Edit:** scrap that, currently that is way slower than the array indexing construct... 235ms in the above example.

(2) if we have already created the label image and we are modifying it, we can update *only the modified locations* in the resulting array. ie, rather than doing a full refresh() after painting, only update the necessary pixels. The undo/redo machinery from #2339 could be very useful for this.

**Comment by DragaDoncila** [comment]
This is something I see as critical for the labels layer. For example, the performance issues with painting into large images are not ameliorated by using a sparse data structure because the rendering is still so slow.

**Comment by sofroniewn** [comment]
This would be closed by #2415

**Comment by DragaDoncila** [comment]
@sofroniewn technically #2415 only closes idea 1. 

Idea 2 - only refresh painted pixels would be a separate PR. However, in the context of #2416 I'm curious as to whether you think this partial refresh would still be worth it?

**Comment by sofroniewn** [comment]
> However, in the context of #2416 I'm curious as to whether you think this partial refresh would still be worth it?

Yes very much so - in the context of #2416 though it become about just invalidating and redrawing the tiles where data has changed.

We basically need to add a method to each chunk to say if any of a list of coordinates is inside and then have a way to make those coordinates available to the chunk after painting. Will be pretty cool when it works!!

**Comment by DragaDoncila** [comment]
Sorry, should've been more clear.

>invalidating and redrawing the tiles where data has changed.

Totally agree with this. Specifically what I meant was that we would want to be redrawing the full invalidated tile, rather than strictly the pixels which were painted, which I think is what this issue is suggesting

**Comment by jni** [comment]
Just came across another option here, could be very nice! From this blog post:

https://lemire.me/blog/2016/06/27/a-fast-alternative-to-the-modulo-reduction/

```python
In [3]: image = np.random.randint(0, 5, size=(2000, 2000)).astype(np.int32)

In [4]: %timeit image % 256
272 ms ± 17.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [5]: %timeit ((image.astype(np.int64) * 256) >> 8).astype(np.uint8) ^ 123
35.3 ms ± 2.06 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [6]: %timeit ((image * 256) >> 8).astype(np.uint8) ^ 123
19 ms ± 65.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [7]: vals = np.random.random(5)

In [8]: %timeit vals[image]
111 ms ± 5.28 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [9]: from napari.utils.colormaps import colormap_utils as cu

In [10]: %timeit cu.low_discrepancy_image(image)
200 ms ± 2.79 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

Entries 5 and 6 are the key: they give "random" numbers in 0-256. We can then give those directly to VisPy for vis. The only downside is that we need label information in the bottom 16 bits. If the input labels are `2**16 * i` for i in some range, they will all map to the same value. But honestly I think that is an ok compromise, especially given a nearly 10x speedup from our original baseline and 5x from our current baseline.

The other cool thing about this method is that the shuffling given by the seed (`xor 123`) is an actual shuffle, rather than a shift in 0-1. So our "shuffle" button's functionality should be better than before.

**Comment by sofroniewn** [comment]
I think this is ok, i'm supportive of giving it a try. Could you give the outputs of the labels benchmarks too - before and after - which include some images different sizes, and could help give a sense of the real world impact

**Comment by andy-sweet** [comment]
I did some experiments trying to speed up skimage's `map_array`, but it looks like the alternatives to `std::unordered_map` probably aren't fast enough for this issue and that we seem to have some more promising approaches.

**Comment by psobolewskiPhD** [comment]
@jni is this still an issue with the new labels-on-GPU stuff?
Do you have a script to test with an actual labels layer?
