### ISSUE TITLE
incorrect version in filename of MacOS bundle

### ISSUE THREAD

**Issue by neuromusic** [napari/napari#2386]
## 🐛 Bug

The filename of the dmg to install the MacOS bundled app has the version coded as "0.0.1" in the filename

## To Reproduce

1. Download the [v0.4.6](https://github.com/napari/napari/releases/tag/v0.4.6) MacOS bundle
2. unzip the file

![image](https://user-images.githubusercontent.com/1245615/110504132-189ac280-80ba-11eb-8268-31022acf401e.png)

## Expected behavior

I expected the dmg file to have the same version as the zip file (and the napari version)

**Comment by jaimergp** [comment]
I don't see this happening anymore:

<img width="227" alt="Screen Shot 2021-08-31 at 3 51 40 PM" src="https://user-images.githubusercontent.com/2559438/131514839-d1b6268c-44fe-4052-869b-4bcbc7e8d440.png">

I think it can be closed.
