### ISSUE TITLE
Extra clicking needed to change focus

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#239]
## 🐛 Bug

Extra clicking is now needed to change focus when moving between different parts of the Qt application since the new styles #236. This occurs on my mac OSX, but doesn't seem to happen on @freeman-lab mac OSX - we will need to see which versions of `Qt`, `PyQt5` etc we each have.

**Comment by sofroniewn** [comment]
To reproduce run `examples/add_shapes.py`. You should see the magnifying glass selected on the left in the control panel. Now click on the cursor symbol. On my machine the first click does nothing. If I then click again the cursor gets selected.

For an even stranger example - also run `examples/add_shapes.py`, but now click on the move_to_front button. If you then move the mouse away the button will remain highlighted as if you are hovering when you are not. If you click again it will return to normal.

Similar behavior can be seen if clicking into the layers list on the right or into the viewer into the center. Sometimes clicking in the viewer in the center can lock me into a weird pan mode.

It's really not clear to me what changed in #236 to cause this, nor how to fix it. I've tried a bunch of things including `focusPolicy`, `setWindowModality`, `setMouseTracking`, but none work.

Also I heard from @freeman-lab that he doesn't experience this on his mac. I tried `pip install --upgrade pyqt5` but I am already up to date.

Does anyone else experience this bug?

**Comment by sofroniewn** [comment]
I will note that I also have a double title-bar when I run napari and @freeman-lab does not. These could be unrelated, but it is also strange that there are any differences for us.

See the extra title-bar
![image](https://user-images.githubusercontent.com/6531703/57006229-e4881980-6b93-11e9-98c4-2bb79bb76e82.png)

I will note that I've always had that extra toolbar line, but it wasn't so noticeable before, nor was it causing any problems

**Comment by kne42** [comment]
Unable to reproduce on my machine. Output of `conda list | grep qt` is
```
pyqt5                     5.12                     pypi_0    pypi
pyqt5-sip                 4.19.14                  pypi_0    pypi
qtpy                      1.7.0                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.2                    pypi_0    pypi
```

**Comment by kne42** [comment]
is `PySide2` installed? what is the result of `python -c "import qtpy; print(qtpy.API_NAME)"`

**Comment by sofroniewn** [comment]
I've uninstalled `PySide2` - but I don't think that was the issue as I noticed this before the `qtpy` PR merged and I get `PyQt5` when I run the command above.

I do however get something different when I run `conda list | grep qt`:
```
pyqt                      5.6.0            py36he5c6137_6
qtawesome                 0.4.4            py36h468c6fb_0
qtconsole                 4.3.1            py36hd96c0ff_0
qtpy                      1.3.1            py36h16bb863_0
```

I'm not quite sure why, but this is what I see!

**Comment by sofroniewn** [comment]
Ah if I make it `Q` I get more, `conda list | grep Qt`
```
PyQt5                     5.12.1                    <pip>
PyQt5_sip                 4.19.15                   <pip>
```

**Comment by sofroniewn** [comment]
So I completely deleted python from my laptop (which happened to be 3.6), `rm -rf` my anaconda folder, then installed python 3.7 using anaconda, then `pip install -e .` on the napari repo and it is still broken :-(

So strange to me that no one else can reproduce. Here's my `conda list | grep qt`

```
pyqt                      5.9.2            py37h655552a_2
pyqt5                     5.12.1                   pypi_0    pypi
pyqt5-sip                 4.19.15                  pypi_0    pypi
qt                        5.9.7                h468cd18_1
qtawesome                 0.5.7                    py37_1
qtconsole                 4.4.3                    py37_0
qtpy                      1.7.0                    py37_1
```

I'm really at a loss

**Comment by sofroniewn** [comment]
I tried rolling back to `pyqt5 5.12` and `pyqt5-sip 4.19.14` but that didn't help

I also updated all my mac OSX software with the following
![image](https://user-images.githubusercontent.com/6531703/57060891-de676b00-6c6f-11e9-8e5b-05c452c14493.png)
but note that I am still on mac OS Sierra 10.12.6

Maybe I need to update to macOS Mojave and 10.14.3, but that would be a little unfortunate

**Comment by sofroniewn** [comment]
Something else strange. If I comment out most of the stylesheet stuff that was new in #236 the problem doesn't go away, and more strange if I roll back to an older version of napari the problem is still there despite the fact that I never noticed it before ....

**Comment by sofroniewn** [comment]
I have updates to macOS Mojave, 10.14.4, and updated to Xcode 10.2.1 but nothing has gotten better, I still have the same problem :-(

**Comment by jni** [comment]
Sorry to hear about all your issues @sofroniewn! As mentioned in the conference call, one more thing to try is to create a new user account and see whether you see the problem there. That might narrow down *where* in you stack the problem is happening.

**Comment by sofroniewn** [comment]
@jni progress!! Creating a new user account fixes the problems - both the extra title bar and the weird clicking!!! At least we now have something to work with :-)

**Comment by jni** [comment]
Woot! To me it feels like it might be an issue with your Qt install. You should make sure that PyQt is picking up the Qt from the new conda environment you're creating and not some other user-level Qt install — maybe you installed Qt separately as a framework on another occasion? Check your `/Library/` for suspicious items. I don't know whether PyQt has a way to easily introspect this...

**Comment by jni** [comment]
It could also be something that is global-level but relies on your bashrc messing with your PATH/LDLIBRARYPATH, e.g. Homebrew. Try backing up and removing your bashrc? As a reminder, you can call a conda env's Python without activating by specifying the full path to the python binary.

**Comment by sofroniewn** [comment]
Unfortunately @jni I've been able to make no further progress. I'm having a hard time determining which Qt version is getting used by PyQt, and how many Qt versions I have on my computer. I did `brew update qt` and it didn't change anything, then I did `brew uninstall qt` and it didn't change anything either, so I guess it was using a `Qt` in the anaconda folder. I then tried directly installing `Qt` from the Qt website, but that doesn't seem to have changed anything either.

I also deleted my `bashrc` with no effect.

I'm not quite sure what to try next, but I at least have hope. Also googling the "double title bar pyqt` turns up nothing useful so that part at least doesn't seem to be a common problem

**Comment by jni** [comment]
Two other things to try:

- if you install and run Spyder, do you see a double title bar?
- if you create a tiny Qt app with a simple push button ("click to print hello world"), do you see a double title bar?

There might also be some macOS display preference, such as "hide scroll bar by default", that is affecting things.

A few things I've found that might be relevant:

https://doc.qt.io/qt-5/macos-issues.html

This one in particular is super-suspicious:
https://doc.qt.io/qt-5/qmainwindow.html#unifiedTitleAndToolBarOnMac-prop

You should also wipe and re-clone your napari repo — doing so is what made my dim slider issue disappear, nothing else worked. And check your home directory for .files that might contain/affect Qt settings.

**Comment by sofroniewn** [comment]
Trying to launch spyder already throws me an error

```
 spyder
objc[50112]: Class RunLoopModeTracker is implemented in both /anaconda3/lib/python3.7/site-packages/PyQt5/Qt/lib/QtCore.framework/Versions/5/QtCore (0xb1aaaa270) and /anaconda3/lib/libQt5Core.5.dylib (0xb222a9a80). One of the two will be used. Which one is undefined.
Traceback (most recent call last):
  File "/anaconda3/bin/spyder", line 11, in <module>
    sys.exit(main())
  File "/anaconda3/lib/python3.7/site-packages/spyder/app/start.py", line 186, in main
    from spyder.app import mainwindow
  File "/anaconda3/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 90, in <module>
    from qtpy import QtWebEngineWidgets  # analysis:ignore
  File "/anaconda3/lib/python3.7/site-packages/qtpy/QtWebEngineWidgets.py", line 22, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEnginePage
ValueError: PyCapsule_GetPointer called with incorrect name
```

**Comment by sofroniewn** [comment]
I also get that Spyder error on my new clean username after pip installing napari. Would get good to chase down as a separate issue if napari is not compatible with spyder.

I also get the double title bar with a tiny Qt app

**Comment by sofroniewn** [comment]
So `self._qt_window.setUnifiedTitleAndToolBarOnMac(True)` inside the window view file makes the double titlebar go away, but it doesn't fix my clicking issue, which was also fixed on the new user

**Comment by jni** [comment]
Since none of us had the double titlebar problem, this does suggest to me that you have some default Qt settings *somewhere* that are different from ours. This could be due to a different Qt version being used, or a hidden/cached config file somewhere.

**Comment by sofroniewn** [comment]
This issue hasn't reappeared again, and I think I may have gotten so used to it I don't notice anymore so I will close, but if others start to see similar problems we can re-open
