### ISSUE TITLE
Labels Brush Size Potentially Unbounded

### ISSUE THREAD

**Issue by ianhi** [napari/napari#2393]
## 🐛 Bug

It is possible to make a labels layer `brush_size` arbitrarily large by using the `+=` operator. Normal assignment of the property seems to cap the value at 40, but this can be overcome when using `+=` as in the script below. This can lead to the brush size going off the canvas:
![image](https://user-images.githubusercontent.com/10111092/110580809-60136400-8137-11eb-97d2-bd8f8d7cfc1f.png)

and also lead to screen wide graphical errors blacking out all the rest of my screen:
![image](https://user-images.githubusercontent.com/10111092/110580850-73beca80-8137-11eb-8615-8d83a8c342a0.png)

## To Reproduce

```python
import napari
import numpy as np


with napari.gui_qt():
    arr = np.zeros([512, 512])
    arr1 = np.zeros([512, 512])

    viewer = napari.view_image(arr)

    labels = viewer.add_labels(arr1, name='labels_1')

    # Set the labels layer mode to picker with a string
    labels.mode = 'paint'
    print(labels.brush_size) # 10
    # this seems protected
    labels.brush_size = 2500
    print(labels.brush_size) # 40
    labels.brush_size += 5
    print(labels.brush_size) # 45
    def scroll_callback(layer, event):
        if event.delta[1] > 0:
            labels.brush_size += 5
        else:
            labels.brush_size = max(labels.brush_size - 1, 1)

    labels.mouse_wheel_callbacks.append(scroll_callback)
```

Then scroll the mouse wheel a bunch to make the brush size large.

## Environment

```
napari: 0.4.7.dev15+gdff1675.d20210308
Platform: Linux-5.8.0-7630-generic-x86_64-with-glibc2.31
System: Pop!_OS 20.04 LTS
Python: 3.9.1 | packaged by conda-forge | (default, Jan 26 2021, 01:34:10) [GCC 9.3.0]
Qt: 5.15.2
PyQt5: 5.15.2
NumPy: 1.19.5
SciPy: 1.6.0
Dask: 2021.01.1
VisPy: 0.6.6

OpenGL:
- GL version: 4.6 (Compatibility Profile) Mesa 20.2.6
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1080, scale 1.0

Plugins:
- console: 0.0.3
- svg: 0.1.4
```

**Comment by ianhi** [comment]
I think that ideally any solution for this would not simply limit the maximum brush size but would instead deal with clipping of the brush when it is outside the canvas. I'd like to keep it unlimited as I find that the default limit is often too small for me and a larger one would then likely be too small for someone else..

**Comment by jni** [comment]
I love your jumbo brush! :joy: 

Note that the brush size limitation could be overcome if we implement @VolkerH's suggestion of zoom independent brush size (so zooming out increases your effective brush size). see #1419

**Comment by psobolewskiPhD** [comment]
I think this is largely fixed with the new overlay brushes:
https://github.com/napari/napari/pull/5763
(note in the code in the OP the dtype of the array needs to be specified, because default is float64)
plus open PR to lift the brush size cap:
https://github.com/napari/napari/pull/5761

Would be cool to be able to bind mousewheel+modifier to the now-repeatable current brush size keybindings (https://github.com/napari/napari/pull/5086) in the GUI.
In the meantime, there is this PR that implements photoshop-like brush resizing by moving mouse with modifier:
https://github.com/napari/napari/pull/5753
