### ISSUE TITLE
Creating examples folder

### ISSUE THREAD

**Issue by AhmetCanSolak** [napari/napari#24]
Currently we have a `demo.py` in the root. This should change and we should have examples folder in the root and examples in it.

**Comment by kevinyamauchi** [comment]
With #21, I moved demo.py and the marker layer demo notebook into a folder called "demo". Feel free to change the name to examples if you prefer.

**Comment by kevinyamauchi** [comment]
As of #44, master has an examples folder, which includes demo.py
