### ISSUE TITLE
Cancel doesn't work on preference dialog

### ISSUE THREAD

**Issue by ppwadhwa** [napari/napari#2405]
## 🐛 Bug

The cancel button on the preferences dialog isn't working properly.  I think its possible that the function I removed in the last PR that I thought was unnecessary was actually necessary. 
## To Reproduce

1.
2.
3.

## Environment

 - Please copy and paste the information at napari info option in help menubar here:

 - Any other relevant information:

**Comment by sofroniewn** [comment]
No worries, fixing in a followup sounds good. thanks for making the issue

**Comment by ppwadhwa** [comment]
I just found the problem.  It wasn't the function that I thought.  I will get it done this weekend!
