### ISSUE TITLE
Default layer selection logic

### ISSUE THREAD

**Issue by jni** [napari/napari#241]
## ❓ Questions and Help

By default, as far as I can tell, all layers are selected as they are added to the viewer. In all of the examples, whenever there is more than one layer, they all appear selected. I think this is unintuitive, and it particular it means that layer reordering feels broken by default (because we need to click to select first, and only then can we reorder).

I think the selection should be *empty* before any clicks. Does anyone feel differently? Was this a conscious design choice? Sorry if I am behind the curve here.

**Comment by sofroniewn** [comment]
Agreed, wasn't really a conscious design choice, was just sort of the way it worked out and we havn't fixed.

How about when you add a new layer that layer is selected and all the others become unselected. That seems most intuitive to me.
