### ISSUE TITLE
Convert napari.types.ImageData to itk.Image for plugin

### ISSUE THREAD

**Issue by ViktorvdValk** [napari/napari#2425]
## 📚 Documentation

How do I convert the napari.types.ImageData returned by the napari viewer to a data type that I can use in itk.
I'm currently writing a plugin for an itk-elastix, but the napari.types.ImageData seems not to be excepted by itk.

```python
@magic_factory(call_button="register", transform = {"choices": ["rigid", "affine", "bspline"]})
def register(fixed: 'napari.types.ImageData', moving: 'napari.types.ImageData', transform: str) -> 'napari.types.LayerDataTuple':
 
    result_image, result_transform_parameters = itk.elastix_registration_method(
        fixed, moving)

    return np.asarray(result_image).astype(np.float32), {'name':transform + ' Registration'}
```

**Comment by tlambert03** [comment]
`napari.types.ImageData` is not so much a custom type, it is a type _annotation_ that tells magicgui to deliver to the function the `layer.data` attribute of the layer currently selected in the widget.  In most cases, `layer.data` on an image layer is just a numpy array (with perhaps the exception of multi-resolution data).  So in your example above, `fixed` and `moving` are just numpy arrays.  I'm not sure what types itk is looking for though...

```python
@magic_factory
def register(fixed: 'napari.types.ImageData'):
	print(type(fixed))  # np.ndarray
```


see related documentation here:
https://napari.org/guides/stable/magicgui.html#annotating-as-napari-types-data

**Comment by ViktorvdValk** [comment]
Thanks for the quick responds. 
Napari returned a imageio.core.util.Array, which I managed to convert to ITK readable format with numpy.

**Comment by tlambert03** [comment]
Interesting... What was the image layer?  Was a reader plugin being used?

**Comment by ViktorvdValk** [comment]
No, I just opened a .mha file with a fresh Napari install without any reader plugin (at least not installed by me).

**Comment by tlambert03** [comment]
huh... I just dragged an `.mha` file (from the [ITK Example data](https://github.com/InsightSoftwareConsortium/ITK/tree/master/Examples/Data) into napari and got the "no plugin capable of reading..." error).  Just cause I'm curious about what's turning this into an  `imageio.core.util.Array`, can you copy the output of `napari --info` here for me? (or, if you're on a recent master version of napari, you can also provide `napari --plugin-info`)

**Comment by tlambert03** [comment]
@sofroniewn, @jni, this does generally highlight an eventual issue that we might have in our "goal" of having napari-assisted processing pipelines.  Inasmuch as we accept heterogeneous data inputs to something like an `Image` layer  (i.e. numpy array, multiresolution list of arrays, dask array, etc...) that we _don't_ necessarily normalize internally, it does make the concept of an analysis plugin that "takes an `Image` and returns an `Image`" much more complicated.  I know that normalization task is no easy feat (and nothing new), but just noting that here.

**Comment by ViktorvdValk** [comment]
napari: 0.4.6
Platform: Windows-10-10.0.19041-SP0
Python: 3.9.2 (default, Mar  3 2021, 15:03:14) [MSC v.1916 64 bit (AMD64)]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.20.1
SciPy: 1.6.1
Dask: 2021.03.0
VisPy: 0.6.6

OpenGL:
  - GL version:  4.6.0 NVIDIA 456.71
  - MAX_TEXTURE_SIZE: 32768

Screens:
  - screen 1: resolution 2880x1800, scale 1.0
  - screen 2: resolution 5120x2880, scale 1.0

Plugins:
  - console: 0.0.3
  - itk-elastix_napari: 0.1.dev5+g5cde6ab.d20210318
  - svg: 0.1.4

**Comment by ViktorvdValk** [comment]
PluginManager for "napari"
(10 hook specs and 4 plugins)
---------------------------------------------
builtins v0.4.6                       6 hooks
  - napari_get_reader
  - napari_get_writer
  - napari_write_image
  - napari_write_labels
  - napari_write_points
  - napari_write_shapes

console v0.0.3                        0 hooks

itk-elastix_napari v0.1.dev5+g5cde6ab.d20210318    1 hooks
  - napari_experimental_provide_dock_widget

svg v0.1.4                            6 hooks
  - napari_get_writer
  - napari_write_image
  - napari_write_labels
  - napari_write_points
  - napari_write_shapes
  - napari_write_vectors

**Comment by tlambert03** [comment]
thanks!  sorry to belabor this, I'm just curious.  How are you getting the `.mha` file into napari?  drag-drop?  custom script?  `viewer.open`?

**Comment by ViktorvdValk** [comment]
I run napari from the command line and then I load the images from the menu (File -> Open File(s) ...)

**Comment by ViktorvdValk** [comment]
And just a completely different question wrt the plugin layout.
how do I make the plugin load automatically on the bottom panel of napari (right seems default now for me)
and how do I increase the font size of the plugin text?

**Comment by tlambert03** [comment]
> how do I make the plugin load automatically on the bottom panel of napari 

the [`napari_experimental_provide_dock_widget`](https://napari.org/plugins/stable/hook_specifications.html#napari.plugins.hook_specifications.napari_experimental_provide_dock_widget) spec also allows you to return a tuple `(callable, options)` where `options` is a dict of key/value pairs that will be passed to [`viewer.window.add_dock_widget`](https://github.com/napari/napari/blob/master/napari/_qt/qt_main_window.py#L790).  To put something at the bottom, you can do:
```python
    return register, {'area': 'bottom'}
```

**Comment by tlambert03** [comment]
> I run napari from the command line and then I load the images from the menu (File -> Open File(s) ...)

welp, color me perplexed :) I'm really not familiar with the mha format, but when I try to do this using the mha files from the ITK examples, it doesn't work.  we don't need to dig into this if you're happy and your application is working again, I was just curious what might be turning `layer.data` into a `imageio.core.util.Array`.  @jni, @sofroniewn ... do you have any ideas here?

**Comment by ViktorvdValk** [comment]
Unfortunately replacing `return register` with `return register, {'area': 'bottom'}`  causes the plugin to crash, also when I put brackets around the output.

**Comment by tlambert03** [comment]
> and how do I increase the font size of the plugin text?

there isn't a direct API to do that at the moment.  For many specific style adjustments, you'd have to directly modify the Qt widget backing the magicgui widget (or just directly provide a `QWidget`).  With `magic_factory` that's a bit tricker, since you need to do it _after_ the widget is created by napari.  Here's a rough idea:

```python
def on_init(widget):
    # widget.native is a QWidget, and you can use anything from the 
    # Qt API: https://doc.qt.io/qt-5/qwidget.html
    widget.native.setStyleSheet("QWidget{font-size: 20pt;}")

@magic_factory(widget_init=on_init)
def func(first: int, second: str):
	...
```

**Comment by tlambert03** [comment]
> Unfortunately replacing return register with return register, {'area': 'bottom'} causes the plugin to crash, also when I put brackets around the output.

can you give me more info, like a stack trace, or anything it might say in the console?  I just pip installed your github repo and changed your implementation to this and it worked:
```python
@napari_hook_implementation
def napari_experimental_provide_dock_widget():
    return register, {'area': 'bottom'}
```

**Comment by tlambert03** [comment]
> I was just curious what might be turning layer.data into a `imageio.core.util.Array`

ok, figured this out.  It's the presence of ITK in the environment.  right [here in imageio](https://github.com/imageio/imageio/blob/187578526a5791dee813bd7546324169d3236dac/imageio/core/functions.py#L178), the format of the mha open request is determined to be `imageio.plugins.simpleitk.ItkFormat`, and it looks like `imageio.plugins.simpleitk.ItkFormat.Reader` returns its data as a `imageio.core.util.Array`

**Comment by ViktorvdValk** [comment]
Yes, sorry. Found a typo.
Thanks a lot for the help

**Comment by tlambert03** [comment]
no problem!  Thanks for raising awareness of the remaining type ambiguities on `Image.data` :)

**Comment by sofroniewn** [comment]
Yeah, just catching up on this thread - seemed like a great discussion - and agreed with all points around challenges of a plugin ecosystem when the `data` object and be so heterogeneous, will be something to discuss more!
