### ISSUE TITLE
clim slider disappears when image layer is renamed

### ISSUE THREAD

**Issue by d-v-b** [napari/napari#243]
## 🐛 Bug

When I rename an image layer, the clim slider disappears.

## To Reproduce

run `examples/nD_image.py` and rename the image layer to "Tane", or a name of your choice.

## Expected behavior

clim slider shouldn't have layer-name-dependent behavior

## Environment

 - napari : 0.0.6+33.g7b8750f
 - OS: OSX 10.12.6:
 - Python version: 3.7.3

**Comment by d-v-b** [comment]
Update! there actually is no layer-name-dependent behavior. _Deselecting the image layer_ made the clim slider disappear (probably as it should). After renaming the layer, I clicked on the image layer itself (to escape the focus of the layer name textbox), and this also deselected the layer, which made me _think_ the layer rename was making the clim slider disappear. I'm not sure what kind of issue this is -- maybe escaping focus of the layer name textbox shouldn't also deselect the layer?

**Comment by sofroniewn** [comment]
hmm, we've just updated some of our stylings. Can you try how it feels on the latest (v0.0.8 from pip is fine). I'm curious if it is still confusing / deselecting inappropriately - I think probably it is, but worth checking. Also you might like the new stylings! (Though note that some of the dims ordering has also changed if you have 3D data)

**Comment by d-v-b** [comment]
Yes, this phenomenon still occurs with v0.0.8. I still think it's still a bit confusing -- my instinct when clicking outside of a textbox to deselect it is that _only_ that textbox will be deselected. Current behavior is to deselect the textbox and the entire layer with the same action. 

(the new stylings look good, and I'm much happier with the new dims ordering!)

**Comment by sofroniewn** [comment]
yup, thanks @d-v-b we'll fix this

**Comment by sofroniewn** [comment]
@d-v-b this should now be fixed on master by #271. Can you give it a try and let me know if you like it

**Comment by d-v-b** [comment]
I'm still seeing that same issue on the latest version

**Comment by sofroniewn** [comment]
Just discussed this with @d-v-b - the functionality is now such that clicking within the layer properties when editing text will deselect the text and leave the layer selected. However, clicking elsewhere in the layers panel will both deselect the text and unselect the layer. I don't find this particularly unintuitive, but a majority of users might disagree and think that only the text should be deselected and the layer should remain selected.

We plan to do more through a more thorough review of our interactivity for our `0.2` release, and as there are now plans to work on this further right now I will close this issue.
