### ISSUE TITLE
Ctrl+W no longer works for closing the napari window

### ISSUE THREAD

**Issue by jni** [napari/napari#2445]
## 🐛 Bug

I guess this one probably snuck in during the action manager refactor? If I try `Ctrl+W` on an open napari window I now get the message:

```
WARNING: QAction::event: Ambiguous shortcut overload: Ctrl+W
21:43:18 WARNING QAction::event: Ambiguous shortcut overload: Ctrl+W
```

and nothing happens.

**Comment by jni** [comment]
This is on Linux, haven't yet tested on macOS

**Comment by ppwadhwa** [comment]
I just checked on my mac, and it closes with Cmd+W.

**Comment by goanpeca** [comment]
I introduced this with the work on https://github.com/napari/napari/pull/2397

Will add a fix :)
