### ISSUE TITLE
History of last opened files 

### ISSUE THREAD

**Issue by Czaki** [napari/napari#2447]
## 🚀 Feature

It will be nice to have a list of the last opened files with one click open. 

## Motivation

When developing a new algorithm/widgets etc it will be nice to fast open one of the last files to check how it works now. 

Also when would like to discuss with someone else the result, it is nice to preview few last files. 
 

## Pitch

Add "Last files" entry to "File" menu with a list of last opened files. This list should also remember the hook used for reading a file and try to discover which hook to use only if the saved one is not 
available. 

Something like: 

![Zrzut ekranu z 2021-03-22 15-15-13](https://user-images.githubusercontent.com/3826210/112003805-8535a880-8b21-11eb-9667-bb07dc66f10f.png)

It should be preserved between sessions. 

## Alternatives

Opening napari from the console using shell history, but this not will well work with a bundle, windows `cmd` etc.

**Comment by goanpeca** [comment]
This is indeed a very nice feature!

**Comment by sofroniewn** [comment]
I'd be supportive of this. We'd probably behind the scenes have to store which "File Open ..." method was called (we have three), but that seems very doable!

**Comment by Czaki** [comment]
> I'd be supportive of this. We'd probably behind the scenes have to store which "File Open ..." method was called (we have three), but that seems very doable!

There is a need to remember exactly which function is used.

**Comment by sofroniewn** [comment]
Closed by #2467
