### ISSUE TITLE
Move the plugin sorter to the Preferences dialog

### ISSUE THREAD

**Issue by goanpeca** [napari/napari#2451]
## 🚀 Feature

![image](https://user-images.githubusercontent.com/3627835/112019090-1c3c3980-8afd-11eb-8057-d018826e0a71.png)

![image](https://user-images.githubusercontent.com/3627835/112019203-32e29080-8afd-11eb-8280-96701e4d21e3.png)

## Motivation

With the new preferences dialog, it probably makes sense to move these options there, and remove the entry from the Plugins menu.

## Additional context

- [ ] Move the widget to the preferences and integrate it with the preferences system, so order is restored on startup.
- [ ] Remove entry from menu

**Comment by goanpeca** [comment]
I would like to hear thoughts @napari/core-devs :) ?

**Comment by tlambert03** [comment]
I'm on board with that.  it was one of the first "options" widgets we had... but now I agree that preferences is a better place for it.  (note, it can also be accessed through the `Install/Uninstall` dialog... that can probably stay)

**Comment by goanpeca** [comment]
>(note, it can also be accessed through the Install/Uninstall dialog... that can probably stay)

Agreed

**Comment by sofroniewn** [comment]
I'd be very supportive of this too, I like the idea of unifying this with preferences. I think preserving install/ uninstall makes sense too

**Comment by ppwadhwa** [comment]
Do we want to keep the plugin sorter as a docked widget?  @liaprins-czi How should the plugin sorter option look in the preferences menu?

**Comment by goanpeca** [comment]
@ppwadhwa I would expect the plugin sorter to work as a "normal" custom preferences widget. So something like (but in the plugins page):

![image](https://user-images.githubusercontent.com/3627835/112513605-81449900-8d62-11eb-8195-7dacc8b6ddd5.png)

We can update the description and title so that it behaves and matches the other style of widgets in the preferences.

**Comment by ppwadhwa** [comment]
@goanpeca sounds good.  thanks for the reply.  will work on getting this in place!

**Comment by liaprins-czi** [comment]
Yes, I agree with @goanpeca that it should not be dockable anymore, but fit into the window like the other preferences. :+1:

**Comment by goanpeca** [comment]
@ppwadhwa can we close this one?

**Comment by sofroniewn** [comment]
Look's like it was closed by #2501
