### ISSUE TITLE
Better chunk and/or memory awareness when rolling dims

### ISSUE THREAD

**Issue by jni** [napari/napari#2468]
## 🚀 Feature
@AbigailMcGovern and I have run into the issue that we have bigger-than-RAM 3D+t data chunked into timepoints. During manual annotation we want to roll the dims to be able to look at XZ or YZ planes, but the UI does not allow one to ignore t when rolling.

This is more general, e.g. 3D data where individual planes are usable but the full dataset is larger than RAM.

There's a few, not-mutually exclusive routes that napari could take here:

- understand chunks and chunked loading, and prevent views (rolling or 2D/3D) that would result in larger-than-RAM loads.
- allow users to define axes that shouldn't be rolled
- have a "rolling" widget where one can drag and drop axes to reorder them
- something else?

**Comment by sofroniewn** [comment]
Agreed the situation here should be improved! This is something that if we improved https://github.com/napari/napari/issues/906#issuecomment-774749188 could be done with more awareness over axis labels too.
