### ISSUE TITLE
Allow adjustment of layer list/layer controls width in UI

### ISSUE THREAD

**Issue by jni** [napari/napari#2470]
## 🚀 Feature

Currently, the width of the layer list and layer controls panels is hardcoded. For the layer list at least, it would be useful to be able to make it wider, both in docked and especially in the undocked configuration.

See also [this comment](https://github.com/napari/product-heuristics-2020/issues/18#issuecomment-803757365) in napari/product-heuristics-2020#18 from @goanpeca.

**Comment by goanpeca** [comment]
>For the layer list at least, it would be useful to be able to make it wider,

I suggest we have minimum width hints, that should update based on content. Also the dockwidgets should probably be resizable?

**Comment by tlambert03** [comment]
I agree too. Was going to address this with the upcoming qt layerlist and layer tree... we can do it sooner too, but some of the style targets may be changing

**Comment by sofroniewn** [comment]
Yup, this is fine with me. Maybe we at least wait until after #2423 or its equivalent merges

**Comment by brisvag** [comment]
Closed by #4368 :)
