### ISSUE TITLE
Possible Qt-related segmentation fault when streaming with pycro-manager

### ISSUE THREAD

**Issue by yfukai** [napari/napari#2472]
## 🐛 Bug

Hi, I appreciate all the contributors to this great application, thanks!
Now I'm trying to stream the live view from pycro-manager to napari in Windows, but found a possible Qt-related segmentation fault that kills the python interpreter itself. I would like to know if this is a bug or I'm doing something wrong.

## To Reproduce

1. install `napari=0.4.6`, `pycromanager=0.7.6` via `conda`
2. launch Micro-Manager 2.0.0-gamma1 20210323 with the default MMConfig_demo.cfg, click `Tools -> Options` and check `Run server on port 4827`
3. launch the Jupyter notebook `6.3.0` from the Anaconda Prompt (anaconda3).
4. press the `Live` button in Micro-Manager to get live display
5. execute the following code in the notebook (adapted from https://napari.org/docs/0.3.8/events/threading.html )
```python
import numpy as np
from pycromanager import Bridge
import time
import napari 
from napari.qt.threading import thread_worker
from qtpy.QtWidgets import QPushButton

bridge = Bridge()
core = bridge.get_core()

with napari.gui_qt():
     viewer = napari.Viewer()

     def update_layer(new_image):
         try:
             viewer.layers['result'].data = new_image
            
         except KeyError:
             viewer.add_image(
                 new_image, name='result'
             )

     @thread_worker
     def yield_pycro_images():
         global core
         i = 0
         while True:  # infinite loop!
            tagged_image = core.get_tagged_image()
            time.sleep(0.05)
            image=np.reshape(tagged_image.pix, 
                                newshape=[-1, 
                                tagged_image.tags['Height'], 
                                tagged_image.tags['Width']])
            yield image[0,:512,:512]
     worker = yield_pycro_images()
     worker.yielded.connect(update_layer)
     # add a button to the viewew that, when clicked, stops the worker
     button = QPushButton("STOP!")
     button.clicked.connect(worker.quit)
     worker.finished.connect(button.clicked.disconnect)
     viewer.window.add_dock_widget(button)
     worker.start()
```
6. it sometimes shows the live display, sometimes kills the Python kernel.

Checking the Windows event log, I found the following error log with the exception code `0xc0000005` (which I found memory-handling related ) :

```
- System
  - Provider
   [ Name]  Application Error
  - EventID 1000
   [ Qualifiers]  0
   Level 2
   Task 100
   Keywords 0x80000000000000
  - TimeCreated
   [ SystemTime]  2021-03-26T03:02:32.066996200Z
   EventRecordID 111959
   Channel Application
   Computer DESKTOP-2PM4JFG
   Security
- EventData
   python.exe
   3.8.8150.1013
   6036cbe3
   Qt5Core.dll
   5.15.1.0
   5f506b86
   c0000005
   00000000001facf2
   437c
   01d721ec5f225638
   C:\\Users\\cellPC\\anaconda3\\python.exe
   C:\\Users\\cellPC\\anaconda3\\lib\\site-packages\\PyQt5\\Qt\\bin\\Qt5Core.dll
   17881b84-9d47-4b0e-95ce-924e97a18976

```

## Expected behavior

The cell runs without error and shows the streaming view from Micro-Manager (which happens sometimes).

## Environment

- Please copy and paste the information at napari info option in help menubar here:

```
napari: 0.4.6
Platform: Windows-10-10.0.18362-SP0
Python: 3.8.8 (default, Feb 24 2021, 15:54:32) [MSC v.1928 64 bit (AMD64)]
Qt: 5.15.1
PyQt5: 5.15.1
NumPy: 1.19.2
SciPy: 1.6.1
Dask: 2021.03.0
VisPy: 0.6.6

OpenGL:
- GL version: 4.6.0 NVIDIA 442.05
- MAX_TEXTURE_SIZE: 32768

Screens:
- screen 1: resolution 1920x1080, scale 1.0

Plugins:
- console: 0.0.3
- svg: 0.1.4

```

- Any other relevant information:
`pycromanager==0.7.6`

Thanks!

**Comment by jni** [comment]
I don't have time to reproduce right now but you're not doing something *obviously* wrong from my quick reading! One minor thing to note is that we no longer recommend the `napari.gui_qt()` context — you should instead remove the context and just call `napari.run()` at the end of the script.

Another thing I would recommend to debug this is to use `%gui qt` at the top of your jupyter notebook*, then instead of having a thread worker, use core.get_tagged_image and do the data updating in separate cells yourself, to see whether the thread worker is what's causing this rather than some other issue.

I would also suggest fiddling with the sleep timer — I wonder whether there is a race condition between creating the layer and trying to update it...? We probably take longer than 50ms to first create a layer...

*: note that this will happen automatically from 0.4.7 and up.

**Comment by yfukai** [comment]
Hi @jni, thank you for your response and suggestion! It seems that I have not updated myself with the new API, and I will try again with your recommendations to see how it will be.

> a race condition

Thanks, also this was not in my mind; I will check if this happens with longer sleeping time (like 1s)!

**Comment by yfukai** [comment]
Let me update the thread with some additional tests. I updated the test code as follows (with the waiting time 1s).
Interestingly, now the cell runs in the first run, but fails in the second run if I don't quit the `thread_worker` by the "Stop" button. If I quit the `thread_worker` before closing napari window, the code runs without error even in the second run.
Now I'm more guessing this is not the problem of napari itself but of my coding with `thread_worker`, and close the issue for now. Thanks @jni !

```python 
import numpy as np
from pycromanager import Bridge
import time
import napari 
from napari.qt.threading import thread_worker
from qtpy.QtWidgets import QPushButton
%gui qt

bridge = Bridge()
core = bridge.get_core()
viewer = napari.Viewer()

def update_layer(new_image):
    try:
         viewer.layers['result'].data = new_image

    except KeyError:
         viewer.add_image(
             new_image, name='result'
         )

@thread_worker
def yield_pycro_images():
    global core
    i = 0
    while True:  # infinite loop!
        tagged_image = core.get_tagged_image()
        time.sleep(1)
        image=np.reshape(tagged_image.pix, 
                            newshape=[-1, 
                            tagged_image.tags['Height'], 
                            tagged_image.tags['Width']])
        yield image[0,:512,:512]
worker = yield_pycro_images()
worker.yielded.connect(update_layer)
# add a button to the viewew that, when clicked, stops the worker
button = QPushButton("STOP!")
button.clicked.connect(worker.quit)
worker.finished.connect(button.clicked.disconnect)
viewer.window.add_dock_widget(button)
worker.start()
napari.run()
```
