### ISSUE TITLE
Docs not updating correctly

### ISSUE THREAD

**Issue by jni** [napari/napari#2473]
## 📚 Documentation
I randomly noticed that the 0.4.7 release notes are not on napari.org. I found the github action build for the docs and found [this interesting line](https://github.com/napari/napari/runs/2195089768?check_suite_focus=true#step:6:2294):

> WARNING: Found a content page that is not in _toc.yml: release/release_0_4_7.md.

though I'll note that it's in amongst similar lines for all releases. @kne42 do we need to update a `_toc` entry for each new docs page, or is there some autodiscovery happening that's somehow not worked here?

**Comment by sofroniewn** [comment]
I've just tried updating https://github.com/napari/docs/blob/master/index.html to include `0.4.7` but that doesn't seem to have helped. Is that index still getting used @kne42? I'm not sure.

**Comment by kne42** [comment]
I tried adding it but our tests are failing due to something with `viewer.theme = 'light'` and I'm not really sure what changed with that but it's been breaking since the 0.4.7 release. See [here](https://github.com/napari/napari.github.io/runs/2230177679?check_suite_focus=true#step:5:30) for the error output.

**Comment by tlambert03** [comment]
does this fail locally too?  or just in CI?

**Comment by kne42** [comment]
I'm unable to run it locally since I'm having issues with `py.test` even in a fresh environment 🤷‍♀️

**Comment by tlambert03** [comment]
to be totally honest, I think we should drop the testing before building the docs for now.  It's a nice idea in principle, but it's too brittle at this point using nbval, and it's far more important to actually have docs online that to make sure that we haven't broken a small API somewhere (which, frankly, should be covered in napari tests anyway).  I'd turn that feature off, make an issue, and debug that before turning them on again.  (And preferably, drop our ipynb and nbval altogether)

**Comment by kne42** [comment]
okay well I made it so that failing the tests won't make it not build the docs, also suspiciously this new build works sooooooooo

python stuffs

**Comment by jni** [comment]
@kne42 hilarious and awesome catching up on this thread. 😂 It seems we can close this issue now?

**Comment by kne42** [comment]
not yet, I'm working on another github action to do automatic updating then we can close it

**Comment by sofroniewn** [comment]
This has now been closed by #2562
