### ISSUE TITLE
Viewer Crash when using 3D mode

### ISSUE THREAD

**Issue by Chris-N-K** [napari/napari#2476]
## 🐛 Bug
Hi and thank you all for your hard work.

I use a plugin to load images of the nifti format with included translate information. When I start napari directly from the command line with: 'napari', load an image and directly try to use the 3D mode the Viewer crashes.

The viewer does not crash if I open the iPython console, add a new layer to the viewer before clicking the  3D mode button or if I start napari out of a python console with the commands:

with napari.gui_qt():
    napari.Viewer()

## To Reproduce

1. install a plugin that loads files with translational data [add_image(translate=XXX)]
2. start napari from command line with: 'napari'
3. load an image using the napari explorer
4. click on the 3D mode button

Error messages:

WARNING: Error drawing visual <Volume at 0x7ff4112d0fd0>
11:21:03 WARNING Error drawing visual <Volume at 0x7ff4112d0fd0>
Illegal instruction

or:

WARNING: Error drawing visual <Volume at 0x7fcf7ceec760>
11:21:42 WARNING Error drawing visual <Volume at 0x7fcf7ceec760>
Segmentation fault

## Expected behavior

The viewer displayes 3D mode normally without crashing.

## Environment

napari: 0.4.4
Platform: Linux-3.10.0-1127.19.1.el7.x86_64-x86_64-with-glibc2.10
Python: 3.8.5 (default, Sep 4 2020, 07:30:14) [GCC 7.3.0]
Qt: 5.15.2
PyQt5: 5.15.2
NumPy: 1.20.1
SciPy: 1.6.1
Dask: 2021.03.0
VisPy: 0.6.6

OpenGL:
- GL version: 2.1 Mesa 18.3.4
- MAX_TEXTURE_SIZE: 8192

Screens:
- screen #1: resolution 1920x1080, scale 1.0

Plugins:
- itk-elastix_napari: 0.1.0
- napari-nifti_io: 0.1.dev11+gbaeb213
- svg: 0.1.4

**Comment by sofroniewn** [comment]
Hi @ch-n sorry to hear about this problem, and sorry for the long delay in reply! Reading the error message it sounds like something bad is going on with the rendering. I'm curious if you update to `0.4.7` if this might work for you? We've fixed a couple other things along the way, but not sure about this.

If not, could you provide a link to the plugin/ file that you're using or maybe see if you can recreate the error without needing the plugin/ file (not sure if that's really possible though). But if i was able to reproduce the bug then we could take it from there!! Thanks for filing the report

**Comment by Chris-N-K** [comment]
Hi @sofroniewn, I don't mind the delayed reply. the update to 0.4.7 seems to fix the bug. I could not recreat the bug in this version, while he happened constantly in 0.4.4.

Thanks for the unintentional fix ^^

**Comment by sofroniewn** [comment]
Ok great! I will close this issue then, if it comes up again or someone else wants to know more we could try and find the PR that fixed it, but I'm happy to leave it at this. Do let us know if you run into more problems with the latest version!!
