### ISSUE TITLE
Axes visual not updating when adding image data

### ISSUE THREAD

**Issue by alisterburt** [napari/napari#2482]
## 🐛 Bug

The axes visual does not automatically stay in sync when image data is added

A similar issue was posted on the [zulip](https://napari.zulipchat.com/#narrow/stream/212875-general/topic/issues.20with.20axes) by Uwe Schmidt, it looks like there might be more to his issue than just this though?

## To Reproduce
```python
import napari
import numpy as np

data = np.random.random((10, 20, 30))

with napari.gui_qt():
    viewer = napari.Viewer()
    viewer.dims.ndisplay = 3
    
    viewer.axes.visible = True
    viewer.add_image(data)
    viewer.camera.angles = (10, -30, 60)
    viewer.screenshot('axes_before_add_layer.png')
```
<img src="https://user-images.githubusercontent.com/7307488/112751330-47270180-8fc5-11eb-8a96-4c4afeb9310f.png" width=300>

Toggling axes on and off fixes the display/labels
```python
    viewer.axes.visible = False
    viewer.axes.visible = True
    viewer.screenshot('axes_after_add_layer.png')
```
<img src="https://user-images.githubusercontent.com/7307488/112751333-49895b80-8fc5-11eb-8aa8-d9692b0581d1.png" width=300>

adding axes once data is already in place works as expected
```python
with napari.gui_qt():
    viewer = napari.Viewer()
    viewer.dims.ndisplay = 3
    
    
    viewer.add_image(data)
    viewer.axes.visible = True
    viewer.camera.angles = (10, -30, 60)
    viewer.screenshot('axes_after_add_layer_only.png')
```

<img src="https://user-images.githubusercontent.com/7307488/112751336-4bebb580-8fc5-11eb-89a0-63ca29346f3c.png" width=300>

## Expected behavior

Axes visual should update itself when data is added to the viewer

**Comment by sofroniewn** [comment]
Looks like we might be missing some event connection to the axes visual https://github.com/napari/napari/blob/fee29a32b05499466cd2f6e9192cb0c43c92011f/napari/_vispy/vispy_axes_visual.py#L194-L203. Maybe if `ndim` changes? I'd need to look to see exactly how best to do this. We could always fall back on just updating it whenever the layer list changes, but that seems like overkill. the necessary information should be in our dims model
