### ISSUE TITLE
Documenting issues/solutions for plugin-developers when switching between napari versions

### ISSUE THREAD

**Issue by haesleinhuepf** [napari/napari#2492]
## 📚 Documentation
Hi all,

is there a place where we can collect issues and potential solutions when upgrading the napari versions our plugins support? I mean, as "migration guide" for plugin developers. ITK for example does it like [that](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Documentation/ITK5MigrationGuide.md).

I just experienced two small issues, which cost a non-python-expert like myself multiple hours. Would be cool if we could collect them somewhere in the docs.

When switching from napari 0.4.5 to 0.4.7:
1. Label-layers must be of integer type, float Label-layers are no longer allowed (see #2491)
2. If a magicgui-annotated function took an `Image` as parameter, this included 'Labels' layers in 0.4.5. In 0.4.7, developers have to change the accepted parameter type to `Layer` if they want to consume images and labels.

If there is a place where these things can live, I'm happy to file a PR and write a more clear explanation if necessary.

Otherwise the transition from 0.4.5 to 0.4.7 was pretty smooth. Thanks for your hard work!

:-)

**Comment by sofroniewn** [comment]
This seems like a great place to start. We should probably add these to the breaking changes in the release notes!! https://github.com/napari/napari/blob/master/docs/release/release_0_4_7.md#api-changes

If you could make a PR there then that would be great
