### ISSUE TITLE
Bundle extra in setup.cfg?

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#2500]
## 🚀 Feature
as pointed out by @sofroniewn  in https://github.com/napari/napari/pull/2483#discussion_r605152291, it'd be nice to move the `EXTRA_REQS` from our bundle.py into `setup.cfg` to make it clearer what is included where.  This might be made slightly complicated by the extra logic going on to when `bundle.py` is run as a script... and by what beeware needs in the pyproject.toml.  but it's a good goal!  didn't want to lose it in that thread:

https://github.com/napari/napari/blob/102a7e8f845893c874d2b86f9371d41130100b89/bundle.py#L22-L29

**Comment by sofroniewn** [comment]
When we do this we might also want to pin `scikit-image[data] >= 0.18`, see https://github.com/napari/napari/pull/2483/files#r607548848

**Comment by tlambert03** [comment]
😂  sorry about merging #2483 without that

**Comment by sofroniewn** [comment]
no worries! I'm glad you merged, easy to fix later

**Comment by jaimergp** [comment]
This was fixed a while ago, see current main.

https://github.com/napari/napari/blob/8bf7e1b2e5028be1eb620135826faf2e5046f656/setup.cfg#L150-L158

That said, it won't be as relevant now that we are using conda packaging for the bundle.
