### ISSUE TITLE
Widgets not cleaned up when using pytest and make_napari_viewer()

### ISSUE THREAD

**Issue by haesleinhuepf** [napari/napari#2520]
## 🐛 Bug

Hi @tlambert03 ,

just following up [our discussion from yesterday](https://github.com/napari/napari-plugin-devtools/issues/15#issuecomment-815248487) about testing a napari-plugin with napari GUI. I reduced my tests to [this code](https://github.com/clEsperanto/napari_pyclesperanto_assistant/blob/add_test2/napari_pyclesperanto_assistant/_tests/test_dock_widget.py):
```
def test_whatever2(make_napari_viewer):
    viewer = make_napari_viewer()
    pass
```

I receive then an error message like this locally:
```
_________________________________________ ERROR at teardown of test_whatever2 _________________________________________

qtbot = <pytestqt.qtbot.QtBot object at 0x000001AF30B4D108>

    @pytest.fixture
    def _strict_qtbot(qtbot):
        """A modified qtbot fixture that makes sure no widgets have been leaked."""
        from qtpy.QtWidgets import QApplication

        initial = QApplication.topLevelWidgets()
        prior_exception = getattr(sys, 'last_value', None)

        yield qtbot

        # if an exception was raised during the test, we should just quit now and
        # skip looking for leaked widgets.
        if getattr(sys, 'last_value', None) is not prior_exception:
            return

        QApplication.processEvents()
        leaks = set(QApplication.topLevelWidgets()).difference(initial)
        # still not sure how to clean up some of the remaining vispy
        # vispy.app.backends._qt.CanvasBackendDesktop widgets...
        if any([n.__class__.__name__ != 'CanvasBackendDesktop' for n in leaks]):
>           raise AssertionError(f'Widgets leaked!: {leaks}')
E           AssertionError: Widgets leaked!: {<PyQt5.QtWidgets.QWidget object at 0x000001AF3D25EE58>, <PyQt5.QtWidgets.QWidget object at 0x000001AF3D286678>, <PyQt5.QtWidgets.QWidget object at 0x000001AF3D248CA8>, <PyQt5.QtWidgets.QWidget object at 0x000001AF3D2BE8B8>, <PyQt5.QtWidgets.QWidget object at 0x000001AF3D234AF8>, <PyQt5.QtWidgets.QWidget object at 0x000001AF3D2DF318>, <PyQt5.QtWidgets.QWidget object at 0x000001AF3D1D0D38>, <PyQt5.QtWidgets.QWidget object at 0x000001AF3D2A8D38>, <PyQt5.QtWidgets.QWidget object at 0x000001AF3D2E9558>, <PyQt5.QtWidgets.QWidget object at 0x000001AF3D27D168>, <PyQt5.QtWidgets.QWidget object at 0x000001AF3D300B88>, <PyQt5.QtWidgets.QWidget object at 0x000001AF3D2C9DC8>, <PyQt5.QtWidgets.QWidget object at 0x000001AF3D29E1F8>}
```

And in the [github CI](https://github.com/clEsperanto/napari_pyclesperanto_assistant/runs/2295021608#step:10:20):
```
Error: Process completed with exit code 134.
```

Are these error messages related to [this issue](https://github.com/napari/napari/issues/2089)? Or is there something wrong on my side? 

Is there an example napari plugin where tests work using `make_napari_viewer`?

## To Reproduce

1. Fork/clone this branch: https://github.com/clEsperanto/napari_pyclesperanto_assistant/tree/add_test2
2. Push to github and read CI error https://github.com/clEsperanto/napari_pyclesperanto_assistant/runs/2295021608#step:10:20
3. Or: run `pytest` from command line

## Expected behavior

A simple test like this should pass

## Environment

 - Please copy and paste the information at napari info option in help menubar here:
 - napari: 0.4.7
Platform: Windows-10-10.0.19041-SP0
Python: 3.7.8 | packaged by conda-forge | (default, Jul 31 2020, 01:53:57) [MSC v.1916 64 bit (AMD64)]
Qt: 5.12.5
PyQt5: 5.12.3
NumPy: 1.19.1
SciPy: 1.5.0
Dask: 2.23.0
VisPy: 0.6.4

OpenGL:
- GL version: 4.6.0 - Build 27.20.100.9168
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1080, scale 1.0

Plugins:
- clEsperanto: 0.7.6.dev22+g1b6b7d0.d20210408
- console: 0.0.3
- svg: 0.1.4

 - Any other relevant information:

**Comment by tlambert03** [comment]
> Is there an example napari plugin where tests work using make_napari_viewer?

Hi @haesleinhuepf, I'm adding an example dock widget test to the cookiecutter: napari/cookiecutter-napari-plugin#21 ... still running into issues with the tests on the cookiecutter repo itself (on linux)... but actual repo that it generates is working fine.  Here's a an example: https://github.com/tlambert03/napari-foobar
here is the test: https://github.com/tlambert03/napari-foobar/blob/main/napari_foobar/_tests/test_dock_widget.py 
and here are the passing logs: https://github.com/tlambert03/napari-foobar/runs/2298667532?check_suite_focus=true#step:7:24

I'm still trying to figure out what's going on with assistant though...  trying stuff here: https://github.com/tlambert-forks/napari_pyclesperanto_assistant/pull/1

**Comment by tlambert03** [comment]
I think at this point we need to entertain the possibility that there's some side-effect of something installed in the pyclesperanto environment, or perhaps at import time, that's contributing to the funny Qt stuff.  I would further comment out the [`import denoise, background_removal`](https://github.com/clEsperanto/napari_pyclesperanto_assistant/pull/8/files#diff-1ebd085e84798469b8eeeefa25807dd00ba36341c85e3c0788c16bdcf5c3f97cR38) line... just in case you're potentially creating widgets or side effects during import?

**Comment by tlambert03** [comment]
> further comment out ...

but i don't think that's going to work anyway, since even in [my super-stripped down test](https://github.com/tlambert-forks/napari_pyclesperanto_assistant/pull/1/files) is failing.  so, I think I'm going to start with the working example [here](https://github.com/tlambert03/napari-foobar), and gradually build back up to the pyclesperanto environment needs

**Comment by haesleinhuepf** [comment]
> I would further comment out the [`import denoise, background_removal`](https://github.com/clEsperanto/napari_pyclesperanto_assistant/pull/8/files#diff-1ebd085e84798469b8eeeefa25807dd00ba36341c85e3c0788c16bdcf5c3f97cR38) line... just in case you're potentially creating widgets or side effects during import?

That's a good hint actually!

The tests pass locally after commenting this line out. If I bring back this line the tests fail:
```
from .._operations._operations import denoise
```

The [function I'm importing](https://github.com/clEsperanto/napari_pyclesperanto_assistant/blob/add_test2/napari_pyclesperanto_assistant/_operations/_operations.py#L56) is nothing fancy. But it's magicgui-annotated. Does magicgui create widgets before the function being called?

**Comment by tlambert03** [comment]
> Does magicgui create widgets before the function being called?

ahh, yeah that may be it (or at least some of the widgets).  `magicgui` is a factory function that returns an instance of a widget.  so yes: `decorated_func = magicgui(func)` creates a widget (and using `@magicgui` is just syntactic sugar for the same thing).  This might be something that will require special consideration.  That widgets leaked test was mostly for internal use...  it's probably too strict for general usage..

**Comment by haesleinhuepf** [comment]
No hurry. I just would like to write some tests for this little repo so that codecov doesn't look so embarassing ;-)

[![codecov](https://codecov.io/gh/clesperanto/napari_pyclesperanto_assistant/branch/master/graph/badge.svg)](https://codecov.io/gh/clesperanto/napari_pyclesperanto_assistant)

**Comment by tlambert03** [comment]
couple additional observations and tips here:

1. `make_napari_viewer` will _only_ raise an Error if new widgets were created during that test.  So as long as you import all of those operations before start the test, you should be ok...

2. It's probably going to bite you at some point that you're creating magicgui widget _instances_ up front in `_operations.py`, and then potentially trying to reuse the same widget. (for instance, have you tried your plugin across multiple viewers?  I would expect it to fail).  It would be better if you delayed the creation of those widgets to right when you need them (probably in `_activate()`. There are a few ways you can do that, but probably the easiest is for you to switch to using `magicui.magic_factory` (insead of `magicgui.magicgui`) ... and then _call_ the factory and assign a parent before using it.  In other words:

```python
# _operations.py

from magicgui import magic_factory

# do this instead of @magicgui
@magic_factory(
    auto_call=True,
    layout='vertical',
    ...


# _Assistant.py
    def _activate(self, factory):
        widget = factory()  # create the widget
        widget.native.setParent(self)   # give it a parent for proper cleanup
        LayerDialog(self.viewer, widget)
```

**Comment by haesleinhuepf** [comment]
> 2\. and then _call_ the factory and assign a parent before using it.  In other words:

I really appreciate this hint. It sounds very good. However, it results in an error message I have issues understanding. It's a bit too magic ;-) [Here](https://github.com/clEsperanto/napari_pyclesperanto_assistant/commit/b7b34052569d4746c339f0cf4a4ec462c08ddf45) are my code changes. And this is the error:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
c:\programs\miniconda3\envs\te_oki\lib\site-packages\magicgui\widgets\_bases\value_widget.py in (*x=(,))
     42         self.changed = EventEmitter(source=self, type="changed")
     43         self._widget._mgui_bind_change_callback(
---> 44             lambda *x: self.changed(value=x[0] if x else None)
        x = (,)
        global self.changed = undefined
        global value = undefined
     45         )
     46 

c:\programs\miniconda3\envs\te_oki\lib\site-packages\magicgui\events.py in __call__(self=, *args=(), **kwargs={'value': })
    653                     continue
    654 
--> 655                 self._invoke_callback(cb, event)
        self._invoke_callback = >
        cb = . at 0x000002AE9524A5E0>
        event = 
    656                 if event.blocked:
    657                     break

c:\programs\miniconda3\envs\te_oki\lib\site-packages\magicgui\events.py in _invoke_callback(self=, cb=.>, event=)
    674             cb(event)
    675         except Exception:
--> 676             _handle_exception(
        global _handle_exception = 
        self.ignore_callback_errors = False
        self.print_callback_errors = 'reminders'
        self = 
        global cb_event = undefined
        cb = . at 0x000002AE9524A5E0>
        event = 
    677                 self.ignore_callback_errors,
    678                 self.print_callback_errors,

c:\programs\miniconda3\envs\te_oki\lib\site-packages\magicgui\events.py in _handle_exception(ignore_callback_errors=False, print_callback_errors='reminders', obj=, cb_event=(.>, ), node=None)
    138     # Handle
    139     if value and not ignore_callback_errors:
--> 140         raise value
        value = AttributeError("'FunctionGui' object has no attribute 'self'")
    141     if print_callback_errors != "never":
    142         this_print: Optional[str] = "full"

c:\programs\miniconda3\envs\te_oki\lib\site-packages\magicgui\events.py in _invoke_callback(self=, cb=.>, event=)
    672     def _invoke_callback(self, cb: Callback, event: Event):
    673         try:
--> 674             cb(event)
        cb = . at 0x000002AE9524A5E0>
        event = 
    675         except Exception:
    676             _handle_exception(

c:\programs\miniconda3\envs\te_oki\lib\site-packages\magicgui\widgets\_bases\container_widget.py in (x=)
    157         """Insert widget at ``key``."""
    158         if isinstance(widget, ValueWidget):
--> 159             widget.changed.connect(lambda x: self.changed(value=self))
        global widget.changed.connect = undefined
        x = 
        global self.changed = undefined
        global value = undefined
        global self = undefined
    160         _widget = widget
    161 

c:\programs\miniconda3\envs\te_oki\lib\site-packages\magicgui\events.py in __call__(self=, *args=(), **kwargs={'value': })
    653                     continue
    654 
--> 655                 self._invoke_callback(cb, event)
        self._invoke_callback = >
        cb = , operation_name: str = 'threshold_otsu', radius_x: int = 1, radius_y: int = 1, radius_z: int = 0)>>
        event = 
    656                 if event.blocked:
    657                     break

c:\programs\miniconda3\envs\te_oki\lib\site-packages\magicgui\events.py in _invoke_callback(self=, cb=>, event=)
    674             cb(event)
    675         except Exception:
--> 676             _handle_exception(
        global _handle_exception = 
        self.ignore_callback_errors = False
        self.print_callback_errors = 'reminders'
        self = 
        global cb_event = undefined
        cb = , operation_name: str = 'threshold_otsu', radius_x: int = 1, radius_y: int = 1, radius_z: int = 0)>>
        event = 
    677                 self.ignore_callback_errors,
    678                 self.print_callback_errors,

c:\programs\miniconda3\envs\te_oki\lib\site-packages\magicgui\events.py in _handle_exception(ignore_callback_errors=False, print_callback_errors='reminders', obj=, cb_event=(>, ), node=None)
    138     # Handle
    139     if value and not ignore_callback_errors:
--> 140         raise value
        value = AttributeError("'FunctionGui' object has no attribute 'self'")
    141     if print_callback_errors != "never":
    142         this_print: Optional[str] = "full"

c:\programs\miniconda3\envs\te_oki\lib\site-packages\magicgui\events.py in _invoke_callback(self=, cb=>, event=)
    672     def _invoke_callback(self, cb: Callback, event: Event):
    673         try:
--> 674             cb(event)
        cb = , operation_name: str = 'threshold_otsu', radius_x: int = 1, radius_y: int = 1, radius_z: int = 0)>>
        event = 
    675         except Exception:
    676             _handle_exception(

c:\programs\miniconda3\envs\te_oki\lib\site-packages\magicgui\widgets\_function_gui.py in _on_change(self=, e=)
    208             self._dump()
    209         if self._auto_call:
--> 210             self()
        self = , operation_name: str = 'threshold_otsu', radius_x: int = 1, radius_y: int = 1, radius_z: int = 0)>
    211 
    212     @property

c:\programs\miniconda3\envs\te_oki\lib\site-packages\magicgui\widgets\_function_gui.py in __call__(self=, *args=(), **kwargs={})
    283         self._tqdm_depth = 0  # reset the tqdm stack count
    284         with _function_name_pointing_to_widget(self):
--> 285             value = self._function(*bound.args, **bound.kwargs)
        value = undefined
        self._function = 
        bound.args = (, 'threshold_otsu', 1, 1, 0)
        bound.kwargs = {}
    286 
    287         self._call_count += 1

c:\structure\code\napari_pyclesperanto_assistant\napari_pyclesperanto_assistant\_operations\_operations.py in binarize(input1=, operation_name='threshold_otsu', radius_x=1, radius_y=1, radius_z=0)
    165 
    166         # show result in napari
--> 167         if not hasattr(binarize.self, 'layer'):
        global hasattr = undefined
        global binarize.self = None
    168             binarize.self.viewer.add_labels(output, translate=input1.translate)
    169         else:

c:\programs\miniconda3\envs\te_oki\lib\site-packages\magicgui\widgets\_bases\container_widget.py in __getattr__(self=, name='self')
     82             if name == widget.name:
     83                 return widget
---> 84         return object.__getattribute__(self, name)
        global object.__getattribute__ = undefined
        self = , operation_name: str = 'threshold_otsu', radius_x: int = 1, radius_y: int = 1, radius_z: int = 0)>
        name = 'self'
     85 
     86     def __setattr__(self, name: str, value: Any):

AttributeError: 'FunctionGui' object has no attribute 'self'
```

**Comment by tlambert03** [comment]
> It's a bit too magic 

sometimes I wish I hadn't called it magicgui ... people feel like everything is magic now.  I'd call it functional vs object oriented.  If you're more comfortable thinking about objects classes and instance, consider that `magicgui` creates an _instance_ of a `FunctionGui` class (i.e. an actual widget), whereas `magic_factory` returns a class itself, that must be called to be instantiated to create a widget.  The  `@decorator` is just syntactic sugar... so without any decorators, here's how you can think about magicgui:

```python
def magicgui(function):
    # magicgui is a "factory" function that creates an instance
    widget = FunctionGui(function)
    return widget

def my_function(x: int, y: str): ...

my_widget = magicgui(my_function)
```

`magic_factory` works exactly like [functools.partial](https://docs.python.org/3/library/functools.html#functools.partial), meaning it creates a new function (with "some" of the arguments "partially" provided)

```python
def magic_factory(function, *args, **kwargs):
    return functools.partial(magicgui, function, *args, **kwargs)

my_factory = magic_factory(my_function)
my_first_widget_instance = my_factory()
my_second_widget_instance = my_factory()
...
``` 

this attribute error you're seeing here has to do with the assignment of the "self" that you [do here](https://github.com/clEsperanto/napari_pyclesperanto_assistant/blob/master/napari_pyclesperanto_assistant/_gui/_LayerDialog.py#L14)... and I'm afraid I still haven't worked through why you have to do that... , or why it's causing your error here (but presumably line 167 in binarize is being called before line 14 in LayerDialog. but I'll try to look later.  Ultimately, I'd like to see the whole storage of the layer dialog and the layer itself back onto the widget disappear.  You'd be better off constructing a new object somewhere to persist state, and simply use magicgui as a "view" onto a set of parameters that can call a function..  in the meantime  I'd definitely encourage you to use another name besides "self" for saving the `LayerDialog` instance, since it makes it harder to figure out what it's looking for.

**Comment by haesleinhuepf** [comment]
Ok, I think, I'm a step ahead. I got rid of the `self` and introduced the factory as you suggested. I'm also [setting](https://github.com/clEsperanto/napari_pyclesperanto_assistant/pull/9/files#diff-45cba30a70f44169c3ea470f3ed9de1a50cd9921b9217e94a4081a5d7eb2ec02R12) the `native.setParent` and still leak Widgets...

**Comment by haesleinhuepf** [comment]
I can also confirm, that we are indeed leaking [this](https://github.com/clEsperanto/napari_pyclesperanto_assistant/pull/9/files#diff-45cba30a70f44169c3ea470f3ed9de1a50cd9921b9217e94a4081a5d7eb2ec02R15) widget.

pytest output:

napari_pyclesperanto_assistant/_tests/test_dock_widget.py::test_complex_workflow
  C:\structure\code\napari_pyclesperanto_assistant\napari_pyclesperanto_assistant\_gui\_LayerDialog.py:17: UserWarning: **are we leaking this?<PyQt5.QtWidgets.QWidget object at 0x0000023616610790**>
    warnings.warn("are we leaking this?" + str(self.filter_gui.native))

napari_pyclesperanto_assistant/_tests/test_dock_widget.py::test_complex_workflow
  C:\structure\code\napari_pyclesperanto_assistant\napari_pyclesperanto_assistant\_tests\test_dock_widget.py:31: UserWarning:
  Leaking widget:<**PyQt5.QtWidgets.QWidget object at 0x0000023616610790**>
    warnings.warn(debug_output)

**Comment by haesleinhuepf** [comment]
If I call `self.filter_gui.native.setParent(viewer.window.qt_viewer)` after `viewer.window.add_dock_widget(self.filter_gui, area='right')`, the widget is no longer leaking but the GUI looks like this:
![image](https://user-images.githubusercontent.com/12660498/114285032-4c1f9280-9a54-11eb-9f36-a70fd6744750.png)

I may stop investigating here for a moment :-) Thanks for reading

**Comment by psobolewskiPhD** [comment]
@haesleinhuepf I can't reproduce the issue from the OP in a dummy plugin, is this still a problem?

**Comment by haesleinhuepf** [comment]
I haven't tested for a while - GitHub CI in the context of python/napari is too volatile to spend much time on it.

**Comment by Czaki** [comment]
> I haven't tested for a while - GitHub CI in the context of python/napari is too volatile to spend much time on it.

My experience is that nonstable GitHub CI in the context of python/napari shows the bug hidden in plugin code. 

Bug that depends on various conditions and may hit the user randomly.

**Comment by dalthviz** [comment]
Hi, checking the issue tracker, this seems related with https://github.com/napari/napari/issues/2161 and maybe this could be closed as fixed by https://github.com/napari/napari/pull/2715 ?

**Comment by GenevieveBuckley** [comment]
I'm not able to check whether #2715 completely fixes this issue, since it's been so long that the `add_test2` branch in `napari_pyclesperanto_assistant` no longer exists.

I'll close this for now, but if you find it happens again please re-open this issue (or start a new one, whatever you think best!) Thanks @haesleinhuepf
