### ISSUE TITLE
plugin duplicated in dock widgets menu when providing both dock_widget and function

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#2522]
## 🐛 Bug

when a plugin provides uses both the `provide_dock_widget` and the `provide_function` (which we use to generate a widget), then two entries for that plugin appear in the Plugins > Dock Widgets menus.  we need to make sure that the submenu logic takes function widgets into account

**Comment by psobolewskiPhD** [comment]
I think this is solved with npe2 manifests?
cc: @DragaDoncila

**Comment by DragaDoncila** [comment]
Yep, this is no longer relevant, thanks for the ping @psobolewskiPhD. Closing now.
