### ISSUE TITLE
Better handling of `cmd-W` with multiple non-modal windows

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#2527]
## 🐛 Bug

The addition of some new non-modal windows is revealing a little bug in our handling of window keyboard shortcuts like command-W.  As an example, if you were to hit command-comma to open the preferences window, I would expect command-w to then close the preferences window and return you to what you were doing.  However, command-w is tied to the `viewer.window._qt_main_window`, and since the app is set to quit when the last main window is closed, the entire program just quits (assuming you have only one viewer).

**Comment by goanpeca** [comment]
Indeed!, I am really wondering how this works on other OSs, any input there?

Should we add this on all OSs or is this more of a Mac thing?

And yes, indeed the `Cmd+W` (should close the active window, whatever that is.)

**Comment by sofroniewn** [comment]
> And yes, indeed the Cmd+W (should close the active window, whatever that is.)

My preference (as a mac user) would be this too, it's tripped me up a couple times also!!
