### ISSUE TITLE
Napari save screenshot does not work

### ISSUE THREAD

**Issue by dzyla** [napari/napari#2545]
## 🐛 Bug

Script loads 4 stacks of different channels into the viewer window. I adjust the contrast limits for all channels and want to save the file into single-layer PNG. I do it via File menu --> save the screenshot. The window pops out, I put the name and location and save. The file is not present in the location indicated during saving. I open again the Save screenshot menu and see that the new path is/run/user/1000/doc/******/, where **** is some random name. Sometimes the image is properly saved but recently realized that it does not save the whole image and only the first ~35% rows are saved and the rest is white.

In the command line there is the current message:

`(python:2580878): Gtk-WARNING **: 14:34:46.890: Failed to measure available space: Connection timed out`

## To Reproduce

1. Load layers into NumPy arrays and assign them to a single layer
2. Try to save a screenshot
3. Fail to save in the indicated location and sometimes do not save the whole image.

```
import matplotlib.pyplot as plt
import easygui
import glob
import numpy as np
import napari
import imageio
from skimage import io
import tqdm

# Get data per channel
folder = easygui.diropenbox(default='/mnt/keyence/')
print(folder)

ch1 = sorted(glob.glob(folder+'/*CH1.tif'))
ch2 = sorted(glob.glob(folder+'/*CH2.tif'))
ch3 = sorted(glob.glob(folder+'/*CH3.tif'))
ch4 = sorted(glob.glob(folder+'/*CH4.tif'))

if len(ch1) != 0:
    print(ch1[0])
elif len(ch2) != 0:
    print(ch2[0])
elif len(ch3) != 0:
    print(ch3[0])
elif len(ch4) != 0:
    print(ch4[0])
else:
    pass


# Load data to arrays
ch1_data = []
ch2_data = []
ch3_data = []
ch4_data = []

channels = [ch1_data, ch2_data, ch3_data, ch4_data]


for n, channel in enumerate([ch1, ch2, ch3, ch4]):
    for data in tqdm.tqdm(channel):
        channels[n].append(io.imread(data, as_gray=True))

chanels_selector = []

for channel in channels:
    chanels_selector.append(len(channel))

chanels_selector = np.array(chanels_selector)
chanels_selector = (chanels_selector == np.max(chanels_selector))

channels_tostack = []

for n, channel in enumerate(chanels_selector):
    if channel:
        channels_tostack.append(channels[n])

data = np.stack(channels_tostack)

print(data.shape)

channels_color = ['gray', 'blue', 'green', 'red']
channels_name = ['CH1', 'CH2', 'CH3', 'CH4']

# create Qt GUI context
with napari.gui_qt():
    # create a Viewer and add an image here
    viewer = napari.Viewer()

    if data.shape[0] == 3:
        channels_color = channels_color[1:]
        print(channels_color)
    elif data.shape[0] == 2:
        channels_color = channels_color[2:]
        print(channels_color)

    #viewer.add_image(reader.data)

    for n, channel in enumerate(data):
        viewer.add_image(channel, colormap=channels_color[n], blending='additive', name=channels_name[n], interpolation='gaussian')
```

## Environment

 - Please copy and paste the information at napari info option in help menubar here:

 - Any other relevant information:
 napari: 0.4.7
Platform: Linux-5.8.0-44-generic-x86_64-with-glibc2.10
System: Ubuntu 20.04.2 LTS
Python: 3.8.5 (default, Sep  4 2020, 07:30:14)  [GCC 7.3.0]
Qt: 5.15.2
PyQt5: 5.15.2
NumPy: 1.20.2
SciPy: 1.5.4
Dask: 2.30.0
VisPy: 0.6.6

OpenGL:
  - GL version:  4.6.0 NVIDIA 460.39
  - MAX_TEXTURE_SIZE: 32768

Screens:
  - screen 1: resolution 1920x1200, scale 1.0
  - screen 2: resolution 1200x1920, scale 1.0

Plugins:
  - console: 0.0.3
  - mrcfile-reader: 0.1.2
  - napari-czifile2: 0.1.1
  - svg: 0.1.4
  - tifffile: 0.1.0

**Comment by sofroniewn** [comment]
Yikes, this is no good! Thanks for flagging.

I've not seen

```
(python:2580878): Gtk-WARNING **: 14:34:46.890: Failed to measure available space: Connection timed out
```

before, so not sure whats going on here. Out of curiosity are your images particularly large? Or anything otherwise not worthy about them (multidimensional etc.).

I also see an import to `easygui` which is a package I didn't know about before. I wonder if there is a funny interaction happening with that and the napari GUI

**Comment by jni** [comment]
Looks like a very strange Qt/OS interaction...

@dzyla are you using a non-standard desktop on Ubuntu, or the default GNOME?

**Comment by dzyla** [comment]
Hi,

thanks for the reply and sorry for the late answer.

easygui is a very simple GUI package that allows opening the file or directory open box so the script can be run without command line parameters. It runs before napri so I cannot imagine any conflict here. I can check without easygui and let you know.

Images are loaded into the Numpy stack and have ~500 MB total with the dimensionality of (4, 70, 720, 960).

When I run the script as it is, it saves data in /run/user/. When I try to resave it, it shows the /run/user directory and when trying to save file there this error happens:

```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~/miniconda3/envs/pycharm/lib/python3.8/site-packages/napari/_qt/dialogs/screenshot_dialog.py in accept(self=<napari._qt.dialogs.screenshot_dialog.ScreenshotDialog object>)
     40 
     41     def accept(self):
---> 42         save_path = self.selectedFiles()[0]
        save_path = undefined
        self.selectedFiles = <built-in method selectedFiles of ScreenshotDialog object at 0x7f5664073670>
     43         if os.path.splitext(save_path)[1] == "":
     44             save_path = save_path + ".png"

IndexError: list index out of range
```

Regarding the second question, no I use vanilla Ubuntu 20.04 with GNOME. No significant modifications were made. The laptop is Lenovo P1 with Nvidia T2000 and 2 screens connected via HDMI or USB-C.


I tested this script without easygui and the error is the same and saves a screenshot in /run/user/.

Cheers,
Dawid

**Comment by jni** [comment]
Thanks for the extra info @dzyla. I guess my next question is, are you able to reproduce this bug with (preferably) generated data, or arbitrary data, so that we can try to reproduce it locally? As long as the example script is tied to your data it will be difficult for us to reproduce — I think none of us has encountered something like this. ☹️

**Comment by dzyla** [comment]
@jni I would be happy to share the data that works with this script. I don't know what is causing this issue tho.

In addition to previous information, I am using Python 3.8 environment from conda via PyCharm. In general napari works well, just the saving screenshot makes troubles.

**Comment by psobolewskiPhD** [comment]
@dzyla 
Gentle bump here, I obviously don't have access to your data, but napari has a 4 channel Lily sample file (File > Open sample > napari > Lily (4 Ch).
I tried that and saving screenshot worked as expected with the full size PNG.
This is using `main` or napari 0.4.17 and python 3.10
Are you still having this issue or can we consider this fixed/solved?
thanks!

**Comment by psobolewskiPhD** [comment]
I'm going to close this, because it seems solved and due to lack of activity.
@dzyla If this is still a problem, please update us on the details!
