### ISSUE TITLE
maybe less interpolation options?

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#2546]
## 🚀 Feature
I wonder if we could maybe curate the 2D image interpolation options a little bit?  I'm not personally quite sure when it's ever necessary to use, say, "catrom" interpolation instead of "hermite" 😄  ... and I suspect it's a bit over the top for the majority of users.

**Comment by sofroniewn** [comment]
Yes, I believe @kevinyamauchi and I have talked about this. Personally I don't like that there is such a big difference between the 2D and 3D interpolation modes and would prefer if they aligned.

I had thought we might want to just reduce them to `None` and `linear`, though I have heard from @alisterburt that he uses some of the others

**Comment by alisterburt** [comment]
For super low SNR/poorly resolved stuff I've found lanczos is noticeably nicer than something like bilinear/bicubic (something I only found out by experimenting with the options in the dropdown) 

https://user-images.githubusercontent.com/7307488/114469329-d3037500-9be4-11eb-918f-949972c1129c.mp4

Agree that some curation wouldn't hurt though!

Quick list of 'most similar to each other' for the data above...

interpolation mode 'bessel' is closest to ['bessel' 'mitchell' 'spline16' 'catrom']
interpolation mode 'bicubic' is closest to ['gaussian' 'bicubic' 'bilinear' 'hamming']
interpolation mode 'bilinear' is closest to ['bilinear' 'hamming' 'mitchell' 'gaussian']
interpolation mode 'blackman' is closest to ['blackman' 'lanczos' 'spline36' 'spline16']
interpolation mode 'catrom' is closest to ['catrom' 'spline16' 'spline36' 'blackman']
interpolation mode 'gaussian' is closest to ['gaussian' 'bicubic' 'hamming' 'mitchell']
interpolation mode 'hamming' is closest to ['hamming' 'kaiser' 'hermite' 'mitchell']
interpolation mode 'hanning' is closest to ['hanning' 'hermite' 'kaiser' 'hamming']
interpolation mode 'hermite' is closest to ['hanning' 'hermite' 'kaiser' 'hamming']
interpolation mode 'kaiser' is closest to ['hanning' 'kaiser' 'hermite' 'hamming']
interpolation mode 'lanczos' is closest to ['blackman' 'lanczos' 'spline36' 'spline16']
interpolation mode 'mitchell' is closest to ['mitchell' 'hamming' 'bessel' 'bilinear']
interpolation mode 'nearest' is closest to ['nearest' 'hanning' 'kaiser' 'hermite']
interpolation mode 'spline16' is closest to ['catrom' 'spline16' 'spline36' 'blackman']
interpolation mode 'spline36' is closest to ['blackman' 'lanczos' 'spline36' 'spline16']

calculated with the following script
```python
import napari
import numpy as np
from imageio import imread
from napari.layers.image._image_constants import Interpolation

image = imread('example.png')

viewer = napari.Viewer()
layer = viewer.add_image(image)

# screenshots of each interp mode
interpolated_images = {}
interpolation_modes = Interpolation.keys()
for interpolation_mode in interpolation_modes:
    layer.interpolation = interpolation_mode
    interpolated_images[interpolation_mode] = viewer.screenshot(canvas_only=True)

# pairwise L2 distance
n_interpolation_modes = len(interpolation_modes)
diff_matrix = np.empty((n_interpolation_modes, n_interpolation_modes))

for i, interp_base in enumerate(interpolation_modes):
    for j, interp_test in enumerate(interpolation_modes):
        im1 = interpolated_images[interp_base]
        im2 = interpolated_images[interp_test]
        diff_matrix[i, j] = np.sum(np.sqrt((im2 - im1) ** 2), dtype=np.float64)

# 3 most similar modes for each interp mode
k = 4  # 4 smallest elements (0 distance to self)

for idx, interpolation_mode in enumerate(interpolation_modes):
    idx_4_smallest = np.argpartition(diff_matrix[idx], k)[:k]
    four_closest = np.array(interpolation_modes)[idx_4_smallest]
    print(f"interpolation mode '{interpolation_mode}' is closest to {four_closest}")
    
```

**Comment by tlambert03** [comment]
now that's what I call curation :)

those families seem to visually match this example from mpl as well:


![](https://matplotlib.org/mpl_examples/images_contours_and_fields/interpolation_methods.hires.png)

I think we should keep, at least, `nearest`, `bilinear`, `bicubic`,  one from the `lanczos`/`splineX` family, and one from the `hanning`/`hermite`/`kaiser` family ... ?

**Comment by alisterburt** [comment]
I agree @tlambert03 - should we go with
- nearest
- bilinear
- bicubic
- spline36
- kaiser

Choices from the 'families' were based on how they look in the mpl image - happy to put together a PR if there's consensus

**Comment by sofroniewn** [comment]
works for me. i wonder if it would be possible to add the additional ones to the 3D rendering mode too, but maybe unifying the 2D and 3D rendering modes is a goal for a later date. It would simplify a bunch of code though ...

**Comment by kevinyamauchi** [comment]
>  I agree @tlambert03 - should we go with
> 
> - nearest
> - bilinear
> - bicubic
> - spline36
>  - kaiser


Nice work, @alisterburt ! Those look good to me.

> i wonder if it would be possible to add the additional ones to the 3D rendering mode too, but maybe unifying the 2D and 3D rendering modes is a goal for a later date. It would simplify a bunch of code though ...

I agree this would be super nice. I took a quick look and I'm not sure it's a quick fix, but it would definitely be cool to have in the near-ish future.
