### ISSUE TITLE
Properties behavior is inconsistent the data setter for Shapes, Points, and Tracks

### ISSUE THREAD

**Issue by kevinyamauchi** [napari/napari#2547]
## 🐛 Bug

As pointed out in #2532  by @JoOkuma , the `Tracks.data` setter clears the layer properties except for the updated `track_id` field. This is different from the Shapes and Points layers, which trim/extend the properties to fit the shape of the new data. I think it is generally convenient to have the properties trimmed/extended to match the new data. However, I can see how that might be a little "magic". I don't have a strong opinion either way, but I do think the behavior should be consistent across all layers with properties. 

A comment from @quantumjot [here](https://github.com/napari/napari/pull/2532#issuecomment-817694882):
> Yes, I think that behaviour exists so as to not make any assumptions about how the data is changing; in general I'm not a fan of these 'silent' changes to the underlying data. However, I can see why mimicking the behaviour of the Shapes and Points layers when updating the data makes sense for uniformity across the layers. I agree that the TrackManager should keep the IDs in sync. My guess is that, if the user knows that they're completely changing the structure of the data (for example, filtering tracks) then they also know that the properties and graph will need updating too.

## To Reproduce

1. Create a points, shapes, and tracks layer with properties
2. Change the data via the `layer.data` setter to data with a different number of items
3. Shapes and points trims/extends the properties to match the new data shape and tracks clears the properties except for the updated `track_id` field.

## Expected behavior

I think the behavior should be consistent across all layers with properties, but I am unsure what that behavior should be.

## Environment

napari 0.4.7

**Comment by sofroniewn** [comment]
@DragaDoncila and @jni I were recently discussing this in the context of the shapes layer https://github.com/napari/napari/issues/2354#issuecomment-810677482, see #2507 which will do this for shapes

**Comment by kevinyamauchi** [comment]
Thanks for the links to the discussion, @sofroniewn .

If I understood #2507 correctly, after it merges, the `Shapes` layer will be in line with the `Points` layer in that the layer properties and viz attributes will be trimmed/extended to match the shape of the new data. Is that right, @DragaDoncila ?

If that's the case, then I think we should do the same for `Tracks`. When we do so, perhaps we can add some text to the docstring and the docs explaining the data setter behavior (as was done by @DragaDoncila in #2507). I agree with @quantumjot that it's best to avoid "invisible" changes to the layer data.

**Comment by DragaDoncila** [comment]
> Is that right, @DragaDoncila ?

That's right, we keep attributes when the same number of shapes is passed, trim them when fewer shapes are passed and extend them with defaults when more shapes are passed.

> perhaps we can add some text to the docstring and the docs explaining the data setter behavior (as was done by @DragaDoncila in #2507)

Definitely agree this should be explicitly documented, and tbh I think it deserves more documentation in #2507 as well, maybe even an example or two in the shapes layer tutorial. I'll probably make it a separate PR though.

**Comment by andy-sweet** [comment]
Also related to the larger discussion in https://github.com/napari/napari/issues/3779

**Comment by willingc** [comment]
I'm going to close this issue as addressed via documentation. #3779 and refactor discussions can address going forward.
