### ISSUE TITLE
Getting deprecation warning when saving data

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#2549]
## 🐛 Bug

When saving data, this line https://github.com/napari/napari/blob/25e08d6659427a57a9c33d09b37aac724d91ea43/napari/_qt/qt_viewer.py#L451 is triggering a deprecation warning. We should fix before our next release. Should be a one-liner

```
/Users/nsofroniew/GitHub/napari/napari/_qt/qt_viewer.py:442: FutureWarning: 'viewer.layers.selected' is deprecated and will be removed in or after v0.4.9. Please use 'viewer.layers.selection'!
```

**Comment by wadhikar** [comment]
Hello @sofroniewn, I would like to work on this issue. Could you please assign it to me? Thank you.

**Comment by wadhikar** [comment]
Just made the changes in my fork. This is my first open source contribution so please let me know if you have any pointers. Thank you!

**Comment by sofroniewn** [comment]
> This is my first open source contribution so please let me know if you have any pointers. Thank you!

Great job on your first open source PR! Here's to many more!!
