### ISSUE TITLE
Perhaps hide the IPython interactive setting

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#2567]
There was a [case on image.sc recently](https://forum.image.sc/t/napari-jupyter-notebook-issue/32640/27?) where a user turned off the "IPython interactive" setting in the preferences dialog, and then was confused when the napari viewer did not show when using `ipython --gui=qt` (without having to use `napari.run`).  While having better tooltips (https://github.com/napari/napari/issues/2566) and documentation (#2564) in preferences might help a little bit here, I wonder if perhaps that setting should be hidden from the gui and restricted to command line usage.

**Comment by sofroniewn** [comment]
I will defer to @jni and others, but in general I favor exposing less in the GUI if it the option is fairly advanced/ specialized so I would be fine making it CLI only. It should obviously still be documented somewhere nicely though

**Comment by jni** [comment]
I'm happy to have it default to True and having it be turn-off-able only through the API.
