### ISSUE TITLE
pydicom plugin for Radiotherapy files

### ISSUE THREAD

**Issue by ferdymercury** [napari/napari#2576]
## 🚀 Feature
A plugin to view CT / MR and RTdose images on Napari (when the grid spcaing is regular), suggested by @jni.

## Motivation
Right now, one can use e.g. for RTdoses:

```
from pydicom import dcmread, uid
import napari
rtd = dcmread("/home/piguar/RT_Dose/eclipse-8.1.20-phantom-breast/Original/RD.1.2.246.352.71.7.2088656855.452097.20110920152341.dcm")
if not ds.file_meta.MediaStorageSOPClassUID == '1.2.840.10008.5.1.4.1.1.481.2':
	sys.exit()
if not hasattr(rtd.file_meta,'TransferSyntaxUID'):
	rtd.file_meta.TransferSyntaxUID = uid.ImplicitVRLittleEndian
dose = rtd.pixel_array.astype('float')
dose *= rtd.DoseGridScaling
napari.view_image(dose)
```

## Pitch
To specifically support RTdose files first, and maybe later CT and MR images.
```
import napari
viewer = napari.Viewer()
viewer.open(‘myfilenameRtdose.dcm’)
```
## Alternatives
https://github.com/pydicom/contrib-pydicom/pull/19
https://pypi.org/project/mpl-volume-viewer/
https://www.slicer.org/
https://github.com/ferdymercury/amide
https://github.com/marcomusy/vedo

**Comment by ferdymercury** [comment]
I just found this other plugin for neuroimaging https://github.com/nipy/napari-nibabel that could be a good template / model for radiotherapy, too.

**Comment by tlambert03** [comment]
Awesome!  are you interested in giving this a shot?
Given the example code you've provided here, you might be able to get most of this accomplished as follows:

1. use https://github.com/napari/cookiecutter-napari-plugin to create an "empty" plugin package
   - read the readme there for detailed instructions, but here's the tldr;
   ```
   pip install cookiecutter
   cookiecutter https://github.com/napari/cookiecutter-napari-plugin
   # answer questions, make sure to say "y" to reader plugin, but can say no to the rest

   cd <whatever-you-named-your-plugin>
   git init
   pip install -e .
   ```
2. in the `_reader.py` file that gets generated for you
   - in `napari_get_reader` change the extension to `path.endswith(". dcm"):`
   - replace the body of `reader_function` with the code you pasted above.  In other words, it should be a function that (minimally)  takes a `.dcm` filename, reads it with dcmread, and returns a numpy array

3. restart napari and drag your file into the viewer and cross your fingers! :)  (and, of course, ping us for help if needed!)

**Comment by ferdymercury** [comment]
Thanks for the instructions. I can not work on it for the moment, but maybe later on I can give it a shot.

Note: It would be then nice that it also allows CT and MRI 2D images, that are also with .dcm extension. Or folders containing several dcm files that all together build a volume. Though the latter is a more delicate thing, it requires regular spacing, etc.

**Comment by thewtex** [comment]
Hey, @ferdymercury , following @tlambert03 's guidance, we now have an [napari-itk-io](https://github.com/InsightSoftwareConsortium/napari-itk-io) plugin.

```
pip install napari-itk-io
```

This supports DICOM images and DICOM series. For DICOM Series, use *File -> Open Folder...* in napari. It will work with DICOM files that have a *.dcm* extension or not. It will extract the first series volume that is found, sort the slices spatially, and preserve metadata like the voxel spacing for rendering in napari. This does not work with all DICOM image types, but most.

Single DICOM files, 2D or multi-frame 3D files, will also load in napari.

**Comment by thewtex** [comment]
Following https://github.com/napari/napari/issues/2628 , we will also have support for the image orientation, common in DICOM images and series.

**Comment by ferdymercury** [comment]
@thewtex Amazing!! Glad to hear this.

I checked and it opens correctly CT images, US, as well as RTdoses.

So closing the issue. Thanks so much again!!

**Comment by tlambert03** [comment]
so cool!  tried it too :)  great job
