### ISSUE TITLE
Set objectName on all QDockWidgets to avoid warning at shutdown

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#2578]
## 🐛 Bug
I've been seeing this warning a lot when closing napari:

```
WARNING: QMainWindow::saveState(): 'objectName' not set for QDockWidget 0x7f8cf9467330 ';
```

the docs on [saveState](https://doc.qt.io/qt-5/qmainwindow.html#saveState) say:

> The objectName property is used to identify each QToolBar and QDockWidget. You should make sure that this property is unique for each QToolBar and QDockWidget you add to the QMainWindow

so we should probably make sure to add some sort of objectName to each of our QDockWidgets in 

https://github.com/napari/napari/blob/c618f310a5c837e77799f2d80286eea1db214f57/napari/_qt/widgets/qt_viewer_dock_widget.py#L21

**Comment by sofroniewn** [comment]
Yes, I've seen that too!! Agreed

**Comment by goanpeca** [comment]
@tlambert03 is this related to plugin widgets? I have not seen this 🤔

**Comment by tlambert03** [comment]
Probably. I don’t see it every time either... but if you just start using viewer.window.add_dock_widget you’ll probably hit it.

**Comment by goanpeca** [comment]
```python

    def add_dock_widget(
        self,
        widget: QWidget,
        *,
        name: str = '',
        area: str = 'bottom',
        allowed_areas=None,
        shortcut=None,
    ):
```

why is name optional 🤔 ? Should we add some uuid in case name is empty?

**Comment by tlambert03** [comment]
Name will actually be shown in the title bar, so while creating a uuid for objectName does sound like a good idea, we want to make sure it doesn’t show up in the title bar

**Comment by goanpeca** [comment]
Then a generic `Dock widget 1`  `Dock widget 2` etc?

**Comment by tlambert03** [comment]
yeah, that would be fine.  We could maybe check to see if the inner widget being wrapped by the DockWidget has an objectName... but it probably wont :) so anything that satisfies `window.getState` is fine by me :)
