### ISSUE TITLE
View > Axes > Visible doesn't sync with model

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#2585]
## 🐛 Bug
The checkbox for `View > Axes > Visible` doesn't stay synced with the viewer model.  If you set axes.visible programmatically, the checkstate on the menu action doesn't go with it...

**Comment by sofroniewn** [comment]
Hmm, maybe we need to unify something with the action manager here? cc @Carreau

**Comment by goanpeca** [comment]
>Hmm, maybe we need to unify something with the action manager here? cc @Carreau

Indeed, the action manager will handle these cases for us (eventually)
