### ISSUE TITLE
Label layer: Selected label spinner cannot show higher than a certain value

### ISSUE THREAD

**Issue by clbarnes** [napari/napari#2587]
## 🐛 Bug

The UI element showing the value of the currently selected label maxes out at a value other than that representable by the underlying label array.
When this issue was raised, it was a hardcoded 1024; otherwise it would be the spinbox's internal i32 maximum.
This does not affect color picking and painting, which can correctly use higher values.
However, the spinner buttons cannot be used to select a label higher than 1024, and "show selected:" checkbox cannot be used to show any label higher than 1024, and it's generally confusing.

## To Reproduce

```python
import napari
import numpy as np

# TEST_VALUE = 1024
TEST_VALUE = 2**31 - 1

shape = (64, 64)
labels = np.arange(0, np.product(shape), dtype=np.uint64).reshape(shape) + TEST_VALUE

napari.view_labels(labels)
napari.run()
```

1. Hover over a pixel in the lower right corner and note its value
2. Use the color picker to select that pixel
3. Note that the value in the "label:" spinner on the layer control is not the same value, although the color matches the true selected pixel
4. Paint with that label
5. Note that the value of the new painting is the true selected label
6. Check "show selected:"
7. Note that a label lower than the true selected label is shown

## Environment

Manjaro-i3 linux.

Installed using `pip install git+https://github.com/napari/napari.git`; also present in `napari==0.4.6` and `napari==0.4.7`.

```
napari: 0.4.8.dev48+gc618f310
Platform: Linux-5.4.112-1-MANJARO-x86_64-with-glibc2.29
System: Manjaro Linux
Python: 3.8.5 (default, Aug 5 2020, 13:09:57) [GCC 10.1.0]
Qt: 5.14.2
PyQt5: 5.14.2
NumPy: 1.19.1
SciPy: 1.5.2
Dask: 2.23.0
VisPy: 0.6.4

OpenGL:
- GL version: 4.6 (Compatibility Profile) Mesa 21.0.1
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1080, scale 1.0
- screen 2: resolution 1920x1080, scale 1.0

Plugins:
- console: 0.0.3
- scikit-image: 0.4.8.dev48+gc618f310
- svg: 0.1.4
```

**Comment by sofroniewn** [comment]
This should be easy to fix, looks like we hardcoded a max value here https://github.com/napari/napari/blob/9b46dd5a92653a194b870e433debd672ff0457ad/napari/_qt/layer_controls/qt_labels_controls.py#L92

Seems like I changed the value here https://github.com/napari/napari/pull/2296#issuecomment-787211320, it used to be `2147483647`. Maybe you can submit a PR to change it back @clbarnes?

Thanks!!

**Comment by clbarnes** [comment]
Thought I'd replied to this; taking a look now. I had planned to set the min/max values based on `np.iinfo(self.layer.data.dtype)`, but the underlying widget can only contain int32, so I'll simply switch it back to `[0, 2**31]`. It might be nice to add a `specialValueText` for "empty" and "max", but it seems `specialValueText` can only be used for the minimum.

Could this be a problem going forward, e.g. for large lazy-loaded segmentations? `QDoubleSpinBox` with input validation would provide more bits of integer precision. Otherwise it would be a small amount of C++ to implement a [64-bit spinbox](https://stackoverflow.com/questions/8383620/64bit-int-spin-box-in-qt) - presumably that couldn't be done on the python side?

**Comment by clbarnes** [comment]
PR #2597 sets the range to the intersection of i32 and the label layer's dtype, which means that u32 and larger label arrays will still have the broken behaviour above, but it'll be hit less often.

The simple thing to do would be to (write and) use a spinner with a massive data type and then restrict its value as the PR does, for future proofing, although it seems like anything bigger than u64 would be a pain to implement. We could use different spinner dtypes for different label data types, but given the label data can be replaced by arrays of different dtypes (so long as they're int or bool), we'd then need to propagate that change up to the layer controls which seems unnecessarily complicated.

**Comment by clbarnes** [comment]
I have a branch implementing the float-as-uint spinbox idea - it works fine and would give considerably more headroom for the maximum label value.

However, napari (or presumably one of its dependencies) rejects the mere idea of high labels: it seems that there is some other limitation lower than i32 max which causes napari to crash (after taking up all the RAM on my 20GB machine), even when the array is small. The critical value is somewhere between `2**29+1` and `2**30-2`.

**Comment by sofroniewn** [comment]
> However, napari (or presumably one of its dependencies) rejects the mere idea of high labels: it seems that there is some other limitation lower than i32 max which causes napari to crash (after taking up all the RAM on my 20GB machine), even when the array is small. The critical value is somewhere between 2**29+1 and 2**30-2.

Yeah, we might be running into a vispy limitation here. Is `u64` important for your use case?

**Comment by clbarnes** [comment]
No data I currently have my hands on has 2^64-1 unique segments. We generally store labels in u64 but certainly aren't near its limits but I thought I'd try pushing it while I was in there.

I don't know what the earliest supervoxel stage of neurite segmentation looks like for some of the bigger volumes out there, but Scheffer et al's hemibrain is into the tens of millions of synapses at least, which is 2 orders of magnitude off the limitation we're looking at here; I imagine an early neurite segmentation of a similar-sized volume would have an order of magnitude more (although whether you would need to visualise such a volume with napari is another question).

**Comment by jni** [comment]
> However, napari (or presumably one of its dependencies) rejects the mere idea of high labels: it seems that there is some other limitation lower than i32 max which causes napari to crash (after taking up all the RAM on my 20GB machine), even when the array is small. The critical value is somewhere between 2**29+1 and 2**30-2.

Oops! No we do not reject them, we just neglected to take them into consideration when adding [this "speed" hack](https://github.com/napari/napari/pull/2415/files#diff-11f2c63f66f3e9b0271b3c1584a67e2eb682b8638c1c679bcd9d036f977675c5R707-R712) (the motivation of which is described [here](https://github.com/napari/napari/issues/2380#issue-825308887)). Sorry about that!!!

We should (a) have memory benchmarks in addition to speed benchmarks, and (b) maybe revert that change (😞). @clbarnes can you check whether earlier napari runs into the same RAM explosion issue?

Although — 2**30 * 8 bytes gives 8.5GB which doesn't seem like it should have destroyed your RAM @clbarnes. So maybe my diagnosis is incorrect... Either way it's worrisome. 😬

**Comment by clbarnes** [comment]
Ah, so the issue may be that the colors array is indexed by `np.arange(0, img.max()+1), which is just a colossal array for high labels? And then it's just the machine running out of RAM for that array, rather than a built-in hard limit from vispy or whatever else. 

Taking a closer look, it seems that the RAM abuse is only passing - when using labels as high as `2**29`, it spikes up to 12GB on launch and then drops down to 4GB.

If the colormap is cyclic, could that lookup be done using `label_vals % len(colormap)` instead of the raw values? Or have I missed the point?

**Comment by clbarnes** [comment]
> @clbarnes can you check whether earlier napari runs into the same RAM explosion issue?

Indeed, https://github.com/napari/napari/commit/f0e108ed4d0dda0317b361c7e76923931268a73b is the commit which did it. Before that my toy example is fine (and indeed loads faster, because it's a very small image with very high label values); afterwards it RAMsplodes. This seems like a conflict between loading large images (with good performance) and loading images with a high absolute max IDs. Large images seem to be the more common use case, though!

**Comment by sofroniewn** [comment]
>  This seems like a conflict between loading large images (with good performance) and loading images with a high absolute max IDs. Large images seem to be the more common use case, though!

Ah nice catch - I had forgotten about this. It is something for us to keep in mind though!

**Comment by clbarnes** [comment]
I think this specific issue is dealt with in #2597 and #2608 , but has spun off 2 other discussions/ todos of lower importance, so I'll close this and raise those separately.
