### ISSUE TITLE
Units in Scale Bar visual

### ISSUE THREAD

**Issue by lukasz-migas** [napari/napari#2591]
## 🚀 Feature
Hi!
In a project I am working on that utilizes napari as the image viewer, I’ve added scalebar visual that can display the pixel dimensions, not unlike the [matplotlib_scalebar](https://github.com/ppinard/matplotlib-scalebar) project. Here is a screen grab of the scalebar in action.

![napari-scale-bar](https://user-images.githubusercontent.com/25161821/115525279-3b122500-a28f-11eb-8148-70a81da10bdd.gif)

It is based on the original implementation, however, it adds a of couple of extra attributes to the ScaleBar model, namely: **dimension** (e.g. m, um, ft, …) and **px_size** (size of the pixel in the base unit). I’ve also added **font_size** attribute to control the size of the text node and the scale bar visual was adjusted to move the text node below the scale bar line. 

Would you be interested in such a PR  or do you prefer for the [units PR](#1701) to come through that might address this?

**Comment by sofroniewn** [comment]
This looks very nice @lukasz-migas. I might prefer us to get #1701 working more broadly, but I'm not sure what the latest progress is there. Maybe @jni or @Czaki, @alisterburt who I believe were discussing units before could weigh in with a status update there. Also if you have ideas on how to push #1701 along they would be much appreciated

**Comment by Czaki** [comment]
I could try to answer any questions. We stuck, because introducing units we should still deal with unitless data. How to treat them. Also, the whole unitless code needs to work smoothly. From the discussion, we think that the best option is to use `pint` library and put the global register instance in some small package. Maybe @jni will remember which package was selected.

**Comment by jni** [comment]
@sofroniewn personally I'd be pretty happy to have this intermediate solution for now. I think the combination of scale + transforms is quite hairy to solve generally. For example, in napari we can display kymographs no problem — and these require multiple scale bars, one for time and one for space. We could do a big push on it but imho getting this in first would be a good thing.

And thanks @lukasz-migas for tackling it! But btw I would prefer to just specify unit, ie `viewer.scale_bar.unit = um`. Would that work or do we really need the disambiguation of `si-length-um`?

**Comment by lukasz-migas** [comment]
Thanks @jni. 

Sure, the API could be changed to use `viewer.scale_bar.unit = 'unit'` instead of the cumbersome `si-length-um` etc. I will take a look at changing the current implementation. 

One thing to consider is that the unit `um` is actually a prefixed `m` unit with 1e-6 factor that belongs to the `SILengthDimension`. If we wanted to simply use any valid `unit`, then we would have to have some sort of register of currently available units. This could be done by having dictionary of `Dimension : Units`. Then when the user specifies the unit via `viewer.scale_bar.unit` attribute, we simply lookup the appropriate dimension and update the scale bar and if one cannot be found, we throw an exception. Does that sound reasonable?

Are you happy with having a separate `px_size` attribute? This value is always 1 if the scale bar is unitless or in pixels, otherwise, it takes the specified value. The alternative is to use e.g. `viewer.scale_bar.unit = 10um` but in this case, we would have to parse the provided value and handle `10 um` or `0 um` or `um`.

**Comment by tlambert03** [comment]
>  If we wanted to simply use any valid unit, then we would have to have some sort of register of currently available units. 

I think ultimately we’d like to use pint for this sort of thing.  It has great support for string-> order of magnitude parsing as well

**Comment by sofroniewn** [comment]
> I think ultimately we’d like to use pint for this sort of thing. It has great support for string-> order of magnitude parsing as well

@lukasz-migas do you have experience with [pint](https://pint.readthedocs.io/en/stable/)? Is that something we want to incorporate in this current work?

**Comment by lukasz-migas** [comment]
@tlambert03 I agree, using `pint` would be a much better solution in the long term - this was just temporary solution. 

@sofroniewn I don't have much experience with `pint`, but it looks simple to use. I could take a look at how it could be incorporated to replace my custom unit coversion classes.

**Comment by sofroniewn** [comment]
> @sofroniewn I don't have much experience with pint, but it looks simple to use. I could take a look at how it could be incorporated to replace my custom unit coversion classes.

Great, yeah, that could be really helpful! Thanks!!

**Comment by Czaki** [comment]
If I good remeber there was a decision to use register from @tlambert03 maintained package as default one for napari. @tlambert03 did you remember which one?

**Comment by tlambert03** [comment]
it was `ome-types`, but honestly, we barely add anything beyond the default pint registry (you can see it [here](https://github.com/tlambert03/ome-types/blob/master/src/ome_types/_units.py)) ... so I'm not sure it's worth using.  I bet we can get a _long_ way without defining anything beyond the built in `ureg = pint.UnitRegistry()` that uses [these](https://github.com/hgrecco/pint/blob/master/pint/default_en.txt) definitions.

**Comment by jni** [comment]
@tlambert03 the key in that discussion was to make sure that all plugins can share the same global registry instance without having to depend on napari. But @Czaki we can have an internal napari one for now and then move to the global one in subsequent PRs. This is not *the* units support PR, just something that gets us 75% of the way to what we need.

**Comment by sofroniewn** [comment]
> @tlambert03 the key in that discussion was to make sure that all plugins can share the same global registry instance without having to depend on napari. But @Czaki we can have an internal napari one for now and then move to the global one in subsequent PRs. This is not the units support PR, just something that gets us 75% of the way to what we need.

Agreed, I think this will be very beneficial, for reasonable effort

**Comment by lukasz-migas** [comment]
Hi,

I've had a bit of time this afternoon to work on this and the scale bar visual is now using `pint` to do all unit conversions.
The scale bar can remain unitless when `viewer.scale_bar.unit = ""` or have any (valid) `pint` unit, e.g. `viewer.scale_bar.unit = "um"` or `viewer.scale_bar.unit = "100 mm"` etc. 
Since `pint` has a very powerful parsing functionality, it makes sense to simply specify the unit and pixel size in one place.

@tlambert03 I am currently using the default `UnitRegistry` that is instantiated in the `vispy_scale_bar_visual` but when in the future a custom registry is used, it can be migrated.

![napari-scale-bar](https://user-images.githubusercontent.com/25161821/115993812-c7488300-a5d4-11eb-99ee-ce02af9dafac.gif)

**Comment by sofroniewn** [comment]
This looks great @lukasz-migas, I'd happily review this as a PR if you'd like to make one, I had a quick look through the branch and it's looking very nice.

> @tlambert03 I am currently using the default UnitRegistry that is instantiated in the vispy_scale_bar_visual but when in the future a custom registry is used, it can be migrated.

Personally I think this could live in a `napari/utils/_units.py` file for now. I'd like to keep as much out of `vispy_` files as we can.
