### ISSUE TITLE
Add dask cache size preference

### ISSUE THREAD

**Issue by jni** [napari/napari#2594]
## 🚀 Feature

In #2590 we removed the auto-creation of a dask cache. However, it might be useful to expose this as a preference, see https://github.com/napari/napari/pull/2590#issuecomment-824172250

## Motivation

Performance of dask with and without a cache is very dependent on use case and chunking. By default, I think it's better to not touch the cache at import, since this is on the same spectrum as monkey-patching. However, it's good to give users the ability to opt-in to this behaviour.

**Comment by goanpeca** [comment]
Hi @jni, some questions :) 
- Would this require a checkbox to enable/disable it plus a number spinner to change size?
- Size should be in... MB ?
- What should be a reasonable default so that when enabled a "reasonable" number appears by default
- What should be the minimum allowed value?
- What should be the maximum allowed value? (e.g. get free space on the computer and multiply by some factor smaller than 1?)

**Comment by jni** [comment]
I know nothing. :joy: 

No seriously, I can guess, but :shrug: I leave these to more experienced UI persons and/or dask users. I will say that it's nice to be able to set in text however one likes, e.g. "64GB" for someone with a large workstation. Once we depend on pint this will be easy-ish to achieve I think.

Our previous default was 1/10th of RAM and I think that's reasonable. But seriously: :shrug: 

:joy:

**Comment by goanpeca** [comment]
That works as a starter 😆

**Comment by sofroniewn** [comment]
I also don't know what is best here, we could start with "fraction of RAM" though, and then have a spinbox for 0 to 1 with 0 meaning not used at all? Maybe we don't want to go all the way to 1?

**Comment by goanpeca** [comment]
>fraction of RAM

Available free RAM or total?

**Comment by jni** [comment]
Total?

**Comment by goanpeca** [comment]
🤷🏼 ?

**Comment by sofroniewn** [comment]
I don't mind, starting with total seems fine - we can change later if needed

**Comment by GenevieveBuckley** [comment]
@jni - Nick and I are having a chat about how to better leverage Dask with napari. I'll send you a meeting invite in case you want to join, we might touch on this issue then.

**Comment by GenevieveBuckley** [comment]
> I also don't know what is best here, we could start with "fraction of RAM" though, and then have a spinbox for 0 to 1 with 0 meaning not used at all? Maybe we don't want to go all the way to 1?

Yeah, I suspect it might not be a good idea to go all the way up to 1

> Performance of dask with and without a cache is very dependent on use case and chunking. 

I think we probably need some better documentation with example use cases & the best option for those. Then users can try and match their situation to the most similar example, to get a bit of an idea about what might work well for them.

Trouble is, I don't think we *have* a good set of established rules of thumb. What do you think @jni?

**Comment by jni** [comment]
Closed by #5490
