### ISSUE TITLE
Layer controls, layer buttons, layer list, viewer buttons, and status bar do not appear

### ISSUE THREAD

**Issue by mikiotada** [napari/napari#2601]
## 🐛 Bug

Hello, after installing napari using `conda install -c conda-forge napari`, I ran `napari` from the command. Then, the below viewer appeared. However, it does not contain some components such as layer controls, layer buttons, etc. 

## To Reproduce

1. `napari` on terminal
2. 
![Screen Shot 2021-04-22 at 2 47 02 PM](https://user-images.githubusercontent.com/36828160/115789265-b819c900-a379-11eb-850a-f51c7172b906.png)
![Screen Shot 2021-04-22 at 2 57 53 PM](https://user-images.githubusercontent.com/36828160/115790150-257a2980-a37b-11eb-91dc-56778e4bbad0.png)

UserWarning:
    napari was tested with QT library `>=5.12.3`.
    The version installed is 5.9.7. Please report any issues with this
    specific QT version at https://github.com/Napari/napari/issues.
### 
## Expected behavior
![Screen Shot 2021-04-22 at 2 50 15 PM](https://user-images.githubusercontent.com/36828160/115789509-1ba3f680-a37a-11eb-9e47-dd4e614b302d.png)

## Environment
napari: 0.4.7
Platform: macOS-11.2.3-x86_64-i386-64bit
System: MacOS 11.2.3
Python: 3.9.2 | packaged by conda-forge | (default, Feb 21 2021, 05:02:20)  [Clang 11.0.1 ]
Qt: 5.9.7
PyQt5: 5.9.2
NumPy: 1.20.2
SciPy: 1.6.2
Dask: 2021.04.0
VisPy: 0.6.6

OpenGL:
  - GL version:  2.1 INTEL-16.1.12
  - MAX_TEXTURE_SIZE: 16384

Screens:
  - screen 1: resolution 1280x800, scale 2.0
  - screen 2: resolution 1920x1080, scale 1.0

Plugins:
  - console: 0.0.3
  - svg: 0.1.4

**Comment by tlambert03** [comment]
Hi @mikiotada, sorry you're running into this.  I'm curious if you've already tried installing into a clean environment?
It's a bit strange that you would have ended up with Qt: 5.9.7 ... so I'm wondering if perhaps this was your base environment with some older pre-existing dependencies?

```
conda create -y -n napari-env  -c conda-forge python=3.9 napari
conda activate napari-env

napari
```

**Comment by sofroniewn** [comment]
good catch on the 5.9.7 @tlambert03, if it's not that - i wonder @mikiotada did you ever see them and then maybe close them and now they won't come back? 

if you go to the window menu bar, can you add them in? (select layer controls/ layer list)

<img width="1076" alt="Screen Shot 2021-04-22 at 5 14 56 PM" src="https://user-images.githubusercontent.com/6531703/115799983-75aeb700-a38e-11eb-9320-c7fb33b12179.png">

**Comment by tlambert03** [comment]
oh yeah... that's an even better point! :)

**Comment by mikiotada** [comment]
oh wow, adding layers at the window menu bar solved the issue! 

Yeah, I was able to see them for a while. Probably I closed them by accident. I didn't know there is the window menu bar that we can change the napari viewer. Thanks! 

Thank you for maintaining this awesome library! @sofroniewn, @tlambert03
