### ISSUE TITLE
Drop support for edge_width_rel and scaling in markers

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#261]
## 🐛 Bug

I think we should drop support for exposing the `edge_width_rel` property and set the scaling property to always be `True`.

Only one of `edge_width_rel` and `edge_width` can ever be used and the rest of our mesh like layers only use `edge_width`. When making the `to_svg` conversion only `edge_width` is supported too. I think the api is cleaner and simpler without it.

Similarly in all our other mesh-like layers the equivalent of the `scaling` property is `True`. We should make sure though that the size of the markers is in units of the image and not of the screen, again similar to our other mesh-like layers.

@kevinyamauchi what is your opinion on this?

**Comment by kevinyamauchi** [comment]
I think this makes sense to me!

One additional thing we can sneak into this refactor: I think we should change how we set individual marker sizes. I propose that we keep the `marker_size` property, but change the size slider in the layer properties to modulate a `marker_scale_factor` layer property. Thus when rendered, each marker has size `marker_size * marker_scale_factor` and when the size slider is used, relative scaling is preserved.

Thoughts?

**Comment by sofroniewn** [comment]
@kevinyamauchi relative scaling makes sense, happy to explore

**Comment by sofroniewn** [comment]
Closed by #276
