### ISSUE TITLE
start issue - ValueError: dlsym(RTLD_DEFAULT, NSEventTrackingRunLoopMode): symbol not found

### ISSUE THREAD

**Issue by YubinXie** [napari/napari#2610]
## 🐛 Bug

I am not able to run napari on my mac - the old version works but not the latest one.
## To Reproduce

`import napari `

## Error

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-fb5950bf9f09> in <module>
      1 from skimage import data
----> 2 import napari
      3 
      4 viewer = napari.view_image(data.astronaut(), rgb=True)

~/miniconda3/envs/napari/lib/python3.7/site-packages/napari/__init__.py in <module>
      5 
      6 
----> 7 from .viewer import Viewer  # isort:skip
      8 
      9 # this unused import is here to fix a very strange bug.

~/miniconda3/envs/napari/lib/python3.7/site-packages/napari/viewer.py in <module>
      1 from typing import TYPE_CHECKING
      2 
----> 3 from .components import ViewerModel
      4 from .utils import config
      5 

~/miniconda3/envs/napari/lib/python3.7/site-packages/napari/components/__init__.py in <module>
     15 """
     16 
---> 17 from .camera import Camera
     18 from .dims import Dims
     19 from .layerlist import LayerList

~/miniconda3/envs/napari/lib/python3.7/site-packages/napari/components/camera.py in <module>
      3 from pydantic import validator
      4 
----> 5 from ..utils.events import EventedModel
      6 from ..utils.misc import ensure_n_tuple
      7 

~/miniconda3/envs/napari/lib/python3.7/site-packages/napari/utils/__init__.py in <module>
----> 1 from .colormaps import Colormap
      2 from .dask_utils import resize_dask_cache
      3 from .info import citation_text, sys_info
      4 from .notebook_display import nbscreenshot
      5 

~/miniconda3/envs/napari/lib/python3.7/site-packages/napari/utils/colormaps/__init__.py in <module>
      1 from .colorbars import make_colorbar
----> 2 from .colormap import Colormap
      3 from .colormap_utils import (
      4     ALL_COLORMAPS,
      5     AVAILABLE_COLORMAPS,

~/miniconda3/envs/napari/lib/python3.7/site-packages/napari/utils/colormaps/colormap.py in <module>
      4 from pydantic import validator
      5 
----> 6 from ..events import EventedModel
      7 from ..events.custom_types import Array
      8 from .colorbars import make_colorbar

~/miniconda3/envs/napari/lib/python3.7/site-packages/napari/utils/events/__init__.py in <module>
----> 1 from .event import EmitterGroup, Event, EventEmitter  # isort:skip
      2 from .containers._evented_list import EventedList
      3 from .containers._nested_list import NestableEventedList
      4 from .containers._selection import Selection
      5 from .containers._set import EventedSet

~/miniconda3/envs/napari/lib/python3.7/site-packages/napari/utils/events/event.py in <module>
     67 
     68 from typing_extensions import Literal
---> 69 from vispy.util.logs import _handle_exception, logger
     70 
     71 

~/miniconda3/envs/napari/lib/python3.7/site-packages/vispy/__init__.py in <module>
     28     pass
     29 
---> 30 from .util import config, set_log_level, keys, sys_info  # noqa
     31 from .util.wrappers import use, test  # noqa
     32 # load the two functions that IPython uses to instantiate an extension

~/miniconda3/envs/napari/lib/python3.7/site-packages/vispy/util/__init__.py in <module>
     12 from .fetching import load_data_file  # noqa
     13 from .frozen import Frozen  # noqa
---> 14 from . import fonts       # noqa
     15 from . import transforms  # noqa
     16 from .wrappers import use, run_subprocess  # noqa

~/miniconda3/envs/napari/lib/python3.7/site-packages/vispy/util/fonts/__init__.py in <module>
     11 __all__ = ['list_fonts']
     12 
---> 13 from ._triage import _load_glyph, list_fonts  # noqa, analysis:ignore
     14 from ._vispy_fonts import _vispy_fonts  # noqa, analysis:ignore

~/miniconda3/envs/napari/lib/python3.7/site-packages/vispy/util/fonts/_triage.py in <module>
     12     from ...ext.fontconfig import _list_fonts
     13 elif sys.platform == 'darwin':
---> 14     from ._quartz import _load_glyph, _list_fonts
     15 elif sys.platform.startswith('win'):
     16     from ._freetype import _load_glyph  # noqa, analysis:ignore

~/miniconda3/envs/napari/lib/python3.7/site-packages/vispy/util/fonts/_quartz.py in <module>
     10 from ctypes import byref, c_int32, c_byte
     11 
---> 12 from ...ext.cocoapy import cf, ct, quartz, CFRange, CFSTR, CGGlyph, UniChar, \
     13     kCTFontFamilyNameAttribute, kCTFontBoldTrait, kCTFontItalicTrait, \
     14     kCTFontSymbolicTrait, kCTFontTraitsAttribute, kCTFontAttributeName, \

~/miniconda3/envs/napari/lib/python3.7/site-packages/vispy/ext/cocoapy.py in <module>
   1125 NSDefaultRunLoopMode = c_void_p.in_dll(appkit, 'NSDefaultRunLoopMode')
   1126 NSEventTrackingRunLoopMode = c_void_p.in_dll(
-> 1127     appkit, 'NSEventTrackingRunLoopMode')
   1128 NSApplicationDidHideNotification = c_void_p.in_dll(
   1129     appkit, 'NSApplicationDidHideNotification')

ValueError: dlsym(RTLD_DEFAULT, NSEventTrackingRunLoopMode): symbol not found
## Environment

- Mac Big Sur
- Python 3.7

**Comment by tlambert03** [comment]
> Mac Big Sur
> Python 3.7

I'm actually surprised that napari would have ever worked for you on big sur using python 3.7.  As far as we've seen, big sur only works for python 3.9 ... Can you try 3.9?

**Comment by YubinXie** [comment]
i tried with 3.9 now, and still the same issue.

**Comment by YubinXie** [comment]
Update: 3.9.4 does not work. 3.9.0 works on importing.

**Comment by YubinXie** [comment]
I am not able to open any new image when I open napari with ipython:

no longer has a delegate to respond to shouldEnableURL

**Comment by tlambert03** [comment]
can you give us the full output of `napari --info` and `pip list`?

**Comment by YubinXie** [comment]
error
```
In [2]: 2021-04-23 14:42:43.537 python[72425:24261630] WARNING: <NSOpenPanel: 0x7fa11b3a7df0> -[NSSavePanel(exportedInterface) requestAppEnabledStateForItems:replyBlock:] no longer has a delegate to respond to shouldEnableURL
2021-04-23 14:42:43.538 python[72425:24261630] WARNING: <NSOpenPanel: 0x7fa11b3a7df0> -[NSSavePanel(exportedInterface) requestAppEnabledStateForItems:replyBlock:] no longer has a delegate to respond to shouldEnableURL
2021-04-23 14:42:43.538 python[72425:24261630] WARNING: <NSOpenPanel: 0x7fa11b3a7df0> -[NSSavePanel(exportedInterface) requestAppEnabledStateForItems:replyBlock:] no longer has a delegate to respond to shouldEnableURL
2021-04-23 14:42:43.538 python[72425:24261630] WARNING: <NSOpenPanel: 0x7fa11b3a7df0> -[NSSavePanel(exportedInterface) requestAppEnabledStateForItems:replyBlock:] no longer has a delegate to respond to shouldEnableURL
2021-04-23 14:42:43.538 python[72425:24261630] WARNING: <NSOpenPanel: 0x7fa11b3a7df0> -[NSSavePanel(exportedInterface) requestAppEnabledStateForItems:replyBlock:] no longer has a delegate to respond to shouldEnableURL
2021-04-23 14:42:43.538 python[72425:24261630] WARNING: <NSOpenPanel: 0x7fa11b3a7df0> -[NSSavePanel(exportedInterface) requestAppEnabledStateForItems:replyBlock:] no longer has a delegate to respond to shouldEnableURL
2021-04-23 14:42:43.538 python[72425:24261630] WARNING: <NSOpenPanel: 0x7fa11b3a7df0> -[NSSavePanel(exportedInterface) requestAppEnabledStateForItems:replyBlock:] no longer has a delegate to respond to shouldEnableURL
2021-04-23 14:42:43.538 python[72425:24261630] WARNING: <NSOpenPanel: 0x7fa11b3a7df0> -[NSSavePanel(exportedInterface) requestAppEnabledStateForItems:replyBlock:] no longer has a delegate to respond to shouldEnableURL
2021-04-23 14:42:43.539 python[72425:24261630] WARNING: <NSOpenPanel: 0x7fa11b3a7df0> -[NSSavePanel(exportedInterface) requestAppEnabledStateForItems:replyBlock:] no longer has a delegate to respond to shouldEnableURL
2021-04-23 14:42:43.539 python[72425:24261630] WARNING: <NSOpenPanel: 0x7fa11b3a7df0> -[NSSavePanel(exportedInterface) requestAppEnabledStateForItems:replyBlock:] no longer has a delegate to respond to shouldEnableURL
2021-04-23 14:42:43.539 python[72425:24261630] WARNING: <NSOpenPanel: 0x7fa11b3a7df0> -[NSSavePanel(exportedInterface) requestAppEnabledStateForItems:replyBlock:] no longer has a delegate to respond to shouldEnableURL
2021-04-23 14:42:43.539 python[72425:24261630] WARNING: <NSOpenPanel: 0x7fa11b3a7df0> -[NSSavePanel(exportedInterface) requestAppEnabledStateForItems:replyBlock:] no longer has a delegate to respond to shouldEnableURL
2021-04-23 14:42:43.539 python[72425:24261630] WARNING: <NSOpenPanel: 0x7fa11b3a7df0> -[NSSavePanel(exportedInterface) requestAppEnabledStateForItems:replyBlock:] no longer has a delegate to respond to shouldEnableURL
2021-04-23 14:42:43.539 python[72425:24261630] WARNING: <NSOpenPanel: 0x7fa11b3a7df0> -[NSSavePanel(exportedInterface) requestAppEnabledStateForItems:replyBlock:] no longer has a delegate to respond to shouldEnableURL

```

/Users/xiey/miniconda3/envs/napari-env/lib/python3.9/site-packages/napari/__main__.py:356: UserWarning: pythonw executable not found.
To unfreeze the menubar on macOS, click away from napari to another app, then reactivate napari. To avoid this problem, please install python.app in conda using:
conda install -c conda-forge python.app
  warnings.warn(msg)
napari: 0.4.7
Platform: macOS-10.16-x86_64-i386-64bit
System: MacOS 11.2.3
Python: 3.9.0 (default, Nov 15 2020, 06:25:35)  [Clang 10.0.0 ]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.20.2
SciPy: 1.6.2
Dask: 2021.04.0
VisPy: 0.6.6

OpenGL:
  - GL version:  2.1 ATI-4.2.15
  - MAX_TEXTURE_SIZE: 16384

Screens:
  - screen 1: resolution 2560x1440, scale 2.0

Plugins:
  - console: 0.0.3
  - svg: 0.1.4



Package                       Version
----------------------------- -------------------
alabaster                     0.7.12
appdirs                       1.4.4
appnope                       0.1.2
attrs                         20.3.0
Babel                         2.9.0
backcall                      0.2.0
cachey                        0.2.1
certifi                       2020.12.5
chardet                       4.0.0
cloudpickle                   1.6.0
cycler                        0.10.0
dask                          2021.4.0
decorator                     4.4.2
docstring-parser              0.7.3
docutils                      0.16
freetype-py                   2.2.0
fsspec                        2021.4.0
HeapDict                      1.0.1
idna                          2.10
imageio                       2.9.0
imagesize                     1.2.0
ipykernel                     5.5.3
ipython                       7.22.0
ipython-genutils              0.2.0
jedi                          0.18.0
Jinja2                        2.11.3
jsonschema                    3.2.0
jupyter-client                6.1.12
jupyter-core                  4.7.1
kiwisolver                    1.3.1
locket                        0.2.1
magicgui                      0.2.9
MarkupSafe                    1.1.1
matplotlib                    3.4.1
napari                        0.4.7
napari-console                0.0.3
napari-plugin-engine          0.1.9
napari-svg                    0.1.4
networkx                      2.5.1
NEURON                        7.6
numpy                         1.20.2
numpydoc                      1.1.0
packaging                     20.9
parso                         0.8.2
partd                         1.2.0
pexpect                       4.8.0
pickleshare                   0.7.5
Pillow                        8.2.0
pip                           21.0.1
prompt-toolkit                3.0.18
psutil                        5.8.0
ptyprocess                    0.7.0
pydantic                      1.8.1
Pygments                      2.8.1
PyOpenGL                      3.1.5
pyparsing                     2.4.7
PyQt5                         5.15.4
PyQt5-Qt5                     5.15.2
PyQt5-sip                     12.8.1
pyrsistent                    0.17.3
python-dateutil               2.8.1
pytz                          2021.1
PyWavelets                    1.1.1
PyYAML                        5.4.1
pyzmq                         22.0.3
qtconsole                     5.0.3
QtPy                          1.9.0
requests                      2.25.1
scikit-image                  0.18.1
scipy                         1.6.2
setuptools                    52.0.0.post20210125
six                           1.15.0
snowballstemmer               2.1.0
Sphinx                        3.5.4
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        1.0.3
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.4
tifffile                      2021.4.8
toolz                         0.11.1
tornado                       6.1
traitlets                     5.0.5
typing-extensions             3.7.4.3
urllib3                       1.26.4
vispy                         0.6.6
wcwidth                       0.2.5
wheel                         0.36.2
wrapt                         1.12.1

**Comment by sofroniewn** [comment]
>I am not able to open any new image when I open napari with ipython:
>
> no longer has a delegate to respond to shouldEnableURL

Is this likely related to https://github.com/napari/napari/issues/2571? Is the issue with the open dialog?

Sorry that things aren't working for you @YubinXie. Can you maybe give us a little more detail on exactly how you're trying to open the image and the full error message. Screenshots could be really helpful too. This will let us help you better. Thanks!

**Comment by YubinXie** [comment]
@sofroniewn Hi Nicholas, I was trying to open new images with Menu bar of Napari and the window for choosing file appeared for one second and gone. No more other errors but showing the following in terminal:

```In [2]: 2021-04-23 14:42:43.537 python[72425:24261630] WARNING: <NSOpenPanel: 0x7fa11b3a7df0> -[NSSavePanel(exportedInterface) requestAppEnabledStateForItems:replyBlock:] no longer has a delegate to respond to shouldEnableURL
2021-04-23 14:42:43.538 python[72425:24261630] WARNING: <NSOpenPanel: 0x7fa11b3a7df0> -[NSSavePanel(exportedInterface) requestAppEnabledStateForItems:replyBlock:] no longer has a delegate to respond to shouldEnableURL
2021-04-23 14:42:43.538 python[72425:24261630] WARNING: <NSOpenPanel: 0x7fa11b3a7df0> -[NSSavePanel(exportedInterface) requestAppEnabledStateForItems:replyBlock:] no longer has a delegate to respond to shouldEnableURL
2021-04-23 14:42:43.538 python[72425:24261630] WARNING: <NSOpenPanel: 0x7fa11b3a7df0> -[NSSavePanel(exportedInterface) requestAppEnabledStateForItems:replyBlock:] no longer has a delegate to respond to shouldEnableURL
2021-04-23 14:42:43.538 python[72425:24261630] WARNING: <NSOpenPanel: 0x7fa11b3a7df0> -[NSSavePanel(exportedInterface) requestAppEnabledStateForItems:replyBlock:] no longer has a delegate to respond to shouldEnableURL
2021-04-23 14:42:43.538 python[72425:24261630] WARNING: <NSOpenPanel: 0x7fa11b3a7df0> -[NSSavePanel(exportedInterface) requestAppEnabledStateForItems:replyBlock:] no longer has a delegate to respond to shouldEnableURL
2021-04-23 14:42:43.538 python[72425:24261630] WARNING: <NSOpenPanel: 0x7fa11b3a7df0> -[NSSavePanel(exportedInterface) requestAppEnabledStateForItems:replyBlock:] no longer has a delegate to respond to shouldEnableURL
2021-04-23 14:42:43.538 python[72425:24261630] WARNING: <NSOpenPanel: 0x7fa11b3a7df0> -[NSSavePanel(exportedInterface) requestAppEnabledStateForItems:replyBlock:] no longer has a delegate to respond to shouldEnableURL
2021-04-23 14:42:43.539 python[72425:24261630] WARNING: <NSOpenPanel: 0x7fa11b3a7df0> -[NSSavePanel(exportedInterface) requestAppEnabledStateForItems:replyBlock:] no longer has a delegate to respond to shouldEnableURL
2021-04-23 14:42:43.539 python[72425:24261630] WARNING: <NSOpenPanel: 0x7fa11b3a7df0> -[NSSavePanel(exportedInterface) requestAppEnabledStateForItems:replyBlock:] no longer has a delegate to respond to shouldEnableURL
2021-04-23 14:42:43.539 python[72425:24261630] WARNING: <NSOpenPanel: 0x7fa11b3a7df0> -[NSSavePanel(exportedInterface) requestAppEnabledStateForItems:replyBlock:] no longer has a delegate to respond to shouldEnableURL
2021-04-23 14:42:43.539 python[72425:24261630] WARNING: <NSOpenPanel: 0x7fa11b3a7df0> -[NSSavePanel(exportedInterface) requestAppEnabledStateForItems:replyBlock:] no longer has a delegate to respond to shouldEnableURL
2021-04-23 14:42:43.539 python[72425:24261630] WARNING: <NSOpenPanel: 0x7fa11b3a7df0> -[NSSavePanel(exportedInterface) requestAppEnabledStateForItems:replyBlock:] no longer has a delegate to respond to shouldEnableURL
2021-04-23 14:42:43.539 python[72425:24261630] WARNING: <NSOpenPanel: 0x7fa11b3a7df0> -[NSSavePanel(exportedInterface) requestAppEnabledStateForItems:replyBlock:] no longer has a delegate to respond to shouldEnableURL```

**Comment by sofroniewn** [comment]
> @sofroniewn Hi Nicholas, I was trying to open new images with Menu bar of Napari and the window for choosing file appeared for one second and gone. No more other errors but showing the following in terminal:

@YubinXie, just to confirm is this after launching from IPython?

@goanpeca do you know what might be causing that error (or #2571, if it is related)?

**Comment by goanpeca** [comment]
@YubinXie could you open a terminal, activate the conda env where and paste the output of conda list?

```
conda activate napari-env
conda list
```

Thanks!

**Comment by YubinXie** [comment]
> > @sofroniewn Hi Nicholas, I was trying to open new images with Menu bar of Napari and the window for choosing file appeared for one second and gone. No more other errors but showing the following in terminal:
> 
> @YubinXie, just to confirm is this after launching from IPython?
> 
> @goanpeca do you know what might be causing that error (or #2571, if it is related)?

yes

**Comment by YubinXie** [comment]
> @YubinXie could you open a terminal, activate the conda env where and paste the output of conda list?
> 
> ```
> conda activate napari-env
> conda list
> ```
> 
> Thanks!

here it is:

```
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12                   pypi_0    pypi
appdirs                   1.4.4                    pypi_0    pypi
appnope                   0.1.2                    pypi_0    pypi
attrs                     20.3.0                   pypi_0    pypi
babel                     2.9.0                    pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
ca-certificates           2020.12.5            h033912b_0    conda-forge
cachey                    0.2.1                    pypi_0    pypi
certifi                   2020.12.5        py39h6e9494a_1    conda-forge
chardet                   4.0.0                    pypi_0    pypi
cloudpickle               1.6.0                    pypi_0    pypi
cycler                    0.10.0                   pypi_0    pypi
dask                      2021.4.0                 pypi_0    pypi
decorator                 4.4.2                    pypi_0    pypi
docstring-parser          0.7.3                    pypi_0    pypi
docutils                  0.16                     pypi_0    pypi
freetype-py               2.2.0                    pypi_0    pypi
fsspec                    2021.4.0                 pypi_0    pypi
heapdict                  1.0.1                    pypi_0    pypi
idna                      2.10                     pypi_0    pypi
imageio                   2.9.0                    pypi_0    pypi
imagesize                 1.2.0                    pypi_0    pypi
ipykernel                 5.5.3                    pypi_0    pypi
ipython                   7.22.0                   pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
jedi                      0.18.0                   pypi_0    pypi
jinja2                    2.11.3                   pypi_0    pypi
jsonschema                3.2.0                    pypi_0    pypi
jupyter-client            6.1.12                   pypi_0    pypi
jupyter-core              4.7.1                    pypi_0    pypi
kiwisolver                1.3.1                    pypi_0    pypi
libcxx                    10.0.0                        1  
libffi                    3.3                  hb1e8313_2  
locket                    0.2.1                    pypi_0    pypi
magicgui                  0.2.9                    pypi_0    pypi
markupsafe                1.1.1                    pypi_0    pypi
matplotlib                3.4.1                    pypi_0    pypi
napari                    0.4.7                    pypi_0    pypi
napari-console            0.0.3                    pypi_0    pypi
napari-plugin-engine      0.1.9                    pypi_0    pypi
napari-svg                0.1.4                    pypi_0    pypi
ncurses                   6.2                  h0a44026_1  
networkx                  2.5.1                    pypi_0    pypi
numpy                     1.20.2                   pypi_0    pypi
numpydoc                  1.1.0                    pypi_0    pypi
openssl                   1.1.1k               h0d85af4_0    conda-forge
packaging                 20.9                     pypi_0    pypi
parso                     0.8.2                    pypi_0    pypi
partd                     1.2.0                    pypi_0    pypi
pexpect                   4.8.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    8.2.0                    pypi_0    pypi
pip                       21.0.1           py39hecd8cb5_0  
prompt-toolkit            3.0.18                   pypi_0    pypi
psutil                    5.8.0                    pypi_0    pypi
ptyprocess                0.7.0                    pypi_0    pypi
pydantic                  1.8.1                    pypi_0    pypi
pygments                  2.8.1                    pypi_0    pypi
pyopengl                  3.1.5                    pypi_0    pypi
pyparsing                 2.4.7                    pypi_0    pypi
pyqt5                     5.15.4                   pypi_0    pypi
pyqt5-qt5                 5.15.2                   pypi_0    pypi
pyqt5-sip                 12.8.1                   pypi_0    pypi
pyrsistent                0.17.3                   pypi_0    pypi
python                    3.9.0                h88f2d9e_2  
python-dateutil           2.8.1                    pypi_0    pypi
python.app                1.3              py39hcbf5805_4    conda-forge
python_abi                3.9                      1_cp39    conda-forge
pytz                      2021.1                   pypi_0    pypi
pywavelets                1.1.1                    pypi_0    pypi
pyyaml                    5.4.1                    pypi_0    pypi
pyzmq                     22.0.3                   pypi_0    pypi
qtconsole                 5.0.3                    pypi_0    pypi
qtpy                      1.9.0                    pypi_0    pypi
readline                  8.1                  h9ed2024_0  
requests                  2.25.1                   pypi_0    pypi
scikit-image              0.18.1                   pypi_0    pypi
scipy                     1.6.2                    pypi_0    pypi
setuptools                52.0.0           py39hecd8cb5_0  
six                       1.15.0                   pypi_0    pypi
snowballstemmer           2.1.0                    pypi_0    pypi
sphinx                    3.5.4                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.2                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.2                    pypi_0    pypi
sphinxcontrib-htmlhelp    1.0.3                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.3                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.4                    pypi_0    pypi
sqlite                    3.35.4               hce871da_0  
tifffile                  2021.4.8                 pypi_0    pypi
tk                        8.6.10               hb0a8c7a_0  
toolz                     0.11.1                   pypi_0    pypi
tornado                   6.1                      pypi_0    pypi
traitlets                 5.0.5                    pypi_0    pypi
typing-extensions         3.7.4.3                  pypi_0    pypi
tzdata                    2020f                h52ac0ba_0  
urllib3                   1.26.4                   pypi_0    pypi
vispy                     0.6.6                    pypi_0    pypi
wcwidth                   0.2.5                    pypi_0    pypi
wheel                     0.36.2             pyhd3eb1b0_0  
wrapt                     1.12.1                   pypi_0    pypi
xz                        5.2.5                h1de35cc_0  
zlib                      1.2.11               h1de35cc_3 
```

**Comment by goanpeca** [comment]
@YubinXie how about you try to install from scratch but using conda?

```bash
conda create -n napari-env2 python=3.9 napari -c conda-forge
conda activated napari-env2
napari
```

**Comment by YubinXie** [comment]
Some updates:
When i use napari directly in terminal without calling from python. The loading of the file works.

**Comment by YubinXie** [comment]
> @YubinXie how about you try to install from scratch but using conda?
> 
> ```shell
> conda create -n napari-env2 python=3.9 napari -c conda-forge
> conda activated napari-env2
> napari
> ```

I think it is not install issue but ipython and Mac issue. I will directly call napari from terminal, which seems to be working.
