### ISSUE TITLE
Labels annotation

### ISSUE THREAD

**Issue by Czaki** [napari/napari#2622]
## 🚀 Feature

Add possibility to display labels annotation in inteface

## Motivation

When adjusting parameters of ROI classification it is nice to simply preview single label information to understand why a given component is classified in a such way. 
![Zrzut ekranu z 2021-04-27 13-27-06](https://user-images.githubusercontent.com/3826210/116236634-99437a00-a75f-11eb-9081-1e68e3546d91.png)

## Pitch

Add annotation dict to Labels and display its content respectively to current component using tooltip.  

## Additional context

The screenshot comes from PartSeg and I could implement it in napari if You think that this is worth it.

**Comment by jni** [comment]
@Czaki btw do you know labels does have an annotations table called `properties=`? See:

https://github.com/napari/napari/blob/97865a9051a3ce33ffd58903ea1cb016fd1b4ba9/examples/add_labels_with_properties.py

However, the option to display these on hover would be extremely welcome! (Currently they appear in the status bar)

**Comment by Czaki** [comment]
The property does not allow simple add text like in example. As you could see I need to show numerical parameters, not only labels. 
Of course, I could create one label for each parameter, like `"voxels: 502"` but in such a case there could be heavy collect step.

**Comment by jni** [comment]
> The property does not allow simple add text like in example

Huh? You pass in a table of columns, e.g. {"index": [51, 47, ...], "voxels": [502, 320, ...], "sharpness": [2.21, 3.14, ...]} and you would get an annotation per segment.

**Comment by Czaki** [comment]
Ok. I see that I wrong understand, but this construction forced to have all properties for all components defined. Personally, I prefer some sparse format. 

I think that there are provided numbers of components which should have a such label. 

Text which I show on example will not fit in status bar.

**Comment by jni** [comment]
Missing labels in the properties table are also allowed.

> The property does not allow simple add text like in example

Yes, that's why I said above that the hover would be a very welcome addition!

**Comment by Czaki** [comment]
> Missing labels in the properties table are also allowed.

I do not see this described in docstring. Did You mean `None` instead of value?

Did I correct to understand that property should be array of length `N+1` instead `N` (as zero means background)?

**Comment by jni** [comment]
> I do not see this described in docstring

See #2596 😂 Sorry!

**Comment by tlambert03** [comment]
i think this was added in #2658
