### ISSUE TITLE
Use static base class for Image if possible

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#2623]
## 🐛 Bug
tiny thing, but don't want to forget it... in `image.py`, this dynamic inheritance pattern breaks IDE inspection for anything annotated as an `Image`

```
_image_base_class = _get_image_base_class()

class Image(_image_base_class):
```

would be nice to figure out a way to accomplish the same goal without the dynamic base class.

**Comment by goanpeca** [comment]
>would be nice to figure out a way to accomplish the same goal without the dynamic base class.

Any more details here can help @tlambert03 :)

**Comment by tlambert03** [comment]
sorry, will take care of it! :)
