### ISSUE TITLE
Windows test fail on CI

### ISSUE THREAD

**Issue by Czaki** [napari/napari#2629]
## 🐛 Bug

Current CI configuration fails because fail of OpenGL installation:

```

Run git clone --depth 1 git://github.com/pyvista/gl-ci-helpers.git
Cloning into 'gl-ci-helpers'...

SUCCESS: The file (or folder): "C:\Windows\system32\opengl32.dll" now owned by the administrators group.
processed file: C:\Windows\system32\opengl32.dll
Successfully processed 1 files; Failed processing 0 files
Downloading vispy/demo-data@master/mesa/opengl32_mingw_64.dll (raw)
Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (404) Not Found."
At D:\a\napari\napari\gl-ci-helpers\appveyor\install_opengl.ps1:42 char:9
+         $webclient.DownloadFile($url, $filepath)
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException
```

See: https://github.com/napari/napari/runs/2462557951?check_suite_focus=true

## Additional context

As #2481 is still open then the bot does not open new issue. 

cc @sofroniewn @jni @tlambert03

**Comment by jni** [comment]
Thanks for creating this @Czaki. Do you have any idea what changed/how to fix it? I don't think we have touched our CI settings recently.

**Comment by Czaki** [comment]
It looks like `vispy/demo-data` rename `master` branch to `main` so github update links 
from https://github.com/vispy/demo-data/raw/master/mesa/opengl32_mingw_64.dll to 
https://github.com/vispy/demo-data/raw/main/mesa/opengl32_mingw_64.dll

These need to be fixed in the https://github.com/pyvista/gl-ci-helpers/blob/master/appveyor/install_opengl.ps1 script 

There is even proper PR created https://github.com/pyvista/gl-ci-helpers/pull/6 and we should wait. Maybe you know one of the developers and could ping them using another channel.

**Comment by tlambert03** [comment]
We can also just vendor that script.  There's no real need for it to come from their repo

**Comment by tlambert03** [comment]
Yeah let's copy it and put it in our .github folder or something.  I can do that later today, unless someone wants to tackle it sooner?

**Comment by Czaki** [comment]
> We can also just vendor that script. There's no real need for it to come from their repo

If you decide to do this please do this using a separate repository to simplify usage by plugins creator.

**Comment by tlambert03** [comment]
We would put it in the cookie cutter too.  That script isn't very dynamic at all.

**Comment by tlambert03** [comment]
I'm also ok with just fixing the url, can you make a PR?

**Comment by tlambert03** [comment]
Oh I see, it needs to happen upstream...

**Comment by Czaki** [comment]
I have had created #2630 which should allow an easier understand of such bugs.

**Comment by larsoner** [comment]
Should be all better now

**Comment by Czaki** [comment]
Thanks

**Comment by tlambert03** [comment]
thanks @larsoner!
