### ISSUE TITLE
Support Enum preference types in preferences window

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#2634]
## 🐛 Bug

We are unable to show preferences that are `Enum` types in the preferences window

see: https://github.com/napari/napari/pull/2211#pullrequestreview-610272341 for a little background

**Comment by goanpeca** [comment]
@tlambert03 indeed, I think I want to rework a bit all this logic to remove the qtform external dependency and support more use cases here.

**Comment by tlambert03** [comment]
thanks!
