### ISSUE TITLE
Table headers not readable in dark theme

### ISSUE THREAD

**Issue by haesleinhuepf** [napari/napari#2644]
## 🐛 Bug
Hi all, 

in dark theme, table headers are not readable, likely because their background-color is not defined in the stylesheet. This may be different depending on operating system.

Dark theme:
![image](https://user-images.githubusercontent.com/12660498/116822865-8ecf1900-ab81-11eb-93e7-95e8612c6436.png)

Light theme:
![image](https://user-images.githubusercontent.com/12660498/116822880-a0b0bc00-ab81-11eb-953e-333720423df8.png)

## To Reproduce

Run this from a jupyter notebook:
```
%gui qt
```

```
import napari

viewer = napari.Viewer()

data = {
    'header_a':[1,2,3],
    'header_b':[1,2,3]
}

from magicgui.widgets import Table

table = Table(data)
viewer.window.add_dock_widget(table.native)
```

## Expected behavior

The background color of the table headers should change so that the changed font-colour becomes readable again.

## Environment

 - Please copy and paste the information at napari info option in help menubar here:
napari: 0.4.7
Platform: Windows-10-10.0.19041-SP0
Python: 3.8.8 (default, Feb 24 2021, 15:54:32) [MSC v.1928 64 bit (AMD64)]
Qt: 5.15.2
PyQt5: 5.15.2
NumPy: 1.19.2
SciPy: 1.6.1
Dask: 2021.03.0
VisPy: 0.6.6

OpenGL:
- GL version: 4.6.0 - Build 27.20.100.8681
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1080, scale 1.0

Plugins:
- console: 0.0.2
- svg: 0.1.4

 - Any other relevant information:
I'm running on Windows 10 with a custom personalization (Windows mode / app mode):
![image](https://user-images.githubusercontent.com/12660498/116822993-26346c00-ab82-11eb-8f30-9cecb7fa787f.png)

**Comment by tlambert03** [comment]
interesting.  wonder if this is a windows thing, or a custom style thing

here's what I see (macOS 10.15, napari master):

<img width="745" alt="light" src="https://user-images.githubusercontent.com/1609449/116823150-e7d28900-ab50-11eb-8e8e-a8efea4a2f44.png">
<img width="744" alt="dark" src="https://user-images.githubusercontent.com/1609449/116823151-e7d28900-ab50-11eb-86a9-4ba46e7b1f82.png">

will try to test on windows soon... or, if you want to dig into this.  The file(s) to play with would be any of the [`.qss` files in `qt_resources/styles`](https://github.com/napari/napari/tree/master/napari/_qt/qt_resources/styles) (they all get merged into one at runtime, so it doesn't matter too much which one).  And the relevant documentation is [here](https://doc.qt.io/qt-5/stylesheet-reference.html) (scroll down to QTableView) and an example [here](https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qtableview).

**Comment by haesleinhuepf** [comment]
Thanks for the pointer @tlambert03! I'm playing with it. Looks like [here](https://stackoverflow.com/questions/11454694/how-to-change-the-header-background-color-of-a-qtableview) is a solution. I will prepare a PR.
