### ISSUE TITLE
Toggle theme menu missing in 0.4.8-dev

### ISSUE THREAD

**Issue by haesleinhuepf** [napari/napari#2646]
## 🐛 Bug

While fixing #2644 I had issues toggling the theme of napari because the corresponding menu is missing in the current master branch:
![image](https://user-images.githubusercontent.com/12660498/116824241-77942980-ab89-11eb-8625-0001c4a279a1.png)

In comparison 0.4.7:
![image](https://user-images.githubusercontent.com/12660498/116824277-9eeaf680-ab89-11eb-9b3a-3561d2cbc649.png)

Furthermore, the shortcut for toggling the view is hard to read. What is the second key?
![image](https://user-images.githubusercontent.com/12660498/116824336-e2ddfb80-ab89-11eb-9b28-e17825ec23a7.png)

## To Reproduce

```
git clone https://github.com/napari/napari
cd napari
pit install -e .
napari 
```

Take first screenshot

```
pip install napari==0.4.7
napari
```

Take second screenshot

```
pit install -e .
napari 
```

Help > Show Key Bindings

Take third screenshot

## Expected behavior

Please bring back the `View > Toggle theme` menu

## Environment

 - Please copy and paste the information at napari info option in help menubar here:
napari: 0.4.8.dev78+g7c74df3d
Platform: Windows-10-10.0.19041-SP0
Python: 3.8.8 (default, Feb 24 2021, 15:54:32) [MSC v.1928 64 bit (AMD64)]
Qt: 5.15.2
PyQt5: 5.15.2
NumPy: 1.19.2
SciPy: 1.6.1
Dask: 2021.03.0
VisPy: 0.6.6

OpenGL:
- GL version: 4.6.0 - Build 27.20.100.8681
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1080, scale 1.0

Plugins:
- console: 0.0.2
- scikit-image: 0.4.8.dev78+g7c74df3d
- svg: 0.1.4

**Comment by tlambert03** [comment]
removed in https://github.com/napari/napari/pull/2462

second key is shift (up arrow) `⇧` ... agree... it looks terrible on Windows :/

**Comment by haesleinhuepf** [comment]
I see. Ok, it this was intentional, fine with me. Wo uses light theme anyway? :-)
