### ISSUE TITLE
Add a sample_ray method to layers

### ISSUE THREAD

**Issue by kevinyamauchi** [napari/napari#2653]
## 🚀 Feature
In support of 3D picking, I think it would be nice to add a method to the base layer that calculates end points of the ray going through the data volume from a point in the canvas in the direction of the view.

## Motivation

This ray (`sample_ray`?) can be used for 3D picking or sampling/exploring data along the ray (e.g., plotting intensity, finding voxels with specific values)

## Pitch

We add a method to the base layer class that when given a point on the canvas (in canvas coordinates), finds the intersection between the ray cast from that point in the direction of the view with the axis-aligned bounding box of the data. In this context, "axis-aligned" means the bounding box is aligned with the axes of the data. For now, the bounding box is the extents of the data (`layer._extent_data`?).

In a next step, we could add some basic 3D picking to the layers using the `sample_ray` method. For labels, it's fairly straight forward. For Points and Shapes, we might need to be a bit more careful about performance (e.g., make axis aligned bounding boxes for each object and then test for intersection using those).

I have made a (quick and dirty) prototype implementation of finding the intersections sample ray with the data bounding box (used to perform 3D picking) [here](https://github.com/kevinyamauchi/napari-label-picker/blob/c5c9d980360962d14adca2739e103591e8429ff6/napari_label_picker/label_selection_model.py#L40-L113) (`near_point` and `far_point` are the end points of the `sample_ray` in data coordinates).

In action:
![3d_picking](https://user-images.githubusercontent.com/1120672/116980580-af54bb80-acc6-11eb-9faf-147644d86c22.gif)

**Comment by kevinyamauchi** [comment]
@sofroniewn , where is the best place to get caught up on the napari transform system? In particular, I would like to get the transformation between the screen coordinates (i.e., coordinates returned by the event.pos in the mouse event) and the data coordinates.

**Comment by sofroniewn** [comment]
This is awesome @kevinyamauchi! We've been trying to move cursor position information off the layer, so I'd prefer if this wasn't directly on the base layer, but instead was something that could be calculated with the layer. One option would be to add `viewer.cursor.ray` which contained the ray in world coordinates (note `viewer.cursor.position` contains the position in world coordinates in 2D - I'm not actually sure what it has in 3D!)

Given the ray in world coordinates each layer can map that back to make a ray in data coordinates

> @sofroniewn , where is the best place to get caught up on the napari transform system? In particular, I would like to get the transformation between the screen coordinates (i.e., coordinates returned by the event.pos in the mouse event) and the data coordinates.

The key method to go from canvas coordinates (what you call screen above, but the origin is in the top left of the canvas) to world coordinates uses the function defined here https://github.com/napari/napari/blob/097dca8763f5414732887a89a29f613047304580/napari/_qt/qt_viewer.py#L661-L684

and updates the cursor here https://github.com/napari/napari/blob/097dca8763f5414732887a89a29f613047304580/napari/_qt/qt_viewer.py#L720-L721

I think you could also use/ adapt that method to make the ray and update `viewer.cursor.ray`.

That cursor position then gets added to the mouse event `event.position`, you could also add `event.ray` here https://github.com/napari/napari/blob/097dca8763f5414732887a89a29f613047304580/napari/_qt/qt_viewer.py#L723-L724

And then inside each layer mouse function callback there is a line
```python
    coordinates = layer.world_to_data(event.position)
```
see https://github.com/napari/napari/blob/097dca8763f5414732887a89a29f613047304580/napari/layers/labels/_labels_mouse_bindings.py#L24 for example

and you then have something like

```python
    data_ray = layer.world_to_data(event.ray)
```

How does this sound?

**Comment by kevinyamauchi** [comment]
Thank you, @sofroniewn ! This is super helpful. I agree that we should try to keep the cursor stuff off of the layers and I think the general approach you outlined looks good.

I have a couple of follow up questions:

- in napari, are "world coordinates" the same as vispy ["scene coordinates"](https://github.com/vispy/vispy/blob/e33aae23847e8e5f43248ba9d014cc4aea211a90/vispy/visuals/transforms/transform_system.py#L15-L58)
-  Why is the camera transform used in the [`_map_canvas2world()` method](https://github.com/napari/napari/blob/097dca8763f5414732887a89a29f613047304580/napari/_qt/qt_viewer.py#L661-L684)? From [this issue](https://github.com/vispy/vispy/issues/1699#issuecomment-525101399), it looks like the camera transform isn't the complete transformation from canvas to scene. From my reading/experimentation, I think the `ViewBox.scene.transform` is what we want. That being said, I'm still trying to wrap my head around the vispy coordinates systems and transforms, so I am not totally sure.

**Comment by sofroniewn** [comment]
> in napari, are "world coordinates" the same as vispy "scene coordinates"

Yes, but "world coordinates" in napari are fully nD, I think we at places might say "worldslice coordinates" to mean the "scene coordinates"

> From this issue, it looks like the camera transform isn't the complete transformation from canvas to scene.

Hmm that could be - i think in 2D some of this stuff might not matter / stuff might be equivalent so we didn't notice, but in 3D the differences might be more significant.

My hope though is that we could keep changes localized to the `_map_canvas2world` method and just make it so that it does the right thing for us with 3D canvases
