### ISSUE TITLE
Add `test_plugin_manager` fixture to `make_napari_viewer`?

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#2676]
## 🚀 Feature
#2535 added the `test_napari_plugin_manager` fixture, which mocks the plugin manager to prevent discovery of plugins unless they are specifically registered.  I've still be noticing various local test failures due to leaked widgets and other things caused by plugins in my environment.
If we added that `test_napari_plugin_manager` to the `make_napari_viewer`, it would immediately make a lot of our tests less prone to breakage from plugins in the env.  However ... it would also immediately break the tests of any plugins that were using `make_napari_viewer`... until they manually registered with something like:

```python
import my_plugin_module

def test_something(make_napari_viewer, test_napari_plugin_manager):
    test_napari_plugin_manager.register(my_plugin_module)
    ...
```

... _or_ if we changed all of our internal `make_napari_viewer` fixture to something that plugins _weren't_ using, so that we can patch it as desired.

thoughts?

**Comment by sofroniewn** [comment]
Need to wrap my head around this one, sorry - will think on it and get back to you!!

**Comment by tlambert03** [comment]
no hurry.  it's there if we want it :)  let me know if my explanation needs improving
