### ISSUE TITLE
Segfault of test on linux

### ISSUE THREAD

**Issue by Czaki** [napari/napari#2682]
## 🐛 Bug

As requested I try to debug why `napari` test set ends with an error on Linux. I create this issue to collect the current state of knowledge. 

### Operating system:  
Ubuntu 20.10 x86_64 
Python installed with pyenv 
Gdbinit:
```
$ cat ~/.gdbinit 
add-auto-load-safe-path ~/.pyenv

```

### Found problems
1. Current tests often ends with `Segmentation fault` during `napari/_qt/_tests/test_qt_notifications.py` 

Doing bin search on git history I found that bug hammens from version 3e35226f8f467fe957440635bfffb235e6d1d03e (Add global progress wrapper and ProgressBar widget (#2580))

To debug this I run who code under gdb with command `CI=1 gdb --args  `pyenv which python` -m pytest napari` 

Then I got:
```
Thread 1 "python" received signal SIGSEGV, Segmentation fault.
0x00007fffaa675976 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) () from /home/czaki/.pyenv/versions/3.8.3/envs/napari/lib/python3.8/site-packages/PyQt5/Qt/lib/libQt5Widgets.so.5
```  

I see also other similar errors. 

After googling I found topics like this:
https://forum.qt.io/topic/80629/totally-confusing-segmentation-violation/2

All of them suggest that problems happen when having unprocessed events and delete some Qt Object ealier. This bug may comes from using `del` statement instead of `oject.deleteLater()`

**Comment by Czaki** [comment]
I found that if I disable all tests from `test_progress.py` then the test passes without segfault.
Enable any of the tests ends with segfault in `test_qt_notifications.py` And based on the output of the debugger it looks like unprocessed events.

**Comment by tlambert03** [comment]
That's super useful information @Czaki!  Thanks so much for digging.  I'll try to take a closer look at that soon if you haven't already fully solved it.

**Comment by Czaki** [comment]
I partially solved it. The problem is caused by attaching ProgressBar to the viewer which is not shown. There are a set of actions that are waiting to perform, but before executing them, the viewer was destroyed, and events are still waiting on the execution queue. Then, in the next tests, Qt try to perform these events, but objects were already destroyed. 

If you have time, you could start from these changes: https://github.com/Czaki/napari/commit/50b987450a6b9bd19fbbbc07c3e93f5aad3e0cd2

Now I stuck on
```
if any([n.__class__.__name__ != 'CanvasBackendDesktop' for n in leaks]):
>           raise AssertionError(f'Widgets leaked!: {leaks}')
E           AssertionError: Widgets leaked!: {<PyQt5.QtWidgets.QMenu object at 0x7f8cbb701c10>, <napari._qt.dialogs.qt_modal.QtPopup object at 0x7f8d14d8b430>, <PyQt5.QtWidgets.QMenu object at 0x7f8cbb76aca0>, <PyQt5.QtWidgets.QMenu object at 0x7f8cbb7018b0>, <PyQt5.QtWidgets.QFrame object at 0x7f8d14df7d30>, <PyQt5.QtWidgets.QMenu object at 0x7f8d53c2e160>, <napari._qt.qt_main_window._QtMainWindow object at 0x7f8d53c7fb80>, <PyQt5.QtWidgets.QMenu object at 0x7f8cbb7019d0>, <PyQt5.QtWidgets.QMenu object at 0x7f8cbb701b80>, <PyQt5.QtWidgets.QMenu object at 0x7f8d14e04280>, <PyQt5.QtWidgets.QMenu object at 0x7f8d53c2e280>, <PyQt5.QtWidgets.QFrame object at 0x7f8d14df7ee0>, <PyQt5.QtWidgets.QMenu object at 0x7f8cbb701310>, <PyQt5.QtWidgets.QMenu object at 0x7f8cbb76a790>, <PyQt5.QtWidgets.QMenu object at 0x7f8cbb76ab80>, <napari._qt.dialogs.qt_modal.QtPopup object at 0x7f8d14d9e790>}

napari/utils/_testsupport.py:37: AssertionError
```

and have no idea how to trace these.

**Comment by sofroniewn** [comment]
@Czaki is this still an issue or has this been fixed?

**Comment by Czaki** [comment]
I have another error but in PartSeg. (similar to this with reference to a deleted object). This could be closed.
