### ISSUE TITLE
Image io plugin priority setting

### ISSUE THREAD

**Issue by ViktorvdValk** [napari/napari#2685]
## 🚀 Feature
Image io plugin priority setting

## Motivation

For the elastix_napari plugin we want to be able to load the images with the itk-napari-io plugin rather then with imageio that's installed as well. This would enable the preservation of the world coordinates of the images, these are important for image registration with the elastix plugin.

## Pitch

Set the plugin/packages (priority) with what napari loads images.

## Alternatives

Disable python packages installed for image loading, but only consider napari plugins.

**Comment by tlambert03** [comment]
Hey @ViktorvdValk! It's possible that what you're looking for is already possible, with the plugin sorter (available both in the preferences window, and in the plugin installer window):

https://user-images.githubusercontent.com/1609449/117665722-24197100-b171-11eb-9ac9-22130848effe.mov

you can do that programmatically with:

```python
plugin_manager.hook.napari_get_reader.bring_to_front(['napari-itk-io'])
```

if you want to verify which plugin is getting used, you can look at `layer.source` (and more could/should be done to make that easily accessible)

<img width="961" alt="Untitled 2" src="https://user-images.githubusercontent.com/1609449/117666333-c0437800-b171-11eb-91cd-fff0c093fb2c.png">

but if you've sorted as desired and you're still running into issues, let us know

**Comment by tlambert03** [comment]
I also think that we need something a bit more direct than the plugin sorter, and opened a feature request at #2686

**Comment by ViktorvdValk** [comment]
Thanks @tlambert03, this works
