### ISSUE TITLE
Cross platform napari 1-click installer

### ISSUE THREAD

**Issue by goanpeca** [napari/napari#2692]
## 🚀 Feature

Add a 1-click installer that works on all supported platforms.

## Motivation

Provide access to users that are not python but still want to use napari :) 

## Pitch

The project https://github.com/conda/constructor could be integrated to do this. Because of the way conda works, it would make sense to use this tool, and provide on top of it:

- Integrate installer with mamba for fast solves. 
- Provide conda to be able to leverage dependencies that fall out of the scope of pypi and python packaging ecosystem
- Create a cross platform way to manage updates of napari (background download), and creation of isolated environments to be able to roll back in case of problems

This will require direct changes to constructor or the creation of a package that leverages it and enhances it with some of the bullet points described before.

## Alternatives

Briefcase, the current alternative does not seem to play well with conda.

## Additional context

This topic has been discussed in https://github.com/napari/napari/issues/1074#issuecomment-829378353

**Comment by jaimergp** [comment]
I think this issue is mostly taken care of? We are only missing the update-in-place features, but that's in the works so maybe we can rename this or either close plus open a specific one for the updates? @goanpeca

**Comment by jni** [comment]
I agree. Thank you @jaimergp @goanpeca for all your work on this! I know I was skeptical at various points about the conda-only bundle but some recent experiences with pip, together with your efforts, have made me a hardcore convert! :smiley:

**Comment by goanpeca** [comment]
Happy to hear this @jni  😄
