### ISSUE TITLE
Thread worker segfaults

### ISSUE THREAD

**Issue by goanpeca** [napari/napari#2694]
See: https://github.com/napari/napari/issues/2681#issuecomment-836439812

>This also happens when warnings occur in threads not managed by thread_worker e.g. dask threads, as @jni and @DragaDoncila  discovered today.

---

From https://github.com/napari/napari/pull/2688#issuecomment-837377129

For error, I got the only text in the terminal. No dialog appears.

```
/home/czaki/.pyenv/versions/napari/bin/python /home/czaki/Projekty/napari/examples/napari_error_catch.py
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/czaki/.pyenv/versions/3.8.3/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/czaki/.pyenv/versions/3.8.3/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/czaki/Projekty/napari/examples/napari_error_catch.py", line 23, in make_error
    raise ValueError("Error in another thread")
ValueError: Error in another thread
For warnings I got these text

/home/czaki/Projekty/napari/examples/napari_error_catch.py:15: UserWarning: Warning in another thread!
WARNING: QObject::setParent: Cannot set parent, new parent is in a different thread
WARNING: QObject::startTimer: Timers can only be used with threads started with QThread
WARNING: QObject::killTimer: Timers cannot be stopped from another thread
And these black dialog:
```

From the theoretical point of view, I also do not see moments when errors and warnings are moved to the main thread. If I'm wrong, then please point me where this information is moved to the main thread. Signals are moving information to the tread where objects live. Please remember than different systems could work with a different implementation of threads. I Work on ubuntu 20.10.

Looking direct it cannot work because this PR Fix only WorkerBase and does not touch QThread and threading.Thread, but napari still install hooks globally using NotificationManager. So it needs to be solved in the notification manager (best, because it will support any connected event) or inside

`NapariQtNotification.show_notification`
`napari/napari/_qt/dialogs/qt_notification.py`

```python

import time
import warnings
import threading

import napari
from napari._qt.widgets.qt_viewer_buttons import QtViewerPushButton


def call_warning(*_):
    thr = threading.Thread(target=make_warning)
    thr.start()

def make_warning():
    time.sleep(0.05)
    warnings.warn('Warning in another thread')

def call_error(*_):
    thr = threading.Thread(target=make_error)
    thr.start()

def make_error():
    time.sleep(0.05)
    raise ValueError("Error in another thread")


viewer = napari.Viewer()
layer_buttons = viewer.window.qt_viewer.layerButtons
err_btn = QtViewerPushButton(None, 'warning', 'new Error', call_error)
warn_btn = QtViewerPushButton(None, 'warning', 'new Warn', call_warning)
layer_buttons.layout().insertWidget(3, warn_btn)
layer_buttons.layout().insertWidget(3, err_btn)


napari.run()
```

**Comment by goanpeca** [comment]
Thanks for the example @Czaki, will let you know what I find :)

**Comment by DragaDoncila** [comment]
@goanpeca thanks for looking into this. Here's a minimal example to show my use-case, using dask. 

```python
import napari
import dask.array as da
from qtpy.QtWidgets import QPushButton, QVBoxLayout, QWidget

v = napari.Viewer()

my_im = da.random.random(size=(50, 50))
v.add_image(my_im)

def my_function():
    result = da.divide(my_im, da.zeros(50, 50))
    v.add_image(result)

button_layout = QVBoxLayout()

da_btn = QPushButton("Run Dask with Warnings")
da_btn.clicked.connect(my_function)
button_layout.addWidget(da_btn)
base_widget = QWidget()
base_widget.setLayout(button_layout)

v.window.add_dock_widget(base_widget)

napari.run()
```

This exhibits the same behaviour as highlighted by @Czaki with his example, since it's all just variations on using threads not explicitly managed by our `thread_worker`.

**Comment by goanpeca** [comment]
Thanks @DragaDoncila :) this definitely helps a lot!
