### ISSUE TITLE
Installation instructions not working on Windows

### ISSUE THREAD

**Issue by haesleinhuepf** [napari/napari#2699]
## 📚 Documentation
Hi all,

I just realized that the installation instructions on the napari.org starting page are like this:
```
pip install 'napari[all]'
```
This doesn't work on Windows.
![image](https://user-images.githubusercontent.com/12660498/117844766-3e8e4000-b280-11eb-8d9a-3a4b5bb4c9bc.png)

On Windows, you need to call
```
pip install napari[all]
```

Does the second version maybe also work on Mac and Linux?

**Comment by goanpeca** [comment]
@haesleinhuepf thank for the report.

On Mac, since the new terminal uses zsh (or on linux using zsh) by default it will not work.

Question: does using double quotes work on windows?

`pip install "napari[all]"`

?

**Comment by haesleinhuepf** [comment]
> pip install "napari[all]"

This works on Windows! :-)

**Comment by goanpeca** [comment]
Will update the docs to use `""` then :) 

Thanks˜

**Comment by haesleinhuepf** [comment]
Thanks for the quick response! :-)

**Comment by goanpeca** [comment]
Thank you for the help :)
