### ISSUE TITLE
Add documentation note for installation/setup workaround on macOS Big Sur

### ISSUE THREAD

**Issue by andy-sweet** [napari/napari#2704]
## 📚 Documentation

I recently set up a developer/contributor environment for napari on an Intel Macbook Pro with Big Sur. I ran into the VisPy/OpenGL dependency issue that has been described in a few issues (e.g. #1393, #2485) and in a few forum posts (e.g. [image.sc](https://forum.image.sc/t/napari-issues-on-bigsur/52630/9), [zulip](https://napari.zulipchat.com/#narrow/stream/212875-general/topic/napari.20on.20MacOS.20.20Big.20Sur)).

I imagine this problem is relatively widespread and the workaround seems fairly stable at this point, so I thought it might be a good idea to mention it in at least one place in the setup/installation docs rather than require users to find it or ask for help elsewhere.

Another related thought is that it might make sense for developers/contributors to standardize their Python environment a bit more. In this case, using the conda-forge channel for Python when creating the conda environment fixes the issue, and that might be a good standard channel to use going forward. I don't think we should require all napari users to use conda to manage their Python environment (though it's fine to recommend it), but it seems more reasonable to require contributors to do so.

**Comment by sofroniewn** [comment]
> I thought it might be a good idea to mention it in at least one place in the setup/installation docs rather than require users to find it or ask for help elsewhere.

Agreed @andy-sweet - I'd probably say https://github.com/napari/napari.github.io/blob/master/tutorials/fundamentals/installation.md#installation is the best place for this, it will appear on our website here. https://napari.org/tutorials/fundamentals/installation.html#installation

If you wanted to write something up and make a PR on that other repo that would be great!!

**Comment by goanpeca** [comment]
Also here https://napari.org/docs/dev/developers/contributing.html maybe?

**Comment by sofroniewn** [comment]
Maybe in contributing guide we just add link to installation tutorial - "... if case you have problems, you might want to read our installation tutorial ..." but just keep the 3.9 details in one place?

**Comment by goanpeca** [comment]
The thing is that a dev environment is different from a user environment

For example one could do (I do this)

```bash
conda install python -c conda-forge
pip install -e ".[all]"
pip install -e ".[test]"
pip install pre-commit
```

A user would just do

```bash
conda install napari -c conda-forge
napari
```

**Comment by psobolewskiPhD** [comment]
Big Sur isn't really relevant anymore and we do already recommend using conda and conda-forge to make envs.
