### ISSUE TITLE
Move NAPARI_OCTREE and NAPARI_ASYNC to settings

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#2712]
## 🚀 Feature
We should move the current NAPARI_OCTREE and NAPARI_ASYNC env vars to our settings. Adjusting these may require restarts.

They will probably go in an experimental/ developer section. We should also merge in the custom config stuff that was done for async into our settings

**Comment by goanpeca** [comment]
It seems we will also remove config.py logic @sofroniewn   https://github.com/napari/napari/blob/102a7e8f845893c874d2b86f9371d41130100b89/napari/utils/config.py ?

**Comment by goanpeca** [comment]
>1) Set NAPARI_OCTREE=1 to enabled octree rendering with defaults.2) Set NAPARI_OCTREE=/tmp/config.json use a config file.

@sofroniewn do we want to support this behavior or move everything to the settings?

**Comment by sofroniewn** [comment]
> It seems we will also remove config.py logic @sofroniewn https://github.com/napari/napari/blob/102a7e8f845893c874d2b86f9371d41130100b89/napari/utils/config.py ?
>
> @sofroniewn do we want to support this behavior or move everything to the settings?

In the long run it would definitely be nice to remove the custom config. I don't think we really have a good sense of which of all the settings are essential though. I'd probably try and preserve as much of the existing functionality as we can, but I don't want us to get stuck in some deep rabbit hole for some edge case or special property that isn't as important.

It would also be nice to keep all this stuff inside an `experimental` tab inside the settings so that it was accessible, but clear that it might change before it is finalized.

If in the first PR though we could try leaving the custom config but just add two checkboxes for `NAPARI_OCTREE` and `NAPARI_ASYNC`. If we get that working then maybe in follow-up PRs we remove the custom config?

**Comment by goanpeca** [comment]
>If in the first PR though we could try leaving the custom config but just add two checkboxes for NAPARI_OCTREE and NAPARI_ASYNC. If we get that working then maybe in follow-up PRs we remove the custom config?

Sounds good 👍🏼
