### ISSUE TITLE
Line numbers are vertically misaligned with code

### ISSUE THREAD

**Issue by andy-sweet** [napari/napari#2727]
## 📚 Documentation

In the [threading guide](https://github.com/napari/napari/blob/master/docs/guides/threading.md), we specify `linenos: true` in the code-block directive.

On my MacBook Pro (model version 16,2; macOS 11.3.1) on Chrome (Version 90.0.4430.212 (Official Build) (x86_64)), the line numbers of lines in the code block are vertically misaligned, which makes the later line references difficult to follow, also creates some vertical white space in the line number column, and just generally looks bad.

![Screen Shot 2021-05-17 at 9 34 15 AM](https://user-images.githubusercontent.com/2608297/118527834-85ec5480-b6f6-11eb-915b-7d93c7ef43f4.png)

It looks like the code font size is larger than the line number font size and this only happens for certain window sizes (i.e. the code font size grows as I make the window bigger, but the line number font size stays the same).

**Comment by tlambert03** [comment]
Thanks @andy-sweet 
We can just remove that if it's not consistent.

I agree, it's kinda worse than not having it

**Comment by andy-sweet** [comment]
@tlambert03 In that case, I guess we should also remove the line number references in the text too, right?

Note that some of the line number references in the screenshot are actually out of sync (possibly due to this bug) and need fixing, so removing them also removes some current and future maintenance burden.

**Comment by tlambert03** [comment]
yep! fine with me.
