### ISSUE TITLE
Napari crashes at launch following update 0.4.5 -> 0.4.6 and onward on specific system only

### ISSUE THREAD

**Issue by Remote-Radical** [napari/napari#2731]
## 🐛 Bug

With everything else being constant, updating napari from version 0.4.5 to 0.4.6 results in the GUI hanging up and crashing python. White, unresponsive window appears which needs to be terminated. Reproducing the conda environment on a different computer results in napari functioning correctly.

## To Reproduce

- I have set up minimal examples for each installation, which included complete reinstallation of anaconda and starting from scratch. I have followed these steps exactly to set up the environment:
conda create -y -n napari-env python=3.8
conda activate napari-env
pip install "napari[all]"
- This installed napari version 0.4.7 (not the 0.4.8rc). 
- When launching napari window through 'napari' command in console- white, unresponsive window appears which needs to be terminated.
- Downgrading the napari with pip to version 0.4.5 allows it to work
- Reproducing the conda environment on a different machine allows versions > 0.4.5 to work as well.

## Environments

Below are the info logs from three cases

Case 1: Napari crashes on launch
napari: 0.4.7
Platform: Windows-10-10.0.19041-SP0
Python: 3.8.10 | packaged by conda-forge | (default, May 11 2021, 06:25:23) [MSC v.1916 64 bit (AMD64)]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.20.3
SciPy: 1.6.3
Dask: 2021.05.0
VisPy: 0.6.6
OpenGL:
  -GL version:  4.6.0 NVIDIA 462.31
  -MAX_TEXTURE_SIZE: 32768
Screens:
  -screen 1: resolution 2560x1440, scale 1.0
  -screen 2: resolution 1440x2560, scale 1.0
Plugins:
  -console: 0.0.3
  -svg: 0.1.5

Case 2: Downgraded napari launches correctly
napari: 0.4.5
Platform: Windows-10-10.0.19041-SP0
Python: 3.8.10 | packaged by conda-forge | (default, May 11 2021, 06:25:23) [MSC v.1916 64 bit (AMD64)]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.20.3
SciPy: 1.6.3
Dask: 2021.05.0
VisPy: 0.6.6
OpenGL:
  -GL version:  4.6.0 NVIDIA 462.31
  -MAX_TEXTURE_SIZE: 32768
Screens:
  -screen 1: resolution 2560x1440, scale 1.0
  -screen 2: resolution 1440x2560, scale 1.0
Plugins:
  -console: 0.0.3
  -svg: 0.1.5

Case 3: Napari launches correctly when environment is reproduced on a laptop

napari: 0.4.7
Platform: Windows-10-10.0.18363-SP0
Python: 3.8.10 | packaged by conda-forge | (default, May 11 2021, 06:25:23) [MSC v.1916 64 bit (AMD64)]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.20.3
SciPy: 1.6.3
Dask: 2021.05.0
VisPy: 0.6.6
OpenGL:
 -GL version:
 4.6.0 - Build 26.20.100.6888
 -MAX_TEXTURE_SIZE: 16384
Screens:
 -screen 1: resolution 1920x1080, scale 1.0
Plugins:
 -console: 0.0.3
 -svg: 0.1.5

## Additional context

I have investigated the effect of disabling one of the displays on the PC, where napari >0.4.5 crashes. Even after disabling secondary display, the window tries to open on the second screen- resulting in off-screen window. This leads me to suspect that the persistent napari settings which were introduced in 0.4.6 may have something to do with the issue.

**Comment by Remote-Radical** [comment]
Update: In the process of experimenting with enabling/disabling the second screen, the napari GUI application which was a white, unresponsive screen suddenly recovered and became functional. It appears that launching the application on a second screen has been the cause of napari creating a non-responsive window. More experimentation is needed to determine the nature of the bug. This thread can now be closed.

**Comment by tlambert03** [comment]
thanks for investigating!
