### ISSUE TITLE
Some napari code references are broken

### ISSUE THREAD

**Issue by andy-sweet** [napari/napari#2737]
## 📚 Documentation

Some references to napari code are badly formatted. For example:

![Screen Shot 2021-05-18 at 2 09 35 PM](https://user-images.githubusercontent.com/2608297/118729668-2a4fc300-b7eb-11eb-9496-8fe9d02ad473.png)

In this case, I think that's because of a new line breaking up the reference. My guess is that an auto-formatter sees the space between `thread_worker` and `<` and decides that it's OK to break these up even though they are surrounded by backticks. In other parts of the docs, the space is replaced by a `~` which seems to prevent this, and in other parts the space is simply omitted.

In general, it's probably also worth making the code references a bit more consistent. Most of the time, I think we can just use plain backticks to just format the font, as generating a link to the API for every code reference probably isn't necessary. But sometimes linking to the API is useful (e.g. when first introducing a function) though we want to make sure the link is actually generated and that it will be formatted correctly.

**Comment by goanpeca** [comment]
@Carreau do you have a suggestion on what should we use?

Also are any of the tools you are working on helpful in formatting these cases :) ?

**Comment by sofroniewn** [comment]
> Also are any of the tools you are working on helpful in formatting these cases :) ?

@melissawm curious if you know of any good tools here as well?

**Comment by grlee77** [comment]
Several of these in the developer guide were fixed recently in #3296.

> In this case, I think that's because of a new line breaking up the reference. My guess is that an auto-formatter sees the space between thread_worker and < and decides that it's OK to break these up even though they are surrounded by backticks. In other parts of the docs, the space is replaced by a ~ which seems to prevent this, and in other parts the space is simply omitted.

Hmmmm, I ended up just putting things back on a single line, but think I typically left the space there. Hopefully no future automatic formatting will go back and break these again!

**Comment by andy-sweet** [comment]
Closing this because the issues I saw were fixed in #3296.
