### ISSUE TITLE
Napari notifications don't show up when napari is launched from jupyterlab

### ISSUE THREAD

**Issue by jluethi** [napari/napari#2749]
## 🐛 Bug

When I launch napari from the command line, I see error messages and warnings pop up nicely in the napari interface as notifications. When I do the same with a napari viewer launched from a jupyterlab notebook, I only get error messages in the console that's running the jupyter notebook and warnings in the napari console (when opened) or below the jupyterlab cell that launched napari (when the napari console wasn't opened).

## To Reproduce

1. Open napari from within jupyterlab
```
import napari
viewer = napari.Viewer()
```
2. Add images to napari and do something that would trigger a warning or an error
3. Check where the error message/warning shows up

E.g. I'm trying to use this in my [feature visualization plugin using the initialize_classifier dockwidget](https://github.com/jluethi/napari-feature-visualization). That dockwidget is sending warnings for some user behaviors (e.g. overwriting an existing classifier), but the user never gets to see them within napari.

## Expected behavior

I would like to see error messages or warnings as notifications. It works when I launch napari directly from my console, but not when I launch napari via jupyterlabs.

## Environment

 - Please copy and paste the information at napari info option in help menubar here:
napari: 0.4.8rc3
Platform: macOS-10.16-x86_64-i386-64bit
System: MacOS 11.3.1
Python: 3.9.0 (default, Nov 15 2020, 06:25:35) [Clang 10.0.0 ]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.20.2
SciPy: 1.6.3
Dask: 2021.04.1
VisPy: 0.6.6

OpenGL:
- GL version: 2.1 INTEL-16.2.16
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 2560x1440, scale 1.0
- screen 2: resolution 1280x800, scale 2.0

Plugins:
- console: 0.0.3
- napari-feature-visualization: 0.1.dev48+g8f1f174.d20210519
- scikit-image: 0.4.8rc3
- svg: 0.1.5

 - Any other relevant information:
I also tested this in the napari 0.4.8 release version, same issue.

**Comment by tlambert03** [comment]
Hi @jluethi,

that was by design, and is controlled by these lines here:
https://github.com/napari/napari/blob/3c7cb3af367edac361baf4a7e25d929a02f6e99f/napari/_qt/qt_event_loop.py#L156-L162 

... and the fact that we only "install" our notification_manager if we're not running in IPython, here:
https://github.com/napari/napari/blob/3c7cb3af367edac361baf4a7e25d929a02f6e99f/napari/_qt/qt_event_loop.py#L375


it's been hard to decide where to "walk the line" between being an independent application, and a viewer that plays well with the existing python ecosystem.  Here, we reasoned that if someone is using napari interactively in IPython, then they likely want the messages where they're typing.  IPython has its own excepthook and warnings display, so we detect when the use is "in IPython world" and try not to fight with IPython.

So, it's not a "bug" per se... but perhaps we can expose a setting that would install the notification manager even in IPython (this might be trickier than it sounds with the way that IPython reclaims hooks on every cell, @Carreau?)

**Comment by jluethi** [comment]
Hmm, ok, I understand the thinking.

Would it be possible for me as the plugin developer to send something directly to napari notification manager instead? 
I can understand wanting warnings generally in the IPython console. But sometimes the user may not notice the messages in the console/in the jupyterlab notebook. If I can directly send some warnings to the notification manager, that would allow me to ensure certain messages are always shown in the napari interface.

**Comment by tlambert03** [comment]
>  But sometimes the user may not notice the messages in the console/in the jupyterlab notebook.

yeah, I get the desired behavior.  makes sense.

> Would it be possible for me as the plugin developer to send something directly to napari notification manager instead?

yeah, try `napari.utils.notifications.show_info`:

```python
from napari import Viewer
from napari.utils.notifications import show_info

v = Viewer()
show_info("i'm a message")
```

... a relatively simple feature addition would be to add a couple helper functions there to show error and warnings as well based on a string message)

**Comment by jluethi** [comment]
Ah, that's neat. Thanks a lot @tlambert03 ! That works well for me to inform the user interactively in the plugin!

I wrote a small wrapper for my plugin:
```
from napari.utils.notifications import show_info
from napari._qt.qt_event_loop import _ipython_has_eventloop

def napari_warn(message):
    warnings.warn(message)
    if _ipython_has_eventloop():
        show_info(message)
```

When I use it that way, I get the actual warning but also a message in the interface if it's run in IPython. The only fun part is that whenever I use `show_info(message)`, the jupyterlab gets the word `Notification` (without details of the notification) displayed below the jupyter notebook cell as well. Any chance that can be suppressed? (that would be pure cosmetics though, the functionality works great!)

**Comment by tlambert03** [comment]
maybe use this instead:
```python
from napari._qt.dialogs.qt_notification import NapariQtNotification
from napari._qt.qt_event_loop import _ipython_has_eventloop

def napari_warn(message):
    if _ipython_has_eventloop():
        NapariQtNotification(message, 'WARNING').show()
    warnings.warn(message)
```

**Comment by jluethi** [comment]
Neat, that works beautifully. Thanks a lot for the explanation and the help! Issue solved then!
