### ISSUE TITLE
Also map colormap display names to colormaps

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#2766]
## 🐛 Bug

I just tried setting `layer.colormap = 'twilight shifted'` and got and the following error

```
  File "/Users/nsofroniew/GitHub/napari/napari/components/viewer_model.py", line 624, in add_image
    colormap = ensure_colormap(colormap)
  File "/Users/nsofroniew/GitHub/napari/napari/utils/colormaps/colormap_utils.py", line 492, in ensure_colormap
    name
  File "/Users/nsofroniew/GitHub/napari/napari/utils/colormaps/colormap_utils.py", line 397, in vispy_or_mpl_colormap
    name=name,
KeyError: 'Colormap "twilight shifted" not found in either vispy or matplotlib.'```

The correct name is `twilight_shifted`, but both should work

**Comment by goanpeca** [comment]
>The correct name is `twilight_shifted`, but both should work

Does this mean that if I was using a translation, the translation should also work @sofroniewn ?

```python
layer.colormap = 'crepúsculo desplazado'  # This translation is both a serious and a joke one!
```

**Comment by sofroniewn** [comment]
> Does this mean that if I was using a translation, the translation should also work @sofroniewn ?

It's tricky. I remember @jni concern about this, and not wanting code that has translations in it in case they stop working for people that don't have the language pack, it can become a reproducibility nightmare.

Maybe the better solution for now is just to improve the error message, for example

```
KeyError: 'Colormap "twilight shifted" not found in either vispy or matplotlib, but you might want to use 
"twilight_shifted".'

# and

KeyError: 'Colormap "crepúsculo desplazado" not found in either vispy or matplotlib, but you might want to use 
"twilight_shifted".'
```

would already have helped me a lot. Even, just listing all the recognized colormaps would have helped too

```
KeyError: 'Colormap "twilight shifted" not found in either vispy or matplotlib, recognized colormaps are .... .'
```

These approaches might eliminate the user frustration, but be safer

**Comment by tlambert03** [comment]
> KeyError: 'Colormap "twilight shifted" not found in either vispy or matplotlib, but you might want to use 
"twilight_shifted".'

I like that.  Using display names as valid keys feels like a slippery slope
