### ISSUE TITLE
Can't load files through samba smb:// 

### ISSUE THREAD

**Issue by ederancz** [napari/napari#2767]
## 🐛 Bug

"No plugin found capable of reading" error when trying to load tiff images through smb protocol.

## To Reproduce
1. Drop tiff image from files onto napari window. 
Traceback provided at the end.

## Expected behavior
Loading as with other sources. 

## Environment
napari: 0.4.8
Platform: Linux-4.4.0-210-generic-x86_64-with-glibc2.10
System: Ubuntu 16.04.5 LTS
Python: 3.8.8 (default, Apr 13 2021, 19:58:26) [GCC 7.3.0]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.19.5
SciPy: 1.6.3
Dask: 2021.05.0
VisPy: 0.6.6

OpenGL:
- GL version: 4.6.0 NVIDIA 465.19.01
- MAX_TEXTURE_SIZE: 32768

Screens:
- screen 1: resolution 3440x1440, scale 1.0

Plugins:
- brainglobe-io: 0.0.2
- brainreg-standard: 0.0.2
- cellfinder: 0.0.10
- console: 0.0.3
- ndtiffs: 0.1.1
- scikit-image: 0.4.8
- svg: 0.1.5

## Additional context
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~/miniconda3/envs/cellfinder-napari/lib/python3.8/site-packages/napari/_qt/qt_viewer.py in dropEvent(self=, event=)
    900                 filenames.append(url.toString())
    901 
--> 902         self.viewer.open(filenames, stack=bool(shift_down))
        self.viewer.open = ], _persisted_mouse_event={}, _mouse_drag_gen={}, _mouse_wheel_gen={}, keymap={'Control-Shift-C': >})>
        filenames = ['smb://data.thecrick.org/lab-rancze/working/tranvaa/brainsaw/results/ERAE28_2e/ERAE28_2e_detected14_retrained5/registration/downsampled.tiff']
        global stack = undefined
        global bool = undefined
        shift_down = 
    903 
    904     def closeEvent(self, event):

~/miniconda3/envs/cellfinder-napari/lib/python3.8/site-packages/napari/components/viewer_model.py in open(self=Viewer(axes=Axes(visible=False, labels=True, col...t.qt_viewer.QtViewer object at 0x7f88bcccc040>>}), path=['smb://data.thecrick.org/lab-rancze/working/tranv...tected14_retrained5/registration/downsampled.tiff'], stack=False, plugin=None, layer_type=None, **kwargs={})
    834         for _path in paths:
    835             added.extend(
--> 836                 self._add_layers_with_plugins(
        self._add_layers_with_plugins = ], _persisted_mouse_event={}, _mouse_drag_gen={}, _mouse_wheel_gen={}, keymap={'Control-Shift-C': >})>
        _path = 'smb://data.thecrick.org/lab-rancze/working/tranvaa/brainsaw/results/ERAE28_2e/ERAE28_2e_detected14_retrained5/registration/downsampled.tiff'
        kwargs = {}
        plugin = None
        layer_type = None
    837                     _path, kwargs, plugin=plugin, layer_type=layer_type
    838                 )

~/miniconda3/envs/cellfinder-napari/lib/python3.8/site-packages/napari/components/viewer_model.py in _add_layers_with_plugins(self=Viewer(axes=Axes(visible=False, labels=True, col...t.qt_viewer.QtViewer object at 0x7f88bcccc040>>}), path_or_paths='smb://data.thecrick.org/lab-rancze/working/tranv...tected14_retrained5/registration/downsampled.tiff', kwargs={}, plugin=None, layer_type=None)
    879         from ..plugins.io import read_data_with_plugins
    880 
--> 881         layer_data, hookimpl = read_data_with_plugins(
        layer_data = undefined
        hookimpl = undefined
        read_data_with_plugins = 
        path_or_paths = 'smb://data.thecrick.org/lab-rancze/working/tranvaa/brainsaw/results/ERAE28_2e/ERAE28_2e_detected14_retrained5/registration/downsampled.tiff'
        plugin = None
    882             path_or_paths, plugin=plugin
    883         )

~/miniconda3/envs/cellfinder-napari/lib/python3.8/site-packages/napari/plugins/io.py in read_data_with_plugins(path='smb://data.thecrick.org/lab-rancze/working/tranv...tected14_retrained5/registration/downsampled.tiff', plugin=None)
    129 
    130         # TODO: change to a warning notification in a later PR
--> 131         raise ValueError(message)
        global ValueError = undefined
        message = "No plugin found capable of reading 'smb://data.thecrick.org/lab-rancze/working/tranvaa/brainsaw/results/ERAE28_2e/ERAE28_2e_detected14_retrained5/registration/downsampled.tiff'."
    132 
    133     if errors:

ValueError: No plugin found capable of reading 'smb://data.thecrick.org/lab-rancze/working/tranvaa/brainsaw/results/ERAE28_2e/ERAE28_2e_detected14_retrained5/registration/downsampled.tiff'.

**Comment by sofroniewn** [comment]
Hi @ederancz I'm afraid I'm not familiar with samba smb:// can you provide some more info on how you normally read these files into Python. Can they be read with [imageio](https://imageio.readthedocs.io/en/stable/)? Our builtin image reader uses that under the hood. You might need to create a custom reader plugin for this file type, which can be done using instructions here https://napari.org/plugins/stable/index.html

**Comment by tlambert03** [comment]
This is a bit more of a feature request than a bug.  SMB is one of many internet protocols that we don't natively support... I also use SMB at work, so certainly would like to have this as well, but we should have a broader talk about what this might look like.  For instance, it would be kind of a shame to require each individual plugin to have to support smb, ftp, (... insert your favorite file transfer protocol here), so some sort of intermediate layer would be nice.  But that's also a non-trivial undertaking with a number of platform specific implications and decisions.

In the meantime, does it change anything for you in napari if you mount your SMB share locally?

**Comment by ederancz** [comment]
Thanks, that's a really good idea, will try it later today. Perhaps that's what happens under the hood in macOS, where I have no issue loading files from the same server.

**Comment by ederancz** [comment]
> Thanks, that's a really good idea, will try it later today. Perhaps that's what happens under the hood in macOS, where I have no issue loading files from the same server.

Yep, mounting it locally solves it, thank you!

**Comment by tlambert03** [comment]
Good to know!  Thanks for testing that out
