### ISSUE TITLE
Preferences that require a napari restart

### ISSUE THREAD

**Issue by ppwadhwa** [napari/napari#2790]
The way things are currently implemented, the following will require a restart of napari if they are changed in the Preferences dialog.  Please feel free to add others...

1. octree
2. async

**Comment by sofroniewn** [comment]
@ppwadhwa are these the only two? i'm actually thinking now that if these are the only two then we should try and make them no longer requiring a restart. In general it's probably much better to not require a restart. Let's discuss more before you start working on it. I know @tlambert03 agrees here too. cc @goanpeca

**Comment by ppwadhwa** [comment]
I was thinking it was just these 2.  However, thinking about it, changing the language requires a restart, right?  I'm not sure how to get around that one.  

Anyway, we could still work on making the settings for async and octree not require a restart.

**Comment by goanpeca** [comment]
> However, thinking about it, changing the language requires a restart, right? I'm not sure how to get around that one.

We could allow for this without a restar but would be tricky for some widgets, we would need some "refresh/update" method that updated all the strings if a language changes in labels and buttons.

**Comment by andy-sweet** [comment]
Note that #5816 would remove the two preferences that require a restart, with the new async approach/setting not requiring a restart itself, so I think (if merged) it would close this issue.
