### ISSUE TITLE
pre color test fail from numpy 1.21

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#2791]
## 🐛 Bug

Our pre-tests are currently failing - it's a fairly innocuous fail, so no need to rush a release, but we should fix them. The test is passing an intentionally invalid  `color = ('a', 1, 1, 1)` which is now raising a warning that didn't used to happen. I'm not quite sure how we want to fix, I can see many different ways - but given that no-one should really pass a color with a string in it as long as we do something reasonable I don't mind

```python-traceback
  _________________________ test_invalid_colors[color6] __________________________
  
  color = ('a', 1, 1, 1)
  
      @pytest.mark.parametrize("color", invalid_colors)
      def test_invalid_colors(color):
          with pytest.raises((ValueError, AttributeError, KeyError)):
  >           transform_color(color)
  
  napari/utils/colormaps/_tests/test_color_to_array.py:50: 
  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
  napari/utils/colormaps/standardize_color.py:65: in transform_color
      return _color_switch[colortype](colors)
  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
  
  colors = ('a', 1, 1, 1)
```
...
```python-traceback
  >           color_array = np.atleast_2d(np.asarray(colors))
  E           FutureWarning: Promotion of numbers and bools to strings is deprecated. In the future, code such as `np.concatenate((['string'], [0]))` will raise an error, while `np.asarray(['string', 0])` will return an array with `dtype=object`.  To avoid the warning while retaining a string result use `dtype='U'` (or 'S').  To get an array of Python objects use `dtype=object`. (Warning added in NumPy 1.21)
```

**Comment by andy-sweet** [comment]
I decided to fix this by explicitly providing dtype if any of the elements are strings, as effectively suggested by the [associated numpy release note](https://numpy.org/devdocs/release/1.21.0-notes.html#promotion-of-strings-with-numbers-and-bools-is-deprecated).

Some other ideas I had with reasons against them.

1. Filter the warning in the test using `pytest.mark.filterwarnings`. The user may still see the FutureWarning, which may distract from the custom warning/error that we want to show.
2. Filter the warning in the implementation using `with warnings.catch_warnings()` and `warning.simplefilter(...)`. Unless we match the message exactly or with a regex, we may also suppress other potentially important FutureWarnings in the future.
3. Raise an exception if the list-like is not homogeneous. This may prevent desired upcasting if mixing ints/floats is allowed. Even if it doesn't we'd need a new translated string for the message, and the existing one for this test case seems fine ("Invalid color found: a at index 0.").

Feel free to comment if you think something else is preferred.

**Comment by sofroniewn** [comment]
> I decided to fix this by explicitly providing dtype if any of the elements are strings

That sounds reasonable, but I'm trying to remember here what normal usage looks like - I know people can pass strings for colors, like `'k'` for black etc, but an input like  `colors = ('a', 1, 1, 1)` doesn't make any sense. It might come back to me when I review PR, but this sounds like a fine thing to try

**Comment by andy-sweet** [comment]
Just to confirm, the current test verifies that an exception is raised with `('a', 1, 1, 1)`. I assumed the test was written to check that we both stop execution for that input and provide a hopefully useful error message to the user. If we really don't ever expect that input, we should probably just remove the test case.

**Comment by sofroniewn** [comment]
> I assumed the test was written to check that we both stop execution for that input and provide a hopefully useful error message to the user.

We have this fairly long list of invalid colors - see https://github.com/napari/napari/blob/102a7e8f845893c874d2b86f9371d41130100b89/napari/utils/colormaps/_tests/colors_data.py#L105-L121 none of which we'd really expect as inputs, but agreed we should raise a more helpful error message for all of those as i could see someone typing one in by mistake. If your PR gets us to that more helpful error message than i think it's probably the right call. I'll take a look now
