### ISSUE TITLE
Ergonomy of key bindings suboptimal

### ISSUE THREAD

**Issue by haesleinhuepf** [napari/napari#2800]
## 🐛 Bug

Hi all,

I just noticed that there are key-bindings when a label-layer is selected. To me the bindings appear sub-optimal and too widely distributed over the whole keyboard:

![image](https://user-images.githubusercontent.com/12660498/120074365-cce62c80-c09c-11eb-99b9-555f28d11229.png)

This distribution might be easy to remind (L for label picker, p for paintbrush...) however, it's not ergonomic. Annotate labels for 10 minutes with this scheme and your fingers hurt. Furthermore, if key bindings are spread over the whole keyboard, key bindings for other tools (see also #2799) cannot be put in one place together (e.g. WASD for [natari](https://github.com/haesleinhuepf/natari/blob/master/napari_cell_counting_arcade.py#L17) gaming) because there is everywhere bindings related to label layers.

## To Reproduce

Start napari 0.4.8 and add a labels layer.

## Expected behavior

As a base for discussion, I'm suggesting a different scheme, The order of the keys on the keyboard is the same as in the graphical user interface. Furthermore for increasing and decreasing the current label, I'm suggesting the `+` and `-` keys on the english/international keyboard:
![image](https://user-images.githubusercontent.com/12660498/120074228-27cb5400-c09c-11eb-8233-c20b13dee155.png)

## Environment

napari: 0.4.8rc1
Platform: Windows-10-10.0.19041-SP0
Python: 3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AMD64)]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.20.2
SciPy: 1.6.3
Dask: 2021.04.1
VisPy: 0.6.6

OpenGL:
- GL version: 4.6.0 - Build 27.20.100.8729
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1080, scale 2.0

Plugins:
- clEsperanto: 0.9.0
- console: 0.0.3
- napari_webcam: 0.1.12
- scikit-image: 0.4.8rc1
- svg: 0.1.5

## Additional context

I have an english/international keyboard.

**Comment by tlambert03** [comment]
now that's what I call a  well-crafted issue! :)

**Comment by haesleinhuepf** [comment]
Just adding the raw key map file in case somebody wants to craft an improved version for discussion 😁 
[keymap.pptx](https://github.com/napari/napari/files/6564875/keymap.pptx)

**Comment by sofroniewn** [comment]
Yeah, wow, nice issue! Agreed we can change. We should soon be in a position to have our keybindings be user configurable thanks to some great work from @Carreau and @ppwadhwa. When that is possible we can also think about changing some of the defaults too

**Comment by ianhi** [comment]
I agree with this big time! I made a similar suggestion (with much worse graphics :upside_down_face: ) here: https://github.com/napari/napari/issues/2189#issuecomment-769559211 but it never made it's way to its own issue

My one comment here is that your proposed scheme is probably best for left handed people, and one with the keys on the left of the keyboard would be better for right handers. Perhaps there could be a togglebale left/right setting that would choose between these?

**Comment by psobolewskiPhD** [comment]
@haesleinhuepf 
the keybinds have changed a lot since this, particularly with https://github.com/napari/napari/pull/3072 but also the press-hold behavior has been changed: https://github.com/napari/napari/pull/4814
And there is also the possibility to make secondary keybindings: https://github.com/napari/napari/pull/5018
Do you think this is still an issue?
