### ISSUE TITLE
Discussion on improved events for `Shapes` and `Points` layers

### ISSUE THREAD

**Issue by DragaDoncila** [napari/napari#2809]
I wanted to raise this issue as a place to discuss how we might provide better access to data changes
for `Shapes` and `Points` layers through some new events. As evidenced by discussions on #720, #2720 and #2260 (potentially among others), users would like to know when there is an internal data change (as opposed to data being explicitly reassigned).

I've made a couple of suggestions for what I think we should do, as well as done a small stocktake of our current events.

# Considered Layers
This proposal considers `Shapes` and `Points` layers due to their similarities
- Data consisting of a list of discrete elements
- Ability to select, move, add and remove these discrete elements to the data
- Ability to change aspects of the display of each discrete element e.g. edge color and face color

# Existing Behaviour
Currently, the following events are being emitted by these layers, in addition to those emitted by base. Note that `Shapes` do not emit any events not also shared by `Points`.

## `Points` Only

| Event         	| Included Value 	| Emitted When                   	|
|---------------	|----------------	|--------------------------------	|
| `size`          	| None           	| Layer `current_size` changes     	|
| `symbol`        	| None           	| Marker symbol is changed       	|
| `n_dimensional` 	| None           	| Layer `n_dimensional` is set      |

## Both `Shapes` and `Points`

| Event              	| Included Value 	| Emitted When                                                                              	    |
|--------------------	|----------------	|------------------------------------------------------------------------------------------------   |
| `mode`               	| mode           	| Layer `mode` e.g. (select, add, interactive) changes                                        	    |
| `edge_width`         	| None           	| `edge_width` changes (shapes, `current_edge_width`)                                               |
| `edge_color`         	| None           	| `edge_color` is set (and shapes, `current_edge_color` is set and `_update_properties` is True)  	|
| `face_color`         	| None           	| `face_color` is set (and shapes, `current_face_color` is set, and `_update_properties` is True) 	|
| `properties`         	| None           	| `properties` is set                                                                         	    |
| `current_edge_color` 	| None           	| `current_edge_color` is set                                                                 	    |
| `current_face_color` 	| None           	| `current_face_color` is set                                                                 	    |
| `current_properties` 	| None           	| `current_properties` is set                                                                 	    |
| `highlight`          	| None           	| Points: highlight setter, on selection, symbol change, Shapes: highlight setter             	    |

As we can see, there are no custom events emitted when the user adds, removes or changes the position of an existing element of the layer (whether this element be a point or a shape). This means users must listen for data changes, and then poll the data for what’s changed in an at best linear complexity operation. 

Additionally, `data` events are only emitted in the data setters of both layers, so there is currently no direct way to detect when a point or a shape has been added, removed, or moved (and certainly no easy way to identify the element(s) in question).

# Proposed Events

I propose we add the following events to `Points` and `Shapes` layers:

**Move** - emitted when a point/shape or selection of points is moved

**Add** - emitted when a shape or point is added to the layer

**Remove** - emitted when a shape or point is removed from the layer 

There are a few options for how we might implement these events.

## 1. Just emit `data`
Simply ensure we emit `layer.events.data` when all of the above actions occur.

**Pros**
- Minimal change to codebase

**Cons**
- Still have to do linear scans to see what's changed

## 2. Overload the Data Event

`layer.events.data`, when emitted, gets an additional keyword argument `type` whose value can be `"set"`,`"move"`, `"add"` or `"remove"`. 
The event is additionally emitted with a keyword argument `index` corresponding to the index/indices of the elements in data
affected for all `types` except `"set"`. For `move`, the coordinates of the move are also emitted through `coord`. 

`layer.events.data` is then emitted in the requisite methods of both `Shapes` and `Points` layers i.e. `add`, `remove_selected`,
`points._move` and `_shapes_mouse_bindings._move`.

**Pros**
- Easy to connect to for developers - can rely on data event being emitted with any changes
- Doesn't clutter list of events

**Cons**
- Users might be catching lots of events they don't need
- Additional `if` statement for each callback to check what type of data event it is
- Event name is not explicit

## 3. New events

Both `Shapes` and `Points` layers get three new events - `data_added`, `data_removed`, `data_moved`.
Each event emits `data` and `index` to allow users to access the changed elements.
`move` also emits `coord`.

We could additionally emit a `data` event alongside each of these events, though this might be
ambiguous.

**Pros**
- Explicit
- Potentially more intuitive for new users?

**Cons**
- Might require connecting to more events to achieve the same purpose
- Might want to also emit just plain `data` event, maybe redundant?

## Elements instead of index?
With the above suggestions we are emitting the full `data`, and an associated `index` to identify
the affected elements. This might be problematic for `remove` events, so we could alternatively
emit the points or shapes affected directly. Alternatively we could only emit the deleted elements
for the `remove` event.

# Questions
- Are there any other events for these two layers we should also consider while we're here?
- Are there other implementation options we should consider?
- Move events will fire a lot with each drag - is this a problem? Is it up to developers to handle this?
- Naming conventions?

I'm curious to hear what people think about the options above, anything I might've missed in discussion,
and what they'd prefer to see moving forward. I'm leaning towards Option 2 personally. @sofroniewn @jni @tlambert03, any thoughts?

**Comment by jni** [comment]
I favour 2, but perhaps we can step via 1, since 2 is backwards compatible with 1. I think that's a really nice advantage of that road. I also think some users might want to know when data changes and not care *how* it changed, so we would always need to emit data in 3 anyway.

> Are there any other events for these two layers we should also consider while we're here?

Yes, property changes, see also #2866 

> Move events will fire a lot with each drag - is this a problem? Is it up to developers to handle this?

We have encountered this problem in a couple of places and I think that should be up to us — we should throttle events globally to 60Hz or maybe even 30Hz.

**Comment by sofroniewn** [comment]
Maybe we start with (1.) then and see what that looks like. 

> Move events will fire a lot with each drag - is this a problem? Is it up to developers to handle this?

Maybe we just emit on drag start/ end? Same for drawining. Otherwise throttle might be needed

**Comment by jni** [comment]
> Maybe we just emit on drag start/ end? Same for drawining. Otherwise throttle might be needed

My Q is whether the actual drawing of the points on canvas relies on events. If it does (and I think it does?), then emitting on start/end is a no-go?

**Comment by DragaDoncila** [comment]
> Maybe we just emit on drag start/ end?

Points `_move` gets called in `select` of `_points_mouse_bindings` so we could emit in this method if we wanted - the yields should give us a good indication of when to do it.

Shapes have a `finish_drawing` method which we could hook into, I think.

> My Q is whether the actual drawing of the points on canvas relies on events.

From what I can see (but maybe I'm misunderstanding what you mean here) the `Points` model doesn't have the same concept of drawing - in fact adding points just adds them to data, and doesn't call `refresh`. So I think you're right that we wouldn't be able to use the same trick as for `Shapes`.

Maybe I'm confused about what "drawing" is though in this context.

**Comment by sofroniewn** [comment]
@jni @DragaDoncila what's still left to do on this issue after #2992? Apologies for not recalling, but i just want to track it here so we still remember in the future

**Comment by DragaDoncila** [comment]
@sofroniewn we've now got equivalence between `Shapes` and `Points` for adding, removing and moving layer contents. However, I still think it's worth implementing additional information into the `data` events to surface what type of change occurred (`add`, `remove` or `move`) and which indices where affected, to save users having to search through the data in an at best linear pass.

I'm not sure if @jni reopened this issue for any other reason though.

**Comment by DragaDoncila** [comment]
Closed by #5967! 🎉
