### ISSUE TITLE
you cannot split an xarray.DataArray image into channels via add_image / channel_axis

### ISSUE THREAD

**Issue by cyrilcros** [napari/napari#2814]
## 🐛 Bug

When you have an image with channel data, it is possible to split the channels into separate image layers via the `channel_axis` argument. This works for Numpy but triggers a dimensionality error for `xarray.DataArray`.
Notably, the bug occurs with `pyimagej` multichannel images.

## To Reproduce

```
   import napari
   import imagej
   ij = imagej.init('sc.fiji:fiji:2.1.1')
   dataset = ij.io().open("Image 27.czi")  # any image would do
   image = ij.py.from_java(dataset) # yields xarray.DataArray z, c, y, x
   viewer = napari.Viewer()
   viewer.add_image(image, channel_axis=1) # buggy line
   viewer.add_image(image.values, channel_axis=1) # DataArray converted to numpy, works
```

Error trace: https://pastebin.com/Kf5A5FAp

## Environment
 - napari 0.4.8 installed via conda

## Additional context

https://forum.image.sc/t/napari-should-i-reorder-the-dimensions-of-an-array-created-via-ij-py-from-java/53436

**Comment by sofroniewn** [comment]
Ok, thanks good to know - we should really get better at testing xarray support!!

**Comment by cyrilcros** [comment]
Fixed by https://github.com/napari/napari/pull/2780
