### ISSUE TITLE
Shapes layer: Double click to finish polygon or path.

### ISSUE THREAD

**Issue by Carreau** [napari/napari#2828]
## 🚀 Feature

I have the impression that many other software that allow to manipulate path let you double click to finish a path/polygon, at least my muscle memory make me double click in napari. At least inkscape have it documented (https://inkscape.org/doc/keys.html#idm3170) 

## Motivation

1) it seem to be what other software are doing consistency and familiarity is good.
2) it allow to not reach the keyboard, and even with the keyboard "esc" feel unnatural.

## Pitch

Have double click add a node at location of double click and finish the current line/polygon

## Alternatives

Use another key press like shift-click to fisnish, or left click.

## Additional context

for Inkscape, polygon and line are the same except you can click on initial point to "close", or use shift-click for last point, I doubt this is of importance.

**Comment by kcpevey** [comment]
This functionality is available for paths and polygons as of napari=0.4.17. 

For paths and polygons, a single click adds a vertex, and a double-click will add a vertex and "finish" the shape. Escape will "finish" the vertex without adding a vertex.
