### ISSUE TITLE
Vectors should have out-of-slice rendering like points.n_dimensional

### ISSUE THREAD

**Issue by brisvag** [napari/napari#2832]
## 🚀 Feature
It would be great if `Vectors` had the same `n_dimensional` attribute as points. I imagine it's more complicated to implement than points. Is it even doable? Was this discussed before?

## Motivation

I use vectors and points to indicate positions and orientations in a 3D volume. I often want to slice through the volume in 2D, and right now I lose orientation information while doing so. Some vectors show up, but it only happens (I think) when they start exactly on the slice.

## Pitch

I would like `Vectors` to have an `n_dimensional` flag that when enabled will act similarly to the `n_dimensional` flag of `Points`. I would expect vectors to be visible as a projection of the vector onto the viewed slice, and only when they intersect the viewed slice.

While `Points` uses size to convey the out-of-plane-ness of a point, `Vectors` is a bit harder. I see a few options:
- do nothing
- use transparency
- use width (though I doubt that's possible with the current vector rendering)

**Comment by jni** [comment]
I think it should be doable. The main thing is to add the setting and change the slicing logic to match the Points layer's, here:

https://github.com/napari/napari/blob/ed6b8ef2e55471b42a3ea47875b7e1ef0f99ba80/napari/layers/points/points.py#L1313-L1329

Some thoughts though:

(1) I think "n-dimensional" is a bit of a misleading name. Maybe we should take this opportunity to rethink it. In all cases the points/vectors are n-dimensional, it's just whether we display out-of-slice elements in the current slice, and how to denote that they are out of slice.
(2) I think the same feature would be useful for shapes. So we might want to unify the slicing behaviour for all these layers, rather than tack something on to Vectors.

Regarding your options, I like transparency the best.

**Comment by brisvag** [comment]
Agree on the name; I was quite confues about it at first, cause the name seems to refer to a property fo the data, rather than visualization. Maybe simply `display_out_of_slice`? :P

I also think transparency would be the most intuitive. So you would simply either project the whole vector or not at all, and set the transparency of the whole vector depending on how out-of-slice the starting point is?

**Comment by alisterburt** [comment]
Awesome job with #2902 @brisvag, so cool to see what this could look like!!

I'm definitely on board with @jni's suggestion of trying to unify this behaviour across points/vectors/shapes. 
It seems like we might need a way to define at the level of the viewer whether the canvas is 2D, '2D+' or 3D. In '2D+' the projection of annotations from outside the current slice would be made visible for supported layers. I'm not sure what the most intuitive way would be to expose this to users.

Can we imagine any case where you may want this behaviour for one layer type but not another (e.g. for a points layer but not a vectors/shapes layer)? I can't but I'm probably not dreaming big enough.

**Comment by jni** [comment]
> Can we imagine any case where you may want this behaviour for one layer type but not another (e.g. for a points layer but not a vectors/shapes layer)? I can't but I'm probably not dreaming big enough.

The lesson you learn from maintaining napari long enough is that if it's possible, someone will want it. 😂 I would never have thought your little local-orthogonal-projection-on-a-plane thingy would be useful (vs just cropping the volume) but here we are. 😂

**Comment by brisvag** [comment]
I agree that unifying would be nice, but there are some complications:
- how to determine whether something should be rendered differs from one to the other
- conveying out-of-planeness would also probably differ

This is easier if we pre-determine (or expose) a slice "thickness", and base everything on that. But as I said in #2902, we are then encroaching on 2.5D slicing territory...

**Comment by brisvag** [comment]
This was implemented in #2902.
