### ISSUE TITLE
Regression on plugin hookspec sorter styling in preferences 

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#2839]
## 🐛 Bug

There seems to be a regression with the styling of the hookspec sorter in the preferences.

I get a lot of

```
WARNING: QPainter::begin: A paint device can only be painted by one painter at a time.
18:13:18 WARNING QPainter::begin: A paint device can only be painted by one painter at a time.
```

and if I uncheck one of the reader hookspecs it goes away instead of being dimmed. Maybe this was from the recent opactiy adjustment in #2783 cc @ppwadhwa @goanpeca 

<img width="1061" alt="Screen Shot 2021-06-03 at 6 13 21 PM" src="https://user-images.githubusercontent.com/6531703/120731117-c63e2780-c497-11eb-84ec-38287d4560db.png">

**Comment by ppwadhwa** [comment]
yes, that's from that PR. I will look at it now!
