### ISSUE TITLE
ipy_interactive / napari.run blocking (or mechanism under this) not working properly while running codes with Spyder 

### ISSUE THREAD

**Issue by AKEOPLUS-boris-bocquet** [napari/napari#2849]
## To Reproduce

1. Install napari  0.4.8.
2. run the script given below using Spyder "F5", which calls ```runfile``` command.
3. The console will output ```after run``` but the napari window is still running (you don't have to close it, so ```run``` does not block execution).

```python
import napari 
from napari.utils.settings import SETTINGS
SETTINGS.ipy_interactive = False

viewer = napari.Viewer()
print("SETTINGS.ipy_interactive ==", SETTINGS.ipy_interactive)
napari.run()
print("after run")
print("SETTINGS.ipy_interactive ==", SETTINGS.ipy_interactive)
```

## Expected behavior

```run``` should block code execution as expected / as writen in the documentation.

## Environment

 - Please copy and paste the information at napari info option in help menubar here:
```
napari: 0.4.8
Platform: Windows-10-10.0.19041-SP0
Python: 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)]
Qt: 5.15.2
PyQt5: 5.15.2
NumPy: 1.19.4
SciPy: 1.6.0
Dask: 2020.12.0
VisPy: 0.6.6

OpenGL:
- GL version: 4.6.0 - Build 26.20.100.8142
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1080, scale 1.0

Plugins:
- console: 0.0.3
- svg: 0.1.4
```

 - Any other relevant information:
 Maybe the problem is that  the type of shell is ```spyder_kernels.console.kernel.SpyderShell``` ??
printing ```shell.active_eventloop``` : returns ```qt```

**Comment by tlambert03** [comment]
@goanpeca, do you know what might be going on that might make spyder behave any differently here?

@AKEOPLUS-boris-bocquet ... we recently merge a better way intentionally block in #2669
if you have time, can you try from master with

```python
viewer = napari.Viewer()
viewer.show(block=True)
```

**Comment by AKEOPLUS-boris-bocquet** [comment]
Remarks : the code behaves properly using ```VSCodium``` with ```ms-python``` plugging

**Comment by tlambert03** [comment]
@AKEOPLUS-boris-bocquet, other things that would be good to know here, what are the outputs of this script when run in spyder?

```python
import sys

print("IPython" in sys.modules)

import IPython

shell = IPython.get_ipython()
print(shell, bool(shell))
print(shell.active_eventloop)

from qtpy.QtWidgets import QApplication

app = QApplication.instance()
if app:
    print(app.applicationName())

```

**Comment by AKEOPLUS-boris-bocquet** [comment]
> ```python
> viewer.show(block=True)
> ```

This proposal works as expected with the same Spyder installation, but new python virtual environment and using freshly cloned napari source code from master branch.

**Comment by tlambert03** [comment]
great.  thanks for testing, That will be in the next release (0.4.9) which will be released very soon

**Comment by AKEOPLUS-boris-bocquet** [comment]
> 
> 
> @AKEOPLUS-boris-bocquet, other things that would be good to know here, what are the outputs of this script when run in spyder?
> 
> ```python
> import sys
> 
> print("IPython" in sys.modules)
> 
> import IPython
> 
> shell = IPython.get_ipython()
> print(shell, bool(shell))
> print(shell.active_eventloop)
> 
> from qtpy.QtWidgets import QApplication
> 
> app = QApplication.instance()
> if app:
>     print(app.applicationName())
> ```

Here is the output 
```
True
<spyder_kernels.console.kernel.SpyderShell object at 0x000002496B76DE08> True
qt
napari
```

**Comment by tlambert03** [comment]
thanks again.  I assume you put that in a script after making a napari viewer?  I'm surprised the `applicationName` would already be napari with that script alone...  
Basically, what I'm trying to figure out is whether something in spyder is starting the ipython `gui_qt` interactive event loop before napari even has a chance to get involved.  If that is the case, then I'm not sure there's anything we can do to make `napari.run` block, and using the newer `viewer.show(block=True)` is probably going to be the better (only?) way.

**Comment by AKEOPLUS-boris-bocquet** [comment]
> 
> 
> thanks again. I assume you put that in a script after making a napari viewer? I'm surprised the `applicationName` would already be napari with that script alone...

You are probably right. I retried today, "freshly", and this time I have this output : 
```
True
<spyder_kernels.console.kernel.SpyderShell object at 0x00000270DD9BCF48> True
inline
```

**Comment by AKEOPLUS-boris-bocquet** [comment]
@tlambert03 : So, what's your conclusion / proposal ? Are you going to release a patch or not (and then I should go for your recent 0.4.9 release) ? I am not currently sticked to a release version. But maybe my issue is a problem for someone else (even if I haven't seen something similar in the opened and closed issues).

**Comment by tlambert03** [comment]
>  So, what's your conclusion / proposal ?

The proper way to have napari block on showing a viewer is going to be `viewer.show(block=True)`  ... 
`SETTINGS.ipy_interactive = False` setting is there to control whether or not napari instructs IPython to start a `%gui qt`  event loop.  But it looks like spyder is already doing this, so `SETTINGS.ipy_interactive` and `napari.run` can't be the place to attack that problem (we would effectively need to go in and _stop_ the app that Spyder had already created ... which is going to be very bug prone).

let me know if you have any issues using the `viewer.show(block=True)` approach instead

**Comment by AKEOPLUS-boris-bocquet** [comment]
`viewer.show(block=True)` does the job properly. I have updated all my codes on my project [UCVTK](https://github.com/AKEOPLUS-boris-bocquet/UCVTK) and I don't experience troubles so far (even if I am not hard trying to make the code to fail). So let's forget about the "old way" and continue with a properly implemented and maintained `viewer.show(block=True)`.
Thanks for your help.
