### ISSUE TITLE
Non-private dimensionality-based interpolation

### ISSUE THREAD

**Issue by brisvag** [napari/napari#2852]
## 🚀 Feature
`Image` layer has a "private" `_interpolation` attribute that contains a dictionary that maps number of displayed dimensions to interpolation used. However, the public counterpart only exposes the *current* value, which depends on the current `dims.ndisplay`. It would be nice to have a public access to the full dict-like attribute.

## Motivation

If I prepare a bunch of layers in advance, I'd like to be able to prepare some sane defaults based on the type of data. For example, I know that in most of my use cases one will want an interpolation of `spline36` rather than `linear`. Currently, pre-setting this value for 2D while in 3D is only possible by first switching `dims.ndisplay` to 2, then back to 3.

## Pitch

I'd like to either be able to access the dict, or another settable form of it.

**Comment by tlambert03** [comment]
sounds good to me.  That was only "private by default".   but it definitely seems reasonable to set the non-visible interpolation setting!

**Comment by jni** [comment]
@goanpeca I'm not sure this is a good first issue. 😂 I think there's some tricky API discussions to be had here!

**Comment by goanpeca** [comment]
Whoops, it felt like a simple change from afar :)

**Comment by brisvag** [comment]
closed by #4725.
