### ISSUE TITLE
napari octree doesn't work for multiple layers blended

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#2862]
## 🐛 Bug

Multiple layers blended do not work with the napari octree right now as it doesn't track the layer id properly in the cache. This can be fixed by disabling an aspect of the cache, but then performance is slow. We also might want to think about delaying the update until all layers for a certain tile have loaded to avoid an unseemly flickering.

## To Reproduce

```python
import dask.array as da
import napari

file_name = 'data/camelyon16/tumor_001.zarr'
pyramid = [da.from_zarr(file_name + '/' + str(i)) for i in range(10)]

# create an empty viewer
viewer = napari.Viewer()

# add the pyramid
viewer.add_image([p[:, :, 0] for p in pyramid], name='red', colormap='red', blending='additive')
viewer.add_image([p[:, :, 1] for p in pyramid], name='green', colormap='green', blending='additive')
viewer.add_image([p[:, :, 2] for p in pyramid], name='blue', colormap='blue', blending='additive')
napari.run()
```

## Expected behavior

Here is the current behaviour

https://user-images.githubusercontent.com/6531703/121442205-02fa9a80-c940-11eb-9b91-c2b8748b923e.mov

Here is the expected behavior (which comes from rendering image as rgb with all layers together).

https://user-images.githubusercontent.com/6531703/121442265-1c034b80-c940-11eb-8d65-3b9835575af8.mov

**Comment by sofroniewn** [comment]
Note the above was done with NAPARI_OCTREE enabled. If disabled then things render correctly, but are slow 

<img width="1202" alt="Screen Shot 2021-06-09 at 4 34 53 PM" src="https://user-images.githubusercontent.com/6531703/121442582-c8453200-c940-11eb-8064-eef97ca4c9f1.png">

**Comment by sofroniewn** [comment]
So far I've been able to identify at least three issues that might be preventing this from working.

The first is that with tiled rendering enabled but `force_synchronous` set to True, we still see artifacts like

<img width="1202" alt="Screen Shot 2021-06-09 at 6 34 31 PM" src="https://user-images.githubusercontent.com/6531703/121450941-7e187c80-c951-11eb-9787-b16031611d48.png">

and the blending isn't quite right, suggesting that work is still needed on the vispy tiled visual.

Next off is that the `cancel_unseen` will cancel all chunks from other layers apart from the last one, so this clearly needs to be changed
https://github.com/napari/napari/blob/ced9a10708e57cdfa20e0e82c6a9802a38f570b9/napari/layers/image/experimental/_octree_loader.py#L423-L425

And then finally the `OctreeLocation` doesn't have the layer id in the hash and eq methods, see https://github.com/napari/napari/blob/ced9a10708e57cdfa20e0e82c6a9802a38f570b9/napari/components/experimental/chunk/_request.py#L103-L112 which means that some of the tracking of chunks in dictionaries and the cache will match objects from the same location but different layers.

All this will need to be fixed for this to work as expected. I think during that process there will be an opportunity to consider the multilayer use-case with fresh perspective and improve the implementation for this use case

**Comment by jluethi** [comment]
@sofroniewn Hey Nick! Curious if this is still the up-to-date view in the napari community regarding multiple layers and using lazy loading (/pyramid-based) approaches. We're really interested to go further in this direction and use napari to view large (e.g. > 1000 image sites), multiplexed (> 20 channels) datasets.

Here's a movie of how this looks in an old tool from our lab, but that's 2D only. Would be great to build the next version of this (with 3D & time) in napari!

https://user-images.githubusercontent.com/18033446/145804740-371b158f-a88b-4d99-8a53-7b6196693021.mov

Any pointers to where we can push to get around this issue?

**Comment by sofroniewn** [comment]
> Any pointers to where we can push to get around this issue?

Maybe @perlman can weigh in. I'm afraid the above represents my latest knowledge

**Comment by psobolewskiPhD** [comment]
With octree having been removed, I think this issue is no longer valid and we can close?
cc: @andy-sweet

**Comment by andy-sweet** [comment]
> With octree having been removed, I think this issue is no longer valid and we can close? cc: @andy-sweet

Agreed. Closing.
