### ISSUE TITLE
Pin vispy < 0.7

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#2875]
## 🚀 Feature
I think we should pin vispy < 0.7 for our next release. Everyone is working hard to ensure a migration will be easy, but there might be some breaking changes when the release comes out, and I think we'll want to be able to adopt 0.7 when we have everything working as expected.

**Comment by jni** [comment]
@sofroniewn As an alternative, how about adding a CI configuration that uses the VisPy main branch? I've been doing light testing on main and it seems to be working fine. Hopefully not too onerous to maintain that compatibility?

Just a thought — I'm also ok with pinning.

**Comment by sofroniewn** [comment]
vispy 0.7 is now ready for testing - see https://github.com/vispy/vispy/issues/2104

I'm making this thread for us to collect any changes on the napari end that we need to make to get up to date.

I've already found one minor one 

```python-traceback
  File "/Users/nsofroniew/GitHub/napari/napari/view_layers.py", line 17, in <module>
    from .viewer import Viewer
  File "/Users/nsofroniew/GitHub/napari/napari/viewer.py", line 3, in <module>
    from .components import ViewerModel
  File "/Users/nsofroniew/GitHub/napari/napari/components/__init__.py", line 17, in <module>
    from .camera import Camera
  File "/Users/nsofroniew/GitHub/napari/napari/components/camera.py", line 5, in <module>
    from ..utils.events import EventedModel
  File "/Users/nsofroniew/GitHub/napari/napari/utils/__init__.py", line 1, in <module>
    from .colormaps import Colormap
  File "/Users/nsofroniew/GitHub/napari/napari/utils/colormaps/__init__.py", line 2, in <module>
    from .colormap import Colormap
  File "/Users/nsofroniew/GitHub/napari/napari/utils/colormaps/colormap.py", line 11, in <module>
    from .standardize_color import transform_color
  File "/Users/nsofroniew/GitHub/napari/napari/utils/colormaps/standardize_color.py", line 27, in <module>
    from vispy.color import ColorArray, get_color_dict, get_color_names
  File "/Users/nsofroniew/GitHub/vispy/vispy/color/__init__.py", line 12, in <module>
    from .colormap import (Colormap, BaseColormap,  # noqa
  File "/Users/nsofroniew/GitHub/vispy/vispy/color/colormap.py", line 12, in <module>
    from hsluv import hsluv_to_rgb
ModuleNotFoundError: No module named 'hsluv'
```

Which we new was coming (i think from https://github.com/vispy/vispy/pull/2066).

Maybe @alisterburt we can coordinate here on making sure we'll be compatible

**Comment by sofroniewn** [comment]
Actually that error might be inside vispy - i have created https://github.com/vispy/vispy/issues/2108 to document

**Comment by sofroniewn** [comment]
ok, this is fixed by `pip install hsluv`, see comment in thread - package was moved to be an external dependency

**Comment by sofroniewn** [comment]
ok, i'm able to launch napari with `0.7` and see an image - I get a `divide by zero encountered in true_divide` printed in the console which we should look into, but that's already a very good sign!!!

I will try running tests now

**Comment by sofroniewn** [comment]
that warning pops up here 

```
self = <napari._vispy.vispy_camera.VispyCamera object at 0x7f83b8f1f3d0>

    @property
    def zoom(self):
        """float: Scale from canvas pixels to world pixels."""
        canvas_size = np.array(self._view.canvas.size)
        if self._view.camera == self._3D_camera:
            # For fov = 0.0 normalize scale factor by canvas size to get scale factor.
            # Note that the scaling is stored in the `_projection` property of the
            # camera which is updated in vispy here
            # https://github.com/vispy/vispy/blob/v0.6.5/vispy/scene/cameras/perspective.py#L301-L313
            scale = self._view.camera.scale_factor
        else:
            scale = np.array(
                [self._view.camera.rect.width, self._view.camera.rect.height]
            )
>       zoom = np.min(canvas_size / scale)
E       RuntimeWarning: divide by zero encountered in true_divide

napari/_vispy/vispy_camera.py:109: RuntimeWarning
```

need to fix for tests to pass

**Comment by alisterburt** [comment]
awesome work @sofroniewn - I'll take a look myself tomorrow morning and report back here if I find anything else

**Comment by alisterburt** [comment]
'tomorrow morning' - whoops

#2958 is a fix for the error you found - I ran a bunch of examples covering a range of layer types (image volume vectors surface points shapes) and didn't find any other glaring issues so I think we're relatively safe
