### ISSUE TITLE
ipython + visible console results in AttributeError

### ISSUE THREAD

**Issue by maweigert** [napari/napari#2880]
## 🐛 Bug

When instantiating a napari viewer with a visible console dock from inside ipython results in `AttributeError` (seems to be something related to `ipython` itself, see below)

## To Reproduce

1. start napari from command line `napari`
2. select the console dock to be visible and close again
3. start napari from within ipython `ipython -c "import napari;napari.Viewer()"`

```
napari/_qt/qt_viewer.py in <lambda>(visible)
    173         # gets (or creates) the console when the dock console is made visible.
    174         self.dockConsole.visibilityChanged.connect(
--> 175             lambda visible: self.console if visible else None
    176         )
    177         self.dockLayerControls.visibilityChanged.connect(self._constrain_width)

AttributeError: 'QtViewer' object has no attribute 'console'
```

This does *not* happen, when
*  the console dock is not visible
*  using `python` instead of `ipython`, i.e. `python -c "import napari;napari.Viewer()"` works

## Environment
```
napari: 0.4.9
Platform: macOS-10.15.7-x86_64-i386-64bit
System: MacOS 10.15.7
Python: 3.8.0 (default, Nov 6 2019, 15:49:01) [Clang 4.0.1 (tags/RELEASE_401/final)]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.20.3
SciPy: 1.6.3
Dask: 2021.06.0
VisPy: 0.6.6

OpenGL:
- GL version: 2.1 ATI-3.10.18
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1792x1120, scale 2.0

Plugins:
- console: 0.0.3
- scikit-image: 0.4.9
- svg: 0.1.5
```

## Additional context

happens too on linux and python 3.8/3.9

**Comment by tlambert03** [comment]
thanks @maweigert .  git blame puts it at #2861 ... will have a look
