### ISSUE TITLE
Save selected layers and save all layers are enabled, if no layers have been added

### ISSUE THREAD

**Issue by goanpeca** [napari/napari#2883]
## 🐛 Bug

On `File menu` Save selected layers and save all layers are enabled, if no layers have been added.

## To Reproduce

1. Open napari
2. Look at the `File menu` and see enabled entries that are tied to the existence of a layer

<img width="622" alt="Screen Shot 2021-06-14 at 4 40 33 PM" src="https://user-images.githubusercontent.com/3627835/121963076-3e75da00-cd2f-11eb-8cf7-c9b205fbe3d2.png">

## Expected behavior

If no layers are available, options that apply to layers should be grayed out.

Example on Chrome
<img width="366" alt="Screen Shot 2021-06-14 at 4 40 45 PM" src="https://user-images.githubusercontent.com/3627835/121963102-459ce800-cd2f-11eb-8bc5-c0fc11d24faa.png">

**Comment by adriehz** [comment]
Hi! 
I'm new here, can I try to work on this?

**Comment by goanpeca** [comment]
Hi @adriehz, sure you can! 💪🏼 

Some pointers to get you going:
- This is where the File menu is created. https://github.com/napari/napari/blob/master/napari/_qt/qt_main_window.py#L457
- We will need to keep references to the actions that need to be disabled based on context.
