### ISSUE TITLE
Convert TextManager to an EventedModel

### ISSUE THREAD

**Issue by andy-sweet** [napari/napari#2886]

**Comment by sofroniewn** [comment]
Will this be closed by #2885? Curious why you needed to open a new issue here. Was it for estimation, or do you have something else in mind?

**Comment by andy-sweet** [comment]
Yes, this should be closed by [#2885](https://github.com/napari/napari/pull/2885). Intuitively, I opened an issue for this for sprint planning, but agreed that it's not really needed.
