### ISSUE TITLE
Save function defect 0.4.9

### ISSUE THREAD

**Issue by Chris-N-K** [napari/napari#2887]
## 🐛 Bug

In 0.4.9 the save selected layers and save all layers functions do no longer work. If selected they throw a list index out of range error. Tested it in a clean environment with a new installation via: pip install napari[all]

## To Reproduce

1. Open napari
2. Load or create a layer
3. Try to save it via selected or all layers function

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~/anaconda3/envs/napari4.9test/lib/python3.8/site-packages/napari/_qt/qt_main_window.py in ()
    485         save_selected_layers.setStatusTip(trans._('Save selected layers'))
    486         save_selected_layers.triggered.connect(
--> 487             lambda: self.qt_viewer._save_layers_dialog(selected=True)
        global self.qt_viewer._save_layers_dialog = undefined
        global selected = undefined
    488         )
    489 

~/anaconda3/envs/napari4.9test/lib/python3.8/site-packages/napari/_qt/qt_viewer.py in _save_layers_dialog(self=, selected=True)
    531             parent=self,
    532             caption=trans._('Save {msg} layers', msg=msg),
--> 533             directory=hist[0],  # home dir by default,
        global directory = undefined
        hist = []
    534             filter=ext_str,
    535         )

IndexError: list index out of range

## Environment

napari: 0.4.9
Platform: Linux-3.10.0-1160.25.1.el7.x86_64-x86_64-with-glibc2.10
Python: 3.8.10 | packaged by conda-forge | (default, May 11 2021, 07:01:05) [GCC 9.3.0]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.20.3
SciPy: 1.6.3
Dask: 2021.06.0
VisPy: 0.6.6

OpenGL:
- GL version: 2.1 Mesa 18.3.4
- MAX_TEXTURE_SIZE: 8192

Screens:
- screen 1: resolution 1440x960, scale 1.0

Plugins:
- console: 0.0.3
- scikit-image: 0.4.9
- svg: 0.1.5

**Comment by goanpeca** [comment]
Hi @ch-n 

Thanks for the report. This has been fixed in master and will be available in the following release.

**Comment by Chris-N-K** [comment]
Sadly 4.9 is not usable for many tasks with this bug then.
When will be the following release approximately?

**Comment by goanpeca** [comment]
In the meantime you could patch the file yourself (is a one line fix)

you can execute this code to get the file you need to update

```bash
python -c "from napari.utils import history;print(history.__file__)"
```

A and then update the file from:

```python
def get_save_history():
    """A helper for history handling."""
    folders = SETTINGS.application.save_history
    folders = [f for f in folders if os.path.isdir(f)]
    return folders
```

To:

```python
def get_save_history():
    """A helper for history handling."""
    folders = SETTINGS.application.save_history
    folders = [f for f in folders if os.path.isdir(f)]
    return folders or [str(Path.home())]
```

---

@sofroniewn maybe we could do a mini-patch (0.4.9.1) release to include this, while 0.4.10 is out?

**Comment by Chris-N-K** [comment]
Thanks for the self patch suggestion. :)
Will fix it on our machines.

**Comment by sofroniewn** [comment]
> Sadly 4.9 is not usable for many tasks with this bug then.

We could start the `0.4.10` release process today / make the release tomorrow. I think it might be worth it - cc @jni @tlambert03

**Comment by tlambert03** [comment]
while trying something with magicgui yesterday, I realized I may have also introduced a regression in the `napari.types.*` registration during the `__init__` reorg.  so that should also get fixed ASAP and should go in a quick patch release

**Comment by sofroniewn** [comment]
`0.4.10` has now been released with fix
