### ISSUE TITLE
code after the `yield` in a bound callback does not always execute on key release

### ISSUE THREAD

**Issue by alisterburt** [napari/napari#2893]
## 🐛 Bug

In some situations, code after the yield in a bound callback does not execute on key release. e.g. just after clicking a layer in the layer list

**EDIT** should've read [the docs](https://napari.org/tutorials/fundamentals/viewer.html#custom-keybinding) - happy for this to be closed if it's an issue you're aware of

## To Reproduce
```Python
import napari
from skimage import data

viewer = napari.Viewer()
layer = viewer.add_image(data.astronaut())

@viewer.bind_key('h')
def hide_image_layer(event=None):
    print('hiding')
    layer.opacity = 0
    yield
    print('showing')
    layer.opacity = 1
```

https://user-images.githubusercontent.com/7307488/122301440-97449e80-cef8-11eb-94ea-77c064b1e6ca.mp4

In this video, if I have clicked in the canvas then the callback works as expected: hide on keypress, show on key release

If I click on a layer in the layerlist then hit my key only the first part of the callback is activated, the code after the `yield` never executes.

The behaviour is the same with any keybinding I've tried. I'm happy to look into this but would need some pointers on how to debug 🙂 

## Environment

```
napari: 0.4.9
Platform: macOS-11.2.1-x86_64-i386-64bit
System: MacOS 11.2.1
Python: 3.9.4 | packaged by conda-forge | (default, May 10 2021, 22:13:15)  [Clang 11.1.0 ]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.20.3
SciPy: 1.6.3
Dask: 2021.05.0
VisPy: 0.6.6

OpenGL:
  - GL version:  2.1 Metal - 71.0.7
  - MAX_TEXTURE_SIZE: 16384

Screens:
  - screen 1: resolution 1440x900, scale 2.0

Plugins:
  - console: 0.0.3
  - scikit-image: 0.4.9
  - svg: 0.1.5
```

**Comment by jni** [comment]
@alisterburt I don't understand your edit... is this working as expected or not?

**Comment by alisterburt** [comment]
@jni the docs have a note saying 

> Currently the keybindings only work when the main canvas is in focus, we are working to ensure they always work.

So I guess the behaviour comes under that umbrella and is expected if you have read the docs properly, otherwise it still feels pretty unexpected

**Comment by Carreau** [comment]
I believe this is the same issue as #2714

**Comment by psobolewskiPhD** [comment]
I can't reproduce this. 
I used the script from the OP and then clicked in various places and used the keybind:
https://github.com/napari/napari/assets/76622105/4c5934e2-ebb4-4001-a268-9c53f190c052

Keybinds have changed a lot so I think this is fixed.

This means the docs should be updated. I'll make an issue in the docs repo.
