### ISSUE TITLE
Move to python 3.9 in the bundle for Big Sur support

### ISSUE THREAD

**Issue by alisterburt** [napari/napari#2898]
## 🚀 Feature
This is an issue to discuss whether we should move to Python 3.9 for the bundled napari installation 

## Motivation
As mentioned in #2895, the bundle is currently incompatible with macOS Big Sur because it comes with Python 3.8. The workaround seems to be moving to the conda-forge distribution of Python 3.9. Moving to Python 3.9 in the bundle would mean users on Big Sur (including those on systems with M1 chips) could use the bundled installation of napari.

Are there any negatives of moving to 3.9 we should think about?

EDIT:
info from @tlambert03 (copied here from #2895) 
> As for 3.9, we had been waiting for the 3.9 briefcase support pack to drop. It's now [available](https://github.com/beeware/briefcase/issues/540), and so is [m1 support](https://github.com/beeware/Python-Apple-support/issues/107) ... so it might be worth a try updating the bundle.

**Comment by jni** [comment]
:+1: on this

**Comment by alisterburt** [comment]
bundle built and working locally without any fuss on Big Sur (running on an M1, but built for x86) - I just have to figure out how to replicate on github actions
![image](https://user-images.githubusercontent.com/7307488/123012840-e5efae00-d3ba-11eb-98df-e4a0e93445e5.png)

**Comment by tlambert03** [comment]
actually... looks like you might have a bug there:

<img width="128" alt="Untitled" src="https://user-images.githubusercontent.com/1609449/123013107-8fba4500-d391-11eb-9b61-fa763c73aaed.png">

**Comment by alisterburt** [comment]
*big trouble* 🤣

**Comment by Carreau** [comment]
> actually... looks like you might have a bug there:

Actually it's a secret folder he has changed the icon of, to make sure nobody click on it.

**Comment by Czaki** [comment]
For support macos arm natively you need to check if all packages with binary extension provides `universal2` wheels.  At this moment `imagecodecs` does not provide. 

Other solution may be create build base on `conda`.

**Comment by alisterburt** [comment]
I was not planning on building a native bundle (for now at least), I was planning to build with the conda-forge packaged python interpreter though

**Comment by tlambert03** [comment]
Briefcase packs it's own python interpreter... (https://github.com/beeware/Python-Apple-support) so I'm not sure that's going to be as easy as it might seem?  That is, it doesn't use the python in the build environment

**Comment by alisterburt** [comment]
oh! I assumed it was using my conda-forge interpreter and that was why it worked... it seems like the 3.9 briefcase interpreter already works out of the box then, great! 🙂

**Comment by Czaki** [comment]
But it works using rosetta emulation or uses native architecture? 
The main problem with rosetta is that it does not support vector instruction translation (SSE2 etc). This instruction could be used to speed up typical image processing operations.

**Comment by alisterburt** [comment]
It's using rosetta emulation (at least the way I built it). I understand it might not be the perfect solution, but it's at least better than the current situation which is no working bundle on Big Sur on any mac? Longer term I agree we should look at building a native bundle too

**Comment by Czaki** [comment]
I agree. But with this update, there should be added proper annotation on the download page.

**Comment by goanpeca** [comment]
Pinging @jaimergp

**Comment by jaimergp** [comment]
Note that my tests for #3266 are being done with Python 3.9 on Big Sur :)

**Comment by sofroniewn** [comment]
This has now been closed by #2991, thanks all!
