### ISSUE TITLE
How to load a tiff segmentation image with unique label as label layer instead of image

### ISSUE THREAD

**Issue by YubinXie** [napari/napari#2899]
## 🚀 Feature
Hi, I hope to load a tiff segmentation image with unique label as label layer instead of image. Currently it opens the tiff as image layer and I dont know how to convert it to a label layer. Thanks!

## Motivation

Load my own segmentation for visualization

**Comment by jni** [comment]
@yubinXie how are you using napari? From Python, from the command line, or as an application? In the latter option, you currently *have* to make sure that your .tiff file pixels are 32-bit or 64-bit signed/unsigned integers. All other data types will be interpreted as an image.

If you can tell us how you are generating your segmentation images we might be able to help you make sure they are one of those formats.

We are hoping to add functionality to convert one layer type to the other but haven't gotten around to it yet — see #1442.

**Comment by YubinXie** [comment]
@jni Thanks a lot for your reply. The mask is generated by the latest version of deep cell and I reloaded the tiff file, which shows dtype=int64.

I am using napari from terminal calling (an application I assume). It currently looks like this.

![7F8CFECF-CCCC-4091-A720-1611798D7CED](https://user-images.githubusercontent.com/16257776/122796418-5cda5900-d28c-11eb-821d-bd86792f4352.png)

**Comment by jni** [comment]
that's very strange. Could you provide the tiff file so that we can investigate?

**Comment by YubinXie** [comment]
Hey @jni I just tested on the latest version napari and it worked! I think this is version related! Thank you for your help!
