### ISSUE TITLE
Notification can't be expanded and slowly moves off screen

### ISSUE THREAD

**Issue by DragaDoncila** [napari/napari#2938]
## 🐛 Bug

This is an odd bug I discovered while playing with other things this week. On Ubuntu when I expand a notification it doesn't expand but rather move further down the screen with each click of the arrow. Has anyone else seen this?? I'll investigate it this coming sprint.

https://user-images.githubusercontent.com/17995243/123702615-b521e400-d8a6-11eb-87ca-18c9f323445e.mp4

## To Reproduce

1. Open napari
2. Try to open a text file or generate a notification in some other way
3. Try to expand and contract the notification

## Expected behavior

Notification is expanded and contracted, and doesn't move off screen.

## Environment

```
napari: 0.4.9
Platform: Linux-5.4.0-77-generic-x86_64-with-glibc2.17
System: Ubuntu 20.04.2 LTS
Python: 3.8.10 (default, Jun 4 2021, 15:09:15) [GCC 7.5.0]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.20.3
SciPy: 1.6.3
Dask: 2021.06.0
VisPy: 0.6.6

OpenGL:
- GL version: 4.6 (Compatibility Profile) Mesa 20.2.6
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1080, scale 1.0
- screen 2: resolution 1920x515, scale 1.0
- screen 3: resolution 1920x1080, scale 1.0

Plugins:
- console: 0.0.3
- scikit-image: 0.4.9
- svg: 0.1.5
```

**Comment by goanpeca** [comment]
I have seen this, but I can't remember how I got there in the first place!

**Comment by DragaDoncila** [comment]
@goanpeca just glad it's not only me :laughing:
