### ISSUE TITLE
Refactor progress bars to not inherit from `tqdm`

### ISSUE THREAD

**Issue by DragaDoncila** [napari/napari#2940]
Many of the issues we've been seeing with tests are a result of the ProgressBar widgets leaking and not being tightly coupled with the viewer.

While working on #2931 and #2656 it's become evident that at least part of the complexity lies in `tqdm` and its complex refresh logic. We can maintain most if not all of the functionality we currently have without inheriting from `tqdm`. I think this will give us more control over the ProgressBars, and also give us a chance to more tightly couple the viewer and ProgressBars to avoid some of the issues we've been seeing.

**Comment by tlambert03** [comment]
i'd be ok with that

**Comment by DragaDoncila** [comment]
I think it's safe to say we can close this after the comments in #3004, #3439 and the intervening two years. If anyone comes across this after experiencing issues with this inheritance model, feel free to reopen!
