### ISSUE TITLE
Remove deprecated brush_shape

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#2942]
## 🧰 Task

Following on from #2426 by @ppwadhwa, are we now ready to remove the deprecated brush shape and only allow for the square brush? It will simplify the codebase. @jni if you're good for this to go now then @ppwadhwa you could pick this up when you have time - should be pretty easy once green light from @jni. We'd just be left with the circle brush as the only brush type after this.

**Comment by jni** [comment]
Yup I'm good with this! 👍

**Comment by sofroniewn** [comment]
@ppwadhwa this could be a good thing to pick up during the "quality sprint" if you like too
