### ISSUE TITLE
Documentation on how to debug plugins during development

### ISSUE THREAD

**Issue by jni** [napari/napari#2948]
## 📚 Documentation
@Czaki wrote a really nice guide about [profiling in Python](https://napari.org/developers/profiling.html) in the context of napari. It would be good to have a similarly detailed guide about debugging, both in the context of napari development and in the context of plugins.

One extremely useful feature in particular that I think is currently undocumented is @tlambert03's "Enter debugger" from error notifications, which I've used a *lot* over the past few weeks.

**Comment by jni** [comment]
CC @alisterburt @kevinyamauchi @DragaDoncila who were around when this question was asked at the EMBO workshop.

**Comment by tlambert03** [comment]
This is something I have thoughts/strategies on... I can help with this or do it if no else wants it

**Comment by seankmartin** [comment]
I would like to help out with this issue, I think it would be great to have these docs.

I'm not sure what the movement on this issue has been, but I perhaps I can gather together the information that is available on the forums and zulip and github around this issue and draft something up to get the ball rolling?
I am very open to other ideas though if help would be preferred in some other manner!

**Comment by DragaDoncila** [comment]
@seankmartin thanks for reaching out about this issue! There hasn't been any movement on writing these docs, so anything that you can draft up with what's spread out there on the forums and zulip would be excellent. Once we have something drafted we can always look at expanding it, but having something is better than having nothing at all!

Please ping me for review or assistance whenever 😃
