### ISSUE TITLE
Creating a labels layer from the layer `data_tuple` results in empty colors.

### ISSUE THREAD

**Issue by JoOkuma** [napari/napari#2953]
## 🐛 Bug

Copying labels through the `data_tuple` API results in a new Labels layers with empty colors.
I'm not sure if this a real bug because I'm using some "private" methods.

## To Reproduce

```python3
import napari
import numpy as np

viewer = napari.Viewer()
labels = viewer.add_labels(np.random.randint(10, size=(10, 10)))

data_tuple = labels.as_layer_data_tuple()
cpy = viewer._add_layer_from_data(*data_tuple)[0]

# cpy.color_mode = labels.color_mode  # with this line it works                                                                                                                                                                                          

napari.run()
```

## Expected behavior

The new layer should be equal to its source, including the color mapping.

## Environment

```
napari: 0.4.8
Platform: Linux-5.8.0-55-generic-x86_64-with-glibc2.10
System: Ubuntu 20.04.2 LTS
Python: 3.8.8 (default, Apr 13 2021, 19:58:26) [GCC 7.3.0]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.20.3
SciPy: 1.6.3
Dask: 2021.04.0
VisPy: 0.6.6

OpenGL:
- GL version: 4.6 (Compatibility Profile) Mesa 20.2.6
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 3440x1440, scale 1.0

Plugins:
- console: 0.0.3
- napari-dexp: 0.1.dev7+g3714459
- napari-simple-crop: 0.1.dev1+gd89c7ea.d20210629
- ome_zarr: 0.0.19
- scikit-image: 0.4.8
- svg: 0.1.4
```

## Additional context

I thought this could be solved by adding this attribute to the [_get_state](https://github.com/napari/napari/blob/d310847f0c79f062daadecb8a159e8972c074470/napari/layers/labels/labels.py#L514) but it does not work with the `_add_layer_from_data` since it is not an argument of the `add_labels` method.

**Comment by tlambert03** [comment]
that's a bug,
it appears that the default `color_mode` default really depends on whether the `color` argument is provided or not (i.e.  `color_mode` is _also_ set in `@color.setter`)

```python
In [53]: labels = Labels(np.zeros((1,1), int))

In [54]: labels.color_mode
Out[54]: 'auto'

In [55]: Labels(labels.data, color=labels.color).color_mode
Out[55]: 'direct'
```

cc @andy-sweet

**Comment by tlambert03** [comment]
> I'm not sure if this a real bug because I'm using some "private" methods.

by the way... `viewer._add_layer_from_data(*data_tuple)` is a very important private method, that may actually be public someday soon (see https://github.com/napari/napari/pull/2556/files#r659247491).  so this is one "private" usage that should definitely work.

**Comment by JoOkuma** [comment]
Do you think the `color_mode` default is the issue?

I think that the `color` key from `_get_state` dict returning a partially complete dict is the problematic behavior. I think it should return the complete dict if `color_mode` is `direct`, else it should return an empty dict. 

We could remove the `None` and `_background_label` values from the `color` key in `_get_state()`  dict because they are added if not available, but it might lead to other problems.

**Comment by tlambert03** [comment]
> Do you think the color_mode default is the issue?

I'm not so much trying to state that the color_mode default itself is the problem, just that the round trip is not consistent due to the way `color_mode` is initialized. (which I think is what you're saying too).    You could either have the color.setter recognize that the provided `color` argument is the default, set color_mode to auto... or you could strip the default values from `_get_state()`... don't have a strong preference for the approach
