### ISSUE TITLE
Feature: `add_<shape_type>` methods on Shapes layer

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#2956]
## 🚀 Feature
was just using the shapes layer programmatically (for maybe the first time?? 😂)  ... I had two points and wanted to draw a line.  I found myself looking for an `add_line` method, but found slightly more confusing `add()` method.

I wonder how folks would feel about some of convenience methods?  it might allow us to do a little more data validation and provide guidance for the corresponding shape type?  (i.e. `line` expects a different number of vertices than `rectangle` right?)

I kinda wanted to do `layer.add_line((x1, y1),  (x2, y2))`.  but I'd understand if we don't like supporting non-container arguments like that.  but I next tried a list: 
```python
layer.add([(x1, y1),  (x2, y2)], shape_type='line')
``` 
... looks like that failed because it wasn't a numpy array... however, the error message there was rather confusing:

```python
ValueError: <enum 'ShapeType'> may only be called with a `str` or an instance of <enum 'ShapeType'>. Got <class 'int'>
```

<details>

```pytb
In [94]: shp.add([coord1, coord2], shape_type='line')
---------------------------------------------------------------------------
~/Dropbox (HMS)/Python/forks/napari/napari/layers/shapes/shapes.py in add(self, data, shape_type, edge_width, edge_color, face_color, z_index)
   1677                 self.text.remove(indices_to_remove)
   1678
-> 1679             self._add_shapes(
   1680                 data,
   1681                 shape_type=shape_type,

~/Dropbox (HMS)/Python/forks/napari/napari/layers/shapes/shapes.py in _add_shapes(self, data, shape_type, edge_width, edge_color, face_color, z_index, z_refresh)
   1883             )
   1884
-> 1885             self._add_shapes_to_view(shape_inputs, self._data_view)
   1886
   1887         self._display_order_stored = copy(self._dims_order)

~/Dropbox (HMS)/Python/forks/napari/napari/layers/shapes/shapes.py in _add_shapes_to_view(self, shape_inputs, data_view)
   1893         for d, st, ew, ec, fc, z in shape_inputs:
   1894
-> 1895             shape_cls = shape_classes[ShapeType(st)]
   1896             shape = shape_cls(
   1897                 d,

~/Dropbox (HMS)/Python/forks/napari/napari/utils/misc.py in __call__(cls, value, names, module, qualname, type, start)
    234                 return value
    235             else:
--> 236                 raise ValueError(
    237                     trans._(
    238                         '{class_name} may only be called with a `str` or an instance of {class_name}. Got {dtype}',

```

</details>

anyway, just some thoughts from a new shapes user :)

**Comment by jni** [comment]
I'm 👍 on this proposal. Different shapes have very different natural parameterizations that is hard to capture with a single `.add` call.

**Comment by DragaDoncila** [comment]
I think this is a good idea and also agree it's probably expected behaviour, especially since each shape has its own button in the layer controls. It'd be nice to have a corresponding `add_` method for each new shape button in the controls.
