### ISSUE TITLE
Linux bundle build needs to be migrated to ubuntu-latest

### ISSUE THREAD

**Issue by jni** [napari/napari#2963]
## 🧰 Task

We are currently building our Linux bundle on ubuntu-16.04. It looks like that image is deprecated which is causing our builds to fail, see e.g.:

https://github.com/napari/napari/actions/runs/988280586

The message suggests switching to ubuntu-latest. I presume though that we are using 16.04 to ensure compatibility, in which case, maybe we switch to 18.04?

**Comment by jaimergp** [comment]
This will happen on September 20th, so I am happy to give a try. I think @ziyangczi was working on this too. Should we coordinate?
