### ISSUE TITLE
Error while loading plugins

### ISSUE THREAD

**Issue by strambc** [napari/napari#2972]
## 🐛 Bug
When attempting to load a plugin I get the following error:
2021-07-02 16:46:43.047 napari[70356:7689775] error: unrecognized arguments: --upgrade
This applies to all attempted plugins including:

napari-bioformats
napari-omero
napari-demo
napari-animation
napari-ome-zarr

## To Reproduce

1. Launched latest version of Napari
2. Plugins>Install/uninstall package(s)
3. Hit "Install" (blue button)
4. Received error --> 2021-07-02 16:46:43.047 napari[70356:7689775] error: unrecognized arguments: --upgrade

## Environment

 - Please copy and paste the information at napari info option in help menubar here:
napari: 0.4.10
Platform: macOS-10.15.7-x86_64-i386-64bit
System: MacOS 10.15.7
Python: 3.8.8 (default, Mar 6 2021, 04:04:59) [Clang 12.0.0 (clang-1200.0.32.29)]
Qt: 5.15.2
PySide2: 5.15.2
NumPy: 1.19.3
SciPy: 1.6.3
Dask: 2021.06.0
VisPy: 0.6.6

OpenGL:
- GL version: 2.1 INTEL-14.7.12
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1440x900, scale 2.0

Plugins:
- console: 0.0.3
- scikit-image
- svg: 0.1.5

## Additional context

macOS Catalina
10.15.7

Hardware Overview:

  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro16,2
  Processor Name:	Quad-Core Intel Core i5
  Processor Speed:	2 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	512 KB
  L3 Cache:	6 MB
  Hyper-Threading Technology:	Enabled
  Memory:	16 GB
  Boot ROM Version:	1554.80.3.0.0 (iBridge: 18.16.14347.0.0,0)
  Serial Number (system):	C02D77HGML7M
  Hardware UUID:	4519F2F3-D6B4-5583-9D44-CD4F95491B79
  Activation Lock Status:	Disabled

**Comment by tlambert03** [comment]
Hi @strambc, sorry about that.  This is a known issue with the bundle at the moment (see https://github.com/napari/napari/issues/2965) ... we hope to have it fixed soon.  but in the meantime, you'll have to install napari from the terminal (see tutorial [here](https://napari.org/tutorials/fundamentals/installation.html) for details), here's the gist:

```
conda create -y -n napari-env -c conda-forge python.app
conda activate napari-env
pip install "napari[all]"
napari
```

once you do that, the built-in plugin installer should work.

**Comment by strambc** [comment]
Hi @tlambert03 thank you for your speedy reply. Not urgent for me. I will wait until you fix the known issue.
