### ISSUE TITLE
Feature: Static plugin "manifest" file

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#2975]
## 🚀 Feature

In vscode, if you open an file with an extension that a plugin could help with, you get the following message:
<img width="519" alt="60721732-c8538080-9f26-11e9-8d42-106ad7bff32f" src="https://user-images.githubusercontent.com/1609449/124388727-159f8f80-dcb2-11eb-8a01-7d8f812b4131.png">

It would be awesome if napari could do the same thing.  like, you drop a `.czi` file on the viewer, and instead of getting the "no plugin available" error, you could get something like "there are plugins that can help with `.czi` files".

VScode achieves this through a static [extension manifest](https://code.visualstudio.com/api/references/extension-manifest) (json file) that, among many other fields, includes a `contributes` field that declares the plugin's [contribution points](https://code.visualstudio.com/api/references/contribution-points) (which is where the plugin can declare a `contributes.languages`).

The static manifest concept would solve a lot of problems for us.  It could be used to declare file extensions that reader/writer plugins provide without requiring a python import (see [prior conversation](https://github.com/napari/napari/issues/1790#issuecomment-719958933)).  It could be parsed by the hub's [`get_extra_metadata`](https://github.com/chanzuckerberg/napari-hub/blob/e4f28ef65bed4e786a97aa1edb7a8adadd7c456c/backend/napari.py#L143) (cc @neuromusic)... 

_Installed_ plugins could use a dedicated `entry_point` to provide the manifest (which would avoid any python imports), but how we would get the info for uninstalled plugins is another question (since this is obviously more detail than the PyPI API will let us query).  The hub seems like a natural place to store that data, and it would be great if the napari application could hit an API at the hub to realize the "there are plugins that could help with this" goal.

side-note: if we had this, it should also be possible to [ignore recommendations](https://code.visualstudio.com/docs/editor/extension-marketplace#_ignoring-recommendations)

**Comment by neuromusic** [comment]
> The hub seems like a natural place to store that data, and it would be great if the napari application could hit an API at the hub to realize the "there are plugins that could help with this" goal.

💯 % 

@goanpeca kicked off the convo re: a public API from the hub here: https://github.com/chanzuckerberg/napari-hub/discussions/133

I'd love to make this happen by the end of 2020. Its technically quite feasible, but on the CZI side, we'll need to go through a legal & security review to make sure we're doing it right. The sooner we can get a spec and plan together, the sooner I can kick off that process.

**Comment by tlambert03** [comment]
great.  I do think that this particular spec will need to be much more tightly developed with napari core than other metadata on the hub... so it may not be possible to go quite as fast on this?

edit: (I see this as a bit different than #133 too for what it's worth.  That proposal would let us move away from parsing HTML in our [`pypi.py`](https://github.com/napari/napari/blob/master/napari/plugins/pypi.py#L65) file... this one would form the basis of a lot of APIs)

**Comment by tlambert03** [comment]
i think we can close this now :)  we done got ourselves a manifest.
