### ISSUE TITLE
Feature: add `.npy` reader to builtin reader

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#2976]
## 🚀 Feature
Feels like reading a single `.npy` array file would be in-scope for our builtin reader?  objections?

**Comment by alisterburt** [comment]
no objection, great idea!

**Comment by jni** [comment]
Finally, an actually good good-first-issue! :joy: Might be a good one for the upcoming SciPy sprints!

**Comment by AhmetCanSolak** [comment]
It looks like this issue is addressed, so I am closing it.
