### ISSUE TITLE
Affine.rotate does not always return the `rotate` input

### ISSUE THREAD

**Issue by andy-sweet** [napari/napari#2984]
## 🐛 Bug

When defining an Affine transform by only a rotation matrix, the Affine.rotate property is not the same as the output for some angles. This was originally found in work related to the [`itk-napari-conversion` plugin](https://github.com/InsightSoftwareConsortium/itk-napari-conversion/pull/11).

## To Reproduce

For example, when the 2D rotation angle is 120 degrees, the final assertion will not pass.

```python
import numpy as np

angle_radians = np.deg2rad(120)
cos_angle = np.cos(angle_radians)
sin_angle = np.sin(angle_radians)
rotate = np.array([[cos_angle, -sin_angle], [sin_angle, cos_angle]])

transform = Affine(rotate=rotate)

np.testing.assert_almost_equal(rotate, transform.rotate)
```

## Expected behavior

When only a rotation matrix is passed in on construction of an Affine transform object, the `Affine.rotate` property of that instance should match it. This should always be the case when the `rotate` matrix does not contain any overall reflection (i.e. its determinant is 1), and maybe also when it does.

## Environment

napari at HEAD with standard environment from setup.

## Additional context

This is a bug that should be fixed regardless, but also represents part of an effort to make napari play nicely with ITK. In that spirit, we probably want to allow the rotation component of a transform to contain reflections instead of absorbing those into the scale component.

**Comment by sofroniewn** [comment]
@andy-sweet and I discussed this offline - it seems like this is the case because we absorb the any reflections into the sign of the scale. I think we did this at the beginning as we didn't have rotate, we only had scale. Now that we have rotate, I'm fine with them being in rotate. @jni do you have any thoughts on this?

**Comment by jni** [comment]
I'm wondering whether we should just *not* compose these elements — keep them as separate elements in the chain and use caching to speed things up. ie, if we move them to rotate, then users giving a negative scale will have the same problem later on, right? Also, isn't it true that some reflections can't be expressed as rotations? (e.g. reflections about only one axis)

**Comment by sofroniewn** [comment]
I think avoiding composition and decomposition as much as possible could be good, it might make things a little less standard, but would guarantee the round trips above. Thoughts @andy-sweet?

**Comment by andy-sweet** [comment]
Agreed that the best long term fix is to not compose these elements in a lossy way, so that we can just return what was passed in (or at least the equivalent coerced form). I have some old work that does this by defining a new `Transform` type, so let me get that up for review to see if it's useful.

The affine matrix decomposition as defined now will always be ambiguous up to reflections, so when they exist in a transform, they have to be absorbed into one of the elements. Like @jni mentioned, if we absorb them into rotate (as ITK's Direction effectively does), then the naming would be unfortunate because that's not strictly a rotation matrix anymore (i.e. it's just an orthonormal matrix with a determinant that could be -1). We might want to try to force the decomposed form into something more standard to avoid the weird behavior in the example above where scale absorbs two reflections and thus gives a different true rotation matrix back, but that might be more work than is useful if we skip the composition in most places.
