### ISSUE TITLE
self._mode_history seem to be unused on points, shapes and labels.

### ISSUE THREAD

**Issue by Carreau** [napari/napari#2987]
## 🧰 Task

This seem to have been used for "hold space to XXXX" in the past looking at git log, but seem unused now.
It could be an easy first issue.

**Comment by nclack** [comment]
It doesn't look like anything reads from this so I'll just remove it.

**Comment by sofroniewn** [comment]
Likely a remnant of previous functionality! I think it's good to be dropped
