### ISSUE TITLE
Vispy colormap deprecation warnings.

### ISSUE THREAD

**Issue by Carreau** [napari/napari#2988]
## 🧰 Task

There seem to be many new colormap deprecation warnings in vispy about using 'cubehelix' literal instead of creating a CubeHelixColormap. I've open https://github.com/vispy/vispy/pull/2134 to have a proper stacklevel and see where this is actually coming from.

I think that will likely affect the following where we might want custom logic

```
napari/components/_tests/test_viewer_model.py
50:    assert viewer.add_image(data, colormap='cubehelix')

napari/utils/colormaps/colormap_utils.py
65:    cubehelix=(trans._p('colormap', 'cubehelix'), _VCO['cubehelix']),
```

and the following vendored file.

```
napari/_vispy/vendored/mesh.py
122:        self._cmap = get_colormap('cubehelix')
```

**Comment by kevinyamauchi** [comment]
I just tested this on main and it appears to no longer be an issue, so I am closing for now. Please feel free to reopen if you experience it!
