### ISSUE TITLE
Instant flash effect on screenshot

### ISSUE THREAD

**Issue by alisterburt** [napari/napari#3000]
## 🚀 Feature
Add an option to make the flash effect seen when taking a screenshot feel more 'instant'

Current behavior on the left, desired alternative behaviour on the right

https://user-images.githubusercontent.com/7307488/125000812-1c7b2900-e049-11eb-9b27-aef67ca48477.mp4

## Motivation
The (awesome) flash effect added in #2721 by @lukasz-migas ramps from no colour at `t=0` to the desired colour at `t=0.5` back down to no colour at `t=1` over the duration of the flash effect. This behaviour is great for highlighting UI features but when taking screenshots, it could be nice to have the flash feel more 'instant', like a camera flash which starts really bright then fades.

This idea came from playing with `napari-animation` where screenshots are taken in quick succession. In that situation, the slight delay between clicking the button and the bright flash felt slightly out of place

## Pitch
Add a `mode` parameter to `add_flash_animation()`
https://github.com/napari/napari/blob/0df4c87f30ed99ca178b26639899e9c7641ccb8d/napari/_qt/utils.py#L258-L271
mode could be set to
- `fade_in_out` (current behaviour)
- `fade_out` (instant flash effect)

The options could be defined in a `StringEnum` as we do for the `mode` of our shapes layer
https://github.com/napari/napari/blob/102a7e8f845893c874d2b86f9371d41130100b89/napari/layers/shapes/_shapes_constants.py#L8-L35

The `fade_out` behaviour could be implemented by changing the starting color here
https://github.com/napari/napari/blob/0df4c87f30ed99ca178b26639899e9c7641ccb8d/napari/_qt/utils.py#L279

and removing the key-frame of the animation here
https://github.com/napari/napari/blob/0df4c87f30ed99ca178b26639899e9c7641ccb8d/napari/_qt/utils.py#L293

## Alternatives
We could also expose the position of the key-frame rather than defining specific modes, shifting the key-frame position to 0.1 or so would provide a very similar effect

## Additional context
This would be a great issue for the upcoming scipy sprints

**Comment by jni** [comment]
@alisterburt I don't think an option is a good idea here — I agree with your design suggestion but let's just pick that one, rather than have a configurable option here.

**Comment by alisterburt** [comment]
@jni initially I thought the same, the reason I suggested making it configurable was I can imagine the flash effect as implemented being used in the proposed 'guided tour' of UI features (#2361) - happy to start with only the fade out effect though if there's consensus!

**Comment by alisterburt** [comment]
closed by #3060
