### ISSUE TITLE
Add pop-out button for grid mode and store defaults in settings

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#3009]
## 🚀 Feature
This would supersede #3007 and #2974 by adding a pop out to the grid button, accessible by right clicking it that would allow the user to set the `grid size` as a 2-tuple of int (could be two int comboboxes > 0) and the stride could be a int combobox that could be negative or positive (0 should result in no grid). It should look like the pop out dialog for the play button

<img width="1175" alt="Screen Shot 2021-07-09 at 8 40 14 AM" src="https://user-images.githubusercontent.com/6531703/125105193-10b45480-e093-11eb-8c2c-e27b4910e990.png">

Clicking the button normally should toggle between grid enabled/ disabled.

The default values of size, stride, and enabled should also be stored in the settings. Changing the values in the popout shouldn't change defaults (like is done with the play button) but changing values in settings should change values in popout.

How does this sound @haesleinhuepf @tlambert03? If agreed on this behaviour we can give to @ppwadhwa for the next sprint.

**Comment by sofroniewn** [comment]
@liaprins-czi this is also something you could mock up in design before @ppwadhwa implements. Should be fairly quick to do, compared to some of the other work, and I know @haesleinhuepf is pretty eager for this functionality!

**Comment by tlambert03** [comment]
i like it

**Comment by haesleinhuepf** [comment]
> and I know @haesleinhuepf is pretty eager for this functionality!

😃 Yes, especially if `stride=-1` was default 🙂

**Comment by sofroniewn** [comment]
> 😃 Yes, especially if stride=-1 was default 🙂

After this was added you'd be able to set the default value in the settings to be `-1`. You'd have to change it once, but then it would persist for all time - literally forever!!!! :-)

**Comment by haesleinhuepf** [comment]
Alright, no hurry from my side!

**Comment by sofroniewn** [comment]
@LCObus new plan for grid button is here (see comment from @LCObus in https://github.com/napari/napari/pull/2974#issuecomment-878444882)

> just throwing my 2 cents I agree that we should
>
> 1. make it configurable
> 2. have clear UX that designates it as such (we're going to start accruing configurable/customizable modes that users should understand and value!) and point in documentation (per nick's "Possibly that needs to be better documented if people aren't aware that works.")
> 3. We could do quick polling on the default (or more in depth testing if we have additional queries about the set up experience) but i think the more important signal is to educate users they can configure as they please!

**Comment by LCObus** [comment]
thanks @sofroniewn, excited to see this develop!
Agree on the
> It should look like the pop out dialog for the play button

maintaining expectations about when to discover and customize more will be helpful for heuristics (recognition not recall)

**Comment by liaprins-czi** [comment]
![Grid mode settings](https://user-images.githubusercontent.com/53277128/125686798-165928c3-69c1-4cef-b596-49497902a3b8.png)

@neuromusic @ppwadhwa Here is my mockup for the popout, let me know if this makes sense. Also, what should the default stride be first time user opens the grid mode popout?

**Comment by liaprins-czi** [comment]
And if we want to includ emore explanatory info, it could live in little help icons; here is a little prototype mocking it up:
https://www.figma.com/proto/5yHtWYtZ9KzEuCFRzVMwRI/Grid-mode-settings?page-id=0%3A1&node-id=3%3A116&viewport=172%2C-851%2C1&scaling=min-zoom&starting-point-node-id=3%3A116

**Comment by sofroniewn** [comment]
Thanks so much for this @liaprins-czi! Great to see it mocked out and I love the little help icon in
![image](https://user-images.githubusercontent.com/6531703/125735867-518fb39a-f918-4aa0-9816-346bd2c5c5c6.png)

Definitely something we might want to use more of!

I'm thinking that we might want to go with `Grid stride`, `Grid height`, and `Grid width` as the three options. I find `shape height` and `shape width` a little funny as its not really the height of the shape, it was more the shape of the grid which has a height and width.

Also @ppwadhwa is it possible to make a combobox which skips `0` as then we could use a combobox that goes `-1, 1, 2, ...` for width/ height. And possibly one that goes `... -2, -1, 1, 2, ....` for stride. I think having comboboxes for height and width will probably feel better than having free text though as the values are only integers.

For tooltip help we could have the following for stride

```
Number of layers to place in each grid square before moving on to
        the next square. The default ordering is to place the most visible
        layer in the top left corner of the grid. A negative stride will
        cause the order in which the layers are placed in the grid to be
        reversed.
```

and the following for height/ width.

```
        Number of rows and columns in the grid. A value of -1 for either or
        both of will be used the row and column numbers will trigger an
        auto calculation of the necessary grid shape to appropriately fill
        all the layers at the appropriate stride.
```


> Also, what should the default stride be first time user opens the grid mode popout?

The defaults are -1, -1 for `width` / `height` and `1` for stride, see 
 
 https://github.com/napari/napari/blob/a8e618a742ef915ea3638a61592981fb17b2bd7f/napari/components/grid.py#L33-L34

Does this all sound good to @jni? Might be good to get one more look over (I'd also be open to rows/ columns instead of height/ width, but don't have a strong feeling).

Maybe @liaprins-czi you can look over my suggestions above and if you agree can make an update mock that @ppwadhwa can then build against. Also happy to discuss more if you disagree with any. Thanks!!

**Comment by liaprins-czi** [comment]
@sofroniewn Yeah that all sounds good to me! I will update soon.

So just to verify, the width and height inputs will now be the same style as the stride (the + and - buttons with int showing in the middle)?

Also, we can have sepaarate "?" icons for the width vs height if that is better, I just put them as one because the initial text you posted in the Slack thread describing each input had width and height with one description. I think that way does make sense since they are very similar, but just checking if we want them to have separate descriptions we can

**Comment by sofroniewn** [comment]
> So just to verify, the width and height inputs will now be the same style as the stride (the + and - buttons with int showing in the middle)?

Yes i think so

> Also, we can have sepaarate "?" icons for the width vs height if that is better, I just put them as one because the initial text you posted in the Slack thread describing each input had width and height with one description. I think that way does make sense since they are very similar, but just checking if we want them to have separate descriptions we can

I like how you did one "?" between the two as they are so related to each other

**Comment by liaprins-czi** [comment]
Alreight, here is the updated prototype:
https://www.figma.com/proto/5yHtWYtZ9KzEuCFRzVMwRI/Grid-mode-settings?page-id=0%3A1&node-id=3%3A116&viewport=-167%2C-1050%2C1&scaling=min-zoom&starting-point-node-id=3%3A116

**Comment by ppwadhwa** [comment]
Thanks, @liaprins-czi and @sofroniewn.  I'm going to start putting this in place!  :)

**Comment by sofroniewn** [comment]
> Thanks, @liaprins-czi and @sofroniewn. I'm going to start putting this in place! :)

Love it! Great hand off @liaprins-czi 

![image](https://user-images.githubusercontent.com/6531703/125865899-0b15bedd-e3ed-4447-880a-8f90466481b2.png)
