### ISSUE TITLE
Access violation as test runner exits in github ci

### ISSUE THREAD

**Issue by nclack** [napari/napari#3012]
## 🐛 Bug

An [access violation](https://github.com/napari/napari/runs/3030822582?check_suite_focus=true#step:7:278) was observed for the `py38-windows-pyqt` environment during a run of the 'PR Test' check.  

It appears as if all tests passed and the access violation happened as the pytest process exited.  This suggests some kind of race condition during process shutdown.

## To Reproduce

It's not so clear to me how to reproduce.  I attempted running `tox -e py38-windows-pyqt` a few times on a local machine but failed to see it there.

## Expected behavior

The software should never produce an access violation.

**Comment by kcpevey** [comment]
All of the latests test on PRs and on main are passing and I don't see any access violation on any of the windows tests. 
The latest test using [`py38-windows-qt`](https://github.com/napari/napari/actions/runs/3641488208/jobs/6147481818)

The old GH Action logs in the original issue are no longer available. 

Everything seems fine now. I suggest closing. If it shows up again we can reopen.

**Comment by Czaki** [comment]
I think that we could mark it as resolved. I have made few PR like #5171 or #2726 to prevent this.
