### ISSUE TITLE
Opacity slider label should be between 0 and 1

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#3014]
## 🐛 Bug

Opacity slider label should be between 0 and 1 not 0 and 100. This will remove need for normalization on slider https://github.com/napari/napari/blob/aade148d8e5cb339bb2981ab4d1081ae5d2747e0/napari/_qt/layer_controls/qt_layer_controls_base.py#L79

![image](https://user-images.githubusercontent.com/6531703/125152865-96bcb380-e104-11eb-9a09-7a9784a3da0c.png)

**Comment by svenkat19** [comment]
Hasn't line 79 solved the issue?

**Comment by sofroniewn** [comment]
> Hasn't line 79 solved the issue?

@svenkat19 line 79 does do the normalization, but if you look at the diff in #3016 you'll see what I had in mind, there we move away from an integer based slider to a float based slider so the normalization isn't needed and the label has the "correct" value
