### ISSUE TITLE
Example data hooks pointing to resources on HTTP don't load TIF files correctly

### ISSUE THREAD

**Issue by haesleinhuepf** [napari/napari#3021]
## 🐛 Bug

I'm trying to make example data available from zenodo.org. napari doesn't load it correctly. I also can't tell which plugin loaded the data. It's not AICSImageIO, because I have reported a [related issue](https://github.com/AllenCellModeling/napari-aicsimageio/issues/16) there and deactivated it before observing the issue reported below:

## To Reproduce

I implemented a napari hook for example data like this::
```
@napari_hook_implementation
def napari_provide_sample_data():
    return {
        "Haase_MRT_tfl3d1": "https://zenodo.org/record/5090508/files/Haase_MRT_tfl3d1.tif?download=1",
    }
```

When clicking it, it only loads the first plane of that dataset:
![image](https://user-images.githubusercontent.com/12660498/125190067-996df480-e23b-11eb-9f13-9391ad19f057.png)

You can reproduce it by installing napari-pyclesperanto-assistant 0.9.5 in your napari. You will then find this entry under File > Open Samples > clEsperanto > Haase_MRT_tfl3d1. Click it to reproduce the error above.

## Expected behavior

When I load the same file from disc, it looks like this, a proper stack:

![image](https://user-images.githubusercontent.com/12660498/125190086-b1457880-e23b-11eb-89c8-849e9e5d2bc1.png)

Let me know if I can help tracing this issue down!

## Environment

 - Please copy and paste the information at napari info option in help menubar here
napari: 0.4.10
Platform: Windows-10-10.0.19041-SP0
Python: 3.9.4 | packaged by conda-forge | (default, May 10 2021, 22:10:34) [MSC v.1916 64 bit (AMD64)]
Qt: 5.12.9
PyQt5: 5.12.3
NumPy: 1.19.5
SciPy: 1.6.3
Dask: 2021.06.0
VisPy: 0.6.6

OpenGL:
- GL version: 4.6.0 NVIDIA 466.77
- MAX_TEXTURE_SIZE: 32768

Screens:
- screen 1: resolution 1920x1200, scale 1.0

Plugins:
- OpenCL_Random_Forest_Classifier: 0.3.1
- StarDist: 2021.6.1
- animation: 0.0.2
- clEsperanto: 0.9.4
- console: 0.0.3
- devbio: 0.1.0
- napari-skimage-regionprops: 0.1.0
- scikit-image: 0.4.10
- svg: 0.1.5

 - Any other relevant information:

## Additional context

I had similar issues while loading data from zenodo when using `skimage.io.imread`. It helps to provide the plugin to the reader:
```
imread(filename, plugin='tifffile')
```

**Comment by tlambert03** [comment]
> I also can't tell which plugin loaded the data.

have you tried `layer.source`?

```py
In [1]: viewer.layers[0].source
Out[1]: Source(path='https://zenodo.org/record/5090508/files/Haase_MRT_tfl3d1.tif?download=1', reader_plugin='builtins', sample=None, widget=None)
```

note, you can also specify which plugin should be used in [`viewer.open_sample`](https://github.com/napari/napari/blob/aade148d8e5cb339bb2981ab4d1081ae5d2747e0/napari/components/viewer_model.py#L713) (but it looks like that isn't yet an optional part of the hookspec)

**Comment by tlambert03** [comment]
I suspect that, being a url, the builtin reader is using `imageio.imread`, which would probably need some help in loading a full 3D stack.  Definitely would be a nice feature... but probably takes some digging, starting around here:

https://github.com/napari/napari/blob/aade148d8e5cb339bb2981ab4d1081ae5d2747e0/napari/utils/io.py#L129-L131

let me know if I can help with the sleuthing

**Comment by haesleinhuepf** [comment]
Ok, when I modify [this part](https://github.com/napari/napari/blob/aade148d8e5cb339bb2981ab4d1081ae5d2747e0/napari/utils/io.py#L122-L131) so that the URL passes and the image is loaded by tifffile, like this:
```
    ext = os.path.splitext(filename)[1].split("?")[0]
    print(ext)
    if ext.lower() in [".tif", ".tiff", ".lsm"]:
        import tifffile
        print("loading", filename, 'via tifffile')
        return tifffile.imread(filename)
    else:
        import imageio

        return imageio.imread(filename)
```

Then I see an error on the command line:
```
(bio2) C:\structure\code\napari>napari
.tif
loading https://zenodo.org/record/5090508/files/Haase_MRT_tfl3d1.tif?download=1 via tifffile
14:31:50 ERROR PluginError: Error in plugin 'builtins', hook 'napari_get_reader'
  Cause was: ValueError('no files found')
    in file: C:\Users\rober\miniconda3\envs\bio2\lib\site-packages\tifffile\tifffile.py
    at line: 801
     author: napari team
      email: napari-steering-council@googlegroups.com
    package: napari
        url: https://napari.org
    version: 0.4.11.dev37+gaade148d.d20210711
```

Thus, tifffile also doesn't allow to read this file. The error can be confirmed by calling:
```
import tifffile
  
filename = 'https://zenodo.org/record/5090508/files/Haase_MRT_tfl3d1.tif?download=1'

image = tifffile.imread(filename)
```

However, calling skimag.io.imread with plugin='tifffile' works:
```
from skimage import io

filename = 'https://zenodo.org/record/5090508/files/Haase_MRT_tfl3d1.tif?download=1'

image = io.imread(filename, plugin='tifffile')
image.shape
```
```
(240, 320, 320)
```

Shall we add another if-block in the code linked above and use scikit-image io with plugin tifffile in case an image filename is supposed to load starting with "http" and containing ".tif?". It feels a bit cumbersome...

**Comment by tlambert03** [comment]
We just generally need to handle URLs better.  A while back, we stopped using `skimage.io.imread` so as to avoid the full dependency (as implied in our imread docstring), but one thing that didn't come over is the [`file_or_url_context` manager](https://github.com/scikit-image/scikit-image/blob/d85b06468e063f2b8aa6aa7e073e120294e8e2f8/skimage/io/util.py#L21-L43) that scikit-image uses in their [imread function](https://github.com/scikit-image/scikit-image/blob/d85b06468e063f2b8aa6aa7e073e120294e8e2f8/skimage/io/_io.py#L47).  That context manager will detect a url, download it first, and only _then_ let tifffile do it's job.  Our imread, by contrast, has very limited url detection capabilities, and does no preliminary download step (and tifffile itself doesn't handle downloading), so that's why `skimage.io.imread(..., plugin='tifffile')` works but `napari.utils.io.imread(...)` doesn't, even if you strip the query params. 

Sidenote here, [`urllib.parse.urlparse`](https://docs.python.org/3/library/urllib.parse.html#module-urllib.parse) is your friend when parsing urls in the general format of `scheme://netloc/path;parameters?query#fragment`, it works for local filepaths too.

```py
In [19]: urlparse('https://zenodo.org/record/5090508/files/Haase_MRT_tfl3d1.tif?download=1')
Out[19]: ParseResult(scheme='https', netloc='zenodo.org', path='/record/5090508/files/Haase_MRT_tfl3d1.tif', params='', query='download=1', fragment='')
```

a possible short-term solution is to just copy over that `file_or_url` context manager to napari... but I also think that remote file handling is a much bigger topic that requires a lot more consideration.

**Comment by evamaxfield** [comment]
Just patched `napari-aicsimageio` to allow for proper passthrough to the next in line readers.

I will say, part of your problem will be trying to read from zenodo... it seems like the they don't like getting slammed with requests and a lot of remote read libraries split reads into chunks. After I patched I was getting `Too many requests` errors.

As cool as zenodo is.. maybe using an object store would be better (s3 / gcs / heck even [dropbox has an implementation](https://github.com/intake/filesystem_spec/blob/master/setup.py#L42))

**Comment by willingc** [comment]
I'm closing this old issue as it seems to be resolved by the patch to `napari-aicsimagio`. :sunny:

**Comment by psobolewskiPhD** [comment]
I'm not sure the underlying issue of handling URLs to open things is really handled, but we can consider https://github.com/napari/napari/issues/7264 as a fresh, more specific take.
