### ISSUE TITLE
Building image from dockerfile results in "WARNING Could not load the Qt platform plugin "xcb" in "" even though it was found."

### ISSUE THREAD

**Issue by MaximLippeveld** [napari/napari#3024]
## 🐛 Bug

When running a docker image built with the dockerfile provided in this repository, I get a warning from Qt which states that "xcb" could not be loaded.

## To Reproduce

1. In local napari repository, run: `docker build -t napari .` to build the image
2. Run `docker run -e DISPLAY=host.docker.internal:0 napari:bad python3 /tmp/examples/add_image.py`

This prints the following error:
```
WARNING: Could not load the Qt platform plugin "xcb" in "" even though it was found.
WARNING: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.
```
This error was also mentioned in #1457, which was not initially submitted as a docker-related issue. 

## Expected behavior

Napari pops up and Eileen Collins smiles at me.

## Environment

 - Please copy and paste the information at napari info option in help menubar here:
 I cannot copy/paste, since napari won't launch.

 - Any other relevant information:
OS is Fedora 34 (Workstation edition)
Docker version 20.10.7, build f0df350

## Additional context

I managed to get a working docker image.

I added the xcb related libraries from [this comment](https://github.com/napari/napari/issues/1457#issuecomment-752667286) on #1457 to the dockerfile, and also added libxcb-shape0. After rebuilding and running with the same command from the documentation, I got the following error: `WARNING: could not connect to display host.docker.internal:0`.

I solved this by first running `xhost +local:root` and then running the image using
```
docker run -it --rm --device=/dev/dri:/dev/dri -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix:ro -v /home/maximl:/data napari:latest python3 /tmp/examples/add_image.py
```
I found these commands in the [documentation of the CellProfier project](https://github.com/CellProfiler/distribution/blob/master/docker/README.md). Unfortunately, this will only work on linux systems (and the xhost command is insecure).

Not sure if this is worth a pull request, but I just wanted to post it here in case anyone wants to locally run napari in a docker container. I turned to docker, because I had issues on Fedora when trying to do a native install with conda.

**Comment by liu-ziyang** [comment]
good catch! host.docker.internal:0 is a docker MacOS convention where other platforms have different ways of mounting the display device address which I couldn't exhaust when I worked on this. I will add the dependencies in the docker file and rebuild some of the images.

We will continue the discussion of the underlying issue in #1457 for visibility. I will rebuild the images as fast as I can, and please see above tips if you run into the issue
