### ISSUE TITLE
Design for (#3009) "Add pop-out button for grid mode and store defaults in settings"

### ISSUE THREAD

**Issue by liaprins-czi** [napari/napari#3029]
- [ ] Find out what content needs to be included in the pop-out + map the interactions
- [ ] Mockup design / prototype interaction if needed
- [ ] Consider right-click interaction...
- [ ] Share on #3009

**Comment by liaprins-czi** [comment]
https://github.com/napari/napari/issues/3009

**Comment by sofroniewn** [comment]
This has now been done, and #3009 has merged, thanks!!
