### ISSUE TITLE
[SPIKE] Investigate future of progress bar architecture

### ISSUE THREAD

**Issue by DragaDoncila** [napari/napari#3032]
Currently our `progress` objects inherit from `tqdm` allowing them to behave like terminal progress bars when there is no active viewer, and be added to the viewer when there is one. See [this discussion](https://github.com/sofroniewn/waver/pull/5#discussion_r666692376) for how useful that can be.

The ability to "alias" our own progress objects as `tqdm` can be very useful for code which already has terminal progress bars available, and @Carreau initially suggested the possibility of a patch we could use for code that we suspect might have a `tqdm` progress bar:

```python
@contextmanager
def patch()
     import tqdm
     orig = tqdm.tqdm
     tqdm.tqdm = progress # the progress you define.
     yield 
     tqdm.tqdm = orig
```

which could be used like:

```python
def action():
      with patch():
        dask.do_stuff() # maybe use tqdm
button.click(action)
```

In an ideal scenario, users would be able to get progress bars in the napari viewer without making any changes to their code - potentially there is an avenue for a patch similar to the above that is even less invasive e.g. it patches the update method of any progress bars used to emit an event which we then connect to in the viewer (@jni originally suggested something like this). 

This issue is meant to track suggestions, discussions and decisions for the desired long term behaviour and architecture of our progress bars, and how we can provide maximal flexibility with minimal changes in user code.

**Comment by jni** [comment]
Nice. =)

> it patches the update method of any progress bars used to emit an event which we then connect to in the viewer

Yeah ideally what we want is an "evented progressbar" that allows callbacks on update, and it perhaps allows a *global* callback register so that we can register napari as a viewer of those progress bars. Unclear to me how easy that would be to do for tqdm or for alternatives like [alive-progress](https://github.com/rsalmei/alive-progress), the latter of which has some rather honking great ideas such as throttling visible updates to 60fps.

**Comment by tlambert03** [comment]
Fwiw, we were also benefiting from throttling using tqdm, which has its own cap on update frequency.
