### ISSUE TITLE
Storing window size in properties fails when closing napari in full screen mode

### ISSUE THREAD

**Issue by haesleinhuepf** [napari/napari#3038]
## 🐛 Bug

If you close napari when its window is maximized, it stores the window size of the full screen.

## To Reproduce

1. Start napari.
2. Make the window e.g. 500x500 pixels large.
3. Make the window full screen.
4. Close napari
5. Start napari again
6. Undo full screen

## Expected behavior

Napari should have size 500x500 then. This could be achieved by automatically undoing full screen before saving the window size to the settings.

## Environment

 - Please copy and paste the information at napari info option in help menubar here:
napari: 0.4.10
Platform: Windows-10-10.0.19041-SP0
Python: 3.8.5 (default, Sep 3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]
Qt: 5.12.9
PyQt5: 5.12.3
NumPy: 1.21.0
SciPy: 1.7.0
Dask: 2021.07.0
VisPy: 0.7.0

OpenGL:
- GL version: 4.6.14756 Compatibility Profile Context 20.40.44.02 27.20.14044.2001
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1200, scale 1.0

Plugins:
- console: 0.0.3
- ome-types: 0.2.7
- scikit-image: 0.4.10
- svg: 0.1.5
 - Any other relevant information:

**Comment by goanpeca** [comment]
Hi @haesleinhuepf thanks for the report.

I started looking at this and it is going to be a bit tricky, will look for options.
