### ISSUE TITLE
Setting `Points.face_color` as a property with cycling colors raises IndexError

### ISSUE THREAD

**Issue by andy-sweet** [napari/napari#3039]
## 🐛 Bug

When setting `Points.face_color` to be a property that is associated with a color cycle raises an IndexError in some cases. In particular, this causes problems when the layer is initialized without any points data, which will be added later.

## To Reproduce

The following test case fails at HEAD.

```python
import enum

import numpy as np

from napari.layers import Points
from napari.utils.colormaps.standardize_color import transform_color


@enum.unique
class CellState(enum.Enum):
    Interphase = 0
    Prometaphase = 1
    Metaphase = 2
    Anaphase = 3
    Apoptosis = 4


COLOR_CYCLE = [
    '#1f77b4', # blue
    '#ff7f0e', # orange
    '#2ca02c', # green
    '#d62728', # red
    '#9467bd', # purple
]

def test_points_with_face_color_property_cycle():
   points_layer = Points(
        name="Annotation",
        properties={'State': [s.name for s in CellState]},
        ndim=2,
    )
    points_layer.mode = 'add'
    points_layer.face_color = 'State'
    points_layer.face_color_cycle = COLOR_CYCLE
    points_layer.face_color_mode = 'cycle'

    points_layer.current_properties['State'] = ['Anaphase']
    points_layer.add((200, 200))

    assert points_layer.properties['State'][0] == 'Anaphase'
    np.testing.assert_array_equal(points_layer.face_color, [transform_color(COLOR_CYCLE)[0]])
```

## Expected behavior

I would expect to be able to set these properties without any errors and for the points layer to be in the desired state after doing so.

## Environment

napari: 0.4.9rc1.dev70+g5fe37b47.d20210709
Platform: macOS-11.3.1-x86_64-i386-64bit
System: MacOS 11.3.1
Python: 3.9.4 | packaged by conda-forge | (default, May 10 2021, 22:13:15) [Clang 11.1.0 ]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.19.5
SciPy: 1.6.3
Dask: 2021.04.1
VisPy: 0.6.6

OpenGL:
- GL version: 2.1 INTEL-16.2.16
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 2560x1440, scale 1.0

Plugins:
- brainglobe-io: 0.0.2
- brainreg-standard: 0.0.2
- cellfinder: 0.0.10
- console: 0.0.3
- napari-demo: 0.0.2
- napari-properties-plotter: 0.1.0
- napari-properties-viewer: 0.0.2
- napari-skimage-regionprops: 0.1.0
- ndtiffs: 0.1.1
- scikit-image: 0.4.9rc1.dev70+g5fe37b47.d20210709
- svg: 0.1.5

## Additional context

I first noticed this when it was brought to my attention [on zulip](https://napari.zulipchat.com/#narrow/stream/212875-general/topic/points.20layer.20properties/near/245842509), though there was [an existing bug in the `cnn-annotator`](https://github.com/lowe-lab-ucl/cnn-annotator/issues/43) repo.

This is similar to #2755 and also fits into the larger work described in #2866. We may want to fix this issue specifically now, or wait until a larger properties redesign/refactor hopefully fixes this and other related bugs that might be lurking.

**Comment by andy-sweet** [comment]
Note that passing `face_color` and `face_color_cycle` when creating the `Points` layer seems to act as an effective and safe workaround for this issue, but does not negate the need to fix it.

```python
   points_layer = Points(
        name="Annotation",
        properties={'State': [s.name for s in CellState]},
        ndim=2,
        face_color='State',
        face_color_cycle=COLOR_CYCLE,
    )
    points_layer.mode = 'add'
    points_layer.face_color_mode = 'cycle'
```

**Comment by kevinyamauchi** [comment]
Thanks for flagging @andy-sweet and @quantumjot ! I think this is related to https://github.com/napari/napari.github.io/issues/133 (sorry, I lost track of this one over my holidays 😞 )

**Comment by quantumjot** [comment]
@kevinyamauchi - absolutely - I "borrowed" your code!
