### ISSUE TITLE
Z-slider does not work when napari OCTREE is enabled with multiscale images

### ISSUE THREAD

**Issue by mfranzon** [napari/napari#3049]
## 🐛 Bug

I have a stack of multiscale images. When I set  `export NAPARI_OCTREE=1`, then the z-slider stop working. I can move the slide but the image is stuck at the first one of the stack. 

## To Reproduce

In the terminal:
` export NAPARI_OCTREE=1`

and then:

```
import numpy as np
import napari
img=[]
d =2000
for level in range(3):
    dataset = np.random.randint(1000, size=(10,d,d))
    img.append(dataset)
    d=d//2

viewer = napari.Viewer()
viewer.add_image(img,multiscale=True)
```

## Environment

```
napari: 0.4.7
Platform: Linux-5.8.0-59-generic-x86_64-with-glibc2.29
System: Ubuntu 20.04.2 LTS
Python: 3.8.10 (default, Jun  2 2021, 10:49:15)  [GCC 9.4.0]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.20.3
SciPy: 1.6.3
Dask: 2021.06.0
VisPy: 0.6.6

OpenGL:
  - GL version:  4.6.0 NVIDIA 465.27
  - MAX_TEXTURE_SIZE: 32768

Screens:
  - screen 1: resolution 1920x1080, scale 1.0

Plugins:
  - console: 0.0.3
  - svg: 0.1.5
```

## Additional context

Thank you very much for the support and for your job!

**Comment by sofroniewn** [comment]
Yes, so sorry about this - it's a known limitation that the "octree" doesn't really work beyond 2D. It might be a little hard to tell that from the "future work" comments here https://napari.org/guides/stable/rendering.html#time-series-multiscale, but it is something that's on our radar and that we want to improve, though we're not actively working on right now

**Comment by mfranzon** [comment]
Ohh I see, thank you for the reference.

**Comment by GenevieveBuckley** [comment]
This issue looks like it's been addressed by https://github.com/napari/napari/pull/3208

If there's anything left remaining, please feel free to reopen the issue.

**Comment by sofroniewn** [comment]
I'll just add that we still hope to eventually address this - cc @perlman
