### ISSUE TITLE
Label Layer square brush is deprecated since 0.4.7 and marked for removal in 0.4.9, still there.

### ISSUE THREAD

**Issue by Carreau** [napari/napari#3051]
## 🧰 Task

#2426 marker square brush are deprecated and to be removed, though it is still there. 
If we actually want to remove it, it should not be too hard and would simplify some code.

This could be an easy task for a new contributor.

**Comment by Carreau** [comment]
This would affect code added by #3050, and remove the piece of logic that checks whether a new cursor value is callable and simplify it a bit.

**Comment by sofroniewn** [comment]
Closed by #3047
