### ISSUE TITLE
QGroupBox Styling hard to see on linux

### ISSUE THREAD

**Issue by ianhi** [napari/napari#3052]
## 🐛 Bug
Checkboxes (`QGroupBox`?) are very difficult to notice on linux (this seems OS dependent see https://github.com/tlambert03/napari-micromanager/issues/23#issuecomment-880797592)

![image](https://user-images.githubusercontent.com/10111092/125816876-10e52200-2817-4701-aa86-ff2f3d88ae92.png)

## To Reproduce

1. Be on linux
2. Open napari-micromanager plugin

## Expected behavior

I can easily notice the checkbox

## Environment
```
napari: 0.4.8
Platform: Linux-5.8.0-7642-generic-x86_64-with-glibc2.10
System: Pop!_OS 20.04 LTS
Python: 3.8.5 (default, Sep 4 2020, 07:30:14) [GCC 7.3.0]
Qt: 5.12.9
PyQt5: 5.12.3
NumPy: 1.20.3
SciPy: 1.6.3
Dask: 2021.06.0
VisPy: 0.6.6

OpenGL:
- GL version: 4.6 (Compatibility Profile) Mesa 20.3.2
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1080, scale 1.0

Plugins:
- console: 0.0.3
- micromanager: 0.1.dev229+g96a8a0c.d20210712
- scikit-image: 0.4.8
- svg: 0.1.5
```

**Comment by tlambert03** [comment]
specifically, we need to fix `QGroupBox::indicator` in our QSS

https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qgroupbox

**Comment by dalthviz** [comment]
Hi, I noticed the `QGroupBox` checkbox not being styled on Windows too (although there the checkbox is white instead):

![imagen](https://user-images.githubusercontent.com/16781833/232111619-023e461f-b6c2-4b88-ba79-c6f67303228d.png)

Probably applying the same/similar [style rules for `QCheckBox::indicator`](https://github.com/napari/napari/blob/eb2385ad3168c56d72b1a91eb87eb9566d8c2cd4/napari/_qt/qt_resources/styles/00_base.qss#L269-L310) to `QGroupBox::indicator` should be enough, right?

Adding as rules something like:

```
QGroupBox::indicator {
  width: 12px;
  height: 12px;
  background-color: {{ foreground }};
  border: 0px;
  padding: 1px;
  border-radius: 2px
}

QGroupBox::indicator:hover {
  background-color: {{ lighten(foreground, 5) }};
}

QGroupBox::indicator:unchecked {
  image: none;
}

QGroupBox::indicator:checked {
  image: url("theme_{{ id }}:/check.svg");
}

QGroupBox::indicator:indeterminate {
  image: url("theme_{{ id }}:/minus.svg");
  padding: 2px;
  width: 14px;
  height: 14px;
}

QWidget[emphasized="true"] QGroupBox::indicator {
  background-color: {{ primary }};
  border-color: {{ primary }};
}

QWidget[emphasized="true"] QGroupBox::indicator:hover {
  background-color: {{ lighten(primary, 5) }};
}

QWidget[emphasized="true"] QGroupBox::indicator:unchecked:hover {
  background-color: {{ lighten(primary, 5) }};
  border-color: {{ lighten(primary, 5) }};
}
```
I got:

|Windows|Linux|Mac|
|---------|------|----|
|![imagen](https://user-images.githubusercontent.com/16781833/232115245-fcfaa969-165f-422b-bb1f-734e81c39250.png)|![imagen](https://user-images.githubusercontent.com/16781833/232123328-24e91224-e8f4-4c5e-98a0-7ed697aeac64.png)|![image](https://user-images.githubusercontent.com/16781833/232123982-6b7dba74-ad37-4d4f-b109-db0b302c142f.png)|

**Comment by psobolewskiPhD** [comment]
That looks great and makes sense—can you pretty please make a PR so it's easier to test? 😘
