### ISSUE TITLE
Progress test breaks local testing

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#3061]
## 🐛 Bug

this line, added in #2931 breaks local tests when you just run `pytest`, since it's expecting the viewer to be shown:

https://github.com/napari/napari/blob/712a96e27fc901d052abb37202d15ccf285b52f3/napari/_qt/_tests/test_progress.py#L161

(I'm guessing it worked for @DragaDoncila locally because that particular module shows things for linux as well?)

## To Reproduce

```
pytest napari/_qt/_tests/test_progress.py
```

## Expected behavior

should be able to run tests locally without setting CI=1

**Comment by DragaDoncila** [comment]
@tlambert03 thanks for flagging this. I've made a PR which I think should address this issue, but it would be great if you could review that and also run tests locally to make sure it has fixed it.
