### ISSUE TITLE
Set `use_enum_values` to False on EventedModel

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#3062]
## 🧰 Task
Assuming everyone is ok with it, we should remove `use_enum_values = True` from our EventedModel.Config.

this would make it so that internally, accessing the value of an Enum field on an EventedModel would give you the enum object itself (this is the pydantic default), rather than the string version.

This comes in handy when comparing a current value to its field default value.   It will be particularly annoying in settings to keep it as is.  For instance, #2933 added the first "proper" enum type to our settings... so checking whether the current `application.playback_mode` is the default value or not requires always doing some conversion (either that, or setting the default to a string, instead of an enum, which is also weird).

**Comment by andy-sweet** [comment]
I just ran into this morning and it confused me for a little while, so I'd be in favor of going ahead with this task.

If it's helpful, here are some test cases that all fail that help to demonstrate the weirdness.

```python
class TestMode(StringEnum):
    UNKNOWN = auto()
    SOME_MODE = auto()
    ANOTHER_MODE = auto()

class ModelWithStringEnum(EventedModel):
    mode: TestMode = TestMode.UNKNOWN

def test_evented_model_with_string_enum_default():
    model = ModelWithStringEnum()
    assert model.mode == TestMode.UNKNOWN

def test_evented_model_with_string_enum_parameter():
    model = ModelWithStringEnum(mode=TestMode.SOME_MODE)
    assert model.mode == TestMode.SOME_MODE

def test_evented_model_with_string_enum_setter():
    model = ModelWithStringEnum()
    model.mode = TestMode.SOME_MODE
    assert model.mode == TestMode.SOME_MODE
```

Comparing to the string values (e.g. `'some_mode'`) pass, which I can see as a convenient behavior, but not at the cost of comparing against the enum values.
