### ISSUE TITLE
Bringing back the example from the old napari homepage

### ISSUE THREAD

**Issue by willingc** [napari/napari#3085]
## 📚 Documentation

Hi @sofroniewn @kne42, 

I was at a conference this weekend and met a postdoc doing work on tumors at a Childrens Hospital. I wanted to show her a quick demo of napari that used to be on the landing page. The GIF/image of the cell was the one that I was thinking about. I eventually found something on the CZI website. 

I love the docs. Awesome job all around. 

If you point me in the direction of the old homepage, I would be happy to make a PR to the docs. :smile:

**Comment by sofroniewn** [comment]
Hi @willingc, we definitely want to bring the gallery back and thanks for offering to make a PR!

While the old homepage had custom made gifs that were committed directly to the repo, we want to now leverage juptyerbook/ sphinx to make autogenerated movies like vispy have done here https://vispy.org/gallery/scene/index.html as they will then both automatically be kept up to date and easily provide example scripts that folks can download.

It might be a little before we get to this, but we def want to get there soon at which point I can ping you again. I'm not sure what's best in the meantime - maybe @jni will have ideas too?

**Comment by willingc** [comment]
Got it! @sofroniewn I think even a static image with the cells and ui would be awesome during the transition.

Gallery will be so cool.
