### ISSUE TITLE
Use QDialog accept/reject instead of custom signals

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#3086]
## 🧰 Task
In looking through some settings stuff, I see this pattern being used in a few places, where a custom `valueChanged` signal is added to a `QDialog`, and emitted just before closing the dialog, based on whether the user clicked ok or cancel:

https://github.com/napari/napari/blob/d6bc683b019c4a3a3c6e936526e29bbd59cca2f4/napari/_qt/dialogs/qt_message_dialogs.py#L47-L59

usage example here:
https://github.com/napari/napari/blob/d6bc683b019c4a3a3c6e936526e29bbd59cca2f4/napari/_qt/dialogs/preferences_dialog.py#L191-L196

QDialogs run in `exec` mode (modal dialogs) already [have the concept of "accept" and "reject"](https://doc.qt.io/qt-5/qdialog.html#modal-dialogs), so this is reinventing the wheel a bit.  Instead of hooking up new internal signals to various potential outcomes, you can use the [`DialogCode`](https://doc.qt.io/qt-5/qdialog.html#DialogCode-enum) returned from the [`exec`](https://doc.qt.io/qt-5/qdialog.html#exec) method.

In this case, you can get rid of the whole `ConfirmDialog` class and do it with a single static dialog:

```py
ret = QMessageBox.question(
    None,
    "Dialog Title",
    "Are you sure you want to restore default settings?",
    QMessageBox.RestoreDefaults | QMessageBox.Cancel,
    QMessageBox.RestoreDefaults,
)
if ret == QMessageBox.RestoreDefault:
    _reset_widgets()
   # and then modify _reset_widgets to not take an event
```

cc @ppwadhwa

**Comment by sofroniewn** [comment]
I'm supportive of this change
