### ISSUE TITLE
Discussion to plan for re-directing keypress events

### ISSUE THREAD

**Issue by ppwadhwa** [napari/napari#3089]
Make plan for how to accomplish https://github.com/napari/napari/issues/3087.  Map out steps, understand changes needed, etc.

**Comment by psobolewskiPhD** [comment]
https://github.com/napari/napari/issues/3087 has quite a bit of discussion since this issue was opened. Given the lack of progress here, I'm going to close in favor of https://github.com/napari/napari/issues/3087.
