### ISSUE TITLE
Add debugging information for generated code

### ISSUE THREAD

**Issue by jni** [napari/napari#309]
## 🐛 Bug

**Note** I have no idea about what the below message means, but it seems useful.

I was just debugging an issue with `add_image`. When I got to the `add_image` function in the stack, the debugger gave me the following helpful message:

```
<no source code available>

> If this is generated code and you would like the source code to show up here,                               
  add it to linecache.cache, like

      import linecache
      linecache.cache[filename] = (size, mtime, lines, fullname)

  You can also set the attribute _MODULE_SOURCE_CODE in the module in which this function
  was compiled to a string containing the code.
```

This suggests a way to add debugging info to code generated by `add_to_viewer`. I don't know how hard/easy this is, and I don't consider it 0.1.0 material, but just wanted to add it here for tracking. (And anyway it was interesting and wanted to share! :smile:)

**Comment by lucyleeow** [comment]
Closing as I don't think this is relevant anymore cc @jni
