### ISSUE TITLE
NAPARI_CATCH_ERRORS=0 does not disable catching errors by Notification manager

### ISSUE THREAD

**Issue by Czaki** [napari/napari#3090]
## 🐛 Bug

NAPARI_CATCH_ERRORS=0 does not disable catching errors by Notification manager which does not allow to use of IDE integration during debugging.  

## Expected behavior

Use NAPARI_CATCH_ERRORS=0 should disable all caching methods (book installing own excepthooks) 

## Environment

napari: 0.4.10
Platform: Linux-5.11.0-25-generic-x86_64-with-glibc2.2.5
System: Ubuntu 21.04
Python: 3.8.3 (default, Dec 6 2020, 00:47:20) [GCC 10.2.0]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.21.1
SciPy: 1.7.0
Dask: 2021.07.0
VisPy: 0.7.3

OpenGL:
- GL version: 4.6.0 NVIDIA 470.57.02
- MAX_TEXTURE_SIZE: 32768

Screens:
- screen 1: resolution 2560x1440, scale 1.0
- screen 2: resolution 1920x1080, scale 1.0
- screen 3: resolution 1920x1080, scale 1.0

Plugins:
- PartSeg Analysis project: 0.13.7.dev9+ge4260d9.d20210727
- PartSeg Image: 0.13.7.dev9+ge4260d9.d20210727
- PartSeg Mask project: 0.13.7.dev9+ge4260d9.d20210727
- PartSeg Masked Tiff: 0.13.7.dev9+ge4260d9.d20210727
- PartSeg measurements: 0.13.7.dev9+ge4260d9.d20210727
- console: 0.0.3
- svg: 0.1.5
 - Please copy and paste the information at napari info option in help menubar here:

 - Any other relevant information:

## Additional context

If You agree I could prepare PR.

**Comment by tlambert03** [comment]
> does not allow to use of IDE integration during debugging.

yep, agreed.  PR would be great.

**Comment by Czaki** [comment]
> yep, agreed. PR would be great.

After check of code. Did you prefer to disable notification manager or only disable registration of `excepthook`?

**Comment by tlambert03** [comment]
I don't have a very strong opinion.  Whatever allows IDE debugging is most important.  but I guess the name itself `NAPARI_CATCH_ERRORS=0` implies that the excepthook itself should not be registered... what do you think?

**Comment by tlambert03** [comment]
> implies that the excepthook itself should not be registered

actually, I guess one tricky thing here is how to deal with the Qt abort.  i think the original intention of that env var was to toggle whether the exceptions appear in the gui or in the console... but if we disable the except hook altogether, a Qt exception will cause a full-on program exit.  is that what we want for IDE debugging?

**Comment by Czaki** [comment]
It is possible to do this without halting the program. I have access to such code.
