### ISSUE TITLE
Superqt installation issue

### ISSUE THREAD

**Issue by su2804** [napari/napari#3092]
## 🐛 Bug 
ERROR: Could not find a version that satisfies the requirement superqt (from napari[all])
ERROR: No matching distribution found for superqt

When I install napari using a git cloned repository it throws this error.
I also tried installing superqt using pip but it throws the same error.
## To Reproduce

1. Install napari by cloning the GitHub repository

**Comment by tlambert03** [comment]
strange... it's definitely on there: https://pypi.org/project/superqt/

can you tell me more about your system?  python version? os? etc...

**Comment by su2804** [comment]
Thanks for the reply. Here are the system details:

Python 3.6.8
macOS catalina

**Comment by tlambert03** [comment]
ah, ok.  Yeah, neither `napari` nor `superqt` support python 3.6 anymore.  Can you update?

**Comment by su2804** [comment]
That fixes it!
