### ISSUE TITLE
Additional option to tracks layer to display the tracks of subsequent time points.

### ISSUE THREAD

**Issue by JoOkuma** [napari/napari#3093]
## 🚀 Feature

Add a checkbox to allow seeing tracks independent of the current time point. Currently, we only display the tracks of previous time points.

## Motivation

This is useful to check where cells a migrating given a starting point and investigate other cell divisions behaviors.

## Pitch

I think it would be extremely useful to be able to toggle between seeing tracks from previous or every time point.

## Additional context

The checkbox would alter the behavior of [this method](https://github.com/napari/napari/blob/82ca467b515023a9ad6105cfbace9282f67be69c/napari/layers/tracks/tracks.py#L324-L334), maybe I could change its name as well.

**Comment by alisterburt** [comment]
this would be super useful! Rather than changing the time point, what do you think about the idea of 'two-tailed' tracks with one tail for previous time points and one for future time points? 

Visually, this might look more correct than just shifting the head of the track because the thickest part would be centered on the object of interest.

**Comment by quantumjot** [comment]
~~If I recall - you can just set the blending mode to opaque - that should show the whole track independent of time.~~ I take that back - I changed it so that it discards the vertices in the shader - so my suggestion won't work.

**Comment by JoOkuma** [comment]
@alisterburt And we would have two checkboxes, one for each direction?

It would tackle my use case because I just want to see both directions simultaneously.

For example, analyzing cell divisions:
<img src="https://user-images.githubusercontent.com/21022743/127357895-755a7e99-2e10-4208-950e-35241e0cdc13.png" width=50% height=50%>

**Comment by quantumjot** [comment]
What if you had a double slider for +ve tail length and -ve tail length? You could effectively show an arbitrary window of time (or whatever dim 0 represents).

**Comment by JoOkuma** [comment]
@quantumjot I think that's a great idea. I will work on it.
