### ISSUE TITLE
`ShapesData` not properly passed to magicgui function

### ISSUE THREAD

**Issue by alisterburt** [napari/napari#3095]
**Describe the bug**
Only the shapes layer data which was present when a layer was initialised is passed to magicgui when a function argument is decorated as `napari.types.ShapesData`.

**To Reproduce**
Run the following example, add a new shape interactively then hit the `print my shapes` button. Only the shape present upon layer initialisation will be printed. For a shapes layer which started empty, an empty list is returned.

```python
import napari
import numpy as np
from magicgui import magicgui

viewer = napari.Viewer()

x = np.linspace(0, 2 * np.pi, 28)
y = np.sin(x)
path = np.stack((x, y), axis=-1)

viewer.add_shapes([path], shape_type='path')


@magicgui(call_button='print my shapes')
def print_my_shapes(shapes_data: napari.types.ShapesData):
    print(shapes_data)


viewer.window.add_dock_widget(print_my_shapes)

napari.run()
```

**Expected behavior**
Shapes added to the layer after initialisation should also be passed to the magicgui function

**Comment by tlambert03** [comment]
hmm... I'm not seeing it.  napari and magicgui versions?

**Comment by tlambert03** [comment]
https://user-images.githubusercontent.com/1609449/127573089-6d57e7b4-33ea-420c-b45a-2bb9fb85d0fb.mov

**Comment by alisterburt** [comment]
Oh! In my dev environment I can't reproduce either, napari master and magicgui 0.2.9.

This came up in the context of working on a plugin, there I was on napari 0.4.10 and magicgui 0.2.10. Trying to recreate now but installing xcode seems to have borked my conda installation... this can probably be closed!

**Comment by sofroniewn** [comment]
@DragaDoncila can you give this issue a quick read over and see if you can reproduce or if it can be closed, this might be something you fixed not too long ago, thanks!!

**Comment by DragaDoncila** [comment]
Have given this a try and cannot reproduce. Not sure what the original issue was, but it's no longer present in the codebase. 

I think this can be closed for now.

**Comment by tlambert03** [comment]
yay!  best type of issue :)
