### ISSUE TITLE
Write document for options on building mamba/conda integration for bundled app

### ISSUE THREAD

**Issue by goanpeca** [napari/napari#3098]
## 🧰 Task

This task will provide a document summarizing the steps needed to provide initial support for conda/mamba on briefcase. This will also define the posible options on including this in the bundle. 

Topics to detail and coves

- napari installation in user space
- Plugin installation in user space
- micromamba vs mamba vs conda
- Briefcase work to allow
- Autoupdates
- App store
- Other app stores

**Comment by goanpeca** [comment]
Pinging @jaimergp

**Comment by jaimergp** [comment]
I am drafting a first version of this document!

**Comment by goanpeca** [comment]
I think we can close this for now
