### ISSUE TITLE
Consider making default shapes edge-color not black

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#3106]
## 🐛 Bug
The default edge-color of black doesn't work well with a default canvas color of black.
it looks like lines don't work:

https://user-images.githubusercontent.com/1609449/127573341-255a2f03-7459-4c97-90ad-1b0b4296c1a5.mov

**Comment by DragaDoncila** [comment]
Totally agree, I've run into this and it's pretty annoying because you have to select all the shapes and then change the edge colour - new users may not realize. Whatever we choose would obviously still have to work with the light theme where the canvas is white, so maybe a middle grey.
