### ISSUE TITLE
[discussion] Proposal for napari plugin manifest schema

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#3115]
## 🧰 Gathering input on new napari plugin schema

This task is for discussing ideas around a new static manifest proposal (see https://github.com/napari/napari/issues/2975 for original proposal).  This is very incomplete at the moment, we're still fleshing out ideas and welcoming input.

The primary benefits of a static manifest would be full "awareness" of what a plugin has to offer without having to import anything.  This is nice for multiple reasons:
1) startup-time and memory costs: Currently, we must import whatever `entry_points` a plugin declares in order to look for `@napari_hook_implementation`-decorated objects.  This leaves us at the mercy of the plugin developer to avoid costly imports in their entry point.  This is something that is already beginning to bite us.
2) declaration of functionality, even without installation.  `napari-hub` could use this to add rich metadata to plugin pages, and `napari` could in turn use that to "query the marketplace" for functionality that might help a user.  For example, rather than getting a "no plugin installed that can read that file" error, one might get a "no plugin installed... but there are extensions that can help."
3) visual UI representation of functionality without import.  Menus and submenus can be populated, keybindings declared, and "command-palette"s populate without _any_ python imports.  Plugins are only imported once a user requests functionality (by, for example, selecting a command from a menu, or using a declared keybinding).  (currently, we don't even have a good concept of how a plugin offers menus/submenus... this addresses that)

as a starting point, we're looking at the extension schema/mechanism used by VS Code, a program often praised for being "snappy" even with a lot of extensions installed.  Those interested are encouraged to have a look through [vscode's extension documentation](https://code.visualstudio.com/api).  In particular, the [Contribution Points](https://code.visualstudio.com/api/references/contribution-points) docs explains how a set of static (JSON) declarations can announce _all_ functionality provided by an extension, prior to "activation".  The contribution points with immediate napari parallels are:
- [`commands`](https://code.visualstudio.com/api/references/contribution-points#contributes.commands)
- [`configuration`](https://code.visualstudio.com/api/references/contribution-points#contributes.configuration) 
- [`keybindings`](https://code.visualstudio.com/api/references/contribution-points#contributes.keybindings)
- [`menus`](https://code.visualstudio.com/api/references/contribution-points#contributes.menus)
- [`submenus`](https://code.visualstudio.com/api/references/contribution-points#contributes.submenus)
- [`themes`](https://code.visualstudio.com/api/references/contribution-points#contributes.themes)
- [`productIconThemes`](https://code.visualstudio.com/api/references/contribution-points#contributes.productIconThemes)
- [`views`](https://code.visualstudio.com/api/references/contribution-points#contributes.views) (most like our widgets)

### npe2

I created a new repo to play around with these ideas: https://github.com/tlambert03/npe2 ... this is _temporary_.  It's unclear at this point whether this would be a major version bump of napari-plugin-engine, or a new plugin engine altogether

That repo has a pydantic model for the proposed plugin manifest schema.  **This schema is the thing that we most want feedback on**.  If you like looking at schemas/models as python objects in pydantic form, see [`schema.py`](https://github.com/tlambert03/npe2/blob/main/npe2/manifest/schema.py) as a starting point.  If you prefer looking at json-schema, see [`napari-schema.json`](https://github.com/tlambert03/npe2/blob/main/napari-schema.json) (which is autogenerated from the pydantic model.

For an example of a pyproject.toml that implements the schema, including a couple commands, menus, submenus, and keybindings...  see [`EXAMPLE/pyproject.toml`](https://github.com/tlambert03/npe2/blob/main/EXAMPLE/pyproject.toml)
(no widgets are in there yet, but they will be)

### Open questions
- [ ] Do we like the activate/deactivate pattern?
    - VS Code has plugins define a single required function (`activate()`) that serves the purpose of linking command `ids` from the static manifest to their actual function objects, and an optional "`deactivate()`" function where the plugin can add cleanup items if necessary.  This is a departure from our current model where we have _module_ that napari will inspect for decorated functions.  One advantage of the `activate` function is that it takes an argument (a "plugin context" object) that encapsulates a lot of stuff about the plugin – including what needs to be done to cleanup the plugin during deactivation.  I guess the major disadvantage is that it's a paradigm shift for us.  We should mock-up some examples with and without an activate/deactivate pattern.
- [ ] what exactly are the contributes (in addition to the ones above)
- [ ] where does the manifest live?  
    - `pyproject.toml` is typically used by devs for build-time (or perhaps develop-time) config.  But it isn't normally shipped with the sdist (see https://github.com/pypa/setuptools/issues/1632 for some discussion), and it would be even stranger to include in a wheel.  However, we definitely need this file to be included in both plugin sdists and wheels.  Is that inclusion strange enough that we should _not_ use `pyproject.toml` at all?  And perhaps just use `napari.toml` or `napari.yaml` instead?  (the entry point in the plugins `setup.cfg` would then point to this file).
- [ ] documentation-driven-development?   Not so much an "open question" but something we could definitely strive for.  This needs good docs, so we could even write the docs that we "want" to implement, and then implement it to match the docs.

**Comment by haesleinhuepf** [comment]
Hey @tlambert03 ,

thanks for your initiative! Great to see that :-)

Just a quick question: 

> Menus and submenus can be populated

Would it be ok if multiple plugins populate a similar / shared menu structure? E.g.

Plugin A:
* Segmentation
  * Algorithm A

Plugin B:
* Segmentation
  * Algorithm B

I'm asking because that would allow us to keep the first level in the plugins menu short and clearly structured. 

Best,
Robert

**Comment by tlambert03** [comment]
The plugins menu isn't the only menu that plugins can contribute to.  In the schema, napari declares menus that plugins can add to. So in this case napari would expose the `Segmentation` menu, and plugins could add to it. 

But, I think this is also a good case for the "analysis protocols" concept that we've been discussing.  So one could imagine "segmentation" being its own contribution point (functions that take an image and return labels), in which case the plugin itself wouldnt specify menu at all, it would just say "I've got a segmentation command for you"

**edit**:

> Would it be ok if multiple plugins populate a similar / shared menu structure? E.g.

To answer this another way.  The way menus work in this pattern is that napari declares a set of "top level" menus that can be added to.  (Like `command_palette`, `layers__context`, etc... in [this part](https://github.com/tlambert03/npe2/blob/ecc74e4ef77699924a5e79dc91b8cd0199518314/napari-schema.json#L158-L190) of the schema).  Commands/actions can appear in multiple menus.  This is how we could, for example, offer _both_ something like the `Analysis > Segmentation` menu that you're referring to here, have `Segment > ` appear as an option when right-clicking on an image layer in the layers list, _and_ have it appear in the command pallete when someone uses a hotkey then starts typing "segment...".  The important point here is a slight decoupling between the action itself (`Algorithm A` and `Algorithm B` in your example) and the  exact place(s) where it appears.

**Comment by haesleinhuepf** [comment]
> In the schema, napari declares menus that plugins can add to. So in this case napari would expose the `Segmentation` menu, and plugins could add to it.

Fantastic! That sounds exactly like what I was looking for 🌞

> have `Segment > ` appear as an option when right-clicking on an image layer

And that's even more exciting! 😍

I love the proposal! Let me know if I can help making it happen. And: no hurry 🙂

**Comment by DragaDoncila** [comment]
I've been meaning to comment on this for a while.

First, I love the proposal as a whole and much prefer the flexibility and control it offers plugin developers. In particular I love that we can know all the functionality provided by the plugin without having to first import it, as this could feed into some great features for the napari-hub as well.

One aspect I want to flag early on, which we've briefly discussed at dev meeting, is that this schema is potentially a significant step up in complexity/overhead for users who just want to quickly get started with a simple plugin. I think this can be mitigated in a couple of ways:
- clear documentation with both toy examples and fully fleshed out examples (maybe walking through well formed plugins?). Good documentation is always important but I feel here it is particularly critical.
- detailed comments in the cookiecutter template guiding users through the different parts of the schema (and its associated code)
- a VS code schema autocomplete extension

Another aspect I'm curious about here is - how will we ensure backwards compatibility with the existing system? If the plan is to not provide backwards compatibility, how can we best support existing developers to transition to the new infrastructure? @tlambert03 have you had any thoughts on this already?

**Comment by tlambert03** [comment]
thanks @DragaDoncila!  totally agree on all points, and currently feel optimistic that none will be big problems (and maybe even nicer UX ultimately)

> Good documentation is always important but I feel here it is particularly critical.

💯 ... I meant it when I said "documentation-driven-development" above! :)  One nice thing here is that we can lean very heavily on the example (and literally documentation structure) of VS Code, since we can see their docs [here](https://github.com/microsoft/vscode-docs).  I think we have the potential to come out the other side with docs that are much better than what we currently have.

> detailed comments in the cookiecutter template guiding users through the different parts of the schema (and its associated code)

I was kind of imagining that the main companion for the schema here would be less in-code comments, and more the html docs (like [here](https://code.visualstudio.com/api/references/contribution-points)) and ...

> a VS code schema autocomplete extension

💯 ... I've already made some toy examples of exporting a pydantic schema to json schema and then using it with a VScode extension like "[even better TOML](https://marketplace.visualstudio.com/items?itemName=tamasfe.even-better-toml)" or "[YAML](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml)" ... it's a dream.  

Ultimately, i think the combination of the IDE help/linting/autocompletion/docs in the schema, and a few prebaked tests in the cookiecutter will make the experience even less confusing than it currently is.  Tests in particular will be much easier to conceive (currently it's hard to write tests for plugins, this will make it easier).  With this sort of thing, the "github action test" that I've always wanted should be even easier.

> this schema is potentially a significant step up in complexity/overhead for users who just want to quickly get started with a simple plugin.

... so my hope is still that it will go the other direction in complexity.  (maybe less familiar at first, but i don't think much more complex).

>  how will we ensure backwards compatibility with the existing system? If the plan is to not provide backwards compatibility, how can we best support existing developers to transition to the new infrastructure?

probably by 
A) changing the entry_point name from `napari.plugin` to something else (`napari.manifest`?)
B) keeping the existing napari plugin engine as is... and making a new plugin package
C) writing a thin translation layer that converts "non-schema" based plugins to work with the new system
D) make a script that imports a current plugin and exports a manifest
E) using github search tools to track down/help stragglers

anyone plugin running tests with `napari_plugin_manager.register` (like [in the cookiecutter](https://github.com/napari/cookiecutter-napari-plugin/blob/94f8e454fdd047ea4bfe240f03742a94591e3d31/%7B%7Bcookiecutter.plugin_name%7D%7D/%7B%7Bcookiecutter.module_name%7D%7D/_tests/test_dock_widget.py#L12)) will see errors/warnings in their tests.

**Comment by Czaki** [comment]
From my point of view the main problem with current napari engine is lack of mechanism for shared state between multiple widgets other than global object. 

If I would like to try port PartSeg to be napari plugin it cannot be fitted in one widget (to keep clear interface). Also there is no need to spawn all "PartSeg" widgets every time. It will be nice to have option to provide some shared state Evented object which could be serialized on drive (to preserve state between sessions). 

So it will be nice to have some hook for providing such objects and some way to provide it to Widgets from different plugin hooks. Of course it may be provided by some field in the viewer but it may create some name collision. 

For me some inspiration may be fixtures from pytest?

**Comment by DragaDoncila** [comment]
> I was kind of imagining that the main companion for the schema here would be less in-code comments, and more the html docs (like [here](https://code.visualstudio.com/api/references/contribution-points))

Totally agree that the main companion should be properly formatted and categorized HTML docs. In-code comments can only do so much 😂  - I do still think it's worth at the very least having comments on, for example, the `activate` function of the cookiecutter template saying `# This function is connected to the viewer via the schema in pyproject.toml. See *link* for how to use this schema`. 

Essentially, I think wherever there is something new or seemingly disconnected/unfamiliar, we should have a comment in the cookiecutter template linking to where the user can learn more.
 
> ... so my hope is still that it will go the other direction in complexity. (maybe less familiar at first, but i don't think much more complex).

I completely agree - I don't think any of the concerns I've raised are reasons to back off at all. I just wanted to flag them as things I think are particularly important - and also would love to help out on!

> probably by
> A) changing the entry_point name from `napari.plugin` to something else (`napari.manifest`?)
> B) keeping the existing napari plugin engine as is... and making a new plugin package
> C) writing a thin translation layer that converts "non-schema" based plugins to work with the new system
> D) make a script that imports a current plugin and exports a manifest
> E) using github search tools to track down/help stragglers
> 
> anyone plugin running tests with `napari_plugin_manager.register` (like [in the cookiecutter](https://github.com/napari/cookiecutter-napari-plugin/blob/94f8e454fdd047ea4bfe240f03742a94591e3d31/%7B%7Bcookiecutter.plugin_name%7D%7D/%7B%7Bcookiecutter.module_name%7D%7D/_tests/test_dock_widget.py#L12)) will see errors/warnings in their tests.

Awesome, I think it's definitely worth the engineering effort to generate schemas for existing plugins if it's possible - while still supporting those users to migrate across to the new system, maybe even making PRs with the generated schema (but maybe that's a bit much)

**Comment by tlambert03** [comment]
✅
