### ISSUE TITLE
fix TypedList error throwing and add comprehensive test suite

### ISSUE THREAD

**Issue by kne42** [napari/napari#312]
- `List.__contains__` should handle all exception types
- `TypedList.index` should throw a `ValueError` instead of a `KeyError`
- comprehensive test suites should be added for all custom lists

as brought up in https://github.com/napari/napari/pull/306#issuecomment-497146532

**Comment by sofroniewn** [comment]
Note this no longer be needed after #1444 and followup PRs using the new evented list
