### ISSUE TITLE
Progress bar when loading multiple files

### ISSUE THREAD

**Issue by Czaki** [napari/napari#3125]
## 🚀 Feature

Progress bar when loading multiple files (for example from drag n drop)

## Motivation

When loading multiple files it will be nice to have some feedback information, not frozen interface. 

## Pitch

As there Is a great threading mechanism with the generator worker then loading data could be moved to separated thread, layers added live and progress bar in the interface.

**Comment by DragaDoncila** [comment]
I think we should be able to leverage the `progress` interface relatively easily to provide this feedback to the user - and I do agree we should move the opening of large files into a separate thread for usability.
