### ISSUE TITLE
Switch "master" to "main"

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#3128]
## 🧰 Task
GitHub now defaults new projects to use "main" instead of "master" - see https://github.com/github/renaming for context - and many projects like vispy and scikit-image have now switched to using "main".

There has been some discussion on the cookie-cutter of renaming see https://github.com/napari/cookiecutter-napari-plugin/issues/18 and https://github.com/napari/cookiecutter-napari-plugin/pull/20 and I think the time has now come for us to rename everything within the napari ecosystem.

How do @napari/core-devs feel about this? We can discuss at team meeting tomorrow. Thanks all!!

**Comment by justinelarsen** [comment]
I think it's a great idea! Thanks for suggesting it @sofroniewn

**Comment by kevinyamauchi** [comment]
Sounds good to me!

**Comment by tlambert03** [comment]
yep.  anytime!

**Comment by jni** [comment]
I think >50% of my projects now use main, and it's only going to increase going forward, so I'd very much like to make it 100% to give my muscle memory a chance to relax again. 😂

Advice for devs: once the switch happens, *delete your master branch locally*. I checked out master many times when skimage made the switch, only to realise later that my PRs were based off some ancient commit. 🤦

**Comment by GenevieveBuckley** [comment]
When we did this for dask-image, Julia had excellent instructions for what developers needed to do on their end locally. Here's the comment: https://github.com/dask/dask-image/issues/184

It was pretty straightforward. It involved:
1. (Admin only) Going into the repository settings on github and renaming the master branch
2. (Admin only) Find and replace "master" with "main" in the repository, and merge a PR. This tends to update the github actions CI workflows, and also instructions for new contributors (example here: https://github.com/dask/dask-image/pull/185/files)
3. (**Everyone who contributes**) Follow these instructions to update their branch names locally:
    ```
    git branch -m master main
    git fetch origin
    git branch -u origin/main main
    ```

**Comment by sofroniewn** [comment]
Ok great, thanks all for the support, and @GenevieveBuckley that guide looks great! I propose we do this sometime early next week. Say Tuesday August 10th. I'll post in the zulip too and give people a heads up
