### ISSUE TITLE
Feature: make mask from points with sizes

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#3132]
## 🚀 Feature
Similar to how we can convert shapes to masks, I'd like to be able to generate masks from a points layer with sizes.  In `skimage` my (probably very crappy) implementation is something like this:

(where the last column of `blobs` is the `size` parameter in the points layer)

```py
def blobs2mask(blobs, shape, grow=2) -> np.ndarray:
    """Create mask for `blobs` (coordinates, with radii) with `shape`."""
    from skimage import draw

    mask = np.zeros(shape, bool)
    for *c, r in blobs:
        coords = draw.disk(c[-2:], r + grow, shape=shape[-2:])
        if len(c) == 3:
            mask[c[0]][coords] = True
        else:
            mask[coords] = True

    return mask
```

**Comment by jni** [comment]
I mean, the fact that this draws in 2D only hurts my soul 😂😜, but other than that, 👍!

I *will* note that we are considering moving to size being a "visual attribute" that must always be derived from a property, but there are ways around this for the purposes of this feature, e.g. you could always access the derived values.

**Comment by tlambert03** [comment]
> I mean, the fact that this draws in 2D only hurts my soul 😂😜, but other than that, 👍!

I did warn you it was crappy! 😅

**Comment by sofroniewn** [comment]
@andy-sweet this could be a fun one for you - i'd look at the `Shapes.to_masks` and `Shapes.to_labels` functions here https://github.com/napari/napari/blob/4489e43c4d5162ddf3d3aa2eb73dc0cf9cfd6a79/napari/layers/shapes/shapes.py#L2765-L2809 for inspiration, there could be some utils we could resuse there. Might note be the most performant implementation, but could be a starting point

**Comment by andy-sweet** [comment]
I started working on this, but had some questions before I make any more progress.

1. Do we want this to work in n-dimensions? Or is 2D OK?
Based on @jni's soul, I assume n-dimensions.

2. Does `napari.layers.shapes.Ellipse` work with more than 2-dimensions?
From a quick look, I don't think it does. But if it does, or it's easy to make it do so, then a simple implementation is to transform each point to an `Ellipse`, create a `ShapeList` from those, call `ShapesList.to_masks()` and merge the results.

3. Is it sufficient to specify a `shape` for the output mask in `Shapes.to_masks`?
In general, I think about defining a reference space (i.e. with an origin, spacing, size, and maybe some other transforms) for the output (e.g. from a reference image), and filling in the pixels based on where the points are in that space. We can default to a zero origin and identity spacing. But if the more general use case here is to generate a mask from points layer using an image layer as a reference (i.e. the output mask has the same size as that image layer), then I think we want to handle the general case.

**Comment by sofroniewn** [comment]
> Based on @jni's soul, I assume n-dimensions.

I think that is the correct assumption 🤣 

> Does napari.layers.shapes.Ellipse work with more than 2-dimensions?

No, unfortunately I believe all that code is ultimately just 2D and works with the polygon approximation of each shape - eventually calling this code here
https://github.com/napari/napari/blob/3081a1f21136e3b61882cdd8f3c134ab22ef71a0/napari/layers/shapes/_shapes_models/shape.py#L358

> Is it sufficient to specify a shape for the output mask in Shapes.to_masks?

Hmm interesting, I'd probably just start with a shape, but I like your thinking there too!! Might be useful to have a little more flexibility
