### ISSUE TITLE
Bug in _QtMainWindow `window_position` on first resizeEvent

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#3137]
## 🐛 Bug
after #3075, the `resizeEvent` in `_QtMainWindow` seems a bit buggy, and I often find my window pinned in the upper left corner.

I haven't dug too deep, but a pretty repeatable way to see the problem is to open napari, open the console, then close napari.  I believe that the very first `resizeEvent` ends up appending a window position of `(0, -22)`, so if you save after two resize events, it saves that first incorrect window position.

cc @goanpeca

**Comment by goanpeca** [comment]
Thanks @tlambert03, will take a look.

**Comment by goanpeca** [comment]
@tlambert03 I cannot reproduce with the steps you mention 🤔

**Comment by tlambert03** [comment]
ok, thanks for looking.  fixed in #3196
