### ISSUE TITLE
Feature: accept RGB(A) tuple as colormap

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#3141]
## 🚀 Feature
Just as our `add/view_image()` function accepts a string "red" for the `colormap` value (meaning you want a colormap that goes from black to red), it should accept an RGBA tuple, meaning you want a linear colormap that goes from black to whatever color that is.

The alternative is to import either napari or vispy to create a colormap object manually (which means heavy dependencies for plugins is that's the only thin they're using it for)

originally mentioned in https://github.com/napari/napari/pull/2936#issue-679256433

**Comment by alisterburt** [comment]
agreed, seems like something we should add 👍🏼
