### ISSUE TITLE
Linux bundle build failing

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#3170]
## 🐛 Bug
I know it probably doesn't get used much, but we should either fix the failing Linux bundle build, or skip it for now, since it will make all of our master branch tests look like they're failing.    best I can tell from the [logs](https://github.com/napari/napari/runs/3331141461?check_suite_focus=true),  this might be an issue?
```
-- Running output plugin: appimage -- 
[appimage/stdout] Found appimagetool: /tmp/appimage_extracted_1cdfc4fa2d98741b846c2cf3d6a277cc/plugins/linuxdeploy-plugin-appimage/usr/bin/appimagetool
[appimage/stdout] 
[appimage/stdout] WARNING: appstreamcli command is missing, please install it if you want to use AppStream metadata
[appimage/stderr] Running command: /tmp/appimage_extracted_1cdfc4fa2d98741b846c2cf3d6a277cc/plugins/linuxdeploy-plugin-appimage/usr/bin/appimagetool "/home/runner/work/napari/napari/linux/napari/napari.AppDir" "-g"
[appimage/stderr] 
[appimage/stderr] appimagetool, continuous build (commit 8bbf694), build <local dev build> built on 2020-12-31 11:48:33 UTC
[appimage/stderr] More than one architectures were found of the AppDir source directory "/home/runner/work/napari/napari/linux/napari/napari.AppDir"
[appimage/stderr] A valid architecture with the ARCH environmental variable should be provided
[appimage/stderr] e.g. ARCH=x86_64 appimagetool ...
ERROR: Failed to run plugin: appimage (exit code: 1) 
Error while building app napari.
```

cc @ziyangczi, @goanpeca

**Comment by liu-ziyang** [comment]
Looking into this, hopefully I can address the issue along with ubuntu version upgrade

**Comment by goanpeca** [comment]
Pinging @jaimergp

**Comment by jaimergp** [comment]
I'm looking into this! @ziyangczi Should we sync? Ubuntu 16 doesn't ship a recent enough libssh I think. I am going to try with 18.04 and see if that fixes it. Is there any reason we are stuck with 16.04?

**Comment by liu-ziyang** [comment]
I have also been trying to upgrade it to ubuntu 20 if not 18, the problem is that the build process fails and it looks like there is some graphics issue with connecting to the virtual monitor when doing so.
