### ISSUE TITLE
Viewer creation bug in PyCharm's `PyDevConsole`

### ISSUE THREAD

**Issue by alisterburt** [napari/napari#3172]
## 🐛 Bug

Creating a viewer in the PyCharm `PyDevConsole` without explicitly starting an event loop (`%gui qt`) fails. 

```python
Python 3.9.6 (default, Jul 30 2021, 09:31:09) 
import napari
viewer = napari.Viewer()
```

```python
WARNING: WARNING: QApplication was not created in the main() thread.
```

The same example in normal ipython works flawlessly

## To Reproduce

1. Open the python console in PyCharm
2. Try to create a napari viewer
3. ☹️ 

## Expected behavior

Viewer should pop up and not block the console

## Additional context

I imagine a fix similar to that in #2905 will apply here, looking into it now

**Comment by alisterburt** [comment]
this is irritating - any attempt to add print statements/drop into a debugger to find out what's going on seems to fix the issue...

**Comment by alisterburt** [comment]
https://github.com/napari/napari/blob/0989e71cd31e05d8fef8c6a4022be8e71bbad72b/napari/_qt/qt_event_loop.py#L146

This failure mode happens with a viewer created here

being able to reproduce this seems to require
- starting the pydev console manually, not in a 'run configuration'
- typing the commands manually/copy and pasting (not accessing console history)


edit: giving up for the evening
QApp is created at the place marked above, program gets to 

https://github.com/napari/napari/blob/0989e71cd31e05d8fef8c6a4022be8e71bbad72b/napari/_qt/qt_main_window.py#L508

and everything still seems okay so I'm not sure when it actually crashes

**Comment by psobolewskiPhD** [comment]
Can any PyCharm users see if this is still a thing? 
CC: @melonora

**Comment by willingc** [comment]
This is a PyCharm bug @psobolewskiPhD: https://youtrack.jetbrains.com/issue/PY-75365/PyQt5-not-detected-in-Python-Console Closing here.

**Comment by willingc** [comment]
For folks that may experience this in the future, the best workaround is to use IPython in the PyCharm terminal to run the example above.

<img width="1426" alt="Screenshot 2024-11-16 at 2 00 23 PM" src="https://github.com/user-attachments/assets/4124ef6c-6584-446e-961a-ac1f14641436">
