### ISSUE TITLE
Labels colors sometimes mismatch between canvas and controls

### ISSUE THREAD

**Issue by DragaDoncila** [napari/napari#3174]
## 🐛 Bug

I found this bug while working on #3135. I don't believe the two bugs are related, as the behaviour of this one is quite different.

Briefly, shuffling labels colors eventually leads to a mismatch between the thumbnail/label spinbox color of a label, and the color displayed for that label on the canvas.

![labels_color_error](https://user-images.githubusercontent.com/17995243/129496945-0e24ddf9-6310-4752-aa93-a13bafab14b0.png)

When this mismatch occurs, entering `paint` mode on the layer causes napari to crash with this message shown in terminal:

```
WARNING: The X11 connection broke (error 4). Did the X11 server die?
WARNING:vispy:The X11 connection broke (error 4). Did the X11 server die?
``` 

Unlike in #3135, incrementing the selected label and then changing back doesn't fix the issue.

## To Reproduce

```python
import napari
import numpy as np

viewer = napari.view_labels(np.array([[1, 2]]))
napari.run()
```

1. Run the code above
2. Click shuffle on the labels layer until you see similar behaviour to the screenshot above (may be easier to notice if running using fix in #3173) i.e. layer controls/thumbnail don't match canvas
3. Click the `paint` button
4. napari crashes

## Expected behavior

- Colors match between layer controls and canvas
- Entering paint mode doesn't crash napari

## Environment

```
napari: 0.4.8rc6.dev144+g3c8c68c7
Platform: Linux-5.4.0-80-generic-x86_64-with-glibc2.17
System: Ubuntu 20.04.2 LTS
Python: 3.8.10 (default, Jun 4 2021, 15:09:15) [GCC 7.5.0]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.21.0
SciPy: 1.7.0
Dask: 2021.06.2
VisPy: 0.6.6

OpenGL:
- GL version: 4.6 (Compatibility Profile) Mesa 21.0.3
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1080, scale 1.0
- screen 2: resolution 1920x515, scale 1.0

Plugins:
- console: 0.0.3
- napari-ome-zarr: 0.1.1
- scikit-image: 0.4.8rc6.dev144+g3c8c68c7
- segmenter-2: 0.0.1
- segmenter: 0.1.dev6+gccf878d.d20210727
- svg: 0.1.5
```

I have also reproduced this bug on `0.4.10`.

**Comment by sofroniewn** [comment]
Huh funny, i wonder @DragaDoncila if you go back to `0.4.10` -> `0.4.0` if you can always see this bug or if you can find a PR which introduced it

**Comment by DragaDoncila** [comment]
@sofroniewn I'll do a bit more digging later today to narrow this down - just wanted to get the issue up while I was already in labels shuffling land

**Comment by DragaDoncila** [comment]
@sofroniewn I've gone back as far as 0.4.0 and have been able to reproduce the bug (mismatching colours between thumbnails and canvas) consistently for all releases (except 0.4.7 when shuffle was broken). I've reproduced on Mac as well. What's weird is I can no longer reproduce the X11 error, and was never able to reproduce it on the Mac, so maybe that was specific to my machine and is now gone. Regardless, I've not been able to reproduce any errors with painting.

I think next steps for this bug is someone else to reproduce and see whether they have any issues painting. If there's no issues with painting then I would class this as a low priority bug. It may even not be a "bug" necessarily, but an artifact of how `Qt` and `vispy` represent colors? I'm not familiar enough with either to draw a conclusion there.

**Comment by sofroniewn** [comment]
ok sounds like it might have always been bug, i might have seen it before, but definitely sporadically - let's keep an eye out though, and maybe other folks have noticed it too

**Comment by sofroniewn** [comment]
Looks like another user ran into this (see image.sc link above). Maybe we should revisit - cc @perlman @grlee77

**Comment by perlman** [comment]
I am unable to recreate replicate @DragaDoncila's example. (Yes,I hit the shuffle button many times. :-)

I initially thought that this might would be related to a quirk of the GLSL spec where division can be replaced with multiplication (see https://github.com/google/neuroglancer/issues/51). This seems to manifest itself on Intel integrated video cards versus discrete graphic cards, but I was unable to replicate with either.

I _am_ working through Loïc Sauteur's issue on forum.sc, and am able to reproduce when `num_colors>=~505`. I am digging in to see if there is a difference between the CPU code [label widget color] and the shader+texture [labels layer].

**Comment by perlman** [comment]
I believe this was fixed in https://github.com/napari/napari/pull/4321.
