### ISSUE TITLE
✨ Allow mapping of file extensions to plugin (to open them)

### ISSUE THREAD

**Issue by liaprins-czi** [napari/napari#3197]
### Overview of design need
- **Is there an existing GitHub issue this design work pertains to?** 
[Direct plugin-reader selection by extension #2686](https://github.com/napari/napari/issues/2686)

- **Also link to any specific comments or threads where the problem to be solved by design is mentioned**
[Talley's comment about allowing users to make plugin-to-extension mappings in the UI (one-to-many)](https://github.com/napari/napari/issues/2686#issuecomment-836772792)

- **In a sentence or two, describe the problem to be solved for users**
Allow users, via the UI to indicate certain extensions to always be opened by specified plugins. 
Consider also how to scale this to suggest plugins they don't have yet that could open extensions they try dragging in to open but that cannot be opened by napari default (and whether the suggestions should link to the hub?).
Look at pattern within Mac Os when opening files, how it allows you to choose to always open with a certain application.

### What level of design is needed? (Choose all that apply)
_This section may be updated by the designer / UX researcher working on this issue_

- [X] _(Maybe)_ **User experience research:**  high-level recommendation/exploration of user needs, design heuristics, and / or best practices to inform a design experience  
(Use this option when you feel there’s a challenge to be solved, but you’re curious about what the experience should be — may involve research studies to understand challenges/opportunities for design)
- [X] **information flow / conceptual:** organizing and structuring of information flow and content, including layout on screen or across multiple steps
- [X] **Visual:** creating mockups, icons, etc
(If choosing this level alone, it means that the content to be mocked up and its organization is already known and specified)

### Is design a blocker?
- [ ] **Yes:** engineering cannot proceed without a design first
- [X] **No:** engineering can create a first version, and design can come in later to iterate and refine

### T-shirt size
- [ ] ●○○○○ XS: able to be done in a typical workday or two
- [X] ●●○○○ S: able to do within one sprint, if also working on other things in the sprint
- [ ] ●●●○○ M: able to do within one sprint, if it is the sole focus
- [ ] ●●●●○ L: will likely take more than one sprint to complete, but less than two
- [ ] ●●●●● XL: a very large experience to be determined or overhauled, will need to be broken down further

**Comment by DragaDoncila** [comment]
This is now possible via the preference dialog, and the option is given when opening files with plugins. Going to close this now.
