### ISSUE TITLE
Thoughts re: adding `einops` as a dependency

### ISSUE THREAD

**Issue by alisterburt** [napari/napari#3199]
## What is `einops`, should we add it as a dependency?
This is an issue to gauge whether people would be okay with adding `einops` as a dependency in napari.

Writing vectorised code is great, but the same code can be quite hard to read (and maintain!). [einops](https://github.com/arogozhnikov/einops) is a library which provides [einstein-like notation](https://en.wikipedia.org/wiki/Einstein_notation) for rearranging, repeating and reducing multidimensional arrays. There are some [basic examples](https://github.com/arogozhnikov/einops/blob/master/docs/1-einops-basics.ipynb) and some [direct comparisons](http://einops.rocks/pytorch-examples.html) here so you can get a feel for the library.

Here is an example of some code I wrote recently implemented both with einops and numpy for reshape operations
```python
# generate a set of n oriented particles and m transformations
# we will apply m transformations, defined in the reference frame of the oriented particle, on the particles

n = 100  # number of particles
m = 5  # number of transformations

particle_positions = np.random.random(size=(n, 3, 1))
particle_orientations = np.random.random(size=(n, 3, 3))

transformation_shifts = np.random.random(size=(m, 3, 1))
transformation_rotations = np.random.random(size=(m, 3, 3))

# vectorise the rotation of n oriented points by m rotation matrices
# transformation rotations     (m, 3, 3)
# broadcastable rotations   (m, 1, 3, 3)
# particle orientations        (n, 3, 3)
# final orientations        (m, n, 3, 3)

# einops
broadcastable_rotations = einops.rearrange(self.rotations, 'm i j -> m 1 i j')

# numpy
broadcastable_rotations = rotations.reshape(-1, 1, 3, 3)

# calculate the final orientations
final_rotations = broadcastable_rotations @ pose.orientations

# vectorise the rotation of shifts to apply to particles
# transformation shifts        (m, 3, 1)
# broadcastable shifts      (m, 1, 3, 1)
# particle orientations        (n, 3, 3)
# oriented particle shifts  (m, n, 3, 1)
# particle positions           (n, 3, 1)
# final positions           (m, n, 3, 1)

# einops
broadcastable_shifts = einops.rearrange(transformation_shifts, 'm i j -> m 1 i j')
# numpy
broadcastable_shifts = transformation_shifts.reshape(-1, 1, 3, 1)

# orient the shifts 
oriented_particle_shifts = particle_orientations @ broadcastable_shifts

# calculate the final positions
final_positions = particle_positions + oriented_shifts
```

## Motivation
In the new geometry utilities, it would be good to vectorise vectorise a bunch of the functions we've written because some of these things will be called quite often. It might be nice to be able to use `einops` to make this more readable but before writing anything I wanted to get a feel for if people would be okay with adding a dependency like this

**Comment by sofroniewn** [comment]
The library looks to be pure Python - with no additional dependencies which is good.

The library looks like it's trying to support many different array libraries which is good, but one concern might be if it ended up limiting what types of arrays we could support (maybe not an issue though).

I'm not sure I love the `'m i j -> m 1 i j'` string style notation, to me it's harder to reason about and parse compared to the numpy syntax, but it's probably personal preference and frequency of exposure thing

Curious what others think?

**Comment by alisterburt** [comment]
Thanks for taking a look @sofroniewn - I think if you struggle to reason about the notation then it's reason enough not to use it. I had a similar thing with @brisvag when he switched to xarrrays within something we were working on, adding extra barriers is not something we want to do, I'll close this!

**Comment by sofroniewn** [comment]
Thanks for the consideration and suggesting it though - i will keep this on my radar, and at some point we could revisit if it looks like there is more of an uptake in this style of notation in the broader community
