### ISSUE TITLE
Git Flow

### ISSUE THREAD

**Issue by AhmetCanSolak** [napari/napari#32]
@AhmetCanSolak sure, happy for it to be questioned, but I'll point out that the SciPy "master-only" model came *after* Fernando Perez and others questioned whether git-flow was necessary, or just overhead. Many of these projects started out using git-flow then got to the point that dev could nicely act as master anyway. Specifically, if we have good test coverage and process, master should never be broken. dev to me seems to encourage breaking things.

I also don't like the sound of squashing everything in between releases. A clean history is absolutely critical for finding regressions and when things broke.

_Originally posted by @jni in https://github.com/Napari/napari-gui/pull/30#issuecomment-435512157_
-------------

Let me transfer this discussion to issue to keep PR away.

**Comment by AhmetCanSolak** [comment]
`dev` branch encourages breaking thins, it is true @jni . Indeed, that's the reason as @kne42 explained. We want to develop breaking things together and after having a release we may review our decision on this, for example if you will not have enough time to develop and want Napari to turn into a totally community project. 

Squashing is mandatory for contributors. You are right on that having a clean history is better. We want contributors to PR with smallest functional unit possible, without squashing it will be terribly hard for maintainers to review. This practice is also one of the important ones that followed by big open source projects in general. Maybe there will be totally different group of people maintaining the repository years later :)

**Comment by sofroniewn** [comment]
I agree with @jni, I prefer not to have an explicit `dev` branch. I think it will lead us to situations like we're in right now where things like the markers commit is on the `master` branch but the `dev` branch has a lot of the refactoring and slider. It would be much easier now to move forward and develop if it was all together on one branch.

Regardless we should be making sure that the `examples` continue to work on `dev` and `master` so that the early experience that @royerloic mentioned is preserved.

**Comment by royerloic** [comment]
I don't have a strong opinion about a dev branch as long as master is clean 
and all examples/demos work. I like the idea of using topic branches because
in my experience that has worked well -- but only if the branches are short lived.

@AhmetCanSolak @kne42  Let's give it a try and see how it goes. If it does not go
well we change. This project is young enough that we can try things and see how it goes.

**Comment by jni** [comment]
@royerloic this is the thing. If you only require master to work, but development happens in dev, and dev can be broken, then long lived feature branches are equivalent, but cleaner, and easier to maintain in the long term. Having a long-lived branch with many unrelated but not quite ready/broken changes is a recipe for maintenance disaster.

**Comment by royerloic** [comment]
agreed. Let's do it. I think it can work welll, maybe when the number of contributors is multiplied by ten we might have to reevaluate, or not. Let's see what @AhmetCanSolak and @kne42 say about it.

Also, in general, let's keep in mind that at such an early stage for the project, we should not be under the illusion that we can set things in stone... Everything can and must change.... Let's stay agile and be ready to change our minds as evidence surfaces... 

Also, I would like to see an emphasis now on getting things done versus getting lost in premature hair-splitting discussions... Right now we should move fast, add features, refactor regularly, revisit apis often, change our minds... Different project stages require different levels of 'entropy', right now we need lots of ideas and lots of entropy. Later, we can reduce the temperature and get very formal, conservative and put road-blocks on changes. 
(yes, I am using simulated annealing as an analogy here...)

**Comment by jni** [comment]
@royerloic absolutely, I am not aiming to set almost anything at all about Napari or its development in stone. In particular, I think the API should be completely changeable at any moment. However, I think the following three principles should apply now and forever:

- on master, tests (which we don't have now but should probably start to acquire... but I have zero experience in GUI testing, does anyone here know the best way to do it?), and demos should *always* pass.
- It is the responsibility of a PR's author(s) to ensure that all demos and tests remain valid even as they change an API. This scales.
- PRs to master/dev should not be merged before they are tested. For now, we can rely on trust that if the contributor says everything passes, it does. But the contributor should make this statement before any merge happens.

I agree that dev vs master could be seen as hair-splitting, but not if dev serves a different purpose to "master" in my principles above, in which case I think it's a questionable purpose. One of the twelve principles of agile development is "Working software is the primary measure of progress". I don't want to hold things up *unless* things are not actually working.

**Comment by kne42** [comment]
I agree with @royerloic and @jni that it’s probably too early/perhaps completely unnecessary to do this so we should merge and close the `dev` branch.

@jni As far as testing GUIs goes, I think it would be best to have a 3-stage testing suite:

1. Each computation-performing operation that can be compartmentalized should be. E.g. if we have a function that dynamically places a button in the layout we should separate the part where it determines the location from the part where it actually applies that to the button and test it separately.
2. There should be tests to check that all methods that modify internal attributes actually do this, especially if they modify inherited Qt attributes.
3. There should be a framework that screenshots the window whenever the GUI visually changes. A reviewer must manually mark the generated screenshots as valid after which they will be compared with future runs and automated.

Obviously the last one is probably too difficult/complex for right now but it should eventually be addressed.

**Comment by AhmetCanSolak** [comment]
As far as I observed, the concept of having both `master` and `dev` is not clear for us. 

Planned purpose of `dev` branch was to be the place where development happens. Individual developers fork project, create their future/fix branch on their fork and PR from their branch to our `dev`, where contributors expected to PR to our stable `master`.  Why so? Because we do not have a concrete design and/or specs. That's why we trust to the communication between developers during the development. This also brings a clean commit history of development on `dev` branch. Also keeping `master` as a stable source supports the git-based plugins of napari project and allows us to address people about the "working software" we built. Regular merges from `dev` to `master` would be useful to keep "working software" updated. Roughly, this was the intention behind the having both branches on the repository. By no means, we are obliged to stick this convention, i just wanted to make the motivation clear.

About feature branches, I think it so useful when you have more documentation prior to development, which is not the case for us, but even if we do not have detailed specs it is achievable. As @royerloic mentioned, we are in the early stages of the project and can try new things. While switching, we should decide well on how to sustain the stability of `master`.

**Comment by royerloic** [comment]
Ok, let's merge dev into master and go with until we change our minds...

About the git-based plugin system: we can also use version tags to mark 'good' commits to be used. In any case, once we start playing with the plugin system we will probably realise that there are tons of issues and things we have not thought of yet... let's see how it goes and stay agile.

**Comment by sofroniewn** [comment]
We have now settled into a pattern of PRs to master, with the occasional feature branch
