### ISSUE TITLE
Preferences dialog refactor followup

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#3206]
## 🧰 Task
#3178 got merged before I could address some of @ppwadhwa's points, so copying them here for followup.  Some of them point to interesting issues that we were sort of "working around", where the proper solution requires something beyond the preferences dialog:

> 1. On the experimental tab, if I select the octree settings, the async option is supposed to be disabled. It is not disabled right now.

@ppwadhwa, @sofroniewn ... can you guys remind me about the underlying thing we're trying to prevent here (i.e. if octree is on, does async have to be _on_ or off?).  Simply disabling a widget doesn't seem deep enough to me.  If there is some relationship between these settings, it should be declared as a validator on the settings model.  

> 2. For both the plugins tab and shortcuts tab, if I make a change, and then choose to restore defaults, the defaults are not reset on the plugins or shortcuts widgets until napari is closed and re-opened.

This one is because we have duplicated sources of truth: both the `plugin_manager` and the `settings` are trying to remember the call order.  Since there really isn't a true "default call order" (it's a side effect of plugin discovery order), if one clears the call order in the settings, you'd need to force a rediscovery to get back to the "default".  However, since that default order wasn't particularly meaningful to begin with, I don't see this as urgent to fix.

> ~3. For the plugins and~ keyboard shortcuts tabs, ~if I make a change and then click cancel, the change I made is not canceled--at least it doesn't appear to be in the widget. If I close and re-open napari, the old settings are there.~

~Also related to dual-sources of truth.  Definitely problematic... but the proper solution lives outside of the preferences dialog (which should be a relatively dumb widget that just shows/sets the settings... and does not try to manage the dual truth problem)~

> ~4. If I go to the plugins tab~ (or keyboard shortcuts tab),~ make a change, click cancel. Go back to the preferences dialog, click cancel (with or without the change), you will get a ValidationError.~

~I get this too: seems to be related to settings `schema_version` ... will try to handle on the settings model itself~

(these are now fixed by #3215 for plugins ... but not for keyboard shortcuts yet)

**Comment by sofroniewn** [comment]
> #3178 got merged before I could address some of @ppwadhwa's points, so copying them here for followup. 

My apologies here! Sorry for the early merge, and thanks for opening this up!!

> @ppwadhwa, @sofroniewn ... can you guys remind me about the underlying thing we're trying to prevent here (i.e. if octree is on, does async have to be on or off?). Simply disabling a widget doesn't seem deep enough to me. If there is some relationship between these settings, it should be declared as a validator on the settings model.

If octree is on then the async setting is ignored and the viewer automatically behaves async regardless of the async setting - the value doesn't actually matter

@tlambert03 do the above items need to be addressed before the `0.4.11` release?

**Comment by tlambert03** [comment]
> @tlambert03 do the above items need to be addressed before the 0.4.11 release?

I don't seem them as super critical.  they're all indicative of deeper problems.  but 1/3/4 shouldn't be too hard

**Comment by psobolewskiPhD** [comment]
Octree isn't a thing anymore and I can't reproduce the issue with shortcuts?

**Comment by psobolewskiPhD** [comment]
With 0.5.0 octtree is out  and not in the experimental settings. I also tested changing shortcuts and using reset to defaults and it worked as expected, so I'm going to close.
