### ISSUE TITLE
Button to expand layer properties

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#321]
## 🚀 Feature
Right now you need to double click the layer properties to expand then, but instead we could have a button that either pointed up or down to expand them. I think people would find this a more intuitive UI. Now that we've made the top part of the layer properties independent (in #314) we can easily add the button next to the layer name, and drop support for double clicking. Thoughts?

**Comment by jni** [comment]
imho we should add the button (with the sandwich icon), but keep double click anywhere else on the layer. I don't think double clicking hurts here.
