### ISSUE TITLE
napari freezes when napari-plot-profile gets started

### ISSUE THREAD

**Issue by haesleinhuepf** [napari/napari#3220]
## 🐛 Bug

Hi all, I'm observing this bug with napari 0.4.11rc0: When I start [napari-plot-profile](https://www.napari-hub.org/plugins/napari-plot-profile), napari freezes and crashes with no error message.

## To Reproduce

1. Start napari
2. Load an image
3. Click on Plugins > Measurements (Plot Profile): Plot Profile

https://user-images.githubusercontent.com/12660498/130471714-e3a90833-8390-4d98-8fe4-4bc9ffc78214.mp4

## Expected behavior

The plugin shows a Dock Widget (in 0.4.10 it worked nicely)

## Environment

 - Please copy and paste the information at napari info option in help menubar here:

napari: 0.4.11rc0
Platform: Windows-10-10.0.19041-SP0
Python: 3.8.5 (default, Sep 3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]
Qt: 5.12.9
PyQt5: 5.12.3
NumPy: 1.21.1
SciPy: 1.7.1
Dask: 2021.05.1
VisPy: 0.7.0

OpenGL:
- GL version: 4.6.0 NVIDIA 466.77
- MAX_TEXTURE_SIZE: 32768

Screens:
- screen 1: resolution 1920x1200, scale 1.0

Plugins:
- Measurements (Plot profile): 0.1.3
- Measurements (skimage regionprops): 0.1.6
- Search (Plugin): 0.1.0
- Segmentation (OCLRFC): 0.4.4
- Segmentation (split/merge): 0.1.2
- Utilities (skimage regionprops): 0.1.6
- Visualization(B/C): 0.1.1
- aicsimageio-in-memory: 0.3.5
- cellpose-napari: 0.1.3
- clEsperanto: 0.10.0
- console: 0.0.3
- napari-yapic-prediction: 0.1.dev99
- ome-types: 0.2.7
- omero: 0.1.1
- scikit-image: 0.4.11rc0
- svg: 0.1.5

 - Any other relevant information:

**Comment by tlambert03** [comment]
unable to repeat so far... will keep trying

**Comment by psobolewskiPhD** [comment]
Works for me as well on MacOS Big Sur 11.5.2
<img width="1612" alt="image" src="https://user-images.githubusercontent.com/76622105/130815059-aee089e2-936d-4f43-8d4a-d30e61ecc770.png">

I do get a warning when opening the Shapes layer:
```
/Users/piotrsobolewski/Dev/miniforge3/envs/TF-StarDist-napari/lib/python3.9/site-packages/napari/layers/shapes/shapes.py:2508: RuntimeWarning: divide by zero encountered in true_divide!
/Users/piotrsobolewski/Dev/miniforge3/envs/TF-StarDist-napari/lib/python3.9/site-packages/napari/layers/shapes/shapes.py:2508: RuntimeWarning: divide by zero encountered in true_divide!
```

Edit: BTW, I don't have that Blobs image in the Sample menu, even though all my plugins are listed as up-to-date.

**Comment by haesleinhuepf** [comment]
@goanpeca Similar to #3221, I can fix this issue when using pyqt5 5.15.4. The bug is reproducible in pyqt5 5.12.3. Thus, maybe the solution is to make sure that the right pyqt version gets installed with napari...

**Comment by tlambert03** [comment]
> The bug is reproducible in pyqt5 5.12.3. 

thanks again, great to know.

> Thus, maybe the solution is to make sure that the right pyqt version gets installed with napari...

same answer as https://github.com/napari/napari/issues/3221#issuecomment-905695092 ... we either have to support 5.12 fully or not at all, and not at all is not yet an option due to conda.  will dig deeper

**Comment by tlambert03** [comment]
OK, I see the deprecation warnings now on 5.12 ... I think the simplest solution here, for now, is to change your thread_worker implementation.  In this case, if you're only using the thread as a timer to trigger some main-thread computation every so often (i.e. [`update_layer`](https://github.com/haesleinhuepf/napari-plot-profile/blob/937ae492b465b72e8ba1ba732f1eac74d05ab99e/napari_plot_profile/_dock_widget.py#L88-L92)) ... then you should use a [QTimer](https://doc.qt.io/qt-5/qtimer.html) instead:

```py
from qtpy.QtCore import QTimer
...

        self.timer = QTimer()
        self.timer.setInterval(0.5)
        @self.timer.timeout.connect
        def update_layer(*_):
            if self.cb_live_update.isChecked():
                self.redraw()
            if not self.isVisible():
                self.timer.stop()
        self.timer.start()
```

I know that's not a totally satisfying answer, but it at least makes your plugin work with 5.12.

I agree with your comment though: that it should be a mouse_drag_callback instead of a constant polling function.  Can you elaborate on what difficulties you ran into there?

**Comment by tlambert03** [comment]
there's a type warning for the QElidingLabel in superqt that I can fix for 5.12 (we test 5.11 and 5.15 ... but I'll also start testing everything in between).  However, the vispy warning is not something we can fix as easily

**Comment by Czaki** [comment]
@tlambert03 QTimer takes time in miliseconds not second. Sou you should use 500 instead of 0.5

**Comment by haesleinhuepf** [comment]
Awesome, thanks @Czaki and @tlambert03! The timer works great, also with pyqt5 5.12.3 :-)

Feel free to close this issue if you feel like!

**Comment by haesleinhuepf** [comment]
> that it should be a mouse_drag_callback instead of a constant polling function. Can you elaborate on what difficulties you ran into there?

Sure. There you go: https://github.com/napari/napari/issues/3246
