### ISSUE TITLE
Remove extra search box on plugin dialog

### ISSUE THREAD

**Issue by goanpeca** [napari/napari#3232]
## 🚀 Feature

Now that plugin dialog is uniform in displaying packages on both installed and non-installed plugins, we could move to use a singe search box.

<img width="1192" alt="Screen Shot 2021-08-24 at 1 50 45 PM" src="https://user-images.githubusercontent.com/3627835/130673163-50f6d16f-c5d1-4d01-a6fb-2730770b3544.png">

## Motivation

Simplify UI :) 

## Pitch

No need for two separate boxes if we can filter using a single one #2345 

## Additional context

Thanks @Carreau for suggesting this on the dev meeting!

**Comment by goanpeca** [comment]
@tlambert03 commented 

>I wonder if the LineEdit should now on its own line above Installed Plugins, with a label that says "Search plugins" or something. (as it is, it looks like you'd be searching the installed plugins)

![napari](https://user-images.githubusercontent.com/3627835/130686792-ff932787-d92b-40a9-9f5e-fa8d68af84c5.gif)

@liaprins-czi I think indeed we might need to put the box in a different place to convey the right meaning. Thanks!

**Comment by liaprins-czi** [comment]
> we might need to put the box in a different place to convey the right meaning

This was my first thought as well. Is it possible to put it at the very top of the page for now, above the "Installed plugins" label?

In future I would like to examine the relationship between the search bar and the Install bar at the bottom. But this is a bigger issue.
