### ISSUE TITLE
This Windows version (6.3.9600) does not support the required bluetooth API.

### ISSUE THREAD

**Issue by bpavie** [napari/napari#3240]
## 🐛 Bug

Running napari from windows server 2012R2, I have got the following error:
![image](https://user-images.githubusercontent.com/1775952/130799950-59e0d48f-9eb8-470f-9744-65dc8c22f58f.png)

'This Windows version (6.3.9600) does not support the required bluetooth API.'

Looking on others projects, it looks to be a dependency (PyQT) issue (see similar error in https://github.com/GIS4WRF/gis4wrf/issues/103 ).
It looks like it could be avoid if 
`from PyQt5 import Qt`
is not done (`import Qt` imports all the modules including bluetooth which has issues on Win8.1 + PyQt5 >= 5.10)
(see https://github.com/spyder-ide/qtpy/issues/166 )

## To Reproduce

1. Install Napari
2. run it

## Expected behavior

Napari should start

## Environment

Windows server 2012R2
Python 3.8.10

## Additional context

Renaming the file D:\bin\napari_conda_env\Lib\site-packages\PyQt5\Qt5\bin\Qt5Bluetooth.dll to _Qt5Bluetooth.dll temporary fixed the issue.

**Comment by psobolewskiPhD** [comment]
We don't import from PyQt directly, instead use `qtpy` which appears to have resolved this in https://github.com/spyder-ide/qtpy/pull/143
Closing -- if this is still occurring, please open a new issue and provide `napari --info` output.
