### ISSUE TITLE
mouse_drag_callback on shapes layer does not fire while dragging

### ISSUE THREAD

**Issue by haesleinhuepf** [napari/napari#3246]
## 🐛 Bug

I was trying to implement a mouse-drag event on a shapes layer for [napari-plot-profile](https://www.napari-hub.org/plugins/napari-plot-profile). Goal was to plot intensities along the line while the user is dragging. I didn't manage to use the `layer.mouse_drag_callbacks` list. It does not fire while dragging and also not when releasing the mouse. (See video below)

## To Reproduce

1. Run the code below
2. Select the "Line" tool
3. Draw a line

```
import time
import matplotlib.pyplot as plt
from matplotlib.backends.backend_qt5agg import FigureCanvas
from skimage import measure
from skimage import io
import numpy as np
import os
import napari

viewer = napari.Viewer()

viewer.add_image(np.random.random((1000,1000)))


line_prof_layer = viewer.add_shapes(
    np.asarray([(100, 100), (200,300)]), shape_type="line", edge_color="red", name="Line Profile"
)

@line_prof_layer.mouse_drag_callbacks.append
def profile_lines_drag(shapes_layer, event):
    print("Drag", time.time())
```

https://user-images.githubusercontent.com/12660498/130849756-da5d39e6-8007-484e-913f-83ad4b66bedc.mp4

## Expected behavior

I'm expecting "Drag 1234456" output all the time while dragging, not just once after mouse-click.

## Environment
This bug already existed in napari 0.4.10

 - Please copy and paste the information at napari info option in help menubar here:

napari: 0.4.11rc1
Platform: Windows-10-10.0.19041-SP0
Python: 3.8.5 (default, Sep 3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]
Qt: 5.12.9
PyQt5: 5.12.3
NumPy: 1.19.5
SciPy: 1.7.1
Dask: 2021.05.1
VisPy: 0.7.0

OpenGL:
- GL version: 4.6.0 NVIDIA 466.77
- MAX_TEXTURE_SIZE: 32768

Screens:
- screen 1: resolution 1920x1200, scale 1.0

Plugins:
- Measurements (Plot profile): 0.1.5
- Measurements (skimage regionprops): 0.1.6
- Search (Plugin): 0.1.0
- Segmentation (OCLRFC): 0.4.4
- Segmentation (split/merge): 0.1.2
- Utilities (skimage regionprops): 0.1.6
- Visualization(B/C): 0.1.1
- aicsimageio-in-memory: 0.3.5
- cellpose-napari: 0.1.3
- clEsperanto: 0.10.0
- console: 0.0.3
- napari-features: 0.1.4
- napari-yapic-prediction: 0.1.dev99
- ome-types: 0.2.7
- omero: 0.1.1
- scikit-image: 0.4.11rc1
- svg: 0.1.5

 - Any other relevant information:

**Comment by tlambert03** [comment]
ah, this isn't that well documented... but the `mouse_drag_callback` decorator was designed expecting a generator (if you want it to fire while dragging) ... see the example [here](https://github.com/napari/napari/blob/master/examples/mouse_drag_callback.py), or try:

```py
@line_prof_layer.mouse_drag_callbacks.append
def profile_lines_drag(shapes_layer, event):
    yield
    while event.type == 'mouse_move':
        print("Drag", time.time())
        yield
```

does that work for you?

**Comment by psobolewskiPhD** [comment]
I use this method in my somewhat similar tool and it works perfectly, so it's odd it doesn't for you.
https://gist.github.com/psobolewskiPhD/025704ad8ec6991216e2899d82b68334
I've polished it slightly so you can just import it as a module and call
`profile_line(viewer)` 
where viewer is the name of your napari viewer (`viewer = napari.view_image(img)`)
As long as you don't delete the last line (or the first one) it works for my needs well. 
Updates on drag of the line or drag of vertex or slice change.
But don't delete the last line! I still need to fix that!

**Comment by haesleinhuepf** [comment]
> does that work for you?

I'm not 100%ly sure. In the code I posted above it obviously works. However, when I try to do this in my environment, I would like to use a class member function as callback. This doesn't work; or is at least not straightforward. [Here is the code](https://github.com/haesleinhuepf/napari-plot-profile/pull/10/files) and [there comes the error message](https://github.com/haesleinhuepf/napari-plot-profile/pull/10#issuecomment-905818149) when the event is fired.

Any hint is welcome. And no hurry. This doesn't need to be fixed before the 0.4.11 release :-)

**Comment by tlambert03** [comment]
> 100%ly

😆 

> This doesn't work; or is at least not straightforward. Here is the code and there comes the error message when the event is fired.

I think the issue there is that you're using the same callback for [two different types](https://github.com/haesleinhuepf/napari-plot-profile/pull/10/files#diff-fa5d7f298451227ac2b797c30aa04f641cf3a74e91fdf9f1fcd719de855e02c4R123-R124) of "connections".  

```py
layer.events.data.connect(self._data_changed_event)
layer.mouse_drag_callbacks.append(self._data_changed_event)
```

the `layer.events.data` connection is going to call your callback with a single `Event` object (where `event.value` will hold the current data of the layer), whereas the `layer.mouse_drag_callbacks` API expects a callback that takes two arguments (the `shapes_layer` and the mouse `event`).  Your `_data_changed_event` method _requires_ two arguments... so in this case, the mouse drag callback should work fine, but the `layer.events.data` signal is failing because it's only giving your `_data_changed_event` a single argument
(that's what the last little bit of your tracback is telling you).

don't connect `layer.events.data` to `self._data_changed_event` ... connect it directly to `redraw`:

**Comment by haesleinhuepf** [comment]
Thanks for the hint @tlambert03 it works like a charm for the `drag` callback like you suggested. I'm still struggling to make it work for the `move` callback, because when drawing paths, mouse button isn't down. See also #3226 . 

Thanks again and feel free to close this issue here!

**Comment by haesleinhuepf** [comment]
Has this been solved @kne42 ?
