### ISSUE TITLE
experimental_clipping_planes should accept a dictionary

### ISSUE THREAD

**Issue by kevinyamauchi** [napari/napari#3250]
## 🚀 Feature
I think the `Image.experimental_clipping_planes` setter should accept a single dictionary when a single plane is being defined.

## Motivation
I think the user should be able to pass just the dictionary defining the clipping plane when they want to add a single clipping plane.

## Pitch

If a valid dictionary (i.e., can be used to instantiate a Plane object), it is automagically wrapped in a `list`.

## Alternatives

Raise a `TypeError` with a clear explanation of what the expected type is.

**Comment by sofroniewn** [comment]
makes sense to me - cc @alisterburt

**Comment by alisterburt** [comment]
yep, agreed we should do this! cc @brisvag too
