### ISSUE TITLE
4.11rc2 Plugin window Installed panel not showing available plugin updates.

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari/napari#3251]
## 🐛 Bug

In Napari 4.11rc2 I am not seeing any updates to my installed plugins, even though I know there's new versions.
For example:
Installed: napari_plot_profile 0.1.3, but that's 2 versions out of date: both the hub and pypi show 0.1.5 available.
Installed: napari-pyclesperanto-assistant 0.9.10, while I know 0.10 has been released few weeks ago.
Installed: napari-skimage-regionprops 0.1.4, but 0.1.6 is the latest version on hub and pypi.
<img width="1192" alt="image" src="https://user-images.githubusercontent.com/76622105/130945121-f80dbf1f-41c4-42b8-bfc5-621fb4e8429b.png">

This is a regression, because this last one (`napari-skimage-regionprops`) I had in napari 4.10 in another conda env and there I was correctly shown that I can update to 0.1.6.
<img width="1192" alt="image" src="https://user-images.githubusercontent.com/76622105/130945200-9bcfe5fc-e2fa-43ea-bd3f-0a7dca048a1b.png">

If I *uninstall* the out of date plugin, then the Available pane will show me the correct latest version. Here's `napari_plot_profile` (4.11rc2)
<img width="1192" alt="image" src="https://user-images.githubusercontent.com/76622105/130945456-1e6d1648-17f3-493e-bbb5-92353fb9ab79.png">

## To Reproduce

1. Install napari 4.11rc2 using `pip install --pre napari -U`
2. Have an out of date plugin
3. Open plugin panel.

## Expected behavior

If a plugin is out of date, then the Installed Plugin listing should flag that and let me update, just like in 4.10.

## Environment

napari: 0.4.11rc2
Platform: macOS-11.5.2-arm64-arm-64bit
System: MacOS 11.5.2
Python: 3.9.6 | packaged by conda-forge | (default, Jul 6 2021, 08:51:19) [Clang 11.1.0 ]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.21.0
SciPy: 1.7.0
Dask: 2021.06.2
VisPy: 0.7.0

OpenGL:
- GL version: 2.1 Metal - 71.7.1
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1680x1050, scale 2.0

Plugins:
- 3 Utilities: 0.1.4
- 4 Measurements (skimage): 0.1.4
- StarDist: 2021.6.28
- aicsimageio-in-memory: 0.3.5
- aicsimageio-out-of-memory: 0.3.5
- animation: 0.0.2
- clEsperanto: 0.9.10
- console: 0.0.3
- ome-types: 0.2.6
- scikit-image: 0.4.11rc2
- svg: 0.1.5
- video

## Additional context

N/A

**Comment by goanpeca** [comment]
Ohhh dear, yes this is probably a side effect of when we moved from hook-specs to actual plugins in the installed plugins section of the plugin dialog.

I can take a look at this in a couple of hours @sofroniewn 

Thanks for the report  @psobolewskiPhD !

**Comment by sofroniewn** [comment]
Ok thanks @goanpeca - much appreciated!!

**Comment by psobolewskiPhD** [comment]
Not sure if related, but on 4.11rc2 some plugins don't show up to install?
Here's 4.11rc2, when I went to install `napari-plot-profile`
<img width="1192" alt="image" src="https://user-images.githubusercontent.com/76622105/131006803-a78d1d31-271d-4b9c-b251-9b36fc19da2a.png">
Also note it says 58 available.
Here's 4.10 in a different conda env:
<img width="1192" alt="image" src="https://user-images.githubusercontent.com/76622105/131006989-db9d3451-4b0e-43a5-b489-d9d982ee3073.png">

Notice it says 65 Available.

**Comment by sofroniewn** [comment]
Soon I think it would be nice to switch over to using the napari-hub open API endpoint that @ziyangczi has been working on. I know @codemonkey800 is interested in getting a little more involved in some of the napari Qt UI would, could be a fun thing for him to help out with too
