### ISSUE TITLE
clipping plane and plane rendering appear to not be aligned

### ISSUE THREAD

**Issue by kevinyamauchi** [napari/napari#3262]
## 🐛 Bug

When using the same plane parameters for a layer with a clipping plane and a layer with a slicing plane, they appear to not be aligned (see screenshot below).

<img width="1059" alt="Screenshot 2021-08-27 at 07 27 41" src="https://user-images.githubusercontent.com/1120672/131076586-1ad9b5ca-06fb-4ff9-8af5-8202514d1e26.png">

## To Reproduce

<details>
  <summary>Click to expand!</summary>
  
  ```python
import napari
import numpy as np


data = np.zeros((384, 513, 513))
data[100:300, 100:400, 100:400] = 1

plane_parameters = {
    'position': [ 87.35316989, 104.39580705, 296.60489348],
    'normal':  [0.56115536, -0.82554534, -0.05982944],
    'thickness': 5,
    'enabled': True
}

viewer = napari.view_image(
    data,
    experimental_clipping_planes=[plane_parameters],
    name='clipping plane'
)

plane_layer = viewer.add_image(
    data,
    experimental_slicing_plane=plane_parameters,
    rendering='translucent',
    colormap='magenta',
    name='slicing plane'
)

viewer.dims.ndisplay = 3
napari.run()


  ```
</details>

## Expected behavior

I would expect the planes to be coincident.

## Environment
napari: 0.4.11rc2
Platform: macOS-10.15.7-x86_64-i386-64bit
System: MacOS 10.15.7
Python: 3.8.11 (default, Aug 6 2021, 08:56:27) [Clang 10.0.0 ]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.21.2
SciPy: 1.7.1
Dask: 2021.08.1
VisPy: 0.8.0

OpenGL:
- GL version: 2.1 INTEL-14.7.17
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1440x900, scale 2.0

Plugins:
- console: 0.0.3
- scikit-image: 0.4.11rc2
- svg: 0.1.5

**Comment by kevinyamauchi** [comment]
It's a bit easier to see with a movie:


https://user-images.githubusercontent.com/1120672/131077060-52686e5c-a10a-4ee0-9c46-729f4e1ae9f9.mov

**Comment by alisterburt** [comment]
Oh wow, thanks for picking this up @kevinyamauchi ! Will have to have a thorough check of what's going on here

**Comment by brisvag** [comment]
It seems to be a shape-related issue. Things only break if the volume is non-cubic (we didn't do a great job at testing, it seems ^^').
