### ISSUE TITLE
outline viewing of labels layer

### ISSUE THREAD

**Issue by thanushipeiris** [napari/napari#3272]
## 🚀 Feature
Add a toggleable option for viewing the outlines of objects in the labels layer.
![image](https://user-images.githubusercontent.com/54516770/131237813-d4f7f9b0-ed71-47ab-a460-314165aafa99.png)

## Motivation
See the inside of each object really clearly while still identifying separate objects (using different label colours). 

## Pitch
User can press the "visible" icon next to the labels layer to toggle to a new option that shows the outlines only. So the toggle options for a layers layer would become: not visible -> visible -> outlines visible.

## Alternatives

I haven't looked at the visible toggle so it might be too tightly coupled to the visible property to make a non-breaking change. Could alternatively add a checkmark box on the layer controls.

## Additional context

Inspiration from the cellpose napari plugin that outputs these outlines of the segmentation: https://www.youtube.com/watch?v=Dzej2YDQM6Q
Screenshot was taken from this video!

**Comment by jni** [comment]
@thanushipeiris this actually already exists! 😅 Check out the "contour" option of the labels layer controls (see screenshot). I'll warn you though that it can be slow if your images are big.

<img width="1195" alt="Screen Shot 2021-08-29 at 3 53 05 pm" src="https://user-images.githubusercontent.com/492549/131240248-6dee52b1-db35-4e12-ac5a-881cf41119b2.png">

**Comment by thanushipeiris** [comment]
woooaaaaah okay I'll add this to the documentation 😆 Thanks for pointing it out!
