### ISSUE TITLE
Every change in theme now emits a warning from napari-console

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#3274]
## 🐛 Bug
pulling https://github.com/napari/napari/pull/3034#pullrequestreview-721014464 out of #3034 

every time you change themes now, you see a warning:
```
/Users/talley/miniconda3/envs/napdev/lib/python3.9/site-packages/napari_console/qt_console.py:161: FutureWarning: Themes were changed to use evented model with Pydantic's color type rather than the `rgb(x, y, z)`. You can get the old color by calling `color.as_rgb()`. The `as_dict=True` option will be removed in 0.X.X!
```

would be nice to fix that before release.  Yes this is a `napari-console` issue, but we include that by default, so posting this here for more visibility.  cc @sofroniewn, @lukasz-migas

**Comment by sofroniewn** [comment]
> would be nice to fix that before release. Yes this is a napari-console issue, but we include that by default, so posting this here for more visibility. cc @sofroniewn, @lukasz-migas

Yup agreed!

**Comment by sofroniewn** [comment]
Not sure if it needs a PR here or to napari console https://github.com/napari/napari-console

**Comment by sofroniewn** [comment]
@lukasz-migas any thoughts on what to do about this one?

**Comment by lukasz-migas** [comment]
@tlambert03 @sofroniewn Thanks for putting this here. I will push a fix to `napari-console`.

For the time being simple filterwarning will be ok and then in the future we can make it version dependent?

**Comment by sofroniewn** [comment]
> For the time being simple filterwarning will be ok and then in the future we can make it version dependent?

Yeah i think that's fine
