### ISSUE TITLE
✨ Interaction to allow user to toggle layers visibly

### ISSUE THREAD

**Issue by liaprins-czi** [napari/napari#3284]
### Overview of design need
- **Is there an existing GitHub issue this design work pertains to?**
[Viewer toggle mode #2166](https://github.com/napari/napari/issues/2166)
[Double click for layer control #1338](https://github.com/napari/napari/issues/1338)
 
- **In a sentence or two, describe the problem to be solved for users**
It would be useful to be able to compare image layers visually via a more expedient experience than the current method: "Currently, this can be achieved by first hiding all layers using the eye icon. Then one layer is made visible. To make another layer visible, the user will first hide the old layer, and then unhide the new layer. This process is not convenient as it involves a lot of mouse clicks."

### What level of design is needed? (Choose all that apply)
- [X] **User experience research:**  high-level recommendation/exploration of user needs, design heuristics, and / or best practices to inform a design experience  
(Use this option when you feel there’s a challenge to be solved, but you’re curious about what the experience should be — may involve research studies to understand challenges/opportunities for design)
- [X] **Information flow / conceptual:** organizing and structuring of information flow and content, including layout on screen or across multiple steps
- [ ] **Visual:** creating mockups, icons, etc
(If choosing this level alone, it means that the content to be mocked up and its organization is already known and specified)

### Is design a blocker?
- [ ] **Yes:** engineering cannot proceed without a design first
- [X] **No:** engineering can create a first version, and design can come in later to iterate and refine

If selecting **Yes**, how much design input is needed to unblock engineering? For example, is a full, final visual design needed, or just a recommendation of which conceptual direction to go?

### T-shirt size
- [ ] ●○○○○ XS: able to be done in a typical workday or two
- [X] ●●○○○ S: able to do within one sprint, if also working on other things in the sprint
- [ ] ●●●○○ M: able to do within one sprint, if it is the sole focus
- [ ] ●●●●○ L: will likely take more than one sprint to complete, but less than two
- [ ] ●●●●● XL: a very large experience to be determined or overhauled, will need to be broken down further

**Comment by tlambert03** [comment]
quick note, that comment from the original post about how this is currently done is true when restricted to mouse clicks, but the `v` (toggle visibility) key will let you do more.  for example: cmd-A (select all) -> v  will hide all layers. ... and v will toggle only the selected layers (so you can swap visibility with all or a subset of layers).  For mouse clicks though, we could add what photoshop has:

<img width="197" alt="Untitled" src="https://user-images.githubusercontent.com/1609449/131387068-6732c3ee-7de2-4354-be6b-f05ae6a5ba25.png">

and the "option-click"  which does some sort of cool toggling magic

**Comment by liaprins-czi** [comment]
Great, thanks for the heads-up about keybindings @tlambert03 !

**Comment by psobolewskiPhD** [comment]
So in https://github.com/napari/napari/pull/5574 I added a menu like the suggestion above:
<img width="288" alt="image" src="https://github.com/user-attachments/assets/930ede02-06a3-4a3d-9129-ad6795ea00e6">
In https://github.com/napari/napari/pull/5618 I added the option-click behavior referenced above.
And in https://github.com/napari/napari/pull/6590 I added arrow key bindings to show individual layers.
I think that across all of those, we can consider this closed?
CC: @jni

**Comment by jni** [comment]
Yup, I would close this
