### ISSUE TITLE
✨ Add ability for user to split / group layers from UI

### ISSUE THREAD

**Issue by liaprins-czi** [napari/napari#3292]
### Overview of design need
- **Is there an existing GitHub issue this design work pertains to?**
[Add split layer/ group layers shortcuts/ button #1543](https://github.com/napari/napari/issues/1543)
[Functions to split/combine multiple layers along an axis #1322](https://github.com/napari/napari/pull/1322) 

- **In a sentence or two, describe the problem to be solved for users**
Now that napari has the functionality for users to group layers, and then to split apart grouped layers, we should make it easier for them to do this from the UI.

### What level of design is needed? (Choose all that apply)
- [ ] **User experience research:**  high-level recommendation/exploration of user needs, design heuristics, and / or best practices to inform a design experience  
(Use this option when you feel there’s a challenge to be solved, but you’re curious about what the experience should be — may involve research studies to understand challenges/opportunities for design)
- [X] **Information flow / conceptual:** organizing and structuring of information flow and content, including layout on screen or across multiple steps
- [X] **Visual:** creating mockups, icons, etc
(If choosing this level alone, it means that the content to be mocked up and its organization is already known and specified)

### Is design a blocker?
- [ ] **Yes:** engineering cannot proceed without a design first
- [X] **No:** engineering can create a first version, and design can come in later to iterate and refine

If selecting **Yes**, how much design input is needed to unblock engineering? For example, is a full, final visual design needed, or just a recommendation of which conceptual direction to go?

### T-shirt size
- [ ] ●○○○○ XS: able to be done in a typical workday or two
- [X] ●●○○○ S: able to do within one sprint, if also working on other things in the sprint
- [ ] ●●●○○ M: able to do within one sprint, if it is the sole focus
- [ ] ●●●●○ L: will likely take more than one sprint to complete, but less than two
- [ ] ●●●●● XL: a very large experience to be determined or overhauled, will need to be broken down further

**Comment by tlambert03** [comment]
This was also added in the layer co text menu

**Comment by kevinyamauchi** [comment]
Hello @liaprins-czi ! Thanks for this issue. Since we are still working on layer groups (as far as I know), I have removed the "good first issue" label. Please feel free to re-add it if I misunderstood the goal of issue or the state of napari layer groups!

**Comment by tlambert03** [comment]
i don't think this is about what we've been calling layer groups, but rather about "stacking" and splitting layers. I'm not quite sure what more need to be done here, since you can do it from the layerlist context menu?

**Comment by liaprins-czi** [comment]
Hmm I do not actually remember anythign about making this issue now that it's been almost a year ago haha. But from context I can tell I created it as a design-specific issue in response to [#1543](https://github.com/napari/napari/issues/1543) where @sofroniewn said "we should add some GUI button or keyboard short cuts to split/ combine layers". I will reassign to @Lisa-CZI and @isabela-pf since they are focused on the viewer work now; but they can close if it seems like we don't need this.

But @kevinyamauchi I agree with removing the "good first issue" label, thanks!

**Comment by psobolewskiPhD** [comment]
I think this is solved by the layer list contextual menu split/merge.

**Comment by psobolewskiPhD** [comment]
Those layer list contextual menu actions for split/merge are now documented:
https://napari.org/stable/tutorials/fundamentals/viewer.html#right-click-menu
So going to close this.
