### ISSUE TITLE
✨ Window with list of all installed plugins is too short by default

### ISSUE THREAD

**Issue by liaprins-czi** [napari/napari#3304]
### Overview of design need
- **Is there an existing GitHub issue this design work pertains to?**
[Increase hieght of GUI listing all installed plugins #1302](https://github.com/napari/napari/issues/1302) 

- In a sentence or two, describe the problem to be solved for users
Even when only a couple plugins are installed, the window is too short to see them all. Ideally you could see at least 3-4 without needing to scroll.

To access the window: "Plugins" menu --> "List installed Plugins...". Plugins should be installed, though, to populate the space to get an idea of the problem described: 
1. From the “Plugins” menu within the napari application, select “Install/Uninstall Package(s)...”.
2. Choose a few plugins from napari-hub.org and search for the name where it says “Install by name/url…”.
3. Click the "Install" button.

### What level of design is needed? (Choose all that apply)
- [ ] **User experience research:**  high-level recommendation/exploration of user needs, design heuristics, and / or best practices to inform a design experience  
(Use this option when you feel there’s a challenge to be solved, but you’re curious about what the experience should be — may involve research studies to understand challenges/opportunities for design)
- [ ] **Information flow / conceptual:** organizing and structuring of information flow and content, including layout on screen or across multiple steps
- [X] **Visual:** creating mockups, icons, etc
(If choosing this level alone, it means that the content to be mocked up and its organization is already known and specified)

### Is design a blocker?
- [ ] **Yes:** engineering cannot proceed without a design first
- [X] **No:** engineering can create a first version, and design can come in later to iterate and refine

If selecting **Yes**, how much design input is needed to unblock engineering? For example, is a full, final visual design needed, or just a recommendation of which conceptual direction to go?

### T-shirt size
- [X] ●○○○○ XS: able to be done in a typical workday or two
- [ ] ●●○○○ S: able to do within one sprint, if also working on other things in the sprint
- [ ] ●●●○○ M: able to do within one sprint, if it is the sole focus
- [ ] ●●●●○ L: will likely take more than one sprint to complete, but less than two
- [ ] ●●●●● XL: a very large experience to be determined or overhauled, will need to be broken down further

**Comment by tlambert03** [comment]
this can be closed... that window doesn't exist anymore
