### ISSUE TITLE
unexpected chaining of `affine` and `scale` parameters in Viewer.add_image

### ISSUE THREAD

**Issue by grlee77** [napari/napari#3317]
## 🐛 Bug

When calling the `add_image` method of a Viewer, if both the `affine` as well as `scale`,`translation` and/or `shear` are specified the effects seem to be additive. This disagrees with the description in the `add_image` docstring:

https://github.com/napari/napari/blob/8f1126c82bfbabd6cafd9739fa8c747ddff79583/napari/components/viewer_model.py#L652-L653

(the description in the `_ImageBase` class also [says the same](https://github.com/napari/napari/blob/f1b3be15b33ddd141575d56dd315f5f5676c1d94/napari/layers/image/image.py#L93-L94))

After looking a bit at the code, it seems that the `Layer` class does indeed chain these transformations:
https://github.com/napari/napari/blob/f1b3be15b33ddd141575d56dd315f5f5676c1d94/napari/layers/base/base.py#L254-L268

And notably the `affine` parameter description on the `Layer` class does describe the current behavior accurately:
https://github.com/napari/napari/blob/f1b3be15b33ddd141575d56dd315f5f5676c1d94/napari/layers/base/base.py#L144-L145

Obviously one can work around this by only supplying one or the other so that there is not redundant information.

## To Reproduce

I noticed this when playing around with these arguments with a development version of the `napari.nibabel` plugin. If I set both, the slices from a single slice MRI scan appear much thicker in the slice direction than one would expect from the affine alone.

## Expected behavior

It sounds like we most likely just need to update some docstrings to match the current behavior. Is this correct? If so, I can make a PR for that.

## Environment

current Napari development branch (~0.4.11rc2)

**Comment by sofroniewn** [comment]
Ah I think @andy-sweet recently changed this behaviour to chain, but we might have missed a couple doc strings - can you @grlee77 update all doc strings and then maybe @andy-sweet can review. thanks!

**Comment by andy-sweet** [comment]
Yep, sorry, I must have updated the docstring in `base.py`, but not the duplicates in `image.py` or `viewer_model.py`.
