### ISSUE TITLE
Launching two viewers broken

### ISSUE THREAD

**Issue by jni** [napari/napari#3322]
## 🐛 Bug

Unfortunately I think this is a blocking regression for 0.4.11. The following script crashes on master without any error message:

```python
import napari

v1 = napari.Viewer()
v2 = napari.Viewer()

napari.run()
```

I traced the regression to #3034 07f35e652ca136de318eeac5d16717333fdbf432 with git-bisect. Unfortunately I don't have any ideas about how to fix it.

```
napari: 0.4.11rc3
Platform: macOS-11.4-x86_64-i386-64bit
System: MacOS 11.4
Python: 3.9.6 | packaged by conda-forge | (default, Jul 11 2021, 03:36:15)  [Clang 11.1.0 ]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.21.1
SciPy: 1.7.0
Dask: 2021.07.1
VisPy: 0.7.3

OpenGL:
  - GL version:  2.1 ATI-4.5.14
  - MAX_TEXTURE_SIZE: 16384
```

**Comment by sofroniewn** [comment]
I'm surprised this wasn't caught by any of our tests! I guess we don't have multi-viewer tests?

I'd like us to give fixing this a try @Carreau @goanpeca any chance you could give this one a look? Thanks!!

**Comment by sofroniewn** [comment]
I tried both
```
export NAPARI_EXIT_ON_ERROR=1
export NAPARI_CATCH_ERRORS=1
```

and i still just get an exit with no error message which isn't great! I'd hope those would keep working regardless of bug ... I'll keep looking

**Comment by sofroniewn** [comment]
maybe @nclack wants to dive into this one! just getting a stack trace/ error message would be a big help. it could be a trivial fix, it could be really tricky - no way to know right now. @lukasz-migas might also want to give it a try if he has time

**Comment by tlambert03** [comment]
it's failing because it thinks that ipython has the event loop in the call to `run()`... so it bails (and there's no error because that's not technically an error 🤪)

haven't figured out why yet... but it might have to do with updates to napari-console

_edit_: (it doesn't... same with console-0.0.3)

**Comment by tlambert03** [comment]
note, this is actually related to #2925 and #3033... (not sure what happened in #3034 to aggravate it)

**Comment by tlambert03** [comment]
lets try: #3328
