### ISSUE TITLE
pip install 'napari[all]' doesn't work on Windows 10 in some cases

### ISSUE THREAD

**Issue by kevinyamauchi** [napari/napari#3335]
## 🐛 Bug

@alisterburt and I were just running a workshop and some students on Windows 10 ran into some issues with the installation. They received an error when using `pip install 'napari[all]'`, but `pip install napari[all]` (i.e., no quotes) worked I believe they were using mini forge or Anaconda, but I forgot to clarify. We may want to consider updating the readme instructions to have a special case for windows vs. mac os + zsh

## Expected behavior

The README installation instructions should work on Windows 10

## Environment

 - Please copy and paste the information at napari info option in help menubar here:

 - Any other relevant information:

**Comment by goanpeca** [comment]
>We may want to consider updating the readme instructions to have a special case for windows vs. mac os + zsh

Agreed! Would you like to open a PR @kevinyamauchi ? :)

**Comment by tlambert03** [comment]
this is actually a duplicate of https://github.com/napari/napari/issues/2699
our instructions at `napari.org` actually specify double quotes `pip install "napari[all]"`, which I believe _does_ work on windows.  so we should switch our readme to match the napari.org instructions.  easy one

**Comment by goanpeca** [comment]
So can we close this? or we need to update single to double quotes somehwere?

**Comment by tlambert03** [comment]
> or we need to update single to double quotes somehwere?

the readme, as per @kevinyamauchi's original expectation: 

> The README installation instructions should work on Windows 10

**Comment by goanpeca** [comment]
Ahhh ok
