### ISSUE TITLE
`napari.Viewer()` breaks "stock" python REPL

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#3338]
## 🐛 Bug

Turns out that running `napari.Viewer()` from the vanilla python REPL doesn't work so well!  It enters a quasi-IPython state...

Obviously no one uses it like this much, but for debugging (particularly debugging stray object references) it's nice to be able to use the plain REPL sometimes.  So probably worth fixing.

## To Reproduce

```sh
❯ python
Python 3.9.6 | packaged by conda-forge | (default, Jul 11 2021, 03:36:15)
[Clang 11.1.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import napari
>>> viewer = napari.Viewer()
In :  # we're in IPython now!  (kind of)
```

unfortunately, using `exit` or `exit()` don't really work anymore (I think keyboard interrupt got me out)

**Comment by psobolewskiPhD** [comment]
I was having this happen in 4.10, but only when I activated the Napari console (or it was active in the last Viewer). See https://napari.zulipchat.com/#narrow/stream/212875-general/topic/Measuring.20shapes.20via.20keybind/near/246470750

This was *so annoying*—especially due to inability to exit without using `kill`—that it led me to switch my workflow from running code in the VS Code integrated terminal to using the interactive window—which I now quite like, so lemonade?

Can confirm it happens now in 4.11 *without* a Napari console active. Trying to <control>-c to break out, gives a traceback:
```
^C
Traceback (most recent call last):
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/napari-pyCL-D/lib/python3.9/site-packages/napari/_qt/qthreading.py", line 429, in wait_for_workers_to_quit
    def wait_for_workers_to_quit(msecs: int = None):
KeyboardInterrupt
```
Trying to `quit()` also gives a traceback—same as I had before:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/napari-pyCL-D/lib/python3.9/site-packages/IPython/core/autocall.py", line 70, in __call__
    self._ip.ask_exit()
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/napari-pyCL-D/lib/python3.9/site-packages/ipykernel/zmqshell.py", line 523, in ask_exit
    self.exit_now = (not self.keepkernel_on_exit)
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/napari-pyCL-D/lib/python3.9/site-packages/traitlets/traitlets.py", line 604, in __set__
    self.set(obj, value)
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/napari-pyCL-D/lib/python3.9/site-packages/traitlets/traitlets.py", line 593, in set
    obj._notify_trait(self.name, old_value, new_value)
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/napari-pyCL-D/lib/python3.9/site-packages/traitlets/traitlets.py", line 1217, in _notify_trait
    self.notify_change(Bunch(
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/napari-pyCL-D/lib/python3.9/site-packages/traitlets/traitlets.py", line 1227, in notify_change
    return self._notify_observers(change)
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/napari-pyCL-D/lib/python3.9/site-packages/traitlets/traitlets.py", line 1264, in _notify_observers
    c(event)
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/napari-pyCL-D/lib/python3.9/site-packages/ipykernel/zmqshell.py", line 467, in _update_exit_now
    loop = self.kernel.io_loop
AttributeError: 'InProcessKernel' object has no attribute 'io_loop'
```

**Comment by psobolewskiPhD** [comment]
BTW, is this new? I opened the Napari console, after launching napari from my VS Code Interactive Window:
```
Jupyter QtConsole 5.1.1
Python 3.9.6 | packaged by conda-forge | (default, Jul  6 2021, 08:51:19) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.25.0 -- An enhanced Interactive Python. Type '?' for help.

_rwho_ls = %who_ls
...: print(_VSCODE_getVariableTypes(_rwho_ls))
```
It knows variables I set in VS Code??!
```
In [15]: microns_per_pixel
Out[15]: [0.6484374633000588, 0.6484376743503157]
```
Seems the console may actually be quite useful, now that I'm not affected by this bug!
🤣

**Comment by Carreau** [comment]
> AttributeError: 'InProcessKernel' object has no attribute 'io_loop'

That's likely a bug in IPython/IPykernel, we don't have that many users of in-process kernels.
And indeed it only triggered when the console is opened.
I might be able to have in-process kernels that do less modifications of global state, but unfortunately there are some things that are globals (like sys.ps1, or display hooks.)

**Comment by Carreau** [comment]
https://github.com/ipython/ipykernel/pull/766 should at least avoid the errors. 

quit() / exit() still wont' work, this will be a bit more complicated though.

**Comment by tlambert03** [comment]
thanks @Carreau!

**Comment by tlambert03** [comment]
want to bump this... just tried again with the newest ipykernel and i'm still seeing this.  It's actually kinda problematic because it's often quite hard to interactively check garbage collection in IPython (it always seems to maintain references to objects that get cleaned up successfully in the regular python REPL).  so this bug makes it a lot harder to debug leaked object references.  @Carreau, do you have any insight as to why this is happening?

**Comment by psobolewskiPhD** [comment]
> BTW, is this new? I opened the Napari console, after launching napari from my VS Code Interactive Window:
> 
> ```
> Jupyter QtConsole 5.1.1
> Python 3.9.6 | packaged by conda-forge | (default, Jul  6 2021, 08:51:19) 
> Type 'copyright', 'credits' or 'license' for more information
> IPython 7.25.0 -- An enhanced Interactive Python. Type '?' for help.
> 
> _rwho_ls = %who_ls
> ...: print(_VSCODE_getVariableTypes(_rwho_ls))
> ```
> 
> It knows variables I set in VS Code??!
> 
> ```
> In [15]: microns_per_pixel
> Out[15]: [0.6484374633000588, 0.6484376743503157]
> ```
> 
> Seems the console may actually be quite useful, now that I'm not affected by this bug! 🤣

The above no longer happens with napari 0.4.15. The console opens blank.

However, the bug in the OP still happens for me. In vanilla `python` REPL when you launch napari, the console is functional and so is the REPL (you can use for example `viewer.camera.zoom = 2`, but it enters that wierd state where you can't close, etc. even after closing napari. `control-c` didn't help either. I had to make a new terminal and use `ps` to get the process and kill it.

**Comment by tlambert03** [comment]
can't reproduce on main with a fresh environment.  Maybe stuff got fixed upstream!

**Comment by psobolewskiPhD** [comment]
I still have this behavior with a pretty fresh env.
```
>>> import napari
>>> viewer = napari.Viewer()
```
from python REPL (3.9.12) opens napari (0.4.16) that has a functional console.
if you activate the console, closing napari and trying to use the REPL results the `In:` non responsive state (napari icon stays in dock).
Typically a few keystrokes (trying to exit) will result in a crash:
```
In : WARNING: Traceback (most recent call last):
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/apple-TF29/lib/python3.9/site-packages/superqt/utils/_qthreading.py", line 262, in await_workers
    @classmethod
KeyboardInterrupt
fish: Job 1, 'python' terminated by signal SIGABRT (Abort)
/Users/piotrsobolewski/Dev/miniforge3/envs/apple-TF29/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

Edit: just checked in a totally fresh env:
`mamba create -y -n test-env python=3.9 napari`
```
Python 3.9.13 | packaged by conda-forge | (main, May 27 2022, 17:00:33) 
```
napari 0.4.16 (live).
banging some more, sometimes the `In:` yields:
`<IPython.core.autocall.ZMQExitAutocall object at 0x283b4ae80>`
Maybe that helps? This time I could get a few commands in the `In:` (import numpy, random.rand).
It doesn't seem to crash spontaneously, but neither quit not exit work. At least now  `control-c` does work:
```
In : WARNING: Traceback (most recent call last):
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/test-env/lib/python3.9/site-packages/superqt/utils/_qthreading.py", line 262, in await_workers
    @classmethod
KeyboardInterrupt
WARNING:vispy:Traceback (most recent call last):
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/test-env/lib/python3.9/site-packages/superqt/utils/_qthreading.py", line 262, in await_workers
    @classmethod
KeyboardInterrupt
fish: Job 1, 'python' terminated by signal SIGABRT (Abort)
```

Edit2:
If you launch napari from regular REPL and *don't open the console* then everything is fine: you can use the REPL to add a layer, etc. But it's enough to click the console icon, not use the console, close it, and then the REPL breaks, even with napari open.

**Comment by ctrueden** [comment]
With python 3.10.4 + napari 0.4.15 on Linux, I observe:

* Starting napari via `napari.Viewer()` from plain Python REPL works.
* I can still use `exit()` to quit the Python REPL.
* But after using the napari console, typing `exit()` yields a new line reading: `In : ` (like an IPython console prompt, but with no number). Pressing ^D at this prompt quits the REPL successfully.

As an aside: for those <kbd>ctrl</kbd>+<kbd>C</kbd>-hungry people: I suggest trying <kbd>ctrl</kbd>+<kbd>D</kbd> first, because that sends EOF and will successfully terminate processes in some scenarios where <kbd>ctrl</kbd>+<kbd>C</kbd> would instead hang them. If <kbd>ctrl</kbd>+<kbd>D</kbd> doesn't work, *then* spam <kbd>ctrl</kbd>+<kbd>C</kbd> :laughing: 

All of that said, I imagine behavior here may be different on Windows and macOS.

**Comment by psobolewskiPhD** [comment]
The above is exactly consistent with my observations. And `ctrl-D` works nicely! Thanks!

**Comment by psobolewskiPhD** [comment]
Bump. this is still an issue, but I want to note that when using the stock REPL, one can keep entering commands in that window and they interact with napari. It works just like ipython/jupyter as far as I can tell—but not as nice obviously. For those two cases, we block the console from opening. Should we just do that for the stock REPL? 
Would prevent this bug from triggering and make it more consistent.
In this new world, the console would function when launched from a script or from the command line directly, but not from other interactive python envs.

**Comment by jni** [comment]
Hmm, I must say I'm surprised that you can still enter commands in the base REPL, but that's good! In that case I support #5350, that was my main concern.
