### ISSUE TITLE
API Proposal: rename Markers to Points

### ISSUE THREAD

**Issue by jni** [napari/napari#334]
To my ears Markers has always sounded a bit ambiguous: I don't know immediately what the data type is. Even though our Points have attributes (unlike mathematical points) such as size and colour, I think it is clearer and fits in better with Vectors and Shapes than Markers.

Happy to be outvoted here but just wanted to raise it before 0.1.

**Comment by sofroniewn** [comment]
I'm supportive - to me it makes it cleaner with `Vectors`. curious what others think. @kevinyamauchi 

Let's try and get as much of this major renaming done before `0.1`!!!

**Comment by AhmetCanSolak** [comment]
Agree with @jni from very first day i feel a friction with Marker naming but i thought it was a coined term for biological/medical image analysis community. Points seems more friendly to me.

**Comment by kevinyamauchi** [comment]
Sounds great! I can make the change.
