### ISSUE TITLE
Alpha doesn't work with depth setting in isosurface rendering

### ISSUE THREAD

**Issue by jni** [napari/napari#3343]
## 🐛 Bug

As @kevinyamauchi knows, I absolutely love his work in #3181. However, it has also ruined my workflow. :joy: 

Specifically, the way it currently works, *nothing* behind an object is currently rendered, *even if that object is transparent*. Here is code to reproduce the example:

```python
import napari
import numpy as np
from skimage import data, filters, morphology, segmentation
from scipy import ndimage as ndi

cells3d = data.cells3d()

viewer = napari.view_image(
    cells3d, channel_axis=1, name=['membranes', 'nuclei'], ndisplay=3
)
membrane, nuclei = cells3d.transpose((1, 0, 2, 3)) / np.max(cells3d)
edges = filters.scharr(nuclei)
denoised = ndi.median_filter(nuclei, size=3)
thresholded = denoised > filters.threshold_li(denoised)
cleaned = morphology.remove_small_objects(
    morphology.remove_small_holes(thresholded, 20**3),
    20**3,
)
maxima = ndi.label(morphology.local_maxima(filters.gaussian(nuclei, sigma=10)))[0]
markers_big = morphology.dilation(maxima, morphology.ball(5))

segmented = segmentation.watershed(
    edges,
    markers_big,
    mask=cleaned,
)

labels_layer = viewer.add_labels(segmented)
points_layer = viewer.add_points(np.transpose(np.nonzero(maxima)), size=2)

napari.run()
```

This results in the following display now, even on low opacity for the labels layer:

![pts0](https://user-images.githubusercontent.com/492549/132195781-36983256-85cd-4d8f-9df6-bd9e34359040.png)

The points are actually there, but can only be seen if the Labels layer is made invisible:

![pts1](https://user-images.githubusercontent.com/492549/132195889-fb0a8ea8-c641-4719-aef2-2bbb63da2931.png)

Whereas it used to look like this:

![pts2](https://user-images.githubusercontent.com/492549/132195934-1c76ac4a-31b6-4cd2-9915-0aff5b36d3b8.png)

It was always weird that the points would be "on top" of any previous layers, and messed with our perspective, but unfortunately I think the current behaviour is worse, in that transparency gives the impression that there is nothing "behind" a surface when in fact there is.

In the worst case, we can have a switch for setting depth or not during rendering.

**Comment by kevinyamauchi** [comment]
Ah, sorry about that @jni . This makes sense. I think the best fix is probably to have a switch to turn the depth checking on/off. Doing transparency + depth will be a lot more tricky.

I think we can use `set_gl_state(depth_test=False)` on the visual, but I am not sure if that will cause other issues. Do we want to tie it to the opacity value (i.e., turn of depth test for opacity < 1).

**Comment by jni** [comment]
> Do we want to tie it to the opacity value (i.e., turn of depth test for opacity < 1).

I kinda like this but it seems like a recipe for some *other* unforeseen problem. :joy:

**Comment by kevinyamauchi** [comment]
> I kinda like this but it seems like a recipe for some other unforeseen problem. 😂

For sure. This was my thought as well.

**Comment by kevinyamauchi** [comment]
I've thought about this a bit more and I am not sure that adding a `depth_test` flag is the right approach here. I made a small PR showing this approach (#3395). The issue with a `depth_test` flag is that we set `depth_test` when we set `blending` modes, so they can "fight" eachother.

I now think the best approach is to add another blending mode that is  the same as`translucent` with the exception that `depth_test=False`. For some context, here are the blending modes:

https://github.com/vispy/vispy/blob/585266c07a5d0f954523651ba20604bb49793b08/vispy/gloo/wrappers.py#L37-L52

What do you think, @jni?

**Comment by jni** [comment]
@kevinyamauchi I must say I'm rather agnostic here, but yes, I do have a slight preference to your second approach.

**Comment by kevinyamauchi** [comment]
> @kevinyamauchi I must say I'm rather agnostic here, but yes, I do have a slight preference to your second approach.

Sounds good. I'll make a PR with the second approach today and close #3395.

**Comment by brisvag** [comment]
Relevant discussions on vispy:
- vispy/vispy#2039
- vispy/vispy#2208

I *think* that the OIT PR is what we need to solve a lot of our problems (including how ugly antialiased borders are currently), but I tried my hand at it and it's really hard stuff. We need someone with more experience than me to pick it up, or asnt to find the time to work on it :)
