### ISSUE TITLE
Standardize platform architectures?

### ISSUE THREAD

**Issue by jaimergp** [napari/napari#3345]
## 🧰 Task

With the new naming scheme followed in the bundles (introduced by #3302), we suffix the zipname with `x86_64` on Unix and `amd64` on Windows. See [here](https://github.com/napari/napari/actions/runs/1201969002) for an example.

This is because we use `platform.machine()`, which does not try to canonicalize arch names across OSs, but instead [tries to return the most common vocabulary in each OS](https://bugs.python.org/issue7146). Do we want a consistent naming scheme here or not? I guess we only need to map AMD64 back to `x86_64` but happy to hear your thoughts.

**Comment by sofroniewn** [comment]
I'm afraid I don't have experience here, so I will defer to people more knowledgable than I
