### ISSUE TITLE
black --exclude in precommit being ignored

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#335]
## 🐛 Bug

Our precommit hook is ignoring our excludes in our `pyproject.toml` and reformatting our `_vispy` files. This is known behaviour as described here https://github.com/python/black/issues/395 (and other places referenced there in) and it seems like the solution is to move the excludes to the `.pre-commit-config.yaml` which I will try, but I wanted to flag here in case @AhmetCanSolak or @kne42 have any further thoughts

**Comment by sofroniewn** [comment]
Turns out you need the exclude in both the `.pre-commit-config.yaml` and `pyproject.toml` for our testing and precommit to both work. This is done now in #331

**Comment by kne42** [comment]
it was erroneously left in `.pre-commit-config.yaml` which has been overriding the `pyproject.toml`

**Comment by kne42** [comment]
oh nevermind just read the thread which is kinda dumb

**Comment by AhmetCanSolak** [comment]
thanks @sofroniewn
