### ISSUE TITLE
Long-term plans for pinned support package in Briefcase

### ISSUE THREAD

**Issue by jaimergp** [napari/napari#3360]
Writing this down here so we do not forget. Right now we are pinning the support package to previous releases so we can actually have a Python interpreter there we can use to run `pip`. This is just a patch, not a solution.

Ideally, we could either ask Briefcase to:

* Expose an option to bundle a full Python installation
* Implement a CLI forwarder so the main executable can take arguments like `sys.executable -m napari` or even run scripts.

*** 

_Originally posted by @goanpeca in https://github.com/napari/napari/issues/2965#issuecomment-871926379_:

@jni I asked Russell over the discord beeware channel

He said the following:

>Yes - a month or two back we made a modification to the way we package Python apps to get around some limitations with sandboxing in Big Sur.

>Big Sur wasn't very happy with the general approach of using a shell script as the "app", launching python as a second executable

>So - we now package a bootstrap app that is very similar to what happens on iOS - a C program that doesn't do much more than "start the Python interpreter"

>The downside is that fork-based subprocesses don't work any more, because there isn't a python interpreter (by default), and sys.executable is now hard coded to start a specific app.
(threads still work - it's only forks that are a problem)

>Option 1: Modify the stub app so it behaves like a "normal" python executable when it's called with python-like arguments (like -m), but behaves like the existing stub when it is given no arguments.
That would be the most generic solution - and it would also mean that fork-based processing would work again, because sys.executable would be a viable Python interpreter.

>Option 2: A custom Python support package that includes a python executable. We're currently explicitly removing bin/python from the support package because it isn't needed when the stub exists; but if you include it, you should be able to call it.

>(This very use case was raised earlier today by SpencerNewton - so there might be an argument to include the python binary as part of the default support package, and strip it as part of briefcase, with that stripping being an option that is enabled by default, but could be disabled by a project like Napari)

>Option 3: would be to work out how to invoke pip as an API - I know that's something that PyPA strictly advises against, but... it might still work :slight_smile:

So we have something to work with :)

**Comment by liu-ziyang** [comment]
Glad we don't have to explore this with conda packaging 😄
