### ISSUE TITLE
Layer list menu not using current theme

### ISSUE THREAD

**Issue by goanpeca** [napari/napari#3361]
## To Reproduce

1. Open napari
2. Change theme (toggle theme)
3. Add any sample image and right click on the layer
4. The menu will show the old theme not the current one

## Expected behavior

The layer list menu should follow the current theme

## Environment

 - Please copy and paste the information at napari info option in help menubar here:

 - Any other relevant information:

## Additional context

<img width="328" alt="Screen Shot 2021-09-08 at 4 20 09 PM" src="https://user-images.githubusercontent.com/3627835/132587295-d4e5a308-7fc4-43b7-9815-f72181ebc028.png">

**Comment by tlambert03** [comment]
that's only dark there because of your system theme right?  see my comment in https://github.com/napari/napari/pull/3362#issuecomment-915589178... I'm not immediately sure about this.

**Comment by psobolewskiPhD** [comment]
@goanpeca I think this is fixed by https://github.com/napari/napari/pull/5381
Can we close?

**Comment by goanpeca** [comment]
Sure thing!
