### ISSUE TITLE
Provide a preference to auto-match OS theme (light/dark)

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari/napari#3364]
## 🚀 Feature
I use automatic OS theming (macOS).
I'd **love** for Napari to be able to pick up on that and match the light/dark status to the OS theme.

## Motivation

For me, the overall brightness of my monitor affects my perception of what is on it. In a dark microscope room, my OS is in dark mode, I use dark-background LUTs, and Napari dark theme is sweet. In an office setting, my OS theme matches day/night. I use inverted LUTs (color on white) for images as appropriate to the lightning (day/night). In fact, it's super awesome that the napari theme can be easily checked! I use:
```
if self.viewer.theme == "light":
            colormap = "gray_r"
        else:
            colormap = "gray"
```
This way I can start off with a reasonable LUT and avoid the clash reported here: https://github.com/napari/napari/issues/3313

But I still have to manually set the napari theme morning/evening to match my OS, because it remembers prior theme—this is a blessing and a curse sometimes!

## Pitch

In an ideal world, I could set a Napari preference to auto-detect my OS theme and match it and also the *default* colormap would match as well (gray vs. gray_r).
(I'll settle for just the auto-theming though!)

## Alternatives

I've managed to get a bunch command line utilities and my R console (radian) to do it, by calling:
defaults read -globalDomain AppleInterfaceStyle
I've figured out that in python I can use `os.system` and `os.popen` to get that value of the theme, so I can actually set the napari theme programatically, but it's kinda annoying since it will still open "wrong" until I change it—I just don't need to go to the Preferences.

Edit2: Here's my trick in case someone else wants, fixed to actually catch `light` mode correctly, as it returns an error!
```
import os
test = os.popen('defaults read -globalDomain AppleInterfaceStyle &> /dev/null && echo dark || echo light')
theme = test.read().strip()
viewer = napari.Viewer()
viewer.theme = theme
```

## Additional context

N/A

**Comment by goanpeca** [comment]
We could use this https://pypi.org/project/darkdetect/

Or vendor it.. 

Thoughts @napari/core-devs ?

**Comment by sofroniewn** [comment]
i'm open, will be curious what others say though. i don't have strong feelings

**Comment by goanpeca** [comment]
I think the initial theme mockups combobox/boxes had a `Use system theme` and in this case, we would either use, dark or light by default (and this could be the default 🤷🏼 option?)

**Comment by tlambert03** [comment]
fine by me.  I also don't have strong feelings.  our dark/light themes aren't terribly well matched to the native dark/light themes, but it does feel like a nifty thing to have :)

probably a slight preference for vendoring `darkdetect`, and wrapping calls to `darkdetect.isDark()` in some exception handling just in case

**Comment by goanpeca** [comment]
Sounds good, will work on it.

Thoughts on making "Use system default" as the default @napari/core-devs ?

**Comment by tlambert03** [comment]
Hmm, I would probably immediately turn that off (and be annoyed every time i use `napari --reset` 😅 ) ...  so my preference would be no, but there too I'm happy to defer to others.
I feel like the light theme is much less attractive, and gets less attention.

**Comment by goanpeca** [comment]
>I feel like the light theme is much less attractive, and gets less attention.

Well.. that means we need to fix it :-p

**Comment by sofroniewn** [comment]
> Thoughts on making "Use system default" as the default @napari/core-devs ?

I'd probably still make "dark" the default, and then if folks want to enable use system default they can.
