### ISSUE TITLE
Traceback from WorkerBase `__getattr__` with some Qt versions

### ISSUE THREAD

**Issue by jni** [napari/napari#3366]
## 🐛 Bug

I don't have a *small* reproducible example yet, but I thought I'd post this in case the traceback alone makes sense to someone. You can also reproduce it with a plugin installation + some interactions, detailed below, but it's definitely not "minimal".

## To Reproduce

- install `platelet-unet-watershed` from PyPI.
- run this script:

```python
import napari
import numpy as np

viewer = napari.Viewer(ndisplay=3)
image_layer = viewer.add_image(np.random.random((2, 20, 512, 512)))

napari.run()
```

- Add the widget Plugins > platelet-unet-watershed > U Net Predict Widget

<img width="463" alt="Screen Shot 2021-09-10 at 7 15 41 pm" src="https://user-images.githubusercontent.com/492549/132831093-03d1bece-0278-4135-88a7-d7ec10de4155.png">

- click Run (the output is of course expected to be gibberish, but don't worry, you won't get that far. 😂)

## Actual behavior

This results in the following traceback:

```pytb
~/conda/envs/all/lib/python3.9/site-packages/napari/_qt/qthreading.py in create_worker(func=<function predict_output_chunks>, _start_thread=True, _connect={'aborted': <function predict_output_chunks_widget.<locals>.clear_volume>, 'returned': [<bound method UNetPredictWidget.add_watershed_wi...tainer (predict_output_chunks_widget: NoneType)>>], 'yielded': [<bound method Layer.refresh of <Image layer 'z-aff'>>, <bound method Layer.refresh of <Image layer 'y-aff'>>, <bound method Layer.refresh of <Image layer 'x-aff'>>, <bound method Layer.refresh of <Image layer 'mask'>>, <bound method Layer.refresh of <Image layer 'centroids'>>]}, _progress=None, _worker_class=<class 'napari._qt.qthreading.FunctionWorker'>, _ignore_errors=False, *args=(UNet(
  (d0): MaxPool3d(kernel_size=(1, 2, 2), s...el_size=(1, 2, 2), stride=(1, 2, 2), groups=32)
), <class 'numpy.ndarray'> (20, 512, 512) float32, (10, 256, 256), <class 'numpy.ndarray'> (5, 20, 512, 512) float32), **kwargs={'margin': (0, 0, 0)})
    613                         )
    614                     )
--> 615                 getattr(worker, key).connect(v)
        global getattr = undefined
        worker = <napari._qt.qthreading.FunctionWorker object at 0x1d8dc3ee0>
        key.connect = undefined
        v = <bound method Layer.refresh of <Image layer 'z-aff' at 0x1da2844f0>>
    616
    617     # either True or a non-empty dictionary

~/conda/envs/all/lib/python3.9/site-packages/napari/_qt/qthreading.py in __getattr__(self=<napari._qt.qthreading.FunctionWorker object>, name='yielded')
     98             # `pyqtBoundSignal` in PyQt)
     99             return getattr(self.signals, name)
--> 100         return super().__getattr__(name)
        global super.__getattr__ = undefined
        name = 'yielded'
    101
    102     def quit(self) -> None:

AttributeError: 'super' object has no attribute '__getattr__'
```

Complete traceback [here](https://gist.github.com/jni/b75dfb4d7294f7a9d1b946c8c419034b).

## Expected behavior

This should start running the deep learning inference pipeline on chunks on the array. In fact, you can see this happening with the instructions below!

```
conda create -y -n worker-yield-tb -c conda-forge python=3.9 napari
conda activate worker-yield-tb
pip install platelet-unet-watershed
python -c "import numpy; numpy.save('image.npy', np.random.random((2, 20, 512, 512)))"
napari image.npy
```

Then run the plugin as above. This time, you won't get the traceback! 🤯 (You *will* get a traceback from magicgui at the end, that's expected, fix is in unreleased magicgui.)

## Environment

```
napari: 0.4.11
Platform: macOS-11.4-x86_64-i386-64bit
System: MacOS 11.4
Python: 3.9.7 | packaged by conda-forge | (default, Sep  2 2021, 17:58:46)  [Clang 11.1.0 ]
Qt: 5.12.9
PyQt5: 5.12.3
NumPy: 1.21.2
SciPy: 1.7.1
Dask: 2021.09.0
VisPy: 0.8.1

OpenGL:
  - GL version:  2.1 ATI-4.5.14
  - MAX_TEXTURE_SIZE: 16384

Screens:
  - screen 1: resolution 2304x1296, scale 2.0
  - screen 2: resolution 1792x1120, scale 2.0

Plugins:
  - console: 0.0.4
  - nd2-reader: 0.0.6
  - platelet-unet-watershed: 0.0.1
  - scikit-image: 0.4.11
  - svg: 0.1.5
```

## Additional context

Additionally, whether running from a Python script or from the command line, I *always* get the traceback if I use PyQt from pip. This is recent-ish, because this was all working fine on Jul 1.

Anyway, I'm still investigating, all of this is partly for my own notes, but if something jumps out to @tlambert03 or @Czaki, for example, please let me know! 🙏

**Comment by Czaki** [comment]
I cannot reproduce in pip based environment.

**Comment by jni** [comment]
@Czaki what OS? This might be mac-specific. Personally I can't *not* reproduce in pip! :joy: Though I suspect I could with older PyQt, as noted in "additional context".

**Comment by Czaki** [comment]
Ubuntu 21.04

**Comment by tlambert03** [comment]
worked fine for me on the first try (cool to watch the watershed build 😄 )  will play with environment now.

btw, here's a script that avoid the manual interaction above:

```py
import napari
import numpy as np

viewer = napari.Viewer(ndisplay=3)
image_layer = viewer.add_image(np.random.random((2, 20, 512, 512)))
_, w = viewer.window.add_plugin_dock_widget('platelet-unet-watershed', 'U Net Predict Widget')
w.predict_widget()

napari.run()
```

**Comment by tlambert03** [comment]
@jni ... can you construct an environment from scratch that reproduces this?  (you can use whatever qt from any source you need...)  I can't reproduce it yet, but I assume it's an environment version/source thing

**Comment by jni** [comment]
@tlambert03 Here's my environment:

https://gist.github.com/jni/7f0e9106dbb390923f23b6802a132604

I'll clarify a little bit from above:

- running from the Python script, I always get the failure.
- running as `napari file.npy`, I don't get the failure with this environment.
- ~~if I `pip install -U pyqt5`, then it always fails~~ ... Aaaaand it fixed itself. 😂 But I still get the failure from your script (thanks, I always forget the syntax!):

```pytb
 $ python run-napari.py
Traceback (most recent call last):
  File "/Users/jni/projects/platelet-unet-watershed/run-napari.py", line 7, in <module>
    w.predict_widget()
  File "/Users/jni/conda/envs/all/lib/python3.9/site-packages/magicgui/widgets/_function_gui.py", line 285, in __call__
    value = self._function(*bound.args, **bound.kwargs)
  File "/Users/jni/projects/platelet-unet-watershed/plateseg/_dock_widget.py", line 93, in predict_output_chunks_widget
    worker = launch_prediction_worker(
  File "/Users/jni/conda/envs/all/lib/python3.9/site-packages/napari/_qt/qthreading.py", line 765, in worker_function
    return create_worker(
  File "/Users/jni/conda/envs/all/lib/python3.9/site-packages/napari/_qt/qthreading.py", line 615, in create_worker
    getattr(worker, key).connect(v)
  File "/Users/jni/conda/envs/all/lib/python3.9/site-packages/napari/_qt/qthreading.py", line 100, in __getattr__
    return super().__getattr__(name)
AttributeError: 'super' object has no attribute '__getattr__'
```

**Comment by Czaki** [comment]
Few things which I found @jni:

1) `QRunnable` does not have `__getattr__`  so this line https://github.com/napari/napari/blob/b9549fea3b79be993bd7398f227ff665f764c2f5/napari/_qt/qthreading.py#L100
should be replaced with 
```python
    raise AttributeError(f"{self.__class__.__name__} has no attribute {name}")
```

2) Base on log from first post we could see that object is `FunctionWorker`, not `GeneratorWorker` and getattr is called on `yielded`. So the core of problem is that `predict_output_chunks` from `platseg.predict` is recognized as function, not generator. In both logs which you post you use local copy of `platseg` with path `/Users/jni/projects/platelet-unet-watershed/plateseg/_dock_widget.py` Maybe You just comment a line 99 from this file?

**Comment by tlambert03** [comment]
makes sense, thanks!

**Comment by jni** [comment]
> Maybe You just comment a line 99 from this file?

... 🤦🤦🤦🤦🤦🤦 I friggin *had* done that. That explains the different behaviour in Python vs the command line napari call — I expect the latter does not add the current directory to the python path. Apologies for the noise!!!!

**Comment by Czaki** [comment]
> ... 🤦🤦🤦🤦🤦🤦 I friggin _had_ done that. That explains the different behaviour in Python vs the command line napari call — I expect the latter does not add the current directory to the python path. Apologies for the noise!!!!

this is a reason why I love `src` layout when create package.

**Comment by jni** [comment]
Very good point. Totally not common in Python-land but a very good point!

**Comment by tlambert03** [comment]
I like this article on it: https://hynek.me/articles/testing-packaging/

Definitely helps prevent some gotchas!

**Comment by jni** [comment]
"Another interlude from 2021: NASA landed another robot on Mars, and they use src directories in their Python code. My job here is done." :rofl: 

Yup that's very good. *Interesting!* Thank you both!

Now I wonder whether we should do something about it! :joy: In napari but also cookiecutter plugin etc...
