### ISSUE TITLE
Additive blending mode requires black canvas (broken in light theme)

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari/napari#3374]
## 🐛 Bug
Originally posted at napari-aicsimageio: https://github.com/AllenCellModeling/napari-aicsimageio/issues/22 

When using Light theme in Napari, the napari-aicsimageio plugin results in wierd behavior: drag-n-dropping a LIF results in a blank image, regardless of colormap, etc. 
However, switching to Dark theme shows that the image was properly loaded.
Light theme:
<img width="1546" alt="image" src="https://user-images.githubusercontent.com/76622105/132992458-01d18391-6c62-42a8-b7b7-973d40402597.png">

There is no error message.
Note that the tiny preview icon in the layer list does properly show the image.

Dark theme:
<img width="1546" alt="image" src="https://user-images.githubusercontent.com/76622105/132992463-0ce65f4b-63b2-4283-a1aa-30a1202c3d14.png">

## To Reproduce

Drag-and-drop a LIF onto napari with napari-aicsimageio v 0.3.3 or 0.3.5 in napari 4.10 or 4.11.
Change theme between Light and Dark.
Here's the smallest LIF I have handy:
https://www.dropbox.com/s/7201v0ae0f3iiy8/2021040_H33342_L929_24w_A3_tilescan.lif?dl=0

## Expected behavior

Image should be visible regardless of theme. 
Perhaps the colormap needs to be adjusted for optimal viewing, but it should not be a blank canvas.

## Environment

```

napari: 0.4.11
Platform: macOS-11.5.2-arm64-arm-64bit
System: MacOS 11.5.2
Python: 3.9.6 | packaged by conda-forge | (default, Jul 6 2021, 08:51:19) [Clang 11.1.0 ]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.21.0
SciPy: 1.7.0
Dask: 2021.06.2
VisPy: 0.7.0

OpenGL:
- GL version: 2.1 Metal - 71.7.1
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1680x1050, scale 2.0

Plugins:
- Measurements (Plot profile): 0.1.5
- Measurements (skimage regionprops): 0.1.6
- Utilities (skimage regionprops): 0.1.6
- aicsimageio-out-of-memory: 0.3.5
- animation: 0.0.2
- clEsperanto: 0.10.0
- console: 0.0.4
- ome-types: 0.2.6
- scikit-image: 0.4.11
- svg: 0.1.5

```

(Note: I also tested 4.10 and v. 0.3.3 of the plugin)

**Comment by kevinyamauchi** [comment]
Hey, @psobolewskiPhD ! Thanks for the issue. What happens if you switch the blending mode to translucent? It could be due to the additive blending (adding on top of white results in white).

If that is the case, I could still see this being considered a bug. I am not sure if the visuals in additive mode should be blended with the canvas background (although, I can't think of what the alternative behavior would be at the moment).

Edit: typo

**Comment by psobolewskiPhD** [comment]
Ok, in Light mode the new image layer is invisible in additive blending—the default, I've never set it I don't think. The other modes make it appear.
I'm not sure I understand how additive blending would result in pure white...
Edit: plus why does it work in Dark mode?
Also, should there be any blending with just one layer?
Edit: Is light mode canvas considered 255 255 255 so when additive it yields 255 255 255, while Dark mode is 0 0 0 so additive works? 🤯

**Comment by tlambert03** [comment]
> Is light mode canvas considered 255 255 255 so when additive it yields 255 255 255, while Dark mode is 0 0 0 so additive works? 🤯

exactly :)  it's already "saturated" with white in light mode... so white + anything is still white

> should there be any blending with just one layer?

yeah, I think we need to solve this independently of clever setting of blending anyway.  we don't want to have to go back and re-evaluate the blending of each layer as someone adds them to the viewer (so we shouldn't do anything "too clever" to determine the default blending mode when there is a single layer vs multiple layers).  See also #3353 (I think additive should be the default in most cases)

**Comment by psobolewskiPhD** [comment]
Just make the canvas in both light and dark neutral gray? 🤷 
Solves https://github.com/napari/napari/issues/3313 as well! 🤣

**Comment by tlambert03** [comment]
moving to "needs discussion".  This is a reasonably bad bug, but the solution isn't immediately obvious.  @kevinyamauchi, @alisterburt ... do you have thoughts on how we might solve this?  essentially, additive blending mode assumes we have a black starting point.  can/should we create a faux black background independent of the canvas color?  How do we even determine the boundaries for that background in canvas coordinates?

**Comment by kevinyamauchi** [comment]
I agree this is a tricky one. I will think about it some more, but I am not sure how to make additive blending work with a white background without more complicated rendering. I am just spitballing, but maybe rendering the scene with additive blending  and a background color like [0, 0, 0, 1]  or [0, 0, 0, 0] and then translucently blending that with a white background.

**Comment by nclack** [comment]
I like @psobolewskiPhD's suggestion to use a gray background by default for light mode.  See e.g. blender's [light theme](https://docs.blender.org/manual/en/latest/editors/preferences/themes.html).

When choosing the blending mode, are users mostly trying to control how layers composite together?  Different modes could be used for drawing most of the foreground vs compositing w the background.  That would require doing most of the rendering to a framebuffer (e.g. with additive blending), and then drawing the framebuffer in a separate pass (with "normal" alpha blending).

**Comment by jni** [comment]
I don't think gray solves anything, it just brings us closer to saturation. (I also don't love having gray outside of the image region... that would look weird eg when displaying non overlapping tiles, or points/shapes that might exist outside of an overlaid image.)

imho we should:
- make background independent of theme as suggested by @Czaki 
- use *subtractive* blending when using a white background. This should give pleasantly inverted images [like this one](https://twitter.com/christlet/status/1133729602696884224).

**Comment by psobolewskiPhD** [comment]
Yes! Light theme with invert-by-default LUTs would be :fire:!

**Comment by Czaki** [comment]
Canvas has `background_color_override` property added in #2270. Maybe it should be exposed to settings?

**Comment by psobolewskiPhD** [comment]
Switching the canvas to Black would solve the additive blending issue, but would make the Light theme look horrible, so it's not an ideal solution...

**Comment by Czaki** [comment]
For me, it looks ok (i use it in this mode).

**Comment by kevinyamauchi** [comment]
Hey everyone. I have a prototype of subtractive blending working and I have a couple questions about what we should do about the colormaps.

https://user-images.githubusercontent.com/1120672/147909940-cd52f300-d1c7-4cc4-977b-1c420c58a6dd.mov

As @jni mentioned above, subtractive blending "inverts" the colors. For example, the magenta colormap appears green since it is being "subtracted" from the white canvas:

```python
canvas = [1, 1, 1]
magenta = [1, 0, 1]
magenta_sub = canvas - magenta
magenta_sub
>>> [0, 1, 0]
```
1. Do we want to create extra colormaps that "correct" for this (e.g,. `*_sub` colormaps)? For example, we could make the magenta_sub colormap go from [0, 0, 0] -> [0, 1, 0], which would appear to go from white to magenta in the subtractive blending mode.
2. Do we want to automagically swap in the corrected colormaps when in light mode with subtractive blending? I am leaning against this as it feels too magical. Instead, I am in favor of some clear explanatory docs for blending.

Does it seem worth it to make a small PR to add the subtractive blending mode?

**Comment by Czaki** [comment]
> Do we want to automagically swap in the corrected colormaps when in light mode with subtractive blending? I am leaning against this as it feels too magical. Instead, I am in favor of some clear explanatory docs for blending.

What happens if we subtract multiple reversed colormaps? It will produce a similar effect that in the additive mode for not reversed?

**Comment by alisterburt** [comment]
Super cool @kevinyamauchi !

This seems like an interesting workaround which allows us to achieve the visual effect that we want (additive on white backgrounds) rather than the actual solution (separation of rendering and compositing as @nclack suggested)

Given that it's a workaround rather than what we'd ideally have, I'm supportive of a bit of magic to make it feel normal. I'd like to know the answer to @Czaki's question

Another path we could consider... using subtractive and the subtractive colormaps in place of additives when the background is white, does this feel better/worse to you?

**Comment by psobolewskiPhD** [comment]
That looks sweet @kevinyamauchi 
There's an apropos thread on image.sc regarding inverted LUTs and compositing multichannel images. The whole thread has a lot of info and examples:
https://forum.image.sc/t/multi-channel-composite-view-with-inverted-luts-in-imagej-fiji/61163
And starting about here some discussion of subtractive blending:
https://forum.image.sc/t/multi-channel-composite-view-with-inverted-luts-in-imagej-fiji/61163/23?u=psobolewskiphd

**Comment by alisterburt** [comment]
Thanks @psobolewskiPhD, that thread is super useful! It seems that subtractive blending with inverted colormaps does change the way different colours interact so we definitely shouldn't do what I suggested above

**Comment by kevinyamauchi** [comment]
Thanks for the links to the thread, @psobolewskiPhD ! Very useful.

> Thanks @psobolewskiPhD, that thread is super useful! It seems that subtractive blending with inverted colormaps does change the way different colours interact so we definitely shouldn't do what I suggested above

Agreed. As nicely shown in that thread, the colors interact are composed differently in additive and subtractlive blending. Thus, I don't think we should automatically swapping colormaps or blending mode.

> What happens if we subtract multiple reversed colormaps? It will produce a similar effect that in the additive mode for not reversed?

If we compose multiple layers with different colormaps in subtractive blending mode on a white background, the behavior is similar to additive blending on a black background, but there are some subtle differences as shown in the thread linked by @psobolewskiPhD . The example I posted above is two layers with subtractive blending. I will make a PR later today so you can play around with it.
