### ISSUE TITLE
Naming convention on _window component

### ISSUE THREAD

**Issue by AhmetCanSolak** [napari/napari#338]
## 📚 Documentation

I realized name of the file with Window class is view :D 

`napari/napari/components/_window/view.py`

is there a specific reason for such naming that im missing? or just a not-refactored-yet problem?

**Comment by sofroniewn** [comment]
we were going for a system where every model file was named `model.py` and every Qt view file was named `view.py` inside a folder with the name of the component, like `_window` or `_dims`. If this leads to confusion we can discuss changing it, but it was intentional

**Comment by AhmetCanSolak** [comment]
for rest it was okay, maybe not having a model but view kind of confusing

**Comment by sofroniewn** [comment]
this file is now named `qt_main_window.py`, which i think is much more clear
