### ISSUE TITLE
Misleading error when certifi package is missing

### ISSUE THREAD

**Issue by rkspsm** [napari/napari#3383]
## 🐛 Bug

I am using Arch Linux OS, and I installed napari[pyqt5] using pip (user local installation). When I started the basic program which creates a viewer and calls napari.run(), it shown me error that QApplication is not created. I am experienced with PyQt5, and I understand that its a very trivial issue to exist as a bug. After sometime searching in the code I realized that I was missing the "certifi" package, which is not even listed as a dependency.

After I installed certifi, it worked flawlessly.

## To Reproduce

1. Install napari[pyqt5].
2. Uninstall certifi package.
3. Launch any napari app (any basic tutorial app will do).

```
import napari
v = napari.Viewer()
napari.run()
```

## Expected behavior

The napari Viewer should open.

## Environment

napari: 0.4.11
Platform: Linux-5.14.3-arch1-1-x86_64-with-glibc2.33
System: Arch Linux
Python: 3.9.7 (default, Aug 31 2021, 13:28:12) [GCC 11.1.0]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.20.3
SciPy: 1.6.2
Dask: 2021.09.0
VisPy: 0.8.1

OpenGL:
- GL version: 4.6.0 NVIDIA 470.63.01
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1080, scale 1.0

Plugins:
- console: 0.0.4
- scikit-image: 0.4.11
- svg: 0.1.5

## Additional context

Adding dependency on package "certifi" should fix the problem.

**Comment by tlambert03** [comment]
good catch!  it's kind of amazing that you ended up with an environment without certifi 😂 ... but I did just double check and none of our direct dependencies depend on it.  It comes in with `requests`, which tons of our dev and docs packages use, but we missed this.  thanks!
