### ISSUE TITLE
Dask cache not getting hit with chanked dask array slowing z scroling

### ISSUE THREAD

**Issue by boazmohar** [napari/napari#3384]
## 🐛 Bug

Every z step hits dask without using the cache. In multiscale array, I think both levels are hit with drag / zoom.
I think I have some dask configuration issue maybe. 
Any advice would be appreciated.

## To Reproduce

```python
from dask.distributed import Client, LocalCluster
cluster = LocalCluster(n_workers=8)
client = Client(cluster)

import dask.array as da
import numpy as np
dask_temp = da.random.randint(
    low=0, high=1000, size=(1024,1024,1024),
    chunks=(64,64,64), dtype=np.uint16)

import napari
viewer = napari.Viewer()
viewer.add_image(data=dask_temp,contrast_limits=[0, 1000])
napari.utils.resize_dask_cache(1000000)
napari.run()
```

https://user-images.githubusercontent.com/9434009/133434452-4e647e33-461b-4fac-a214-d45e78a401db.mp4

I have checked the cache as in the test and it is not getting hit:

```python
v = napari.viewer.ViewerModel()
dask_stack = dask_temp
v.add_image(dask_stack, multiscale=False, contrast_limits=(0, 1))
print(napari.utils.dask_cache.cache.available_bytes)
for i in range(3):
    v.dims.set_point(0, i)
print(len(napari.utils.dask_cache.cache.heap.heap))
```
output:
1000000
0

For multiscale array even dragging is an issue:
```python
import dask.array as da
import numpy as np
dask_temp_s0 = da.random.randint(
    low=0, high=1000, size=(1024*4,1024*4,1024*4),
    chunks=(64*4,64*4,64*4), dtype=np.uint16)
dask_temp_s1 = da.random.randint(
    low=0, high=1000, size=(1024,1024,1024),
    chunks=(64,64,64), dtype=np.uint16)

import napari
viewer = napari.Viewer()
viewer.add_image(data=[dask_temp_s0, dask_temp_s1],
                 multiscale=True,
                 contrast_limits=[0, 1000])
napari.utils.resize_dask_cache(1000000)
napari.run()
```

https://user-images.githubusercontent.com/9434009/133435670-dea4d0cd-7dab-4261-87a9-44ecd9263d4f.mp4

## Expected behavior

As in the [tests](https://github.com/napari/napari/blob/main/napari/layers/_tests/test_dask_layers.py#L247) I expected the chunks to be chaced and the moving in z within the first block should be faster without involving dask.
For multiscale array it also seems all levels are being hit.

## Environment

 napari: 0.4.11
Platform: Windows-10-10.0.19042-SP0
Python: 3.8.10 | packaged by conda-forge | (default, May 11 2021, 06:25:23) [MSC v.1916 64 bit (AMD64)]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.21.2
SciPy: 1.7.1
Dask: 2021.09.0
VisPy: 0.8.1

OpenGL:
- GL version: 4.6.0 NVIDIA 466.47
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1080, scale 1.0
- screen 2: resolution 1920x1200, scale 1.0

Plugins:
- console: 0.0.4
- scikit-image: 0.4.11
- svg: 0.1.5

## Additional context

Setting `dask.config.set({"optimization.fuse.active": False})` didn't help.

**Comment by tlambert03** [comment]
thanks @boazmohar.  Will have a closer look later, but two quick questions for now:
1) if you put `napari.utils.resize_dask_cache(1000000)` _before_ the call to `add_image`, does it change anything?
2) if you have a moment, could you try https://github.com/napari/napari/pull/3285 ?  (that PR turns dask caching back on by default... in a context-manager while slicing the layer.  You can see how we test for heap population [here](https://github.com/napari/napari/pull/3285/files#diff-e8b12d6af4f66a0a4c2a4841e10580ea5aad2c8fd6b7443502b70be88e883cfcR139-R143)

**Comment by boazmohar** [comment]
Hi @tlambert03,

Thanks for the quick responce.
1. No
2. Didn't help (I think I did the right thing)

I still see it hitting the dask array with get value.
but this is making sense:
```python
import dask.array as da
import numpy as np
import napari
v = napari.components.ViewerModel()
dask_stack = da.random.randint(
    low=0, high=1000, size=(1024,1024,1024),
    chunks=(64,64,64), dtype=np.uint16)
layer = v.add_image(dask_stack)
with layer.dask_optimized_slicing() as (_, cache):
        print(f'bytes:{cache.cache.available_bytes}')
        print(f'active:{cache.active}')
        # make sure the cache actually has been populated
        print(f'len:{len(cache.cache.heap.heap)}')
```
output is:
```
bytes:17158577152.0
active:{(<bound method Cache._start of <dask.cache.Cache object at 0x000001548AF93B20>>, None, <bound method Cache._pretask of <dask.cache.Cache object at 0x000001548AF93B20>>, <bound method Cache._posttask of <dask.cache.Cache object at 0x000001548AF93B20>>, <bound method Cache._finish of <dask.cache.Cache object at 0x000001548AF93B20>>)}
len:4096
```

Here is the info I get for that branch:
napari: 0.1.10.dev601+gca38d5e4
Platform: Windows-10-10.0.19042-SP0
Python: 3.8.10 | packaged by conda-forge | (default, May 11 2021, 06:25:23) [MSC v.1916 64 bit (AMD64)]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.21.2
SciPy: 1.7.1
Dask: 2021.09.0
VisPy: 0.8.1

OpenGL:
- GL version: 4.6.0 NVIDIA 466.47
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1080, scale 1.0
- screen 2: resolution 1920x1200, scale 1.0

Plugins:
- console: 0.0.4
- scikit-image: 0.1.10.dev601+gca38d5e4
- svg: 0.1.5
I still see the same behavior of hitting

**Comment by jni** [comment]
@boazmohar I noticed you are using the dask distributed scheduler in your first example — are you using it always? Note that dask does *no caching* when using the distributed scheduler:

https://docs.dask.org/en/latest/caching.html#disclaimer

"Opportunistic caching is not available when using the distributed scheduler."

**Comment by tlambert03** [comment]
ahh, good point!  sorry I missed that

**Comment by boazmohar** [comment]
Thanks @jni I think this is solved. At least in the new branch I am on from @tlambert03 repo. 
I don't have a schduler to look at the calls but the behivor is as expected from looking at the delay of rendering (higher between chunks)

Just for completness this is what I ran:
```python
import dask
dask.config.set({"optimization.fuse.active": False})
dask.config.set(scheduler='threads')
import dask.array as da
import numpy as np
import napari
dask_temp_s0 = da.random.randint(
    low=0, high=1000, size=(1024*4,1024*4,1024*4),
    chunks=(64*4,64*4,64*4), dtype=np.uint16)
dask_temp_s1 = da.random.randint(
    low=0, high=1000, size=(1024,1024,1024),
    chunks=(64,64,64), dtype=np.uint16)

viewer = napari.Viewer()
layer = viewer.add_image(data=[dask_temp_s0, dask_temp_s1],
                 multiscale=True,
                 contrast_limits=[0, 1000])

with layer.dask_optimized_slicing() as (_, cache):
    napari.run()
    print(f'len:{len(cache.cache.heap.heap)}')
```
output was: `len:21698`
