### ISSUE TITLE
Convert to Image/Convert to Labels do not preserve scaling

### ISSUE THREAD

**Issue by chili-chiu** [napari/napari#3389]
## 🐛 Bug

Right click on label/image layers > Convert to Image/Convert to Labels do not preserve scaling.

## To Reproduce

1. Create an image layer, set the layer scale to something other than default [1,1,1]
2. Right click on the image layer > Convert to Labels
3. The new labels layer ignores the scaling and reverts back to default [1,1,1]  

Same behavior also goes from labels layer to image layer.

## Expected behavior

Convert to Image/Convert to Labels should maintain the same scaling as the original layer. 

## Environment
napari: 0.4.12.dev11+g5a43dc59
Platform: macOS-11.5.2-x86_64-i386-64bit
System: MacOS 11.5.2
Python: 3.8.2 (default, Jun 8 2021, 11:59:35) [Clang 12.0.5 (clang-1205.0.22.11)]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.20.3
SciPy: 1.7.1
Dask: 2021.09.0
VisPy: 0.8.1

OpenGL:
- GL version: 2.1 ATI-4.6.20
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1792x1120, scale 2.0

Plugins:
- bioformats: 0.2.1
- cellpose-napari: 0.1.3
- console: 0.0.4
- napari-features: 0.1.4
- ome-types: 0.2.9
- scikit-image: 0.4.12.dev11+g5a43dc59
- svg: 0.1.5

**Comment by tlambert03** [comment]
thanks!  For anyone motivated to work on this, the code needing modification is right here:
https://github.com/napari/napari/blob/80877fcb411c2b12d974507895259c5ae3047b4a/napari/layers/_layer_actions.py#L80-L86

and it could borrow the metadata-copying strategy from here:

https://github.com/napari/napari/blob/80877fcb411c2b12d974507895259c5ae3047b4a/napari/layers/_layer_actions.py#L68-L76
