### ISSUE TITLE
Enable discussions feature on the napari repo

### ISSUE THREAD

**Issue by GenevieveBuckley** [napari/napari#3399]
## 🚀 Feature

Enable the discussions feature on the napari repository.

## Motivation

Often, discussions in issues ([example](https://github.com/napari/napari/issues/3390)) end up having multiple topics discussed. It might be nice to have a dedicated place for these types of speculative discussions where new topics can easily be created.

## Pitch

@codemonkey800 has suggested that it would be helpful if the "disucssions" feature was enabled on the napari repository https://github.com/napari/napari/issues/3390#issuecomment-923096890

>> On another note, it seems this thread is now mixing a lot of different topics around the original one, maybe we could do the convo around H2/H3 and display technicalities in another issue dedicated to that :)
>
> Agreed, it also would be cool if we could enable the Discussions tab on the napari repo so we could have the separate discussions in different threads 🤔 

## Alternatives

We could keep using issue threads for this purpose instead.

## Additional context

Link: https://github.com/napari/napari/issues/3390#issuecomment-923096890

**Comment by GenevieveBuckley** [comment]
Probably a question best for @sofroniewn or @jni to answer?

**Comment by sofroniewn** [comment]
I don't mind. I think when they first came out we worried that they might be duplicative with the zulip, but not everyone is in the zulip and maybe there are for a slightly different person. I think it's fine to enable them and then if people organically use them they will take off, if not there won't be much activity and after a while we could close. I don't think its too bad to have one more place to look - but if there are strong objections then I wouldn't insist either

**Comment by nclack** [comment]
I worry about splitting folks over multiple platforms.  I'm not very familiar with github discussions though.  

IMO, github issues and zulip (and github discussions?) will have problems with tasks involving gathering broad collaborative feedback. PRs work better but are only for code.  @andy-sweet used hackmd for a shared design doc for #3327.  I thought that worked pretty well.  Maybe there are better options?

**Comment by GenevieveBuckley** [comment]
I kind of worry about splitting things up over too many places too. I personally will often forget discussions exist and find they can go stale more easily if inactive than issue threads (because I'm more likely to look back over the issue list at some point).

**Comment by codemonkey800** [comment]
Somewhere for conversations where certain topics can branch into separate threads is mostly what I was going for. I'm sure hackmd and Zulip work well for it, but the #3390 and also #3399 were created in issues instead of those platforms anyway.

I guess some clarity on where certain things should go would be great. For example, issues could be for bugs/regressions/etc. that show up in napari and hackmd can be for RFC-like documents.

I have no preference and I'm sure other platforms can achieve some of the below, but a few nice things about GitHub discussions are:

1. Colocated with the napari repo.
2. You can convert issues to discussions and vice versa.
3. Discussions can be organized by categories and labels.

As an example, I really like how Next.js manages discussions on their repo: https://github.com/vercel/next.js/discussions

**Comment by nclack** [comment]
> 2\. You can convert issues to discussions and vice versa.

That's pretty nice.  I think that alone makes it worth trying out.

**Comment by GenevieveBuckley** [comment]
> Discussions can be organized by categories and labels.

You can do this for issues too.

Zulip is good for interaction, not so good for having a documented record (the conversation exists, it's just not always easy to find, and not everyone is on zulip to weigh in there). So that might help for deciding what conversation goes where.

**Comment by sofroniewn** [comment]
> > 2. You can convert issues to discussions and vice versa.
> > 
> That's pretty nice. I think that alone makes it worth trying out.


Ok I think this means that we can turn them on, see how we like it, and then if we decide we don't like it we can convert everything over to issues and close it or just close it. That would be my vote. Happy to still hear more from others though. If i don't hear anything within a day or two I'll just turn them on
