### ISSUE TITLE
Theme testing incredibly slow in CI

### ISSUE THREAD

**Issue by Carreau** [napari/napari#3404]
Here is an excerpt of slowest tests duration.

```
 ============================= slowest 5 durations ==============================
  25.94s call     napari/_tests/test_examples.py::test_examples[new_theme.py]
  12.13s call     napari/utils/_tests/test_theme.py::test_theme[color5]
  12.03s call     napari/utils/_tests/test_theme.py::test_theme[color4]
  11.98s call     napari/utils/_tests/test_theme.py::test_theme[color3]
  11.94s call     napari/utils/_tests/test_theme.py::test_theme[#FF0000]
```

`napari/utils/_tests/test_theme.py::test_theme` is parametrized with 6 alternative, and each takes between 10 and 15 second on github, so we use between 1 and 1min30 (between 5 and 10% of our test suite), just to test theme.

We might want to just skip this on Python != 3.9 if we don't want to dig into why it's slow.

**Comment by Carreau** [comment]
@goanpeca might have an idea ? 

The full test is:

```python
def test_theme(color):
    theme = get_theme("dark", False)
    theme.background = color

    with pytest.raises(ValidationError):
        theme.syntax_style = "invalid"
```

**Comment by goanpeca** [comment]
Hi @Carreau ohh that is very slow. That code was probably still there. Will look at your PR :)

**Comment by lukasz-migas** [comment]
Wow, that is slow as hell. I just checked #3034 and these tests were not amongst the 5 slowest on none of the platforms/python versions so something must have changed to cause this.
