### ISSUE TITLE
Code snippets on napari tutorials documentation displaying traceback errors

### ISSUE THREAD

**Issue by i-jey** [napari/napari#3411]
## 🐛 Bug

The code snippets on the napari tutorials page are showing traceback errors.
See the tutorial page: https://napari.org/tutorials/index.html

Here is a screenshot of what I see on my end:
![image](https://user-images.githubusercontent.com/25993326/134583060-2707977a-63d8-49e9-9af2-0961734b3dfe.png)

**Comment by psobolewskiPhD** [comment]
I was supposed to post an issue on this, but forgot 😢 
Anyhow, there's also issues here:
https://napari.org/tutorials/fundamentals/vectors.html
and broken image links here:
https://napari.org/plugins/stable/find-and-install-plugin.html

edit:
Also, this example: https://napari.org/docs/0.4.4/api/napari.qt.html?highlight=dock_widget#napari.qt.Window.close
Should it look like that? I hope not...

**Comment by jni** [comment]
Bahaha no it should not, thanks both for raising this. We have a dedicated group looking at our docs now, hopefully all this (and more) will be fixed soon.

**Comment by psobolewskiPhD** [comment]
Woof, the root of tutorials also has a wall-of-errors:
https://napari.org/tutorials/
<img width="1067" alt="image" src="https://user-images.githubusercontent.com/76622105/137623834-f8820feb-e881-4ed6-96dc-12a4c15b9a36.png">

**Comment by psobolewskiPhD** [comment]
Based on a recent closed duplicate issue, it looks like this is being handled in the other repo: https://github.com/napari/napari.github.io/issues/161
(this is a bit confusing, as to where to report what, but as long as folks are aware, it's all good)

**Comment by tlambert03** [comment]
Yep thanks @psobolewskiPhD!
