### ISSUE TITLE
Dask images are often posterized after initial load + autoscale

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#3422]
## 🚀 Feature
in a previous PR, we made it so that contrast limits aren't auto-calculated on dask images, so as to prevent extra compute.  (sidenote: we've since fixed up some things about dask... so the situation might not be as bad.)  However, if the contrast limits are a very small percent of the total bit depth, then you get posterization of the image after hitting autoscale (this is related to the way that we calculate contrast on the GPU, trying to not to create a new shader, ... and would probably also be solved by moving to float textures by default).  One has to then toggle visibility (reset) the layer in order to avoid the posterization...

we should generally fix that.

To reproduce. run this script, hit autoscale, then toggle the visibility of the layer.  It only looks correct after the final toggle.  it _should_ look correct after the initial autoscale, (and it would be nice to prevent needing that initial autoscale again)

```py
import dask.array as da
import napari

napari.view_image(da.arange(1024).reshape(32,32))
napari.run()
```

**Comment by sofroniewn** [comment]
I just approved #3425, though it does seem like

> would probably also be solved by moving to float textures by default

would be a more appealing long term solution to all this
