### ISSUE TITLE
Copy `rendering` documentation for `average` to class property

### ISSUE THREAD

**Issue by kolibril13** [napari/napari#3423]
It is possible to set the rendering to `average` programmatically:
`viewer.layers[0].rendering= 'average'`
But it does not show in the API.
https://napari.org/api/stable/napari.layers.Image.html#napari.layers.Image.rendering

It was added here:
https://github.com/napari/napari/commit/fcbf8cd35274ec46451347b3cbbe455ae999477b

And has also documentation here:
https://github.com/napari/napari/blob/fcbf8cd35274ec46451347b3cbbe455ae999477b/napari/layers/image/_image_constants.py#L58
which can be added here :
https://github.com/napari/napari/blob/5f96d5d814aad697c367bdadbb1a57750e2114ad/napari/layers/image/image.py#L494-L501

**Comment by jni** [comment]
Thanks for pointing this out @kolibril13! I agree that this would be good to add. Would you like to make a pull request adding this note?

**Comment by kolibril13** [comment]
It is at #3436.
First time I used the new GitHub webIDE making a pull request by pressing "." .
Really useful feature!

**Comment by alisterburt** [comment]
Closed by #3436 - thanks again @kolibril13
