### ISSUE TITLE
Create `napari-menu` conda-forge package

### ISSUE THREAD

**Issue by jaimergp** [napari/napari#3432]
This will be just a wrapper package that provide menu entries for `napari` so they can be used by the new `constructor` installers.

Future work might also involve adding `menuinst` support for other platforms/desktops (e.g. Gnome and others on Linux).

xref https://github.com/conda-forge/napari-feedstock/issues/28

**Comment by alisterburt** [comment]
By menu, you mean OS menus, not menus in napari itself, right?

**Comment by goanpeca** [comment]
Correct!

**Comment by jaimergp** [comment]
Closed by https://github.com/conda-forge/napari-feedstock/pull/32
