### ISSUE TITLE
remove broadcast mode from nD shapes

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#344]
## 🐛 Bug

#297 introduced nD shapes containing both `broadcast` and `sliced` shapes, with the option to toggle between them, but really looking back on it that was a mistake. As some people pointed out at the time - being able to switch back and forth between the two modes was strange. In reality it was unnecessary - `broadcast` mode is achieved by adding a `2D` shapes layer to the viewer. There was no need to have the concept of and `nD` shape that appeared everywhere.

For a really simple example of how this works see the nD vectors example in #343. 

I'd like to remove the explicit broadcast mode, which will preserve all functionality and reduce confusion

**Comment by sofroniewn** [comment]
this might also make some of the weird special casing for the 2D case that I think @jni didn't like go away

**Comment by jni** [comment]
@sofroniewn but can one add a 2D shapes layer from the GUI when the current image is 3D?

But, yes, in general, non-existent dimensions should be broadcast as NumPy does. =)

**Comment by sofroniewn** [comment]
Unfortunately it'll now not be possible to add 2D shapes onto a 3D image with a button click from the GUI, but I think we should solve that problem independent of this fix
