### ISSUE TITLE
Persistence of full-screen mode confusing, hard to close/minimize

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#3441]
## 🐛 Bug

Issue copied from @optomanishk image.sc: https://forum.image.sc/t/napari-opens-in-full-screen-mode-and-doesnt-function/58286

----

I’m using the usual example code from a jupyter notebook to start napari UI.
Code:

```py
from skimage import data
import napari

viewer = napari.view_image(data.astronaut(), rgb=True)
napari.run()  # start the event loop and show viewer
```

napari opens in this full-screen mode where none of the options (File - View - Window - Plugins - Help) work. There is no close/maximize/minimize button either.

I get this warning:
```
WARNING: QWindowsWindow::setGeometry: Unable to set geometry 1920x1080+1928+31 (frame: 1936x1119+1920+0) on QWidgetWindow/"_QtMainWindowClassWindow" on "\\.\DISPLAY2". Resulting geometry: 1920x1061+1928+31 (frame: 1936x1100+1920+0) margins: 8, 31, 8, 8 minimum size: 608x520 MINMAXINFO maxSize=0,0 maxpos=0,0 mintrack=624,559 maxtrack=0,0)
```

----

solved by `napari --reset` ... but it would be nice to avoid that 

related issue: #2971 #3038 #3075 
cc @goanpeca

**Comment by dalthviz** [comment]
Hi, just in case, I was able to reproduce this issue on Windows. I think this is related to https://bugreports.qt.io/browse/QTBUG-41309 

Some workarounds and more info available at:

* https://bugreports.qt.io/browse/QTBUG-41309?focusedCommentId=318322&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-318322
* https://doc.qt.io/qt-5/windows-issues.html#fullscreen-opengl-based-windows

In the maintime, as a way to workaround this without having to reset the preferences you can use the Toggle Fullscreen shortcut (`Ctrl + F` or `Alt + Enter`)
