### ISSUE TITLE
Introduce channel_axis argument to `add_labels`

### ISSUE THREAD

**Issue by VolkerH** [napari/napari#3447]
## 🚀 Feature

When adding label images it is currently not possible to assign a  channel_axis, in contrast to intensity images. 
While channels in label images may not seem quite as intuitive as channels in intensity images (where they can correspond to different colors, for examples) they can be meaningful as holding segmentations of different object types. These could (but don't have to) correspond to segmentations in different channels of a corresponding intensity image (e.g. nuclei segmented from a DAPI channel, cytoplasm from a GFP channel). 

## Motivation

Adding a layer with a 5D label images can currently cause problems through conflicting viewer dimensions between image layers and  label layers in napari (see: https://github.com/napari/napari/issues/2487#issuecomment-932076245). The suggestion to add a channel axis to label images as well arose from the related discussion in that issue.

 
## Also relevant

There is an existing (slightly stale?) task (#3019) to abolish the channel_axis argument altogether, I am not sure whether this is still seen as a good idea.

**Comment by sofroniewn** [comment]
> There is an existing (slightly stale?) task (#3019) to abolish the channel_axis argument altogether, I am not sure whether this is still seen as a good idea.

Yeah, I still lean towards dropping `channel_axis` and just making it really easy to split by channels. If it isn't possible to split labels by channels in the layer specific context menu then I think we should just enable that. It means it takes an extra click/ API call - but I think it will be much cleaner. What does @tlambert03 think here?

**Comment by tlambert03** [comment]
> What does @tlambert03 think here?

yeah, I'm still in favor of removing `channel_axis` and standardizing the return type.  Every downstream method that receives the result of `add_<layer>` would really benefit from not having to check `if isinstance(result, list)` for the chance that `channel_axis` was used.   so i'd vote for some sort of helper function in favor of adding a new parameter to `add_labels` that changes the return type from `Layer` to `List[Layer]`

**Comment by VolkerH** [comment]
Thanks for your thoughts on this @sofroniewn , @tlambert03 
So if the plan is to drop `channel_axis` from the `add_*` functions, this issue can probably be closed.
