### ISSUE TITLE
PyPI source package contents

### ISSUE THREAD

**Issue by jaimergp** [napari/napari#3448]
## 🧰 Task

The PyPI source package (.tar.gz) contains the `/binder` directory, but lacks the `/resources` one (needed for icons in `napari-menu`). Two questions:

1. Is `/binder` there on purpose or accidentally? @goanpeca 
2. Can we include `/resources` or is there anything against that?

**Comment by goanpeca** [comment]
Hi @jaimergp 

>Is /binder there on purpose or accidentally?

Probably accidental, need to add an exclude on the manifest

>Can we include /resources or is there anything against that?

@tlambert03 , @sofroniewn ?

**Comment by tlambert03** [comment]
you can include it.  is it the icns files in there that you need?  we do have a resources folder of icon svgs that is already included at `napari/resources/icons`, you could either put it in there, or go ahead and update the manifest to also include that top level folder.

**Comment by jaimergp** [comment]
I need the `.ico` and the `.icns` I think. Maybe it's easier to put those under `napari/resources/icons` too and skip the top-level directory?
