### ISSUE TITLE
styling on layer widgets on new layer

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#346]
## 🐛 Bug

When a new layer gets added the styling of the new layer does not reflect that it is selected, but the control panels display and functionality indicates that it is

**Comment by kne42** [comment]
see the [3rd](https://github.com/napari/napari/pull/330#discussion_r293176542) and [4th](https://github.com/napari/napari/pull/330#discussion_r293176737) review comment on https://github.com/napari/napari/pull/330#pullrequestreview-249089637
