### ISSUE TITLE
Cannot search for available plugins on macOS Big Sur

### ISSUE THREAD

**Issue by amgfernandes** [napari/napari#3461]
## 🐛 Bug

If I use napari on Windows 10 I can search for available plugins but that's not the case when I install on macOS Big Sur. Is the filter menu missing for Mac?

Details:
```
napari: 0.4.10
Platform: macOS-11.6-x86_64-i386-64bit
System: MacOS 11.6
Python: 3.9.6 | packaged by conda-forge | (default, Jul 11 2021, 03:36:15) [Clang 11.1.0 ]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.19.5
SciPy: 1.7.1
Dask: 2021.07.2
VisPy: 0.7.3
```

**Comment by psobolewskiPhD** [comment]
Pretty sure the Filter box at the top was added in 0.4.11—are you using the same version on both OS?

**Comment by amgfernandes** [comment]
Yes, you are right upgrading to version 0.4.11 fixed it. Thanks
