### ISSUE TITLE
`show_info` is not displayed in `thread_worker` functions 

### ISSUE THREAD

**Issue by glyg** [napari/napari#3467]
## 🐛 Bug

When using a `thread_worker` decorator to define a threaded function, the calls to `show_info` in that function are not routed to the  

## To Reproduce

Execute the following code from the napari IPython prompt
```python

import napari
from napari_plugin_engine import napari_hook_implementation
from magicgui import magic_factory

from napari.qt import thread_worker
from napari.utils.notifications import show_info

show_info('Test from main')  # This is displayed in the activity window 
import time

@thread_worker
def test_thread():
    print("started thread")
    show_info("in thread info")  # This prints "Notification" to stdout
    return 0

test_thread().start()
```

## Expected behavior

The message in a `show_info` call in the separate thread should be displayed

## Environment

 - Please copy and paste the information at napari info option in help menubar here:
napari: 0.4.12.dev51+g87f1ccac
Platform: Linux-5.13.0-7614-generic-x86_64-with-glibc2.33
System: Pop!_OS 21.04
Python: 3.9.7 | packaged by conda-forge | (default, Sep 14 2021, 01:17:55) [GCC 9.4.0]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.21.2
SciPy: 1.7.1
Dask: 2021.09.0
VisPy: 0.8.1

OpenGL:
- GL version: 4.6 (Compatibility Profile) Mesa 21.2.1
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1080, scale 1.0
- screen 2: resolution 1920x1080, scale 1.0

Plugins:
- console: 0.0.4
- napari-useg: 0.0.1
- scikit-image: 0.4.12.dev51+g87f1ccac
- svg: 0.1.5

**Comment by tlambert03** [comment]
Thanks @glyg 

I think the fix here could be as easy as using @Czaki's new `ensure_main_thread` decorator from superqt on the `show_info` function [here](https://github.com/tlambert03/napari/blob/3217587ba8cb9080eef5a983c6cd3b0849efafb3/napari/utils/notifications.py#L290-L291)

```py
from superqt import ensure_main_thread

@ensure_main_thread
def show_info(message: str):
    notification_manager.receive_info(message)
```

@Czaki ... would you have time to give that a shot?

**Comment by Czaki** [comment]
I would rather decorate clasmethod `show_notification` of `NapariQtNotification` (to keep qt code in qt part) or eventually `dispatch` of `NotificationManager`. 

The code attached to this issue does not work on my computer (there is even no napari window create), s I could sit on this tomorrow (because I nee try to create my own code for reproduction).

**Comment by Czaki** [comment]
@glyg Could you update your script to allow to reproduce the error when run as `python path_to_script.py`

**Comment by glyg** [comment]
Here is a script version<sup>1</sup>:

```python
import time

from skimage import data
import napari
from napari.qt import thread_worker
from napari.utils.notifications import show_info

napari.view_image(data.astronaut(), rgb=True)

@thread_worker
def test_thread():
    print("started thread")
    time.sleep(1)
    show_info("in thread info")  # This prints "Notification" to stdout
    return 0


test_thread().start()

show_info("Test from main")  # This is displayed as a notification
napari.run()

```

1. ~~This segfaults on my machine -- I suspect due to newest Qt? -- but this is unrelated to the bug~~ (edited, I forgot the `napari.run()` line)

**Comment by Czaki** [comment]
Ok, I could reproduce the error and found the source of the problem:

This part of code properly handle information that calls comes from the wrong thread and pass it to Qt Signal 
https://github.com/napari/napari/blob/ab7bb40a37dc6d2faa46e1b74f8ca93ed396d7a9/napari/_qt/dialogs/qt_notification.py#L380-L388

but the connection is moved (last modification in #2703) to update tooltip method of main window (so it is not connected):

https://github.com/napari/napari/blob/ab7bb40a37dc6d2faa46e1b74f8ca93ed396d7a9/napari/_qt/qt_main_window.py#L128-L140

This time fastest solution may be to use `ensure_main_thread`  to `show_notification` of `NapariQtNotification` but @tlambert03 maybe you prefer to fix existing code?

**Comment by tlambert03** [comment]
I don't have a strong opinion here.  If @goanpeca moved that code to another place, perhaps he has a thought here.  I'm happy to go with whatever solves this immediate issue here

**Comment by goanpeca** [comment]
Hmmmm, that was an old PR 🤔 

>This time fastest solution may be to use ensure_main_thread to show_notification of NapariQtNotification

I would go with this, and perhaps leave a note @Czaki while I think of this a bit more
