### ISSUE TITLE
macOS builds are failing repeatedly with a timeout

### ISSUE THREAD

**Issue by jni** [napari/napari#3472]
## 🐛 Bug

See example here:

https://github.com/napari/napari/runs/3872943744#step:7:296

This appears to have been introduced by #3407, and was not fixed by #3457.

**Comment by goanpeca** [comment]
I think #3457 was supposed to remove the tiemout when running tests locally.

Might need to bump the timeout for Macos conditionally or ? 

What do you think @Carreau ? 🤔

**Comment by jni** [comment]
Yeah that's the thing, we want to either speed up the tests or raise the timeout on macOS, but I don't think it's good that all our [commits](https://github.com/napari/napari/commits/main) look like they are failing CI, or that all our PRs fail on macOS.

**Comment by tlambert03** [comment]
bump...

**Comment by tlambert03** [comment]
another observation: 
running tests locally, i found a dependence between _when_ the test is run (in the context of all the tests) and how long it takes.  for instance, the magicgui tests that are marked with `@slow(10)` now take only about 0.2 seconds to run if I only test that module, but can take 20+ seconds when run in the context of the full test.  I can't see anything in the tests themselves that should actually be that slow... so I think it's a red herring (and marking them as slow is probably just patching a symptom and not the cause).  I wonder if it's something in `make_napari_viewer` (which has certainly grown in complexity).

**Comment by Carreau** [comment]
> another observation:
> running tests locally, i found a dependence between _when_ the test is run (in the context of all the tests) and how long it takes. for instance, the magicgui tests that are marked with `@slow(10)` now take only about 0.2 seconds to run if I only test that module, but can take 20+ seconds when run in the context of the full test. I can't see anything in the tests themselves that should actually be that slow... so I think it's a red herring (and marking them as slow is probably just patching a symptom and not the cause). I wonder if it's something in `make_napari_viewer` (which has certainly grown in complexity).

That is interesting, I'm guessing we can likely use a form of bisect by deleting test to find out what the problem is. I think I also had issues reproducing the slow test locally. so I'm not sure how to track that down.

**Comment by Carreau** [comment]
So I narrowed it down to at least in run-examples with runpy:
```
viewer = Viewer()
napari.run()
# viewer not closed
```

I think we can take care of that with a close_all classmethod on viewer and use it in the right place.

**Comment by tlambert03** [comment]
I think @Carreau's fix in #3516 has taken care of this!
