### ISSUE TITLE
surface layer clim buttons not respecting layout

### ISSUE THREAD

**Issue by alisterburt** [napari/napari#3474]
## 🐛 Bug

![image](https://user-images.githubusercontent.com/7307488/137180948-7e9991d6-f732-4d1d-9a52-350cb8185460.png)

## To Reproduce

1. run `python examples/nD_surface.py` on `0.4.11`
2.
3.

```sh
napari: 0.4.11rc3.dev18+g04b1baa1
Platform: macOS-10.16-x86_64-i386-64bit
System: MacOS 11.5.2
Python: 3.9.6 (default, Jul 30 2021, 09:31:09)  [Clang 10.0.0 ]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.21.1
SciPy: 1.7.0
Dask: 2021.07.2
VisPy: 0.7.3

OpenGL:
  - GL version:  2.1 Metal - 71.7.1
  - MAX_TEXTURE_SIZE: 16384

Screens:
  - screen 1: resolution 1440x900, scale 2.0

Plugins:
  - mrcfile-reader: 0.1.3
  - scikit-image: 0.4.11rc3.dev18+g04b1baa1
  - svg: 0.1.5
```

**Comment by andy-sweet** [comment]
@alisterburt : I can reproduce this with v0.4.11, but I can't on `main`. Not sure what fixed it, but can you try to reproduce it and close this if you can't?

**Comment by alisterburt** [comment]
all looks good!
