### ISSUE TITLE
Linux bundle crash on new linux versions

### ISSUE THREAD

**Issue by Czaki** [napari/napari#3487]
## 🐛 Bug

When trying to start bundle:

```
$ ./napari-0.4.11-x86_64.AppImage 
Traceback (most recent call last):
  File "/tmp/.mount_napari5EDOCz/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/tmp/.mount_napari5EDOCz/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/.mount_napari5EDOCz/usr/app/napari/__main__.py", line 428, in <module>
    sys.exit(main())
  File "/tmp/.mount_napari5EDOCz/usr/app/napari/__main__.py", line 424, in main
    _run()
  File "/tmp/.mount_napari5EDOCz/usr/app/napari/__main__.py", line 230, in _run
    from napari import run, view_path
  File "/tmp/.mount_napari5EDOCz/usr/app/napari/_lazy.py", line 42, in __getattr__
    from scipy import stats  # noqa: F401
  File "/tmp/.mount_napari5EDOCz/usr/app_packages/scipy/__init__.py", line 153, in <module>
    from scipy._lib._ccallback import LowLevelCallable
  File "/tmp/.mount_napari5EDOCz/usr/app_packages/scipy/_lib/_ccallback.py", line 1, in <module>
    from . import _ccallback_c
  File "_ccallback_c.pyx", line 210, in init scipy._lib._ccallback_c
  File "/tmp/.mount_napari5EDOCz/usr/lib/python3.9/ctypes/__init__.py", line 8, in <module>
    from _ctypes import Union, Structure, Array
ImportError: libffi.so.6: cannot open shared object file: No such file or directory                                                                        /0,6s
```

## To Reproduce

1. Start napari Appimage on a new linux release (in my case it is ubuntu 21.04)

## Expected behavior

start napari from the bundle

## Environment
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 21.04
Release:	21.04
Codename:	hirsute           
```

## Additional context

When I check Pyinstaller build output then libffi.so.6 is included in bundle output.

**Comment by sofroniewn** [comment]
@jaimergp any idea what might be going on here?

**Comment by jaimergp** [comment]
Apparently Ubuntu updated their `libffi` so now instead of providing `*.so.6`, they have `*.so.7`. That library should be bundled in the AppImage though so no clue why it wasn't found. I'll look into it!

**Comment by Czaki** [comment]
> so now instead of providing `*.so.6`, they have `*.so.7`.

on ubuntu 21.04 libffi is in *.so.8

If you have some solution I could test it.

**Comment by jaimergp** [comment]
@Czaki can you confirm if the new conda-based installers work for you now? I believe so, but let's confirm before closing this.

**Comment by Czaki** [comment]
this still fail: https://github.com/napari/napari/actions/runs/2031505558

I do not know where live last build for conda so download from release page. 

When try to run I found that file is not executable (no `+x`). This is caused by using zip format that not preserve permissions. 

After install applications starts correctly.

**Comment by jaimergp** [comment]
Latest release is enough to try this out. The installer needs to be executed with `bash <installer>.sh`, so no chmod'ing should be necessary. This will be covered in the documentation for 0.4.16, so no worries.

The good news is that it starts correctly so we can close this! Thanks for checking it out!

**Comment by Czaki** [comment]
> The installer needs to be executed with `bash <installer>.sh`, so no chmod'ing should be necessary.

Based on the header the `sh <installer>.sh` should be enough. If bash is required, then the header should be updated.

**Comment by jaimergp** [comment]
It _should_ according to these [checks](https://conda.io/projects/conda/en/latest/user-guide/install/linux.html), but Anaconda's [instructions](https://conda.io/projects/conda/en/latest/user-guide/install/linux.html) always used `bash` 🤷
