### ISSUE TITLE
Layers how-tos, introduction and explanation

### ISSUE THREAD

**Issue by melissawm** [napari/napari#3490]
## 📚 Documentation

Hi all!

I've recently started with a proposal to refactor the [Layers tutorials](https://napari.org/tutorials/fundamentals/image.html). This includes:

- Grouping all the layer how-tos into a "Using layers" section;
- Removing duplication of content by creating a "Layers at a glance" document, explaining basic features common to all layers;
- Cleaning up links and wording to reflect this new organization.

For this, I assumed the [proposed reorganization](https://github.com/napari/napari.github.io/pull/176) is the starting point, as well as the new theme, so things look different from what is currently on the main site. 

You can see the proposal [in this PR](https://github.com/napari/napari.github.io/pull/268). 

Feedback and ideas welcome!

**Comment by chili-chiu** [comment]
@melissawm are there still outstanding items for this one?

**Comment by melissawm** [comment]
Not at this point, if there are any other suggestions we should probably open a new issue. Thanks for the heads up!
