### ISSUE TITLE
update contributing guidelines for compiling resources 

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#350]
## 📚 Documentation

As pointed out by @csweaver following the instructions in our contributing guidelines for installing `pyrcc5` does not actually lead to the install of `pyrcc5`. It seems like this comes with `PyQt5`. There is also the option to use `pyside2-rcc`  which comes with `PySide2`. We should document both these usage options.

**Comment by csweaver** [comment]
I've confirmed that pyrcc5 and pyside2-rcc both come with installation of their respective packages and no additional packages are necessary.

`bin` directory from a fresh virtual env
```
activate         easy_install     pip3             python3
activate.csh     easy_install-3.6 pip3.6
activate.fish    pip              python
```

after `pip install pyqt5`
```
activate         easy_install-3.6 pylupdate5       pyuic5
activate.csh     pip              pyrcc5
activate.fish    pip3             python
easy_install     pip3.6           python3
```

after `pip install pyside2` (on a fresh virtual env)
```
activate         easy_install-3.6 pyside2-lupdate  python3
activate.csh     pip              pyside2-rcc
activate.fish    pip3             pyside2-uic
easy_install     pip3.6           python
```

This is python 3.6 on OSX 10.14.5, it could be different on other platforms.

**Comment by jni** [comment]
👋 @csweaver! 😊 

@sofroniewn so based on the above I guess we should just remove any mention of rcc in the contributing guide?

**Comment by sofroniewn** [comment]
I have given this a try in #353

**Comment by csweaver** [comment]
👋 Hi @jni! Off topic, but thanks for getting me started on python3. I haven't looked back 😁
