### ISSUE TITLE
Layer bounding box calculated incorrectly

### ISSUE THREAD

**Issue by alisterburt** [napari/napari#3506]
## 🐛 Bug

We currently calculate an (ndisplay, 2) bounding box around our data using a boolean mask on the displayed dimensions

https://github.com/napari/napari/blob/9af23fb0ddd8b9804edc84d534095a00b697c41c/napari/layers/base/base.py#L1167-L1169

The dims displayed mask has no order so can produce incorrect results, we should modify this to take the list of displayed dimensions for indexing into the bounding box.

This came up when implementing functionality which depended on the bounding box with @kevinyamauchi

**Comment by kevinyamauchi** [comment]
I think we should rename the kwarg to `dims_displayed` and then use `dims_displayed` instead of `dims_displayed_mask` here: 

https://github.com/napari/napari/blob/9af23fb0ddd8b9804edc84d534095a00b697c41c/napari/layers/base/base.py#L1217

**Comment by alisterburt** [comment]
closed by #3511
