### ISSUE TITLE
adding points changes their size

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#351]
## 🐛 Bug
Adding points changes the size of the points due to a weird bug in how we're now setting the point sizes. This got introduced when we allowed for points to be rescaled keeping their relative scalings and needs to be fixed

**Comment by sofroniewn** [comment]
also using the size slider after deleting points is causing a crash

**Comment by kevinyamauchi** [comment]
I propose that we change the way the relative sizes are preserved. I think we should calculate the marker size by multiplying the user-specified size by a scale factor set by the size slider. I think this should make the size of the spots independent of the number of spots. Thoughts @sofroniewn?

**Comment by sofroniewn** [comment]
I have a PR in the works that fixes this. It allows points to be selected individually and then be resized, like in the shapes layer. I'll push it soon(ish)

**Comment by kevinyamauchi** [comment]
Awesome!

**Comment by sofroniewn** [comment]
This has been fixed with #371
