### ISSUE TITLE
GUI + Ipython Integrate Terminal Very Slow

### ISSUE THREAD

**Issue by lstrgar** [napari/napari#3520]
## 🐛 Bug

I don't know if this is a problem with my system -- perhaps I'm looking for recommendations of how I may be able to speed things up. Generally I find that reading images in the integrated console is much slower than if I was to do this in a regular notebook, script, etc. Similarly, interacting with the viewer object is also very slow. Any assistance would be much appreciated!

## Environment

napari: 0.4.11
Platform: macOS-11.6-x86_64-i386-64bit
System: MacOS 11.6
Python: 3.9.6 (default, Jul 31 2021, 05:03:56) [Clang 12.0.5 (clang-1205.0.22.9)]
Qt: 5.15.2
PySide2: 5.15.2
NumPy: 1.19.3
SciPy: 1.7.1
Dask: 2021.08.1
VisPy: 0.8.1

OpenGL:
- GL version: 2.1 ATI-4.6.20
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1792x1120, scale 2.0

Plugins:
- console: 0.0.4
- scikit-image
- svg: 0.1.5

**Comment by sofroniewn** [comment]
Hi sorry to hear this @lstrgar. I'm not quite sure why the integrated console would be much slower. Is this for all operations or just reading operations? Does @Carreau have any ideas?

**Comment by lstrgar** [comment]
Thanks for getting back to me. Most operations it is slow.
