### ISSUE TITLE
Documentation build failure?

### ISSUE THREAD

**Issue by haesleinhuepf** [napari/napari#3527]
## 🐛 Bug

Hi all,

I think something went wrong with building the documentation. E.g. the [labels layer tutorial](https://napari.org/tutorials/fundamentals/labels.html) contains error messages.

![image](https://user-images.githubusercontent.com/12660498/139024098-df653097-1220-4a4b-a4c5-c73ad0259192.png)

## To Reproduce

1. Go to https://napari.org/tutorials/fundamentals/labels.html
2. Scroll down

## Expected behavior

Would be nice if the tutorials would look nice again :-)

## Environment

 - Please copy and paste the information at napari info option in help menubar here:

 - Any other relevant information:

**Comment by tlambert03** [comment]
thanks, we're aware, being discussed at https://github.com/napari/napari.github.io/issues/161
