### ISSUE TITLE
Plugin data storage

### ISSUE THREAD

**Issue by Czaki** [napari/napari#3528]
## Magicgui plugins

Maybe it will be nice to preserve values of parameters of magicgui generated plugins between napari runs. Base on my experience when working on one project then I prefer to use one set of parameters. But often one session is not enough. My current solution is to update default parameters in code but it is not the ideal solution.

This should also apply to widgets not constructed from functions.

This should be easy to achieve because there is a fixed data structure like in current napari settings. 

## Custom plugin storage

Next to the serialization state of plugin parameters on close to restore on open it will be nice to have the option of saving some plugin data for later reuse. 

An example of such a plugin is PartSeg with ROI extraction widgets ([link](https://github.com/4DNucleome/PartSeg/blob/develop/package/PartSeg/plugins/napari_widgets/roi_extraction_algorithms.py)), which use PartSeg serialization mechanism. 

The simplest mechanism which could be implemented is to use the same approach as in `NapariSettings`. Where napari will provide only a base class for event settings object as part of stable API. Also, `NapariSettings` should provide the path to the storage directory.

As far As I know, the currently used mechanism requires strong typing of such structure and does not allow Union field. So I do not see the option to declare a field that could contain "Any thresholding method description", Where such thresholding method could contain not only `int` or `float` but also `Enum`.

The approach which I use in PartSeg is to put information about the class in serialized data. I use JSON with using custom JSONEncoder subclass (`cls` parameter) for `json.dump` and `object_hook` for `json.load`. 

Base on my experience I could suggest such protocol as the starting point of discussion.
Serializable classes should be:

1. `Enum`
2. `dataclasses`
3. any class with `as_dict` method which output should be valid input to the constructor (please see that `dataclasses.asdict` does not satisfy this condition)

When dict of object is created then add information about the class. Something like:

```python
import dataclasses
import enum
import json

class NapariEncoder(json.JSONEncoder):
    def default(self, obj):
        if isinstance(obj, enum.Enum):
            return {
                "__class__": obj.__module__ + "." + obj.__class__, "value": obj.value,
            }
        if dataclasses.is_dataclass(obj):
            fields = dataclasses.fields(obj)
            dkt = {x.name: getattr(obj, x.name) for x in fields}
            dkt["__class__"] = obj.__module__ + "." + obj.__class__
            return super().default(dkt)

        if hasattr(obj, "as_dict"):
            dkt = obj.as_dict()
            dkt["__class__"] = obj.__module__ + "." + obj.__class__
            return super().default(dkt)

        if isinstance(obj, np.integer):
            return int(obj)
        if isinstance(obj, np.floating):
            return float(obj)
        if isinstance(obj, dict) and "__error__" in obj:
            del obj["__error__"]  # diffrent napari environments without same plugins installed
        return super().default(obj)
```

and deserialization
```python 
import importlib
import json

def napari_object_hook(dkt):
    if "__class__" in dkt:
        module_name, class_name = dkt["__class__"].rsplit(".")
        # the migration code should be called here
        try:
            del dkt["__class__"]
            module = importlib.import_module(module_name)
            obj = getattr(module, class_name)(**dkt)
            return obj
        except Exception as e:
            dkt["__class__"] = module_name + "." + class_name
            dkt["__error__"] = e
    return dkt
```

## Migration

When updating the plugin then may happen that the planned structure does not fit new requirements. Some fields could be renamed or removed. It will be nice if the plugin creator could provide some migration scheme and it would be applied to outdated save. 

For inspiration, for migration mechanism, we could look to Django. If the saved file will contain a plugin version for each class then should be easy to decide which migration needs to be applied. 

In PartSeg I create class Register and the `register` function/decorator has optional arguments that allow providing simple migration information (used in `object_hook`) but it is not the ideal solution. Especially some part of migration code is hidden inside`object_hook` which will not be acceptable as part of the solution for plugin ecosystem. 

## Serialization and moving to another machine

When the plugin provides the option to save some state for later reuse (from dropdown, button, etc) it will be nice to have the option to export such state to some file and import it on another machine. For example, adjust parameter on a small subset of data using a laptop and then perform a calculation on some stronger machine without using a physical notebook (which introduce another point of failure). 

Also, it allows increasing science reproducibility as such a file could be attached as supplementary material to the article. 

Having serialization mechanism as part of public API it is possible to implement it in a plugin but maybe something more general?

## Example serialization data
The dump from current PartSeg as an example:
```json
{
  "test_batch": {
    "__MeasurementProfile__": true,
    "name": "test_batch",
    "chosen_fields": [
      {
        "__Serializable__": true,
        "__subtype__": "PartSegCore.analysis.measurement_base.MeasurementEntry",
        "name": "ROI Volume",
        "calculation_tree": {
          "__Serializable__": true,
          "__subtype__": "PartSegCore.analysis.measurement_base.Leaf",
          "name": "Volume",
          "dict": {},
          "power": 1.0,
          "area": {
            "__Enum__": true,
            "__subtype__": "PartSegCore.analysis.measurement_base.AreaType",
            "value": 1
          },
          "per_component": {
            "__Enum__": true,
            "__subtype__": "PartSegCore.analysis.measurement_base.PerComponent",
            "value": 1
          },
          "channel": null
        }
      },
      {
        "__Serializable__": true,
        "__subtype__": "PartSegCore.analysis.measurement_base.MeasurementEntry",
        "name": "ROI Volume per component ",
        "calculation_tree": {
          "__Serializable__": true,
          "__subtype__": "PartSegCore.analysis.measurement_base.Leaf",
          "name": "Volume",
          "dict": {},
          "power": 1.0,
          "area": {
            "__Enum__": true,
            "__subtype__": "PartSegCore.analysis.measurement_base.AreaType",
            "value": 1
          },
          "per_component": {
            "__Enum__": true,
            "__subtype__": "PartSegCore.analysis.measurement_base.PerComponent",
            "value": 2
          },
          "channel": null
        }
      },
      {
        "__Serializable__": true,
        "__subtype__": "PartSegCore.analysis.measurement_base.MeasurementEntry",
        "name": "ROI Diameter per component ",
        "calculation_tree": {
          "__Serializable__": true,
          "__subtype__": "PartSegCore.analysis.measurement_base.Leaf",
          "name": "Diameter",
          "dict": {},
          "power": 1.0,
          "area": {
            "__Enum__": true,
            "__subtype__": "PartSegCore.analysis.measurement_base.AreaType",
            "value": 1
          },
          "per_component": {
            "__Enum__": true,
            "__subtype__": "PartSegCore.analysis.measurement_base.PerComponent",
            "value": 2
          },
          "channel": null
        }
      },
      {
        "__Serializable__": true,
        "__subtype__": "PartSegCore.analysis.measurement_base.MeasurementEntry",
        "name": "ROI Component Bounding Box per component ",
        "calculation_tree": {
          "__Serializable__": true,
          "__subtype__": "PartSegCore.analysis.measurement_base.Leaf",
          "name": "Component Bounding Box",
          "dict": {},
          "power": 1.0,
          "area": {
            "__Enum__": true,
            "__subtype__": "PartSegCore.analysis.measurement_base.AreaType",
            "value": 1
          },
          "per_component": {
            "__Enum__": true,
            "__subtype__": "PartSegCore.analysis.measurement_base.PerComponent",
            "value": 2
          },
          "channel": null
        }
      }
    ],
    "name_prefix": ""
  }
}
```

**Comment by tlambert03** [comment]
Have you tried using the `persist` argument in magicgui?

Another related note: npe2 has a configuration contribution that lets the plugin provide a schema with defaults for all configurables.  These will be persisted for plugins

**Comment by Czaki** [comment]
> Have you tried using the `persist` argument in magicgui?

not, but it looks like this does not solve the problem of isolation storage between projects (or napari overwrite `user_cache_dir` to be inside setting directory? 

> Another related note: npe2 has a configuration contribution that lets the plugin provide a schema with defaults for all configurables. These will be persisted for plugins

I do not understand. There is a place (maybe in code) which I could read?

**Comment by tlambert03** [comment]
> not, but it looks like this does not solve the problem of isolation storage between projects (or napari overwrite user_cache_dir to be inside setting directory?

please elaborate.  napari isn't involved in that persistence at all, it's a magicgui (FunctionGui) feature.  

> I do not understand. There is a place (maybe in code) which I could read?

sure, the proposal is to accept JSON schema [like this](https://github.com/tlambert03/npe2/blob/ad10394fa07d005e09ec79e0d712a1c0b818d165/tests/sample/my_plugin/napari.yaml#L15-L21) as a part of the [`contributions` in the manifest](https://github.com/tlambert03/npe2/blob/ad10394fa07d005e09ec79e0d712a1c0b818d165/npe2/manifest/contributions.py#L16)...

**Comment by Czaki** [comment]
> please elaborate. napari isn't involved in that persistence at all, it's a magicgui (FunctionGui) feature.

For me, it is important to have the possibility of separate data between different projects. There is a possibility now for separate napari settings using the environment variable. But using persistence from magicgui this data will be shared between different projects. 



> sure, the proposal is to accept JSON schema [like this](https://github.com/tlambert03/npe2/blob/ad10394fa07d005e09ec79e0d712a1c0b818d165/tests/sample/my_plugin/napari.yaml#L15-L21) as a part of the [`contributions` in the manifest](https://github.com/tlambert03/npe2/blob/ad10394fa07d005e09ec79e0d712a1c0b818d165/npe2/manifest/contributions.py#L16)...

Looks really nice. But JSON schema is the name connected with: https://json-schema.org/ wit scheme like https://json-schema.org/learn/examples/card.schema.json. JSON schema is the standard description of data structure in JSON file.  Maybe another name should be selected if the description is in YAML? 

Also, the mechanism of migration should be provided. 

And I'm not sure how to grab Union fields in such schema?

**Comment by tlambert03** [comment]
> For me, it is important to have the possibility of separate data between different projects. There is a possibility now for separate napari settings using the environment variable. But using persistence from magicgui this data will be shared between different projects.

maybe I'm missing what we mean by "project" here.  Do you mean, like you want the same widget to have different settings depending on what project the _user_ is working on?  (that's certainly a good use case that we could try to support)

> Maybe another name should be selected if the description is in YAML?

we likely won't describe it as JSON schema.  but ... it _is_ JSON schema, from json-schema.org under the hood.  https://github.com/tlambert03/npe2/blob/ad10394fa07d005e09ec79e0d712a1c0b818d165/npe2/manifest/configuration.py#L75  (doesn't particularly matter if the user enters it in yaml or json)... 

> And I'm not sure how to grab Union fields in such schema?

the `anyOf` field from json schema captures unions (https://github.com/tlambert03/npe2/blob/ad10394fa07d005e09ec79e0d712a1c0b818d165/npe2/manifest/configuration.py#L92)

**Comment by tlambert03** [comment]
https://json-schema.org/understanding-json-schema/reference/combining.html#anyof

**Comment by Czaki** [comment]
could You explain why You close this issue? 
This is what you point addresses only the first part of the issue. From my point of view, it is not completely cover this part. 

Your comment does not address migrations and does not address moving data from one computer to another. 

By default, JSONschema covers only basic types. Even in your code: https://github.com/tlambert03/npe2/blob/ad10394fa07d005e09ec79e0d712a1c0b818d165/npe2/manifest/configuration.py#L33-L41.  To cover even Enum there is a need to write an extension of this. Such extension is proposed in this issue.  I do not found it in `npe2` code 

I go back to my code which uses JSON schema and reminds its definition. It is not so simple to create the proper schema for more complex data and keep it up to date to reflect inner code structures. 

EDIT. And when I wrote about union I don't think about the difference between int and string, but also two big and depth structures.

**Comment by tlambert03** [comment]
> could You explain why You close this issue?

sorry, that was completely a mistake,  hit the wrong button

**Comment by tlambert03** [comment]
all good thoughts here.  i encourage you leave some comments over at npe2 on the configuration spec.  Migrations are a good thing to be thinking ahead about.  definitely "next level" stuff we hadn't got to yet

**Comment by tlambert03** [comment]
> To cover even Enum there is a need to write an extension of this. Such extension is proposed in this issue. I do not found it in npe2 code

enums are covered in json schema using the [enum](http://json-schema.org/understanding-json-schema/reference/generic.html?highlight=enum#enumerated-values) field ([here](https://github.com/tlambert03/npe2/blob/ad10394fa07d005e09ec79e0d712a1c0b818d165/npe2/manifest/configuration.py#L94) in our spec)

**Comment by Czaki** [comment]
> enums are covered in json schema using the [enum](http://json-schema.org/understanding-json-schema/reference/generic.html?highlight=enum#enumerated-values) field ([here](https://github.com/tlambert03/npe2/blob/ad10394fa07d005e09ec79e0d712a1c0b818d165/npe2/manifest/configuration.py#L94) in our spec)

I still worry about needs of duplicationion information about structure of data. Or there is a plan to allow specify it as path to python enum class?

**Comment by Czaki** [comment]
closed by publishing `nme` package https://pypi.org/project/nme/
