### ISSUE TITLE
Docs page - how new users can contribute tutorials

### ISSUE THREAD

**Issue by GenevieveBuckley** [napari/napari#3532]
We need a docs page explaining how new users can contribute tutorial content.

I think we should assume:
* The user is starting from a jupyter notebook they've put together
* The user needs to know how to convert that into the right format using jupytext
* The user needs to know about how to use demo datasets, or how to contribute their own demo dataset

Useful links:
* https://jupytext.readthedocs.io/en/latest/index.html

**Comment by GenevieveBuckley** [comment]
@DragaDoncila has started working on this here: https://github.com/napari/napari.github.io/pull/206

This may also be relevant: https://github.com/napari/napari.github.io/pull/181

**Comment by DragaDoncila** [comment]
I think this can be closed now that #4168 is in @GenevieveBuckley @sofroniewn?
