### ISSUE TITLE
Tutorial "annotating videos with napari" fails

### ISSUE THREAD

**Issue by ntatsisk** [napari/napari#3534]
Hi, I am following the tutorial "annotating videos with napari" and it throws `IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed`. This occurs when I click to set a new point or press '.' which is the binding for the same functionality. Let me know if the complete error trace is needed. Thanks.

napari 0.4.7
magicgui 0.2.9

**Comment by kevinyamauchi** [comment]
Sorry, I forgot to circle back to this when we merged this fix, @ntatsisk. I believe we fixed this in https://github.com/napari/napari.github.io/pull/114. Please feel free to re-open it if the tutorial is still broken for you when following the updated instructions.
