### ISSUE TITLE
Replace "image pyramid" language with "multiscale image"

### ISSUE THREAD

**Issue by GenevieveBuckley** [napari/napari#3535]
## Problem
The documentation has a lot of language referring to "image pyramids", including mention of an `is_pyramid` keyword argument.

## Solution
This language should be replaced with "multiscale image" instead, and the correct keyword argument to refer to is `multiscale` (this was changed some time ago in the main napari repository, so we need to update the docs to match).

## Where to apply the fix
Affects line 92 - 113 of the documentation at https://github.com/napari/tutorials/blob/master/fundamentals/image.md

**Comment by DragaDoncila** [comment]
I think this can be closed following #4202 @GenevieveBuckley @sofroniewn?
