### ISSUE TITLE
Add documentation for `channel_axis` parameter to the image layer

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#3541]
The image layer tutorial lacks description of the channel_axis parameter of `add_image` and `view_image` - https://github.com/napari/napari/blob/cf73afc7dcd525a02cbf58d13324f330cc8b2d2f/napari/components/viewer_model.py#L545-L550

**Comment by AhmetCanSolak** [comment]
@sofroniewn could you update the links this issue? I think this is an important parameter and I like to make sure it is in the updated documentation.

**Comment by sofroniewn** [comment]
I updated link. This issue was should actually have been closed by https://github.com/napari/napari.github.io/pull/147, the information is now there. 

We actually have a proposal in #3019 to drop the channel axis parameter though. If you'd like us to keep it @AhmetCanSolak maybe you can weigh in there. Thanks!

**Comment by AhmetCanSolak** [comment]
thank you for heads up @sofroniewn
