### ISSUE TITLE
Documentation page for colormaps

### ISSUE THREAD

**Issue by kevinyamauchi** [napari/napari#3542]
As mentioned in https://github.com/napari/tutorials/pull/62#discussion_r430519300, our descriptions of colormaps is outdated. Since more layers can now use colormaps, it probably makes sense to make a single page describing them that we can link to.

**Comment by GenevieveBuckley** [comment]
cc @melissawm - relevant info for the documentation reorganization work

**Comment by chili-chiu** [comment]
see also [issue 3597](https://github.com/napari/docs/issues/39)
