### ISSUE TITLE
Shapes to labels / mask

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#3544]
Add documentation of shapes to labels / mask to our shapes layer tutorial - see [this image.sc post](https://forum.image.sc/t/finding-a-roi-within-an-image-array/32072) and this [examples/shapes_to_labels.py](https://github.com/napari/napari/blob/master/examples/shapes_to_labels.py) for details

**Comment by dstansby** [comment]
I'm struggling to understand what the issue is outlined in the comment above - @miketaormina could you elaborate a bit, ideally with a self contained reproducible example showing what currently happens, and an explanation of what you expect to happen?

**Comment by miketaormina** [comment]
@dstansby Sorry, I'm honestly having a difficult remembering. However, it seems like this issue was likely fixed in [PR 920](https://github.com/napari/napari/pull/920)

**Comment by jni** [comment]
Awesome. 😃 @dstansby thanks for picking these old issues off! Gonna close for now, we can reopen if someone else runs into this again. 🙏
