### ISSUE TITLE
Add save label in tutorials 

### ISSUE THREAD

**Issue by YubinXie** [napari/napari#3546]
Hi,

I'd like to use napari as annotation tool but I am not sure how to download/save the label after annotation. Thanks!

**Comment by GenevieveBuckley** [comment]
We need to make sure this information (especially the compression keyword argument Juan suggests above) is easy to find in the documentation. Maybe in the label layer tutorial? 

cc @melissawm (I think you're keeping some sort of documentation content wishlist, is that right?)

**Comment by melissawm** [comment]
Yup, thanks @GenevieveBuckley !

**Comment by lucyleeow** [comment]
I think this can be closed by #4832
