### ISSUE TITLE
The colors with the same RGBA value look different.

### ISSUE THREAD

**Issue by WenChentao** [napari/napari#3552]
## 🐛 Bug

I modified the color dict in the label layer to show two labels (from the same object) with the same color. However, even when the two labels were assigned with the same RGBA value, their colors look different.

Here is one example:
The first label (47):
<img width="1310" alt="Screen Shot 2021-10-28 at 10 08 44" src="https://user-images.githubusercontent.com/27986173/139170844-4b5acdf7-a1bf-46a4-86dd-120d0a611b98.png">
The second label (55):
<img width="1310" alt="Screen Shot 2021-10-28 at 10 07 46" src="https://user-images.githubusercontent.com/27986173/139170897-04d93edf-6c7a-40cc-82f9-aac12fa67515.png">

Both of them have the same RGBA value: (array([0.35514173, 0.2253761 , 0.20268829, 1.        ]), while their colors look different.

## To Reproduce
Here is a part of my code related to this bug:

1. Add the label layer
```
viewer = napari.Viewer()
viewer.add_labels(initial_data, name='segmentation')
```
2.  Update the data of the labels and colors
```
viewer.layers['segmentation'].data = updated_data # numpy.ndarray,  2D or 3D
viewer.layers['segmentation'].color = updated_color # Dict[int, array]
```

## Expected behavior
I expected the labels with the same RGBA value should be shown with the same color but it did not.

## Environment

 - Please copy and paste the information at napari info option in help menubar here:
napari: 0.4.10
Platform: macOS-10.15.6-x86_64-i386-64bit
System: MacOS 10.15.6
Python: 3.8.5 (default, Sep 4 2020, 02:22:02) [Clang 10.0.0 ]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.21.2
SciPy: 1.5.2
Dask: 2.30.0
VisPy: 0.7.0

OpenGL:
- GL version: 2.1 INTEL-14.7.8
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1440x900, scale 2.0

Plugins:
- console: 0.0.3
- itk-elastix_napari: 0.1.7
- napari-itk-io: 0.1.0
- scikit-image: 0.4.10
- svg: 0.1.5
 - Any other relevant information:

**Comment by DragaDoncila** [comment]
Thank you for raising this issue @WenChentao. I think there is actually an existing issue, #3174, that might have the same root cause. In particular it looks like in this case too the label color thumbnail is "correct" and it's the canvas that's misrendering the label. @sofroniewn any ideas at all?

**Comment by sofroniewn** [comment]
Hmm I'm not sure maybe @perlman could look into this?

**Comment by perlman** [comment]
#3174 was related to changing of the seed values (and failing to update the colorbox) which has been fix.

The issue here is related to all of the other quirky issues with using a discrete colormap for labels. I'll link here when I figure out which issue is the most related.

**Comment by perlman** [comment]
I believe this will be fixed by https://github.com/napari/napari/pull/4935.

**Comment by psobolewskiPhD** [comment]
@WenChentao 
I'm going to close this as fixed. If it still happens for you using napari 0.4.17, please reopen.
