### ISSUE TITLE
Change default dims.point to the centroid of the world extents.

### ISSUE THREAD

**Issue by kevinyamauchi** [napari/napari#3559]
## 🚀 Feature
When a new layer is added, we could set `Dims.point` to the centroid of the new world extents. I think this default behavior is more likely to show an "interesting" slice.

## Motivation

Currently, when a layer is added, the `Dims.point` is set to the minimum of the world extents. As @Czaki pointed out in #2104, this often leads to the default view being blank when loading data (e.g., an out of focus or empty slice in a z stack).

## Pitch

Update the behavior so that when a layer is added the `Dims.point` is set to the centroid of the new world extent (I can't find where that's done at the moment).

**Comment by Czaki** [comment]
This is set here:

https://github.com/napari/napari/blob/c4d1038fc3ed30dc228949cbdedf12826ec2efc2/napari/components/dims.py#L108-L111

Instead of using the 0 there should be used middle between minimum and maximum.

**Comment by alisterburt** [comment]
Love it! Supportive

**Comment by sofroniewn** [comment]
> Love it! Supportive

me too

**Comment by sofroniewn** [comment]
@grlee77 can you give this a go in a new PR - then we can revisit #2104 - thanks!!

**Comment by sofroniewn** [comment]
I was thinking about this more. While I think it makes sense for Points, I wonder if it will be annoying for people looking at timeseries data, you now get a middle timepoint. Maybe for Z-stack data it's ok?

Also, if we go with #2104 then if someone has points + a 3D image layer will the sliders now go out of bounds of the image to show black slices with parts of points. That might be a bit funny.

What does @jni think here? I just worry this might have some unintended consequences and be less desirable in those cases

**Comment by grlee77** [comment]
> Also, if we go with #2104 then if someone has points + a 3D image layer will the sliders now go out of bounds of the image to show black slices with parts of points. That might be a bit funny.

Hmmm... yeah, I had not thought of this, but it does seem like that could happen for points that are more than twice the slider step size. I am not sure if excluding the point's radius from the extent is actually annoying users in practice? I noticed it caused a poor initial zoom when doing some tests on a layer with a single point, but that isn't a typical real-world use case.

**Comment by Czaki** [comment]
> Also, if we go with #2104 then if someone has points + a 3D image layer will the sliders now go out of bounds of the image to show black slices with parts of points. That might be a bit funny.

currently, when you load data with an empty first slice you will get also an empty slice. The question is which case is more often.

**Comment by jni** [comment]
> Also, if we go with #2104 then if someone has points + a 3D image layer will the sliders now go out of bounds of the image to show black slices with parts of points. That might be a bit funny.

@sofroniewn doesn't this assume that the points centroid is outside of the image space? I don't think that would be a common scenario?

> While I think it makes sense for Points, I wonder if it will be annoying for people looking at timeseries data, you now get a middle timepoint. Maybe for Z-stack data it's ok?

Having worked with a lot of time series recently, I think this is actually ok. Typically at the start of the time series, nothing much is going on, and the middle/end really differentiates between the different treatment samples. So I think in this context it would be good. Ditto for z-stacks.

**Comment by sofroniewn** [comment]
Ok, all good - thanks for weighing in @jni let's press on with #3718 then
