### ISSUE TITLE
bug in normalize_callback (or bug in disconnect call)

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#3565]
working on #3184, I just came across a unexpected bug in the `closeEvent` of `QtBaseImageControls`

```pytb
Traceback (most recent call last):
  File "/Users/talley/Dropbox (HMS)/Python/forks/napari/napari/_qt/layer_controls/qt_image_controls_base.py", line 191, in closeEvent
    self.layer.events.disconnect(self)
  File "/Users/talley/Dropbox (HMS)/Python/forks/napari/napari/utils/events/event.py", line 1001, in disconnect
    ret = EventEmitter.disconnect(self, callback)
  File "/Users/talley/Dropbox (HMS)/Python/forks/napari/napari/utils/events/event.py", line 504, in disconnect
    callback, _pass_event = self._normalize_cb(callback)
  File "/Users/talley/Dropbox (HMS)/Python/forks/napari/napari/utils/events/event.py", line 574, in _normalize_cb
    obj = callback[0]()
TypeError: 'QtBaseImageControls' object is not subscriptable
```

It seems to be caused by this line (added in #3217)

https://github.com/napari/napari/blob/9af23fb0ddd8b9804edc84d534095a00b697c41c/napari/_qt/layer_controls/qt_image_controls_base.py#L199

and with some print statements in the `_normalize_cb` method, it looks like the callback variable is _not_ a tuple of weakref on this line (added in #3449) ... and thus fails:

https://github.com/napari/napari/blob/156ad000b2b7d2922d229787df70367ff97c4be9/napari/utils/events/event.py#L574

@Czaki, can you take a look?

**Comment by Czaki** [comment]
> @Czaki, can you take a look?

Maybe I miss something when I create #3449. It should've been possible to disconnect all object events by passing the object itself?

**Comment by tlambert03** [comment]
> It should've been possible to disconnect all object events by passing the object itself?

yeah, I wasn't entirely clear on that myself... but since you also added that [disconnect line in 3217](https://github.com/napari/napari/pull/3217/files#diff-7b43dacbdfe011eea412f799bc5117e8b5cf760ccc0f1024153dcc91f7ca825bR199) I thought you might know

**Comment by Czaki** [comment]
> yeah, I wasn't entirely clear on that myself... but since you also added that [disconnect line in 3217](https://github.com/napari/napari/pull/3217/files#diff-7b43dacbdfe011eea412f799bc5117e8b5cf760ccc0f1024153dcc91f7ca825bR199) I thought you might know

I should remember this, but unfortunately, I miss this. I will create a fix and add the missing test.

**Comment by tlambert03** [comment]
thanks!

**Comment by Czaki** [comment]
There was inproper annotation of `disconnect` function wgich does not contain object in signature.
