### ISSUE TITLE
OpenGL runtime error when a multiscale image is moved outside the canvas

### ISSUE THREAD

**Issue by grlee77** [napari/napari#3567]
## 🐛 Bug

When viewing a multiscale 2D layer, if the object is moved out of the viewer window, a RuntimeError error is raised:
`RuntimeError: OpenGL got errors (Check before draw): GL_INVALID_VALUE`

This is illustrated here:
![Peek 2021-10-31 17-23](https://user-images.githubusercontent.com/6528957/139602114-cb4a4b82-bee2-426c-85e8-e5ae0c221465.gif)

## To Reproduce

1. Run the script below to generate a simple multi-scale layer
2. From the viewer, drag the rectangle until it is not visible and an error window will pop up

```Python
import napari
import numpy as np

with napari.gui_qt():
    viewer = napari.Viewer()
    img = np.ones((256, 512))
    img_multi = [img[::s, ::s] for s in (1, 2, 4)]
    viewer.add_image(img_multi)
```

## Expected behavior

I would not expect this to cause an error (i.e. the same behavior as a non-multiscale 2D view).

## Environment
```
napari: 0.4.12.dev8+g3cb4b85d.d20210923
Platform: Linux-5.10.0-1050-oem-x86_64-with-glibc2.10
System: Ubuntu 20.04.3 LTS
Python: 3.8.10 | packaged by conda-forge | (default, May 11 2021, 07:01:05) [GCC 9.3.0]
Qt: 5.12.9
PyQt5: 5.12.3
NumPy: 1.21.2
SciPy: 1.7.0
Dask: 2021.09.1+11.gaa559ca4
VisPy: 0.9.3

OpenGL:
- GL version: 4.6.0 NVIDIA 465.19.01
- MAX_TEXTURE_SIZE: 32768

Screens:
- screen 1: resolution 1920x1080, scale 2.0

Plugins:
- nibabel: 0.1.dev6+g4395ab5.d20210831
- scikit-image: 0.4.12.dev8+g3cb4b85d.d20210923
```

**Comment by jni** [comment]
Ha, interesting. I guess VisPy isn't too happy if we send an empty array to render. 😬 I guess we can set a minimum crop size and render the minimum off-canvas.  Thoughts @sofroniewn?

e.g. we could add a check here:

https://github.com/napari/napari/blob/785e49a1e4a54f10a09ce87fccb95dc19e3886d5/napari/layers/base/base.py#L1420-L1434

and default corners to a 1-pixel-by-1-pixel "image".
