### ISSUE TITLE
Adding shapes layer (empty) results in divide-by-zero warning

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari/napari#3568]
## 🐛 Bug

When adding a shapes layer using the GUI, a warning is generated:
```
/Users/piotrsobolewski/Dev/miniforge3/envs/TF-StarDist-napari/lib/python3.9/site-packages/napari/layers/shapes/shapes.py:2519: RuntimeWarning: divide by zero encountered in true_divide!
/Users/piotrsobolewski/Dev/miniforge3/envs/TF-StarDist-napari/lib/python3.9/site-packages/napari/layers/shapes/shapes.py:2519: RuntimeWarning: divide by zero encountered in true_divide!
/Users/piotrsobolewski/Dev/miniforge3/envs/TF-StarDist-napari/lib/python3.9/site-packages/napari/layers/shapes/shapes.py:2519: RuntimeWarning: divide by zero encountered in true_divide!
```

All other layers work without any warnings.
In 4.10 I also got such warnings for creating an image layer (eg. open sample image). That was resolved in 4.11. But the shapes layer warning remained in 4.11 and is still present in 4.12. 
See also: https://github.com/napari/napari/issues/3159#issuecomment-909974727
The shapes layer functions normally.
Edit: closing an **empty** shapes layer also triggers the warning.

## To Reproduce

1. Launch fresh napari
2. Add shapes layer using GUI button
Edit: this is important, it seems the warning occurs when the shapes layer is spawned *empty* such as by the GUI button.

## Expected behavior

No warning should be produced.

## Environment

```
napari: 0.4.12
Platform: macOS-12.0.1-arm64-arm-64bit
System: MacOS 12.0.1
Python: 3.9.6 | packaged by conda-forge | (default, Jul 6 2021, 08:51:19) [Clang 11.1.0 ]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.21.0
SciPy: 1.7.0
Dask: 2021.06.2
VisPy: 0.7.0

OpenGL:
- GL version: 2.1 Metal - 76.1
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1680x1050, scale 2.0

Plugins:
- Measurements (skimage regionprops): 0.1.10
- StarDist: 2021.10.25
- Utilities (skimage regionprops): 0.1.10
- aicsimageio-in-memory: 0.4.1
- aicsimageio-out-of-memory: 0.4.1
- animation: 0.0.2
- clEsperanto: 0.10.7
- console: 0.0.4
- napari-tools-menu: 0.1.3
- ome-types: 0.2.6
- scikit-image: 0.4.12
- svg: 0.1.5

```

## Additional context

Note: this is on an Apple Silicon M1, with everything native—I expect more such envs though with the latest Apple releases!

**Comment by psobolewskiPhD** [comment]
The warning refers to a calculation in `shapes.py` `_update_thumbnail`.
Comparing that section to the same function in `points.py` — making a new Points layer does not trigger a warning—it seems like these lines, present in `points.py` but not `shapes.py` are the key?
https://github.com/napari/napari/blob/785e49a1e4a54f10a09ce87fccb95dc19e3886d5/napari/layers/points/points.py#L1354-L1355

This looks like a check to see whether any points are present, which makes sense. However, there does not appear to be an equivalent check in shapes.
Testing with:
```
line = np.array([[11, 13], [111, 113]])
line_prof_layer = viewer.add_shapes(
    line, shape_type="line", edge_color="red", name="Line Profile"
)
```
No warnings. Can close, also no warning. Meanwhile, *closing* an empty shapes layer also generates the same warning.

Edit: a similer, but slightly different approach in `tracks.py`:
https://github.com/napari/napari/blob/c53f34e85c4fa4e2a767521ea7304cb735fa0c4d/napari/layers/tracks/tracks.py#L271-L276

I can't figure out where the equivalent code is for the labels layer, which also spawns empty with no issue.

Edit:
I was able to fix the issue locally by adding that check for being empty:
https://github.com/psobolewskiPhD/napari/commit/aca8e63fbe9e7575364852d2b70bc61e0607e764#diff-8cf0a8f7039380cc36fc53577fb83f0864711525da0f6d9a16f726c645d7e085
but this all relates back to this issue, that the layer types have a different way of doing the thumbnail, which I guess is in progress and will solve this issue.
https://github.com/napari/napari/issues/3409
For example, here I mimic the colormapping of points thumbnails in `shapes.py`:
https://github.com/psobolewskiPhD/napari/commit/11a64409f7b77d10ef6b1a0289a6a2a930084191

**Comment by psobolewskiPhD** [comment]
FYI: I still get this in a new conda env (pyqt via andfoy, rest conda-forge python 3.9.9, but arm64 macOS).
Easy reproducer:
```
import napari

viewer = napari.Viewer()
viewer.add_shapes(None)
```


Here's the napari info:
```
napari: 0.4.13
Platform: macOS-12.1-arm64-arm-64bit
System: MacOS 12.1
Python: 3.9.9 | packaged by conda-forge | (main, Dec 20 2021, 02:41:07) [Clang 11.1.0 ]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.22.0
SciPy: 1.7.3
Dask: 2022.01.0
VisPy: 0.9.4

OpenGL:
- GL version: 2.1 Metal - 76.3
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1680x1050, scale 2.0

Plugins:
- affinder: 0.2.2
- aicsimageio-in-memory: 0.4.1
- aicsimageio-out-of-memory: 0.4.1
- console: 0.0.4
- ome-types: 0.2.10
- scikit-image: 0.4.13
- svg: 0.1.5

```

**Comment by psobolewskiPhD** [comment]
An update:
On live 0.4.14 I still get the div by zero.
But on 0.4.15rc1 I now get an *extra* warning!
```
/Users/piotrsobolewski/Dev/miniforge3/envs/apple-TF28/lib/python3.9/site-packages/numpy/core/numeric.py:2446: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison!
/Users/piotrsobolewski/Dev/napari/napari/layers/shapes/shapes.py:2548: RuntimeWarning: divide by zero encountered in true_divide!
/Users/piotrsobolewski/Dev/napari/napari/layers/shapes/shapes.py:2548: RuntimeWarning: divide by zero encountered in true_divide!
/Users/piotrsobolewski/Dev/napari/napari/layers/shapes/shapes.py:2548: RuntimeWarning: divide by zero encountered in true_divide!
/Users/piotrsobolewski/Dev/napari/napari/layers/shapes/shapes.py:2548: RuntimeWarning: divide by zero encountered in true_divide!
```
I think I managed to get the most recent `main` into my branch and the fix still works, but I still get the FutureWarning, so that must be triggered by something else.

**Comment by tlambert03** [comment]
@psobolewskiPhD, do you still see the divide by error on main?  I'm fixing the other warning in https://github.com/napari/napari/pull/4256, and would be curious to know if you still get it there

**Comment by psobolewskiPhD** [comment]
On line I still get the 3 div by zero.
I did `gh pr checkout 4256` and now I don't get the extra warning (FutureWarning), but i still get the divide by zero warnings:
```
/Users/piotrsobolewski/Dev/napari/napari/layers/shapes/shapes.py:2548: RuntimeWarning: divide by zero encountered in true_divide!
/Users/piotrsobolewski/Dev/napari/napari/layers/shapes/shapes.py:2548: RuntimeWarning: divide by zero encountered in true_divide!
/Users/piotrsobolewski/Dev/napari/napari/layers/shapes/shapes.py:2548: RuntimeWarning: divide by zero encountered in true_divide!
/Users/piotrsobolewski/Dev/napari/napari/layers/shapes/shapes.py:2548: RuntimeWarning: divide by zero encountered in true_divide!
```

I guess this is somehow an arm64 only issue? x86 somehow treats empty data as *not* zero for this division? Anyhow, the fix from the points layer: https://github.com/napari/napari/issues/3568#issuecomment-956115305
still seems to work.

**Comment by tlambert03** [comment]
Your patch in https://github.com/psobolewskiPhD/napari/commit/aca8e63fbe9e7575364852d2b70bc61e0607e764#diff-8cf0a8f7039380cc36fc53577fb83f0864711525da0f6d9a16f726c645d7e085 seems pretty reasonable!  Can you think of any circumstances in which we _wouldn't_ want that?

On a completely unrelated side note, I was shocked to recently realize that you haven't yet contributed a PR to napari! :wink: :wink: :wink:

**Comment by psobolewskiPhD** [comment]
> Your patch in [psobolewskiPhD@aca8e63#diff-8cf0a8f7039380cc36fc53577fb83f0864711525da0f6d9a16f726c645d7e085](https://github.com/psobolewskiPhD/napari/commit/aca8e63fbe9e7575364852d2b70bc61e0607e764#diff-8cf0a8f7039380cc36fc53577fb83f0864711525da0f6d9a16f726c645d7e085) seems pretty reasonable! Can you think of any circumstances in which we _wouldn't_ want that?

I have no idea, I mean checking there is something before making a thumbnail seems to make sense to me. This check is performed in Points and Tracks—in different ways though... I copy-pasta'd the points way here, but one could use the other approach.
In the end I think making all layers behave the same using the same code/approach would make sense? See also this related issue: https://github.com/napari/napari/issues/3409

> On a completely unrelated side note, I was shocked to recently realize that you haven't yet contributed a PR to napari! 😉 😉 😉

What can I say, I'm just a vocal end user.

**Comment by tlambert03** [comment]
That was a not-so-subtle hint for you to make a PR with that patch so we can have you as a contributor :)  I think it's a good solution here.

**Comment by psobolewskiPhD** [comment]
> That was a not-so-subtle hint for you to make a PR with that patch so we can have you as a contributor :) I think it's a good solution here.

Oh, derp. I'll try and figure out how to get back on my fork and that branch this evening (I did `gh pr checkout 4201` to play with the screenshot scaling).
