### ISSUE TITLE
Should we add versioneer to development.txt or INSTALL_REQUIRES in setup.py?

### ISSUE THREAD

**Issue by jni** [napari/napari#357]
I'm trying to copy our version infrastructure for napari-app, and I don't quite grok it. Where is the base version string stored? (ie where does 0.0.9 vs 0.1.0 live, whether it's dev or not) Also, since versioneer is required to run setup.py, does it need to go in the requirements somewhere?

CC @kne42

**Comment by kne42** [comment]
versioneer works based off of the latest git tag

it does not need to be downloaded off of pip because it installs its source code in the repository

**Comment by jni** [comment]
> versioneer works based off of the latest git tag

Ah! Gets me every time :joy: So essentially one should always pull the tags from upstream before building and installing, right?

I also only just noticed the `versioneer.py` file :man_facepalming: 

Thanks for the clarifications @kne42!

**Comment by kne42** [comment]
> So essentially one should always pull the tags from upstream before building and installing, right?

uhhh it should work for a local installation just fine although the wrong version will be shown which can be problematic downstream for those who enforce a specific version of napari

perhaps we should add a `--tags` argument to the pull command on our contributing guide?

**Comment by jni** [comment]
> uhhh it should work for a local installation just fine although the wrong version will be shown which can be problematic downstream for those who enforce a specific version of napari

This is exactly the problem I was running into with #356 and napari-app. To make matters worse, pip now *enforces* this. There appears to be no way to pip install a package with an incompatible version of a dependency. (I tried all possible combinations of `--force` options.)

> perhaps we should add a --tags argument to the pull command on our contributing guide?

That's probably the right approach. I'll reopen this to track it.

**Comment by sofroniewn** [comment]
@kne42 @jni can we get this closed? Not sure of it's difficulty level, but I'm trying to go through our open `0.1` issues and close them out
