### ISSUE TITLE
Provide a way for documentation contributors to preview their documents with the theme from `napari.github.io`

### ISSUE THREAD

**Issue by DragaDoncila** [napari/napari#3572]
## 🧰 Task
After the migration proposed in #3529 is complete, users will be able to contribute documentation by only making PRs to `napari/napari`. However, because the theme and build tooling all lives at `napari.github.io`, they will not be easily able to preview their documents.

We therefore need a way to build a preview using the theme from `napari.github.io` but pointing to `napari` docs sources. 

The best workflow for the contributor (arguably) is having a local preview they can build that refreshes quickly with any new changes, rather than the approach we've taken on the napari hub of previewing in a GitHub Action.

`napari.github.io` already has the capability of local preview using a `yarn` development environment. @codemonkey800 can expand more on how that works. Ideally we could reuse much of this work to preview based on `napari/napari` docs.

@neuromusic and I were thinking of a workflow whereby you could run `make docs` or something similar in your local `napari/napari`, and the minimal content required to build the theme would then be fetched from `napari.github.io` and used to build the theme and provide you with a local preview. @codemonkey800 how feasible is this? What would be the minimum content required locally to run `yarn dev` or a similar command but point it to `napari/napari/docs` instead of the website repo's docs content?

**Comment by melissawm** [comment]
One way of doing this would be defining the theme to be a git submodule.

**Comment by codemonkey800** [comment]
My impression from #3529 is that the `napari.github.io` repo would be restructured to be only the theme and tooling, so it already contains the minimum content required for building the theme. @melissawm's git submodule solution also sounds good to me.

Another thing I thought of was creating an npm or pypi package that exposes a CLI for building the theme, but it might be overkill for now

**Comment by DragaDoncila** [comment]
@melissawm and @codemonkey800 thanks for weighing in! I haven't run into git submodules before, so I just wanted to check my understanding.

If we were to go down that path we would:
- add `napari.github.io` as a submodule to the napari repo
- people who wanted to contribute docs would need to `init` the submodule after cloning `napari`, or clone using `--recurse-submodules`
- once the submodule is initialized, they could use the same dev environment workflow as for `napari.github.io` but it would be configured to point to a folder within `napari` e.g. `napari/docs`?

I do like the dev workflow we currently have for the theme, so it would be great if we could duplicate that without duplicating the actual code & config.

I know I suggested over on #3529 generating a preview on PRs (@codemonkey800 suggested Netlify as an easy solution). I think this would be valuable for new users contributing documentation, but core developers would probably prefer the local dev workflow as it's much faster, so I'd say a PR preview service is a stretch goal and probably optional?

**Comment by melissawm** [comment]
> * add `napari.github.io` as a submodule to the napari repo
> 
> * people who wanted to contribute docs would need to `init` the submodule after cloning `napari`, or clone using `--recurse-submodules`
> 
> * once the submodule is initialized, they could use the same dev environment workflow as for `napari.github.io` but it would be configured to point to a folder within `napari` e.g. `napari/docs`?

Yes, that is what I am imagining, but I'm not entirely familiar with the whole deployment workflow as it is right now so I could be underestimating the work here :)

> I know I suggested over on #3529 generating a preview on PRs (@codemonkey800 suggested Netlify as an easy solution). I think this would be valuable for new users contributing documentation, but core developers would probably prefer the local dev workflow as it's much faster, so I'd say a PR preview service is a stretch goal and probably optional?

I'm ok with that, but I can tell you it can be very useful when reviewing docs PRs - it's easy to see build issues for both submitters and reviewers, and if the build is successful keeps the review workflow entirely on github.

**Comment by codemonkey800** [comment]
> > I know I suggested over on #3529 generating a preview on PRs (@codemonkey800 suggested Netlify as an easy solution). I think this would be valuable for new users contributing documentation, but core developers would probably prefer the local dev workflow as it's much faster, so I'd say a PR preview service is a stretch goal and probably optional?

> I'm ok with that, but I can tell you it can be very useful when reviewing docs PRs - it's easy to see build issues for both submitters and reviewers, and if the build is successful keeps the review workflow entirely on github.

I'm fine with it being a stretch goal. I think it's mostly useful for PR reviewers, less technical folks, and people who don't want to install the required theme tooling 😄

**Comment by jni** [comment]
@codemonkey800 

> people who don't want to install the required theme tooling :smile: 

:raising_hand: 

I use the PR-built-docs *all the friggin time* on user contributions over at scikit-image. Compare the workflow:

- cd napari
- gh pr checkout (number)
- cd ../napari.github.io
- make build  # or whatever command it is to build the docs
- open _build/index.html

vs:

- click a link

All this to say, I think a gh action to build the docs on PRs should be a primary goal, not a stretch goal.

**Comment by GenevieveBuckley** [comment]
I agree with Juan's comment. 

I would totally click a link, but much less reliably build the docs locally to check. 

Plus, the whole idea is that people shouldn't need to set up a development environment in order to contribute a tutorial or similar to the docs. They should be able to make their tutorial using the napari release they are *already* using, then contribute that without much extra effort. Setting up a development environment and working out how to build docs is a lot of extra friction.

**Comment by neuromusic** [comment]
> the whole idea is that people shouldn't need to set up a development environment in order to contribute a tutorial or similar to the docs

This is a good point. Moreover, as @DragaDoncila's contributor guide work has noted, folks should be able to contribute a new tutorial or update the docs without even cloning the repo locally, just using Github's editing and contribution mechanisms.

I'll +1 the Netlify suggestion. It's a great platform & it looks like the [free starter version](https://www.netlify.com/pricing/) should support our needs here (incl perhaps hosting, instead of github.io?). This would also add CI checks for docs building, to help ensure that napari changes don't break the docs: https://docs.netlify.com/site-deploys/notifications/#github-commit-statuses

For the first step, though, I agree with @codemonkey800 ... let's get this working for a local workflow, then get that workflow building for each PR.

**Comment by DragaDoncila** [comment]
Yeah, definitely didn't mean to understate the importance of having a preview built on documentation PRs - it's important for a lot of people and makes the process much smoother.

When I said "stretch goal" I meant, let's stretch this out until we've built a local workflow first 😄

**Comment by melissawm** [comment]
Now that all the docs are building locally with the napari-sphinx-theme, is there anything left to do here?

**Comment by DragaDoncila** [comment]
@melissawm I think the only remaining work for previewing docs is to provide an "in PR" preview, but we do already provide the build artifact and I think this would also be part of broader discussion on hosting going forward so I'm not sure if we want to keep this open, or close in favour of a specific, much lower priority issue (imo), of providing in-PR previews.
