### ISSUE TITLE
"import pandas as pd" cause napari menu to become unresponsive: "File/Open File(s)..." etc not working. 

### ISSUE THREAD

**Issue by RoccoDAnt** [napari/napari#3578]
## 🐛 Bug

Hello, I would need to use pandas to save a .csv file. If I "import pandas as pd" in my plugin, the napari menu becomes not responsive. If I comment out that specific import, the menu works fine: I can open images/stacks etc.

I am using pandas and other packages in conjunction with magicgui to build the interface.

## To Reproduce
Use napari 0.4.10
Try to install a simple plugin template such as:

        from napari_plugin_engine import napari_hook_implementation
        from napari.layers import Image, Labels, Layer, Points
        from magicgui import magicgui, magic_factory
        import napari
        from napari import Viewer
        from magicgui.widgets import SpinBox, FileEdit, Slider, FloatSlider, Label, Container, MainWindow, ComboBox, TextEdit, PushButton, ProgressBar
        import skimage
        import skimage.filters
        from skimage.feature import peak_local_max
        from skimage.transform import rotate
        from skimage.segmentation import watershed
        from skimage import measure
        import numpy as np
        import pandas as pd
        
        @magicgui(labels=False,
                 label={'widget_type':'Label', 'value':" apply Threshold"},
                 threshold={'widget_type': 'FloatSlider', "max": 65535.0, 'min':0.0},
                 call_button="Apply",
                 persist=True
                 )
        def threshold(viewer: 'napari.Viewer', label, layer: Image, threshold: int = 1)-> napari.types.ImageData:
            if layer:
                th=layer.data>threshold
                viewer.add_image(th, name='Threshold th='+str(threshold)+' of '+str(layer.name))
        
        @magic_factory(
                       auto_call=True,
                       call_button=True,
                        )
        def launch_test(
                viewer: 'napari.Viewer',
                ):
        
                dock_widgets=MainWindow(name='mywidget', annotation=None, label=None, tooltip=None, visible=True,
                                       enabled=True, gui_only=False, backend_kwargs={}, layout='vertical', widgets=(), labels=True)
                viewer.window.add_dock_widget(dock_widgets, name='mytest')
                dock_widgets.show()
                dock_widgets.insert(1, threshold)
                prop={'Parent_label': 1,'Area': 1}
                prop_df=pd.DataFrame(prop)
                prop_df.to_csv(r'C:\Users\dantuor\Documents\res.csv')

1. Try to open a file with napari menu. It works fine.
2. Install the plugin with the "Install by name/url" (use path to the local folder) 
3. Retry to open the napari menu: no file browser opens
 
## Expected behavior
napari menu and FileEdit widgets opening when user clicks on them

## Environment

        napari: 0.4.10
        Platform: Windows-10-10.0.19041-SP0
        Python: 3.8.0 | packaged by conda-forge | (default, Nov 22 2019, 19:04:36) [MSC v.1916 64 bit (AMD64)]
        Qt: 5.15.2
        PyQt5: 5.15.6
        NumPy: 1.21.3
        SciPy: 1.7.1
        Dask: 2021.10.0
        VisPy: 0.9.3
        
        OpenGL:
        - GL version: 4.6.0 - Build 27.20.100.8681
        - MAX_TEXTURE_SIZE: 16384
        
        Screens:
        - screen 1: resolution 1600x900, scale 1.0
        
        Plugins:
        - console: 0.0.4
        - napari-test: 0.1.0
        - scikit-image: 0.4.10
        - svg: 0.1.5

If I am not wrong, pandas is already a requirement for either napari and/or magicgui. Maybe pandas is imported somewhere upstream and my import is conflicting with a previous one? 

Thank you!

**Comment by RoccoDAnt** [comment]
Curiously, if I use instead "[datatable](https://github.com/h2oai/datatable)" (R package) napari menu shows no issue:

    import datatable as dt 

works fine for my purpose but is a bit weird not being able to use pandas.

For interested developers, the template above works with the correction:

    a=np.array([1,2,3])
    b=np.array([1,2,3])
    prop={'Parent_label': a,'Area': b}

Any suggestion on how to fix pandas import is welcome!
Thank you.

**Comment by alisterburt** [comment]
Very strange, thanks for the bug report @RoccoDAnt !

Could you try updating napari to `0.4.12` to see if the problem persists?

Another troubleshooting step you could try if it persists is to restart napari after installing the plugin - I remember this being a required step fairly recently but am not sure whether that's still the case.

Let us know how you get on 🙂

**Comment by RoccoDAnt** [comment]
Hi @alisterburt , unfortunately updating to version 0.4.12 does not fix the import, and the issue persists also closing and reopening napari.
For the moment being, I am using `datatable` instead of `pandas`.
Thanks for your help!

**Comment by guiwitz** [comment]
Hi @RoccoDAnt,

this line:
```python
prop={'Parent_label': 1,'Area': 1}
prop_df=pd.DataFrame(prop)
```
is not a valid Pandas statement. If you want to create a dataframe from a dictionary, the elements of the dictionary have to be a list or array e.g.
```python
prop={'Parent_label': [1], 'Area': [1]}
prop_df=pd.DataFrame(prop)
```
Maybe it's just this that makes your plugin fail and then perturbs napari?

**Comment by RoccoDAnt** [comment]
Hi @guiwitz very good observation. It was my error while reporting the issue, the dictionary had instead arrays like 
`'Area': properties['area']`

Thanks for the good point anyway. As said I moved on by using another package but it might be relevant, as Pandas is foundational!

**Comment by jaimergp** [comment]
I am seeing Python packaged by conda-forge but PyQt v5.15 (which was not available on conda-forge back then when this issue was created; it should have been 5.12). This makes me thing that a mixture of conda and pip install commands were used to obtain napari, which can result in all kinds of incompatibilities. As such I am inclined to diagnose this as an installation error that could be fixed by reinstalling napari with a single tool:

```
$ conda create -n napari napari pandas
$ conda activate napari
$ napari
```

If the team agrees, we can close this issue.
