### ISSUE TITLE
Incorrect number of sliders for particular shapes

### ISSUE THREAD

**Issue by jni** [napari/napari#358]
## 🐛 Bug

This might be due to trying to be too clever with detecting multichannel, but maybe not... If I try to visualise an array of shape (51, 5, 2, 196, 171), I only get two sliders, corresponding to dimensions 0 and 2. I have no way to scroll through dimension 1. Additionally, there are too many stops for dimension 2, which can be set to three positions, 0, 1, and 2. The status happily tells me that I'm looking at coordinates [0, 0, 2, <whatever>, <whatever>]. 

Note: this was discovered while trying to visualise `mitosis.tif` from the Fiji examples, but random data does the trick (see below)

## To Reproduce

In IPython:

```python
import numpy as np
import napari

image = np.random.random((51, 5, 2, 196, 171))
napari.view(image)
```

As a script:

```python
import numpy as np
import napari
import napari.util

image = np.random.random((51, 5, 2, 196, 171))
with napari.util.app_context():
    napari.view(image)
```

## Expected behavior

I get three sliders, and they range from 0-50, 0-4, and 0-1.

## Environment

 - napari Version (e.g., 1.0): master
 - OS (e.g., Linux): Ubuntu 18.04
 - Python version: 3.6
 - Any other relevant information:

**Comment by sofroniewn** [comment]
The too many stops bug is true for all of our sliders and noted in #287, but has not been fixed yet. I'm surprised that you're missing a slider though, and I'll look into it
