### ISSUE TITLE
Test failure when image.data.shape is an ndarray.

### ISSUE THREAD

**Issue by Carreau** [napari/napari#3589]
## 🐛 Bug
`napari/_tests/test_adding_removing.py` test fails with the earliest supported version of tensorstore:

```
setup.cfg
109:    tensorstore>=0.1.10,!=0.1.11
```

Because at some point:

```
napari/utils/context/_layerlist_context.py:59: in _same_shape
    return len({getattr(x.data, "shape", ()) for x in s}) == 1
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

.0 = <set_iterator object at 0x7ffaf154ca40>

>   return len({getattr(x.data, "shape", ()) for x in s}) == 1
E   TypeError: unhashable type: 'numpy.ndarray'
```

That is because with this version of tensor store, the data.shape is itself an ndarray instead of tuple. 

this is fixed in later version of tensor store, but I still want to open this to ask:

Should we make the assumption that image.data.shape is always a hashable item ? Always a tuple? or do we want to support image backing with shape that are non-hashable. 

I'm in favor of assuming data.shape is a tuple of int. 

If so we want to bump minimal version of tensor store, and maybe fail earlier if an data.shape is a non tuple ?

**Comment by perlman** [comment]
> If so we want to bump minimal version of tensor store, and maybe fail earlier if an data.shape is a non tuple ?

Sounds good to me! Unlike numpy, there isn't a large community of tensorstore users out there relying on older releases.

**Comment by tlambert03** [comment]
The array api states tuple, so I think we should go with that:

https://data-apis.org/array-api/latest/API_specification/array_object.html#shape
