### ISSUE TITLE
Modify order of test execution

### ISSUE THREAD

**Issue by Czaki** [napari/napari#3592]
## 🚀 Feature

Use `pytest_collection_modifyitems` for reorder test from the most basic one (event system) through middle structures (labels definition) to Qt. 

## Motivation

For default napari pytest run is finished after 5-th fail. But currently, the first Qt tests are executed. So this test could find bugs in some basic structures but may not be clear. 

## Additional context

https://github.com/4DNucleome/PartSeg/blob/19ee18184a0ac72229d0124fa59beadb0d48b23d/package/tests/conftest.py#L194-L198

**Comment by dalthviz** [comment]
Hi, maybe https://pypi.org/project/pytest-order/ could be useful for this?

**Comment by Czaki** [comment]
it was fixed in #4483

**Comment by Czaki** [comment]
Thanks for pointing out that this issue was still opened. The pytest-order requires to much work.
