### ISSUE TITLE
running_as_bundled_app no longer works

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#3596]
## 🐛 Bug
The `running_as_bundled_app`  function no longer seems to work, and the reason is that the METADATA file currently produced (at `app/napari-...dist-info/METADATA`) is extremely minimal, and lacks the stuff (like Briefcase-Version) that is "supposed" to be in there as per https://briefcase.readthedocs.io/en/latest/how-to/access-packaging-metadata.html?highlight=briefcase-version.

@goanpeca, @jaimergp ... do you have any ideas why that might be?
Perhaps we can come up with another strategy?  like adding a package metadata flag ourselves (in `bundle.py` that we could look for?

**Comment by goanpeca** [comment]
>app/napari-...dist-info/METADATA

@tlambert03 what command produces that file? is this a `python sdist...` thing that might have changed? Maybe we have to pass a flag to preserve whatever information is missing?

Or maybe I am not understanding the issue 🤔 

---

Also was this the result of the last PR that added constructor things?

**Comment by jaimergp** [comment]
I gave up with the metadata approach and introduced a sentinel file next to `sys.executable` in my PR.

See [creation](https://github.com/napari/napari/pull/3555/files#diff-192446c64cc8dd900288f1523d9d032513bf68066f0c0ad4fd3a29b8baf6fd3bR226-R234) and [detection](https://github.com/napari/napari/pull/3555/files#diff-09b82be2ee4fc3ca890d1d940d9b55e60d35290e15ad69d74f53734da25dda8cR15-R32).

**Comment by tlambert03** [comment]
> @tlambert03 what command produces that file?

briefcase itself, during installation, based on the setup.cfg and pyproject.toml in the project

> See creation and detection.

that works for me!  any chance we could get that in main?  or does it really require the full toolchain that you're working on there?

**Comment by jaimergp** [comment]
Yep I'll port it, it's totally independent from conda.
