### ISSUE TITLE
Disabled controls in widgets do not have the correct style

### ISSUE THREAD

**Issue by MosGeo** [napari/napari#3601]
## 🐛 Bug
When disabling a control using the setEnabled function, the styles of the controls are not correct. Note that the a qpushbutton become transparent and a qcombobox does not change the styling when it was disabled.

![image](https://user-images.githubusercontent.com/10503349/141262455-e00d556c-f28e-493b-b606-e30c9b254780.png)

## To Reproduce

```python
import napari
from napari.viewer import Viewer
from qtpy.QtWidgets import QWidget, QPushButton, QVBoxLayout, QComboBox

class MyTestTool(QWidget):

    viewer: Viewer

    def __init__(self):
        super().__init__()
        layout = QVBoxLayout()
        self.btn = QPushButton("I am a dummy button that doesn't do anything looking weired", parent=self)
        self.btn.setEnabled(False)
        layout.addWidget(self.btn)

        self.checkbox = QComboBox(parent=self)
        self.checkbox.addItem("I am a dummy combobox")
        self.checkbox.setEnabled(False)
        layout.addWidget(self.checkbox)

        self.btn2 = QPushButton("Toggle the dummies (currently they are enabled: False)", parent=self)
        self.btn2.clicked.connect(self.toggle)
        layout.addWidget(self.btn2)

        self.setLayout(layout)

    def toggle(self):
        is_enabled = self.checkbox.isEnabled()
        self.checkbox.setEnabled(not is_enabled)
        self.btn.setEnabled(not is_enabled)
        self.btn2.setText(f"Toggle the dummies (currently they are enabled: {not is_enabled})")

napari_viewer = napari.viewer.Viewer()
widget = MyTestTool()

dock_widget = napari_viewer.window.add_dock_widget(widget, name="Test Tool")

napari.run()
```

I expected all the disabled controls to be grayed out automatically. For example

![image](https://user-images.githubusercontent.com/10503349/141262923-dc366ede-343d-424c-9931-36a38c669d7a.png)

```python 
import sys
from PyQt5 import QtGui
from PyQt5.QtWidgets import QApplication, QVBoxLayout, QWidget, QPushButton, QLabel, QComboBox

def window():
   app = QApplication(sys.argv)
   w = QWidget()

   layout = QVBoxLayout()
   b = QPushButton("hellowWorld", parent=w)
   b.setEnabled(False)
   layout.addWidget(b)

   checkbox = QComboBox()
   checkbox.addItem("I am a dummy combobox")
   checkbox.setEnabled(False)
   layout.addWidget(checkbox)

   w.setLayout(layout)
   w.setWindowTitle("PyQt")
   w.show()
   sys.exit(app.exec_())
	
if __name__ == '__main__':
   window()
```

## Environment

napari: 0.4.12
Platform: Windows-10-10.0.19043-SP0
Python: 3.8.10 (tags/v3.8.10:3d8993a, May 3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]
Qt: 5.15.2
PyQt5: 5.15.6
NumPy: 1.21.4
SciPy: 1.7.2
Dask: 2021.11.1
VisPy: 0.9.3

OpenGL:
- GL version: 4.6.0 - Build 27.20.100.9621
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1620x1080, scale 2.0

Plugins:
- aicsimageio-in-memory: 0.4.1
- aicsimageio-out-of-memory: 0.4.1
- console: 0.0.4
- ome-types: 0.2.9
- scikit-image: 0.4.12
- svg: 0.1.5

## Additional context

It seems that napari uses a customized utility function to gray out and disable control `disable_with_opacity` (https://github.com/napari/napari/blob/c28b47a05ae1ef64432ff37c2d246ea056828e30/napari/_qt/utils.py#L143-L150) as noted by Alistor. I don't understand the reasoning for this. Furthermore, even if napari is using it, I don't expected plugins to use it and I think the expected default behavior should be the normal one.

**Comment by alisterburt** [comment]
Hey @MosGeo - thanks for taking the time to put together a nice minimal example, I agree this looks wrong!

For the button, the piece of qss we have to modify can be found here

https://github.com/napari/napari/blob/8981dbc4a179850fd3524420d8b339ad31e793a9/napari/_qt/qt_resources/styles/00_base.qss#L85-L87

e.g. modifying this to 
```qss
QPushButton:disabled {
  background-color: {{ darken(foreground, 20) }};
}
```
gives the following (which is also incorrect, just demonstrates the change
![image](https://user-images.githubusercontent.com/7307488/141270587-a1565bd7-1f40-44a5-acc1-21fce9f6b675.png)


I'm not super familiar with qss and haven't done a deep dive but I can't see an equivalent of `darken` or `lighten` for `reduce opacity` - I can take a look in more detail later but maybe @tlambert03 or @goanpeca will more immediately know the solution

**Comment by MosGeo** [comment]
@alisterburt Thanks for the note. Interesting. This is my first time seeing qss. It looks very similar to css.

**Comment by dalthviz** [comment]
Hi, checking seems like this was fixed with PR https://github.com/napari/napari/pull/5381 However, that also introduced a regression for some widgets that get disabled in the layers control section (issue https://github.com/napari/napari/issues/5445 ). After some testing, probably the style rule for disabled widgets could be something like this:

```
QWidget[emphasized="false"]:disabled, QComboBox:disabled {
  background-color: {{ background }};
  selection-background-color: transparent;
  border: 1px solid;
  border-color: {{ foreground }};
  color: {{ opacity(text, 90) }};
}
```

**Comment by psobolewskiPhD** [comment]
@dalthviz Thanks for checking this! It was also on my to-do list ❤️ 
Do you think this should be added to https://github.com/napari/napari/pull/5446
or shall we merge that and plan a new PR to better adress this?

**Comment by dalthviz** [comment]
> or shall we merge that and plan a new PR to better adress this?

Creating a new PR sounds good to me (with that we can check for a better style rule for the disabled widgets than the one above :+1:).

Thanks for the quick response @psobolewskiPhD !
