### ISSUE TITLE
Test bundle installation on CI?

### ISSUE THREAD

**Issue by jaimergp** [napari/napari#3602]
## 🧰 Task

Right now we have CI to test that the bundles can be _created_ across platforms, but we do not try to install them and see if at least we can get the `napari --help` output. We can always check the bundles locally and run the installation (which can take a few mins), but right now we don't have a consistent check protocol across OSs.

Thoughts? Is this a good idea or overkill?

**Comment by tlambert03** [comment]
I'm for it if it's not too much trouble

**Comment by Czaki** [comment]
In PartSeg, I have a particular command-line argument `_test`, which performs a basic test of the bundle (with importing modules, creating potentially problematic objects, but without showing a window or starting qt event loop).

Maybe it could be a good starting idea for a testing bundle on CI?

Here is link to my code: https://github.com/4DNucleome/PartSeg/blob/7413e5c60e779a7ae81cbfb061459d4081ce1af5/package/PartSeg/launcher_main.py#L26

This approach requires that the installer need to be possible to run in windowless mode (PartSeg bundle need only unpack, not installation as is PyInstaller output).
