### ISSUE TITLE
Feature request: key-hold callbacks

### ISSUE THREAD

**Issue by alisterburt** [napari/napari#3603]
## 🚀 Feature
Auto repeating keypress callbacks

## Motivation
Sometimes I want an action to be repeated whilst a key is held down, rather than fired once on key press and once on key release.
A concrete example would be keyboard controls for the 3D camera, you don't want to repeatedly press the button to shift you by many small increments in a particular direction. Instead, you want to press and hold the button.

## Pitch

Some supported API for repetition of behaviour whilst a key is held down. This could be an extension of the current 'bind_key' API or a new API, whichever we think is more appropriate. 

A similar API to that of mouse drag callbacks could be considered and that consistency may be useful for end users. If we go this route it may be hard to keep backwards compatible though 
https://github.com/napari/napari/blob/8981dbc4a179850fd3524420d8b339ad31e793a9/examples/custom_mouse_functions.py#L53-L67

## Alternatives

One way this can achieved now is by activating a context which enables your behaviour on key press then deactivating this context on key release. This is how we do pan and zoom whilst holding the space bar currently and how I've been working in my own work.

In the example below, switching to `PAN_ZOOM` mode is the 'activator' of the context, connection/disconnection of relevant callbacks happens behind the scenes on mode change.

https://github.com/napari/napari/blob/8981dbc4a179850fd3524420d8b339ad31e793a9/napari/layers/points/_points_key_bindings.py#L13-L27

## Additional context

This feature is currently disabled in napari here

https://github.com/napari/napari/blob/8981dbc4a179850fd3524420d8b339ad31e793a9/napari/utils/key_bindings.py#L479-L487

**Comment by psobolewskiPhD** [comment]
@alisterburt I think https://github.com/napari/napari/pull/5086 has added exactly this, for example the brush size keybinds. Can we close this?

**Comment by alisterburt** [comment]
absolutely! Thanks @psobolewskiPhD
