### ISSUE TITLE
Adding single item to empty vectors layer results in no drawn object

### ISSUE THREAD

**Issue by alisterburt** [napari/napari#3605]
## 🐛 Bug

Creating an empty vectors layer then adding vectors to it leads to all vectors except the first one being rendered.

I've dug into it a bit, the data appears to be correctly set on the napari side and it's just the rendering which is borked, I'm not sure if the problem is on the vispy side or something to do with how we're passing things to vispy in this situation.

https://user-images.githubusercontent.com/7307488/141323753-9fc6919d-e24e-416c-bc6c-a67af3ad61cf.mp4

## To Reproduce
```python
import numpy as np

import napari

pos = np.array([0, 0, 0])
dir = np.array([1, 0, 0])
first_vector = np.stack((pos, dir), axis=0)  # (2, 3)
second_vector = np.stack((pos + 1, dir), axis=0)  # (2, 3)

single_vector = first_vector[np.newaxis, ...]  # (1, 2, 3)
two_vectors = np.stack((first_vector, second_vector), axis=0)

viewer = napari.Viewer(ndisplay=3)

# works
single_vector_layer = viewer.add_vectors(data=single_vector)

two_vectors_layer = viewer.add_vectors(data=two_vectors)

# nothing rendered
start_empty_single_vec_layer = viewer.add_vectors(
    name='empty -> 1 vector', data=None, ndim=3
)
start_empty_single_vec_layer.data = single_vector

# only shows second vector
start_empty_two_vec_layer = viewer.add_vectors(
    name='empty -> 2 vectors', data=None, ndim=3
)
start_empty_two_vec_layer.data = two_vectors

# works
single_vectors_layer_2 = viewer.add_vectors(
    name='single vector replaced', data=np.random.random(size=(1, 2, 3))
)
single_vectors_layer_2.data = single_vector
napari.run()
```

## Expected behavior

All vectors in `Vectors.data` should be rendered after updating the data in an empty vectors layer.

## Environment
environment is napari main, not sure why version is showing up as 0.1.10

napari: 0.1.10.dev639+gab7bb40a.d20211019
Platform: macOS-11.6-x86_64-i386-64bit
System: MacOS 11.6
Python: 3.9.7 | packaged by conda-forge | (default, Sep 29 2021, 19:23:19)  [Clang 11.1.0 ]
Qt: 5.15.2
PyQt5: 5.15.5
NumPy: 1.21.2
SciPy: 1.7.1
Dask: 2021.09.1
VisPy: 0.9.0

OpenGL:
  - GL version:  2.1 ATI-4.6.20
  - MAX_TEXTURE_SIZE: 16384

Screens:
  - screen 1: resolution 2560x1440, scale 2.0

Plugins:
  - console: 0.0.4
  - scikit-image: 0.1.10.dev639+gab7bb40a.d20211019
  - svg: 0.1.5

**Comment by psobolewskiPhD** [comment]
This is fixed.
Here is the `empty -> 2 vectors` case
<img width="1337" alt="image" src="https://github.com/user-attachments/assets/6ec5d466-427d-4bd7-b05d-9c7e23a5cc86">
And `empty -> 1 vector` case:
<img width="1337" alt="image" src="https://github.com/user-attachments/assets/cf0cb342-9dc1-4d3d-8fda-520e8414b5a1">
