### ISSUE TITLE
Vendored tests failing for darkdetect

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#3619]
## 🧰 Task
There is a new version of [darkdetect](https://github.com/albertosottile/darkdetect) out now causing our vendored test to fail.

There was some discussion around whether to vendor or not in the original PR - see https://github.com/napari/napari/pull/3370#issuecomment-921321704, which lead to the test getting created.

Now that a new version is out, I'm curious should we just update all the files? If so is there an easy tool to do this? Or do we actually want to end up depending on package. I don't mind, I just want to see our tests all passing again :-)

Thoughts @jni @Carreau @goanpeca and anyone else interested?

**Comment by tlambert03** [comment]
it would also be nice to have this test on a cron job instead of PRs... not necessary to have PRs fail because our vendored code is behind

**Comment by sofroniewn** [comment]
> it would also be nice to have this test on a cron job instead of PRs... not necessary to have PRs fail because our vendored code is behind

yeah, that's a good idea too!

**Comment by Carreau** [comment]
@tlambert03  did #3626, 

What we can even do is use https://github.com/marketplace/actions/create-pull-request so that when `tools/check_vendored_modules.py` find changes, it actually send a PR with updates. 

Drawbacks is it will keep sending it until the first one is merge so we may want to use `0 2 * * 1` to only make PRs on monday :-)

**Comment by Carreau** [comment]
Actually correcting myself:

> The default behaviour of the action is to create a pull request that will be continually updated with new changes until it is merged or closed.
