### ISSUE TITLE
Long layer names get cut off

### ISSUE THREAD

**Issue by kevinyamauchi** [napari/napari#3620]
## 🐛 Bug

When layers have long names, they get cut off in the layer list.

cc @imagejan

## To Reproduce

```
import napari
import numpy as np

data = np.random.random((30, 30))

viewer = napari.view_image(data, name='asdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfadfasdfaasd')

napari.run()
```

## Expected behavior
It should be possible to see the name,.

## Environment

 - Please copy and paste the information at napari info option in help menubar here:

 - Any other relevant information:

**Comment by imagejan** [comment]
Hovering the mouse over the layer name is sufficient to see the full name, but it would be great if the panel size was adjustable by dragging its border, just as the other panes (i.e. console and plugin dialogs).

**Comment by brisvag** [comment]
I agree that the left are ashould be resizeable like the bottom and right dock widget areas. Are there reasons why we wouldn't want this?

**Comment by schoinh** [comment]
I came here to post about this same issue, specifically to request that the left panel width be made adjustable. 

We're working on the AICS segmenter plugin, and as it gets more complex, we are currently appending information about layers created during a workflow to the layer name. So the layer names are getting longer, with important distinguishing info often at the end of the layer name, and the only way to see them is to hover or click on the name. An ideal long term solution for this would be to have a more proper way to save and display metadata about a layer, but as a short-term solution, just having the left panel expandable would make things much more usable! Thanks!

**Comment by schoinh** [comment]
Seems closely related to #2470

**Comment by goanpeca** [comment]
Will start working on this :)

**Comment by JoOkuma** [comment]
cc @merlinzebra

**Comment by brisvag** [comment]
With #4368, the panel is now adjustable; closing this!
