### ISSUE TITLE
Use imageio imwrite instead of imsave in notebook screenshot

### ISSUE THREAD

**Issue by Carreau** [napari/napari#3650]
## 🧰 Task

See https://github.com/imageio/imageio/pull/688#issuecomment-973125411 for background. 
Simple code is better code.

**Comment by FirefoxMetzger** [comment]
Note: `imsave` is simply an alias of `imwrite` (https://github.com/imageio/imageio/blob/f48bace7d9cbc1858814e0e26c7ed8895eee1012/imageio/__init__.py#L43); both functions can write to `"<bytes>"`.

**Comment by psobolewskiPhD** [comment]
As far as I can tell this has been implemented in https://github.com/napari/napari/commit/45044be5c04f79a7a59e2ce229e8ee97248ef4fc
