### ISSUE TITLE
Events reference is blank

### ISSUE THREAD

**Issue by DragaDoncila** [napari/napari#3654]
## 📚 Documentation
Hi team, @chili-chiu and I were hoping to make use of the recently merged events reference from #2750, however it appears the tables aren't being populated as we expected i.e. they're blank:

![image](https://user-images.githubusercontent.com/17995243/142502268-9db08b59-a89b-49df-b8eb-904df984386f.png)

[Reference link](https://napari.org/guides/stable/events_reference.html)

I know the tables were supposed to be populated by a script but it looks like that's not happening. It could be an issue with the content being copied across to `napari.github.io`? @tlambert03 any ideas?

**Comment by tlambert03** [comment]
my guess is that the `yarn build` command, that is used by the [github.io site](https://github.com/napari/napari.github.io/blob/main/package.json#L11) is not running the scripts that are [run in the napari repo](https://github.com/napari/napari/blob/main/Makefile#L7-L8) (specifically, `update_preference_docs` and `update_event_docs`)

there are a lot of cooks in this documentation kitchen :joy: ... as the `github.io` site changes the build pipeline, i think we're going to need a way for people who are not closely following the `yarn build` stuff to know that what they do over at napari/org is going to work over at `github.io`... and that's a question for the github.io team.  `github.io` using our makefile might be a solution, but I'm also happy to do whatever is recommended.

I'll note that preferences are also not working.  click on "Setting Preferences" on [this page](https://napari.org/guides/stable/index.html)  for a funny surprise.

**Comment by tlambert03** [comment]
let me add a bit more detail here:

people paying attention to docs in the main napari repo (where most of the documentation source lives) pay attention to 1 or 2 things:

- the `Build & Publish Docs` workflow [here](https://github.com/napari/napari/blob/291a11a70fdc8210bf3053ec6bc0e3db3c416d1e/.github/workflows/make_docs.yml#L51)... which I kind of thought was the thing that built docs and pushed it somewhere to be published online?
- the `make docs` command in the Makefile [here](https://github.com/napari/napari/blob/291a11a70fdc8210bf3053ec6bc0e3db3c416d1e/Makefile#L3)

It's possible that the `Build & Publish Docs` workflow is no longer being used by the `napari.org` website?  but I don't know

**Comment by tlambert03** [comment]
m

**Comment by DragaDoncila** [comment]
> I'll note that preferences are also not working. click on "Setting Preferences" on this page for a funny surprise.

LMAO

Yeah the docs build workflow is more complex than many of us realized as @melissawm is also discovering. 

> It's possible that the Build & Publish Docs workflow is no longer being used by the napari.org website? but I don't know

I'm not sure either. Pinging @kne42 - do you know what changes need to be made in `napari/napari` or `napari/napari.github.io` to make sure the `update_preferences_docs` and `update_events_docs` scripts are run and their results included in docs builds?

**Comment by melissawm** [comment]
> I'll note that preferences are also not working. click on "Setting Preferences" on [this page](https://napari.org/guides/stable/index.html) for a funny surprise.

Oops. that was a pure reference to "preferences" that got picked up by intersphinx instead of picking up the local doc. I'll fix that in a bit.

**Comment by tlambert03** [comment]
> Oops. that was a pure reference to "preferences" that got picked up by intersphinx instead of picking up the local doc. I'll fix that in a bit.

I'm also actually wondering if it _would_ work if the local doc were actually present.  that local doc gets built by [this script](https://github.com/napari/napari/blob/main/docs/_scripts/update_preference_docs.py) ... however, part of the point here is that the build pipeline being used at github.io isn't actually running that script...

**Comment by sofroniewn** [comment]
> It's possible that the Build & Publish Docs workflow is no longer being used by the napari.org website? but I don't know

Maybe @codemonkey800 can take a look here

**Comment by codemonkey800** [comment]
There are a bunch of moving parts here from what I can see. Currently we have three workflows (I'm hoping not, but there could be more since the napari-docs bot was a surprise):

1. Deploy workflow on `napari/napari.github.io`: [deploy.yml](https://github.com/napari/napari.github.io/blob/main/.github/workflows/deploy.yml)
    - This deploys napari.org whenever there's a push to `main`
2. Copy docs workflow in `napari/napari`: [make_docs.yml#L11-L48](https://github.com/napari/napari/blob/291a11a70fdc8210bf3053ec6bc0e3db3c416d1e/.github/workflows/make_docs.yml#L11-L48)
    - This runs a script that updates the `_toc.yml` file on `napari/napari.github.io` and copies new files to the repo
    - This triggers the `Deploy workflow` above since it pushes to `main`.
3. Build and publish workflow in `napari/napari`: [make_docs.yml#L50-L121](https://github.com/napari/napari/blob/291a11a70fdc8210bf3053ec6bc0e3db3c416d1e/.github/workflows/make_docs.yml#L50-L121)
    - This runs the aforementioned `update_preference_docs.py` and `update_event_docs.py` scripts, but it publishes it to https://github.com/napari/docs, which is hosted at https://napari.org/docs
    
Ultimately, the docs is very complicated 🤯 

---

I think perhaps in the meantime, what we could do is copy those Python scripts and add it to `napari/napari.github.io`. But I think it's also a sign we should push harder for consolidating the docs since there may be more and more workarounds we need to take into account 😭

**Comment by sofroniewn** [comment]
Thanks for digging in here @codemonkey800 

> But I think it's also a sign we should push harder for consolidating the docs since there may be more and more workarounds we need to take into account 😭

Agreed, maybe we could get this on your docket for the near future. Having a simpler process here could let a lot more folks contribute and save us a lot of time in the long run. cc @neuromusic

**Comment by melissawm** [comment]
I think this is solved by #3751 - I have a successful cross build (napari/napari and napari/napari.github.io) locally. Unless there are additional steps for deployment that I don't understand - maybe @codemonkey800 can confirm that is works?

**Comment by melissawm** [comment]
Ok I was wrong, these files actually need to be added to the napari.github.io repo for it to work. This is being done as part of napari/napari.github.io#299

**Comment by melissawm** [comment]
Looks like the toc reorganization fixed this, can anyone confirm? Thanks folks!
