### ISSUE TITLE
dead link to https://napari.org/docs/plugins/for_plugin_developers.html

### ISSUE THREAD

**Issue by chili-chiu** [napari/napari#3661]
## 🐛 Bug

The link is mentioned here: https://napari-plugin-engine.readthedocs.io/en/latest/
See also: documentation for writing a napari plugin.

Is the documentation still somewhere?

**Comment by melissawm** [comment]
The current page is here: https://napari.org/plugins/stable/for_plugin_developers.html

The legacy versions documentation follows a pattern of `https://napari.org/docs/<version>/plugins/for_plugin_developers.html`, with the most recent one here: https://napari.org/docs/dev/plugins/for_plugin_developers.html

**Comment by tlambert03** [comment]
thanks @chili-chiu, since those are the docs for the plugin engine itself, could you open an issue there? 
https://github.com/napari/napari-plugin-engine
