### ISSUE TITLE
Plugin install filter feature inconsistent depending on timing

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#3664]
## 🐛 Bug
See discussion at https://napari.zulipchat.com/#narrow/stream/212875-general/topic/.E2.9C.94.20Plugin.20installation

I think there are a few subtle issues going on in the plugin install filter field, such that depending on when you start typing, results may or may not appear, or, the filter may or may not be applied? 
To reproduce, start napari, open the plugin installer, and try to start typing into the field quickly (for instance "redlionfish" as in the zulip convo).  Try a few times, with different "latency-to-type", and you might see different results.

cc @goanpeca

**Comment by goanpeca** [comment]
Yep I think that is another easter egg you have found 🤪

Will look into it !
