### ISSUE TITLE
Window scaling issue on Linux and Windows

### ISSUE THREAD

**Issue by marshuang80** [napari/napari#367]
## 🐛 Bug

The drop down menu has scaling issues on linux
![image](https://user-images.githubusercontent.com/15271135/60139287-35665980-9762-11e9-8b3a-100b43d7fe51.png)

## To Reproduce
Run `python examples/labels-0-2d.py` and expand drop down menu for segmentation

## Environment

 - napari: 0.9
 - Linux Ubuntu 18.04LTS
 - Python version: 3.7
 - Laptop: Lenovo X1 Carbon 6th gen

**Comment by sofroniewn** [comment]
Nice catch @marshuang80 - this is probably because we are hard coding a size for the `expanded` properties widget, but we might need to make it depend on things like screen resolution etc. I can look into it further.

In general we need to do a bit more testing of our stylings on linux and windows!

**Comment by jni** [comment]
Note that I haven't run into these issues, and probably has to do with GNOME scaling on 2x (retina/HiDPI) displays (I don't have that turned on because I'm on i3).

It's *very* interesting that the layer name text is not scaled but all the other text is — that might be a hint about what "correct" styling looks like. Incidentally, I think the rest of the chrome should be doubled, rather than the text be made smaller — the window title text is a good guide.

**Comment by marshuang80** [comment]
Seems like this issue only happens when the display on linux is scaled to anything larger than 100%. 

![image](https://user-images.githubusercontent.com/15271135/60553931-60b0f180-9cea-11e9-8e85-3bf8ee5ba655.png)

**Comment by jni** [comment]
As noted by @hmaarrfk in #530, his library might be a good way to deal with this issue:

https://github.com/hmaarrfk/qtpy-tools

**Comment by sofroniewn** [comment]
@hmaarrfk any PRs around this would be great, @marshuang80 and I found some settings that might have helped but couldn't quite get it working

**Comment by hmaarrfk** [comment]
I've never coded up qt, just converted the UI files into py files with the qt tools. I typically do that step at build time.

**Comment by sofroniewn** [comment]
Ok, I'll try and look into this again soon

**Comment by jni** [comment]
For Windows, an image.sc user found a fix:

https://forum.image.sc/t/napari-issues-it-works-but-no-gpu-and-the-gui-is-all-squashed/31411/13

It would be great if we could figure out how to find that setting programmatically...

**Comment by sofroniewn** [comment]
I wonder if `Qt::AA_EnableHighDpiScaling` and `Qt::AA_DisableHighDpiScaling` - see https://doc.qt.io/qt-5/qt.html#ApplicationAttribute-enum might be important settings here

**Comment by sofroniewn** [comment]
@jni maybe you can try the above fix? I don't have access to a linux / windows machine right now to test.

**Comment by jni** [comment]
@sofroniewn do you know how I set those in PySide/PyQt? If not I can investigate.

My daily Linux workspace doesn't have this problem but I think I can reboot into GNOME to test it.

**Comment by sofroniewn** [comment]
Should be similar syntax to this - https://github.com/napari/napari/blob/e4f1b1f264b72cc22f188f03014eebd94e89e676/napari/_qt/qt_viewer.py#L50, not sure if we want in `QtViewer` vs `Window`, but that can get figured out later

**Comment by hmaarrfk** [comment]
It seems that as of PySide2 5.14, you can use

```
QT_ENABLE_HIGHDPI_SCALING=1 napari
```

**Comment by sofroniewn** [comment]
Closed by #820
