### ISSUE TITLE
Proposal: refactor repo

### ISSUE THREAD

**Issue by jni** [napari/napari#368]
This is a major refactor so I wanted to check with everyone before going ahead.

I think the napari repo is far too nested, which makes navigation a chore. Even for skimage, which is a much bigger library, we only use two levels of nesting (`skimage/package/module.py`), with only the ~~module~~ **Edit:** package level actually publicly used. I think that is the right way to do it.

Additionally, the current directory structure needlessly pairs models with views. As discussed in #115, models should have no knowledge of a view and should be able to live quite happy existences without corresponding views. Therefore, putting a `_view` folder right next to each model is a bit jarring. In my opinion, we should completely divorce our models from our views — all the views should live in their own subdirectory.

Finally, it's not really necessary to name model files `model` — it can essentially be inferred by the path in the proposal below. Additionally, it's annoying in many/most IDEs to have all the names be `model.py` or `qt_properties.py` because most IDEs don't provide the full path, or most of the path is hidden anyway because it is too long.

Ok, on to my proposed repo structure:

```
setup.py
napari/
  layers/
    __init__.py
    base.py  # formerly layers/_base_layer/model.py
    image.py  # formerly layers/_image_layer/model.py
    vectors.py
    ...
  _qt/
    __init__.py
    app_context.py
    base_qt.py
    dims_qt.py  # formerly components/_dims/view.py
    layerlist_qt.py  # formerly components/_layers_list/view.py
    image_qt.py  # formerly layers/_base_layer/view/{controls/properties}.py
    ...
    window_qt.py  # formerly components/_window/view.py
  components/
    dims.py  # formerly components/_dims/model.py
    layers_list.py  # formerly components/_layers_list/model.py
    viewer_model.py  # formerly components/_viewer/model.py
  view_function.py
  viewer.py
```

Things I like here:

- the core napari data model is very easy to extract.
- if we decide we hate Qt one day that's very easy to cast aside
- if we want to a web viewer that gets added as a directory and nothing else
- the repo is easier to navigate e.g. on github because there's a more limited nesting level.

If others agree I'm happy to give this a whirl.

**Comment by sofroniewn** [comment]
@jni i'm supportive of the approach for the reasons you mention. I do like the idea that if we decided to swap out `Qt` or add a web view it would be one simple change, and separating the models and views makes sense. We also then just need to have one `tests` folder per top level folder `layers`, `components`, and `_qt`.

One thing I find a little strange though is that we have two separate folders `layers` and `components` for the model files, but then only one folder `_qt` for all the qt files for both layer and component views. Ultimately I'm ok with this, as I think one of our `0.2` goals is to support autogeneration of layer `qt_properties` and `qt_controls` from the layer model files as described in #285 

For 
```python
image_qt.py  # formerly layers/_base_layer/view/{controls/properties}.py
```
Do you plan to merge `controls`/`properties` into one file? That doesn't make sense to me. I think we'd still need something like `image_controls_qt.py` and `image_properties_qt.py`

There are also some layer specific util files, like `shape_list.py`, `shape_util.py`, and the `shapes` folder inside `_shapes_layer`. Would these still live inside `layers` or would they get pulled out into our general `util` folder. I'd probably say our `util` folder, but our `util` folder should also get some refactoring. That can come after this PR though.

All in all, I'd say go ahead and start a PR and we can discuss some of these details on it

**Comment by sofroniewn** [comment]
We'll also need to put the `_constants.py` files somewhere. Potentially a new top level folder called `_constants` that would have files like `shape_constants.py` inside it

**Comment by jni** [comment]
> Do you plan to merge controls/properties into one file? That doesn't make sense to me. I think we'd still need something like `image_controls_qt.py` and `image_properties_qt.py`

Why do you feel so strongly that these need to be in separate files? This ain't Matlab where each file can only have one public-facing function. =) I favour breaking things into smaller units when having everything in one file would make the file unwieldy. In this case, the files are small enough that I think merging them could work. I'm in no way tied to this view though, just leaning that way because I'm in tidying mode. =)

> One thing I find a little strange though is that we have two separate folders layers and components for the model files, but then only one folder _qt for all the qt files

It's true, I agree with this concern, but I also think that it makes some logical sense: napari itself is the models, and then _qt contains a (whole) view of napari models. In a sense this is the original separation of `napari-gui` and `napari-core`. We're just putting `napari-gui` in a folder instead of a repo. =)

> Would these still live inside layers or would they get pulled out into our general util folder.

I'd stick these in the layers with an underscore, since they are not expected (?) to have utility outside of the layers.

**Comment by sofroniewn** [comment]
> Why do you feel so strongly that these need to be in separate files? This ain't Matlab

Yup - ok 100% agree with you, both of these "layer qt" classes can live in the same file with names like `image_qt.py` the classes are small and clear enough.

But I'd probably rename and keep the following separate

- `components/_viewer/view/buttons.py` -> `_qt/layerbuttons_qt.py`
- `components/_viewer/view/controls.py` -> `_qt/controls_qt.py`
- `components/_viewer/view/main.py` -> `_qt/viewer_qt.py`

> I'd stick these in the layers with an underscore

How about a single `util` folder inside our `layers` folder? I know it's a little nested, but I really like the idea of being able to look into the `layers` folder and all the files I see be actual layers and have everything else inside a folder. To me that's cleaner than everything else be a file with an `_`. Same applies to `constants` too.

In general very excited about this, and looking forward to a PR!
