### ISSUE TITLE
Points properties are not equal if labels array ends with empty string

### ISSUE THREAD

**Issue by FudgeMunkey** [napari/napari#3680]
## 🐛 Bug

I rewrote the `test_empty_points_with_properties` function using Hypothesis. There is an assertion error between `pts.current_properties` and `current_props` if the labels array has at least two elements where the last one is an empty string. For example, `["0", ""]` causes an error however, the following do not: `[""]` or `["", "0"]`.

## To Reproduce

This test generates a 1D array of random unicode strings and uses them for the point labels. You can view this test on my branch [here](https://github.com/FudgeMunkey/napari/tree/fix-unequal-points-labels) or add it to your test suite if you would like run it. 

```Python
@given(arrays(dtype=unicode_string_dtypes(), shape=array_shapes(max_dims=1)))
def test_empty_points_with_label_properties(labels):
    properties = {'label': labels}
    pts = Points(property_choices=properties)
    current_props = {k: v[0] for k, v in properties.items()}
    np.testing.assert_equal(pts.current_properties, current_props)
```

These are the results from running the above test.

```
Falsifying example: test_empty_points_with_properties(
    labels=array(['0', ''], dtype='<U1'),
)
...
E       AssertionError: 
E       Arrays are not equal
E       key='label'
E       
E       Mismatched elements: 1 / 1 (100%)
E        x: array([''], dtype='<U1')
E        y: array('0', dtype='<U1')
```

## Expected behavior

`pts.current_properties` should be equal to `current_props`. 

## Environment

```
napari: 0.4.13.dev59+g1f9cbfc6
Platform: Linux-5.11.0-40-generic-x86_64-with-glibc2.29
System: Ubuntu 20.04.3 LTS
Python: 3.8.10 (default, Sep 28 2021, 16:10:42)  [GCC 9.3.0]
Qt: 5.15.2
PyQt5: 5.15.6
NumPy: 1.21.4
SciPy: 1.7.2
Dask: 2021.11.2
VisPy: 0.9.3

OpenGL:
  - GL version:  4.6.0 NVIDIA 450.156.00
  - MAX_TEXTURE_SIZE: 32768

Screens:
  - screen 1: resolution 2560x1440, scale 1.0
  - screen 2: resolution 2560x1440, scale 1.0
  - screen 3: resolution 2560x1440, scale 1.0

Plugins:
  - console: 0.0.4
  - scikit-image: 0.4.13.dev59+g1f9cbfc6
  - svg: 0.1.5
```

**Comment by psobolewskiPhD** [comment]
I can't reproduce this, both ["0", ""] and  ["", "0"] work, passing the assert.
We're going to deprecate properties soon, so I'm going to close.
