### ISSUE TITLE
Changing the mode of linked layers leads to RecursionError or crash

### ISSUE THREAD

**Issue by jojoelfe** [napari/napari#3681]
## 🐛 Bug

When the mode of a layer that is linked to another layer is changed napari crashes for me without error most of the time, even though I sometimes have seen a RecursionError. It looks to me like the interactive attribute of the layer oscillates between True and False, thereby bypassing the equality check that prevents recursions.

## To Reproduce

1. Add two point layers
2. Link the two layers
3. Switch on the of the layers into "Add" mode

**Comment by tlambert03** [comment]
thanks @jojoelfe ... fixed in #3684

**Comment by tlambert03** [comment]
side question: 
when we link layers, we exclude a couple key attributes like `data`, and `thumbnail`...  while #3684 does fix the recursion, I wonder whether we want to add `mode` and/or `interactive` to the properties that are excluded from linking?

**Comment by jojoelfe** [comment]
For transforming multiple layers there is a mild convenience when the mode is linked, because it will be active no matter which layer is selected:

![linked](https://user-images.githubusercontent.com/6081039/143046351-a7f98bd7-cf46-44d3-b533-0d8b9d127a8e.gif)

But the real magic is the linking of the affine attribute and I can imagine that linked modes become more complicated when layers of different types are linked that support different kinds of modes.
