### ISSUE TITLE
Support for npe2 in the plugin install dialog

### ISSUE THREAD

**Issue by nclack** [napari/napari#3685]
## 🧰 Task

The napari plugin install dialog should list installed npe2 plugins.

This requires
- [x] listing any installed npe2 plugins in the plugin install dialog #3694 
- [x] #3924
- [x] #3925

Support for enable/disable requires some npe2 library support. See napari/npe2#36

**Comment by goanpeca** [comment]
Hi @nclack any pointers here :) ?

**Comment by nclack** [comment]
@goanpeca so many pointers! I've also been discussing this w @ppwadhwa.

See napari/napari-svg for an example of an npe2 enabled plugin. We can play around with a locally installed version of it to observe how it interacts with the plugin install dialog.

But first we need npe2 installed.  At the moment, napari/npe2 needs to be installed from source. Once you can successfully `import npe2` in your python environment, napari will attempt to use it.

If you look at napari-svg's setup.cfg, you'll find entry points groups for the original plugin engine (npe1) and for npe2.  It looks like:

```ini
[options.entry_points]
napari.plugin =
    svg = napari_svg
napari.manifest =
    napari-svg = napari_svg:napari.yaml
```

The `napari.plugin` one is the original plugin style. `napari.manifest` is the npe2 style. As is, napari-svg will be recognized as both the old and new engines.

As an npe1 plugin it will be listed in the list of installed plugins, but if you remove the `napari.plugin` entry point group it'll only be recognized by npe2. In that case, it won't be listed. That's what this issue addresses.

There are various points within the napari code base where npe2 is already integrated. See `napari/plugins/_npe2.py` for examples.

**Comment by tlambert03** [comment]
as mentioned elsewhere: I _don't_ think we should support this case of providing double entrypoints.  so don't spend too much time trying to deduplicate things that do that.

@goanpeca ... I would just a hook to iterate over the registered plugins in the npe2 plugin manager around here: https://github.com/napari/napari/blob/64b7a9541815f2f9ab357993d7876c5e66eda78f/napari/_qt/dialogs/qt_plugin_dialog.py#L597

**Comment by nclack** [comment]
all done!
