### ISSUE TITLE
Rename app_context

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#369]
## ❓ Questions and Help

It was floated at the last meeting that we should rename `app_context` to something without the underscore like just `context` and expose it at the top level of napari, not just from `napari.util`. Putting this here to foster discussion / keep track of this change

**Comment by jni** [comment]
imho it should be called app or even qtapp (since it's qt-specific):

```python
import napari
from skimage import data

# Not needed in IPython when launched with --gui=qt or using %qt magic
with napari.qtapp():
    napari.view(data.coins())
```

`context` by itself isn't right. It's the equivalent of calling `layerslist` just `list`.

**Comment by sofroniewn** [comment]
Fair - how about `qtcontext` instead of `qtapp`?

Or maybe `qtgui` or `guiqt` or `qt_gui` or `gui_qt`- in someways that last one mirrors the IPython usage the best which is `%gui qt`

@freeman-lab, @kne42 ?

**Comment by jni** [comment]
So, I feel like there's two conflicting issues:

`with napari.qtgui():` or `with qtgui():` *sounds* better in English than `with gui_qt()`, at least to me (?). The ordering is now different from IPython but I think that's not a big deal — `gui=qt` is already different from `gui_qt`. In one you're saying "give me a Qt GUI" and in the other you're saying "make the GUI be of type Qt". From a readability perspective, I think this is better, and I think that it is clear *enough* that they are doing the same thing.

However, I'm open to `gui_qt` if people feel strongly that it's better.

Regarding @kne42's suggestion that this should be `with qt_eventloop()`, I mean, sure, that's technically what we're doing, but in the end I think that this is an implementation detail that users shouldn't need to know about. They just need to know that we are "enabling" the use of a Qt GUI. I see the appeal, but I think it's more important to match IPython's terminology than it is to be "correct" here.

**Comment by sofroniewn** [comment]
I'm open to either `qtgui` or `gui_qt`. I'd probably vote for `gui_qt`, but one thing to consider though is the file that contains this might make more sense as `qtgui.py` instead of `gui_qt.py` as the latter naming convention is similar to how @jni plans to refactor our qt views in #368

**Comment by sofroniewn** [comment]
As noted in #390 I'm now leaning pretty strongly to `with gui_qt` instead of `with qtgui` for the sole reason that I really think it will be less confusing for beginners to keep `with gui_qt` and `%gui qt` straight for scripting and notebook usage instead of having to remember two different orders of the words for the two different scenarios. It took me a long time to remember `%gui qt` in the notebook and if i'd been using `qtgui` sometimes in scripts I'm confident it would have been much harder. @jni notes that they aren't identical, but I think replacing the `_` with and `=` or ` ` is much easier to remember than swapping the order. I think the extra pros of `qtgui` sounding better or maybe (or might not) being more consistent with how we do things internally don't outweigh those potential confusion costs. Ultimately I see `with gui_qt` as the safer option.

**Comment by jni** [comment]
@sofroniewn very well, your argument has swayed me. It's sometimes hard to put oneself in a beginner's shoes, I hadn't done that here, and I think you are definitely right that it would be easier in this case.
