### ISSUE TITLE
Contrast limits range with dask data

### ISSUE THREAD

**Issue by brisvag** [napari/napari#3698]
## 🚀 Feature
Right now, if a `dask` array is passed to `Image`, the contrast limits range will be set to `0, 1` (same for anything that's not `np.ndarray`). This is unfortunately really bad with some of my data (which can sometimes be between `-0.0001` and +`0.0001`,  or similarly tiny ranges). Now, I know that I can manually set these limits, but what if I don't know this?

At a first glance, it seems that the code already has some [logic to handle very big data](https://github.com/napari/napari/blob/d0b6b3f17298578f157188b50b2660e533c10d97/napari/layers/utils/layer_utils.py#L100-L127). Could we implement a similar solution which uses just a few chunks of the dask array?

**Comment by sofroniewn** [comment]
i think we used to guess, but then we changed the behaviour, cc @jni @tlambert03. There are some closed issues that discuss this for sure

**Comment by tlambert03** [comment]
> Right now, if a dask array is passed to Image, the contrast limits range will be set to 0, 1 (same for anything that's not np.ndarray).

it _should_ schedule an autoscale to happen [right here](https://github.com/napari/napari/blob/6ba0845de10dcd63b2583dcc719454358b0f5b2a/napari/layers/image/image.py#L311), which should execute [right here](https://github.com/napari/napari/blob/6ba0845de10dcd63b2583dcc719454358b0f5b2a/napari/layers/image/image.py#L681) using the data from the first view chunk ... can you maybe try to confirm that that code is indeed not executing for you, and see why not?

**Comment by brisvag** [comment]
Actually, after trying again with different data, everything seemed to work fine. I need to get back to the office and try with that first data I had to make sure it wasn't somwthing wrong with the data itself.

**Comment by brisvag** [comment]
Ok, took a look at this (at last :laughing: ) and the issue is cause by the fact that the autoscale on `set_view_slice` only happens for `contrast limits`, and not `contrast_limits_range`. It's easy enough to replace this, but I'm not 100% sure we *do* want to reset the contrast limits *range* every time we change slice, cause this could cause us to lose the contrast picked in a different slice. One thing we could do is pick the biggest range possible:

```
new_range = [min(old_low, new_low), max(old_high, new_high)]
```

This would ensure we never lose previously set `clim`.

**Comment by brisvag** [comment]
Here's a minimal example:

```py
import napari
import numpy as np
import dask.array as da
np_arr = np.array([[0.000001, -0.0002], [0, 0.0000004]])
da_arr = da.array(np_arr)
v = napari.Viewer()
l_np = v.add_image(np_arr)
l_da = v.add_image(da_arr)
print(l_np.contrast_limits_range)
print(l_da.contrast_limits_range)
```
