### ISSUE TITLE
Deprecation warnings when using thread_worker

### ISSUE THREAD

**Issue by haesleinhuepf** [napari/napari#3704]
## 🐛 Bug

Hi all,

I'm facing deprecation warnings like this one when using the napari `thread_worker`:
```
C:\Users\rober\miniconda3\envs\threading_test\lib\site-packages\vispy\app\backends\_qt.py:627: DeprecationWarning: 
an integer is required (got type KeyboardModifiers).  Implicit conversion to integers using __int__ is deprecated, and may 
be removed in a future version of Python.!
```

## To Reproduce

1. Set up an environment:
```
conda create --name threading_test python=3.8
conda activate threading_test
conda install napari
``` 
2. Save the following code to `threading_test.py`:
```
import numpy as np
import napari
import time
from napari._qt.qthreading import thread_worker

def image():
    return np.random.random((10, 10))

viewer = napari.Viewer()
viewer.add_image(image())

# https://napari.org/guides/stable/threading.html
@thread_worker
def loop_run():
    while True:  # endless loop
        time.sleep(2)
        print("Hello world")
        yield True

worker = loop_run()

# Start the loop
worker.start()

napari.run()
```
3. run it using `python threading_test.py`.
4. Move your mouse over the canvas and there will be many deprecation warnings:

![image](https://user-images.githubusercontent.com/12660498/143679951-ac73c08a-e369-4184-8005-9aa4a1329f40.png)

## Expected behavior

I would love to learn how this message could be prevented.
It would be cool to at least suppress the notification window popping up all the time. 

## Environment

 - Please copy and paste the information at napari info option in help menubar here:
```
napari: 0.4.12
Platform: Windows-10-10.0.19042-SP0
Python: 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:22:46) [MSC v.1916 64 bit (AMD64)]
Qt: 5.12.9
PyQt5: 5.12.3
NumPy: 1.21.4
SciPy: 1.7.3
Dask: 2021.11.2
VisPy: 0.9.4

OpenGL:
- GL version: 4.6.14761 Compatibility Profile Context 21.30.02.01 30.0.13002.1001
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1200, scale 1.0

Plugins:
- console: 0.0.4
- scikit-image: 0.4.12
- svg: 0.1.5
```

 - Any other relevant information:

**Comment by tlambert03** [comment]
this probably isn't due to the threadworker, but rather implicit casting of some Qt enum into an int somewhere else in the code.  I wasn't able to reproduce this with the environment provided (but on mac)... but I have certainly seen something like this before.  I suspect if you use a newer version of qt you won't see it (so you'd have to `conda uninstall pyqt; pip install pyqt5`...

> I would love to learn how this message could be prevented.

it would require finding the implicit cast, and making it explicit.  Follow the stack trace above `threading_test\lib\site-packages\vispy\app\backends\_qt.py:627: DeprecationWarning: ` and figure out where the napari code is that is passing something like a Qt Enum object to vispy, and provide an explicit `int()` ...

> It would be cool to at least suppress the notification window popping up all the time.

This would either be `filterwarnings` (I know it's challenging to set up, and you've struggled to get it to work in the past), or, as discussed elsewhere, we would just drop support for using `warnings.warn` to trigger GUI warnings, and create a new napari-specific `notifications.show_warn` method instead.  I'm definitely fine with that change.

**Comment by haesleinhuepf** [comment]
Thanks for the reply Talley @tlambert03! 

> Follow the stack trace above `threading_test\lib\site-packages\vispy\app\backends\_qt.py:627: DeprecationWarning: ` and figure out where the napari code

That seems increadibly hard as I need to find from where this code is called. I went a bit in the other direction: Where does a thread-worker invoke anything that is related to vispy or QEnums, and couldn't find anything.

Anyway, the bug goes away by updating pyqt5 to >= 5.15.0. Does anything speak against specifying that version as dependency in napari?

**Comment by tlambert03** [comment]
> Anyway, the bug goes away by updating pyqt5 to >= 5.15.0. Does anything speak against specifying that version as dependency in napari?

Yes, the fact that it's unavailable on conda-forge

> Where does a thread-worker invoke anything that is related to vispy or QEnums, and couldn't find anything.

As mentioned, I think the threadworker is a red herring...

**Comment by haesleinhuepf** [comment]
> As mentioned, I think the threadworker is a red herring...

Yes, I understand. But why does it only happen in case the thread_worker is activated? (-:

**Comment by tlambert03** [comment]
I would start at
`site-packages\vispy\app\backends\_qt.py:627`, throw an exception or breakpoint there, perhaps use the "enter debugger" button in napari when your exception gets raised.  Unfortunately, until I can cause it to happen I can't test locally

**Comment by tlambert03** [comment]
just tried on my windows system, still no luck in reproducing it
```
napari: 0.4.12
Platform: Windows-10-10.0.19042-SP0
Python: 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:22:46) [MSC v.1916 64 bit (AMD64)]
Qt: 5.12.9
PyQt5: 5.12.3
NumPy: 1.21.4
SciPy: 1.7.3
Dask: 2021.11.2
VisPy: 0.9.4

OpenGL:
  - GL version:  4.6.0 NVIDIA 456.71
  - MAX_TEXTURE_SIZE: 32768

Screens:
  - screen 1: resolution 1768x992, scale 1.0

Plugins:
  - console: 0.0.4
  - scikit-image: 0.4.12
  - svg: 0.1.5
```

**Comment by MosGeo** [comment]
I remember seeing a might be related depreciation warning regarding implicit functions when using pytorch/fastai. It seems thread worker converts something to implicit. I will dig it up when I have time.

**Comment by jo-mueller** [comment]
Can reproduce:

```
napari: 0.4.12
Platform: Windows-10-10.0.19042-SP0
Python: 3.8.12 (default, Oct 12 2021, 03:01:40) [MSC v.1916 64 bit (AMD64)]
Qt: 5.12.9
PyQt5: 5.12.3
NumPy: 1.22.0
SciPy: 1.7.3
Dask: 2021.12.0
VisPy: 0.9.4

OpenGL:
- GL version: 4.6.0 NVIDIA 496.13
- MAX_TEXTURE_SIZE: 32768

Screens:
- screen 1: resolution 2560x1440, scale 1.0
- screen 2: resolution 1920x1080, scale 1.0

Plugins:
- console: 0.0.4
- scikit-image: 0.4.12
- svg: 0.1.5
```

**Comment by psobolewskiPhD** [comment]
I can't reproduce this on macOS with napari 0.5.4 from conda-forge.

napari doesn't support python 3.8 or Qt 5.12.
and conda-forge has both pyqt5 5.15.x and pyside2 5.15.x for all platforms.

So I'm going to close. If there is a current install that triggers this, please make a new issue.
