### ISSUE TITLE
Coordinates in status bar not updated when moving dim slider

### ISSUE THREAD

**Issue by royerloic** [napari/napari#372]
## 🐛 Bug

When viewing for example a nD stack (n>=3),
coordinates in status bar are not updated when moving dim slider.
This is confusing as it is difficult to know where we are.

## Expected behavior

The status bar should display something like:

[3, 5, :, :], layer_name, value ...

where 3 or 5 are changing depending on the dim slider being moved.
the ':' are there because we are not overing over a pixel, so in some sense
we have nothing relevant to give there. So why not have something 'pythonic'
to show... 

## Environment

 - napari Version (e.g., 1.0):  0.0.8
 - OS (e.g., Linux): osx
 - Python version: 3.7

**Comment by royerloic** [comment]
fixed in 0.0.9 !
but the ':' might still be relevant...

**Comment by sofroniewn** [comment]
@jni is working on the string reformatting as discussed in #93 and can look into displaying `:` when moving the dims sliders

**Comment by sofroniewn** [comment]
I've added this request on string formatting to #93 and am closing this issue in favor of that one
