### ISSUE TITLE
Move napari to start using the Hub API

### ISSUE THREAD

**Issue by goanpeca** [napari/napari#3720]
## 🚀 Feature

Move napari plugin manager dialog to use the hub API

## Motivation

Use napari hub as the source of truth.

## Additional context

The current endpoints for the napari hub API are as follows

https://api.napari-hub.org/plugins gives the full list of available plugins (plugin developers can "hide" deprecated or pre-release plugins, so this list is smaller than what PyPI returns)
https://api.napari-hub.org/plugins/ gives aggregated metadata for a given plugin (e.g. https://api.napari-hub.org/plugins/devbio-napari)

**Comment by liu-ziyang** [comment]
Update: we have added the api doc for our supported endpoints: https://api.napari-hub.org
