### ISSUE TITLE
Setting the camera center also resets the zoom

### ISSUE THREAD

**Issue by jni** [napari/napari#3723]
## 🐛 Bug

Additionally, there appears to be a race condition during which the model and VisPy view fall out of sync.

Motivated by this imagesc post:

https://forum.image.sc/t/different-ways-to-control-camera-in-napari/60552

```python
import napari
import time
from skimage import data

eagle = data.eagle()

viewer = napari.view_image(eagle)
viewer.camera.zoom = 5
viewer.camera.center = (0, 100, 100)

print(viewer.camera.zoom)  # prints 5.0, but it's not 5

napari.run()
```

If you then open the console and `print(viewer.camera.zoom)`, you'll get 0.2something.

I had a look at the code, and nothing on our end is actually doing the zoom setting. `viewer.camera` is an EventedModel, [defined here](https://github.com/napari/napari/blob/634777fbbd782539dd960de4f94d26e4801d2951/napari/components/camera.py#L12-L38). There's no `center` setter or any such thing.

The QtViewer then has a VispyCamera, instantiated [here](https://github.com/napari/napari/blob/cdacb2b57f804bf9992fb98c29ea024d4c4e019f/napari/_qt/qt_viewer.py#L304-L306) and defined [here](https://github.com/napari/napari/blob/cc06d317038bc11fa9e8d2d6528381901142517d/napari/_vispy/camera.py#L7-L44). Setting the center in the Camera model calls [`_on_center_change`](https://github.com/napari/napari/blob/cc06d317038bc11fa9e8d2d6528381901142517d/napari/_vispy/camera.py#L146-L147) in the VispyCamera, which then calls its [`center` setter](https://github.com/napari/napari/blob/cc06d317038bc11fa9e8d2d6528381901142517d/napari/_vispy/camera.py#L88-L93). This [sets the `center`](https://github.com/vispy/vispy/blob/e2df393fffaf9512dd1e945b213b7ce2eb4bf794/vispy/scene/cameras/panzoom.py#L160-L176) on the Vispy ViewBox's camera (PanZoomCamera), then calls `view_changed` there.

That's the bit that I don't understand, and probably the cause of the issue, as it changes the viewbox rectangle based on the *current* rectangle center, which has nothing at all to do with the desired rectangle:

https://github.com/vispy/vispy/blob/e2df393fffaf9512dd1e945b213b7ce2eb4bf794/vispy/scene/cameras/panzoom.py#L160-L176

So, ultimately, I think this is a bug in vispy, and if one of our vispy gurus could help me with a pure-vispy reproducer, I'll raise an issue there and maybe fix that computation.

## Expected behavior

The zoom should not be changed by changing the center.

## napari info

```
napari: 0.4.13.dev125+ga79b353d3.d20211129
Platform: macOS-11.4-x86_64-i386-64bit
System: MacOS 11.4
Python: 3.9.7 | packaged by conda-forge | (default, Sep  2 2021, 17:58:46)  [Clang 11.1.0 ]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.20.3
SciPy: 1.7.1
Dask: 2021.09.0
VisPy: 0.9.4
```

**Comment by sofroniewn** [comment]
Oof - thanks for reporting this @jni - might be great if @brisvag or @kevinyamauchi could take a look, it causing some problems getting reported on the zulip

**Comment by alisterburt** [comment]
THIS!!!!

Thank you - this is a problem I came up against with napari/napari-animation#113 too, after sinking a few hours into it a couple of times knowing the actual source of the issue is a big kick to actually solving it 😆 I'll add it to my 'explore this on the train' list for the week

**Comment by jni** [comment]
This will be fixed with the next vispy release, so I think it can be closed! 🎉
