### ISSUE TITLE
Reordering layers remove translation grid

### ISSUE THREAD

**Issue by Czaki** [napari/napari#3725]
## 🐛 Bug

When reordering layers, the information about the translation grid is set to 0. 

## To Reproduce

1. run code:
 ```python
 import numpy as np

import napari


data1 = np.zeros((30, 30), dtype=np.uint8)
data1[10:25, 10:25] = 200

data2 = np.zeros((20, 20), dtype=np.uint8)
data2[5:15, 5:15] = 200

view = napari.Viewer()

view.add_image(data1, blending="additive")
layer = view.add_image(data2, blending="additive")
layer.translate_grid = (5, 5)
print()

napari.run()
```
![Zrzut ekranu z 2021-12-01 10-21-14](https://user-images.githubusercontent.com/3826210/144207986-450bc0f7-83de-4c64-b802-98337511551c.png)
2. reorder ~axes~ layers
![Zrzut ekranu z 2021-12-01 10-27-17](https://user-images.githubusercontent.com/3826210/144208015-b9a258ea-4282-412e-97be-a8c998df7f7b.png)

## Expected behavior

Reorder should not impact translations. 

## Environment

 - Please copy and paste the information at napari info option in help menubar here:

 - Any other relevant information:
 ```
napari: 0.4.13.dev80+gd0b6b3f17.d20211126
Platform: Linux-5.11.0-41-generic-x86_64-with-glibc2.2.5
System: Ubuntu 21.04
Python: 3.8.3 (default, Sep 3 2021, 01:19:46) [GCC 10.3.0]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.19.5
SciPy: 1.7.1
Dask: 2021.09.0
VisPy: 0.9.2

OpenGL:
- GL version: 4.6.0 NVIDIA 470.86
- MAX_TEXTURE_SIZE: 32768

Screens:
- screen 1: resolution 2560x1440, scale 1.0
- screen 2: resolution 1920x1080, scale 1.0
- screen 3: resolution 1920x1080, scale 1.0

Plugins:
- Segment (blobs and things with membranes): 0.2.7
- animation: 0.0.2
- console: 0.0.4
- napari-time-slicer: 0.1.4
- napari-tools-menu: 0.1.5
- ome-types: 0.2.9
- scikit-image: 0.4.13.dev80+gd0b6b3f17.d20211126
- svg: 0.1.5
```

**Comment by brisvag** [comment]
@Czaki, is there a reason why you set `translation_grid`, rather than `translation`? `translation_grid` gets automatically calculated every time the layerlist changes, because it's the transform used by the grid mode to put layers side by side.
It seems that `translation_grid` should have been private in the first place.

**Comment by Czaki** [comment]
I do not remember, this is based on the old part of the code which is based on grid view from 0.3.x napari line code.

**Comment by brisvag** [comment]
But are you actually trying to affect the grid view, or is this supposed to be a simple translation? Can you provide a bit more context so we can see if there's a reason for `translation_grid` to be accessible? Otherwise, I think you should just stick to `translate` and I will open a PR proposing to privatise `translate_grid`.

**Comment by Czaki** [comment]
I will check tomorrow.

**Comment by Czaki** [comment]
@brisvag  using `translate` instead of `translate_grid` works perfectly. But `translate_grid` getter should remain public. And maybe the setter should become first deprecated.

**Comment by brisvag** [comment]
Why do you think the getter should stay public? Definitely agree on deprecation.

**Comment by Czaki** [comment]
> Why do you think the getter should stay public? Definitely agree on deprecation.

I think that getting the current (final) value of the current translation grid value for some calculation. But maybe it should be done with `world2data` and `data2world`. But one of them is not public yet.

**Comment by andy-sweet** [comment]
@Czaki : I'm not sure, but I think that #3754 might have resolved the issues you described in the comments here. If so, can you close this?
