### ISSUE TITLE
Add "tips for debugging plugins during development" page

### ISSUE THREAD

**Issue by jni** [napari/napari#3735]
## 📚 Documentation

Talley had a wonderful answer to an imagesc question on best practices for debugging a plugin during development, where you might be editing code, then having to reload the whole napari state (data, view, plugin dock widgets) manually each time. This is an issue I've come across a lot myself, and we should definitely add these tips to the docs.

https://forum.image.sc/t/debug-develop-napari-plugin-how-to-reload-changed-code/60618/4

**Comment by chili-chiu** [comment]
see also issue #2948
