### ISSUE TITLE
[Discussion] Overlays

### ISSUE THREAD

**Issue by brisvag** [napari/napari#3755]
## 🚀 Feature
Often the desire to work on (and unify) `overlays` (or `highlights`) comes up in different contexts (#2560, #3068, #2954, #999). By overlays, I mean visuals that live in canvas space that are not data and are supposed to be displayed on top of everything that's data.

While this is currently possible, it's not unified (see the code duplication in [`napari/_vispy/overlays/`](https://github.com/napari/napari/tree/main/napari/_vispy/overlays)) and a bit finnicky to work with. Despite this, we are getting updates on this, like the recent, beatuiful work by @jojoelfe on the interaction box (#3577).

A few weeks ago we discussed about this with @kevinyamauchi and @alisterburt , who then started working on the "3D" counterpart to overlays (non-data objects that live in data space) over at https://github.com/alisterburt/napari-threedee. This issue is to start some discussion on 2D overlays.

I'm already mocking up something in a branch, but I'd like some feedback before I move forward.

## Goal

It would be great to get `overlays` to the same level (or better :P) as `layers`. This means:

- [ ] evented models on the viewer
    - [x] evented models for each overlay
    - [ ] unified behaviour: currentlly they all live on `viewer` except for `interaction_box`, which lives on `viewer.overlays`. Why? Should we move everything to `viewer`?
- [ ] automatically generate overlays (with something like like `create_vispy_visual` for layers), to minimize how much `qt_viewer` needs to know about vispy
- [ ] create superclass similar to `VispyBaseLayer` and make all overlays use it
- [ ] start using them properly (e.g: remove the selection box from the points visual and use `interaction_box` instead)

## Questions

What does everyone think about this? Am I going in the wrong direction?
The one thing I'm particularly in doubt about is where these things should live on the API, especially after the precedent of `interaction_box`. Should we even allow multiple `interaction_box` to be displayed?

**Comment by jojoelfe** [comment]
> * unified behaviour: currentlly they all live on `viewer` except for `interaction_box`, which lives on `viewer.overlays`. Why? Should we move everything to `viewer`?

When we were discussing where to put the interaction_box a fear was to crowd the namespace of the viewer and the plan was to move other overlays, such as the axes and the scalebar,  also into this dedicated namespace.


> The one thing I'm particularly in doubt about is where these things should live on the API, especially after the precedent of `interaction_box`. Should we even allow multiple `interaction_box` to be displayed?

The nice thing about it existing as an instance in the API is that is simplifies dealing with keyboard and mouse events, as it guarantees that only one exists. For the visual there is no problem if multiple existed, just the controller would be more complicated.


> * start using them properly (e.g: remove the selection box from the points visual and use `interaction_box` instead)

Yes, happy to do that! The only issues that has me a bit worried is that in the edit mode of the point layer there is a mouse-event listener on the layer, while the interaction_box uses a mouse-event listener on the viewer. Not quite sure yet how one would assign priority to the events.

**Comment by brisvag** [comment]
Housekeeping: will be closed by #4894!
