### ISSUE TITLE
Add tooltip to npe2 plugin enable/disable checkboxes

### ISSUE THREAD

**Issue by DragaDoncila** [napari/napari#3780]
## 🧰 Task
Currently it's not clear why some plugins' enable/disable button is greyed out because there's nothing telling the user it's an npe2 plugin. It would be great if we could add a tooltip on checkbox hover that tells the user "This plugin cannot be disabled as it's an npe2 plugin" or something like that.

This depends on how long we think it'll take us to get the enable/disable functionality sorted. Pinging @tlambert03 @nclack and @ppwadhwa.

**Comment by nclack** [comment]
I like the tooltip idea.

I also wonder if there should be an npe2 badge or something displayed on those plugins. It would be nice to have some visual indicator especially for plugin developers who are migrating their plugins.

**Comment by ppwadhwa** [comment]
Yes,  I like the tooltip and the badge!

**Comment by tlambert03** [comment]
> I also wonder if there should be an npe2 badge or something 

maybe 😎 ?
