### ISSUE TITLE
Color maps for images displayed

### ISSUE THREAD

**Issue by pranathivemuri** [napari/napari#381]
## 🚀 Feature
It would be great to have the images displayed in default colormaps like a grayscale color map for grayscale images and RGB for color images instead of the default "magma" colormap. It converts images to unexpected colors. It might be a problem with binary images containing 0, 1 to be displayed in "gray" colormap but something else might be a good colormap in this case. I am not sure if this is easy to add or if there was a reason to chose the "magma" 

## Motivation

<See the images in expected colors-->

## Pitch

<Based on the number of channels and datatype - set normally expected colormaps instead of magma colormap-->

**Comment by jni** [comment]
magma allows more contrast than grayscale, so it allows users to see the variation in their data better than a grayscale colormap. For our current examples, which include natural images, it doesn't make sense, but for scientific data it's quite useful to get that added contrast. Matplotlib use viridis and Matlab uses parula (previously jet), so I think it's pretty standard in scientific communities to use a high-contrast colormap.

Having said this, I'm not too fanatical about this, and could be talked into grayscale as the default.

**Comment by pranathivemuri** [comment]
yes, totally for scientific data added contrast would be great. But having that optional and showing what actually the images look like would be better I think.

we could mention in the docs/help section that changes in colormaps can yield add contrast. or just a note on the gui at the "cmap" button that hovers and says change colormap to add contrast probably?

I can see two sides to this. If someone has low contrast images and they open it up on napari if everything is black they might wonder if napari is working. But it would still give them the right data that their thumbnails and other viewers show.

**Comment by sofroniewn** [comment]
I'm open to either. I think in the first instance though just exposing the colormap keyword argument and clims arguments on the `Image` layer will be a step in the right direction

**Comment by sofroniewn** [comment]
As discussed on the call - we will switch this to `gray`, thanks @pranathivemuri for highlighting this.

@jni I can do this in the PR I'm working on right now for testing the image layer and adding keyword args like `colormap` etc

**Comment by jni** [comment]
Go for it!

**Comment by sofroniewn** [comment]
We have switched to `gray` as default in #391
