### ISSUE TITLE
multiple copies of the OpenMP runtime have been linked into the program

### ISSUE THREAD

**Issue by AuSpotter** [napari/napari#3810]
## To Reproduce

1. Open napari
2. Try to open an image
3. Software crash

OMP: Error #15: Initializing libiomp5md.dll, but found libiomp5md.dll already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.

## Environment

 - Please copy and paste the information at napari info option in help menubar here:
napari: 0.4.12
Platform: Windows-10-10.0.19043-SP0
Python: 3.9.7 | packaged by conda-forge | (default, Sep 29 2021, 19:15:42) [MSC v.1916 64 bit (AMD64)]
Qt: 5.15.2
PyQt5: 5.15.6
NumPy: 1.20.3
SciPy: 1.7.3
Dask: 2021.12.0
VisPy: 0.9.4

OpenGL:
- GL version: 4.6.0 NVIDIA 456.71
- MAX_TEXTURE_SIZE: 32768

Screens:
- screen 1: resolution 2560x1080, scale 1.0
- screen 2: resolution 1050x1680, scale 1.0

Plugins:
- Measurements (skimage regionprops): 0.2.5
- Utilities (skimage regionprops): 0.2.5
- console: 0.0.4
- napari-allencell-segmenter: 1.1.3
- napari-tools-menu: 0.1.7
- ome-types: 0.2.9
- platelet-unet-watershed: 0.0.3
- scikit-image: 0.4.12
- svg: 0.1.5=

**Comment by jni** [comment]
@AuSpotter napari doesn't include any compiled code, so this is unlikely to be a napari issue. I suspect it's rather scikit-image. Can you tell us more about how you installed napari, and what kind of image you're opening?

**Comment by jaimergp** [comment]
Seeing Python packaged by conda-forge but PyQt at version 5.15 (back in 2021) makes me think that a combination of `conda` and `pip` install commands was used to get to this point (which is not supported). It should work with a fresh environment created like this:

```
$ conda create -n napari -c conda-forge napari
$ conda activate napari
$ napari
```
