### ISSUE TITLE
Cannot get napari to run in ubuntu 20.04

### ISSUE THREAD

**Issue by bheit** [napari/napari#3816]
## 🐛 Bug

I am unable to get napari to run in ubuntu 20-04, using either the appimage or the conda install option.

conda fails as the QT version that has been installed (5.9.7) doesn't work with napari. I have tried installing the 5.12.3 version that napari is tested on, but even so, conda ignores the 5.12.3 version and refuses to launch. From the command line I get:

```
bryan@bryans-desktop:~$ napari
/home/bryan/miniconda3/lib/python3.9/site-packages/napari/_qt/__init__.py:54: UserWarning: 

napari was tested with QT library `>=5.12.3`.
The version installed is 5.9.7. Please report any issues with
this specific QT version at https://github.com/Napari/napari/issues.
  warn(message=warn_message)
Segmentation fault (core dumped)
```
When I try to update miniconda to QT 5.12.3 I get the following:
```
bryan@bryans-desktop:~$ conda install -c conda-forge qt
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/bryan/miniconda3

  added / updated specs:
    - qt


The following packages will be UPDATED:

  ca-certificates    conda-forge/label/cf202003::ca-certif~ --> conda-forge::ca-certificates-2021.10.8-ha878542_0

The following packages will be SUPERSEDED by a higher-priority channel:

  conda              pkgs/main::conda-4.11.0-py39h06a4308_0 --> conda-forge::conda-4.11.0-py39hf3d152e_0


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
```
When I try to run napari after this "upgrade" I get the same error about QT 5.9.7.

For the appimage, the issue is different. From the command line I get:
```
bryan@bryans-desktop:~/Programs$ ./napari.AppImage
Traceback (most recent call last):
  File "/tmp/.mount_napari0AUgAz/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/tmp/.mount_napari0AUgAz/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/.mount_napari0AUgAz/usr/app/napari/__main__.py", line 435, in <module>
    sys.exit(main())
  File "/tmp/.mount_napari0AUgAz/usr/app/napari/__main__.py", line 431, in main
    _run()
  File "/tmp/.mount_napari0AUgAz/usr/app/napari/__main__.py", line 230, in _run
    from napari import run, view_path
  File "/tmp/.mount_napari0AUgAz/usr/app/napari/_lazy.py", line 42, in __getattr__
    from scipy import stats  # noqa: F401
  File "/tmp/.mount_napari0AUgAz/usr/app_packages/scipy/__init__.py", line 153, in <module>
    from scipy._lib._ccallback import LowLevelCallable
  File "/tmp/.mount_napari0AUgAz/usr/app_packages/scipy/_lib/_ccallback.py", line 1, in <module>
    from . import _ccallback_c
  File "_ccallback_c.pyx", line 210, in init scipy._lib._ccallback_c
  File "/tmp/.mount_napari0AUgAz/usr/lib/python3.9/ctypes/__init__.py", line 8, in <module>
    from _ctypes import Union, Structure, Array
ImportError: libffi.so.6: cannot open shared object file: No such file or directory
```

This appears to be because ubuntu comes with libffi7, not with libffi6. Using pienv I have manually installed python version 3.7.4, which should resolve this issue (at least, it did for a different program where I had the same issue), but in this case the issue remains.

Bryan

**Comment by tlambert03** [comment]
> the QT version that has been installed (5.9.7) doesn't work with napari.

this suggests that you might have installed without using the conda-forge channel, or that you installed into an existing environment that already had qt.  Can you try, in a clean environment, as described in the readme, and paste the full output of what you get?

```sh
# from readme
conda create -y -n napari-env -c conda-forge python=3.9
conda activate napari-env
pip install "napari[all]"
```

> When I try to update miniconda to QT 5.12.3 I get the following:
> `conda install -c conda-forge qt`

you more or less never want to update qt like that (it will very often lead to a binary incompatibility like you observed).  In general, look for _all_ of qt backends you have installed (like `pyqt` and or `pyside2`, uninstall them all, then reinstall _one_ of them, for instance `conda install pyqt` (note, `pyqt` not `qt).

However, in this case, it's probably better to just start with a fresh environment.

**Comment by bheit** [comment]
Removing and reinstalling conda appears to have fixed the issue, although I can only launch it from terminal. If I "pin" it to favourites, it won't launch from the icon.

**Comment by tlambert03** [comment]
> Removing and reinstalling conda appears to have fixed the issue, although I can only launch it from terminal.

that suggests you may have messed up the base environment somehow along the way (very possible to do with Qt if you install a few different qt-dependent things into your base environment).  I don't think pinning the icon like that from a python app from a conda environment will ever work.  For that, you'd need to use the bundled application.

thanks for letting us know about the fix!
