### ISSUE TITLE
Capability to exporting markers,regions coordinates into csv file or xlsx files

### ISSUE THREAD

**Issue by pranathivemuri** [napari/napari#382]
## 🚀 Feature
<Capability to exporting markers,regions coordinates into csv file or xlsx files-->

## Motivation

Annotators/Pathologists/ in general people who don't have access to/know how to code in python can just go to in the menu on GUI File -> export markers -> select file type/filename (csv or xlsx) and save them.

**Comment by GenevieveBuckley** [comment]
I think something like this might work well for points, and a similar method for polygons could be made pretty easily as well. I'll open a PR in a bit, unless anyone has comments now.

```python
def to_csv(self, filename):
    with open(filename, mode='w') as file:
        writer = csv.writer(file, delimiter=',', quotechar='"', quoting=csv.QUOTE_MINIMAL)
        n_dimensions = self.data.shape[1]
        header = ['id'] + ['dimension_' + str(n) for n in range(n_dimensions)]
        writer.writerow(header)
        for idx, row in enumerate(self.data):
            point_data = np.concatenate([np.array([idx]), row])
            writer.writerow(point_data)
```

**Comment by sofroniewn** [comment]
This has now been implemented with our builtin writer plugin
