### ISSUE TITLE
Zulip link not obvious in the documentation page

### ISSUE THREAD

**Issue by dpshelio** [napari/napari#3822]
## 📚 Documentation

The Zulip link is shown at the bar in the bottom of the page, but not in any of the community pages (or at least that I could find quickly). 

There's a link when creating an issue on github, but that's a bit far reached for someone want/need to open an issue.
Adding a small "chat with us" link on the main community page or in the readme will make it easier to find.

**Comment by jni** [comment]
There *is* a link in the "about the project and team" page, but it's certainly buried in the text. I agree that we should make it more visible on the home page. Thanks @dpshelio!

**Comment by dpshelio** [comment]
Wow! I completely missed that link. It's even mentioned twice! (again at the bottom of the history section). My suggestion would be to have it in the top of [Community resources](https://napari.org/community/index.html), a link to Zulip, the forum and probably to the issues on GH.

**Comment by melissawm** [comment]
I believe this is done as now we do have a link to zulip in the Community page. Please reopen otherwise!
