### ISSUE TITLE
Move napari calendar to it's own page in the docs

### ISSUE THREAD

**Issue by GenevieveBuckley** [napari/napari#3826]
## 📚 Documentation
As discussed elsewhere, we want to move the napari calendar to it's own separate page in the docs.

It currently lives on the community page called "About the Project and Team" https://napari.org/community/team.html

We want to move it to it's own separate page called "calendar" still under the community section.

What problem is this solving?
- People have reported it takes them a few tries to remember where the calendar lives in our docs today
- We also want to be able to link directly to the calendar when inviting new folks to join (not, link to a page and then explain they should scroll down past a bunch of stuff they don't care about right now)
- We would also be able to do things like set up a nice preview of the page when we link to it from social media (for example, a link to the page from twitter could show a preview including the next couple of scheduled events)

**Comment by liu-ziyang** [comment]
closing the loop: we now have it under https://napari.org/community/meeting_schedule.html
