### ISSUE TITLE
Eraser in fill/paint brush layer 

### ISSUE THREAD

**Issue by pranathivemuri** [napari/napari#383]
Add "eraser" feature to pixel-wise painting layer

Motivation
If a pixel is incorrectly painted as a label and we want to erase the label and set it to zero. It would be great to have a single pixel/varying pixel sized eraser icon that lets you change that. For example, I had manual annotations of cells that are touching each other when they weren't actually. So, I had to open them in matplotlib and manually set these pixel locations to zeros.

Pitch
Press an eraser icon to erase the incorrect annotations manually

**Comment by sofroniewn** [comment]
To achieve this you can set the value of the label to be painted to zero and then use the exact same paintbrush and fill tools. You can set the label to zero either in the expanded properties widget in the right or by selecting the color picker and clicking on an unlabeled background pixel. Would this meet your needs? If so we need to make sure we make this clear in our documentation

**Comment by jni** [comment]
It's probably useful to have an eraser button that sets the label to 0.

**Comment by pranathivemuri** [comment]
both solutions work. but maybe eraser button would be good to have, I think

**Comment by sofroniewn** [comment]
This has now been more extensively documented in our tutorial on the labels layer - see here http://napari.org/tutorials/labels.html

pressing the `E` key will also set the selected label to 0
