### ISSUE TITLE
npe2 doc feedback

### ISSUE THREAD

**Issue by nclack** [napari/napari#3830]
## 📚 Documentation

This is a collation of issues reported in this [zulip thread](https://napari.zulipchat.com/#narrow/stream/212875-general/topic/npe2.20migration.20questions)

npe2 getting started guide
- [x] cookiecutter should generate reader for *.npy files but doesn't

npe2 migration guide
- [x] migration guide refers to `_hookimpls:AnimationWidget` in one place and `_qt.AnimationWidget` in another.
- [x] using builtins in examples is confusing
- [x] not clear: what happens when a plugin has both `napari-plugin-engine` bindings and `npe2` bindings.
- [x] need examples with multiple kinds of contributions.
- [x] surprising: commands, readers, writers at same level in hierarchy

**Comment by guiwitz** [comment]
Thanks for opening this issue regarding my comments. I just wanted to mention that I opened an issue regarding the very first point directly on the cookiecutter-napari-plugin repo (https://github.com/napari/cookiecutter-napari-plugin/issues/73).

**Comment by nclack** [comment]
> I opened an issue regarding the very first point directly on the cookiecutter-napari-plugin repo

thanks!

**Comment by nclack** [comment]
@tlambert03 has done some significant improvements to the plugin docs in napari#3916. Linking it here since it addresses some of this feedback.

**Comment by chili-chiu** [comment]
@nclack looks like these items are all addressed for npe2 doc? Are there still outstanding ones you'd like to track, or should we close this issue?

**Comment by nclack** [comment]
Yes all issues have been addressed
