### ISSUE TITLE
Documentation on Napari example without context manager

### ISSUE THREAD

**Issue by pranathivemuri** [napari/napari#384]
## 📚 Documentation

Without context manager, we would have to %gui qt5 and wait for a few seconds until it generates the window and then call napari methods. Can we mention in this documentation to avoid seeing the below warning/abort

(napari) vemuri-mbp:~ pranathivemuri$ ipython3
impPython 3.6.5 (default, Jun 17 2018, 12:13:06)
Type "copyright", "credits" or "license" for more information.

IPython 5.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import napari

In [2]: %gui qt5
  ...: from skimage import data
  ...: import napari
  ...: viewer = napari.view(data.astronaut(), multichannel=True)
  ...:
WARNING: QWidget: Must construct a QApplication before a QWidget
Abort trap: 6

Mention in readme/docstring that in another ipython window to execute the magic command %gui qt5 and see that a window is created

**Comment by jni** [comment]
ouch! We should also point out that one can launch IPython with `ipython --gui=qt`, or even set this in the configuration (which is what I have). That should provide a more seamless experience, although annoyingly on mac it means the terminal loses focus immediately after launch.

**Comment by sofroniewn** [comment]
Yup, this is the second time it's come up - see #206, so we definitely need to make this clear

**Comment by sofroniewn** [comment]
This has now been explained in our [installation tutorial](https://napari.github.io/napari-tutorials/tutorials/installation.html), including the ability to launch `ipython --gui=qt5`

**Comment by sofroniewn** [comment]
link should be [getting started tutorial](https://napari.github.io/napari-tutorials/tutorials/getting_started.html)
