### ISSUE TITLE
For example, you can add multiple images in different layers and adjust them

### ISSUE THREAD

**Issue by pranathivemuri** [napari/napari#385]
## 📚 Documentation
In the readme, the example output doesn't really seem like images were overlaid.
This below image might be better and mentioning that opacity on layers is tweaked to obtain such an image might be good. Just a suggestion
<img width="637" alt="Screen Shot 2019-07-02 at 4 02 08 PM" src="https://user-images.githubusercontent.com/10284094/60552218-d2853d00-9ce2-11e9-91b0-2193ac0988c5.png">

**Comment by jni** [comment]
I love it!

**Comment by sofroniewn** [comment]
agreed, thanks for the suggestion @pranathivemuri. Would you like to make a PR changing the example to be this way?

**Comment by sofroniewn** [comment]
fixed in #399
