### ISSUE TITLE
3D stack example in Readme doesn't give the expected figure as in the Readme

### ISSUE THREAD

**Issue by pranathivemuri** [napari/napari#386]
## 📚 Documentation
It gives a very anisotropic narrow pixel figure as below

array size = (128, 128, 128, 10), dtype=bool
code ran:
import numpy as np
from skimage import data
import napari
from napari.util import app_context

with app_context():
    # create fake 3d data
    blobs = np.stack([data.binary_blobs(length=128, blob_size_fraction=0.05,
                                        n_dim=3, volume_fraction=f)
                     for f in np.linspace(0.05, 0.5, 10)], axis=-1)
    # add data to the viewer
    viewer = napari.view(blobs.astype(float))

obtained output:
<img width="424" alt="Screen Shot 2019-07-02 at 4 20 01 PM" src="https://user-images.githubusercontent.com/10284094/60552897-a5865980-9ce5-11e9-8a5a-272de3f22b86.png">

expected output:
https://github.com/napari/napari/blob/master/resources/screenshot-nD-image.png
<img width="1162" alt="screenshot-nD-image" src="https://user-images.githubusercontent.com/10284094/60552951-d797bb80-9ce5-11e9-9960-3ce7ad070411.png">

**Comment by jni** [comment]
This probably was missed when we changed the dimensions ordering. We just need to change `axis=-1` to `axis=0`.

**Comment by pranathivemuri** [comment]
oh makes sense! z is the first dimension

**Comment by pranathivemuri** [comment]
fixed in https://github.com/napari/napari/pull/399
