### ISSUE TITLE
Add sensible `builtin` defaults as reader preferences

### ISSUE THREAD

**Issue by DragaDoncila** [napari/napari#3868]
## 🧰 Task
Add sensible default settings for common filetypes so that the file open dialog doesn't pop up on initial opening of common filetypes.

My plan is to add defaults for anything that builtin plugins *can* read. These preferences could then of course be removed/changed via the preferences dialog.

**Comment by DragaDoncila** [comment]
So I started looking at implementing this, but I actually don't necessarily think we should? I initially opened this issue based on discussion in community meeting, and I think it was @sofroniewn who originally suggested it.

However, working with a clean install of napari now, I think I prefer the existing behavior. The reader dialog only ever pops up when there's a choice to be made. This means if you just clean install napari, you *can* already use all the builtins as you'd expect.


https://user-images.githubusercontent.com/17995243/151274336-cfd7ac5d-4a2f-42f1-8c8b-a5cb5b27dffa.mov


It's only once you install plugins that can *also* read what builtins can read that the dialog pops up and asks you to make a choice.

https://user-images.githubusercontent.com/17995243/151274611-8efe29e5-7c5a-4764-ae1f-f30c72a4d60b.mov


Adding default fie extension preference seems less usable because in that second recording, you'd have to actually go into preferences and remove the association before you could use your freshly installed plugin.

I'm curious whether now that the reader dialog has been out in the wild and people have had a chance to play with it, we still think we'd like to add default associations? Pinging @jni who liked this issue before, and @nclack and @tlambert03 who are also familiar with the work, but I'd love to get feedback from anyone who's interacted with the dialog as is.

**Comment by nclack** [comment]
> The reader dialog only ever pops up when there's a choice to be made.

Seems pretty convincing to me.

**Comment by sofroniewn** [comment]
Ok yeah, i have actually given this more thought after I started using the new release too and quite like the current behavior. thanks for looking into it more - i think you've made a pretty compelling case though that we shouldn't do this. curious what others think, but right now i'd be fine with just closing this.

**Comment by tlambert03** [comment]
I like the current behavior too after using it a bit!  thanks @DragaDoncila!

**Comment by tlambert03** [comment]
Btw... do we know what happens if the previously selected plugin has been uninstalled in the meantime?  I forget if that was handled

**Comment by DragaDoncila** [comment]
> Btw... do we know what happens if the previously selected plugin has been uninstalled in the meantime? I forget if that was handled

If for whatever reason we can't open the file with the associated plugin, we present the dialog to the user (even if there's only one choice remaining) e.g.

https://user-images.githubusercontent.com/17995243/151281429-b269f2ba-8e8f-47f1-bae0-50c32f551ffe.mov

It's up to them at that stage if they want to overwrite the association with the remaining plugin, cancel the file open and figure out where their plugin went, etc.

**Comment by DragaDoncila** [comment]
Thanks everyone for weighing in. I will leave this issue open overnight in case someone dissents, and will otherwise close tomorrow morning.
