### ISSUE TITLE
Surface layer control panel looks wrong

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#3877]
## 🐛 Bug

![image](https://user-images.githubusercontent.com/6531703/147324724-14e344ec-4495-4d26-8727-0f9c5bc315f5.png)

Something doesn't look right with the control panel in the top left for the surface layer. it looks like the continous button is now overlapping with the opacity slider. run `python examples/add_surface_2D.py` to see.

we should fix before next release

**Comment by kevinyamauchi** [comment]
I had a quick look and I think it is because we forgot to add the "autoscale bar" to the surface controls layout when it was added for the image layers (the surface layer controls inherit from `QtBaseImageControls`). I can make a fix.
