### ISSUE TITLE
Drop image `meta` dict and replace with kwargs

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#388]
## 🚀 Feature
I'd like to drop the image meta data property and replace with explicit keyword arguments to the image layer. I worry passing an arbitrary dictionary right now is too much freedom and we should be explicit about what keyword arguments we support. I also think we should expose all the key parameters as keyword arguments (like `clim`, `colormap`, `blending`, etc.). Thoughts @kne42 @royerloic @jni?

**Comment by sofroniewn** [comment]
resolved by #391 - we added a `metadata={}` keyword arg only for image metadata and made all other input params like `clim`, `colormap` etc. keyword args too

**Comment by jni** [comment]
@sofroniewn fwiw I think it should be `metadata=None`, as it's considered bad practice to use mutable types as default arguments.

**Comment by sofroniewn** [comment]
that's fine, I will fix in a followup
