### ISSUE TITLE
3 files ASCII with CRLF, should maybe be converted to unix ending ? 

### ISSUE THREAD

**Issue by Carreau** [napari/napari#3889]
## 🧰 Task

It seem we have 3 files that have CRLF in them, some tools don't like those, and it may be disturbing to some contributors that may see spurious `^M` (CR) in diff tools.

It would be good to update those to redo the newline, but unfortunately that would modify all the lines in history

```
 fd '.py' | xargs file | grep CRLF
napari/_tests/test_interactive_transforms.py:                         Python script text executable, ASCII text, with CRLF line terminators
napari/components/_interaction_box_mouse_bindings.py:                 Python script text executable, ASCII text, with CRLF line terminators
napari/layers/image/_image_key_bindings.py:                           Python script text executable, ASCII text, with CRLF line terminators
```

and if you are curious:

```
$ fd '.py$' | xargs file | cut -f2 -d: | tr -s ' ' | sort | uniq -c | sort -nr
 662  Python script text executable, ASCII text
  31  empty
  25  Python script text executable, Unicode text, UTF-8 text
   6  ASCII text
   3  Python script text executable, ASCII text, with CRLF line terminators
   1  directory
   1  Unicode text, UTF-8 text, with very long lines (1116)
   1  Python script text executable, ASCII text, with very long lines (497)
   1  Python script text executable, ASCII text, with very long lines (471)
   1  Python script text executable, ASCII text, with very long lines (310)
   1  Pascal source text, ASCII text
   1  GNU gettext message catalogue text, Unicode text, UTF-8 text, with very long lines (2060)
```

**Comment by sofroniewn** [comment]
Hmm, i know very little about this. I would be fine with any approach. What do others think here?

**Comment by tlambert03** [comment]
Unix ending works for me

**Comment by jni** [comment]
I'm also +1 on harmonising line endings. @Carreau do you think we should also add another pre-commit check so that we don't add any new such files by accident?

**Comment by Carreau** [comment]
> I'm also +1 on harmonising line endings. @Carreau do you think we should also add another pre-commit check so that we don't add any new such files by accident?

Nah, I don't think it's necessary. It's rare enough, I don't even know how it could have happen.
And if anything we might want to add a .gitattributes files asking git to aumatically do the CRLF to LF conversion I belive this is possible on a per-repository setting.
