### ISSUE TITLE
Issue with HoloViews and napari notebook magics interfering even after kernel restart?

### ISSUE THREAD

**Issue by StephenThornquist** [napari/napari#3892]
Hi, I don't actually know much about Notebooks (or `holoviews`), and I'm only now starting to use and learn about `napari`, so maybe this is a totally silly question with a trivial fix. Or maybe the two are destined never to be compatible for reasons that I would understand if I were a more learned programmer. But I thought I'd ask, since `holoviews` has lots of functionality that is nice for plotting non-image data (though here I intend it to be a transformed version of something extracted from image data), and it'd be great if the two can play nice. Both behave well in fresh environments -- as well as in ones where I already have installed many packages -- on their own.

## 🐛 Bug

If both of 
1) `holoviews` is imported and any extension (`bokeh` or `matplotlib`) initialized in a Notebook with `holoviews.extension`
and
2) a `Viewer` object is created

it causes all sorts of funny stuff with holding up the interpreter. In general, it seems to lag one cell behind the most recent request. Execution of the next cell can be induced by closing the open `Viewer` but that will only execute the next cell called (it won't allow you to just execute all subsequent cells).

## To Reproduce

Doing the following has been sufficient to reproduce the behavior in my hands, in a Jupyter notebook.

In the first cell:
```
import numpy as np
import napari

napari.view_image(data=np.random.randn(10,512,512))
```

Now run a second cell and see that it executes
```
2+2
```
```
4
```

```
# importing Bokeh itself is fine, as is holoviews
import holoviews as hv
import bokeh
2+2
```
```
4
```

The above should execute without freezing the interpreter. Now run the cell below, and observe that the interpreter will hang on subsequent cells:

```
hv.extension('bokeh')
```
(this one executes but then...)
```
2+2
```
You can see it appear to hang, but watch: run the next cell!
```
2+2
```
The previous one now executes and returns 4! So it hasn't totally locked up, it just seems like something strange is
happening with the interpreter?

But now restart the kernel, and try running the above again. The first cell will execute (creating a new `Viewer`), but the next cell will similarly hang, even though `holoviews` and `bokeh` haven't yet been imported, much less initialized. If you don't create a new `Viewer`, then everything behaves totally fine after the kernel restart (even if you again import and initialize `holoviews`). To get a well-behaved Notebook, now you have to shut down the notebook entirely and open it again.

It's specifically something about the `extension` call -- creating and manipulating simple `holoviews` objects doesn't cause any problems.

## Environment

I'm on macOS Mojave 10.14.6 though I don't think my old versioning is the issue. 

In my actual data analysis environment, I'm using:

`napari == 0.4.12`
`holoviews == 1.14.2`
`bokeh == 2.3.0`
`python == 3.9.2`
`jupyter == 1.0.0`

Though I can reproduce the bug in a fresh `conda` environment in which I only install (along with automatic dependencies) `numpy`, `holoviews`, `bokeh`, and `napari` without specifying any versioning (which ends up being `python == 3.9.9`, `napari == 0.4.12`, `holoviews == 1.14.7`, and `bokeh == 2.4.2`).

**Comment by psobolewskiPhD** [comment]
Oh wow! I've seen this same behavior with VS Code Interactive Windows—thought I was going crazy and was busy so sort of neglected it.
Using the example above:
```
# %%
import numpy as np
import napari
# %%
napari.view_image(data=np.random.randn(10,512,512))
# %%
2+2
# %%
2+2
# %%
```
The second `2+2` will hang but if you replace `napari.view_image` with just the `np` command, everything is fine.

**Comment by tlambert03** [comment]
I'm not familiar with holoviews, but the most likely interaction is with Ipython's [GUI event loop](https://ipython.readthedocs.io/en/stable/config/eventloops.html), which napari starts by default when creating a viewer (unless it's turned off in the settings).

Can you leave napari out of it (don't import or create a viewer), and just test whether calling the `%gui qt` magic has the same result as creating a viewer?  If so, we'll need to look into how any event loops in holoview are interacting with ipython's qt event loopp

**Comment by StephenThornquist** [comment]
> I'm not familiar with holoviews, but the most likely interaction is with Ipython's [GUI event loop](https://ipython.readthedocs.io/en/stable/config/eventloops.html), which napari starts by default when creating a viewer (unless it's turned off in the settings).
> 
> Can you leave napari out of it (don't import or create a viewer), and just test whether calling the `%gui qt` magic has the same result as creating a viewer? If so, we'll need to look into how any event loops in holoview are interacting with ipython's qt event loopp

Correct! Strangely, it's slightly less consistent, in the sense that it will sometimes execute a few cells normally before the issue springs up. If it's a generic HoloViews thing, sounds like I should raise the issue there, and not bother you with it (though the above comment suggests whatever pathology underlies this issue might show up in more than one external package?). Thanks!

EDIT: As you might expect, this means that if I give up on interactivity (a high price to pay since `napari` seems to do this so beautifully) by preceding everything with a `get_settings().application.ipy_interactive = False` then everything behaves well until the eventual `napari.run()` call. I'll come back to this space to elaborate if I find a solution that is less heartbreaking.

For others encountering these issues (and they seem to be more generic than just applying to HoloViews, so perhaps the solution(s) will be more generic too), I've posted a discussion here: https://discourse.holoviz.org/t/holoviews-interferes-with-gui-qt-event-loops-in-jupyter-notebooks-is-there-a-way-to-avoid-this/3209 and an issue here: https://github.com/holoviz/panel/issues/3054

**Comment by psobolewskiPhD** [comment]
Same here in VS Code Interactive Python.
```
# %%
import numpy as np
# %%
%gui qt
np.random.randn(10,512,512)
# %%
2+2
# %%
2+2
# %%
```
Results in the 2nd `2+2` hanging just like the napari viewer code above.
(I don't get this issue in ipython btw.)

**Comment by pmeyer321** [comment]
I had the same problem with VS Code Interactive Python (often) hanging on executing the second cell after opening a napari viewer, however the problem seemed to be caused by the qt loop, as the following code reproduced the issue:
```
# %%
%gui qt
# %%
1+1
# %%
2+2   # hangs here
````
Updating VS Code to Version 1.64.2 solved the problem for me though. (using Microsofts Jupyer extension v2022.2.1010551006)

**Comment by psobolewskiPhD** [comment]
> Updating VS Code to Version 1.64.2 solved the problem for me though. (using Microsofts Jupyer extension v2022.2.1010551006)

Same here! I'm on 1.65-Insider now, forgot about this issue, but it's been fine for a little while.

**Comment by StephenThornquist** [comment]
For those not getting it in iPython, could you let me know what version of python / ipython you're using? Would really love for this not to be an issue for me anymore!

**Comment by pmeyer321** [comment]
The problem of `%gui qt` making the second cell executed afterwards hang does not occur for me with the updated VSCode using Python 3.9.9 and IPython 8.0.1

**Comment by psobolewskiPhD** [comment]
I can't reproduce with Jupyter Lab Version 4.2.5 or latest VS Code Version: 1.96.0-insider
Based on the message above https://github.com/napari/napari/issues/3892#issuecomment-1049711033 this was likely fixed a while ago.
Closing.
