### ISSUE TITLE
Collapsing slider in examples/slider.py leads to crash

### ISSUE THREAD

**Issue by royerloic** [napari/napari#39]
Collapsing slider in examples/slider.py leads to crash:

![image](https://user-images.githubusercontent.com/1870994/47972309-b2b45100-e04f-11e8-8a31-ee266910898a.png)

I 'right' clicked and bam...

**Comment by AhmetCanSolak** [comment]
Thank you so much @royerloic !
I proposed a fix with #42  . Please check that.

**Comment by AhmetCanSolak** [comment]
PR merged
