### ISSUE TITLE
napari GUI does not work : "ImportError: cannot import name 'run' from 'napari'"

### ISSUE THREAD

**Issue by emoebel** [napari/napari#3908]
## 🐛 Bug

I installed Napari using Conda. But when launching GUI from terminal, I get error:

```
/Users/emoebel/miniconda3/envs/tradefi/lib/python3.7/site-packages/napari/_qt/__init__.py:54: UserWarning: 

napari was tested with QT library `>=5.12.3`.
The version installed is 5.9.6. Please report any issues with
this specific QT version at https://github.com/Napari/napari/issues.
  warn(message=warn_message)
/Users/emoebel/miniconda3/envs/tradefi/lib/python3.7/site-packages/napari/_qt/__init__.py:54: UserWarning: 

napari was tested with QT library `>=5.12.3`.
The version installed is 5.9.6. Please report any issues with
this specific QT version at https://github.com/Napari/napari/issues.
  warn(message=warn_message)
Traceback (most recent call last):
  File "/Users/emoebel/miniconda3/envs/tradefi/bin/napari", line 10, in <module>
    sys.exit(main())
  File "/Users/emoebel/miniconda3/envs/tradefi/lib/python3.7/site-packages/napari/__main__.py", line 431, in main
    _run()
  File "/Users/emoebel/miniconda3/envs/tradefi/lib/python3.7/site-packages/napari/__main__.py", line 230, in _run
    from napari import run, view_path
ImportError: cannot import name 'run' from 'napari' (/Users/emoebel/miniconda3/envs/tradefi/lib/python3.7/site-packages/napari/__init__.py)
```

Note: in Ipython, the commant `import napari` works

## To Reproduce

1. `$ conda create --name tradefi python=3.7`
2. `$ source activate tradefi`
3. `$ conda install -c conda-forge napari`
4. `$ napari`

## Expected behavior

Should open Napari GUI.

## Environment

I'm using macOS Sierra 10.12.6

**Comment by tlambert03** [comment]
we need to figure out why you ended up with Qt 5.9.6 (and not ≥5.12, the min requirements)

I don't have access to a Sierra installation, so I can't test it locally, but it does look [Qt 5.12 supports macos 10.12](https://doc.qt.io/qt-5.12/supported-platforms.html).

when I run your reproduce commands and then run `conda list` I see:

```
...
pyqt                      5.12.3           py37hf985489_8    conda-forge
pyqt-impl                 5.12.3           py37hab5ec1f_8    conda-forge
pyqt5-sip                 4.19.18          py37h070e122_8    conda-forge
pyqtchart                 5.12             py37hab5ec1f_8    conda-forge
pyqtwebengine             5.12.1           py37hab5ec1f_8    conda-forge
pyrsistent                0.18.0           py37h271585c_0    conda-forge
pysocks                   1.7.1            py37hf985489_4    conda-forge
python                    3.7.12          haf480d7_100_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.7                     2_cp37m    conda-forge
pytz                      2021.3             pyhd8ed1ab_0    conda-forge
pywavelets                1.2.0            py37h032687b_1    conda-forge
pyyaml                    6.0              py37h271585c_3    conda-forge
pyzmq                     22.3.0           py37h8f778e5_1    conda-forge
qt                        5.12.9               h126340a_4    conda-forge
qtconsole                 5.2.2              pyhd8ed1ab_1    conda-forge
qtconsole-base            5.2.2              pyhd8ed1ab_1    conda-forge
qtpy                      2.0.0              pyhd8ed1ab_0    conda-forge
...
```

and napari runs fine.

Are you certain that you didn't install something else into that environment before installing napari (like jupyter or something that may have pulled in Qt 5.9)/.

Just to rule out that some intermediate dependency on conda is pinning you to Qt 5.9, please try the pip install, described [here](https://napari.org/#installation).

```
conda create -n tradefi -c conda-forge python=3.7
conda activate tradefi
pip install "napari[all]"
```

**Comment by emoebel** [comment]
Ok I just solved the issue. For some reason, the default PyQt version conda installs is 5.9.2
So I forced the installation of a more recent version: `conda install -c conda-forge pyqt==5.12.3`

And now it works as expected. Thanks for pointing me in the right direction!

**Comment by tlambert03** [comment]
> For some reason, the default PyQt version conda installs is 5.9.2

This is true for the default ["anaconda" channel](https://anaconda.org/anaconda/pyqt), but it's not the case for the [conda-forge channel](https://anaconda.org/conda-forge/pyqt), which ships 5.12.

This is why asked if you happened to install something prior to running `conda install -c conda-forge napari` (since, if you didn't specify conda-forge there, it's possible that you would end up with 5.9 depending on your config).

I would strongly recommend adding conda-forge to your conda config, and setting the channel priority as suggested on the [conda-forge homepage](https://conda-forge.org/), this way conda-forge will take priority over the default anaconda channel:

```
conda config --add channels conda-forge
conda config --set channel_priority strict
```
