### ISSUE TITLE
napari instances share layer mode

### ISSUE THREAD

**Issue by jwindhager** [napari/napari#3917]
## To Reproduce

1. Run the MWE below
2. Change the layer mode in first viewer (e.g. to "Add rectangles")
3. The layer mode of both napari instances changes (see screencast)
4. Changing the layer mode in the second viewer doesn't affect the first viewer

Minimum working example (MWE):

```python
#!/usr/bin/env python
import napari

from qtpy.QtWidgets import QApplication

if __name__ == "__main__":
    app = QApplication([])
    viewer1 = napari.Viewer()
    shapes1 = viewer1.add_shapes()
    viewer2 = napari.Viewer()
    shapes2 = viewer2.add_shapes()
    app.exec()
```

https://user-images.githubusercontent.com/7105759/148750090-6316b1b9-1dcc-4825-a4fd-ce4ad688ee86.mp4

## Expected behavior

The layer mode should change in the active napari window only

## Environment

Ubuntu 20.04.3 LTS

Fresh conda environment with Python 3.9.7 and napari 0.4.12

## Additional context

If only the first viewer has a Shapes layer, changing the mode of that layer will crash the application:
```
WARNING: Traceback (most recent call last):
  File "/home/jonas/miniconda3/envs/napari/lib/python3.9/site-packages/napari/utils/action_manager.py", line 53, in <lambda>
    self._command_with_context = lambda: call_with_context(
  File "/home/jonas/miniconda3/envs/napari/lib/python3.9/site-packages/napari/utils/action_manager.py", line 42, in call_with_context
    return function(**ctx)
  File "/home/jonas/miniconda3/envs/napari/lib/python3.9/site-packages/napari/layers/shapes/_shapes_key_bindings.py", line 90, in activate_direct_mode
    layer.mode = Mode.DIRECT
AttributeError: 'NoneType' object has no attribute 'mode'
```

**Comment by jwindhager** [comment]
Could this be caused by the new `current_viewer` global?

I see that this is used in https://github.com/napari/napari/blob/main/napari/utils/_injection.py

If that's the case, this would effectively mean that at the moment no two napari instances can run at the same time.

EDIT: Tried replacing `current_viewer` with [this _get_reader() function](https://github.com/BodenmillerGroup/napari-imc/blob/ce2ff998b33b49f19a786585cc2cb8e59db74c24/napari_imc/_reader.py#L35-L43), didn't help.

**Comment by jwindhager** [comment]
Probably related to/a duplicate of https://github.com/napari/napari/issues/2897

**Comment by tlambert03** [comment]
Hey @jwindhager, I'm not seeing this on main... 
#2987 was fixed in https://github.com/napari/napari/pull/3692
can you verify that you're on main?

**Comment by jwindhager** [comment]
Apologies! Thought I had tested this on the latest main, too, not realizing I was on another branch... My bad, closing

**Comment by tlambert03** [comment]
No worries thanks for checking
