### ISSUE TITLE
Catch when user provides non-RGB data but claims they do

### ISSUE THREAD

**Issue by stefanv** [napari/napari#3923]
This is more of an improvement than a bug.

## 🐛 Bug

When the user provides `rgb=True` to the viewer, there are some simple checks that can be done to confirm that the data conforms.  Instead, Napari gives cryptic error messages:

```
ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)
```

## To Reproduce

```python
import napari
import numpy as np

image = np.random.random((1024, 1024))
viewer = napari.view_image(image, rgb=True)
```

## Expected behavior

Error message: "`rgb` was set to True, but data does not have suitable dimensions"

**Comment by DragaDoncila** [comment]
Completely agree we should add some basic checks for RGB data and provide a more reasonable error message. In the interest of helping with our bug triage process, I've removed the `bug` label and added the `feature` and `good first issue` labels so other contributors know it's up for grabs!

@stefanv please ping me if you think that's unreasonable or there's another reason you'd like to keep the `bug` label! 🐞

**Comment by stefanv** [comment]
Thank you @lucyleeow for the patch and @Czaki for reviewing!
