### ISSUE TITLE
missing doc items (may be copy-docs problem)

### ISSUE THREAD

**Issue by nclack** [napari/napari#3927]
## 🐛 Bug

I was looking at napari.org after seeing #3916 get merged (a big update to plugin docs), and it looks like the toc is missing items. This seems to have something to do with the copy-docs script.

In particular, 
* it looks like files that are not in the toc are missing
* some items in the toc go missing
* the order of the items in the toc seems to change from the authored order

@tlambert03 please feel free to add detail

**Comment by sofroniewn** [comment]
Looks like some links are broken too https://github.com/napari/napari/pull/3916#issuecomment-1011897037 - cc @guiwitz (and thanks for quick report!)

**Comment by guiwitz** [comment]
Sorry, I should have checked whether an issue had already been opened. On a more general point: the official plugin docs are now no more in sync with the latest napari release which is still incompatible with npe2. Is a there a plan to release soon a new version of napari? If not, it should probably be (temporarily) mentioned that one needs to install napari from main (but I haven't read the docs in detail so I might have missed it).

**Comment by sofroniewn** [comment]
> Is a there a plan to release soon a new version of napari?

Yes, I think we can actually start the release process within next 24hrs and then release early next week. So things will probably be out of sync over weekend, but hopefully not too much longer. We could also add that note too in the mean time

**Comment by melissawm** [comment]
Got it - some docs are not being copied over because of [how the copy-docs.py file treats duplicate files](https://github.com/napari/napari/blob/bf74cbc1266d6e04045f084c4c19a0991f7e362b/docs/copy-docs.py#L70). I've submitted a fix for the plugin docs in #3929, including fixing the ToC and internal links. Please review :)

**Comment by kne42** [comment]
For clarity, are there other files missing from the ToC besides `find_and_install_plugin` and `npe1`?

I've double checked and they don't start with the includes directive, I think it's a different reason it's not working.

**Comment by melissawm** [comment]
Actually `npe1` and `find_and_install_plugin` are there, we are still missing the Manifest Reference and the Contributions Reference. This is what is added in #3929
