### ISSUE TITLE
Broken link and missing/blank page in Plugin section

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari/napari#3940]
## 📚 Documentation

I'm not sure if this is the proper place to report this but:
1. The It's your first plugin tutorial has a broken image link in Section 4. 
https://napari.org/plugins/stable/first_plugin.html#install-your-plugin-and-try-it-out
It's unfortunate, because the text doesn't make 100% clear what the user should expect to happen, so without the image...
2. The root Plugins page at the top has a list of what plugins can do, which includes a strange bullet point (nr. 3):
```
Providing [sample data][contributions-sample_data]

```
Should those be links or some sort of formatting?
3. The root Plugins page has a link that leads to a blank page in Section `How to build plugins`:
https://napari.org/plugins/stable/index.html#how-to-build-plugins
Specifically it's the 2nd line `Contribution reference` which leads to: https://napari.org/plugins/stable/contributions.html
This page for me is blank.

Also, the top-most bullet point on the page `Best practices` perhaps should allude to being for developers: `Best practices for developing plugins` or `Best practices for plugin developers` or some such. After all, this is napari.org and not GitHub so probably a good portion of visitors may be just interested in plugins from the user side. In fact, maybe the `Finding and installing ...` bullet should be the first one? The rest all relate to plugin development.

4. the Contribution Guides page: https://napari.org/plugins/stable/guides.html has an odd set of 3 horizontal lines at the top that other pages don't?

**Comment by tlambert03** [comment]
Hi @psobolewskiPhD, we've got a lot of problems with our docs-publishing pipeline at the moment.  Things work fine locally, and then fail to publish correctly.  We're aware of them, and working on them (see #3930 for discussion).  In the meantime, you might consider just using the "proof of principle" docs I posted in that discussion:

https://napari-docs-example.github.io/plugins/index.html

**Comment by psobolewskiPhD** [comment]
Ok, sorry for the dupe/nuisance. 
And thanks a ton for that link, it helps **a ton**.
❤️
