### ISSUE TITLE
10th layer bug

### ISSUE THREAD

**Issue by xcasas** [napari/napari#3952]
## 🐛 Bug

If I add more than 10 layers, then I can still keep seeing the new ones on the menu, but I cannot select them and they will all show as layer 10.

## To Reproduce

1. v = napari.view_image(image1)
2. v.add_image(image2)
 Until layer 10, or a for loop with the same image would work too, I guess.

## Expected behavior

Maybe if there is a limit at 10 one shouldn't be allowed to add new images anymore.

## Environment
```
napari: 0.4.7
Platform: Windows-10-10.0.19043-SP0
Python: 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:19:05) [MSC v.1916 64 bit (AMD64)]
Qt: 5.15.2
PyQt5: 5.15.6
NumPy: 1.19.5
SciPy: 1.7.3
Dask: 2021.12.0
VisPy: 0.9.4

OpenGL:
- GL version: 4.6.0 NVIDIA 496.13
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1200, scale 1.0

Plugins:
- console: 0.0.4
- svg: 0.1.5
```

**Comment by psobolewskiPhD** [comment]
`napari: 0.4.7`
Your napari is quite old, current version is 0.4.12 with 0.4.13 nearing release.
I can't reproduce this problem on 0.4.12, so updating napari should solve the problem.

**Comment by xcasas** [comment]
Thanks @psobolewskiPhD I confirm that updating napari solved the issue, sorry!
