### ISSUE TITLE
Enable shapes layer (right click) > convert to labels

### ISSUE THREAD

**Issue by chili-chiu** [napari/napari#3976]
## 🚀 Feature

Enable shapes layer (right click) > convert to labels so that this function is accessible from GUI directly.

## Pitch

Currently it is accessible through API to generate labels layer from shapes layer through napari.layers.Shapes.to_labels, but the option to access from the shapes layer (right click) > convert to labels is grayed out. 
The additional input that might be required is the labels layer data shape. One possible implementation is after clicking on “convert to labels”, add a dialog box to select “match dimension to [available image layer]”, which might be the most common usage. 

## Alternatives

Continue to only support via API. Though it would be nice to have a tooltip when hovering on the grayed out option that shows the corresponding API. 

## Additional context
In general, the right click menu from different layers shows the same contents but grayed out with different parts. 
This could be confusing as the grayed out options may be due to:
(1) Non-applicable actions
(2) Not sufficient selection/condition (i.e. Link Layers is only available if more than one layer is selected)
Ideally (1) should be removed so that users do not have to guess if those actions could be activated at all.

**Comment by sofroniewn** [comment]
This would be great!

**Comment by tlambert03** [comment]
added in #3978
