### ISSUE TITLE
The close button on dock widgets is gone, only hide is there

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#3983]
## 🐛 Bug
Not sure if it was intentional (maybe a miscommunication) or an oversight, but the x at the top left of dock widgets is gone.  I think we should go back to having an x icon (close the dock widget and destroy the instance).  a hide (eye) icon (hide the dock widget but don't destroy it).  and the icon that pops it out of the dock

**Comment by psobolewskiPhD** [comment]
Curious: if the x—destroy—function was there, would it be possible to test changes to plugin widgets (installed in editable mode) by relaunching the plugin/widget?
I've been relaunching napari...

**Comment by tlambert03** [comment]
this is more complicated.  The issue here is that once python imports a module, it will not reimport it (even if you've made changes to it) without specific "reload" instructions (https://docs.python.org/3/library/importlib.html#importlib.reload)

so, the answer to your question is "kinda sorta, depending on exactly how you set it up".  I would encourage you to familiarize yourself with IPython's autoreload magic.  Which will generally detect whether a module has changed its code, and reload accordingly:
https://ipython.readthedocs.io/en/stable/config/extensions/autoreload.html?highlight=autoreload

In some cases, this can even prevent you from needing to close the widget and reopen... but that is _very_ case specific, depending on exactly what methods you're calling, and what changes you're looking to see.  So it's hard to give a general "yeah/no that will/won't work"

**Comment by tlambert03** [comment]
@ppwadhwa, could you have a look at this?
