### ISSUE TITLE
OSError: exception: access violation reading 0x000000000000001C

### ISSUE THREAD

**Issue by SebastienTs** [napari/napari#3986]
When loading image layers I occasionaly get this exception (a priori not image dependent since the same image "often" loads fine):

OSError: exception: access violation reading 0x000000000000001C
C:\Anaconda\envs\napari-env\lib\site-packages\vispy\gloo\gl\_gl2.py in glDrawArrays(mode=GL_TRIANGLES, first=0, count=6)
    413     except AttributeError:
    414         nativefunc = glDrawArrays._native = _get_gl_func("glDrawArrays", None, (ctypes.c_uint, ctypes.c_int, ctypes.c_int,))
--> 415     nativefunc(mode, first, count)
        nativefunc = 
        mode = GL_TRIANGLES
        first = 0
        count = 6
		
## Environment

napari: 0.4.12
Platform: Windows-10-10.0.19041-SP0
Python: 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)]
Qt: 5.12.9
PyQt5: 5.12.3
NumPy: 1.20.3
SciPy: 1.7.1
Dask: 2021.10.0
VisPy: 0.9.4

OpenGL:
- GL version: 4.6.0 NVIDIA 511.23
- MAX_TEXTURE_SIZE: 32768

Screens:
- screen 1: resolution 1364x768, scale 1.0

Plugins:
- console: 0.0.4
- scikit-image: 0.4.12
- svg: 0.1.5

**Comment by psobolewskiPhD** [comment]
Yikes! Did this one fall through the cracks or what!
Looks like an issue in vispy, probably related to GPU or drivers.
A lot has changed in 2 years on that front and the OP says it wasn't fully reproducible, so I'm going to close.
If this is still a thing, please make a new issue with `napari --info` and full traceback.
