### ISSUE TITLE
Run examples with PyTest

### ISSUE THREAD

**Issue by kne42** [napari/napari#40]
We should include running examples with `pytest`, not only to ensure that we are providing working examples, but for right now they’re reasonably effective as tests while we create actual unit tests...

**Comment by royerloic** [comment]
Definitely.
We need both unit tests and 'demos'.
Tests are machines (automated testing etc)... 
Demos are for humans...

**Comment by AhmetCanSolak** [comment]
I agree with @royerloic that we need both unit tests and examples/demos and as far as I understand you want to make people run examples with `pytest` too? Correct me if i misunderstood you.

**Comment by royerloic** [comment]
For now, we should focus on automated non-UI unit tests.
Later, once we converge on a UI, it will be worth adding
unit tests for the UI. But for now I think it is overkill given how
young this project is. UI testing is potentially very complex to
do well and woulkd consume a disproportionate amount of time
to implement. In any case it is too early.

Eventually, we could make use of the following tools,
some of which are pytest based:
https://wiki.python.org/moin/PyQt/GUI_Testing

**Comment by jni** [comment]
@royerloic sure, I totally agree. However we should make sure that each PR is properly tested. Perhaps the PR author can make a "script" (as in, a human-readable set of instructions) that exercises all the new functionality, so that reviewers can properly test the PR.

**Comment by royerloic** [comment]
With clearvolume we had lots of 'demos' and each demo had a description of what people should expect to see. Once the project matures and we have more contributors we can start thinking about automating that...

**Comment by sofroniewn** [comment]
With #176 we have added support for automatically running examples with pytest.

Complex UI testing has not been implemented yet, but could come in the future
