### ISSUE TITLE
Drop python 3.7?

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#4008]
## 🧰 Task
How does everyone feel about dropping python 3.7? 

We had previously discussed following [NEP29](https://numpy.org/neps/nep-0029-deprecation_policy.html) which:

>  recommends that all projects across the Scientific Python ecosystem adopt a common “time window-based” policy for support of Python and NumPy versions.

with a proposed support table of 

Date | Python | NumPy
-- | -- | --
Jul 26, 2021 | 3.7+ | 1.18+
Dec 22, 2021 | 3.7+ | 1.19+
Dec 26, 2021 | 3.8+ | 1.19+
Jun 21, 2022 | 3.8+ | 1.20+
Apr 14, 2023 | 3.9+ | 1.20+

with 3.8, we could get in on that sweet, sweet walrus operator, and `functools.cached_property`

**Comment by sofroniewn** [comment]
Looks like it is time! I'm +1.

Have there been any major regressions we have caught since our release last week that means we need a bug fix in the next couple of days? I don't think so - in which case I'm good with dropping and then having 0.4.14 being first 3.8+ release in March. If we want to do a bug fix release this week then we should do that first and then drop 3.7.

What do @napari/core-devs think?

**Comment by tlambert03** [comment]
I like a bug fix first and soon, then drop 3.7 on the following one

**Comment by tlambert03** [comment]
> Have there been any major regressions we have caught since our release last week that means we need a bug fix in the next couple of days?

I think #3988 is a somewhat big bug fix that should be released soon

**Comment by sofroniewn** [comment]
> I think #3988 is a somewhat big bug fix that should be released soon

Sounds good. I have started a [zulip topic](https://napari.zulipchat.com/#narrow/stream/215289-release/topic/0.2E4.2E14/near/269312045) to discuss `0.4.14` more

**Comment by kevinyamauchi** [comment]
I am +1 on dropping python 3.7!

**Comment by Czaki** [comment]
There is one big question. If released with drop python 3.7 will be 0.4.15 or 0.5.0. If 0.5.0 then part of deprecations should be postponed, as there are still open issues, for example, #3970 and  #3781 connected with the deprecation of `qt_viewer`. 

But I support a drop of python 3.7.

**Comment by liu-ziyang** [comment]
that is a great point, we dropped 3.6 with the 0.4 releases, it would make sense to increase the minor version for this breaking change and not backward compatible. I second the 0.5.0 version. And if this makes anything easier, I vote for delaying other deprecations like #3970 or #3781 to 0.5.1

**Comment by brisvag** [comment]
> with 3.8, we could get in on that sweet, sweet walrus operator, and `functools.cached_property`

Yes, walrus!

I agree on dropping 3.7. It seems reasonable to do that for 0.5!

**Comment by sofroniewn** [comment]
If we move to releasing ~2 months on the second tuesday do we then see `0.5` happening in March, May, or July? Should we try and coordinate other big breaking changes, or just go ahead in March with `0.5`. We can always turn around to do `0.6` as soon as we want after :-)

**Comment by tlambert03** [comment]
I am fine both with releasing 0.5 just as a py3.7 drop, with 0.5.1 bringing all the other deprecations (as @potating-potato suggested), or just bringing all of our breaking changes together in 0.5.0.  whatever the @napari/core-devs consensus is

**Comment by jni** [comment]
I think we could just drop 3.7 on 0.4.15? I don't see this as a big reason to bump to 0.5. Then this doesn't have to affect any of the other deprecations.
