### ISSUE TITLE
Review the nightly builds for the bundle app

### ISSUE THREAD

**Issue by goanpeca** [napari/napari#4010]
## 🧰 Task

The bundle app work in  https://github.com/napari/napari/pull/3555/files#diff-afc0068c04c2f82b5ba745d52a251795a27940607f0257cb7861a9d687ab8909R98 is merged is currently building for both PyQt and PySide.

This issue is a reminder to evaluate the need for those in terms of resources and debugging.

**Comment by jaimergp** [comment]
Given that we released them for 0.4.15 and you can see them in the [Nightly assets](https://github.com/napari/napari/releases/tag/latest), and that the [CI jobs have been successful reliably](https://github.com/napari/napari/actions/workflows/make_bundle_conda.yml?query=event%3Aschedule), we can close this one @potating-potato.
