### ISSUE TITLE
Ensure example data works in bundled app

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#4011]
## 🧰 Task
See discussion in https://github.com/napari/napari/issues/3968#issuecomment-1019482358 for context - we should add pooch to our bundle deps - cc @jaimergp @goanpeca

**Comment by jni** [comment]
Rather than depending on pooch directly, we should depend on `scikit-image[data]`, since we are using the scikit-image API. I don't anticipate that we will use a different data provider in the future, but we could do so conceivably, so `scikit-image[data]` is "syntactically" the correct dependency.

**Comment by sofroniewn** [comment]
Sounds good - I have changed title of issue to be less proscriptive on how issues gets fixed
