### ISSUE TITLE
Event on point selection change

### ISSUE THREAD

**Issue by alisterburt** [napari/napari#4023]
## 🚀 Feature
An event we could connect to when the point selection changes

## Motivation
Making point selection changes triggers for custom behaviour in plugins

## Alternatives
There is currently a highlight event we can use but it is less discoverable/intuitive

## Additional context
- This came up when working on point manipulators in napari-threedee
- We might be able to use our existing [`Selectable` model](https://github.com/napari/napari/blob/5f96d5d814aad697c367bdadbb1a57750e2114ad/napari/utils/events/containers/_selection.py)
cc @kevinyamauchi

**Comment by psobolewskiPhD** [comment]
#5691 implemented psygnal Selection for points selection:
https://psygnal.readthedocs.io/en/latest/API/containers/#psygnal.containers.Selection
As a result, the requested event is already implemented:
https://psygnal.readthedocs.io/en/latest/API/containers/#psygnal.containers._selection.SelectionEvents
I tested and the following can be used
`viewer.layers['Points'].selected_data.events.items_changed.connect()`

Can we close this?
