### ISSUE TITLE
Empty name on choose reader npe2 dialog

### ISSUE THREAD

**Issue by JoOkuma** [napari/napari#4036]
## 🐛 Bug

Alternative reader plugin dialog shows no text when `display_name` is not present on the npe2 manifest. When `display_name` is filled that string is shown. 

![image](https://user-images.githubusercontent.com/21022743/152026910-28df821c-273f-43dc-9a6d-f3395e3b86ad.png)

This might be the expected behavior, but `display_name` is optional.

## To Reproduce

1. Create an alternative reader plugin.
2. Drag and drop to napari a file with an extension that has multiple readers.

## Expected behavior

To not be empty, it could show the plugin name when the `display_name` is not provided.

## Environment
```
napari: 0.4.14rc1.dev37+g691034f6
Platform: Linux-5.11.0-44-generic-x86_64-with-glibc2.10
System: Ubuntu 20.04.3 LTS
Python: 3.8.8 (default, Apr 13 2021, 19:58:26) [GCC 7.3.0]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.20.3
SciPy: 1.7.3
Dask: 2021.11.2
VisPy: 0.9.4

OpenGL:
- GL version: 4.6.0 NVIDIA 460.73.01
- MAX_TEXTURE_SIZE: 32768

Screens:
- screen 1: resolution 3440x1440, scale 1.0

Plugins:
- animation: 0.0.2
- console: 0.0.4
- scikit-image: 0.4.14rc1.dev37+g691034f6
- svg: 0.1.4
```

cc @nclack

**Comment by tlambert03** [comment]
fixed in https://github.com/napari/npe2/pull/92
