### ISSUE TITLE
points layer ignores symbol 

### ISSUE THREAD

**Issue by maweigert** [napari/napari#4042]
## 🐛 Bug

Constructing a points layer with a non-disc marker symbol currently results in the default (disc) marker being used instead.

## To Reproduce

```python

import numpy as np
import napari

data = np.array([[0,0],[4,4],[8,8]])

napari.view_points(data, symbol='ring')

```

<img width="260" alt="img" src="https://user-images.githubusercontent.com/11042162/152258845-53a6320f-9301-4418-ac0b-012bf4f495d6.png">

## Environment

Happens in napari `0.4.13` on both MacOS and Linux. 

Git blame points to commit b5405402a where the following supposedly important line got removed:

https://github.com/napari/napari/blob/9af23fb0ddd8b9804edc84d534095a00b697c41c/napari/_vispy/layers/points.py#L62

So I think it might be an easy fix e.g. for @brisvag,  @alisterburt, et al

**Comment by alisterburt** [comment]
thanks for the detailed report @maweigert !

**Comment by maweigert** [comment]
Thanks @alisterburt for the fast reponse and @brisvag for the fast PR - should be fixed with it!
