### ISSUE TITLE
vispy 0.6 release

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#407]
## 🐛 Bug

We currently have a bug with the new `0.6.0` vispy release - see errors in `add_image.py`

![image](https://user-images.githubusercontent.com/6531703/61162374-e5abc000-a4cd-11e9-90ad-ce1b111d3c1c.png)

and `add_labels.py`

![image](https://user-images.githubusercontent.com/6531703/61162400-ff4d0780-a4cd-11e9-95c7-65ab735d5206.png)

The first bug is already fixed in #406 by removing our vispy backport. we need to still fix the second one

**Comment by sofroniewn** [comment]
The above colormap issue can be fixed by reverting this function back to its `0.5.6` version in the `vispy.color.colormaps.py` file

```python
def _glsl_step(controls=None):
    assert (controls[0], controls[-1]) == (0., 1.)
    ncolors = len(controls) - 1
    assert ncolors >= 2
    s = ""
    for i in range(ncolors-1):
        if i == 0:
            ifs = 'if (t < %.6f)' % (controls[i+1])
        elif i == (ncolors-2):
            ifs = 'else'
        else:
            ifs = 'else if (t < %.6f)' % (controls[i+1])
        s += """%s {\n    return $color_%d;\n} """ % (ifs, i)
    return """vec4 colormap(float t) {\n%s\n}""" % s
```
i'll look into a better fix, though it would be easy to back port this if needed @jni @kne42 @perlman

**Comment by sofroniewn** [comment]
Something to try for @perlman is reversing the colors list inside the `_glsl_step` function
```python
def _glsl_step(controls=None, colors=None, texture_map_data=None):
    assert (controls[0], controls[-1]) == (0., 1.)
    ncolors = len(controls) - 1
    assert ncolors >= 2
    assert (texture_map_data is not None)
    # Reverse color
    # print(colors[::-1])
    colors = colors[::-1]
```
I'll check it out when I get the chance, for now I've merged our bug fix #426

**Comment by perlman** [comment]
I think this is a bug in vispy. The colors in the generated LUT appear to be in inverse order from how they are specified.

I can add
>  colors = colors[::-1]

to _glsl_step (https://github.com/vispy/vispy/blob/master/vispy/color/colormap.py#L168) to bring back the prior behavior.

(To be clear, this isn't a proper fix. I think there is a logic flaw with how it's assigning the LUT bucket. e.g., one can invert LUT_tex_idx as well.)

**Comment by perlman** [comment]
Here's the problem:
https://github.com/vispy/vispy/blob/v0.6.0/vispy/color/colormap.py#L186 needs to either be < or <= rather than >=.

**Comment by perlman** [comment]
This is the real fix, I think:
https://github.com/vispy/vispy/pull/1668

(Edit: The whole function should probably be redone, but this is the minimal viable fix. 1 character.)

**Comment by jni** [comment]
@sofroniewn do you mind reverting `#426` (thanks to git squash, just a `git revert` away), and replacing it by @perlman's `color = color[::-1]`?

**Comment by sofroniewn** [comment]
i made a followup PR with the `<` and `>` switch. Closing this now, hopefully to be removed with the next vispy release.
