### ISSUE TITLE
improvements to organization

### ISSUE THREAD

**Issue by neuromusic** [napari/napari#4077]
## 📚 Documentation
in reviewing #4047, @sofroniewn noted suggested improvements to docs organization, taking advantage of the new top nav...

> - [x] The napari logo in the top left doesn't load for me
> - [x] I'd move `napari workshop` out of `napari tutorials` and under `usage` (so not the top nav, but also not at the third level)
> - [x] `Single cell tracking with napari` and `Annotating segmentation with text and bounding boxes` appear both in the left nav at the level of `napari tutorials` and but are also under `Tracking` and `Segmentation`. I guess these will be triple nested when that works
> - [x] Can we put `Annotating videos with napari` under `Annotation`
> - [x] Can we put `Using Dask and napari to process & view large datasets` under `Processing`
> - [x] We will then end up with `napari tutorials` -> `Segmentation`, `Tracking`, `Annotation`, and `Processing`. Future tutorials can add to those sections, or create new sections.
> - [x] In community can we put `Handling Code of Conduct Reports` under `Code of Conduct` somehow, I don't think it needs to also be it's own top line item, but can link out

**Comment by melissawm** [comment]
Folks I think this is all covered, let me know if there are any pending items. Thanks!
