### ISSUE TITLE
Different set of shape layers for each image in a stack

### ISSUE THREAD

**Issue by vonclites** [napari/napari#4083]
## 🧰 Task
I am trying to overlay a set of bounding box annotations onto an image. What I would like to do is create a separate Shape Layer for each annotation. Having one layer per annotation allows me to turn on/off the visibility of each annotation as desired. I have successfully done this for a single image. The name of each Shape Layer conveys the predicted class, confidence score, and IOU with groundtruth. My layers look like this:

![napari_layers](https://user-images.githubusercontent.com/4926264/153662779-72300c50-e912-4b60-b205-1e79ed52e202.png)

My question is this: 
Is it possible to do this for a stack of images, where each image has a variable length set of predictions? It seems as I go from one image to the next, I would need to remove the old layers and add the new set. How would I accomplish this with napari?

Thanks!

**Comment by tlambert03** [comment]
> It seems as I go from one image to the next, I would need to remove the old layers and add the new set.

just to clarify, is that because the layerlist would get completely unruly otherwise?  or because you would have confusing overlaying annotations?

I'll mention that layer "groups" might help here.  They have long been in the works and are getting a little closer again (#4018).

> How would I accomplish this with napari?

In the meantime, if you want to just clear the layerlist before moving on to the next image, you can always use `viewer.layers.clear()` before populating again with your next image and set of shapes layers ... but I imagine that I'm probably missing crux of the question?

**Comment by vonclites** [comment]
> just to clarify, is that because the layerlist would get completely unruly otherwise? or because you would have confusing overlaying annotations?

The latter. I would have confusing overlaying annotations. Even in the single image case, there are potentially confusing overlaying annotations, hence my use of separate layers so that I can show/hide certain annotations.

> I'll mention that layer "groups" might help here. They have long been in the works and are getting a little closer again (#4018).

Cool, I'll keep an eye on that!

> In the meantime, if you want to just clear the layerlist before moving on to the next image, you can always use `viewer.layers.clear()` before populating again with your next image and set of shapes layers... but I imagine that I'm probably missing crux of the question?

That sounds like that could work. I think you understand the question. I just lack the knowledge to execute on your suggestion. It sounds like I need to create some kind of function that sets the shape layers based on the currently viewed frame, and something that listens for the change of frame? I looked at https://napari.org/guides/stable/events_reference.html but I'm not sure what event(s) I'm looking for. I've studied https://napari.org/tutorials/applications/annotate_points.html and https://napari.org/tutorials/segmentation/annotate_segmentation.html and am reading through the API, but I'm having a hard time finding the information I need.

Thanks

**Comment by tlambert03** [comment]
> It sounds like I need to create some kind of function that sets the shape layers based on the currently viewed frame, and something that listens for the change of frame? I looked ... am reading through the API, but I'm having a hard time finding the information I need.

totally get it! there's a lot of stuff to dig through.  Glad you opened an issue (sidenote: for general questions like this you might have better luck/visibility either at https://forum.image.sc/tag/napari, or in the napari chat at https://napari.zulipchat.com/)

Do I have this correct?  You've got something like a 3D stack of images, perhaps a timelapse or something, and each frame/plane in the image stack needs a different group of (multiple) shapes layers.  When you move to the next frame/plane, you'd like all the shapes layers to clear, and ideally "return" when you go back to a plane you've already annotated?

If so, I think one option might be to just make all of your shapes layers _also_ be n-dimensional (matching the dims of your image), with `viewer.add_shapes(ndim=3)` for example.  then you don't have to clear the shapes:

https://user-images.githubusercontent.com/1609449/153672917-e3d20d04-edf8-42b3-9307-247bb4d10ab5.mov

is that getting closer?

**Comment by vonclites** [comment]
> totally get it! there's a lot of stuff to dig through. Glad you opened an issue (sidenote: for general questions like this you might have better luck/visibility either at https://forum.image.sc/tag/napari, or in the napari chat at https://napari.zulipchat.com/)

Ah, great to know. Thanks.

> If so, I think one option might be to just make all of your shapes layers _also_ be n-dimensional (matching the dims of your image), with `viewer.add_shapes(ndim=3)` for example. then you don't have to clear the shapes
> is that getting closer?

Yeah I think that's getting closer. I just haven't had success using ndim. For example, for the layer which will have my ground-truth annotations, I do this:
`gt_layer = viewer.add_shapes(
        data=gt_bbox,
        face_color='transparent',
        edge_color='cyan',
        text=gt_text,
        name='gt',
        ndim=3
    )`

where `gt_bbox.shape == (56, 4, 2)`
I have a stack of 56 images.

I get the error `"ValueError: Shape dimensions must be equal to ndim"`

In order to do what you're describing, what should the shape of the given data be?

Thanks,
Dom

**Comment by vonclites** [comment]
> totally get it! there's a lot of stuff to dig through. Glad you opened an issue (sidenote: for general questions like this you might have better luck/visibility either at https://forum.image.sc/tag/napari, or in the napari chat at https://napari.zulipchat.com/)

Great to know, thanks!

> Do I have this correct? You've got something like a 3D stack of images, perhaps a timelapse or something, and each frame/plane in the image stack needs a different group of (multiple) shapes layers. When you move to the next frame/plane, you'd like all the shapes layers to clear, and ideally "return" when you go back to a plane you've already annotated?

Exactly.

> If so, I think one option might be to just make all of your shapes layers _also_ be n-dimensional (matching the dims of your image), with `viewer.add_shapes(ndim=3)` for example. then you don't have to clear the shapes
> is that getting closer?

Yes! I wasn't understanding how to use ndim but I think I get it now. How difficult would it be to dynamically change the name of the layer so that it conveys the class label | confidence score | IOU as my the original example image?

Thanks again!

**Comment by jni** [comment]
> How difficult would it be to dynamically change the name of the layer

This is easy, `layer.name = new_name`. :blush:

**Comment by vonclites** [comment]
> This is easy, `layer.name = new_name`. 😊

That part I was able to figure out, but what event should I be listening for? How do I get that code to trigger when I change frame?

**Comment by tlambert03** [comment]
if you want to connect a callback to one of the dimensions sliders changing:

```python
@viewer.dims.events.current_step.connect
def _on_change(event):
    index = event.value
    # this will be a tuple of length ndim, with the current index of each dim
    # for example, for viewer with 3 dims, the index[0] would be your current z position
```

not sure exactly how you're calculating the IOU from the plane, but if you need any other events or data there, let us know

**Comment by vonclites** [comment]
Perfect, thanks so much! That's probably all I need. I'll give it a shot!

**Comment by vonclites** [comment]
That worked like a dream! Thanks so much @tlambert03 and @jni

Napari is fantastic!

**Comment by tlambert03** [comment]
glad to hear it!
