### ISSUE TITLE
License info for limited release of bundled app

### ISSUE THREAD

**Issue by junxini** [napari/napari#4095]
### Context
The napari bundled app will have a limited release in March that will allow users to install napari viewer along with the majority of available plugins (final number of plugins during initial release TBD). As part of the initial release, license information will need to be made available to users.

### Goal
Surface licensing information in a location accessible to users (e.g., napari.org)
- [X] generate output of script
- [x] store license list in docs (location to live under "Community" at the same level as "Roadmaps" and "Releases")
- [x] surface license to users in napari install process (e.g., via link)

**Comment by neuromusic** [comment]
@jaimergp can you link to the relevant script for generating the licensing info for the bundled packages?

**Comment by jaimergp** [comment]
It's [here](https://github.com/napari/napari/pull/3555/files#diff-bfda80c9ae6bf68b16e9eea38d15406d2a71be66e35df6981dad8e0d7f29b0e7R243-R267).

It relies on some behaviour we [implemented](https://github.com/jaimergp/constructor/commit/574e9941ed1b02225673f99528ac7909525fc167) on our `constructor` fork.

**Comment by sofroniewn** [comment]
This is great, thanks @jaimergp can you copy either directly in here, or as a link the output of that script (i.e. the concatenated licenses) or make a PR to the docs (probably somewhere under the community tab) with the license so we can see what it looks like. Thanks!!!

**Comment by jaimergp** [comment]
The full text is cat'd in a separate step in the conda bundle CI. I am on mobile now so I can't link to the exact line, but you can see it in the PR!

**Comment by sofroniewn** [comment]
Ok thanks! I couldn't find it in PR - but no rush, i'll check it out when you can get to it

**Comment by jaimergp** [comment]
@sofroniewn check [here](https://github.com/napari/napari/runs/5289596178?check_suite_focus=true#step:13:54)

**Comment by sofroniewn** [comment]
Great, i see them now - thanks!!

**Comment by neuromusic** [comment]
re: license location, I think "Licensing" should probably live under "Community" at the same level as "Roadmaps" and "Releases".

can you submit a PR @jaimergp adding the file as an RST or markdown file to `docs/` and add the relevant link to the table of contents? https://github.com/napari/napari/blob/main/docs/_toc.yml

**Comment by sofroniewn** [comment]
> re: license location, I think "Licensing" should probably live under "Community" at the same level as "Roadmaps" and "Releases".

+1

**Comment by jaimergp** [comment]
@neuromusic 

I can submit a PR but I think we need to discuss the contents. I am assuming we don't need to disclose the open-source licenses (MIT, BSD, GPL), since these only require the license to be _present_ in the installation (and they are). Some other licenses do behave more like a EULA and require (in a way) that user _accepts_ it.

I'll start by adding the necessary cross-job automation to create that document. Then we can refine what gets included.

**Comment by sofroniewn** [comment]
Ok sounds good - i didn't know we had any of those more EULA agreements, but yeah - let's start with PR and then refine from there. I think at the beginning if in doubt include it, we can always remove things, but harder to remember to add things back in. Thanks for keeping this moving forward!!
