### ISSUE TITLE
`update_console` example is broken

### ISSUE THREAD

**Issue by ianhi** [napari/napari#4098]
## 🐛 Bug

The `update_console` example: https://github.com/napari/napari/blob/main/examples/update_console.py does not acutally filly the ipython console with variables.

Also discussed here: https://napari.zulipchat.com/#narrow/stream/212875-general/topic/ipython-variables-from-script

## To Reproduce

1. Run the example
2. try to use some of the locals in the napari ipython console

## Expected behavior
Locals are there

## Environment

```
napari: 0.4.14
Platform: Linux-5.15.15-76051515-generic-x86_64-with-glibc2.34
System: Pop!_OS 21.10
Python: 3.9.10 | packaged by conda-forge | (main, Jan 30 2022, 18:04:04) [GCC 9.4.0]
Qt: 5.12.9
PyQt5: 5.12.3
NumPy: 1.22.1
SciPy: 1.7.3
Dask: 2022.01.1
VisPy: 0.9.4

OpenGL:
- GL version: 4.6 (Compatibility Profile) Mesa 21.2.2
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1080, scale 1.0

Plugins:
- console: 0.0.4
- scikit-image: 0.4.14
- svg: 0.1.5
```
## Additional context

I believe that this is due to the lazy loading of the console. In particular here:

https://github.com/napari/napari/blob/bf8682ec9e1ba50e40f3d078a68360903ce58a06/napari/viewer.py#L78-L81

the check for `_console` will always return `None` here as the console hasn't been initialized. You can forcibly init the console by accessing the

`_qt_viewer.console` property, but that's not ideal because of the usage of a private variable. So i suggest changing the beahvior of `update_console` to:

1. `update_console` defaults to intiatlizing the console if one doesn't exist
2.  add a kwarg to brign the current behavior of not creating one

I think this is a sensible default because if you are updating the console then you probably want one to exist if it doesn't already.

**Comment by ianhi** [comment]
Oh man - also running that example generates two separate napari windows. I'm pretty sure that thats not right either?

**Comment by jni** [comment]
Rather than having a public `update_console()`, imho we should make efforts to ensure that the console is prepopulated with the right variables. How this could/should look like:

- console gets launched
- we traverse the stack until we find the highest level where the viewer is present (since the viewer can be present in many lower parts of the stack e.g. because it gets injected and handed to plugins)
- inject the locals at that level

**Comment by ianhi** [comment]
@jni that's definitely what I was expecting to happen when I first tried this so :+1: from me. Though it may also be nice to be able to specify exactly what you want
