### ISSUE TITLE
Your First Plugin guide needs more guidance around napari requirements

### ISSUE THREAD

**Issue by andy-sweet** [napari/napari#4099]
## 📚 Documentation

If you follow the [Your First Plugin](https://napari.org/plugins/stable/first_plugin.html) guide faithfully, running `napari` at the end will typically fail. That's because of the following steps.

1. Recommend creating a fresh virtual environment for your plugin (e.g. using conda).
2. Implement a plugin that depends on `napari` (specifically `napari.utils.notifications`). The dependency should not be `napari[all]` to follow [the best practice around depending on specific Qt backends](https://napari.org/plugins/stable/best_practices.html#don-t-include-pyside2-or-pyqt5-in-your-plugin-s-dependencies).
3. Calling `pip install -e .` then running `napari`.

We discussed a couple of solutions in the plugin working group. The one we preferred is to include a step like `pip install napari[all]` in the [Before you start](https://napari.org/plugins/stable/first_plugin.html#before-you-start) section to ensure that napari is installed and be run from that environment.

**Comment by psobolewskiPhD** [comment]
Related, something that came up during hackathon prep:
https://napari.zulipchat.com/#narrow/stream/309872-plugins/topic/.E2.9C.94.20can't.20seem.20to.20get.20plugin.20to.20show.20up/near/268130692
the image link in the "try it out section" is broken—at least for me.
https://napari.org/plugins/stable/first_plugin.html#install-your-plugin-and-try-it-out

Another thing that came up was the minimum `napari` version, which I believe is 0.4.13. Maybe should be mentioned along side the `npe2` requirement.

**Comment by andy-sweet** [comment]
Thanks @psobolewskiPhD  - looks like the missing image bug is being tracked over on the npe2 repo: https://github.com/napari/npe2/issues/98

As we started using git lfs for tracking image files, I'm guessing we need to push that image with git lfs tracking into `napari/docs/images`. I'll probably fix that it in a separate PR just because I haven't really used git lfs before.
