### ISSUE TITLE
Documentation refers to missing requirements.txt

### ISSUE THREAD

**Issue by jhnnsrs** [napari/napari#4104]
## 📚 Documentation

Hey everyone! Following up on my commitment yesterday on resolving that shapes issue, I am diving head first into my fork. And I thought I would track hurdles on the way for new contributors (from the learner's perspective). One thing quite early on my journey:

Doc -> Developer Resources -> Contributing guide -> Setting up a development installation:

Install the package in editable mode, along with all of the developer tools
```bash
pip install -r requirements.txt
```

Problem: There is no requirements.txt. Maybe it could be added or the documentation updated to specify which set of dev tools (conda) are required to construct a dev environment?

**Comment by tlambert03** [comment]
Sorry that got missed in the recent pr,  please use `pip install -e .[dev]` and we'll update the docs
