### ISSUE TITLE
bug in contrast slider popup when dtype is a signed integer

### ISSUE THREAD

**Issue by grlee77** [napari/napari#4112]
## 🐛 Bug

I noticed a few issues with the contrast limits popup widget:

1.) The "full range" button appears for signed integer dtype, but the button [only has any effect on unsigned integer inputs](https://github.com/napari/napari/blob/eb9ef90f5de9858523da5a02ab7044427911410c/napari/layers/intensity_mixin.py#L43-L51). Here is the slider I see for signed integer data:

![contrast_slider_signed_bug](https://user-images.githubusercontent.com/6528957/154597556-38549ee3-2639-4b0f-8f16-f971c61f84cb.png)

2.) The button sizes are also a bit too small and the text appears a bit truncated (also visible in image above). Do others also see this?

3.) I have a question about the desired behavior of the "reset" button. Currently it always resets based on the data range. However, if the user had provided `contrast_limits` as a kwarg when adding the layer, should it instead reset to those?

I can make a small PR to fix issues 1 and 2, but need some feedback regarding desired behavior for item 3.

## To Reproduce

1. add a signed integer layer via the console

```Python
import numpy as np
x = np.arange(256*256, dtype=int).reshape(256, 256)
viewer.add_layer(x)
```

2. right click on the contrast limits slider

## Expected behavior

No "full range" button should be shown and text on the buttons should be fully legible.

## Environment

 - Please copy and paste the information at napari info option in help menubar here:

 - Any other relevant information:

**Comment by tlambert03** [comment]
> 1)

👍 better signed int support would be great.  I'm not sure we should _hide_ the full range though?  just make it more appropriate?

> 2.) The button sizes are also a bit too small and the text appears a bit truncated (also visible in image above). Do others also see this?

what os? Generally speaking we've found it rather hard to maintain consistent styling across all OS,  specifically when it comes to text sizes.  Windows is usually the biggest offender here, but not the only.  Any attempts to fix there will probably need to be double checked on as many OS as possible.

> However, if the user had provided contrast_limits as a kwarg when adding the layer, should it instead reset to those?

I would say no?  This was one of the first "autoscale" buttons available.  something that a user could use even if (for example) they or a plugin loaded the image with not-so-great values for contrast_limits

**Comment by grlee77** [comment]
Okay, I will revisit these points later this afternoon.

> what os? Generally speaking we've found it rather hard to maintain consistent styling across all OS, specifically when it comes to text sizes.

Ubuntu 20.04, but I do have it set to "Large Text" under the "Universal Access" system setting, so that might be why? I am not familiar with how Qt deals with these things.

**Comment by tlambert03** [comment]
> Ubuntu 20.04, but I do have it set to "Large Text" under the "Universal Access" system setting, so that might be why?

yeah, that's probably it.  we've often had issues with Qt's handling of OS-specific display scaling.  macOS pretty much always looks great, but windows and linux are a pain.  It's very hard to fix on one OS in a way that doesn't mess up the other OS.  This is definitely something that would be great to get some true Qt expertise on somewhere.  (i.e. someone out there must have the "correct" answer for how we're supposed to handle display scaling across OS)
