### ISSUE TITLE
Figure out the best way to handle our git-lfs build going forward

### ISSUE THREAD

**Issue by jni** [napari/napari#4115]
## 🧰 Task

Our git-lfs setup is already [causing headaches](https://github.com/napari/napari/pull/4114) due to GitHub's bandwidth limitations on LFS. We need to consider sustainable options going forward.

1. Based on our burn rate, 10x the bandwidth should cover us easily and would cost $600/y, which is not that terrible. So we (ie CZI 😂 Thank you!!! 😂🙏) could just fork it out.
2. We could urgently add more dynamically generated screenshots and remove a large number of objects from LFS, which could decrease our burn rate, while at the same time ensuring our documentation is up to date.
3. The burn rate should be very small if we can correctly implement caching. The build-docs workflow has some breadcrumbs on how to implement that [here](https://github.com/napari/napari/blob/eb9ef90f5de9858523da5a02ab7044427911410c/.github/workflows/build_docs.yml#L17-L21). ie in theory it's already implemented but clearly it's not working correctly.
4. It looks like some non-docs builds are running into the lfs quotas, which should **never happen**. This I don't understand currently (it doesn't look like the checkout action has lfs enabled without adding the `with: lfs: true` parameter to the action), but it's definitely happening, see e.g. [this line](https://github.com/napari/napari/runs/5242457597?check_suite_focus=true#step:4:13) in a failed build.
5. We can drop LFS and go back to "GHIFS", ie having images served by GitHub links. @neuromusic has strongly opposed this approach because it's not officially supported by Github, though. It's a fair objection but the LFS approach presents its own headaches. (One could say that Github *already* doesn't *really* support LFS! 😂)
6. On that note, it also makes no sense that the same bandwidth with a git submodule stored in github would be completely fine. We could try contacting github to ask them whether they can update their LFS bandwidth policy to something more reasonable.

**Comment by jni** [comment]
> 

Oh wow, it looks like [`pip install git+https:`](https://github.com/napari/napari/blob/d323b18cd42fe4aa2f1ff11df65159e78435c2e3/.github/workflows/test_pull_requests.yml#L178) will actually download lfs files! 🤯 

I'm unclear why that would be the case, and whether it can be fixed, but most of all I'm unclear why we do that for ubuntu-latest rather than use the checkout action. @tlambert03 any comment on this?

**Comment by jni** [comment]
Ah, looks like it's to test `pytest --pyargs napari` while not having any napari in the local directory. We could/should fix this by putting our code in a `src/` directory, but in the meantime, perhaps we can come up with a more lfs-compatible solution? For example, checkout, install, then delete.

Come to think of it, maybe going to point 3 above, caching *is* working in the build-docs (which would explain why build-docs *didn't* fail), and all our bandwidth was consumed by this pip install line???

**Comment by jni** [comment]
Indeed, *no build-docs or build-and-deploy docs* actions have failed:

https://github.com/napari/napari/actions/workflows/build_docs.yml

So #4114 is not the right way forward, and we need to fix this ubuntu-latest action.

**Comment by tlambert03** [comment]
> > 
> 
> 
> 
> Oh wow, it looks like [`pip install git+https:`](https://github.com/napari/napari/blob/d323b18cd42fe4aa2f1ff11df65159e78435c2e3/.github/workflows/test_pull_requests.yml#L178) will actually download lfs files! 🤯 
> 
> 
> 
> I'm unclear why that would be the case, and whether it can be fixed, but most of all I'm unclear why we do that for ubuntu-latest rather than use the checkout action. @tlambert03 any comment on this?

That was just for the pip install test right?  It's fine to use the checkout action if it helps.  It was just another way to do it.  Should be identical (in terms of the test) to the checkout I think

_edit_: yes your comment about not having the napari dir in cwd is also a good one

**Comment by melissawm** [comment]
Thanks for looking at this - hope no other issues come up 🤞🏻

**Comment by jni** [comment]
Just an extra data point: currently, we've had ~93 docs and ~23 deploy builds. Even if *all* of them resulted in a checkout (~200-300MB), that only accounts for at most ~25GB of bandwidth. So we would still be an order of magnitude out from our actual usage. The bandwidth is leaking elsewhere...

**Comment by jni** [comment]
We have decided to move away from lfs because the bandwidth issue is in fact outside of our control. This issue is superseded by #4306.
