### ISSUE TITLE
IndexError: deque index out of range

### ISSUE THREAD

**Issue by Carreau** [napari/napari#4131]
## 🐛 Bug

Using  bucket on empty label layer raises IndexError

## To Reproduce

1. open napari
2. create empty label layer (don't edit it)
3. let label color to 0 (either click on -, or use picker and click anywhere in image)
4. Select bucket
5. click somewhere on image

Lead to this traceback:

https://gist.github.com/Carreau/283d6d3275b371bfaff58146f72cdae9

(napari still usable)

## Expected behavior

No exceptions.

## Environment

napari: 0.4.15.dev18+g6f639ca03.d20220215
Platform: macOS-10.16-x86_64-i386-64bit
System: MacOS 12.0.1
Python: 3.9.0 | packaged by conda-forge | (default, Nov 26 2020, 07:54:06) [Clang 11.0.0 ]
Qt: 5.15.2
PyQt5: 5.15.6
NumPy: 1.21.4
SciPy: 1.7.2
Dask: 2021.11.1
VisPy: 0.9.6

OpenGL:
- GL version: 2.1 Metal - 76.1
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1512x982, scale 2.0

## Additional context

I think this is a corner case of having no undo history.

**Comment by psobolewskiPhD** [comment]
I can't reproduce this on 0.4.18 or main
I think it was fixed as part of https://github.com/napari/napari/pull/4702
