### ISSUE TITLE
Nonsensical "bicubic" interpolation for labels layer

### ISSUE THREAD

**Issue by Carreau** [napari/napari#4133]
It seem to me that either bicubic has a bug or is non-sensical for label layer.  As the interpolation is done in data-sapce, if say labe 13  and  42 are next to each other, havin bicubic interpolation will go through all the colors of the ~~rainbow~~ colormap to interpolate from one color to the other.

I'm not sure there is something to "fix". Maybe interpolation in label layer should be a completely different logic and interpolate in color space ? Or be completely deactivated ?

<img width="1202" alt="Screen Shot 2022-02-21 at 14 49 36" src="https://user-images.githubusercontent.com/335567/154967743-e64072af-dd62-4558-85e3-621fa16fcd01.png">

<img width="1079" alt="Screen Shot 2022-02-21 at 14 56 12" src="https://user-images.githubusercontent.com/335567/154969029-07dd7265-ea88-495f-bed0-ff037a2edc9c.png">

_Originally posted by @Carreau in https://github.com/napari/napari/pull/4124#discussion_r811157141_

**Comment by psobolewskiPhD** [comment]
As of https://github.com/napari/napari/pull/6548 Labels layer no longer has interpolation (2d or 3d):
`AttributeError: 'Labels' object has no attribute 'interpolation2d'`
`AttributeError: 'Labels' object has no attribute 'interpolation3d'`
