### ISSUE TITLE
"In this example of we will" , maybe remove "of" ? 

### ISSUE THREAD

**Issue by Carreau** [napari/napari#4136]
## 📚 Documentation

I'm not sure if this is un unknown english construct to me, but it sounds like a shuffling of word gone wrong from 

"In this example of XXXX we will", to "in this example we will <do stuff> to the image of XXXX" , where the of stayed behind.

Also maybe one shape -> vector ?

```
$ rg 'In this example of we will'
docs/howtos/layers/shapes.md
36:In this example of we will overlay some shapes on the image of a photographer:

docs/howtos/layers/tracks.md
36:In this example of we will overlay some tracks on an image from the Hubble space

docs/howtos/layers/vectors.md
37:In this example of we will overlay some shapes on the image of a photographer:

docs/howtos/layers/points.md
44:In this example of we will overlay some points on the image of an astronaut:
```

**Comment by psobolewskiPhD** [comment]
Yeah, those aren't correct.
Simple fix would be to search & replace `<space>of` with `,<space>` .
From:
`36:In this example of we will overlay some shapes on the image of a photographer:`
To:
`36:In this example, we will overlay some shapes on the image of a photographer:`

Edit: to be safer: search and replace `In this example of we will` with `In this example, we will`
