### ISSUE TITLE
Paint color doesn't match color indicator after shuffle color button is pressed

### ISSUE THREAD

**Issue by marshuang80** [napari/napari#414]
## 🐛 Bug

When the "shuffle colors" button is pressed, the paint brush's color is changed as well. However, the paint brush color indicator on the left still displays the previous color. 

## To Reproduce

1. Make a label layer
2. Click shuffle colors
3. Paint on layer

![image](https://user-images.githubusercontent.com/15271135/61186046-6aedbc80-a615-11e9-8f15-e380a59f075d.png)

## Expected behavior

The paint color indicator should match the actual paint color. 

## Environment

 - napari 1.0
 - Linux 18.04 LTS
 - Python version: 3.7

**Comment by sofroniewn** [comment]
This will hopefully be fixed after fixing our vispy `0.6` update - as discussed here #407

**Comment by sofroniewn** [comment]
fixed by #416
