### ISSUE TITLE
Vispy issue on tracks layer when extending data if the layer has graph attributes

### ISSUE THREAD

**Issue by pmcesky** [napari/napari#4155]
## 🐛 Bug

Hi all,

I found one issue, when extending the tracks layer's data, if the layer has graph attributes, then there will be an error in vispy. 
I have asked this question in Image.sc, and thought it was an issue related to tracks.properties, but after many test, found it is probably related to tracks.graph.
https://forum.image.sc/t/how-to-update-an-existing-layer-using-layerdatatuple/63817/5

## To Reproduce
A notebook example to catch this error is linked here. 
https://gist.github.com/pmcesky/b4c5428ec647380bbfe4d2990c6319c4

## Environment
napari                    0.4.14
python                    3.9.7

There was a similar issue on tracks.graph before [Vispy error and warning in visulizing 4D time-lapse image and tracks · Issue #3819 · napari/napari · GitHub](https://github.com/napari/napari/issues/3819)
which seems to have been solved in 0.4.13.

I don’t know what caused the error this time though.

**Comment by pmcesky** [comment]
Found one thing, if a layer has graph attributes, then set it to another value, like {}, without doing other things, would lead to a vispy error:
![image](https://user-images.githubusercontent.com/18007222/155801788-77e3a70f-61d3-4435-bdae-1ad82819b47c.png)

**Comment by alisterburt** [comment]
sorry this isn't working for you @pmcesky and thank you for digging into this!

Maybe @JoOkuma has some insight here?

**Comment by JoOkuma** [comment]
Thanks, @alisterburt and @pmcesky. I opened a PR to fix this issue.

**Comment by andy-sweet** [comment]
@JoOkuma : I think #4165 closes this right?

**Comment by JoOkuma** [comment]
@andy-sweet Yes, thanks.

**Comment by andy-sweet** [comment]
@JoOkuma , @pmcesky : in that case, I'm closing this. Feel free to reopen if you think that's a mistake.
