### ISSUE TITLE
Setting contrast_limits to [1,1] causes hard to debug error

### ISSUE THREAD

**Issue by haesleinhuepf** [napari/napari#4158]
## 🐛 Bug

Hi all,

I just debugged an issue deep in napari and it turned out, I was unintentionally setting contrast_limits to [1,1]. If min and max of contrast limits are equal, this causes an error and it took me quite some time to understand what's the reason. I'm suggesting to catch this situation early with a clear error message. 

## To Reproduce

From python (I did in a juptyer notebook), call this:
```
import napari
import numpy as np

viewer = napari.Viewer()
image = np.asarray([[0,1], [0, np.inf]])
viewer.add_image(image, contrast_limits=[1,1])
```

This error happens:

```
File ~\miniconda3\envs\bio_39\lib\site-packages\napari\_qt\layer_controls\qt_image_controls_base.py:287, in range_to_decimals(range_, dtype)
[...]
OverflowError: cannot convert float infinity to integer
```

<details>
<summary markdown="span">Detailed log</summary>
<pre>
divide by zero encountered in log10
---------------------------------------------------------------------------
OverflowError                             Traceback (most recent call last)
Input In [3], in <module>
      1 image = np.asarray([[0,1], [0, np.inf]])
----> 3 viewer.add_image(image, contrast_limits=[1,1])

File ~\miniconda3\envs\bio_39\lib\site-packages\napari\components\viewer_model.py:732, in ViewerModel.add_image(self, data, channel_axis, rgb, colormap, contrast_limits, gamma, interpolation, rendering, iso_threshold, attenuation, name, metadata, scale, translate, rotate, shear, affine, opacity, blending, visible, multiscale, cache, experimental_slicing_plane, experimental_clipping_planes)
    724             raise TypeError(
    725                 trans._(
    726                     "Received sequence for argument '{argument}', did you mean to specify a 'channel_axis'? ",
   (...)
    729                 )
    730             )
    731     layer = Image(data, **kwargs)
--> 732     self.layers.append(layer)
    734     return layer
    735 else:

File ~\miniconda3\envs\bio_39\lib\_collections_abc.py:1073, in MutableSequence.append(self, value)
   1071 def append(self, value):
   1072     'S.append(value) -- append value to the end of the sequence'
-> 1073     self.insert(len(self), value)

File ~\miniconda3\envs\bio_39\lib\site-packages\napari\components\layerlist.py:90, in LayerList.insert(self, index, value)
     88 new_layer = self._type_check(value)
     89 new_layer.name = self._coerce_name(new_layer.name)
---> 90 super().insert(index, new_layer)

File ~\miniconda3\envs\bio_39\lib\site-packages\napari\utils\events\containers\_selectable_list.py:65, in SelectableEventedList.insert(self, index, value)
     64 def insert(self, index: int, value: _T):
---> 65     super().insert(index, value)
     66     if self._activate_on_insert:
     67         # Make layer selected and unselect all others
     68         self.selection.active = value

File ~\miniconda3\envs\bio_39\lib\site-packages\napari\utils\events\containers\_evented_list.py:179, in EventedList.insert(self, index, value)
    177 self.events.inserting(index=index)
    178 super().insert(index, value)
--> 179 self.events.inserted(index=index, value=value)
    180 self._connect_child_emitters(value)

File ~\miniconda3\envs\bio_39\lib\site-packages\napari\utils\events\event.py:715, in EventEmitter.__call__(self, *args, **kwargs)
    712     self._block_counter.update([cb])
    713     continue
--> 715 self._invoke_callback(cb, event if pass_event else None)
    716 if event.blocked:
    717     break

File ~\miniconda3\envs\bio_39\lib\site-packages\napari\utils\events\event.py:752, in EventEmitter._invoke_callback(self, cb, event)
    750     self.disconnect(cb)
    751     return
--> 752 _handle_exception(
    753     self.ignore_callback_errors,
    754     self.print_callback_errors,
    755     self,
    756     cb_event=(cb, event),
    757 )

File ~\miniconda3\envs\bio_39\lib\site-packages\napari\utils\events\event.py:739, in EventEmitter._invoke_callback(self, cb, event)
    737 try:
    738     if event is not None:
--> 739         cb(event)
    740     else:
    741         cb()

File ~\miniconda3\envs\bio_39\lib\site-packages\napari\_qt\layer_controls\qt_layer_controls_container.py:128, in QtLayerControlsContainer._add(self, event)
    120 """Add the controls target layer to the list of control widgets.
    121 
    122 Parameters
   (...)
    125     Event with the target layer at `event.value`.
    126 """
    127 layer = event.value
--> 128 controls = create_qt_layer_controls(layer)
    129 self.addWidget(controls)
    130 self.widgets[layer] = controls

File ~\miniconda3\envs\bio_39\lib\site-packages\napari\_qt\layer_controls\qt_layer_controls_container.py:67, in create_qt_layer_controls(layer)
     65 candidates.sort(key=lambda layer_type: layer_cls.mro().index(layer_type))
     66 controls = layer_to_controls[candidates[0]]
---> 67 return controls(layer)

File ~\miniconda3\envs\bio_39\lib\site-packages\napari\_qt\layer_controls\qt_image_controls.py:46, in QtImageControls.__init__(self, layer)
     45 def __init__(self, layer):
---> 46     super().__init__(layer)
     48     self.layer.events.interpolation.connect(self._on_interpolation_change)
     49     self.layer.events.rendering.connect(self._on_rendering_change)

File ~\miniconda3\envs\bio_39\lib\site-packages\napari\_qt\layer_controls\qt_image_controls_base.py:92, in QtBaseImageControls.__init__(self, layer)
     90 # Create contrast_limits slider
     91 self.contrastLimitsSlider = _QDoubleRangeSlider(Qt.Horizontal, self)
---> 92 decimals = range_to_decimals(
     93     self.layer.contrast_limits_range, self.layer.dtype
     94 )
     95 self.contrastLimitsSlider.setRange(*self.layer.contrast_limits_range)
     96 self.contrastLimitsSlider.setSingleStep(10 ** -decimals)

File ~\miniconda3\envs\bio_39\lib\site-packages\napari\_qt\layer_controls\qt_image_controls_base.py:287, in range_to_decimals(range_, dtype)
    279 else:
    280     # scale precision with the log of the data range order of magnitude
    281     # eg.   0 - 1   (0 order of mag)  -> 3 decimal places
   (...)
    284     #       ≥ 3 orders of mag -> no decimals
    285     # no more than 64 decimals
    286     d_range = np.subtract(*range_[::-1])
--> 287     return min(64, max(int(3 - np.log10(d_range)), 0))

OverflowError: cannot convert float infinity to integer
</pre>
</details>

## Expected behavior

Either no error happens at all, or a clear warning message tells that contrast_limits must be two different numbers. I'd be happy to implement the second case , e.g. [here](https://github.com/napari/napari/blob/main/napari/layers/image/image.py#L329), and send a PR if there is concensus that this is the right place and strategy.

## Environment

 - Please copy and paste the information at napari info option in help menubar here:
```
napari: 0.4.14
Platform: Windows-10-10.0.19042-SP0
Python: 3.9.10 | packaged by conda-forge | (main, Feb 1 2022, 21:22:07) [MSC v.1929 64 bit (AMD64)]
Qt: 5.12.9
PyQt5: 5.12.3
NumPy: 1.21.5
SciPy: 1.8.0
Dask: 2022.02.0
VisPy: 0.9.6

OpenGL:
- GL version: 4.6.14761 Compatibility Profile Context 21.30.02.01 30.0.13002.1001
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1200, scale 1.0

Plugins:
- PlatyMatch: 0.0.3
- RedLionfish: 0.6
- aicsimageio-in-memory: 0.5.0
- aicsimageio-out-of-memory: 0.5.0
- animation: 0.0.2
- cellpose-napari: 0.1.4
- clEsperanto: 0.15.4
- console: 0.0.4
- devbio_napari: 0.4.0
- napari-3d-ortho-viewer: 0.0.1
- napari-accelerated-pixel-and-object-classification: 0.6.6
- napari-allencell-segmenter: 1.1.4
- napari-brightness-contrast: 0.1.6
- napari-clusters-plotter: 0.2.2
- napari-crop: 0.1.5
- napari-curtain: 0.1.1
- napari-folder-browser: 0.1.3
- napari-itk-io: 0.1.0
- napari-ome-zarr: 0.1.0
- napari-plot-profile: 0.2.1
- napari-plugin-search: 0.1.3
- napari-segment-blobs-and-things-with-membranes: 0.2.17
- napari-simpleitk-image-processing: 0.2.1
- napari-tabu: 0.1.5
- napari-time-slicer: 0.4.3
- napari-tools-menu: 0.1.10
- napari-workflow-optimizer: 0.1.3
- napari_skimage_regionprops1: 0.2.9
- napari_skimage_regionprops2: 0.2.9
- ome-types: 0.2.10
- ome_zarr: 0.0.18
- scikit-image: 0.4.14
- svg: 0.1.5
```
 - Any other relevant information:

**Comment by sofroniewn** [comment]
> I'd be happy to implement the second case , e.g. [here](https://github.com/napari/napari/blob/main/napari/layers/image/image.py#L329), and send a PR if there is concensus that this is the right place and strategy.

I would put it here https://github.com/napari/napari/blob/842008f6df909bcbc391789badd7f2414eed6ec4/napari/layers/intensity_mixin.py#L76 AND here https://github.com/napari/napari/blob/842008f6df909bcbc391789badd7f2414eed6ec4/napari/layers/intensity_mixin.py#L99 sorry that's a bit hard to find. You could make a function `validate_increasing` and call it after `validate_2_tuple`.

**Comment by tlambert03** [comment]
Should it be strictly increasing?  Can't remember what happens, but I think it's ok to be inverted...

**Comment by haesleinhuepf** [comment]
Great question @tlambert03 

This code...
```
import napari
import numpy as np

viewer = napari.Viewer()
image = np.asarray([[0,1], [0, np.inf]])

# min > max:
viewer.add_image(image, contrast_limits=[1,0])
```

... causes this error in current napari main:
```
invalid value encountered in log10
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Input In [2], in <module>
----> 1 viewer.add_image(image, contrast_limits=[1,0])

File C:\structure\code\napari\napari\components\viewer_model.py:733, in ViewerModel.add_image(self, data, channel_axis, rgb, colormap, contrast_limits, gamma, interpolation, rendering, iso_threshold, attenuation, name, metadata, scale, translate, rotate, shear, affine, opacity, blending, visible, multiscale, cache, experimental_slicing_plane, experimental_clipping_planes)
    725             raise TypeError(
    726                 trans._(
    727                     "Received sequence for argument '{argument}', did you mean to specify a 'channel_axis'? ",
   (...)
    730                 )
    731             )
    732     layer = Image(data, **kwargs)
--> 733     self.layers.append(layer)
    735     return layer
    736 else:

File ~\miniconda3\envs\bio_39\lib\_collections_abc.py:1073, in MutableSequence.append(self, value)
   1071 def append(self, value):
   1072     'S.append(value) -- append value to the end of the sequence'
-> 1073     self.insert(len(self), value)

File C:\structure\code\napari\napari\components\layerlist.py:135, in LayerList.insert(self, index, value)
    133 self._clean_cache()
    134 new_layer.events.set_data.connect(self._clean_cache)
--> 135 super().insert(index, new_layer)

File C:\structure\code\napari\napari\utils\events\containers\_selectable_list.py:65, in SelectableEventedList.insert(self, index, value)
     64 def insert(self, index: int, value: _T):
---> 65     super().insert(index, value)
     66     if self._activate_on_insert:
     67         # Make layer selected and unselect all others
     68         self.selection.active = value

File C:\structure\code\napari\napari\utils\events\containers\_evented_list.py:183, in EventedList.insert(self, index, value)
    181 self.events.inserting(index=index)
    182 super().insert(index, value)
--> 183 self.events.inserted(index=index, value=value)
    184 self._connect_child_emitters(value)

File C:\structure\code\napari\napari\utils\events\event.py:715, in EventEmitter.__call__(self, *args, **kwargs)
    712     self._block_counter.update([cb])
    713     continue
--> 715 self._invoke_callback(cb, event if pass_event else None)
    716 if event.blocked:
    717     break

File C:\structure\code\napari\napari\utils\events\event.py:752, in EventEmitter._invoke_callback(self, cb, event)
    750     self.disconnect(cb)
    751     return
--> 752 _handle_exception(
    753     self.ignore_callback_errors,
    754     self.print_callback_errors,
    755     self,
    756     cb_event=(cb, event),
    757 )

File C:\structure\code\napari\napari\utils\events\event.py:739, in EventEmitter._invoke_callback(self, cb, event)
    737 try:
    738     if event is not None:
--> 739         cb(event)
    740     else:
    741         cb()

File C:\structure\code\napari\napari\_qt\layer_controls\qt_layer_controls_container.py:128, in QtLayerControlsContainer._add(self, event)
    120 """Add the controls target layer to the list of control widgets.
    121 
    122 Parameters
   (...)
    125     Event with the target layer at `event.value`.
    126 """
    127 layer = event.value
--> 128 controls = create_qt_layer_controls(layer)
    129 self.addWidget(controls)
    130 self.widgets[layer] = controls

File C:\structure\code\napari\napari\_qt\layer_controls\qt_layer_controls_container.py:67, in create_qt_layer_controls(layer)
     65 candidates.sort(key=lambda layer_type: layer_cls.mro().index(layer_type))
     66 controls = layer_to_controls[candidates[0]]
---> 67 return controls(layer)

File C:\structure\code\napari\napari\_qt\layer_controls\qt_image_controls.py:46, in QtImageControls.__init__(self, layer)
     45 def __init__(self, layer):
---> 46     super().__init__(layer)
     48     self.layer.events.interpolation.connect(self._on_interpolation_change)
     49     self.layer.events.rendering.connect(self._on_rendering_change)

File C:\structure\code\napari\napari\_qt\layer_controls\qt_image_controls_base.py:92, in QtBaseImageControls.__init__(self, layer)
     90 # Create contrast_limits slider
     91 self.contrastLimitsSlider = _QDoubleRangeSlider(Qt.Horizontal, self)
---> 92 decimals = range_to_decimals(
     93     self.layer.contrast_limits_range, self.layer.dtype
     94 )
     95 self.contrastLimitsSlider.setRange(*self.layer.contrast_limits_range)
     96 self.contrastLimitsSlider.setSingleStep(10**-decimals)

File C:\structure\code\napari\napari\_qt\layer_controls\qt_image_controls_base.py:291, in range_to_decimals(range_, dtype)
    283 else:
    284     # scale precision with the log of the data range order of magnitude
    285     # eg.   0 - 1   (0 order of mag)  -> 3 decimal places
   (...)
    288     #       ≥ 3 orders of mag -> no decimals
    289     # no more than 64 decimals
    290     d_range = np.subtract(*range_[::-1])
--> 291     return min(64, max(int(3 - np.log10(d_range)), 0))

ValueError: cannot convert float NaN to integer
```

**Comment by tlambert03** [comment]
Ah!  Ok, sounds good.  I know vispy does work with inverted clims, but if we've already lost that capability, looks like we've got other things to fix before that's a concern.  Thanks for checking
