### ISSUE TITLE
Numpy warning on adding point layer

### ISSUE THREAD

**Issue by hanjinliu** [napari/napari#4172]
## 🐛 Bug

Although I've not checked with other layer types yet, numpy warns every time a point layer is created.

## To Reproduce

```python
import napari
viewer = napari.view_points([1,2])
```

This warning is printed out

```
FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  return bool(asarray(a1 == a2).all())
```

## Environment

 - Please copy and paste the information at napari info option in help menubar here:

napari: 0.4.15rc0
Platform: Windows-10-10.0.22000-SP0
Python: 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)]
Qt: 5.15.2
PyQt5: 5.15.6
NumPy: 1.21.5
SciPy: 1.7.3
Dask: 2021.11.1
VisPy: 0.9.6

OpenGL:
- GL version: 4.6.0 - Build 27.20.100.9621
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1368x912, scale 2.0

Plugins:
- animation: 0.0.2
- console: 0.0.4
- napari-multitask: 0.0.2
- napari-roi: 0.1.0
- scikit-image: 0.4.15rc0
- svg: 0.1.5

Any other relevant information:

- numpy: 1.21.5

**Comment by VolkerH** [comment]
Also noticed this with 0.4.15

One additional observation I had is that neither the notification manager message nor the console output show the line number where this warning is thrown. For me, this was in a larger block of code so the connection to the point layer wasn't immediately obvious before coming here.

**Comment by tlambert03** [comment]
do you still see this after https://github.com/napari/napari/pull/4256?

**Comment by tlambert03** [comment]
I just went back and was able to reproduce this error in main just before #4256, but not after... I'm going to close this since I think it was resolved there (just missed this issue).  But feel free to re-open if you find otherwise

**Comment by VolkerH** [comment]
Thanks, I looked for an issue with FutureWarning. I found this and overlooked #4526 

Will give it a try.

**Comment by VolkerH** [comment]
just confirming that it is fixed
