### ISSUE TITLE
A "c" is printed when napari info is clicked

### ISSUE THREAD

**Issue by hanjinliu** [napari/napari#4173]
## 🐛 Bug

Before I copy the related environments from "Help > napari info" to report an issue, a "c" was printed.

## To Reproduce

"Help > napari info" or "Ctrl + /".

## Environment

 - Please copy and paste the information at napari info option in help menubar here:

napari: 0.4.15rc0
Platform: Windows-10-10.0.22000-SP0
Python: 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)]
Qt: 5.15.2
PyQt5: 5.15.6
NumPy: 1.21.5
SciPy: 1.7.3
Dask: 2021.11.1
VisPy: 0.9.6

OpenGL:
- GL version: 4.6.0 - Build 27.20.100.9621
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1368x912, scale 2.0

Plugins:
- animation: 0.0.2
- console: 0.0.4
- napari-multitask: 0.0.2
- napari-roi: 0.1.0
- scikit-image: 0.4.15rc0
- svg: 0.1.5

 - Any other relevant information:

**Comment by goanpeca** [comment]
Thanks for the report @hanjinliu , you mean like on the console?

I do not see a `c`

**Comment by hanjinliu** [comment]
Thanks for your reply @goanpeca ,
Yes, I see a "c" printed in the shell (or in Jupyter QtConsole if I launched `napari` there).
![output](https://user-images.githubusercontent.com/40591297/156274073-ad9193ff-810b-4588-a65e-732c5a265a18.gif)

**Comment by tlambert03** [comment]
found it!
https://github.com/tlambert03/napari/blob/c1f65b1b12ddcec9addb759d4eb47543d503b492/napari/utils/info.py#L66
