### ISSUE TITLE
Volume Plane slicing breaks with more than 3D

### ISSUE THREAD

**Issue by brisvag** [napari/napari#4196]
## 🐛 Bug

Somewhere the 4th dimension is getting passed all the way to the `Plane` model, which only knows 3D. This breaks on current main if tring to use the GUI to set the plane orientation!

## To Reproduce

```
ptyhon examples/nD_image.py
```

Then switch to 3D and change to `plane` mode. When you then click on `oblique`:

```
File ~/git/napari/venv/lib/python3.10/site-packages/pydantic/main.py:370, in pydantic.main.BaseModel.__setattr__()

ValidationError: 1 validation error for SlicingPlane
normal
  wrong tuple length 4, expected 3 (type=value_error.tuple.length; actual_length=4; expected_length=3)
```

cc @alisterburt 

## Environment

`v0.4.15rc1`

**Comment by jni** [comment]
Closed by #4197
