### ISSUE TITLE
A more sophisticate constrast limit bar

### ISSUE THREAD

**Issue by szsdk** [napari/napari#4203]
I am data science. In our field, the pixel values follow an exponential distribution. However, the default behavior of napari is setting the max pixel value as the vmax, which makes the control of values in the interesting region very difficult. A potential good solution is something like the contrast limit widget from `pyqtgraph`.

**Comment by tlambert03** [comment]
Are you looking for gamma?  It's true we don't have histogram like widget for contrast limits, but the linearity of the lookup is controlled by gamma... just below the contrast limits slider

**Comment by szsdk** [comment]
From my understanding, the gamma is for [gamma correction](https://www.wikiwand.com/en/Gamma_correction). Then that is not what I want. I want the ability to set contrast limits from (0, 0.0001) to (0, 10000) with a widget at the same time.

**Comment by tlambert03** [comment]
Right click on the contrast limits slider for more control of the exact numbers

**Comment by szsdk** [comment]
Thanks. Do not know about that. That helps a lot.

**Comment by tlambert03** [comment]
yeah, "make contrast limits widget more discoverable" has been on our to-do list for quite some time now :/ sorry about that.  Glad it works for you
