### ISSUE TITLE
Previously selected point deleted when deleting layer

### ISSUE THREAD

**Issue by jamesyan-git** [napari/napari#4209]
## 🐛 Bug

Recently selected points are erroneously removed when deleting new layers with the delete key. (reproduced with points and labels layer)

## To Reproduce

Steps to reproduce the behaviour:

1. Create a point on a points layer
2. Create a new points layer
3. Select the newly created points layer from the layer list (visually deselecting the point)
4. Delete newly created layer using the delete key, the last selected point will also be deleted

Please note that this issue does not occur when the layer is deleted using the bin icon, leading me to believe it is a keybinding issue (and the point must still be 'selected' in come capacity)

https://user-images.githubusercontent.com/95660545/156966137-b2a645a6-25ae-42b4-baf7-137e7506e20a.mp4

## Expected behaviour
It is expected that only the newly created points layer (with no points assigned to it) should be deleted, not the point as well.

## Environment

napari: 0.4.15.dev68+gdd3a2afd
Platform: Windows-10-10.0.19044-SP0
Python: 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)]
Qt: 5.15.2
PyQt5: 5.15.6
NumPy: 1.21.5
SciPy: 1.7.3
Dask: 2022.01.0
VisPy: 0.9.6

OpenGL:
- GL version: 4.6.0 - Build 26.20.100.7372
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1080, scale 1.0

Plugins:
- console: 0.0.4
- scikit-image: 0.4.15.dev68+gdd3a2afd
- svg: 0.1.6

napari contributors (2019). napari: a multi-dimensional image viewer for python. doi:10.5281/zenodo.3555620

**Comment by jni** [comment]
Wowza! That's indeed very surprising behaviour! :joy: thanks for reporting it @jamesyan-git!
