### ISSUE TITLE
Mouse / Brush disappears on large label layers

### ISSUE THREAD

**Issue by Karol-G** [napari/napari#4222]
Hi,

## 🐛 Bug

On label layers (e.g 5000x5000 pixel or 500x500x500 voxel) the mouse / brush disappears for certain brush sizes. In the first reproduction example the mouse disappears for very small brush sizes. However, in 3D images the mouse tends to disappear for larger brush sizes (second example) and that much more frequently. In my case this is quite problematic and makes it very difficult to annotate a 3D image.
It appears that the bug occurs much more on Linux (Ubuntu) than on Windows.

## To Reproduce

Example for brush size of 1 (Reproducable on Windows and Linux for me):
```python
from napari import Viewer
import napari
import numpy as np

viewer = Viewer()
viewer.add_labels(np.zeros((5000, 5000), dtype=int))
napari.run()
```

Example for maximum brush size (Only reproducable on Linux for me):
```python
from napari import Viewer
import napari
import numpy as np

viewer = Viewer()
viewer.add_labels(np.zeros((500, 500, 500), dtype=int))
napari.run()
```

## Expected behavior

Mouse / Brush should not disappear.

Best,
Karol

**Comment by Karol-G** [comment]
Has a developer tried to reproduce this issues? I have to annotate data from time to time and this is a bit annoying :/

Best,
Karol

**Comment by psobolewskiPhD** [comment]
Woof, I'm really sorry! This really fell through the cracks!
I can't reproduce this on my mac--I think this was fixed by using overlays for the brush: 
https://github.com/napari/napari/pull/5763

**Comment by Karol-G** [comment]
Hey,

yes, this bug seems to be fixed. I was not able to reproduce it anymore on my side. Thanks!
However, I found another bug that might be related to this solved one. I will open another issue for that one though.

Best,
Karol
