### ISSUE TITLE
Layer controls is showing up empty in Windows

### ISSUE THREAD

**Issue by lauramarcos** [napari/napari#4228]
## 🐛 Bug

Layer controls is just a grey square without the needed controls

## To Reproduce

1. Install napari v0.4.15rc3
2. Open napari and pay attention to the Layer Controls

## Actual behavior

<img width="209" alt="image" src="https://user-images.githubusercontent.com/63799148/157489174-b19588b9-a36e-48e6-b7fb-c21fd68e8c03.png">

## Expected behavior

Layer controls should be visible

<img width="262" alt="image" src="https://user-images.githubusercontent.com/63799148/157489223-25cd06a3-f82d-4916-9473-f26203c15722.png">

## Environment

napari: 0.4.15rc3
Platform: Windows-10-10.0.17763-SP0
Python: 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:22:46) [MSC v.1916 64 bit (AMD64)]
Qt: 5.12.9
PySide2: 5.13.2
NumPy: 1.22.3
SciPy: 1.8.0
Dask: 2022.02.1
VisPy: 0.9.6

**Comment by psobolewskiPhD** [comment]
Silly question, but do you have a layer created and selected?
E.g. File > Open Samples > napari > binary blobs
Edit: or click on the Points layer icon to create a points layer...
With no layer selected that's the behavior.

**Comment by lauramarcos** [comment]
> Silly question, but do you have a layer created and selected? E.g. File > Open Samples > napari > binary blobs Edit: or click on the Points layer icon to create a points layer... With no layer selected that's the behavior.

yup... you are right.. I freaked out for a second there... thank you!
