### ISSUE TITLE
Plugins are not being installed the first time when selected a bunch of them

### ISSUE THREAD

**Issue by lauramarcos** [napari/napari#4229]
## 🐛 Bug

When selecting several plugins to get installed, some of the plugins get installed. If selected each of them or again a couple of them, then they are installed successfully

## To Reproduce

1. Go to Install/Uninstall plugins
2. Click on Install button for several plugins from the Available Plugins section
3. Wait for them to get installed ---> some plugins were installed successfully but not all of them
4. Select again the plugins that were not installed
5. Now they are installed

https://user-images.githubusercontent.com/63799148/157492927-e81215e5-8b8a-4ef2-abb5-d89b1b68b770.mov

## Expected behavior

All plugins should get installed during the first time

## Environment

napari: 0.4.15rc3
Platform: macOS-11.6.4-x86_64-i386-64bit
System: MacOS 11.6.4
Python: 3.9.10 | packaged by conda-forge | (main, Feb 1 2022, 21:28:27) [Clang 11.1.0 ]
Qt: 5.12.9
PySide2: 5.13.2
NumPy: 1.22.3
SciPy: 1.8.0
Dask: 2022.02.1
VisPy: 0.9.6

napari: 0.4.15rc3
Platform: Windows-10-10.0.17763-SP0
Python: 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:22:46) [MSC v.1916 64 bit (AMD64)]
Qt: 5.12.9
PySide2: 5.13.2
NumPy: 1.22.3
SciPy: 1.8.0
Dask: 2022.02.1
VisPy: 0.9.6

**Comment by liu-ziyang** [comment]
this should be addressed as part of the #4283, if anyone experience again or have more information please reopen this issue
