### ISSUE TITLE
Waver plugin crashes app in windows and shows Error in mac

### ISSUE THREAD

**Issue by lauramarcos** [napari/napari#4230]
## 🐛 Bug

When selecting Waver -> Simulation, app crashes in windows and in mac, thee is a Error displayed

## To Reproduce

1. Install Waver plugin
2. Click on Plugins -> Waver -> Simulation
3. Pay attention to app

## Expected behavior

App crashes in windows and shows error in ma

https://user-images.githubusercontent.com/63799148/157494446-31774dc3-6181-4842-baab-e03d85914a6d.mov

https://user-images.githubusercontent.com/63799148/157494700-7a80be54-550d-4307-8b67-823baa4bb453.mov

[waver_tracebak.pdf](https://github.com/napari/napari/files/8216752/waver_tracebak.pdf)

## Environment

 napari: 0.4.15rc3
Platform: macOS-11.6.4-x86_64-i386-64bit
System: MacOS 11.6.4
Python: 3.9.10 | packaged by conda-forge | (main, Feb 1 2022, 21:28:27) [Clang 11.1.0 ]
Qt: 5.12.9
PySide2: 5.13.2
NumPy: 1.22.3
SciPy: 1.8.0
Dask: 2022.02.1
VisPy: 0.9.6

napari: 0.4.15rc3
Platform: Windows-10-10.0.17763-SP0
Python: 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:22:46) [MSC v.1916 64 bit (AMD64)]
Qt: 5.12.9
PySide2: 5.13.2
NumPy: 1.22.3
SciPy: 1.8.0
Dask: 2022.02.1
VisPy: 0.9.6

**Comment by tlambert03** [comment]
this is an issue in Waver, not napari.  so going to close this.  But cc @sofroniewn: I think line 33 of _dock_widget.py should be:

```python
               custom: Optional['napari.layers.Layer']=None,
               # instead of
               custom: 'napari.layers.Layer'=None,
```

if `None` is a valid option

**Comment by sofroniewn** [comment]
Thanks for catching @lauramarcos and thanks for flag @tlambert03 - i will fix on waver end when i get this chance.

I wonder if this is a good example of a plugin bug that could be caught through automated testing?

**Comment by tlambert03** [comment]
yep, pretty sure this would be caught by my CI action ([this test](https://github.com/tlambert03/napari-plugin-action/blob/67f98a4e4081e77ff8c9340d79f37ea6f2451c6c/test_plugin.py#L100-L120))

try it:
```
    - uses: tlambert03/napari-plugin-action@main
      with:
        package_name: <your-package-name>
```

https://github.com/tlambert03/napari-plugin-action

**Comment by tlambert03** [comment]
(nevermind, the [last few lines there](https://github.com/tlambert03/napari-plugin-action/blob/67f98a4e4081e77ff8c9340d79f37ea6f2451c6c/test_plugin.py#L118-L120) would need to be uncommented for this to be caught)
