### ISSUE TITLE
Warnings are displayed when new label is added

### ISSUE THREAD

**Issue by lauramarcos** [napari/napari#4231]
## 🐛 Bug

When adding a new label a warning is displayed in Windows and Mac

## To Reproduce

1. Open napari
2. Click on File -> Open Sample -> napari -> "any option"
3. Click on any of the buttons on the layer list
4. Pay attention to warnings

## Expected behavior

Warning should not be displayed

https://user-images.githubusercontent.com/63799148/157496090-8f1052b8-a4cc-4b54-877d-d133624ae5ba.mov

## Environment

napari: 0.4.15rc3
Platform: Windows-10-10.0.17763-SP0
Python: 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:22:46) [MSC v.1916 64 bit (AMD64)]
Qt: 5.12.9
PySide2: 5.13.2
NumPy: 1.22.3
SciPy: 1.8.0
Dask: 2022.02.1
VisPy: 0.9.6

napari: 0.4.15rc3
Platform: macOS-11.6.4-x86_64-i386-64bit
System: MacOS 11.6.4
Python: 3.9.10 | packaged by conda-forge | (main, Feb 1 2022, 21:28:27) [Clang 11.1.0 ]
Qt: 5.12.9
PySide2: 5.13.2
NumPy: 1.22.3
SciPy: 1.8.0
Dask: 2022.02.1
VisPy: 0.9.6

**Comment by psobolewskiPhD** [comment]
Ah! This is what I was seeing the other day, also on macOS (12.2.1) but arm64.
https://github.com/napari/napari/issues/3568#issuecomment-1061049259
