### ISSUE TITLE
Uninstall is not happening for some plugins in mac

### ISSUE THREAD

**Issue by lauramarcos** [napari/napari#4232]
## 🐛 Bug

Plugins cannot be uninstalled

## To Reproduce

1. Instal several plugins
2. Click on Uninstall button for a bunch of them

https://user-images.githubusercontent.com/63799148/157497851-56f78252-8ad4-4794-89ac-5cd3ea4c1813.mov

## Expected behavior

Plugins should be uninstalled

## Environment

 napari: 0.4.15rc3
Platform: macOS-11.6.4-x86_64-i386-64bit
System: MacOS 11.6.4
Python: 3.9.10 | packaged by conda-forge | (main, Feb 1 2022, 21:28:27) [Clang 11.1.0 ]
Qt: 5.12.9
PySide2: 5.13.2
NumPy: 1.22.3
SciPy: 1.8.0
Dask: 2022.02.1
VisPy: 0.9.6

**Comment by liu-ziyang** [comment]
this should be addressed as part of #4283, if anyone experience this again please reopen this issue
