### ISSUE TITLE
More selection rules discussion + a keyboard shortcut

### ISSUE THREAD

**Issue by jni** [napari/napari#424]
After deleting a layer, the layer underneath it should be selected. This allows rapid deletion of layers by clicking the trashcan icon, rather than the current behavior, which requires going back and forth between the trash icon and the next layer. When deleting the bottommost layer, the layer above it should be selected.

Finally, we should add a shortcut, say Shift-Backspace, for deleting layers.

**Comment by sofroniewn** [comment]
This is easy to do. @kne42 is going to move over the current keybindings to the new style soon. once that is done i can do this

**Comment by jni** [comment]
CC @stefanv who just pinged me privately to ask for exactly this. ;)

**Comment by sofroniewn** [comment]
fixed by #472

**Comment by jni** [comment]
This is amazing @sofroniewn! I just tried it and it's soooo much nicer! :clap: 

I agree wholeheartedly with the decision to merge and revisit default bindings later, btw. =) Thank you!
