### ISSUE TITLE
New napari window spawned when plugin starts a new `Process()`

### ISSUE THREAD

**Issue by dstansby** [napari/napari#4244]
## 🐛 Bug

I have a plugin that spawns multiple `multiprocessing.Process()` to run tasks concurrently. If I launch `napari` from the command line and run the plugin everything is fine. If I launch `napari` from a Python script, multiple `napari` windows are spawned, I presume one per `Process()`?

The script I'm using to open `napari` is:
```python
import napari
from skimage.data import astronaut

viewer = napari.view_image(astronaut(), rgb=True)
napari.run()
```

And the contents of my plugin are:
```python
from multiprocessing import Process

def show_hello_message():
    p = Process(target=print, args=('Hello, world',))
    p.start()
    p.join()
```

## Expected behavior
Only a single `napari` window open, with no new ones sapwning.

## Environment

```
napari: 0.4.14
Platform: macOS-12.2.1-arm64-arm-64bit
System: MacOS 12.2.1
Python: 3.9.10 | packaged by conda-forge | (main, Feb 1 2022, 21:27:43) [Clang 11.1.0 ]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.21.5
SciPy: 1.8.0
Dask: 2022.02.1
VisPy: 0.9.6

OpenGL:
- GL version: 2.1 Metal - 76.3
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1080, scale 1.0
- screen 2: resolution 1440x900, scale 2.0

Plugins:
- brainglobe-io: 0.1.3
- brainreg-standard: 0.1.3
- console: 0.0.4
- napari-arboretum: 0.0.3.dev10+g95ec652.d20220309
- ndtiffs: 0.1.2
- scikit-image: 0.4.14
- svg: 0.1.5
- ```

## Additional context

<!-- Add any other context about the problem here. -->

**Comment by tlambert03** [comment]
I believe this is just an idiosyncracy of the way python spawns processes.  In your main script, you should hide the stuff that you only want to happen in the main process behind `if __name__ == '__main__'`

```python
import napari
from skimage.data import astronaut

if __name__ == '__main__':
    viewer = napari.view_image(astronaut(), rgb=True)
    napari.run()
```

see these for a bit more discussion:
https://stackoverflow.com/questions/20360686/compulsory-usage-of-if-name-main-in-windows-while-using-multiprocessi
https://stackoverflow.com/questions/20222534/python-multiprocessing-on-windows-if-name-main

(it's not just windows as those link titles suggest... I need to do it on *nix platforms too)

**Comment by dstansby** [comment]
That works great, thanks for the solution. I'll close this since that works.
