### ISSUE TITLE
Change default location for next release of bundle app

### ISSUE THREAD

**Issue by goanpeca** [napari/napari#4249]
## 🧰 Task

To avoid users getting an error message from installing the constructor app on the same location.

This is a one time fix. After updates in place are ready, this problem should be there.

**Comment by jaimergp** [comment]
I think this is a non-issue. Current conda bundle appends the version to the default installation path, e.g. `$HOME/.local/napari-v0.4.15`.

**Comment by goanpeca** [comment]
>$HOME/.local/napari-v0.4.15.

Correct, but we probably want something more generic that does not use the version itslef since the newer versions of napari will live inside this folder too.
