### ISSUE TITLE
Label features in status bar inconsistent with label identifier

### ISSUE THREAD

**Issue by haesleinhuepf** [napari/napari#4250]
## 🐛 Bug

Hi all,

I'm observing an inconsistency in the status bar of napari when inspecting a label image. In the following screenshot, I was hovering over a label with intensity 17; label 17. In napari-skimage-regionprops lives an interactive table that also highlights label 17 in that situation. However, the status bar of napari then lists the properties/features of label 18 and the wrong area measurement for this object.

I'm wondering if the status bar takes the colum "label" in the table into account.

![image](https://user-images.githubusercontent.com/12660498/157976697-6f5b1f03-7de2-444a-ba68-650c6fe09e0e.png)

## To Reproduce

1. Install napari, napari-segment-blobs-and-things-with-membranes and napari-skimage-regionprops
2. Open the [blobs.tif](https://github.com/clEsperanto/napari_pyclesperanto_assistant/blob/master/napari_pyclesperanto_assistant/data/blobs.tif) image
3. Apply the menu `Tools > Segmentation / Labeling > Voronoi-Otsu-Labeling (nsbatwm)` with parameters 5 and 2.
4. Apply the menu `Tools > Measurement > Regionprops (nsr)`
5. Hower over labels in the image. It will show the inconsistency in the status bar.

## Expected behavior

The status bar text should show the right value (row) from the table, from the line where label=17 in my above mentioned case.

If this is an error in napari-skimage-regionprops, I'm happy to fix it, I just need precise instructions how layer.features should be interpreted to assign the right measurements to the right label. Thanks!

## Environment

 - Please copy and paste the information at napari info option in help menubar here:
```
napari: 0.4.15rc3
Platform: Windows-10-10.0.19042-SP0
Python: 3.9.10 | packaged by conda-forge | (main, Feb 1 2022, 21:22:07) [MSC v.1929 64 bit (AMD64)]
Qt: 5.12.9
PyQt5: 5.12.3
NumPy: 1.21.5
SciPy: 1.8.0
Dask: 2022.02.0
VisPy: 0.9.6

OpenGL:
- GL version: 4.6.14761 Compatibility Profile Context 21.30.02.01 30.0.13002.1001
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1200, scale 1.0

Plugins:
- PlatyMatch: 0.0.3
- RedLionfish: 0.6
- aicsimageio-in-memory: 0.5.0
- aicsimageio-out-of-memory: 0.5.0
- animation: 0.0.2
- cellpose-napari: 0.1.4
- clEsperanto: 0.15.5
- console: 0.0.4
- devbio_napari: 0.4.0
- napari-3d-ortho-viewer: 0.0.1
- napari-accelerated-pixel-and-object-classification: 0.6.6
- napari-allencell-segmenter: 1.1.4
- napari-assistant: 0.1.0
- napari-brightness-contrast: 0.1.7
- napari-clusters-plotter: 0.2.2
- napari-crop: 0.1.5
- napari-curtain: 0.1.1
- napari-folder-browser: 0.1.3
- napari-itk-io: 0.1.0
- napari-ome-zarr: 0.1.0
- napari-plot-profile: 0.2.1
- napari-plugin-search: 0.1.3
- napari-segment-blobs-and-things-with-membranes: 0.2.17
- napari-simpleitk-image-processing: 0.2.1
- napari-tabu: 0.1.5
- napari-time-slicer: 0.4.3
- napari-tools-menu: 0.1.10
- napari-workflow-optimizer: 0.1.3
- napari_skimage_regionprops1: 0.2.9
- napari_skimage_regionprops2: 0.2.9
- ome-types: 0.2.10
- ome_zarr: 0.0.18
- scikit-image: 0.4.15rc3
- svg: 0.1.5
```
 - Any other relevant information:

**Comment by jni** [comment]
Interesting! Thanks for the report @haesleinhuepf! I think you are right that we probably have an off-by-one error in indexing the features...

**Comment by jni** [comment]
Aaaah, memories flooding in, you are running into #2596! For now, you need to rename 'label' to 'index'. 

If you look at [`examples/add_labels_with_features.py`](https://github.com/napari/napari/blob/b6cc4bf6a8d8a49792817e7aa70008e954f60dc0/examples/add_labels_with_features.py#L38-L43), you will see that we sweep this issue completely under the rug there. :joy: 

So, yeah, for now, renaming 'label' to 'index' *should* fix your problem...

**Comment by haesleinhuepf** [comment]
Thanks for the feedback @jni ! I cannot _rename_ the "label" column because this would break a hand full of plugins and scripts. Thus, I added a workaround to napari-skimage-regionprops: If there is a "label" column, I'm adding an "index" column with the same content. This solves the issue; presumably in all plugins that use our tables. 

![image](https://user-images.githubusercontent.com/12660498/158009930-921bb2c8-fcba-4732-bca5-1c97ea17022e.png)
