### ISSUE TITLE
'examples/notebook.ipynb' link on napari.org is no longer available.

### ISSUE THREAD

**Issue by 2dx** [napari/napari#4260]
## 📚 Documentation

A minor issue, but a link in the napari.org of [Jupyter notebook usage part](https://napari.org/tutorials/fundamentals/getting_started.html#jupyter-notebook-usage) is now broken.

Would recommend remove this link or prepare notebook.ipynb in the repository. This file seems to have been deleted in the main branch at some point.
![image](https://user-images.githubusercontent.com/11834588/158281964-ab016c83-af8b-4e1a-aad1-5cd6db04a443.png)

**Comment by Carreau** [comment]
Thanks for the report, 

It looks like this has been removed as part of 2243b1fe92ab654a89c35455d81c788387a33c3b in #4063
