### ISSUE TITLE
'napari._vispy.layers.image' is not a package

### ISSUE THREAD

**Issue by lukasvasadi** [napari/napari#4263]
## Activating experimental rendering features causes persistent ModuleNotFoundError

Recently, I discovered the two "experimental" features designed to enhance viewer performance with asynchronous rendering. After checking both options in Preferences (under Experimental), the GUI prompted a restart. When attempting to relaunch Napari, the following error is thrown: `ModuleNotFoundError: No module named 'napari._vispy.layers.image.experimental'; 'napari._vispy.layers.image' is not a package`. I tried recreating my virtual environment, installing a different version of Napari, using the `--no-cache-dir` flag with pip to ensure that the installation process did not use cached files...but every new installation of Napari now throws this error.

## To Reproduce

1. Check both experimental rendering options under File/Preferences/Experimental
2. Restart Napari

**Comment by tlambert03** [comment]
> I tried recreating my virtual environment, installing a different version of Napari, using the --no-cache-dir flag with pip to ensure that the installation process did not use cached files...but every new installation of Napari now throws this error.

sorry for the trouble!  napari stores settings outside of the site-packages folder (e.g. `~/Library/ApplicationSupport/Napari/` for mac)  you can run `napari --reset` to reset settings to their defaults.  Let us know if that helps (with the annoyance).  Looks like there might be an actual bug though with the import?

**Comment by lukasvasadi** [comment]
Wow that was a quick fix! Thanks for the tip.

Yes not sure about the import. I think the program is looking for the "octree_image.py" file in the wrong "image" directory, as the the "_vispy" directory does not contain an "image/experimental/" sub-directory...May be worth some investigation 🙂

**Comment by tlambert03** [comment]
yep, can reproduce thanks.  Will add a fix

**Comment by MichaelSNelson** [comment]
Thanks for posting the solution, just ran into this today with a fresh install, also based on checking both options (only needed one for the .ims file viewer, but did not expect it to kill Napari!)

napari: 0.4.14
Platform: Windows-10-10.0.19044-SP0
Python: 3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:50:36) [MSC v.1929 64 bit (AMD64)]
Qt: 5.15.4
PyQt5: 5.15.7
NumPy: 1.23.1
SciPy: 1.9.0
Dask: 2022.8.0
VisPy: 0.11.0

**Comment by psobolewskiPhD** [comment]
@MichaelSNelson I think you may also be affected by this issue: https://github.com/napari/napari/issues/4891
where packages from conda-forge are actually out-dated (0.4.14) and not latest release (0.4.16).
You should be able to force it to install the proper version by using:
`conda install napari=0.4.16`
(or by using mamba)
Napari is iterating quickly so lots of bug fixes are pushed and dependencies can also change.
