### ISSUE TITLE
Contributing Guide instructions don't work: requirements.txt missing??

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari/napari#4266]
## 🐛 Bug

<preface: I have no idea if this is the proper place to report this. The whole napari/napari.org/docs/etc. thing is **super confusing**.>

Following the Contributing Guide: https://napari.org/docs/dev/developers/contributing.html#setting-up-a-development-installation fails when it says to: `pip install -r requirements.txt`
This doesn't work: 
```
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
```
This file does not appear to be present in the napari repo.

## To Reproduce

Follow the Guide:
1. clone the repo
2. cd napari
3. pip install -r requirements.txt

## Expected behavior

Not sure? Not an error anyways—already stressed enough!

## Environment

```
napari: 0.4.16.dev17+g2a14717f
Platform: macOS-12.2.1-arm64-arm-64bit
System: MacOS 12.2.1
Python: 3.9.10 | packaged by conda-forge | (main, Feb 1 2022, 21:27:43) [Clang 11.1.0 ]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.21.5
SciPy: 1.8.0
Dask: 2022.02.0
VisPy: 0.9.6

OpenGL:
- GL version: 2.1 Metal - 76.3
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1680x1050, scale 2.0

Plugins:
- StarDist: 2021.10.25
- aicsimageio-in-memory: 0.6.1
- aicsimageio-out-of-memory: 0.6.1
- clEsperanto: 0.15.3
- console: 0.0.4
- napari-brightness-contrast: 0.1.6
- napari-time-slicer: 0.4.3
- napari-tools-menu: 0.1.10
- napari_skimage_regionprops1: 0.2.9
- napari_skimage_regionprops2: 0.2.9
- ome-types: 0.2.9
- scikit-image: 0.4.16.dev17+g2a14717f

```

## Additional context

macOS 12.2.1, arm64

**Comment by tlambert03** [comment]
well, I'm not sure if this adds to the confusion or decreases it, but that docs link isn't actually showing the newest docs :joy:?

I fixed this in https://github.com/napari/napari/pull/4105, and it's live now on https://napari.org/developers/contributing.html ... do you have a bookmark to https://napari.org/docs/dev/ perhaps?  @jni, any idea where that's pulling from?

**Comment by tlambert03** [comment]
> The whole napari/napari.org/docs/etc. thing is super confusing

so sorry about this.  it's a large scale cleanup project midway through 😖

**Comment by tlambert03** [comment]
(I feel responsible for encouraging you to make a PR 😅 ... lemme know if I can help!)

**Comment by tlambert03** [comment]
ahhhh.... it's this repo: https://github.com/napari/docs  ... will look into whether we can kill it

**Comment by tlambert03** [comment]
I turned off gh-pages for `napari/docs` ... so that confusing `napari.org/docs` won't be there anymore.  just go to napari.org.  closing this since the actual issue has been fixed, but lemme know if I can help

**Comment by psobolewskiPhD** [comment]
Gah, I'm sorry I wasn't clear. It's this page:
https://napari.org/docs/dev/developers/contributing.html
It's linked from GitHub napari/napari (https://github.com/napari/napari)
https://github.com/napari/napari

**Comment by psobolewskiPhD** [comment]
Anyhow, I'm forging ahead, because I'm thick and I've had a Sidecar. Sorry if I mess something up!

**Comment by tlambert03** [comment]
🤦‍♂️

**Comment by psobolewskiPhD** [comment]
Good news: the wrong info is gone.
Bad news: 404 error 🤣 
Again if I wasn't clear before it's the link here in the GitHub homepage to contributing guide
<img width="665" alt="image" src="https://user-images.githubusercontent.com/76622105/158478065-5d2e267c-1caa-4567-a23a-4c6417bb37e4.png">

**Comment by psobolewskiPhD** [comment]
> I turned off gh-pages for `napari/docs` ... so that confusing `napari.org/docs` won't be there anymore. just go to napari.org. closing this since the actual issue has been fixed, but lemme know if I can help

FYI: a lot of google search results point to the napari.org/docs and it's all 404 now. Not sure there's anything to be done about it...

**Comment by tlambert03** [comment]
We can work on a redirect at napari/docs, and it will also resolve over time.  I'm actually less concerned  about 404 for a period of time than something that directs to a seemingly correct (but not) page!
