### ISSUE TITLE
Unable to find `https://napari.org/docs/dev/objects.inv`

### ISSUE THREAD

**Issue by michalk8** [napari/napari#4270]
## 📚 Documentation

As mentioned above, previously accessible https://napari.org/docs/dev/objects.inv is no longer found.

**Comment by melissawm** [comment]
Can you try using https://napari.org/objects.inv instead? Because of recent changes in our docs deployment, this file has moved.

**Comment by michalk8** [comment]
Thanks, using https://napari.org in intersphinx works, think this can be closed. Quick question: will ``napari`` docs be versioned in any way (e.g. stable/latest) in the future?

**Comment by tlambert03** [comment]
> Quick question: will napari docs be versioned in any way (e.g. stable/latest) in the future

Yes!  Definitely something we very much want and are (slowly) working towards
