### ISSUE TITLE
AttributeError: 'LayerList' object has no attribute 'name'

### ISSUE THREAD

**Issue by Carreau** [napari/napari#4271]
## 🐛 Bug

- open napari, 
- Click on empty canvas.
- Press Ctrl-C
Console will show:

```
File ~/dev/napari/napari/_qt/containers/qt_layer_model.py:17, in QtLayerListModel.data(self=<napari._qt.containers.qt_layer_model.QtLayerListModel object>, index=<PyQt5.QtCore.QModelIndex object>, role=0)
     16 if role == Qt.DisplayRole:  # used for item text
---> 17     return layer.name
        layer = []
     18 if role == Qt.TextAlignmentRole:  # alignment of the text
     19     return Qt.AlignCenter

AttributeError: 'LayerList' object has no attribute 'name'
```

## Expected behavior

Don't.

## Environment

This seem to be because `_base_item_model:_BaseEventedItemModel.getItem` is not type stable.

```
    def getItem(self, index: QModelIndex) -> ItemType:
        """Return python object for a given `QModelIndex`.

        An invalid `QModelIndex` will return the root object.
        """
        return self._root[index.row()] if index.isValid() else self._root
```

The `else_self.root` is not of Type `ItemType`, but an (Empty) container.

**Comment by Carreau** [comment]
I tried to understand the logic behind `_BaseEventedItemModel`, but I think that may needs @tlambert03

**Comment by Czaki** [comment]
Did you play with connecting functions to layer list events? Because it looks like it may be result of inconsistent internal state.

**Comment by tlambert03** [comment]
@Czaki, I linked those discussions in https://github.com/napari/napari/pull/4276#issuecomment-1116810562
