### ISSUE TITLE
Labels layer not visible on Windows

### ISSUE THREAD

**Issue by joe-albert** [napari/napari#428]
## 🐛 Bug

If you add a labels layer on Windows you can see the labels in the thumbnail but not in the viewer.

I also get a vispy warning: 
INFO: Program has unset variables: ('texture2D_LUT')

## To Reproduce

```python
image = io.imread('image.png')
segmentation = io.imread('segments.png')
glom = (segmentation == 1).astype(int)
v = napari.Viewer()
v.add_image(image)
v.add_labels(glom)
```
~~@jni will provide the example data asap~~ **Note from @jni:** Added below

## Environment

 - napari Version (e.g., 1.0): 0.1.1+5g1a87b2b
 - OS (e.g., Linux): Windows 7
 - Python version:3.7
 - Any other relevant information:

**Comment by jni** [comment]
test images: (though I suspect this would work fine with random data)

image.png
![image](https://user-images.githubusercontent.com/492549/61493092-678d6480-a978-11e9-9f0c-e10f13022acb.png)

segments.png
![segments](https://user-images.githubusercontent.com/492549/61493098-6b20eb80-a978-11e9-902f-7058f3779f67.png)

**Comment by sofroniewn** [comment]
interesting, we've been running into some problems with our labels colormap - i have a PR in right now #430 that might fix it. if not we'll follow up

**Comment by sofroniewn** [comment]
@DowneastFreaks do you mind upgrading napari to `0.2.0` and trying this again, we've made a number of improvements that might fix this, and we've also been trying to understand our windows problems a little more systematically - see for example this thread #558.

If it still doesn't work, do you mind running
```python
import vispy
print(vispy.sys_info())
```
and sending us the results.

Thanks!!

**Comment by joe-albert** [comment]
@sofroniewn 

I was able to get this running using some of the comments in #558 

Specifically this was the code that worked for me:
```
from skimage import io
import napari

image = io.imread('image.png')
segments = io.imread('segments.png')
glom = (segments == 1).astype(int)

with napari.gui_qt():
    viewer = napari.view_image(image)
    viewer.add_labels(glom)
```

![image](https://user-images.githubusercontent.com/51097457/66314110-864d2880-e8e1-11e9-82f5-d937c08ae9bc.png)

Thanks for looking into this and let me know if there are any other questions I can help with! :)

**Comment by sofroniewn** [comment]
That's great. So glad it is working. Do you mind actually posting the results of 

```python
import vispy
print(vispy.sys_info())
```

anyway. Just trying to keep track of which windows systems are still causing us problems and which are not

**Comment by joe-albert** [comment]
Here is what i'm getting as output from those commands:
```
Platform: Windows-7-6.1.7601-SP1
Python:   3.6.3 |Anaconda, Inc.| (default, Oct 15 2017, 03:27:45) [MSC v.1900 64 bit (AMD64)]
NumPy:    1.16.4
Backend:  PySide2
pyqt4:    None
pyqt5:    None
pyside:   None
pyside2:  ('PySide2', '5.13.1', '5.13.1')
pyglet:   None
glfw:     None
sdl2:     None
wx:       None
egl:      None
osmesa:   None
_test:    None
GL version:  '4.4.0 - Build 21.20.16.4821'
```

**Comment by sofroniewn** [comment]
Perfect, thanks! I am going to close this issue, but feel free to reopen or make a new one if you have anymore problems
