### ISSUE TITLE
fixed-range rendered marker size

### ISSUE THREAD

**Issue by berl** [napari/napari#429]
## 🚀 Feature

I'd like to have the (perhaps optional) ability to set a min and max rendered marker size
## Motivation

Analyzed data from [starfish](https://github.com/spacetx/starfish) can be rendered very nicely as marker layers in napari. Using different colors for the many different mRNA species (~20 here) is great.  However, when I zoom in, the fixed marker size makes all the colors for different mRNA species blend together to white (in additive blending) or otherwise become confusing (in other blending modes or when the face color == None).    
## Pitch
I'd like to be able to set a minimum and maximum size of the _rendered_ marker so that when I zoom in beyond a certain point, the markers don't get bigger. This would allow me to zoom in far enough that the rendered markers would not overlap. 

## Alternatives
A slider to adjust marker size for all markers at once might also do the trick?  I'd like to retain the expected behavior over the majority of the zoom range.

**Comment by VolkerH** [comment]
Can I bring this back up.
The marker size in the points layer is currently too large to accurately place points on pixels:
![image](https://user-images.githubusercontent.com/2210044/105469016-f1b63780-5c97-11eb-9131-0ccc74c6b2ea.png)

They do scale with camera zoom, but I cannot find any zoom level that lets me see which pixel a marker is centrerd over

![image](https://user-images.githubusercontent.com/2210044/105469191-2b873e00-5c98-11eb-9dfb-e4d1c4b62507.png)

**Comment by brisvag** [comment]
I forgot to close this one when #3734 was merged. Closing now!
