### ISSUE TITLE
Option to suppress console logging

### ISSUE THREAD

**Issue by lukasvasadi** [napari/napari#4296]
## Suppress console logging
I upgraded my Napari version and am now seeing loads of logging output on my launch console (not the built-in Napari console). This makes it difficult to view other information being printed. I tried various approaches to suppress the logging output from the module, but have not found any success. Logging suppression may already be a feature, but I cannot seem to find it in the documentation. Ideally, there would be a way to select which information is printed, e.g., deprecation warnings.

The "Console notification level" in Preferences seems to only affect the built-in console.

## Motivation

Want to be able to view other printed output without sifting through loads of logging info 🙂

**Comment by tlambert03** [comment]
Can you provide an example of the logging so we can see where it's coming from?  (e.g. if it's a plugin?)

**Comment by lukasvasadi** [comment]
First, I receive a printout of every package from my virtual environment. Then, I see various warnings and debug messages.

![image](https://user-images.githubusercontent.com/18079821/159521189-aed3fdbc-7b89-476c-adf2-90c2ec034f55.png)

**Comment by tlambert03** [comment]
strange.  I don't _think_ it's napari doing that... that is, I've never seen that while working on/with napari.  That could happen though if _any_ of the packages imported in your environment modify the global python logger.  Have you already tried a new environment?  and could you perhaps give the output of `conda list` or `pip list` so we can see what's in the environment?  (even still, it does seem like it could also be settings-related for another package.  I do see a lot of matplotlib in there, which makes me wonder whether something is adjusting _its_ logging level?)`

I also wonder what would happen if you manually [set the python logging level with basicConfig](https://docs.python.org/3/library/logging.html#logging.basicConfig):


```
import logging
logging.basicConfig(level=logging.CRITICAL)

import napari
viewer = napari.Viewer()
```

**Comment by lukasvasadi** [comment]
You are probably right. Unfortunately, setting the logging level to critical does not seem to suppress the output. Just running `napari` from my environment does not throw all that information, but then that instance is missing all the features we added to the program, which I assumed was the cause of the problem ha.

Please see below for the long list of packages...

`Package                       Version
----------------------------- -----------
aiohttp                       3.7.4.post0
alabaster                     0.7.12
anyio                         3.1.0
appdirs                       1.4.4
argon2-cffi                   20.1.0
asciitree                     0.3.3
asttokens                     2.0.5
async-generator               1.10
async-timeout                 3.0.1
atomicwrites                  1.4.0
attrs                         21.2.0
Babel                         2.9.1
backcall                      0.2.0
black                         21.11b1
bleach                        3.3.0
cachetools                    4.2.2
cachey                        0.2.1
certifi                       2021.5.30
cffi                          1.14.5
chardet                       4.0.0
click                         8.0.1
cloudpickle                   1.6.0
codetiming                    1.3.0
colorama                      0.4.4
commonmark                    0.9.1
cycler                        0.10.0
dask                          2021.6.0
dask-image                    0.6.0
decorator                     4.4.2
defusedxml                    0.7.1
dnspython                     2.1.0
docstring-parser              0.8.1
docutils                      0.17.1
entrypoints                   0.3
executing                     0.7.0
fasteners                     0.16.2
freetype-py                   2.2.0
fsspec                        2021.11.0
gcsfs                         2021.11.0
google-api-core               1.30.0
google-auth                   1.31.0
google-auth-oauthlib          0.4.4
google-cloud-core             1.6.0
google-cloud-secret-manager   2.5.0
google-cloud-storage          1.38.0
google-crc32c                 1.1.2
google-resumable-media        1.3.0
googleapis-common-protos      1.53.0
greenlet                      1.1.0
grpc-google-iam-v1            0.12.3
grpcio                        1.38.0
HeapDict                      1.0.1
icecream                      2.1.1
idna                          2.10
imageio                       2.9.0
imagesize                     1.2.0
iniconfig                     1.1.1
ipykernel                     5.5.5
ipython                       7.24.1
ipython-genutils              0.2.0
ipywidgets                    7.6.3
jedi                          0.18.0
Jinja2                        2.11.3
jsonschema                    3.2.0
jupyter-client                6.1.12
jupyter-core                  4.7.1
jupyter-server                1.8.0
jupyter-server-proxy          3.0.2
jupyterlab-pygments           0.1.2
jupyterlab-widgets            1.0.0
kiwisolver                    1.3.1
libcst                        0.3.19
locket                        0.2.1
magicgui                      0.3.4
MarkupSafe                    2.0.1
matplotlib                    3.4.2
matplotlib-inline             0.1.2
mistune                       0.8.4
multidict                     5.1.0
mypy-extensions               0.4.3
napari                        0.4.12
napari-console                0.0.4
napari-plugin-engine          0.1.9
napari-svg                    0.1.5
nbclient                      0.5.3
nbconvert                     6.0.7
nbformat                      5.1.3
nest-asyncio                  1.5.1
networkx                      2.5.1
notebook                      6.4.0
numcodecs                     0.7.3
numpy                         1.20.3
numpydoc                      1.1.0
oauthlib                      3.1.1
opencv-python-headless        4.5.2.54
packaging                     20.9
pandas                        1.2.4
pandocfilters                 1.4.3
parso                         0.8.2
partd                         1.2.0
pathspec                      0.9.0
pep517                        0.12.0
pickleshare                   0.7.5
Pillow                        8.2.0
PIMS                          0.5
Pint                          0.17
pip                           22.0.4
pip-tools                     6.5.1
platformdirs                  2.4.0
plotly                        4.14.3
pluggy                        1.0.0
prettytable                   2.2.0
prometheus-client             0.11.0
prompt-toolkit                3.0.18
proto-plus                    1.18.1
protobuf                      3.17.3
psutil                        5.8.0
psygnal                       0.2.0
py                            1.11.0
pyasn1                        0.4.8
pyasn1-modules                0.2.8
pycparser                     2.20
pydantic                      1.8.2
Pygments                      2.9.0
pymongo                       4.0.1
PyMySQL                       1.0.2
PyOpenGL                      3.1.5
pyparsing                     2.4.7
PyQt5                         5.15.4
PyQt5-Qt5                     5.15.2
PyQt5-sip                     12.9.0
pyqtgraph                     0.12.2
pyrsistent                    0.17.3
pytest                        6.2.5
pytest-qt                     4.0.2
python-dateutil               2.8.1
pytz                          2021.1
PyWavelets                    1.1.1
pywin32                       302
pywinpty                      1.1.6
PyYAML                        5.4.1
pyzmq                         22.1.0
qtconsole                     5.1.0
QtPy                          1.9.0
regex                         2021.11.10
requests                      2.25.1
requests-oauthlib             1.3.0
retrying                      1.3.3
rich                          10.9.0
rsa                           4.7.2
scikit-image                  0.18.0
scipy                         1.6.3
Send2Trash                    1.5.0
setuptools                    56.0.0
simpervisor                   0.4
SimpleITK                     2.0.2
six                           1.16.0
slicerator                    1.0.0
sniffio                       1.2.0
snowballstemmer               2.1.0
Sphinx                        4.0.2
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
SQLAlchemy                    1.4.18
star-utilities                1.0.5
superqt                       0.2.5.post1
tcping                        0.1.1rc1
terminado                     0.10.1
testpath                      0.5.0
tifffile                      2021.6.6
toml                          0.10.2
tomli                         1.2.2
toolz                         0.11.1
tornado                       6.1
tqdm                          4.61.0
traitlets                     5.0.5
tulsa                         1.5.3
typing-extensions             3.10.0.0
typing-inspect                0.7.1
urllib3                       1.26.5
vispy                         0.6.6
wcwidth                       0.2.5
webencodings                  0.5.1
websocket-client              1.1.0
websockify                    0.9.0
wheel                         0.37.1
widgetsnbextension            3.5.1
wrapt                         1.12.1
yarl                          1.6.3
zarr                          2.8.3
zarrutil                      0.2.8`

**Comment by tlambert03** [comment]
thanks for the env info!

>  but then that instance is missing all the features we added to the program, which I assumed was the cause of the problem ha.

can you tell me how you're starting napari then?  is it a custom script? something other than running `napari` on the command line or just creating a viewer in ipython, eg.  Any particular imports there that might be involved?

**Comment by lukasvasadi** [comment]
Yes! I have a launch script that creates an instance of a custom Controller object. Inside that object we instantiate a Viewer object—this is also where we start modifying some of the GUI. Then we run `napari.run()` at the end of the launch script. Please see below...

```
import napari
import logging

from controller import Controller


if __name__ == "__main__":
    logging.basicConfig(level=logging.CRITICAL)

    # execute main application loop
    well_controller = Controller(version="1.5.2")
    napari.run()
```

**Comment by lukasvasadi** [comment]
The reason I suspected this may be due to a change in Napari was that this logging output only started appearing after a recent upgrade of the Napari package, and all other packages were kept at their current version.

**Comment by tlambert03** [comment]
we certainly can't rule it out!  but I can't think of anything that changed recently specifically related to logging verbosity.  So, need to dig a bit deeper.  Thanks for the script!  will try to reproduce

**Comment by tlambert03** [comment]
ok, I don't see `controller` in your pip list above, and when I tried `pip install controller` I get an object that lacks `version` param:
```
TypeError: Controller() got an unexpected keyword argument 'version'
```

so ... need more information.  What is `controller` and what version do you have

**Comment by tlambert03** [comment]
(and, if you don't import controller, do you still get the verbose loggin?)

**Comment by lukasvasadi** [comment]
Sorry, controller is a local script that we import. However, if I run the script below, I still see the verbose logging.

```
import napari
import logging

from controller import Controller


if __name__ == "__main__":
    logging.basicConfig(level=logging.CRITICAL)

    # execute main application loop
    # well_controller = Controller(version="1.5.2")
    viewer = napari.Viewer()
    napari.run()
```

**Comment by tlambert03** [comment]
yes, but do you see it if you comment out `from controller import Controller`?

*edit*: if not, then I'd need to see what's in the controller module

**Comment by lukasvasadi** [comment]
No, if that is commented out then the verbose logging stops. So that means it must be related to another package?

**Comment by tlambert03** [comment]
It at least means there's an interaction somehow.  The fact that it didn't happen on an earlier version of napari is interesting, but without knowing more about the source of the chatter it's hard to say why

**Comment by tlambert03** [comment]
We can absolutely continue this conversation here, but since the actually logging is coming from outside of napari, I'm going to close this as I'm not sure there's too much we can do besides help guide you in discovering and suppressing the source of the logging.  Free free to share more of your `controller` module if you'd like some help

**Comment by lukasvasadi** [comment]
Thanks for your help @tlambert03! I have no issue sharing my code, but it is also a massive project. I will try to first hunt down the module responsible 🙂
