### ISSUE TITLE
Data Sync/Binding

### ISSUE THREAD

**Issue by AhmetCanSolak** [napari/napari#43]
> I havn't addressed any of the event handling / linking of gui / object properties. Nor have I addressed any of the image specific properties of the layers / support for marker layers.
> 
I believe this is important to discuss so I will be converting an issue out of it.

_Originally posted by @AhmetCanSolak in https://github.com/Napari/napari-gui/pull/41/comment#issuecomment-436432488_

**Comment by sofroniewn** [comment]
Closed by #155
