### ISSUE TITLE
Top google result for `napari points layer` gives a 404

### ISSUE THREAD

**Issue by ianhi** [napari/napari#4302]
## 📚 Documentation

When I google `napari points layer` (even in incognito mode) the top result is:
https://napari.org/docs/dev/_modules/napari/layers/points/points.html

![image](https://user-images.githubusercontent.com/10111092/159735267-d204a791-7671-43e8-8255-498289c94d9c.png)

which leads to a 404 page:
![image](https://user-images.githubusercontent.com/10111092/159735347-9f3896de-6182-4e88-a536-8db40082ee24.png)

It would be great to set up some redirects so this doesn't happen

**Comment by tdimino** [comment]
We can also request that [Google reindex this 404 URL](https://support.google.com/webmasters/answer/9012289#request_indexing), speeding up their update of this search query.

**Comment by psobolewskiPhD** [comment]
This is no longer the case. The changes to docs building have propagated:
<img width="1202" alt="image" src="https://user-images.githubusercontent.com/76622105/197409576-d0443f8b-7049-4181-a759-87cbc0f85778.png">
