### ISSUE TITLE
Drop meshzoo ?

### ISSUE THREAD

**Issue by Carreau** [napari/napari#4324]
This is more a question than a task, but it looks like most of the recent failure are from meshzoo, 
As far as I can tell the author have deleted all version but the most recent one, the source code from github is [gone but for a readme](https://github.com/meshpro/meshzoo), and it seem now to be deployed from private.

Now this might have been a mistake, but as this is used only in examples, I think it is safe to remove. My main problem is removal of all previous version and source code is concerning and eroding my trust in the package.

**Comment by kevinyamauchi** [comment]
I am open to dropping meshzoo. We would have to update our surface layer examples:

- [examples/clipping_planes_interactive.py](https://github.com/napari/napari/blob/c9360dc3e5741e57b1b7e00d245273cd3d7b95de/examples/clipping_planes_interactive.py)
- [examples/spheres.py](https://github.com/napari/napari/blob/c9360dc3e5741e57b1b7e00d245273cd3d7b95de/examples/spheres.py)

I'm not sure we need the spheres example (it just shows to spheres).  For the clipping planes, maybe we can swap to using the brain mesh from `nilearn` we use in the [surface_timeseries.py](https://github.com/napari/napari/blob/main/examples/surface_timeseries.py) example. Thoughts, @brisvag ?

**Comment by brisvag** [comment]
Yup, I used meshzoo just for convenience. Anything else would do! And the two spheres example was created only to test surface depth setting, so it could be removed.

**Comment by Czaki** [comment]
I vote for remove it

**Comment by perlman** [comment]
+1 to removing mesh zoo.

This is currently the only library I am unable to install on macOS arm64 with `pip install -e ".[all]"`, ultimately due to [`x21`](https://pypi.org/project/x21/) and  [`kgt`](https://pypi.org/project/kgt/) being a binary-only dependency of mesh zoo. [Edit: It is not clear why either of these binary packages are even required...]

Thanks for pointing me to this issue @psobolewskiPhD !

**Comment by perlman** [comment]
I was able to download and install [0.9.4 from a github tag](https://github.com/meshpro/meshzoo/tags), but that is not a proper solution.

**Comment by perlman** [comment]
Closed in #4620.
