### ISSUE TITLE
Cannot render ellipse orthogonal to current volume on N>3 dimension.

### ISSUE THREAD

**Issue by Carreau** [napari/napari#4326]
## 🐛 Bug

Here is mvp

```
import napari
import numpy as np

# Create rectangles in 4D
shapes_data = np.array(
    [
        [
            [ -1, -1, 1, 0],
            [ 0 , -1, 1, 0],
            [ 0 ,  0, 1, 0],
            [ -1,  0, 1, 0],
        ],
    ]
)

# add an empty 4d points layer
viewer = napari.view_points(ndim=4, size=3)
viewer.axes.visible = True
points_layer = viewer.layers[0]

# add the shapes layer to the viewer
shapes_layer = viewer.add_shapes(
    shapes_data,
    shape_type='ellipse',
    ndim = 4,
)


viewer.dims.ndisplay = 3
napari.run()
```

leads to 

```
  File "/Users/bussonniermatthias/dev/napari/napari/layers/shapes/_shapes_models/ellipse.py", line 86, in _update_displayed_data
    vertices, triangles = triangulate_ellipse(self.data_displayed)
  File "/Users/bussonniermatthias/dev/napari/napari/layers/shapes/_shapes_utils.py", line 512, in triangulate_ellipse
    vertices = vertices + center
ValueError: operands could not be broadcast together with shapes (101,2) (3,)
```

Reason being that `triangulate_ellipse` in `_shape_utils` try to determine the transform to get the ellipse wrt the current base. And get it back to 2D coord to make an ellipse (x*cos(thetha),y*sin(theta))...

If it can't find the transform it fallback to identity (`eye()`)  transform:
https://github.com/napari/napari/blob/1ba738c36d7ac0faf9bc7b5e8a2228cd93e656f2/napari/layers/shapes/_shapes_utils.py#L499

This is 
1) I believe non-sensical. Well I guess if you are in 2D, that give you a 2D identity matrix, 
but in NxD you need a Nx2 matrix, not an N*N matrix as you are mapping from ND to 2D. 
2) This transformed eye matrix is not used anyway as it's computed only if `len_vec <=0` and used only if `len_vec > 0`. 
3) fail on 3D, as you try to add center (3D) with vertices, (2D, as the transform matrix was not applied). 

I'm not sure how to fix it, as there is technically nothing to triangulate. With current projection the "ellipse", intersection with the current 3D space is a line, so there is nothing to return anyway. And my brain consistency is like mashed potato enough after trying to understand what was happening that I will for now stop at writing this description that I hope will make sens.

**Comment by Carreau** [comment]
This is related to #4289 , maybe #4262 though this one should have been fixed, and to #4258

**Comment by Carreau** [comment]
Ellipse code seem to be completely wrong in 3D


Modifying examples/add_points_on_nD_shapes.py to create ellipses, and plot the 3d points, 
```
"""Add points on nD shapes in 3D using a mouse callback"""
import napari
import numpy as np

# Create rectangles in 4D
data = [
        [
            [0, 50, 75, 75],
            [0, 50, 125, 75],
            [0, 100, 125, 125],
            [0, 100, 75, 125]
        ],
        [
            [0, 10, 75, 75],
            [0, 10, 125, 75],
            [0, 40, 125, 125],
            [0, 40, 75, 125]
        ],
        [
            [1, 100, 75, 75],
            [1, 100, 125, 75],
            [1, 50, 125, 125],
            [1, 50, 75, 125]
        ]
    ]

shapes_data = np.array(
    data
)

# add an empty 4d points layer
viewer = napari.view_points(ndim=4, size=3)
points_layer = viewer.layers[0]

# add the shapes layer to the viewer
features = {'index': [0, 1, 2]}
shapes_layer = viewer.add_shapes(
    shapes_data,
    face_color=['magenta', 'green', 'blue'],
    edge_color='white',
    blending='additive',
    features=features,
    text='index',
    shape_type='ellipse'
)

for d in data:
    viewer.add_points(np.array(d))
# set the viewer to 3D rendering mode with the first two rectangles in view
viewer.dims.ndisplay = 3
viewer.dims.set_point(axis=0, value=0)
viewer.camera.angles = (70, 30, 150)
viewer.camera.zoom = 2.5
napari.run()

```

I get completely non-sensical visualisation, the ellipses drawn are always on a plan.

https://user-images.githubusercontent.com/335567/160586984-e99d1c50-260e-41fd-9ad6-ba886e65d969.mov

**Comment by andy-sweet** [comment]
@Carreau : did #4330 fix this? The first example doesn't raise an error on `main` now, but it looks like the second example has not changed.

**Comment by Carreau** [comment]
the second example is fine now, the dots are at the corner of the ellipse.

**Comment by Carreau** [comment]
Thanks for flagin this was fixed.
