### ISSUE TITLE
napari.utils.progress.update(n) misses default parameter value

### ISSUE THREAD

**Issue by aeisenbarth** [napari/napari#4332]
## 🐛 Bug

Instead of an indeterminate progress bar (total=0), I tried to use tqdm's dask callback to get detailed progress for a dask computation (see also https://github.com/napari/napari/issues/3418). This should work since `napari.utils.progress` is a subclass of `tqdm` and [`TqdmCallback`](https://tqdm.github.io/docs/dask/) takes any tqdm class. However it failed because Napari's [`update(n)`](https://github.com/napari/napari/blob/978dd9e8108a3cd243c2266013eed4b3d2a604fc/napari/utils/progress.py#L115) cannot be called without argument as tqdm's [`update(n=1)`](https://github.com/tqdm/tqdm/blob/165a23a31c746447707bb1ec6417776e9fd06140/tqdm/std.py#L1212).

## To Reproduce

```python
import dask.array as da
from napari.utils import progress
import numpy as np
from tqdm.dask import TqdmCallback

with TqdmCallback(tqdm_class=progress, desc="description"):
    array0 = da.from_array(np.random.random((10, 10)))
    array1 = array0 * 1.0
    array1.compute()
```

## Expected behavior

Napari progress should fully implement tqdm.

## Environment

 - Please copy and paste the information at napari info option in help menubar here:
    napari: 0.4.14
    Platform: Linux-5.4.0-105-generic-x86_64-with-glibc2.17
    System: Ubuntu 20.04.4 LTS
    Python: 3.8.10 (default, Jun 4 2021, 15:09:15) [GCC 7.5.0]
    Qt: 5.15.2
    PyQt5: 5.15.6
    NumPy: 1.21.5
    SciPy: 1.7.3
    Dask: 2021.06.2
    VisPy: 0.9.4

    OpenGL:
    - GL version: 4.6.0 NVIDIA 470.103.01
    - MAX_TEXTURE_SIZE: 16384

    Screens:
    - screen 1: resolution 1920x1200, scale 1.0
    - screen 2: resolution 1920x1200, scale 1.0

    Plugins:
    - console: 0.0.4
    - scikit-image: 0.4.14
    - svg: 0.1.5

 - Any other relevant information:
   - tqdm: 4.62.3
   - dask: 2021.6.2

**Comment by aeisenbarth** [comment]
There is more work necessary to make the progress bar work with dask. 

Napari can only instantiate `progress` in the GUI thread (not inside a `thread_worker`), but `TqdmCallback` wants to instantiate `tqdm` (or `progress`) on its own. This means `TqdmCallback` currently cannot be used in a `thread_worker`. 

So we either use threading (but no determinate progress bar for dask), or we use the dask progress without threading and get an unresponsive UI.

**Comment by imfog** [comment]
***@***.***。上线后，我将认真审核您的来信，尽快给您回复，谢谢你的支持。请继续关注www.v5cg.com！
