### ISSUE TITLE
File > Open File(s) error when reading tif files

### ISSUE THREAD

**Issue by chili-chiu** [napari/napari#4337]
## To Reproduce

1. File > Open Sample > napari > Cell
2. File > Save Selected Layer(s) > save as test.tif file
3. File > Open File(s) > select test.tif --> AttributeError: 'NapariPluginManager' object has no attribute 'ext_map'

The same file can be opened by File > Open Files as Stack.

## Expected behavior
tif file should be able to open using File > Open File(s) option.

## Environment

 - Please copy and paste the information at napari info option in help menubar here:
napari: 0.4.15
Platform: macOS-12.3-x86_64-i386-64bit
System: MacOS 12.3
Python: 3.9.12 | packaged by conda-forge | (main, Mar 24 2022, 23:27:05) [Clang 12.0.1 ]
Qt: 5.15.2
PyQt5: 5.15.6
NumPy: 1.22.3
SciPy: 1.8.0
Dask: 2022.03.0
VisPy: 0.9.6

OpenGL:
- GL version: 2.1 ATI-4.8.13
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1792x1120, scale 2.0

Plugins:
- clEsperanto: 0.16.0
- console: 0.0.4
- napari-assistant: 0.1.6
- napari-segment-blobs-and-things-with-membranes: 0.2.21
- napari-time-slicer: 0.4.3
- napari_skimage_regionprops1: 0.3.2
- napari_skimage_regionprops2: 0.3.2
- scikit-image: 0.4.15
- svg: 0.1.6

 - Any other relevant information:
No reader plugins are installed.

@Czaki

**Comment by nclack** [comment]
@chili-chiu I'm having trouble reproducing this one. Does this still happen for you?

**Comment by nclack** [comment]
@chili-chiu I'm going to go ahead and close this. Please reopen if you see it happen again!
