### ISSUE TITLE
Update npe1 to depend on npe2 and warn if it finds plugins that are npe2-only and require newer napari

### ISSUE THREAD

**Issue by jni** [napari/napari#4340]
## 🧰 Task

We had a [discussion on Zulip](https://napari.zulipchat.com/#narrow/stream/309872-plugins/topic/.E2.9C.94.20Minimum.20napari.20version.20for.20npe2.20plugins.3F/near/275792747) and I've encountered this helping other users too. When a user has an older napari version (e.g. 0.4.12), npe2 plugins are never discovered, even if installed manually. This leads to user confusion as they have followed the plugin creation guide to the letter but their plugins don't appear.

Potentially we can just wait, as fewer and fewer people will be on older napari versions, *but*, this might be worth fixing anyway, as it's probably not too much effort.

My idea for the fix is as follows: npe1 version doesn't have an upper cap in older napari, so if we update npe1, older napari will still pull the newer version. So we update npe1 to depend on npe2, and then we run the npe2 plugin discovery, and we warn for any plugin we find that is npe2 only if napari is less than (I think) 0.4.14.

We can also decide to let the problem fade away, or just put a big warning in the "my first plugin" docs that you *must* have napari>some version.

**Comment by tlambert03** [comment]
Do we need this issue open as well since we have an npe1 issue for it?

**Comment by jni** [comment]
Oh, I missed you opening the npe1 issue @tlambert03, sorry about that! You're right, closing this as duplicate.
