### ISSUE TITLE
Middle-slice rendering vs. data reduction (max project)

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari/napari#4350]
## 🐛 Bug

By default, stacks are loaded at the middle slice.
https://github.com/napari/napari/issues/3559
This is nice, because you're more likely to see something.
But, this can be very confusing if you then do some data reduction, like a (max) projection.
The (max) projection will be at the first slice only, while the view will still show the middle slice, so the new layer will be blank, with a blank thumbnail. This makes it seem like the projection didn't work. Worse yet, if you delete the stack, then there doesn't appear to be a way to recover the actual projection.

## To Reproduce

1. Open sample napari blobs 3D
2. Right click the layer and make a projection, such as max.
3. Note nothing appears to happen.
4. Delete the original image (the stack)
5. Note that the projection is now lost—neither changing colormaps nor contrast settings brings it back

## Expected behavior

When adding a layer that is a data reduction (such as a projection) it would be most intuitive to then show it, so alter the stack position to a new center slice (or the single single slice in the case of a projection).

## Environment

```
napari: 0.4.15
Platform: macOS-12.2.1-arm64-arm-64bit
System: MacOS 12.2.1
Python: 3.9.10 | packaged by conda-forge | (main, Feb 1 2022, 21:27:43) [Clang 11.1.0 ]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.21.5
SciPy: 1.8.0
Dask: 2022.02.0
VisPy: 0.9.6

OpenGL:
- GL version: 2.1 Metal - 76.3
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1680x1050, scale 2.0

Plugins:
- aicsimageio-in-memory: 0.6.1
- aicsimageio-out-of-memory: 0.6.1
- clEsperanto: 0.16.0
- console: 0.0.4
- napari-assistant: 0.1.7
- napari-ome-zarr: 0.4.0
- napari-time-slicer: 0.4.3
- napari-tools-menu: 0.1.10
- napari_skimage_regionprops1: 0.4.0
- napari_skimage_regionprops2: 0.4.0
- natari: 0.2.7
- ome-types: 0.2.9
- scikit-image: 0.4.15
- svg: 0.1.6
```

## Additional context

This first came up with this plugin https://github.com/jdeschamps/napari-sklearn-decomposition where a stack of images is decomposed into, for example, PCA and it seemed like it didn't work.
There adding `viewer.dims.set_point(0, 0)` to get to the first slice of the new stack was an easy solution. Perhaps something similar can be done for the right-click mage projection?

**Comment by psobolewskiPhD** [comment]
I see that this is the effect of:
https://github.com/napari/napari/issues/3803
and https://github.com/napari/napari/pull/3859
I can understand that making a points layer triggering re-centering would be annoying. But, I think recentering would be expected by the user upon making a new image layer.

**Comment by jni** [comment]
Thanks for the issue and the attempted fix, @psobolewskiPhD!

I'll comment more specifically about the fix on the PR, but the issue is pretty major, thank you for raising it. I think there are two problems that need fixing separately:

1: the max-projected image should be broadcast over the existing image. We do this if the max-projected image has one less dimension, but we *don't* do it if it has the same dimension but it is a singleton. I do wonder if we should broadcast singleton dimensions by default, rather than consider them single slices in 3D space. @sofroniewn? The long term solution here is to correctly map axes to dims according to axis labels, and then remove the singleton axis.
2: removing the original image should correctly snap back to the max-projected image. This one seems like lower-hanging fruit to me.

**Comment by psobolewskiPhD** [comment]
Splitting the issue makes sense. 
The max project was just me trying to make an easy example of the unintuitive behavior I observed when opening a new image with reduced data (nr of slices < original/2).
I posted this in the PR but I'll duplicate here:
>I've been tripped up so many times by the behavior, but only recently realized what was happening: there was nothing wrong with my images, they simply were not displayed because all images/stacks share the same slider—and it's linked—even if different lengths. This is super when say two layers share z/t-axis info, but pretty annoying otherwise, which happens to be common for me:
Typically a control has 60 images from the same well, while a sample is a subset of the well area, so it may just have 5-12 images. So if I open the 60-stack first, then the smaller stack, it appears like nothing was loaded—even the thumbnail is empty.

2D images like projections just really easily trigger the problem because then nr of slices = 1, which will be < original/2 whenever original is >2.

Edit: Here's an example:
```
import numpy as np
image_60 = np.zeros((60, 10, 10))
viewer.add_image(image_60)
image_10 = np.ones((10, 10, 10))
viewer.add_image(image_10)
```
On live this shows nothing on screen and nothing in the thumbnail. To me this makes it seem like the image is empty or something failed to open, which is not the case, it's just the linked slider interaction with the exceeded 0-axis.
Edit2: BTW in this example deleting the sub-layer works, because I guess as long as the other image layers have a slider stays and dims are properly reset.

**Comment by jni** [comment]
> On live this shows nothing on screen and nothing in the thumbnail. To me this makes it seem like the image is empty or something failed to open, which is not the case, it's just the linked slider interaction with the exceeded 0-axis.

You're right that this is confusing, but in my opinion this is exactly correct behaviour... Perhaps something like an n-dimensional minimap might be the right approach here... (ie have some kind of indicator that there's more data in that bit of the slider...)

> BTW in this example deleting the sub-layer works, because I guess as long as the other image layers have a slider stays and dims are properly reset.

Makes sense!

**Comment by brisvag** [comment]
> n-dimensional minimap

This is my new favorite thing.

**Comment by psobolewskiPhD** [comment]
> 1: the max-projected image should be broadcast over the existing image. We do this if the max-projected image has one less dimension, but we _don't_ do it if it has the same dimension but it is a singleton. I do wonder if we should broadcast singleton dimensions by default, rather than consider them single slices in 3D space. @sofroniewn? The long term solution here is to correctly map axes to dims according to axis labels, and then remove the singleton axis.

I read up on this and played with things a bit more. I tired 3D and 4D stacks (using `binary_blobs(..., n_dim)` and projections were always broken as described above. I never saw broadcasting and deleting the base layer always left a blank image.
I think that if I'm understanding right the broadcasting is how an array with one less dim is stretched to match another array. A projection is inherently a form of reduction, so a z-axis projection results in no z-axis. So broadcasting the projection should essentially put the projection on all of the slices, which would be the expected behavior and not yield black boxes.
After importing numpy, `viewer.add_image(viewer.layers[-1].data.max(axis=0))` does exactly that. And this works for 4D as well and deleting the original stack doesn't glitch the projection. So this should be the behavior to aim for.

Now looking at napari projections, they *don't* do this, they *don't* reduce the number of dims in the output, instead leaving a singleton dimension. Then—rightfully so—napari treats the new layer the same as the old, as a 3D or 4D or whatnot stack. I see in the code that this is because napari uses `keepdims=True` and trying  `viewer.add_image(viewer.layers[-1].data.max(axis=0, keepdims=True))` results in the current napari behavior, which makes the output have that singleton dimension and gives the black box. And when the original stack is deleted, the projection is lost, just the black box remains. So this is the source of both aspects of this issue!

Testing further, I tried changing that argument to `false` in napari `_layer_actions.py`, but that gave errors related to transformations. Looking further, I think the reason napari makes the singleton dims is to make getting the metadata from the original layer work. See here:
https://github.com/napari/napari/blob/60c4a77e16c71fd4757a41aa75f4d6f7b829d4bd/napari/layers/_layer_actions.py#L73 
Commenting this line out makes everything work exactly like the manual case of `.max(axis=0)`. The projection is broadcast properly and deleting the original stack causes no issues.
Importantly, this line 73 is assigning the transformations, etc. of the existing layer to the new layer, the projection: 
```
In [6]: viewer.layers[-1]._get_base_state()
Out[6]: 
{'name': 'test_4d',
 'metadata': {},
 'scale': [1.0, 1.0, 1.0, 1.0],
 'translate': [0.0, 0.0, 0.0, 0.0],
 'rotate': [[1.0, 0.0, 0.0, 0.0],
  [0.0, 1.0, 0.0, 0.0],
  [0.0, 0.0, 1.0, 0.0],
  [0.0, 0.0, 0.0, 1.0]],
 'shear': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 'opacity': 1.0,
 'blending': 'translucent',
 'visible': True,
 'experimental_clipping_planes': []}
``` 
If we reduce the stack while making the projection, as expected, then the just copying the meta data won't work because of the different number of dims. But if we don't use the original meta data and the base stack was transformed, the projection won't match up.
If I'm reading the code right, the right-click projections always/only use the 0-axis? 
So it looks to me like the key to fixing this is properly dropping that extra 0-axis dim from those transforms, so that the projection is also transformed?

**Comment by jni** [comment]
>  So it looks to me like the key to fixing this is properly dropping that extra 0-axis dim from those transforms, so that the projection is also transformed?

@psobolewskiPhD very nice investigation! I actually thought that the main reason for keepdims was our issues with transposing axes, and that the projections would work with other axes than axis=0. Given that it only works with axis=0, I do actually think that it's worth using keepdims=False, and cleaning the metadata. Our transforms have a `set_slice()` method that you could use to slice out the 0th axis from the transform.
