### ISSUE TITLE
Blue text in plugin tracebacks is very low contrast

### ISSUE THREAD

**Issue by dstansby** [napari/napari#4360]
## 🐛 Bug
The dark blue text in error tracebacks from plugin errors is very low contrast against a black background, and therefore really hard to read:

![Screenshot 2022-04-06 at 12 51 54](https://user-images.githubusercontent.com/6197628/161968666-c7fbfd09-76cd-4431-ab1e-7ecdb26e3aec.png)

## To Reproduce

1. Trigger an error in a plugin

## Expected behavior

High contrast text 😄 

## Environment

 - Please copy and paste the information at napari info option in help menubar here:

 - Any other relevant information:

**Comment by psobolewskiPhD** [comment]
Yes, I've definitely struggled with that a bit in Dark mode.
In light mode the Red highlight is also low contrast:
<img width="609" alt="image" src="https://user-images.githubusercontent.com/76622105/162578960-90f57edc-0721-4272-a7dc-4b22e2fc7ec8.png">

**Comment by jni** [comment]
Yeah, I agree this is terrible, in fact I thought I'd raised an issue about it long ago but I can't find it. Thanks for raising @dstansby!
