### ISSUE TITLE
annotate_segmentation_with_text.py example TypeError

### ISSUE THREAD

**Issue by XareniGalindo** [napari/napari#4371]
## 📚 Documentation

Hello, I am trying to run the annotate_segmentation_with_text.py example to know how is working and apply some of their features to my script. However, when I run it I get the next error:

TypeError: add_shapes() got an unexpected keyword argument 'features'

As well. I tried to copy-paste the example from [napari.org ](https://napari.org/tutorials/segmentation/annotate_segmentation.html) but in this case, the text is not displayed. 

In this case, I am very interested in knowing how the text is been displayed in a layer because that is the feature I would like to incorporate into my script. I hope you can help me. Thanks in advance.

**Comment by jni** [comment]
@XareniGalindo it seems you are using the development version of the example but an older version of napari. You can look at the example for different versions of napari by clicking on the "tags" icon next to the path. This will let you choose different branches or tags. You'll get an address like this one:

https://github.com/napari/napari/blob/v0.4.15/examples/annotate_segmentation_with_text.py

So you can replace the `v0.4.15` with your current version.

You should also update your version :wink: , but I just wanted to write the above for future reference, as it's always important to match the version of the examples you're looking at with your version of napari.

The example in the docs seems to be out of date, so I'll leave this issue open as a note to fix it.

**Comment by psobolewskiPhD** [comment]
This was fixed by 
https://github.com/napari/docs/pull/425/files#diff-70d70cf05ab6dac5d954fa3a852af1adfabc237f04bfeb27519e58ade1dcb1c0
