### ISSUE TITLE
frozen when toggle on/off channel, tune opacity etc.

### ISSUE THREAD

**Issue by xwyan1230** [napari/napari#4380]
## 🐛 Bug

I'm not sure if this is my own problem. But it happens repeatedly. My napari could run well, I could change parameters by changing my code beforehand (python), but if I want to change anything manually after the napari window pop up (toggle on/off channel, change opacity, color etc.), there's a high chance that napari will froze and I have to force it to quit. I wonder if there's a system requirement that I'm not compatible with or any ideas to try improve this? 

## To Reproduce

This is how I call napari:

viewer = napari.Viewer()
viewer.add_image(img)
napari.run()

## Expected behavior

Napari stops responding/ freezes after manually adjusting parameters (toggle on/off channel, change opacity, color etc.)
Mouse turns into this rolling circle and never ends (see image).
<img width="714" alt="Screen Shot 2022-04-12 at 12 12 36 PM" src="https://user-images.githubusercontent.com/17604384/163037880-1f342857-9dc1-47f2-8816-36377fd1d515.png">

## Environment

napari: 0.4.12
Platform: Darwin-20.6.0-x86_64-i386-64bit
System: MacOS 11.5.2
Python: 3.7.11 (default, Jul 27 2021, 07:03:16)  [Clang 10.0.0 ]
Qt: 5.12.9
PyQt5: 5.12.3
NumPy: 1.21.2
SciPy: 1.7.1
Dask: 2021.09.1
VisPy: 0.9.2

OpenGL:
  - GL version:  2.1 ATI-4.6.20
  - MAX_TEXTURE_SIZE: 16384

Screens:
  - screen 1: resolution 2560x1440, scale 2.0

Plugins:
  - console: 0.0.4
  - scikit-image: 0.4.12
  - svg: 0.1.5

**Comment by andy-sweet** [comment]
Sorry for the major issues here!

Does your Apple computer have an M1 processor? If so, there's a [long thread on image.sc discussing some issues](https://forum.image.sc/t/issue-with-downloading-napari-on-mac-m1-chip/53961/15) and another [on Zulip](https://napari.zulipchat.com/#narrow/stream/212875-general/topic/Napari.20.26.20Python.20on.20Apple.20M1).

If I understand the comments there correctly and your comfortable installing napari from the command line, then it looks like the following command might create a usable installation: `conda create -y -n napari-env python=3.9 napari`.

If it's not an M1 mac, then this is really bad! Can you provide some more information?
- How did you install napari?
- Are you able to share the data that causes this issue? Or alternatively, share some code that uses some simple synthetic data (e.g. `img = np.random.rand(32, 24)`) that causes a similar issue?

Thanks!

**Comment by psobolewskiPhD** [comment]
i can't see how this could possibly be an M1 Mac.
Python 3.7 isn't supported and Rosetta emulation would report `Metal` for OpenGL.
I think the ATI OpenGL means AMD GPU?
Very puzzling.

**Comment by andy-sweet** [comment]
Thanks for the clarification @psobolewskiPhD ! I don't have an M1 Mac, so I wasn't quite sure what to expect from the report. You're right that ATI probably refers to an AMD GPU which I think were present in some macbooks before the M1.

**Comment by psobolewskiPhD** [comment]
What stands out for me is the quite old (2019) PyQt5 version, and fairly `modern` napari & vispy (and numpy).

**Comment by andy-sweet** [comment]
One guess is that this might be related to installation type and environment. I.e. miniconda vs. anaconda and `pip` vs. `conda` install. Sometimes I've seen old Qt versions bundled with anaconda remain as defaults in a conda environment and cause issues, though usually less severe than this.

@xwyan1230 : if you're able to provide details on exactly how you installed napari, that could be useful. Also, the output of `pip list` and/or `conda list` could be helpful too.

**Comment by xwyan1230** [comment]
Hi @andy-sweet  and @psobolewskiPhD 
Thank you so much for getting back to me!

It is not a M1 Mac, it is an iMac (Retina 5K, 27-inch, 2020 with macOS Big Sur version 11.5.2). It does have a AMD Radeon Pro 5700 XT 16 GB GPU and I guess that's what you guys are referring to?

It is very possible that this could be an installing/environmental thing since the current environment is inherited from an old project that we have been working on and we kind of hesitating/lazy of changing it whenever it is still working :(

I installed napari when setting up the environment using an .yml file that I got from my colleague(conda env create -f env_os_independent.yml). I could try set up a new environment with updated python and pyqt to see if the problem still exists. I wouldn't have enough time today but will update with you guys if you think that is worthwhile a trial!

Here's some relevant info from the .yml file:
channels:
  - defaults
dependencies:
  - python=3.7
  - napari
  - pyqt=5.12.3
  - jupyterlab
  - Jupiter

For the pip list, I attached a file here. I have trouble getting the conda list result and attached what I get here in another file. Hopefully it is useful!
[conda list.txt](https://github.com/napari/napari/files/8857358/conda.list.txt)
[pip list.txt](https://github.com/napari/napari/files/8857359/pip.list.txt)
Let me know if you have any other suggestions or need anything else!
Thank you so much for the help!

**Comment by Czaki** [comment]
It is possible for you to change the python version to a more modern (at least 3.8) and upgrade napari to 0.4.16?

**Comment by andy-sweet** [comment]
If possible, I'd suggest creating a new conda environment from scratch following [the instructions on napari.org](https://github.com/orgs/napari/teams/core-devs). There is [an issue with how that documentation](https://github.com/napari/napari-sphinx-theme/issues/99) is displayed right now, so if you click on the `1. FROM PIP` title that will show the recommended pip install command.

Following the current recommended instructions would look like:

```
conda create -y -n napari-env -c conda-forge python=3.9
conda activate napari-env
python -m pip install "napari[all]"
```

**Comment by psobolewskiPhD** [comment]
Question: what's the advantage of that over the one-liner:
`conda create -y -n napari-env -c conda-forge python=3.9 napari`
if we're already using conda anyways?

**Comment by andy-sweet** [comment]
I don't think there's a big advantage, so either works. Though I guess it will depend on your hardware, OS, and the packages you're installing, right?

I shouldn't have said using `pip` is recommended - it's just what I've been using for a year on a non-M1 mac and haven't run into any serious issues.

**Comment by psobolewskiPhD** [comment]
`pip` works fine for napari on M1 too **if you have pyqt from conda-forge**
I was just wondering why the extra line, here on x86 😄

**Comment by xwyan1230** [comment]
I create a new environment as @andy-sweet suggested, it looks good so far! I will use this new environment to try more things and hopefully it will be good from now on!  Thank you so much for all you guys' input, it has been really helpful!! I will update on this Friday if everything looks good and have this thread closed. Thank you all @psobolewskiPhD @andy-sweet @Czaki !!

**Comment by psobolewskiPhD** [comment]
@xwyan1230 Just wanted to touch base, is everything working for you now? Can we close?

**Comment by xwyan1230** [comment]
Yes! It’s working now! Sorry I probably forgot to update.

Thank you so much!
Xiaowei

From: Peter Sobolewski ***@***.***>
Date: Thursday, May 18, 2023 at 1:32 AM
To: napari/napari ***@***.***>
Cc: Xiaowei Yan ***@***.***>, Mention ***@***.***>
Subject: Re: [napari/napari] frozen when toggle on/off channel, tune opacity etc. (Issue #4380)

@xwyan1230<https://github.com/xwyan1230> Just wanted to touch base, is everything working for you now? Can we close?
