### ISSUE TITLE
Shift-drag or Alt-drag should always open plugin selection dialog

### ISSUE THREAD

**Issue by jni** [napari/napari#4388]
## 🚀 Feature

With #4347 (and maybe previous PRs), whenever multiple plugins can open a particular file, we get a plugin selection dialog when dragging and dropping a file onto the viewer. This dialog allows users to save the file association to preferences. At that point, if the user wants to use a different plugin under some circumstances, they have to wipe the preference. (I think?) It would be good if shift-drag or alt-drag would *always* open the plugin selection dialog, regardless of preferences.

Additionally, this option could correspond to a menu item, e.g. File > Open with Plugin...

CC @DragaDoncila

**Comment by DragaDoncila** [comment]
I'm going to work on this now. Couple of initial thoughts -

- Implementing this for drag&drop should be pretty trivial. Shortcut would be Alt+Drag (or Alt+Shift+Drag for open as stack). 
- Implementing in file menu is going to be annoying because of the whole open file/open folder separation. Might start with a submenu and see how that looks. Long term would love to maybe just have one Open with a dialog where you both select files/folders *and* make these decisions about stacking, plugin, etc.

**Comment by Czaki** [comment]
Why we would like to implement separate positions in the menu for the open files with selected dialog? Why we could not simply add name filters to the standard "Open file" menu position? https://doc.qt.io/qt-6/qfiledialog.html#setNameFilters

**Comment by DragaDoncila** [comment]
@Czaki I'm not sure what you're suggesting here - can you please expand a little on where we would be using `setNameFilters` and for what purpose? I'd love to avoid that submenu if at all possible.

**Comment by Czaki** [comment]
There could be one filter, `All files (*)` for our mechanism of selecting plugins based on preferences and one entry per plugin reader that will be constructed by `reader name (list of supported extensions separated by space)` 

Here sample screenshot from PartSeg:
![obraz](https://user-images.githubusercontent.com/3826210/181842533-b9802211-527d-4dcc-bb2c-5ad5197fa29a.png)

Then when the user clicks open, we could select in base mechanism should be used or if the user selects some filter that determines the given plugin reader based on string comparison.

(PartSeg uses Qt Filedialog, but it also works with native system dialog).

**Comment by DragaDoncila** [comment]
@Czaki yeah I like that - that's partially what I was envisioning when I said "one Open dialog where you select everything". Except for me I think it should also support opening files OR folders, and have a checkbox for stacking.

I think that's a much bigger lift though, as it would involve rewriting our file open dialogs and the plugin dialog, as well as exploration into how to get this all into ideally one dialog (and still keeping the native file browser which iirc is a hard requirement)

**Comment by Czaki** [comment]
The main problem is that adding some checkbox requires to stop using native dialog and switch to qt one what I remember is not preferred option in napari.
