### ISSUE TITLE
Insert a new layer covers all the others, no matter where it is inserted

### ISSUE THREAD

**Issue by cnstt** [napari/napari#4420]
## 🐛 Bug

Insert a new layer covers all the others, no matter where it is inserted.

## To Reproduce

1. Insert a new layer at a given index, see that it covers all other layers

`viewer.layers.insert(insert_index, denoised_im)`

And then I need to insert a dummy layer and remove it again to make this bug disappear.
```
dummy = napari.layers.Layer.create(np.zeros((1, 1, 1)), {'name': 'dummy'}, layer_type='image')
viewer.layers.insert(0, dummy)
viewer.layers.remove(viewer.layers['dummy'])
```

## Expected behavior

The insert method should just work as expected and the viewer should update accordingly.

## Environment

napari: 0.4.15
Platform: Linux-5.17.4-200.fc35.x86_64-x86_64-with-glibc2.34
System: Fedora Linux 35 (Workstation Edition)
Python: 3.10.4 (main, Mar 25 2022, 00:00:00) [GCC 11.2.1 20220127 (Red Hat 11.2.1-9)]
Qt: 5.15.2
PyQt5: 5.15.6
NumPy: 1.21.5
SciPy: 1.8.0
Dask: 2022.04.0
VisPy: 0.9.6

OpenGL:
- GL version: 4.6.0 NVIDIA 510.47.03
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1200, scale 1.0

## Additional context
This bug appears in the context of the development of a new plugin (this logic is triggered in a widget). I have another bug when I want to move layer from one index to another...so these bugs might be related.

**Comment by cnstt** [comment]
Is this a known issue? ping @brisvag ;)

**Comment by brisvag** [comment]
I assumed it was the same underlying issue as #4421; is this happening in a different context (i.e: not withing a callback after insertion)? If so, can you make up an example like in #4421 that shows the behaviour? I cannot reproduce it manually.

**Comment by cnstt** [comment]
I will try to show an example, but this behaviour is happening everywhere in my plugin.

**Comment by cnstt** [comment]
Here the example that triggers the bug:
```
import napari
import numpy as np
v = napari.Viewer()
il = v.add_image(np.random.rand(10, 10), colormap='reds')
il2 = v.add_image(np.random.rand(10, 10), colormap='reds')
data = np.ones((10,10))
im_layer = napari.layers.Layer.create(data, {'name': 'im'}, layer_type='image')
im = v.layers.insert(0, im_layer)
```

**Comment by brisvag** [comment]
Thanks! This looks different from the other issue... I'll take a look :)

**Comment by brisvag** [comment]
Foudn the issue! #4433 should fix it :)

**Comment by cnstt** [comment]
Thanks a lot for the PR!
Indeed it's really surprising that is issue has not been detected before ^^
Maybe it's because I am really digging in the depths of Napari for my plugin :laughing:
