### ISSUE TITLE
Plugin update in bundle does not work

### ISSUE THREAD

**Issue by Czaki** [napari/napari#4427]
## 🐛 Bug

To update the plugin I need to uninstall it and then install it again. Clicking update trigger a processing event but ends without a result

![Zrzut ekranu z 2022-04-26 18-44-25](https://user-images.githubusercontent.com/3826210/165351187-700dfbce-e556-48e2-9750-50b835b7a2d5.png)

## To Reproduce

1. install bundled (new with conda) napari
2. install old version plugin
3. try to update it from GUI 

## Expected behavior

Update should work

## Environment
```
napari: 0.4.15
Platform: Linux-5.13.0-40-generic-x86_64-with-glibc2.34
System: Ubuntu 21.10
Python: 3.9.10 | packaged by conda-forge | (main, Feb 1 2022, 21:24:11) [GCC 9.4.0]
Qt: 5.12.9
PySide2: 5.13.2
NumPy: 1.22.3
SciPy: 1.8.0
Dask: 2022.02.1
VisPy: 0.9.6

OpenGL:
- GL version: 4.6.0 NVIDIA 510.60.02
- MAX_TEXTURE_SIZE: 32768

Screens:
- screen 1: resolution 2560x1440, scale 1.0
- screen 2: resolution 1920x1080, scale 1.0
- screen 3: resolution 1920x1080, scale 1.0

Plugins:
- PartSeg Analysis project reader: 0.14.0
- PartSeg Image reader: 0.14.0
- PartSeg Image tiff writer: 0.14.0
- PartSeg Mask project reader: 0.14.0
- PartSeg Mask project writer: 0.14.0
- PartSeg Masked Tiff reader: 0.14.0
- PartSeg widgets: 0.14.0
- console: 0.0.4
- scikit-image: 0.4.15
- svg: 0.1.5
```

**Comment by sofroniewn** [comment]
@jaimergp @goanpeca have you observed this too? any ideas on a fix?

**Comment by jaimergp** [comment]
Hm, I am curious where 0.1.6 is coming from if `napari-svg` only has [0.1.5](https://anaconda.org/conda-forge/napari-svg/files) on conda-forge?

**Comment by Czaki** [comment]
But has 0.1.6 on pypi.

I also observe same error with PartSeg update after new release land on conda. 

I need to uninstall old one and install new because update does not work.

**Comment by jaimergp** [comment]
I thought the bundle only accepted conda packages at this point, so PyPI updates shouldn't be visible? @goanpeca can you help clarify?

**Comment by jaimergp** [comment]
Ok, nevermind, I see that part of the UI now. It just takes quite a while to show up.

<img width="1091" alt="image" src="https://user-images.githubusercontent.com/2559438/166450844-897f6b66-2f60-4a9d-bdf7-353153b5a258.png">


I can try reproducing now!

**Comment by jaimergp** [comment]
These are the full logs (verbosity=3, lots of noise!) for the update operation.

[issue-4427.osx-arm64.txt](https://github.com/napari/napari/files/8610694/issue-4427.osx-arm64.txt)

You can see the mamba operation is successful. After cleaning up:

```

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.22.1) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


Looking for: ['napari-svg']

Pinned packages:
  - python 3.9.*
  - napari 0.4.15.*

Transaction

  Prefix: /Users/jrodriguez/Library/napari-0.4.15/envs/napari-0.4.15

  Updating specs:

   - napari-svg
   - ca-certificates
   - certifi
   - openssl


  Package      Version  Build           Channel                    Size
─────────────────────────────────────────────────────────────────────────
  Change:
─────────────────────────────────────────────────────────────────────────

  - certifi  2021.10.8  py39h2804cbe_1  installed
  + certifi  2021.10.8  py39h2804cbe_2  conda-forge/osx-arm64     149kB

  Upgrade:
─────────────────────────────────────────────────────────────────────────

  - openssl     1.1.1l  h3422bc3_0      installed
  + openssl     1.1.1n  h90dfc92_0      conda-forge/osx-arm64       2MB

  Summary:

  Change: 1 packages
  Upgrade: 1 packages

  Total download: 2MB

─────────────────────────────────────────────────────────────────────────


Preparing transaction: done
Verifying transaction: done
Executing transaction: done

```

... but napari-svg is not updated after all. I think we either need to use `mamba update napari-svg` OR force an update `mamba install napari-svg=<newversion>`. If we just use `mamba install napari-svg` it will consider it already satisfied because, well, it's indeed installed, but not the last version.


***

However, we shouldn't be seeing this update :/ It's not on conda-forge (yet, I am building the new version as we speak!
