### ISSUE TITLE
Wrong event rendering for LayerList documentation

### ISSUE THREAD

**Issue by Czaki** [napari/napari#4440]
## 📚 Documentation

Documentation of LayerList contains documentation of events, but without the information that the documented entirs are events. 

Events information in LayerList:
![Zrzut ekranu z 2022-04-28 11-36-52](https://user-images.githubusercontent.com/3826210/165724421-851ef99b-5d2d-4b9a-a679-8207f00b3e30.png)

Expected events information (here Evented list)
![Zrzut ekranu z 2022-04-28 11-36-59](https://user-images.githubusercontent.com/3826210/165724444-dea13d4e-8587-451a-a4ae-6c55595a5506.png)

Events of different objects should be rendered in the same way to increase documentation readability.

**Comment by melissawm** [comment]
Thanks @Czaki  - please keep them coming if you notice other problems with the docs!
