### ISSUE TITLE
layerlist and controls now showing before viewer

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#4443]
## 🐛 Bug

the lines added here in #4195:

https://github.com/napari/napari/blob/413488578b4ca22e09c300e194978c1ce6bf6f06/napari/_qt/qt_main_window.py#L882-L884

are now causing the layerlist and controls to appear briefly before being moved into the viewer:

https://user-images.githubusercontent.com/1609449/165848892-4e81231d-f952-4daf-a8ed-cd05c7a47a98.mov

cc @brisvag

**Comment by tlambert03** [comment]
this also means that all tests using make_napari_viewer now flash these two panels

https://user-images.githubusercontent.com/1609449/165849462-8f493631-e72b-4419-8ad1-a82cae115e01.mov

**Comment by sofroniewn** [comment]
oops! Thanks for flagging this - maybe @brisvag can take a look. @goanpeca might be able to help too. We should fix before 0.4.16 cc @jni

**Comment by jni** [comment]
> We should fix before 0.4.16

Absolutely. I've added the milestone so we don't drop that ball.

**Comment by brisvag** [comment]
Oef... I guess it's too fast on my machine for me to notice?

I think this is worse than the alternative (#3624), so at worst we can simply revert the change.

@goanpeca , do you remember what else you tried to solve that problem?

**Comment by ppwadhwa** [comment]
Not sure if this helps---I just did a quick look and I may be missing something, but I tried commenting out `dock_widget.setFloating(True)` and just have `dock_widget.setFloating(False)` being called.  I *think* its still working as expected and doesn't have the dock widget flash separately.


```
# dock_widget.setFloating(True) (remove this line)
dock_widget.setFloating(False)
        ```
