### ISSUE TITLE
Labels-to-Image conversion does not preserve transform

### ISSUE THREAD

**Issue by jwindhager** [napari/napari#4450]
## 🐛 Bug

It seems that the conversion between `Labels` and `Image` loses the transform associated with the layer.

## To Reproduce

1. Add a `Labels` layer to the viewer with `Viewer.add_labels(..., affine=affine)`
2. In the viewer, right-click on the `Labels` layer and `Convert to Image`
3. The transform is lost

## Expected behavior

Upon conversion, the image should re-appear in the same place as the mask was

## Environment

napari: 0.4.16.dev101+g2648c307
Platform: Linux-5.4.0-107-generic-x86_64-with-glibc2.17
System: Ubuntu 20.04.4 LTS
Python: 3.8.13 (default, Mar 28 2022, 11:38:47) [GCC 7.5.0]
Qt: 5.15.2
PyQt5: 5.15.6
NumPy: 1.21.6
SciPy: 1.8.0
Dask: 2022.04.1
VisPy: 0.10.0

OpenGL:
- GL version: 4.6.0 NVIDIA 510.54
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1080, scale 1.0
- screen 2: resolution 1920x1080, scale 1.0

Plugins:
- console: 0.0.4
- scikit-image: 0.4.16.dev101+g2648c307

**Comment by psobolewskiPhD** [comment]
I can confirm this too—it's bidirectional.
Looks like the `_convert` uses `_get_base_state()` which does not include affines:
https://github.com/napari/napari/blob/5cf4b13e6ad76013f32e2c91725783cf6410d353/napari/layers/base/base.py#L781-L803
Is the fix to add affine to this dict or to copy the transforms from first layer to the new one?

**Comment by jni** [comment]
Thanks for opening the PR @psobolewskiPhD! Yes that is the right fix, and getting #4457 in should fix the failing tests there.
