### ISSUE TITLE
Stop installing doc dependencies when running `make docs`?

### ISSUE THREAD

**Issue by dstansby** [napari/napari#4451]
## 🐛 Bug

I was running `make docs` for the first time today, and was surprised that it runs an install command (`pip install -qr docs/requirements.txt`) on my python environment. I would suggest that this is removed - building docs is not something I expect to have a side effect on my current Python environment, and I hastily cancelled operation to stop it interfering with my mainly-conda environment setup.

## To Reproduce

1. Run `make docs` in the root folder

## Expected behavior

None of my installed packages affected by running `make docs`

## Environment

 - Please copy and paste the information at napari info option in help menubar here:

 - Any other relevant information:

**Comment by jni** [comment]
Good points all @dstansby! I'm definitely open to this. I didn't like having docs/requirements.txt anyway since we have a [docs] section in `setup.cfg` already.
