### ISSUE TITLE
napari --plugin-info does not list contributions from npe2 plugins

### ISSUE THREAD

**Issue by jni** [napari/napari#4456]
## 🐛 Bug

As noted by @tlambert03 in #4445, `napari --plugin-info` only lists hookimpl information about old-style napari_plugin_engine plugins, not npe2 plugins.

**Comment by lucyleeow** [comment]
Currently the output for me looks like this:
```
PluginManager for "napari"
(12 hook specs and 1 plugins)
---------------------------------------------
console v0.0.4  
```

Should we now include both the hook specs and npe2 plugin information?

**Comment by tlambert03** [comment]
Yes, but there’s a lot in flux here at the moment,  so it’s not immediately clear how best to do this in a way that won’t change very soon.   See https://github.com/napari/npe2/pull/192 which is doing exactly this for npe2, so the feature is there… but the “merging” with npe1 plugin manager output is the issue

**Comment by lucyleeow** [comment]
Thanks, will leave for now then!
