### ISSUE TITLE
viewer.events.layers_change is not documented and not triggered when layer name changed

### ISSUE THREAD

**Issue by cnstt** [napari/napari#4469]
## 🐛 Bug

viewer.events.layers_change is not documented and not triggered when layer name changed

## To Reproduce

```
import napari
import numpy as np
v = napari.Viewer()
il = v.add_image(np.random.rand(10, 10), colormap='reds')
il2 = v.add_image(np.random.rand(10, 10), colormap='reds')
def change(event):
    print('change')
v.events.layers_change.connect(change)
```

## Expected behavior

The event should be triggered on layer name change.

## Environment

napari: 0.4.15
Platform: Linux-5.17.4-200.fc35.x86_64-x86_64-with-glibc2.33
System: Freedesktop.org 21.08.12 (Flatpak runtime)
Python: 3.9.9 (main, Nov 10 2011, 15:00:00) [GCC 11.2.0]
Qt: 5.15.2
PyQt5: 5.15.6
NumPy: 1.22.3
SciPy: 1.8.0
Dask: 2022.04.1
VisPy: 0.10.0

OpenGL:
- GL version: 4.6.0 NVIDIA 510.47.03
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1200, scale 1.0

Plugins:
- console: 0.0.4
- scikit-image: 0.4.15
- svg: 0.1.6

**Comment by cnstt** [comment]
I found that the layers_change is located in this file : https://github.com/napari/napari/blob/main/napari/components/viewer_model.py
Has anyone an idea about why this event is publicly exposed or what is supposed to do?
(maybe ping @Czaki)

**Comment by Czaki** [comment]
A fast look at code shows that is emitted on these updates triggers some update in rendering. 

The name change is not connected to the function that triggers this event but to some method of the layer list.

https://github.com/napari/napari/blob/main/napari/components/viewer_model.py#L489

Last person touching this part of code is @sofroniewn, but it is only refactored. I do not touch this code earlier. 

I have some ideas about adding tools to force better documentation, but it is a time-consuming task.

**Comment by cnstt** [comment]
Because as of now it is a little bit strange to have it exposed as a public accessible event, but as I showed with my code snippet it is never triggered (layer change, layerlist change, layer name changed...)

**Comment by Czaki** [comment]
It is often triggered. On add layer. On remove layer, on reorder layer, and on this event from layer:

https://github.com/napari/napari/blob/32176714d2852f1c3c0b65d39b7877d27255a404/napari/components/viewer_model.py?rgh-link-date=2022-07-28T16%3A51%3A43Z#L483-L488

I test it on the current main, and its works. 

But I totally agree that the lack of documentation makes it hard to determine why it is added and if there is some regression in API.

**Comment by cnstt** [comment]
Ah my bad, I may have done something wrong in my snippet/testing ^^

**Comment by sofroniewn** [comment]
`layers_change` should just be removed - It used to be used internally, but we did a refactor > 17 months ago that made it no longer used, but there was pressure at the time not to break the API without a more formal deprecation process. To me this is a prime example of how not letting us actually develop as we are in an alpha stage and removing things quickly led to cruft sticking around in the project that should have been dropped (cc @jni). 
 https://github.com/napari/napari/blob/87a263328fd71c8d3fc6252fe8ee2d09056ae776/napari/components/viewer_model.py#L178-L179

My strong preference would now be to formally deprecate the event for the next release and encourage people to use the `viewer.layers.events` instead.

@cnstt is there anything you need from this event that you can't get from those events?

I'd also like to drop the `reset_view` event ASAP too as I don't think we should manually add any events to the viewer model, but we can discuss that elsewhere.

**Comment by cnstt** [comment]
> @cnstt is there anything you need from this event that you can't get from those events?

No I don't use it if I remember correctly. I wanted to use it in the first place, but it didn't work and the lack of documentation made me switch to viewer.layers.event: see an example here https://github.com/deep-finder/napari-deepfinder/blob/d288f4ed9fd2dec6682c98cb861b783ec80197ee/src/napari_deepfinder/_cluster_widget.py#L24

**Comment by sofroniewn** [comment]
`viewer.layers.event` is recommended.

@Czaki can you make a PR to deprecate `viewer.events.layers_change` with a suggestion to use `viewer.layers.event` instead? It would be good to get this in for next release so we can drop for `0.5.0` - cc @jni

**Comment by cnstt** [comment]
Thanks a lot for the fix! :+1:
