### ISSUE TITLE
Alt-text missing for "Dimension slider" example

### ISSUE THREAD

**Issue by melissawm** [napari/napari#4472]
## 📚 Documentation

In the [Dimension sliders section](https://napari.org/tutorials/fundamentals/viewer.html#dimension-sliders) of the viewer tutorial, the alt-text argument of `nbscreenshot` is empty, which is causing a parse error.

Alt-text should be added there - see https://napari.org/tutorials/fundamentals/viewer.html#layer-controls for an example.

**Comment by cnstt** [comment]
I just did a small PR to solve this issue. I hope the new alt text is understandable :)
