### ISSUE TITLE
Image layer should be able to display non-normalised float arrays 

### ISSUE THREAD

**Issue by royerloic** [napari/napari#449]
## 🐛 Bug

Thumbnail display chokes on ndarrays  of dtype float32 that are not normalised,
see stacktrace below...

```
    @thumbnail.setter
    def thumbnail(self, thumbnail):
        if thumbnail.dtype != np.uint8:
            with warnings.catch_warnings():
                warnings.simplefilter("ignore")
                thumbnail = img_as_ubyte(thumbnail)
        self._thumbnail = thumbnail
        self.events.thumbnail()
```

```
  File "/Users/royer/anaconda3/envs/pitl/lib/python3.7/site-packages/napari/layers/base/base.py", line 177, in thumbnail
    thumbnail = img_as_ubyte(thumbnail)
  File "/Users/royer/anaconda3/envs/pitl/lib/python3.7/site-packages/skimage/util/dtype.py", line 486, in img_as_ubyte
    return convert(image, np.uint8, force_copy)
  File "/Users/royer/anaconda3/envs/pitl/lib/python3.7/site-packages/skimage/util/dtype.py", line 255, in convert
    raise ValueError("Images of type float must be between -1 and 1.")
ValueError: Images of type float must be between -1 and 1.
```

## Environment

 - napari Version (e.g., 1.0): 0.1.3
 - OS (e.g., Linux): OSX
 - Python version: 3.7
 - Any other relevant information:

**Comment by jni** [comment]
Yeah that's our (scikit-image's) bad. See https://github.com/scikit-image/scikit-image/issues/3009.

I think @sofroniewn didn't want to stretch the contrast in the thumbnail, so I think the fix here would be:

```python
try:
    thumbnail = img_as_ubyte(thumbnail)
except ValueError:  # out of range, so we rescale
    thumbnail = img_as_ubyte(rescale_intensity(thumbnail))
```

(where `rescale_intensity` is from `skimage.exposure`)

**Comment by jni** [comment]
As noted in #468, this potentially requires further clarification. It might also be that @royerloic needs a more recent skimage version.

**Comment by sofroniewn** [comment]
i am unable to reproduce on my system - given the added tests in #468 this issue is now closed
