### ISSUE TITLE
Future of Dev branch

### ISSUE THREAD

**Issue by AhmetCanSolak** [napari/napari#45]
## ❓ Questions and Help
What do we like to see about `dev` branch in future?
Shall we delete it? Or keep it?
We will be now trying to have feature branches and we might want to try back having a `dev` branch in future? Are we interested in to keep commit history separately? (we already merge all commits in master, fyi)

In my opinion, we can delete it since we have commits in master already. Wondering your thoughts!

**Comment by royerloic** [comment]
Let's delete dev. Anybody object?

**Comment by jni** [comment]
:+1: from me to @royerloic's suggestion

**Comment by sofroniewn** [comment]
+1 from me

**Comment by royerloic** [comment]
@AhmetCanSolak  Please proceed with merging... Thanks!

**Comment by AhmetCanSolak** [comment]
`dev` branch is deleted. 🎊
