### ISSUE TITLE
inverted points depth with `translucent_no_depth` blending

### ISSUE THREAD

**Issue by dagewa** [napari/napari#4526]
## 🐛 Bug

I am not sure what the `translucent_no_depth` blending mode is intended for, but in 3D its behaviour took me by surprise. The apparent ordering of points away from the viewer appears to be inverted when switching between `translucent_no_depth` and `opaque`. Is this expected?

## To Reproduce

1. View some points in 3D
2. Switch between `translucent_no_depth` and `opaque` blending

```python
import numpy as np
import napari

if __name__ == "__main__":

    viewer = napari.Viewer(ndisplay=3)
    points = np.array([[0,0,0], [10,0,0], [20,0,0], [30,0,0], [40,0,0]])
    viewer.add_points(points)
    napari.run()
```

Apologies for the slightly rubbish screen capture:

https://user-images.githubusercontent.com/11502083/168292728-dad10ffc-6cbd-4847-8467-bd9e0d028ce2.mp4

## Expected behavior

The apparent depth of points should not be inverted by changing the blending mode.

## Environment

napari: 0.4.15
Platform: Linux-5.4.0-110-generic-x86_64-with-glibc2.27
System: Ubuntu 18.04.6 LTS
Python: 3.9.10 | packaged by conda-forge | (main, Feb 1 2022, 21:24:11) [GCC 9.4.0]
Qt: 5.12.9
PyQt5: 5.12.3
NumPy: 1.22.2
SciPy: 1.8.0
Dask: 2022.04.0
VisPy: 0.9.6

OpenGL:
- GL version: 3.0 Mesa 20.0.8
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1080, scale 1.0
- screen 2: resolution 1920x1080, scale 1.0

Plugins:
- console: 0.0.4
- scikit-image: 0.4.15
- svg: 0.1.5

**Comment by alisterburt** [comment]
thanks for the report @dagewa !

I think this is expected, just slightly counterintuitive... the order is set by depth when depth checking is enabled, in the absence of depth checking (`translucent_no_depth`) the order is set by draw order instead. In this specific case, draw order is reversed relative to the depth.

I don't think the `translucent_no_depth` blending mode should ever be appropriate/needed for our points layer - maybe we should remove it entirely, what do you think?

cc @brisvag

**Comment by dagewa** [comment]
Thanks @alisterburt! Makes sense. I wonder if this mode has a valid use case in 2D for points? In 3D it is pretty weird - when displayed alongside some shapes and rotated, the effect is bit like a brain-scrambling optical illusion...

**Comment by alisterburt** [comment]
>  I wonder if this mode has a valid use case in 2D for points? 
I can't think of one, maybe @brisvag will chime in with something that's not obvious to me though!

I'm going to close this and open a separate issue for discussing whether or not to keep `translucent_no_depth` for points - cheers!
