### ISSUE TITLE
Centralized place for napari workshop materials

### ISSUE THREAD

**Issue by kevinyamauchi** [napari/napari#4531]
## 📚 Documentation
As discussed with @chili-chiu , @haesleinhuepf , @alisterburt  in #4528 , it would be nice if we had a centralized place to host napari workshop materials. In my mind, this "workshop repository" would have the following characteristics:

- community members can contribute materials freely (e.g., review is to make sure the content fits the scope of the repo and flag any major errors, not for style, etc.)
- each workshop is citable
- each workshop has a license that allows re-use (e.g., [CC-BY](https://creativecommons.org/licenses/by/4.0/))
- somebody giving a workshop would be able to find relevant materials

Some nice-to-haves:
- workshops can be versioned
- workshops can be rendered to a website if they are made with jupyter book / executable books (see @alisterburt and my workshop site [here](https://alisterburt.github.io/napari-workshops/home.html))

Some examples I've found:
- `xarray-contrib` has a tutorials repo: https://github.com/xarray-contrib/xarray-tutorial
- okay, I started this bulleted list before I found a second example, but I'm sure there are others!

As @alisterburt suggested, it might make sense for this all to live in a separate org (e.g., `napari-contrib` or `napari-community`) as it might lower the barrier to making/accepting contributions. I am curious what you all think!

**Comment by chili-chiu** [comment]
Thanks @kevinyamauchi for making this issue. Lowering the contribution barrier and making resources easier to find/reuse would be valuable for the community!

I'm curious what's your thought on what materials would be good to be part of napari.org (under Usage/tutorial, how-to, etc.), versus a separate workshop repo? Should we lower the barrier to contributing to napari.org?

**Comment by melissawm** [comment]
Since we are moving towards a "docs-only" repo (see #4306), we discussed at the Documentation working group today how the workshops could also fit under that repo. That way, all workshop content is also served in the main website, and built automatically with the docs. How does this sound, @kevinyamauchi ?

**Comment by alisterburt** [comment]
@melissawm I think this assumes all of the content will be formatted in the same way which might be setting the 'contribution standard' a little high? It also means that people wanting to contribute workshops would have to deal with a very large repo

I would personally prefer a situation where people in the community who want to run workshops just have to create a repo with their materials, formatted however they want to for their workshop. We could then archive each repository in a `napari-workshops` org.

Something which might be really great for the docs repo would be some sort of 'template' workshop materials which are kept relatively current... this could lower the barrier to running workshops for people in the community

cc @jluethi would something like this have been useful for you when you ran your workshop?

**Comment by jluethi** [comment]
I agree with @alisterburt on this. Just planning another small workshop for tomorrow and workshop templates would indeed be very valuable. Would both make life easier when preparing a new workshop and make the workshop material more similar in structure if people follow the templates. And would make it easier to share content between workshops.

**Comment by alisterburt** [comment]
Thanks for chiming in @jluethi !

@chili-chiu what do you think about this as a path forward? How should we best get started? I would propose making a napari-community org and starting to centralise existing materials

**Comment by jluethi** [comment]
@alisterburt in the meantime, I'd assume this https://github.com/alisterburt/napari-workshops is a good place to start getting workshop inspiration from, right?

I'm just creating a small tutorial to get people up & running with a local napari installation and give them a demo of the napari screenshot & animation functionality.

**Comment by alisterburt** [comment]
@jluethi totally, please feel free to use any and everything which is useful! Good luck with the tutorial :)

**Comment by chili-chiu** [comment]
@alisterburt and @jluethi it's great to see the demand for running workshops and having a way to lower the barrier/reduce the preparation time would be the goal for sure :)

One possibility is to have a separate folder under the napari docs-only repo that requires only minimal review (e.g. content is relevant to napari), and we don't necessarily have to surface it to napari.org (yet) but can do that once it's more mature/stable. 
Essentially, something similar to the examples folder under the napari repo which doesn't go through the same level of the review process as other codes, but is still in the same repo.

Would like to have others in docs WG to chime in @melissawm @jni @DragaDoncila

**Comment by kevinyamauchi** [comment]
Hello everyone! Sorry for the late reply.

> Since we are moving towards a "docs-only" repo (see https://github.com/napari/napari/issues/4306), we discussed at the Documentation working group today how the workshops could also fit under that repo. That way, all workshop content is also served in the main website, and built automatically with the docs. How does this sound, @kevinyamauchi ?

I think this would be great! I think it would be helpful to have some "reference" workshop materials available that are served in the main website and built automatically with the docs. However, as @alisterburt and @chili-chiu suggested, I think it would also to have a "low barrier of entry" route for community contributions.

> One possibility is to have a separate folder under the napari docs-only repo that requires only minimal review (e.g. content is relevant to napari), and we don't necessarily have to surface it to napari.org (yet) but can do that once it's more mature/stable.

I like this suggestion, @chili-chiu ! I think it would be super valuable to have a venue where community members can share and showcase their workshops without having to worry about the formatting, etc. required to make the materials buildable with our docs. Also, I think there might be an additional barrier to contributing something that goes on the main site.

**Comment by alisterburt** [comment]
@chili-chiu I feel relatively strongly that the flow of what you're suggesting

1. user clones docs repo
2. user adds their material (likely from an existing git repo)
3. user submits PR
4. someone approves PR
5. at a later date someone may come and tidy up materials from this workshop so they can be surfaced on napari.org

is a lot of extra work for quite a few people compared to
1. user creates workshop materials, stored in a git repo
2. user notifies us that they've run a workshop after the fact
3. we archive a copy of their repo on some new org account (`napari-workshops` or `napari-community`)

we could optionally add
4. napari.org page which links out to

I think in terms of discoverability people are much more likely to look at individual repos on an org account than subfolders of a workshops folder in a docs repo. Is there a particular reason you don't like this suggested approach and would prefer the subfolder in the docs repo?

**Comment by Czaki** [comment]
If materials contain some Jupyter maybe it will be possible to test it against new releases. Like I test the example notebook for PartSeg with the command:

```bash
jupyter nbconvert --to notebook --execute tutorials/tutorial_neuron_types/Neuron_types_example.ipynb
```

**Comment by alisterburt** [comment]
@Czaki thanks for the tip! That will be great for some example workshop material :)

**Comment by chili-chiu** [comment]
After today's community meeting and also a brief discussion at the docs working group, here's the summary of the possible solution moving forward. @alisterburt and everyone please see if this correctly describes what has been discussed.

Current situation:
The past events/workshops are added to [napari.org](http://napari.org/) > Usage > napari workshops, with links to the materials that are hosted by the content creators. 

Current advantages (that we may want to maintain):
- Very light-weight to contribute
- Low maintenance for the napari team 

Current limitation:
- Not all events/workshops are captured on the napari workshops page (low visibility)
- Materials are not archived thus contents might be lost in the future 

Proposed additions:
- Have a new Github repo (napari-workshops) to serve as a centralized location to archive workshop/event materials
(1) Read-only access for the archiving purpose
(2) If materials are already in the form of a Github repo, fork it to this location
(3) If materials are larger than 25 MB (Github limit), upload them to Zenodo and provide links, then add to this location
(4) Provide clear instructions for (2) and (3) to encourage community contributions
- Better descriptions/visibility for napari workshops page, which can then link to the centralized location
- [longer term] Provide napari workshop cookiecutter to lower the entry barrier for generating basic workshop materials

**Comment by kevinyamauchi** [comment]
Thanks for the nice summary, @chili-chiu ! I am sorry I missed the community meeting - sounds like there was some great discussion.

Quick clarifying question: do we think there can/should be different places for listing what napari events have taken place and for hosting workshop/event materials? Based on [@psobolewskiPhD 's comment on zulip](https://napari.zulipchat.com/#narrow/stream/311822-hackathon/topic/.22official.22.20details/near/287098648), my understanding is that he was looking for some "official" proof that the hackathon he attended was a real professional development event (which I think it was!). 

> Have a new Github repo (napari-workshops) to serve as a centralized location to archive workshop/event materials

I think this is my favored approach since I think it is fairly low maintenance and we don't have to worry about dead links. A few questions/comments:

- I think we should have some "deprecation" policy (e.g., if we get an issue saying that a workshop is broken, we notify the authors and give them 2 months to respond before archiving the repo and removing it from the list).
- Do the original repo contributors get some sort of access to the forked repo so they can maintain it?
- What is our policy with regards to updating materials and repeated workshop. For example, if I give a plugin workshop once per month for three months and make some incremental changes between (e.g., fix some typos, update a screenshot) - do I contribute three separate repos? Personally, I would likely have worked from one repo, but this wouldn't satisfy @psobolewskiPhD's request for an official listing for CV/credit purposes.

> [longer term] Provide napari workshop cookiecutter to lower the entry barrier for generating basic workshop materials

This sounds awesome! I could imagine having prompts for different modules and then the repo gets populated with relevant content. Super cool.

**Comment by psobolewskiPhD** [comment]
Yeah, along what @kevinyamauchi wrote, I think there is room for a listing of past events/workshops/hackathons that have been organized, say in the Community pages? Maybe some why to scrape from the calendar? (assuming those events do go on the calendar)
This would make those events public record and verifiable, in a central location rather than zulip threads. This would both show how active the community is and let someone double check what/when they engaged in an activity plus easily show it to someone/list on CV/website, etc. For some participants, it may be important to document where they spent their time.

At the same time, the idea of a repo or such for the tutorial/training materials plus links to videos, etc. is great! I can see why those would be under usage, since they are additional tutorials, examples, etc. which can be useful for someone self-learning (or thinking of doing some workshops).

**Comment by jluethi** [comment]
> (4) Provide clear instructions for (2) and (3) to encourage community contributions

For community contributions, this documentation of best practices & how to do them would be very useful! For example, I had a [little intro to napari workshop I held at FMI in early June](https://github.com/jluethi/napari-animation-tutorial), but had not figured out a good way to provide example data publicly and if there are instructions for e.g. zenodo already linked at the workshop page, I could use something like this in the future :)

**Comment by kevinyamauchi** [comment]
I haven't had a chance to look yet too closely, but I saw this on twitter and it may be of interest: a repo for community bonej scripts. It looks like there is some automated zendo archiving, but I'm not sure how this works


https://github.com/bonej-org/bonej-scripts

**Comment by jni** [comment]
We discussed this at docs wg and decided to close this as wontfix — the napari workshops page:

https://napari.org/stable/further-resources/napari-workshops.html

and napari workshop template:

https://github.com/napari/napari-workshop-template/

are sufficient for now. We don't think we need to archive everything and can leave individual orgs to manage their materials — if they want to delete them, that is ok, and the linkcheck from napari/docs#474 can alert us to remove non-existent materials.
