### ISSUE TITLE
Shapes Layer: Unable to draw horizontal/verticle line

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari/napari#4538]
## 🐛 Bug

It seems impossible to draw a horizontal or vertical line.
Perhaps related to:
https://github.com/napari/napari/pull/3259

## To Reproduce

1. Open napari
2. Add shapes layer
3. Try to draw a horizontal or tercile line

https://user-images.githubusercontent.com/76622105/168588334-68040e6d-2943-427e-9f92-7c66f644a627.mp4

You can see the line skipping from almost horizontal to the "other side" of horizontal. Same with vertical. I can never just make a flat or vertical line.

I thought maybe using shift would help, but that's actually...worse!
Holding shift when starting to draw yields lines fixed at the SE direction. 
(Pressing shift while drawing locks the current orientation).

https://user-images.githubusercontent.com/76622105/168588558-fee849f8-ce50-4221-bb12-e2daa8771df1.mp4

## Expected behavior

It should be possible to draw lines oriented at the 0°/180° or 90°/270° orientations free-hand.
Also, shift before drawing should "skip" through 45° steps all the way from 0° to 360°.

## Environment

```
napari: 0.4.16rc2.dev17+g0c148bb6
Platform: macOS-12.3.1-arm64-arm-64bit
System: MacOS 12.3.1
Python: 3.9.12 | packaged by conda-forge | (main, Mar 24 2022, 23:25:14) [Clang 12.0.1 ]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.21.5
SciPy: 1.8.0
Dask: 2022.02.0
VisPy: 0.10.0

OpenGL:
- GL version: 2.1 Metal - 76.3
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1680x1050, scale 2.0

Plugins:
- aicsimageio-in-memory: 0.6.1
- aicsimageio-out-of-memory: 0.6.1
- clEsperanto: 0.16.0
- console: 0.0.4
- napari-accelerated-pixel-and-object-classification: 0.6.8
- napari-assistant: 0.1.7
- napari-math: 0.0.1b0
- napari-ome-zarr: 0.4.0
- napari-sklearn-decomposition: 0.0.1
- napari-svg: 0.1.6
- napari-time-slicer: 0.4.3
- napari-tools-menu: 0.1.10
- napari_skimage_regionprops1: 0.4.0
- napari_skimage_regionprops2: 0.4.0
- natari: 0.2.7
- ome-types: 0.2.9
- scikit-image: 0.4.16rc2.dev17+g0c148bb6
- stardist-napari: 2022.4.8
```

**Comment by brisvag** [comment]
Bizarre... I tried diving down, and all I could figure out is that `Shapes._selected_box` at some point becomes "blocked", but I could not find the point where it happens :/

**Comment by dalthviz** [comment]
Hi, not sure but maybe the code related to a threshold definition could be causing the blocked behavior? Seems like that is being defined in the logic that is handling shapes movement/resize at:  https://github.com/napari/napari/blob/a79537cac7c2a595c4fca41b85f2c7b4a44d0a61/napari/layers/shapes/_shapes_mouse_bindings.py#L453-L459

**Comment by jni** [comment]
That video is 🔥 @psobolewskiPhD! 😂 😱 😂
