### ISSUE TITLE
Cannot launch a viewer from VSCode Jupyter extension.

### ISSUE THREAD

**Issue by hanjinliu** [napari/napari#4547]
## 🐛 Bug

`napari` is not working in Jupyter notebook opened in VSCode.
(I remember it used to be OK but I have no idea when it stopped working because I've not been using Jupyter notebook these days.)

## To Reproduce

```python
import napari
viewer = napari.Viewer()
```

<details><summary>error message</summary><div>

```
Validation errors in config file(s).
The following fields have been reset to the default value:

schema_version
  value is not a valid tuple (type=type_error.tuple)

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
c:\Users\liuha\Desktop\Analysis\python_codes\_ipynbs\Untitled1.ipynb Cell 1' in <cell line: 2>()
      1 import napari
----> 2 viewer = napari.Viewer()

File c:\Users\liuha\Anaconda3\envs\mt\lib\site-packages\napari\_lazy.py:47, in install_lazy.<locals>.__getattr__(name)
     45     return import_module(f'{module_name}.{name}')
     46 elif name in attr_to_modules:
---> 47     submod = import_module(f'{module_name}.{attr_to_modules[name]}')
     48     return getattr(submod, name)
     49 else:

File c:\Users\liuha\Anaconda3\envs\mt\lib\importlib\__init__.py:127, in import_module(name, package)
    125             break
    126         level += 1
--> 127 return _bootstrap._gcd_import(name[level:], package, level)

File <frozen importlib._bootstrap>:1030, in _gcd_import(name, package, level)

File <frozen importlib._bootstrap>:1007, in _find_and_load(name, import_)

File <frozen importlib._bootstrap>:986, in _find_and_load_unlocked(name, import_)

File <frozen importlib._bootstrap>:680, in _load_unlocked(spec)

File <frozen importlib._bootstrap_external>:850, in exec_module(self, module)

File <frozen importlib._bootstrap>:228, in _call_with_frames_removed(f, *args, **kwds)

File c:\Users\liuha\Anaconda3\envs\mt\lib\site-packages\napari\viewer.py:8, in <module>
      4 from weakref import WeakSet
      6 import magicgui as mgui
----> 8 from .components.viewer_model import ViewerModel
      9 from .utils import _magicgui, config
     11 if TYPE_CHECKING:
     12     # helpful for IDE support

File c:\Users\liuha\Anaconda3\envs\mt\lib\site-packages\napari\components\__init__.py:19, in <module>
     17 from .camera import Camera
     18 from .dims import Dims
---> 19 from .layerlist import LayerList
     21 # Note that importing _viewer_key_bindings is needed as the Viewer gets
     22 # decorated with keybindings during that process, but it is not directly needed
     23 # by our users and so is deleted below
     24 from . import _viewer_key_bindings  # isort:skip

File c:\Users\liuha\Anaconda3\envs\mt\lib\site-packages\napari\components\layerlist.py:9, in <module>
      5 from typing import TYPE_CHECKING, Iterable, List, Optional, Tuple, Union
      7 import numpy as np
----> 9 from ..layers import Layer
     10 from ..layers.image.image import _ImageBase
     11 from ..utils.context import create_context

File c:\Users\liuha\Anaconda3\envs\mt\lib\site-packages\napari\layers\__init__.py:13, in <module>
     11 from .base import Layer
     12 from .image import Image
---> 13 from .labels import Labels
     14 from .points import Points
     15 from .shapes import Shapes

File c:\Users\liuha\Anaconda3\envs\mt\lib\site-packages\napari\layers\labels\__init__.py:1, in <module>
----> 1 from . import _labels_key_bindings
      2 from .labels import Labels
      4 # Note that importing _labels_key_bindings is needed as the Labels layer gets
      5 # decorated with keybindings during that process, but it is not directly needed
      6 # by our users and so is deleted below

File c:\Users\liuha\Anaconda3\envs\mt\lib\site-packages\napari\layers\labels\_labels_key_bindings.py:6, in <module>
      4 from ...utils.translations import trans
      5 from ._labels_constants import Mode
----> 6 from .labels import Labels
      9 @Labels.bind_key('Space')
     10 def hold_to_pan_zoom(layer: Labels):
     11     """Hold to pan and zoom in the viewer."""

File c:\Users\liuha\Anaconda3\envs\mt\lib\site-packages\napari\layers\labels\labels.py:9, in <module>
      6 import pandas as pd
      7 from scipy import ndimage as ndi
----> 9 from napari.utils.misc import _is_array_type
     11 from ...utils import config
     12 from ...utils._dtype import normalize_dtype

ImportError: cannot import name '_is_array_type' from 'napari.utils.misc' (c:\Users\liuha\Anaconda3\envs\mt\lib\site-packages\napari\utils\misc.py)
```

---
</div></details>

## Environment

 - Please copy and paste the information at napari info option in help menubar here:

napari: 0.4.16rc1
Platform: Windows-10-10.0.22000-SP0
Python: 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)]
Qt: 5.15.2
PyQt5: 5.15.6
NumPy: 1.21.5
SciPy: 1.7.3
Dask: 2021.11.1
VisPy: 0.10.0

OpenGL:
- GL version: 4.6.0 - Build 27.20.100.9621
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1368x912, scale 2.0

Plugins:
- animation: 0.0.2
- console: 0.0.4
- napari-molecule-reader: 0.1.2
- napari-multitask: 0.0.2
- napari-roi: 0.1.3
- napari-svg: 0.1.6
- scikit-image: 0.4.16rc1

 - Any other relevant information:

## Additional context

VSCode Jupyter: v2022.4.1021342353

**Comment by psobolewskiPhD** [comment]
I can't reproduce this in a notebook nor in the python interactive window. Slightly newer version of the Jupyter extension. 
Are you sure you have the right kernel launched, with an env that has napari et al?
I believe the default is what you have selected in the bottom bar of the VS Code window, which may be the last one you used. Once you have a notebook you can check in the top right corner.
Could also be a python version issue? Or maybe:
`pip install -U typing_extensions`

**Comment by hanjinliu** [comment]
Hi @psobolewskiPhD ,
yes, the active kernel is the correct one (I can confirm that the environment I used is correct from the paths in error messages).
Also, updating `typing_extensions` didn't change anything.
I *guess* it's a deeper problem since the error came from `import_module`... maybe importing something using `import_module` with a relative path is broken in certain condition?

**Comment by Czaki** [comment]
This message is most often connected with circular import. But I cannot found it 

@hanjinliu could you install latest develop and verify if problem stills is present?

**Comment by hanjinliu** [comment]
I installed `0.4.16rc2.dev31+g48cdf4d1` but still ran into the same error...

**Comment by Czaki** [comment]
> I installed `0.4.16rc2.dev31+g48cdf4d1` but still ran into the same error...

And if you add the line `from napari.utils.misc import _is_array_type` before import napari? (I cannot reproduce error so need your help)

**Comment by hanjinliu** [comment]
`from napari.utils.misc import _is_array_type` resulted in the same import error.

I also tried 

```python
from napari.utils import misc
misc._is_array_type
```

and I got

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
c:\Users\liuha\Desktop\Analysis\python_codes\_ipynbs\Untitled1.ipynb Cell 5' in <cell line: 2>()
      1 from napari.utils import misc
----> 2 misc._is_array_type

AttributeError: module 'napari.utils.misc' has no attribute '_is_array_type'
```

Next I tried to find why `_is_array_type` was lost.

```python
for k, v in misc.__dict__.items():
    if k.startswith("_"):
        print(k)
```

```
__name__
__doc__
__package__
__loader__
__spec__
__file__
__cached__
__builtins__
_file_hash
_combine_signatures
```
It's weird that other functions like `_file_has` exist but only `_is_array_type` was lost.

**Comment by Czaki** [comment]
could you attach `misc.py` to comment?

**Comment by hanjinliu** [comment]
I finally found the reason why it was happening!
Once I fail to pip-install `napari` because in a program it was still running. After that, the newest `napari` have always been downloaded in the place called `"C:\Users\liuha\AppData\Roaming\Python\Python39\site-packages"` instead of the correct environment for some reasons.
What makes things more confusing is that IPython and VSCode type checker etc. had `"C:\Users\liuha\AppData\Roaming\Python\Python39\site-packages"` in `sys.path` for some reasons so they could import the latest `napari` but Jupyter extension of VSCode did not.
`_is_array_type` could not be imported just because it was not found in early versions of `napari`. 
I have to say this is completely my mistake...
