### ISSUE TITLE
Display total number of slices on right end of corresponding slider

### ISSUE THREAD

**Issue by jni** [napari/napari#456]
## 🚀 Feature

From my colleague @VolkerH who was trying out napari on his (oddly-shaped due to IO issues) data: it would be nice if the max value of each slider was shown e.g. at the right end of that slider, so that you could at a glance tell the shape of your data.

**Comment by sofroniewn** [comment]
@jni @VolkerH, now that we have a QScrollBar, which has a width proportional to the number of steps, do you still think this is as important? If so we can add it after adding the names to the axes in #14

**Comment by VolkerH** [comment]
I still think it would be useful to see the number of frames / z-slices etc. in absolute numbers (rather than based on reltive slider width). But I also realize that there are probably more urgent things.

**Comment by jni** [comment]
I agree with @VolkerH — having actual numbers is helpful, especially once you get to >30 slices or so, when it becomes harder to estimate the actual total value. At least, the total size could appear on hover.

**Comment by sofroniewn** [comment]
@tlambert03 just wanted to draw your attention to this. should be relatively easy to add after #726 goes in if we want, but let's wait till that merges before doing anything here
