### ISSUE TITLE
Layer updates lag on Windows

### ISSUE THREAD

**Issue by jni** [napari/napari#457]
## 🐛 Bug

A fun one! When viewing multiple layers on Windows (or at least @VolkerH's machine), the update of each layer lags. This is very visible when layers are supposed to be the same object but different color tags, as the colors should never be "out of sync". Here is an example:

**Edit:** updated link (made an imgur account, not sure how long ephemeral posts last): https://i.imgur.com/kuadZsn.mp4

## To Reproduce

```python
import numpy as np
from skimage import data
import napari


with napari.gui_qt():
    blobs = np.stack(
        [
            data.binary_blobs(
                length=128, blob_size_fraction=0.05, n_dim=3, volume_fraction=f
            )
            for f in np.linspace(0.05, 0.5, 10)
        ],
        axis=0,
    )
    viewer = napari.Viewer()
    blobs1 = viewer.add_image(blobs.astype(float))
    blobs1.colormap = 'cyan'
    blobs1.blending = 'additive'
    blobs2 = viewer.add_image(blobs.astype(float))
    blobs2.colormap = 'yellow'
    blobs2.blending = 'additive'
```

Then adjust the sliders.

## Expected behavior

The blobs appear always appear white.

## Environment

 - napari Version (e.g., 1.0): 0.1.3
 - OS (e.g., Linux): Windows
 - Python version: 3.7
 - Any other relevant information:

**Comment by VolkerH** [comment]
I can now also provide an animated gif

![napari](https://user-images.githubusercontent.com/2210044/62185958-ca82f080-b3a7-11e9-909d-22279cf57248.gif)

**Comment by sofroniewn** [comment]
Hmm yeah - those layers are separately getting refreshed when you move the slider, so one will get refreshed and then the other one, and if it takes a long time then this will happen. I guess the issue here is that the refresh is taking a long time. I'm curious if you have a sense of how this scales with the size of the 2D array being looked at? my feeling is large arrays will be much worse.

**Comment by jni** [comment]
@sofroniewn well that's only 128x128 so I think size is a secondary concern to some implementation details. It's also curious that it only seems to happen on Windows — I can't reproduce at all on my machine (same gen processor/integrated graphics as @VolkerH's).

We might also be able to fiddle with our event system so that `update()` is only called after all the layers have switched slices.

**Comment by VolkerH** [comment]
Without being familiar with the vispy or the napari code base I just googled whether vispy supports double-buffering and I came across the `autoswap` parameter for the vispy Canvas.

> autoswap bool
> 
>     Whether to swap the buffers automatically after a draw event. Default True. If True, the swap_buffers Canvas method will be called last (by default) by the canvas.draw event handle
r.

Without having looked at the code in detail I am taking a wild guess here, but setting this to False and triggering the redraw after the last layer has been drawn might be a way to address this?

**Comment by jni** [comment]
@sofroniewn just experienced this on Linux now. =\

**Comment by sofroniewn** [comment]
@VolkerH @jni i'm going through some old bug issues and just came across this one. I'm wondering if this is still an issue for you? Judging from the above gif it was first observed on quite an old version of napari!

If so I'm curious how high priority you both see it?

**Comment by liu-ziyang** [comment]
assuming this is addressed in our latest version (I don't recall a similar bug report on this past 0.4), going to close this bug. please feel free to reopen if it happens again!
