### ISSUE TITLE
Napari erroneously downsamples image stack in X/Y on load

### ISSUE THREAD

**Issue by raacampbell** [napari/napari#4576]
## 🐛 Bug

I am using Napari 0.4.15 to overlay two 3D image stacks of the same size. When I do this in Fiji, I can load the stacks separately and merge perfectly. In Napari, however, one of the stacks appears downsampled in X/Y so the two stacks do not overlay.
![Screenshot_20220526_105123](https://user-images.githubusercontent.com/5427811/170464863-60a0ea2f-8dcc-476f-842d-a2951b07e20b.png)

## To Reproduce

1. Download images: https://www.dropbox.com/s/ckaik6jhmseipte/example_not_overlay.tar.gz?dl=1
2. File > Open Files for each image
3. Overlay is incorrect

## Expected behavior
The images should overlap perfectly as they are the same size and the overlap works in Fiji. I have also confirmed that loading the images into Python produces 3-D arrays of the same size.

## Environment

 - Please copy and paste the information at napari info option in help menubar here:
napari: 0.4.15
Platform: Linux-5.13.0-44-generic-x86_64-with-glibc2.31
System: Ubuntu 20.04.4 LTS
Python: 3.9.7 (default, Sep 16 2021, 13:09:58) [GCC 7.5.0]
Qt: 5.15.2
PyQt5: 5.15.6
NumPy: 1.21.6
SciPy: 1.8.0
Dask: 2022.02.0
VisPy: 0.9.6

OpenGL:
- GL version: 4.6.0 NVIDIA 510.73.05
- MAX_TEXTURE_SIZE: 32768

Screens:
- screen 1: resolution 2560x1440, scale 1.0

Plugins:
- OtherView: 0.1.1
- brainglobe-io: 0.1.3
- brainreg-register: 0.0.4rc0
- brainreg-segment: 0.2.14
- brainreg-standard: 0.1.3
- cellfinder: 0.0.18
- cellpose-napari: 0.1.4
- console: 0.0.4
- itk-elastix_napari: 0.1.7
- napari-brightness-contrast: 0.1.7
- napari-demo: 0.1.0
- napari-itk-io: 0.1.0
- napari-tools-menu: 0.1.10
- ndtiffs: 0.1.2
- scikit-image: 0.4.15
- svg: 0.1.6

## Additional context
na

**Comment by Czaki** [comment]
Please verify 'scale' attribute for each layer. 
Currently napari default reader do not respect scale from tifffile metadata.

Currently you may use reader from PartSeg plugin. Fix scale from console or  use plugin that provide interface to modify scale.

**Comment by raacampbell** [comment]
I am not defining the number of microns per pixel in any meta-data. One of the image stacks simply appears to occupy a smaller number of pixels on screen than it should. Exactly as shown in the image, above. 

EDIT: Yes, the scales are wrong and I can fix the issue by editing them:

```
viewer.layers[0].scale
Out[17]: array([1.        , 0.35277778, 0.35277778])

viewer.layers[1].scale
Out[18]: array([1., 1., 1.])

viewer.layers[0].scale=[1,1,1]
```

**Comment by raacampbell** [comment]
So I can manually fix the problem by setting the scales to 1, but why would napari display this behavior in the first place?

**Comment by psobolewskiPhD** [comment]
I can't replicate this with drag-n-drop or File open in a fresh napari.
Maybe you have a reader plugin installed?
You can check filetype associations and reader plugins here in the preferences:
<img width="1127" alt="image" src="https://user-images.githubusercontent.com/76622105/170486744-4b168dc9-bc02-4afd-b8da-65755fc25118.png">
Cool images btw:
<img width="1228" alt="image" src="https://user-images.githubusercontent.com/76622105/170486958-18dd633e-8862-4521-9b90-d2d1683bd71c.png">

**Comment by raacampbell** [comment]
I just tried drag and drop with the built in reader and that indeed worked fine. `FIle > Open File` continues to exhibit the problem. I can't see anything in the reader plugins which could cause this but I anyway disabled everything but the defaults (see attached) and the issue still happens. 
![Screenshot_20220526_133144](https://user-images.githubusercontent.com/5427811/170488354-d0748155-c83c-4587-872c-b682601e0f79.png)

We don't know what the labelling even is yet, which is cool. It's all autofluoro.

**Comment by psobolewskiPhD** [comment]
In live napari the plugin reader behavior is tricky and really confusing.
I believe that File > open behaves differently than drag-n-drop, with only drag-n-drop respecting the bottom panel (File Extension Readers) which you set with the dialog (one time, always, etc.)
I think File > open still uses the top panel. 
So you have `ndtiffs` and `napari-itk-io` above `builtins` so I'm guessing one of those is used and causes the issue. Try sorting `builtins` to the top?

I *think* all of this will be harmonized in 0.4.16—maybe @DragaDoncila can chime in?

**Comment by Czaki** [comment]
> I am not defining the number of microns per pixel in any meta-data.

you may not define, but metadata of `ds_TM_RML_FVB_120dpi_220427_142730_25_25_ch02_chan_2_red.tif` contains information that pixel size is (0.35mm, 0.35mm) and  not provided z scale. 

```
In [1]: import tifffile

In [2]: t = tifffile.TiffFile("ds_TM_RML_FVB_120dpi_220427_142730_25_25_ch02_chan_2_red.tif")

In [3]: t.pages[0].tags["XResolution"].value
Out[3]: (72, 1)

In [4]: t.pages[0].tags["ResolutionUnit"].value
Out[4]: <RESUNIT.INCH: 2>
```

$$\frac{1}{72} \cdot 2.54 \approx 0.035 \mathrm{cm}$$ 

For labels tiff there is no information about pixel size. 

So napari renders your data properly. It just show that your lableling process should also take care about voxel size.

If I read your image using Bioformats plugin it also shows this resolution.

![Zrzut ekranu z 2022-05-26 15-52-47](https://user-images.githubusercontent.com/3826210/170501529-8f7ce1c1-29f5-4b5b-9acc-63b81c316a55.png)

**Comment by raacampbell** [comment]
Ok, thanks, that's clear now.

**Comment by Czaki** [comment]
Could I close this issue, or there are some unsolved problems?

**Comment by raacampbell** [comment]
Depends on you. Personally, I find this behaviour unexpected. Partly
because drag and drop behaves differently from File : Open, but also
because there is no visual indication why the scaling happens.

I think the ultimate way to resolve this is to have a radio button to
switch between pixels and microns and have an edit box for modifying the
scale. If you feel this is beyond the scope of the issue then please do
close.

Rob

**Comment by DragaDoncila** [comment]
> So you have ndtiffs and napari-itk-io above builtins so I'm guessing one of those is used and causes the issue. Try sorting builtins to the top?

@psobolewskiPhD I do think you've probably hit the nail on the head here as to why this is happening. @raacampbell you could verify this by checking `viewer.layers[0].source` and seeing which plugin opened your file when you get desired vs. undesired behavior.

You're right that it's super weird that File>Open doesn't match drag&drop. @psobolewskiPhD is right that this should all have been fixed for 0.4.16 and all GUI opening methods should exhibit identical behavior in the next release. You can try out the next release with `pip install --pre napari`. Alternatively, it should be out next Tuesday, and you can try again then. 

I suggest we leave this issue open until @raacampbell has a chance to verify whether the source plugin is the issue and if the new behavior after release is more consistent.

**Comment by raacampbell** [comment]
Interestingly I can no longer reproduce this issue. So I guess we close. I can't see why this has happened as I did originally try closing and restarting. I guess we close.

**Comment by DragaDoncila** [comment]
@raacampbell feel free to reopen if it does come back! 0.4.16 is out now and should hopefully resolve the ambiguities in file opening.
