### ISSUE TITLE
Multiple issues cause by Vispy versioning

### ISSUE THREAD

**Issue by brisvag** [napari/napari#4587]
## 🐛 Bug

Lately we had several people report problems that were tricky to debug due to weird vispy stack traces.

Ultimately, several of them were caused by the fact that we (me being a major culprit...) have been pushing many updates in vispy that changed the internals of visuals. These changes were to a point that the patches we do here in napari (a recurring problem being our specialized `Labels` isosurface rendering) need to be updated accordingly.

This, combined with the fact that so far we're been pinning only a minimum version for vispy, results in a lot of people installing non-dev versions of napari with a vispy version that's incompatible.

What do people think about pinning an exact version of vispy to solve this problem?

- #4570
- #4415
- #4548

Another thing that we should do is:
- #3771

**Comment by brisvag** [comment]
To clarify, this means that no matter what we do on the napari side now, if a new version of vispy comes out that's incompatible with an existing napari version, users will get these cryptic errors, with the nly solution being releasing a new napari version that fixes it.

**Comment by Czaki** [comment]
If I good understand these problems comes from vispy 0.10.0. So maybe it will be enough to pin `vispy <= 0.11.0`?

**Comment by brisvag** [comment]
But we also regularly depend on newer versions of vispy to implement new functionality. so in practice most of the times we have a minimum vispy version that's very recent (0.10.0 in current main, but it's 0.9 on the current latest release) and at the same time we have to preemptively lock upper version in case new stuff breaks (which as I mentioned, has been happing somewhat regularly lately). So you'd end up with `vispy=>0.10.0,<=0.11.0`, which is the same as pinning :P

**Comment by Czaki** [comment]
> So you'd end up with `vispy=>0.10.0,<=0.11.0`, which is the same as pinning :P

no, because 0.10.1 may introduce bugfix or new features without breaking API. It is different to `vispy==0.10.0`. 
Strict pinning requires politics for release new versions of napari when bugfix of strictly pinned library is released. 

For example, some time ago all release of `hsluv` was removed from pypi (it looks like some try of account higjack).
They restore it but cannot recovery old versions because of single upload policy on pypi. So if any project has strict pinning of hslav then its installation is broken until new project release: pypi.org/project/hsluv/#history

**Comment by brisvag** [comment]
But we can pin with `~=0.10`, and it should, right?

**Comment by jni** [comment]
@brisvag @Czaki your constraints are equivalent. I find `>=0.10.0,<0.11` to be the most readable. But, annoyingly, neither version will fix #4589! Can someone weigh in on whether that means we should do a hard pin, or update something on our end to make things compatible with vispy 0.10.x?

**Comment by jni** [comment]
(Also note `<0.11`, not `<=0.11`.)

**Comment by brisvag** [comment]
@jni What do you mean neither version will fix it? Tghat bug should not happen with 0.10.0, but only if you use `dev`. To fix #4589 *NOW* we have to replace `$sample` with `$get_data` in the gatecorical isosurface shader. However, that would require the next vispy version to be out, so that's the problem :P
