### ISSUE TITLE
Follow-up PR to #41

### ISSUE THREAD

**Issue by AhmetCanSolak** [napari/napari#46]
_Originally posted by @sofroniewn in https://github.com/Napari/napari-gui/pull/41#issuecomment-436826845_

We need a follow-up after cleaning qt folder in elements.

**Comment by sofroniewn** [comment]
this comment referenced organization of qt folder that has been somewhat addressed in #88 and #90. We may still want to rearrange the qt folder more if we move away from peer UI / non-UI classes, but we can do address that at the appropriate time. It is also being discussed on #92
