### ISSUE TITLE
Coords displayed should update with dimension slider movement

### ISSUE THREAD

**Issue by GenevieveBuckley** [napari/napari#4606]
## 🐛 Bug

When you move the dims slider in napari, then coordinates displayed in the bottom left hand corner do not update to reflect the new slice position.

## To Reproduce

1. Open napari and load an example dataset
```python
import napari
viewer = napari.Viewer()
viewer.open_sample('napari', 'cells3d')
```
2. Hover your mouse above the image canvas and observe the position coordinates displayed in the bottom left hand corner.
3. Move your mouse off the image canvas and click the dimension slider. Move the dimension slider several slices to the left or right, and observe that the displayed coordinates in the bottom left hand corner do NOT update (unless you move your mouse back onto the image canvas)

## Expected behavior

I expected that the displayed coordinates would update to reflect the current slice position.

## Environment

napari version 0.4.15 (installed with pip).

## Additional context

cc @jamesyan-git

**Comment by cnstt** [comment]
It seems to me that the coordinates displayed in the bottom left hand corner reflect the last position of the mouse cursor on the canvas. So the behavior might seem strange, but for me it seems currently "coherent". Because when moving the slider you are changing slice and arriving on a slice "where you mouse hasn't been yet".

**Comment by psobolewskiPhD** [comment]
I think there are 2 issues:
The coordinates are mouse coordinates, so `[z y x]` and in fact the value is also shown. When the mouse leaves the image data to click on the slider, then it's unclear what they should show: you can update `z` for the change of slice, but what do you do about [y x]?
The way ImageJ handles this is that the coordinates & values are only displayed when the mouse is hovering over image data.

The 2nd issue is that if you leave your mouse over a data point (it does not exit the canvas) and use the arrow keys to advance the slider, the coordinates *are also not updated* (nor is the value). You have to move the mouse again. This is clearly a bug.
