### ISSUE TITLE
napari.org calendar link to architecture working group call is broken

### ISSUE THREAD

**Issue by kevinyamauchi** [napari/napari#4608]
## 📚 Documentation

Some of the links to the Architecture working group are broken because they have "RWC-801J-3-324-Machu Picchu (7) [Zoom]" appended (e.g., May 16, 5PM CEST).

<img width="1435" alt="Screenshot 2022-06-02 at 17 34 09" src="https://user-images.githubusercontent.com/1120672/171666236-86d4b474-90b7-4c1a-bc3a-f8a68394ac24.png">

**Comment by sofroniewn** [comment]
@codemonkey800 @potating-potato can you look into this - thanks!

**Comment by codemonkey800** [comment]
Pretty sure this is something we can fix on the theme side, but I just noticed that URL looks different from my end?

<img width="280" alt="image" src="https://user-images.githubusercontent.com/2176050/171748889-c603f4ca-fdff-451b-a295-bf2ce64e8b5a.png">


was the meeting details changed recently?

**Comment by Czaki** [comment]
Andy do some changes: 
https://napari.zulipchat.com/#narrow/stream/296574-working-group-architecture/topic/Meeting.202022.2F06.2F02/near/284808045

**Comment by lucyleeow** [comment]
Have checked and it seems to be fixed now, closing
