### ISSUE TITLE
`AttributeError: type object 'Policy' has no attribute 'Maximum'` upon launch w/PyQt5 5.9.6 >> fine with PyQt5 5.15+

### ISSUE THREAD

**Issue by MMathisLab** [napari/napari#4610]
## 🐛 Bug

Firstly huge thanks for napari! 💜 

I hit an error that I *think* is not reported (I searched open/closed bugs first), and checked image forum sc. In short, installed on a new computer (macOS) today w/pip and it clearly starts to launch, icon pops up, and then crashes out. Traceback below. I just wanted to post this incase others hit the issue (and to note TL;DR, the warning solves it).

**To solve** the issue I uninstalled and re-installed PyQt5 (`pip install pyqt5`) to version `pyqt5-5.15.6`, then uninstalled/re-installed `napari-0.4.14`: `Successfully installed dask-2022.2.0 napari-0.4.14 npe2-0.2.1 pooch-1.6.0 pytomlpp-1.0.11 superqt-0.3.2 typer-0.4.1 vispy-0.10.0`

## To Reproduce

1. fresh install on macOS Monterey 12.1 (late 2021 Apple M1 Pro chip) with `pip install 'napari[all]'`
2. run `napari`
3. I see the warning that `UserWarning: napari was tested with QT library `>=5.12.3`.
The version installed is 5.9.6. Please report any issues with this specific QT version at https://github.com/Napari/napari/issues.` 
4. full traceback:
```bash
❯ napari
/Users/mwmathis/opt/anaconda3/lib/python3.7/site-packages/napari/_qt/__init__.py:38: UserWarning: napari was tested with QT library `>=5.12.3`.
The version installed is 5.9.6. Please report any issues with this specific QT version at https://github.com/Napari/napari/issues.
  warn(message=warn_message)
/Users/mwmathis/opt/anaconda3/lib/python3.7/site-packages/napari/_qt/__init__.py:38: UserWarning: napari was tested with QT library `>=5.12.3`.
The version installed is 5.9.6. Please report any issues with this specific QT version at https://github.com/Napari/napari/issues.
  warn(message=warn_message)
/Users/mwmathis/opt/anaconda3/lib/python3.7/site-packages/napari/__main__.py:374: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  platform.release()
/Users/mwmathis/opt/anaconda3/lib/python3.7/site-packages/napari/__main__.py:375: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  ) > StrictVersion('19.0.0')
/Users/mwmathis/opt/anaconda3/lib/python3.7/site-packages/napari/__main__.py:377: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  platform.release()
/Users/mwmathis/opt/anaconda3/lib/python3.7/site-packages/napari/__main__.py:378: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  ) > StrictVersion('20.0.0')
Traceback (most recent call last):
  File "/Users/mwmathis/opt/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/mwmathis/opt/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/mwmathis/opt/anaconda3/lib/python3.7/site-packages/napari/__main__.py", line 408, in <module>
    sys.exit(main())
  File "/Users/mwmathis/opt/anaconda3/lib/python3.7/site-packages/napari/__main__.py", line 404, in main
    _run()
  File "/Users/mwmathis/opt/anaconda3/lib/python3.7/site-packages/napari/__main__.py", line 297, in _run
    **kwargs,
  File "/Users/mwmathis/opt/anaconda3/lib/python3.7/site-packages/napari/view_layers.py", line 6, in view_path
    function signature is a merged version of one of the ``Viewer.__init__`` method
  File "/Users/mwmathis/opt/anaconda3/lib/python3.7/site-packages/napari/viewer.py", line 52, in __init__
    self._window = Window(self, show=show)
  File "/Users/mwmathis/opt/anaconda3/lib/python3.7/site-packages/napari/_qt/qt_main_window.py", line 342, in __init__
    self.qt_viewer = QtViewer(viewer, show_welcome_screen=True)
  File "/Users/mwmathis/opt/anaconda3/lib/python3.7/site-packages/napari/_qt/qt_viewer.py", line 144, in __init__
    object_name='layer list',
  File "/Users/mwmathis/opt/anaconda3/lib/python3.7/site-packages/napari/_qt/widgets/qt_viewer_dock_widget.py", line 140, in __init__
    self.title = QtCustomTitleBar(self, title=self.name)
  File "/Users/mwmathis/opt/anaconda3/lib/python3.7/site-packages/napari/_qt/widgets/qt_viewer_dock_widget.py", line 272, in __init__
    QSizePolicy(QSizePolicy.Policy.Maximum, QSizePolicy.Policy.Maximum)
AttributeError: type object 'Policy' has no attribute 'Maximum'
```

## Environment

 - python 3.7

## Additional context

hope this is useful, of course feel free to close 🤗

**Comment by psobolewskiPhD** [comment]
Just for completeness, can you just confirm you're running in an emulated python environment—I'm guessing because python 3.7 isn't supported anymore, so it's—to my knowledge—not available native arm64.
If you open the python REPL can you try: `import platform; platform.platform()`

**Comment by MMathisLab** [comment]
Hi @psobolewskiPhD no problem! For my 3.7 test:
```python
❯ python
Python 3.7.4 (default, Aug 13 2019, 15:17:50)
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform
>>> platform.platform()
'Darwin-21.2.0-x86_64-i386-64bit'
```

I should note, thank you, that I also tried with 3.8 (napari works for me with pyqt5>5.15+ as well). I do use a conda envs (simple `conda create --name napari-dlc python=3.8` then install pyqt5 then napari)
```python
❯ python
Python 3.8.13 (default, Mar 28 2022, 06:16:26)
[Clang 12.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform
>>> platform.platform()
'macOS-10.16-x86_64-i386-64bit'
```

**Comment by psobolewskiPhD** [comment]
Thanks!
BTW Did you get the pyqt error in the 3.8 env too after just pip install? Or does that install work out-of-the-box?
I suspect/hope that issue is limited to the 3.7 python, probably due to combo of very old python, latest macOS, plus emulation—quite the combo! 
Odd that platform doesn't even report macOS, just darwin.

Reason I ask is probably M1 macs will become steadily more common, so it's good to know expectations, install process, etc. in emulated envs vs native envs.

**Comment by MMathisLab** [comment]
of course! Afaik, 3.7 is still the native in base (have anaconda installed), so I was first just going to install napari outside of a dedicated env, and I can reproduce my error with lower version pyqt5 in that native state. For 3.8, I don't believe I did actually... so it could just be the magical native 3.7 with older pyqt5 :)

**Comment by psobolewskiPhD** [comment]
Just to head-off any confusion for future/other readers: I believe @MMathisLab is using `native` to refer to default python, present in the base anaconda env, while I was using `native` to refer to arm64, not emulated envs.
