### ISSUE TITLE
Label image 3D + image rendering issue in napari==0.4.16 / vispy 0.10.0

### ISSUE THREAD

**Issue by haesleinhuepf** [napari/napari#4618]
## 🐛 Bug

Hi all,

I'm seeing some black dust artifacts in napari==0.4.16 when rendering label images in 3D on top of normal images. It appears normal images have a different transparency rendering now. I'm not sure if this is intentional and thus, I'm creating this issue to discuss quickly.

Napari 0.4.16:
![image](https://user-images.githubusercontent.com/12660498/171998416-589bb459-021b-4113-b8ed-87ed7c2c4d9b.png)

The same scene in napari 0.4.15:
![image](https://user-images.githubusercontent.com/12660498/171998599-7474b271-d291-4676-bb1c-cfc7862cca7f.png)

## To Reproduce

1. [install devbio-napari](https://github.com/haesleinhuepf/devbio-napari)
2. run `pip install napari==0.4.16 vispy==0.10.0`
3. Start napari and load the example dataset `clEsperanto > Lund`
4. Start menu `Tools > Utilities > Assistant (na)`
5. Click on the `Remove background` button
6. Click on the `Label` button
7. Click on the `Process labels` button
8. Choose operation "dilate labels" and select a radius of `6`
9. Switch to 3D view, hide the layers "Result of Voronoi Otsu Labeling" and "Lund"
10. Take the first screenshot shown above
11. Close napari, run `pip install napari==0.4.15 vispy==0.9.6`
12. Repeat steps 3-9
13. Take the second screenshot shown above

## Expected behavior

It would be cool if the label image is rendered on top of the image again. Alternatively, I'm happy to learn how to configure napari 0.4.16 so that the rendering is more similar to 0.4.15

## Environment

 - Please copy and paste the information at napari info option in help menubar here:

```
napari: 0.4.16
Platform: Windows-10-10.0.19044-SP0
Python: 3.9.10 | packaged by conda-forge | (main, Feb 1 2022, 21:22:07) [MSC v.1929 64 bit (AMD64)]
Qt: 5.12.9
PyQt5: 5.12.3
NumPy: 1.22.4
SciPy: 1.8.0
Dask: 2022.02.0
VisPy: 0.10.0

OpenGL:
- GL version: 4.6.0 NVIDIA 496.49
- MAX_TEXTURE_SIZE: 32768

Screens:
- screen 1: resolution 1920x1200, scale 1.0

Plugins:
- PlatyMatch: 0.0.3
- RedLionfish: 0.6
- aicsimageio-in-memory: 0.5.0
- aicsimageio-out-of-memory: 0.5.0
- animation: 0.0.2
- cellpose-napari: 0.1.4
- clEsperanto: 0.18.1
- console: 0.0.4
- devbio_napari: 0.5.0
- morphometrics: 0.0.1
- napari-3d-ortho-viewer: 0.0.1
- napari-accelerated-pixel-and-object-classification: 0.8.0
- napari-allencell-segmenter: 1.1.4
- napari-animated-gif-io: 0.1.2
- napari-assistant: 0.3.4
- napari-brightness-contrast: 0.1.7
- napari-clusters-plotter: 0.5.0
- napari-crop: 0.1.5
- napari-cupy-image-processing: 0.2.3
- napari-curtain: 0.1.1
- napari-folder-browser: 0.1.3
- napari-itk-io: 0.1.0
- napari-layer-details-display: 0.1.2
- napari-npe2-test: 0.0.1
- napari-ome-zarr: 0.1.0
- napari-plot-profile: 0.2.1
- napari-plugin-search: 0.1.3
- napari-process-points-and-surfaces: 0.2.0
- napari-script-editor: 0.2.8
- napari-segment-blobs-and-things-with-membranes: 0.2.22
- napari-simpleitk-image-processing: 0.3.0
- napari-stress: 0.0.14
- napari-tabu: 0.1.5
- napari-time-slicer: 0.4.5
- napari-tools-menu: 0.1.15
- napari-workflow-inspector: 0.2.2
- napari-workflow-optimizer: 0.1.3
- napari_skimage_regionprops1: 0.5.0
- napari_skimage_regionprops2: 0.5.0
- natari: 0.2.7
- ome-types: 0.2.10
- ome_zarr: 0.0.18
- omero: 0.1.1
- scikit-image: 0.4.16
- stardist-napari: 2022.4.8
- svg: 0.1.5
- the-segmentation-game: 0.1.0
```

 - Any other relevant information:

**Comment by kevinyamauchi** [comment]
Thanks for the report @haesleinhuepf ! I am wondering if this is an issue with the depth of the labels layer “fighting” with the depth of another layer. It looks like there is another image layer visible in your screenshot.

What is the blending mode of the visible image layer?

**Comment by psobolewskiPhD** [comment]
I'm not able to reproduce this on my Mac. Get the same image in 0.4.16 and 0.4.15, which looks like the 2nd one above (the 0.4.15). Not seeing any artifacts. This is all with no changes to blending, rendering whatever. Just clicking the tiles in the Assistant as indicated.
![image](https://user-images.githubusercontent.com/76622105/172041144-92cdb09b-9ef4-45e5-b799-7048c8e3655d.png)

napari info:
<details>

```
napari: 0.4.16
Platform: macOS-12.3.1-arm64-arm-64bit
System: MacOS 12.3.1
Python: 3.9.12 | packaged by conda-forge | (main, Mar 24 2022, 23:25:14) [Clang 12.0.1 ]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.21.5
SciPy: 1.8.0
Dask: 2022.02.0
VisPy: 0.10.0

OpenGL:
- GL version: 2.1 Metal - 76.3
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1680x1050, scale 2.0

Plugins:
- aicsimageio-in-memory: 0.6.1
- aicsimageio-out-of-memory: 0.6.1
- clEsperanto: 0.18.2
- console: 0.0.4
- napari-accelerated-pixel-and-object-classification: 0.7.4
- napari-annotatorj: 0.0.5.dev0+ge3d5944.d20220601
- napari-assistant: 0.3.5
- napari-math: 0.0.1b0
- napari-ome-zarr: 0.4.0
- napari-sklearn-decomposition: 0.0.1
- napari-svg: 0.1.6
- napari-time-slicer: 0.4.4
- napari-tools-menu: 0.1.11
- napari_skimage_regionprops1: 0.5.0
- napari_skimage_regionprops2: 0.5.0
- natari: 0.2.7
- ome-types: 0.2.9
- scikit-image: 0.4.16
- stardist-napari: 2022.6.4

```
</details>

Also maybe relevant, my `pyopengl` is 3.1.6

**Comment by haesleinhuepf** [comment]
> What is the blending mode of the visible image layer?

It's translucent

![image](https://user-images.githubusercontent.com/12660498/172041844-38a61d90-3a56-4e61-94c8-14799d13e2a6.png)

If I switch it to additive, the effect goes away:

![image](https://user-images.githubusercontent.com/12660498/172041868-e52308cf-1b7d-4300-a4fa-c981571880b2.png)

Is this expected behaviour?

**Comment by kevinyamauchi** [comment]
Thanks for the additional info, @haesleinhuepf ! Given that additive mode removes the issue, it does sound like it is a depth fighting issue. To determine which visual to render at a given pixel, we assign a depth (distance from foreground) for each position in each visual and check which is most in the foreground. when multiple visuals are at approximately the same depth, this can  cause a salt and pepper  pattern of the visuals switching which is “in front”. I believe there were some changes in vispy/napari (cc @alisterburt , @brisvag ) such that the depth buffer is now being set for the Image layer, which is why you probably didn’t see this behaviour before. 

What happens if you set the top hat image layer blending to `transluscent_no_depth`? This is a translucent blending without depth checking.

**Comment by haesleinhuepf** [comment]
> What happens if you set the top hat image layer blending to `transluscent_no_depth`? This is a translucent blending without depth checking.

This also makes the visualization in napari==0.4.16 look like in napari==0.4.15:

![image](https://user-images.githubusercontent.com/12660498/172043924-a18dbf64-2218-45d5-aea7-05545189ac8e.png)

So this appears more and more like a feature and not a bug, right @alisterburt @brisvag ? :-)

**Comment by kevinyamauchi** [comment]
@psobolewskiPhD , thanks for the additional example. What happens if you change the layer visibility such that the labels layer and the “top hat results” layer are the only ones visible? It’s possible that the calculated depth is different for the “lund” image layer.

> So this appears more and more like a feature and not a bug, right @alisterburt @brisvag ? :-)

Yeah, I think this is the expected behavior. However, I think this is useful conversation because I think we still need to figure out the best defaults and the best ways to communicate how blending works and how to get the desired visualisations!

**Comment by psobolewskiPhD** [comment]
> @psobolewskiPhD , thanks for the additional example. What happens if you change the layer visibility such that the labels layer and the “top hat results” layer are the only ones visible? It’s possible that the calculated depth is different for the “lund” image layer.
> 

Yup, that makes a difference, probably because of the blending mode as noted above.
Opening an example image uses `translucent_no_depth` while the extra layers are just `translucent`.
![image](https://user-images.githubusercontent.com/76622105/172044925-50adce08-648a-48d3-b24c-36ca07ea1898.png)
Swapping one of any of the paired layers (Result of dilated... or Result of top... or Lund) to `translucent_no_depth` also eliminates the issue.

**Comment by alisterburt** [comment]
agh - so sorry about this @haesleinhuepf, as has been noted, we added optional depth checking to the `ImageVisual` in vispy and thought we had figured out the defaults with #4523 #4567

I'm curious as to why your image layer was in the `translucent`  blending mode - this should default to `translucent_no_depth` now to avoid this...

e.g. when I run

```python
import napari
import numpy as np

viewer = napari.Viewer()
viewer.add_image(np.random.random((10, 10, 10)))

napari.run()
```

I get a layer with the blending set to `translucent_no_depth`

@haesleinhuepf which API are you using to add the image? It seems like we missed something if you didn't explicitly set the blending mode

**Comment by haesleinhuepf** [comment]
> I'm curious as to why your image layer was in the `translucent` blending mode - this should default to `translucent_no_depth` now to avoid this...

This makes a lot of sense!

> @haesleinhuepf which API are you using to add the image? It seems like we missed something if you didn't explicitly set the blending mode

I'm obviously using the assistant and that's where the devil is in the detail: We defined our own default value for this:
https://github.com/haesleinhuepf/napari-assistant/blob/fe4a40342ff232acddaca863209dbf0e94e20e7f/napari_assistant/_categories.py#L30

That means I can fix this in on our side. 🙌 

Thanks everyone for the feedback!

**Comment by alisterburt** [comment]
Thanks for your patience! Pleasure as always
