### ISSUE TITLE
Canvas margin too wide in napari==0.4.16

### ISSUE THREAD

**Issue by haesleinhuepf** [napari/napari#4619]
## 🐛 Bug

Hi all,

a merged pull-request of mine https://github.com/napari/napari/pull/4496 obviously didn't make it into the recent release, even though it was merged 27 days ago. The canvas margin in napari==0.4.16 is wide again:

![image](https://user-images.githubusercontent.com/12660498/171999125-5a5517ee-923c-4b22-9038-b6b372e5e990.png)

As the changed code is obviously on the main branch:;

https://github.com/napari/napari/blob/7b940daa453dfb39e2a28f3540d60468a36f891d/napari/_qt/qt_viewer.py#L267:

```
main_layout.setContentsMargins(0, 2, 0, 2)
```

... but in my local installation of napari 0.4.16 (which came via pypi) it says 

```
main_layout.setContentsMargins(10, 22, 10, 2)
```

... which is the old code. I'm wondering if something went wrong with the deployment of napari to pypi?

## To Reproduce

1. pip install napari==0.4.16
2. launch napari
3. take screenshot

## Environment

 - Please copy and paste the information at napari info option in help menubar here:

```
napari: 0.4.16
Platform: Windows-10-10.0.19044-SP0
Python: 3.9.10 | packaged by conda-forge | (main, Feb 1 2022, 21:22:07) [MSC v.1929 64 bit (AMD64)]
Qt: 5.12.9
PyQt5: 5.12.3
NumPy: 1.22.4
SciPy: 1.8.0
Dask: 2022.02.0
VisPy: 0.10.0

OpenGL:
- GL version: 4.6.0 NVIDIA 496.49
- MAX_TEXTURE_SIZE: 32768

Screens:
- screen 1: resolution 1920x1200, scale 1.0

Plugins:
- PlatyMatch: 0.0.3
- RedLionfish: 0.6
- aicsimageio-in-memory: 0.5.0
- aicsimageio-out-of-memory: 0.5.0
- animation: 0.0.2
- cellpose-napari: 0.1.4
- clEsperanto: 0.18.1
- console: 0.0.4
- devbio_napari: 0.5.0
- morphometrics: 0.0.1
- napari-3d-ortho-viewer: 0.0.1
- napari-accelerated-pixel-and-object-classification: 0.8.0
- napari-allencell-segmenter: 1.1.4
- napari-animated-gif-io: 0.1.2
- napari-assistant: 0.3.4
- napari-brightness-contrast: 0.1.7
- napari-clusters-plotter: 0.5.0
- napari-crop: 0.1.5
- napari-cupy-image-processing: 0.2.3
- napari-curtain: 0.1.1
- napari-folder-browser: 0.1.3
- napari-itk-io: 0.1.0
- napari-layer-details-display: 0.1.2
- napari-npe2-test: 0.0.1
- napari-ome-zarr: 0.1.0
- napari-plot-profile: 0.2.1
- napari-plugin-search: 0.1.3
- napari-process-points-and-surfaces: 0.2.0
- napari-script-editor: 0.2.8
- napari-segment-blobs-and-things-with-membranes: 0.2.22
- napari-simpleitk-image-processing: 0.3.0
- napari-stress: 0.0.14
- napari-tabu: 0.1.5
- napari-time-slicer: 0.4.5
- napari-tools-menu: 0.1.15
- napari-workflow-inspector: 0.2.2
- napari-workflow-optimizer: 0.1.3
- napari_skimage_regionprops1: 0.5.0
- napari_skimage_regionprops2: 0.5.0
- natari: 0.2.7
- ome-types: 0.2.10
- ome_zarr: 0.0.18
- omero: 0.1.1
- scikit-image: 0.4.16
- stardist-napari: 2022.4.8
- svg: 0.1.5
- the-segmentation-game: 0.1.0
```

 - Any other relevant information:

**Comment by Czaki** [comment]
Hi Robert, 
Unfortunately, need to copy this contribution to the `v0.4.16x`  branch. Last common commit from `v0.4.16x` and `main` #4477 from 5 of May.  After this date release manager pick up only selected commits from the main branch (mainly bugfixes). 

As far as I understand you need to wait for the next release. At this moment I do not see a plan for a bugfix release that main contains this commit.

**Comment by haesleinhuepf** [comment]
> As far as I understand you need to wait for the next release. 

Ok cool. No hurry. I was just confused, because I thought this should come with napari 0.4.16.
