### ISSUE TITLE
Turn off ndim for painting by default

### ISSUE THREAD

**Issue by marshuang80** [napari/napari#462]
## 🚀 Feature
Requesting to turn off n-dim paint by default. 

## Motivation
I think cases where users will paint on multiple dimensions by default is small. Having paint default to ndim will confuse users when they see their paintings leak to other dimensions. 

## Pitch

Simply default ndim painting to False. 

## Alternatives

Better indication that paint bush is painting on multiple dimensions.

**Comment by sofroniewn** [comment]
Yup, makes sense - happy to change that default

**Comment by sofroniewn** [comment]
fixed in #485
