### ISSUE TITLE
"Ctrl + Alt + / show all key bindings" doesn't work

### ISSUE THREAD

**Issue by haesleinhuepf** [napari/napari#4625]
## 🐛 Bug

Hi all,

I just noticed that Ctrl+Alt+/  show all key bindings doesn't work. I also cannot find a menu where the key bindings are listed.

![image](https://user-images.githubusercontent.com/12660498/172236203-862c0933-b6a6-46af-a438-d0cfdf0bf6c2.png)

## To Reproduce

1. Open napari
2. Hit Ctrl+Alt+/

## Expected behavior

The shortcut should work. Also a menu for showing key bindings would be great - especially for the people who prefer having menus for things.

## Environment

 - Please copy and paste the information at napari info option in help menubar here:

```
napari: 0.4.16
Platform: Windows-10-10.0.19044-SP0
Python: 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)]
Qt: 5.12.9
PyQt5: 5.12.3
NumPy: 1.22.4
SciPy: 1.8.0
Dask: 0+unknown
VisPy: 0.10.0

OpenGL:
- GL version: 4.6.0 NVIDIA 511.69
- MAX_TEXTURE_SIZE: 32768

Screens:
- screen 1: resolution 1920x1200, scale 1.0

Plugins:
- PlatyMatch: 0.0.3
- RedLionfish: 0.6
- StarDist: 2021.10.25
- animation: 0.0.2
- cellpose-napari: 0.1.4
- clEsperanto: 0.18.1
- console: 0.0.4
- devbio_napari: 0.5.5
- napari-3d-ortho-viewer: 0.0.1
- napari-accelerated-pixel-and-object-classification: 0.7.4
- napari-assistant: 0.3.7
- napari-brightness-contrast: 0.1.7
- napari-clusters-plotter: 0.5.0
- napari-crop: 0.1.5
- napari-cupy-image-processing: 0.2.0
- napari-curtain: 0.1.1
- napari-folder-browser: 0.1.3
- napari-itk-io: 0.1.0
- napari-layer-details-display: 0.1.3
- napari-mouse-controls: 0.1.3
- napari-ome-zarr: 0.4.0
- napari-plot-profile: 0.2.1
- napari-plugin-search: 0.1.3
- napari-process-points-and-surfaces: 0.2.0
- napari-segment-blobs-and-things-with-membranes: 0.2.19
- napari-simpleitk-image-processing: 0.3.1
- napari-stress: 0.0.14
- napari-svg: 0.1.6
- napari-tabu: 0.1.5
- napari-time-slicer: 0.4.6
- napari-tools-menu: 0.1.15
- napari-workflow-inspector: 0.2.2
- napari-workflow-optimizer: 0.1.4
- napari_skimage_regionprops1: 0.5.2
- napari_skimage_regionprops2: 0.5.2
- ome-types: 0.2.10
- scikit-image: 0.4.16
- the-segmentation-game: 0.1.0
```

 - Any other relevant information:

I'm working on Windows 10 with a US keyboard layout.

**Comment by Czaki** [comment]
Fast checking shows tath it was removed between 0.4.10 and 0.4.11 releases. 

Currently, shortcuts could be checked in preferences. 
I do not know what should be bugfix. remove this message or open the preferences dialog with the proper tab selected?

**Comment by DragaDoncila** [comment]
I don't think we should remove the message, that would make our already kinda hidden keybindings even more hidden lol. 

> open the preferences dialog with the proper tab selected?

This makes most sense to me
