### ISSUE TITLE
Ctrl + Q shuts down napari without asking

### ISSUE THREAD

**Issue by haesleinhuepf** [napari/napari#4626]
## 🐛 Bug

Hi all,

I was just in the middle of something and hit Ctrl+Q unintentionally. This shut down napari without asking. I'm a windows user and on Windows, Ctrl+Q is not common short cut, and it's unexpected that one can shut down applications like this. I'm wondering why this short-cut was introduced. Windows does have a short cut for exiting applications: Alt + F4, which also works with napari.

## To Reproduce

1. Start napari
2. hit Ctrl + Q

## Expected behavior

I'm proposing to disable the Ctrl+Q short-cut. There are cooler things we could do with this short-cut.

## Environment

 - Please copy and paste the information at napari info option in help menubar here:

```
napari: 0.4.16
Platform: Windows-10-10.0.19044-SP0
Python: 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)]
Qt: 5.12.9
PyQt5: 5.12.3
NumPy: 1.22.4
SciPy: 1.8.0
Dask: 0+unknown
VisPy: 0.10.0

OpenGL:
- GL version: 4.6.0 NVIDIA 511.69
- MAX_TEXTURE_SIZE: 32768

Screens:
- screen 1: resolution 1920x1200, scale 1.0

Plugins:
- PlatyMatch: 0.0.3
- RedLionfish: 0.6
- StarDist: 2021.10.25
- animation: 0.0.2
- cellpose-napari: 0.1.4
- clEsperanto: 0.18.1
- console: 0.0.4
- devbio_napari: 0.5.5
- napari-3d-ortho-viewer: 0.0.1
- napari-accelerated-pixel-and-object-classification: 0.7.4
- napari-assistant: 0.3.7
- napari-brightness-contrast: 0.1.7
- napari-clusters-plotter: 0.5.0
- napari-crop: 0.1.5
- napari-cupy-image-processing: 0.2.0
- napari-curtain: 0.1.1
- napari-folder-browser: 0.1.3
- napari-itk-io: 0.1.0
- napari-layer-details-display: 0.1.3
- napari-mouse-controls: 0.1.3
- napari-ome-zarr: 0.4.0
- napari-plot-profile: 0.2.1
- napari-plugin-search: 0.1.3
- napari-process-points-and-surfaces: 0.2.0
- napari-segment-blobs-and-things-with-membranes: 0.2.19
- napari-simpleitk-image-processing: 0.3.1
- napari-stress: 0.0.14
- napari-svg: 0.1.6
- napari-tabu: 0.1.5
- napari-time-slicer: 0.4.6
- napari-tools-menu: 0.1.15
- napari-workflow-inspector: 0.2.2
- napari-workflow-optimizer: 0.1.4
- napari_skimage_regionprops1: 0.5.2
- napari_skimage_regionprops2: 0.5.2
- ome-types: 0.2.10
- scikit-image: 0.4.16
- the-segmentation-game: 0.1.0
```

 - Any other relevant information:

**Comment by Czaki** [comment]
I agree that missing all jobs because of a single shortcut click may be frustrating.

**Comment by haesleinhuepf** [comment]
Just another note: Ctrl + Q is not in the list of shortcuts in File > Preferences. Instead it's a short-cut provided for the Exit menu:

![image](https://user-images.githubusercontent.com/12660498/172241918-dd534c30-d43b-4944-9f16-ef35cf0767e5.png)

**Comment by haesleinhuepf** [comment]
I also propose to remove the short-cut Ctrl + W, which also closes napari.

**Comment by jni** [comment]
@haesleinhuepf Ctrl-W is absolutely a standard shortcut for closing a window, both on Mac and Linux. Ditto for Ctrl/Cmd-Q (just checked on Firefox for Linux). So I don't want to remove these shortcuts. I'm totally open to adding a preference to check for "confirm before closing main window", though.

**Comment by psobolewskiPhD** [comment]
Confirm before closing with a populated layer list and/or maybe open dock widget would be a nice feature.

**Comment by jni** [comment]
Personally I would want this to be a preference and/or a distinction between the bundle and IPython versions, because I open and close viewers many times within an IPython session. (ie I use napari a lot as a quick "plt.imshow" replacement.)

**Comment by Czaki** [comment]
> Personally I would want this to be a preference and/or a distinction between the bundle and IPython versions, because I open and close viewers many times within an IPython session. (ie I use napari a lot as a quick "plt.imshow" replacement.)

maybe the second `Ctrl+Q` on the asking dialog should be counted as confirmation?
