### ISSUE TITLE
New shortcuts are not populated if user modified default shortcuts

### ISSUE THREAD

**Issue by Czaki** [napari/napari#4631]
## 🐛 Bug

During the development of #4628 I found that napari settings treat shortcuts as a single field in the base model, so if the user modifies any of the shortcuts and a new shortcut is added then its value is ignored and a user needs to define it or restore all keybindings 

## To Reproduce

1. checkout 5c10022337601f350ad64ce56eddf6664306e40e commit. 
2. restore default keybindings (to be sure)
3. modify one of shortcuts
4. checkout  #4628 (or its merge commit)
5. check-in preferences dialog that shortcut field is empty

![Zrzut ekranu z 2022-06-07 10-43-06](https://user-images.githubusercontent.com/3826210/172337633-d34c78aa-0efd-4c46-8d96-c0e2f5723d9f.png)

## Expected behavior

New shortcuts need to be pulled from the default value. 

## Environment

 - Please copy and paste the information at napari info option in help menubar here:

 - Any other relevant information:

**Comment by jni** [comment]
@Czaki that's a rather complex reproducer. Should we just wait until #4628 is in to deal with this?

**Comment by psobolewskiPhD** [comment]
Is this still an issue? Is there some clearer reproducer? I think the OP is out-dated?

**Comment by Czaki** [comment]
it was fixed in #5018
