### ISSUE TITLE
Terminal error while trying to create an environment and installing napari using using conda 

### ISSUE THREAD

**Issue by kpavani14** [napari/napari#4642]
I am trying to create a new environment for napari and install it using the commands
conda create -y -n napari-env python=3.7.4  (the current python version I have )
conda activate napari-env
conda install -c conda-forge napari

I am getting the same error for each command 

Error report:
Traceback (most recent call last):
      File "c:\Anaconda\lib\site-packages\conda\exceptions.py", line 1082, in __call__
        return func(*args, **kwargs)
      File "c:\Anaconda\lib\site-packages\conda\cli\main.py", line 87, in _main
        exit_code = do_call(args, p)
      File "c:\Anaconda\lib\site-packages\conda\cli\conda_argparse.py", line 84, in do_call
        return getattr(module, func_name)(args, parser)
      File "c:\Anaconda\lib\site-packages\conda\cli\main_create.py", line 41, in execute
        install(args, parser, 'create')
      File "c:\Anaconda\lib\site-packages\conda\cli\install.py", line 116, in install
        if context.use_only_tar_bz2:
      File "c:\Anaconda\lib\site-packages\conda\base\context.py", line 775, in use_only_tar_bz2
        import conda_package_handling.api
      File "c:\Anaconda\lib\site-packages\conda_package_handling\api.py", line 6, in <module>
        import tqdm as _tqdm
    ModuleNotFoundError: No module named 'tqdm'

`$ c:\Anaconda\Scripts\conda-script.py create -y -n napari-env python=3.7.4`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=c:\Anaconda\condabin\..\Scripts\conda.exe
               CONDA_EXES="c:\Anaconda\condabin\..\Scripts\conda.exe"
             CONDA_PREFIX=c:\Anaconda
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=c:\Anaconda\python.exe
               CONDA_ROOT=c:\Anaconda
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
                 HOMEPATH=\Users\paka874c
                     PATH=c:\Anaconda;c:\Anaconda\Library\mingw-w64\bin;c:\Anaconda\Library\usr\
                          bin;c:\Anaconda\Library\bin;c:\Anaconda\Scripts;c:\Anaconda\bin;c:\Ana
                          conda;c:\Anaconda\Library\mingw-w64\bin;c:\Anaconda\Library\usr\bin;c:
                          \Anaconda\Library\bin;c:\Anaconda\Scripts;c:\Anaconda\bin;c:\Anaconda\
                          condabin;C:\Program Files\jdk-8.0.222-jre\bin;C:\Windows\system32;C:\W
                          indows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\
                          v1.0;C:\Windows\System32\OpenSSH;C:\Windows\system32\config\systemprof
                          ile\AppData\Local\Microsoft\WindowsApps;C:\Program
                          Files\MATLAB\R2020b\runtime\win64;C:\Program Files\MATLAB\R2020b\bin;C
                          :\Users\paka874c\AppData\Local\Microsoft\WindowsApps;.
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\Windows
                          PowerShell\v1.0\Modules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : c:\Anaconda
            shell level : 1
       user config file : C:\Users\paka874c\.condarc
 populated config files : C:\Users\paka874c\.condarc
          conda version : 4.12.0
    conda-build version : 3.18.9
         python version : 3.7.4.final.0
       virtual packages : __win=0=0
                          __archspec=1=x86_64
       base environment : c:\Anaconda  (writable)
      conda av data dir : c:\Anaconda\etc\conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : c:\Anaconda\pkgs
                          C:\Users\paka874c\.conda\pkgs
                          C:\Users\paka874c\AppData\Local\conda\conda\pkgs
       envs directories : c:\Anaconda\envs
                          C:\Users\paka874c\.conda\envs
                          C:\Users\paka874c\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.12.0 requests/2.27.1 CPython/3.7.4 Windows/10 Windows/10.0.17763
          administrator : False
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.

Upload did not complete.

I cannot understand where it went wrong. can some one help me to install napari.

**Comment by Czaki** [comment]
Napari drops support of python 3.7 a few versions ago. It is possible for you to use a more modern python version?

**Comment by jaimergp** [comment]
This is a problem with your Anaconda installation, I am afraid; nothing to do with `napari` since you would probably obtain the same error if you tried to install `numpy` instead.

A possible workaround is to `pip install tqdm` on your `base` environment and cross your finger. If that doesn't work, reinstalling Anaconda might be simplest way :(
