### ISSUE TITLE
updating a layer by assigning .data is slow

### ISSUE THREAD

**Issue by bryantChhun** [napari/napari#465]
## 🐛 Bug

Assigning an image layer's data by directly modifying layer.data takes roughly 500ms to display.  Updates more frequently than this will result in unrendered data, sometimes crashing the app.

## To Reproduce

1. Create a napari image layer
2. Assign data to it by using "layer.data = ..."
3. Sleep some interval time.
4. Assign more data as in 2 above
3. Observe the rendered GUI throughout the script

I used the following test code as a script.  Modify 'update_interval' to observe loss of rendered data.

```
import numpy as np
import napari
from PyQt5.QtCore import QThread
import time
from datetime import datetime


def send_random(layer_):
    # number of images to stream
    num_images = 10
    
    # time between image assignment
    update_interval = 0.5

    # pause so we can observe beginning/end of visual update
    time.sleep(2)

    print('from another thread')
    start = datetime.now()
    for k in range(num_images):

        time.sleep(update_interval)

        dat = np.random.random((512, 512))
        layer_.data = dat
        
        # check that data layer is properly assigned and not blocked?
        while layer.data.all() != dat.all():
            layer_.data = dat

    stop = datetime.now()
    print("time per update = "+
          str((stop-start).microseconds/num_images))


class ThreadRandom(QThread):

    def __init__(self, layer_):
        QThread.__init__(self)
		self.layer_ = layer_

    def run(self):
        send_random(self.layer_)


with napari.gui_qt():
    # create the viewer with an image

    data = np.random.random((512,512))
    viewer = napari.Viewer()
    layer = viewer.add_image(data)

    t = ThreadRandom(layer)
    t.start()
```

## Observations:
1) fastest we can update is roughly 500 ms without “loss” of data
2) as update time interval is decreased, we start to lose rendered images, even though we successfully assign to layer.data (?)
3) as the number of images increases, and with short update interval, the application can crash.
4) in step 3 above, the time per update can decrease as number of images increases— suggesting qeventloop congestion (as per ahmet can’s suggestion)
5) the size of the image has a small influence.

It's likely this update interval is dependent on computer hardware.

## Expected behavior

In very early versions of napari, I could modify the layer data this way in real-time (0.03s update interval), with no visible lag or crashing.

## Environment

 - napari Version (e.g., 1.0): 0.1.3
 - OS (e.g., Linux): OSX
 - Python version: 3.7
 - Any other relevant information:

**Comment by sofroniewn** [comment]
@bryantChhun the main change in how napari has displayed images was the introduction of the `_data_view` 

https://github.com/napari/napari/blob/0481f2546df389b3c0f2962a3a73d2b6c9b4cd68/napari/layers/image/image.py#L282

If you skipped this, say by setting `layer._node.set_data(img)` and calling `layer._node.update()` directly then you'll probably have much faster speeds (though you won't actually be changing the "data" on the layer - and this assumes you're looking at 2D data.

Can you write a bit more about what sort of functionality you expect and what is tolerable from a "loss of rendered data" perspective. i.e. if you generate data every 1ms it doesn't make sense to display it (nor would it be possible for your monitor to display it) that fast so we'd have to drop some frames there. I think 30Hz - 60Hz are reasonable target numbers.

**Comment by sofroniewn** [comment]
I'll add the `_data_view` was added to support the lazy loading with dask / zarr etc

**Comment by jni** [comment]
@sofroniewn another thing that has changed is the thumbnails. I wonder if processing thumbnails is taking a while also? More generally, a side effect of our model/view separation is that we are sending a heck of a lot of signals around that we weren't historically, and I wonder if that is what is causing the slowness...

**Comment by bryantChhun** [comment]
Nick's solution above, to use:

```
layer._node.set_data(img)
layer._node.update()
```

Works like a charm.  Can drop update_rate to 0.001 with seemingly no issues.

**Comment by jni** [comment]
Let's keep this open as a reminder to follow up on streaming data. It'll be important to be able to e.g. stream a volume and have the 3D sliders work.

**Comment by VolkerH** [comment]
I used some of the info contained in this issue and the opencv facedetect example to create a little live capture/processing demo. These are just webcam images, but the update happens fast enough for this application. Not sure whether just assigning to the `shape_layer.data` is the right way to go to update polygons. I could imagine this in smart microscopy applications detecting regions of biological interest. 
![webcam2](https://user-images.githubusercontent.com/2210044/67730216-7c35ca00-fa48-11e9-90e3-8dede7076dc4.gif)

Code: https://github.com/VolkerH/NapariPlayground/blob/master/LiveUpdate/webcam_opencv.py

**Comment by GenevieveBuckley** [comment]
That's really cool, @VolkerH 
Are you planning to try out something similar on a microscopy application soon?

**Comment by VolkerH** [comment]
@GenevieveBuckley, I will answer that outside of this issue as it is somewhat off-topic.

**Comment by sofroniewn** [comment]
I added some more `set_data` like benchmarks in #747 and things are now pretty fast with the main `layer.data = new_data` api. A lot has changed since this original issue was made that could account for it. With a 4096 x 4096 image the update time is now `1.5ms` and most of that is spent in the thumbnail generation, which still isn't too bad.

@bryantChhun can you test this again with the latest version of napari `0.2.6` and see if it is still slow?

**Comment by sofroniewn** [comment]
Based on the benchmarks reported above this has now been fixed. This PR can always be reopened, or a new one created if new issues arise, but I am closing for now.
