### ISSUE TITLE
Public API for viewer.window._qt_window

### ISSUE THREAD

**Issue by cnstt** [napari/napari#4650]
## 🚀 Feature
Public API for `viewer.window._qt_window`. This feature request is close to https://github.com/napari/napari/issues/4434

## Motivation

This attribute need to be accessed outside of "napari" publicly: by plugins for example, or even by software projects depending on the napari viewer like https://github.com/bioimageit here (ping @sylvainprigent): https://github.com/bioimageit/bioimageit_viewer/blob/845112069f7f0112bec8ba10107f665ea0716748/bioimageit_viewer/viewer/napari.py

## Pitch

Make this API public

**Comment by Czaki** [comment]
In the example, you link it could be achieved using `viewer.window.add_dock_widget`

https://github.com/napari/napari/blob/1546f18ecc13364d5415623a9c11ed760ff043e2/napari/_qt/qt_main_window.py#L729-L774

**Comment by cnstt** [comment]
> In the example, you link it could be achieved using `viewer.window.add_dock_widget`
> 
> https://github.com/napari/napari/blob/1546f18ecc13364d5415623a9c11ed760ff043e2/napari/_qt/qt_main_window.py#L729-L774

I didn't meant this one but more specifically this one: https://github.com/bioimageit/bioimageit_viewer/blob/845112069f7f0112bec8ba10107f665ea0716748/bioimageit_viewer/viewer/napari.py#L27

**Comment by Czaki** [comment]
but this is embedding napari in some other application and I'm not sure if QMainWindow should be embedded in another QMainWindow.

**Comment by Czaki** [comment]
And looking at code same could be achieved using QtViewer and ViewerModel which are part of public API.

**Comment by cnstt** [comment]
> And looking at code same could be achieved using QtViewer and ViewerModel which are part of public API.

Thanks for the advice! So maybe I will close the issue, as for now in my plugin only this https://github.com/napari/napari/issues/4434 is needed ;)
