### ISSUE TITLE
Run ASV only once a day ?

### ISSUE THREAD

**Issue by Carreau** [napari/napari#4653]
Should we run ASV only once/twice a day on CI ?
Or at least set the concurrency to cancel the previous run if not finished ? 
Each run eats about 2h or ci-worker time, and when merging a few PRs we ended up losing more than the time we gained by speeding up the standard test suite.

**Comment by Carreau** [comment]
For example right now our 4 free workers are all busy with ASV, meaning that nothing else runs.

**Comment by Czaki** [comment]
I think that it should only execute once per day.

And on PR should be triggered only on request (if core developers worry about performance)

**Comment by jaimergp** [comment]
I'll put some PRs today to fix this and other issues!
