### ISSUE TITLE
Allow public access to points layer's `_antialias` attribute

### ISSUE THREAD

**Issue by dagewa** [napari/napari#4683]
## 🚀 Feature
I am working on a 3D viewer in which a potentially large number of points may be displayed. There is useful information available from an overall view of the points cloud, as well as working closer in. However, at low zoom the points tend to fade to indistinctness. Following [a discussion](https://forum.image.sc/t/adjusting-depth-fading/68181/6) at image.sc, I found that setting 

```
points_layer._antialias = 0.3
```

provides an excellent solution to the problem. However, I'm not too keen on relying on a private attribute for this. From the discussion, I understand that this is private because it works around an upstream bug. Nevertheless, the workaround works very well for me. Perhaps this attribute could be supported publicly for now, with the possibility of formal deprecation in future, if indeed upstream changes render it obsolete?

## Motivation

Developing a new 3D viewer application, while trying to adhere to the supported API.

## Pitch

Create a public `antialias` property for the points layer, with documented effects.

## Alternatives

As discussed at image.sc, setting `experimental_canvas_size_limits` provides a partial workaround for the issue, but the visual effect is not as close to what I want as reducing the `_antialias` value.

## Additional context

Overview, where points layers have `_antialias = 1.0`:
![antialias_1 0](https://user-images.githubusercontent.com/11502083/173359921-f1007fe2-8794-4656-83b1-78fcca256761.png)

Improved overview, once point layers have `_antialias = 0.3`:
![antialias_0 3](https://user-images.githubusercontent.com/11502083/173360018-bed4a8a8-f13f-4c2e-a547-ba4e4612cfa5.png)

**Comment by cnstt** [comment]
This shouldn't be too hard to to, as I'm currently doing 2 other PRs about public access. Maybe @Czaki or @tlambert03 is this something we want? (because I don't want to work on it, if this change is not desired :laughing:  )

**Comment by tlambert03** [comment]
Fine with me I think, but I'd yield to @jni @alisterburt @brisvag @andy-sweet on this one

**Comment by Czaki** [comment]
I do not work with such type of data. I would rater call @brisvag or @alisterburt.

**Comment by brisvag** [comment]
I'm ok with having `antialias` public. I think @sofroniewn was "against" it when I first introduced the attribute (see https://github.com/napari/napari/pull/3430#issuecomment-984199297), maybe he can comment here now.

I would also still argue in favor of setting a non-zero value (even just 1 or 2 pixels) for the minimum of `experimental_canvas_size_limits`, just so the points never disappear (see discussion in #4705).

**Comment by alisterburt** [comment]
I'm absolutely in favour, I don't think the upstream issue will be fixed any time soon so have no problem with a public API here - PR incoming

**Comment by cnstt** [comment]
> PR incoming

Thanks for the PR @alisterburt, I would have done it but you have already done the work so it's great, thanks! ;)

**Comment by alisterburt** [comment]
@cnstt sorry I totally missed that you were going to take it on!! Hopefully this frees you up to take on something bigger 😉

**Comment by sofroniewn** [comment]
> I'm ok with having antialias public. I think @sofroniewn was "against" it when I first introduced the attribute (see https://github.com/napari/napari/pull/3430#issuecomment-984199297), maybe he can comment here now.

Given the need I'm fine with this - i was just trying to limit too rapid growth of our API. I have approved #4735

**Comment by brisvag** [comment]
Closed by #4735! The attribute is now exposed as `antialiasing` and as a keyword argument as well.

**Comment by dagewa** [comment]
Thanks all, just catching up after a while working on some other projects. This is great :+1:
