### ISSUE TITLE
Seed values passed to viewer.add_labels() behaving incorrectly

### ISSUE THREAD

**Issue by GenevieveBuckley** [napari/napari#4695]
## 🐛 Bug

Passing a seed value in to the `viewer.add_labels()` function does not work the way you'd expect.

## To Reproduce

```python
import napari

viewer = napari.Viewer()

for i in range(3):
    img = np.random.random((100,100)) > 0.5
    viewer.add_labels(img, seed=i)
```

All the labels layers here have the same (yellow) colour.

## Expected behavior

I expected every label layer to have a different colour, since they all had a different seed value.

## Environment
```
napari: 0.4.16
Platform: macOS-12.3.1-arm64-arm-64bit
System: MacOS 12.3.1
Python: 3.9.13 | packaged by conda-forge | (main, May 27 2022, 17:00:33) [Clang 13.0.1 ]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.22.4
SciPy: 1.8.1
Dask: 2022.02.1
VisPy: 0.10.0

OpenGL:
- GL version: 2.1 Metal - 76.3
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1440x900, scale 2.0

Plugins:
- console: 0.0.4
- napari-svg: 0.1.6
- scikit-image: 0.4.16
```

 - Any other relevant information:
This bug also occurs in a development napari environment, using the latest main branch.

**Comment by GenevieveBuckley** [comment]
Experiments:
* We found that seed values using `np.random.random()` worked as expected. Those values always fall between 0.0 and 1.0, which is different than my example above
* We also found that *negative* seed values (using `-1 * np.random.random()`) also worked.
* Oddly, when we tried `1 + np.random.random()` this also worked,
* But seed values like: 1.1, 1.2, 1.3 did not work 🤷

**Comment by GenevieveBuckley** [comment]
I'm pretty sure you can use any value you like for numpy seed values, so I expect that seeds in napari should also work the same way. 

If consistency with numpy seed behaviour cannot be achieved, we should at least put it clearly in the docs to let people know what the restrictions are.

**Comment by DragaDoncila** [comment]
^ To add to this I also tried seeds `[1.1, 2.2, 3.3]` and that works, so it's not even that they're limited by absolute value or anything... It's very unclear what values will and won't work. This might be not a napari thing but a `np` thing or `vispy` thing where we generate the colormaps, but in that case we really should document the `seed` parameter a bit more. Certainly this is totally not obvious to a user.

**Comment by perlman** [comment]
This is an interesting quirk of `low_discrepancy_image`. It clearly works for values `[0.0-1.0)`, which are what @jni and I initially tested with (you know, `random.random()` 🙃). I agree with @GenevieveBuckley that we should either behave as expected with any floating point value _or_ document the behavior and generate a warning. Preferably the former.

Here's a simplified case, showing the 

```
import np
from napari.utils.colormaps import low_discrepancy_image
for i in range(3):
    print(low_discrepancy_image(np.array([1]), seed=i))
```

Output:
```
[0.61711185]
[0.61711185]
[0.61711185]
```

**Comment by perlman** [comment]
Well, the problem is pretty clear. In `low_discrepancy_image`, we do `(image_float - np.floor(image_float))` (effectively `%`), which will be identical if the seed values are exact integer values apart.

It seems to me that the right solution is to document `seed` as being `[0,1.0)`, or, alternatively, we can perform a hash function on the seed itself...?

@jni What do you think? Our shader in #3308 behaves identically. (`value = mod((t * phi_mod + $seed), 1.0);`)

**Comment by psobolewskiPhD** [comment]
Updating this issue:
`seed` in `add_labels` has been deprecated.
The recommended approach is now, if I understand correctly, to first
`from napari.utils.colormaps import label_colormap`
 and then pass `colormap=label_colormap(seed=X)` to add_labels.
This has the same issue though, that it's only decimals that matter, so 1.1 and 0.1 give the same colors. But 0.1 and 0.11 are different.

**Comment by jni** [comment]
Yes this is a documentation issue rather than a bug. I think we'll eventually deprecate the whole function in favour of something to generate colors directly, but for now let's leave it as a docs issue.
