### ISSUE TITLE
Fail of create conda package tests

### ISSUE THREAD

**Issue by Czaki** [napari/napari#4714]
## 🐛 Bug

Conda creates package fail with:

```
Adding in variants from argument_variants
/home/runner/work/_temp/edcbc389-633a-4961-a9a1-fa7d8a87c0ff.sh: line 12:  2943 Killed                  conda-smithy rerender
```

## To Reproduce

https://github.com/napari/napari/runs/6958614736?check_suite_focus=true

## Environment

last main

 - Please copy and paste the information at napari info option in help menubar here:

 - Any other relevant information:

## Additional context

cc @jaimergp @goanpeca

**Comment by jaimergp** [comment]
Looks like out-of-memory during the feedstock rerender. We can _temporarily_ comment [that line](https://github.com/napari/napari/blob/main/.github/workflows/make_bundle_conda.yml#L92) out; it's just "nice-to-have".

**Comment by jaimergp** [comment]
Looks like it fixed itself (or [thanks to this](https://github.com/conda-forge/conda-smithy/pull/1636)?). We can close!
