### ISSUE TITLE
Formatting of traceback in test output on github actions is unreadable

### ISSUE THREAD

**Issue by Czaki** [napari/napari#4744]
## 🐛 Bug

Current formatting of a traceback in test run add coloring but breaks spaces in rendering preview of a traceback in browser making it hard to read:

![obraz](https://user-images.githubusercontent.com/3826210/175829957-6a358522-f9e4-484f-98ba-3a87fa8d5a40.png)

How it looks without formating in the different repository (PartSeg)

![obraz](https://user-images.githubusercontent.com/3826210/175829977-50ff2ebc-3b8f-40ef-b96f-3c46a6a2d547.png)

Also, raw logs preview is unreadable:

![obraz](https://user-images.githubusercontent.com/3826210/175830055-6cc6b16a-5380-4961-82b7-296462d33b69.png)

![obraz](https://user-images.githubusercontent.com/3826210/175830071-2b7977a8-06a0-4684-9e62-797652d3a207.png)

I think that coloring should be disabled when running on CI.

**Comment by psobolewskiPhD** [comment]
This no longer appears to be the case. Here's a traceback from a recent test fail:
<img width="771" alt="image" src="https://github.com/napari/napari/assets/76622105/54607d1c-c446-44a0-9e2c-64049304d1cc">

Looks fine to me.
I think this PR fixed it: https://github.com/napari/napari/pull/5525
Can we close @Czaki ?

**Comment by Czaki** [comment]
It still looks like this when one download logs 
![obraz](https://github.com/napari/napari/assets/3826210/ab5375d3-7e51-4083-9dd0-2bfe7f39f519)

**Comment by psobolewskiPhD** [comment]
😮
Well, don't download them? 😇

**Comment by Czaki** [comment]
I agree. But it is not resolved. We could close it as wont-fix.

**Comment by GenevieveBuckley** [comment]
> I agree. But it is not resolved. We could close it as wont-fix.

Sounds reasonable to me. People typically do look at the logs online more often than they download them anyway.
