### ISSUE TITLE
Behavior of selected layer

### ISSUE THREAD

**Issue by AhmetCanSolak** [napari/napari#475]
## ❓ Questions and Help
I have a minor experience concern.

- I think, with current implementation, the relationship between objects on canvas and layers is not intuitive. Like when i add couple images of same size, i can disable top layers to see previously added ones but i cannot move the only top layer and see the layers underneath (even if i select only top layer). Could there be another way to implement this feature?

**Comment by sofroniewn** [comment]
@AhmetCanSolak when you say "move only the top layer" do you mean drag the image on top to reveal the image below as discussed here #299 or do you have something else in mind?

**Comment by AhmetCanSolak** [comment]
Missed #299. sorry to re-issue same thing.
