### ISSUE TITLE
Links to other version of documentation contains invalid entries

### ISSUE THREAD

**Issue by Czaki** [napari/napari#4754]
Another version combo box contains nonexisting versions and links lead to `localhost:3000` 

![Zrzut ekranu z 2022-05-26 10-55-06](https://user-images.githubusercontent.com/3826210/170487799-02fdc608-9a5c-46df-a8d7-41ed727ea084.png)

**Comment by melissawm** [comment]
Thanks for reporting!

**Comment by neuromusic** [comment]
@melissawm is this a sphinx theme issue? if not, we should move it to napari/napari

**Comment by melissawm** [comment]
@Czaki I think this is fixed now, can you confirm? Thanks!

**Comment by Czaki** [comment]
It is solved, but the version switcher is not working properly: 
![Zrzut ekranu z 2022-07-27 22-23-12](https://user-images.githubusercontent.com/3826210/181365336-08b3b130-dc4f-4cc5-97eb-d044a1ab05d3.png)

Should I open a separate issue?

**Comment by melissawm** [comment]
Please comment on #4871 - I'll make sure to make that a priority. Thanks!
