### ISSUE TITLE
Is pyqt5 a dependency? (or: does PySide2 work?)

### ISSUE THREAD

**Issue by clbarnes** [napari/napari#478]
I `pip install napari`'d and tried the simple example

```python
%gui qt5
from skimage import data
import napari
viewer = napari.view(data.astronaut(), multichannel=True)
```

and got 

```
ERROR:root:
    Could not load requested Qt binding. Please ensure that
    PyQt4 >= 4.7, PyQt5, PySide >= 1.0.3 or PySide2 is available,
    and only one is imported per session.

    Currently-imported Qt library:                              None
    PyQt4 available (requires QtCore, QtGui, QtSvg):            False
    PyQt5 available (requires QtCore, QtGui, QtSvg, QtWidgets): False
    PySide >= 1.0.3 installed:                                  False
    PySide2 installed:                                          True
    Tried to load:                                              ['pyqt5']
```

PySide2 is installed, but ipython tried to import pyqt5, which isn't. Installing pyqt5 made it work. Running a napari-based script previously had given me issues re. finding qt; installing pyqt5 seems to have resolved that.

**Comment by sofroniewn** [comment]
Hmm, very odd, can you try pip installing `0.1.3` instead of `0.1.4` and see if the same error happens.

We should be compatible with either `PySide2` or `PyQt5` through our use of `qtpy` (see more info [here](https://github.com/spyder-ide/qtpy)). We are now choosing to depend on `PySide2` and you shouldn't need `PyQt5` at all. I'm worried though that something has crept through on of our PRs that depends on `PyQt5` or that when we added the jupyter console - which is new in `0.1.4` we brought some additional `PyQt5` dependency with us that is causing conflicts. @kne42 do you have any thoughts on this?

**Comment by sofroniewn** [comment]
You should be able to use the environment variable `QT_API` to switch between `PyQt5` and `PySide2` if you have both installed, and on my laptop both work

```
export QT_API="pyside2"
```

**Comment by clbarnes** [comment]
Hm, this may be an ipython issue more than a napari one - the failure is at the `%gui qt5` line. The behaviour is the same with napari 0.1.3 (unsurprisingly, as it's ipython's problem). The ipython version is 7.7.0.

Pip freeze:

```
backcall==0.1.0
cycler==0.10.0
decorator==4.4.0
freetype-py==2.1.0.post1
imageio==2.5.0
ipykernel==5.1.2
ipython==7.7.0
ipython-genutils==0.2.0
jedi==0.15.1
jupyter-client==5.3.1
jupyter-core==4.5.0
kiwisolver==1.1.0
matplotlib==3.1.1
napari==0.1.4
networkx==2.3
numpy==1.17.0
parso==0.5.1
pexpect==4.7.0
pickleshare==0.7.5
Pillow==6.1.0
prompt-toolkit==2.0.9
ptyprocess==0.6.0
Pygments==2.4.2
PyOpenGL==3.1.0
pyparsing==2.4.2
PySide2==5.13.0
python-dateutil==2.8.0
PyWavelets==1.0.3
pyzmq==18.1.0
qtconsole==4.5.2
QtPy==1.9.0
scikit-image==0.15.0
scipy==1.3.1
shiboken2==5.13.0
six==1.12.0
tornado==6.0.3
traitlets==4.3.2
vispy==0.6.1
wcwidth==0.1.7
```

`ipython -c "%gui qt5"` output:

```
ERROR:root:
    Could not load requested Qt binding. Please ensure that
    PyQt4 >= 4.7, PyQt5, PySide >= 1.0.3 or PySide2 is available,
    and only one is imported per session.

    Currently-imported Qt library:                              None
    PyQt4 available (requires QtCore, QtGui, QtSvg):            False
    PyQt5 available (requires QtCore, QtGui, QtSvg, QtWidgets): False
    PySide >= 1.0.3 installed:                                  False
    PySide2 installed:                                          True
    Tried to load:                                              ['pyqt5']
```

I get exactly the same output with `QT_API="pyside2" ipython -c "%gui qt5"`.

This is on python 3.7.3 installed using pyenv on ubuntu 16.04.

**Comment by clbarnes** [comment]
Confirmed, the "script" example works in both a raw python interpreter and an ipython interpreter. Looks like an issue with ipython and pyside2.

**Comment by sofroniewn** [comment]
@clbarnes try `%gui qt` instead of `%gui qt5`, having the 5 in there may force it to look for pyqt5 related things instead of pyside2 related things

**Comment by clbarnes** [comment]
Aha! That seems to be it. Trivial docs change, then.

**Comment by sofroniewn** [comment]
@clbarnes definitely something to fix in the docs, but unfortunately maybe not so trivial - right now on my computer I get errors when I do `%gui qt` due to multiple version conflicts of `qt`, so we'll need to look into this a bit more @kne42: 

```
Class RunLoopModeTracker is implemented in both /anaconda3/lib/python3.7/site-packages/PySide2/Qt/lib/QtCore.framework/Versions/5/QtCore (0x11c2cf120) and /anaconda3/lib/libQt5Core.5.9.7.dylib (0x121378a80). One of the two will be used. Which one is undefined.
objc[21548]: Class QCocoaPageLayoutDelegate is implemented in both /anaconda3/lib/python3.7/site-packages/PySide2/Qt/lib/QtPrintSupport.framework/Versions/5/QtPrintSupport (0x11e1e3478) and /anaconda3/lib/libQt5PrintSupport.5.9.7.dylib (0x11e32eef0). One of the two will be used. Which one is undefined.
objc[21548]: Class QCocoaPrintPanelDelegate is implemented in both /anaconda3/lib/python3.7/site-packages/PySide2/Qt/lib/QtPrintSupport.framework/Versions/5/QtPrintSupport (0x11e1e34f0) and /anaconda3/lib/libQt5PrintSupport.5.9.7.dylib (0x11e32ef40). One of the two will be used. Which one is undefined.
QObject::moveToThread: Current thread (0x7fce15a24f30) is not the object's thread (0x7fce15a4c820).
Cannot move to target thread (0x7fce15a24f30)

You might be loading two sets of Qt binaries into the same process. Check that all plugins are compiled against the right Qt binaries. Export DYLD_PRINT_LIBRARIES=1 and check that only one set of binaries are being loaded.
qt.qpa.plugin: Could not load the Qt platform plugin "cocoa" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: cocoa, minimal, offscreen.
```

glad we got it working for you, and keep letting us know any problems / feature requests etc.
