### ISSUE TITLE
Plugin tests suddenly produce errors in napari-core code

### ISSUE THREAD

**Issue by haesleinhuepf** [napari/napari#4797]
## 🐛 Bug

Hi all,

I'm experiencing a bug in napari on github CI. The detailed error log is [here](https://github.com/haesleinhuepf/napari-segment-blobs-and-things-with-membranes/runs/7270515756?check_suite_focus=true#step:7:99) and these are the last lines of the traceback:

```
if sys.platform.startswith('linux') and running_as_bundled_app():
  .tox/py37-linux/lib/python3.7/site-packages/napari/utils/misc.py:65: in running_as_bundled_app
      metadata = importlib_metadata.metadata(app_module)
  .tox/py37-linux/lib/python3.7/site-packages/importlib_metadata/__init__.py:1005: in metadata
  return Distribution.from_name(distribution_name).metadata
  .tox/py37-linux/lib/python3.7/site-packages/importlib_metadata/__init__.py:562: in from_name
  raiseValueError("A distribution name is required.")
  E   ValueError: A distribution name is required.
```

## Environment

 - Please copy and paste the information at napari info option in help menubar here:
See traceback above

 - Any other relevant information:

## Additional context

The tests were passing until [recently](https://github.com/haesleinhuepf/napari-segment-blobs-and-things-with-membranes/commits/main) and just suddenly stopped working. Any suggestions are appreciated! Thanks

**Comment by haesleinhuepf** [comment]
We have the same issue in other plugins as well aparently:

https://github.com/BiAPoL/napari-stress/issues/93

**Comment by haesleinhuepf** [comment]
I _think_ this is specific to python 3.7. Dropped napari supporting that version officially?

**Comment by haesleinhuepf** [comment]
Answering that question myself: https://github.com/napari/napari/pull/4063

**Comment by haesleinhuepf** [comment]
Confirmed: Removing Python 3.7 from the tests solves the issue. 

Thanks for reading 😄

**Comment by Czaki** [comment]
@haesleinhuepf https://github.com/napari/napari/issues/4747#issuecomment-1173469950
