### ISSUE TITLE
Napari as a plugin depency can break napari conda install

### ISSUE THREAD

**Issue by cnstt** [napari/napari#4800]
## 🐛 Bug

Napari as a plugin dependency can break napari conda install.

## To Reproduce

Steps to reproduce the behaviour:

1. Have a Python 3.9 fresh conda environment on Ubuntu 21.10 and installed napari through conda.
```
conda create -y -n napari-env-testing -c conda-forge python=3.9
conda activate napari-env-testing
conda install -c conda-forge napari
```
3. Install a plugin that has napari in its dependencies.
```
pip install git+https://github.com/deep-finder/napari-deepfinder.git@194fef7d6c87141fdf656b4013dcef3f4c1ff033
```
5. Try to launch napari:
```
napari
```

## Expected behavior

It should not break the conda install, after removing napari from dependencies all works fine.
After having removed the napari dependency, all works fine: when following the same procedure but installing the following plugin version:
```
pip install git+https://github.com/deep-finder/napari-deepfinder.git@7bcc71552458f5c2cd109fd25df0369e7b9cc267
```

**Comment by jaimergp** [comment]
While this is not technically supported, there might be some ways it can work better:

* Use `pip install --no-deps ...` to make sure you are only installing the plugin and provide the dependencies with conda whenever possible
* Try your luck with the experimental [`pamba`](https://github.com/tlambert03/pamba) tool

**Comment by tlambert03** [comment]
The issue here isn't declaring napari in your requirements, (you actually _should_ do that if you directly import napari, and should probably revert https://github.com/deep-finder/napari-deepfinder/commit/7bcc71552458f5c2cd109fd25df0369e7b9cc267), the issue here is that your dependency `deep-finder` is itself [directly depending on PyQt5](https://gitlab.inria.fr/caronsso/deep-finder/-/blob/improve-current-pip/setup.cfg#L41) instead of qtpy.

This is right at the top of the list of "best practices for napari plugins": https://napari.org/plugins/best_practices.html#don-t-include-pyside2-or-pyqt5-in-your-plugin-s-dependencies (and a full explanation for what you're seeing is given there)

You have a few options here:

1. if you want to install `napari-deepfinder` via pip as you've done in your example, then you should _also_ install napari via pip (not via conda).  I would expect that to work.  Note you can still create an environment with conda, just don't use `conda install -c conda-forge napari` ... instead use `pip install napari` before pip installing `deep-finder`
2. If you want to install `napari` via conda, then you should get `napari-deepfinder` and `deep-finder` itself on conda-forge, where it can use the `pyqt` distribution coming from conda.
3. Ideally, since you also have have deepfinder, you would remove `PyQt5` from your explicit dependencies, and instead of `qtpy` as we've done here.  If you'd like, you can add an extra (like `[gui]` or `[pyqt]` the `[all]` extra that we use here) to make it easier for your users to get a fully-ready gui version.

Ultimately, there's nothing napari itself can do here, since we _already_ don't declare pyqt or pyside in our install requirements.  We _do_ ship it with conda, which is why you're seeing this issue, but since conda doesn't support extras, there's no easy way to let someone conda install napari and have it work without including pyqt.

Hope that helped to explain what's going on here.  Since it's not actionable for us, I'm going to close, but feel free to keep the thread going with more questions

**Comment by cnstt** [comment]
Thanks a lot for the detailed answer! I will try to explain my situation for each point :smile: 

> The issue here isn't declaring napari in your requirements, (you actually _should_ do that if you directly import napari, and should probably revert [deep-finder/napari-deepfinder@7bcc715](https://github.com/deep-finder/napari-deepfinder/commit/7bcc71552458f5c2cd109fd25df0369e7b9cc267)), the issue here is that your dependency `deep-finder` is itself [directly depending on PyQt5](https://gitlab.inria.fr/caronsso/deep-finder/-/blob/improve-current-pip/setup.cfg#L41) instead of qtpy.
> 
> This is right at the top of the list of "best practices for napari plugins": https://napari.org/plugins/best_practices.html#don-t-include-pyside2-or-pyqt5-in-your-plugin-s-dependencies (and a full explanation for what you're seeing is given there)

I already know the good practice about PyQt/qtpy in napari, and that's why my plugin itself only has qtpy as a dependency. Unfortunately deepfinder itself needs PyQt for it's own UI elements (not related to the napari plugin). Indeed I could modify it with an extra like [gui] but that's not the top priority at the moment ;)
Especially because I don't think the issue is cause by this dependency. I will explain my issue:
- Installing napari through pip in a fresh virtualenv on ubuntu 21.10 also failed the same way (the same why than after installing my plugin on a conda installation with napari in the dependencies).
- I don't see why I it is important to have napari in the dependencies of a plugin, as it's purpose is to be used as a plugin, so in an environment where napari is already installed.



> You have a few options here:
> 
>     1. if you want to install `napari-deepfinder` via pip as you've done in your example, then you should _also_ install napari via pip (not via conda).  I would expect that to work.  Note you can still create an environment with conda, just don't use `conda install -c conda-forge napari` ... instead use `pip install napari` before pip installing `deep-finder`

As I have written above, the installation via pip fails giving me errors like https://github.com/napari/napari/issues/3686 or others (issue with "xcb")

>     2. If you want to install `napari` via conda, then you should get `napari-deepfinder` and `deep-finder` itself on conda-forge, where it can use the `pyqt` distribution coming from conda.

That could be a good thing, but for the moment haven't found the time to look a this ;)

>     3. Ideally, since you also have have deepfinder, you would remove `PyQt5` from your explicit dependencies, and instead of `qtpy` as we've done here.  If you'd like, you can add an extra (like `[gui]` or `[pyqt]` the `[all]` extra that we use here) to make it easier for your users to get a fully-ready gui version.

Already answered above. This could be a very good improvement for deepfinder! Maybe this is not too much work :thinking: ... If I find the time maybe xD

I hope my post is not too messy and still somewhat understandable. Feel free to ask anything if you have questions :)

**Comment by Czaki** [comment]
@cnstt I cannot reproduce the error on bare metal Ubuntu 21.10. So same version as you report. 
So if you still have an error please attach a stack trace (or another error report). I agree that most probably a source of error is installing PyQt5 again. 

We may try even try to organize debug session on a zulip/zoom/gather to find real source of the problem. 

But first, try to reproduce errors in environments created from scratch. Without any additional plugins. 

And without removing PyQt5 (and maybe pyqtgraph) from deepfinder dependencies you will always have problems. Because the napari bundle works with PySide2 backend, so it creates a bigger problem. 

I do not think that adding `gui` and curating imports is a big problem.

**Comment by tlambert03** [comment]
is your issue just on ubuntu?  I can't reproduce this issue

**Comment by tlambert03** [comment]
> I don't see why I it is important to have napari in the dependencies of a plugin, as it's purpose is to be used as a plugin, so in an environment where napari is already installed.

i understand where you're coming from here.  and it's "fine" if you want to have a package that only works in certain environments.  I guess the main counterpoints are

1. "principle" :)  ... if you import a package, you should list it in your dependencies 
2. ability to declare version: if you eventually use a feature of napari that was introduced after some version, you would have to specify that in your deps
3. A package really should be importable after installation.  We routinely check things like npe2 by installing plugins into their own environments and testing stuff by importing them.  If you can't pip install and then import your top level module, then it's sort of a broken package.  We can (and do) maintain a list of packages that "don't work" without napari, and inject that dependency when we test them, but it would be more "correct" if those packages were importable on their own after installation

**Comment by cnstt** [comment]
> is your issue just on ubuntu? I can't reproduce this issue

On Fedora 36 I haven't had this issue at least. Only when trying on Ubuntu 21.10. (I think MacOS worked, but don't have a MacOS to test it now).

**Comment by tlambert03** [comment]
thanks!  Can you paste what error you get?  It sounds kinda like you're running into the classic xcb missing libraries issue, but it's hard to say without more info (and it's also not clear why that would be the case _only_ when you also install napari).

If your error seems to come from qt, can you also try the following, and paste the output?

```
QT_DEBUG_PLUGINS=1 napari
```

**Comment by cnstt** [comment]
> Can you paste what error you get?

```
WARNING: Could not load the Qt platform plugin "xcb" in "" even though it was found.
14:10:29 WARNING Could not load the Qt platform plugin "xcb" in "" even though it was found.
WARNING: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

14:10:29 WARNING This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Abandon (core dumped)
```

**Comment by tlambert03** [comment]
yeah, now try with `QT_DEBUG_PLUGINS` ... it will likely show you exactly what system library it's missing

**Comment by cnstt** [comment]
> If your error seems to come from qt, can you also try the following, and paste the output?
> 
> ```
> QT_DEBUG_PLUGINS=1 napari
> ```

I get 

```
napari was tested with QT library `>=5.12.3`.
The version installed is 5.9.7. Please report any issues with
```
And a lot of other things, but this is the start and looks to be the most important. An outdated version of Qt seems to be the reason of the issue...

**Comment by tlambert03** [comment]
> And a lot of other things, 

actually, what I'm really looking to see is probably in that big mass of text.  it will usually tell you exactly what `.so` file is missing.  

> The version installed is 5.9.7. Please report any issues with

huh... how did you end up with 5.9.7?  when I follow your environment setup above I don't end up with that.  This feels like an environment setup issue...  Can you run your env setup:

```
conda create -y -n napari-env-testing -c conda-forge python=3.9
conda activate napari-env-testing
conda install -c conda-forge napari
```

and then paste the output of `conda list` (I know it's long... but it would help if we can see it)

and then run `pip install git+https://github.com/deep-finder/napari-deepfinder.git@194fef7d6c87141fdf656b4013dcef3f4c1ff033` and paste the output of `pip list`?

**Comment by tlambert03** [comment]
another question.  if you create a fresh environment, without napari or anything, and simply pip install deepfinder and run _its_ gui... do you not also get these xcb issues?

**Comment by cnstt** [comment]
> > And a lot of other things,
> 
> actually, what I'm really looking to see is probably in that big mass of text. it will usually tell you exactly what `.so` file is missing.
> 
> > The version installed is 5.9.7. Please report any issues with
> 
> huh... how did you end up with 5.9.7? when I follow your environment setup above I don't end up with that. This feels like an environment setup issue... Can you run your env setup:
> 
> ```
> conda create -y -n napari-env-testing -c conda-forge python=3.9
> conda activate napari-env-testing
> conda install -c conda-forge napari
> ```
> 
> and then paste the output of `conda list` (I know it's long... but it would help if we can see it)
> 
> and then run `pip install git+https://github.com/deep-finder/napari-deepfinder.git@194fef7d6c87141fdf656b4013dcef3f4c1ff033` and paste the output of `pip list`?

This time I was creating a virtualenv and installing napari from pip. (which should work...)
But I will retry with a conda env and paste the output of pip list!

**Comment by tlambert03** [comment]
Let me give a little bit of a higher-view summary here to let you know what I'm thinking:

in a fresh ubuntu install, Qt won't actually work without additional libraries.  This is why on github actions, we add this `setup-qt-libs` action that [you use in your tests](https://github.com/deep-finder/napari-deepfinder/blob/7bcc71552458f5c2cd109fd25df0369e7b9cc267/.github/workflows/test_and_deploy.yml#L37).  What that does is install [a bunch of libraries](https://github.com/tlambert03/setup-qt-libs/blob/main/index.js#L13) that are missing on ubuntu that are required to run a Qt GUI.

When you install pyqt from conda it comes with [a ton of pre-compiled libraries on linux](https://github.com/conda-forge/pyqt-feedstock/blob/02b547b15e1f7deedf673d43472e6d2ec1b2ba0a/recipe/meta.yaml#L70-L109), so `conda install pyqt` should "just work" on ubuntu... but those libraries will be restricted to your conda environment.  However, if you pip install PyQt, it _doesn't_ come with those libraries, so usually you will need to install them system wide using something like:

```sh
sudo apt-get install -y libegl1 libdbus-1-3 libxkbcommon-x11-0 \
    libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 \
    libxcb-render-util0 libxcb-xinerama0 libxcb-xinput0 libxcb-xfixes0
```

So, depending on your system libraries, and the order & source from which you've installed pyqt (i.e. from conda and/or from pip), you will usually run into one variant of the missing library issue.

**Comment by cnstt** [comment]
> and then run `pip install git+https://github.com/deep-finder/napari-deepfinder.git@194fef7d6c87141fdf656b4013dcef3f4c1ff033` and paste the output of `pip list`?

Here is the output:
```
Package                       Version
----------------------------- ---------
absl-py                       1.1.0
alabaster                     0.7.12
appdirs                       1.4.4
art                           5.7
asciitree                     0.3.3
asttokens                     2.0.5
astunparse                    1.6.3
attrs                         21.4.0
Babel                         2.10.3
backcall                      0.2.0
backports.functools-lru-cache 1.6.4
bokeh                         2.4.3
brotlipy                      0.7.0
build                         0.7.0
cachetools                    5.2.0
cachey                        0.2.1
certifi                       2022.6.15
cffi                          1.15.1
charset-normalizer            2.1.0
click                         8.1.3
cloudpickle                   2.1.0
colorama                      0.4.5
commonmark                    0.9.1
cryptography                  37.0.4
cycler                        0.11.0
cytoolz                       0.12.0
dask                          2022.7.0
dataclasses                   0.8
debugpy                       1.6.0
decorator                     5.1.1
deepfinder                    1.1.0
distributed                   2022.7.0
docstring-parser              0.13
docutils                      0.16
entrypoints                   0.4
et-xmlfile                    1.1.0
executing                     0.8.3
fasteners                     0.17.3
flatbuffers                   2.0
fonttools                     4.34.4
freetype-py                   2.3.0
fsspec                        2022.5.0
future                        0.18.2
gast                          0.5.3
google-auth                   2.9.0
google-auth-oauthlib          0.4.6
google-pasta                  0.2.0
grpcio                        1.47.0
h5py                          3.7.0
HeapDict                      1.0.1
hsluv                         5.0.2
idna                          3.3
imagecodecs                   2022.2.22
imageio                       2.19.3
imagesize                     1.4.1
importlib-metadata            4.11.4
importlib-resources           5.8.0
ipykernel                     6.15.1
ipython                       8.4.0
ipython-genutils              0.2.0
jedi                          0.18.1
Jinja2                        3.0.3
joblib                        1.1.0
jsonschema                    4.7.1
jupyter-client                7.3.4
jupyter-core                  4.10.0
keras                         2.8.0
Keras-Preprocessing           1.1.2
kiwisolver                    1.4.3
libclang                      14.0.1
locket                        1.0.0
lxml                          4.9.1
lz4                           4.0.0
magicgui                      0.5.1
Markdown                      3.3.7
MarkupSafe                    2.1.1
matplotlib                    3.5.2
matplotlib-inline             0.1.3
mrcfile                       1.4.0
msgpack                       1.0.4
napari                        0.4.14
napari-console                0.0.4
napari-deepfinder             0.0.1
napari-plugin-engine          0.2.0
napari-svg                    0.1.6
nest-asyncio                  1.5.5
networkx                      2.8.4
npe2                          0.5.1
numcodecs                     0.10.0
numpy                         1.23.1
numpydoc                      1.4.0
oauthlib                      3.2.0
openpyxl                      3.0.10
opt-einsum                    3.3.0
packaging                     21.3
pandas                        1.4.3
parso                         0.8.3
partd                         1.2.0
pep517                        0.12.0
pexpect                       4.8.0
pickleshare                   0.7.5
Pillow                        9.2.0
Pint                          0.19.2
pip                           22.1.2
ply                           3.11
pooch                         1.6.0
prompt-toolkit                3.0.30
protobuf                      3.19.4
psutil                        5.9.1
psygnal                       0.3.5
ptyprocess                    0.7.0
pure-eval                     0.2.2
pyasn1                        0.4.8
pyasn1-modules                0.2.8
pycm                          3.5
pycparser                     2.21
pydantic                      1.9.1
Pygments                      2.12.0
PyOpenGL                      3.1.6
pyOpenSSL                     22.0.0
pyparsing                     3.0.9
PyQt5                         5.15.7
PyQt5-sip                     12.11.0
pyqtgraph                     0.12.4
pyrsistent                    0.18.1
PySocks                       1.7.1
python-dateutil               2.8.2
pytomlpp                      1.0.11
pytz                          2022.1
PyWavelets                    1.3.0
PyYAML                        6.0
pyzmq                         23.2.0
qtconsole                     5.3.1
QtPy                          2.1.0
requests                      2.28.1
requests-oauthlib             1.3.1
rich                          12.5.1
rsa                           4.8
scikit-image                  0.19.3
scikit-learn                  1.1.1
scipy                         1.8.1
setuptools                    63.1.0
shellingham                   1.4.0
sip                           6.6.2
six                           1.16.0
snowballstemmer               2.2.0
sortedcontainers              2.4.0
Sphinx                        5.0.2
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
stack-data                    0.3.0
superqt                       0.3.3
tblib                         1.7.0
tensorboard                   2.8.0
tensorboard-data-server       0.6.1
tensorboard-plugin-wit        1.8.1
tensorflow                    2.8.2
tensorflow-estimator          2.8.0
tensorflow-io-gcs-filesystem  0.26.0
termcolor                     1.1.0
threadpoolctl                 3.1.0
tifffile                      2022.5.4
toml                          0.10.2
tomli                         2.0.1
toolz                         0.12.0
tornado                       6.1
tqdm                          4.64.0
traitlets                     5.3.0
typer                         0.5.0
typing                        3.7.4.3
typing_extensions             4.3.0
urllib3                       1.26.10
vispy                         0.11.0
wcwidth                       0.2.5
Werkzeug                      2.1.2
wheel                         0.37.1
wrapt                         1.14.1
zarr                          2.12.0
zict                          2.2.0
zipp                          3.8.0

```

**Comment by tlambert03** [comment]
> PyQt5                         5.15.7

well that time you ended up with an updated version :joy:  ... maybe we can throw this one in the "broken environment" pile?

**Comment by cnstt** [comment]
> well that time you ended up with an updated version :joy: ... maybe we can throw this one in the "broken environment" pile?

This is soo weird :thinking: 
This means I could revert my commit that removed the napari dependency?

**Comment by cnstt** [comment]
> another question. if you create a fresh environment, without napari or anything, and simply pip install deepfinder and run _its_ gui... do you not also get these xcb issues?

Indeed  I encounter also these issues, which are resolved when installing the several indicated things :)

**Comment by tlambert03** [comment]
> Indeed I encounter also these issues, which are resolved when installing the several indicated things :)

great!  Ok, then it sounds like this is settled?  A lesson in the frustrations of using PyQt on ubuntu, and the terrible tangle of pyqt on conda vs pyqt5 on pypi :)

**Comment by tlambert03** [comment]
> This means I could revert my commit that removed the napari dependency?

yeah, I think that was a red herring.  To be sure, it's tricky to coordinate multiple packages that all use Qt (here, napari and deepfinder), but it's possible.  Feel free to ping me over in your own repos if you want help on packaging/installation strategies

**Comment by cnstt** [comment]
Yes and some broken conda environments :thinking: 
It is very frustrating to encounter all these bugs, and I'm really sorry to have made you loose time for this :/

**Comment by Czaki** [comment]
I use pyenv for manage environments. And all try to work on base anaconda env ends with tragedy.

**Comment by Czaki** [comment]
I means, that I use base env only for create separate env using `conda create`. Then work in it.
