### ISSUE TITLE
View -> Toggle Menubar Visibility not reversible with Strg+M

### ISSUE THREAD

**Issue by gatoniel** [napari/napari#4803]
## 🐛 Bug

After deactivating the menubar via View -> Toggle Menubar Visibility or Strg+M it is not possible to recover the menubar with Strg+M.

## To Reproduce

1. Deactivate Menubar via clicking View -> Toggle Menubar Visibility or hitting Strg+M
2. Try to recover the menubar with Strg+M
3. Get stuck with napari without Menubar, and therefore without any other shortcuts...

## Expected behavior

I expect that there is one shortcut with which one can recover the menubar.

 - Please copy and paste the information at napari info option in help menubar here:
napari: 0.4.12
Platform: Windows-10-10.0.22000-SP0
Python: 3.9.5 (tags/v3.9.5:0a7dcbd, May 3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]
Qt: 5.15.2
PyQt5: 5.15.6
NumPy: 1.21.4
SciPy: 1.7.3
Dask: 2021.11.2
VisPy: 0.9.4

OpenGL:
- GL version: 4.6.0 NVIDIA 512.15
- MAX_TEXTURE_SIZE: 32768

Screens:
- screen 1: resolution 2560x1440, scale 1.0
- screen 2: resolution 2560x1440, scale 1.0

Plugins:
- StarDist: 2021.10.25
- napari-3d-ortho-viewer: 0.0.1
- napari-timeseries-opener-plugin: 0.1.dev4+g19acf27
- scikit-image: 0.4.12
- svg: 0.1.5

 - Any other relevant information:
https://github.com/napari/napari/blob/b45dff1de28d4a02d757b31c658fd002bf6de24c/napari/_qt/qt_main_window.py#L600 adds a separate global shortcut (Strg+M) independent of the menubar that is being activated when the visibility is set to false here https://github.com/napari/napari/blob/b45dff1de28d4a02d757b31c658fd002bf6de24c/napari/_qt/qt_main_window.py#L629
But it seems that it does not help. Maybe, this global recovery shortcut Strg+M is overwritten by the local one that disables the visibility. This is defined here https://github.com/napari/napari/blob/b45dff1de28d4a02d757b31c658fd002bf6de24c/napari/_qt/menus/view_menu.py#L42 which is called after setting the global Strg+M shortcut in this line https://github.com/napari/napari/blob/b45dff1de28d4a02d757b31c658fd002bf6de24c/napari/_qt/qt_main_window.py#L608

## Additional context

I actually found this line https://github.com/napari/napari/blob/036931253c2ed26c87ad1b95cdb1c08c15d1e22f/napari/_qt/_tests/test_app.py#L59
in the tests which shows that the test is aware of the fact that the Ctrl+M shortcut is used twice. Maybe some Qt version changes disallowed overwriting shortcuts?

I would suggest to use a different Shortcut for the global recovery, something like Ctrl+Alt+M or to newly create the global shortcut Ctrl+M in the toggle function.
```python
def __init__():
    self._main_menu_shortcut = None

def _toggle_menubar_visible(self):
    if not self.main_menu.isVisible():
        self._main_menu_shortcut.disconnect()  # Something to unregister the  shortcut again
        self._main_menu_shortcut = None

    self.main_menu.setVisible(not self.main_menu.isVisible())

    if not self.main_menu.isVisible():
        # register the new shortcut after the menubar has been disabled
        self._main_menu_shortcut = QShortcut('Ctrl+M', self._qt_window)
        self._main_menu_shortcut.setEnabled(False)
        self._main_menu_shortcut.activated.connect(
            self._toggle_menubar_visible
        )
```

**Comment by Czaki** [comment]
fixed in #4636. Will be available in the next release
