### ISSUE TITLE
[bug] painting options not working

### ISSUE THREAD

**Issue by JoOkuma** [napari/napari#4813]
## 🐛 Bug

Alternative painting options are not working (e.g. alt, shift, control), space does work (pan/move).

Here I tried using them but it just did the default painting, with the exception of the pan/move.

![labeling_options](https://user-images.githubusercontent.com/21022743/179044996-bdfedac0-517c-4fff-ba5a-c4ed5c69aa39.gif)

## To Reproduce

1. open napari
2. create labels
3. draw something
4. try different painting options using the shortcuts

## Expected behavior

For the painting to work as described in the bottom right tips.

## Environment

```
napari: 0.4.16rc2.dev161+g66ffffc2
Platform: Linux-5.15.0-41-generic-x86_64-with-glibc2.17
System: Ubuntu 20.04.4 LTS
Python: 3.8.10 (default, Jun 4 2021, 15:09:15) [GCC 7.5.0]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.20.3
SciPy: 1.7.0
Dask: 2021.06.2
VisPy: 0.10.0

OpenGL:
- GL version: 4.6.0 NVIDIA 510.73.05
- MAX_TEXTURE_SIZE: 32768
```

Screens:
- screen 1: resolution 3440x1440, scale 1.0

**Comment by psobolewskiPhD** [comment]
Related issue:
https://github.com/napari/napari/issues/3926

**Comment by jni** [comment]
See also #4814 — fix might be coming real soon! 🎉

**Comment by psobolewskiPhD** [comment]
> See also #4814 — fix might be coming real soon! 🎉

This is and isn't a fix. 
First, the shortcuts Preference UI (and napari/utils/shortcuts.py) don't permit modifiers alone, like Shift, Control. So while a *different key* can now function as an on-hold modifier, it *can't* be one of those using just #4814 
I've noted this here: https://github.com/napari/napari/issues/5016#issuecomment-1237416747
Ideally, one could set more than one keybind, including just a modifier key for this purpose.

Second, `preserve_labels` isn't presently registered, so no keybind is available for that *incredibly useful* function. I've made a PR:
https://github.com/napari/napari/pull/5017

**Comment by psobolewskiPhD** [comment]
The fix for this will be possible once this PR goes in:
https://github.com/napari/napari/pull/5018
Then you can 1. set the secondary shortcuts and 2. use modifiers like shift, control, etc. as shortcuts.
