### ISSUE TITLE
Close confirm dialog should tell people they can disable dialog through preferences or say never ask again

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#4815]
## 🧰 Task
Like @tlambert03 remarks here https://github.com/napari/napari/pull/4637#issuecomment-1156640165 I have just discovered this behaviour and it also drives me a little nuts. I'm grateful there is a way to disable it through the preferences, but that required me reading the GitHub to discover. It would be nice it the close dialog either told people they can disable in the preferences or even better had an option to "close and never ask again" - cc @Czaki

**Comment by tlambert03** [comment]
Yeah a checkbox would be awesome
