### ISSUE TITLE
Viewer lock up during data access

### ISSUE THREAD

**Issue by d-v-b** [napari/napari#4818]
## 🐛 Bug

Napari locks up completely while accessing data.

## To Reproduce
In this example, I generate a small dask array (should load fast) and a transformed version of that same array where each chunk is delayed by 8 seconds, which should load in a minimum of 8s, potentially more depending on the dask backend. Note that we know in advance the shape and datatype of the slow array. The only slow thing is access to the chunks of the data. 

```python
import napari
import dask.array as da
import time

def slow_func(v):
    time.sleep(8.0)
    return v

data = da.random.randint(0, 10, (10,10), chunks=(1,1))
data_slow = data.map_blocks(slow_func, meta=data)

viewer = napari.Viewer()
viewer.add_image(data)
viewer.add_image(data_slow)

if __name__ == '__main__':
    napari.run()
```

## Expected behavior

Napari should not show the user a black screen while data is being fetched. A layer with slow data should not freeze the entire program. All the UI elements that are independent of the slow data should render, and a "loading data..." status should be indicated to the user.

**Comment by Czaki** [comment]
@andy-sweet is working on implementing async access to data.

**Comment by jni** [comment]
@d-v-b this can't possibly be the first time you encounter this 😂 but tbh I'm not sure that there is a specific issue for it so thanks! 😂 This is a high priority and as @Czaki mentions, @andy-sweet is actively working to fix it.

**Comment by andy-sweet** [comment]
See the tracking issue (#4795) for more details and feel free to comment there.

**Comment by andy-sweet** [comment]
I think closing this seems reasonable. There are known limitations with the current experimental async on main and we also have upcoming work that might supersede it, but closing this issue encourages people to try it out, so we get can more written feedback about problematic and desired behaviors to inform any future implementations.
