### ISSUE TITLE
[Feature] add-or-update layer

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#4822]
## 🚀 Feature
I find myself repeating this chunk of code a lot in various scenarios where I want to create a layer if it doesn't exist, or update it if it does. 

```python
try:
    viewer.layers["my_layer"].data = some_data
except KeyError:
    viewer.add_labels(some_data, name="my_layer")
```

how do @napari/core-devs  feel about a convenience around that?  Useful?  or API creep?

It could be either a new parameter to all of the `add_*` methods (like `replace`, or `clobber` or something) that overrides a layer of the same name if it already exists, rather than doing the magic name changing,  or it could be a new `viewer.add_or_update(data, **kwargs)`

**Comment by alisterburt** [comment]
Super supportive! I slightly prefer the parameter to `Viewer.add_*()` to the new `Viewer.add_or_update()` but wouldn't oppose either :)

**Comment by Czaki** [comment]
I prefer `add_or_update`, where parameters different from data (point and edge colors are treated as data) will be updated only if the layer is created.

**Comment by alisterburt** [comment]
I would expect the opposite behaviour, any parameters specified would also be clobbered on an existing layer...

**Comment by jni** [comment]
Yeah I'm unsure:

> Useful? or API creep?

I think it's both? 😂 @Czaki and I just had a conversation about how enormous our `add_*` function signatures are now, so I am wary of adding yet another parameter. On the other hand `add_or_update` is ugly.

Anyway, I'm weakly in favour of the extra parameter.

**Comment by Czaki** [comment]
> I would expect the opposite behaviour, any parameters specified would also be clobbered on an existing layer...

from my point Is that I return some default view (like colormaps) but if the user decides to change it to better fit his requirements (like colorblindness) then it should not be overwritten. 

But this is connected with only parameters connected to rendering. Many others should be updated.

**Comment by alisterburt** [comment]
@Czaki interesting, I was thinking about it from the point of view of someone using napari interactively who would then think 'oh, why didn't my parameters get set' - both arguments are totally valid and incompatible 😂

**Comment by Czaki** [comment]
After longer think. I do not like additional paremeter to `add_layer` because when I will be reading someone else code the semantic that comes from name of function will mean they here a new layer is created. Using one of ~30 parameters to change semantic will make it harder to understand. 

Having separate name for me will produce more readable code. 

The next thing is that we currently does not have way distinguish if value is provided by user, or is default favlue for `add_*` function. This could be solved by using some wrapper, called for example `Maybe`, that will mark values that should be set only in constructor (it may be also usfull in situation like me and @alisterburt talk, as plugin creator could use it in his own output of plugin).

**Comment by andy-sweet** [comment]
If I understand correctly, the `ViewerModel.add_*` methods mostly pass through the arguments to the corresponding layer type initializer and add the layer the layer list. I think the only exception is `add_image` which has the extra `channel_axis` argument, which we don't like (https://github.com/napari/napari/issues/3019).

I don't like adding an extra parameter like `update` to `ViewerModel.add_*` for two reasons.

1. It adds a parameter that is not passed through to the initializers.
2. It changes the semantics of the method. Right now the method always creates a new layer and appends it to the layer list. After the suggested change, if `update` is `True`, then it will try to update a layer in place, and will fallback to the original behavior.

If it's a useful behavior we should probably add it, but it's also a slightly ugly behavior, so an ugly, explicit name like `ViewerModel.add_or_update_layer` suits it in my opinion and draws attention to the fact that it is doing something different to `ViewerModel.add_*`.

Seems somewhat related to #3005, though that is more magicgui specific. Though that discussion and this one makes me think we might want to define `Layer.update` to handle general in-place mutation of settable properties, as with the `EventedModel`.

**Comment by tlambert03** [comment]
i'm swayed by the argument for `ViewerModel.add_or_update_layer`.

> Seems somewhat related to https://github.com/napari/napari/issues/3005, though that is more magicgui specific.

yeah it's related.  Though I don't really see that as magicgui specific.  magicgui is just one of the things that makes the most use of our `LayerDataTuple` idea... but the idea of representing layers in pure python types (and not forcing someone to import napari to pass napari-compatible data) was a "valued" idea before our magicgui processors took advantage of it. (that issue also showed that different kwargs are sometimes necessary for instantiation vs updating... so that also highlights that simply adding an `update` parameter to `add_*` would probably not work in all cases)

it's also related to [this discussion on zulip](https://napari.zulipchat.com/#narrow/stream/309872-plugins/topic/Giving.20a.20layer.20a.20unique.20name), which also ran into difficulty with the "embedding of semantics" in our Layer Data Tuple concept


..., also I could happily just leave this whole thing as a thing to think about for now (and continue requiring those who want to add-or-update to do their own try/catch) :)

**Comment by sofroniewn** [comment]
> ..., also I could happily just leave this whole thing as a thing to think about for now (and continue requiring those who want to add-or-update to do their own try/catch) :)

I also don't love `update` parameter to `add_*` for reasons named above too.

I don't really love `ViewerModel.add_or_update_layer` right now as it doesn't really match our layer type semantics - i.e. we don't have `ViewerModel.add` or `napari.view`, and then `ViewerModel.add_or_update_image` etc feels like major API expansion. If however we moved towards also supporting `ViewerModel.add` and `napari.view`, then I might support `ViewerModel.update` too. Note these methods would now take a layer type and could match the semantics of something like `LayerDataTuple`. Thoughts?

**Comment by tlambert03** [comment]
Yeah i agree.  I think there's enough to dislike about the concept for now that I'm gonna close this.  Thanks for entertaining the thought everyone! :)
