### ISSUE TITLE
Layer tooltips not working (since v0.4.11)

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#4824]
## 🐛 Bug
Just noticed that #3204 broke #2658 ... (Window no longer even has a `tooltip_menu` attribute anymore)
so this feature has been broken since v0.4.11.  but it was never detected by tests, and it looks like no one has noticed.  @Czaki, is this still a feature that you want to have and fix?  Or does the fact that no one has noticed mean we can trim this one?

**Comment by Czaki** [comment]
![Zrzut ekranu z 2022-07-16 15-55-04](https://user-images.githubusercontent.com/3826210/179357885-372734fd-d833-45e7-a991-2db156ad8c79.png)

Could you explain what you mean when writing that it is not working? This screenshot I do a moment ago on the main branch.

**Comment by tlambert03** [comment]
ah, ok sorry my bad.  At the very least, there's some hanging/stale code in qt main window:
https://github.com/napari/napari/blob/458a7e0f0a15c17fab12cb5ae45cbfc591fa303e/napari/_qt/qt_main_window.py#L634-L637

that's the only reference I can find to `Window.tooltip_menu`

**Comment by Czaki** [comment]
Not only this one. 
I remove few of them in #4817

**Comment by tlambert03** [comment]
(fixed in https://github.com/napari/napari/pull/4817)
