### ISSUE TITLE
Labels layer: Zooming while brush is activated

### ISSUE THREAD

**Issue by haesleinhuepf** [napari/napari#4837]
## 🚀 Feature

It would be cool if the mouse wheel allows zooming in and out while the brush tool is activated on a labels layer.

## Motivation

While annotating small structures on a large image, I'm zooming in and out between drawing lines. It would be cool if this was possible without switching between brush and zoom tool.

## Pitch

When I use the mouse-wheel while the brush is activated, nothing happens. Thus, I presume we could use this input for zooming without harming any preexisting workflow.

## Alternatives

For annotating, we could use the right mouse button while the zoom-mode is on.

**Comment by Czaki** [comment]
Might #4814 be a solution for this issue? Holding 5 will switch mode for a moment.

**Comment by haesleinhuepf** [comment]
I'd like to avoid using the keyboard in case a convenient user interface is possible without. I outlined above how this could be done single-handed.

**Comment by ianhi** [comment]
> When I use the mouse-wheel while the brush is activated, nothing happens. Thus, I presume we could use this input for zooming without harming any preexisting workflow.

fwiw I and I think a few other people have set it up so that scrolling with the brush active modifies the brush size which I find to be very convenient. If I want to zoom then I press and hold space and scroll.

**Comment by haesleinhuepf** [comment]
> fwiw I and I think a few other people have set it up so that scrolling with the brush active modifies the brush size

That's cool, too. How can I get this?



> If I want to zoom then I press and hold space and scroll.

Awesome! I'm learning new things here. Where in the documentation can I find this? Are there more tricks of that kind?

**Comment by Czaki** [comment]
> Awesome! I'm learning new things here. Where in the documentation can I find this? Are there more tricks of that kind?

On the bottom bar of napari when activating brush. 

![Zrzut ekranu z 2022-07-19 18-59-04](https://user-images.githubusercontent.com/3826210/179807715-e92c7dae-465e-4649-85c4-d002407d8365.png)

But other shortcuts are not working and need to be treated from settings.

**Comment by ianhi** [comment]
> That's cool, too. How can I get this?

Feel free to use this callback: https://github.com/Hekstra-Lab/napari-labeller/blob/74913dce72c773df2ec94e1cb3798dd40fedf219/src/napari_labeller/_keybinds.py#L59-L66

**Comment by haesleinhuepf** [comment]
> On the bottom bar of napari when activating brush.

Wow. Indeed. I have never noticed that! Thanks again. And if more people complain that this is not obvious / accessible enough. Consider putting this hint in a more prominent place.

> Feel free to use this callback: https://github.com/Hekstra-Lab/napari-labeller/blob/74913dce72c773df2ec94e1cb3798dd40fedf219/src/napari_labeller/_keybinds.py#L59-L66

How about making this part of napari-core? I mean at the moment, the mouse wheel has no function attached. It would be cool if it had. It would make napari more user-friendly

**Comment by Czaki** [comment]
I try to understand how napari/vispy change wheel behavior base on layer mode. But still have no idea how it works. 

I end in place when it comes to rendering under the mouse.

**Comment by GenevieveBuckley** [comment]
I agree.
It doesn't make sense that you need to use a different method to zoom for image layers vs other layer types. And especially so because the mouse wheel isn't even given another purpose, it just does nothing. 

It would make much more sense if the zoom user interface was consistent across all layer types and modes. I also support the idea of adding to core napari a way to use the scroll wheel plus a modifier key to adjust the brush size when a user is in paint mode.

**Comment by GenevieveBuckley** [comment]
There was a design audit done on napari a quite a while back. My understanding was that it was intended in part to find these kinds of inconsistencies. Perhaps it's worthwhile revisiting that?

**Comment by haesleinhuepf** [comment]
See also:
- https://github.com/napari/napari/issues/2060
- https://www.napari-hub.org/plugins/napari-mouse-controls

![](https://github.com/haesleinhuepf/napari-mouse-controls/raw/main/docs/zoom.gif)

![](https://github.com/haesleinhuepf/napari-mouse-controls/raw/main/docs/windowing.gif)

I'm happy to contribute code from the linked napari plugin to napari core if a core developer guides me where to put it

**Comment by Czaki** [comment]
I may help, but I do not have an idea how should look interface for this (understanding that we will implement these controls in the image control area)
