### ISSUE TITLE
Plugin file extension preferences dialog cut off

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#4840]
## 🐛 Bug

It is not possible to scroll down to edit file extensions for file extension reader preference. Here you can see two showing - but I have many more.

<img width="1035" alt="image" src="https://user-images.githubusercontent.com/6531703/179577001-b061e5ef-20f2-498c-afcc-a9385ea97c85.png">

In general this preference page should be cleaned up - it's not clear what the plugin sort order is now used for too. cc @DragaDoncila @junxini @Lisa-CZI

**Comment by DragaDoncila** [comment]
@sofroniewn thanks for raising, the table is configured to scroll when many items are added but it looks like we've got a size policy issue there. Will look into it.

As for the call order dialog we didn't initially remove it as we still support legacy plugins without conversion. I think technically though, the code paths can't get into a state where the call order is applied, but will have to investigate a bit more.

**Comment by psobolewskiPhD** [comment]
Not sure when this was fixed, but the extensions table does scroll now:
<img width="1284" alt="image" src="https://github.com/user-attachments/assets/d57f65e0-5d89-4e04-9590-5b085072eb49">
@DragaDoncila Do you think we can close?

**Comment by DragaDoncila** [comment]
@psobolewskiPhD yes, let's close. Confirmed on Mac and Linux at least, the scrollbar appears as soon as you add the preference that dips below the horizon so I think this is solved.
