### ISSUE TITLE
FileIO for plugins might be unreliable

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#4843]
## 🐛 Bug

We may have a problem mapping plugins to file extensions - see comment here
https://twitter.com/apoliscope/status/1549074725158227969

<img width="595" alt="image" src="https://user-images.githubusercontent.com/6531703/179579069-5121593b-e6fb-4c0e-a51d-556b1324fa20.png">

I have sporadically encountered some errors myself too the first time i install a plugin and try to load a file. If I go in to the preferences and set things manually then it works, but there might be something funny going on if the file extension has been seen  before and failed.

I'll try and create a reproducible example. cc @DragaDoncila

**Comment by DragaDoncila** [comment]
@sofroniewn thanks for the ping, I'm still travelling this week but will investigate when I'm back home next week (if nobody gets to it first, of course)

**Comment by sofroniewn** [comment]
> @sofroniewn thanks for the ping, I'm still travelling this week but will investigate when I'm back home next week (if nobody gets to it first, of course)

Sounds good @DragaDoncila - the image.sc thread above has a lot of folks looking into this too - it might be unrelated to file extension linking, but still good to look into!! Thanks!!

**Comment by tlambert03** [comment]
Yeah I think this is just an issue aicsimageio conda as I mentioned on the thread

**Comment by tlambert03** [comment]
> Yeah I think this is just an issue aicsimageio conda as I mentioned on the thread 

Should be fixed by https://github.com/conda-forge/aicsimageio-feedstock/pull/17

I'm not sure we need an open issue for this without a reproducible example?

**Comment by sofroniewn** [comment]
Sounds good - will close. If people run into problems associating file extensions reproducibly then we can either reopen or create new issue. Thanks!!
