### ISSUE TITLE
Unable to open anything in napari

### ISSUE THREAD

**Issue by skeltoh** [napari/napari#4850]
## 🐛 Bug

I'm unable to get napari to work at all, with a new install (per instructions, I tried pip and conda, all in new environments). The GUI will open, but it won't open any images. 

## To Reproduce

1. Install napari via conda:
      conda create -n napari -c conda-forge napari
2. Run "getting started code"
```
     from skimage import data; import napari
     viewer = napari.view_image(data.astronaut(),rgb=True)
```
3. Result -> napari opens, blank window. 

1. Install napari via conda:
      conda create -n napari -c conda-forge napari
2. Open gui (seems to open file), open .png file
3. Result -> command line error
```
`~/mambaforge/envs/napari/lib/python3.10/site-packages/napari/components/viewer_model.py:1023: RuntimeWarning: Can't find napari plugin associated with /mnt/f/tmp/test.png files. This may be because you've switched environments, or have uninstalled the plugin without updating the reader preference. You can remove this preference in the preference dialog, or by editing `settings.plugins.extension2reader`
```

1. Install napari via pip:
      conda create -n napari -c conda-forge python=3.9
      pip install napari[all]
     (I have also tried pip+git)
2. Run "getting started code"
```
     from skimage import data; import napari
     viewer = napari.view_image(data.astronaut(),rgb=True)
```
3. Result -> napari opens, blank window. 

## Environment
Conda install:
```
napari: 0.4.16
Platform: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.31
System: Ubuntu 20.04.4 LTS
Python: 3.10.5 | packaged by conda-forge | (main, Jun 14 2022, 07:04:59) [GCC 10.3.0]
Qt: 5.15.4
PyQt5: 5.15.7
NumPy: 1.23.1
SciPy: 1.8.1
Dask: 2022.7.0
VisPy: 0.10.0

OpenGL:
  - GL version:  3.1 Mesa 21.2.6
  - MAX_TEXTURE_SIZE: 16384

Screens:
  - screen 1: resolution 3840x2160, scale 1.0
  - screen 2: resolution 3840x2160, scale 1.0

Plugins:
  - console: 0.0.4
  - napari-svg: 0.1.6
  - scikit-image: 0.4.16
Segmentation fault
```

Pip install:
```
napari: 0.4.16
Platform: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.31
System: Ubuntu 20.04.4 LTS
Python: 3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:58:50)  [GCC 10.3.0]
Qt: 5.15.2
PyQt5: 5.15.7
NumPy: 1.23.1
SciPy: 1.8.1
Dask: 2022.7.0
VisPy: 0.10.0

OpenGL:
  - GL version:  3.1 Mesa 21.2.6
  - MAX_TEXTURE_SIZE: 16384

Screens:
  - screen 1: resolution 3840x2160, scale 1.0
  - screen 2: resolution 3840x2160, scale 1.0

Plugins:
  - console: 0.0.4
  - napari-svg: 0.1.6
  - scikit-image: 0.4.16
Segmentation fault
```

## Additional context

This is within WSL2, with functional GUI apps (e.g., cellpose)

**Comment by GenevieveBuckley** [comment]
Hi @skeltoh, thanks for the report!

Do you get an error message?

Can you open a new napari window with `viewer = napari.Viewer()` and then open a sample image from the menu? File > Open Sample > napari > Astronaut (RGB)

**Comment by Czaki** [comment]
I think that it may be an OpenGL problem. when I try last cellpose does not use OpenGL for rendering.  And when having OpenGL problem on my machine (driver update) it happen that the whole napari window was black.

**Comment by GenevieveBuckley** [comment]
Ii don't think there is any cellpose in the napari environment at all @Czaki 
I think @skeltoh means that they have tested using other GUI software (like Cellpose which [has its own GUI](https://cellpose.readthedocs.io/en/latest/gui.html)) with WSL and that did work.

Please correct me if I'm wrong, @skeltoh

**Comment by psobolewskiPhD** [comment]
I'm going to close this as stale. Not much we can do on our end for a driver issue like this.
