### ISSUE TITLE
Redirect for stable links in the documentation is not working

### ISSUE THREAD

**Issue by melissawm** [napari/napari#4853]
## 📚 Documentation

After the versioning of the docs was merged, we were supposed to have a redirect pointing to `stable` for any of the old links.

For example: `napari.org/usage.html` should redirect to `napari.org/stable/usage.html`

I am investigating, but any ideas for fixing this are welcome!

**Comment by psobolewskiPhD** [comment]
For me macOS 12.6 Safari 16 this works.
https://napari.org/stable/usage.html
goes to 0.4.16 (Stable)
@melissawm can we close this?

**Comment by melissawm** [comment]
Yes, thanks for pinging!
