### ISSUE TITLE
Making zoom function accessible from View menu and hotkey shortcuts

### ISSUE THREAD

**Issue by GenevieveBuckley** [napari/napari#4855]
## 🚀 Feature
Make zoom function accessible from View menu and hotkey shortcuts (Ctrl +/-), in addition to current mouse scroll wheel.

## Motivation
I was unable to zoom in a napari instance running on a remote desktop.

Originally I thought maybe it was something to do with the remote desktop itself not understanding. However, I've since reinstalled napari and the newer version behaves better, so it may have been a bug specific to a particular version. So I hope that this particular problem never comes up again, but it's what sparked a conversation with Nick. We realized that there is in fact no alternative way to control the zoom (eg: through the View menu, or with hotkey shortcuts like Ctrl +/-)

## Pitch

I would like us to add "Zoom In" and "Zoom Out" options to the napari View menu. When activated, they should increase the magnification level by some percentage (25%? What does Fiji or other software choose?).

Additionally, I would like those menu items to be attached to hotkey shortcuts using control plus the `+` and `-` keys.  

## Alternatives

I guess we could keep the status quo, and only use the mouse scroll wheel to zoom

## Additional context

Unrelated to this suggestion, there is a separate conversation here about inconsistencies on zoom behavior across different layer types: https://github.com/napari/napari/issues/4837

**Comment by haesleinhuepf** [comment]
I support this feature request. Fiji users will love it too I presume. 🏝️♥️

**Comment by psobolewskiPhD** [comment]
I met with a user today and they were very strongly in favor of keybinds for zoom.
I'll take a look, shouldn't be too bad?

**Comment by Czaki** [comment]
> I met with a user today and they were very strongly in favor of keybinds for zoom.

If you add this as layer/viewer keybinding, editable in the preferences dialog, it should be ok. If you want to add it as menu (for example using app-model) be ready for conflicts.

**Comment by haesleinhuepf** [comment]
I vote for having all keyboard shortcuts in the menu as well - for improved discoverability.

**Comment by Czaki** [comment]
> I vote for having all keyboard shortcuts in the menu as well - for improved discoverability.

I agree. But we are in the middle of refactor shortcuts and menus are desynchronized. Our plan is to have a single source of shortcuts to avoid collisions and allow edit also menu shortcuts. But it cannot be done quickly.

**Comment by psobolewskiPhD** [comment]
My thought here was to mimic things like terminal and chrome and just have the shortcuts in the View menu:
Command/Control - 0 : Reset Zoom
Command/Control - = : Zoom in 
Command/Control - - : Zoom Out

I don't think these need to be editable do we? But yea, if we want them editable in the Preferences then this would get complex.
These are basically in every app on macOS and appear to be pretty standard on Windows.

BTW: Today I learned you on macOS you can override keybinds on the system level for menu items, even of napari:
<img width="323" alt="image" src="https://github.com/user-attachments/assets/cf27f3c0-532c-422f-a88b-1c47689aaa54">
Note that Toggle Acitivity Dock doesn't have a keybind in napari, but I was able to add it via App Shortcuts.

**Comment by jni** [comment]
> BTW: Today I learned you on macOS you can override keybinds on the system level for menu items, even of napari:

🤯
