### ISSUE TITLE
Names of versions for version switcher

### ISSUE THREAD

**Issue by melissawm** [napari/napari#4871]
## 📚 Documentation

Currently, we have 3 versions available at the version switcher: `latest`, `0.4.16 (stable)`  and `0.4.15`. However, as @kandarpksk pointed out to me:

- For the stable docs, this is the link: https://napari.org/stable/index.html
And this is how it's presented on the page: version 0.4.16 (stable)
- For the latest doc, this is the link: https://napari.org/dev/index.html
And this is how it's presented on the page: version latest

The suggestions is to add rename `latest` to match the URL, or change the URL to match the version name.

Any feedback is appreciated!

(EDIT: as a note, there is currently an annoying issue with the 0.4.15 version name in the switcher, which I'll fix soon)

**Comment by kandarpksk** [comment]
Thanks for making this, Melissa! An alternative design is to say 'version latest (dev)' where the text in parentheses indicates to the stable/dev "channel" if that makes sense.

**Comment by jni** [comment]
I'd also say @melissawm I think we should have "0.4.15", "0.4.16", "stable (0.4.16)", and (say) "development", for the reason @Czaki pointed out: sometimes people are looking for the latest stable docs just to see what to do, sometimes people want a permalink to the current version docs, and they shouldn't have to mess with the URL bar for that.

**Comment by Czaki** [comment]
![Zrzut ekranu z 2022-07-27 22-23-12](https://user-images.githubusercontent.com/3826210/181371808-03683042-8c68-4e23-97f7-c10ac010eb6a.png)

I have found that when I select version 0.4.15 then version selector is showing "Version latest" instead of 0.4.15.

**Comment by kandarpksk** [comment]
Maybe another related issue: I can't remember where I found this link
https://napari.org/tutorials/fundamentals/installation.html#install-as-a-bundled-app

but it redirects to
https://napari.org/stable/tutorials/fundamentals/installation.html

Notice that the anchor is dropped. Is that possibly a browser (Chrome) issue?

**Comment by kandarpksk** [comment]
Aside: Does the "latest" release have a version number that could be shown in the switcher?

**Comment by melissawm** [comment]
@kandarpksk that shouldn't be a browser issue - let me check. Thanks for reporting!

**Comment by kandarpksk** [comment]
Another broken link that may be related to this:
https://napari.org/docs/api/napari.layers.image.html?highlight=translation

Here's the current link:
https://napari.org/stable/api/napari.layers.Image.html?highlight=translation

**Comment by melissawm** [comment]
In this case @kandarpksk I don't this it's related - the `docs` URL has been deprecated some time ago (~1year if I remember correctly) so this link should be updated on the other side. I may be wrong though... (Also - I never realized these links were case sensitive, but it looks like they are as even https://napari.org/stable/api/napari.layers.image.html gives me a 404)

**Comment by melissawm** [comment]
I am closing this as completed - please reopen otherwise. Thanks!
