### ISSUE TITLE
website: text block too narrow

### ISSUE THREAD

**Issue by brisvag** [napari/napari#4873]
## 🐛 Bug
 
If I search `something` on the search bar, the website will look like this:
![image](https://user-images.githubusercontent.com/23482191/181184375-acff1313-f154-447f-bb10-cc25a7e03676.png)

**Comment by jni** [comment]
CC @neuromusic @codemonkey800 

Last time I moved an issue to napari-sphinx-theme I was totally wrong so I'll wait on this one until I get a few more eyeballs on this. 😂

**Comment by brisvag** [comment]
I just checked the dev site and everything seems fine there... So I think we can close this :)
