### ISSUE TITLE
Re-enable make conda bundle test on mac

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#4879]
## 🧰 Task

re-enable the failing ci from napari/napari#4878 ... it would be nice if we could somehow isolate these sorts of tests that fail due to reasons outside of our immediate control

**Comment by Czaki** [comment]
What is the plan o 0.4.17 if this is not fixed before? Lack of OSX bundle or build locally on some of core developer mac?

**Comment by jaimergp** [comment]
Notice that [0.4.16](https://github.com/napari/napari/releases/tag/v0.4.16) didn't have the arm64 builds either (just noticed), and the version tags are wrong (they have a `rc` suffix, when it's not needed).

Also take into account napari/packaging#11 - installers are not being signed on MacOS.

**Comment by Carreau** [comment]
napari/napari#4883 may fix the issue by muting error messages.

**Comment by kandarpksk** [comment]
When I did a conda-forge install, I got version 0.4.14 instead of the newest stable one (0.4.16). Is it the same/related issue, or should I create another one?

EDIT: created napari/napari#4891 based on Czaki's reply.

**Comment by Czaki** [comment]
This is totally different issue, but first idea is that you do not install napari in a fresh environment and some of the already installed packages force conda to use the older napari version.

**Comment by jaimergp** [comment]
Btw team, the fix is ready in https://github.com/napari/napari/pull/4904

**Comment by liu-ziyang** [comment]
before I open a PR to re-enable the tests, how do people feel about dropping the conda build tests from PRs? At the moment they have a somewhat significant false negative rate. I found myself having to rerun failed runs sometimes and it is annoying. I believe the daily runs and main branch merge runs are more than enough to catch early issues if any.

**Comment by Czaki** [comment]
maybe only linux one? 

The main question is if any change in PR may fail to build process and will not be handled by tests run from conda?

**Comment by liu-ziyang** [comment]
> maybe only linux one?
> 
> The main question is if any change in PR may fail to build process and will not be handled by tests run from conda?

I would argue:
1. the false negative rate is too high. Even if people saw the test fail, they would assume it was because of a transient failure.
2. barely any code change touches the build process. The chances of someone did break the building are low. (I would also argue that empirically upstream changes break our build more often than us making code changes)
3. The conda build process is not easily fixable for the time being. The fixing process is probably the same regardless of whether we block the PR or not. For that purpose, I think the daily run is sufficient to catch the problem so we can create an issue to track it.

**Comment by jaimergp** [comment]
Agreed. The main areas we need to watch out for in term of packaging are:

* Dependencies (if `setup.cfg` is modified an issue will be posted, tagging me).
* Entry points / CLI - we do test for successful `napari --info` runs, which loads a few things
* Version strings
* Artifact size

**Comment by liu-ziyang** [comment]
going to close this ticket now that we changed the run frequency
