### ISSUE TITLE
Icon for napari in web-browser

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#4897]
Can we make it so napari logo appears in my web-browser as a little icon instead of the default gray globe when you're at napari.org - like how the github logo appears when you're on github.com

<img width="549" alt="image" src="https://user-images.githubusercontent.com/6531703/182433910-f56f8b58-667a-4fc3-90cf-eedf5d2b47eb.png">

It's just a detail, but i think it's a nice touch :-)

cc @codemonkey800 @melissawm

**Comment by codemonkey800** [comment]
oooh definitely, although I think that's something that should be handled as part of the docs source and not the theme, so it should go into `napari/napari` instead. thoughts?

**Comment by Czaki** [comment]
Agree with @codemonkey800. 

It looks quite simple https://stackoverflow.com/a/54665517/7475772

**Comment by sofroniewn** [comment]
Great - maybe we move this issue over to that repo then. Thanks!!

**Comment by aganders3** [comment]
I'm happy to take this on. Every time I look favicons seem to get more complicated.

At a basic level there is a design choice to be made between a full-color favicon and a silhouette. Here are some screenshots to show what they might look like. I think the full-color version is a bit low-contrast at these small sizes. With the silhouette modern browsers will also support setting a color. This is not currently supported by the sphinx extension linked from the StackOverflow answer above but it wouldn't be too much work to add.

Full-color logo:
<img width="512" alt="Screen Shot 2022-10-03 at 12 34 19 PM" src="https://user-images.githubusercontent.com/1231828/193650790-4c55deb5-bdf1-4c28-82ae-80d60e73831d.png">

Silhouette:
<img width="512" alt="Screen Shot 2022-10-03 at 1 59 51 PM" src="https://user-images.githubusercontent.com/1231828/193650592-ba0a5c80-964f-4ad3-af7a-e2da844139ac.png">

There's also the "apple-touch-icon" which is used when you "save to homescreen" on an iPhone or iPad. I don't suspect this is a common use, but apparently this icon is sometimes used for favicon-like purposes in other applications. If we want this, it looks better to crop the border from the logo. Cropping this border may also help the tab favicon look better in full color.

<img src="https://user-images.githubusercontent.com/1231828/193649756-dae05ff8-0486-4cc9-a3c8-be828702c97d.png" width="256">
<img src="https://user-images.githubusercontent.com/1231828/193649765-6bd9e34c-3363-462b-a1ed-85c45fce3c99.png" width="256">

**Comment by psobolewskiPhD** [comment]
Wowza ❤️ @aganders3 
I love look of the silhouette!
CC: @jni

**Comment by aganders3** [comment]
Thanks! I'll also just note here (mostly a reminder to myself) we may need to consider light/dark mode.

**Comment by aganders3** [comment]
Safari is (as expected) a bit weird/behind so there's a bit of mixed implementation to get this working. On the other hand Chrome supports "themes" and I'm not even going to try to make things work well with that.

In any case here are screenshots of Chrome and Safari in dark and light mode on macOS, and again of the page saved to the home screen on an iPhone. (The black-on-dark Github icon is some Chrome quirk/bug, usually it inverts properly if you go to the tab.)

<img width="768" alt="Screen Shot 2022-10-03 at 9 07 16 PM" src="https://user-images.githubusercontent.com/1231828/193713195-02643984-a9fb-4435-a437-dddc16644e29.png">
<img width="768" alt="Screen Shot 2022-10-03 at 9 05 58 PM" src="https://user-images.githubusercontent.com/1231828/193713201-f35f1451-2eea-4120-8893-81aee73b9cc7.png">
<img width="256" alt="Simulator Screen Shot - iPhone 14 - 2022-10-03 at 21 09 31" src="https://user-images.githubusercontent.com/1231828/193713233-8b1838a0-465a-4626-b700-6c454ca2fc01.png">

If people like the silhouette (I do) I think this is a decent solution and I will open a PR. Unfortunately it does add a doc-building dependency on [sphinx-favicon](https://pypi.org/project/sphinx-favicon/). If that's a problem I can think I can work around it by writing a local Sphinx extension.

**Comment by kevinyamauchi** [comment]
Wow, looks great to me, @aganders3 ! I also prefer the silhouette over the full logo. I am not super up to date on our docs build, but the `sphix-favicon` dependency looks okay to me. From my side, I think a PR would be great!
