### ISSUE TITLE
napari (installed using conda) appears as 'python3.9' in macOS

### ISSUE THREAD

**Issue by kandarpksk** [napari/napari#4910]
In macOS, napari (installed using conda) appears as 'python3.9' in the app menu (left side of the menu bar) and dock icon. It would be a nice touch to see 'napari' there!

PS: maybe it's better in the bundled app (which I haven't tried yet).

**Comment by jaimergp** [comment]
Yes, this little issue should be fixed in the new bundles!

**Comment by psobolewskiPhD** [comment]
@jaimergp Can it also be changed when launching from the terminal or ipython in a non-bundle install?

**Comment by jaimergp** [comment]
@psobolewskiPhD It's tricky... 😂 It took me a while to find out where MacOS takes the app name from and if there's no .app shortcut, it takes the process executable name. One reliable way is to copy the `python` executable to `napari` and then do `napari -m napari` but that's super hacky. ~Symlinks did not work, IIRC.~ They do!

**Comment by liu-ziyang** [comment]
as @jaimergp said, the name "python3.9" is the executable's name, which cannot be changed as far as I am aware. I want to write more on where this python3.9 is picked up from.

when a package that defines a console_script (or gui_script) is installed via pip, pip generates a shebang script that maps the command to the specified entry point in setup.cfg, etc. This shebang script looks like this:
```
#!/opt/homebrew/anaconda3/envs/napari-pyside/bin/python3.9
# EASY-INSTALL-ENTRY-SCRIPT: 'napari','console_scripts','napari'
...
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(load_entry_point('napari', 'gui_scripts', 'napari')())
```

The executable name "python3.9" is picked up from this shebang script. The only way to change the displayed name seems to be having pip compiling this file to an executable binary that does not infer the python executable with a shebang approach.

**Comment by jaimergp** [comment]
Possible solution in #4989!
