### ISSUE TITLE
Example for add_image() in gallery doesn't actually use that API

### ISSUE THREAD

**Issue by kandarpksk** [napari/napari#4911]
## 📚 Documentation

The example for the `add_image` function uses `view_image` instead:
https://napari.org/stable/gallery/add_image.html

**Comment by psobolewskiPhD** [comment]
On a related, but different note:
On Safari (both my 12.4 macOS and my 15.5 iOS) I get the examples repeated like 4x in the list, so it's like 5+ screenfuls of scrolling to actually see the example.
<img width="1202" alt="image" src="https://user-images.githubusercontent.com/76622105/182975232-8aae8298-0934-4060-8878-f75decc8a096.png">
<5+ screenfuls beyond this before I get the example>
Not sure where to report this—separate issue I guess?

**Comment by kandarpksk** [comment]
> On a related, but different note: On Safari (both my 12.4 macOS and my 15.5 iOS) I get the examples repeated like 4x in the list, so it's like 5+ screenfuls of scrolling to actually see the example. Not sure where to report this—separate issue I guess?

Yes, I'd think so. This is a content issue, while yours sounds like something in the template/how the site is coded.

**Comment by lucyleeow** [comment]
This can be closed by #4932
