### ISSUE TITLE
Add shapes layer to prototype

### ISSUE THREAD

**Issue by kephale** [napari/napari#4925]
The output of this task is to modify the [existing prototype PR on napari/napari](https://github.com/napari/napari/pull/4905) to include a shapes layer that supports asynchronous slicing.

**Comment by kephale** [comment]
Working on this one I run into this issue (https://github.com/napari/napari/issues/4674) when trying to generate large `Shapes` layers

**Comment by kephale** [comment]
This PR https://github.com/vispy/vispy/pull/2248 seems to fix both (after updating to upstream main: https://github.com/kephale/vispy/tree/fix-triangulation-ignore-flat):
- https://github.com/napari/napari/issues/4674
- https://github.com/napari/napari/issues/1058

**Comment by kephale** [comment]
Just making a note here that in one instance where I generate 128,000 random shapes with 5 vertices 127,726 are valid for triangulation with the current triangulation implementation.

**Comment by kephale** [comment]
Testing example available here https://github.com/kephale/napari/blob/async-examples/examples/dev/slicing/random_shapes.py

**Comment by liu-ziyang** [comment]
@kephale can you please PR to Andy's branch so we can merge all prototypes to the same place? thanks!

**Comment by kephale** [comment]
I'm changing this to a backlog for now. I had mentioned to @potating-potato that this would be better to do after we get some of the early NAP-4 PRs merged. 

I tested enough that I'm not worried about any major obstacles in supporting the Shapes layer in the real async implementation, but the idea with backlogging this is to save some effort on refactoring.

**Comment by liu-ziyang** [comment]
@andy-sweet now that we are in the implementation phase, do you think there is still value in investing more here? I felt we have a good idea on the shapes layer with the existing branch, and can continue implementation from there instead of spending more time on adding it to the prototype
