### ISSUE TITLE
_dims_order and scale are not consistend in 3D view

### ISSUE THREAD

**Issue by Steffen-Wolf** [napari/napari#4926]
## 3D scaling does not match axis order

Images with non-trivial scale factors are not correctly visualized if (visible) axis order is changed

[A screenrecording of the bug is avalable here](https://user-images.githubusercontent.com/5748117/184362528-536186b4-88db-48da-a3e7-5c5ba483d384.mp4)

## To Reproduce

1. Open a 3D image with a scale factor in napari. For example run:
```
import napari
import numpy as np

if __name__ == "__main__":
        
    with napari.gui_qt():
        data = np.zeros([100, 100, 50])
        
        # create a cube
        data[40:60, 40:60, 20:30] = np.random.rand(20*20*10).reshape(20, 20, 10)
                
        scale = (1, 1, 2)
        viewer = napari.Viewer()
        viewer.add_image(data, name="data", rgb=False, scale=scale)
```

2. Toggle 3D view on
3. Press the "change visible axis order button"

## Expected behavior
Images should be scaled correctly independently of the axis order

## Environment
napari: 0.1.dev2406+g9ea0159
Platform: Linux-5.8.0-53-generic-x86_64-with-glibc2.31
System: Ubuntu 20.04.2 LTS
Python: 3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:58:50) [GCC 10.3.0]
Qt: 5.15.2
PyQt5: 5.15.7
NumPy: 1.23.1
SciPy: 1.9.0
Dask: 2022.8.0
VisPy: 0.11.0

OpenGL:
- GL version: 4.6.0 NVIDIA 450.119.03
- MAX_TEXTURE_SIZE: 32768

Screens:
- screen 1: resolution 1920x1080, scale 2.0

**Comment by andy-sweet** [comment]
Thanks for the well described issue @Steffen-Wolf ! The test case is a really powerful way to check if things work for all possible orders, so I wrote a test exactly like that in #5004. That PR almost fixes things, but there is one case that behaves strangely. That might be due to a fundamental limitation about how napari is doing dimension correspondence right now, but hopefully we can get a full fix in soon!

**Comment by andy-sweet** [comment]
@Steffen-Wolf : should be fixed on `main` now. Feel free to reopen this issue if that doesn't work for you or you find more related weirdness.
