### ISSUE TITLE
DOC Calendar in meeting schedule page empty

### ISSUE THREAD

**Issue by lucyleeow** [napari/napari#4933]
## 📚 Documentation

The calendar on the 'meeting schedule' page is empty. I think https://github.com/napari/napari/pull/4914/ was meant to fix but the dev page still shows an empty calendar: https://napari.org/dev/community/meeting_schedule.html

Related - calendar also seems to appear jumbled in safari: https://github.com/napari/napari.github.io/issues/371

**Comment by lucyleeow** [comment]
Looking at the CI built documentation from https://github.com/napari/napari/pull/4914, the calendar was empty there too.

Could it be a secret problem like here: https://github.com/napari/napari/pull/4176#issuecomment-1055986791 ?

cc @codemonkey800

**Comment by codemonkey800** [comment]
I updated the calendar recently in another PR recently: https://github.com/napari/napari-sphinx-theme/pull/116
and then I made a PR to add the directive option for calendar ID: #4914 

it looks like it works fine on the docs site: https://napari.org/napari-sphinx-theme/demo/kitchen-sink/calendar.html

so I wonder if this is related to the docs versioning. any ideas @melissawm? 🤔

**Comment by lucyleeow** [comment]
I noticed that the calendar ID in the napari sphinx theme docs is not the same as in the napari docs:
sphinx theme:
```
c_35r93ec6vtp8smhm7dv5uot0v4@group.calendar.google.com
```
napari docs:
```
c_35r93ec6vtp8smhm7dv5uot0v4%40group.calendar.google.com
```
could this be the reason?

Also a naive question, is the calendar directive in rst:
```
.. calendar::
```
the same as using this syntax in md:
```
```{calendar}
```
?

**Comment by codemonkey800** [comment]
> c_35r93ec6vtp8smhm7dv5uot0v4%40group.calendar.google.com

hmm this might be the issue actually, the `@` probably got serialized when copying from my chrome address bar

**Comment by lucyleeow** [comment]
It looks like it is working now so maybe it was just the ID that needed to be updated. I think this can be closed now.

https://napari.org/dev/community/meeting_schedule.html
