### ISSUE TITLE
plugin installer bugs

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#4937]
## 🐛 Bug
looks like the plugin installer has accumulated a number of bugs:

- [ ] when uninstalling an npe2 plugin, the warning that pops up has an unclickable "close" button

    https://user-images.githubusercontent.com/1609449/184726352-8321dd46-f326-4fa4-bb74-f25112b769ef.mov

- [ ] When you install a plugin, it no longer moves from the "available" section to the "installed" section (though it _does_ get installed)

   https://user-images.githubusercontent.com/1609449/184726452-d3cc72d3-07eb-4521-a2e5-7a5bfa781490.mov

- [ ] When you uninstall something the available list goes into a permanent clear/refresh loop that needs a restart to fix

    https://user-images.githubusercontent.com/1609449/184726526-8756f0fd-3d48-4902-9268-688b6ec9bcca.mov

**Comment by tlambert03** [comment]
(it might be time for a full refactor there, using #4931

**Comment by psobolewskiPhD** [comment]
I can reproduce all of these on main, macOS 12.6 arm64.
One small detail: for me the 2nd bug `When you install a plugin, it no longer moves from the "available" section to the "installed" section (though it does get installed)` affects only `npe2` plugins. Of course the user has no way of knowing a priori if that's the case. But non-npe2 plugins do list in the available after install. For npe2, a restart of napari is needed.
