### ISSUE TITLE
Changing from 2D from 3D will give an error message and will not show the image

### ISSUE THREAD

**Issue by Micro-Sandworms** [napari/napari#4938]
## 🐛 Bug

The display of an image stack in 2D is correct. When changing to 3D, it does not show and there is an error message:
Cannot SIZE object 39 because it does not exist

I tested this with several stacks and did not always get the error. If cropped to a smaller size, napari was still able to display

## To Reproduce

```python
import numpy as np
import napari

image = np.ones((100, 100, 100), dtype=np.int16)*255
viewer = napari.view_image(image, ndisplay=2)
napari.run()
```

## Environment

napari: 0.4.16
Platform: Windows-10-10.0.19041-SP0
Python: 3.8.2 (default, May 6 2020, 09:02:42) [MSC v.1916 64 bit (AMD64)]
Qt: 5.12.9
PyQt5: 5.12.3
NumPy: 1.18.5
SciPy: 1.6.1
Dask: 2021.04.1
VisPy: 0.10.0

OpenGL:
- GL version: 4.6.0 - Build 30.0.101.1122
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1200, scale 1.0
- screen 2: resolution 1680x1050, scale 1.0
- screen 3: resolution 1280x720, scale 2.0

Plugins:
- console: 0.0.4
- napari-svg: 0.1.6
- scikit-image: 0.4.2

**Comment by Czaki** [comment]
could you provide information about your GPU? It is an intel one?

**Comment by Micro-Sandworms** [comment]
Hi Czaki,

I have two display adapters on this computer:
-	Intel UHD Graphics 620
-	NVIDIA GeForce MX250 

However, I just tried making a fresh env and now it works. If I find out what caused the error (which package), I'll let you know.

Thanks

**Comment by Carreau** [comment]
As this seem to work, I'm going to close. Feel free to reopen (or ask for reopening) if this happens again. 

Thanks.

**Comment by Micro-Sandworms** [comment]
Hi,

I have two display adapters in this computer:

-          Intel UHD Graphics 620

-          NVIDIA GeForce MX250
