### ISSUE TITLE
Points jump in viewer if matplotlib plt.plot() is called first

### ISSUE THREAD

**Issue by mwshinn** [napari/napari#4940]
## 🐛 Bug

The napari viewer jumps around if a plot has been plotted in matplotlib before the first napari window is initialised.  

## To Reproduce

Minimal working example:

```
import numpy as np
import napari
import matplotlib.pyplot as plt

# napari.Viewer(show=False).close() # Uncomment this and the bug disappears

plt.plot([1, 2, 3]) # Does not matter whether plt.show() was called or not

v = napari.Viewer()
v.add_points(np.asarray([[1, 2, 3], [4, 5, 6], [1, 1, 1]]))


```
Now try to drag the viewport in either 2D or 3D.  The points will jump to other positions when the mouse is clicked, and then jump back.  If the mouse is clicked once, the points will jump and stay there until the viewport/canvas loses focus, either from clicking on another widget in napari or from switching to another window.

Uncomment the given line for a workaround.

## Expected behavior

No jumping the viewport should occur on dragging

## Environment

```
napari: 0.4.16
Platform: Linux-4.18.0-17-generic-x86_64-with-glibc2.27
System: Ubuntu 18.04.6 LTS
Python: 3.9.0 (default, Nov 15 2020, 14:28:56) [GCC 7.3.0]
Qt: 5.15.2
PyQt5: 5.15.7
NumPy: 1.20.3
SciPy: 1.8.0
Dask: 2022.7.1
VisPy: 0.10.0

OpenGL:
- GL version: 3.0 Mesa 18.0.5
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1192x670, scale 1.1458333333333333
- screen 2: resolution 2234x1257, scale 1.1458333333333333

Plugins:
- console: 0.0.4
- napari-nikon-nd2: 0.1.3
- napari-svg: 0.1.6
- scikit-image: 0.4.16
```

I am running this directly from the python command on the terminal, not via jupyter/ipython, etc.  It is in a conda environment.

- Matplotlib version 3.4.2 with the Qt5Agg backend using the PyQt5 QT API
- Besides the installed packages, the only non-default customisation of my conda environment is setting the QT_FONT_DPI environment variable, but this does not seem to make a difference for this bug

**Comment by psobolewskiPhD** [comment]
Sorry this got neglected for so long, fell trough the cracks.
The good news is, I'm not able to reproduce this using the script in the OP (or in ipython) and napari 0.4.19post1.
I'm going to close, but if it still happens, please re-open or make a new issue.
