### ISSUE TITLE
Support more than 1024 user-defined colors on label layers

### ISSUE THREAD

**Issue by perlman** [napari/napari#4942]
## 🧰 Task

_I'm adding this issue as a placeholder for known technical debt._

The current implementation of mapping user-defined colors to labels is limited to ~1024 unique colors.
This is due to the implementation overloading a Vispy colormap, which is ultimately backed by a 1024-element LUT.

Related: #4935 aims to fix the color aliasing occurring with ~100+ unique colors.

**Comment by jluethi** [comment]
@perlman Very cool that you've found ways to fix this for 100s of unique colors!
For my understanding, with the new implementation: If I provide a dictionary with 20'000 elements as a colormap (1 element for each label object, like in the original issue), but there are only say 900 unique colors there, would you then expect the mapping to work correctly? In that case, one could implement some logic in the plugins using such custom colormaps to limit the number of unique colors that are generated and then not have to worry about such aliasing effects anymore :)

**Comment by perlman** [comment]
@jluethi Yes, your understanding is correct, it's the count of unique colors, not number of labels. You could create your own array of materialized colors and sample from there.

The performance will degrade as you get to a larger number of labels. Hopefully, with a GPU shader, we can help there as well...
