### ISSUE TITLE
Create public API for set canvas size and reset without margin.

### ISSUE THREAD

**Issue by Czaki** [napari/napari#4943]
## 🚀 Feature

It will be nice to have a public API to set the canvas size. Even in public documentation, we show an option to use napari from a notebook to make screenshots. But not always data ratio fit to canvas ratio. Also, screenshot resolution depends on the size of the canvas. 

Because of this, it will be nice to have option to adjust canvas size to data. I think that API for controlling canvas size is better than API for set window size as the second one require knowledge about all docked widget size for a proper calculation. 

During the implementation of this, it may be nice to allow adjust the scale factor for reset view 
https://github.com/napari/napari/blob/9ea0159ad2b690556fe56ce480886d8f0b79ffae/napari/components/viewer_model.py#L311

That should allow adjusting margins for screenshots to reduce postprocessing steep. 

## Motivation

Here discussion with @alisterburt https://forum.image.sc/t/making-napari-canvas-match-data-extents/70720

## Pitch

Add `set_canvas_size` to the viewer model that will resize the main window to get the proper canvas size.

Move `0.95` factor of `reset_view` to function argument to allow better adjust reset margin from python code. 

## Additional context

https://forum.image.sc/t/making-napari-canvas-match-data-extents/70720

**Comment by psobolewskiPhD** [comment]
This sounds great! Somewhat related to https://github.com/napari/napari/pull/4201
where the goal was enabling data only screenshots at full res, with no canvas background.
Being able to set the canvas size to the data and then screenshot would be awesome.

**Comment by aeisenbarth** [comment]
Would the original use case become obsolete with a rendering API suggested in https://github.com/napari/napari/issues/6334?
(I'm also interested in this.)

Otherwise, it can happen that `set_canvas_size` makes the canvas mismatch the Napari window. Should the gap be black (or overflow hidden)? Or should the window size be adjusted? (Which can cause undesired side effects, GUI elements off-screen, window jumping to front.)
