### ISSUE TITLE
Qt version

### ISSUE THREAD

**Issue by hereariim** [napari/napari#4953]
## 🐛 Bug

Hi I tried to install napari in ubuntu 20.04.3.

I think I correctly followed the instruction from [napari installation](https://napari.org/stable/tutorials/fundamentals/installation.html)
But, when the installation is done, I run `napari` in my console and I got this error message :

`User napari was tested with QT library '>=5.12.3'. The version installed is 5.9.7. Please report any issues with this specific QT version at https://github.com/Napari/napari/issues.`

Kindly help me. I will be highly grateful to all of you.
Thank you!
Best

**Comment by Czaki** [comment]
Did you install it from `conda` or `pip` as both versions are in instruction?
Could you please paste information output of `napari --info` command (from terminal)

**Comment by hiroalchem** [comment]
I got the same message too.
I am also getting warnings about Scipy and numpy versions.
I installed with conda. OS is Windows.
I am not sure if there are other problems or not, but it won't start.
```

C:\Users\Hiroki\anaconda3\envs\napari\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.2
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
C:\Users\Hiroki\anaconda3\envs\napari\lib\site-packages\napari\_qt\__init__.py:53: UserWarning:

napari was tested with QT library `>=5.12.3`.
The version installed is 5.9.7. Please report any issues with
this specific QT version at https://github.com/Napari/napari/issues.
  warn(message=warn_message)
c
WARNING: pyqt5 already imported, cannot switch to pyqt5
WARNING:vispy:pyqt5 already imported, cannot switch to pyqt5
napari: 0.4.14
Platform: Windows-10-10.0.19044-SP0
Python: 3.9.13 (main, Aug 25 2022, 23:51:50) [MSC v.1916 64 bit (AMD64)]
Qt: 5.9.7
PyQt5: 5.9.2
NumPy: 1.23.2
SciPy: 1.7.3
Dask: 2022.9.0
VisPy: 0.11.0

OpenGL:
  -   File "C:\Users\Hiroki\anaconda3\envs\napari\lib\site-packages\vispy\app\application.py", line 263, in _use
  -     self._backend = self.backend_module.ApplicationBackend()

Screens:

Plugins:
  - console: 0.0.4
  - scikit-image: 0.4.14
  - svg: 0.1.6
```

**Comment by hiroalchem** [comment]
```
napari was tested with QT library `>=5.12.3`.
The version installed is 5.9.7. Please report any issues with
this specific QT version at https://github.com/Napari/napari/issues.
  warn(message=warn_message)
QObject::moveToThread: Current thread (0x2d031aa5a70) is not the object's thread (0x2d035d5c640).
Cannot move to target thread (0x2d031aa5a70)

qt.qpa.plugin: Could not load the Qt platform plugin "windows" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: direct2d, minimal, offscreen, windows.
```

**Comment by hiroalchem** [comment]
In the conda virtual environment, no error occurred when installing with pip.

**Comment by Czaki** [comment]
Which command did you use for install napari in conda?

In general you have outdated napari version (0.4.14 instead of 0.4.16) and totally outdated qt.

Did you install napari in main conda environment?

**Comment by hiroalchem** [comment]
`conda install -c conda-forge napari`
I saw a solution to the problem of 0.4.16 not being installed with this command somewhere else, so now I'm using
conda install -c conda-forge napari=0.4.16

However, I still have the same problem.

On the other hand,
if I use
`pip install "napari[all]"`,
The problem no longer occurs, so it has been resolved to a point.

**Comment by Czaki** [comment]
@hiroalchem mase on my experience it looks like you try to install napari in `base` anaconda environment. And part of programs shipped by default in `anaconda` requires outdated Qt. And because of this conda decided to not upgrade Qt. 

When you install `PyQt5` from pip it may broke your conda environment tools (like Spyder).

**Comment by hiroalchem** [comment]
@Czaki No, I am working in a newly created virtual environment with conda. However, what came to mind with your suggestion is that I could have simply specified a version such as pyqt5 and installed the new version. I did not check carefully. I will try it again properly later.

**Comment by jaimergp** [comment]
I am seeing this in an Ubuntu 22.04 `aarch64` VM with no 3D acceleration (UTM 3.2.4 running on macOS 11.2.3, Apple Silicon).

1. Create VM from scratch, using Ubuntu 22.04 Server for ARM.
2. `sudo apt update && sudo apt install ubuntu-desktop`
3. Reboot VM
4. Get Miniforge / Mambaforge to install `conda` / `mamba`
5. Create new conda environment with `conda create -n napari-pip python=3.9 pip compilers pyqt`
6. `conda activate napari-pip`
7. `pip install napari`
8. `napari`

Sorry about screenshots, I can't copy text from the VM:


![image](https://user-images.githubusercontent.com/2559438/213318383-831fc97f-0a6e-4776-8418-cc35262f6bb7.png)

![image](https://user-images.githubusercontent.com/2559438/213318448-673be1a9-88be-49e5-93ea-d28b08505181.png)

![image](https://user-images.githubusercontent.com/2559438/213318524-c17335bb-ca69-48ae-a52c-82fcf2eec418.png)

![image](https://user-images.githubusercontent.com/2559438/213318568-4babddd5-971b-497d-8015-b24e2d97764e.png)

![image](https://user-images.githubusercontent.com/2559438/213318596-960d9bb2-f542-4fd3-ba34-d5dd6f4087cc.png)

![image](https://user-images.githubusercontent.com/2559438/213318617-4f2697a3-e858-4cbe-abae-8528ab1662ac.png)

**Comment by hereariim** [comment]
hello, have you already tried this command `pip install napari[all]` instead of `pip install napari`?

**Comment by Czaki** [comment]
He cannot use all as there are no qt5 wheels on pypi. 

It looks like the real error message is hidden, as one of the imports in lines 32 or 33 fails in a silent way. 

https://github.com/vispy/vispy/blob/fcc0139ba9c4e7dc655a663c075e3973f1c73e25/vispy/app/backends/_pyqt5.py#L30-L33 

it comes from warning: `pyqt5 already imported, cannot switch pyqt5`

**Comment by jaimergp** [comment]
Thanks for the tip @Czaki 

It had to do with `QtTest` not being available [in this line](https://github.com/vispy/vispy/blob/7ab945f8573732fb557c0060889d7091cdbd0fb9/vispy/app/backends/_qt.py#L99). After removing it from the import, `napari` can start without issues.

Reported to `conda-forge`: https://github.com/conda-forge/pyqt-feedstock/issues/126

**Comment by psobolewskiPhD** [comment]
I'm going to close as this is an upstream issue.
