### ISSUE TITLE
[Task] Fix mypy path selection and re-enable type checks

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#4956]
## 🧰 Task

https://github.com/napari/napari/pull/4950 disabled mypy checks for now.

The problem appears to be that, for some reason, running `mypy path/to/folder` is no longer restricting mypy to `path/to/folder`.  For example:

```
╰─❯ mypy napari/settings/
napari/_vispy/visuals/clipping_planes_mixin.py:26: error: Argument 2 for "super" not an instance of argument 1  [misc]
napari/_vispy/visuals/clipping_planes_mixin.py:28: error: "_PVisual" has no attribute "_clip_filter"  [attr-defined]
napari/_vendor/experimental/cachetools/cachetools/abc.py:16: error: "Type[DefaultMapping]" has no attribute "__missing__"  [attr-defined]
napari/utils/mouse_bindings.py:19: error: Function "builtins.callable" is not valid as a type  [valid-type]
napari/utils/mouse_bindings.py:19: note: Perhaps you meant "typing.Callable" instead of "callable"?
napari/utils/mouse_bindings.py:20: error: Function "builtins.callable" is not valid as a type  [valid-type]
napari/utils/mouse_bindings.py:20: note: Perhaps you meant "typing.Callable" instead of "callable"?
napari/utils/mouse_bindings.py:21: error: Function "builtins.callable" is not valid as a type  [valid-type]
napari/utils/mouse_bindings.py:21: note: Perhaps you meant "typing.Callable" instead of "callable"?
napari/utils/mouse_bindings.py:22: error: Function "builtins.callable" is not valid as a type  [valid-type]
...
```

once we determine why that is, mypy checks should be re-enabled

**Comment by Carreau** [comment]
See #4960 that renabled mypy on CI with a setuptools workaround. We should likely still fix it for local mypy run.

**Comment by Carreau** [comment]
Maybe dumb questions, but why is typing workflow install as editable ? We don't need an editable install to do that ?

**Comment by tlambert03** [comment]
Not a dumb question! 😂

Let's try without?

**Comment by Carreau** [comment]
Well it did not work... See #4966

**Comment by kcpevey** [comment]
This was fixed in CI with https://github.com/napari/napari/pull/4960 . It looks like the only reason this is still open is to apply the same fix to local mypun runs via pyproject.toml (See comment [here](https://github.com/napari/napari/pull/4960#issuecomment-1220669142)). Can we get consensus from another @napari/core-devs ?
