### ISSUE TITLE
DOC Sidebar ToC missing in gallery examples

### ISSUE THREAD

**Issue by lucyleeow** [napari/napari#4963]
## 📚 Documentation
In the dev version of the docs, the sidebar ToC is missing when you click on any of the gallery examples (https://napari.org/dev/gallery/add_image.html#):

![image](https://user-images.githubusercontent.com/23182829/185561917-4b71a745-8427-490a-a0f3-f06fee3ab884.png)

Sidebar ToC is present in the stable version of the docs (https://napari.org/stable/gallery/add_image.html#):

![image](https://user-images.githubusercontent.com/23182829/185562170-5f57f67b-957d-4fde-87f3-561190596f20.png)

Do you think it could have something to do with https://github.com/napari/napari/pull/4936 @melissawm ?

**Comment by melissawm** [comment]
Yes, probably. I'm not sure if this is something related to the theme or the integration between sphinx-gallery, sphinx-external-toc and the theme. I'll investigate - thanks!
