### ISSUE TITLE
[WIP] Explore ways to make napari-animation work with async prototype

### ISSUE THREAD

**Issue by kephale** [napari/napari#4969]
This task is motivated by [a comment in the NAP's first PR](https://github.com/napari/napari/pull/4892#discussion_r934961214).

The [napari-animation plugin](https://www.napari-hub.org/plugins/napari-animation) is an example of a plugin that relies on the mutation of `Dims.current_step` being synchronous (both with an active viewer and headless). There are likely others too, but it should serve as a good example that we know is well used.

Here are some possible solutions/ideas, but others likely exist.
- Define new async entry points in the API and leave the existing sync ones alone (e.g. `Dims.set_current_step_async`).
- Define a context manager that forces synchronous (or maybe asynchronous?) slicing.
- Define functions like `LayerSlicer.waitUntilIdle` to wait for any pending slicing tasks to be done.

The output of this task should describe a solution with working prototype code. We should probably cover [the examples](https://github.com/napari/napari-animation/tree/main/examples) in the napari-animation repo. We should incorporate the description into the NAP to address the questions and feedback in the original comment and replies.

Edit: Initial text comes from @andy-sweet. Github didn't seem to track the attribution.

**Comment by Czaki** [comment]
A synchronous solution will be best for keeping plugins simple.

**Comment by kephale** [comment]
Edit: I've confirmed this is happening even with the current napari head, so this isn't specific to the async prototype.

This error comes up when running https://github.com/napari/napari-animation with the async prototype (my update of Andy's branch: https://github.com/kephale/napari/tree/async-slice-proto). The video is still generated, but there is no viewer content recorded (although it was rendered in the window).

Note that there is a color change in the UI over the course of the recorded video.

Rendered:




![Image](https://user-images.githubusercontent.com/400105/186158250-0b62266a-0baa-4d72-b534-f585dd1ac088.png)






Recorded:




![Image](https://user-images.githubusercontent.com/400105/186158359-88cd325e-c7cc-4445-928a-4f54a30496b9.png)





```
Rendering frames...
  0%|                                                                                                                     | 0/151 [00:00<?, ?it/s]WARNING : 2022-08-23 08:11:52,191 : MainThread : /Users/kharrington/miniconda3/envs/napari-animation-async/lib/python3.9/site-packages/imageio_ffmpeg/_io.py:547 : IMAGEIO FFMPEG_WRITER WARNING: input image is not divisible by macro_block_size=16, resizing from (3456, 2054) to (3456, 2064) to ensure video compatibility with most codecs and players. To prevent resizing, make your input image divisible by the macro_block_size or set the macro_block_size to 1 (risking incompatibility).
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████| 151/151 [00:20<00:00,  7.50it/s]
DEBUG : 2022-08-23 08:12:12,146 : MainThread : /Users/kharrington/miniconda3/envs/napari-animation-async/lib/python3.9/site-packages/napari/layers/image/_image_slice.py:67 : ImageSlice.__init__
DEBUG : 2022-08-23 08:12:12,146 : MainThread : /Users/kharrington/miniconda3/envs/napari-animation-async/lib/python3.9/site-packages/napari/_vispy/layers/image.py:100 : VispyImageLayer._set_slice : _ImageSliceRequest(ndim=3, ndisplay=2, point=(64.0, 64.0, 64.0), dims_order=[0, 1, 2])
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
File ~/miniconda3/envs/napari-animation-async/lib/python3.9/site-packages/superqt/utils/_ensure_thread.py:31, in CallCallable.call(self=<superqt.utils._ensure_thread.CallCallable object>)
     28 @Slot()
     29 def call(self):
     30     CallCallable.instances.remove(self)
---> 31     res = self._callable(*self._args, **self._kwargs)
        self = <superqt.utils._ensure_thread.CallCallable object at 0x29234c940>
        self._callable = <function QtViewer._on_slice_ready at 0x290108280>
        self._args = (<napari._qt.qt_viewer.QtViewer object at 0x295c03dc0>, <Event blocked=False handled=False native=None source=None sources=[] type='ready'>)
        self._kwargs = {}
     32     self.finished.emit(res)

File ~/miniconda3/envs/napari-animation-async/lib/python3.9/site-packages/napari/_qt/qt_viewer.py:350, in QtViewer._on_slice_ready(self=<napari._qt.qt_viewer.QtViewer object>, event=<Event blocked=False handled=False native=None source=None sources=[] type='ready'>)
    347 # These came from the previous implementation of Layer.refresh.
    348 # Some of these should probably be removed in the future.
    349 layer.events.set_data()
--> 350 layer._update_thumbnail()
        layer = <Image layer 'blobs' at 0x16c0bf4f0>
    351 layer._set_highlight(force=True)

File ~/miniconda3/envs/napari-animation-async/lib/python3.9/site-packages/napari/layers/image/image.py:1106, in _ImageBase._update_thumbnail(self=<Image layer 'blobs'>)
   1104 with warnings.catch_warnings():
   1105     warnings.simplefilter("ignore")
-> 1106     downsampled = ndi.zoom(
        ndi = <module 'scipy.ndimage' from '/Users/kharrington/miniconda3/envs/napari-animation-async/lib/python3.9/site-packages/scipy/ndimage/__init__.py'>
        image = <class 'numpy.ndarray'> (128,) float64
        zoom_factor = (0.25, 0.25)
   1107         image, zoom_factor, prefilter=False, order=0
   1108     )
   1109 low, high = self.contrast_limits
   1110 downsampled = np.clip(downsampled, low, high)

File ~/miniconda3/envs/napari-animation-async/lib/python3.9/site-packages/scipy/ndimage/_interpolation.py:767, in zoom(input=<class 'numpy.ndarray'> (128,) float64, zoom=(0.25, 0.25), output=None, order=0, mode='constant', cval=0.0, prefilter=False, grid_mode=False)
    765 if input.ndim < 1:
    766     raise RuntimeError('input and output rank must be > 0')
--> 767 zoom = _ni_support._normalize_sequence(zoom, input.ndim)
        input = <class 'numpy.ndarray'> (128,) float64
        zoom = (0.25, 0.25)
        _ni_support = <module 'scipy.ndimage._ni_support' from '/Users/kharrington/miniconda3/envs/napari-animation-async/lib/python3.9/site-packages/scipy/ndimage/_ni_support.py'>
    768 output_shape = tuple(
    769         [int(round(ii * jj)) for ii, jj in zip(input.shape, zoom)])
    770 complex_output = numpy.iscomplexobj(input)

File ~/miniconda3/envs/napari-animation-async/lib/python3.9/site-packages/scipy/ndimage/_ni_support.py:67, in _normalize_sequence(input=(0.25, 0.25), rank=1)
     65     if len(normalized) != rank:
     66         err = "sequence argument must have length equal to input rank"
---> 67         raise RuntimeError(err)
        err = 'sequence argument must have length equal to input rank'
     68 else:
     69     normalized = [input] * rank

RuntimeError: sequence argument must have length equal to input rank
DEBUG : 2022-08-23 08:12:12,428 : MainThread : /Users/kharrington/miniconda3/envs/napari-animation-async/lib/python3.9/site-packages/napari/layers/image/_image_slice.py:67 : ImageSlice.__init__
DEBUG : 2022-08-23 08:12:12,435 : MainThread : /Users/kharrington/miniconda3/envs/napari-animation-async/lib/python3.9/site-packages/napari/_vispy/layers/image.py:100 : VispyImageLayer._set_slice : _ImageSliceRequest(ndim=3, ndisplay=3, point=(64.0, 64.0, 64.0), dims_order=[0, 1, 2])
```

**Comment by kephale** [comment]
It looks like the color change is happening in `napari-animation` itself. However, the objects in the viewport should have been multicolored segments instead of all yellow. 

Edit: No. Different issue.

**Comment by kephale** [comment]
The color change issue might be related to https://github.com/napari/napari-animation/issues/110

**Comment by andy-sweet** [comment]
If you pull on the prototype branch, I think the error above should be fixed. But there may be other/new issues!

**Comment by kephale** [comment]
@andy-sweet, this is from the latest napari-animation being run with the latest napari.

```
python ../napari-animation-async/test_async_movie.py
Traceback (most recent call last):
  File "/Users/kharrington/dev/napari-animation-test/../napari-animation-async/test_async_movie.py", line 10, in <module>
    from napari_animation import Animation
  File "/Users/kharrington/dev/napari-animation-test/napari-animation/napari_animation/__init__.py", line 1, in <module>
    from ._hookimpls import napari_experimental_provide_dock_widget
  File "/Users/kharrington/dev/napari-animation-test/napari-animation/napari_animation/_hookimpls.py", line 3, in <module>
    from ._qt import AnimationWidget
  File "/Users/kharrington/dev/napari-animation-test/napari-animation/napari_animation/_qt/__init__.py", line 1, in <module>
    from .animation_widget import AnimationWidget
  File "/Users/kharrington/dev/napari-animation-test/napari-animation/napari_animation/_qt/animation_widget.py", line 16, in <module>
    from .keyframeslist_widget import KeyFramesListWidget
  File "/Users/kharrington/dev/napari-animation-test/napari-animation/napari_animation/_qt/keyframeslist_widget.py", line 1, in <module>
    from napari._qt.containers import QtListModel, QtListView
  File "/Users/kharrington/dev/napari-animation-test/napari/napari/_qt/containers/__init__.py", line 2, in <module>
    from .qt_layer_list import QtLayerList
  File "/Users/kharrington/dev/napari-animation-test/napari/napari/_qt/containers/qt_layer_list.py", line 10, in <module>
    from ._layer_delegate import LayerDelegate
  File "/Users/kharrington/dev/napari-animation-test/napari/napari/_qt/containers/_layer_delegate.py", line 47, in <module>
    from ..qt_resources import QColoredSVGIcon
ImportError: cannot import name 'QColoredSVGIcon' from 'napari._qt.qt_resources' (unknown location)
```

**Comment by andy-sweet** [comment]
That error seems odd as the `napari._qt_.qt_resources` package is in the napari repo, in which `QColoredSVGIcon` is defined. Can you check your installed version to make sure it's there? Maybe there's a python path issue, but I feel like that would cause bigger issues.

**Comment by kephale** [comment]
I did check for it, and the SVG wasn't showing up at the time. I did have some issues with the `napari.__version__` losing the patch version which I started overriding with `SETUPTOOLS_SCM_PRETEND_VERSION` and for some reason 0.4.6 kept coming up. I did things fresh and it seems OK for now.

**Comment by kephale** [comment]
@andy-sweet I do still get this error:
```
WARNING : 2022-08-23 17:42:16,307 : MainThread : /Users/kharrington/miniconda3/envs/napari-animation-async/lib/python3.9/site-packages/vispy/app/backends/_qt.py:234 : Traceback (most recent call last):
  File "/Users/kharrington/miniconda3/envs/napari-animation-async/lib/python3.9/site-packages/superqt/utils/_ensure_thread.py", line 31, in call
    res = self._callable(*self._args, **self._kwargs)
  File "/Users/kharrington/miniconda3/envs/napari-animation-async/lib/python3.9/site-packages/napari/_qt/qt_viewer.py", line 350, in _on_slice_ready
    layer._update_thumbnail()
  File "/Users/kharrington/miniconda3/envs/napari-animation-async/lib/python3.9/site-packages/napari/layers/image/image.py", line 1118, in _update_thumbnail
    downsampled = ndi.zoom(
  File "/Users/kharrington/miniconda3/envs/napari-animation-async/lib/python3.9/site-packages/scipy/ndimage/_interpolation.py", line 767, in zoom
    zoom = _ni_support._normalize_sequence(zoom, input.ndim)
  File "/Users/kharrington/miniconda3/envs/napari-animation-async/lib/python3.9/site-packages/scipy/ndimage/_ni_support.py", line 67, in _normalize_sequence
    raise RuntimeError(err)
RuntimeError: sequence argument must have length equal to input rank
```

With this napari commit 
```commit adc2fb7e797bbff823f599e66611672af3cd46c1 (HEAD -> async-slice-proto, origin/async-slice-proto)
Author: Andy Sweet <andrew.d.sweet@gmail.com>
Date:   Mon Aug 22 16:34:52 2022 -0700

    Disable buggy offset calculation
```

The video recording still completes and the UI is visible in the video, but no image data.

**Comment by andy-sweet** [comment]
@kephale : can you share `test_async_movie.py`? Or can you confirm if this can be reproduced with one of the napari-animation examples?

**Comment by kephale** [comment]
It is one of the napari-animation examples:

```

"""
Display a labels layer above of an image layer using the add_labels and
add_image APIs
"""

from skimage import data
from scipy import ndimage as ndi
from napari_animation import Animation
import napari


blobs = data.binary_blobs(length=128, volume_fraction=0.1, n_dim=3)
viewer = napari.view_image(blobs.astype(float), name='blobs')
labeled = ndi.label(blobs)[0]
viewer.add_labels(labeled, name='blob ID')

animation = Animation(viewer)
viewer.update_console({'animation': animation})

viewer.dims.ndisplay = 3
viewer.camera.angles = (0.0, 0.0, 90.0)
animation.capture_keyframe()
viewer.camera.zoom = 2.4
animation.capture_keyframe()
viewer.camera.angles = (-7.0, 15.7, 62.4)
animation.capture_keyframe(steps=60)
viewer.camera.angles = (2.0, -24.4, -36.7)
animation.capture_keyframe(steps=60)
viewer.reset_view()
viewer.camera.angles = (0.0, 0.0, 90.0)
animation.capture_keyframe()
animation.animate('/Users/kharrington/Documents/demo3D_async.mov', canvas_only=False)

if __name__ == '__main__':
    napari.run()
```

**Comment by andy-sweet** [comment]
I can't reproduce the error with `animateMixed.py` (which seems to be where the above comes from), though the output movie shows nothing in the canvas on the async proto (it works fine on napari's `main`).

Just to double check, can you rerun `pip install -e .` for `napari` in that environment. I'm thinking if you ran into something like [this issue described on Zulip](https://napari.zulipchat.com/#narrow/stream/212875-general/topic/Unable.20to.20launch.20napari.20on.20main/near/294955436) because the error messages refers to `site-packages/napari`, whereas I'd expect the error to show the local install path.

**Comment by kephale** [comment]
This gives me a little bit of funkiness: 

```
% python ../napari-animation-async-1661290317/test_async_movie.py 
Traceback (most recent call last):
  File "/Users/kharrington/dev/napari-animation-async/../napari-animation-async-1661290317/test_async_movie.py", line 10, in <module>
    from napari_animation import Animation
  File "/Users/kharrington/dev/napari-animation-async/napari-animation/napari_animation/__init__.py", line 1, in <module>
    from ._hookimpls import napari_experimental_provide_dock_widget
  File "/Users/kharrington/dev/napari-animation-async/napari-animation/napari_animation/_hookimpls.py", line 3, in <module>
    from ._qt import AnimationWidget
  File "/Users/kharrington/dev/napari-animation-async/napari-animation/napari_animation/_qt/__init__.py", line 1, in <module>
    from .animation_widget import AnimationWidget
  File "/Users/kharrington/dev/napari-animation-async/napari-animation/napari_animation/_qt/animation_widget.py", line 13, in <module>
    from ..animation import Animation
  File "/Users/kharrington/dev/napari-animation-async/napari-animation/napari_animation/animation.py", line 12, in <module>
    from .frame_sequence import FrameSequence
  File "/Users/kharrington/dev/napari-animation-async/napari-animation/napari_animation/frame_sequence.py", line 11, in <module>
    from .viewer_state import ViewerState
  File "/Users/kharrington/dev/napari-animation-async/napari-animation/napari_animation/viewer_state.py", line 8, in <module>
    class ViewerState:
  File "/Users/kharrington/dev/napari-animation-async/napari-animation/napari_animation/viewer_state.py", line 27, in ViewerState
    def from_viewer(cls, viewer: napari.viewer.Viewer):
AttributeError: module 'napari' has no attribute 'viewer'
```

Not sure why that import isn't there, but I can add `import napari.viewer` into `viewer_state.py` to fix it, then I get:

```
% python ../napari-animation-async-1661290317/test_async_movie.py
Traceback (most recent call last):
  File "/Users/kharrington/dev/napari-animation-async/../napari-animation-async-1661290317/test_async_movie.py", line 10, in <module>
    from napari_animation import Animation
  File "/Users/kharrington/dev/napari-animation-async/napari-animation/napari_animation/__init__.py", line 1, in <module>
    from ._hookimpls import napari_experimental_provide_dock_widget
  File "/Users/kharrington/dev/napari-animation-async/napari-animation/napari_animation/_hookimpls.py", line 3, in <module>
    from ._qt import AnimationWidget
  File "/Users/kharrington/dev/napari-animation-async/napari-animation/napari_animation/_qt/__init__.py", line 1, in <module>
    from .animation_widget import AnimationWidget
  File "/Users/kharrington/dev/napari-animation-async/napari-animation/napari_animation/_qt/animation_widget.py", line 16, in <module>
    from .keyframeslist_widget import KeyFramesListWidget
  File "/Users/kharrington/dev/napari-animation-async/napari-animation/napari_animation/_qt/keyframeslist_widget.py", line 1, in <module>
    from napari._qt.containers import QtListModel, QtListView
  File "/Users/kharrington/dev/napari-animation-async/napari-async/napari/_qt/__init__.py", line 53, in <module>
    from .qt_event_loop import get_app, gui_qt, quit_app, run
  File "/Users/kharrington/dev/napari-animation-async/napari-async/napari/_qt/qt_event_loop.py", line 14, in <module>
    from .. import Viewer, __version__
ImportError: cannot import name '__version__' from 'napari' (unknown location)
```

Yet:
```
% cat /Users/kharrington/dev/napari-animation-async/napari-async/napari/_version.py
# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.4.8rc3.dev1092+gadc2fb7e'
__version_tuple__ = version_tuple = (0, 4, 8, 'dev1092', 'gadc2fb7e')
```

**Comment by kephale** [comment]
@andy-sweet yeah, this seems to be something going wrong with the editable installations. Maybe from installing `napari-animation` then installing the editable `napari` after.

**Comment by Czaki** [comment]
@kephale Read linked discussion from zulip. Locate `site-packages` directory for your env and remove `napari` directory inside.

**Comment by kephale** [comment]
Yeah, that is why I was mentioning it. I'm not 100% sure that this was the cause, but it is the most plausible explanation I have for now. But I'm no longer blocked at least.

**Comment by kephale** [comment]
By overriding `napari.layers.Image._is_async` and forcing the layers in the async branch to be treated as synchronous, I can get a rendered output:

<img width="1711" alt="image" src="https://user-images.githubusercontent.com/400105/186441886-0cbae216-9743-4452-b773-aa214d6ec9da.png">

This is clearly still not correct yet.

**Comment by kephale** [comment]
If I run the script incrementally through a prompt, then I get an improved result:

<img width="1425" alt="image" src="https://user-images.githubusercontent.com/400105/186455160-817844af-784e-47ad-88f4-fdfc8358b3fe.png">

Note that:

- the labels in the main napari frame are yellow instead of multicolored
- the thumbnail for the labels layer is correctly multicolored 
- the recorded video is grayscale, but has reasonable shading now

**Comment by kephale** [comment]
The issue of image data being rendered with a yellow color is present in 2D as well:

<img width="1421" alt="image" src="https://user-images.githubusercontent.com/400105/186456790-53c15eac-ee5c-44cc-a773-0cd0688cb712.png">

**Comment by kephale** [comment]
@andy-sweet I am guessing this might be an actual issue with the current async implementation and the way labels are rendered, but I'm still looking.

**Comment by andy-sweet** [comment]
Yeah, I think that's my best guess too. Though if you're overriding `_is_async`, then it should be following the old path. My changes to `_ImageBase` could definitely have still broken things though.

**Comment by andy-sweet** [comment]
Yep, just running `python examples/add_labels.py` shows that same issue. Though defining `Labels._is_async` to return `False` fixes it for me.

**Comment by kephale** [comment]
Arr yes, I was just overriding for `Image`. Indeed, this works when async is disabled for `Labels` as well. Phew.

**Comment by alisterburt** [comment]
loving watching this from afar @kephale and @andy-sweet !

> Define a context manager that forces synchronous (or maybe asynchronous?) slicing.

I think I like this option the most :)

**Comment by kephale** [comment]
It looks like a promising strategy so far!

**Comment by kephale** [comment]
Saving some notes here to make this easier to revisit later:

# How napari-animation works

napari-animation works with napari by applying a set of `Viewer` atttributes (from `Dims` and `Camera`) over a sequence of frames and generating a screenshot for each frame<sup hidden><a id="fnr.1" class="footref" href="#fn.1" role="doc-backlink">1</a></sup>.

1.  Updating Dims is an event that triggers a canvas update, which becomes asynchronous with the async slicing prototype.
2.  Actual screenshot acquisition happens at the QT level, and there is no check if the current canvas is stale or not.


# Feedback

Suggested change: either (1) viewer.screenshot() should check if async threads are complete, or (2) async threads should always be complete when viewer.screenshot() is evaluated. 

If screenshots are working in the async branch ****and**** there are no major changes to `Viewer` attributes, then napari-animation is likely to still run but would still need the above suggested change.


# Bugs found

-   Labels layer is not rendered correctly (wrong colors): <https://github.com/napari/napari/issues/4969#issuecomment-1225862463> (Resolved: <https://github.com/napari/napari/pull/4905/files/adc2fb7e797bbff823f599e66611672af3cd46c1..6740474f72ebbdcc75f2284f7c509dcd44e80a28>)
-   Bug in napari-animation on M1: <https://github.com/napari/napari-animation/issues/123> (Resolved: https://github.com/napari/napari-animation/pull/126)


## Footnotes

<sup hidden><a id="fn.1" class="footnum" href="#fnr.1">1</a></sup> <https://github.com/napari/napari-animation/blob/d0d5778cf37f191d53934eeff18f7a455049fafd/napari_animation/viewer_state.py#L58>

**Comment by andy-sweet** [comment]
I think that waiting for slicing threads to be done in `Viewer.screenshot` is an attractive solution that also hits some other usage of screenshot in scripts. The main problem is that we don't actually want to take a screenshot until we've set the new vispy node data, which must necessarily happen on the main thread. Assuming `screenshot` is called on the main thread, then it won't have been set yet and it can't wait for that be done (because the two tasks occur on the same thread).

So, I think the preferred technical approach is to force slicing to be synchronous at the time when attributes/properties/fields like `Dims.current_step` or `Camera.zoom` are changed - that way we can wait for everything to be done on the main thread before calling `screenshot` or similar. Initially that should probably be the default behavior, but if that ever changes, we should consider adding something like `ViewerModel.sync_slicing` that would return a context manager to force that behavior.

**Comment by kephale** [comment]
FWIW, in sciview we actually ended up making screenshots async.

**Comment by andy-sweet** [comment]
Thanks for all the work here @kephale!

Do you think there's any extra work needed to close this issue? The write up in [the previous comment](https://github.com/napari/napari/issues/4969#issuecomment-1230729769) is probably enough for me. I also incorporated this investigation into the latest version of the async slicing NAP.

I also [added the context manager approach to the prototype PR](https://github.com/napari/napari/pull/4905/commits/2bd9a159c633acc702c01fc76a9d4ddfd7b71c6e). Maybe it would be worth trying that out? I tried it from the console quickly with success, but have not tried to modify napari-animation to make it work.

**Comment by kephale** [comment]
Great. I'm happy to close this one now.
