### ISSUE TITLE
Add turbo colormap to Napari

### ISSUE THREAD

**Issue by henrypinkard** [napari/napari#497]
## 🚀 Feature

A group at Google has created a rainbow colormap that shares some of the desirable properties of inferno/viridis/etc., but is slightly better for visualizing very dim and very bright features. You can read about it more [here](https://ai.googleblog.com/2019/08/turbo-improved-rainbow-colormap-for.html). I think this would be a very useful addition to Napari (which, btw is awesome, thank you!)

**Comment by sofroniewn** [comment]
@henrypinkard yes, we were talking about that the other day. We'd love to have it in there. Would you like to make a PR adding it? We can guide you through the process if you get stuck

**Comment by henrypinkard** [comment]
In theory, yes, but realistically I would likely triage it for at least a few months as I have no urgent need for it

**Comment by sofroniewn** [comment]
No worries, if someone else wants to start working on it in the meantime they can post here, otherwise we'll get to it when we get to it. It should be pretty easy to add here https://github.com/napari/napari/tree/master/napari/util/colormaps
