### ISSUE TITLE
Add github actions check for validate if some files that should be in LFS are stored directly in repository

### ISSUE THREAD

**Issue by Czaki** [napari/napari#4973]
## 🚀 Feature

It will be nice to have GitHub action that will perform check on PR if this PR contains a file that would be stored in LFS but is stored directly in the repository.

## Motivation

https://github.com/napari/napari/pull/4961

## Alternatives

core dev needs to remember about LFS.

**Comment by andy-sweet** [comment]
This is one option I looked into: https://github.com/andy-sweet/napari/pull/1

But I put it on hold given the flux of git-lfs and the two-repo solution.

**Comment by Czaki** [comment]
Yes, but this checks file sizes, not match to extensions (I think that both are important).

**Comment by Carreau** [comment]
```
$ cat <(find . -name '*.png'|sed 's/\.\///g') | grep -v -f <(git lfs ls-files -n | grep '.png'|sort )
napari/resources/logo.png
docs/developers/documentation/images/doc-ci-2.png
docs/developers/documentation/images/doc-ci-3.png
docs/developers/documentation/images/doc-ci-1.png
```

Will give us the png files in the repo that are not in LFS. `find` adds. a `./` at the path, hence the sed. `-n` ask ls files.

We then need to find how to make that fail if there are more than one line.

**Comment by Czaki** [comment]
but this solution also doe not use gitattibutes, so requires a manually curated list of extensions. But is really nice and may be a good starting point.

**Comment by melissawm** [comment]
Fortunately, I don't think this is necessary anymore. Feel free to reopen otherwise!
