### ISSUE TITLE
"napari Code of Conduct - How to follow up on a report." link broken

### ISSUE THREAD

**Issue by kevinyamauchi** [napari/napari#5001]
## 📚 Documentation
The "[napari Code of Conduct - How to follow up on a report.](https://github.com/napari/napari/blob/main/docs/developers/code_of_conduct_reporting.md)" link at https://napari.org/stable/community/code_of_conduct.html#incident-reporting-resolution-code-of-conduct-enforcement currently gives 404.

**Comment by psobolewskiPhD** [comment]
The link to the scipy Code of Conduct listed below in Endnotes (https://napari.org/stable/community/code_of_conduct.html#endnotes) is also broken. Should be:
http://scipy.github.io/devdocs/dev/conduct/code_of_conduct.html
Also, the link to `Resolutions` here:
`4. enforcement via transparent decision (see [Resolutions](https://github.com/napari/napari/blob/main/docs/REPORT_HANDLING_MANUAL.md#resolutions)) by the Code of Conduct Committee`
is also broken. Should be: `https://napari.org/stable/community/code_of_conduct_reporting.html#resolutions`
