### ISSUE TITLE
add Surface layer for easy 2D / 3D mesh rendering

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#502]
## 🚀 Feature
Following this discussion on twitter - https://twitter.com/TrackingActions/status/1168040048664530949

I propose we add a new layer type `Surface` with a corresponding `add_surface` method that allows you to easily render a 2D or 3D mesh with certain colorings / shadings.

We can take inspiration for this from the MRI neuroimaging community that frequently wants to render surface plots of the brain - see here for an example API from a tool in that space https://nilearn.github.io/modules/generated/nilearn.plotting.plot_surf.html

Here there are 3 core input args - `surf_mesh` which is a pair or arrays, one with vertices and one with faces. This maps identically to vispy mesh visual. Then theres `surf_map` and `bg_map` which contain value information for coloring (either with a custom colormap / grayscale) - at the vertex level, which can be mapped to either `vertex_colors` or `vertex_values` in a vispy mesh visual (which also has `face_colors` too).

Using that tool one can generate plots like this:
![image](https://user-images.githubusercontent.com/6531703/64080658-871fe880-ccab-11e9-850c-b88b766591be.png)

This layer type is similar to our `Shapes` layer in some respect, but will be much simpler as there won't be interactivity, and should scale well to very large meshes. I think it would be awkward also to force the user to use a `Shapes` layer when all they want to do are display surfaces.

As to api - how do people feel about `data` being a tuple of (vertices, faces), or is that just confusing, and you'd rather have separate keyword args for both? Also do we want to expose both coloring by vertex / coloring by face or just one? I think we might need to just play around to see what feels right.

Thoughts @royerloic @jni?

**Comment by sofroniewn** [comment]
A followup thought is how we should best handle timeseries of meshes. One simple option is to have the vertices be NxD where the data is then `D` dimensional and use the rest of our machinery to handle the slicing. This allows for the meshes to change over time which could be useful for some applications, but I also imagine there will be cases where the meshes are fixed `Nx3` but what changes over time are the color values. That data can be reformatted into the `NxD` case, which might be our best / most general approach.

Curious what @freeman-lab thinks too, and also if @danlurie has any thoughts as it was his initial comment that prompted this thread.

**Comment by danlurie** [comment]
I've uploaded the surface data that I used in my example: https://gist.github.com/danlurie/891bd6c42ec2edd468b82976ad2fdb5a

(Example notebook here: https://gist.github.com/danlurie/691d0cea1b2c74b227e11d32147e9823)

**Comment by sofroniewn** [comment]
see #503 for beginnings of an implementation

**Comment by royerloic** [comment]
@sofroniewn This is great! Good that the current API matches vispy, as it also matches what OpenGL ingests which means speed... Would not be a bad ideas to have key-values for data, as we could add other per-vertex or per-face elements such as normals, texture coordinates, etc... In that case tuples might be brittle long-term. also the keys provide a form of explicit documentation that is in general useful... 
For n-dimensional support, the approach you outline is fine and useful...  One thing: To be able to change the faces over time might be useful too... in the case that remeshing is needed for large surface deformations...
