### ISSUE TITLE
Add reference of layer duplication to `Layer.source` 

### ISSUE THREAD

**Issue by alisterburt** [napari/napari#5023]
## 🧰 Task

Based on discussion in #5010, it would be great to have a way to know that a newly inserted layer is a duplicate rather than a brand new layer. This should be added to our `Source` object which currently tracks the provenance of layers 

https://github.com/napari/napari/blob/3531441de2ee581f9f9da4414c03ae26a49c1441/napari/layers/_source.py#L11-L43

It looks like the fact that source deepcopy is overriden may need to be revisited if the duplicated layer has a different source

**Comment by alisterburt** [comment]
cc @mstabrin @brisvag

**Comment by mstabrin** [comment]
I added a new implementation possibility utilizing the Source class.

**Comment by psobolewskiPhD** [comment]
I think we can consider this closed by https://github.com/napari/napari/pull/5028
There is another issue for further discussing `Source.parent`
