### ISSUE TITLE
pytest not catching errors in event callbacks

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#504]
## 🐛 Bug

As noted during #498 pytest is not catching any errors that are inside callbacks triggered by our events. To note this you can put any trivial error inside on of our callbacks (for example a new undefined variable) and this will not cause the test to fail, even though this code is getting run and causing an error.

I'm not sure how to fix, but maybe @kne42 or @jni knows?

**Comment by sofroniewn** [comment]
So I've figured out the reason for this is the following line in our event emitter class
https://github.com/napari/napari/blob/3803e0ad0e8c89089bfdf00269717a779c22de4b/napari/util/event.py#L245

which currently ignores all callback errors. I think this is good behavior for when we're actually running `napari` as it maybe lets us recover from some errors, but it's definitely very bad from a testing standpoint.

What are peoples thoughts? Do we want to set to be `False` always? Or only set to `False` when testing? I'm open to suggestions

**Comment by sofroniewn** [comment]
I'll note that we have currently have 6 tests that only fail with this set to `False` (all introduced in #498) around `dtypes` and vispy (and now easily fixed, but previously invisible)

**Comment by jni** [comment]
Why do we want to allow errors in callbacks ever? Errors should *never* silently pass. At an absolute minimum they should be printed in stderr. Better, expected errors should be specifically caught and handled.

**Comment by sofroniewn** [comment]
Ok, I will change this to `False` and then fix the tests :-)

**Comment by sofroniewn** [comment]
closed by #505
