### ISSUE TITLE
Duplication of comments with link to documentation

### ISSUE THREAD

**Issue by Czaki** [napari/napari#5055]
## 🐛 Bug

The nice feature to provide the direct link to documentation with styles is added in #5014. But when the next commit is pushed, a new comment is added that makes it harder to trace discussions. 

The comment should be edited or removed. 

## To Reproduce

https://github.com/napari/napari/pull/5054#issuecomment-1241788104

![obraz](https://user-images.githubusercontent.com/3826210/189340371-ef6b5d0d-ff4a-4eae-ac07-e48a8eb753f6.png)

## Expected behavior

should be only one comment with a link to the documentation.

**Comment by melissawm** [comment]
Thanks @Czaki  - I think there is a way to fix that by deleting the old comments as soon as the new one is posted. I`ll investigate and submit a PR :+1:

**Comment by goanpeca** [comment]
https://github.com/tonyhallett/artifacts-url-comments/issues/79

>Hi. It's been some time since I looked at GitHub actions. Too busy to look into at the moment.

We could look into another action, or run a workflow that deletes all comments that have specific text in it, except the last one

**Comment by melissawm** [comment]
Do we want to delete or hide the comments?

- [here's an example of hiding](https://github.com/betaflight/blackbox-log-viewer/pull/591)
- [action for hiding a comment with the artifacts link](https://github.com/betaflight/betaflight/blob/2615645f52a6a099b8eb1ae6f72f2c9b8359627d/.github/workflows/hide-artifact-links.yml)

**Comment by Carreau** [comment]
I think you should update the existing comment instead of posting the new one, or use something like https://github.com/marketplace/actions/github-status-action that put the download link the the status at the bottom. Because this is not only adding comments in the issue, but sending mails, and personally this + assign author action is filling up my mailbox.

**Comment by Czaki** [comment]
Agree with @Carreau This comment storm is terrifying in the context of notifications.

**Comment by Carreau** [comment]
I think we might even be able to edit the PR description to avoid
notifications completely.
