### ISSUE TITLE
Gallery ToC shows both tags and individual examples

### ISSUE THREAD

**Issue by chili-chiu** [napari/napari#5057]
## 📚 Documentation
After merging PR #4975 we now have both tags and the original example list shown on the left-hand side
<img width="526" alt="image" src="https://user-images.githubusercontent.com/89602983/189409870-1966f602-6f33-4bc1-bc8a-c7ec356fbcac.png">
Since we can already browse all examples with image tiles, removing the text list and only keeping the tags could make the navigation cleaner.

**Comment by melissawm** [comment]
Awesome this actually makes it simpler since that is the default for sphinx-gallery. Will update soon!
