### ISSUE TITLE
Changing current viewer property (e.g. theme) becomes persistent change of settings

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari/napari#5062]
## 🐛 Bug

If you want to change the theme, for example, for the current viewer you can do:
`viewer.theme = 'light'`
This works nicely, but actually will change the *setting* so that if System or Dark was set in the settings, it will be overwritten. This is annoying in the case of an example script, as discussed here:
https://github.com/napari/napari/pull/4875#issuecomment-1243019620

But in general, it's counter intuitive that changing the *current* viewer will change all future viewers. If the user wants to change the setting they certainly can, using either the GUI Preferences or using `get_settings().appearance.theme = 'light'`

## To Reproduce

1. open a viewer
2. open the console
3. enter:
```
from napari.settings import get_settings
get_settings().appearance.theme
```
4. If this prints Dark or System enter:
```
viewer.theme = 'light'
```
else if it prints Light, then enter
```
viewer.theme = 'dark'
```
6. Watch the theme of the current viewer change. Now enter:
```
get_settings().appearance.theme
```
7. You will see the setting is changed. You can confirm the issue by checking Preferences > Appearance

## Expected behavior

Changing the theme of the *current* viewer should not change the user settings.
So using `viewer.theme = 'light'` should change the current theme of the viewer, but `get_settings().appearance.theme` should not report a change.
 
## Environment

 ```
napari: 0.4.16rc2.dev280+g332860f9
Platform: macOS-12.5.1-arm64-arm-64bit
System: MacOS 12.5.1
Python: 3.9.13 | packaged by conda-forge | (main, May 27 2022, 17:00:33)  [Clang 13.0.1 ]
Qt: 5.15.3
PyQt5: 5.15.4
NumPy: 1.22.4
SciPy: 1.8.1
Dask: 2022.6.0
VisPy: 0.11.0

OpenGL:
  - GL version:  2.1 Metal - 76.3
  - MAX_TEXTURE_SIZE: 16384

Screens:
  - screen 1: resolution 1680x1050, scale 2.0

Plugins:
ERROR:npe2.manifest.schema:napari.manifest -> 'napari' could not be imported: Cannot find module 'napari_builtins' declared in entrypoint: 'napari_builtins:builtins.yaml'
  - bfio: 2.3.0 (4 contributions)
  - napari: 0.4.16rc2.dev280+g332860f9 (77 contributions)
  - napari-aicsimageio: 0.7.2 (2 contributions)
  - napari-assistant: 0.3.8 (2 contributions)
  - napari-console: 0.0.4 (0 contributions)
  - napari-pyclesperanto-assistant: 0.18.4 (51 contributions)
  - napari-skimage-regionprops: 0.5.2 (2 contributions)
  - napari-svg: 0.1.6 (2 contributions)
  - napari-time-slicer: 0.4.7 (2 contributions)
  - napari-tools-menu: 0.1.15 (0 contributions)
  - ome-types: 0.3.0 (4 contributions)
  - stardist-napari: 2022.6.7 (8 contributions)
  ```

## Additional context

N/A

**Comment by psobolewskiPhD** [comment]
I'll add another aspect to this issue:
Changing the theme of one viewer changes the theme of all viewers.
Try:
```
import napari

viewer1 = napari.Viewer()
viewer2 = napari.Viewer()

viewer2.theme = 'dark' # or light, whatever is opposite of your current theme
```
Both viewers will change to dark.

**Comment by Czaki** [comment]
> Both viewers will change to dark.

@psobolewskiPhD Yes. This is intentional and allows us to simply style additional windows (opened ex from the viewer) and keep synchronizing with the main window. 

Also, this allows the user to change the theme from the menu and keep it after the restart. I think that case when the user needs to change the theme each time after starting napari (until discovering settings - remind discussion about interface from #5127).

When I think about this, maybe a better solution could be properly separating settings between different python environments. What did you think?

**Comment by psobolewskiPhD** [comment]
> > Both viewers will change to dark.
> 
> @psobolewskiPhD Yes. This is intentional and allows us to simply style additional windows (opened ex from the viewer) and keep synchronizing with the main window.

Newly opened viewers use the theme setting, so they will be the same regardless. I get synchronization and I know I'm not the smartest user, but if I'm saying `viewer2.theme = 'light'` that means I want `viewer2` to change themes—maybe for a screenshot with `minimum` blending or a comparison, whatever. If I wanted `viewer1` to change, I would have done that.

> Also, this allows the user to change the theme from the menu and keep it after the restart. I think that case when the user needs to change the theme each time after starting napari (until discovering settings - remind discussion about interface from #5127).

Changing the theme from the settings/preferences is a different use case. That's where the user expects the setting to affect everything—it's a **napari** setting after all, not a viewer setting—and be stored. And indeed it does work that way in napari: if you change the theme in the settings, both viewers will change.

> When I think about this, maybe a better solution could be properly separating settings between different python environments. What did you think?

I'm not sure I follow. I have multiple conda envs, but I do most of my use of napari from one env—I suspect that the majority of users do that too. Within my env, I frequently use multiple viewers, change themes, etc. to make screenshots or demo something. It's just real irritation to have to then every time go into preferences and fix my preferences.

Edit: BTW, when I reply like this, should I also be using the @ or is that annoying?

**Comment by Czaki** [comment]
An napari core dev, I just have all PR subscribed, so it will not be a big difference if using @ or not (but using @ allows me to faster come back to talk after a long time). 

> Changing the theme from the settings/preferences is a different use case. That's where the user expects the setting to affect everything—it's a **napari** setting after all, not a viewer setting—and be stored. And indeed it does work that way in napari: if you change the theme in the settings, both viewers will change.

But this may be unintuitive for a new user. In most of the applications that I meet, when allowing toggle theme from the view menu, it happens globally.  


> I'm not sure I follow. I have multiple conda envs, but I do most of my use of napari from one env—I suspect that the majority of users do that too. Within my env, I frequently use multiple viewers, change themes, etc. to make screenshots or demo something. It's just real irritation to have to then every time go into preferences and fix my preferences.

But it is lookalike an advanced usage. Maybe there should be a startup option (or environment variable) to disable saving settings on change?

**Comment by psobolewskiPhD** [comment]
> But this may be unintuitive for a new user. In most of the applications that I meet, when allowing toggle theme from the view menu, it happens globally.

I don't think this is possible in napari? At least on my mac, I don't have theme options in any menu. Changing theme is only possible from settings or programmatically. And it's those two cases I think should be separated, because programmatically one can be explicit about which viewer should have a different theme, with no ambiguity and changing from settings should affect all viewers.

> > I'm not sure I follow. I have multiple conda envs, but I do most of my use of napari from one env—I suspect that the majority of users do that too. Within my env, I frequently use multiple viewers, change themes, etc. to make screenshots or demo something. It's just real irritation to have to then every time go into preferences and fix my preferences.
> 
> But it is lookalike an advanced usage. Maybe there should be a startup option (or environment variable) to disable saving settings on change?

I think that's just complexity? Changing the settings is done in settings. This is simple and intuitive. Adding an extra way to change settings seems like an overcomplication.

**Comment by Czaki** [comment]
> I don't think this is possible in napari? At least on my mac, I don't have theme options in any menu

I'm pretty sure that there was such an option in the view menu at some moment. But after your response, I check and cannot find it. I must have it in the memory menu that was before some settings migration. 
So you are totally right. 

I need to remember to do less base on memory and spend more time on verify if something was not changed.
