### ISSUE TITLE
Disable opacity slider if layer blending mode is `opaque`

### ISSUE THREAD

**Issue by VolkerH** [napari/napari#5074]
## 🚀 Feature

For a layer with blending mode `opaque` the opacity slider has no effect (*).
Therefore the opacity slider should either be hidden or disabled. For the `min` blending mode (@psobolewskiPhD), the `opacity` slider is disabled but not hidden, so for consistency, the opacity should probably be disabled as well.

(*) Caveat:  

For a layer with properties that are shown as text, the text is affected by the opacity slider, not sure whether this is intentional:

![properties_text_opacity](https://user-images.githubusercontent.com/2210044/189856701-fc856836-1bd6-4036-a432-76cbbbbc1808.gif)

**Comment by VolkerH** [comment]
I think I will close this for now. This feature request was based on a misunderstanding that the opacity slider has no effect for opaque layers, which is not the case.

**Comment by psobolewskiPhD** [comment]
Pretty sure the original post is still correct in terms of actual behavior, despite what it says:
https://napari.org/stable/guides/layers.html#blending-layers
For the `opaque` preset, `blending=false` on the vispy/OpenGL side, so literally there can't be blending.
Interestingly, if you watch the thumbnail (which doesn't use vispy) then you can see the behavior described by the docs, where reducing opacity makes the layer go to black.

**Comment by VolkerH** [comment]
Ok, so I will re-open this. 
I was not sure what the intended behaviour was, as the layer documentation https://napari.org/stable/guides/layers.html seems to disagree with the implementation:

> An opaque layer renders all the other layers below it invisible and will fade to black as you decrease its opacity.

The observed behaviour was inconsistent for me as the actual blending behaviour  also changed with mouse interaction (see #5076) while the selected blending mode remained "opaque".
