### ISSUE TITLE
macOS menus are very not-native Pt. 2: menu order is non-standard

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari/napari#5091]
The jarring screenshot here https://github.com/napari/napari/issues/5079#issuecomment-1247007865 reminded me of a long standing issue I have with napari, which I know I've mentioned somewhere but can't find.
On macOS the menus in the menu bar for napari are:
Apple - napari - File - View - Window - Plugins - Help
<img width="467" alt="image" src="https://user-images.githubusercontent.com/76622105/190253744-c8793dd4-15aa-4434-9cca-0db846adc908.png">
This is really strange and non-native. It's jarring. Yes, one get's used to it, but then when I don't use napari for a bit and relaunch it it's there again. I can't unsee it. Plus making things native does ease a barrier to entry & increases comfort.

First—and most importantly—the mandatory Edit menu is missing, see: #5080 (per https://github.com/napari/napari/issues/5080#issuecomment-1249970063 splitting this into two Issues)

Second, the menu bar menu order is **wrong**. To be native, it should be:
Apple - napari - File - Edit - View - Plugins - Window - Help
Basically, the pattern is Apple - File - Edit - View - ... - Window - Help
where ... is everything your application does. See twitter:
<img width="563" alt="image" src="https://user-images.githubusercontent.com/76622105/190254523-c7cbfd43-c02d-4064-b09d-b8bf9eed1590.png">

Now the contents of View and Window are also mixed up (Window should have for example Maximize), but it's less jarring. That said it would be nice if Minimize, normally in Window, shortcut command-M also used the native shortcut, I hit this all the time and am sad each time. See: https://github.com/napari/napari/issues/5092
Edit: I never noticed the native `Enter Full Screen` is at the bottom of View and respects OS shortcuts. But Minimize is missing.

## To Reproduce

1. open napari on macOS
2. open any macOS app
3. compare the menus

## Expected behavior

napari should look and feel like a native macOS app.
The order of the menus should also be the native order, with Window and Help last.

## Environment

macOS 12.5.1 arm64

**Comment by Czaki** [comment]
How will fixing this impact preparing documentation and tutorials? As it may introduce inconsistency between OS.

**Comment by psobolewskiPhD** [comment]
Looking at the code, I think the menu order is hard-coded the same for all OS.
So the question is does Windows or Linux have a native order that is preserved, like macOS?
If so, then we have a bind. If not, then I'd move Window over to be "correct" as on macOS—this is a boon for macOS users and no harm/no foul for other users.
For Docs and Tutorials, screenshots with the full menu bar would need to be updated, but I believe they are always rebuilt when a new release is made? So that should be automatic? 
I doubt any refer to the order of the menus in text, but i've not checked.

Edit: to clarify, I'm not sure it's worth making different menus for macOS and for Windows and Linux. Just that if those other OS don't have a preferred native ordering, then use the macOS since then at least one place will look native.
