### ISSUE TITLE
Dimension slider is very slow with points layer

### ISSUE THREAD

**Issue by hanjinliu** [napari/napari#5123]
## 🐛 Bug

Since 0.4.17rc2 the dimension slider is slow if points layers are added to the viewer. It used to be very smooth in 0.4.16.

https://user-images.githubusercontent.com/40591297/191882100-cc139050-8e58-4e7b-8c18-884b34377809.mp4

## To Reproduce

1. Run following lines.

```python
import napari
viewer = napari.Viewer()
viewer.add_image(np.random.random((100, 100, 100)))
viewer.add_points(np.random.random((300, 3))*100)
```
2. Grab and move dimension slider.

## Expected behavior

Slider should move smoothly.

## Environment

 - Please copy and paste the information at napari info option in help menubar here:

```
napari: 0.4.17rc2
Platform: Windows-10-10.0.22621-SP0
Python: 3.9.7 | packaged by conda-forge | (default, Sep 29 2021, 19:20:16) [MSC v.1916 64 bit (AMD64)]
Qt: 5.15.2
PyQt5: 5.15.6
NumPy: 1.23.2
SciPy: 1.9.1
Dask: 2022.9.0
VisPy: 0.11.0
magicgui: 0.5.1
superqt: 0.3.2
in-n-out: 0.1.5
app-model: 0.0.9
npe2: 0.6.1

OpenGL:
- GL version: 4.6.0 - Build 27.20.100.9621
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1368x912, scale 2.0

```

 - Any other relevant information:

**Comment by Czaki** [comment]
Hello. Could you provide information what GPU did you use? It is dedicated card from Nvidia or ATI or integrated in the procesor?

**Comment by hanjinliu** [comment]
Intel(R) Iris(R) Plus Graphics (integrated one in Surface pro7)

**Comment by andy-sweet** [comment]
Thanks for the report @hanjinliu. I found a similar performance issue, though it occurs when adding and moving points.

Downgrading vispy to 0.10 is the only thing I found that fixes the issue for me, but I believe that will cause other problems with napari.

I also have integrated Intel Iris Plus Graphics (1536 MB), though on a macbook pro. For completeness, here's my napari info.

```
napari: 0.4.17rc2
Platform: macOS-10.16-x86_64-i386-64bit
System: MacOS 12.5
Python: 3.9.13 (main, Aug 25 2022, 18:29:29) [Clang 12.0.0 ]
Qt: 5.15.2
PyQt5: 5.15.7
NumPy: 1.23.3
SciPy: 1.9.1
Dask: 2022.9.1
VisPy: 0.11.0
magicgui: 0.5.1
superqt: 0.3.5
in-n-out: 0.1.5
app-model: 0.0.9
npe2: 0.6.1

OpenGL:
- GL version: 2.1 INTEL-18.8.4
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1080, scale 1.0
```
