### ISSUE TITLE
Install plugins from the command line

### ISSUE THREAD

**Issue by ElpadoCan** [napari/napari#5125]
## 🚀 Feature
Install plugins from the command line

## Motivation

Installing plugins from napari GUI sometimes is a bit of a waste of time and it anyway requires restarting napari. I think it would be beneficial to be able to install them from the command line. 

## Additional context

This feature would allow third-party python software to automatically install the required napari plugins (e.g., through a call to `subprocess.check_call`).

**Comment by Czaki** [comment]
> Installing plugins from napari GUI sometimes is a bit of a waste of time and it anyway requires restarting napari. I think it would be beneficial to be able to install them from the command line.

what prevents installing it using conda/pip directly?

**Comment by ElpadoCan** [comment]
You are right, it worked now that I tried again. I don't know what I did wrong when I tried earlier, thanks for the quick answer!
