### ISSUE TITLE
Filter available plugins

### ISSUE THREAD

**Issue by ElpadoCan** [napari/napari#5126]
## 🚀 Feature
The text box where the user inserts the name of the plugin to install should also act as a filter on the available plugins as the user type the name.

## Motivation

Sometimes I know which plugin I want to install, but I forgot the exact name. Having the possibility to filter available plugins directly in the napari plugins window would spare me from searching it in the hub.

**Comment by psobolewskiPhD** [comment]
There is a filter text box, that filters by name, at the top of the plugin UI panel:
![image](https://user-images.githubusercontent.com/76622105/191990971-a0e1f932-2c1a-42b5-b1ff-d6fe334e6ece.png)
Is the use of that box not clear? perhaps it suggests just installed plugins are filtered?
Anyhow, the issue with filtering in the bottom input field, is that it can be used to install in other ways like from a local file or GitHub.

**Comment by ElpadoCan** [comment]
Oh yeah, I thought it was for filtering only the installed ones, I think I tried it when it was still loading the list of available plugins and I didn't realise it was also filtering below, sorry about that. Somehow it seemed more intuitive to use the text box below to filter the list below.

**Comment by psobolewskiPhD** [comment]
@ElpadoCan Maybe the shadowed text shouldn't say `filter...` but `filter installed & available plugins`?
Do you think that would help?

**Comment by ElpadoCan** [comment]
Yes, it would definitely help, and instead of `filter...` I would call it `Search`
