### ISSUE TITLE
Add points slice function with request and response

### ISSUE THREAD

**Issue by kephale** [napari/napari#5169]
# Description

The task here is similar to that described for the image slice function, except that this is for the `Points` layer type.

There should be a little similarity between the `Image` and `Points` layers, but `Points` layers have quite a few different inputs and outputs.

See the [prototype PR for a crude reference implementation](https://github.com/napari/napari/pull/4905).

**Comment by kephale** [comment]
Currently here https://github.com/kephale/napari/tree/points-slicing-request

**Comment by kephale** [comment]
It seems like this should cover testing whether this test should work for the async points layer.
`NAPARI_POPUP_TESTS=1 pytest napari/_tests/test_with_screenshot.py::test_z_order_image_points`

**Comment by kephale** [comment]
@JoOkuma Can you link me to your graph layer implementation? It would be great to make sure the updates to the `Points` layer works with your layer.

Aha, @andy-sweet linked me to https://github.com/napari/napari-graph/pull/1 I'll check it out!

**Comment by JoOkuma** [comment]
Hi, [this is the branch ](https://github.com/JoOkuma/napari/tree/graph-layer)
Thanks!
