### ISSUE TITLE
Broken link on installation page for bundled app

### ISSUE THREAD

**Issue by justinelarsen** [napari/napari#5183]
## 📚 Documentation

There is "click here" text on this page that does not link anywhere.
https://napari.org/stable/tutorials/fundamentals/installation.html#prerequisites-for-installing-napari-as-a-bundled-app

"Click here to see instructions for installing the bundled app." 
The "Click here" text should link to the bundled app installation section below on the same page (https://napari.org/stable/tutorials/fundamentals/installation.html#install-as-a-bundled-app).
<img width="801" alt="Screen Shot 2022-10-05 at 1 58 07 PM" src="https://user-images.githubusercontent.com/57509887/194170037-0789d529-83ee-42d6-990e-3f39ba5b7117.png">

**Comment by psobolewskiPhD** [comment]
This link works for the `dev` docs (menu in the upper right), so it seems it's been fixed in the repo, but I'm not sure how to go back and fix for that release.

**Comment by Carreau** [comment]
See https://github.com/napari/napari.github.io/pull/365, but there is about 92 broken links. Like just in your screenshot "as a Python package instead", should also be a link.

**Comment by justinelarsen** [comment]
Ah, so many broken links! @Carreau Is there an issue already created to track all those broken links? Thanks for the quick PR to fix this one 😄

**Comment by Carreau** [comment]
no, there is not. the question is: do we want to fix broken links in old
stable, or should we only ensure that new links are valid in future
releases.

**Comment by justinelarsen** [comment]
Good question! I don't know, but maybe best to create an issue to track it and then we can gather feedback on that issue to make a decision? The reason I found this was because a user was trying to install napari and had trouble finding the right instructions, so for right now, it is a problem for the stable docs, but I imagine that with time, this will become less of an issue. I would like to hear what others think.

**Comment by psobolewskiPhD** [comment]
I mean broken links are obviously bad, so fixing them is good. But this can be semi-dealt with via a warning that the docs are out-dated, see https://github.com/napari/docs/issues/82
Edit: going forward, there is this merged PR https://github.com/napari/napari/pull/5008 that should help keep links not broken. 
Is back propagating link fixes practical? Which version do you stop at?

**Comment by justinelarsen** [comment]
Cool! Good to see napari/napari#5008 going forward. Since 0.4.17 will be released soon, maybe the warning banner is more practical. Either way, I really like that proposed addition.

**Comment by psobolewskiPhD** [comment]
This is fixed in every version of the live page on napari.org (0.4.15, 16, 17, and dev).
