### ISSUE TITLE
Plugin installation dialog "hang" after uninstall

### ISSUE THREAD

**Issue by liu-ziyang** [napari/napari#5188]
## 🐛 Bug

After uninstalling a plugin, the installation dialog keeps refreshing and effectively prevents any action from happening.

## To Reproduce

1. install a plugin from napari plugin dialog (optional)
2. uninstall the plugin installed from previous step
3. see the plugin dialog keeps refreshing

## Expected behavior

The plugin dialog should show the latest status instead of hanging in refreshing

## Environment

 - main branch napari or 0.4.17 rc both have this behavior
 - this is discovered on macOS, not sure if can be reproduced elsewhere

**Comment by Czaki** [comment]
Which OS?

**Comment by psobolewskiPhD** [comment]
I cannot replicate this on macOS 12.6 arm64.
Uninstalling a plugin seems normal, no refreshing.
Edit: whoops spoke too soon!
Uninstalling a regular plugin is fine, but those with the `npe2` label causes the chain refresh and requires killing napari. Pretty annoying!
Edit2: I found this printed in my terminal, in case it's a clue:
```
/Users/piotrsobolewski/Dev/miniforge3/envs/apple-TF29/lib/python3.9/site-packages/napari_plugin_engine/manager.py:490: UserWarning: 'No plugin found with the name napari-aicsimageio'!
```
(that is the plugin that I uninstalled, that was labeled `npe2`)

**Comment by Czaki** [comment]
It looks like part of problem source may be this dialog:
![obraz](https://user-images.githubusercontent.com/3826210/194403965-3ee8b2e9-fe8f-449a-94f8-18237541f404.png)

That blocks interactions with GUI. But there is still 100% processor usage.

**Comment by liu-ziyang** [comment]
> It looks like part of problem source may be this dialog: ![obraz](https://user-images.githubusercontent.com/3826210/194403965-3ee8b2e9-fe8f-449a-94f8-18237541f404.png)
> 
> That blocks interactions with GUI. But there is still 100% processor usage.

The refreshing happens still after dismissing this dialog, I am not sure if this dialog is the culprit or the victim of the refreshing at the moment. I can see both ways

**Comment by Czaki** [comment]
Close this dialog allows us to perform some action, but this is not the core of the problem, as everything is laggy.

**Comment by psobolewskiPhD** [comment]
Just to note, I double checked and this doesn't happen on live 0.4.16.

**Comment by psobolewskiPhD** [comment]
Of course Talley has already reported all of this, see:
https://github.com/napari/napari/issues/4937

**Comment by jaimergp** [comment]
I found this yesterday too. It's due to this block:

https://github.com/napari/napari/blob/2c05dbfd9197accbe46421f65589191d7a9b7671/napari/_qt/dialogs/qt_plugin_dialog.py#L982-L983

**Comment by Czaki** [comment]
@jaimergp not because of this, but because not remove uninstalled plugin from the plugin manager. The fix is here https://github.com/napari/napari/pull/5190 and wait on the review
