### ISSUE TITLE
Extending painting to the image layer (merging image / labels)

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#519]
## 🚀 Feature
Right now we have a separation between our image layer - which can have continuously varied pixel information and different colormaps and our labels layer which has discrete values meant to represent labeled regions and the ability to paint / fill.

We could those merge these layers and allow for painting / filling of continuously valued pixel information like is possible in photoshop.

In some ways its nice as it reduces duplication in the codebase, on the other hand, maybe it's also nice just to see an image and not be able to edit it (especially for big images!). People feel that way about the labels layer too though and so maybe the solution is to just have one layer with an `editable` property that can be true or false.

**Comment by jni** [comment]
I don't favour merging the layers, as they represent fundamentally different information. And I think painting in scientific images is much much less common than in natural images (hence photoshop). So I would mark this for 3.0 rather than 0.3.0. =P

**Comment by psobolewskiPhD** [comment]
Stumbled upon this...
I'm definitely not a fan of merging image and labels layers nor of editable image layers -- outside of crop.
I think we should stick to image data being immutable and all labels/annotations/etc. are "on top of" the data as layers or overlays.
IOW, let's stick to napari being an image viewer and not an image editor.

I'd propose we close this as a `won't fix`.

**Comment by jni** [comment]
Done!

btw I LOLed at: https://hachyderm.io/@mgattozzi/112447804706094851 😂
