### ISSUE TITLE
Multi-selection widget: Selection is hard to see

### ISSUE THREAD

**Issue by haesleinhuepf** [napari/napari#5200]
## 🐛 Bug

When using a multi-selection widget in napari, its selection is hard to see because the blue is hardly different from the grey: 

![image](https://user-images.githubusercontent.com/12660498/195296255-23f8d7e4-fec5-4f4c-9d99-047199f4dd8a.png)

## To Reproduce

```
@magic_factory(quality=dict(widget_type='Select', choices=Quality))
def surface_quality_table(surface: SurfaceData, quality, napari_viewer:"napari.Viewer"):
```

See also:
https://forum.image.sc/t/generate-multi-selection-widget-from-magicgui-for-napari-plugins/72631/6

## Expected behavior

Would be cool if we could change the stylesheet of the dark theme so that the selection color is more different from the background color.

## Environment

 - Please copy and paste the information at napari info option in help menubar here:

```
napari: 0.4.17rc4
Platform: Windows-10-10.0.19044-SP0
Python: 3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:51:29) [MSC v.1929 64 bit (AMD64)]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.22.4
SciPy: 1.8.1
Dask: 2022.7.1
VisPy: 0.11.0
magicgui: 0.5.1
superqt: 0.3.3
in-n-out: 0.1.5
app-model: 0.0.9
npe2: 0.6.1

OpenGL:
- GL version: 4.6.0 NVIDIA 512.78
- MAX_TEXTURE_SIZE: 32768

Screens:
- screen 1: resolution 1920x1200, scale 1.0

```

 - Any other relevant information:

**Comment by Czaki** [comment]
@haesleinhuepf Could you post a longer code that will work out of the box? Or point a plugin from you bring it?

**Comment by psobolewskiPhD** [comment]
I think the code @brisvag can be used as a reproducer with small tweak.
In the napari console this should work:
```
from magicgui import magicgui
from enum import Enum, auto

class Choices(Enum):
    a = auto()
    b = auto()
    c = auto()
    d = auto()


@magicgui(x=dict(widget_type='Select', choices=Choices))
def test(x):
    print(x)

viewer.window.add_dock_widget(test)
```
In my case the highlight color is grey not blue, probably an OS thing:
<img width="320" alt="image" src="https://user-images.githubusercontent.com/76622105/195342396-3ba7bf82-969a-468f-9b69-da10aec49679.png">

**Comment by Czaki** [comment]
I also cannot reproduce. So we need more input from @haesleinhuepf

**Comment by haesleinhuepf** [comment]
>  probably an OS thing

Yes, it's known to be a Windows problem.

**Comment by Czaki** [comment]
this is how it looks on my windows with #5202
![obraz](https://user-images.githubusercontent.com/3826210/195575618-108d37b2-f2c2-440d-a4c1-6e9871666de1.png)
