### ISSUE TITLE
"Confirm Window or Application closing" checkbox does not work

### ISSUE THREAD

**Issue by haesleinhuepf** [napari/napari#5201]
## 🐛 Bug

When closing napari, there is a warning message that pops up. You can set a checkbox that deactivates this warning popup. To reactivate the warning, I presume the checkbox under `File > Preferences` does not work.

## To Reproduce

1. Start napari
2. close the window
3. Activate the "do not show again" checkbox.
4. Restart napari
5. Go to File > Preferences, deactivate the checkbox "Confirm Window or Application closing"
6. Close napari, restart it, close it.

... you will not see the warning message again, independent from if you check the checkbox or not.

## Expected behavior

The checkbox under File > PReferences should be connected to the actual setting.

## Environment

 - Please copy and paste the information at napari info option in help menubar here:

```
napari: 0.4.17rc4
Platform: Windows-10-10.0.19044-SP0
Python: 3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:51:29) [MSC v.1929 64 bit (AMD64)]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.22.4
SciPy: 1.8.1
Dask: 2022.7.1
VisPy: 0.11.0
magicgui: 0.5.1
superqt: 0.3.3
in-n-out: 0.1.5
app-model: 0.0.9
npe2: 0.6.1

OpenGL:
- GL version: 4.6.0 NVIDIA 512.78
- MAX_TEXTURE_SIZE: 32768

Screens:
- screen 1: resolution 1920x1200, scale 1.0

```

 - Any other relevant information:

## Additional context

By the way, `napari --reset` also does not reset this setting.

**Comment by Czaki** [comment]
@haesleinhuepf The question dialog is showing only if there is at least one layer added to the viewer. If there is no layer, then the independent to settings dialog will not show. 

Is this source of your confusion?

**Comment by haesleinhuepf** [comment]
Yes! Thanks for the instant reply @Czaki !
