### ISSUE TITLE
ptime: time.clock back-compatibility with python 3.10

### ISSUE THREAD

**Issue by folterj** [napari/napari#5204]
## 🐛 Bug
In the ptime module:
time.clock() is no longer available in python >= 3.8
The Windows back-compatibility code causes an issue when Python version >= 3.10

## To Reproduce
This issue occurs in Windows with Python 3.10
e.g.:
```
import napari
viewer = napari.view_image(image)
```

## Result
...
  File "C:\Users\Y\miniconda3\envs\Napari\lib\site-packages\vispy\util\ptime.py", line 36, in <module>
    cstart = systime.clock()  # Required to start the clock in windows
AttributeError: module 'time' has no attribute 'clock'

## Additional context
This section fails on Windows if python version >= 3.10 because of string comparison: `'3.10' < '3.3'` = True
```
if sys.platform.startswith('win') and sys.version < '3.3':
    cstart = systime.clock()  # Required to start the clock in windows
```

**Comment by Czaki** [comment]
Where this code with comparison is in the napari codebase?

**Comment by folterj** [comment]
Hi @Czaki thanks for the quick response.
As in the post above:
C:\Users\Y\miniconda3\envs\Napari\lib\site-packages\vispy\util\ptime.py", line 36
The comparison is in the line before that, line 35.

**Comment by folterj** [comment]
Actually, this may be in the vispy package instead!

**Comment by Czaki** [comment]
I just checked the vispy repository and did not see such a line here.  

https://github.com/vispy/vispy/blob/859fcaedcc54ebe1ecfd21348cefa37a1cf08ca6/vispy/util/ptime.py

What version of vispy did you have installed?

**Comment by Czaki** [comment]
Ok. They remove it in 0.9 version, and recent napari versions require 0.9 or 0.10.   

If you need to use old napari/vispy versions, then use also older python releases, as more things may not work.

**Comment by folterj** [comment]
Hi @Czaki,
Thank you for the advice, I think I have a broken conda env as it indeed reports an older vispy version as latest (0.7.3) for unkown reason.
Apologies for this - please feel free to remove this issue.
