### ISSUE TITLE
option to display of 3d axis when using 3d viewer

### ISSUE THREAD

**Issue by yunhal** [napari/napari#5212]
## 🚀 Feature

It would be great to have a 3d axis in a corner that can rotate together with a 3d image. It would be also useful for 2 d image cases. This feature can be on and off, for those who doesn't need this. 

## Motivation

I like to use napari's 3D viewer but a few rotation of a image viewing angle, I lost which side of image I am looking at.  The axis of my image have a physical meaning, so I need to know which side I am looking at. 

## Pitch

I put a simple 3d axis in the screenshot to give you an idea.  

<img width="1147" alt="Screen Shot 2022-10-13 at 2 39 43 PM" src="https://user-images.githubusercontent.com/28872346/195682063-c612ce53-ea54-4a6f-834b-84a8991f7121.png">

**Comment by psobolewskiPhD** [comment]
You can sort of do this with `viewer.axes.visible = True` or using the View > Axes > Visible menu item. 
Not super discoverable and doesn't seem to the covered in any of the user-friendly docs, but how does that work for you?

**Comment by yunhal** [comment]
Thanks @psobolewskiPhD.  This is what I was looking for!  I will close this.

**Comment by psobolewskiPhD** [comment]
Glad I could help. I'll try to take a look at the docs and tutorials to see how this can be better covered.
