### ISSUE TITLE
Direct color rendering labels does not work in 3D

### ISSUE THREAD

**Issue by Czaki** [napari/napari#5218]
## 🐛 Bug

When using direct color rendering and switching to 3D, the labeled objects are not visible. 

As in PartSeg I allow user to manually select label colors (required for readable screenshots), it uses direct color rendering. I just found that after switching to 3d the labels are not visible.  

https://user-images.githubusercontent.com/3826210/195829281-c1a013bf-1f2c-4c9b-8f5f-9a179b36f116.mp4

## To Reproduce

1. Create labels 
2. assign custom colormap for labels
3. switch to 3d
4. see that labels are not visible. 
5. switch mode to auto, and they are present. 

## Expected behavior

Labels should be visible in 3d

## Environment

napari: 0.4.17rc4.dev54+gc0a9c8905
Platform: Linux-5.15.0-50-generic-x86_64-with-glibc2.35
System: Ubuntu 22.04.1 LTS
Python: 3.9.12 (main, May 2 2022, 12:30:14) [GCC 11.2.0]
Qt: 5.15.2
PyQt5: 5.15.7
NumPy: 1.23.1
SciPy: 1.8.1
Dask: 2022.7.0
VisPy: 0.11.0
magicgui: 0.5.1
superqt: 0.3.3
in-n-out: 0.1.5
app-model: 0.0.9
npe2: 0.6.1

OpenGL:
- GL version: 4.6.0 NVIDIA 515.65.01
- MAX_TEXTURE_SIZE: 32768

Screens:
- screen 1: resolution 2560x1440, scale 1.0
- screen 2: resolution 1920x1080, scale 1.0
- screen 3: resolution 1920x1080, scale 1.0

**Comment by psobolewskiPhD** [comment]
It looks like you are in iso_categorical rendering mode, so I think this is a duplicate of:
https://github.com/napari/napari/issues/5199

**Comment by Czaki** [comment]
Yes, it is a duplicate. close in favor of #5199
