### ISSUE TITLE
Update workflow for deploying docs from main repo

### ISSUE THREAD

**Issue by jni** [napari/napari#5219]
## 🧰 Task

Since #5216, we have docs in the github.com/napari/docs repo. As we were planning this move, we thought that this meant that docs need to be built in that repo and then deployed from there. But actually, we can just build in either place:

- in the docs repo, we clone the current napari/napari@main, and then build the docs with the current main or PR within that repo, and (optionally) deploy.
- in the main repo, we just clone the current napari/docs@main, then build the docs with the current main or PR, and then optionally deploy.

Since both repos have deploy keys to napari.github.io, both can do this. As far as I can tell, you won't get into race conditions here — later PRs in one will contain the latest commit in the other one, even if that one has not yet finished building. It *could* happen that one build hangs, but that can happen already — a manual workflow trigger would solve this, or we can just wait till the next PR.

The advantage of this is that we don't need to do the remote workflow trigger, which requires my personal access token, which is yucky.

**Comment by melissawm** [comment]
So, is the idea that this build docs workflow from the napari/napari repo would build and deploy to napari.github.io on every PR, include those that don't touch the docs? If that's the case, copying the build docs workflow from the napari/docs repo (with very minor changes) would be enough.

**Comment by jni** [comment]
Every *merged* PR, yes. 😅 I *think* that should work? And yes, I think the changes are just related to which checkout goes in which directory but otherwise the action is basically unchanged I think. 🙏

**Comment by psobolewskiPhD** [comment]
SO the idea is to replace: https://github.com/napari/napari/blob/main/.github/workflows/deploy_docs.yml
which is triggering the deploy in napari/docs with a deploy step in the build workflow?
https://github.com/napari/napari/blob/main/.github/workflows/build_docs.yml

So basically what we have in napari/docs now:
https://github.com/napari/docs/blob/main/.github/workflows/build_and_deploy.yml

**Comment by jni** [comment]
that's my idea, yes. I don't know however whether it is the *right* idea. 😅 If the last few weeks have taught us anything it's that the interaction of many workflows and various race conditions can have unexpected consequences. 😅

**Comment by jni** [comment]
I think the latest changes in the napari/docs workflows (napari/docs#462 and napari/docs#463), which allow deploying from triggered workflows, *should* be enough to resolve what this issue was meant to resolve? So I think actually we can close this. Please reopen if I'm mistaken. 😅
