### ISSUE TITLE
Add makefile for docs in this repo

### ISSUE THREAD

**Issue by jni** [napari/napari#5222]
## 🧰 Task

It's possible to build the API docs from the full docs repo, or to build the full docs from this repo, by cloning both repos next to each other. We should add a makefile to this repo that checks out the docs repo and builds the docs, to make it convenient to build docs from main repo.

CC @Czaki

**Comment by Carreau** [comment]
Be careful, we recently had issue as there was both a makefile in the root of this repo and in the docs folder and they were getting out of sync. Maybe it's better to have a single way of doing things ? Aka "There should be one-- and preferably only one --obvious way to do it.".

**Comment by Czaki** [comment]
The best way for sync is to call one makefile from another. 
As I'm the person who asks about this entry in Makefile.

The general idea is to have one standardized way for build-docs after split infrastructure.  The way that will not require reading long instructions.

**Comment by melissawm** [comment]
If we are already cloning both repos side by side, do we really need another makefile? My preferred solution would be to fix the current docs generation to be more general. [Here's a proposed solution](https://github.com/melissawm/napari-docs/tree/improve-makefile) that works by calling
```
make -C <napari-docs-path> docs GALLERY_PATH=<examples folder absolute path>
```
from your local napari/napari clone. Let me know if this is a reasonable solution!

**Comment by Czaki** [comment]
> If we are already cloning both repos side by side

Based on multiple issues related to napari, even this part may create problems. 

And if someone is working with the napari code and the requirement to switch directories for build docs may be problematic. Many IDE does not support working outside the project directory, so for some persons, it may be better to clone docs directory inside the napari directory. 

Also one could work with napari without docs repository but cannot perform build docs without napari repository.

**Comment by jni** [comment]
After discussion at the docs wg, we're closing this as wontfix: there should be one way to build the docs, which we have. Instructions are at: https://napari.org/stable/developers/contributing/documentation/index.html
