### ISSUE TITLE
Layers should have an attribute to uniquely identify them

### ISSUE THREAD

**Issue by VasudhaJha** [napari/napari#5229]
## 🚀 Feature

A way to uniquely identify layers.

## Motivation

@cudmore and I are working on an undo-redo plugin for napari layers. As part of this we are storing undo and redo stacks for each napari layer. However, we need to have a way to uniquely identify layers.

## Pitch

If each layer has an `id` attribute that is unique (by using uuid.uuid4) and generated once when the layer is created, then we can easily use this attribute to identify each layer and their data for undo and redo operations.

## Alternatives

We could use the `name` attribute, but that can change and we'll need to track that. We have also tried using `id(layer)` which gives us the layer's address, but this may not stay unique during the lifetime of the program.

## Additional context

Created https://github.com/napari/napari/pull/5230 to add the id attribute.

**Comment by Czaki** [comment]
I see 3 possible solutions in the current codebase:

1. Use weak references to layers
2. Use id. It is guaranteed to be unique and constant during object life https://docs.python.org/3/library/functions.html#id 
3. Use hash(layer). It is internally used for referring to layer objects in the napari codebase.

**Comment by VasudhaJha** [comment]
> 3\. Use hash(layer). It is internally used for referring to layer objects in the napari codebase.

I tried using `hash` and it works, unlike `id` which wasn't unique. Thanks for your suggestions!
