### ISSUE TITLE
Fix our github actions versions so we use node16

### ISSUE THREAD

**Issue by jni** [napari/napari#5232]
## 🧰 Task

I've started to see this warning in our CI ([example](https://github.com/napari/napari/actions/runs/3256892988)):

> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/setup-python, tlambert03/setup-qt-libs, GabrielBB/xvfb-action, actions/upload-artifact, actions/setup-python

We should monitor those actions for updates and change the versions we use.

@tlambert03 [updated](https://github.com/tlambert03/setup-qt-libs/commit/5f9906e101c92be548f01c8bd76e91a9e9b139bc) `setup-qt-libs` but it looks like he reused the v1 tag (?) and maybe GHA simply caches actions? (The example above was run 2h ago, Talley's update was 2d ago.) ie I think (?) we should make a *new* `setup-qt-libs` release and update the versions.

**Comment by tlambert03** [comment]
huh,  ok, that's unfortunate, will fix

**Comment by psobolewskiPhD** [comment]
This is stale and bas been fixed.
