### ISSUE TITLE
Napari can't open an image

### ISSUE THREAD

**Issue by sunglyoungKim** [napari/napari#5238]
## 🐛 Bug

I have ubuntu 22.04 with AMD RX6900XT with Rocm 5.3

I have installed napari in a conda environment by following

conda install -c conda-forge napari

When I run napari I see this error,

WARNING: Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
16:47:13 WARNING Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
libGL error: MESA-LOADER: failed to open radeonsi: /usr/lib/dri/radeonsi_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: radeonsi
libGL error: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast

I have looked up issues and some one suggest to install
conda install -c conda-forge libstdcxx-ng==11.2. 

but it doesn't work.

**Comment by jni** [comment]
Sorry @sunglyoungKim, this looks both OS *and* graphics card specific, so it's going to be hard for us to debug beyond what else you find on the internet. (A quick search confirms this.)

By the way, can you type `napari --info` and show us the printout? It would be good to know what napari version you got. Sometimes you can get an old version, and then you won't be able to get the latest fixes. Can you start with an empty conda environment and specify napari=0.4.16?

**Comment by sunglyoungKim** [comment]
@jni 

I have installed the specific version of napari with a new environment on conda.

It works! 

Thank you
