### ISSUE TITLE
DOC Transfer doc issues to `napari/docs`

### ISSUE THREAD

**Issue by lucyleeow** [napari/napari#5241]
## 📚 Documentation

With https://github.com/napari/napari/pull/5216/https://github.com/napari/napari/issues/4306 relevant doc issues should be transfered to `napari/docs`.

Note not all doc issues should be moved over:

> some issues that relate to overall infrastructure, or API docs, or gallery examples, should remain on the main repo, for example.

Also note that this can only be done with someone with the right permissions in `napari/napari` and `napari/docs`. How to transfer: https://docs.github.com/en/issues/tracking-your-work-with-issues/transferring-an-issue-to-another-repository

cc @jni @melissawm

**Comment by Carreau** [comment]
I've create the `documentation-migrate-do-docs` label, reason being that I can tag issue with this label, but don't have enough permissions to migrate. Devs in the same category as me can thus tag issues, and a core dev can just look at all of those tagged issues and migrate them.

**Comment by melissawm** [comment]
I believe this is taken care of for now? There are a few items related to docs still in this repo but I think they should stay.

**Comment by lucyleeow** [comment]
Thanks closing in that case!

**Comment by psobolewskiPhD** [comment]
I've tagged a few more with the `migrate` tag that seem worth transferring. Maybe you can glance at them @melissawm and @lucyleeow ?

**Comment by lucyleeow** [comment]
Thanks @psobolewskiPhD ! I don't have transfer rights but @melissawm may be onto this? :)

**Comment by psobolewskiPhD** [comment]
I can transfer them, just wanted to let people see them first, so that we don't need to transfer any back 😊
