### ISSUE TITLE
Multiple napari instances with magicgui widget

### ISSUE THREAD

**Issue by MartinK84** [napari/napari#5243]
## 🐛 Bug

It appears that during a single python session the same magicgui widget can only be used once by napari when adding it via ```add_dock_widget()```. If you close napari and readd the widget in another napari instance an error is thrown:

> Traceback (most recent call last):
>   File "D:\git\pymri\napari_bug.py", line 15, in <module>
>     viewer.window.add_dock_widget(my_widget)
>   File "...\lib\site-packages\napari\_qt\qt_main_window.py", line 805, in add_dock_widget
>     dock_widget = QtViewerDockWidget(
>   File "...\lib\site-packages\napari\_qt\widgets\qt_viewer_dock_widget.py", line 139, in __init__
>     self.setWidget(widget)
>   File "...\lib\site-packages\napari\_qt\widgets\qt_viewer_dock_widget.py", line 278, in setWidget
>     super().setWidget(widget)
> RuntimeError: wrapped C/C++ object of type QWidget has been deleted

## To Reproduce

1. create a napari viewer and add a magicgui widget using ```add_dock_widget()```
2. close napari
3. create another napari viewer and add the same widget again

```python
import napari
import numpy as np
from magicgui import magicgui

@magicgui(call_button='Do Something')
def my_widget(vertical: bool = True, label: str = 'Dummy'):
    pass

data = np.random.random((10,128,128))
viewer = napari.view_image(data)
viewer.window.add_dock_widget(my_widget)
napari.run()

viewer2 = napari.view_image(data)
viewer2.window.add_dock_widget(my_widget)
napari.run()
```

## Expected behavior

The second time napari is run it should recreate a new widget without trying to reference the widget of the other and already closed napari viewer.

## Environment

> napari: 0.4.16
> Platform: Windows-10-10.0.19043-SP0
> Python: 3.10.6 | packaged by conda-forge | (main, Oct 7 2022, 20:14:50) [MSC v.1916 64 bit (AMD64)]
> Qt: 5.15.2
> PyQt5: 5.15.7
> NumPy: 1.23.4
> SciPy: 1.9.2
> Dask: 2022.10.0
> VisPy: 0.10.0
> 
> OpenGL:
> - GL version: 4.6.0 NVIDIA 511.65
> - MAX_TEXTURE_SIZE: 32768
> 
> Screens:
> - screen 1: resolution 1920x1200, scale 1.0
> - screen 2: resolution 1920x1200, scale 1.0
> 
> Plugins:
> - console: 0.0.6
> - napari-svg: 0.1.6
> - scikit-image: 0.4.16

## Additional context

A similar problem was reported in #4377, however, I do believe that the solution of reusing the same napari instance over and over again is not ideal because this is not intuitive for an average user. Furthermore, the above posted code will also fail it the first  ```napari.run()``` call is removed, in this case the widgets content will be placed two times within the first viewer. It appears as if there are some fundamental problems when using ```add_dock_widget()``` and multiple napari viewers. The problem could also be related to using ```magicgui```.

**Comment by Czaki** [comment]
This is a bug in magicgui as such a widget should be recreated. Without manual undocking, it Qt will remove Qt children.

**Comment by MartinK84** [comment]
Does napari support adding an event/callback that is called when napari is closed? For some cases as in #4377 it might work to have an event fired when napari is closed to then programmatically undock the widget.

**Comment by Czaki** [comment]
If I correctly remember, there is no such event.

**Comment by MartinK84** [comment]
You are correct that this is apparently a magicgui problem,
I tried running the following code using a simple QtWidget instead and the problem does not occur. 
```python
import napari
import numpy as np
from qtpy.QtWidgets import QWidget

class my_widget(QWidget):
    def __init__(self, viewer: 'napari.viewer.Viewer'):
        super().__init__()
        self._viewer = viewer

data = np.random.random((10,128,128))
viewer = napari.view_image(data)
viewer.window.add_dock_widget(my_widget(viewer))
napari.run()

viewer2 = napari.view_image(data)
viewer2.window.add_dock_widget(my_widget(viewer))
napari.run()
```

**Comment by Czaki** [comment]
Your code is not equivalent. The magicgui equivalent code will look like this:

```python
import napari
import numpy as np
from magicgui import magicgui

def my_widget(vertical: bool = True, label: str = 'Dummy'):
    pass

data = np.random.random((10,128,128))
viewer = napari.view_image(data)
viewer.window.add_dock_widget(magicgui(my_widget, call_button='Do Something'))
napari.run()

viewer2 = napari.view_image(data)
viewer2.window.add_dock_widget(magicgui(my_widget, call_button='Do Something'))
napari.run()
```

and will not crash.

**Comment by MartinK84** [comment]
I'm not so deep into magicgui that I fully understand the difference (except that the decorator somehow breaks). 
Nevertheless, your code seems to work, thank you for that!

If you want you can close the issue unless you think the @magicgui decorator thing should be fixed in the future.

**Comment by Czaki** [comment]
The core problem with magicgui is that it creates a widget when `@magicgui` is called, not when docking. 

The best code for you will be:

```python
import napari
import numpy as np

def my_widget(vertical: bool = True, label: str = 'Dummy'):
    pass

data = np.random.random((10,128,128))
viewer = napari.view_image(data)
viewer.window.add_function_widget(my_widget, magic_kwargs={'call_button': 'Do Something'})
napari.run()

viewer2 = napari.view_image(data)
viewer2.window.add_function_widget(my_widget, magic_kwargs={'call_button': 'Do Something'})
napari.run()
```

**Comment by MartinK84** [comment]
Yes, both this way and using pure pyqt5 and QWidget do work and will not crash when napari is repeatedly opened.

**Comment by tlambert03** [comment]
> The core problem with magicgui is that it creates a widget when @magicgui is called, not when docking.
> The best code for you will be:

... (or use `magic_factory`)

**Comment by Czaki** [comment]
Maybe, but magicgui docs does not provide any information about magic_factory 

https://napari.org/magicgui/search.html?q=magic_factory

**Comment by tlambert03** [comment]
🙄... ok, well let's add it to the docs then, it doesn't make it a "maybe" though.  It's a first class use case that is discussed in the napari docs: https://napari.org/stable/guides/magicgui.html#magic-factory

**Comment by Czaki** [comment]
Nice to know. For a long time, I do not visit this part of the docs, and when trying to respond on questions I prefer to suggest methods that are documented. 

And I check only magicgui docs.

**Comment by jwrth** [comment]
Hi all, I accidentally stumbled across another solution how to make @MartinK84 first code work: By wrapping the `my_widget` function into an "initialization" function:

First run:
```python
import napari
import numpy as np
from magicgui import magicgui
from magicgui.widgets import FunctionGui

def initialize_widget() -> FunctionGui:     
    @magicgui(call_button='Do Something')
    def my_widget(vertical: bool = True, label: str = 'Dummy'):
        pass
    return my_widget

data = np.random.random((10,128,128))
viewer = napari.view_image(data)
my_widget = initialize_widget()
viewer.window.add_dock_widget(my_widget)
napari.run()
``` 

Then close napari window and run:
```python
viewer2 = napari.view_image(data)
my_widget = initialize_widget()
viewer2.window.add_dock_widget(my_widget)
napari.run()
``` 

This also works for me without getting the error mentioned above :)

**Comment by Czaki** [comment]
Exactly the same result will be if you use magic-factory decorator byt with less code.

**Comment by jwrth** [comment]
Ah! Thanks for pointing that out!
