### ISSUE TITLE
Segfaulting from README example in Jupyter

### ISSUE THREAD

**Issue by arokem** [napari/napari#526]
## 📚 Documentation

While the first example in the README does work when implementing #525, I can't get this working in the notebook. Instead, the kernel dies without much information given in the terminal. 

This is on a mac laptop running 10.14.6 and napari was installed with `pip install napari` followed by a `pip install -e .` from current master.

**Comment by sofroniewn** [comment]
I think this can be closed by the doc change in #525, right?
