### ISSUE TITLE
Default styling: Disabled PushButtons can't be distinguished from Labels

### ISSUE THREAD

**Issue by VolkerH** [napari/napari#5260]
When using magicgui `PushButton` widgets in napari, the default styling of a disabled button is to not show the box around the button text. This essentially makes the widget look like a text Label widget.

I think this styling is unfortunate:

* Depending on the context, the user may not realize that there is a button that may become activated through some means. 
* The user may mistake the button text as an explanatory label for a neighbouring widget, not as an action.
* It doesn't look nice.

Here is an example where a disabled button looks a bit odd (the button only becomes visible once enough reference points have been selected)
![image](https://user-images.githubusercontent.com/2210044/175529847-a1520595-11bc-4739-bf60-2887b6351fc1.png)

Suggestion:
Use a button styling that retains the button look but visually communicates the enabled/disabled status through other means such as greyed out text, or changed bg color. This is standard in many other UI frameworks. I realize that "graying out" the text in the napari context is not that trivial as the default styling already uses various shades of gray.

**Comment by tlambert03** [comment]
hi @VolkerH, this is a napari issue, not a magicgui issue.

Widgets inherit the stylesheet of their parent. So, when you dock a magicgui widget in a napari viewer, it assumes all of the styles defined in https://github.com/napari/napari/tree/main/napari/_qt/qt_resources/styles

without napari, this is what a disabled button looks like in magicgui:
<img width="284" alt="Screen Shot 2022-10-22 at 10 57 46 AM" src="https://user-images.githubusercontent.com/1609449/197346251-0b76ed2c-2cbb-4db7-bd0f-d58c4a1073a9.png">



I'll move this issue to that repo for you.
