### ISSUE TITLE
windows problem

### ISSUE THREAD

**Issue by dany-fu** [napari/napari#527]
## 🐛 Bug
Napari launches and a thumbnail of my image can be seen in the top right corner, but the actual viewer is just black

![image](https://user-images.githubusercontent.com/7750862/64814859-49a44080-d572-11e9-8c8d-95a01a09fbc6.png)

## To Reproduce
Jupyter notebook
https://github.com/hicsail/neuro-circuit/blob/df-dev/starfish-notebooks/sample2Round2.ipynb

## Expected behavior
See an enlarged version of the thumbnail in the viewer

## Environment
see notebook

## Additional context
I have run the example notebooks in the past on Napari v0.0.6 on a Mac and not did encounter this bug. Not sure if it's Windows specific or if it's my images.

**Comment by sofroniewn** [comment]
hi @dany-fu this example is using napari `0.1.3` can you update to `0.1.5` and see how it goes?

**Comment by kne42** [comment]
@sofroniewn starfish currently enforces napari's version to be `0.1.3`

**Comment by dany-fu** [comment]
I can change that constant locally just for testing

**Comment by kne42** [comment]
@dany-fu yeah you could try that. however, looking at the errors, it looks like it has to do with OpenGL/maybe VisPy. could you check if you have OpenGL installed?

**Comment by dany-fu** [comment]
I have pyopengl

**Comment by dany-fu** [comment]
Interestingly, when I upgraded to 0.1.5 the openGL errors went away, but the initial 'LooseVersion' error still persists

**Comment by kne42** [comment]
That's the python bindings, but it does not guarantee that OpenGL is installed on your system.

Could you send me the output of the following?
```python
from vispy.gloo.gl2 import _lib, _get_gl_version

print(_lib)
print(_get_gl_version(_lib))
```

**Comment by dany-fu** [comment]
`ModuleNotFoundError: No module named 'vispy.gloo.gl2'` 

My errors look similar to this thread here https://github.com/vispy/vispy/issues/1503, is it worth to try and install pyqt4? Would that work with Napari?

**Comment by kne42** [comment]
my bad, it was `vispy.gloo.gl.gl2`, but regardless, if it was fixed by the latest napari version then it probably wasn't OpenGL

we are not compatible with PyQt4

your LooseVersion error may have to do with conda doing funny stuff. could you send me the output of `conda list`?

**Comment by sofroniewn** [comment]
This could be related to some problems with windows people were having in #428 with the labels layer on windows

**Comment by dany-fu** [comment]
I updated the notebook with the stacktrace for v0.1.5 and gl version. It does print `unknown` for `_get_gl_version(_lib)`, does that mean the machine is missing the driver? 

https://github.com/hicsail/neuro-circuit/blob/df-dev/starfish-notebooks/sample2Round2.ipynb

**Comment by sofroniewn** [comment]
@dany-fu is this issue still unresolved for you? apologies we havn't been able to get it working, but if you try the latest `0.2.5` version of napari you can do into the help menu and select `napari info` which will bring a dialog box up that looking like this:

<img width="692" alt="Screen Shot 2019-11-11 at 10 12 47 AM" src="https://user-images.githubusercontent.com/6531703/68610190-0c720700-046c-11ea-8d45-bf1b5e478400.png">

If you can copy and paste the info from that box into this issue it might give us a better chance at understanding what's going wrong. We have found that a lot of windows users are able to use napari without a problem, see here for some verified configurations https://github.com/haesleinhuepf/napari_playground/tree/master/logs, but I'm not sure what's happening with your configuration.

**Comment by dany-fu** [comment]
Thanks for checking in - I think it might have been a driver issue with the cluster computer, but I am no longer involved so @abedghanbari2 will be better able to answer this and close out this issue?

**Comment by sofroniewn** [comment]
Thanks for the update @dany-fu - we can leave this open for a bit in case your colleague can give us further info

**Comment by sofroniewn** [comment]
I'm going to close this issue now, but it can always be reopened if this team looks into it further. Future windows users running into problems should feel free to open a new issue and include the details in the `napari info` dialog box under the `help` drop down. We're definitely committed to windows support and so would love to hear from you with specifics if running into problems.
