### ISSUE TITLE
BUG: Plugins can downgrade napari via plugin GUI, without warning the user

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari/napari#5279]
## 🐛 Bug

If a plugin pins napari to an older version than the running napari with plugin installer GUI, the plugin will install and downgrade napari, silently without warning to the user.

## To Reproduce

1. install napari 0.4.16 or 0.4.17rc
2. use the plugin GUI to install `napari-n2v`

## Expected behavior

napari should resist version changes initiated by a plugin and should instead raise a warning to the user that such and such plugin is trying to downgrade napari and that to force install it—which may break your environment—please use the command line or make a fresh env.

## Environment

fresh conda-forge install of napari 0.4.16, python 3.9, macOS 12.6, arm64

**Comment by Carreau** [comment]
Do you suggest that the plugin installer always adds `napari==<current version>` to the install command ? Because I guess a plugin could also downgrade numpy, or any other package.

**Comment by Czaki** [comment]
I suggest to use constraints file and generate it base on napari (and other plugins metadata.

**Comment by dstansby** [comment]
One option would be to resist *any* version changes that installing a plugin tries to do. For pip the new `--dry-run` option (added in version 22.2: https://github.com/pypa/pip/pull/10771) might help here.

**Comment by Czaki** [comment]
It was fixed on main, but need to be separately fixed on 0.4.18 release branch.

**Comment by jni** [comment]
@Czaki potentially this also should get bumped to 0.5?

**Comment by jni** [comment]
(and therefore closed)

**Comment by jni** [comment]
This was probably closed by #6022. We can reopen if that is incorrect.
