### ISSUE TITLE
Idea: add b'napari' watermark to saved screenshots or movies

### ISSUE THREAD

**Issue by jni** [napari/napari#5298]
matplotlib embeds the `b'Matplotlib'` string in saved pngs and pdfs. This enables cool analyses like [this one](https://github.com/mrocklin/arxiv-matplotlib) that count how many papers in arxiv use matplotlib (A: quite a lot!). Napari is more useful interactively than to create figures, but that might change at some point — already people use napari-animation in papers.

We might want to use something more specific like `made-in-napari`, to make it easy to distinguish mentions from actual figures.

**Comment by GenevieveBuckley** [comment]
I'm also working on this for animations, and will make a separate PR to napari-animation. 

Right now I can set metadata directly with ffmpeg, but the imageio-ffmpeg writer is blocking metadata being passed down.

https://github.com/imageio/imageio/blob/c591a1c4ea20269382877110ce486c5bf84bd99d/imageio/plugins/ffmpeg.py#L597-L600
```python
        def set_meta_data(self, meta):
            raise RuntimeError(
                "The ffmpeg format does not support setting " "meta data."
            )
```

**Comment by GenevieveBuckley** [comment]
https://github.com/imageio/imageio/issues/934

**Comment by psobolewskiPhD** [comment]
Can we close this? napari png and gifs should be covered by https://github.com/napari/napari/pull/5494
I don't think there are any ways to save movies out of napari, so anything else should be in napari-animation, where it also appears implemented:
https://github.com/napari/napari-animation/pull/167
