### ISSUE TITLE
callback hook to provide additional information on hover over image

### ISSUE THREAD

**Issue by VolkerH** [napari/napari#531]
## 🚀 Feature
Allow the user to provide the viewer with a callback function, that receives the current x,y coordinate and intensity and returns data to either be shown somewhere in the viewer or as a tooltip.

## Motivation / Pitch

One possible use case:

When dealing with segmented objects (label images) it is desirable to query information about these objects, e.g. object measurements such as those calculated with `skimage.measure.regionprops_table`.

```python
def example_callback(coord, intensity):
     ... # code to access table 
     if intensity > 0:
          measurements = obj_props_table[intensity]
          return f"<b>Area</b> {measurements["area"]}"
    else:
        return "background" 
```

There are probably also some uses for intensity images (e.g. providing the mean over a neighbourhood around the pixel, or the label number (from a label layer). Be allowing the user to provide a callback they have the flexibility to tailor this to their needs.

## Alternatives

There would be various ways to visualize the data, either as a hover tooltip, somewhere where currently the intensity values are shown or in a separate inspector window that can render HTML and which would offer more space. One could also consider having multiple such options with a callback for each.

**Comment by sofroniewn** [comment]
thanks @VolkerH for making an issue. I think it would be addressed by #252 which we havn't worked on yet, but good to know another example use case, @kne42.

**Comment by sofroniewn** [comment]
We've now added custom callbacks for mouse operations, we havn't added an additional display or html rendering capabilities, but for now you could print to the terminal. Curious if this is helpful to you.

We also need to add a tutorial on using the custom mouse functions, but for now you can maybe get a sense by looking at the top of #544

**Comment by VolkerH** [comment]
Thanks, I will give this a try and see whether I can come up with a short demo.

**Comment by VolkerH** [comment]
This is a very quick & dirty demo of what I had in mind:

![napari_label_inspector](https://user-images.githubusercontent.com/2210044/67252983-31083e00-f4c1-11e9-988c-03fd40318312.gif)

Code is here:
https://github.com/VolkerH/NapariPlayground/blob/master/CustomMouseFunctions/custom_mouse_functions.py

I experinted with a QTableView (which doesn't make too much sense as we can only hover over one object at a time, so there is only one row.  A table view would make sense for selections, e.g. rectangular selections containing multiple objects). The best thing might be a tooltip.

I will try and make a more "tidy" demo in the coming weeks.

At the moment this is just "bolted on", I am thinking about a more general inspector type widget where desired properties can be selected and measurements get updated if the label data changes. Also using the other layers as corresponding intensity images would be useful.

**Comment by sofroniewn** [comment]
This looks so cool! Ultimately I think this is the sort of functionality we want people building plugins to be able to provide. Still need to work with @jni to figure out the best way to enable it, but this is pretty cool to see!!

**Comment by VolkerH** [comment]
I guess the callback hook is there now, so the issue can be closed if you agree.
Thanks again !

**Comment by sofroniewn** [comment]
Sounds good, thanks!
