### ISSUE TITLE
Missing settings schema version change from 0.5.0 to 0.6.0

### ISSUE THREAD

**Issue by andy-sweet** [napari/napari#5316]
## 🐛 Bug

In #5103 we changed the schema of napari settings, but did not bump the [schema version number](https://github.com/napari/napari/blob/1cc90a74211c6cbf3fc644da5866f9752cf1ac78/napari/settings/_napari_settings.py#L19).

If I understand the implementation correctly, I believe we also need to provide a migrator from 0.5.0 to 0.6.0, in order for the new schema version to actually be written to the new settings file.

We should probably write at least one test to cover this migration path.

This is somewhat related to #5314, as I would expect older versions of napari to respond in some useful way to future versions of the schema (e.g. by warning and ignoring them).

**Comment by jni** [comment]
@andy-sweet any chance you could handle this before the release? Seems important 😅 but I don't really know what needs doing 😅😅😅

**Comment by andy-sweet** [comment]
When I said "we", I didn't me the royal we - I didn't write much of this and don't have an immediate idea of how to fix this! Seems like past-me had some ideas, but it would take a little while for me to catch back up with them.

I also think one of the main issues here was fixed in https://github.com/napari/napari/pull/5333 , so I'm not sure if this is still a high priority.

**Comment by jni** [comment]
@andy-sweet ok your cluelessness prompted me to read things in a bit more detail. 😂 

Looking at #5103, it only *added* functionality, and it seems to do that "outside" of the schema anyway (?) for pydantic-y reasons that I don't understand, and this message in the schema:

https://github.com/napari/napari/blob/1cc90a74211c6cbf3fc644da5866f9752cf1ac78/napari/settings/_napari_settings.py#L25-L30

says

> You don't need to touch this value if you're just adding a new option

so I think actually we *don't* need to update the schema version?

**Comment by psobolewskiPhD** [comment]
But the representation changed? If you look at a settings file from before and after they are not compatible.
Which, prior to silo'ing settings https://github.com/napari/napari/pull/5333, meant that the changes from https://github.com/napari/napari/pull/5103 made napari not launchable, see: 
https://napari.zulipchat.com/#narrow/stream/320379-core-devs/topic/Keybind.20breaking.20change

I suspect though that if you do an upgrade in place from 0.4.19 to 0.5.0 the issue will return?

**Comment by jni** [comment]
Oh, interesting, thanks for the background @psobolewskiPhD! So would an update to the schema number magically fix things? Or is there work to do re migration of the settings? 🤔

**Comment by psobolewskiPhD** [comment]
So I tried this:
- install 0.4.19 from pypi as normal (napari[all])
- checked that it worked and set some keybinds and theme to ensure that settings were used
- then I did `pip install -U .` in my napari repo (main checked out)
So napari launches, which is good, but there a buncha warnings:
```
/Users/piotrsobolewski/Dev/miniforge3/envs/nap-settings/lib/python3.11/site-packages/napari/utils/action_manager.py:322: UserWarning: `` does not seem to be a valid shortcut Key.
  shorts = jstr.join(f'{Shortcut(s)}' for s in self._shortcuts[name])
/Users/piotrsobolewski/Dev/miniforge3/envs/nap-settings/lib/python3.11/site-packages/napari/_qt/widgets/qt_welcome.py:105: UserWarning: `` does not seem to be a valid shortcut Key.
  self._shortcut_label.setText(Shortcut(shortcut_list[0]).platform)
/Users/piotrsobolewski/Dev/miniforge3/envs/nap-settings/lib/python3.11/site-packages/napari/utils/action_manager.py:322: UserWarning: `` does not seem to be a valid shortcut Key.
  shorts = jstr.join(f'{Shortcut(s)}' for s in self._shortcuts[name])
/Users/piotrsobolewski/Dev/miniforge3/envs/nap-settings/lib/python3.11/site-packages/napari/utils/action_manager.py:322: UserWarning: `` does not seem to be a valid shortcut Key.
  shorts = jstr.join(f'{Shortcut(s)}' for s in self._shortcuts[name])
```

**Comment by psobolewskiPhD** [comment]
Aha! If I downgrade napari, then I'm screwed: it doesn't launch:
```
/Users/piotrsobolewski/Dev/miniforge3/envs/nap-settings/lib/python3.11/site-packages/napari/_qt/qt_viewer.py:426: UserWarning: Attempting to unbind an action which does not exists (napari:activate_labels_polygon_mode), this may have no effects. This can happen if your settings are out of date, if you upgraded napari, upgraded or deactivated a plugin, or made a typo in in your custom keybinding.
  action_manager.unbind_shortcut(action)
/Users/piotrsobolewski/Dev/miniforge3/envs/nap-settings/lib/python3.11/site-packages/napari/_qt/qt_viewer.py:426: UserWarning: Attempting to unbind an action which does not exists (napari:swap_selected_and_background_labels), this may have no effects. This can happen if your settings are out of date, if you upgraded napari, upgraded or deactivated a plugin, or made a typo in in your custom keybinding.
  action_manager.unbind_shortcut(action)
/Users/piotrsobolewski/Dev/miniforge3/envs/nap-settings/lib/python3.11/site-packages/napari/_qt/qt_viewer.py:426: UserWarning: Attempting to unbind an action which does not exists (napari:reset_polygon), this may have no effects. This can happen if your settings are out of date, if you upgraded napari, upgraded or deactivated a plugin, or made a typo in in your custom keybinding.
  action_manager.unbind_shortcut(action)
/Users/piotrsobolewski/Dev/miniforge3/envs/nap-settings/lib/python3.11/site-packages/napari/_qt/qt_viewer.py:426: UserWarning: Attempting to unbind an action which does not exists (napari:complete_polygon), this may have no effects. This can happen if your settings are out of date, if you upgraded napari, upgraded or deactivated a plugin, or made a typo in in your custom keybinding.
  action_manager.unbind_shortcut(action)
Traceback (most recent call last):
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/nap-settings/bin/napari", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/nap-settings/lib/python3.11/site-packages/napari/__main__.py", line 570, in main
    _run()
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/nap-settings/lib/python3.11/site-packages/napari/__main__.py", line 326, in _run
    viewer = Viewer()
             ^^^^^^^^
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/nap-settings/lib/python3.11/site-packages/napari/viewer.py", line 67, in __init__
    self._window = Window(self, show=show)
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/nap-settings/lib/python3.11/site-packages/napari/_qt/qt_main_window.py", line 638, in __init__
    self._qt_window = _QtMainWindow(viewer, self)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/nap-settings/lib/python3.11/site-packages/napari/_qt/qt_main_window.py", line 114, in __init__
    self._qt_viewer = QtViewer(viewer, show_welcome_screen=True)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/nap-settings/lib/python3.11/site-packages/napari/_qt/qt_viewer.py", line 296, in __init__
    self._bind_shortcuts()
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/nap-settings/lib/python3.11/site-packages/napari/_qt/qt_viewer.py", line 428, in _bind_shortcuts
    action_manager.bind_shortcut(action, shortcut)
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/nap-settings/lib/python3.11/site-packages/napari/utils/action_manager.py", line 268, in bind_shortcut
    self._update_shortcut_bindings(name)
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/nap-settings/lib/python3.11/site-packages/napari/utils/action_manager.py", line 187, in _update_shortcut_bindings
    km_provider.bind_key(shortcut, action.injected, overwrite=True)
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/nap-settings/lib/python3.11/site-packages/napari/utils/key_bindings.py", line 283, in bind_key
    key = normalize_key_combo(key)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/nap-settings/lib/python3.11/site-packages/napari/utils/key_bindings.py", line 185, in normalize_key_combo
    raise TypeError(
TypeError: invalid key 
```

**Comment by psobolewskiPhD** [comment]
Also, it's not just keybinds. Octree is removed, some other settings related to the lasso tool have been added.

**Comment by jni** [comment]
@psobolewskiPhD thanks for doing that experiment! 🧑‍🔬 So what happens if you do the same thing, but before installing main, you change the schema version number to 0.6.0?

tbh though I'm less concerned about downgrades. In the words of Thomas Wade from Three Body Problem: Always Advance! 😜

**Comment by psobolewskiPhD** [comment]
OK, not sure what I did previously but what I just did:
- make a fresh 3.12 env
- install napari[all]
- run napari, change theme and set some shortcuts
- `pip install --pre napari -U`
- got the new alpha
- Run it, get warnings:
```
/Users/piotrsobolewski/Dev/miniforge3/envs/napari-419/lib/python3.12/site-packages/napari/utils/action_manager.py:322: UserWarning: `` does not seem to be a valid shortcut Key.
  shorts = jstr.join(f'{Shortcut(s)}' for s in self._shortcuts[name])
/Users/piotrsobolewski/Dev/miniforge3/envs/napari-419/lib/python3.12/site-packages/napari/_qt/widgets/qt_welcome.py:105: UserWarning: `` does not seem to be a valid shortcut Key.
  self._shortcut_label.setText(Shortcut(shortcut_list[0]).platform)
/Users/piotrsobolewski/Dev/miniforge3/envs/napari-419/lib/python3.12/site-packages/napari/utils/action_manager.py:322: UserWarning: `` does not seem to be a valid shortcut Key.
  shorts = jstr.join(f'{Shortcut(s)}' for s in self._shortcuts[name])
/Users/piotrsobolewski/Dev/miniforge3/envs/napari-419/lib/python3.12/site-packages/napari/utils/action_manager.py:322: UserWarning: `` does not seem to be a valid shortcut Key.
  shorts = jstr.join(f'{Shortcut(s)}' for s in self._shortcuts[name])
/Users/piotrsobolewski/Dev/miniforge3/envs/napari-419/lib/python3.12/site-packages/napari/_qt/widgets/qt_keyboard_settings.py:260: UserWarning: `` does not seem to be a valid shortcut Key.!
```
But now the new keybind I set doesn't work and in fact anything that used Command previously is broken:
<img width="1232" alt="image" src="https://github.com/napari/napari/assets/76622105/a36168b3-8699-4d73-9ee8-276dcba4d25b">

**Comment by psobolewskiPhD** [comment]
In my settings.yaml (from 0.4.19) the keybinds are use `Control`:
```
 118   |     napari:reset_scroll_progress:
 119   │     - Control
 120   │     napari:toggle_ndisplay:
 121   │     - Control-Y
 122   │     napari:toggle_theme:
 123   │     - Control-Shift-N
```

**Comment by psobolewskiPhD** [comment]
Adding:
```
@migrator('0.5.0', '0.6.0')
def v050_060(model: NapariSettings):
    """Migrate from v0.5.0 to v0.6.0"""

    print(model.shortcuts)
```
gives good news and bad news.
Just the essentially no-op migrator rewrites the schema version to 0.6.0 and silence the warnings. 
But, the print output are shortcuts that have already been validated, so the ones with Control are now empty:
```
'napari:reset_scroll_progress': [<KeyBinding at 0x17396fc80: >], 'napari:toggle_ndisplay': [<KeyBinding at 0x17396f9e0: >], 'napari:toggle_theme': [<KeyBinding at 0x17396fce0: >], 
```
This happens here:
https://github.com/napari/napari/blob/f0c02a844cdd0eebceb64b696bb4ab73c2aed08f/napari/settings/_shortcuts.py#L21-L32

So to do the fix, we'd need access to the raw values prior to this.

**Comment by jni** [comment]
That... kinda seems to defeat the whole purpose... 😂

**Comment by psobolewskiPhD** [comment]
The migrator is supposed to migrate fields right? But for keybinds, they get altered before they hit the migrator, so I guess it wasn't intended that the keybinding system be swapped?

Anyhow, i can get the real values using `_config_file_settings` but everywhere else I already get ``.

**Comment by psobolewskiPhD** [comment]
I don't get all the pydantic and OO stuff, but ShortcutSettings fires twice and the first time `shortcuts` has the values from the settings. But later in the `shortcut_validate`, `v` already contains `''`
So i'm not sure what's going on.

**Comment by jni** [comment]
Thanks @psobolewskiPhD for the investigation. Having finally put in the time to sit down and think about this, I think we might be able to also update the validator to do something different based on the schema version. But I don't know whether the schema version will already be available at validation time. I'll have a play. Again, as with #7070, your investigation here is suuuuuper appreciated, it's a massive head start for me! 🙏

**Comment by jni** [comment]
>  Also on macOS in 0.4.19 Command is written out as Control and Control as Meta, but in 0.5.0 Command is written out as Meta and Control as Ctrl.

I wonder if we should revisit this — it would be nice for settings files to be cross-platform. But maybe it's a non-issue if we can write utilities to convert across platforms.

**Comment by jni** [comment]
Alternatively, on macOS we shouldn't write Meta, we should write Command

**Comment by jni** [comment]
> [This happens here:](https://github.com/napari/napari/issues/5316#issuecomment-2204634567)

... Actually it doesn't: debugging now, by the time we get there, they have already been converted to app-model keybindings, and we are doomed. I *think* it's because the annotation for the *input* is dict[str, KeyBinding], and Pydantic coerces the dict ahead of time? Experimenting now...

**Comment by jni** [comment]
omg I think I might have just found [the key](https://github.com/pydantic/pydantic/discussions/2640#discussioncomment-584388):

> `pre` just means "validate the raw value before it has been parsed/coerced"

(`pre` is a kwarg to `@validator`)

😭 gonna check this out...

**Comment by jni** [comment]
<img width="1235" alt="Screenshot 2024-07-09 at 3 48 14 PM" src="https://github.com/napari/napari/assets/492549/ea5a538c-1923-495f-80d4-0e408356bffe">

Success!!!! 😭😭😭
