### ISSUE TITLE
tracks 'color_by' attribute not maintained after updating properties

### ISSUE THREAD

**Issue by alisterburt** [napari/napari#5330]
## 🐛 Bug

The `color_by` attribute on a tracks layer changes if the properties are updated. 

## To Reproduce

```python
import napari
from skimage import data
import numpy as np

hubble_image = data.hubble_deep_field()

tracks_data = np.asarray([
    [1, 0, 236, 0],
    [1, 1, 236, 100],
    [1, 2, 236, 200],
    [1, 3, 236, 500],
    [1, 4, 236, 1000],
    [2, 0, 436, 0],
    [2, 1, 436, 100],
    [2, 2, 436, 200],
    [2, 3, 436, 500],
    [2, 4, 436, 1000],
    [3, 0, 636, 0],
    [3, 1, 636, 100],
    [3, 2, 636, 200],
    [3, 3, 636, 500],
    [3, 4, 636, 1000]
])
track_confidence = np.array(5*[0.9] + 5*[0.3] + 5 * [0.1])
properties = {
    'time': tracks_data[:, 1],
    'confidence': track_confidence
}

viewer = napari.view_image(hubble_image)
viewer.add_tracks(tracks_data, properties=properties)
napari.run()
```

then in the console

```ipython
viewer.layers['tracks_data'].color_by
Out[1]: 'track_id'

viewer.layers['tracks_data'].properties = viewer.layers['tracks_data'].properties

viewer.layers['tracks_data'].color_by
Out[3]: 'time'
```
## Expected behavior

If the previous 'color_by' attribute is still present in the properties, this should not be changed by updating the properties

## Additional context

The offending lines of code are 
https://github.com/napari/napari/blob/cd5c3147a13a42304a6e26a56f516bdc8b879557/napari/_qt/layer_controls/qt_tracks_controls.py#L128-L130

**Comment by Kd-Here** [comment]
Hello Alisterburt can I make a try their.
It will my 1st contribution to ML lib.

**Comment by alisterburt** [comment]
@Kd-Here cool! Feel free to drop a message here if you get stuck

The general implementation would probably look like
- store the current 'color_by' attribute before clearing the combobox
- recreate the combobox (exactly as done in the 'offending lines of code')
- check if the previously stored 'color_by' is present in the `self.layer.properties_to_color_by`
- if present, set `self.layers.color_by` to the previously stored value

**Comment by Kd-Here** [comment]
Hey @alisterburt Thanks for detail informatn!!!
From 2 days I was checking & using napari and **amazed by your work.** 👏

I implemented the code as mention above. 
![image](https://user-images.githubusercontent.com/90677747/202175699-d3a707ce-5312-4852-b5b2-9960d757ea2b.png)

But it is not working correctly. (I know it's my mistake I still don't correctly knowt the class used n their attributes)
Do I need to make changes in napari/layers/tracks/tracks.py file https://github.com/napari/napari/commit/88db2f064b1d19a7160560863932ea4ea78474ab

**Comment by andy-sweet** [comment]
It's possible that my work replacing `properties` with `features` makes this more confusing than it needs to be, so happy to help out if that's the case.

@Kd-Here : do you have a work-in-progress PR or branch you could share? I think you might just need to swap 133 and 134 in the image above because assigning `Tracks.color_by` to something will emit the `Tracks.events.color_by` event which will set the current index/text of the combobox here.

**Comment by Kd-Here** [comment]
Thanks @andy-sweet for your suggestion. I shared a pr can you please help by reviewing the code!

**Comment by andy-sweet** [comment]
@Kd-Here : are you still planning to work on fixing this? No problem if you are and haven't got to it yet - there's not too much rush on this. Also no problem if you are not - just let us know here.

**Comment by Kd-Here** [comment]
I worked on it but couldn't resolve the issue.
I will try my best to fix it
