### ISSUE TITLE
On main: new Keybinds with ⌘ on macOS don't work due to #5103 and old show ^

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari/napari#5332]
## 🐛 Bug

On macOS, on `main` after #5103 keybinds with involving ⌘ don't work properly.
First, keybinds that use the actual physical ⌘ key are shown as `^`, see for example the splash screen and the Preferences:
<img width="1232" alt="image" src="https://user-images.githubusercontent.com/76622105/201521675-1ac935a9-b573-4801-b4b9-0359d8d29184.png">
<img width="1232" alt="image" src="https://user-images.githubusercontent.com/76622105/201521675-1ac935a9-b573-4801-b4b9-0359d8d29184.png">

To emphasize, everywhere `^` is shown, the actual physical ⌘ (Command) key actually works for the keybind.

But if we try to set a new keybind that uses the  physical ⌘ key, say pressing `physical-command-option-m` it shows `Ctrl-Alt-M` (command-key is read as control because Qt does this by default) and then when confirmed it shows `⌘⎇M`, because napari displays `⌘` for Ctrl on macOS. Seems good **BUT** that keybind doesn't work: it actually **is** binding `Ctrl⎇M` (which works using the physical control key) and only making a visual substitution for the symbol, but the swap from Ctrl to Meta isn't restored when trying to use the keybind.

This would be also consistent for the display issue above: the keybinds display as `^` but work when pressing physical command `⌘` key, because `^` is shown when Meta is bound (napari symbol swap) and Meta is `⌘` on macOS. So in this case, things work, but the the Qt swap is not accounted for properly in the visual.

## To Reproduce

1. Pull `main` after #5103 on macOS
2. use UI to try to change a keybind using physical command key
3. Confirm and close the UI.
4. try pressing the keybind with physical command key (won't work) with physical control key (will work)

## Expected behavior

1. The UI on macOS should display `⌘` for keybinds that use the physical `⌘` key.
2. Using the physical `⌘` key to bind a keybind should make the keybind work with the physical `⌘` key.

## Environment

napari: 0.4.17rc4.dev72+g1cc90a74
Platform: macOS-12.6-arm64-arm-64bit
System: MacOS 12.6
Python: 3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:41:22) [Clang 13.0.1 ]
Qt: 5.15.4
PyQt5: 5.15.7
NumPy: 1.23.3
SciPy: 1.9.1
Dask: 2022.9.2
VisPy: 0.11.0
magicgui: 0.6.0
superqt: 0.3.8
in-n-out: 0.1.5
app-model: 0.1.0
npe2: 0.6.2.dev9+gafb0bf6

OpenGL:
  - GL version:  2.1 Metal - 76.3
  - MAX_TEXTURE_SIZE: 16384

Screens:
  - screen 1: resolution 1680x1050, scale 2.0

Plugins:
  - bfio: 2.3.0 (4 contributions)
  - napari: 0.4.17rc4.dev54+g6ba16c1a (77 contributions)
  - napari-aicsimageio: 0.5.1.dev25+gf800574.d20221029 (2 contributions)
  - napari-console: 0.0.6 (0 contributions)
  - napari-first-try: 0.0.1 (7 contributions)
  - napari-svg: 0.1.6 (2 contributions)
  - ome-types: 0.3.1 (4 contributions)

**Comment by Carreau** [comment]
Does #5064 help ? I can extend it, but it has been opened for close to two moth, and still not merged...

**Comment by psobolewskiPhD** [comment]
I'll do some tests again, but I'm pretty sure it's related to app-model, see:
https://github.com/napari/napari/pull/5296#issuecomment-1315657792
I'll try to figure out how to have your PR and the other app-model PR at the same time to test further.

I think what might be happening is that the meta-control swap is happening twice. Once when the keybind is made (converting my physical command key to the universal control) and then again when accessing the keybinds so the keybind is interpreted as being Meta which Qt maps to physical control. Something along those lines anyways.

**Comment by psobolewskiPhD** [comment]
To update: on `main` (`54c1dbf81fb4321637e56156b7bf75f971ad8613`)
I still get the same behavior as OP.
However, there is an extra issue: new keybinds arn't saved. After re-opening napari, the preference shows a blank where a keybind had been entered.
