### ISSUE TITLE
ComboBox automatically filled with viewer.layers for `QWidget` class plugins

### ISSUE THREAD

**Issue by gatoniel** [napari/napari#5340]
## 📚 Documentation

It would be great if this page https://napari.org/stable/guides/magicgui.html#using-magicgui-in-napari-plugin-widgets would also explain, how to create a Layers `ComboBox` in a `QWidget` class plugin. It is straight-forward with the `@magicgui` decorator. But if you want something similar in a `QWidget` class plugin, information on how to do this is not so plentyful. The following code snippet worked for me, but I do not know whether this is the best way to go:
```python
from magicgui.widgets import ComboBox
from qtpy.QtWidgets import QWidget

from napari.types import LabelsData
from napari.utils._magicgui import get_layers_data


class SelectLabelsLayerWidget(QWidget):
    def __init__(self, napari_viewer):
        super().__init__()
        self.viewer = napari_viewer

        self.labels_data = ComboBox(
            label="Labels layer: ",
            annotation=LabelsData,  # essential: either layer or LayerData
            choices=get_layers_data,  # internal function that finds the appropriate layers, essential
        )
        # update the choices when new layer is inserted
        self.viewer.layers.events.inserted.connect(
            self.labels_data.reset_choices
        )
        # update the choices when layer is removed
        self.viewer.layers.events.removed.connect(
            self.labels_data.reset_choices
        )
        # update the choices when layer is converted
        self.viewer.layers.events.changed.connect(
            self.labels_data.reset_choices
        )
```
It should be mentioned that `choices=napari.utils._magicgui.get_layers_data` is needed for `annotation=napari.types.*Data` and `choices=napari.utils._magicgui.get_layers` is needed for `annotation=napari.layers.*`. 

If you confirm that the above approach is the way to go, and that this should be part of the above mentioned guide in the docs, I will create a PR for this.

**Comment by Czaki** [comment]
It is possible to do this without using private API. 

In general the workflow is 
use create_widget for creating magicgui widget ex:
 `self.layer_select = create_widget(annotation=Image)` 

add to layout using native 
`self.layout().addWidget(self.layer_select.native)`

Also, it is essential to define two methods:

```
   def reset_choices(self, event=None):
        self.layer_select.reset_choices(event)

    def showEvent(self, event) -> None:
        self.layer_select()
        return super().showEvent(event)
```

to ensure that list of layers will be refreshed. 

Here is a sample code using it:
https://github.com/Czaki/PartSeg_bioimageio/blob/2afcbd558e52d6af6a13f0b844e80d280cd6ba9d/src/PartSeg_bioimageio/_widget.py#L421

But it will be nice to add proper documentation. Currently, napari docs are living in the https://github.com/napari/docs repository.

**Comment by gatoniel** [comment]
Great thanks. I thought this must be possible without private API. Could you explain, why you use `showEvent` to reset the choices? Is `showEvent` triggered everytime, when the widget is already shown, but a Image layer is converted to a Labels layer?

**Comment by Czaki** [comment]
Because napari does not refresh layers in hidden widgets,
