### ISSUE TITLE
Can't install napari on Mac M1

### ISSUE THREAD

**Issue by thorstenwagner** [napari/napari#5369]
Hi,

we try to get napari on an Mac with an M1 processor:
```
mamba create -y -n napari -c conda-forge python=3.10
conda activate napari
pip install 'napari[all]'==0.4.17
```

However, it can't find a matching distribution. The newst version it can install is 0.4.14.

Does someone know the reason?

We also downloaded the latest asset for 0.4.17. When we try to install it we run into the following exception:

```


~ % napari

Traceback (most recent call last):

  File "/opt/anaconda3/bin/napari", line 10, in <module>

    sys.exit(main())

  File "/opt/anaconda3/lib/python3.7/site-packages/napari/__main__.py", line 449, in main

    _run()

  File "/opt/anaconda3/lib/python3.7/site-packages/napari/__main__.py", line 319, in _run

    **kwargs,

  File "/opt/anaconda3/lib/python3.7/site-packages/napari/view_layers.py", line 178, in view_path

    return _make_viewer_then('open', args, kwargs)

  File "/opt/anaconda3/lib/python3.7/site-packages/napari/view_layers.py", line 122, in _make_viewer_then

    viewer = Viewer(**vkwargs)

  File "/opt/anaconda3/lib/python3.7/site-packages/napari/viewer.py", line 57, in __init__

    self._window = Window(self, show=show)

  File "/opt/anaconda3/lib/python3.7/site-packages/napari/_qt/qt_main_window.py", line 430, in __init__

    self._add_menus()

  File "/opt/anaconda3/lib/python3.7/site-packages/napari/_qt/qt_main_window.py", line 591, in _add_menus

    self.file_menu = menus.FileMenu(self)

  File "/opt/anaconda3/lib/python3.7/site-packages/napari/_qt/menus/file_menu.py", line 105, in __init__

    'when': running_as_bundled_app(),

  File "/opt/anaconda3/lib/python3.7/site-packages/napari/utils/misc.py", line 65, in running_as_bundled_app

    metadata = importlib_metadata.metadata(app_module)

  File "/opt/anaconda3/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 822, in metadata

    return Distribution.from_name(distribution_name).metadata

  File "/opt/anaconda3/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 379, in from_name

    raise ValueError("A distribution name is required.")

ValueError: A distribution name is required.

```

Best,
Thorsten

**Comment by Czaki** [comment]
Hi. Unfortunately, not all packages that are used in napari have m1 compatible wheels uploaded to PyPI. 

Currently, you need to install napari from conda 
```bash
mamba create -y -n napari -c conda-forge python=3.10
mamba activate napari
mamba install napari==0.4.17
```
should work. 
If you have more problems maybe @psobolewskiPhD may know something more.

**Comment by psobolewskiPhD** [comment]
Exactly as noted by @Czaki. The issue is that on pypi there are not arm64 wheels for pyqt5, which is what `pip install napari[all]` tries to install.
Conda-forge does provide these binaries though. So the best option is to use pure conda/mamba as suggested above. You can do:
`mamba create -n napari-env -c conda-forge python=3.10 napari`

Alternately, if you do want to install via pip (for example to make an editable install), then you need to first install a Qt backend. So for example pyqt5 from conda-forge (pyside2 is currently broken) or pyqt6 (which is experimentally supported) from pip or conda-forge.
Once you have a Qt backend, then `pip install napari` -- notice there is no [all], because that would try to get pyqt from pypi, which will fail.

note: we have an open issue to improve the docs in this area:
https://github.com/napari/docs/issues/43
So any feedback is welcome!

**Comment by thorstenwagner** [comment]
Hi,

```
mamba create -n napari-env -c conda-forge python=3.10 napari pip
```

works like a charm!

Thank you so much!

Best,
Thorsten

**Comment by psobolewskiPhD** [comment]
> Hi,
> 
> ```
> mamba create -n napari-env -c conda-forge python=3.10 napari pip
> ```
> 
> works like a charm!
> 
> Thank you so much!
> 
> Best, Thorsten

@thorstenwagner To clarify, did you need to install pip from conda as shown above? or was that a copy paste error 😅

**Comment by thorstenwagner** [comment]
We actually had to do it.... it was not installed. I saw that this is happening occasionally when creating enviroments. Not sure why...

**Comment by psobolewskiPhD** [comment]
Huh. For me I get the same env whether the pip is added or not.
Maybe due to versioning?
```
╰─ mamba list | grep mamba                                                       (base) ─╯
libmamba                  1.0.0                h85d17d7_0    conda-forge
libmambapy                1.0.0           py310h4aac58f_0    conda-forge
mamba                     1.0.0           py310h25b57eb_0    conda-forge
```
Here's a one-line tester:
`mamba create -n test-env -c conda-forge python=3.10 napari --dry-run | grep pip`
output:
```
Dry run. Exiting.

DryRunExit: Dry run. Exiting.

  + pip                                  22.3.1  pyhd8ed1ab_0          conda-forge/noarch 
```
