### ISSUE TITLE
Auto-create pyramid when image exceeds expected capabilities

### ISSUE THREAD

**Issue by ambrosejcarr** [napari/napari#537]
## 🚀 Feature
I would like napari to create pyramids for me if I pass an image that's too large for it to handle. 

## Motivation

Right now, napari throws a difficult-to-parse exception when I pass it an image to display that's ~ 20k x 20k. The solution is known, and is simple, but it's not declared in the exception: 

### Suggested Solution:
> should be one line with from `skimage.transform import pyramid_gaussian` - https://scikit-image.org/docs/dev/auto_examples/transform/plot_pyramid.html

## Pitch

Given the simplicity of the solution, Napari should just solve this problem, optionally emitting a warning to tell the user that it's doing something in the background.

**Comment by sofroniewn** [comment]
So one option here would be to drop the `add_pyramid` method entirely and integrate all the `Pyramid` layer functionality into the `Image` layer and then allow for `add_image` to accept a list of arrays too (like `add_pyramid`) does or add a flag that allows us to autocompute pyramids if we think we need to. I think this may be cleaner than having multiple layer types. Thoughts @jni?

We could then subclass this new layer for the `Labels` layer, thereby giving `Labels` multiresolution support largely for free (though we have to think about lazy painting in a labels layer as discussed in #470

**Comment by sofroniewn** [comment]
After discussion at team meeting we will merge pyramid layer into image layer, adding keyword arg that says `is_pyramid`, and guess otherwise, and maybe adding a keyword arg that allows us to try and compute a pyramid if we think we need to (say an image >20k x 20k or something)

We'll also try to extend so that labels now supports pyramid - but will have to think about painting in the pyramid a little

**Comment by sofroniewn** [comment]
Oh and also 3D rendering isn't supported for pyramids yet, so might need to think about that too.

Also if people request 3D rending on too large images we might need to do some pyramid stuff too ...

For now we can just show the top layer of the pyramid in 3D

**Comment by ambrosejcarr** [comment]
Fantastic, thanks for the rapid discussion and design.

**Comment by sofroniewn** [comment]
This is now done for images in #545. We still need to make it work for labels, but that is discussed in #538 and will be started soon
