### ISSUE TITLE
Help with starfish.display for large images & mask collections

### ISSUE THREAD

**Issue by ambrosejcarr** [napari/napari#538]
## 🐛 Bug

I would like to load the segmented Allen data in napari. These data consist of ~2200 regions of interest over a field of view of shape (27084, 20825)

When I attempt to use napari to load these data, the images are too large and the mask collections throw errors. You can view my attempts [here](https://github.com/spacetx/starfish/blob/2d61bdd0490f22db2837aa52249baaf66d40f18b/notebooks/manual_segmentation_example.ipynb), beginning under the "GeoJSON to SegmentationMaskCollection" heading. Please forgive the messy notebook. 

## To Reproduce

unzip the file downloaded from s3: `s3://starfish.data.spacetx/smFISH/mouse/contributor_results/napari_large_image.zip`
```
70167526 Sep 11 16:40 mFISH__001_registered-downsampled.png
3390209  Sep 16 14:56 mFISH_labels.png
```
To reproduce, load the label image and attempt to show the resulting data in napari. 

```
import skimage.io
labels = skimage.io.imread('mFISH_labels.png')
```
## Expected behavior

I'd like to be able to view my images & masks without size constraints. 

## Environment

 - napari Version (e.g., 1.0): 0.1.3 and 0.1.5 both throw the errors
 - OS (e.g., Linux): OS X 10.14
 - Python version: 3.7

**Comment by sofroniewn** [comment]
As noted in our slack exchanges a napari image layer will choke if you try and pass it an image > 16k x 16k, you instead need to use the pyramid layer and pass a list of precomputed image pyramids. There is some discussion right now in #537 around autocreating the pyramid when we need, which could be the long term solution.

**Comment by ambrosejcarr** [comment]
Does this also explain the issue with the masks? If that's the case, it sounds like the fix for this could be relatively simple and I'm happy to close this in favor of #537.

**Comment by ambrosejcarr** [comment]
I tried to display the mask as an image using the pyramid and wasn't able to get it to work. Am I doing it incorrectly? 

```python3
>>> import napari
>>> print(napari.__version__)
0.1.5

>>> from skimage.transform import pyramid_gaussian
>>> pyramid = tuple(pyramid_gaussian(labels, downscale=2, multichannel=False))
>>> len(pyramid)
16

>>> with napari.gui_qt():
>>>     # set up viewer
>>>     viewer = napari.Viewer()
>>>     viewer.add_pyramid(pyramid)
---------------------------------------------------------------------------
AxisError                                 Traceback (most recent call last)
<ipython-input-55-bfa9af93ea1c> in <module>
      4     # set up viewer
      5     viewer = napari.Viewer()
----> 6     viewer.add_pyramid(list(pyramid))

~/projects/spacetx/starfish/.venv/lib/python3.7/site-packages/napari/components/viewer_model.py in add_pyramid(self, data, *args, **kwargs)
    467             The newly-created pyramid layer.
    468         """
--> 469         layer = layers.Pyramid(data, *args, **kwargs)
    470         self.add_layer(layer)
    471         return layer

~/projects/spacetx/starfish/.venv/lib/python3.7/site-packages/napari/layers/pyramid/pyramid.py in __init__(self, data, *args, **kwargs)
     92 
     93         self._data_level = 0
---> 94         super().__init__(np.array([np.asarray(data[-1])]), *args, **kwargs)
     95         self._data = data
     96         self._data_level = len(data) - 1

~/projects/spacetx/starfish/.venv/lib/python3.7/site-packages/napari/layers/image/image.py in __init__(self, data, multichannel, colormap, contrast_limits, interpolation, rendering, name, metadata, scale, translate, opacity, blending, visible)
    174 
    175         # Trigger generation of view slice and thumbnail
--> 176         self._update_dims()
    177 
    178     @property

~/projects/spacetx/starfish/.venv/lib/python3.7/site-packages/napari/layers/base/base.py in _update_dims(self)
    313             self.dims.set_range(i, r)
    314 
--> 315         self._set_view_slice()
    316         self._update_coordinates()
    317 

~/projects/spacetx/starfish/.venv/lib/python3.7/site-packages/napari/layers/pyramid/pyramid.py in _set_view_slice(self)
    186         self._data_thumbnail = np.asarray(
    187             self.data[-1][tuple(indices)]
--> 188         ).transpose(order)
    189 
    190         # Slice currently viewed level

AxisError: axis 2 is out of bounds for array of dimension 2
```

**Comment by jni** [comment]
@ambrosejcarr what is `labels`?

Anyway, based on the [example](https://github.com/napari/napari/blob/master/examples/add_pyramid.py), I'm starting to wonder whether pyramid is RGB by default...

**Comment by sofroniewn** [comment]
That's a bug on our end - you're passing the entire pyramid all the way to the `1x1` image at the top and something is choking - if you use the `max_layer` keyword argument you'll prevent this - for example I just verified that the following works for a 20k x 20k image

```python
"""Test converting an image to a pyramid.
"""

import numpy as np
from napari import Viewer, gui_qt
from skimage.transform import pyramid_gaussian

image = np.random.random((20000, 20000))
pyramid = list(pyramid_gaussian(image, downscale=2, multichannel=False, max_layer=8))

print(image.shape)
print(len(pyramid))
print([p.shape for p in pyramid])

with gui_qt():
    viewer = Viewer()
    viewer.add_pyramid(pyramid, contrast_limits=[0, 1])
```

**Comment by sofroniewn** [comment]
Here's a gif. I can make a fix so that even if you pass in the full pyramid it won't try and show the `1x1` square!

![rand_pyr](https://user-images.githubusercontent.com/6531703/65002604-88573500-d8a9-11e9-8fe7-9c75f5785560.gif)

**Comment by jni** [comment]
@sofroniewn love the gif a lot! Kinda trippy! =D

**Comment by ambrosejcarr** [comment]
Thanks. I was able to get this working -- worth noting that it choked on the `(2, 2)` square too, but `pyramid[:-3]` is 👌 

My next question is: how do I get these to display as masks instead of as a label image? `starfish.display` wasn't able to display the set of ~ 2200 masks.

**Comment by ambrosejcarr** [comment]
> @ambrosejcarr what is labels?
> 
> Anyway, based on the example, I'm starting to wonder whether pyramid is RGB by default...

It's a 2d integer array, the output of `scipy.ndimage.label` on a binary image, meant to reflect distinct cell bodies. the pyramid construction appears to have worked.

**Comment by sofroniewn** [comment]
@ambrosejcarr for masks instead of label image - what is it that you are expecting to see? say you have ~2000 masks do you want one image per mask and then a "z-slider" that allows you to scroll through all 2000? or if you want to see them all at the same time how should they be colored / how do you want to resolve overlap? This is discussed in #269. 

Also if you have ~2000 masks and want to view each one separately with a z-slider and each one is embedded in a 20k x 20k image can you fit all of that into memory if you create one large 2000 x 20k x 20k array? Probably not, which makes me think you could either use dask to create that 20k x 20k image on the fly as you move the z-slider, which will be slow, or you could just show each as a small patch at the appropriate location, but you'd need to write some code to do that, and it's still not clear to me what the expectations are.

**Comment by ambrosejcarr** [comment]
I'm content with the current `starfish.display` functionality, which shows the mask as a series `alpha < 1` colored shapes via `add_labels`, but functioning over large sets of such masks.
