### ISSUE TITLE
Better button tooltips: "Switch 2D/3D view"

### ISSUE THREAD

**Issue by haesleinhuepf** [napari/napari#5390]
## 🚀 Feature
I'm proposing to update tooltips, e.g. `Switch 2D/3D view` instead of `Toggle ndisplay`.

![image](https://user-images.githubusercontent.com/12660498/205486847-be83caa9-9836-4cfd-a454-c532ac8444ce.png)

## Motivation

`Toggle ndisplay` is not easy to understand for normal people;

## Pitch

Call it `Switch between 2D and 3D view.`

## Alternatives

The tooltip could change according to current view: `Switch to 3D view` for example.

## Additional context

I'm using napari 0.4.17

**Comment by Czaki** [comment]
It could be changed here:
https://github.com/napari/napari/blob/c0f27686b724b46109089136c80d9d6191eba692/napari/components/_viewer_key_bindings.py#L49-L51

**Comment by goanpeca** [comment]
Might need to change the decorator so that it can take a list of tooltips per state or similar

**Comment by Czaki** [comment]
We also may think about validating where actions are defined, as the keybindings file is not an expected place.

**Comment by kcpevey** [comment]
Seems like there are to options here:

Option 1: Change the text to "Switch between 2D and 3D view"
and
Option 2: Change the text to "Switch to {dim} view"

Option 1 is straightforward (and indeed a "good first issue" - something I could do). 
Option 2 is obviously more complex (I'd have more follow-up questions, or perhaps this option is not suited for newcomers). 

Which is the preferred solution?
