### ISSUE TITLE
Minor bug: in the layer contextual menu, Split Stack is not disabled for single-channel 2D images.

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari/napari#5418]
## 🐛 Bug

In the layer contextual menu, Split Stack is not disabled for 2D images. Clicking it results in an error: `ValueError: The image needs more than 2 dimensions for splitting`
This error is instructive, but the other functions of the menu are disabled when not usable, so this should also be disabled for consistency.

## To Reproduce

1. Open Binary blobs or any 2D single channel image
2. Right-click, Split Stack is not grey

<img width="304" alt="image" src="https://user-images.githubusercontent.com/76622105/208298172-e0b92073-1e15-4d13-b5b2-a16727291b51.png">

Note: Interestingly, all of the projections are disabled in the sub-menu, but not the menu itself.

## Expected behavior

The Split Stack menu item should be disabled.

## Environment
```
napari: 0.4.17rc4.dev124+g5e0aebee
Platform: macOS-12.6-arm64-arm-64bit
System: MacOS 12.6
Python: 3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:25:29) [Clang 14.0.6 ]
Qt: 5.15.6
PyQt5: 5.15.7
NumPy: 1.23.5
SciPy: 1.9.3
Dask: 2022.12.1
VisPy: 0.12.1
magicgui: 0.6.1
superqt: unknown
in-n-out: 0.1.6
app-model: 0.1.1
npe2: 0.6.1

OpenGL:
- GL version: 2.1 Metal - 76.3
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1680x1050, scale 2.0

Settings path:
- /Users/piotrsobolewski/Library/Application Support/napari/napari-dev_a1eb8b76ba95fa16ad06e26097b46b8455dfbf0b/settings.yaml

```

Note: not sure why superqt is not reporting properly, it's 0.4.1:
`superqt                   0.4.1              pyhd8ed1ab_0    conda-forge`

**Comment by dalthviz** [comment]
Hi, I think I can help with this! Checking seems that what is missing is to use `_IMAGE_IS_3D` as the `enablement` kwarg for the `Split stack` (`CommandId.LAYER_SPLIT_STACK`) action at https://github.com/napari/napari/blob/b9e613acdcd088e61634e5dbdc553c942eb5a75d/napari/_app_model/actions/_layer_actions.py#L53-L58

and the `Projections` (`MenuId.LAYERS_PROJECT`) submenu item at https://github.com/napari/napari/blob/b9e613acdcd088e61634e5dbdc553c942eb5a75d/napari/_app_model/_submenus.py#L16-L23

right?

Also, seems like the `Convert data type` (`MenuId.LAYERS_CONVERT_DTYPE`) submenu item also needs to be disabled (using probably as `enablement` kwarg `_ONLY_LABELS`)?:

![convert](https://user-images.githubusercontent.com/16781833/208728880-4da9d9f9-2bb5-4a33-b6d0-1f5ec676137f.png)
