### ISSUE TITLE
ERROR: Failed building wheel for vispy

### ISSUE THREAD

**Issue by martagraziano** [napari/napari#5425]
## To Reproduce

1.
2.
3.

## Environment

 - Please copy and paste the information at napari info option in help menubar here:

 - Any other relevant information:

**Comment by Czaki** [comment]
Please provide at least information about the operating system and processor architecture.

**Comment by Carreau** [comment]
Closing for lack of information. It is also likely an upstream issue if it can't build vispy.

Feel free to add information later and ask for this to be reopened.
