### ISSUE TITLE
Can't rotate a rectangle (Apple silicon, rosetta, PyQt6, pip)

### ISSUE THREAD

**Issue by chaplinta** [napari/napari#5448]
## 🐛 Bug

After creating a rectangle I can't rotate it. I am on apple silicon and had already used rosetta as a work around to install PyQt6 for some other packages which is likely the cause of this, but I thought I should report it anyway to see if there is a fix or better work around.

## To Reproduce

1. open terminal using rosetta
2. conda create --name naptest python=3.8
3. conda activate naptest
4. pip install napari
5. pip install PyQt6
6. napari
7. load an image
8. draw a rectangle
9. chose select shape and attempt to rotate the rectangle by using the cursor.

The rectangle doesn't rotate and the following error and traceback is produced:

> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> File ~/opt/miniconda3/envs/suite2p/lib/python3.8/site-packages/vispy/app/backends/_qt.py:532, in QtBaseCanvasBackend.mouseMoveEvent(self=<vispy.app.backends._qt.CanvasBackendDesktop object>, ev=<PyQt5.QtGui.QMouseEvent object>)
>     530 if self._vispy_canvas is None:
>     531     return
> --> 532 self._vispy_mouse_move(
>         self = <vispy.app.backends._qt.CanvasBackendDesktop object at 0x7ff421cf2f70>
>         ev = <PyQt5.QtGui.QMouseEvent object at 0x7ff452a87430>
>     533     native=ev,
>     534     pos=_get_event_xy(ev),
>     535     modifiers=self._modifiers(ev),
>     536 )
> 
> File ~/opt/miniconda3/envs/suite2p/lib/python3.8/site-packages/vispy/app/base.py:216, in BaseCanvasBackend._vispy_mouse_move(self=<vispy.app.backends._qt.CanvasBackendDesktop object>, **kwargs={'button': 1, 'buttons': [], 'last_event': <MouseEvent blocked=False button=1 buttons=[] de...urces=[] time=1672144238.037448 type=mouse_press>, 'last_mouse_press': None, 'modifiers': (), 'native': <PyQt5.QtGui.QMouseEvent object>, 'pos': (33, 354), 'press_event': <MouseEvent blocked=False button=1 buttons=[] de...urces=[] time=1672144238.037448 type=mouse_press>})
>     213 else:
>     214     kwargs['button'] = self._vispy_mouse_data['press_event'].button
> --> 216 ev = self._vispy_canvas.events.mouse_move(**kwargs)
>         self = <vispy.app.backends._qt.CanvasBackendDesktop object at 0x7ff421cf2f70>
>         self._vispy_canvas.events.mouse_move = <vispy.util.event.EventEmitter object at 0x7ff421d01100>
>         kwargs = {'native': <PyQt5.QtGui.QMouseEvent object at 0x7ff452a87430>, 'pos': (33, 354), 'modifiers': (), 'buttons': [], 'press_event': <MouseEvent blocked=False button=1 buttons=[] delta=[0. 0.] handled=False is_dragging=False last_event=MouseEvent modifiers=() native=<PyQt5.QtGui.QMouseEvent object at 0x7ff452a87430> pos=[ 33 354] press_event=None source=None sources=[] time=1672144238.037448 type=mouse_press>, 'last_event': <MouseEvent blocked=False button=1 buttons=[] delta=[0. 0.] handled=False is_dragging=False last_event=MouseEvent modifiers=() native=<PyQt5.QtGui.QMouseEvent object at 0x7ff452a87430> pos=[ 33 354] press_event=None source=None sources=[] time=1672144238.037448 type=mouse_press>, 'last_mouse_press': None, 'button': 1}
>         self._vispy_canvas.events = <vispy.util.event.EmitterGroup object at 0x7ff421cf8f70>
>         self._vispy_canvas = <VispyCanvas (PyQt5) at 0x7ff4316ebe50>
>     217 self._vispy_mouse_data['last_event'] = ev
>     218 return ev
> 
> File ~/opt/miniconda3/envs/suite2p/lib/python3.8/site-packages/vispy/util/event.py:453, in EventEmitter.__call__(self=<vispy.util.event.EventEmitter object>, *args=(), **kwargs={'button': 1, 'buttons': [], 'last_event': <MouseEvent blocked=False button=1 buttons=[] de...urces=[] time=1672144238.037448 type=mouse_press>, 'last_mouse_press': None, 'modifiers': (), 'native': <PyQt5.QtGui.QMouseEvent object>, 'pos': (33, 354), 'press_event': <MouseEvent blocked=False button=1 buttons=[] de...urces=[] time=1672144238.037448 type=mouse_press>})
>     450 if self._emitting > 1:
>     451     raise RuntimeError('EventEmitter loop detected!')
> --> 453 self._invoke_callback(cb, event)
>         event = <MouseEvent blocked=False button=1 buttons=[] delta=[0. 0.] handled=False is_dragging=True last_event=MouseEvent modifiers=() native=<PyQt5.QtGui.QMouseEvent object at 0x7ff452a87430> pos=[ 33 354] press_event=MouseEvent source=None sources=[] time=1672144238.5800464 type=mouse_move>
>         self = <vispy.util.event.EventEmitter object at 0x7ff421d01100>
>         cb = <bound method QtViewer.on_mouse_move of <napari._qt.qt_viewer.QtViewer object at 0x7ff421cda820>>
>     454 if event.blocked:
>     455     break
> 
> File ~/opt/miniconda3/envs/suite2p/lib/python3.8/site-packages/vispy/util/event.py:471, in EventEmitter._invoke_callback(self=<vispy.util.event.EventEmitter object>, cb=<bound method QtViewer.on_mouse_move of <napari._qt.qt_viewer.QtViewer object>>, event=<MouseEvent blocked=False button=1 buttons=[] de...urces=[] time=1672144238.5800464 type=mouse_move>)
>     469     cb(event)
>     470 except Exception:
> --> 471     _handle_exception(self.ignore_callback_errors,
>         self = <vispy.util.event.EventEmitter object at 0x7ff421d01100>
>         cb = <bound method QtViewer.on_mouse_move of <napari._qt.qt_viewer.QtViewer object at 0x7ff421cda820>>
>         event = <MouseEvent blocked=False button=1 buttons=[] delta=[0. 0.] handled=False is_dragging=True last_event=MouseEvent modifiers=() native=<PyQt5.QtGui.QMouseEvent object at 0x7ff452a87430> pos=[ 33 354] press_event=MouseEvent source=None sources=[] time=1672144238.5800464 type=mouse_move>
>         (cb, event) = (<bound method QtViewer.on_mouse_move of <napari._qt.qt_viewer.QtViewer object at 0x7ff421cda820>>, <MouseEvent blocked=False button=1 buttons=[] delta=[0. 0.] handled=False is_dragging=True last_event=MouseEvent modifiers=() native=<PyQt5.QtGui.QMouseEvent object at 0x7ff452a87430> pos=[ 33 354] press_event=MouseEvent source=None sources=[] time=1672144238.5800464 type=mouse_move>)
>     472                       self.print_callback_errors,
>     473                       self, cb_event=(cb, event))
> 
> File ~/opt/miniconda3/envs/suite2p/lib/python3.8/site-packages/vispy/util/event.py:469, in EventEmitter._invoke_callback(self=<vispy.util.event.EventEmitter object>, cb=<bound method QtViewer.on_mouse_move of <napari._qt.qt_viewer.QtViewer object>>, event=<MouseEvent blocked=False button=1 buttons=[] de...urces=[] time=1672144238.5800464 type=mouse_move>)
>     467 def _invoke_callback(self, cb, event):
>     468     try:
> --> 469         cb(event)
>         cb = <bound method QtViewer.on_mouse_move of <napari._qt.qt_viewer.QtViewer object at 0x7ff421cda820>>
>         event = <MouseEvent blocked=False button=1 buttons=[] delta=[0. 0.] handled=False is_dragging=True last_event=MouseEvent modifiers=() native=<PyQt5.QtGui.QMouseEvent object at 0x7ff452a87430> pos=[ 33 354] press_event=MouseEvent source=None sources=[] time=1672144238.5800464 type=mouse_move>
>     470     except Exception:
>     471         _handle_exception(self.ignore_callback_errors,
>     472                           self.print_callback_errors,
>     473                           self, cb_event=(cb, event))
> 
> File ~/opt/miniconda3/envs/suite2p/lib/python3.8/site-packages/napari/_qt/qt_viewer.py:1077, in QtViewer.on_mouse_move(self=<napari._qt.qt_viewer.QtViewer object>, event=<MouseEvent blocked=False button=1 buttons=[] de...urces=[] time=1672144238.5800464 type=mouse_move>)
>    1069 def on_mouse_move(self, event):
>    1070     """Called whenever mouse moves over canvas.
>    1071 
>    1072     Parameters
>    (...)
>    1075         The vispy event that triggered this method.
>    1076     """
> -> 1077     self._process_mouse_event(mouse_move_callbacks, event)
>         event = <MouseEvent blocked=False button=1 buttons=[] delta=[0. 0.] handled=False is_dragging=True last_event=MouseEvent modifiers=() native=<PyQt5.QtGui.QMouseEvent object at 0x7ff452a87430> pos=[ 33 354] press_event=MouseEvent source=None sources=[] time=1672144238.5800464 type=mouse_move>
>         self = <napari._qt.qt_viewer.QtViewer object at 0x7ff421cda820>
> 
> File ~/opt/miniconda3/envs/suite2p/lib/python3.8/site-packages/napari/_qt/qt_viewer.py:1026, in QtViewer._process_mouse_event(self=<napari._qt.qt_viewer.QtViewer object>, mouse_callbacks=<function mouse_move_callbacks>, event=<ReadOnlyWrapper at 0x7ff4527b5800 for MouseEvent>)
>    1024 layer = self.viewer.layers.selection.active
>    1025 if layer is not None:
> -> 1026     mouse_callbacks(layer, event)
>         event = <ReadOnlyWrapper at 0x7ff4527b5800 for MouseEvent at 0x7ff412fac1c0>
>         layer = <Shapes layer 'roi' at 0x7ff4129baee0>
>         mouse_callbacks = <function mouse_move_callbacks at 0x7ff43218e040>
> 
> File ~/opt/miniconda3/envs/suite2p/lib/python3.8/site-packages/napari/utils/interactions.py:172, in mouse_move_callbacks(obj=<Shapes layer 'roi'>, event=<ReadOnlyWrapper at 0x7ff4527b5800 for MouseEvent>)
>     169 obj._persisted_mouse_event[gen].__wrapped__ = event
>     170 try:
>     171     # try to advance the generator
> --> 172     next(gen)
>         gen = <generator object select at 0x7ff45277cf90>
>     173 except StopIteration:
>     174     # If done deleted the generator and stored event
>     175     del obj._mouse_drag_gen[func]
> 
> File ~/opt/miniconda3/envs/suite2p/lib/python3.8/site-packages/napari/layers/shapes/_shapes_mouse_bindings.py:63, in select(layer=<Shapes layer 'roi'>, event=<ReadOnlyWrapper at 0x7ff412fb9b40 for ReadOnlyWrapper>)
>      61     _drag_selection_box(layer, coordinates)
>      62 else:
> ---> 63     _move(layer, coordinates)
>         layer = <Shapes layer 'roi' at 0x7ff4129baee0>
>         coordinates = (548.6112116382243, 214.95006156565557)
>      65 # if a shape is being moved, update the thumbnail
>      66 if layer._is_moving:
> 
> File ~/opt/miniconda3/envs/suite2p/lib/python3.8/site-packages/napari/layers/shapes/_shapes_mouse_bindings.py:492, in _move(layer=<Shapes layer 'roi'>, coordinates=(548.6112116382243, 214.95006156565557))
>     487     offset = handle - layer._fixed_vertex
>     488     layer._drag_start = -np.degrees(
>     489         np.arctan2(offset[0], -offset[1])
>     490     )
> --> 492 new_offset = coord - layer._fixed_vertex
>         coord = [548.6112116382243, 214.95006156565557]
>         layer = <Shapes layer 'roi' at 0x7ff4129baee0>
>         layer._fixed_vertex = None
>     493 new_angle = -np.degrees(np.arctan2(new_offset[0], -new_offset[1]))
>     494 fixed_offset = handle - layer._fixed_vertex
> 
> TypeError: unsupported operand type(s) for -: 'list' and 'NoneType'
> 

## Expected behavior

The rectangle should rotate.

## Environment

napari: 0.4.17
Platform: macOS-10.16-x86_64-i386-64bit
System: MacOS 13.0.1
Python: 3.8.15 (default, Nov 24 2022, 09:04:07) [Clang 14.0.6 ]
Qt: 5.15.2
PyQt5: 5.15.7
NumPy: 1.23.5
SciPy: 1.9.3
Dask: 2022.12.1
VisPy: 0.11.0
magicgui: 0.6.1
superqt: unknown
in-n-out: 0.1.6
app-model: 0.1.1
npe2: 0.6.1

OpenGL:
- GL version: 2.1 Metal - 83
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1440x900, scale 2.0

## Additional context
Other basic operations like moving & resizing rectangles, and drawing lines seems to be fine.

**Comment by psobolewskiPhD** [comment]
I'm a bit confused, because your traceback and napari show PyQt5 but you refer to PyQt6 in the title and description—do you have two Qt backends installed?
Eitherway, I can reproduce this on my mac (also arm64, but native env not rosetta)—it works in 0.4.16, so this is a 0.4.17 regression.

**Comment by psobolewskiPhD** [comment]
Git bisect (gosh I love this tool) points to this commit:
```
6d18f10452fdd0c9a53427c52bf0ed34de16d0f8 is the first bad commit
commit 6d18f10452fdd0c9a53427c52bf0ed34de16d0f8
Author: Markus Stabrin <markus.stabrin@mpi-dortmund.mpg.de>
Date:   Mon Sep 5 18:11:24 2022 +0200

    Set fixpoint before move for shapes (#4999)
    
    * Set fixpoint before move for shapes
    
    * Add comments
    
    * Reuse _set_drag_start
    
    * add typing and test
    
    * fix typing on py3.8 and add typing for move method
    
    Co-authored-by: alisterburt <alisterburt@gmail.com>
```
https://github.com/napari/napari/commit/6d18f10452fdd0c9a53427c52bf0ed34de16d0f8
CC @alisterburt @mstabrin

**Comment by chaplinta** [comment]
Hmm sorry I must have mixed up PyQT when trying to reproduce it in another environment.

**Comment by psobolewskiPhD** [comment]
Hi @chaplinta thanks again for reporting the bug. 
I've merged a fix, but you'll need to wait for a release or install `main` from GitHub.
