### ISSUE TITLE
Convert Image to type Labels in memory efficient manner.

### ISSUE THREAD

**Issue by kapoorlab** [napari/napari#5461]
## 🚀 Feature

Usual server nodes have about 190 GB of RAM and when working with datasets where a single image is about 40 GB, naive drag and drop takes about 60 GB to load the data as image layer in Napari, even if the image is actually a label image. If I try to convert it to labels using the builtin function the memory increases to over 180 GB eventually killing the Napari thread. Executing the following commands in the builtin terminal however is able to open both the images, one as image layer and another one as labels layer with 95 GB of RAM usage:

```
image = viewer.layers[0].data.astype('uint16')
viewer.add_labels(image)
```
You can reproduce this using the data loaded in the s3 bucket (s3://example-napari-kapoorlabs/third_dataset_membrane_cellpose_cellpose.tif,), for which please DM me to share the AWS keys to allow read only access: [Label Image, approx 40 GB](https://example-napari-kapoorlabs.s3.eu-west-3.amazonaws.com/third_dataset_membrane_cellpose_cellpose.tif)

If we can build a feature to better manage the memory during this conversion, or if initially an option is proposed to open the image as image or labels layer that would be of great help in handling such datasets that need to be loaded in memory.

## Motivation

My Napari plugins are used by the community of researchers that have 3D+ time datasets that can take huge memory to load for doing the analysis and even with supercomputers memory inefficient steps can render the whole plugin useless for such researchers, hence managing such memory issues would be very much the need of the hour for our Napari user base. 

## Pitch

Have an option to load the image data as labels or image layer or have a more memory efficient builtin conversion strategy to convert an open image to labels layer.

## Alternatives

Using the builtin terminal to force a data type on the open image to compress the labels for doing the analysis.

## Additional context

The above issue can be reproduced using the provided image or any label image dataset that is 40 GB in size.

**Comment by kephale** [comment]
Note that this is related to https://github.com/napari/napari/issues/470

**Comment by Czaki** [comment]
The problems are here:
https://github.com/napari/napari/blob/9104fd3fcdc83fcb6d831f682f2f3d96b1428a35/napari/layers/_layer_actions.py#L59

1) always convert to `int` even if data are already in int type, 
2) do not check the maximum value.  

If data are already in `int*` dtype, then astype should not be called (as it creates a copy of data).  

I will review and merge if someone would like to create PR to solve this.

**Comment by Carreau** [comment]
[`.astype()`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.astype.html) has the following kwarg:

> copybool, optional
>    By default, astype always returns a newly allocated array. If this is set to false, and the dtype, order, and subok requirements are satisfied, the input array is returned instead of a copy.


I think it's safe enough to pass `copy=false`, and review all the places that use `astype(xxx)`, see if we can set `copy=false` (ie is the things are not mutated).

Additionally it would be good to figure out:
 - can we get a custom linting rule to check astype is passed copy=false ? and is it worth it ? 
 - how can we test the memory usage or if a copy is made.

**Comment by Czaki** [comment]
> I think it's safe enough to pass `copy=false`, and review all the places that use `astype(xxx)`, see if we can set `copy=false` (ie is the things are not mutated).

this still does not solve the problem if you have `uint8` image and call `astype(int, copy=False)` then you will get a copy of the array that consumes much more memory.
