### ISSUE TITLE
Detailed slider for contrast limits not popping up on right mouse click.

### ISSUE THREAD

**Issue by engjen** [napari/napari#5464]
## 🐛 Bug

Detailed slider for contrast limits not popping up on right mouse click.
## To Reproduce

1. Load an image stack in a viewer. Select an image layer. 
2. When I right click on the contrast limit slider, I don't get the popup with the detailed slider. 
3. This is only happening on my mac, not PC. My co-worker's mac works fine. I have a MacBook Pro running Monterey version 12.6.2, intel processor.
4. I tried updating qt with brew but the qt version is still stuck at 5.9 in jupyter, despite having 5.15 available.
     brew info qt5
==> qt@5: stable 5.15.8 (bottled) [keg-only]

# Error message
Traceback (most recent call last):
  File "/Users/engje/miniconda3/lib/python3.9/site-packages/napari/_qt/layer_controls/qt_image_controls_base.py", line 37, in mousePressEvent
    self.parent().show_clim_popupup()
  File "/Users/engje/miniconda3/lib/python3.9/site-packages/napari/_qt/layer_controls/qt_image_controls_base.py", line 190, in show_clim_popupup
    self.clim_popup.move_to('top', min_length=650)
  File "/Users/engje/miniconda3/lib/python3.9/site-packages/napari/_qt/dialogs/qt_modal.py", line 142, in move_to
    screen_geometry: QRect = QGuiApplication.screenAt(
AttributeError: type object 'QGuiApplication' has no attribute 'screenAt'

## Expected behavior

The detailed slider should pop up so I can do a fine adjustment to contrast and see the minimum and maximum values.

## Environment

napari: 0.4.14
Platform: macOS-10.16-x86_64-i386-64bit
System: MacOS 12.6.2
Python: 3.9.12 (main, Apr 5 2022, 01:53:17) [Clang 12.0.0 ]
Qt: 5.9.7
PyQt5: 5.9.2
NumPy: 1.23.2
SciPy: 1.9.1
Dask: 2022.9.0
VisPy: 0.11.0

OpenGL:
- GL version: 2.1 INTEL-18.8.5
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1440x900, scale 2.0
- screen 2: resolution 2560x1440, scale 1.0

Plugins:
- console: 0.0.4
- scikit-image: 0.4.14
- svg: 0.1.6

**Comment by Czaki** [comment]
I'm sorry, but napari requires Qt in version at least 5.12.3 for proper working. 

Also latest version of napari is 0.4.17

**Comment by psobolewskiPhD** [comment]
Your traceback shows a conda install, but you refer to brew Qt.
It looks like you're using the `base` env?
can you try:
`conda info`
in your Terminal to confirm that you have a working conda?
If you do, we recommend using dedicated virtual envs, rather than using `base` or a system-wide python (like brew).
You can try:
```
conda create -y -n napari-env -c conda-forge python=3.9 napari
conda activate napari-env
```
This should give you a conda env with functioning napari 0.4.17 and PyQt5 5.15.7

If you prefer to install by pip, you can still use conda to make & manage the virtual env:
```
conda create -y -n napari-env -c conda-forge python=3.9
conda activate napari-env
pip install "napari[all]"
```

Either way, you just need to remember to use `conda activate napari-env` to access your napari.

**Comment by engjen** [comment]
Hi Peter,

I updated napari with 
conda update napari 
and that ended up updating pyQT, fixing the problem. Apparently the brew Qt is not available to conda. 

Thank you for your help!

**Comment by psobolewskiPhD** [comment]
Np! Glad it worked. And yes, `brew` python stuffs is in its own world. If you have no conda env activated you will get the brew python. But if you have conda, it's best to use the virtual envs and keep things sane.
