### ISSUE TITLE
Reduce test_conda_installer total time ?

### ISSUE THREAD

**Issue by Carreau** [napari/napari#5473]
## 🧰 Task

`test_conda_installer` takes by itself about 15% of the full test-suite time (20-ish cumulative minutes):

<img width="1467" alt="Screen Shot 2023-01-12 at 15 51 03" src="https://user-images.githubusercontent.com/335567/212098500-e2a02cfe-9e2c-4440-82be-684f9a9399f5.png">

<img width="1471" alt="Screen Shot 2023-01-12 at 15 49 33" src="https://user-images.githubusercontent.com/335567/212098520-70029382-2ec2-4bc4-8d5e-4f4a37456168.png">

This seem wasteful, should we maybe cut the number of platform on which we test the conda installer ?

**Comment by psobolewskiPhD** [comment]
This test was removed in https://github.com/napari/napari/pull/5743 (being moved to the new [napari/napari-plugin-manager](https://github.com/napari/napari-plugin-manager)
