### ISSUE TITLE
Warning when creating new layers: invalid value encountered in cast

### ISSUE THREAD

**Issue by thorstenwagner** [napari/napari#5484]
Every time I'm creating a new points layers I get a pop up with the warning:

`.../lib/python3.10/site-packages/napari/layers/base/base.py:1632: RuntimeWarning: invalid value encountered in cast!
`

Is there a way to get rid of that?

I'm using napari 0.4.17

Best,
Thorsten

**Comment by brisvag** [comment]
Can you give a small reproducible example?

**Comment by psobolewskiPhD** [comment]
Yeah, please clarify:
- how are you making the points layer? Script? clicking the button in the UI?
- what platform you're on
- how you installed napari


Pasting the output of `napari --info` (or from the help menu) would be a plus too!
Thanks!

**Comment by thorstenwagner** [comment]
I'm using kubuntu 20.04.

Setup:
```
mamba create -y -n napari -c conda-forge python=3.10
conda activate napari
pip install 'napari[all]'==0.4.17
```

To reproduce it, start `napari` and click on the button for creating a point layer. You will see the warning.

napari --info output:
```
napari: 0.4.17
Platform: Linux-5.15.0-56-generic-x86_64-with-glibc2.31
System: Ubuntu 20.04.5 LTS
Python: 3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:26:04) [GCC 10.4.0]
Qt: 5.15.2
PyQt5: 5.15.7
NumPy: 1.24.1
SciPy: 1.10.0
Dask: 2023.1.0
VisPy: 0.11.0
magicgui: 0.6.1
superqt: unknown
in-n-out: 0.1.6
app-model: 0.1.1
npe2: 0.6.2

OpenGL:
  - GL version:  4.6.0 NVIDIA 470.161.03
  - MAX_TEXTURE_SIZE: 32768

Screens:
  - screen 1: resolution 1920x1200, scale 1.0
  - screen 2: resolution 1920x1200, scale 1.0

Plugins:
  - napari: 0.4.17 (77 contributions)
  - napari-console: 0.0.7 (0 contributions)
  - napari-svg: 0.1.6 (2 contributions)

```

Best,
Thorsten

**Comment by psobolewskiPhD** [comment]
Thanks! I can reproduce this on my mac. 
The key is updating numpy to >1.24.0
I think it may be related to:
https://numpy.org/devdocs/release/1.24.0-notes.html#numpy-now-gives-floating-point-errors-in-casts

**Comment by psobolewskiPhD** [comment]
@thorstenwagner 
So the good news is that this issue has already been fixed:
https://github.com/napari/napari/pull/5423
The bad news is the fix isn't yet released and I cannot tell you at the moment when the next release is coming.
So you have to revert to numpy [v1.23.5](https://github.com/numpy/numpy/releases/tag/v1.23.5)
where this doesn't occur.

**Comment by thorstenwagner** [comment]
Works!!! Thanks!
