### ISSUE TITLE
Cap Maximum CI time with timeout.

### ISSUE THREAD

**Issue by Carreau** [napari/napari#5488]
#5433 mention hangin tests that are hanging.

Instead of consuming 6h of runtime and get a failure, I suggest we set:`job.<id>.<steps?>.timeout-minutes` for each GH action item to at least get a quick failure.

Say current job time +10%, with a minimum of 10 minutes ? Possibly only the tox step to be conservative with what can hang ?

See discussion after  https://github.com/napari/napari/issues/5471#issuecomment-1386714906_

**Comment by kcpevey** [comment]
@Carreau Looks like this one can be closed now?
