### ISSUE TITLE
Layer selection rules

### ISSUE THREAD

**Issue by kne42** [napari/napari#55]
How should we determine how layers can be selected from the GUI list?

Since it is a list, imo it's most intuitive/standard to interact with it in the following way ("this layer" always refers to the last clicked layer):
- click
  * if no layers are selected, select this layer
  * if another layer is selected, (deselect them and) select only this layer
  * if this layer is selected, deselect this layer
- ctrl/cmd click
  * toggle inclusion of this layer in the current selection
- shift click
  * first click: select this layer
  * second click: select this layer and all other layers in between the this and the first clicked layer

**Comment by jni** [comment]
This is certainly the behavior I would expect!

**Comment by royerloic** [comment]
Perfect!
I hope that PyQt5 has some of this builtin....

**Comment by AhmetCanSolak** [comment]
Cannot agree more!

**Comment by sofroniewn** [comment]
Yep, got it - will get on making those changes today! Love the list, thanks!

**Comment by sofroniewn** [comment]
Actually question - should it be possible to have no layers selected? i.e. if you only have one selected and you click on it again does it unselect it so that none are selected or does it just keep it selected. I'd argue for the latter (it is how other similar programs do it) and having no layers selected could be strange from the standpoint of other elements in the gui like the clims sliders. Thoughts?

**Comment by sofroniewn** [comment]
Or does a control click on a singly selected layer leave everything unselected? That behavior happens in some other apps, but I find it strange

**Comment by sofroniewn** [comment]
Similarly, should clicking in the "open space" around the layer widgets unselect all of them?

**Comment by sofroniewn** [comment]
Have updated the PR, please check it out

**Comment by jni** [comment]
Well, at a minimum, I do think Ctrl-click should deselect the existing selection even if it's the only one. Not only is this the behaviour in all other apps I know, it's also self-consistent (ie Ctrl-click *always* toggles selection). I would also argue in favour of deselecting when clicking empty space. Personally I dislike leaving things selected when not actually working on them.

**Comment by sofroniewn** [comment]
Ok - i can make those two changes. I think we'll have to see how having no layers and multiple layers selected interacts with other gui elements like the clims sliders, but that is for another PR / issue!

**Comment by kne42** [comment]
Since not all layers will be defining the left-hand "control" panel, I think we can just collapse it in cases where multiple layers, no layers, or a layer with no control panel are selected.

**Comment by sofroniewn** [comment]
I have made unselection changes and updated the current PR, please let me know if the behavior is as desired.
