### ISSUE TITLE
Sort plugin list

### ISSUE THREAD

**Issue by Theresa-S** [napari/napari#5500]
## 🚀 Feature
Dear developers,

I would find it very useful if the plugin list would appear in alphabetical order. After installing a certain amount of plugins, it gets tedious to find the ones I'm looking for.

Best,
Theresa

**Comment by psobolewskiPhD** [comment]
Thanks for the feedback @Theresa-S 
It's definitely something that needs to be improved, both in the `installed plugins` listing in the Plugin Manager window and in the `Plugins` menu.

**Comment by DragaDoncila** [comment]
I have opened #7266 to address the issue of listing in the plugins menu and samples menu. I checked the plugin installer and it seems that the installed plugins **are** now listed alphabetically, so #7266 should address the last portion of this issue. Let me know if that's not the case for the plugin installer - might need to move this issue over to napari/napari-plugin-manager
