### ISSUE TITLE
Installing with conda fails to solve environment on macOS 13 (x64)

### ISSUE THREAD

**Issue by andy-sweet** [napari/napari#5509]
## 🐛 Bug

Following the [recommended installation instructions](https://napari.org/stable/tutorials/fundamentals/installation.html#install-as-python-package-recommended) and installing from `conda-forge` currently fails on my mac.

I'm pretty sure I tested this when handling the 0.4.17 release with success. One thing that's changed locally between that time and now is upgrading macOS 12 to 13. Though changes to other dependencies and their feedstocks could also have caused this issue.

## To Reproduce

I ran the following commands

```
conda create -n napari-test-conda python=3.9
conda install -c conda-forge napari
```

and the second one gets stuck on solving the environment (I've waited over 10 minutes and others on similar hardware have waited longer)

```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: | 
```

## Expected behavior

`conda` should solve the environment in < 10 minutes and I should be able to run napari when it's done.

## Environment

- napari version 0.4.17
- macOS 13.1 (Ventura)
- Intel CPU (x86-64)

## Additional context

Installing with `pip` or `mamba` both work.

**Comment by Czaki** [comment]
maybe we should suggest to use at least mamba solver? 

https://www.anaconda.com/blog/a-faster-conda-for-a-growing-community

(but I remember that also installing this may take over 20 minutes)

**Comment by andy-sweet** [comment]
> maybe we should suggest to use at least mamba solver?

I installed mamba using conda (from conda-forge) pretty quickly. And mamba solved the environment in less than a few minutes (even in an existing conda environment). Though so did pip.

**Comment by andy-sweet** [comment]
@jaimergp and @goanpeca: just an FYI in case there's anything quick you can do to diagnose the underlying issue here. I rand `conda` with `-v` and `-vv`, but can only loosely interpret what the solver is doing.

**Comment by Czaki** [comment]
> I installed mamba using conda (from conda-forge) pretty quickly.

this post that I link is describing how to change conda settings to use libmamba solver even when calling `conda`

**Comment by psobolewskiPhD** [comment]
The docs (dev version of site) do actually adress this:
<img width="762" alt="image" src="https://user-images.githubusercontent.com/76622105/215032279-e651309b-378e-4b16-adb7-78ce0cb3298e.png">
(PR https://github.com/napari/docs/pull/51)

I'm not sure what the advantage is of using mamba solver in conda rather than just doing `conda install mamba` and using mamba. For me at least since mamba 1.0 every `conda ...` is just replaced with `mamba ...`

**Comment by Czaki** [comment]
> I'm not sure what the advantage is of using mamba solver in conda rather than just doing conda install mamba and using mamba.

That it will work even if someone copy and paste command from internet.

**Comment by psobolewskiPhD** [comment]
Also, I notice in the live dev docs (screenshot above from napari.org) the napari version is wrong. 😑 
But it is correct in napari/docs PR builds:
<img width="878" alt="image" src="https://user-images.githubusercontent.com/76622105/215052126-93ff21a3-73b1-4af6-b7b7-ae5efb5dfdf1.png">

So I guess a different build action or env is responsible for the live docs on napari.org.
Will investigate.
Edit: I think I tracked down the problem. I'll make a PR later.

**Comment by psobolewskiPhD** [comment]
The mamba and mamba solver tips will be in the 0.4.18 stable docs. 
I think that's all we can do from our side?
@napari/packaging

**Comment by psobolewskiPhD** [comment]
FYI, looks like both miniconda and miniforge ship with the libmamba solver and it will be the default in Sept 2023.
I think we can close, since we provide info on using the mamba solver and it will be a moot point soon.
