### ISSUE TITLE
Conda build of napari-plugin fails because of something within napari related to vispy

### ISSUE THREAD

**Issue by haesleinhuepf** [napari/napari#5511]
## 🐛 Bug

Hi all,

I just noted that some of my napari-plugins are not longer updated on conda-forge because of a napari-vispy related bug. [detailed error log here](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=642181&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=1581).

In very short it says:
```
File "/home/conda/feedstock_root/build_artifacts/napari-accelerated-pixel-and-object-classification_1673821267566/_test_env_[...]
/lib/python3.11/site-packages/napari/utils/event.py", line 61, in <module>
    from vispy.ext.six import string_types
ModuleNotFoundError: No module named 'vispy.ext.six'
Tests failed for napari-accelerated-pixel-and-object-classification-0.12.2-pyhd8ed1ab_0.conda - moving package to /home/conda/feedstock_root/build_artifacts/broken
WARNING:conda_build.build:Tests failed for napari-accelerated-pixel-and-object-classification-0.12.2-pyhd8ed1ab_0.conda - moving package to /home/conda/feedstock_root/build_artifacts/broken
TESTS FAILED: napari-accelerated-pixel-and-object-classification-0.12.2-pyhd8ed1ab_0.conda
##[error]Bash exited with code '1'.

```

Is there anything I can do about it? Like, pinning vispy?

Any hint is welcome!

Best,
Robert

## To Reproduce

1.
2.
3.

## Environment

 - Please copy and paste the information at napari info option in help menubar here:

 - Any other relevant information:

**Comment by Czaki** [comment]
There is something strange as conda decide to use napati==0.3.4
```
napari:                                             0.3.4-py_0
```
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=642181&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=417

Maybe add napari>=0.4.14 to test requirements?

**Comment by psobolewskiPhD** [comment]
I think the ultimate cause may be python 3.11? I'd bet that's why you're getting the 0.3.4 napari.

**Comment by haesleinhuepf** [comment]
Ok, cool. Pinning `napari>=0.4.11` solved the problem ([see here](https://github.com/conda-forge/napari-accelerated-pixel-and-object-classification-feedstock/pull/18/files#diff-f3725a55bf339595bf865fec73bda8ac99f283b0810c205442021f29c06eea9aR30)) Thanks for the lightspeed response @Czaki !
