### ISSUE TITLE
Newly created label images don't have the same scale as underlying images

### ISSUE THREAD

**Issue by haesleinhuepf** [napari/napari#5512]
## 🐛 Bug

Users annotate the wrong pixels in label images if the label image was created on top of an image that has scale set to something different from [1,1,1]

## To Reproduce

1. Open napari
2. Open an image (CZI, ND2, ...) where the pixel size is not 1x1x1
3. Create a new label image
4. Draw in the label image
5. Save both layers to disc, e.g. as TIF and reload them
6. You will see that the user has drawn in the wrong pixels

## Expected behavior

When creating a new labels layer on top of an image, the labels layer should have the same `scale` as the underlying image layer to prevent this issue.

## Environment

 - Please copy and paste the information at napari info option in help menubar here:

```
napari: 0.4.15
Platform: Windows-10-10.0.19045-SP0
Python: 3.9.12 | packaged by conda-forge | (main, Mar 24 2022, 23:18:12) [MSC v.1929 64 bit (AMD64)]
Qt: 5.15.6
PyQt5: 5.15.7
NumPy: 1.23.2
SciPy: 1.10.0
Dask: 2023.1.1
VisPy: 0.9.6

OpenGL:
- GL version: 4.6.14802 Compatibility Profile Context 21.40.18.19 30.0.14018.19001
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1200, scale 1.0

Plugins:
- PlatyMatch: 0.0.3
- RedLionfish: 0.6
- bfio: 2.3.0
- clEsperanto: 0.22.0
- console: 0.0.7
- devbio_napari: 0.8.1
- napari-3d-ortho-viewer: 0.0.1
- napari-accelerated-pixel-and-object-classification: 0.12.2
- napari-assistant: 0.4.4
- napari-brightness-contrast: 0.1.8
- napari-clusters-plotter: 0.6.0
- napari-crop: 0.1.6
- napari-curtain: 0.1.1
- napari-folder-browser: 0.1.3
- napari-layer-details-display: 0.1.4
- napari-mouse-controls: 0.1.3
- napari-plot-profile: 0.2.2
- napari-plugin-search: 0.1.3
- napari-process-points-and-surfaces: 0.3.3
- napari-segment-blobs-and-things-with-membranes: 0.3.3
- napari-simpleitk-image-processing: 0.4.5
- napari-tabu: 0.1.5
- napari-time-slicer: 0.4.9
- napari-tools-menu: 0.1.18
- napari-workflow-inspector: 0.2.2
- napari-workflow-optimizer: 0.1.4
- napari_skimage_regionprops1: 0.7.0
- napari_skimage_regionprops2: 0.7.0
- ome-types: 0.3.2
- scikit-image: 0.4.15
- svg: 0.1.6
- the-segmentation-game: 0.2.0
```

 - Any other relevant information:

**Comment by Czaki** [comment]
> Save both layers to disc, e.g. as TIF and reload them

The problem is here. Currently, napari does not save scale to file. if you update the scale via console it will be in a proper place. 

This is a duplicate of #5162

**Comment by haesleinhuepf** [comment]
> This is a duplicate of #5162

No it's not. #5162 is about saving files. The bug described here is about creating labels layers with scale. The saving/loading procedure above just serves demonstration purposes.

**Comment by Czaki** [comment]
> The bug described here is about creating labels layers with scale

Could you just check the scale of created labels layer? save and load do not check values.

I load file with scale (plugin reader) and add labels with button. The result is:

```
viewer.layers[0].scale
Out[1]: array([ 1.,  1., 64., 64.])

viewer.layers[1].scale
Out[2]: array([ 1.,  1., 64., 64.])
```

so you could see that scale is properly copied. 


> The saving/loading procedure above just serves demonstration purposes.

If during saving the layer metadata is ignored and not saved, then the loaded layer will have a scale equal to 1, 1, ...

**Comment by haesleinhuepf** [comment]
> so you could see that scale is properly copied.

You're right! So I need to go back to my collaborator and find out what they were doing. Sorry for the headsup. I'll reopen this issue when we can better reproduce it or open a new one.

**Comment by Czaki** [comment]
> You're right! So I need to go back to my collaborator and find out what they were doing. Sorry for the headsup. I'll reopen this issue when we can better reproduce it or open a new one.

Inheriting scale work only if all existing layers have the same scale. If there will be more two or more layers with different scales, then napari will create a label layer with scales 1,1,1,...

**Comment by haesleinhuepf** [comment]
> Inheriting scale work only if all existing layers have the same scale.

Awesome hint. Thanks!

**Comment by Czaki** [comment]
> > Inheriting scale work only if all existing layers have the same scale.
> 
> Awesome hint. Thanks!

If you find an intuitive way to determine the scale for such cases, I will be happy. 
the `1,1,1,...` is only because we do not have a better idea of how to do this.
