### ISSUE TITLE
Support installing on Python 3.11

### ISSUE THREAD

**Issue by dstansby** [napari/napari#5514]
## 🚀 Feature
[In the installation instructions](https://napari.org/stable/#from-pip-with-batteries-included), it says
> napari can be installed on most macOS, Linux, and Windows systems with Python 3.8-3.10 using pip:

It would be good to support installing `napari` on Python 3.11. I'm not sure if this needs upstream changes or changes to `napari` itself, but thought it was worth at least opening an issue to track this.

**Comment by psobolewskiPhD** [comment]
Thanks for the issue.
We actually have a PR already looking into this.
https://github.com/napari/napari/pull/5439

**Comment by psobolewskiPhD** [comment]
FYI, if you want to experiment, napari can be installed and run on 3.11 via conda-forge. Or for an editable install, using `pamba` (https://github.com/tlambert03/pamba).
Just ran it and so far so good when just playing with sample images. I do get this warning:
```
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
```

**Comment by Czaki** [comment]
Python >= 3.11.1 is supported since napari 0.4.18
