### ISSUE TITLE
Clean install of `napari` fails using pip on macOS arm64

### ISSUE THREAD

**Issue by dstansby** [napari/napari#5515]
## 🐛 Bug

Following the [instructions to install napari](https://napari.org/stable/#from-pip-with-batteries-included) fails for me.

## To Reproduce

1. `conda create -y -n napari-env -c conda-forge python=3.9`
2. `conda activate napari-env`
3. `pip install "napari[all]"`

The last command errors out with
```python
Collecting PyQt5!=5.15.0,>=5.12.3
  Using cached PyQt5-5.15.8.tar.gz (3.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      Querying qmake about your Qt installation...
      Traceback (most recent call last):
        File "/Users/dstansby/mambaforge/envs/napari-env/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 144, in prepare_metadata_for_build_wheel
          hook = backend.prepare_metadata_for_build_wheel
      AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/Users/dstansby/mambaforge/envs/napari-env/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "/Users/dstansby/mambaforge/envs/napari-env/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/dstansby/mambaforge/envs/napari-env/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 148, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "/private/var/folders/m4/v0b71w0s22z34l90psw9j82w0000gn/T/pip-build-env-ravz8xlg/overlay/lib/python3.9/site-packages/sipbuild/api.py", line 46, in build_wheel
          project = AbstractProject.bootstrap('wheel',
        File "/private/var/folders/m4/v0b71w0s22z34l90psw9j82w0000gn/T/pip-build-env-ravz8xlg/overlay/lib/python3.9/site-packages/sipbuild/abstract_project.py", line 87, in bootstrap
          project.setup(pyproject, tool, tool_description)
        File "/private/var/folders/m4/v0b71w0s22z34l90psw9j82w0000gn/T/pip-build-env-ravz8xlg/overlay/lib/python3.9/site-packages/sipbuild/project.py", line 601, in setup
          self.update(tool)
        File "project.py", line 166, in update
      sipbuild.exceptions.UserException
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

## Expected behavior
`napari` installs succesfully. 

## Environment

 - Please copy and paste the information at napari info option in help menubar here:

 - Any other relevant information:

**Comment by psobolewskiPhD** [comment]
What platform are you on? architecture?
The failure is due to lack of a PyQt5 wheel on pypi.
What you can try is to install it from conda into your env:
`conda install -c conda-forge pyqt`
and then `pip install napari` which will *not* try to get pyqt5 from pypi.

**Comment by dstansby** [comment]
I'm on macOS Ventura with an M1, which would explain why PyQt doesn't have a wheel. I can't find anywhere (apart from a mailing list) to report or request that upstream. 

Installing `pyqt` from conda worked well. In terms of improving the install instructions here, I think it's worth saying that installing using `pip` can sometimes fail, and directing users to try `conda` if it does fail. I can open a PR for that.

**Comment by Czaki** [comment]
There is such PR https://github.com/napari/docs/pull/89
But it will be nice if next person with macOS ARM experience rewiew it.

**Comment by psobolewskiPhD** [comment]
That would do it. there are no Qt5 wheels on pypi for arm64 (no pyqt5, no pyside2).
So on arm64 you need to provide the QT backend, either build yourself, use conda-forge, or install Qt6 from pypi.
We actually have a docs PR addressing this:
https://github.com/napari/docs/pull/89

Even once it's merged it's a bit of an issue because it will be in the dev docs and not what you get at napari.org.

**Comment by dstansby** [comment]
Woops, I spoke too soon. Installing `pyqt` from conda:
```
conda create -y -n napari-env -c conda-forge python=3.9 pyqt
conda activate napari-env
python -m pip install "napari[all]"
```

actually still tries to install `PyQt5` using pip. It doesn't seem to error out immediately, but I don't fancy waiting for it to build from source!

**Comment by psobolewskiPhD** [comment]
It's because you are using `napari[all]` which is just `napari[pyqt]` under the hood.
If you provide your own QT, then use just `pip install napari`

**Comment by Czaki** [comment]
> actually still tries to install `PyQt5` using pip. It doesn't seem to error out immediately, but I don't fancy waiting for it to build from source!

It is solved here #5438, but also has not been released yet. 

@psobolewskiPhD, we need to push the release, but it requires a release manager...

**Comment by dstansby** [comment]
Ah that worked, thanks! For the user facing install instructions, is there a good reason not to recommend installing using `conda` first so the first set of instructions you come to in the docs works for all platforms?

**Comment by Czaki** [comment]
> is there a good reason not to recommend installing using `conda` first so the first set of instructions you come to in the docs works for all platforms?

Many user does not have conda, not all plugins have a conda version, and mixing (part of packages installed from conda, a part from pip) conda with pip may lead to multiple problems.

**Comment by psobolewskiPhD** [comment]
@Czaki that PR changes [dev] while here the question is [all] and the general install instructions.

@dstansby That's being discussed in the docs PR: 
https://github.com/napari/docs/pull/89#issuecomment-1384675344
and on zulip: https://napari.zulipchat.com/#narrow/stream/270578-reviews/topic/docs.2389

**Comment by psobolewskiPhD** [comment]
@Czaki If we edit the README: https://github.com/napari/napari#installation
That bypasses release right? it just goes live when merged? So could add something like:
```
Note: `pip install "napari[all]"` installs the default Qt framework—currently 
PyQt5—in addition to napari, from PyPI. If there are no wheels (binaries)
available for your platform, this will fail. However, you can install a Qt framework
from conda-forge, for example `conda install pyqt`, and then `pip install napari`
to just install napari.
```

(I think people may think `all` means more than just `pyqt`)

**Comment by psobolewskiPhD** [comment]
@dstansby feedback on https://github.com/napari/docs/pull/89 very welcome.
If you think those instructions would have helped prevent/solve this issue or you have an option on (or experience with) Rosetta2 python, we're all ears.

**Comment by psobolewskiPhD** [comment]
@dstansby I made some changes to adress your comments and @jni merged https://github.com/napari/docs/pull/89
Of course those docs won't be on the stable page until a release, but they are available if someone selects dev from the version switcher—not so obvious.

So the last thing we could do is modify the README on GitHub, as per:
https://github.com/napari/napari/issues/5515#issuecomment-1408508046

Anyone have any thoughts on that?

**Comment by dstansby** [comment]
Thanks! I think the improved docs in https://github.com/napari/docs/pull/89 address this so I'll close. If I find any more issues/have any other suggestions I'll open a new issue or pull request over in the docs repo.
