### ISSUE TITLE
Installed widget plugin is not shown in the plugin menu

### ISSUE THREAD

**Issue by leoguignard** [napari/napari#5516]
Hello everyone,

First, thanks a lot for all the amazing work!
I have this issue/bug(?) that likely come from my end but I am not sure how to solve it.

## 🐛 Bug

When I install a plugin from the sources (`pip install -e .`), the plugin is not shown

## To Reproduce

```
conda create -n test python=3.10
conda activate test
conda install pyqt #workin on an macOs M1 chip
pip install napari
pip install git+https://github.com/GuignardLab/napari-3D-registration.git
```

The plugin is somewhat seen but not accessible:
<img width="1081" alt="Screenshot 2023-01-30 at 16 10 00" src="https://user-images.githubusercontent.com/31226251/215515491-6f129d42-e7ca-4bc8-a136-4dbb8498d947.png">
<img width="323" alt="Screenshot 2023-01-30 at 16 10 10" src="https://user-images.githubusercontent.com/31226251/215515509-b60bba18-0f03-4b5d-9b41-2717a03f3537.png">

Side notes:
1. other plugins installed via the napari GUI are visible
1. "ticking on" the plugin via the GUI does not work, it is ticked off when I restart napari
1. installing the plugin by first clonning the repo and then running `pip install -e .` gives the same result

It is likely an issue on my side but I do not have any error message so it is not easy to debug

## Expected behavior

The plugin should be accessible via the Plugins dropdown menu

## Environment
```
napari: 0.4.17
Platform: macOS-12.2.1-arm64-arm-64bit
System: MacOS 12.2.1
Python: 3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:25:29) [Clang 14.0.6 ]
Qt: 5.15.6
PyQt5: 5.15.7
NumPy: 1.24.1
SciPy: 1.10.0
Dask: 2023.1.1
VisPy: 0.11.0
magicgui: 0.6.1
superqt: unknown
in-n-out: 0.1.6
app-model: 0.1.1
npe2: 0.6.2

OpenGL:
- GL version: 2.1 Metal - 76.3
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1512x982, scale 2.0
```

## Additional context

I manage to make it work sometimes not sure why it does work sometimes and not other times :/

The plugin seems to be somewhat correctly installed, the following commands in python do not raise any error:
```python
from napari import Viewer
from napari_3d_registration import SpatialRegistrationWidget

v = Viewer()
s = SpatialRegistrationWidget(v)
```

**Comment by Czaki** [comment]
Could you mark the checkbox (to enable plugin) and if it is still missed then open "Plugin Errors" and see what error is reported?

**Comment by leoguignard** [comment]
When I mark the checkbox it doesn't raise any error.
When I close the "Install/Uninstall plugins..." window and reopen it, it is not ticked anymore
(video on its way to show the behavior)

**Comment by leoguignard** [comment]
https://user-images.githubusercontent.com/31226251/215519587-5d1f21ea-0788-4050-b834-4762797e8a8b.mov

**Comment by psobolewskiPhD** [comment]
Hmm, I can't reproduce with a fresh conda env (python 3.10) and napari 0.4.17 installed from conda: I see the plugin and the two widgets. 
Same if I just install pyqt from conda-forge and napari from pip.
(arm64 macOS 13.1)
<img width="354" alt="image" src="https://user-images.githubusercontent.com/76622105/215522309-458cb257-5d63-4f1c-ac52-fd82b2275177.png">

```
napari: 0.4.17
Platform: macOS-13.1-arm64-arm-64bit
System: MacOS 13.1
Python: 3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:25:29) [Clang 14.0.6 ]
Qt: 5.15.6
PyQt5: 5.15.7
NumPy: 1.24.1
SciPy: 1.10.0
Dask: 2023.1.1
VisPy: 0.11.0
magicgui: 0.6.1
superqt: unknown
in-n-out: 0.1.6
app-model: 0.1.1
npe2: 0.6.2

OpenGL:
  - GL version:  2.1 Metal - 83
  - MAX_TEXTURE_SIZE: 16384

Screens:
  - screen 1: resolution 1680x1050, scale 2.0

Plugins:
  - napari: 0.4.17 (77 contributions)
  - napari-3D-registration: 0.0.1 (4 contributions)
  - napari-console: 0.0.7 (0 contributions)
  - napari-svg: 0.1.6 (2 contributions)
 
```


Edit: wait, you get the issue when you `pip install -e .` or when using `pip install git...`?
Also any chance you installed it both ways into the same environment? I've had a similar issue once, which I think was related to the two different installs, one leaving something in `site-packages`

**Comment by leoguignard** [comment]
Hello @psobolewskiPhD,
thanks a lot for trying on your end!

I guess the "good news" is that the problem comes from me.
The bad one is I don't know what's the problem ...

**Comment by Czaki** [comment]
What happens if you call `napari --reset` to clean the settings?

**Comment by psobolewskiPhD** [comment]
In case you missed my edit:
You get the issue when you `pip install -e .` or when using `pip install git...`?
Also any chance you installed it both ways into the same environment? I've had a similar issue once, which I think was related to the two different installs, one leaving something in site-packages

**Comment by leoguignard** [comment]
@Czaki: when I call `napari --reset` it then works!
So I guess, I have some weird settings in some napari elsewhere then, is that it?

@psobolewskiPhD: I missed your edit indeed, I was getting the issue with both installations (while recreating a new environment for each installation "type").

**Comment by Czaki** [comment]
> So I guess, I have some weird settings in some napari elsewhere then, is that it?

yes, I remind that I meet something like this in the past, but newer understand what happens.

**Comment by leoguignard** [comment]
It also might be a problem when installing from a cached version?

The reason why I am saying that is that it is not the first time it happened to me:
Creating an evironment and the plugin would not show up. I would drop it for a few days/weeks and come back to it and it would magically work.
Note that it is not a problem for all plugins, for example I could install the other plugins without problem.

Anyway, this time, instead of abandoning, I wanted to at least report the behavior ...

**Comment by Czaki** [comment]
> Anyway, this time, instead of abandoning, I wanted to at least report the behavior ...

it is really valuable. I need to remember to ask for backup first to allow understanding underlying errors.

**Comment by psobolewskiPhD** [comment]
Well, at the moment all envs share the same napari settings file. So if you have multiple napari envs with different versions or something it's possible for stuff like keybinds, installed plugins, etc. to get messed up.
This will be improved in the next release when each env will have it's own settings.

Edit: Just to emphasize, at the moment even a clean env doesn't get you clean settings. you need `napari --reset` for that, but that will nuke settings from other envs too. This will be fixed in the next release by https://github.com/napari/napari/pull/5333

**Comment by psobolewskiPhD** [comment]
I'll try to test this later, but I wonder if this is the pathology, assuming 2 envs with live 0.4.17 so shared settings:
start with 1 napari env
1. install plugin (e.g. example-plugin)
2. disable it (via plugin menu manager)
3. relaunch to confirm it's not in the menu
4. make a new napari env
5. install *same* plugin
6. is it in plugin menu?
7. quit napari
8. relaunch
9. is it in plugin menu?


Edit:
Ok, so it's not as degenerate as I feared. If you use the Plugin > Install Plugin for everything, then it all works as expected.
*However*, if in the 2nd (fresh) env you install the plugin using pip from the command line, then the newly installed plugin won't appear, but it is installed, just disabled due to the shared settings. You can fix it through the Plugin > Install Plugin manager. It will then appear again in the first env.

**Comment by psobolewskiPhD** [comment]
Another thing that comes to mind:
The settings file is written to disk immediately when you click the checkbox.
Any chance you somehow don't (always) have write access to the location?
If the setting change isn't written, then it can also result in wonky behavior.
You appear to be on Mac—I think? not totally standard UI—so it should be `~/Library/Application Support/Napari`

Or have you ever had two napari from two two different envs open? 
That could also mess stuff up I think.
But still hard to explain the video where you open the installer, click, close, reopen and it's still unchecked.

**Comment by leoguignard** [comment]
Indeed, I often have two napari from two different envs open (most of the time for test purposes), so that might be the problem for me.

**Comment by leoguignard** [comment]
Thanks a lot for the quick and efficient answers! That was really helpful!

**Comment by psobolewskiPhD** [comment]
@leoguignard The issue was resolved and should be prevented with the next release, so closing.
If it reoccurs, feel free to re-open with more details!
