### ISSUE TITLE
Add a public way to enable async slicing

### ISSUE THREAD

**Issue by andy-sweet** [napari/napari#5517]
# Description

The `Layer._force_sync` flag effectively acts as a feature/experimental flag that allows to control if async slicing is enabled. If it's true, then we effectively disable async slicing, otherwise we perform it when a layer type supports it.

The goal of this task is to provide at least one public way of controlling that currently private flag. Some possibilities among others.

- Define a napari setting/preference in `NapariSettings`. This will be present in the GUI and will be persisted between napari sessions.
- Define an environment variable name that will be used by napari (e.g. `NAPARI_ASYNC_SLICING`).

One thing that complicates the effort is the [old experimental async implementation](https://napari.org/stable/guides/rendering.html#asynchronous-rendering), which also defines napari settings and environment variables to control whether the async and tiled rendering options are enabled.

We should not try to support or likely even allow the new and old async to be enabled at the same time. Therefore, if both settings are present, we should make them mutually exclusive. Alternatively, we could explore removing the old async style.

# Output

The output of this task should be a PR that adds at least one visible/public way of controlling whether async slicing is enabled or not. This PR should be only be merged after #5236 is done, but could be drafted, prepared, and even reviewed before then.

**Comment by kcpevey** [comment]
TOPIC: Where will this setting live on the UI?
**If we are going to remove the old async altogether** - this is an open question. 
**If the old async will remain** - then they will need to be mutually exclusive - which means that the new async controls will need to sit on the same window as the old async (under Settings -> Experimental). And we'd need to rework it so that the widgets interact (i.e. high level radio buttons for old async and new async which only allow one to be selected at a time. If new async is selected, the sub widgets for old async get deselected and disabled). 

OTHER NOTES:
If we change this flag in the Settings - it should immediately work without restart. 

If we change this flag via the environment variables, a restart will be required.

**Comment by andy-sweet** [comment]
@kcpevey

I got some clarification around this issue from the core-devs and wider community on zulip: https://napari.zulipchat.com/#narrow/stream/212875-general/topic/Old.20to.20new.20async.20migration/near/327096550

I also merged #5377, so this should be easier to test now.

**Comment by kcpevey** [comment]
The result of the discussion is this approach:
```
1.) Replace async setting and remove octree setting.
Remove the octree setting without deprecation since it is experimental.
For anyone we missed here that does need the octree setting, napari 0.4.17 and earlier are still available.
Replace the async setting so that it uses the new async code instead of the old one.

This is simple for napari developers (less code) and users (no changes needed).

But may be confusing since the new async may behave slightly differently to the old one.
```

I started down the path of not only removing the octree setting, but the whole octree implementation. I quickly discovered that there is quite a bit of related code. Should I just focus on the disabling (or making invisible) the octree widget in one PR and fully remove octree in another?

**Comment by andy-sweet** [comment]
> Should I just focus on the disabling (or making invisible) the octree widget in one PR and fully remove octree in another?

That's the approach I would take, so sounds good to me.

I think the trickier thing here may be what happens when you effectively replace the semantics of the existing async rendering to enable to new async slicing instead.

In both cases there might be certain tests that start failing. I think it might be OK to disable those for now.

There are quite a few unknowns here, so feel free to ask questions here, on zulip, or we can find some time to video chat too!

**Comment by kcpevey** [comment]
![image](https://user-images.githubusercontent.com/15659110/223509116-95686107-bfa0-47c6-87df-f57d612f8310.png)

At first I thought to make the octree widgets invisible, but the QLabel widget doesn't have that option, nor does it allow for opacity changes (that I am aware of anyhow). So I settled on disabling and changing the opacity of the checkbox as was done in the code previously.
