### ISSUE TITLE
Qt6: visual error: non-theme border around LayerControlsContainer and Console (maybe macOS only?)

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari/napari#5529]
## 🐛 Bug

Using Qt6 backends there are borders around the LayerControls dock widget and the Console dock widget (when open). If the napari theme matches the OS theme, the border is very subtle, so you may need to toggle theme to see. 
Dark theme (OS light theme)
<img width="1153" alt="image" src="https://user-images.githubusercontent.com/76622105/216760203-04967a18-1adc-44e6-a476-db5462f8b924.png">
Light theme (OS light theme)
<img width="1153" alt="image" src="https://user-images.githubusercontent.com/76622105/216760237-41f87f5d-bfeb-45e3-b915-3d40cef0114b.png">

It's the padding pixels that use color from underneath the widgets. If one undocks the widgets, the issue disappears. Also during undocking, once removed from the dock, one can briefly see that the area beneath the widget is the same color as the problem border, before the theme color kicks in. 

This was originally reported in the Qt tracking issue:
https://github.com/napari/napari/issues/3880

## To Reproduce

1. in a fresh env, install pyqt6 or pyside6
2. `pip install napari` (no [all] to use the Qt6 backend)
3. open the viewer and open the console

## Expected behavior

The border should remain consistent with the napari theme.

## Environment

PySide6, arm64 macOS 13.2, napari `main` (post Qt6 fix PRs)

## Additional context

This may be macOS specific.

**Comment by aganders3** [comment]
Just FYI @psobolewskiPhD this was not closed by merging #5533, as it was only properly linked to the previous (now closed) PR. Sorry!

**Comment by psobolewskiPhD** [comment]
Thanks for the heads up, I linked this issue and am closing now.
