### ISSUE TITLE
viewer axes point in basically random directions 😂

### ISSUE THREAD

**Issue by jni** [napari/napari#5536]
## 🐛 Bug

I was trying to explain anisotropic image resolution to someone the other day and this napari bug severely undermined my otherwise excellent demonstration. 😂 TLDR: the axes 0, 1, 2 displayed in the viewer by default are not the same as the axes 0, 1, 2 on the input array (and by extension the positions of the `layer.scale` parameter).

## To Reproduce

```python
import numpy as np
import napari

volume = np.random.random((64, 64, 64))

viewer, layer = napari.imshow(volume, scale=(1, 2, 4), ndisplay=3)
viewer.axes.visible = True

napari.run()
```

<img width="948" alt="Screen Shot 2023-02-07 at 9 05 39 pm" src="https://user-images.githubusercontent.com/492549/217215889-c6aca123-f529-4a82-9893-4d585ac69256.png">

## Expected behavior

The code produces a 3D oblong/rectangular prism with sides of length 64, 128, and 256 in world-space. Given the scale setting above, one would expect axis 0 to point in the direction of the side of length 64, 1 for 128, and 2 for 256. Instead, you see 0 pointing along the side of length 128, 1 along the side of length 256, and 2 along the side of length 64. (**Edited:** [fixed typo](https://github.com/napari/napari/issues/5536#issuecomment-1420555774), 0->2)

## Environment

```
napari: 0.4.17rc4.dev169+g57fa998e7.d20221219
Platform: macOS-12.5.1-arm64-arm-64bit
System: MacOS 12.5.1
Python: 3.10.5 | packaged by conda-forge | (main, Jun 14 2022, 07:07:06) [Clang 13.0.1 ]
Qt: 5.15.4
PyQt5: 5.15.7
NumPy: 1.22.4
SciPy: 1.8.1
Dask: 2022.9.1
VisPy: 0.12.1
magicgui: 0.5.1
superqt: 0.3.2
in-n-out: 0.1.5
app-model: 0.1.1
npe2: 0.6.1

OpenGL:
  - GL version:  2.1 Metal - 76.3
  - MAX_TEXTURE_SIZE: 16384

Screens:
  - screen 1: resolution 1800x1169, scale 2.0

Settings path:
  - /Users/jni/Library/Application Support/napari/all_f332943dd4a538ce2ff3134fd0ff74396d8d8b23/settings.yaml
Plugins:
  - affinder: 0.2.3.dev12+g6d235f9 (2 contributions)
  - napari: 0.4.17rc4.dev169+g57fa998e7.d20221219 (77 contributions)
  - napari-console: 0.0.6 (0 contributions)
  - napari-multiscale-rendering-prototype: 0.0.1 (6 contributions)
  - napari-pymeshlab: 0.0.5 (17 contributions)
  - napari-skeleton-curator: 0.1.dev21+gf2de859 (4 contributions)
  - napari-svg: 0.1.6 (2 contributions)
  - napari-watershed: 0.0.0 (4 contributions)
  - skan: 0.11.0.dev0 (2 contributions)
  - zarpaint: 0.1.1.dev20+g61ba4a0 (14 contributions)
```

## Additional context

Semi-related: #4633

**Comment by psobolewskiPhD** [comment]
> Given the scale setting above, one would expect axis 0 to point in the direction of the side of length 64, 1 for 128, and 2 for 256. Instead, you see 0 pointing along the side of length 128, 1 along the side of length 256, and 0 along the side of length 64.

That should be 2 for the 64 side...
But yeah, that's pretty wierd. I double checked with (64, 128, 256) array and get the same effect: the axes are (2, 0, 1). So it's not random, but rather an off-by-one error?
Clicking the axis order button fixes it:
![image](https://user-images.githubusercontent.com/76622105/217221840-9358efed-62da-4562-a59d-6949e9871ffa.png)

**Comment by jni** [comment]
> That should be 2 for the 64 side...

oops, edited the original! 🙏 

>  Clicking the axis order button fixes it:

😂 That's... weird. LOL

**Comment by andy-sweet** [comment]
Seems like this isn't broken on 0.4.17, so we can git bisect to find the breaking PRs - my guess is my https://github.com/napari/napari/pull/5004. That fixes some other issues related to `order`, but may have introduced this one accidentally. If so, would be great to add at least one vispy test to cover the example above!

**Comment by andy-sweet** [comment]
I'm planning to take a look at this, but others should feel too!

**Comment by andy-sweet** [comment]
Made a little progress by writing some tests that should pass, but one doesn't. See the PR over on my fork for details: https://github.com/andy-sweet/napari/pull/45

I also ran `git bisect` to find that the overlays refactor https://github.com/napari/napari/pull/4907 is the culprit here.

My understanding is that this is mostly a problem of keeping `ViewerModel.dims.axis_labels` in sync with the vispy axes text labels (including at initialization time). Note that a workaround is to set `viewer.dims.axis_labels = ('z', 'y', 'x')` (or any value that's different to the current ('2', '1', '0')).

Also, both @jni and @psobolewskiPhD mentioned the 2-label in the comments above, but I don't see it when I ran the example and I don't see it in the screenshots above. That behavior is also consistent with the failing test I defined.

**Comment by psobolewskiPhD** [comment]
@andy-sweet yeah, you're right the `2` label of the axes doesn't actually show think 🤔 
I was assigning it by process of elimination 🤣

**Comment by jni** [comment]
Same: I figured it was an issue with depth-setting and the 2 label being occluded 😬

**Comment by psobolewskiPhD** [comment]
The plot thickens:
For a 2D slice of a 3D image I'm not sure I get the axes either:
<img width="361" alt="image" src="https://user-images.githubusercontent.com/76622105/219058921-22d6fa4d-8182-45d4-b73f-21c5a64de6e2.png">
Shouldn't it be ZYX
The slider is showing axis zero, that's Z, so the two visible in the corner should be 1 pointing down and 2 pointing right?
Also no matter how I change the order of the axes, the visible axes always shows 1 to the right and 0 down. Axis two is never shown.
Using `viewer.dims.axis_labels = ('z', 'y', 'x')` does help in 2D, but it looks like `z` (slider axis) is on top of `y`.
<img width="183" alt="image" src="https://user-images.githubusercontent.com/76622105/219060444-f3450aa4-9e16-4bb0-8463-f967d2d3442a.png">

Likewise, if I rotate the axis I get strange behavior:
<img width="250" alt="image" src="https://user-images.githubusercontent.com/76622105/219060958-8dc90d38-c263-4d76-ab4e-8f9f86cad034.png">
`y` on `z` and `x` labeling actual `y` (`x` is on slider)
rotate again:
<img width="282" alt="image" src="https://user-images.githubusercontent.com/76622105/219061117-df22b27e-ffad-4379-baa5-15054349a501.png">
`y` on `z` again on what should be `x`, and `x` labeling the `z` (slider shows `y`)

**Comment by andy-sweet** [comment]
Thanks for the extra info! I can reproduce this with the following script:

```python
import numpy as np
import napari

volume = np.random.random((64, 64, 64))

viewer, layer = napari.imshow(volume, scale=(1, 2, 4), ndisplay=3)
viewer.axes.visible = True
viewer.dims.axis_labels = ('z', 'y', 'x')

napari.run()
```

then changing to 2D display.

For the first issue, one related problem is that on creation of the vispy axes overlay `viewer.dims.ndim == 2` but `viewer.dims.ndisplay == 3` since there are no layers yet. The `ndim` attribute dominates all others in `Dims`, so `viewer.dims.axis_labels == ('0', '1')`. That's why we only get two labels initially. Still thinking about a simple fix for that - but it's likely going to be ensuring that the vispy axes overlay gets updated when axis labels is updated as a result of adding the new layer (which causes ndim to change).

That may also be related to the overlapping text, though I'm not sure.

**Comment by andy-sweet** [comment]
I think I have a fix for both issues. We just need to reset the axis labels in `VispyAxesOverlay._on_data_change`. PR incoming shortly...

One related issue here is that we use a Pydantic root validator in `Dims`. When `ndim` changes is also causes lots of other fields to change (including `axis_labels`), but I think bypasses `EventedModel.__setattr__` so the `axis_labels` event doesn't get emitted. That may bite us later in different places, but no sure we actually need to address it for this.
