### ISSUE TITLE
[Minor] TransformBoxOverlay value error, no selected_vertex field

### ISSUE THREAD

**Issue by melonora** [napari/napari#5538]
## 🐛 Bug

When transforming a label layer a value error occurs due to TransformBoxOverlay not having the field selected_vertex.
Functionality seems not to be affected.

## To Reproduce

1. Start napari
2. Create label layer
3. With label layer active, activate transform by pressing 6.
4. Error occurs when moving mouse. 

![afbeelding](https://user-images.githubusercontent.com/22346363/217260701-5f7f69e2-c6fe-4e67-8064-a3d2f1cf7480.png)

**Comment by dalthviz** [comment]
Hi, checking this maybe what is needed is to change `selected_vertex` to `selected_handle`? Seems like that is the actual name of the attribute defined at:

https://github.com/napari/napari/blob/6416098946d594989072c2044551d7e0eca08328/napari/components/overlays/interaction_box.py#L38-L53

With that change:

![overlay](https://user-images.githubusercontent.com/16781833/229846931-7836e6a4-4bd0-4ce6-ae8f-b41f09444c7d.gif)

**Comment by psobolewskiPhD** [comment]
Looks like you're correct @dalthviz 
I think @brisvag just missed it in this commit when the name was changed:
[napari/napari@`1ae8186` (#4894)](https://github.com/napari/napari/pull/4894/commits/1ae8186b7c75040af2f7bd96e849e462f5fb7747)
Seems like the only place is that _mouse_keybindings:
https://github.com/search?q=repo%3Anapari%2Fnapari%20selected_vertex&type=code
here:
https://github.com/napari/napari/blob/6416098946d594989072c2044551d7e0eca08328/napari/layers/base/_base_mouse_bindings.py#L35

Seems like an easy PR. I can take care of it later today if no-one gets to it first.

**Comment by dalthviz** [comment]
I think I can help with the PR then @psobolewskiPhD !

**Comment by psobolewskiPhD** [comment]
Overlays 2.0 are marked with 0.5.0 milestone, so will make this fix match.
https://github.com/napari/napari/pull/4894
