### ISSUE TITLE
PyQt5 version

### ISSUE THREAD

**Issue by sunyi000** [napari/napari#5547]
we installed napari[all] in a conda environment, but when starting napari, we get error about "xcb" library. 
@tischi

I downgrade PyQt5 to an older version then the error went away.

I checked the pypi that PyQt5 was recently upgraded to v5.15.9. So it seems to me that napari won't work with the latest PyQt5 v5.15.9?

I also checked the napari setup.cfg, I can see that the required version fo PyQt5 is !=5.15.0. 

My question is that, should we change the pin to PyQt5 version? or is the issue caused by something else?

Thanks

**Comment by Czaki** [comment]
Are you the author of this post on image.sc https://forum.image.sc/t/installing-napari-startdist-plugin/77004? 

If no please check if installing the libraries mentioned in this thread solve your problem. If not, please provide details about your operating system as without this is impossible to debug the problem. 

Core devs without problems are using Qt > 5.15

**Comment by AhmetCanSolak** [comment]
Hello @sunyi000,

If you are on a debian-based system(Debian, Ubuntu, etc.), I recommend:
```
sudo apt-get install --reinstall libxcb-xinerama0
```
With recent versions of Ubuntu and recent versions of PyQt5, I faced a similar issue and reinstalling libxcb helped to solve. Somehow  `libxcb-xinerama.so.0`  was missing on each new Ubuntu installations.

**Comment by sunyi000** [comment]
Thanks all 
We did pip install napari[all] in a clean conda environment on Ubuntu 20.04. It didn't work so we change PyQT to 5.12.3 to make napari starts. Install libxcb-xinerrama itself didn't help. 
We will try the solution on image.sc https://forum.image.sc/t/could-not-load-the-qt-platform/52966/2

Thanks

**Comment by psobolewskiPhD** [comment]
Hi, gentle bump, @sunyi000 did you manage to get this issue resolved? Can we close this?
Thanks!

**Comment by sunyi000** [comment]
> Hi, gentle bump, @sunyi000 did you manage to get this issue resolved? Can we close this?
> Thanks!

Yes please close this.thanks
