### ISSUE TITLE
Qt6: toggle of layer visibility broken: can click to hide, but can't re-show

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari/napari#5556]
## 🐛 Bug

If you toggle a layer to invisible using the GUI visibility icon (the eye) in the layer list, the layer is properly hidden and the icon switches to the crossed-out eye (dimmed). This is all correct.
However, clicking again doesn't set it back to visible though.

## To Reproduce

1. install Qt6 backend, like pyside6
2. install napari
3. open/make any layer.
4. Toggle visibility to hide the layer
5. try to re-show the layer

## Expected behavior

Clicking the icon should toggle visibility off and then back on.

## Environment

napari: 0.5.0a1
Platform: macOS-13.1-arm64-arm-64bit
System: MacOS 13.1
Python: 3.11.0 | packaged by conda-forge | (main, Jan 14 2023, 12:26:40) [Clang 14.0.6 ]
Qt: 6.4.2
PySide6: 
NumPy: 1.24.1
SciPy: 1.10.0
Dask: 2023.1.1
VisPy: 0.12.1
magicgui: 0.6.1
superqt: unknown
in-n-out: 0.1.6
app-model: 0.1.1
npe2: 0.6.2

OpenGL:
- GL version: 2.1 Metal - 83
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1680x1050, scale 2.0

Settings path:
- /Users/piotrsobolewski/Library/Application Support/napari/nap-test_7c76622a0687875ccda8795c7fa273700326cf80/settings.yaml

## Additional context

I also checked with pyside6 & pyqt6 in python 3.10—same behavior.

I think this bug may be related to the open PR https://github.com/napari/napari/pull/5541
Will investigate.

**Comment by aganders3** [comment]
I can reproduce this.

For anyone in need of a workaround, right-click -> "Toggle visibility" does still seem to work.

**Comment by psobolewskiPhD** [comment]
Update: I was able to adress this here https://github.com/napari/napari/pull/5541 The visibility toggle is essentially a checkbox so the same issue was responsible for this. Ironically the test was correct, so we didn't pick up this bug in CI. The PR is approved and should be merged shortly.
