### ISSUE TITLE
Problem with fn/globe icon use on MacOS: some keyboards don't show globe symbol

### ISSUE THREAD

**Issue by kephale** [napari/napari#5559]
## 🐛 Bug

Some default keybinds use the `Fn` key on MacOS and use a 🌐 symbol instead of `fn`. Like this:

<img width="215" alt="image" src="https://user-images.githubusercontent.com/400105/218493434-fce9161c-88a2-4cfe-8665-73346f915c8b.png">

Presumably this is because many Macbook Pros have keyboards like this:

![image](https://user-images.githubusercontent.com/400105/218498692-3d59cdbc-0ece-41c0-aaf1-d173feeb8154.png)

However, some Apple keyboards still just show `fn`

![image](https://user-images.githubusercontent.com/400105/218493780-6a6d8c02-8ca2-4ede-afab-4d4c0733b762.png)

I naively got stuck in full screen because I couldn't find the 🌐 logo on my keyboard. Since I couldn't escape full screen *and* full screen persists across napari sessions, I ended up using `napari --reset` based on https://forum.image.sc/t/napari-opens-in-full-screen-mode-and-doesnt-function/58286

## To Reproduce

1. Use a full size Apple bluetooth keyboard with napari
2. Forget that `Fn` = 🌐 
3. Try to use keybinds that require `Fn`

## Expected behavior

It would be great if the default keybinds worked on this model of keyboard as well.

**Comment by kephale** [comment]
I did not notice that the `Fn` key is in a different section of the keyboard. 😳

**Comment by kephale** [comment]
I would still suggest that we use `fn` instead of the 🌐  symbol, because the laptop keyboard has both `fn` and 🌐 but the full size keyboard only says `fn`.

**Comment by psobolewskiPhD** [comment]
Alas, I'm not sure this is easily fixed. That's a *native macOS* keybind and menu item—open Safari and try the same keys, you will get the same behavior.
I don't get why exactly this item is present in the View menu—it's not a napari action and our other menus don't have native actions. 
Ironically, for me it's useful, because I use it. FYI, you can exit by using the keybind or just mousing up top left and clicking the green circle (full screen toggle). You can also change it in Settings > Modifier keys.
Anyhow, I think view hasn't been transition to the new app-model system, so it may disappear then? Not sure.

**Comment by Czaki** [comment]
> I don't get why exactly this item is present in the View menu—it's not a napari action and our other menus don't have native actions.

MacOS adds some positions to menus if they have matching names without asking for permission.

**Comment by kephale** [comment]
@psobolewskiPhD thanks, I had actually made the situation worse by toggling Mission Control to not have separate spaces per desktop in a multimonitor setup. As a result it was actually not possible to get to the usual MacOS window decorator that allows you to get out of full screen mode. 

Okey doke, I get it. Next time I eat an 🍎 I will bite with vigor :D

**Comment by psobolewskiPhD** [comment]
> > I don't get why exactly this item is present in the View menu—it's not a napari action and our other menus don't have native actions.
> 
> MacOS adds some positions to menus if they have matching names without asking for permission.

Ah, well for me it's a nice feature 😉 

Edit: @kephale I'm on the opposite end of the spectrum: single 13" monitor (mbpro) so I use this shortcut (and spaces) a lot, so I'd really like to *not* lose it! I do long for someday having an extra monitor.... 🙏

**Comment by psobolewskiPhD** [comment]
@kephale Because this isn't a napari bug—or anything napari specific really—but a macOS `feature` (or not depending on PoV), is it OK to close this?
