### ISSUE TITLE
How to programmatically close a magicgui.Container widget

### ISSUE THREAD

**Issue by jluethi** [napari/napari#5567]
## 📚 Documentation

This issue summarized some discussion from yesterday's napari community call.

I create a widget using the magicgui.Container class. The widget is very basic, just requesting a bit of information of the user. When they click the run button, a new widget opens and the first widget should close.

I could not figure out how to do this well. I started with 
```
  init_widget = viewer.window._dock_widgets[
      "Annotator (napari-feature-classifier)"
  ]
  viewer.window.remove_dock_widget(init_widget)
```
But that's an internal API and will be deprecated soon according to the warning.

An additional way to get to the widget object was using the `add_plugin_dock_widget` function. This returns the widget object if the widget already exists (thanks @Czaki !)
```
init_widget = viewer.window.add_plugin_dock_widget(plugin_name ='napari-feature-classifier', widget_name = 'Annotator')
viewer.window.remove_dock_widget(init_widget)
```

A more elegant solution to this (thanks again @Czaki !) is using `native`:
```
viewer.window.remove_dock_widget(self.native)
```
~~(with self referring to the magicgui.Container object instance => a reference to QWidget that implements GUI)~~

with self referring to the magicgui.Container instance and self.native a reference to the backend QWidget that implements GUI.

I couldn't find anything on this topic when googling for it. Hopefully, this issue can help someone down the road searching for the same thing :)

----

There's a separate discussion to be had whether one should close widgets or do the whole logic within an existing widget. But if anyone needs to close a magicgui.Container, here's a way :)

**Comment by Czaki** [comment]
> (with self referring to the `magicgui.Container` object instance)

One correction, `self.native` is a reference to QWidget that implements GUI.

**Comment by seankmartin** [comment]
Thanks for posting all this up @jluethi, very helpful 🎉 One small thing on the discussion here:

> (with self referring to ~~the magicgui.Container object instance~~ => a reference to QWidget that implements GUI)

`self` is a `magicgui.Container` instance though, no? `self.native` is the reference to QWidget that implements GUI (the native backend widget in QT, as opposed to the magicgui widget). If I'm understanding all this correctly (easily could be wrong!), then the sentence should be:
with `self` referring to the `magicgui.Container` instance and `self.native` a reference to the backend QWidget that implements GUI.

**Comment by jluethi** [comment]
Thanks for the help & the improvements to how it's worded @Czaki & @seankmartin 

From my side, no further action is required here. If someone wants to use this issue to get more details about it into the documentation, feel free to reopen it again :)
