### ISSUE TITLE
Napari on Windows

### ISSUE THREAD

**Issue by haesleinhuepf** [napari/napari#558]
## 📚 Documentation
Hey @sofroniewn ,

I ❤️ your announcement on the image.sc forum and thus had to try Napari on my Windows. So the installation works fine apparently, but the example script from the readme doesn't:

![image](https://user-images.githubusercontent.com/12660498/65944442-fa935200-e431-11e9-8358-f60728fda7bf.png)

![image](https://user-images.githubusercontent.com/12660498/65944455-03842380-e432-11e9-8b9b-d7a56b9dafbf.png)

```
AttributeError: module 'napari' has no attribute 'view_image'
```

Are maybe just the examples outdated?

Thanks in advnace!

Cheers,
Robet

**Comment by jni** [comment]
@haesleinhuepf :wave: great to see you here! =) You should install the version from GitHub or wait ~12h before pip installing with --update. =) @sofroniewn is about to release v0.2 which includes the new functions.

**Comment by haesleinhuepf** [comment]
Waiting 12h sounds like an amaaaazing solution 😃 

Thanks guys! Looking forward to explore the second island on the other side of the planet ;-)

**Comment by jni** [comment]
> Looking forward to explore the second island on the other side of the planet ;-)

Nice pickup. :wink:

**Comment by sofroniewn** [comment]
@haesleinhuepf this should now be fixed - `0.2.0` has been release on pypi, ~12 hrs later!!

great to here that your windows worked ok, i think we might be having some issues with openGL on older systems, but we havn't figured it all out yet

**Comment by sofroniewn** [comment]
oh actually now that i think about it, you havn't seen an image yet - so the windows problem might still come up :-(
If you get a black screen after adding the image and the error message described here https://github.com/napari/napari/pull/551#issuecomment-536347310 then we'll need to fix it

**Comment by haesleinhuepf** [comment]
Unfortunately, it still comlpains about a missing method: 
![image](https://user-images.githubusercontent.com/12660498/66024501-54f4e700-e4f4-11e9-83ee-6dcf31097941.png)

```
AttributeError: module 'napari' has no attribute 'view_image'
```

To be honest, to me this doesn't look like a windows problem....

Any hints would be helpful!

Thanks!

Cheers,
Robert

**Comment by jni** [comment]
@haesleinhuepf good morning! =D

I was puzzled and was in the process of creating a clean enviroment to test... until I saw your image: your file is called `napari.py`, and the local directory is at the top of `sys.path`. So, you are trying to import `napari.py` from itself, instead of the installed napari! Renaming your file is the answer. =)

**Comment by haesleinhuepf** [comment]
> your file is called napari.py

Oh no! This totally never happened to me before 👼 ;-)

Ok, changing to "nap.py" helps a bit:
![image](https://user-images.githubusercontent.com/12660498/66058423-a6c06000-e53a-11e9-91e1-322948c164e1.png)

The error message is now:
```
WARNING: QWidget: Must construct a QApplication before a QWidget
```
... and no window opens. 

Before you dig deeper now. Is there an entry on the napari roadmap for Windows compatibilty? And if yes, when will it be? I would be happy to volunteer as tester!

Cheers,
Robert

**Comment by sofroniewn** [comment]
Hi Robert, if you're running from a script like that you need to create a gui context before you can launch the Viewer. You can do this as follows:

```python
from skimage import data
import napari

# create Qt GUI context
with napari.gui_qt():
    # create a Viewer and add an image
    viewer = napari.view_image(data.astronaut(), rgb=True)
```

We've got a little more detail on this on our tutorials page here https://napari.github.io/napari-tutorials/tutorials/getting_started.html which is still a bit of a WIP.

So far you still havn't hit the potential windows problem. Thanks for being so persistent! We definitely need to improve some of our docs / readme on this process.

As to windows testing, we need to get a bit of a handle on how what the characteristics of windows systems that we're failing on are, as I know it's not all windows systems, but it does seem to come up consistently. Here's the same issue, but raised in the underlying visualization library which we depend on - https://github.com/vispy/vispy/issues/1688. Understanding this is a top priority for us, but we're somewhat limited by our access to different windows machines. I really hope that over the next month or so we at least come to a complete understanding of the problem, if not a solution.

**Comment by jni** [comment]
Roadmap? Ideally we should have it working right now! We just don’t have anyone on our team regularly using Windows, so it makes it challenging. We *absolutely* would love your help with this!

The message is very strange because the `--gui=qt` flag should have created the QApplication for you... would you mind trying with plain python and our napari.gui_qt() context manager?

Actually, I also wonder if you should first launch ipython with the gui qt option and *then* use %run -i nap.py. I seem to remember that there is some sort of race condition with the flag: IPython will start running the script before Qt has finished initialising. Check that also?

**Comment by jni** [comment]
... Speaking of race conditions... 😂

**Comment by haesleinhuepf** [comment]
It works!
![image](https://user-images.githubusercontent.com/12660498/66060837-9c07ca00-e53e-11e9-9545-629d068430c0.png)

Thanks for your support! Again, I'm happy to help testing. I also got a bunch of Windows systems (mostly win 10) standing around with various GPUs underlying...

**Comment by haesleinhuepf** [comment]
It works with both
```
ipython --gui=qt nap.py
```
and
```
python nap.py
```
Using the code snipped @sofroniewn suggest: `with napari.gui_qt()`. Without the snippet it doesn't work in both cases.

**Comment by sofroniewn** [comment]
@haesleinhuepf whoo! That's great!!

If you were able to do some systematic testing on windows machines with different gpus that would be amazing!!! If you could both check if napari was able to launch and show an image and then run
```python
import vispy
print(vispy.sys_info())
```
and look at the `GL version` on those machines that will tell us a lot about what is / isn't working (on the computers where it fails it will likely not find a `GL version`).

Thanks!! Nick

**Comment by haesleinhuepf** [comment]
@sofroniewn Sure! You helped me, I'm happy to help you! 😄 

I just tested on three systems and it worked in all cases!
* "finley" Intel i7-1065g7 (Intel Iris Plus GPU)
* "ulice" napari throws a warning, Intel i7-8565U (Intel UHD 620 GPU)
* "shannon": AMD Ryzen 3700U (Vega 10 GPU)

All run on a recently updated Win10 64-bit. I saved the output here:
https://github.com/haesleinhuepf/napari_playground/tree/master/logs

As soon as I walk by a system with an NVidia GPU (our microscope workstations have those), I can test there as well. When I hit a system where it doesn't work I'll let you know.

So far it looks good! Thanks again for your great work! 

Cheers,
Robert

**Comment by sofroniewn** [comment]
That's great, I really appreciate the thoroughness and the logs repo. I'm feeling much better about our windows compatibility now.

**Comment by royerloic** [comment]
Nice to see your here @haesleinhuepf ! 
Definitely help on windows system would be great!
Be warned... Once you go napari you never go back ;-/

**Comment by haesleinhuepf** [comment]
> Be warned... Once you go napari you never go back ;-/

Hey @royerloic 👋, you said sth similar about OpenCL to me about two years ago - and you were right 😉

**Comment by sofroniewn** [comment]
I'm going to close this issue now as it was originally about an older release, and we are able to run on multiple windows configurations. If new windows users come along with new problems it might be best to open up a new issue rather than keep going on this one, but we can also always reopen this one if needed
