### ISSUE TITLE
Having many features in layer.features leads to napari window changing size when user hovers over objects

### ISSUE THREAD

**Issue by jluethi** [napari/napari#5617]
## 🐛 Bug

We want to start using layer.features to store some feature measurements associated to a labels layer. We got a feature request for supporting this a year ago and are finally tackling it (see https://github.com/fractal-napari-plugins-collection/napari-feature-classifier/issues/12). Also, my understanding is that layer.features should be the canonical place that we store feature measurements associated with label layers.

When we add features to a label layer, napari wants to show the features belonging to a given object in the footer when hovering over an object. When we have more features than fit into the footer, the napari window gets resized, which makes for a very weird user experience.

If I e.g. have 15 features and my napari window is on a regular laptop, the window size gets tripled when I try to hover, all the image content disappears and I'd have to scroll to find it again. If there is a dockwidget, that stops being visible. If I resize the window and hover again, i resizes the window again.

Here's a brief GIF:
![feature_display_bug](https://user-images.githubusercontent.com/18033446/224359042-253fece3-129f-43c9-a51c-7b93a247d531.gif)

https://www.dropbox.com/s/t69p0nt4py6zatb/Screen%20Recording%202023-03-10%20at%2016.24.02.mov?dl=0

## To Reproduce

1. Add a label image to napari
2. Add features to label_layer.features
3. Hover over a label

Example files:
Label image: 
![test_labels](https://user-images.githubusercontent.com/18033446/224360153-f11ee62e-a632-4ba0-8f76-62fbfc9c24aa.png)

Feature dataframe: 
[test_measurements.csv](https://github.com/napari/napari/files/10943549/test_measurements.csv)

Here's the code I used in the napari console:
```
import pandas as pd
features = pd.read_csv('/Users/joel/Desktop/test_measurements.csv')
viewer.layers[0].features = features
# Now the behavior described above triggers

# One can stop the behavior by removing the features
viewer.layers[0].features = []
```

## Expected behavior

I expect the viewer window to not change size, independent of how many features are in label_layer.features

## Environment

 - Please copy and paste the information at napari info option in help menubar here:
napari: 0.4.17
Platform: macOS-13.2.1-arm64-arm-64bit
System: MacOS 13.2.1
Python: 3.9.16 | packaged by conda-forge | (main, Feb 1 2023, 21:38:11) [Clang 14.0.6 ]
Qt: 5.15.6
PyQt5: 5.15.7
NumPy: 1.24.2
SciPy: 1.9.1
Dask: 2023.3.0
VisPy: 0.11.0
magicgui: 0.7.0
superqt: unknown
in-n-out: 0.1.7
app-model: 0.1.1
npe2: 0.6.2

OpenGL:
- GL version: 2.1 Metal - 83
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1512x982, scale 2.0

 - Any other relevant information:
Also reproduced by 2 other users on Windows

cc @andy-sweet Any idea who I'd need to tag here?

**Comment by psobolewskiPhD** [comment]
Hi @jluethi this is indeed rather annoying. 
It seems though that this is a duplicate issue, if I'm reading right:
https://github.com/napari/napari/issues/5417
https://github.com/napari/napari/issues/5177

The good news is that a fix has been merged:
https://github.com/napari/napari/pull/5451

You could try to use `main` or a Nightly release, which we do have on conda, e.g.
`conda create -n napari-main -c "napari/label/nightly" -c conda-forge napari python=3.10`

Of course, beware of dragons!!

**Comment by jluethi** [comment]
Ah, thanks @psobolewskiPhD , will test on main then! And thanks for linking me to the duplicates, I was looking around but did not find them

also, thanks for the nightly release instructions, I wasn’t aware of them, sounds very useful!

**Comment by jluethi** [comment]
Just to briefly confirm: The issue is indeed fixed in the nightly builds. Thanks again @psobolewskiPhD for the quick feedback & the installation instructions!
