### ISSUE TITLE
Plot lots of spots

### ISSUE THREAD

**Issue by ambrosejcarr** [napari/napari#562]
## 🚀 Plot lots of spots
I would like to be able to plot millions of spots using napari.

## Motivation

Starfish users will often want to plot spots _after_ merging fields of view. In these cases, there will be millions of spots to plot. 

## Pitch

Right now I can plot 20k spots, which takes a while. _After_ the spots populate napari, navigating them is lightning fast. Larger groups of spots take longer than I'm willing to wait (a few minutes for 250k before I interrupt the kernel).

## Alternatives

I tried Vaex, and mayavi, and matplotlib, and could only get mayavi to work, but it ground my computer to a halt, and I had to play some tricks to kill it.

**Comment by jni** [comment]
Thanks for the report! As @sofroniewn mentioned on slack, this should be a matter of being more clever with thumbnails (e.g. subsampling many fewer points). The canvas is only 32x32 = 1024, so three orders of magnitude more points is kinda overkill. :joy:
