### ISSUE TITLE
Dragging layers to trash button doesn't work

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari/napari#5629]
## 🐛 Bug

Dragging layers to the trash button doesn't work, with an error:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
File ~/Dev/napari/napari/_qt/widgets/qt_viewer_buttons.py:408, in QtDeleteButton.dropEvent(self=<napari._qt.widgets.qt_viewer_buttons.QtDeleteButton object>, event=<PyQt5.QtGui.QDropEvent object>)
    406 layer_name = event.mimeData().text()
    407 layer = self.viewer.layers[layer_name]
--> 408 if not layer.selected:
        layer = <Points layer 'Points [1]' at 0x163ade950>
    409     self.viewer.layers.remove(layer)
    410 else:

AttributeError: 'Points' object has no attribute 'selected'
```
See also discussion at: 
https://napari.zulipchat.com/#narrow/stream/212875-general/topic/Drag.20layer.20to.20trash

Looks like this was over-looked when this PR was merged, changing selected layers: https://github.com/napari/napari/pull/2441

## To Reproduce

1. Add a layer or two
2. try to drag a layer to the trash button—should remove

## Expected behavior

Layer should be removed without an error.

## Environment

 ```
napari: 0.5.0a2.dev43+g8e58cff4
Platform: macOS-13.2.1-arm64-arm-64bit
System: MacOS 13.2.1
Python: 3.10.9 | packaged by conda-forge | (main, Feb 2 2023, 20:26:08) [Clang 14.0.6 ]
Qt: 5.15.6
PyQt5: 5.15.7
NumPy: 1.24.2
SciPy: 1.10.1
Dask: 2023.3.1
VisPy: 0.12.1
magicgui: 0.7.2
superqt: unknown
in-n-out: 0.1.7
app-model: 0.1.2
npe2: 0.6.2

OpenGL:
- GL version: 2.1 Metal - 83
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1680x1050, scale 2.0

Settings path:
- /Users/piotrsobolewski/Library/Application Support/napari/napari-main_e240b8daeed1098c91bdc4f2a9ad585200c6d954/settings.yaml
```

## Additional context

As per the zulip discussion, I actually don't think this should work at all. 
The trash button is a **button** it's not a folder or something that you drag items into. Buttons respond to a single click and perform an action.
I learned about this in the Viewer tutorial docs, but it's been broken for 2 years and no-one has reported it, so I assume no-one is using this.
Not used, not tested, not logical -- let's just remove this. I will make a PR.

**Comment by jni** [comment]
fwiw, I'm in favour of keeping it, it's kinda cute and delightful if it works. Those aren't great reasons but that's the vibe I get.

**Comment by psobolewskiPhD** [comment]
@jni I made a PR to remove. 
Here's my argument 🧐 
I think if in 2 years no-one reported this it means that no-one found it logical (nor had the cuteness advertised to them 🤣). That's because the `drag to trash` behavior is part of a *desktop model* (common to macOS and other GUI OS) that napari just doesn't implement, so it's not intuitive at all that it should work. You can't click the trash button to see your removed layers there, for example, to undo the action. Also none of the other elements of that bar have a drag-n-drop behavior, yet they all share iconography with the delete button: they are stylized as buttons.

**Comment by jni** [comment]
Yup, I agree. Thanks @psobolewskiPhD !
