### ISSUE TITLE
Qt6, MacOS: Whole window flashes when resizing canvas with layer

### ISSUE THREAD

**Issue by andy-sweet** [napari/napari#5644]
## 🐛 Bug

When using napari in a recently installed conda environment with PyQt6, the whole window flashes or flickers to white when resizing the canvas (and maybe in other cases). This does not occur when showing the welcome widget instead of the canvas.

Here's a video that shows when this happens, though ⚠️  be warned that the frequency of the flashing may cause issues for those with photosensitivity ⚠️ , so don't press play unless you're prepared for that.

https://user-images.githubusercontent.com/2608297/226410625-281cc376-8c2f-485c-9340-bd54e5740296.mp4

## To Reproduce

The easiest way to reproduce this is as follows.

- Setup a conda environment with pyqt6 and an editable/dev install of napari.
- Open napari.
- Open any layer (I tried 2D and 3D images, and 2D points).
- Move the separator between the left control panel and the canvas.

Adding the layer and resizing the window also causes the issue, but the flashing is less frequent.

## Expected behavior

I'd expect no flashing/flickering.

## Environment

```
napari: 0.4.17rc4.dev224+g1fcceb42e
Platform: macOS-10.16-x86_64-i386-64bit
System: MacOS 13.1
Python: 3.10.9 (main, Mar  8 2023, 04:44:36) [Clang 14.0.6 ]
Qt: 6.4.2
PyQt6: 
NumPy: 1.24.2
SciPy: 1.10.1
Dask: 2023.3.1
VisPy: 0.12.1
magicgui: 0.7.2
superqt: unknown
in-n-out: 0.1.7
app-model: 0.1.2
npe2: 0.6.2

OpenGL:
  - GL version:  2.1 INTEL-20.2.48
  - MAX_TEXTURE_SIZE: 16384

Screens:
  - screen 1: resolution 1920x1080, scale 1.0

Settings path:
  - /Users/asweet/Library/Application Support/napari/napari-dev_94a2c6ecd2bb4e54de7c17f279d1ba0ad46bb93d/settings.yaml
Plugins:
  - napari: 0.4.17rc4.dev224+g1fcceb42e (77 contributions)
  - napari-console: 0.0.7 (0 contributions)
  - napari-svg: 0.1.6 (2 contributions)
  - napari-ui-tracer: 0.1.1 (2 contributions)
```

## Additional context

This does not happen with my pyqt5 environment at the same commit of ab885957f, or my pyqt5 environment associated with v0.4.17. Therefore, I assume this is a pyqt6 issue.

**Comment by psobolewskiPhD** [comment]
I can reproduce on my arm64 macOS 13.2.1 with both pyqt6 and pyside6, so seems more broadly a Qt6 issue.
I guess I don't resize often because I'm on a small window to begin with!

**Comment by Czaki** [comment]
On Linux (qt from pip) I cannot reproduce.

Could you validate if it happens for Qt6 from pip or only conda one?

**Comment by psobolewskiPhD** [comment]
Im my case it was pyqt6 and pyside6 from pip.
Edit: checked conda-forge pyside6, same effect.

**Comment by Czaki** [comment]
Ok. So we need a person with Windows to check if it is mac specific.

**Comment by psobolewskiPhD** [comment]
Interesting, it seems like it's this bug:
https://bugreports.qt.io/browse/QTBUG-96405
And in fact if I pip install pyside==6.3.0 then the flicker goes away.
6.3.2 is also fine (the final 6.3.x)
but 6.4.0 gives flickers.

Note: pyqt6 6.3.1 gives an error when I try to launch:
```
Traceback (most recent call last):
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/napari-dev/bin/napari", line 8, in <module>
    sys.exit(main())
  File "/Users/piotrsobolewski/Dev/napari/napari/__main__.py", line 570, in main
    _run()
  File "/Users/piotrsobolewski/Dev/napari/napari/__main__.py", line 330, in _run
    viewer = Viewer()
  File "/Users/piotrsobolewski/Dev/napari/napari/viewer.py", line 67, in __init__
    self._window = Window(self, show=show)
  File "/Users/piotrsobolewski/Dev/napari/napari/_qt/qt_main_window.py", line 575, in __init__
    self._add_menus()
  File "/Users/piotrsobolewski/Dev/napari/napari/_qt/qt_main_window.py", line 729, in _add_menus
    self.file_menu = menus.FileMenu(self)
  File "/Users/piotrsobolewski/Dev/napari/napari/_qt/menus/file_menu.py", line 149, in __init__
    self._rebuild_samples_menu()
  File "/Users/piotrsobolewski/Dev/napari/napari/_qt/menus/file_menu.py", line 213, in _rebuild_samples_menu
    ).menu()
AttributeError: 'QAction' object has no attribute 'menu'
```

Edit: I don't get why that's related to QAction, because NapariMenu is QMenu?

**Comment by Czaki** [comment]
This bug is about Qt 6.2 and was fixed in 6.3. So I'm not sure if it is the same bug reintroduced in 6.4 or something else. 

But it looks like it was already reported here: https://bugreports.qt.io/browse/QTBUG-110479. 

And comment suggests that it is solved in 6.5 that should be shortly released https://wiki.qt.io/Qt_6.5_Release



> Note: pyqt6 6.3.1 gives an error when I try to launch:

My memory suggests that I see this in past but do not remember the context. 



> Edit: I don't get why that's related to QAction, because NapariMenu is QMenu?

Any menu in Qt application is QMenu. `NapariMenu` is at this moment our abstraction layer.

**Comment by andy-sweet** [comment]
Thanks for the detective work both! Once 6.5 releases and the corresponding pqyt package is available on pypi and/or conda-forge, then I think we can close this. Though we may also want to add a note somewhere if we have any Qt6 specific docs/help anywhere.

**Comment by psobolewskiPhD** [comment]
We don't have anything official about Qt6. Maybe with Qt 6.5 we can add [pyside6], [pyqt6] and make it officially experimental?

**Comment by andy-sweet** [comment]
Yes, I think there was a mention of something like `[experimental_pyqt6]`or `[exppyqt6]` to make it more clear these are experimentally supported. I'd be supportive of that. Then we might have a doc or GitHub super-issue/epic tracking all the known Qt6 issues to help people workaround problems.

**Comment by psobolewskiPhD** [comment]
I just installed pyqt6 6.5 (from pip) and this issue is resolved.
Alas, pyside6 6.5 has as a different problem https://github.com/napari/napari/issues/5703

**Comment by psobolewskiPhD** [comment]
I'm going to close -- we now support pyqt6 >6.5. Once we sort out the pyside6 issues, it will be >6.5 too.
