### ISSUE TITLE
starting napari in ubuntu python 3.8 pip installation gives error and is slow

### ISSUE THREAD

**Issue by perdigao1** [napari/napari#5651]
## 🐛 Bug

Starting napari is very slow. This happens in a conda environment with 3.8 and napari installed with pip.

An error appears on the terminal and visualisation is slow (CPU backend?)

## To Reproduce

Terminal commands
1. `$ conda create -n napari_pip_env python=3.8`
2. `$ pip install napari[all]`
3. start napari with `$ napari`

And the following error appears
```
libGL error: MESA-LOADER: failed to open swrast (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)
libGL error: failed to load driver: swrast
```
Napari is running but when trying to load image data (drag and drop a tif file) many error messages appear

Repeated error message
```
WARNING: QOpenGLWidget: Failed to create context
13:41:39 WARNING QOpenGLWidget: Failed to create context
```

Repeated error message
```
13:41:39 WARNING composeAndFlush: QOpenGLContext creation failed
WARNING: composeAndFlush: makeCurrent() failed
```

and another exception error, summarised here (XXXXX are censored folder locations)

```
File XXXXX/conda_envs/napari_pip_env/lib/python3.8/site-packages/vispy/gloo/glir.py:1756, in GlirFrameBuffer.deactivate(self=<GlirFrameBuffer 53>)
   1754 while self._handle in stack:
   1755     stack.remove(self._handle)
-> 1756 gl.glBindFramebuffer(gl.GL_FRAMEBUFFER, stack[-1])
        stack = []
        gl.GL_FRAMEBUFFER = GL_FRAMEBUFFER
        gl = <module 'vispy.gloo.gl' from 'XXXXX/conda_envs/napari_pip_env/lib/python3.8/site-packages/vispy/gloo/gl/__init__.py'>

IndexError: list index out of range

```

## Expected behavior
No errors
Opens image data

## Environment

 - Please copy and paste the information at napari info option in help menubar here:

```
napari: 0.4.17
Platform: Linux-5.4.0-40-generic-x86_64-with-glibc2.17
System: Ubuntu 20.04 LTS
Python: 3.8.16 (default, Mar 2 2023, 03:21:46) [GCC 11.2.0]
Qt: 5.15.2
PyQt5: 5.15.9
NumPy: 1.24.2
SciPy: 1.9.1
Dask: 2023.3.1
VisPy: 0.11.0
magicgui: 0.7.2
superqt: unknown
in-n-out: 0.1.7
app-model: 0.1.2
npe2: 0.6.2

OpenGL:
- GL version: 
- MAX_TEXTURE_SIZE: ()

Screens:
- screen 1: resolution 1680x899, scale 1.0
```

 - Any other relevant information:
Installation using conda does not result in problem. Resulting environment is slightly different
```
python 3.8.15 gcc 10.4.0
napari 0.4.16
pyqt (not pyqt5) 5.15.7
qtpy 2.3.0
pyopengl 3.1.1a1
```

We suspect that the issue may have something to do with the gcc compiler used to compile python itself. Somehow it cannot find OpenGL drivers.

Within the pip installation (which gives error) if python is downgraded to 3.8.13 using conda and the error does not occur, but error messages emerge.

**Comment by Czaki** [comment]
> We suspect that the issue may have something to do with the gcc compiler used to compile python itself. Somehow it cannot find OpenGL drivers.

Did you try to restart the machine? Similar things happen after the GPU driver update.

**Comment by psobolewskiPhD** [comment]
With NEP29 https://numpy.org/neps/nep-0029-deprecation_policy.html#support-table realistically we'll probably be dropping python 3.8 support before we can figure out whats up with this bug....

**Comment by perdigao1** [comment]
Avery and me have investigating. This appears to be a specific problem with the (remote) linux machines we are using. Other linux machines don't show this problem. It may be an issue with the display driver installation.

**Comment by psobolewskiPhD** [comment]
Going to close. As noted, we're getting ready to drop python 3.8 plus it seems specific to certain machines (post above).
