### ISSUE TITLE
Get CI Time under check. Aka CI takes waaayyy too long.

### ISSUE THREAD

**Issue by Carreau** [napari/napari#5660]
IMHO CI is taking way too long it takes forever to get feedback on PRs.

There are many culprits:
  - Priority of what GitHub action run first. 
    - For example building docs and Bundle often first. I think those should start only if all unittests are passing.
  - Extremely long tests.
    - Windows Bundle creation (20 minute), I think should start only if unittests are passing, or run daily
    - `test_conda_installer` take 15% of the whole unit-test time. Maybe we should only run in on latest Python and not on all matrix items ?

**Comment by goanpeca** [comment]
Pinging @jaimergp

**Comment by jni** [comment]
Thanks @Carreau, I very much like your suggestions!

**Comment by jaimergp** [comment]
> test_conda_installer take 15% of the whole unit-test time. Maybe we should only run in on latest Python and not on all matrix items ?

This one will be removed with https://github.com/napari/napari/pull/5743

**Comment by jaimergp** [comment]
> Windows Bundle creation (20 minute), I think should start only if unittests are passing, or run daily

If this one meant the Briefcase bundles, then see https://github.com/napari/napari/pull/5804

**Comment by kcpevey** [comment]
Related: https://github.com/napari/napari/issues/5473

**Comment by psobolewskiPhD** [comment]
A lot has changed this this was opened.
First: PR tests are now multistage so there is faster fail, see: https://github.com/napari/napari/pull/6156
Second, docs are done on CircleCI, so split from tests.
Finally, bundle and conda stuff has been removed.
While we should aim to improve CI efficiency, I'm going to close this issue as solved.
