### ISSUE TITLE
Labels layer: add keybinding to set the label to 0

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari/napari#5666]
## 🧰 Task

There is the ability to set a new label, bound by default to `m`, but there isn't an easy way to set the label to `0` such that the fill tool can use used to erase in bulk, so to speak.
There should be an easy keybind for this that should be editable by the user. Perhaps `n` because it's close to `m` and the spacebar?

**Comment by jni** [comment]
Well one question is why is it "m" — oh right for max. Anyway, I think n could be confusing because `new`. Should we set to 9 (new/max) and 0? This somewhat corresponds to the labeling modes shortcuts...
