### ISSUE TITLE
Bug: After stopping the play button functionality, adjusting slider results in an indefinite hang

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari/napari#5668]
## 🐛 Bug

If you use the Play button of the dims slider to view a stack (or tracks, whatever) and hit stop midway then touch the slider to adjust dims the viewer becomes unresponsive and hangs indefinitely.

Video:

https://user-images.githubusercontent.com/76622105/228001044-399315ba-f206-4b55-99ee-e80f8daeaf36.mp4

After this I am forced to kill the process.
Also notice how the play button remains as the red stop button after stopping.

## To Reproduce

1. open Cells 3D example
2. press Play in 2D mode to view the stack
3. press the red Stop midway through the stack
4. try to adjust the slider position (note the stop button will still be showing...)

## Expected behavior

The viewer should not hang, it should be possible to adjust the slider as one wishes or resume Play.

## Environment

```
napari: 0.5.0a2.dev51+gfc038f36
Platform: macOS-13.2.1-arm64-arm-64bit
System: MacOS 13.2.1
Python: 3.10.9 | packaged by conda-forge | (main, Feb 2 2023, 20:26:08) [Clang 14.0.6 ]
Qt: 5.15.6
PyQt5: 5.15.7
NumPy: 1.24.2
SciPy: 1.10.1
Dask: 2023.3.1
VisPy: 0.12.2.dev45
magicgui: 0.7.2
superqt: unknown
in-n-out: 0.1.7
app-model: 0.1.2
npe2: 0.6.2.dev26+gd7329b7.d20230324

OpenGL:
- GL version: 2.1 Metal - 83
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1680x1050, scale 2.0

Settings path:
- /Users/piotrsobolewski/Library/Application Support/napari/napari-dev_a1eb8b76ba95fa16ad06e26097b46b8455dfbf0b/settings.yaml

```

**Comment by Czaki** [comment]
@psobolewskiPhD Could you add a video? I could not reproduce this on the main.

**Comment by psobolewskiPhD** [comment]
Just playing around some more and noticed that sometimes it doesn't happen on the first stop. But if I hit play and stop again, it happens.

**Comment by psobolewskiPhD** [comment]
I made a fresh dev env and can still get this to happen. Never on the first play-stop, but with a a couple play-stop or slider drags it happens, so it's a bit flaky.
```
napari: 0.5.0a2.dev109+gd91f4ee5
Platform: macOS-13.3.1-arm64-arm-64bit
System: MacOS 13.3.1
Python: 3.10.10 | packaged by conda-forge | (main, Mar 24 2023, 20:12:31) [Clang 14.0.6 ]
Qt: 5.15.6
PyQt5: 5.15.7
NumPy: 1.24.3
SciPy: 1.10.1
Dask: 2023.4.1
VisPy: 0.12.2
magicgui: 0.7.2
superqt: unknown
in-n-out: 0.1.7
app-model: 0.1.4
npe2: 0.7.0

OpenGL:
  - GL version:  2.1 Metal - 83.1
  - MAX_TEXTURE_SIZE: 16384

Screens:
  - screen 1: resolution 1680x1050, scale 2.0

Settings path:
  - /Users/piotrsobolewski/Library/Application Support/napari/napari-dev_a1eb8b76ba95fa16ad06e26097b46b8455dfbf0b/settings.yaml
Plugins:
  - napari: 0.5.0a2.dev109+gd91f4ee5 (77 contributions)
  - napari-console: 0.0.8 (0 contributions)
  - napari-svg: 0.1.6 (2 contributions)
 ```

**Comment by Czaki** [comment]
Hm. It looks like We need to rewrite QtDims. 
It may be connected with some threading problems that I have observed in the past. 

I do not like this.

**Comment by dalthviz** [comment]
Hi, trying to reproduce this I got a `RuntimeError` while testing on Linux (Ubuntu) when having the application window maximized (but no application freeze ocurred):

```python-traceback
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
File ~/Documents/napari/napari/_qt/widgets/qt_dims_slider.py:550, in QtPlayButton.mouseReleaseEvent(self=<napari._qt.widgets.qt_dims_slider.QtPlayButton object>, event=<PyQt5.QtGui.QMouseEvent object>)
    548     self.popup.show_above_mouse()
    549 elif event.button() == Qt.MouseButton.LeftButton:
--> 550     self._on_click()
        self = <napari._qt.widgets.qt_dims_slider.QtPlayButton object at 0x7fffb82f84c0>

File ~/Documents/napari/napari/_qt/widgets/qt_dims_slider.py:558, in QtPlayButton._on_click(self=<napari._qt.widgets.qt_dims_slider.QtPlayButton object>)
    556     return None
    557 if self.property('playing') == "True":
--> 558     return qt_dims.stop()
        qt_dims = <napari._qt.widgets.qt_dims.QtDims object at 0x7fffd47c2950>
    559 self.play_requested.emit(self.axis)
    560 return None

File ~/Documents/napari/napari/_qt/widgets/qt_dims.py:320, in QtDims.stop(self=<napari._qt.widgets.qt_dims.QtDims object>)
    317 """Stop axis animation"""
    318 if self._animation_worker is not None:
    319     # Thread will be stop by the worker
--> 320     self._animation_worker._stop()
        self._animation_worker = <napari._qt.widgets.qt_dims_slider.AnimationWorker object at 0x7fffb0bc4a60>
        self = <napari._qt.widgets.qt_dims.QtDims object at 0x7fffd47c2950>

File ~/miniconda3/envs/napari-dev/lib/python3.10/site-packages/superqt/utils/_ensure_thread.py:156, in ensure_object_thread.<locals>._out_func.<locals>._func(self=<napari._qt.widgets.qt_dims_slider.AnimationWorker object>, *args=(), **kwargs={})
    153 @wraps(func_)
    154 def _func(self, *args, **kwargs):
    155     return _run_in_thread(
--> 156         func_, self.thread(), await_return, timeout, self, *args, **kwargs
        func_ = <function AnimationWorker._stop at 0x7fffdf854310>
        await_return = False
        timeout = 1000
        self = <napari._qt.widgets.qt_dims_slider.AnimationWorker object at 0x7fffb0bc4a60>
        args = ()
        kwargs = {}
    157     )

RuntimeError: wrapped C/C++ object of type AnimationWorker has been deleted
```

So not totally sure if that is a different issue or a traceback that could help here :thinking:

Also, I tried on Windows and I think I got to reproduce this issue there (the application freezes while using the play/stop button repeatedly). Interestingly is way more frequent/easy to get such freeze state on macOS than on Windows 🤔

**Comment by psobolewskiPhD** [comment]
Just to clarify, were you able to reproduce the issue on macOS?

**Comment by dalthviz** [comment]
> were you able to reproduce the issue on macOS?

Yes! Basically, I was able to reproduce this on macOS and Windows. In the case of Linux (Ubuntu in a virtual machine) I got the traceback above but no application freeze

**Comment by psobolewskiPhD** [comment]
Ah, I was hoping maybe it was some arm64 macOS edge case. Darn!
Thanks for the detective work!
❤️

**Comment by psobolewskiPhD** [comment]
I can still block the viewer and have to force quit, but not easily -- not when interacting with the slider as in the OP, but rather when clicking repeatedly on the play/stop button.

**Comment by psobolewskiPhD** [comment]
I can't reproduce on main or 0.5.0, but got it to happen with 0.4.19.
So somewhere something in 0.5.0 fixed it, maybe the slicing changes associated with async?
It works so well that now you can hit play and scrub the slider back to replay! 🚀
