### ISSUE TITLE
Show logo during startup

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#567]
## 🚀 Feature
Right now napari takes a long time to launch the viewer. People can get discouraged as they wait, unsure if napari is loading, or if their data is loading, or if it is just hanging. Showing the napari logo, possibly with / without some text during that time might make it feel better.

**Comment by jni** [comment]
Just to clarify here: I think we should only do this in `__main__` or even only in the bundled app. It would be very jarring to have this happen when launching from an IPython session. The correct solution for IPython is to dramatically reduce the startup time. To reiterate what I mentioned in the meeting, startup time from the command-line is about 2s on Linux, which is reasonably fast. There's nothing fundamentally slow about our startup, and we need to check what's happening on mac to make it so slow.

**Comment by AhmetCanSolak** [comment]
We can do it in bundled app with a runtime-hook which will be executed right before execution of our main entry point @jni

**Comment by tlambert03** [comment]
@sofroniewn pointed me to this from #744.  Just wanted to hear exactly when people feel like it's slow?  I think the majority of that time might be qt itself spinning up or imports (which is harder to do anything about).  On my system, when running from `__main__`, the majority of time is in `__init__`:
```
start init:    0.000
finish init:   1.413
start main:    1.416
start gui_qt:  1.417
app ready:     1.601
image shown:   2.281
```

So even if we wanted to do something with, say, [QSplashScreen](https://doc.qt.io/qt-5/qsplashscreen.html), that splash wouldn't show up until we instantiate the app in main, and then only very briefly... unless we tried to do something completely independent of Qt, at the very beginning of `__init__`.  I really haven't minded the startup time much, @sofroniewn, is it still slow for you, and under what specific startup procedure?

**Comment by sofroniewn** [comment]
That's great profiling @tlambert03 - how did you do it? I get about `3.2` seconds between hitting enter on the command line after typing `napari` and seeing something on my screen (timed using the stop watch on my phone and me pressing buttons). That becomes a little longer if I try to load a small image at the same time too.

If we could get something up at the end right after app ready it still might feel nicer. There are also times when people are launching from scripts doing more fileIO etc inside our `gui_qt` event loop so it might be nicer there too. Putting it there would also mean people launching from jupyter or IPython wouldn't see it too, which was a concern from @jni, and makes sense to me - I think expectations are different when launching from the command line vs an interactive session.

I might give it a quick try with `QSplashScreen` and we can also decide against it. It looks like that approach will be only a couple lines, thanks for the tips!

**Comment by tlambert03** [comment]
> how did you do it?

just `import time` and printed some `time.time()` statements at various places 😅
the first statement at the top of `__init__` fired pretty much instantaneously after hitting enter.  3.2 seconds is definitely a bit frustrating, and maybe our differences are just computer differences? (but it certainly means that many users will be experiencing 3+ seconds).  

I definitely agree with @jni that we should only have splash screens with `__main__` or a standalone app... but i'd be curious to hear what you think after trying `QSplashScreen`

**Comment by sofroniewn** [comment]
@tlambert03 nice use of timing, I can try that too to be more quantitative. I've added a splash screen PR #745 with the requirements people described. I kinda like it, but we can continue the discussion there.

**Comment by tlambert03** [comment]
to isolate the cause of the delay a bit more:
i put some more timing statements during startup and found that almost all of the delay in start comes when importing ```.viewer```, and in that file, the bulk of the time comes from importing ```._qt.qt_viewer``` ... and there the slow imports are spread across the many imports... with vispy being a notable contributor.

**Comment by sofroniewn** [comment]
Following discussion in #745 I'm closing this issue for now. It was felt the splash screen didn't quite appear fast enough to be warranted. We can always revisit for the bundled app after #496 merges
