### ISSUE TITLE
Bug: non-Viewer keybinding listed in Viewer keybinding shortcut editor

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari/napari#5677]
## 🐛 Bug

When looking at the Viewer keybindings in the Shortcut editor, there is Transform and Pan/zoom at the top, which are not viewer keybindings. See:
<img width="1198" alt="image" src="https://user-images.githubusercontent.com/76622105/228284095-2d2d120e-4af6-45c7-a319-7382d6376d68.png">

## To Reproduce

1. Open Preferences > Shortcuts

## Expected behavior

These shouldn't be present as they don't do anything without a layer—same as using napari 0.4.17.

## Environment

```

napari: 0.5.0a2.dev51+gfc038f36
Platform: macOS-13.2.1-arm64-arm-64bit
System: MacOS 13.2.1
Python: 3.10.9 | packaged by conda-forge | (main, Feb 2 2023, 20:26:08) [Clang 14.0.6 ]
Qt: 5.15.6
PyQt5: 5.15.7
NumPy: 1.24.2
SciPy: 1.10.1
Dask: 2023.3.1
VisPy: 0.12.2.dev45
magicgui: 0.7.2
superqt: unknown
in-n-out: 0.1.7
app-model: 0.1.2
npe2: 0.6.2.dev26+gd7329b7.d20230324

OpenGL:
- GL version: 2.1 Metal - 83
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1680x1050, scale 2.0

Settings path:
- /Users/piotrsobolewski/Library/Application Support/napari/napari-dev_a1eb8b76ba95fa16ad06e26097b46b8455dfbf0b/settings.yaml

```

## Additional context

Doing some testing, it looks like this was introduced in https://github.com/napari/napari/pull/4894

**Comment by Czaki** [comment]
it comes from keeping shortcuts separated from action definition: https://github.com/napari/napari/blob/b1d7c4098287a83f5ecb3e5de6756fb0264cbd8c/napari/utils/shortcuts.py#L27

**Comment by psobolewskiPhD** [comment]
I don't think so? I tracked it down to missing Tracks layer. The way the table is generated is that anything not assigned to a layer is put in Viewer. 
See #5678
