### ISSUE TITLE
feature request: point selection event

### ISSUE THREAD

**Issue by alisterburt** [napari/napari#5686]
## 🚀 Feature
I would like an event to be fired when the selection changes on the points layer

## Motivation

I would like to use the point selection as the model and single source of truth for selection in a plugin. There is no event on selection change.

## Pitch

Add an event for selection change

## Alternatives

there is a 'highlight' event but this is fired when hovering over a point too

**Comment by alisterburt** [comment]
we *could* use a psygnal `EventedSet` internally for the selection model - if we don't want to mix event systems we could keep it private and hook it up to a vispy event emitter

**Comment by jni** [comment]
I'm pro EventedSet and I'm not super concerned about mixing event systems... If we wait to migrate *all* events in one go we are going to be waiting a long time 😂
