### ISSUE TITLE
Labels painting slow for big images

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#569]
## 🐛 Bug

The labels painting is now quite slow for big images, say 2048 x 2048. It's not clear if it has degraded recently - the undo / redo does seem to slow it down a little - but it may have always been that slow. We might need to think about how to make it faster. Another thing to add to our benchmarking list. #476.

**Comment by sofroniewn** [comment]
We might have had a recent regression when we changes some of our openGL options to improve mesh rendering for the shapes / surface layer

**Comment by sofroniewn** [comment]
Note that labels painting will likely be significantly speeded up by #204

**Comment by sofroniewn** [comment]
Painting has been significantly sped up by #684, so I will close this now, but it can still be further improved by #204

**Comment by VolkerH** [comment]
Can this be reopened? 

I just tried creating a labels layer with a size of `(1143, 1069)` on top of an RGB image and drawing annotations with napari from the current master.

When drawing with the brush I get a lag on the order of a second or even more.  I can't compare to the performance before merging #684 but it still feels very slow.  At this level it is too tedious to  label a significant part of an image for machine learning annotation.

Environment used

```
napari: 0.2.6+23.g8735eb2.dirty 
Platform: Windows-10-10.0.18362-SP0 
Python: 3.7.5 (default, Oct 31 2019, 15:18:51) [MSC v.1916 64 bit (AMD64)] 
PySide2: 5.13.2 
Qt: 5.13.2 
VisPy: 0.6.3 
NumPy: 1.17.3 
SciPy: 1.3.1 
scikit-image: 0.16.2 
Dask: 2.8.0 

GL version: '4.5.0 - Build 25.20.100.6472'
MAX_TEXTURE_SIZE: 16384 
```

**Comment by sofroniewn** [comment]
We can re-open, I think this will hopefully be closed by #713 which will remove an expensive int -> float conversion step

**Comment by liu-ziyang** [comment]
cc @VolkerH I wonder if you are still seeing performance issue with large image labeling? I believe 0.3/0.4 releases introduced some improvements to our labelling performance

**Comment by VolkerH** [comment]
I haven't done extensive labelling recently, but I certainly noticed various impreovements since 2019.
I still think it is not quite as responsive as I would hope.

I will tag in @abailoni  he has been working on some [annotation tools](https://github.com/abailoni/cellpose-training-gui)  recently and I believe after testing both napari and QuPath for annotation he found QuPath still had an edge in overall responsiveness and user experience. Maybe he can add some additional comments here.

**Comment by jni** [comment]
@potating-potato despite improvements, there's absolutely still issues, see e.g. https://forum.image.sc/t/napari-label-layer-color-maps-usage-and-colors-in-viewer-mismatching-the-tool-colors/64839

Once #3308 is in, although there will still be performance improvements to be had, we can *probably* close this one. :crossed_fingers:

**Comment by abailoni** [comment]
Yes, I confirm that recently I tried to label some big images with napari and I encountered some issues with responsiveness. It has been one/two months ago though, so right now I would not remember what was the size of the images I used.

**Comment by GenevieveBuckley** [comment]
Recent PRs addressing performance of the labels layer:
* https://github.com/napari/napari/pull/5723
* https://github.com/napari/napari/pull/5732
* https://github.com/napari/napari/pull/3308

**Comment by psobolewskiPhD** [comment]
For what it's worth, I just tried with a (3, 15000, 15000) image layer and labels on top using napari from `main` and napari 0.4.18rc1.
Making the layers (numpy random.rand) took some time, but painting was totally lag free and performant. The only performance issue I noticed was clicking the shuffle button. Incrementing labels was fast, but shuffle had a lag.

**Comment by GenevieveBuckley** [comment]
Ok, I'm going to close this issue. We can track performance improvements to the shuffle function over at https://github.com/napari/napari/issues/6010

**Comment by GenevieveBuckley** [comment]
Ok, I'm going to close this issue. We can track performance improvements to the shuffle function over at https://github.com/napari/napari/issues/6010
