### ISSUE TITLE
view freezes with 2G 13 channel tiff images

### ISSUE THREAD

**Issue by YubinXie** [napari/napari#5694]
I am using the latest 0.4.17 version on python 3.9.2 Mac OS. I opened naperi viewer and dropped a 2G tiff image. The window just freezes. Whatever I do, it says in terminal: 2023-04-04 15:32:44.402 napari[12345:33460107] Warning: Window move completed without beginning.

**Comment by psobolewskiPhD** [comment]
Can you provide the output of `napari --info` or copy paste the info from the Help menu item?
Also by `2G tiff image` do you mean 2Gb, as in size? how was this tiff saved?

**Comment by Czaki** [comment]
How long is freeze? 
Such a size of tiff is expected to freeze napari during load time.

**Comment by YubinXie** [comment]
Sure! It is 2Gb as size, saved by python tifffile. the freeze was like 15min before I closed it.
```
napari: 0.4.17
Platform: macOS-13.2.1-x86_64-i386-64bit
System: MacOS 13.2.1
Python: 3.9.2 | packaged by conda-forge | (default, Feb 21 2021, 05:02:20)  [Clang 11.0.1 ]
Qt: 5.12.9
PyQt5: 5.12.3
NumPy: 1.24.2
SciPy: 1.9.1
Dask: 2021.04.1
VisPy: 0.11.0
magicgui: 0.7.2
superqt: unknown
in-n-out: 0.1.7
app-model: 0.1.2
npe2: 0.6.2

OpenGL:
  - GL version:  2.1 ATI-4.9.51
  - MAX_TEXTURE_SIZE: 16384

Screens:
  - screen 1: resolution 2560x1440, scale 2.0
  - screen 2: resolution 2560x1440, scale 2.0

Plugins:
  - napari: 0.4.17 (77 contributions)
  - napari-console: 0.0.7 (0 contributions)
  - napari-svg: 0.1.6 (2 contributions)

```

**Comment by psobolewskiPhD** [comment]
How did you install napari? your pyqt5 is awfully old...

**Comment by Czaki** [comment]
Could you execute this script (with the proper path to the file)

```python
import tifffile

total_size = 0

with open("/path/to/tiff/file.tif", 'rb') as f:
    tif = tifffile.TiffFile(f)
    for page in tif.pages:
        total_size += page.size * page.dtype.itemsize

print(f"Image requires {total_size} bytes ({total_size / 1024**3} GB)")

import psutil

print(f"Available memory {psutil.virtual_memory().available / 1024**3} GB")
print(f"Total memory {psutil.virtual_memory().total / 1024**3} GB")
```

**Comment by YubinXie** [comment]
> How did you install napari? your pyqt5 is awfully old...

Thank you both for replying! I was installing on top of my napari several years ago. I just reinstalled it and all is good for now. It must be some old version package being slow. Thanks for the help.
