### ISSUE TITLE
QtLayerList does not update in the background

### ISSUE THREAD

**Issue by kne42** [napari/napari#57]
## 🐛 Bug
`QtLayerList` does not visually update when I tamper with `viewer.layers` until after I click on the window again. I.e., it's not updating in the background for whatever reason.

## To Reproduce

1. Create multiple layers and make them identifiable within the layer list.
2. Perform any sort of deleting or reordering operation on the layer list.

## Expected behavior

The layer list GUI should be updating in the background.

## Environment

 - napari-gui Version (e.g., 1.0): [a40163e](https://github.com/Napari/napari-gui/commit/a40163e3d9c8d306109f0ead8df0f1011edc1644)
 - OS (e.g., Linux): MacOS Mojave
 - Python version: 3.6.5

## Additional context

I will note that _adding_ layers has no such problem (although it is rather slow).

**Comment by royerloic** [comment]
probably have to call some 'repaint' like method to force an update of the GUI...
Strange that this is not happening automatically.

**Comment by sofroniewn** [comment]
This seems to be fixed now at least from our console. Maybe the original bug referenced a jupyter notebook / ipython console usecase, but as it works from our console I'm satisfied to close this - see the gif below for the behavior working as expected:

![layers_updating](https://user-images.githubusercontent.com/6531703/66274763-c6a39c80-e836-11e9-9d9c-23f343cc4bd6.gif)
