### ISSUE TITLE
Passing more than 256 (or even 64) pixels bitmap to QCursor can crash the whole X display manager

### ISSUE THREAD

**Issue by ksofiyuk** [napari/napari#5712]
## 🐛 Bug

This code in `QtViewer` changes the size of the cursor for the brush visualization depending on the zoom level and the brush size:
https://github.com/napari/napari/blob/5fa6716fceaa0d77516d664373c3f3a84ccd790d/napari/_qt/qt_viewer.py#L906-L919

It can easily exceed 256 pixels even considering the brush size limit of 40 because it depends on the zoom level that is unbound.

It can be reproduced on my Xubuntu 20.04 system that runs the LightDM X display manager. It is a very nasty bug as it can crash the whole X display manager forcing to reboot the system. 

It is unsafe to set the cursor size to more than 256 pixels on some systems, or even more than 64 pixels according to the [Qt documentation](https://doc.qt.io/qt-6/qcursor.html):

> Valid cursor sizes depend on the display hardware (or the underlying window system). We recommend using 32 x 32 cursors, because this size is supported on all platforms. Some platforms also support 16 x 16, 48 x 48, and 64 x 64 cursors.

## To Reproduce

1. Open napari with a label layer activated.
2. Select the brush mode.
3. Zoom in on an image as much as possible
4. Gradually increase the brush size

If you can zoom in the image so that the circle cursor covers almost the whole window, it means that your system is not affected by this bug.

## Environment

It reproduces on my laptop with Xubuntu 20.04, but it doesn't reproduce on Windows.  I haven't tested it yet on other Linux systems.

Info from the help menubar:
```
napari: 0.1.dev2763+gaee9af7
 Platform: Linux-5.15.0-69-generic-x86_64-with-glibc2.29
 System: Ubuntu 20.04.6 LTS
 Python: 3.8.10 (default, Mar 13 2023, 10:26:41) [GCC 9.4.0]
 Qt: 5.12.8
 PyQt5: 5.14.1
 NumPy: 1.23.0
 SciPy: 1.10.0
 Dask: 2023.3.2
 VisPy: 0.12.2
 magicgui: 0.7.2
 superqt: unknown
 in-n-out: 0.1.7
 app-model: 0.1.2
 npe2: 0.6.2
 
 OpenGL:
 - GL version: 4.6.0 NVIDIA 515.105.01
 - MAX_TEXTURE_SIZE: 32768
 
 Screens:
 - screen 1: resolution 2560x1440, scale 1.0
 - screen 2: resolution 1920x1080, scale 1.0
```

**Comment by ksofiyuk** [comment]
Possible solution: avoid using QCursor for the brush visualization and instead implement it by adding to the scene something like [vispy.scene.visuals.Ellipse](https://vispy.org/api/vispy.scene.visuals.html#vispy.scene.visuals.Ellipse) and update it on the mouse move.

**Comment by jni** [comment]
YIKES. Thanks for the report @ksofiyuk! I agree it's a good idea to change the paint cursor to use an [`Overlay`](https://github.com/napari/napari/pull/4894). (@brisvag it would be nice if you could make a PR to either the examples gallery or the [dev docs](https://napari.org/dev/guides/index.html) illustrating how to make custom overlays...! 😅)

**Comment by brisvag** [comment]
Overlay example ready on #5719 :)

**Comment by brisvag** [comment]
@ksofiyuk do you know if there's a way to query the supported sizes somehow? I don't think so, but I'm not familiar with low level qt stuff.

If not, I guess we can hard cap it at 64 until we come up with a vispy-based solution.

EDIT: actually, the qt docs seem to imply that it's not an upper limit, rather only *specific* sizes are "supported". Or am I reading that wrong?

**Comment by ksofiyuk** [comment]
@brisvag Unfortunately, I don't know how get the maximum cursor size. I even don't know how to google it correctly to find similar issues. It looks like using very large cursors is a gray area not documented for most systems.

And of course, it is undeniably a bug (and a serious security issue) in LightDM as well, as no one should be able to crash the system by manipulating the cursor.

Is there anyone else who also can report similar issues with very large cursors?
