### ISSUE TITLE
Add documentation preview also in main repository

### ISSUE THREAD

**Issue by Czaki** [napari/napari#5713]
## 🚀 Feature

It will be nice to have the option to preview docs also when someone creates PR to the main repository to check if everything renders appropriately. 

## Motivation

It is easier to preview documentation if rendered in the same way as in the docs repository. 

## Pitch

Ad circeCi job to build docs and github action that will add link to fast preview.

**Comment by Czaki** [comment]
@melissawm Could it be possible for you to do this?

**Comment by melissawm** [comment]
I can certainly try 😄 Thanks for pinging @Czaki - let me put something together
