### ISSUE TITLE
3D camera rotation is broken

### ISSUE THREAD

**Issue by brisvag** [napari/napari#5725]
## 🐛 Bug

It seems we introduced a bug in #5701, according to `git bisect`. The 3D camera rotation is "absolute" instead of relative (i.e: the point you press on the canvas determines the starting point of that rotation).

## To Reproduce

```py
import napari
import numpy as np
v = napari.Viewer(ndisplay=3)
pl = v.add_points(np.random.rand(10, 3) * 100)
```

Then move the camera a few times.

**Comment by jni** [comment]
Well... Shit. LOL

**Comment by jni** [comment]
Cool I think a quick fix would be to simply revert this change:

https://github.com/napari/napari/pull/5701/files#diff-5c61f0a4d37071dbd71d5b2933f35237bd3148b35e63d65c2828afd6580f83b2R34

```diff
-        self._3D_camera = ArcballCamera(fov=0)
+        self._3D_camera = MouseToggledArcballCamera(fov=0)
```

A deeper fix would be to understand why [these lines](https://github.com/napari/napari/pull/5701/files#diff-5c61f0a4d37071dbd71d5b2933f35237bd3148b35e63d65c2828afd6580f83b2R241-R249) would have this effect:

```python
        def viewbox_mouse_event(self, event):
            if (
                self.mouse_zoom
                and event.type == 'mouse_wheel'
                or self.mouse_pan
                and event.type in ('mouse_move', 'mouse_press')
            ):
                super().viewbox_mouse_event(event)
            else:
                event.handled = False
```

**Comment by brisvag** [comment]
found the issue!
