### ISSUE TITLE
Bad 3D rendering of labels

### ISSUE THREAD

**Issue by jni** [napari/napari#574]
## 🐛 Bug

I get some bad rendering of labels data in 3D, running the code in this gist:

https://gist.github.com/jni/587d8a946e5e86a8c0d3a7f8bee329cc

with `ipython --gui=qt` then `%run -i rendering.py`

<img width="1200" alt="Screen Shot 2019-10-08 at 12 45 45 pm" src="https://user-images.githubusercontent.com/492549/66361390-59c10b80-e9ca-11e9-9c19-a093758f613c.png">

The issue seems to be that the layer values are interpolated, which causes the crazy fringing with the random colormap. Note that I played around with the interpolation method in the image layers, but the problem does persist after restarting Python.

Additionally, "mip" rendering is a poor choice for labels, because high-value labels appear on top of low-value ones, even when the low labels are in front of the high ones. However, translucent rendering did not fix the fringing problem, so it still looks terrible for me.

## To Reproduce

1. Download https://gist.github.com/jni/587d8a946e5e86a8c0d3a7f8bee329cc to a file named `rendering.py`
2. Launch `ipython --gui=qt` in that directory.
3. Run `%run -i rendering.py`

## Environment

 - napari Version (e.g., 1.0): master
 - OS (e.g., Linux): macOS 10.14.6
 - Python version: 3.7.3
 - Any other relevant information: vispy version 0.6.1

**Comment by sofroniewn** [comment]
I can reproduce this effect on my laptop - both the fringes and the poor order behavior of `mip`. If I switch to `translucent` the order problems go away, but the fringes are terrible, which is likely due to the interpolation @jni mentioned and problems with our colormap

**Comment by jni** [comment]
I think we are probably going to need to mess with the shaders in vispy to fix this one, since as far as I can tell VisPy does not expose the ability to remove interpolation in the Volume Rendering view.
