### ISSUE TITLE
Bounding box for points is wrong

### ISSUE THREAD

**Issue by brisvag** [napari/napari#5750]
## 🐛 Bug

Something's off with the bounding box calculation for points:

![image](https://user-images.githubusercontent.com/23482191/233374459-6e2796d6-dae0-4396-a466-f55b071a9817.png)

```py
import napari
import numpy as np

img = np.random.rand(5, 4, 6)
pts = np.array([[0, 0, 0], [5, 5, 5]])

v = napari.Viewer(ndisplay=3)

il = v.add_image(img)
il.bounding_box.visible = True
pl = v.add_points(pts, size=1)
pl.bounding_box.visible = True
```

**Comment by brisvag** [comment]
Likely a 0.5 offset issue.

**Comment by AmanSal1** [comment]
@brisvag  can you please tell which version of napari are you using because this code is giving me error ?

**Comment by Czaki** [comment]
It should be napari from the main branch. Bounding boxes are implemented but not released yet.

**Comment by andy-sweet** [comment]
@brisvag : this is fixed on main for me now (maybe from https://github.com/napari/napari/pull/5751), so closing. Re-open if you find otherwise.
