### ISSUE TITLE
Selection outline should not be affected by `scale`

### ISSUE THREAD

**Issue by brisvag** [napari/napari#5752]
## 🐛 Bug

While creating new shapes, the shape is marked as selected. Shis adds an outline which seems to be affected by the layer scale and zoom in an odd way. With big scales, this makes picking on some image feature really hard, because the line is covering the features.

## To Reproduce

```py
import numpy as np
import napari
v = napari.Viewer()
sl = v.add_shapes(scale=[100, 100])
sl.add_paths([[0, 0], [1, 1], [3, 4]])
sl.selected_data = {0}
sl.mode = 'select'
```

Then manually zoom out.

## Expected behavior

The outline remains the same size in data space? Or maybe even in screen space?

**Comment by akuten1298** [comment]
Hi @brisvag, I'm looking into this issue currently and will start working on a fix. Can you please assign me to this bug incase it's required? just wanted to make sure that there are no duplicate efforts. Thank you.

**Comment by brisvag** [comment]
Hi @akuten1298! Sorry for not linking to it: I actually already worked on this in #5802. That PR is currently blocked by some test I need to fix, but this part is already fixed!

**Comment by akuten1298** [comment]
Oh..got it, no worries, was just getting started. Thanks for letting me know @brisvag
