### ISSUE TITLE
Documentation deployment is failing

### ISSUE THREAD

**Issue by melissawm** [napari/napari#5766]
## 🐛 Bug

It looks like we have an authentication failure for the docs deployment github action.

## To Reproduce

Full traceback: https://github.com/napari/napari/actions/runs/4787028359/jobs/8511714965

## Additional context

This may have appeared after the token change in #5714 but I'm still not sure how.

**Comment by psobolewskiPhD** [comment]
Hmm, I got this same failure last night when I tried to push something using gh CLI. I had to re-authenticate. So I think it's not related to that token change but some GitHub change taking effect.
Maybe @czaki has an idea?

**Comment by Czaki** [comment]
The message is here:

```
  "message": "`napari` forbids access via a personal access token (classic). Please use a GitHub App, OAuth App, or a personal access token with fine-grained permissions.",
```

So it looks like there is a need to investigate more usage of personal fine-grained tokens. And this requires support from someone with access to napari settings. 

@jni next topic on meeting.

**Comment by jni** [comment]
Fixed — I broke the repo settings while configuring a new token for #5715 😬 

I'll leave this open as a reminder that we should migrate to fine-grained permission tokens (per @Czaki) as done for #5715.

**Comment by psobolewskiPhD** [comment]
The deployment appears to be working, however I notice that the circleCI preview does not appear to be working. The redirector is being skipped?

**Comment by melissawm** [comment]
~~Could this have to do with #5715? I'm not sure...~~ Nope. I can see the action is skipped but it's not clear *why*. I'll debug

Just to be sure: did anyone with admin/owner privileges enable CircleCI in this repo? I think you need to log in once to enable the token used to run the actions there. If you go to https://app.circleci.com/settings/user/plans (after logging in) you should see organizations which have either requested access or have already been granted access. This could be it, as all was working on my fork.

**Comment by psobolewskiPhD** [comment]
Paging @jni

**Comment by Czaki** [comment]
As I review current actions, everything looks fine. But I think I miss something. 

Which workflow needs to be fixed? 

https://github.com/napari/napari/actions/runs/4932212544/jobs/8815028610

**Comment by psobolewskiPhD** [comment]
The CircleCI actions don't appear to be working, if you look at any open PR.

**Comment by Czaki** [comment]
You mean "build docs on napari/docs"?

**Comment by psobolewskiPhD** [comment]
I mean these:
<img width="503" alt="image" src="https://github.com/napari/napari/assets/76622105/b044181f-e93f-401e-98d9-b68831382ba1">

**Comment by Czaki** [comment]
It looks like I have ability to fix this at this moment https://github.com/napari/napari/pull/5784
