### ISSUE TITLE
Performance with invisible layers

### ISSUE THREAD

**Issue by jni** [napari/napari#578]
## 🐛 Bug

When many layers are added to napari, many operations are extremely sluggish, *even if all but one* of the layers are set to invisible. We should instead immediately render only visible layers and turn off most/all data handling for layers with visibility 0.

Here are some things that are very slow when many (~100) layers are added to the display:

- zoom
- changing ndisplay (this is incredibly slow)
- changing the visibility of a layer

In general, it would be great if we didn't use `set_view_slice` at all on invisible layers, so that if the layers are referring to data on disk (e.g. hdf5 array), it is not loaded at all unless it is visible. Additionally, the effect of changing ndisplay should be minimal if the layer is not visible.

**Comment by sofroniewn** [comment]
Ok - makes sense, but we just need to make sure things don't get in weird states where you expect things to be one way, but because of the visible stuff they aren't. Adding in the benchmarking and profiling stuff will help us figure out which are the bits that are really slow

if zoom is slow it's really a vispy thing that would be harder to fix on the napari side

**Comment by eburling** [comment]
I'm experiencing this in a multiplex immunofluorescence imaging use case illustrated [here](https://www.loom.com/share/8af375e297274189bbbb7d2bd34596ea). For reference, each layer is a multiresolution zarr array being read in by dask, e.g.:

```python
cache = Cache(2e9)  # Leverage two gigabytes of memory
cache.register()

viewer = napari.Viewer()

base = imread('stain1.tif')
pyramid = list(pyramid_gaussian(base, downscale=2, max_layer=3, multichannel=False))
root = zarr.open_group('pyramid.zarr', mode='a')

for i in range(0, len(pyramid)):
    shape = pyramid[i].shape
    z = root.create_dataset(str(i), shape=shape, chunks=(300, 300), dtype='float')
    z[:] = pyramid[i]
    
pyramid = [da.from_zarr(file_name + '/' + str(i)) for i in range(len(pyramid))]

viewer.add_image(pyramid, name='stain1', visible=False, opacity=0.5, is_pyramid=True)
```
When I am browsing at the highest resolution of the pyramid (8059 x 9454 pixels) I notice that the layer index at the lower left of the viewer iterates over each layer, presumably loading the chunks of the invisible layers. At most, I expect to be visualizing 5 layers at any one time, with manual switching between layer combinations, so lazy loading at this level would be great.

**Comment by jni** [comment]
@eburling thanks for chiming in! Very cool dataset. :grinning: Fixing this is a high priority for us. We'll keep you posted!

**Comment by sofroniewn** [comment]
Yikes! that's for including the video @eburling, I feel your pain! It should be pretty easy for us to turn off some of those refreshes if the layers aren't visible (certainly the pyramid related ones), that will make a huge difference here.

**Comment by eburling** [comment]
Cheers, @jni and @sofroniewn! I saw the napari demo at Bioimage Informatics this month and have been tinkering every since. Thanks for the great work.

**Comment by VolkerH** [comment]
@jni contacted me via email asking for a multiplexed dataset for testing (showing him the sluggishness with my comparatively small dataset is how this issue started). The code is here https://github.com/VolkerH/NapariPlayground and the dataset is downloaded in the background. 

For performance testing it may be helpful to modify the code to add each layer more than once.

A few observations:

* When switching to 3D mode all the MIP projections appear to be calculated immediately, even for the non-visible layers.
* Thumbnail updates require looking at the data. In some cases it is very useful to have thumnail updates for non-visible layers (if the data changed underneath) but in the multiplexing case it has an unwelcome performance cost.
* Is it possible to instantiate layers with `visible=False` for "lazy data", e.g. images from generator or future objects that only get evaluated once the visibility of the layer is set to True ?
