### ISSUE TITLE
About dialog from drop-down menu

### ISSUE THREAD

**Issue by VolkerH** [napari/napari#579]
## 🚀 Feature

A menu item that brings up an "About" dialog, in a place where one usually finds them.
E.g. pull-down "help", "About".
![image](https://user-images.githubusercontent.com/2210044/66455154-aaf9f980-eab5-11e9-90a0-1b149256effd.png)

The about dialog should show the version numbers.

## Motivation

While the about dialog may not be the most pressing feature, it is useful for reporting bugs, if the dialog reports version numbers of napari (and potentially other libraries).

**Comment by sofroniewn** [comment]
Good idea - getting the version number in there at a minimum sounds useful. Also a way to print all the keybindings.

We can work on these

**Comment by AhmetCanSolak** [comment]
@sofroniewn i can take this if you want it to be implemented soon

**Comment by sofroniewn** [comment]
great @AhmetCanSolak - that would be really helpful

**Comment by AhmetCanSolak** [comment]
Opened a PR on this here #580

**Comment by sofroniewn** [comment]
This is closed by #580 and #583 , thanks for the feature request!

**Comment by VolkerH** [comment]
thank you @sofroniewn and @AhmetCanSolak
