### ISSUE TITLE
Changing Qt layouts

### ISSUE THREAD

**Issue by AhmetCanSolak** [napari/napari#58]
## 🚀 Feature
Hello everybody!
I need to introduce a breaking change in code base.  I'm proposing to change layouts to more design friendly way. Like having a grid on top level and widget based layouts accordingly. I started to implement already just want your collaboration on that for smoother merge of this feature.

## Motivation
Current layouting is not working responsively and hard to manage. Including more gui widgets will cause more and more trouble with current implementation.

## Pitch
I want to put a grid layout on top level where we will have stretchable layouts. Those stretchable layouts will include viewer, layerlist, slicing sliders and cmap sliders.

## Alternatives
we could serve a fixed resolution gui? which will be terrible i believe.

**Comment by jni** [comment]
I just want to flag that some grid-based layouts can be quite terrible, for example with sliders getting incongruously wide. So, I'm in favour of "sane" layouts, for sure, but imho the main image window is what should stretch and everything else should stay the same size (with the sliders matching the image window in width/height for horizontal/vertical sliders).

**Comment by AhmetCanSolak** [comment]
@jni exactly. Sliders, both the ones in bottom and left of the viewer will be matching viewer width/height. As well as sliders, layerlist will be doing same on right hand side too. please find the dummy template below: 
<img width="1057" alt="screen shot 2018-11-13 at 12 53 17 pm" src="https://user-images.githubusercontent.com/15677695/48446778-09581400-e74f-11e8-82c5-1aeb4bbfb526.png">

**Comment by jni** [comment]
Ok, so the width of (1) and the height of (4) will be fixed, right?

What are you gonna do with the corners? :joy:

**Comment by sofroniewn** [comment]
This seems reasonable to me. I think I would make the width of (3) fixed too.

**Comment by AhmetCanSolak** [comment]
@jni 
> Ok, so the width of (1) and the height of (4) will be fixed, right?

They are proportional but trying to find a way to give max height/width to achieve desired functionality.

> What are you gonna do with the corners? 😂

We can have a slideshow of our pictures? :P or getting ads maybe :P. just kidding.

@sofroniewn 
I want to make it similar to 1.

**Comment by jni** [comment]
> They are proportional but trying to find a way to give max height/width to achieve desired functionality.

imho max should be equal to min. =P

**Comment by AhmetCanSolak** [comment]
With #63 I introduced splitters to make main components of the gui, except canvas, collapsable. I will be addressing restructuring gui layout ideas in the following PRs.

**Comment by sofroniewn** [comment]
This has been addressed in #88
