### ISSUE TITLE
Unclear how to deal with unhandled error message

### ISSUE THREAD

**Issue by ianhi** [napari/napari#5815]
## 🐛 Bug

My plugin has some bug that is causing an issue with napari displaying an error in the console. This is being printed out to the console:

```
An error occurred while trying to format an error and show it in console.
You can try to uninstall IPython to disable rich traceback formatting
And/or report a bug to napari
```

I'm having two issues with this:

1. I tried uninstalling `ipython` - to no avail
2. I have no idea how to disable rich traceback - there doesn't seem to be an option in the preferences.

## To Reproduce
```
pip install git+https://github.com/pymmcore-plus/napari-micromanager
napari
# luanch the micromanager plugin
```

## Expected behavior

Error handled differently when ipython is uninstalled - and/or error message gives some guidance on how to disable this rich formatting.

## Environment
```
napari: 0.4.17
Platform: Linux-5.17.15-76051715-generic-x86_64-with-glibc2.35
System: Pop!_OS 22.04 LTS
Python: 3.9.16 | packaged by conda-forge | (main, Feb 1 2023, 21:39:03) [GCC 11.3.0]
Qt: 5.15.2
PyQt5: 5.15.9
NumPy: 1.24.3
SciPy: 1.9.1
Dask: 2023.4.1
VisPy: 0.11.0
magicgui: 0.7.2
superqt: unknown
in-n-out: 0.1.7
app-model: 0.1.4
npe2: 0.7.0

OpenGL:
- GL version: 4.6 (Compatibility Profile) Mesa 22.3.5
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1080, scale 1.0

```

**Comment by Czaki** [comment]
@ianhi is it possible for you to paste the whole stack trace? I have an idea where the problem may be, but I'm not sure. 

Or this is a whole error that you got?

**Comment by ianhi** [comment]
That's pretty much the whole error. Everything for completeness:


```
(test) ian@fermented-beans:~/Documents/oss/micro/napari-micromanager/expts$ python launch.py 
Gtk-Message: 10:25:08.151: Failed to load module "appmenu-gtk-module"
WARNING: QMainWindowLayout::count: ?
An error occurred while trying to format an error and show it in console.
You can try to uninstall IPython to disable rich traceback formatting
And/or report a bug to napari
```

**Comment by Czaki** [comment]
Is it possible to share the code causing this problem?

**Comment by ianhi** [comment]
Unfortunately I can't really get it down to small example,  because I can't see the error message to tell me the responsible line :(


But that said some investigations narrow it down to these lines: https://github.com/pymmcore-plus/napari-micromanager/blob/429776da9484af14426d3a919f5c4499837f9073/src/napari_micromanager/_gui_objects/_toolbar.py#L109-L111

and interestingly only with PyQt5, not with pyside2

**Comment by tlambert03** [comment]
The underlying error here was a recursion error.  And, it was rather specific to a hacky approach in napari-micromanager... and while I can reproduce the error, I can't get it to show the `An error occurred while trying to format an error and show it in console.` message anymore.  
It's possible there's still room to improve napari's error display, but I think it's safe to say that this particular case is too specific for napari to worry about.  going to close it for you
