### ISSUE TITLE
[Qt6] Add support for `pyqt6`

### ISSUE THREAD

**Issue by dstansby** [napari/napari#5820]
## 🚀 Feature
This is a request to replace `pyqt6_experimental` with just `pyqt6` in `setup.cfg`, and update the docs appropriately to metnion the option of using pyqt6 when installing napari. It looks like QT6 support was tracked in https://github.com/napari/napari/issues/3880, which is now closed. So I guess this issue can be used to track any outstanding items specifically related to PyQT6?

**Comment by Czaki** [comment]
The qt6 support is still experimental. We have the important part of GUI not covered with test so we are not sure if everything works correctly on qt6.

**Comment by dstansby** [comment]
👍 - I updated the title of the issue so this can be used to track PyQT6 support in general

**Comment by dstansby** [comment]
It looks like the test suite includes one pyqt6 run:
https://github.com/napari/napari/blob/d8dd1d2f592618064d2b5ac0c770ac1eb4741e77/.github/workflows/test_pull_requests.yml#L90-L92

Do you have an idea of what more needs to be done to complete pyqt6 support?

**Comment by Czaki** [comment]
> Do you have an idea of what more needs to be done to complete pyqt6 support?

A person playing dev with Installed Qt6 backend and checking if something crashes.
We have plan to release 0.5.0 with qt6 marked as experimental. Call people for testing. Fix the bugs and release 0.5.1 as qt6 ready

**Comment by psobolewskiPhD** [comment]
If we do this I think we should say >6.5
to cover this issue: https://github.com/napari/napari/issues/5644
