### ISSUE TITLE
DOC Recommend using virtual environment during dev install

### ISSUE THREAD

**Issue by lucyleeow** [napari/napari#5856]
## 📚 Documentation

Could we recommend using a virtual environment during [development install](https://napari.org/dev/developers/contributing.html#setting-up-a-development-installation) just like we do in the '[Install as Python package](https://napari.org/dev/tutorials/fundamentals/installation.html#install-as-python-package-recommended)' documentation page.

Happy to open PR if we're supportive of this.

**Comment by psobolewskiPhD** [comment]
Could you clarify what you think is missing?
<img width="822" alt="image" src="https://github.com/napari/napari/assets/76622105/9baf219a-8aba-4ece-a47c-c189cd3bc711">

**Comment by lucyleeow** [comment]
Nevermind I was looking at the stable version of the docs, not dev. Closing!

**Comment by psobolewskiPhD** [comment]
Ah, yup. That gets a lot of folks!
See also: https://github.com/napari/docs/issues/86#issuecomment-1529608084
