### ISSUE TITLE
novel gene discovery in Napari  (a.k.a. imperfect layer name incrementing)

### ISSUE THREAD

**Issue by berl** [napari/napari#586]
## 🐛 Bug
napari does a smart thing and adds an integer to the name of a layer if the name is already in use in the viewer. It then increments that number when another layer is added that fits the pattern.  This is great until you have layer names that end in numbers 
![Screenshot from 2019-10-13 13-28-55](https://user-images.githubusercontent.com/6773896/66722077-6379b300-edbe-11e9-91e3-37784cc7aa70.png)
which in this case results in different names that are sometimes real genes and sometimes not.

## To Reproduce

```
v = napari.Viewer()
for i in range(3):
    v.add_points(1000*np.random.rand(10,2), name = "no_problem")
for i in range(3):
    v.add_points(1000*np.random.rand(10,2), name = "problem:GAD1")
```

## Expected behavior
consistent use of a space or other character to separate the auto-increment integer from the original string

**Comment by sofroniewn** [comment]
ok - we can check if there is a spacebar before the last number and if no then we auto increment with `1` separated by a space, and if yes then we bump that number `+=1`. So for you
`GAD1` x3 => `GAD1`, `GAD1 1`, `GAD1 2`
but if you have done
`GAD 1` x3 => `GAD 1`, `GAD 2`, `GAD 3`
seem reasonable? that should be an easy change

**Comment by jni** [comment]
Yikes, next thing you know we'll be interpreting gene names as dates a-la Excel... =P

Another option would be to add parentheses or square brackets: Image [1], Image [2], ...

btw @berl that image is gorgeous, any chance we could use it for our examples? =D

**Comment by sofroniewn** [comment]
I like `Image [1]` better than `Image 1` makes it more clear it was auto-incremented
we'd then have
```
GAD1 x3 => GAD1, GAD1 [1], GAD1 [2]
GAD 1 x3 => GAD 1, GAD 1 [1], GAD 1 [2]
GAD [1] x3 => GAD [1], GAD [2], GAD [3]
Image x3 => Image, Image [1], Image [2]
```
which is probably the most clear

**Comment by berl** [comment]
I like the square brackets-  thanks @sofroniewn!

@jni we've got a lot more data like this... I'll put together something with more a few more genes (and less lipofuscin) and pass it along.
