### ISSUE TITLE
Installation Bug: pydantic error

### ISSUE THREAD

**Issue by landoskape** [napari/napari#5863]
## 🐛 Bug

I tried to install napari as a python packageon a windows 10 machine, but got a TypeError for issubclass() in pydantic\fields.py, line 668. 

## To Reproduce

In anaconda prompt, I typed: 
conda create -y -n napari-env -c conda-forge python=3.9
conda activate napari-env

Then: 
pip install napari[all]

Then:
napari

and I received the error:
File "C:\Users\andrew\anaconda3\envs\napari-env\lib\typing.py", line 852, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class

## Expected behavior

I expected this to open up the napari GUI

## Environment

I can't type napari info because I get the above error. 

Thanks for any help.

**Comment by Czaki** [comment]
this is upstrem pydantic bug: https://github.com/pydantic/pydantic/issues/5821

You need either install typing extension in version 4.5.0 or use python 3.10

**Comment by landoskape** [comment]
Thank you!

**Comment by Modjular** [comment]
For posterity, updating to 3.10 on a Windows 11 machine also works:
```
conda create -y -n napari-env -c conda-forge python=3.10
```

**Comment by Czaki** [comment]
The bugfix of pydantic was released. It is not on conda-forge yet but should land shortly.
