### ISSUE TITLE
invalid value encountered in cast 

### ISSUE THREAD

**Issue by VictorDidier** [napari/napari#5909]
## 🐛 Bug

RunTime Warning after opening a new layer (Windows OS)
## To Reproduce

1.Open a new layer by using the layer buttons
2.
3.

## Expected behavior

No warning

## Environment

 - Please copy and paste the information at napari info option in help menubar here:

 - Any other relevant information:

## Additional context
Windows OS

![Napari Issue](https://github.com/napari/napari/assets/68292394/5efe1cdb-9073-448c-b62c-cda38f715f84)

**Comment by psobolewskiPhD** [comment]
Could you provide the output of `napari --info` or from the Help > napari info menu item?

**Comment by psobolewskiPhD** [comment]
Hmm, seems similar to:
https://forum.image.sc/t/adding-empty-shapes-layer-after-adding-rgb-image-causes-runtimewarning/75676

**Comment by psobolewskiPhD** [comment]
@VictorDidier We have a 0.4.18 release candidate! Please try to install it from pypi and see if this is fixed for you:
Either create an new env and then:
`python -m pip install --pre "napari[all]"`
Or you can try to update in place:
`python -m pip install --pre napari -U`

**Comment by Czaki** [comment]
@psobolewskiPhD did you think that we could close this?
