### ISSUE TITLE
v0.4.18 - release process

### ISSUE THREAD

**Issue by Czaki** [napari/napari#5911]
## 3 opened PRs for milestone 0.4.18
* [x] napari/napari#5761
* [x] napari/napari#6016
* [x] napari/napari#6022

## 259 PRs with milestone 0.4.18:
 * [x] napari/napari#5108
 * [x] napari/napari#5138
 * [x] napari/napari#5135
 * [x] napari/napari#4907
 * [x] napari/napari#5131
 * [x] napari/napari#5160
 * [x] napari/napari#5158
 * [x] napari/napari#5004
 * [x] napari/napari#5186
 * [x] napari/napari#5176
 * [x] napari/napari#5084
 * [x] napari/napari#5173
 * [x] napari/napari#5083
 * [x] napari/napari#5036
 * [x] napari/napari#5003
 * [x] napari/napari#5192
 * [x] napari/napari#5193
 * [x] napari/napari#5191
 * [x] napari/napari#5142
 * [x] napari/napari#5114
 * [x] napari/napari#5220
 * [x] napari/napari#5171
 * [x] napari/napari#5209
 * [x] napari/napari#5202
 * [x] napari/napari#5239
 * [x] napari/napari#4826
 * [x] napari/napari#5245
 * [x] napari/napari#5258
 * [x] napari/napari#4922
 * [x] napari/napari#5180
 * [x] napari/napari#5195
 * [x] napari/napari#5276
 * [x] napari/napari#5270
 * [x] napari/napari#5291
 * [x] napari/napari#5290
 * [x] napari/napari#5292
 * [x] napari/napari#5283
 * [x] napari/napari#5262
 * [x] napari/napari#5215
 * [x] napari/napari#5213
 * [x] napari/napari#5310
 * [x] napari/napari#5318
 * [x] napari/napari#5315
 * [x] napari/napari#5331
 * [x] napari/napari#5093
 * [x] napari/napari#5337
 * [x] napari/napari#5339
 * [x] napari/napari#5277
 * [x] napari/napari#5234
 * [x] napari/napari#5320
 * [x] napari/napari#5354
 * [x] napari/napari#5351
 * [x] napari/napari#5303
 * [x] napari/napari#5329
 * [x] napari/napari#5350
 * [x] napari/napari#5317
 * [x] napari/napari#5363
 * [x] napari/napari#5275
 * [x] napari/napari#5366
 * [x] napari/napari#5333
 * [x] napari/napari#5393
 * [x] napari/napari#5388
 * [x] napari/napari#5394
 * [x] napari/napari#5398
 * [x] napari/napari#5334
 * [x] napari/napari#5150
 * [x] napari/napari#5403
 * [x] napari/napari#5312
 * [x] napari/napari#5386
 * [x] napari/napari#5373
 * [x] napari/napari#4505
 * [x] napari/napari#5406
 * [x] napari/napari#5399
 * [x] napari/napari#5412
 * [x] napari/napari#5423
 * [x] napari/napari#5414
 * [x] napari/napari#5416
 * [x] napari/napari#5089
 * [x] napari/napari#5307
 * [x] napari/napari#5431
 * [x] napari/napari#5381
 * [x] napari/napari#5441
 * [x] napari/napari#5422
 * [x] napari/napari#5143
 * [x] napari/napari#5447
 * [x] napari/napari#5442
 * [x] napari/napari#5437
 * [x] napari/napari#5456
 * [x] napari/napari#5449
 * [x] napari/napari#5446
 * [x] napari/napari#5452
 * [x] napari/napari#5383
 * [x] napari/napari#5465
 * [x] napari/napari#5458
 * [x] napari/napari#5450
 * [x] napari/napari#5208
 * [x] napari/napari#5471
 * [x] napari/napari#5467
 * [x] napari/napari#5469
 * [x] napari/napari#5486
 * [x] napari/napari#5478
 * [x] napari/napari#5474
 * [x] napari/napari#5491
 * [x] napari/napari#5451
 * [x] napari/napari#5480
 * [x] napari/napari#5499
 * [x] napari/napari#5504
 * [x] napari/napari#5513
 * [x] napari/napari#5492
 * [x] napari/napari#5413
 * [x] napari/napari#4894
 * [x] napari/napari#5525
 * [x] napari/napari#5544
 * [x] napari/napari#5539
 * [x] napari/napari#5531
 * [x] napari/napari#5533
 * [x] napari/napari#5548
 * [x] napari/napari#5560
 * [x] napari/napari#5520
 * [x] napari/napari#5541
 * [x] napari/napari#5482
 * [x] napari/napari#5490
 * [x] napari/napari#5532
 * [x] napari/napari#5564
 * [x] napari/napari#5534
 * [x] napari/napari#5546
 * [x] napari/napari#5501
 * [x] napari/napari#5571
 * [x] napari/napari#5565
 * [x] napari/napari#5487
 * [x] napari/napari#5580
 * [x] napari/napari#5566
 * [x] napari/napari#5593
 * [x] napari/napari#5587
 * [x] napari/napari#5586
 * [x] napari/napari#5596
 * [x] napari/napari#5592
 * [x] napari/napari#5602
 * [x] napari/napari#5603
 * [x] napari/napari#5578
 * [x] napari/napari#5577
 * [x] napari/napari#5605
 * [x] napari/napari#5528
 * [x] napari/napari#5130
 * [x] napari/napari#5595
 * [x] napari/napari#5631
 * [x] napari/napari#5636
 * [x] napari/napari#5640
 * [x] napari/napari#5647
 * [x] napari/napari#5646
 * [x] napari/napari#5683
 * [x] napari/napari#5656
 * [x] napari/napari#5635
 * [x] napari/napari#5590
 * [x] napari/napari#5628
 * [x] napari/napari#5669
 * [x] napari/napari#5678
 * [x] napari/napari#5682
 * [x] napari/napari#5698
 * [x] napari/napari#5691
 * [x] napari/napari#5702
 * [x] napari/napari#5708
 * [x] napari/napari#5704
 * [x] napari/napari#5696
 * [x] napari/napari#5695
 * [x] napari/napari#5594
 * [x] napari/napari#5693
 * [x] napari/napari#5649
 * [x] napari/napari#5648
 * [x] napari/napari#5692
 * [x] napari/napari#5701
 * [x] napari/napari#5719
 * [x] napari/napari#5726
 * [x] napari/napari#5720
 * [x] napari/napari#5722
 * [x] napari/napari#5723
 * [x] napari/napari#5645
 * [x] napari/napari#5727
 * [x] napari/napari#5729
 * [x] napari/napari#5642
 * [x] napari/napari#5754
 * [x] napari/napari#5745
 * [x] napari/napari#5707
 * [x] napari/napari#5741
 * [x] napari/napari#5717
 * [x] napari/napari#5715
 * [x] napari/napari#5762
 * [x] napari/napari#5776
 * [x] napari/napari#5742
 * [x] napari/napari#5763
 * [x] napari/napari#5771
 * [x] napari/napari#5746
 * [x] napari/napari#5716
 * [x] napari/napari#5739
 * [x] napari/napari#5795
 * [x] napari/napari#5809
 * [x] napari/napari#5728
 * [x] napari/napari#5796
 * [x] napari/napari#5759
 * [x] napari/napari#5732
 * [x] napari/napari#5827
 * [x] napari/napari#5757
 * [x] napari/napari#5813
 * [x] napari/napari#5836
 * [x] napari/napari#5680
 * [x] napari/napari#5830
 * [x] napari/napari#5823
 * [x] napari/napari#5805
 * [x] napari/napari#5804
 * [x] napari/napari#5862
 * [x] napari/napari#5841
 * [x] napari/napari#5826
 * [x] napari/napari#5854
 * [x] napari/napari#5865
 * [x] napari/napari#5850
 * [x] napari/napari#5867
 * [x] napari/napari#5555
 * [x] napari/napari#5679
 * [x] napari/napari#5885
 * [x] napari/napari#5894
 * [x] napari/napari#5860
 * [x] napari/napari#5736
 * [x] napari/napari#5872
 * [x] napari/napari#5895
 * [x] napari/napari#5899
 * [x] napari/napari#5834
 * [x] napari/napari#5439
 * [x] napari/napari#5848
 * [x] napari/napari#5919
 * [x] napari/napari#5924
 * [x] napari/napari#5831
 * [x] napari/napari#5928
 * [x] napari/napari#5908
 * [x] napari/napari#5877
 * [x] napari/napari#5937
 * [x] napari/napari#5210
 * [x] napari/napari#5615
 * [x] napari/napari#5910
 * [x] napari/napari#5944
 * [x] napari/napari#5947
 * [x] napari/napari#5915
 * [x] napari/napari#5964
 * [x] napari/napari#5922
 * [x] napari/napari#5948
 * [x] napari/napari#5967
 * [x] napari/napari#5968
 * [x] napari/napari#5963
 * [x] napari/napari#5812
 * [x] napari/napari#5824
 * [x] napari/napari#5582
 * [x] napari/napari#5985
 * [x] napari/napari#5979
 * [x] napari/napari#5984
 * [x] napari/napari#5994
 * [x] napari/napari#6018
 * [x] napari/napari#5997
 * [x] napari/napari#6013
 * [x] napari/napari#5980
 * [x] napari/napari#6002

## 1 PRs without milestone:
 * [ ] napari/napari#5992

## 6 PRs with milestone 0.5.0 and label bugfix:
 * [ ] napari/napari#5622
 * [ ] napari/napari#5785
 * [ ] napari/napari#5851
 * [ ] napari/napari#5970
 * [ ] napari/napari#5971
 * [ ] napari/napari#5604

## 1 Opened Issues with label bug and milestone 0.4.18
 * [x] napari/napari#5279

## 62 Opened Issues with label bug
 * [ ] napari/napari#6019
 * [ ] napari/napari#5972
 * [x] napari/napari#6000
 * [ ] napari/napari#5527
 * [ ] napari/napari#5409
 * [x] napari/napari#5657
 * [ ] napari/napari#6001
 * [ ] napari/napari#5999
 * [x] napari/napari#5998
 * [ ] napari/napari#5977
 * [ ] napari/napari#5935
 * [ ] napari/napari#5933
 * [ ] napari/napari#5930
 * [x] napari/napari#5929
 * [x] napari/napari#5914
 * [x] napari/napari#5916
 * [ ] napari/napari#5883
 * [ ] napari/napari#5625
 * [ ] napari/napari#5901
 * [x] napari/napari#5668
 * [ ] napari/napari#5840
 * [x] napari/napari#5752
 * [x] napari/napari#5673
 * [ ] napari/napari#5769
 * [x] napari/napari#5770
 * [ ] napari/napari#5803
 * [ ] napari/napari#5846
 * [ ] napari/napari#5844
 * [ ] napari/napari#5839
 * [ ] napari/napari#5798
 * [x] napari/napari#5815
 * [ ] napari/napari#5599
 * [ ] napari/napari#5790
 * [x] napari/napari#5507
 * [ ] napari/napari#5747
 * [ ] napari/napari#5760
 * [x] napari/napari#5750
 * [ ] napari/napari#5233
 * [ ] napari/napari#5684
 * [ ] napari/napari#5653
 * [x] napari/napari#5619
 * [x] napari/napari#5545
 * [ ] napari/napari#5553
 * [ ] napari/napari#5498
 * [x] napari/napari#5378
 * [ ] napari/napari#5505
 * [ ] napari/napari#5460
 * [ ] napari/napari#5468
 * [ ] napari/napari#5400
 * [ ] napari/napari#5349
 * [ ] napari/napari#5410
 * [x] napari/napari-plugin-manager#35
 * [ ] napari/napari#5395
 * [x] napari/napari#5371
 * [x] napari/napari#5355
 * [ ] napari/napari#5352
 * [ ] napari/napari#5314
 * [ ] napari/napari#5346
 * [ ] napari/napari#5278
 * [ ] napari/napari#5256
 * [ ] napari/napari#5242
 * [ ] napari/napari#5162

The content of this issue will be updated to reflect current state.

**Comment by melonora** [comment]
Here is a quick list of all current PRs that have been set to ready for merge but don't have a milestone and are not mentioned here yet:
## Maintenance label
#5908 
#5877

## Bugfix
#5582 

## Enhancement
#5210

**Comment by Czaki** [comment]
@melonora I mark all as 0.4.18

**Comment by Czaki** [comment]
Backport https://github.com/napari/docs/pull/181

**Comment by jni** [comment]
Since 0.4.18 is out, I am going to close this issue. Thank you @Czaki!
