### ISSUE TITLE
Napari window not showing on laptop screen after working with external display

### ISSUE THREAD

**Issue by seraweevers** [napari/napari#5912]
## 🐛 Bug

I regularly switch from working with napari on my laptop that is connected to an external screen to working on just my laptop (no screen connected). I have a problem with displaying the napari viewer when I work on my just my laptop after it has been connected to an external screen the last time I worked with napari.

When I call the napari viewer on my laptop, the viewer does not show on my laptop screen. The viewer get's created and I can see it's icon in the Windows taskbar, but the viewer itself does not open. Even when I click on the icon in the taskbar, I cannot make it appear.

## To Reproduce

I work on a Windows 10 Enterprise computer that is regularly connected to a larger external display.

1. When connected to the external display, I call the napari viewer from a Jupyter Notebook using `from napari.viewer import Viewer` `napari_viewer = Viewer()` and display the viewer on my external screen.
2. If I, next time that I work, am disconnect from this external display and call the napari viewer (`from napari.viewer import Viewer` `napari_viewer = Viewer()`) again, the bug arises.

## Expected behavior

When I call the napari viewer for the second time (while disconnected from my external display), I expect the viewer to open as normal and display on my laptop screen.

## Environment

The bug happens with both the environments in which I have napari installed.

Environment 1:

napari: 0.4.16
Platform: Windows-10-10.0.19044-SP0
Python: 3.8.13 (default, Oct 19 2022, 22:38:03) [MSC v.1916 64 bit (AMD64)]
Qt: 5.15.2
PyQt5: 5.15.7
NumPy: 1.24.3
SciPy: 1.9.1
Dask: 2022.02.1
VisPy: 0.10.0

OpenGL:
- GL version: 4.6.0 - Build 30.0.101.1692
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1080, scale 1.0

Plugins:
- console: 0.0.6
- napari-svg: 0.1.6
- scikit-image: 0.4.16

Environment 2:

napari: 0.4.16
Platform: Windows-10-10.0.19044-SP0
Python: 3.9.13 (main, Aug 25 2022, 23:51:50) [MSC v.1916 64 bit (AMD64)]
Qt: 5.12.9
PyQt5: 5.12.3
NumPy: 1.23.2
SciPy: 1.8.1
Dask: 2022.6.1
VisPy: 0.10.0

OpenGL:
- GL version: 4.6.0 - Build 30.0.101.1692
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1080, scale 1.0

Plugins:
- console: 0.0.6
- morphometrics: 0.0.6.dev9+g7c2bb20
- napari-svg: 0.1.6
- napari-tools-menu: 0.1.17
- napari_skimage_regionprops1: 0.5.4
- napari_skimage_regionprops2: 0.5.4
- scikit-image: 0.4.16

## Additional context

My workaround at this moment is:
1. Close all my Jupyter Notebooks
2. In my command prompt run `napari --reset`
3. Reopen whichever Jupyter Notebooks I was running / working on

**Comment by Czaki** [comment]
The napari 0.4.16 is not the latest released. Could you check if it still happens in 0.4.17?

**Comment by seraweevers** [comment]
Thanks for the quick reply!
The napari viewer still partially opens outside of my laptop screen, but with the newer version I am able to use the Windows taskbar icon to maximize it on my laptop screen and then continue working without any problems.

**Comment by psobolewskiPhD** [comment]
Great to hear you have it working--btw is that in the same env? so updated napari in place with the same Qt version? or new napari in new env, with new Qt?
You can post `napari --info again` I guess

**Comment by Czaki** [comment]
Ok. So I think that I know the source of the problem. We restore the previous position of viewer without checking if the coordinates are fitting on the current screen.

**Comment by Czaki** [comment]
@seraweevers Could you attach a sketch of how you position your displays? 

I think that the source of the problem is in these lines:
https://github.com/napari/napari/blob/5bced982e57d8d5876884a8f18df6e3efb5084d7/napari/_qt/qt_main_window.py#L288-L291

W should not use only the primary screen but all screens and check if the image fits on any available screen. 

I also meet negative coordinates that we do not check in any way.

**Comment by seraweevers** [comment]
![setup-napari](https://github.com/napari/napari/assets/120113212/4bfeb9c6-f93c-48a1-b223-0e57c7939528)

Forgive me for my mediocre drawing. But this is the setup I use. The external display is positioned (vertically) above the laptop screen.

**Comment by Czaki** [comment]
When you will have access to this monitor could you move the viewer on it open console and execute this line `viewer.window._qt_window.pos()` and paste output of command.

In my case it looks like this:

```python
viewer.window._qt_window.pos()
Out[1]: PyQt5.QtCore.QPoint(2459, 353)
```

**Comment by seraweevers** [comment]
It indeed produces negative values, already when connected to the external screen.

```
napari_viewer.window._qt_window.pos()
Out[1]: PyQt5.QtCore.QPoint(-15, -2040)
```

**Comment by melonora** [comment]
Hi @seraweevers, 

I am working on your issue at the moment. Could you confirm please whether this only happens when napari was not set to full screen on the external screen?

**Comment by melonora** [comment]
@seraweevers #5915 is open to fix the issue you have.

**Comment by seraweevers** [comment]
@melonora Just wanted to confirm here that the problem indeed only arises when not using napari in full screen. When I use the viewer in full screen on my external display and then disconnect and reopen napari, it opened full screen on my laptop display without any problems.

**Comment by melonora** [comment]
@seraweevers Thanks for confirming
