### ISSUE TITLE
Scale bar extends beyond the size of canvas when zooming in

### ISSUE THREAD

**Issue by kephale** [napari/napari#5914]
## 🐛 Bug

When you zoom in past a scale bar size of `1` the scale bar keeps extending beyond the size of the canvas. 

## To Reproduce

https://github.com/napari/napari/assets/400105/1070264d-f82c-4bfc-991d-b507cdc704d2
Caption: Screen recording of zooming in and the scale bar keeps extending once it reaches 1 instead of resizing. 

1. Open an image
2. View > Scale Bar > Scale Bar Visible [check]
3. Zoom in

## Expected behavior

The scale bar unit should continue getting smaller than 1. I think @andy-sweet showed a demo with units enabled and the napari-metadata plugin?

## Environment

On a feature branch that is updated to `902f5197a9e6f4752c0c673a0f4e06b01b407081` on main (~main as of June 1).

**Comment by psobolewskiPhD** [comment]
I can reproduce on main.
If you just enable using the menu, then you get the described behavior.
However, if you set units, e.g.:
`viewer.scale_bar.unit = "um"`
(this can only be done programmatically as far as I know and lacks documentation, see https://github.com/napari/docs/issues/38)
then it works as expected with the scale bar staying approx the same length but units changing.

**Comment by kephale** [comment]
Aha! Thank you @psobolewskiPhD. I saw it in the napari-metadata demo, but I remembered Andy saying it was functionality that previously existed.

In my case the data is unit-less synthetic data, so although setting the units will probably my case for demo purposes, eventually I'd hope for something more like scientific notation in this case.

**Comment by psobolewskiPhD** [comment]
Here's the source of the issue:
https://github.com/napari/napari/blob/af7d46918a67084e6c8e927251936e417ee6d5cc/napari/utils/_units.py#L5-L21
Without units, the `1` is the smallest value possible.

I think as a good fix, we could have the default unit to be `pixel`, rather than `None`:
https://github.com/hgrecco/pint/blob/3fb63af49df803e7bcad1fe9e6bdaab04021f4cc/pint/default_en.txt#L666

Then it works fairly elegantly I think:
<img width="1269" alt="image" src="https://github.com/napari/napari/assets/76622105/16258786-0778-4c27-b5f5-07448e222d5a">

<img width="1269" alt="image" src="https://github.com/napari/napari/assets/76622105/6309624a-b151-448e-8634-434eb9a1e0d1">

**Comment by kephale** [comment]
I like the simplicity of @psobolewskiPhD's `pixel` default unit suggestion. 

I have another issue incoming for `scale_bar` and it may be related.

**Comment by kephale** [comment]
I agree with @andy-sweet on this. However, since `pixel` is also used as a convention in ImageJ *and* using `pixel` as the unit solves the problem in this case, I would give this a low priority. 

However, I'm going to label it as a good first issue, because I think @andy-sweet's implementation tips could be enough information for someone to solve this and I think this can be a small effort.

**Comment by dalthviz** [comment]
Hi, gave this a check, maybe adding a validation like:

```python
        if new_value > new_quantity.magnitude:
            new_value = new_quantity.magnitude
```

After the `new_value = PREFERRED_VALUES[index]` definition at:

https://github.com/napari/napari/blob/5ce6fc9a6beb45cc819a6f4c8a9ccebdef801667/napari/_vispy/overlays/scale_bar.py#L74

Could be enough here?

With this, seems like the scale bar value is able to be lower than 1:

![scale_bar](https://github.com/napari/napari/assets/16781833/0332183a-c2aa-450a-90f0-36e113142f63)

**Comment by kephale** [comment]
@dalthviz oh cool! I suspect we want to use less precision on the floating points, but I'm not sure if we have a convention for numerical precision in napari.
