### ISSUE TITLE
BUG `changing` event in `EventedDict` not emitted

### ISSUE THREAD

**Issue by lucyleeow** [napari/napari#5929]
## 🐛 Bug

The `changing` event in [`EventedDict`](https://github.com/napari/napari/blob/8c307022cc557692409f5e8bc031f1dcde4c374a/napari/utils/events/containers/_evented_dict.py#L9) is created but not documented or emitted:

https://github.com/napari/napari/blob/8c307022cc557692409f5e8bc031f1dcde4c374a/napari/utils/events/containers/_evented_dict.py#L75-L77

It seems not to be missed, should it be added?

**Comment by Czaki** [comment]
The code part you show in Issue is the emission of the event. So only there is a lack of documentation?

**Comment by lucyleeow** [comment]
It emits `changed` but not `changing`?

**Comment by Czaki** [comment]
ah. 100% true. Why I do not notice this difference.

**Comment by lucyleeow** [comment]
I am happy to open a PR to fix this, just wanted to check that we want to add `changing` ?
