### ISSUE TITLE
Repo cleanup on github and pypi

### ISSUE THREAD

**Issue by royerloic** [napari/napari#595]
## 🐛 Not a bug but a cleanup request

We have some stall repos and packages on github and pypi.
pypi: napari-gui
github: image-types, plugin-cookiecutter,  ...

I think it would be great to clean that up and for example delete
napari-gui so as to avoid confusion and in general clutter... 
 
We can discuss here what can be deleted or somehow archived.
Perhaps we could have an archive repo on github  to keep old
unused code, i.e. some of Kira's  original plugin machinery for 
reference and future use. This is better than having repos that
appear legit to newcomers but are in fact completely stale. An 
archive repo would be a very explicit place to retire such old
stuff while keeping them for future reference.

**Comment by AhmetCanSolak** [comment]
related to this, we should be cleaning branches on napari repo as well

**Comment by jni** [comment]
`image-types` is experimental but not deprecated...

We could move some of these to people's personal accounts, including `image-types`...

**Comment by sofroniewn** [comment]
I don't have access rights to our old https://pypi.org/project/napari-gui/ - @jni is there a way to archive that?

**Comment by sofroniewn** [comment]
Can we also maybe clean-up / organize the number of files we have at the top level directory - for example can we maybe put all our `CAPS_LOCK.md` files apart from `README.md` into a folder in `docs`? Maybe our `LICENSE` can go in there too? Maybe `generate_release_notes.py` can also find another home? Maybe our `.github` folder with our templates we can also put inside `docs` and drop the `.` from?

I just feel when people arrive now they have to scroll quite a lot to get to our the actual readme, and the number of files at the top level might be intimidating

**Comment by AhmetCanSolak** [comment]
I partially agree @sofroniewn . I think `README.md` and `LICENSE` should stay at root but for rest we can find new homes.

About `.github` folder i think github has a hook specifically with that name. I am not sure if we can drop the `.`.

**Comment by AhmetCanSolak** [comment]
I achieved repos that i found unused. Please do check, if there are no complaints, i can delete those.

**Comment by jni** [comment]
I'm ok with deleting those, but imho we should wait for @kne42 to be back to get her go ahead. She did a lot of that early work and might like to have a copy of it. If you want to do the cleanup urgently, you could create a new org, eg `napari-archive`, and transfer ownership of those repos to that.

**Comment by sofroniewn** [comment]
yeah, let's wait. I think no need for the new org right now, might only lead to more confusion. I don't see it as that urgent.

The one repo I might make an exception for is `napari-app` because the only thing on there is a PR from @jni. Do you agree @jni?

**Comment by jni** [comment]
Oh yeah, nuke that sucker! =P

**Comment by sofroniewn** [comment]
i just deleted `napari-app`. @jni has deleted `napari-gui` from PyPi.

let's leave this open till I rearrange our docs files as discussed with @AhmetCanSolak
