### ISSUE TITLE
add_* methods accept file paths / urls to data

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#596]
## 🚀 Feature
As we start adding more fileIO should our `napari.view_*` methods and `viewer.add_*` methods start accepting paths and lists of paths to data as well as the data objects themselves.

We'd use the same machinery for fileIO from the dropdown menu, but now someone could leverage that functionality from a script. 

```python
napari.view_image('path_to_astro.png', rgb=True)
```

Would be pretty cool (note that this file IO would not go inside the Image Model files it would get called from inside the viewer file, keeping our models clean). I really like that this would unify fileIO for each of our layer types with its layer type, and it then makes it more clear where to add fileIO functionality when you add a layer type, and simplify our dropdown menu / drag and drop functionality as they only now need to be responsible to providing the correct path / list of paths to the correct `add_*` method and the rest will get handled from inside that method exactly the same regardless of where the data came from.

This will also make it really easy to support viewing of remote datasets, for example I want to be able to run

```python
napari.view_image('s3://my_bucket/path_to_image.zarr', colormap='red)
```

to just view my remote data on s3. We can then also keep track of this path and that the data was remote so that we serialize the viewer we just save this path, so if I send you the serialized `.napari` file it will be really small and you can just open it and see exactly what I saw, which is what was requested in #234 and will be pretty cool functionality for people working with remote data.

What are your thoughts on this @jni?

**Comment by jni** [comment]
I'm not super in love with this idea... In the end in scikit-image we found that allowing the same parameter to take lots of different types is generally a bad idea, as it leads to a lot of increased complexity, and consequent brittleness. When we do want to do this for convenience, I think it's best to contain it, so I would try to keep all this magic within `io.magic_read`. 

So, I'd need to be convinced that the benefits outweigh the long-term maintenance costs, which are substantial.

The viewer serialization application is very cool, but I wonder if it can be implemented in some less magical way, e.g. `layer.data_path = path` (Which is what you would do internally anyway I believe...?

**Comment by sofroniewn** [comment]
Ok, I appreciate your concerns about the complexity and maintenance burden - for example right now with all our existing layer types it is fairly unambiguous if a string is an image array or a file path, but as soon as we have a text layer is that a string that is the string of text we want to display, or is it a path to a csv file of text that we want to display. Or maybe even in the image case someone has an image as a string of bytes that needs to be converted etc.

However, I still really like the idea of being able to add data from files for all our different layers in one line, and I still like having the file IO for each layer live within that layer.

How would this work as an api
```python
napari.view_image(path='path_to_my_data.png')
viewer.add_image(path='s3://my_bucket/my_image.zarr')
viewer.add_shapes(path='path_to_my_shapes.csv')
```
where we now for the user to use the keyword argument `path` (at which point they should no longer provide the unnamed data argument, and we through an error if they do)

How does @royerloic feel about all this?

**Comment by freeman-lab** [comment]
i really like the `path` option -- agree it would be nice to have this, but agree with @jni 's concerns, so that seems like a clean solution!

**Comment by jni** [comment]
I second @freeman-lab! Great solution, @sofroniewn! :clap: 

> how would this work as an api

Well, the first line is a syntax error, but other than that, genius! :joy:

**Comment by royerloic** [comment]
I approve. Very nice approach. I see no issues.

**Comment by sofroniewn** [comment]
Support has now been provided for images and will be rolled out to other layer types as appropriate. We still might want to add chaching with dask where appropriate. We also might want to unify fileIO from the CLI, and we might need to still expose some more of the `magic_imread` keyword args

**Comment by sofroniewn** [comment]
we still have to extend support to our other layer types, but as the basics are now in I will close this issue
