### ISSUE TITLE
Napari progress throws AttributeError if a description is set and it is disabled

### ISSUE THREAD

**Issue by constantinpape** [napari/napari#5961]
## 🐛 Bug

`napari.utils.progress` throws an `AttributeError` if a description is set and it is disabled. This works in `tqdm`.

## To Reproduce

To reproduce it:
```python
# from tqdm import tqdm
from napari.utils import progress as tqdm

for z in tqdm(range(10), total=10, desc="Count to 10", disable=True):
    pass
```
This fails with:
```
Traceback (most recent call last):
  File "/home/pape/Work/playground/napari-prog/progress_napari.py", line 6, in <module>
    for z in tqdm(range(10), total=10, desc="Count to 10 again", disable=True):
  File "/home/pape/software/conda/miniconda3/envs/sam/lib/python3.10/site-packages/napari/utils/progress.py", line 88, in __init__
    if not self.desc:
AttributeError: 'progress' object has no attribute 'desc'
```
It works when using normal `tqdm`.

## Expected behavior

The code should not throw the exception.

## Environment

The napari and tqdm versions are (omitting the rest because irrelevant):
- napari                    0.4.17          pyh275ddea_0_pyqt    conda-forge
- tqdm                      4.65.0             pyhd8ed1ab_1    conda-forge

## Additional context

This should be easy to fix [here](https://github.com/napari/napari/blob/main/napari/utils/progress.py#L88).
For example, one could add the lines
```python
if self.disable:
  self.desc = ""
```
beforehand. I checked that locally and it fixes the issue.

I am happy to open a PR for this.

**Comment by DragaDoncila** [comment]
@constantinpape thanks for raising! I think your identified fix is correct, so please feel free to open the PR :blush:
