### ISSUE TITLE
[main, macOS] post-5432 (VispyCanvas), canvas.background isn't initialized properly

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari/napari#5969]
## 🐛 Bug

#5432 (love git bisect) has introduced a bug where a new viewer made with Light theme gets a black canvas background. However, toggling to `light` sets the background correctly to white.

## To Reproduce

1. Set `light` theme in Preferences.
2. Open a new viewer in light theme
3. make empty labels layer -> see black canvas in light viewer

If you toggle the theme to dark/system and back to light using `viewer.theme = 'light'` it will show correct white canvas.

## Expected behavior

The canvas of new viewer should respect theme settings.

## Environment

```
napari: 0.5.0a2.dev188+gefa55a5b
Platform: macOS-13.3.1-arm64-arm-64bit
System: MacOS 13.3.1
Python: 3.10.10 | packaged by conda-forge | (main, Mar 24 2023, 20:12:31) [Clang 14.0.6 ]
Qt: 5.15.6
PyQt5: 5.15.7
NumPy: 1.24.3
SciPy: 1.10.1
Dask: 2023.4.1
VisPy: 0.13.0
magicgui: 0.7.2
superqt: unknown
in-n-out: 0.1.7
app-model: 0.1.4
npe2: 0.7.1.dev2+gb33bc09

OpenGL:
- GL version: 2.1 Metal - 83.1
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1680x1050, scale 2.0

Settings path:
- /Users/piotrsobolewski/Library/Application Support/napari/napari-dev_a1eb8b76ba95fa16ad06e26097b46b8455dfbf0b/settings.yaml

```

## Additional context

this is on macOS, happens with `system` during the day too. Sorry I missed it!

**Comment by melonora** [comment]
I will pick it up

**Comment by psobolewskiPhD** [comment]
Looks like in the __init__ of VispyCanvas `self.bgcolor` isn't set to anything.
Adding: 
```
self.bgcolor = transform_color(
            get_theme(self.viewer.theme, False).canvas.as_hex()
        )[0]
```
(and the import) fixes the issue on my end.
I can make a PR if you think that's fine.
