### ISSUE TITLE
Add qtpy information and Qt naming convention to contributing guide

### ISSUE THREAD

**Issue by kne42** [napari/napari#6]
All classes inherited from PyQt should follow the same naming conventions as C (which Qt is written in): TitleCase for class names and camelCase for variables & functions/methods.

**Comment by sofroniewn** [comment]
@kne42 do you want to either address this or close it? I'm very open to the standardization and think now's a good time to do it, but I don't quite know if I'd get it done correctly. You could probably just go through both the `_qt` and `_vispy` folders and get it done.

**Comment by sofroniewn** [comment]
@goanpeca @tlambert03 curious your thoughts on this. Is this something that still makes sense? Something we still want to do?

**Comment by goanpeca** [comment]
I am fine with whatever the convention we decide on, it seems we are mostly using python usual convention even if it extends PyQt things 🤷🏼.

**Comment by tlambert03** [comment]
Yeah, I would have stronger feelings if this were a public api.  Otherwise, not too terribly concerned

**Comment by goanpeca** [comment]
So, from the code I have worked on, it seems the convention is, we used python conventions everywhere, unless we need to override a method.

So maybe we would need to (eventually) update some method names from camelcase to python case and some signal names.

I suggest we update docs to inform and settle that any code moving forward should follow python conventions unless we do overrides (methods, basically).

Something we used over at [spyder](https://github.com/spyder-ide/spyder/wiki/Dev%3A-Coding-Style) to make it easier to discover (autocomple and refactors) and update was to prefix custom signals with `sig_`

**Comment by sofroniewn** [comment]
> I suggest we update docs to inform and settle that any code moving forward should follow python conventions unless we do overrides.

This seems like a reasonable approach. I was actually just looking through our [contributing guide](https://github.com/napari/napari/blob/master/docs/developers/contributing.md) and couldn't find any section on qtpy/ qt at all. We have some stuff about PySide2/ PyQt5 in our installation instructions https://napari.org/index.html?highlight=pyside2#from-source, but maybe we just add a small section like

```
# Qt and qtpy
napari needs a library called Qt to run its user interface (UI). In Python, there are two alternative libraries to run this, called PyQt5 and PySide2. By default, we don’t choose for you, and instead use the library qtpy which supports both.

All qt related imports should therefore come from qtpy and not PyQt5 or PySide2 directly, for example ....
[INSERT EXAMPLE]

Additionally when creating custom classes which inherit from qtpy classes we should follow ...
[INSERT STUFF ABOUT NAMING CONVENTION]
```

How does this sound? Obviously above is just meant to be illustrative, but i've definitely seen people start PRs only using PyQt5 imports so having one place where all this is listed seems good.

Maybe one day we write a more general code style guide, but i think this is a good place to start.

**Comment by sofroniewn** [comment]
We now have some information about qtpy in our plugin best practices - see https://napari.org/plugins/best_practices.html?highlight=qtpy#don-t-include-pyside2-or-pyqt5-in-your-plugin-s-dependencies

I think that's probably sufficient such that we can close this issue. I will do so soon unless I hear otherwise
