### ISSUE TITLE
PERFORMANCE: Shuffle label colors function slow for big images

### ISSUE THREAD

**Issue by GenevieveBuckley** [napari/napari#6010]
> For what it's worth, I just tried with a (3, 15000, 15000) image layer and labels on top using napari from `main` and napari 0.4.18rc1.
Making the layers (numpy random.rand) took some time, but painting was totally lag free and performant. The only performance issue I noticed was clicking the shuffle button. Incrementing labels was fast, but shuffle had a lag.

_Originally posted by @psobolewskiPhD in https://github.com/napari/napari/issues/569#issuecomment-1604755537_

**Comment by jni** [comment]
Should be closed or at any rate improved ~5x by #3308. (I know, I know...)

```
In [1]: image = np.random.randint(0, 15, size=(15000, 15000))

In [2]: %timeit image.astype(np.float32)
920 ms ± 241 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [5]: from napari.utils.colormaps.colormap_utils import low_discrepancy_image

In [6]: %timeit low_discrepancy_image(image)
4.77 s ± 345 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
