### ISSUE TITLE
No option to select a given contribution from a plugin in 0.4.18rc2

### ISSUE THREAD

**Issue by adamltyson** [napari/napari#6012]
## 🐛 Bug

In napari 0.4.18rc2 there is no option to select a specific contribution from a plugin. In our case, this is needed to load a directory one of two ways (in two coordinate systems). This was posted on zulip, and I'm raising an issue upon @Czaki's request.

## To Reproduce
In napari <= 0.4.17, I can open data using a specific reader from [brainglobe-napari-io](https://github.com/brainglobe/brainglobe-napari-io):

```python
viewer.open(file, plugin="brainglobe-napari-io.brainreg_read_dir_standard_space")
```
In napari 0.4.18rc2 this produces the error:

```bash
ValueError: There is no registered plugin named 'brainglobe-napari-io.brainreg_read_dir_standard_space'.
Names of plugins offering readers are: set()
```

## Expected behavior

For the data to be loaded with a specific reader as with previous versions. 

## Environment

<details>
  <summary>napari info</summary>
  
napari: 0.4.18rc2
Platform: Linux-5.15.0-75-generic-x86_64-with-glibc2.31
System: Ubuntu 20.04.6 LTS
Python: 3.10.11 | packaged by conda-forge | (main, May 10 2023, 18:58:44) [GCC 11.3.0]
Qt: 5.15.2
PyQt5: 5.15.9
NumPy: 1.24.3
SciPy: 1.10.1
Dask: 2023.5.1
VisPy: 0.12.2
magicgui: 0.7.2
superqt: unknown
in-n-out: 0.1.7
app-model: 0.1.4
npe2: 0.7.0

OpenGL:
- GL version: 4.6.0 NVIDIA 515.105.01
- MAX_TEXTURE_SIZE: 32768

Screens:
- screen 1: resolution 3440x1440, scale 1.0

Settings path:
- /home/adam/.config/napari/brainglobe_eaa3f9e4140a9304dcb5c8fb309cc49886dc0b64/settings.yaml
</details>

## Additional context
A workaround would be much appreciated, otherwise I think we'd need to maintain multiple plugins?

**Comment by psobolewskiPhD** [comment]
The behavior from the OP was broken by #5739 
I've made a PR to fix that regression: #6013
