### ISSUE TITLE
Circular import error trying to run napari.Viewer()

### ISSUE THREAD

**Issue by philipqueen** [napari/napari#6015]
## 🐛 Bug

I am getting a circular import error that does not let me run Napari through a script. I am able to run the app, and from the python interpreter `>>> import napiri >>> viewer = napari.Viewer()`. But trying to run from a file leads to the `partially initialized module 'napari' has no attribute 'Viewer'` error below. The code I'm running seems to be the minimal code to run via script from the tutorial in the documentation.

## To Reproduce

Code I'm running to produce the error:
```import napari

viewer = napari.Viewer()

napari.run()
```

The error I'm getting:

```pytb
Traceback (most recent call last):
  File "/Users/username/Documents/GitHub/poseable/poseable/gui/napari/napari.py", line 1, in <module>
    import napari
  File "/Users/username/Documents/GitHub/poseable/poseable/gui/napari/napari.py", line 3, in <module>
    viewer = napari.Viewer()
AttributeError: partially initialized module 'napari' has no attribute 'Viewer' (most likely due to a circular import)
```

## Expected behavior

The code runs well and a nice gui shows up.

## Environment

 - Please copy and paste the information at napari info option in help menubar here:

```
napari: 0.4.17
Platform: macOS-12.6.2-arm64-i386-64bit
System: MacOS 12.6.2
Python: 3.9.16 (main, May 16 2023, 14:27:50) [Clang 14.0.6 ]
Qt: 6.5.1
PyQt6: 
NumPy: 1.25.0
SciPy: 1.11.0
Dask: 2023.6.1
VisPy: 0.11.0
magicgui: 0.7.2
superqt: unknown
in-n-out: 0.1.7
app-model: 0.1.4
npe2: 0.7.0

OpenGL:
- GL version: 2.1 Metal - 76.3
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1512x982, scale 2.0
```

 - Any other relevant information:

I've tried installing napari with `pip install napari` and `pip install "napari[pyqt6_experimental]"` and both are giving the same behavior. I'm not able to get `pip install "napari[all]"` to work because I cannot pip install pyqt5

**Comment by jni** [comment]
> Expected behavior
> 
> The code runs well and a nice gui shows up.

😂 

I've run into this issue myself, so don't feel bad, but the issue is here:

> "/Users/username/Documents/GitHub/poseable/poseable/gui/napari/napari.py"

Your file is called `napari.py` and by default, Python checks the local directory for files to import, so it tries to import napari.py from napari.py, and you get a time paradox. 😜  So the solution is to rename your file! Suggestion: `not_actually_napari.py`. 😜 

I hope this helps and do let us know if you run into other issues! 🙏

**Comment by philipqueen** [comment]
Wow, that's painful to realize haha, thanks for the help though!
