### ISSUE TITLE
Alternative value normalization for colormap (e.g. log-scale colors)

### ISSUE THREAD

**Issue by kephale** [napari/napari#6045]
## 🚀 Feature

Matplotlib supports value normalization when colormapping: https://matplotlib.org/stable/tutorials/colors/colormapnorms.html

However, napari does not have support for custom value normalization when colormapping.

## Motivation

This can be particularly useful when performing a log-scale normalization. In the following images you can see a Tweet where the authors are displaying a turbulence simulation and using a log-scale to normalize values. It looks significantly better than my attempt (second image) to display the same data without log-scaling.

This is the tweet https://twitter.com/CFDonia/status/1657043268364902403 (duplicated here so everyone can see it)
<img width="654" alt="image" src="https://github.com/napari/napari/assets/400105/a553e607-27fe-485a-bf62-95ec68d9dbd3">

This is what it looks like currently in napari without normalizing values for colormaps:

<img width="1429" alt="image" src="https://github.com/napari/napari/assets/400105/055f7fec-954a-4d97-9d6f-eeda18b4016b">

## Pitch

It would be great to support some kind of value normalization, but I also recognize this can be a costly operation depending on the data size. We could possibly do this on the fly with Dask array.

## Example

You can run this example with:

However, please note that this is using a Dropbox link from the Tweet's author. I do have a hash for checking file validity, but the file could disappear sometime in the future.

```
import pooch

import napari

from netCDF4 import Dataset

dest_path = pooch.retrieve(
    url="https://www.dropbox.com/s/dl/6olaesnuxjnjzk3/turb2d16x8fs.nc",
    known_hash="25e8af3c8685b844fbac43ee48aa6ece523b090f6932ff11ce50ea4c6c911983",
)

f1=Dataset(dest_path, mode='r')
dissipation = f1.variables['dissipation'][:,:,:]
x = f1.variables['x'][:]
y = f1.variables['y'][:]

viewer = napari.Viewer()

viewer.add_image(dissipation, colormap='twilight_shifted', contrast_limits=[9.059638017561156e-08, 0.08985517825714297])
```

**Comment by Czaki** [comment]
Changing the value of gamma is not enough for this use case?

**Comment by kephale** [comment]
Yes it is! 😊 

<img width="1428" alt="image" src="https://github.com/napari/napari/assets/400105/a07f72c9-ca13-4417-85e8-f7224a6f241a">
