### ISSUE TITLE
Two `get_app` functions

### ISSUE THREAD

**Issue by lucyleeow** [napari/napari#6054]
With the app-model migration we have two `get_apps`, one for creating `QApplication` and one for app-model Application. It is confusing and it would be good to change, as mentioned here: https://github.com/napari/napari/pull/4826/files#r942725034

We could rename `_qt.get_app` to `get_qapp` but it is publicly exported. I guess `NapariApplication.get_app` is also public but is newer and may not have many users.

This is a TODO in #4860 but thought it would be worthwhile to discuss in a new issue.

cc @DragaDoncila

**Comment by lucyleeow** [comment]
@Czaki maybe you have an opinion on this?

**Comment by Czaki** [comment]
I think that we should separate them. I also do not know why `NapariApplication.get_app` is public, But I do not deeply dive in this code.

**Comment by lucyleeow** [comment]
Yes good point. Would the `NapariApplication` be useful for plugins to contribute to menus etc @DragaDoncila . Maybe it would be best to change the name of this one?

**Comment by Czaki** [comment]
> Would the `NapariApplication` be useful for plugins to contribute to menus etc @DragaDoncila

No. A plugin should contribute to menus via manifest file. As plugin is loaded on demand and there is no mechanism for updating the menu based on AppModel after the window is created.

**Comment by lucyleeow** [comment]
Yes good point. It seems the best option would be to rename `NapariApplication.get_app`; maybe `get_app_model`? 

Will wait to see if any objections then make PR to change.

**Comment by Czaki** [comment]
> to rename `NapariApplication.get_app`; maybe `get_app_model`?

app model is the name of the package. maybe `get_abstract_model`?

**Comment by lucyleeow** [comment]
Yes no problem, I don't mind what it gets changed to. `NapariApplication` inherits from [`Application`](https://github.com/pyapp-kit/app-model/blob/ee121c6c02bc2a29b16c94085d465c7e8c141ace/src/app_model/_app.py#L21) which is apparently a 'Full application model'. Just a question, why 'abstract' ?

**Comment by Czaki** [comment]
Hm. At this moment is is not full application model, but it may be in future. maybe `get_model`?

**Comment by lucyleeow** [comment]
Would that be confusing due to all the other 'models' we have https://github.com/search?q=repo%3Anapari%2Fnapari%20model&type=code ?

**Comment by lucyleeow** [comment]
Talley had suggested:

>  rename `_qt.get_app` to `get_qapp`... however that's publicly exported, and that needs to be considered

note both are public. I think `app_model.get_app` may be public to allow users to add `Action`s are runtime.

What about changing  `app_model.get_app` to `get_application_model` ?

ping @jni @DragaDoncila @Czaki

**Comment by DragaDoncila** [comment]
I think it should be `get_qapp` and `get_app` :woman_shrugging: I would be surprised if either are used all that frequently outside of internal stuff...

**Comment by jni** [comment]
I agree with @DragaDoncila's comment. Let's deprecate our `get_app` and rename it to `get_qapp`.

**Comment by lucyleeow** [comment]
Yes maybe a warning of some sort. Okay excellent, i have enough to proceed. Thanks all

**Comment by lucyleeow** [comment]
Re-visiting this. I think we have agreement:

* `napari._qt.qt_event_loop.get_app` should be `get_qapp` - note this is public API
* `napari._app_model.get_app` should be `get_app` 

With regard to deprecation of `napari._qt.qt_event_loop.get_app`; do want to go through a deprecation cycle where we support `get_qapp` and `get_app` and warn users who use `get_app`? I think no because this function is probably not widely used, and napari is technically alpha.. Open to other opinions though.

I do agree with https://github.com/napari/napari/issues/6054#issuecomment-1993744096 in that it would be nice to add a warning to `napari._app_model.get_app`, telling them that they are getting a `NapariApplication` not a qapp.

Note we probably need to amend any examples that use the old `get_app` (would probably be nice to do a search in the napari org of `get_app` uses, maybe we use it in a cookiecutter etc?)

cc @Czaki @DragaDoncila @jni

**Comment by Czaki** [comment]
We may even decide to change the first `get_app` to `get_app_model` and the second `get_app` to `get_qapp` to make fully distinguish? Then we could have deprecation warning in both original `get_app`.

**Comment by lucyleeow** [comment]
> We may even decide to change the first get_app to get_app_model

I suggested this above but you said: https://github.com/napari/napari/issues/6054#issuecomment-1635368054 :sweat_smile: 

I do understand that `app-model` is the name of the package, and `get_app_model` is less clear that you are getting a 'app'/application. What I usually say when I am trying to distinguish it is 'app-model app'.

I think I would prefer `get_app` but I am okay either way.

Aside, @DragaDoncila also raised a good point that it would be worthwhile investigating how widely `napari._qt.qt_event_loop.get_app` is (maybe github wide search..?), to guide us on how we deprecate.

**Comment by Czaki** [comment]
But `get_app` from app-model does not return the whole app. It returns only model (for example model from split Model-View-Controler https://en.wikipedia.org/wiki/Model%E2%80%93view%E2%80%93controller).

**Comment by lucyleeow** [comment]
What do you mean by 'whole app' ?

**Comment by Czaki** [comment]
It does not return an object that represents the whole Application (you cannot control the viewer through it). It only returns some models (not even full) so I do not see a problem with using `get_app_model()`

**Comment by lucyleeow** [comment]
Ahhh I see now. I did not realise that was what application meant, I was just going off the nomenclature used in app-model/napari, i.e.,: `NapariApplication(Appilication)`

I guess it makes more sense then but I am okay either way.
