### ISSUE TITLE
[Qt6, PyQt6] AttributeError: type object 'QFileDialog' has no attribute 'Options'

### ISSUE THREAD

**Issue by jeylau** [napari/napari#6060]
## 🐛 Bug

The dialog to load a folder fails to open.

## To Reproduce

1. Open napari
2. Hit File > Open Folder...

```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
File ~/miniconda/envs/napari-dlc/lib/python3.10/site-packages/napari/_qt/qt_viewer.py:910, in QtViewer._open_folder_dialog(self=<napari._qt.qt_viewer.QtViewer object>, choose_plugin=False)
    900 hist = get_open_history()
    901 dlg.setHistory(hist)
    903 folder = dlg.getExistingDirectory(
    904     self,
    905     trans._('Select folder...'),
    906     hist[0],  # home dir by default
    907     (
    908         QFileDialog.DontUseNativeDialog
    909         if in_ipython()
--> 910         else QFileDialog.Options()
        dlg = <PyQt6.QtWidgets.QFileDialog object at 0x288e3dcf0>
        self = <napari._qt.qt_viewer.QtViewer object at 0x284db70a0>
        trans = <napari.utils.translations.TranslationBundle object at 0x1309850c0>
        hist = ['/Users/jessy']
        hist[0] = '/Users/jessy'
        QFileDialog = <class 'PyQt6.QtWidgets.QFileDialog'>
        QFileDialog.DontUseNativeDialog = <Option.DontUseNativeDialog: 8>
    911     ),
    912 )
    914 if folder not in {'', None}:
    915     self._qt_open([folder], stack=False, choose_plugin=choose_plugin)

AttributeError: type object 'QFileDialog' has no attribute 'Options'
```

## Expected behavior

The dialog window opens.

## Environment

napari==0.4.18
PyQt6==6.5.1

**Comment by psobolewskiPhD** [comment]
Thanks for reporting, can you just clarify the env? Also what platform are you on? 
The traceback shows PyQt6, but you listed pyside6. Can you confirm the Qt framework and version?
Could you post the output of `napari --info`?

I can reproduce with PyQt 6.5.1 on my macOS 13.3.1 arm64.

FYI: At the moment, Qt6 support is experimental, with some known issues on pyside6, so definitely appreciate the reporting!!

**Comment by jeylau** [comment]
My bad, it was indeed pyqt6==6.5.1.

`napari --info` gives:
```python
napari: 0.4.18
Platform: macOS-13.3.1-arm64-arm-64bit
System: MacOS 13.3.1
Python: 3.10.9 (main, Jan 11 2023, 09:18:18) [Clang 14.0.6 ]
Qt: 6.5.1
PyQt6: 
NumPy: 1.23.5
SciPy: 1.10.1
Dask: 2023.4.0
VisPy: 0.12.2
magicgui: 0.7.2
superqt: unknown
in-n-out: 0.1.7
app-model: 0.1.4
npe2: 0.7.0

OpenGL:
  - GL version:  2.1 Metal - 83.1
  - MAX_TEXTURE_SIZE: 16384

Screens:
  - screen 1: resolution 1920x1080, scale 1.0

Settings path:
  - /Users/jessy/Library/Application Support/napari/napari-dlc_2303f874d85cdd83941274a5b0fae04a98b410a5/settings.yaml
Plugins:
  - napari: 0.4.18 (77 contributions)
  - napari-console: 0.0.8 (0 contributions)
  - napari-deeplabcut: 0.1.3.dev19+gf7b279a.d20230712 (16 contributions)
  - napari-svg: 0.1.10 (2 contributions)
```

**Comment by psobolewskiPhD** [comment]
I think this can be fixed in similar fashion to Open File fix from https://github.com/napari/napari/pull/5492
I will make a PR.

**Comment by kimiaf1998** [comment]
I have the same issue but for saving the layers.
I am using the same version of pyqt6 and napari:

napari==0.4.18
PyQt6==6.5.1

`AttributeError: type object 'QFileDialog' has no attribute 'Options'
`

`---> 73         'slot': lambda: window._qt_viewer._save_layers_dialog(
        trans = <napari.utils.translations.TranslationBundle object at 0x12913e5f0>
        window = <napari._qt.qt_main_window.Window object at 0x29b5525f0>
        QAction.PreferencesRole = <MenuRole.PreferencesRole: 5>
        QAction = <class 'PyQt6.QtGui.QAction'>
        window._qt_window = <napari._qt.qt_main_window._QtMainWindow object at 0x29b7cf880>
        QAction.QuitRole = <MenuRole.QuitRole: 6>
     74             selected=True
     75         ),
     76         'shortcut': 'Ctrl+S',
`
@psobolewskiPhD

**Comment by psobolewskiPhD** [comment]
Ah, yup, thanks!
I just confirm, the Save layer and Save all layers are also broken.
But screenshots work.

**Comment by psobolewskiPhD** [comment]
With the latest qtpy: https://github.com/spyder-ide/qtpy/releases/tag/v2.4.0
this is fixed!
A just did a `pip install "napari[pyqt6_experimental]" in a fresh env and everything seems to work.
You can try `pip install qtpy -U` to update in place in your env.
