### ISSUE TITLE
Stop automatically highlighting "added" points on set_data

### ISSUE THREAD

**Issue by jni** [napari/napari#6064]
## 🐛 Bug

Currently when we set the data of a points layer, if the new data has more points than the previous data, then the additional points get selected automatically and highlighted. This can be very harmful to a visualisation because the highlight is very distracting and totally unrelated to the data. In many situations, the points are actually a completely different set of points, so highlighting the last few is completely nonsensical — they are not the "new" points, all the points were new.

## To Reproduce

```python
import numpy as np
import napari
from magicgui import magicgui


viewer = napari.Viewer(ndisplay=3)

@magicgui(
    auto_call=True,
    x={'widget_type': 'Slider', 'min': 0, 'max': 5000}
)
def get_pts(x=2500) -> napari.types.LayerDataTuple:
    npoints = np.random.randint(900, 1100)
    data_raw = np.random.random((npoints, 3))
    data = data_raw[np.lexsort(data_raw.T)]
    return (
        data * 255,
        {'size': 2, 'name': 'pts', 'shading': 'spherical'},
        'points',
    )

w = viewer.window.add_dock_widget(get_pts, area='bottom')
_ = get_pts()  # call once to create the layer

napari.run()
```

https://github.com/napari/napari/assets/492549/dd49c2c3-ca94-41e2-a559-85dfb6a0fd04

## Expected behavior

Points should not be selected on setting data.

CC @francescalted

**Comment by jni** [comment]
Thanks @andy-sweet! I think indeed 1 is the desired behaviour. Maybe we can fix this one this week. 😃

**Comment by kevinyamauchi** [comment]
I agree, approach 1 is the way to go!

**Comment by andy-sweet** [comment]
Assigned to me, but delegating to @akuten1298

**Comment by akuten1298** [comment]
Hi, I've raised a PR for this fix https://github.com/napari/napari/pull/6098. Please take a look and give your feedback when you find time, thank you :)
