### ISSUE TITLE
[Bug, Labels, multiscale] Thumbnail doesn't handle multiscale properly 

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari/napari#6069]
## 🐛 Bug

When zooming on a multiscale labels image, the thumbnail will start to show the zoomed view of the canvas, then snap back to the whole canvas. 

https://github.com/napari/napari/assets/76622105/5b868868-f2d4-42ed-ac91-961e366ff219

Also, this only happens on main 9bea15e7b89156654ae02c3dc3144d6fc244aab3
not on 0.4.18 where the thumbnail shows the zoomed out, whole layer view the whole time (as expected, see: https://github.com/napari/napari/issues/6069#issuecomment-1642189439

## To Reproduce

Use this snippet and then zoom in on an edge:
```
import napari
import numpy as np
from skimage.draw import disk

# Draw a curved segmentation with a label value greater 1. Due to varying boundary 
# direction, incorrect downsampling will produce a range of intensity values.
label_image_0 = np.zeros((2048, 2048), dtype=np.uint)
label_image_0[disk(center=(1024, 1024), radius=1000)] = 10
label_image_1 = np.zeros((1024, 1024), dtype=np.uint)
label_image_1[disk(center=(512, 512), radius=500)] = 10
pyramid = [label_image_0, label_image_1]
viewer.add_labels(pyramid, name="label_image")
```

## Expected behavior

The thumbnail should represent the whole canvas, regardless of multiscale.

## Environment

napari: 0.5.0a2.dev233+gb8f9eba2.d20230717
Platform: macOS-13.3.1-arm64-arm-64bit
System: MacOS 13.3.1
Python: 3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:41:52) [Clang 15.0.7 ]
Qt: 6.5.1
PyQt6: 
NumPy: 1.25.1
SciPy: 1.11.1
Dask: 2023.7.0
VisPy: 0.12.2
magicgui: 0.7.2
superqt: unknown
in-n-out: 0.1.8
app-model: 0.2.0
npe2: 0.7.1

OpenGL:
- GL version: 2.1 Metal - 83.1
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1680x1050, scale 2.0

Settings path:
- /Users/piotrsobolewski/Library/Application Support/napari/nap-test-pyqt6_2571d0498f7729f0590a4f0b6f8684e2bbc2a79b/settings.yaml

**Comment by psobolewskiPhD** [comment]
Ah, yeah ok it makes sense the thumbnail gives a preview of the whole canvas—basically zoomed out. I never noticed I guess? 😊 
But with the multiscale, it shows the zoomed, then swaps to whole:

https://github.com/napari/napari/assets/76622105/dd1de961-f4ba-4640-9663-adc51bd25f1b

This doesn't happen with a normal, non-multiscale labels layer.

So there is a bug here, but not exactly the bug I put in the OP! I will edit for clarity shortly.

**Comment by andy-sweet** [comment]
Ooh fun! Thanks for clarifying with the video!

**Comment by andy-sweet** [comment]
I was a little too aggressive on the optimization here: https://github.com/napari/napari/blob/1c57d36d92b6efa60d34863b8ad16fef324754d8/napari/layers/image/_slice.py#L240

Given that the thumbnail should represent the whole canvas, we can't just reuse the image when the levels match because the image is cropped by the FOV. Should be an easy enough fix.
