### ISSUE TITLE
Keyboard shortcut for opening folders doesn't work

### ISSUE THREAD

**Issue by jni** [napari/napari#608]
## 🐛 Bug

This might be my fault, and can't investigate now, but:

<img width="227" alt="Screen Shot 2019-10-21 at 10 27 36 am" src="https://user-images.githubusercontent.com/492549/67168194-91c64680-f3ed-11e9-83de-d88493436234.png">

It's supposed to be Ctrl/Cmd-Shift-O.

## To Reproduce

1.
2.
3.

## Environment

 - Please copy and paste the information at napari info option in help menubar here:

 - Any other relevant information:

**Comment by sofroniewn** [comment]
I'll address this in the PR I'm working on for #604

**Comment by sofroniewn** [comment]
This has now been fixed in #943
