### ISSUE TITLE
Label colors for labels above 2**23 can be aliased together

### ISSUE THREAD

**Issue by jni** [napari/napari#6084]
## 🐛 Bug

#3308 closed *many* existing issues with our labels layers, but opened at least one: because now labels are converted to float32, any adjacent labels above 2**22 will land on the same color (and this problem becomes worse as the label values increase).

## To Reproduce

```python
import numpy as np
import napari

labels = 2**np.arange(21, 25).reshape((4, 1)) + np.arange(8)
viewer = napari.Viewer()
viewer.add_labels(labels)

napari.run()
```

<img width="1189" alt="Screenshot 2023-07-24 at 10 11 54 am" src="https://github.com/napari/napari/assets/492549/710715a0-7f57-4154-95b7-dd0fd6cc5740">

This problem is fundamental to the way the numbers are represented in float32 so it persists no matter how many times a user might click on the "shuffle colors" button. (Good resources about this: https://0.30000000000000004.com/ and Julia Evans's [how integers and floats work](https://jvns.ca/blog/2023/06/23/new-zine--how-integers-and-floats-work/).)

## Expected behavior

Distinct labels should be able to display as distinct colors.

## Environment

```
napari: 0.5.0a2.dev232+g9bea15e7b.d20230713
Platform: macOS-13.4-arm64-arm-64bit
System: MacOS 13.4
Python: 3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:25:13) [Clang 14.0.6 ]
Qt: 5.15.4
PyQt5: 5.15.7
NumPy: 1.23.4
SciPy: 1.11.1
Dask: 2023.3.1+13.g4b1e3600.dirty
VisPy: 0.12.1
magicgui: 0.7.2
superqt: unknown
in-n-out: 0.1.5
app-model: 0.1.4
npe2: 0.6.1

OpenGL:
  - GL version:  2.1 Metal - 83.1
  - MAX_TEXTURE_SIZE: 16384
```

## Additional context

The issue stems from the fact that VisPy does not support texture dtypes above uint16 or float32. (It's unclear to me whether this is a broader OpenGL limitation — @perlman and @brisvag might have a better idea here.) However, we can get around this by using (for example) up to two 8-bit RGBA textures to hold the keys, and then hashing the RGBA values together to get an unambiguous position in the colormap texture. (See #6083 for a bit more detail on the hashing.)

**Comment by brisvag** [comment]
> It's unclear to me whether this is a broader OpenGL limitation

Unless we enforce opengl 4.0 (and get macos to cooperate...) [we cannot use doubles](https://www.khronos.org/opengl/wiki/Data_Type_(GLSL)#Basic_types). Vispy actively disables them *for all openGL versions*, so I suspect it might also take a lot of work to get vispy to accept them.

**Comment by jni** [comment]
Thanks @brisvag! That's fine — I think two RGBAs work fine.

**Comment by Czaki** [comment]
@jni what did you mean about two textures? If it still goes through float 32 then one needs 3 textures to support the full 64 bits range? 
Double will also provide 52 of 64 bits.  

Or do you have an idea to use a wider range and not use only 22 but the whole 32 bits?

**Comment by jni** [comment]
@Czaki the idea is to *view* a 32bit (u)int as an 8-bit RGBA texture (8 x 4 channels = 32 bits), and then process the values with some hash function to index into the color texture, and 64bit (u)int as two 8-bit RGBA textures (8 x 4 channels x 2 textures = 64 bits) similarly. This is nice because we don't even need the current .astype call, so it should be much faster. In integrated architectures like M1 or integrated graphics, there won't even need to be a memory copy!

**Comment by perlman** [comment]
Another nice benefit of getting 64bit uint hashing in place is that we can directly cast any datatype <= 64bit into it, e.g. doubles, and still have labels working.
