### ISSUE TITLE
Abnormally slow test on MacOS CI.

### ISSUE THREAD

**Issue by Carreau** [napari/napari#6087]
## 🐛 Bug

test_add_all_layers seem to be abnormally slow on macos CI. Taking ~20s vs 2 on other platform combinaison.

<img width="1464" alt="Screenshot 2023-07-24 at 14 38 10" src="https://github.com/napari/napari/assets/335567/1661d215-6cae-4716-b4ea-8fe6e95f6d96">

## To Reproduce

You can explore the timings on for example https://pytest-viewer.org/gh/napari/napari/pull/6082

This is highly pronouced for this test but true for other. I'm guessing this might be why Mac-CI is regularly killed after 40min while it should take only 20-ish.

**Comment by willingc** [comment]
Closing this issue re: test on Mac since we're no longer timing out frequently. It's probably a good practice to do a scan once a quarter for very slow tests. Thanks @Carreau.
