### ISSUE TITLE
[ghcr.io/napari/napari-xpra] napari:0.4.18 contains napari 0.4.17

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari/napari#6096]
## 🐛 Bug

The docker container labeled 0.4.18 actually has napari 0.4.17 inside installed by pip.
cc: @jaimergp 

## To Reproduce

1. `docker run -it --rm -p 9876:9876 ghcr.io/napari/napari-xpra:0.4.18`
2. use the Terminal of the container: `pip show napari`

## Expected behavior

A container labeled 0.4.18 should have matching napari version.

## Environment

N/A

## Additional context

As discussed in the packaging meeting on July 26, 2023, this is probably due to time lag between napari getting to pypi and building the container.

**Comment by Czaki** [comment]
I have fixed core problem, and now the docker image contains the correct napari version (0.4.18) by just restart action. 

But I think that this issue should remain open until core problem was solved.
