### ISSUE TITLE
Selecting points of different sizes does not update the point size slider

### ISSUE THREAD

**Issue by Sagnik700** [napari/napari#6115]
Selecting point prompts of different sizes does not update the `point size` slider in the top left corner. In the screenshot below, point prompts of different sizes are registered, but after selecting the smaller point the `point size` slider still shows the size of the previously selected bigger point

![image](https://github.com/napari/napari/assets/23014134/cf8db77e-78d4-475a-9e23-e0e3ebbf79c7)

**Comment by jni** [comment]
Thanks for the report! That's definitely a bug. Probably not too hard to get it working — hook up a function updating the size to `Points.selected_data.events.items_changed`. A PR would be most welcome @Sagnik700! Happy to help if you need more guidance. Otherwise we will try to get to it ASAP! 🙏
