### ISSUE TITLE
Regression: Points.events.data is no longer fired from the data setter

### ISSUE THREAD

**Issue by jni** [napari/napari#6116]
## 🐛 Bug

While investigating affinder CI failures, I found that #5967 broke affinder's tests. (btw if you've never heard of `git bisect run` you should try it! 😍) The reason is [this line](https://github.com/napari/napari/pull/5967/files#diff-0eb960578d63238e8d320dcc3e9fa3b225b34f9b08827835c3ed0bff447f977cL599) which removes the data event emitter from the setter but doesn't replace it with the new style.

It seems to have been simply missed. @melonora was this intentional? I can't imagine the reason for it other than an oversight! 😅 

Fix incoming.

## To Reproduce

```python
import napari
import numpy as np


layer = napari.layers.Points(np.random.random((5, 3)))

layer.events.data.connect(lambda ev: print(ev))

print('adding a single point')
layer.add(np.random.random((1, 3)))  # prints ok

print('setting data')
layer.data = np.random.random((8, 3))  # nothing happens

print('done')
```

Result:

```
adding a single point
Event
setting data
done
```

Expected result (and result before 96516dad057aa8d31328f889ce73d40a800eb67d):

```
adding a single point
Event
setting data
Event
done
```

## Environment

napari main / napari 0.4.18.

**Comment by melonora** [comment]
oops :astonished:, this I believe is indeed an oversight. For sure it was not intentional.
