### ISSUE TITLE
bug with pygments 2.16.0

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#6121]
A heads up on a new bug I just saw when [running superqt tests on napari](https://github.com/pyapp-kit/superqt/actions/runs/5776771215/job/15656224598): 

```pytb
napari/utils/events/evented_model.py:246: in __init__
    super().__init__(**kwargs)
pydantic/main.py:341: in pydantic.main.BaseModel.__init__
    ???
E   pydantic.error_wrappers.ValidationError: 1 validation error for Theme
E   syntax_style
E     Incorrect `syntax_style` value: native provided. Please use one of the following:  abap, algol, algol_nu, arduino, autumn, bw, borland, colorful, default, dracula, emacs, fruity, friendly, friendly_grayscale, github-dark, gruvbox-dark, gruvbox-light, igor, inkpot, lightbulb, lilypond, lovelace, manni, material, monokai, murphy, nord, nord-darker, one-dark, paraiso-dark, paraiso-light, pastie, perldoc, rainbow_dash, rrt, sas, solarized-dark, solarized-light, staroffice, stata, stata-dark, stata-light, tango, trac, vim, vs, xcode, zenburn
E   assert 'native' in {'abap': 'abap::AbapStyle', 'algol': 'algol::AlgolStyle', 'algol_nu': 'algol_nu::Algol_NuStyle', 'arduino': 'arduino::ArduinoStyle', ...} (type=assertion_error)
```

looks like the new release of pygments (2.16.0) may have broken the theme naming strategy here

**Comment by psobolewskiPhD** [comment]
Looks like this PR:
https://github.com/pygments/pygments/pull/2443
which alphabetized the style list, dropped `native`—by accident I presume...

**Comment by psobolewskiPhD** [comment]
Made PR upstream that fixes our issue:
https://github.com/pygments/pygments/pull/2484

**Comment by tlambert03** [comment]
way to go @psobolewskiPhD 👍

**Comment by psobolewskiPhD** [comment]
FYI at present this makes a fresh pip napari not able to launch, which is a bit annoying!
conda-forge is still OK, because the pygments version hasn't propagated yet.

**Comment by Anteru** [comment]
2.16.1 is out with a fix: https://pypi.org/project/Pygments/2.16.1/

**Comment by tlambert03** [comment]
thanks @Anteru

**Comment by psobolewskiPhD** [comment]
Can confirm, `pip install pygments -U` and everything is groovy again.
