### ISSUE TITLE
def _show_warning(self, new_shortcut=''...) first argument is unused.

### ISSUE THREAD

**Issue by Carreau** [napari/napari#6130]
## 🧰 Task

It is a private method used only in a couple of places and this can be removed.

**Comment by Czaki** [comment]
could you point the class?

**Comment by Carreau** [comment]
Sorry, ShortcutEditor in napari/_qt/widgets/qt_keyboard_settings.py, I sent a PR immediately thinking it would have linked the two but forgot the `#`, thanks for fixing.
