### ISSUE TITLE
Scale not respected in 2D display

### ISSUE THREAD

**Issue by jni** [napari/napari#614]
## 🐛 Bug

When viewing an anisotropic volume in 2D, transposing the axes should result in a properly-scaled display of the cross-section.

## To Reproduce

1. Download the cropped sample A volume from cremi.org: https://cremi.org/static/data/sample_A_20160501.hdf
2. Load and display it as follows:

```python
import h5py
import napari

# volume is 125, 1250, 1250 with 10, 1, 1 anisotropy
raw = h5py.File('path/to/sample_A_20160501.hdf', mode='r')['/volumes/raw']
viewer = napari.view_image(raw, scale=[10, 1, 1])
```

3. Push the "roll dimensions order for display" button

<img width="934" alt="Screen Shot 2019-10-22 at 8 02 36 pm" src="https://user-images.githubusercontent.com/492549/67272040-79e2e580-f507-11e9-9aaf-971e380dd764.png">

4. Weep. =P

## Expected behavior

The side view should be expanded with the appropriate interpolation mode. (which I expect will break the labels layer with anything other than nearest-neighbour)

**Comment by sofroniewn** [comment]
Strange to me that this didn't work - i would have expected it to. I'll take a look when I have time

**Comment by sofroniewn** [comment]
Looks like `_on_scale_change` isn't getting triggered on the vispy view when the roll happens - should be easy to fix

**Comment by sofroniewn** [comment]
Note this bug is independent of addition of world coordinates

**Comment by sofroniewn** [comment]
This was fixed by #1102 and a test added. @jni would you like to confirm this is now fixed and close? (I just checked and it looks fixed to me)

**Comment by sofroniewn** [comment]
ping @jni - want to confirm this is fixed and then I can close?

**Comment by jni** [comment]
Yep! Sorry for the delay, works great! 😊
