### ISSUE TITLE
Add `view_multichannel` method

### ISSUE THREAD

**Issue by jni** [napari/napari#615]
## 🚀 Feature

I'm not sure whether we made a conscious decision not to add the `view_multichannel` function corresponding to the `add_multichannel` Viewer method, but if so I now believe that this decision was in error. =P

## Motivation

While working to add documentation, I found that I could meet many use cases of napari with a single `view_` call. However, for `add_multichannel`, I needed to first create an empty viewer, which is kind of ugly. I think it's pretty nice functionality, to, e.g. for the Mitosis Fiji sample, which is order TZCYX, to go:

```python
napari.view_multichannel(mitosis,
    axis=2, colormap=['magenta', 'green'], scale=[10, 1, 1]
)
```
and be done.

**Comment by tlambert03** [comment]
i've been incorporating napari into LLSpy, and this was one of the first things I wanted to do

**Comment by sofroniewn** [comment]
not intentional - was an oversight! i think all out `add_*` methods should have `view_*` method counterparts where the keyword args are the same + the viewer keyword args.

**Comment by jni** [comment]
Turns out this is already on master! 😂
