### ISSUE TITLE
turbojpeg.dll in the user temp directory

### ISSUE THREAD

**Issue by MosGeo** [napari/napari#6159]
Not really a bug but an annoyance (it is not breaking anything). It is also probably related to the tiff reader upstream (tifffile) but I am not sure. 

When reading a tiff file with jpeg compression in napari, napari creates a temperary file "turbojpegxxxxxxxxxxxxxx.dll" in the temp directory of the user (c:\users\username\appdata\local\temp\). A new file with different numbering in the filename is created everytime you restart napari.

## To Reproduce
Load TIFF file into napari using the builtin reader.

## Expected behavior
If it is a needed file, why not have it packaged with napari. A dll is usually not a temperary file. Also, why create multiple copies every time.

## Environment
napari: 0.4.18
platform: windows 10
Python: 3.10.2
Qt: 5.15.2

 - Any other relevant information:

**Comment by cgohlke** [comment]
No way that's tifffile related. 

Most likely Bio-Formats/[scijava](https://github.com/scijava/native-lib-loader/blob/21d6c1e9f9e296e5cdbb151d20e0861e1ee3261d/src/main/java/org/scijava/nativelib/NativeLibraryUtil.java#L78-L79) is triggered to extract it's turbojpeg.dll from JAR to the TEMP directory in order to load it into the process.

**Comment by jni** [comment]
Thanks for the clarification @cgohlke! 😅 

@MosGeo what plugins have you got installed? Does this happen with a *bare* napari install?

**Comment by jni** [comment]
(we don't ship bioformats/scijava or any of that with napari) (we do ship imageio but that doesn't seem likely to be the cause either, since "turbojpeg" doesn't appear [anywhere in the imageio repo](https://github.com/search?q=repo%3Aimageio%2Fimageio%20turbojpeg&type=code).)

**Comment by MosGeo** [comment]
I think it was related to some package that I installed. The issue does not exist with newer virtual environment that I am using. Closing.
