### ISSUE TITLE
Viewport cropping occurs with hidpi scaling and QT_SCALE_FACTOR non-integer

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari/napari#6197]
## 🐛 Bug

Originally reported here: https://github.com/napari/napari/issues/1417
It appears that on linux, using non-integer QT_SCALE_FACTOR such as 1.3 or 1.5 or 1.8 results in viewport cropping.
Basically, napari doesn't use the full canvas. Instead part of the viewport is black and only part of the image is visible.
See screenshot below from the other issue:
![image](https://github.com/napari/napari/assets/76622105/01167d42-3cb6-439e-809d-d4769fb8ce95)

Most recently reported by @lagru see also:
https://github.com/scipy-2023-image-analysis/tutorial/pull/10#discussion_r1253658356

## To Reproduce

1. launch napari using: `QT_SCALE_FACTOR=1.8 napari`
2. open a sample image

## Expected behavior

Image should be displayed as normal

## Environment

the issue has occurred in 2020 and at present on two different systems.
The most recent env info can be found here:
https://github.com/napari/napari/issues/1417#issuecomment-1622587886

**Comment by dalthviz** [comment]
Hi, maybe this could be useful here?: https://doc.qt.io/qt-5/qguiapplication.html#setHighDpiScaleFactorRoundingPolicy

**Comment by dalthviz** [comment]
Just in case, seems like doing some changes on the vispy Qt canvas backend could help with this! From what I have tested, seems like changing the call of `devicePixelRatio` that is done the backend class (which inherits `QOpenGLWidget`) to the value that can be obtained from `QGuiApplication.instance().devicePixelRatio()` enables seeing the canvas correctly :)

So changing:

https://github.com/vispy/vispy/blob/83d029b2c03a6c2d64f63a1f6045b62615d1de11/vispy/app/backends/_qt.py#L387-L394
```python
        # must set physical size before setting visible or fullscreen
        # operations may make the size invalid
        if hasattr(self, 'devicePixelRatio'):
            # handle high DPI displays in PyQt5
            ratio = self.devicePixelRatio()
        else:
            ratio = 1
        self._physical_size = (p.size[0] * ratio, p.size[1] * ratio)
```

To be something like:

```python
        # must set physical size before setting visible or fullscreen
        # operations may make the size invalid
        ratio = QGuiApplication.instance().devicePixelRatio()
        self._physical_size = (p.size[0] * ratio, p.size[1] * ratio)
```

and

https://github.com/vispy/vispy/blob/83d029b2c03a6c2d64f63a1f6045b62615d1de11/vispy/app/backends/_qt.py#L912-L918
```python
        if hasattr(self, 'devicePixelRatio'):
            # We take into account devicePixelRatio, which is non-unity on
            # e.g HiDPI displays.
            # self.devicePixelRatio() is a float and should have been in Qt5 according to the documentation
            ratio = self.devicePixelRatio()
            w = int(w * ratio)
            h = int(h * ratio)
```

To

```python
# We take into account devicePixelRatio, which is non-unity on
        # e.g HiDPI displays.
        # self.devicePixelRatio() is a float and should have been in Qt5 according to the documentation
        ratio = QGuiApplication.instance().devicePixelRatio()
        w = int(w * ratio)
        h = int(h * ratio)
```

Enables usaging the `QT_SCALE_FACTOR`:

![qt_scale_canvas](https://github.com/napari/napari/assets/16781833/9907925f-2273-471f-a3e2-06a6d7b7fd84)

Not totally sure why but seems like the OpenGL Qt widget/vispy canvas Qt backend doesn't return the correct device pixel ratio following the `QT_SCALE_FACTOR` env var config:

![imagen](https://github.com/napari/napari/assets/16781833/22c4c000-e20f-41d5-8d59-32f42eddbff7)

**Comment by dalthviz** [comment]
Just in case, I was able to reproduce this also on Windows:

![imagen](https://github.com/napari/napari/assets/16781833/d1b07b01-dbe1-4183-8814-d3ff8b844e75)

And submitted an issue to vispy: https://github.com/vispy/vispy/issues/2538

**Comment by jni** [comment]
Fantastic sleuthing @dalthviz! 🙏

**Comment by psobolewskiPhD** [comment]
The vispy issue has been closed by https://github.com/vispy/vispy/pull/2540
@dalthviz Does that close this as well?

**Comment by psobolewskiPhD** [comment]
Awesome! I'll leave this open for now, but hopefully that happens with 0.5.0 so I will put that as a milestone and then we need to remember to close!
