### ISSUE TITLE
io.magic_read not updated in __main__.py

### ISSUE THREAD

**Issue by hectormz** [napari/napari#623]
## 🐛 Bug

Call to `io.magic_read()` on line 56 of `__main__.py` not updated to `io.magic_imread()` after #601 

## To Reproduce

1. Running `napari some_file.png` from command line

I'm happy to open this one line change Pull Request, or it can be done by one of the maintainers

**Comment by sofroniewn** [comment]
If you can make a PR to fix that would be great! my fault!

**Comment by sofroniewn** [comment]
i might also quickly make one, as this is a pretty serious bug that we should fix before our next release, thanks for catching it!

**Comment by hectormz** [comment]
Just submitted, happy to help!

**Comment by sofroniewn** [comment]
Perfect, thanks!!
