### ISSUE TITLE
Setting slider position of a multidimensional image

### ISSUE THREAD

**Issue by ziyuanzhao2000** [napari/napari#6236]
## 📚 Documentation

In the tutorial [here](https://napari.org/stable/tutorials/fundamentals/viewer.html), it says: In order to get or update the current position of the slider, use:

```
# to get the current position  
viewer.dims.current_step
# to change the current position  
viewer.dims.current_step = 3
```

However, with the synthetic dataset used in the tutorial, and using napari v0.4.18, `viewer.dims.current_step` gives a tuple output of `(0, 255, 255)` rather than an integer index. Thus, I have to change the current position instead with `viewer.dims.current_step = (3, 255, 255)`, and that line of code from the tutorial doesn't quite work now. 

I hope you can help to check this and see if I'm using the Viewer correctly. Thank you!

**Comment by psobolewskiPhD** [comment]
Is it a bug or is it a change that wasn't documented?
Looks like `viewer.dims.current_step` has been returning a tuple for quite some time—at least 0.4.17 which I had handy.
It makes some sense if you take something Cells_3D and move the z-slider to look at a different xy plane and then rotate the axes and adjust the x-slider.
`viewer.dims.current_step` will report the position of each slider.

And of course once you have a 4D image, where you will always have 2 sliders, then it's clear it needs to be a tuple.

**Comment by melonora** [comment]
I will backtrack, but then we do need a way to actually set the particular slider dimensions I think.

**Comment by psobolewskiPhD** [comment]
> I will backtrack, but then we do need a way to actually set the particular slider dimensions I think.

You can still set the positions by passing the tuple.
e.g. open Cells_3D and merge the channels to a stack (contextual menu)
`viewer.dims.current_step = (0, 40, 128, 128)` 
Sets both sliders.
And the sliders are labeled, so it's not horribly unintuitive.
(one thing is that you can set them out-of-bounds, so e.g. (2, 40, 128, 128) will give a black box)

Now, we could make a feature where something like `current_slider_pos` returned the position of just the currently active sliders, but I'm not sure that actually is a QoL improvement?

**Comment by melonora** [comment]
Sounds good

**Comment by ziyuanzhao2000** [comment]
@melonora Thank you for your quick attention to this issue! I'm a new user of napari, so I wasn't sure if this is more like a bug vs. a documentation issue.

I think I do see Peter's point that slicing 2D planes through >3D images would have to return a tuple for the slice location.

**Comment by melonora** [comment]
No problem, I think one way we could do this is is by having a `_set_current_step` method with 2 arguments, `steps` and `dim_indices`. Either being a single `int` or a `tuple` of `int`, with both arguments being required to be of the same length and indices currently not being displayed. @ziyuanzhao2000 @psobolewskiPhD do you both think this would be more intuitive? In any case lets fix the docs first.

**Comment by melonora** [comment]
PR in napari/docs is open [#241](https://github.com/napari/docs/pull/241)

**Comment by psobolewskiPhD** [comment]
I've merged that PR and I think this can be closed. If there is a feature request for some other way to programmatically move the sliders, then it can be a new issue.
Thanks everyone!
