### ISSUE TITLE
redundant calls to VispyImageLayer._on_data_change

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#625]
## 🐛 Bug

This is just to start an issue to discuss the redundant calls to `VispyImageLayer._on_data_change()` as disccused in https://github.com/napari/napari/issues/575#issuecomment-544797848 ... which will likely be a drag on performance

I know this will be _much_ easier for @sofroniewn and others to solve, but I just wanted to use it as an opportunity to understand the napari event sequence a little better, and I'm adding some observations here in case it's useful for anyone else's debugging process.  I was able to track down the 6 paths leading to `_on_data_change`.  In the image below, you can trace the unique ways to get to `_on_data_change` from the `Dims.events.ndisplay()` event... all 6 of them are traversed when `ndisplay = 3`, only 5 are traversed when changing `ndisplay = 2`.

![Screen Shot 2019-10-25 at 4 59 20 PM](https://user-images.githubusercontent.com/1609449/67604549-d897a180-f749-11e9-81ee-a6a8cb9bf093.png)

and if you log events in the order they happen ... here is the (nested) sequence of calls 
```
components.Dims @ndisplay.setter
    <Dims.events.ndisplay event emitted>
        VispyImageLayer._on_display_change
            Layer._update_dims
                Image._set_view_slice
                    <Image.events.set_data event emitted>
                        ** VispyImageLayer._on_data_change **
            Image._set_view_slice
                <Image.events.set_data event emitted>
                    ** VispyImageLayer._on_data_change **
            VispyImageLayer.reset
                VispyImageLayer._on_contrast_limits_change
                    ** VispyImageLayer._on_data_change **
                ** VispyImageLayer._on_data_change **

        Layer._update_dims
            Image._set_view_slice
                <Image.events.set_data event emitted>
                    ** VispyImageLayer._on_data_change **
        Image._set_view_slice
            <Image.events.set_data event emitted>
                ** VispyImageLayer._on_data_change **
```

**Comment by sofroniewn** [comment]
@tlambert03 thanks for making this! It pains me a little to look at it (though I love the rendering, did some software automatically generate it for you?)

This spaghetti monster clearly needs to be cleaned up, and I'll start thinking about how be to do it. I think we'll just want one pass - corresponding to the outside loop
```
Dims.events.ndisplay -> Image._set_view_slice -> Image.events.set_data -> _on_data_change
```
and we'll want to cut the other paths, without breaking everything else!!

**Comment by jni** [comment]
Wonderful, @tlambert03! I second @sofroniewn's question, but in more detail! You clearly have much better tooling than us! 😂 Could you elaborate on your detective work so we can track it better ourselves in the future?

**Comment by tlambert03** [comment]
I wish I could claim credit for a sweet tooling setup... but I'm afraid that was just brute force.  I made the graphic manually in keynote 🤫starting at `_on_data_change` and connecting stuff back to `ndisplay.setter`.  I have played with [pygraphviz](https://github.com/pygraphviz/pygraphviz) and [pydot](https://github.com/pydot/pydot) for rendering similar connections/relations, like in database schema... but for something small like this, it would take more time to use those tools than to just do it manually.

I did use the `logging` module though to help figure out the sequence of calls... and realized that there is no logging yet in napari.  Is that a discussion that's been had?  I'm not sure whether it's worth littering the code with `logger.debug` calls, but when you need them it's nice to have them already in place... especially in the `EventEmitter.__call__` method

**Comment by jni** [comment]
Logging definitely under consideration! We're considering some more modern external tools though, e.g. loguru.

Massively impressed at your dedication to PR/issue clarity. :joy:

**Comment by tlambert03** [comment]
loguru looks awesome. 👍

**Comment by sofroniewn** [comment]
Adding logging in a dedicated PR sounds good

For now I'm working on fixing this, should have something soonish
