### ISSUE TITLE
Deprecate/Remove unused arguments from utils functions in `napari/napari/utils/misc.py` ?

### ISSUE THREAD

**Issue by Carreau** [napari/napari#6256]
## 🧰 Task
In `napari/utils/misc.py` both `def ensure_iterable` and `def is_iterable` seem to have keywords arguments that are never used (`color=False`, and `allow_none=False`), leading to non-covered branches. 

I suggest to deprecate passing the keyword arguments, then open an issue to remove branches.

**Comment by palec87** [comment]
Hi @Carreau, this is my first PR to such extensive project. Please feel free to guide me to fix things further. Deep regards.

**Comment by Carreau** [comment]
Sorry, I'm not too involved in the project anymore, but will try to comment on your PR.
