### ISSUE TITLE
Support `python==3.12`

### ISSUE THREAD

**Issue by paddyroddy** [napari/napari#6285]
## 🚀 Feature
[Python 3.12 has been released today](https://docs.python.org/3.12/whatsnew/3.12.html)

## Motivation

We should keep up-to-date with the `python` ecosystem

## Pitch

Support running `napari` with `python==3.12`

**Comment by psobolewskiPhD** [comment]
conda-forge has python 3.12 live now.
On a whim I did a pip install of napari.
- scikit_image doesn't have cp12 wheels (but built on my arm64 macOS)
- vispy doesn't have cp12 wheels (but built on my arm64 macOS)
- PyWavelets does not have cp12 wheels and did not build (pkgutil error)

**Comment by Czaki** [comment]
PyWavelets issue: https://github.com/PyWavelets/pywt/pull/693

**Comment by psobolewskiPhD** [comment]
PyWavelets for python 3.12 is on conda-forge, so I was able to install that and then pip install napari et al.
scikit-image now has a python 3.12 wheel (arm64)
It runs and seems fine, but I will try to find time to run tests.

**Comment by Carreau** [comment]
#6308 try to add Python 3.12 CI and list a couple of things that still need to be adressed.

**Comment by rgommers** [comment]
A new PyWavelets release with Python 3.12 support is up on PyPI.

**Comment by psobolewskiPhD** [comment]
numba is now part of our requirements and current release doesn't support 3.12 yet:
https://github.com/numba/numba/issues/9197

**Comment by psobolewskiPhD** [comment]
numb a 3.12 support has been merged:
https://github.com/numba/numba/pull/9246
So we should be good to go when they release?

**Comment by Carreau** [comment]
When released merged master into #6308 and we'll see if CI fails. It seem there were release of most compiled binaries we require, but we won't know until then.

**Comment by paddyroddy** [comment]
[numba now supports 3.12](https://github.com/numba/numba/issues/9197)

**Comment by tlambert03** [comment]
anything still holding up 3.12 on napari?

**Comment by Czaki** [comment]
I think napari is working with 3.12, but we need to set up CI. I have planned to drop python 3.8 first, but there are few PR that should be merged first to avoid conflicts.

**Comment by psobolewskiPhD** [comment]
I'm going to close this with 0.5.0a 
https://github.com/napari/napari/pull/6738
