### ISSUE TITLE
[Python 3.11] "Deal with" python 3.11 debugging warning on startup (re: frozen modules)

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari/napari#6286]
## 🧰 Task

Starting napari (command line or python REPL) on python 3.11 triggers a warning:
```
0.01s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
```
This isn't relevant to most end-users and could be a source of confusion or irritation.
Would be nice to find what module is triggering it and then either silence it or work around it.

**Comment by Czaki** [comment]
The current workaround is to use the npe1 adapter. The warning is triggered by the scan of `napari-console`. Exactly by this line: https://github.com/napari/napari-console/blob/760388c0b5251ab78d45e83270c40f11bee5e289/napari_console/qt_console.py#L6
