### ISSUE TITLE
Unable to set shortcuts/keybindings on Windows

### ISSUE THREAD

**Issue by dalthviz** [napari/napari#6296]
## 🐛 Bug

It is not possible to set shortcuts/keybindings on Windows when using modifier keys (`Ctrl`, `Shift`, etc) plus some other key (for example `Ctrl + T`)

## To Reproduce

1. Go to `Preferences > Shortcuts`
2. Try to set an alternative keybinding for an action. For example, set for the `Toggle current viewer theme` something like `Ctrl + T`
3. Instead of setting the new keybinding or showing the conflict message, a warning is shown and a `Ctrl+unknown` text is left.

* A preview of the behavior:

![mod_shortcuts](https://github.com/napari/napari/assets/16781833/98a9b9b2-8824-48a4-b9c9-6eef29495ba8)

* The warning message being shown:

```python-traceback
E:\Acer\Documentos\Quansight\Napari\napari\napari\utils\action_manager.py:324: UserWarning: `Ctrl-+T` does not seem to be a valid shortcut Key.!
```

## Expected behavior

Set the new keybinding combination or show a warning if it conflicts with an already set keybinding

## Environment

 - Please copy and paste the information at napari info option in help menubar here:

<details>

```
napari: 0.5.0a2.dev365+g08a22b05
Platform: Windows-10-10.0.19045-SP0
Python: 3.10.9 | packaged by conda-forge | (main, Jan 11 2023, 15:15:40) [MSC v.1916 64 bit (AMD64)]
Qt: 5.15.2
PyQt5: 5.15.9
NumPy: 1.25.2
SciPy: 1.9.3
Dask: 2022.10.2
VisPy: 0.13.0
magicgui: 0.7.3
superqt: unknown
in-n-out: 0.1.5
app-model: 0.2.2
npe2: 0.7.2

OpenGL:
- GL version: 4.5.0 - Build 25.20.100.6444
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1366x768, scale 1.0
- screen 2: resolution 1920x1080, scale 1.0
- screen 3: resolution 1600x900, scale 1.0

Settings path:
- C:\Users\dalth\AppData\Local\napari\napari-dev_4454fdbf170edefe23827a4bf512389a6806af69\settings.yaml
```

</details>

## Additional context

I was checking #6204 on Windows when I noticed this. Checking the code related with the shortcuts seems like this is caused due to a replace done at:

https://github.com/napari/napari/blob/08a22b053f87ca5010fe43b983390c199921f83e/napari/utils/interactions.py#L335

Maybe such replace (adding a `-`) shouldn't be done on Windows? Removing the `+ '-'` seems like helps:

![mod_shortcuts_no_minus](https://github.com/napari/napari/assets/16781833/dd77f87e-66f5-47fc-8eb9-8beb588e3a8c)

**Comment by psobolewskiPhD** [comment]
Just want to be super sure: this isn't an issue in 0.4.18 right? just `main`?
