### ISSUE TITLE
error installing on ec2 deep learning ami

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#631]
## 🐛 Bug

Following up on #495 I'm trying to install napari on an amazon ec2 instance with the ubuntu deep learning ami am but running into this error:

```python
ERROR: sparkmagic 0.12.5 has requirement ipykernel<5,>=4.2.2, but you'll have ipykernel 5.1.1 which is incompatible.
ERROR: sparkmagic 0.12.5 has requirement ipython<7,>=4.0.2, but you'll have ipython 7.9.0 which is incompatible.
ERROR: jupyter-console 5.2.0 has requirement prompt_toolkit<2.0.0,>=1.0.0, but you'll have prompt-toolkit 2.0.10 which is incompatible.
```

Once we get #587 in this should be improved. I don't know what `sparkmagic` is

**Comment by sofroniewn** [comment]
If i `pip uninstall sparkmagic` this now goes away (we don't need that package), but I now run into

```python
  Found existing installation: qtconsole 4.3.1
ERROR: Cannot uninstall 'qtconsole'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
```

We have a requirement of `>4.5.1` not sure how to proceed now, will keep trying

**Comment by sofroniewn** [comment]
navigating to `/anaconda3/lib/python3.6/site-packages` and then doing `rm -rf` on the offending packages and then pip installing again seems to have worked

**Comment by sofroniewn** [comment]
As to be expected I can now run `import napari` on in ipython or a jupyter notebook running from my ec2 instance, but I cannot actually view any images as it isn't possible to launch the `QApplication`. I want to now start investigating though if I can connect this python kernel to the qtconsole running inside napari on my local machine

**Comment by jni** [comment]
@sofroniewn *sigh* the pip folks have done a lot of work to try to ensure that your distro remains consistent, but now it results in these annoying errors *that have no workaround*. It's insane that you have to `rm -rf` packages but I think that is sadly where we are at right now. 🤦‍♂ I'm not sure what the right repo is to complain about this.

**Comment by sofroniewn** [comment]
Note the error message on trying the `%gui qt` magic is 
```
qt.qpa.screen: QXcbConnection: Could not connect to display
Could not connect to any X display.
```

**Comment by YubinXie** [comment]
Hi, @sofroniewn  
I am curious that if you run it on AWS, how do you see the windows? Thanks!

**Comment by sofroniewn** [comment]
@YubinXie - you can’t see the window right now! We’re going to be working on a system that will connect a remote napari to napari running locally though so you can still interact with remote data and compute. I’ll be posting more details here as we start to work on it more

**Comment by YubinXie** [comment]
@sofroniewn This is cool. Thanks! It would be great if multiple users can remotely interact the data at the same time.

**Comment by brainwane** [comment]
> @sofroniewn _sigh_ the pip folks have done a lot of work to try to ensure that your distro remains consistent, but now it results in these annoying errors _that have no workaround_. It's insane that you have to `rm -rf` packages but I think that is sadly where we are at right now. man_facepalming I'm not sure what the right repo is to complain about this.

I saw this issue and wanted to mention - could you try [the beta of the new pip release](https://discuss.python.org/t/announcement-pip-20-1b1-beta-release/3960) to see whether it helps you with this?

**Comment by brainwane** [comment]
pip 20.2 is now out. This release includes the **beta of the next-generation dependency resolver**. It is significantly stricter and more consistent when it receives incompatible instructions, and reduces support for certain kinds of constraints files, so some workarounds and workflows may break. **Please test it** with the `--use-feature=2020-resolver` flag. Please see [our guide on how to test and migrate, and how to report issues](https://pip.pypa.io/en/latest/user_guide/#changes-to-the-pip-dependency-resolver-in-20-2-2020). The new dependency resolver is *off by default* because it is *not yet ready for everyday use*.

We plan to make pip's next quarterly release, 20.3, in October 2020. **We are preparing to change the default dependency resolution behavior and make the new resolver the default in pip 20.3.**

More info at [this blog post](https://blog.python.org/2020/07/upgrade-pip-20-2-changes-20-3.html).

**Comment by sofroniewn** [comment]
Thanks @brainwane! I'll give this a try when I get the chance!!

**Comment by jni** [comment]
:wave: @brainwane! I intend to use the resolver every time I use pip now, if I can remember. Bravely onwards! :crossed_fingers:

**Comment by sofroniewn** [comment]
I'm going to close this issue as we've changed some of our dependencies and pins so this no longer applies, but thanks all for the comments and the great info on pip's new resolver!!
