### ISSUE TITLE
Use consistent separator for `commandID`s

### ISSUE THREAD

**Issue by lucyleeow** [napari/napari#6325]
Napari app model command IDs all use `:` between words, e.g., see:

https://github.com/napari/napari/blob/1b1baa8291ff03fb7732b9ca27b33ef471da0b71/napari/_app_model/constants/_commands.py#L18-L28

For plugins we use the command `id` field for this. Our builtins use `.` instead, e.g.,:

https://github.com/napari/napari/blob/1b1baa8291ff03fb7732b9ca27b33ef471da0b71/napari_builtins/builtins.yaml#L10-L15

Can/should we change these over?

Note I know we can't dictate what other plugins do but should we be consistent within napari and builtins?

**Comment by jni** [comment]
Hmmm. In which direction are you proposing the change? tbh I like IDs to match python_name, which implies `.` to separate modules and `:` to separate module path from function path. I don't really understand the reason to have both ID and python name? Is it brevity?

I also discussed with (I think) Draga and Talley at some point to have the leading module name removed/implied by the top level module name (ie [here](https://github.com/napari/napari/blob/1b1baa8291ff03fb7732b9ca27b33ef471da0b71/napari_builtins/builtins.yaml#L2)). I think that should be a priority because the yamls are really repetitive.

**Comment by lucyleeow** [comment]
> I don't really understand the reason to have both ID and python name? Is it brevity?

Not all commands will have a `python_name` (some actions will have a function as a callback) but can use whatever separator you wish.


>  leading module name removed/implied by the top level module name 

In the `ID`? It is used when defining `Actions` so adds the info of where the command came from. I am not sure that once you are at the level of `Action` that info is always there. E.g., not all plugin contributions will have a `python_name` - sample URIs

**Comment by jni** [comment]
> Not all commands will have a python_name (some actions will have a function as a callback) but can use whatever separator you wish.

Well, a function has a Python name? Do you mean a lambda? Or?

> It is used when defining Actions so adds the info of where the command came from. I am not sure that once you are at the level of Action that info is always there.

Ah, yes, sorry, I didn't finish my thought: on parse, npe2 would add the leading package name back in.

This also makes sense from a namespacing perspective: as a plugin developer, you should be able to control IDs in your own namespace. You shouldn't be able to write `napari.whatever` and use an ID that "implies" a built-in napari action?

> Especially as not all plugin contributions will have a python_name - sample URIs

Ok, so maybe ID *defaults* to Python name if there is no ID but there is a Python name?

**Comment by lucyleeow** [comment]
> Well, a function has a Python name? Do you mean a lambda?

I mean specifically the `python_name` field in contribution. Sample URIs do not have one. 

> Ok, so maybe ID defaults to Python name if there is no ID but there is a Python name?

That's fine with me. Can you suggest this in #6227 ? And if we do want to do that then this issue would be redundant and I can close.

> Ah, yes, sorry, I didn't finish my thought: on parse, npe2 would add the leading package name back in.

Sounds reasonable but probably outside the scope of this issue? Is there another issue this is documented in? If not would you open a new issue?

**Comment by lucyleeow** [comment]
Just remembered another case where `id` being the same as `python_name` may cause potential conflict, sometimes 2 different actions call the same function, e.g., `DLG_SAVE_SELECTED_LAYERS` and `DLG_SAVE_LAYERS`. In this case we are currently creating another function with the different args but I think Talley originally wanted `Action` to support a `kwargs` field, in which case the `python_name` would be the same (but `id`s need to be different)

see: https://github.com/pyapp-kit/app-model/issues/52

**Comment by DragaDoncila** [comment]
@lucyleeow I think the command IDs e.g. as those shown in the `File` menu snippet you've shown here, should roughly follow the convention of `.` separation as per the command IDs defined in the `manifest`.

I think questions of whether we should be defaulting command IDs to the `python_name` and/or not requiring plugin developers to prepend the plugin name to command IDs are outside the scope of this issue - should be an issue on the `npe2` repo, or another bullet point in our general "manifest pain points" issue #6227

**Comment by lucyleeow** [comment]
Another point where defaulting to python name would not work - we have several cases where different actions use the same function but with different kwargs, e.g., the help menu which does many calls to `webbrowser.open`. This would not work as command ID needs to be unique.
