### ISSUE TITLE
Be smarter about launching without a Qt event loop

### ISSUE THREAD

**Issue by jni** [napari/napari#634]
Several new users have reported issues with the `%gui=qt` / `--gui=qt` / `with gui_qt()` stuff. It's actually a pretty big gotcha with napari right now. At a minimum, we should catch these exceptions in the following entry-points:

- `Viewer()`
- `view_*()`

and provide an informative error message. Better, we should detect when there is no event loop and create our own, which would be blocking in IPython — but this is fine, this is how matplotlib works.

**Comment by jni** [comment]
CC @GenevieveBuckley @DrLachie

**Comment by sofroniewn** [comment]
Agreed - minimum fail gracefully, 2nd option is to warn and wait an extra couple seconds, sometimes it may be coming, finally we should make our own.

Fixing this is a high priority

**Comment by sofroniewn** [comment]
This has now been closed by #642
