### ISSUE TITLE
Compatibility with pydantic versions >= 2

### ISSUE THREAD

**Issue by VolkerH** [napari/napari#6350]
## 🚀 Feature

This is a feature request is for compatibility with pydantic v2. 
Just adding an issue because I couldn't find one that tracks it. 

## Motivation

I know that  @tlambert03  and @jni [did already discuss this problem with the pydantic people before v2 was released](https://github.com/pydantic/pydantic/discussions/5402):

Napari cannot currently be installed in a python environment where pydantic >= 2. 
Previously, a suggested work-around was pinning pydantic <2 , see e.g. #6029
As more and more other libraries will depend on pydantic > 2, this is not viable long-term (in fact, it is causing problems now).

## Additional context

* @tlambert03 has been working on a compatibility wrapper https://github.com/tlambert03/pydantic-compat
* Pydantic v2 includes a whole pydantic v1 that can be imported like `from pydantic.v1 import BaseModel`. 
* `app-model` also has some compatibility layer (https://github.com/pyapp-kit/app-model/blob/main/src/app_model/_pydantic_compat.py) which I guess is an early version of   https://github.com/tlambert03/pydantic-compat
* `npe2` also requires pydantic < 2

I tried the naive approach of replacing all imports from pydantic with imports of pydantic.v1 in napari and npe2. (`app-kit` is a different story as it is trying to guess which version is used ... for testing purposes I patched it to import from `pydantic.v1` but set `PYDANTIC2` to `False` despite using pydantic 2.4). Well, I did not get very far, various pydantic related issues popped up that I didn't have time to investigate or document further. I have a feeling this is a hard problem and even if it can be fixed for napari it will break some plugins. (as mentioned in the discussion linked to above). 

It is also not a problem that can be fixed with a single PR to napari, but requires corresponding PRs in npe2 and probably app-model.

**Comment by Czaki** [comment]
I think that we should reach pydantic 2 compatibility by migrating to psygnal from custom evented models.

**Comment by Czaki** [comment]
we cannot drop pydantic as part of the plugins may require this.

**Comment by jni** [comment]
@Czaki we should check how many — it might be reasonable effort to migrate any plugins using pydantic.

At any rate these changes are intended to make napari compatible with *either* pydantic 1 or pydantic 2.

**Comment by Czaki** [comment]
T make compatibility it will be enough to create `napari.pydantic` module for re export pydantic symbols based on version. So it will be only a few lines. and then import from `napari.pydantic` instead of `pydantic`

**Comment by tlambert03** [comment]
> but requires corresponding PRs in npe2 and probably app-model.

can you tell me what parts of app-model you expect need updating?  app-model already supports and is tested (with 99% coverage) against both pydantic 1 and 2

**Comment by Czaki** [comment]
I think about using `pydantic.v1` it is different from `pydantic<2` 

Of course fully migration to pydantic 2 will be much more complex.

**Comment by tlambert03** [comment]
ah, yep!  That's an easy fix that should definitely be done asap

**Comment by bentaculum** [comment]
Hi,
I have an interesting follow-up on this:
I can install a plugin that requires pydantic v2 via `pip install napari-trackastra`, but when I use the GUI plugin installer in napari, I get the following error:

```
ERROR: Cannot install napari-trackastra because these package versions have conflicting dependencies.


The conflict is caused by:
    napari 0.4.19.post1 depends on pydantic>=1.9.0
    trackastra 0.1.1 depends on pydantic>=2.0
    napari 0.4.19.post1 depends on pydantic>=1.9.0
    trackastra 0.1.0 depends on pydantic>=2.0
    The user requested (constraint) pydantic<2

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

I don't understand where this line is coming from
```
The user requested (constraint) pydantic<2
```

Does someone have a hint?

**Comment by Czaki** [comment]
The line that you point comes from 

https://github.com/napari/napari/blob/bd47bf0ecbfc74f1efa82343dbdfcbefd3f0bded/napari/_qt/dialogs/qt_plugin_dialog.py#L65

We are on path to release 0.5.0 (hopefully a few weeks) that should drop this constraint. There is no way to workaround it from the GUI at this moment.

**Comment by bentaculum** [comment]
Hi @Czaki, thx for the quick and precise answer, looking forward to napari 0.5.0 🎉.
