### ISSUE TITLE
Bug in progress bar behaviour in examples/mgui_threadworker_.py

### ISSUE THREAD

**Issue by GenevieveBuckley** [napari/napari#6354]
### 🐛 Bug Report

When you run the `mgui_threadworker` example script, napari launches with the dock widget progress bar already running. This is before the user has clicked the "Run" button on the dock widget. But the expected behaviour is that the progress bar should only run while the thread worker is actively computing a result.

This is a problem, because it leads the user to believe that computation is happening when it is not.

### 💡 Steps to Reproduce

1. Run the `mgui_threadworker` example script:
```
python examples/mgui_threadworker_.py
```

2. Observe that the progress bar is already running, before the user has had any chance to interact with the dock widget and click the "Run" button.

### 💡 Expected Behavior

I expected that the progress bar should only run while the thread worker is actively computing a result.

### 🌎 Environment

napari: 0.5.0a2.dev399+g0bf6801a.d20231020
Platform: macOS-13.5.2-arm64-arm-64bit
System: MacOS 13.5.2
Python: 3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:41:52) [Clang 15.0.7 ]
Qt: 5.15.8
PyQt5: 5.15.9
NumPy: 1.26.0
SciPy: 1.11.3
Dask: 2023.10.0
VisPy: 0.14.1
magicgui: 0.7.3
superqt: 0.6.1
in-n-out: 0.1.9
app-model: 0.2.2
npe2: 0.7.2

OpenGL:
- GL version: 2.1 Metal - 83.1
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1440x900, scale 2.0
- screen 2: resolution 1920x1080, scale 1.0

Settings path:
- /Users/genevieb/Library/Application Support/napari/test-napari_4d90fd5740b9355a228bc861dcd2a5bc2d9b29ec/settings.yaml

### 💡 Additional Context

You can see that after clicking the dock widget "Run" button the first time, behaviour then works as expected. It's really only at start up that things do not behave well.

**Comment by GenevieveBuckley** [comment]
Things I have tried:
* Moving the progress bar start command into the thread worker decorator (this didn't help):`@thread_worker(connect={'started': pbar.show, 'returned': pbar.hide})`

**Comment by GenevieveBuckley** [comment]
@tlambert03 is the expert on magicgui, any suggestions here?

**Comment by Czaki** [comment]
@GenevieveBuckley When new magicgui will be released this bug will be solved.
