### ISSUE TITLE
With asynchronous tiling enabled: AttributeError: 'OctreeDisplayOptions'...

### ISSUE THREAD

**Issue by m-albert** [napari/napari#6368]
### 🐛 Bug Report

After activating the experimental asynchronous tiling of images option, I got this error when trying to add a layer.

### 💡 Steps to Reproduce

1. Open napari and activate "Experimental -> Enable Asynchronous Tiling of Images" in the preferences. Close napari.
2. Open a napari viewer and add a layer to it.
```python
import napari
import numpy as np

viewer = napari.Viewer()
viewer.add_image(np.ones((10,10)))
```

Error:

```
  File "/Users/malbert/mambaforge/envs/napari_test/lib/python3.10/site-packages/napari/components/viewer_model.py", line 897, in add_image
    layer = Image(data, **kwargs)
  File "/Users/malbert/mambaforge/envs/napari_test/lib/python3.10/site-packages/napari/layers/image/experimental/octree_image.py", line 87, in __init__
    super().__init__(*args, **kwargs)
  File "/Users/malbert/mambaforge/envs/napari_test/lib/python3.10/site-packages/napari/utils/migrations.py", line 59, in _update_from_dict
    return func(*args, **kwargs)
  File "/Users/malbert/mambaforge/envs/napari_test/lib/python3.10/site-packages/napari/layers/image/image.py", line 399, in __init__
    self.refresh()
  File "/Users/malbert/mambaforge/envs/napari_test/lib/python3.10/site-packages/napari/layers/base/base.py", line 1264, in refresh
    self.set_view_slice()
  File "/Users/malbert/mambaforge/envs/napari_test/lib/python3.10/site-packages/napari/layers/base/base.py", line 1029, in set_view_slice
    self._set_view_slice()
  File "/Users/malbert/mambaforge/envs/napari_test/lib/python3.10/site-packages/napari/layers/image/experimental/octree_image.py", line 452, in _set_view_slice
    self._display.tile_size,
AttributeError: 'OctreeDisplayOptions' object has no attribute 'tile_size'
```

### 🌎 Environment

napari: 0.4.18
Platform: macOS-12.6-arm64-arm-64bit
System: MacOS 12.6
Python: 3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:41:52) [Clang 15.0.7 ]
Qt: 5.15.8
PyQt5: 5.15.9
NumPy: 1.26.0
SciPy: 1.11.3
Dask: 2023.10.0
VisPy: 0.12.2
magicgui: 0.8.0
superqt: 0.6.1
in-n-out: 0.1.9
app-model: 0.2.2
npe2: 0.7.2

OpenGL:
  - GL version:  2.1 Metal - 76.3
  - MAX_TEXTURE_SIZE: 16384

Screens:
  - screen 1: resolution 1440x900, scale 2.0
  - screen 2: resolution 1920x1080, scale 2.0
  - screen 3: resolution 1920x1080, scale 2.0

Settings path:
  - /Users/malbert/Library/Application Support/napari/napari_test_cedd16f321c09946af74e2bb09095696d358ee04/settings.yaml
Plugins:
  - napari: 0.4.18 (77 contributions)
  - napari-console: 0.0.8 (0 contributions)
  - napari-svg: 0.1.10 (2 contributions)

### 💡 Additional Context

Error was first observed using a linux OS.

**Comment by Czaki** [comment]
I could confirm that this bug is present on 0.4.19rc0

**Comment by andy-sweet** [comment]
This was also present in v0.4.18 and [seems to be introduced for that release by using the `field` function to specify the `default_factory`](https://github.com/napari/napari/pull/5985/files#diff-eca41a277c6bad79a7fb53909d2b4c62915aeb01401faf9f36cc1c73782fa0d5R73).

After a quick look, I don't know why that breaks. But reverting the change to just assign to an evaluation of `_get_tile_size()` seems to fix the issue, though I assume this means that the default value will not be dynamic.

In general, tiled rendering is experimental and my general sense is that it has unfortunately been broken/unmaintained for a while now.

But we are working to replace these with simpler implementations (https://github.com/napari/napari/issues/4795) that provide more functionality (https://github.com/napari/napari/issues/5561), which are partially available on `main`.

**Comment by m-albert** [comment]
Thank you for looking into this @Czaki and @andy-sweet .

I hadn't been aware of `main` containing the features you mention. Thanks for the hint, I'll try these out.

**Comment by jni** [comment]
I've changed the milestone as I don't think this is critical for 0.4.19 — I hope we have async 3D in 0.5.0! 0.5.1 at the latest. 😊

**Comment by Czaki** [comment]
Should I disable ocotree on 0.4.19?

**Comment by andy-sweet** [comment]
> Should I disable ocotree on 0.4.19?

It's been broken in various ways since at least 0.4.15, so my personal opinion is just to leave it alone and don't spend time on this.

**Comment by psobolewskiPhD** [comment]
This issue is still present in 0.4.19 but octree and related settings were removed from main by : https://github.com/napari/napari/pull/5816

As a result, I'm marking this as `wont fix` and closing--sorry for the inconvenience to anyone that runs into this.
❤️
