### ISSUE TITLE
qt5-tools needed 

### ISSUE THREAD

**Issue by falkben** [napari/napari#637]
## 📚 Documentation

On Arch Linux needed to install [qt5-tools](https://www.archlinux.org/packages/extra/x86_64/qt5-tools/) in order to be able to launch it from within an ipython session.  Perhaps this should be mentioned on install guide?  If so, I could make a PR

**Comment by sofroniewn** [comment]
@falkben thanks for catching this. I'm not familiar with Arch Linux so am unaware of this. Not sure if @jni has any experience. I take it qt5-tools is not the sort of thing that we can be obtained via pip and so added to our `requirments.txt` but must be installed separately for Arch Linux users? If so probably best to document this on the installation guide on our tutorials website - this page here - https://github.com/napari/napari-tutorials/blob/master/tutorials/installation.md

If you can make a PR over at that repo that would be much appreciated

**Comment by jni** [comment]
I know since this morning that @lagru uses Arch, so maybe he has ideas about how we can catch this/ensure the right packages are installed in addition to the pip requirements...? =)

**Comment by lagru** [comment]
I can't reproduce this (yet). 

I tried to reproduce this by temporarily uninstalling qt5-tools with `sudo pacman -Rdd qt5-tools` and installing napari inside a bare bones conda environment:
```
conda create -n napari python=3.7
source activate napari
pip install napari
napari # works
```
I also tried to start napari from ipython with `import napari; napari.Viewer()` which warns that `/home/lg/.miniconda/envs/napari/lib/python3.7/site-packages/qtpy/__init__.py:216: RuntimeWarning: Selected binding "pyqt5" could not be found, using "pyside2"
  'using "{}"'.format(initial_api, API), RuntimeWarning)` but still works. The warning persists after reinstallation of qt5-tools.

Also, vispy raises an deprecation warning when clicking on "New points layer" `/home/lg/.miniconda/envs/napari/lib/python3.7/site-packages/vispy/visuals/markers.py:564: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  ('a_edgewidth', np.float32, 1)])`.

@falkben Could you clarify several questions for me?

- What do you mean by "launch it from within an ipython session". Something like I did?
- qt5-tools has several [dependencies](https://www.archlinux.org/packages/extra/x86_64/qt5-tools/). Did your installation of qt-tools implicitly install anything else which may have been the real missing dependency?
- Can you post your output of `pip list` or if you are using conda `conda list`? 

(@jni I'm not using Arch but Manjaro which hopefully doesn't matter in this case.)

**Comment by lagru** [comment]
> ideas about how we can catch this/ensure the right packages are installed in addition to the pip requirements...?

[The wiki](https://wiki.archlinux.org/index.php/Python#Package_management) recommends :
> If you must use pip, use a virtual environment, or pip install --user to avoid conflicts with packages in /usr. It is always preferred to use pacman to install software.

The latter requires a PKGBUILD (e.g. hosted on the [AUR](https://aur.archlinux.org/)). That way one can specify all non-Python dependencies.

I try to use virtual/conda environments whenever possible. E.g. conda often provides non-Python dependencies such as its its own OS-independent Qt version.

**Comment by falkben** [comment]
Following up:

I was using a virtual environment (not conda).

Looking through my `pacman.log` I installed the following yesterday:

```
[2019-10-28T11:16:54-0400] [ALPM] installed python-sip-pyqt5 (4.19.19-1)
[2019-10-28T11:16:54-0400] [ALPM] installed pyqt5-common (5.13.1-1)
[2019-10-28T11:16:54-0400] [ALPM] installed python-pyqt5 (5.13.1-1)
[2019-10-28T11:21:27-0400] [ALPM] installed qt5-tools (5.13.1-2)
```

Only after installing qt5-tools could I get ipython to start napari (however it was working from command line).  Perhaps I only just needed to restart my shell/environment and `qt5-tools` is not in fact needed.  **I have removed qt5-tools and have no problems now starting it from an ipython session.**

I was starting napari slightly differently, but don't think that was causing the problem:

```python3
ipython --gui=qt
Python 3.7.4 (default, Oct  4 2019, 06:57:26) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.9.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.                                                                                                                                                                                                                                     
In [1]: import numpy as np                                                                                                                                                                                                                                                                                                                             

In [2]: import napari                                                                                                                                                                                                                                                                                                                                  

In [3]: data = np.random.randint(0, 255, (16, 512, 512), dtype='uint8')                                                                                                                                                                                                                                                                                

In [4]: napari.view_image(data)                                                                                                                                                                                                                                                                                                                        
Out[4]: <napari.viewer.Viewer at 0x7f6ca10aab90>
```

Since I cannot reproduce, I am closing this issue, and will make a PR removing this info from the tutorials repo.  Thanks for making this and sorry for the confusion!

**Comment by sofroniewn** [comment]
Ok, no worries @falkben and thanks for making the issue / trying to figure it out. Maybe someone else will see it and it will help them too. If you do run into more problems feel free to reopen

**Comment by lagru** [comment]
@falkben By the way do you have UI issues to? Notice the cramped sliders in the top-left corner or the file dialog with perhaps some room for UI improvement. I doubt this looks as intended.

![image](https://user-images.githubusercontent.com/20140352/67802834-34389680-fa8c-11e9-993a-89a6b16b78ba.png)

Just trying to determine if it's my particular setup or just a general problem for Arch-based OSs.

**Comment by falkben** [comment]
I do not.  I'm on Gnome/Wayland.  Looks like you are on X11?

**Comment by jni** [comment]
@lagru I think that is a known issue with styling on HiDPI displays (or non-HiDPI, I forget :joy:): #530 If you can help here it would be massively appreciated!
