### ISSUE TITLE
Transform mode problem when zoomed out on multiscale layer

### ISSUE THREAD

**Issue by m-albert** [napari/napari#6382]
### 🐛 Bug Report

The transform box adopts a wrong shape when zooming out on a multiscale layer.

### 💡 Steps to Reproduce

```python
import napari
from skimage import data
from skimage.transform import pyramids

im = data.astronaut()[:,:,0].astype(float)

viewer = napari.Viewer()
layers = viewer.add_image([im] + [pyramids.pyramid_reduce(im, downscale=s) for s in [2]])

viewer.layers.selection.active.mode = 'transform'

viewer.camera.zoom = 0.1
```

Screenshot:

<img width="144" alt="image" src="https://github.com/napari/napari/assets/12528388/cd14ed6f-ec19-437b-b899-6a8456d8e135">

### 🌎 Environment

napari: 0.5.0a2.dev413+gae384aec
Platform: macOS-12.6-arm64-arm-64bit
System: MacOS 12.6
Python: 3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:41:52) [Clang 15.0.7 ]
Qt: 5.15.8
PyQt5: 5.15.9
NumPy: 1.26.1
SciPy: 1.11.3
Dask: 2023.10.0
VisPy: 0.14.1
magicgui: 0.8.0
superqt: 0.6.1
in-n-out: 0.1.9
app-model: 0.2.2
npe2: 0.7.3

OpenGL:
  - GL version:  2.1 Metal - 76.3
  - MAX_TEXTURE_SIZE: 16384

Screens:
  - screen 1: resolution 1440x900, scale 2.0
  - screen 2: resolution 1920x1080, scale 2.0
  - screen 3: resolution 1920x1080, scale 2.0

Settings path:
  - /Users/malbert/Library/Application Support/napari/napari_main_613533f96f8fd75b0ca19a87437ef7196a25cf0a/settings.yaml
Plugins:
  - napari: 0.5.0a2.dev413+gae384aec (77 contributions)
  - napari-console: 0.0.9 (0 contributions)
  - napari-manual-transforms: 0.0.3 (2 contributions)
  - napari-svg: 0.1.10 (2 contributions)
  - napari-threedee: 0.0.12 (26 contributions)

**Comment by psobolewskiPhD** [comment]
Thanks for the reproducer, I can confirm on 0.4.19rc1.
Whats fun is zooming in and out and watching the box pop out when the multiscale level switches.
Worse yet, once the box pops out, you can't interact with the handles.

**Comment by Czaki** [comment]
Does this should be fixed on 0.4.19?

**Comment by psobolewskiPhD** [comment]
I dunno; it's not exposed in the gui and a pretty niche thing (multiscale **and** the transform mode)—I think?
I think the labels issue is a bigger deal?

Not sure how easy the fix is -- it could be fairly simple the like labels one, but it might be a band-aid. I think we need to look into multiscale more carefully and try and get some more robust solutions in place for 0.5.0?

**Comment by m-albert** [comment]
Thanks for looking into this :)

I was looking into the functionality to manually guide / correct the registration of correlative fluorescent - cryo-EM datasets (visualization of the latter strongly benefits from the multiscale capability). Don't have something nice to show at this point yet though.

**Comment by Czaki** [comment]
I have prepared an initial patch for this, but I spot a second bug. So it delay PR.

**Comment by Czaki** [comment]
The second bug is not fixed, but it looks much more problematic than I expected, so I open PR to fix only this bug.

**Comment by psobolewskiPhD** [comment]
Don't forget to make an issue for the 2nd one 😄
