### ISSUE TITLE
Labels layer is lagging in 3d for big data

### ISSUE THREAD

**Issue by Czaki** [napari/napari#6397]
### 🐛 Bug Report

The original bug report is here https://forum.image.sc/t/request-for-testing-napari-0-4-19-release-candidate/87972/2?u=gbokota

In general, if user loads a big image, goes in 3D, and try to rotate, then the view lags. 

For the data from `napari-brainreg` plugin, the first example is small and does not reproduce the error on my machine. 

If I zoom that structure fills the whole space, then rotation starts working normally. 

But when I zoom out (structure is smaller) the lag is bigger and bigger. 

As I check the bug does not depend on the shader implementation (I have applied a simple shader, the same as for the image, and it is still present). 

So it looks like some obsolete calculations are performed for empty voxels. 

But I cannot find which change is responsible as whole shaders is executed under `if floatNotEqual(val, 0)` clause. 

The 3308 solves many problems so it will be  really nice to solve this issue. 

### 💡 Steps to Reproduce

1. install napari-brainreg 
2. select non-first dataset
3. change do 3d mode 
4. observe lagging interface when rotate. 

### 💡 Expected Behavior

same performance or better than in 0.4.18

### 🌎 Environment

Double check with bisect points that the bug was introduced in #3308

### 💡 Additional Context

@perlman @brisvag @jni

**Comment by psobolewskiPhD** [comment]
The plugin is `[brainrender-napari](https://pypi.org/project/brainrender-napari)` if anyone wants to test.

**Comment by jni** [comment]
Thanks for the initial investigation @Czaki! The background thing is very interesting and makes me hopeful that there is a simple fix.

Anyone want to pair with me on this in the coming days? In particular @brisvag as our resident OpenGL/VisPy guru I'd love it if you could make some time for it! 🙏 I think it's very important to fix this before finalising 0.4.19 so it's pretty urgent... Thanks!

**Comment by perlman** [comment]
🤔 Very interesting... I feel like I have a target ton my back :-P

@jni I might have time this week. I've forgotten how we debugged the shaders before, but I think this should be easy to identify.

**Comment by jni** [comment]
"I think this should be easy" — sheesh, way to *paint* a big-ass target on your own back! 🎯😂😂😂

**Comment by brisvag** [comment]
Already paired with @Czaki a bit on this, and I'm quite confused. I don't know if I'll have time in the coming week... Hopefully @perlman can figure it out 🙏

**Comment by Czaki** [comment]
I may fund such time after weekend.

**Comment by perlman** [comment]
@jni I said to identify, not fix! 😆  I'm looking back at where we used a null-shader in some of the vispy debugging.

**Comment by jni** [comment]
Yeah but @Czaki has already tried short-circuiting the shader to no avail. 😬 Anyway, let's see how we go!

**Comment by Czaki** [comment]
I test shader for labels volume (teture lookup). But it is part of bigger shader that uses raytracing.

**Comment by Czaki** [comment]
I do a comparison of shaders code (`Volume.node.shared_program._programs["program0"].frag.compile()`). I do not find any significant difference.

I also find that currently, `GPUScaledTextured3D` is used when 0.4.18 uses `CPUScaledTexture3D`  but docstrings suggest that it only makes a difference in sending data to GPU. 

It is caused by the change of `texture_format` from `None` to `'r32f'` in the `VispyLabelsLayer` constructor.

**Comment by jni** [comment]
gdi, that's it @Czaki @perlman — it's the texture format. 😭 

Pre 3308: labels (could be uint8, uint32, whatever) -> scale to [0, 1] on the CPU -> *discretise as 8 bit and send to GPU* (I remember something about VisPy doing this, @brisvag can probably confirm) -> display. (This btw explains why we were so heavily aliased even if we increased the number of colors in the colormap.) This means that **the texture on the GPU was 8 bit.**

Post 3308: labels -> convert to float32 -> send to gpu as float32 texture (that's the 'r32f' texture format) -> display.

This would explain the performance — I can imagine that sampling from a float32 texture during ray tracing is much more expensive than sampling from a uint8 texture.

I don't know whether the following proposed solution would work:
- send two textures to the GPU:
 - a uint8 binary texture which contains label/no label info. 
 - a float32 texture that has the label ID. When we hit a ray in the first texture, we check the label ID in the second texture.
- Do the ray tracing on the uint8 texture. Then, when we hit a label,
- Check the label ID for that position in the second texture.

*Most* samples in a 3D scene are empty, so this should give you a nice speedup. The downside is that we are now using 5x as much VRAM in the new regime as pre-3308 (btw @Czaki this also explains why you didn't notice the decreased CPU cost — your RAM->VRAM transfer is 4x as big post-3308, so that might be a limiting factor for that machine config).

However, I think that's probably worth the cost. In the future, we can optimise things so that if a user has a uint8 labels volume then we use a uint8 texture format, and so on.

**Comment by jni** [comment]
@Czaki one way to check this hypothesis is to monitor your VRAM pre and post 3308 and check that it's 4x higher now.

**Comment by jni** [comment]
If you are doing things on the CPU you can use something like this:

```
seed = np.random.default_rng().integers(0, 256, dtype=np.uint8)

view = data.view(np.uint8).reshape(data.shape + (arr.itemsize,))
reduced = np.where(
    data != 0,
    np.logical_xor.reduce(view, axis=-1, initial=seed),
    np.uint8(0),
)
```

If I remember correctly, when I tried this it was slower than the `low_discrepancy_image` that we used prior to #3308, but that might not matter since #5732.

It doesn't help with the direct colormap either. 😕

**Comment by Czaki** [comment]
I have done a basic replacement to use uint8 and the performance problems look resolved. It is required to generalize code now.

**Comment by Czaki** [comment]
Current state. I got proper coloring. but currently limited only to 255 colors and do not work with direct colormap.

https://github.com/napari/napari/assets/3826210/75b9a694-a537-4c26-b2c5-aae199cc816c

**Comment by jni** [comment]
Gorgeous, @Czaki! 😍 Do you want to raise a draft PR? Might speed up review later if we can start to see what it looks like.

Sorry this fell all on you, my week ended up being crazy but I should be much freer the coming weeks.

**Comment by Czaki** [comment]
@jni. Yesterday, it was in a fragile state. But today, I got it stable enough to open draft PR and allow people to play with it. So #6411 is opened

Could someone ask the original author (on image.sc) to test the solution?  With provided instructions on how to install napari from the branch and information that he should use a separate environment as the main branch contains significant changes in settings.  

I also have an idea of how to do similar things in direct mode, but it will require some tests if transformation is fas enough (one option is to use sparse matrices).

**Comment by psobolewskiPhD** [comment]
Do you have a programmatic way to generate a problem layer and test or have you been just using the plugin.

**Comment by Czaki** [comment]
I use plugin.
But bug presence depends on your configuration.

There is a script from lorenzo 
```python
import napari
import numpy as np
v = napari.Viewer(ndisplay=3)
a = np.random.randint(0, int(1e9), (500, 800, 800), dtype=np.uint32)
b = np.where(a < 1e6, a, 0)
v.add_labels(b)
```
As original data lead to crash napari on his machine (lack of VRAM as I understand) 
You may need to adjust size of cube to reproduce

**Comment by psobolewskiPhD** [comment]
Hmmm...
I tried with 600, 1200, 1200 and it takes some time to make the layer and python takes 20 Gb of RAM, but I get ~10 FPS minimum and >30 when i zoom out. Further zoomed out is better fps.
(this is on main not RC2, but shouldn't matter? can't get the fps monitor example to work in 0418 or 0419)

**Comment by Czaki** [comment]
On 0.4.18 you may use NAPARI_PERF=1 env variable. Main and 0.4.19 requires bugfix.

**Comment by Czaki** [comment]
> With #6411 fps seems similar to me. I guess I need to make bigger cube? I wonder if this is advantage of my M1 integrated GPU sharing RAM/VRAM.

it may happen that on your GPU there is no difference with processing uint8 and float32 voxel type. Then still #6411 is reducing memory usage.

**Comment by Czaki** [comment]
The #6411 is ready for review
