### ISSUE TITLE
[Windows] Drag&drop doesn't work if opened as admin

### ISSUE THREAD

**Issue by KonradDanielewski** [napari/napari#6399]
### 🐛 Bug Report

When using napari run from the terminal with administrative privileges the drag&drop doesn't work. It doesn't produce any error it just doesn't allow for drag&drop at all showing the crossed circle cursor. 

It's a very unusual issue, it works normally when not running as admin. I prefer to always open my terminal as admin to avoid issues with saving data to some directories.

### 💡 Steps to Reproduce

1. Open Anaconda Prompt on Windows as administrator
2. `activate napari-env`
3. `napari`
4. Try to drag&drop

### 💡 Expected Behavior

Drag&drop to load the dropped image

### 🌎 Environment

napari: 0.4.18
Platform: Windows-10-10.0.19045-SP0
Python: 3.9.18 | packaged by conda-forge | (main, Aug 30 2023, 03:40:31) [MSC v.1929 64 bit (AMD64)]
Qt: 5.15.2
PyQt5: 5.15.10
NumPy: 1.26.1
SciPy: 1.11.3
Dask: 2023.10.1
VisPy: 0.12.2
magicgui: 0.8.0
superqt: 0.6.1
in-n-out: 0.1.9
app-model: 0.2.2
npe2: 0.7.3

OpenGL:
  - GL version:  4.6.0 NVIDIA 537.58
  - MAX_TEXTURE_SIZE: 32768

Screens:
  - screen 1: resolution 1920x1080, scale 1.0

Settings path:
  - C:\Users\kdani\AppData\Local\napari\napari-env_2e626a790d60e92905f0f9db9afaed3db3f38604\settings.yaml
Plugins:
  - napari: 0.4.18 (77 contributions)
  - napari-console: 0.0.9 (0 contributions)
  - napari-svg: 0.1.10 (2 contributions)

**Comment by dalthviz** [comment]
Hi there, I think this was also reported for Spyder a couple of years ago: https://github.com/spyder-ide/spyder/issues/11447. The main conclusion was that due to Windows security policies you can't do a drag and drop if the apps have different levels of integrity/privileges (admin vs non-admin). For more details you can check: https://superuser.com/a/59106

**Comment by psobolewskiPhD** [comment]
Yeah, my wife runs into this with Photoshop and other programs, so it's not a napari issue per se.

**Comment by KonradDanielewski** [comment]
> Hi there, I think this was also reported for Spyder a couple of years ago: [spyder-ide/spyder#11447](https://github.com/spyder-ide/spyder/issues/11447). The main conclusion was that due to Windows security policies you can't do a drag and drop if the apps have different levels of integrity/privileges (admin vs non-admin). For more details you can check: https://superuser.com/a/59106

Oh, then we can close this. I guess that's another reason to think about switching to another OS. Thank you for the links!
