### ISSUE TITLE
Unable to install new user defined plugins

### ISSUE THREAD

**Issue by deyarpan321** [napari/napari#6404]
hello,
I have downloaded the bundled app version of the Napari 0.4.18 and I am unable to install an user defined plugin (not pre-built in the app) designed by one of my seniors. I am not accustomed to using Python thus relying on the bundled APP version. Can someone please let me know how to proceed.

**Comment by psobolewskiPhD** [comment]
So just to make sure I understand clearly:
You have access to a napari plugin that is in development and isn't published on pypi/napari-hub. And you want to install it into the napari bundle app. Is that correct?
(Same issue as: https://forum.image.sc/t/how-could-i-install-plugin-locally-with-plugin-manager/60563)

If so you should be able to install it using the folder of the plugin if you have it locally or the GitHub repo if you have a public link.
Just open the plugin installer:
Plugins menu > Install/uninstall plugins

Then you will see two panes, top with installed plugins, bottom with available public ones. Below that is a text input box that should say:
`Install by name/url or drop file`

Here you can drag and drop the folder containing the plugin onto that text input box. and click install. If you have a GitHub repository link you can instead paste it into the box with the prefix `git+`
The PR that implemented this has a video:
https://github.com/napari/napari/pull/2319

**Comment by deyarpan321** [comment]
Yes, That is exactly what I wanted to try. However, the bundled app version does not show any options in the plugin drop down menu as install by name/url. The 0.4.18 version that I mentioned.

**Comment by psobolewskiPhD** [comment]
Ok sorry I wasn't clear I can't easily show you at the moment.
In the Plugins menu, the first position at the top should be:
`Install/unistall plugins`
Or something similar, perhaps `Plugin manager`?

Open that which should launch a UI that I described or that you can see in the video link I provided. Look at the bottom of that UI for the text box labeled
`Install by name/url or drop file`

**Comment by psobolewskiPhD** [comment]
Closing, in favor of the docs issue:
https://github.com/napari/docs/issues/354
