### ISSUE TITLE
Weird behavior when trying to set delete and backspace keys as shortcuts with modifiers on some OS+bindings combinations

### ISSUE THREAD

**Issue by dalthviz** [napari/napari#6405]
### 🐛 Bug Report

Seems like a weird behavior exists when setting the delete or backspace keys with modifiers as shortcuts. You can set them but you need to either hold `Ctrl + Delete` until the shortcut is detected or hold `Ctrl` and press `Delete` two times for the shortcut to be detected. This happens on Windows with PyQt5 or PyQt6 but on macOS only with PyQt5. On the other hand, on macOS + PyQt6, things work fotr the modifier + `Delete` but you are not able to set single modifiers shortcuts without holding another modifier key first and then releasing it for the shortcut box to detect the single modifier key being pressed.

Edit: Edited bug report taking into account new findings done while trying to define a reliable way to reproduce this

### 💡 Steps to Reproduce

1. Try to set `Ctrl + Delete` or `Ctrl + Backspace`
2. Shortcut text gets deleted instead of being set or showing a warning about shortcut conflicts

A preview of the behavior:

![delete_backspace_shortcuts](https://github.com/napari/napari/assets/16781833/1b86420e-093c-486a-afc2-d0e5b7bf8f48)

### 💡 Expected Behavior

Using key combinations like `Ctrl + Delete` and `Ctrl + Backspace` should be recognized/settable as shortcuts

As a "workaorund", you need to either hold `Ctrl + Delete` until the shortcut is detected or hold `Ctrl` and press `Delete` two times:

![shortcut_mod_del](https://github.com/napari/napari/assets/16781833/8cd74ef7-3399-4005-a25d-1457f0aa0a61)

### 🌎 Environment

napari: 0.5.0a2.dev425+g899edfe3
Platform: Windows-10-10.0.19045-SP0
Python: 3.10.9 | packaged by conda-forge | (main, Jan 11 2023, 15:15:40) [MSC v.1916 64 bit (AMD64)]
Qt: 5.15.2
PyQt5: 5.15.9
NumPy: 1.25.2
SciPy: 1.9.3
Dask: 2023.10.1
VisPy: 0.14.1
magicgui: 0.7.3
superqt: unknown
in-n-out: 0.1.5
app-model: 0.2.2
npe2: 0.7.3

OpenGL:
  - GL version:  4.5.0 - Build 25.20.100.6444
  - MAX_TEXTURE_SIZE: 16384

Screens:
  - screen 1: resolution 1366x768, scale 1.0
  - screen 2: resolution 1536x864, scale 1.0

Settings path:
  - C:\Users\dalth\AppData\Local\napari\napari-dev_4454fdbf170edefe23827a4bf512389a6806af69\settings.yaml
Plugins:
  - napari: 0.5.0a2.dev425+g899edfe3 (77 contributions)
  - napari-assistant: 0.4.4 (4 contributions)
  - napari-console: 0.0.6 (0 contributions)
  - napari-generic-SIMulator: 0.0.19 (2 contributions)
  - napari-ome-zarr: 0.5.2 (2 contributions)
  - napari-pyclesperanto-assistant: 0.22.1 (51 contributions)
  - napari-skimage-regionprops: 0.10.0 (2 contributions)
  - napari-svg: 0.1.10 (2 contributions)
  - napari-time-slicer: 0.4.9 (2 contributions)
  - napari-tools-menu: 0.1.19 (0 contributions)
  - napari-ui-tracer: 0.2.0.dev0 (2 contributions)

**Comment by dalthviz** [comment]
Thanks for the feedback @psobolewskiPhD ! Checked again with main on Windows and on macOS and I would say that I still can reproduce this but indeed there is a catch here. If I keep `Ctrl` press (or `Cmd` on macOS) and then press again `Delete` I'm able to set the shortcut and get the corresponding warning:

![shortcut_mod_del](https://github.com/napari/napari/assets/16781833/d127e7ce-a676-4062-9afd-2c17bc60be73)

A similar behavior occurs with `Ctrl/Cmd + Backspace` and also is possible to achieve to set the shortcut if you keep pressing the keys until the shortcut is detected (so to reproduce the initial behavior I reported you need to quickly press the keys without holding them).

I guess for these kind of shortcuts then there is a need to do them twice/keep holding the keys pressed until the shortcut is detected? Maybe that's the intended behavior? If that's the case feel free to close this :)

**Comment by psobolewskiPhD** [comment]
I think the reason it sometimes takes two tries is in the info at the bottom: to set delete/backspace you need a cleared out box.
For me—on mac—if the binding box is empty, I can double click and set `modifier`+delete. If there's a setting it takes two tries, but that's because the first try uses delete to clear the existing binding and the 2nd sets it.

**Comment by dalthviz** [comment]
I see, so just as a final check to determine if this needs to be closed or an actual issue exists, what happens if you hold `Cmd` and quickly press and release `Delete` in a cleared out box? In my case, I see the `Cmd` symbol being shown and then deleted. Also, what happens if, while still holding `Cmd`, you press `Delete` again? In my case, the box shows the proper shortcut and the corresponding warning. A preview of that on macOS:

![shortcut_mod_del](https://github.com/napari/napari/assets/16781833/8cd74ef7-3399-4005-a25d-1457f0aa0a61)

If that is expected then we probably should close this and #6406 (or close this and update #6406 to just add more tests cases). Let me know what do you see locally and what do you think!

**Comment by psobolewskiPhD** [comment]
I'm on main ef26ef34b0ddea62ba28047c7f4044d21a0db9e4
I need to double click into the Alternative Keybinding, which gets me the insertion bar (blinking |)
Then pressing command (meta) does nothing, but pressing and releasing backspace or delete results in the proper binding. For the case of delete I get the warning.
I never see just command show-up in the box like you do--which means that modifier-only bindings can't be bound, even though the default for Reset Scroll is a modifier only binding. And indeed I can't get shift or control or option alone do work, but any of them work fist try with backspace or delete.

**Comment by dalthviz** [comment]
This is really strange, not sure what could be happening but even when updating my local repo to the latest main (ef26ef34) I still can experience the same behavior (the one you where able to partially reproduce with 0.4.18) on Windows and macOS. Will try to create a new dev env and see if something changes (maybe some dependency version could be causing this behavior for me :thinking:). Could you share your napari info to see if it is different from the one I have?

<details> <summary> napari info on Windows </summary>

```
napari: 0.5.0a2.dev454+gef26ef34
Platform: Windows-10-10.0.19045-SP0
Python: 3.10.9 | packaged by conda-forge | (main, Jan 11 2023, 15:15:40) [MSC v.1916 64 bit (AMD64)]
Qt: 5.15.2
PyQt5: 5.15.9
NumPy: 1.25.2
SciPy: 1.9.3
Dask: 2023.10.1
VisPy: 0.14.1
magicgui: 0.7.3
superqt: unknown
in-n-out: 0.1.5
app-model: 0.2.2
npe2: 0.7.3

OpenGL:
- GL version: 4.5.0 - Build 25.20.100.6444
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1366x768, scale 1.0
- screen 2: resolution 1920x1080, scale 1.0

Settings path:
- C:\Users\dalth\AppData\Local\napari\napari-dev_4454fdbf170edefe23827a4bf512389a6806af69\settings.yaml
```

</details>



<details> <summary> napari info on macOS </summary>

```
TODO
```

</details>

> Pressing Command key results in the word "Control" printed in the box (should be Meta...so something is off) and delete deletes it.

Regarding 0.4.18 I think some changes where done to the shortcuts handling to show some specific icons per platform but those changes are part only of 0.5.0. If you check with 0.4.19 I think you will see a similar behavior (`Control` being shown instead of the `Cmd` symbol on macOS for example 🤔 )

**Comment by psobolewskiPhD** [comment]
My napari info
```
╰─ napari --info                                                 (napari-dev) ─╯
napari: 0.5.0a2.dev429+g47b9527ef
Platform: macOS-13.3.1-arm64-arm-64bit
System: MacOS 13.3.1
Python: 3.11.6 | packaged by conda-forge | (main, Oct  3 2023, 10:37:07) [Clang 15.0.7 ]
Qt: 6.6.0
PyQt6: 
NumPy: 1.26.1
SciPy: 1.11.3
Dask: 2023.10.1
VisPy: 0.14.1
magicgui: 0.8.0
superqt: 0.6.1
in-n-out: 0.1.9
app-model: 0.2.2
npe2: 0.7.3

OpenGL:
  - GL version:  2.1 Metal - 83.1
  - MAX_TEXTURE_SIZE: 16384

Screens:
  - screen 1: resolution 1680x1050, scale 2.0

Settings path:
  - /Users/piotrsobolewski/Library/Application Support/napari/napari-dev_a1eb8b76ba95fa16ad06e26097b46b8455dfbf0b/settings.yaml
Plugins:
  - napari: 0.5.0a2.dev429+g47b9527ef (77 contributions)
  - napari-console: 0.0.9 (0 contributions)
  - napari-svg: 0.1.10 (2 contributions)
  

```

Only thing that stands out is I have pyqt6 cause I'm on arm64. Let me try with pyqt5 from conda-forge.

**Comment by psobolewskiPhD** [comment]
Boom! with pyqt5 from conda-forge and `pip install -e .[dev]` I get the behavior you show in your videos. So Qt6 is affecting something.
Wait, i'm on python 3.10 now >.<
Let me double check pyqt5/python3.11

**Comment by dalthviz** [comment]
> So Qt6 is affecting something.

Oh that was it! Although on Windows even with PyQt6 I still experience the same behavior, checking on macOS I see now the behavior you have been describing (so no single modifier is shown and the usage of Delete/Backspace + a modifier works without double press or full hold).

> So I think we'd consider the Pyqt6 behavior "correct" and Pyqt5 not?

Checking a little bit more the behavior of PyQt6 on macOS, interestingly if I press and hold two modifier keys and then release one I start seeing the symbol of the modifier key I'm still pressing 🤔

TODO: Preview single modifier macOS

So I would say that for single modifiers shortcuts, the behavior should be the one PyQt5 shows (the single modifier is shown and bindable when pressing Enter or doing any other actions to make the shortcut box loss focus) but for modifiers + Delete/Backspace should be the one PyQt6 shows (the part where a modifier hold + any other key press and release binds the shortcut, including the usage of Delete/Backspace):

![shortcut_behavior](https://github.com/napari/napari/assets/16781833/538c1531-9927-41ae-8ec7-9ed02f21ba7e)

I think the current state of #6406 needs a check to enable offering the behavior described above regardless of OS or PyQt/binding version, but what do you think of things working in that way?
