### ISSUE TITLE
Incorrect logic / impossible conditions  or types in _vispy/layer/base

### ISSUE THREAD

**Issue by Carreau** [napari/napari#6414]
It looks to me like  the following function has impossible logic, or incorrect types:

https://github.com/napari/napari/blob/5ddd515c8a7cc3d8c3039f7af67a674280bc0a2b/napari/_vispy/layers/base.py#L167-L193

`__init__` say:
```
self.overlays: Dict[str, VispyBaseOverlay]
                    ^ I think str is is wrong.
```

and as far as I can tell from `napari/layers/base/base.py`:

```
self._overlays: EventedDict[str, Overlay] = EventedDict()
```

Therefore:

```python

def _on_overlays_change(self):
    ...

    overlay_models = self.layer._overlays.values()

    for overlay in overlay_models: # overlay is of type Overlay as we pick from `.values()`
        if overlay in self.overlays: # this cannot be true, as "in" check for keys. 
            continue

        with self.layer.events._overlays.blocker():
            overlay_visual = create_vispy_overlay(
                overlay, layer=self.layer
            )
        self.overlays[overlay] = overlay_visual # this goes against the keys of `self.overlays[overlay]` being str 
        if isinstance(overlay, CanvasOverlay):
            overlay_visual.node.parent = self.node.parent.parent  # viewbox
        elif isinstance(overlay, SceneOverlay):
            overlay_visual.node.parent = self.node

        overlay_visual.node.parent = self.node
        overlay_visual.reset()

    for overlay in list(self.overlays): 
        if overlay not in overlay_models: # this can't be is overlay is a str.
            overlay_visual = self.overlays.pop(overlay)
            overlay_visual.close()

```

@brisvag I think that's your code from https://github.com/napari/napari/pull/4894, are the types just wrong, the logic incorrect, or am I missing something ?

**Comment by brisvag** [comment]
Types are wrong, and I named the attributes a bit confusingly. `VispyBaseLayer.overlays` is supposed to mirror the implementation of `VispyCanvas._overlay_to_visual`, which handles overlays on the viewer level, instead of layer level. Maybe renaming it to `overlay_to_visual` would help clear the confusion. And the types should mirror those on vispy canvas (`Dict[Overlay, VispyBaseOverlay]`).

**Comment by Carreau** [comment]
Ok, thanks, I'v updated the types as part of https://github.com/napari/napari/pull/6352

**Comment by GenevieveBuckley** [comment]
Should this issue be closed now @Carreau ?
