### ISSUE TITLE
[macOS arm64, pypi pyqt5] ImportError: No Qt bindings could be found.

### ISSUE THREAD

**Issue by dustykeyboard1** [napari/napari#6415]
### 🐛 Bug Report

I am using python 3.10.7 on macOS running M1 max Chip, with macOS 13.5.1. 

I am using a venv environment in VS code with a .ipynb file. I have installed napari[all] multiple times using pip install 'napari[all]' with new environments. I have installed PyQt6 as well. Absolutely nothing is working. I keep getting a ImportError: No Qt bindings could be found error.  

I even downloaded the 'constraints_py3.10.txt' file and ran:

pip install 'napari[all, pyqt]' -c /Users/michaelscoleri/Downloads/constraints_py3.10.txt

That failed miserably with the errors:
WARNING: napari 0.3.3 does not provide the extra 'pyqt5'

all the way down for each version of napari.

### 💡 Steps to Reproduce

import napari
viewer = napari.Viewer(ndisplay=3)
viewer.axes.visible = True
viewer.add_image(data=r, name='r', colormap='green', blending='additive', opacity=.5)
napari.run()

### 🌎 Environment

napari: 0.4.18
Platform: macOS-13.5.1-arm64-arm-64bit
System: MacOS 13.5.1
Python: 3.10.7 (v3.10.7:6cc6b13308, Sep  5 2022, 14:02:52) [Clang 13.0.0 (clang-1300.0.29.30)]
Qt: 6.6.0
PyQt6: 
NumPy: 1.26.1
SciPy: 1.11.3
Dask: 2023.10.1
VisPy: 0.12.2
magicgui: 0.8.0
superqt: 0.6.1
in-n-out: 0.1.9
app-model: 0.2.2
npe2: 0.7.3

OpenGL:
  - GL version:  2.1 Metal - 83.1
  - MAX_TEXTURE_SIZE: 16384

Screens:
  - screen 1: resolution 1512x982, scale 2.0

Settings path:
  - /Users/michaelscoleri/Library/Application Support/napari/3.10_bd8d3bfad0a7c9554c872a298649991e4600026a/settings.yaml
Plugins:
  - napari: 0.4.18 (77 contributions)
  - napari-console: 0.0.9 (0 contributions)
  - napari-svg: 0.1.10 (2 contributions)

### 💡 Additional Context
```
	"name": "ImportError",
	"message": "No Qt bindings could be found.

napari requires either PyQt5 or PySide2 to be installed in the environment.
To install the default backend (currently PyQt5), run \"pip install napari[all]\" 
You may also use \"pip install napari[pyside2]\"for Pyside2, or \"pip install napari[pyqt5]\" for PyQt5",
	"stack": "---------------------------------------------------------------------------
QtBindingsNotFoundError                   Traceback (most recent call last)
File ~/Desktop/Coding/School/Physics/SeniorYear/BlackHoleEnv/lib/python3.10/site-packages/napari/_qt/__init__.py:8
      7 try:
----> 8     from qtpy import API_NAME, QtCore
      9 except Exception as e:

File ~/Desktop/Coding/School/Physics/SeniorYear/BlackHoleEnv/lib/python3.10/site-packages/qtpy/__init__.py:287
    286 except ImportError:
--> 287     raise QtBindingsNotFoundError from None
    288 else:

QtBindingsNotFoundError: No Qt bindings could be found

The above exception was the direct cause of the following exception:

ImportError                               Traceback (most recent call last)
/Volumes/USB31FD/MADNT/MAD_research/NewVisualizations/creating3d_black_hole.ipynb Cell 16 line 1
     <a href='vscode-notebook-cell:/Volumes/USB31FD/MADNT/MAD_research/NewVisualizations/creating3d_black_hole.ipynb#X21sZmlsZQ%3D%3D?line=15'>16</a> # viewer.add_surface((vertices, triangles, vertices), name='sphere')
     <a href='vscode-notebook-cell:/Volumes/USB31FD/MADNT/MAD_research/NewVisualizations/creating3d_black_hole.ipynb#X21sZmlsZQ%3D%3D?line=16'>17</a> print(\"added\")
---> <a href='vscode-notebook-cell:/Volumes/USB31FD/MADNT/MAD_research/NewVisualizations/creating3d_black_hole.ipynb#X21sZmlsZQ%3D%3D?line=18'>19</a> napari.run()

File ~/Desktop/Coding/School/Physics/SeniorYear/BlackHoleEnv/lib/python3.10/site-packages/napari/_event_loop.py:12, in run(**kwargs)
     11 def run(**kwargs):
---> 12     raise exc

File ~/Desktop/Coding/School/Physics/SeniorYear/BlackHoleEnv/lib/python3.10/site-packages/napari/_event_loop.py:2
      1 try:
----> 2     from napari._qt.qt_event_loop import gui_qt, run
      4 # qtpy raises a RuntimeError if no Qt bindings can be found
      5 except (ImportError, RuntimeError) as e:

File ~/Desktop/Coding/School/Physics/SeniorYear/BlackHoleEnv/lib/python3.10/site-packages/napari/_qt/__init__.py:11
      9 except Exception as e:
     10     if 'No Qt bindings could be found' in str(e):
---> 11         raise ImportError(
     12             trans._(
     13                 'No Qt bindings could be found.\
\
napari requires either PyQt5 or PySide2 to be installed in the environment.\
To install the default backend (currently PyQt5), run \"pip install napari[all]\" \
You may also use \"pip install napari[pyside2]\"for Pyside2, or \"pip install napari[pyqt5]\" for PyQt5',
     14                 deferred=True,
     15             )
     16         ) from e
     17     raise
     20 if API_NAME == 'PySide2':
     21     # Set plugin path appropriately if using PySide2. This is a bug fix
     22     # for when both PyQt5 and Pyside2 are installed

ImportError: No Qt bindings could be found.

napari requires either PyQt5 or PySide2 to be installed in the environment.
To install the default backend (currently PyQt5), run \"pip install napari[all]\" 
You may also use \"pip install napari[pyside2]\"for Pyside2, or \"pip install napari[pyqt5]\" for PyQt5"
```

**Comment by psobolewskiPhD** [comment]
So up until very recently, there were no PyQt5 wheels on pypi for arm64. Now they are published, but I've also had issues with them, see:
https://napari.zulipchat.com/#narrow/stream/212875-general/topic/pyq5.20MacOS.20sylicon/near/399992548

When you are doing `pip install napari[all]` you are installing napari with those pyqt5 bindings.

In general for arm64 we recommend using conda, but if you need venv you can try using the experimental pyqt6 bindings which do have functioning wheels on pypi for arm64.
Be sure to make a fresh env and then do:
`pip install "napari[pyqt6_experimental]"`

Don't use [all] in this case and don't try to install into one of your [all] ends, it's likely to still error.

**Comment by dustykeyboard1** [comment]
@psobolewskiPhD It worked, you are the goat. Thanks!

**Comment by psobolewskiPhD** [comment]
Going to close: we don't support `napari[all]` on arm64 macOS. 
At the same time, hopefully it will be fixed soon on the pyqt5 side.
