### ISSUE TITLE
KeyPress not detected depending on selected window area

### ISSUE THREAD

**Issue by gordon-n-stevenson** [napari/napari#6416]
### 🐛 Bug Report

Referencing this bug report on the [forums](https://forum.image.sc/t/napari-not-recognizing-key-press/73268/5), I'm having a similiar issue.

If I don't focus a mouse click on the lower left hand corner of the Napari viewer keypresses aren't recognised

### 💡 Steps to Reproduce

A minimal working example 

```
import napari

viewer = napari.Viewer(title='this is the viewer')

@viewer.bind_key('d')
def _print_keypress(viewer):
    print('key press detected!')
napari.run()
```

Then click on the main window (1)

![fbfae2591b6b7ac97438d007535f2197db82b24b_2_954x750](https://github.com/napari/napari/assets/1923114/bf5c56ca-09ab-40bf-b13e-71cb67513ab2)

Try to detect key presses using 'd'

Then click on the side bar area (2)

Try to detect key presses using 'd'

### 💡 Expected Behavior

I would expect keypresses to be found regardless of pressing, but they are not when the main area (1) is selected

### 🌎 Environment

napari: 0.4.18
Platform: Windows-10-10.0.22621-SP0
Python: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr 5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Qt: 5.15.2
PySide2: 5.15.2.1
NumPy: 1.26.1
SciPy: 1.11.3
Dask: 2023.10.0
VisPy: 0.12.2
magicgui: 0.7.3
superqt: 0.6.1
in-n-out: 0.1.9
app-model: 0.2.2
npe2: 0.7.2

OpenGL:
- GL version: 4.6.0 - Build 31.0.101.4502
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1080, scale 2.0
- screen 2: resolution 1920x1080, scale 2.0

Settings path:
- C:\Users\gordo\AppData\Local\napari\.venv_c05b69228fb815e80d4b7eeba47eb2b74c51cefa\settings.yaml

**Comment by psobolewskiPhD** [comment]
I can reproduce this on 0.4.18 & 0.4.19RC2 but only for the case of no image open, so the splash screen showing.
If I open an image it behaves as expected, could you try with an image open?
Or is interacting with an empty canvas a key part of your use-case?

**Comment by gordon-n-stevenson** [comment]
Agreed I reproduce the behaviour you observe it works fine with an image open but not 
with no image open.

I can work with this issue as is but it would be nice to have as lots of example code doesn't mention you need an image open for these events to be detected.

https://forum.image.sc/t/napari-not-recognizing-key-press/73268/8?u=gnstevenson

Is there a rc3 candidate to test this? As suggested above? I have tried with 0.4.19RC2 and

**Comment by Czaki** [comment]
Ok. My bad. I remember that there were three rc releases but forgot that I started numbering them from 0. Yes, rc2 is last one.

**Comment by gordon-n-stevenson** [comment]
All good! Appreciate the help is there any pointers toward what I can do to fix/debug the issue?

**Comment by Czaki** [comment]
@gordon-n-stevenson I did a small debug and I think that I spotted the source of the problem. Could you test #6419?

**Comment by gordon-n-stevenson** [comment]
Great! I believe I've got this working now and it fixes this bug.

Only thing I'm observing now is that if you mouse click on the mainwindow (1) without an image loaded you won't get any keypress events processed. Do you see this too?

**Comment by Czaki** [comment]
> Only thing I'm observing now is that if you mouse click on the mainwindow (1) without an image loaded you won't get any keypress events processed. Do you see this too?

No. After clicking on the window, I got the proper handling. You may try to take inspiration from #6419 to try to spot the place where key events are handled.
