### ISSUE TITLE
BUG: App-model `status_tip` do not appear

### ISSUE THREAD

**Issue by lucyleeow** [napari/napari#6421]
### 🐛 Bug Report

App-model `Action`s have a `status_tip` field, which I assume provides text that would be shown next to the cursor when you hover over menu items related to the `Action`. However they do not seem to appear.

Ref: https://github.com/napari/napari/pull/4991#discussion_r1383648103

### 💡 Steps to Reproduce

Any of the converted menus (files, help, view)

### 🌎 Environment

Seems to be the case for linux and mac.

**Comment by lucyleeow** [comment]
cc @aganders3 @DragaDoncila

**Comment by lucyleeow** [comment]
Ah so it is not a 'tool tip' but a 'status tip' and appears at the bottom status bar:

![Screenshot_2023-11-10_14-57-51](https://github.com/napari/napari/assets/23182829/6b3af509-41b7-47e2-9a46-4ba57e5335f5)

I think this is right and will close but let me know if not @DragaDoncila @aganders3

**Comment by aganders3** [comment]
I still don't see the message on my machine, but maybe it's just a macOS thing?

**Comment by psobolewskiPhD** [comment]
> I still don't see the message on my machine, but maybe it's just a macOS thing?

Also macOS here and I also don't see those infos in the status bar at the bottom.

**Comment by Czaki** [comment]
I think that the source of the problem is using the native menu. So, if such a menu does not emit events, it is impossible to handle it and show text.

**Comment by aganders3** [comment]
Thanks for confirming. The [Qt docs](https://doc.qt.io/qt-6/macos-issues.html#menu-actions) provide a possible hint, but I don't feel that fixing this would be very high-impact:
> [QMenu](https://doc.qt.io/qt-6/qmenu.html) objects used in the native menu bar are not able to handle Qt events via the normal event handlers. Install a delegate on the menu itself to be notified of these changes.

**Comment by psobolewskiPhD** [comment]
Not sure I've ever seen a tooltip for a (textual) menu item...
After all, you're mousing over text to get text? Normally tooltips are for icons/click target areas and/or elided text where meaning may be unclear.
I think for menu items, the status bar info is reasonable? Ideally users learn that it's a reliable area to look for extra context/information.
