### ISSUE TITLE
Napari in ubuntu 22 (WSL)  loads empty...?

### ISSUE THREAD

**Issue by pconesa** [napari/napari#6434]
### 🐛 Bug Report

I have a dedicated env for napari and blik (Lorenzo has seen this beheaviour)

And I was launching napari with blik passion a tomogram (3d volume in mrc format)

Although it should open and it does on linux systems, in WLS it just opens napari without any error message. 100% muted.

### 💡 Steps to Reproduce

Intall napari and blick on WLS ubuntu22

run something similar to this:

conda activate blik-0.5.5 && napari -w blik --  /home/pconesa/ScipionUserData/projects/TestTomoSubSetsTomograms/Runs/000571_ProtImportTomograms/extra/64K_defocus-2_tomo_2_wedge.mrc

### 💡 Expected Behavior

Loas the tomogram or a list of them?

### 🌎 Environment

(blik-0.5.5) pconesa@DESKTOP-Q5K5BNN:~$ napari --info
napari: 0.4.19rc2
Platform: Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
System: Ubuntu 22.04.2 LTS
Python: 3.10.13 | packaged by conda-forge | (main, Oct 26 2023, 18:07:37) [GCC 12.3.0]
Qt: 5.15.2
PyQt5: 5.15.10
NumPy: 1.26.1
SciPy: 1.11.3
Dask: 2023.10.1
VisPy: 0.14.1
magicgui: 0.8.0
superqt: 0.6.1
in-n-out: 0.1.9
app-model: 0.2.2
npe2: 0.7.3

OpenGL:
  - GL version:  4.1 (Compatibility Profile) Mesa 23.0.4-0ubuntu1~22.04.1
  - MAX_TEXTURE_SIZE: 16384

Screens:
  - screen 1: resolution 2560x1600, scale 1.0

Settings path:
  - /home/pconesa/.config/napari/blik-0.5.5_219889d0a2835b5c7068d8548ce58f68386be361/settings.yaml
Plugins:
  - blik: 0.6.0 (30 contributions)
  - napari: 0.4.19rc2 (77 contributions)
  - napari-console: 0.0.9 (0 contributions)
  - napari-label-interpolator: 0.1.0 (2 contributions)
  - napari-properties-plotter: 0.2.2 (2 contributions)
  - napari-properties-viewer: 0.0.2 (2 contributions)
  - napari-svg: 0.1.10 (2 contributions)

**Comment by psobolewskiPhD** [comment]
Could you clarify what you mean by:
> it just opens napari without any error message. 100% muted.

Does a layer appear in the layer list but is rendered as a blank canvas?
Does literally nothing appear, a totally vanilla viewer, equivalent to just running `napari`?

Also can you try running just `napari` from terminal and open a sample image (File menu).

**Comment by pconesa** [comment]
I've just tried to to run just napari and then open a png -->

<img width="644" alt="image" src="https://github.com/napari/napari/assets/785633/9f388152-520b-4eac-b1eb-dfde025ad9ff">

It also does not repaint on resize properly.

It is like a vanilla napari open.... but then you can't do anything. Note: ubuntu 22 on WSL comes quite empty in terms of libraries and GUI stuff... I might miss some of them that are critical to napari?

Other python QT app I got runs fine.

**Comment by psobolewskiPhD** [comment]
When you say `you can't do anything`: do menus work? 
Like `File > Open Sample...`, does the menu function correctly, but then if you select an image nothing shows up on the canvas? Does the welcome screen disappear (the `Drag image(s) here to open`) and replace with a black screen?

I'm not sure how helpful this is, but you can see what system libraries are required on Ubuntu on CI for napari to run:
https://github.com/tlambert03/setup-qt-libs#setup-qt-libraries-for-github-ci
I'm not sure how you can see what you have installed or if any of that is missing though, sorry.

**Comment by willingc** [comment]
@pconesa Thanks for the issue report, and @psobolewskiPhD for the troubleshooting. 

Seeing no further activity in a year including no further reports, I'm going to close out this issue. Please let us know if you wish to keep it open. Thanks! :sunny:
