### ISSUE TITLE
Tooltip of elided long layer names doesn't give full name when coming from a plugin

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari/napari#6435]
### 🐛 Bug Report

When having layers with long names, the names are elided, which is good...
Normally when mousing over them, the full name is provided in the tool tip.
This works for example for a sample image -- e.g. astronaut renamed something really long.
**But**, when using a plugin to open, after mousing over them, the full layer name is not provided, instead info about the filename and plugin is provided -- useful, but not exactly the most helpful when layers have long names that start the same. Especially since this is also provided when mousing the canvas. E.g.:
![image](https://github.com/napari/napari/assets/76622105/0678859e-fc90-4d6f-9374-954fc0855e4f)

The only way to see the full name is to expand the layer list, which is annoying.

### 💡 Steps to Reproduce

1. open an image file with a plugin -- can be any file, e.g. a jpg or png using `builtins`
2. make the name of the layer really long, enough to elide, e.g. add `qwertyuiopasdfghjklzxcvbnmqwertyuiop`
3. mouse over the layer name

### 💡 Expected Behavior

Disambiguating long-named layers is really important. Knowing the file name of origin and plugin is nice.
Seeing the full text of an elided label should be preserved when a plugin is used.
Ideally, when using a plugin the tooltip would *gain* the file name and plugin name as a 2nd line, with the full layer name being still provided.

### 🌎 Environment

napari: 0.4.18
Platform: macOS-13.6.2-arm64-arm-64bit
System: MacOS 13.6.2
Python: 3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:41:52) [Clang 15.0.7 ]
Qt: 5.15.8
PyQt5: 5.15.9
NumPy: 1.25.2
SciPy: 1.11.1
Dask: 2023.8.0
VisPy: 0.12.2
magicgui: 0.7.2
superqt: unknown
in-n-out: 0.1.8
app-model: 0.2.0
npe2: 0.7.2

OpenGL:
  - GL version:  2.1 Metal - 83.1
  - MAX_TEXTURE_SIZE: 16384

Screens:
  - screen 1: resolution 2056x1329, scale 2.0
  - screen 2: resolution 1920x1200, scale 1.0

Settings path:
  - /Users/sobolp/Library/Application Support/napari/napari-418_d279d6cf5d4193876ed97858e757fe322037331b/settings.yaml
Plugins:
  - napari: 0.4.18 (77 contributions)
  - napari-aicsimageio: 0.7.2 (2 contributions)
  - napari-animation: 0.0.7 (2 contributions)
  - napari-console: 0.0.8 (0 contributions)
  - napari-ome-zarr: 0.5.2 (2 contributions)
  - napari-svg: 0.1.10 (2 contributions)
  - napari-workshop-browser: 0.0.3 (2 contributions)
  - ome-types: 0.4.1 (2 contributions)

**Comment by Czaki** [comment]
@psobolewskiPhD the tooltip is generated here:

https://github.com/napari/napari/blob/9d0c449553eaf1acc3be1bf9bc0c8b3eec05afc6/napari/_qt/containers/qt_layer_model.py#L37-L41

If you have a better idea of how it should look, then it may be simple PR, that could be cherry-picked to 0.4.18. 

I do not have the code to determine if label is elited, but we could always add this information.
