### ISSUE TITLE
Shuffle colors doesn't mix labels in auto mode anymore

### ISSUE THREAD

**Issue by jni** [napari/napari#6448]
### 🐛 Bug Report

Because we modulo the labels by the number of colors in auto mode since #6179, hitting the shuffle button doesn't actually mix up the labels anymore: labels that are `num_colors` apart end up being the same color no matter how many times we hit shuffle.

### 💡 Steps to Reproduce

```python
import numpy as np
import napari

period = 49

labels = np.arange(1, 1 + 3 * period).reshape(3, period)
viewer = napari.Viewer()
layer = viewer.add_labels(labels)

napari.run()
```

Then hit shuffle a few times.

Before #6179, (29287c50e), you get:

<img width="1509" alt="Screenshot 2023-11-14 at 8 48 33 pm" src="https://github.com/napari/napari/assets/492549/4d44612f-27b3-4005-b0b2-a316d8742882">

If you find two markers that have the same color, if you hit shuffle, *often* they will then have different colors. (This is not always the case, but that's expected.)

After #6179 (2f6c70737), you get:

<img width="1509" alt="Screenshot 2023-11-14 at 8 48 53 pm" src="https://github.com/napari/napari/assets/492549/141cbb12-d0cb-4f2c-bae2-1940f34bb2ed">

It doesn't matter how many times you hit shuffle, you will always vertical lines.

### 💡 Expected Behavior

Shuffle should result, with high probability, in labels that have the same color then having different color.

### 🌎 Environment

(I've omitted the plugins since this is unrelated to any plugin.)

```
napari: 0.5.0a2.dev472+ge6cf9239d
Platform: macOS-13.5-arm64-arm-64bit
System: MacOS 13.5
Python: 3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:25:13) [Clang 14.0.6 ]
Qt: 5.15.4
PyQt5: 5.15.7
NumPy: 1.24.4
SciPy: 1.9.0
Dask: 2023.10.1
VisPy: 0.12.2
magicgui: 0.7.3.dev15+geff4e27
superqt: 0.5.4
in-n-out: 0.1.8
app-model: 0.2.0
npe2: 0.7.2

OpenGL:
  - GL version:  2.1 Metal - 83.1
  - MAX_TEXTURE_SIZE: 16384

Screens:
  - screen 1: resolution 1800x1169, scale 2.0

Settings path:
  - /Users/jni/Library/Application Support/napari/all_f332943dd4a538ce2ff3134fd0ff74396d8d8b23/settings.yaml
Plugins:
  - napari: 0.5.0a2.dev188+gefa55a5bd (77 contributions)
```

**Comment by Czaki** [comment]
> If you find two markers that have the same color, if you hit shuffle, _often_ they will then have different colors. (This is not always the case, but that's expected.)

Yes. These is expected changes of fixing bugs that lead to showing different color in the color picker and on the image. As shuffle just permutate this 49 colors.

**Comment by jni** [comment]
@Czaki that was not the point of the fix: the point of the fix was to ensure that the colors match between the picker and the image. That does not imply that different labels should have the same color. Of course, some bug fixes introduce other bugs, this is not a new problem in software engineering. 😂 

The number one job of the labels layer is to show different labels in a segmentation differently. Obviously, there are often more labels than there are perceptually-different colors, so it's not always possible, *but* the purpose of the shuffle button is to change the colors in such a way that labels that were indistinguishable are separated after a shuffle with high probability — so you can quickly tell, for example, if two cells that look the same are actually a false-merge/undersegmentation error or just a case of an unlucky color seed.

**Comment by jni** [comment]
See #6460 for a sketch of what it looks like.

Here's a wonky idea:
- apply #6449 to the 0.4.19 branch, not main
- deprecate `num_colors` in #6449, in favour of for example `init_num_colors`; or maybe even just `colormap`.
- document that in the future `shuffle` will result in the colormap being sampled to some new prime basis.
- merge a cleaner (because we don't have to preserve `num_colors` exactly) version of #6460 into main

The rationale is: auto colors are not meant to be strictly specified — they are merely a way to make it as easy as possible to distinguish labels in the data. So having a strict preservation of `num_colors` doesn't really make sense, when it conflicts with the basic idea of distinguishing labels.
