### ISSUE TITLE
Bump min magicgui version to 0.7.0

### ISSUE THREAD

**Issue by lucyleeow** [napari/napari#6454]
## 🧰 Task

I think `magicgui.type_map` module was created in https://github.com/pyapp-kit/magicgui/pull/497 (with files moved from `magicgui/` to `magicgui/type_maps/`), which was added in version [0.7.0](https://github.com/pyapp-kit/magicgui/releases/tag/v0.7.0.rc1).

Types such as [`MagicFactory`](https://pyapp-kit.github.io/magicgui/api/magic_factory/#magicgui.type_map._magicgui.MagicFactory) now live in `magicgui.type_map._magicgui.MagicFactory`. Can we bump min magicgui version so we can import these?

Note, for our CIs:

> Looks like in the requirements we list magicgui>=0.3.6 which, for headless tests, gives us magicgui==0.3.6 but for others, it gives us magicgui==0.8.0 (possibly because we depend on something else that's bumped the requirement for magicgui? 

ref: https://github.com/napari/napari/pull/4991#issuecomment-1811355084

**Comment by lucyleeow** [comment]
cc @DragaDoncila @Czaki

**Comment by Czaki** [comment]
yes
