### ISSUE TITLE
[PyQt6, Qt6] Unable to restore default keybindings: odd dialog

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari/napari#6490]
### 🐛 Bug Report

With python 3.11 (main napari) and 3.10 (napari 0.4.18) and PyQt6 (6.6 or 6.5.1) but not PyQt5, when I try to reset keybindings to defaults, I get a different dialog that only has cancel.
<img width="1088" alt="image" src="https://github.com/napari/napari/assets/76622105/b2519c27-bebb-48f8-9a06-2916a6b4d518">
It has no option to confirm, yes--restore defaults.

### 💡 Steps to Reproduce

1. Install napari either main or 0.4.18 in an env with PyQt6 >6.5
2. Open Preferences > Shortcuts
3. Click Restore defaults

### 💡 Expected Behavior

The normal dialog should appear and it should be possible to reset the keybindings.

### 🌎 Environment

napari: 0.4.18
Platform: macOS-13.3.1-arm64-arm-64bit
System: MacOS 13.3.1
Python: 3.10.13 | packaged by conda-forge | (main, Oct 26 2023, 18:09:17) [Clang 16.0.6 ]
Qt: 6.5.1
PyQt6: 
NumPy: 1.26.0
SciPy: 1.11.3
Dask: 2023.10.1
VisPy: 0.12.2
magicgui: 0.8.0
superqt: 0.6.1
in-n-out: 0.1.9
app-model: 0.2.2
npe2: 0.7.3

OpenGL:
  - GL version:  2.1 Metal - 83.1
  - MAX_TEXTURE_SIZE: 16384

Screens:
  - screen 1: resolution 1680x1050, scale 2.0

Settings path:
  - /Users/piotrsobolewski/Library/Application Support/napari/napari-418_ff44c429019beeb6bb1d5a86a0c4c143d37e89da/settings.yaml
Plugins:
  - bfio: 2.3.0 (4 contributions)
  - napari: 0.4.18 (77 contributions)
  - napari-aicsimageio: 0.7.2 (2 contributions)
  - napari-animation: 0.0.8.dev3+g05122db.d20231119 (2 contributions)
  - napari-console: 0.0.9 (0 contributions)
  - napari-ome-zarr: 0.5.2 (2 contributions)
  - napari-svg: 0.1.10 (2 contributions)
  - ome-types: 0.4.2 (2 contributions)

**Comment by psobolewskiPhD** [comment]
Would be great for someone to test on not-macOS! ❤️

**Comment by jni** [comment]
😂 "Are you sure? No you're not. Look at this folder." 🤣

**Comment by Czaki** [comment]
I cannot reproduce this on ubuntu, but could on macos.

**Comment by Czaki** [comment]
I check a little more. It still works when using PyQt6 in version 6.4.3. But in version 6.4.3 it uses Qt dialog, when since 6.5.0 it uses natve dialog.

**Comment by dalthviz** [comment]
Just in case, on Windows with PyQt6 6.6.0 I was unable to reproduce this (I see the question modal dialog with the `Restore Defaults` and `Cancel` buttons):

![imagen](https://github.com/napari/napari/assets/16781833/8518a4d2-a9c3-4b1f-a177-9a5e2c9f1638)

Also, checking the Qt docs, seems like for Qt 6.6 they added the `options` and `setOptions` attribute/method (https://doc.qt.io/qt-6/qmessagebox.html#options-prop)

**Comment by Czaki** [comment]
On your screenshot is a Qt dialog while on @psobolewskiPhD, there is native Qt one.
