### ISSUE TITLE
Use `open` instead of `exec` for `QDialog`s

### ISSUE THREAD

**Issue by lucyleeow** [napari/napari#6502]
## 🧰 Task

Noticed in https://github.com/napari/napari/pull/4991/files#r1402323286, where use of `QtPluginErrReporter(parent=window._qt_window).exec_()` gave:

> QtPluginErrReporter" has no attribute "exec_" error

The [Qt docs for `QDialog.exec()`](https://doc.qt.io/qt-6/qdialog.html#exec) suggest using `open()` instead:
> Note: Avoid using this function; instead, use open(). Unlike exec(), [open](https://doc.qt.io/qt-6/qdialog.html#open)() is asynchronous, and does not spin an additional event loop. This prevents a series of dangerous bugs from happening (e.g. deleting the dialog's parent while the dialog is open via exec()). When using [open](https://doc.qt.io/qt-6/qdialog.html#open)() you can connect to the [finished](https://doc.qt.io/qt-6/qdialog.html#finished)() signal of [QDialog](https://doc.qt.io/qt-6/qdialog.html) to be notified when the dialog is closed.

We also use `exec_` in other `QDialog`s:

* [`_QtMainWindow.close`](https://github.com/napari/napari/blob/514b40ae19b8c85c0f546976dbcccb29c505095d/napari/_qt/qt_main_window.py#L443)
* [`_QtMainWindow.closeEvent`](https://github.com/napari/napari/blob/514b40ae19b8c85c0f546976dbcccb29c505095d/napari/_qt/qt_main_window.py#L527)
* [`Window._screenshot_dialog`](https://github.com/napari/napari/blob/514b40ae19b8c85c0f546976dbcccb29c505095d/napari/_qt/qt_main_window.py#L1603)
* [`QtViewer._screenshot_dialog`](https://github.com/napari/napari/blob/514b40ae19b8c85c0f546976dbcccb29c505095d/napari/_qt/qt_viewer.py#L827)
* [`_show_plugin_install_dialog`](https://github.com/napari/napari/blob/514b40ae19b8c85c0f546976dbcccb29c505095d/napari/_qt/menus/plugins_menu.py#L135)
* [`QtAbout.showAbout`](https://github.com/napari/napari/blob/514b40ae19b8c85c0f546976dbcccb29c505095d/napari/_qt/dialogs/qt_about.py#L108)
* [`QtReaderDialog.get_user_choices`](https://github.com/napari/napari/blob/514b40ae19b8c85c0f546976dbcccb29c505095d/napari/_qt/dialogs/qt_reader_dialog.py#L144)
* [`ShortcutEditor._show_warning`](https://github.com/napari/napari/blob/514b40ae19b8c85c0f546976dbcccb29c505095d/napari/_qt/widgets/qt_keyboard_settings.py#L522)
* [`QColorButton.onColorPicker`](https://github.com/napari/napari/blob/514b40ae19b8c85c0f546976dbcccb29c505095d/napari/_vendor/qt_json_builder/qt_jsonschema_form/widgets.py#L303)

Some of these are conditionals so maybe there is a reason we use `exec_` instead of `open`?

The task would be to use `open` for `QtPluginErrReporter`, which would hopefully prevent the 'no attribute' error, and consider amending the other uses of `exec_` if appropriate.

**Comment by lucyleeow** [comment]
cc @aganders3 @DragaDoncila

**Comment by Czaki** [comment]
`open` should be used only when opening dialog should not block the main thread. Fast check of this list show that all should `exec_`

**Comment by aganders3** [comment]
Why do we want it to block the main thread? Preventing interaction by marking modal is not enough?

**Comment by Czaki** [comment]
At first, this dialogs are not marked as modal now. At second. Instead of simple function wee will need to impelement callbacks as `open` will not wait on result, when `execs` wait.

**Comment by aganders3** [comment]
Thanks, that makes sense. My understanding then is that it _could_ be changed to use `open`, but it would require extra non-trivial code in many occasions (where we need the result of the dialog), and using `exec_` in the manner it is used now is safe enough.

**Comment by dalthviz** [comment]
Hi there, just in case, [QtPy does some patching to keep `exec_` available when using PyQt6](https://github.com/spyder-ide/qtpy/blob/a5f254828644331d247d3566c285bb0939ccb4d4/qtpy/QtWidgets.py#L87) but maybe that's not enough for the `mypy` check :thinking: Also, for some context, `exec_` was [completely removed in PyQt6](https://www.riverbankcomputing.com/static/Docs/PyQt6/pyqt5_differences.html) while still usable with PySide6. Besides that, with PySide2 the opposite of PyQt6 happens, `exec` doesn't exist and you need to use `exec_`. With PyQt5 you can use both versions (`exec` or `exec_`). So basically:

* PyQt6: Only `exec` is available
* PySide6: Both `exec` and `exec_` are available (for the moment)
* PyQt5: Both `exec` and `exec_` are available
* PySide2: Only `exec_` is available

`exec_` comes from bindings trying to be compatible with Python 2 where `exec` was a reserved keyword.

For more details about `exec_` vs `exec` and `exec` vs `open` you can check: 

* https://stackoverflow.com/q/22610720/15954282
* https://stackoverflow.com/q/70037311/15954282

 Anyhow, if there is something that could be done over QtPy side let me know :+1:

**Comment by aganders3** [comment]
Thanks! I found some QtPy docs/issues when I was initially troubleshooting this, but was unable to find a combination setting `always_true` or `always_false` for the bindings variables that made it work. The recommended settings are already in our `pyproject.toml`, and I didn't dig too much deeper than that. Suffice to say mypy does not seem to be picking up the [changes applied by qtpy ](https://github.com/spyder-ide/qtpy/blob/a5f254828644331d247d3566c285bb0939ccb4d4/qtpy/QtWidgets.py#L87) (as you linked above).

So if I type-check this:
```
from qtpy.QtWidgets import QApplication, QDialog

from typing import reveal_type


app = QApplication([])

d = QDialog()
reveal_type(d)
d.exec_()
```

I get:
```
qtpy_typing.py:9: note: Revealed type is "PyQt6.QtWidgets.QDialog"
qtpy_typing.py:10: error: "QDialog" has no attribute "exec_"; maybe "exec"?  [attr-defined]
Found 1 error in 1 file (checked 1 source file)
```

**Comment by lucyleeow** [comment]
> `open` should be used only when opening dialog should not block the main thread. Fast check of this list show that all should `exec_`

In this case then we should not use `open` in `QtPluginErrReporter` and will keep the mypy ignore comment, unless there is a better mypy solution? I think I will close this issue, thanks for the info @Czaki

**Comment by dalthviz** [comment]
> Suffice to say mypy does not seem to be picking up the [changes applied by qtpy ](https://github.com/spyder-ide/qtpy/blob/a5f254828644331d247d3566c285bb0939ccb4d4/qtpy/QtWidgets.py#L87)(as you linked above).

Not totally sure about how mypy exactly works but checking your testing example, seems like I'm able to make the mypy check pass by doing something like:

```python
from qtpy.QtWidgets import QApplication, QDialog as _QDialog

from typing_extensions import reveal_type


app = QApplication([])


class QDialog(_QDialog):
    def exec_(self):
        return super().exec_()


d = QDialog()

reveal_type(d)
d.exec_()
```

And running:

```
mypy test.py --always-false=PYQT5 --always-false=PYSIDE2 --always-true=PYQT6 --always-false=PYSIDE6
```

In that way the revealed type is `test.QDialog` and the check passes:

```
test.py:14: note: Revealed type is "test.QDialog"
Success: no issues found in 1 source file
```

Also, now that I'm thinking on this, improving the typing inside QtPy started to be discussed some time ago: https://github.com/spyder-ide/qtpy/discussions/467 maybe we need to rethink how we are adding support for deprecated/removed methods over QtPy and instead of direct attributte assignment try to subclass things 🤔

**Comment by aganders3** [comment]
From what I can tell (with a bit of experimenting), subclassing in QtPy is not sufficient because of how `mypy` handles re-exports where QtPy uses `from PyQt6.QtWidgets import *`. I will play around a bit more and see if there is another work-around, but maybe we can leave this issue alone and I will reach out to you/qtpy elsewhere :).
