### ISSUE TITLE
Excessive ram usage on VS Code notebook using viewer.show(block=True)

### ISSUE THREAD

**Issue by Morten10** [napari/napari#6503]
### 🐛 Bug Report

Hey.
Only when executing code with napari on notebook, there is an issue with viewer.show(block=True).
It seems that the even when the cell has been fully executed, the napari GUI although closed is present in the windows task manager and using excess ram. For my understanding, the GUI continue to save all the data in memory even when the GUI is closed.
When killing that task VS Code pops an error
"The Kernel crashed while executing code in the current cell or a previous cell. Please review the code in the cell(s) to identify a possible cause of the failure. Click [here](https://aka.ms/vscodeJupyterKernelCrash) for more info. View Jupyter [log](command:jupyter.viewOutput) for further details."

I work with several large datasets, this behavior is not acceptable

### 💡 Steps to Reproduce

Display a large dataset with napari viewer on VS Code notebook python cell using viewer.show(block=True) on the latest napari version. 0.4.18

### 🌎 Environment

napari 0.4.18
python 3.11.5

**Comment by Czaki** [comment]
You need to delete viewer from code. Otherwise, You still have access to all variables stored by the viewer. 

You could use `del viewer` where `viewer` is the variable name. Other option is to spawn a viewer in function (like in this example of annotation):

```python
import napari
import numpy as np


def annotate_image(data: np.ndarray) -> np.ndarray:
    viewer = napari.Viewer()
    viewer.add_image(data, name='data')
    viewer.add_points([], name='points')

    viewer.show(block=True)
    return viewer.layers['points'].data


img = np.random.rand(10, 10)

points = annotate_image(img)

print(points)
```

**Comment by Morten10** [comment]
del viewer and viewer.close() doesn't seem to work.
The viewer is already in a function.

**Comment by Czaki** [comment]
does this help? 

```
import gc

gc.collect()
```

**Comment by Morten10** [comment]
Update.
When using gc.collect() after a minute or so there is no excess ram usage. Thanks! Working fine.

**Comment by Morten10** [comment]
Update.
When using gc.collect() after a minute or so there is no excess ram usage. Thanks! Working fine.
