### ISSUE TITLE
Introduce the concept of points having a "class" that can be changed in the GUI.

### ISSUE THREAD

**Issue by adamltyson** [napari/napari#651]
## 🚀 Feature

Introduce the concept of points having a "class". Rather than calling `viewer.add_points` multiple times, points should have a label, which means they are rendered in different colors, and can be moved from one class to the other in the GUI.
## Motivation

I want to use napari to curate points, and generate training data. Assuming I have an image, and N classes of detected objects, I want to load them all and visualize them in different colors (maybe with a legend, `class1=blue` etc). Ideally I would then be able to curate these points, by selecting them, and converting them to a different class (or generate a new class).

I can already do this by calling `viewer.add_points` and adding and deleting points, but the concept of changing a class (rather than delete and add) would streamline the process (especially in conjunction with #474.

## Pitch

Assuming there is an NxD `points` array, I would like to be able to pass an Nx1 `classes` array to `viewer.add_points`, `viewer.add_points(points, classes=classes)`. These would appear separated in the GUI, perhaps as an expandable list within a single `Points` section. 

When selecting a point, there would be an additional option to `convert to class X`, and ideally a keyboard shortcut to the number of that class.

Even more ideally, the arguments to `viewer.add_points` should accept lists of length N (or Nx1 arrays) so we could use `viewer.add_points(points, classes=classes, names=["Cell type 1", "Cell type 2", "Cell type 3"])`.

## Alternatives

This idea may have already been proposed (but I couldn't see it).

The only alternative I can think of is to call `viewer.add_points` in a loop, and then deal with adding/deleting points outside of napari (which isn't ideal), and lacks a true "convert" option.

## Additional context

I think a point-based data curation interface like this could be very useful to the community. There are lots of point-based deep learning applications coming out that require training data (e.g. [DeepLabCut](https://github.com/AlexEMG/DeepLabCut), although they have their own training data generation interface).

**Comment by sofroniewn** [comment]
@adamltyson I like this idea a lot, I want to think about it in the context of https://github.com/napari/napari/pull/552#issuecomment-536878528 where the concept of `coordinates and values` has been proposed. I like the idea of `values` / `class` just being a continuous or categorical descriptor.

I think @berl might have opinions on improvements to this api too.

Making sure use case like this are well supported is definitely a priority for us.

**Comment by sofroniewn** [comment]
@kevinyamauchi do you want to post a comment here summarizing some of our chat yesterday about the possibility of a common base layer for `Points` and `Text` #600, or a common `Annotation` layer that would allow you to display points and or text with labels / classes / values as requested above. Could also be something for @jni to keep in mind as he reviews #600.

**Comment by kevinyamauchi** [comment]
Hey @adamltyson! I think this is a great idea.  @sofroniewn and I were discussing and as he alluded to above, there is quite a bit of commonality between the Points and forthcoming Text layers. I think your proposed feature would fit in nicely with a refactor that reduces the code duplication. I think there are a couple of approaches that could make sense. I’ve outlined some thoughts below. Please let me know what you all think!

## Commonalities between Points and Text layers
- with this proposal to add a class/label to each point, the data models become the same: a list of labels and a corresponding list of coordinates
- a lot of the functions for slicing, updating, and selecting/highlighting are similar/shared
- I think there are cases where the text needs a points marker and vice versa


### Approach 1: Create a base class for the Points and Text layers
We could create a points/text layer model base class that encompasses the common methods for the two layer types. We may also want to create a vispy base class in the same spirit. This would be the smallest change to the API, but it means that including points with text requires two layers.

### Approach 2: Combine the Points and Text layers
We could combing the Points and Text layers into a single layer (Annotations?) and make both the Points and the Text toggleable, so that they can behave like the independent layers. I this is beneficial in that it reduces the number of layer types and I think it is handy to have points and text together.

I am about to get on a plane for the weekend, but I look forward to discussing when I get back!

**Comment by adamltyson** [comment]
Hi @kevinyamauchi! I agree with the commonalities. From the user point of view, I think I prefer **Approach 1**. This wouldn't have to be specific to text layers, but it opens up the concept of general coordinate-property pairs. In the future, this could be extended to other labels (e.g. small images when making figures etc.).

From a selfish point of view, both of these approaches would work for me, but the key would be to allow users to easily switch the labels (whatever they may be). Think curating 10,000 data points for a deep learning workflow.

I'll defer to those who are much more involved in the development of napari, but from my POV, a general coordinate-property layer would (in combination with the other layers) would satisfy every use case we have.

**Comment by kevinyamauchi** [comment]
Thanks for the feedback, @adamltyson !

After a bit more thinking I am also in favor of Approach 1. I think combining the `Points` and `Text` layers into a single layer will result in a pretty bloated layer. We have 2 different interactive modes (add, select) and there will be 4 layer display states (e.g., [`Points` visible, `Text` visible], [`Points` visible, `Text` not visible], ...), so there will have to multiple states in the display/selection functions and logic to switch between them. Thus, I agree that Approach 1 (`Points` and `Text` layers will be separate, but share a base class) is probably the cleanest approach. Anybody have a strong leaning towards Approach 2 (combined `Text` + `Points` layer)?

@adamltyson, in terms of viewing the point labels, is it sufficient to display the label in the status bar at the bottom of the viewer window when you mouse over the point (see the screen capture below)? Or is it important that they are displayed on the canvas, next to the points?

![point_label](https://user-images.githubusercontent.com/1120672/68891638-17c86b00-06d6-11ea-9272-5262cfe0c465.png)

Once #600 lands, I can get started on this!

**Comment by sofroniewn** [comment]
That sounds reasonable @kevinyamauchi.

At one point @jni mentioned

> have points have an "attributes" table, which would be anything "pandas.DataFrame"-like, and you could map various attributes to columns, including annotations, size, color, etc.

That I wanted to capture. We might also want to think about how any refactoring would affect the `Shapes` layer too, where I think people also might want to associate an annotation with a shape.

**Comment by adamltyson** [comment]
@kevinyamauchi for my use case, the label wouldn't need to be displayed next to the point, but there would need to be some way of telling what class each point was at a glance (e.g. color coding). Then the points which were "incorrect" could be moved, or have their class changed etc.

**Comment by kevinyamauchi** [comment]
> the label wouldn't need to be displayed next to the point, but there would need to be some way of telling what class each point was at a glance (e.g. color coding).

Makes sense to me @adamltyson ! I think most of the properties other than the symbol can be set on a per-point basis.

Thanks for the reminder, @sofroniewn . I think that's a good idea to keep in mind. I also agree we may want a `(shapes_list, labels)` data model for the `Shapes` layer.

**Comment by kevinyamauchi** [comment]
Point properties (e.g., class) were implemented by #895 .

**Comment by adamltyson** [comment]
Amazing. Thanks again @kevinyamauchi! Is there an ETA for napari 0.2.11 with this functionality?

**Comment by sofroniewn** [comment]
ETA for 0.2.11 is latest this weekend. I want to start the release process today / tomorrow

**Comment by kevinyamauchi** [comment]
No problem, @adamltyson! Please don't hesitate to let me know if you run into any problems!
