### ISSUE TITLE
Delete stale branches

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#653]
## ❓ Questions and Help

I'd like to delete some of our stale branches + active ones we aren't using - see here. Are there any objections @jni, @AhmetCanSolak, @royerloic?

![image](https://user-images.githubusercontent.com/6531703/68076178-92a49400-fd6e-11e9-9034-b99eae454a85.png)

**Comment by jni** [comment]
@sofroniewn I think anything merged can definitely be deleted. I'd check with @royerloic about the dimsliders one — it might have some code there for the mode switching that remains on our to-do.

**Comment by sofroniewn** [comment]
@royerloic any comment on the `dimsliders-loic` branch? I can leave that one, but will delete the others shortly

**Comment by AhmetCanSolak** [comment]
Go head @sofroniewn and thank you for cleaning up those!

**Comment by sofroniewn** [comment]
@AhmetCanSolak - ok if i delete "revert-692-fix_is_pyramid"? thanks again for helping out there

**Comment by AhmetCanSolak** [comment]
yep i think we are already good on that. Please go ahead @sofroniewn. You are welcome!

**Comment by sofroniewn** [comment]
@kne42 can I delete your three old branches here:

![image](https://user-images.githubusercontent.com/6531703/70749951-4be97880-1ce2-11ea-844f-a86fb49b37e6.png)

also @royerloic can I also delete your dims branch

**Comment by kne42** [comment]
go for it

**Comment by sofroniewn** [comment]
Done, thanks @kne42 - only one more to go!

**Comment by sofroniewn** [comment]
@royerloic gave the go ahead to delete that last branch, so we now have no extra branches. I will close this issue. In general I'd like to keep trimming any unnecessary branches on the main repo
