### ISSUE TITLE
Canvas goes black for very small or large numbers in image

### ISSUE THREAD

**Issue by jnahlers** [napari/napari#6533]
### 🐛 Bug Report

When dealing with Nd arrays containing slices with very small or large values, sometimes the image disappears (goes black, under the gray colormap) on the canvas. This seems to be caused by an overflow error.  

### 💡 Steps to Reproduce

```
# imports
import numpy as np
import napari

# create image array
arr = np.linspace(1,9,5*5,dtype=np.float64).reshape((5,5))

# open the image
viewer, image_layer = napari.imshow(arr)
```

1. Click on 'continuous' auto-contrast.

```
viewer.layers[0].data = viewer.layers[0].data*1E37
```

2. The image is still visible in on the canvas.

```
viewer.layers[0].data = viewer.layers[0].data*10
```
3. The canvas has gone black! However, the image is still visible in the preview of the layer in the layer list, and hovering the mouse over the canvas still shows the values under the cursor in the Status Bar. Adjusting the contrast limits slider still varies the contrast in the preview correctly. I get the following error message:

```
C:\Users\...\napari\napari\_vispy\utils\gl.py:120: RuntimeWarning: overflow encountered in cast
  return data.astype(dtype_)
>>> C:\Users\...\Anaconda3\envs\napari-env\lib\site-packages\vispy\gloo\program.py:373: RuntimeWarning: overflow encountered in cast
  data = np.array(data, dtype=dtype).ravel()
```
Keep going. 
```
viewer.layers[0].data = viewer.layers[0].data/10
```
5. The image is back!
```
viewer.layers[0].data = viewer.layers[0].data/1E-75
```
6. Still visible...
```
viewer.layers[0].data = viewer.layers[0].data/10
```
7. And gone.

### 💡 Expected Behavior

The image should be visible on the canvas for any range of data values allowed by the `dtype`.

### 🌎 Environment

napari: 0.5.0a2.dev486+g4d60a7ce
Platform: Windows-10-10.0.19045-SP0
Python: 3.9.18 | packaged by conda-forge | (main, Aug 30 2023, 03:40:31) [MSC v.1929 64 bit (AMD64)]
Qt: 5.15.2
PyQt5: 5.15.10
NumPy: 1.26.2
SciPy: 1.11.4
Dask: 2023.12.0
VisPy: 0.14.1
magicgui: 0.8.0
superqt: 0.6.1
in-n-out: 0.1.9
app-model: 0.2.2
npe2: 0.7.3

OpenGL:
  - GL version:  4.6.0 - Build 27.20.100.9565
  - MAX_TEXTURE_SIZE: 16384

Screens:
  - screen 1: resolution 1920x1200, scale 1.0
  - screen 2: resolution 2000x1125, scale 1.0

Settings path:
  - C:\Users\...\AppData\Local\napari\napari-env_4624f08893c59545bcb98518a8c42a23d61d4ece\settings.yaml

**Comment by jnahlers** [comment]
When running the step between 2. and 3., I am intermittently getting an "overflow encountered in cast" pop-up error message, which seems relevant. 🤔

**Comment by jnahlers** [comment]
The error message seems to be pointing to [this line in vispy](https://github.com/vispy/vispy/blob/4618f6adbec8498abb43a46dca3ffbdbc52fe9b2/vispy/gloo/program.py#L373C20-L373C20).

**Comment by Czaki** [comment]
The source of the problem is that vispy uses float32 textures and when you cast problematic data to float32 you go out of range. 

For example:

```python
In [5]: np.array(image_layer.data, dtype="float32")
<ipython-input-5-3144dfc2f2e5>:1: RuntimeWarning: overflow encountered in cast
  np.array(image_layer.data, dtype="float32")
Out[5]:
array([[9.9999997e+37, 1.3333334e+38, 1.6666666e+38, 1.9999999e+38,
        2.3333334e+38],
       [2.6666667e+38, 3.0000000e+38, 3.3333333e+38,           inf,
                  inf],
       [          inf,           inf,           inf,           inf,
                  inf],
       [          inf,           inf,           inf,           inf,
                  inf],
       [          inf,           inf,           inf,           inf,
                  inf]], dtype=float32)
```

To fix this problem, we need to implement similar things to #6439 and #6411 to smart remap data before pass it to vispy backend. 

```python
In [8]: np.array(image_layer.data, dtype="float32")
<ipython-input-8-3144dfc2f2e5>:1: RuntimeWarning: overflow encountered in cast
  np.array(image_layer.data, dtype="float32")
Out[8]:
array([[inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf]], dtype=float32)

In [9]: image_layer.data
Out[9]:
array([[1.00000000e+112, 1.33333333e+112, 1.66666667e+112,
        2.00000000e+112, 2.33333333e+112],
       [2.66666667e+112, 3.00000000e+112, 3.33333333e+112,
        3.66666667e+112, 4.00000000e+112],
       [4.33333333e+112, 4.66666667e+112, 5.00000000e+112,
        5.33333333e+112, 5.66666667e+112],
       [6.00000000e+112, 6.33333333e+112, 6.66666667e+112,
        7.00000000e+112, 7.33333333e+112],
       [7.66666667e+112, 8.00000000e+112, 8.33333333e+112,
        8.66666667e+112, 9.00000000e+112]])
```

**Comment by jni** [comment]
@Czaki what about using `np.nan_to_num` at the interface to VisPy? I don't think we want to do a fancier remapping than that...? Alternatively, we could use a numpy configuration context such that overflow/underflow trigger CPU-side contrast-limits remapping.

**Comment by jni** [comment]
(thanks @jnahlers for the report! tbh I'm a little shocked we haven't encountered this before.)

**Comment by Czaki** [comment]
> what about using `np.nan_to_num` at the interface to VisPy 

The values are cast to `inf`, not `nan`

**Comment by Czaki** [comment]
Still this will remove Warning, but the image still will not be visible.

**Comment by jni** [comment]
Yeah, so then

> Alternatively, we could use a numpy configuration context such that overflow/underflow trigger CPU-side contrast-limits remapping.

is the only solution...

**Comment by Czaki** [comment]
I was thinking that #6537 will be a fast PR. It took longer that expected, but it is ready for review.
