### ISSUE TITLE
Making Viewer a self-contained Structure

### ISSUE THREAD

**Issue by AhmetCanSolak** [napari/napari#66]
I would prefer to see this code inside of the viewer,
Any reason it is not there?
I would like to keep the window to a minimum and
only concerned with 'window'-specific things like menus, etc...

The viewer widget should be self contained and should be able work independently of the window,
(as part of something else for example...).

_Originally posted by @royerloic in https://github.com/Napari/napari-gui/pull/63/files_

@royerloic, currently viewer is not the thing you are talking about (that's why it is not there but here), however i think a self-contained viewer would be better and we can easily switch to that. Just requires some easy refactoring. If we are all okay with that i can address this right away after clim PR.

**Comment by sofroniewn** [comment]
I'm glad you pulled this out for discussion. Right now I conceive as the window containing the color control panel on the left, the viewer in the middle (which as contains the dimension sliders) and the layers panel on the right. Logically these three things could all live in a `QHBoxLayout`, though I know @AhmetCanSolak was also thinking about a `QGridLayout` - I'm not sure if the `QSplitters` PR changes this.

Regardless, we could introduce another layer of abstraction in between what we currently call viewer and what we currently call window or expand our notion of viewer. I'm open to many options, but am curious about what refactoring @AhmetCanSolak you have in mind and for what reason. One thing to consider is would we ever want to support a tabbed interface and if so at what level would the tabs be, and what would the motivation be for having tabs vs multiple windows open.

**Comment by AhmetCanSolak** [comment]
> I'm glad you pulled this out for discussion. Right now I conceive as the window containing the color control panel on the left, the viewer in the middle (which as contains the dimension sliders) and the layers panel on the right. Logically these three things could all live in a `QHBoxLayout`, though I know @AhmetCanSolak was also thinking about a `QGridLayout` - I'm not sure if the `QSplitters` PR changes this.
> 

Indeed I prefer those in a `QHBoxLayout`. Horizontal Splitters PR does not introduced anything else and Vertical Splitters will not introduce too. But im not 100% sure on keeping canvas and dimension sliders together in the viewer. It might be good to separate them. What do you think guys? @kne42 @jni 

> Regardless, we could introduce another layer of abstraction in between what we currently call viewer and what we currently call window or expand our notion of viewer. I'm open to many options, but am curious about what refactoring @AhmetCanSolak you have in mind and for what reason. One thing to consider is would we ever want to support a tabbed interface and if so at what level would the tabs be, and what would the motivation be for having tabs vs multiple windows open.
>

What I meant by refactoring was: Taking the logic from Window class to Viewer class. Make Window class as only a wrapper to Viewer with menubar and status bar maybe. Making Viewer class a standalone widget which some people could depend. This was every single widget can live in the layout of the Viewer class. 

This was what i had in my mind. Open to suggestions. I also believe that supporting multiple tabs of any level should be a long term feature. For now what people could do is just starting new napari-gui instances.

**Comment by jni** [comment]
> But im not 100% sure on keeping canvas and dimension sliders together in the viewer. It might be good to separate them.

Oh, no, I 100% think that the dimension sliders and the contrast sliders should *always* be attached to the canvas. These are Napari's reason for living. Unless I'm misinterpreting the question? Which is very possible, to be honest I'm a bit out of my depth with all the Qt layout discussion. It would be nice to include diagrams when these things are being discussed... ;)

**Comment by jni** [comment]
fwiw I agree that tabs should not be cluttering our mind at this point.

**Comment by sofroniewn** [comment]
This has been resolved in #88
