### ISSUE TITLE
QOpenGLWidget is not supported on this platform.

### ISSUE THREAD

**Issue by berceanu** [napari/napari#660]
Using `pyqt 5.9.2` on an Ubuntu 18.04 machine with the miniconda3 python 3.6.9 distribution, I launch `IPython` via  `ipython --gui=qt5`, and get

```
import napari
~/miniconda3/lib/python3.6/site-packages/napari/__init__.py:27: UserWarning:
    napari was tested with QT library `>=5.12.3`.
    The version installed is 5.9.6. Please report any issues with this
    specific QT version at https://github.com/Napari/napari/issues.

from skimage.data import astronaut

viewer = napari.view_image(astronaut(), rgb=True)
WARNING: QOpenGLWidget is not supported on this platform.
WARNING: This plugin does not support propagateSizeHints()
```
and nothing is displayed on-screen.

**Comment by jni** [comment]
@berceanu I'm on 18.04 and miniconda so we can certainly get your setup working! =) The first thing to do would be to attempt upgrading PyQt. As noted in the warning message, napari is tested on 5.12+. Have you tried upgrading your pyqt version? You can do this with `pip install -U pyqt`. You can also `pip install -U pyside2`, an alternative Qt-python binding.

**Comment by berceanu** [comment]
Hi @jni, thanks for the quick reply!
So I did `python -m pip install -U PyQt5` and this got rid of the warning when importing `napari`. Now I get
```
viewer = napari.view_image(astronaut(), rgb=True)
WARNING: This plugin does not support propagateSizeHints()
```
So the `QOpenGLWidget` warning also dissapeared, but still nothing happens, i.e. no `napari` window appears.

**Comment by berceanu** [comment]
To narrow down the problem, I tried running this script
```
from PyQt5.QtWidgets import QApplication, QMainWindow
app = QApplication([])
win = QMainWindow()
win.show()
app.exec_()
```
I get no error, but also no window is shown.

See also: https://github.com/matplotlib/matplotlib/issues/11446

**Comment by berceanu** [comment]
I think mixing `pip` and `conda` packages is almost never a good idea.
https://github.com/ContinuumIO/anaconda-issues/issues/1970#issuecomment-306277703

**Comment by jni** [comment]
Aaach! Apologies, I did not realise it was your root env! :grimacing: fwiw I never work in the base environment for similar reasons. It makes it easy to burn an environment to the ground and start anew...

Speaking of which... :grimacing: 

This morning I actually made a brand new install with python 3.7, ipython, numpy, scipy, pyqt etc all latest, all from conda-forge, and it worked out of the box. Might be worth a shot?

**Comment by jni** [comment]
btw what is your window manager? GNOME? Or Wayland? Can you run any other Qt apps e.g. matplotlib with Qt backend?

**Comment by berceanu** [comment]
GNOME. I could, before pip-installing PyQt5. Now matplotlib is also broken.

**Comment by jni** [comment]
Sorry. :sob: That was terrible advice. I am used to mixing the two when I need something that is not easily available in conda, such as recent PyQt5. And anyway I just saw that 5.12.3 is available for Py3.6, which for some reason historically didn't work for me! Grrr. I hope it is not to onerous to reset your env with a new conda install...!

**Comment by tlambert03** [comment]
yeah pyqt specifically causes issues if you install pip pyqt on top of conda (or at least it used to).  you may be able to recover your environment by cleaning tarballs ... I posted an example and fix for a similar issue a couple years ago that you may want to try: https://github.com/ContinuumIO/anaconda-issues/issues/1970#issuecomment-330319773 (or perhaps yours is a different issue entirely)

**Comment by berceanu** [comment]
I guess the long-term solution is a `conda-forge` `napari` recipe/feedstock?

**Comment by berceanu** [comment]
So I did a fresh `miniconda` install, set `conda-forge` as the default channel and then
`conda create -n napari python=3.7 pyqt ipython dask zarr fsspec imageio ipykernel numpy qtpy qtconsole scipy scikit-image vispy backcall PyOpenGL PySide2 wrapt numpydoc`

All the requirements are met, except for `vispy`: `napari` requires at least [`0.6.2`](https://github.com/napari/napari/blob/ff85a1ccdbd77f2fbb704f24eecf704bb82f4349/requirements/default.txt#L11), whereas `conda-forge` provides [`0.6.1`](https://anaconda.org/conda-forge/vispy). 

https://github.com/conda-forge/vispy-feedstock/pull/17#issuecomment-549687900

**Comment by tlambert03** [comment]
for now, until there is a full conda forge package ready, I would try use conda for environments, but pip for dependencies:

```sh
conda create -n napari python=3.7
conda activate napari
pip install napari  # or git clone the repo and pip install -r requirements.txt
```

but for just the vispy dependency in your napari environment, you will probably be ok if you `conda uninstall vispy` and then `pip install vispy==0.6.2`

**Comment by berceanu** [comment]
The official vispy [docs](http://vispy.org/installation.html) recommend installation via conda, does `napari` use any `0.6.2`-specific features?

**Comment by tlambert03** [comment]
see https://github.com/napari/napari/issues/575 and https://github.com/napari/napari/pull/657 for the rationale being requiring 0.6.2

since 0.6.2 was just released days ago, I assume vispy will be updating the conda installation shortly.

**Comment by berceanu** [comment]
I see, I'll wait for that then. I'm reluctant to mix `pip` and `conda` especially for packages with pre-compiled libs.

**Comment by tlambert03** [comment]
Fair enough, but fwiw, I think many of us are developing in exactly that environment (conda as virtual env, pip for dependencies).  You hit one of the few known snags with Qt, but as long as you create a fresh environment and don’t install to base, you really should be fine to experiment with the pip packages.

**Comment by berceanu** [comment]
OK, let me give it a go then, installing everything from pypi this time.

**Comment by berceanu** [comment]
```
$ ipython --gui=qt5
ImportError:
    Could not load requested Qt binding. Please ensure that
    PyQt4 >= 4.7, PyQt5, PySide >= 1.0.3 or PySide2 is available,
    and only one is imported per session.

    Currently-imported Qt library:                              None
    PyQt4 available (requires QtCore, QtGui, QtSvg):            False
    PyQt5 available (requires QtCore, QtGui, QtSvg, QtWidgets): False
    PySide >= 1.0.3 installed:                                  False
    PySide2 installed:                                          True
    Tried to load:                                              ['pyqt5']
```

It seems `pip install napari` doesn't pull in `pyqt5`.

**Comment by berceanu** [comment]
```
$ ipython --gui=qt

In [1]: import napari
In [2]: from skimage.data import astronaut
In [3]: viewer = napari.view_image(astronaut(), rgb=True)
WARNING: This plugin does not support propagateSizeHints()
```

and no window is shown.

**Comment by tlambert03** [comment]
sorry for the frustrations! possible that @jni immediately knows what's going on... but let me see if I can recreate this on an 18.04 box here.  can you run `conda list` in your newly made napari environment and paste the output here?

regarding `pip install napari`: it won't have install `pyqt5`, but it _should_ have installed `pyside2`, and only one of those is required (since napari uses `qtpy` as an abstraction layer for either package).  I think that's why `ipython --gui=qt` doesn't raise the `ImportError`, but `ipython --gui=qt5` does... (but I'm struggling to find ipython documentation about the different event loop options)

**Comment by berceanu** [comment]
```
# packages in environment at /home/berceanu/miniconda3/envs/napari:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
alabaster                 0.7.12                   pypi_0    pypi
asciitree                 0.3.3                    pypi_0    pypi
babel                     2.7.0                    pypi_0    pypi
backcall                  0.1.0                    pypi_0    pypi
bzip2                     1.0.8                h516909a_1    conda-forge
ca-certificates           2019.9.11            hecc5488_0    conda-forge
certifi                   2019.9.11                py37_0    conda-forge
chardet                   3.0.4                    pypi_0    pypi
cycler                    0.10.0                   pypi_0    pypi
dask                      2.6.0                    pypi_0    pypi
decorator                 4.4.1                    pypi_0    pypi
docutils                  0.15.2                   pypi_0    pypi
fasteners                 0.15                     pypi_0    pypi
freetype-py               2.1.0.post1              pypi_0    pypi
fsspec                    0.5.2                    pypi_0    pypi
idna                      2.8                      pypi_0    pypi
imageio                   2.6.1                    pypi_0    pypi
imagesize                 1.1.0                    pypi_0    pypi
ipykernel                 5.1.1                    pypi_0    pypi
ipython                   7.9.0                    pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
jedi                      0.15.1                   pypi_0    pypi
jinja2                    2.10.3                   pypi_0    pypi
jupyter-client            5.3.4                    pypi_0    pypi
jupyter-core              4.6.1                    pypi_0    pypi
kiwisolver                1.1.0                    pypi_0    pypi
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.1.0                hdf63c60_0
libstdcxx-ng              9.1.0                hdf63c60_0
markupsafe                1.1.1                    pypi_0    pypi
matplotlib                3.1.1                    pypi_0    pypi
monotonic                 1.5                      pypi_0    pypi
napari                    0.2.4                    pypi_0    pypi
ncurses                   6.1               hf484d3e_1002    conda-forge
networkx                  2.4                      pypi_0    pypi
numcodecs                 0.6.3                    pypi_0    pypi
numpy                     1.17.3                   pypi_0    pypi
numpydoc                  0.9.1                    pypi_0    pypi
openssl                   1.1.1d               h516909a_0    conda-forge
packaging                 19.2                     pypi_0    pypi
parso                     0.5.1                    pypi_0    pypi
pexpect                   4.7.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    6.2.1                    pypi_0    pypi
pip                       19.3.1                   py37_0    conda-forge
prompt-toolkit            2.0.10                   pypi_0    pypi
ptyprocess                0.6.0                    pypi_0    pypi
pygments                  2.4.2                    pypi_0    pypi
pyopengl                  3.1.0                    pypi_0    pypi
pyparsing                 2.4.4                    pypi_0    pypi
pyside2                   5.13.2                   pypi_0    pypi
python                    3.7.3                h33d41f4_1    conda-forge
python-dateutil           2.8.1                    pypi_0    pypi
pytz                      2019.3                   pypi_0    pypi
pywavelets                1.1.1                    pypi_0    pypi
pyzmq                     18.1.0                   pypi_0    pypi
qtconsole                 4.5.5                    pypi_0    pypi
qtpy                      1.9.0                    pypi_0    pypi
readline                  8.0                  hf8c457e_0    conda-forge
requests                  2.22.0                   pypi_0    pypi
scikit-image              0.16.2                   pypi_0    pypi
scipy                     1.3.1                    pypi_0    pypi
setuptools                41.6.0                   py37_1    conda-forge
shiboken2                 5.13.2                   pypi_0    pypi
six                       1.13.0                   pypi_0    pypi
snowballstemmer           2.0.0                    pypi_0    pypi
sphinx                    2.2.1                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.1                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.1                    pypi_0    pypi
sphinxcontrib-htmlhelp    1.0.2                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.2                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.3                    pypi_0    pypi
sqlite                    3.30.1               hcee41ef_0    conda-forge
tk                        8.6.9             hed695b0_1003    conda-forge
toolz                     0.10.0                   pypi_0    pypi
tornado                   6.0.3                    pypi_0    pypi
traitlets                 4.3.3                    pypi_0    pypi
urllib3                   1.25.6                   pypi_0    pypi
vispy                     0.6.2                    pypi_0    pypi
wcwidth                   0.1.7                    pypi_0    pypi
wheel                     0.33.6                   py37_0    conda-forge
wrapt                     1.11.2                   pypi_0    pypi
xz                        5.2.4             h14c3975_1001    conda-forge
zarr                      2.3.2                    pypi_0    pypi
zlib                      1.2.11            h516909a_1006    conda-forge
```

**Comment by berceanu** [comment]
On the flip side, running `napari` from the command line seems to work :)

**Comment by tlambert03** [comment]
I'm sorry, I'm stumped.  I tried a variety of combinations of python versions, pyqt5, pyside2, on 18.04.3 and never saw the `SizeHints()` warning or a missing napari window.  my conda environment is identical to yours here... so it seems like it must be a more general environmental difference.  Maybe @jni will know where to take it next.

**Comment by jni** [comment]
@berceanu I've been trying to add napari to conda-forge here: https://github.com/conda-forge/staged-recipes/pull/9983 but I'm also running into some Qt issues in the builds... 🤦‍♂ 

It looks like the latest vispy is also having issues:
https://github.com/conda-forge/vispy-feedstock/pull/17

We'll get there...!

**Comment by jni** [comment]
Is Matplotlib working in your new env? Anyway, searching for that "propagateSizeHints" error online took me to a bunch of other Qt (not PyQt) bug reports that all seemed to involve the platform and sometimes OpenGL, so maybe there is something to do with your graphics card drivers / OpenGL settings that needs updating?

**Comment by berceanu** [comment]
Yes, mpl seems to work now :)

**Comment by jni** [comment]
@berceanu napari has changed a lot since this issue was raised. Is it working for you now? There is also a conda-forge recipe so you can `conda install -c conda-forge napari`. Please let us know if we can close this issue...

**Comment by berceanu** [comment]
Yes, all good, you can close :+1:
