### ISSUE TITLE
Shapes layer: after drawing a shape, the last shape should remain/be selected

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari/napari#6624]
## 🧰 Task
Simple enhancement for consistency with Points layers, and well as other graphical tools and PowerPoint.
The last drawn shape should remain selected, to allow the user to easily tweak it's color.

Note: I recognize with our modes (add vs. vertex select vs shape select) this selection will not be fully functional, but at least changing color would work, same as with Points where you also cannot move the Point or interact with it, just change colors.

**Comment by dalthviz** [comment]
Hi there, not totally sure but to keep vertex selected after drawing a shape I think removing this line should be enough?:

https://github.com/napari/napari/blob/70d63868d49b3827b2ad0e838a65e507cc4d919b/napari/layers/shapes/shapes.py#L2573

A preview:

![vertex_selection](https://github.com/napari/napari/assets/16781833/aa4308a8-9421-4f47-9563-7d14727a6a10)

**Comment by psobolewskiPhD** [comment]
@dalthviz yeah that's what I came up with as well!

**Comment by dalthviz** [comment]
Should I do a PR with this little change or do you already have it somewhere and plan to create a PR @psobolewskiPhD ?

**Comment by psobolewskiPhD** [comment]
Um, I might have it somewhere? It was something that came up when doing some paired review with Grzegorz. I may have that change stashed somewhere or in a scratch branch on another machine. I was going to make a PR after 0.4.19 release.
If you want to jump on it, feel free--it's not urgent!--or I can get to it when I get to it 😅 

Also: lovely video, showing exactly what I meant!
