### ISSUE TITLE
[Shapes] Can't resize my shape when the scale is small

### ISSUE THREAD

**Issue by jplumail** [napari/napari#6627]
### 🐛 Bug Report

I was supposed to be able to resize my shape by selecting a vertex. I couldn't.

### 💡 Steps to Reproduce

Run this script:
```python
import napari
import numpy as np


s = (0.01, 0.005, 0.005)

viewer = napari.Viewer()
layers = viewer.open_sample("napari", "cells3d")
for l in layers:
    l.scale = s

viewer.add_shapes(
    np.array(
        [
            [29.0, 130.70802005, 86.37901572],
            [29.0, 130.70802005, 137.70733652],
            [29.0, 182.32797904, 137.70733652],
            [29.0, 182.32797904, 86.37901572],
        ]
    ),
    scale=s,
)

napari.run()
```

Then, press (5) to enter the `select shape` mode. Try to move a vertex.

### 💡 Expected Behavior

I expected the vertex I clicked to be selected, so I can move it.

### 🌎 Environment

```
napari: 0.4.18
Platform: Linux-5.14.0-1057-oem-x86_64-with-glibc2.37
System: Ubuntu 23.04
Python: 3.11.4 (main, Dec  7 2023, 15:43:41) [GCC 12.3.0]
Qt: 5.15.2
PyQt5: 5.15.10
NumPy: 1.26.3
SciPy: 1.12.0
Dask: 2024.1.1
VisPy: 0.12.2
magicgui: 0.8.1
superqt: 0.6.1
in-n-out: 0.1.9
app-model: 0.2.4
npe2: 0.7.4

OpenGL:
  - GL version:  4.6.0 NVIDIA 530.30.02
  - MAX_TEXTURE_SIZE: 32768

Screens:
  - screen 1: resolution 2560x1440, scale 1.0
  - screen 2: resolution 1920x1200, scale 1.0

Settings path:
  - /home/plumail/.config/napari/venv_da3673a96b885522b893f32926f8dca2562a61bf/settings.yaml
Plugins:
  - napari: 0.4.18 (77 contributions)
  - napari-console: 0.0.9 (0 contributions)
  - napari-svg: 0.1.10 (2 contributions)
```

### 💡 Additional Context

I investigated a bit and I think it comes down to this [line](https://github.com/napari/napari/blob/dd9938312702aa693c5c918374661fe2d33f360d/napari/layers/shapes/shapes.py#L2806C39-L2806C64) where `self._normalized_vertex_radius` may be too low?

**Comment by Czaki** [comment]
As I check the problem is connected with non-isotropic scale. I could confirm that it is present on 0.4.19 and current situation is worse as size of balls is big (even for isotropic scale).

![Zrzut ekranu z 2024-01-29 15-09-03](https://github.com/napari/napari/assets/3826210/3c1c9a7c-6f8d-42d7-970e-7e179916aa58)

When I run code snipped on main, no shape is shown. 

So we got multiple bugs at once. 

cc @brisvag

**Comment by Czaki** [comment]
After fixes bug that prevents from rendering on main and have big thickness of visuals, it looks like the bug does not exist on 0.4.19x branch and on main. Maybe someone coul also check this.

**Comment by jplumail** [comment]
Yes I can confirm that the bug does not exist on main and 0.4.19x. Thanks !
