### ISSUE TITLE
environmental vars are ignored if an experimental setting is set (e.g. async is enabled)

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari/napari#6637]
### 🐛 Bug Report

If I have async (or autoswap) set (enabled) in Preferences > Experimental (box is checked, settings.yaml: `async_: true` ) then trying to *disable* via environmental variable doesn't work.
The opposite does work, so if the setting is **unset** in the Settings, then setting it via environmental variable is respected and does work.

Edit: setting the value directly, rather than by using the `env` value does work, so you *can* use: `NAPARI_EXPERIMENTAL_ASYNC_=0 napari`

Edit2: But setting two variables from the same area, by full name also doesn't work, e.g. `NAPARI_EXPERIMENTAL_AUTOSWAP_BUFFERS=0 NAPARI_EXPERIMENTAL_ASYNC_=0 napari` will only set the first.

### 💡 Steps to Reproduce

Launch napari and ensure that Preferences > Experimental > Render Images Asynchronously is checked (so True).
restart napari with: `NAPARI_ASYNC=0 napari` 
Load Balls (3D) sample and play with slider quickly to see that async is still on.

### 💡 Expected Behavior

The state of the environmental variable should be respected and should take priority over what I have in the settings, so I that I can quickly and easily disable something while testing or demoing.

### 🌎 Environment

napari: 0.5.0a2.dev533+gc6abeb5d
Platform: macOS-14.2.1-arm64-arm-64bit
System: MacOS 14.2.1
Python: 3.11.7 | packaged by conda-forge | (main, Dec 23 2023, 14:38:07) [Clang 16.0.6 ]
Qt: 6.6.1
PyQt6: 
NumPy: 1.26.3
SciPy: 1.12.0
Dask: 2024.1.1
VisPy: 0.14.1
magicgui: 0.8.1
superqt: 0.6.1
in-n-out: 0.1.9
app-model: 0.2.4
npe2: 0.7.4

OpenGL:
- GL version: 2.1 Metal - 88
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 2056x1329, scale 2.0
- screen 2: resolution 2560x1440, scale 1.0

Settings path:
- /Users/sobolp/Library/Application Support/napari/napari-dev_36963bf0846bfe99dcf4f566a2cc780b6a723afa/settings.yaml

**Comment by psobolewskiPhD** [comment]
I *think* I may have spotted a problem with the logic of `nested_env_settings` that might be responsible for this. Need to do some more debugging--really should learn how to use a debugger properly I think... 👀

**Comment by andy-sweet** [comment]
Happy to review when you have a solution. I haven't looked much at this part of the code before, but would be happy to learn.

**Comment by psobolewskiPhD** [comment]
Interestingly, on main `RDP_EPSILON=1 napari` does work, even though it *doesn't* declare an `env`.
Likewise, `USE_NPE2_ADAPTOR=1 napari `
So something is up with EventedSettings handling I think

**Comment by psobolewskiPhD** [comment]
Ok! I've figured some more of it out. 
So `experimental` and `plugins` use napari EventedSettings 
https://github.com/napari/napari/blob/89f8194d3fa4eef620755804806ac69ef684df63/napari/settings/_base.py#L41
which uses pydantic BaseSettings class, which sets `env_names` which can be used as environmental variables as follows:
1. using `env='name'` or if not that then
2. using the name of the field with a prefix
See:
https://github.com/pydantic/pydantic/blob/832225b90672c68e2d4067bd0ffecf834d62b48b/pydantic/v1/env_settings.py#L94-L119

We don't specify a prefix in either of `experimental` or `plugins` and the default is '', so hence raw `RDP_EPSILON=1` works.

Meanwhile, `appearance` uses just EventedModel, so fields can only be set as env vars using `NAPARI_APPEARANCE_<field>`, so in this case the `env='napari_theme'` is ignored.

**Comment by psobolewskiPhD** [comment]
Only thing I don't understand is why `NAPARI_ASYNC=1` works after `napari --reset`.
