### ISSUE TITLE
numcodecs update breaking builds

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#665]
Just noticed our OSX and Windows builds are failing again... At first I was worried it was related to our recent CI updates in #658, but it looks like it's a failure to compile `numcodecs` v0.6.4 which was released today.  We could pin to 0.6.3, or just keep an eye on it

**Comment by sofroniewn** [comment]
It looks like 0.6.4 numcodecs is [failing to build on OSX](https://cirrus-ci.com/task/5355480448237568?command=install#L435) and windows. I have now raised an issue on the numcodes repo https://github.com/zarr-developers/numcodecs/issues/210. @jakirkham might also have ideas.

**Comment by jakirkham** [comment]
Do you have a C++ compiler on the CI? It appears that the build is complaining that it cannot find one.

Alternatively if you want to avoid building Numcodecs, you are welcome to use our binaries from conda-forge.

**Comment by sofroniewn** [comment]
I'm afraid I don't know. Thanks for weighing in. I defer to @jni for next steps.

Does it make sense to you that the change from `0.6.3` to `0.6.4` would trigger this build error?

**Comment by jakirkham** [comment]
We upgraded Numcodecs' vendored copy of Blosc in this release. Blosc vendors many more compression libraries, which it updated as well. So the odds for some sort of surprise like this are quite high. Interestingly the Blosc upgrade was made to fix some compilation issues.

Note: The CI appears to have failed while building Snappy.

**Comment by AhmetCanSolak** [comment]
btw `numcodecs` also a problematic package for bundling with pyinstaller(I know due to Blosc it is there). I appreciate at crazy levels if any of you guys manage to drop it at some point :)

**Comment by jakirkham** [comment]
@AhmetCanSolak, can you please raise an issue on the Numcodecs issue tracker with more details about why it is difficult to include in PyInstaller?

**Comment by tlambert03** [comment]
Just had someone someone email me directly because they tried to `pip install napari` but it didn't work.  So anyone who tries to install napari as described in the readme (and who doesn't have the appropriate build tools on their computer) is going to have this issue at the moment.  For this person, they had to either `pip install numcodecs==0.6.3 napari` or `conda install numcodecs; pip install napari`

**Comment by AhmetCanSolak** [comment]
@jakirkham i will drop and issue once i get back to bundling again.

@tlambert03 you are right, tested `pip install napari` and crashed again related to numcodecs. Tested in a fresh conda environment for py3.7

**Comment by sofroniewn** [comment]
ah ok - that's no good. To fix we'd need to pin to `0.6.3` and push a `0.2.5` to pypi. I'm very open to doing this as a temporary fix until we understand a long term solution. What does everyone think? I don't really like that our pip install fails.

@AhmetCanSolak, do both `pip install zarr` and `pip install dask[array]` fail on your test environment too? I see dask just bumped a new release about 2 hours ago.

@jni should be waking up soon - though it is his Saturday! - I'm curious what he recommends.

**Comment by AhmetCanSolak** [comment]
@sofroniewn dask seems okay, zarr fails too

**Comment by sofroniewn** [comment]
When I make a venv on my mac laptop `pip install zarr` works

**Comment by jni** [comment]
@sofroniewn 

> @jni should be waking up soon

yes @jni was peacefully reading in bed when he saw this thread and was rudely awakened. =P

> When I make a venv on my mac laptop pip install zarr works

Your laptop might not be a typical user's laptop, especially now that Apple doesn't ship a C compiler by default. I just tried pip install napari in a new env on my Mac and it failed. That's bad news.

I dislike the idea of pinning, but I can't think of a better one now. However, rather than pin, use `!=0.6.4` so that future versions can be evaluated as they come.

**Comment by jni** [comment]
@jakirkham I have a C++ compiler on my Mac and it still failed:

```
 $ g++ --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

`pip install numcodecs` still errored with:

```
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/nuneziglesiasj/conda/envs/napari-numcodecs/include -arch x86_64 -I/Users/nuneziglesiasj/conda/envs/napari-numcodecs/include -arch x86_64 -DHAVE_LZ4=1 -DHAVE_SNAPPY=1 -DHAVE_ZLIB=1 -DHAVE_ZSTD=1 -Ic-blosc/blosc -Ic-blosc/internal-complibs/lz4-1.9.1 -Ic-blosc/internal-complibs/snappy-1.1.1 -Ic-blosc/internal-complibs/zstd-1.4.1 -Ic-blosc/internal-complibs/zlib-1.2.8 -Ic-blosc/internal-complibs/zstd-1.4.1/compress -Ic-blosc/internal-complibs/zstd-1.4.1/dictBuilder -Ic-blosc/internal-complibs/zstd-1.4.1/decompress -Ic-blosc/internal-complibs/zstd-1.4.1/legacy -Ic-blosc/internal-complibs/zstd-1.4.1/common -Ic-blosc/internal-complibs/zstd-1.4.1/dll -Ic-blosc/internal-complibs/zstd-1.4.1/deprecated -I/Users/nuneziglesiasj/conda/envs/napari-numcodecs/include/python3.7m -c c-blosc/internal-complibs/snappy-1.1.1/snappy-stubs-internal.cc -o build/temp.macosx-10.7-x86_64-3.7/c-blosc/internal-complibs/snappy-1.1.1/snappy-stubs-internal.o -msse2 -DSHUFFLE_SSE2_ENABLED
  warning: include path for stdlibc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
  c-blosc/internal-complibs/snappy-1.1.1/snappy-stubs-internal.cc:29:10: fatal error: 'algorithm' file not found
```

Is there some C++ dependency that's missing? Or some setup.py configuration that specifies that C++ headers are needed?

**Comment by sofroniewn** [comment]
Ok, i'm going to make the `0.2.5` release so pip install continues to work will make release notes now

**Comment by jni** [comment]
Cool, am online and can review. Thanks @sofroniewn!

**Comment by sofroniewn** [comment]
`0.2.5` release is now out!

**Comment by sofroniewn** [comment]
In #873 we have dropped our explicit zarr dependency and so this issue is no longer present in `0.2.10`
