### ISSUE TITLE
Add "About napari" menu option on macOS

### ISSUE THREAD

**Issue by dstansby** [napari/napari#6662]
## 🚀 Feature
Apps on macOS have a standard place for an "About <name of app>" entry in the menu, e.g. for Firefox:

![Screenshot 2024-02-13 at 17 29 40](https://github.com/napari/napari/assets/6197628/8df4dcb3-7cb7-4cb8-aa4a-2686e80d41bd)

It would be nice for napari to have this too; currently it doesn't:
![Screenshot 2024-02-13 at 17 30 00](https://github.com/napari/napari/assets/6197628/48cd6186-4d35-4aae-a16d-3fbfa51510c2)

**Comment by psobolewskiPhD** [comment]
I agree it would be nice -- I've thought about it (and a few other macOS menu things) having the napari info there, the issue is that then it makes docs hard because we say it's in Help and would need to clarify that on macOS we mean napari menu. Not sure we can put a menu item in two places 🤔

**Comment by dalthviz** [comment]
Hi there, just in case, I think you can't have the same action instance in multiple menus but I think it should be possible to create multiple actions instances triggering the same logic. So it should be possible to keep the current action (`napari Info`) and add a second one with the name `About napari` which triggers the same logic and which should be conditioned to only be added to a menu when running on macOS.

Here a quick implementation attempt:   https://github.com/napari/napari/compare/main...dalthviz:napari:issue_6662

Let me know if that makes sense!

**Comment by psobolewskiPhD** [comment]
Seems ok, I like renaming it to `About napari`. In my attempt here: https://github.com/napari/napari/pull/5096 I used `menuRole` set to `QAction.AboutRole` but that was before app-model, so not sure that can work.

**Comment by dalthviz** [comment]
So checked again and, although I was unable to figure out the `menuRole` config, I noticed that we could make the two actions have the `About napari` text and then you will be able to see one `About napari` action over the macOS application menu and one over the help menu. My guess is that on macOS the first action that is encountered having the word `about` in its text gets relocated to the application menu and no further actions get relocated even when they have as part of their text the word `about` :thinking:

A preview:



Anyhow, updated the code at https://github.com/napari/napari/compare/main...dalthviz:napari:issue_6662 if someone wants to give it a check. If that is good enough let me know to open a PR with those changes

**Comment by psobolewskiPhD** [comment]
Does it work if we revert this change:
```
---CommandId.NAPARI_INFO: _i(trans._('napari Info')),
+++CommandId.NAPARI_ABOUT: _i(trans._('‎About napari')),
```
So that the help menu shows the napari info on all systems, unchanged?

**Comment by dalthviz** [comment]
Yep, so you mean like this:

* on Windows:

![about_action](https://github.com/napari/napari/assets/16781833/97e7eb02-143d-484c-954e-00ef236cea67)

* on macOS:

TODO

right?

**Comment by psobolewskiPhD** [comment]
Looks good to me! Keeps our docs consistent and also puts the thing where a Mac user would expect!

**Comment by dstansby** [comment]
🎉 thanks all who helped make this happen!
