### ISSUE TITLE
Expose layer features index in text format string

### ISSUE THREAD

**Issue by aeisenbarth** [napari/napari#6667]
## 🚀 Feature

Make an easy way to add points with unique, automatically enumerated texts.

## Motivation

For some applications, it is important that users can distinguish points and understand their order (e.g. registration, affinder etc.). For this, one could provide `text` with a variable that is filled with a unique value for each point, producing a unique text displayed next to each point.

```pycon
>>> import numpy as np, pandas as pd
>>> layer = viewer.add_points([[0, 0], [0, 100], [0, 200]], features=pd.DataFrame({"col": [0, 1, 2]}), text={"string": "col: {col}", "anchor": "lower_left"})
>>> # User clicks to add more points
>>> layer.data = np.vstack([layer.data, [0, 300]]) # simulating "add points"
>>> layer.text.values
Out[20]: array(['col: 0', 'col: 1', 'col: 2', 'col: 2'], dtype='<U7')
```

These variables are taken from the features dataframe. This requires that a features dataframe is provided. When a new point is added, it does not yet have a value in the features dataframe. Then the value of the last row is copied as fallback (if I'm not mistaken). A dataframe does not have an automatic incrementation feature. This also means the last text is duplicated, and not unique.

Currently, the only way is to listen for `data` changes events and then set values to the features dataframe, which then updates and corrects the wrong text for the newly added point. This seems like an unnecessary cycle because Napari set the text twice, and requires extra code to be written by developers.

## Pitch

Expose "index" as a variable in the format string that users can provide to the text manager, so that there is an easy way to make points with enumerated or unique texts.

## Alternatives

- Exposing the features dataframe index as "index" (or another variable name) in [`FormatStringEncoding.__call__`](https://github.com/napari/napari/blob/7e6a243f9e1b3d4a222c6b2096c288fd70b5bb8b/napari/layers/utils/string_encoding.py#L168) seems to me like a simple solution. There should be not much risk involved, because extra keys in `format` do not raise an error if not used. On the other side, a dataframe could contain a column `"index"`, so either we would have to declare it a forbidden column, use another index name ("_index") or let "index" in the columns override the dataframe index (after all the users set it explicitly, and specified it in the format string explicitly, so should know what they do).
  ```pycon
  >>> layer = viewer.add_points([], text={"string": "index: {index}", "anchor": "lower_left"})
  >>> layer.data = np.vstack([layer.data, [0, 0]]) # simulating "add points"
  >>> layer.data = np.vstack([layer.data, [0, 100]])
  >>> layer.data = np.vstack([layer.data, [0, 200]])
  >>> layer.data = np.vstack([layer.data, [0, 300]])
  >>> layer.text.values
  Out[20]: array(['col: 0', 'col: 1', 'col: 2', 'col: 3'], dtype='<U7')
  ```

- An alternative could be a new layer argument where the user provides a sort of "new value factory" that is called when a new value is needed (for a new dataframe row, for each column) and receives some context. This would give users more freedom, including incrementing strings ("monday", "tuesday"…).

**Comment by andy-sweet** [comment]
> * An alternative could be a new layer argument where the user provides a sort of "new value factory" that is called when a new value is needed (for a new dataframe row, for each column) and receives some context. This would give users more freedom, including incrementing strings ("monday", "tuesday"…).

We had some similar ideas in in #4065

The factory solution feels like the right approach to me, but I haven't thought through the details or API yet. Would be happy to look at potential solutions though!

Before that I'll take a look at the simpler solution in #6703

**Comment by andy-sweet** [comment]
I think was closed by https://github.com/napari/napari/pull/6703 but `Solves` is not in the GitHub approved list of closing keywords: https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests#linking-a-pull-request-to-an-issue
