### ISSUE TITLE
switching themes causes incomplete updates

### ISSUE THREAD

**Issue by jni** [napari/napari#669]
## 🐛 Bug

The 'light' theme for napari is looking pretty terrible these days:

<img width="1200" alt="Screen Shot 2019-11-09 at 8 58 44 pm" src="https://user-images.githubusercontent.com/492549/68526810-c2860580-0333-11ea-8455-4bea32aedf01.png">

We should update it and make sure that any PRs that touch the UI are tested with both themes.

Also worth noting that the base layer needs to have blending mode "translucent" — with additive, you get a totally white canvas. Perhaps it's a chance to play with inverted LUTs or something, not sure.

Finally, I'm not sure whether there is a way to set the theme globally. I could set it on a Viewer instance, but I could not set it on the `napari.Viewer` class. It seems to me that it should be more of a global than an instance setting.

## To Reproduce

```python
import napari
v = napari.Viewer()
v.theme = 'light'
```

This crashes:

```python
import napari
napari.Viewer.theme = 'light'
v = napari.Viewer()
```

This makes sense because it replaces a property with a text string! But I couldn't find how else to set the theme.

**Comment by jni** [comment]
Bonus issue: changing back to dark doesn't work fully:

```python
v.theme = 'dark'
```

<img width="1200" alt="Screen Shot 2019-11-09 at 9 17 38 pm" src="https://user-images.githubusercontent.com/492549/68527028-78525380-0336-11ea-9c7e-bbad8c98e504.png">

**Comment by sofroniewn** [comment]
good to flag!! I'll take a look. our stylesheets need some love in general too

**Comment by marciovm** [comment]
Any reason not to deprecate theme options, and make dark the only option? Having theme options makes UI iteration much more expensive.

**Comment by sofroniewn** [comment]
@jni theme looks fine on my mac so this might be something cross platform :-( 

<img width="1200" alt="Screen Shot 2019-11-11 at 8 17 39 AM" src="https://user-images.githubusercontent.com/6531703/68602853-f52b1d80-045b-11ea-90bc-7b40282e4119.png">

@marciovm we've had comments from people who prefer `light` to `dark`. The way we've set it up should make it pretty easy to maintain both - we have color palettes and style using the palettes, but something funky seems to be happening above :-(

**Comment by AhmetCanSolak** [comment]
@sofroniewn maybe not right place to discuss but isn't it better to keep canvas background black on both themes?

**Comment by sofroniewn** [comment]
Discussing here is good @AhmetCanSolak. I'm completely open to that, and it's easy to change, but curious why do you think black is a better canvas background for both themes? I guess it might be more consistent, but I though it looked nicer to have a white background with the light theme. @jni were you suggesting this too? I think @alexdesiqueira was someone who was excited about the light theme if I remember correctly :-) so curious what they prefer

**Comment by AhmetCanSolak** [comment]
I think black background is more comfortable as white could possibly interfere with image edges or with some other layers. Not a big deal but just to me black background by default makes more sense.

**Comment by jni** [comment]
@sofroniewn please note the problem above. If someone uses code where all the layers have blending mode "additive" (as `channel_axis=n` does), then the image is just all white if the canvas is white. That's a problem.

Regarding the platform dependence: I'm on Catalina, are you? And, can you try with a fresh install from pip? (I am trying it now, but am on a crappy connection so it might take me a while.)

**Comment by alexdesiqueira** [comment]
Hey all,
thanks for remembering @sofroniewn! I don't care about the default, if there's an option for a light theme. :blush: however, @marciovm put a good point: how expensive it is to maintain other themes?

**Comment by sofroniewn** [comment]
reverting to black as a default background makes sense for the reason @jni provides. we can do that soon.

I am on mojave:
<img width="698" alt="Screen Shot 2019-11-11 at 1 20 21 PM" src="https://user-images.githubusercontent.com/6531703/68622057-130d7800-0486-11ea-92b5-eb9ff1e815fa.png">

**Comment by jni** [comment]
I'll try again on my old MBP when I get home and report back. If any other Mac users want to report their results here, we would be grateful!

**Comment by tlambert03** [comment]
mine looks more like @jni   I'm stuck on high sierra cause I want to use my NVIDIA card and apple sucks.  (it's a hackintosh for what it's worth... but I wouldn't expect that to affect this).

<img width="698" alt="Screen Shot 2019-11-11 at 4 40 15 PM" src="https://user-images.githubusercontent.com/1609449/68623259-144c9e00-04a2-11ea-8c21-78271783ceae.png">
<img width="1010" alt="Screen Shot 2019-11-11 at 4 40 10 PM" src="https://user-images.githubusercontent.com/1609449/68623260-144c9e00-04a2-11ea-92a6-97510c03cce9.png">

```
napari, 0.2.4+12.g6c5bb037
Qt, 5.13.1
NumPy, 1.17.3
SciPy, 1.3.1
VisPy, 0.6.2
scikit-image, 0.16.1

Platform: Darwin-17.7.0-x86_64-i386-64bit
Python:   3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 14:38:56) 
   [Clang 4.0.1 (tags/RELEASE_401/final)]
Backend:  PySide2
GL version:  '2.1 NVIDIA-10.33.0 387.10.10.15.15.108'
MAX_TEXTURE_SIZE: 16384
```

**Comment by tlambert03** [comment]
here's a different mac, this one a macbook pro on mojave.  Interestingly, this one didn't even try in the controls area.  Strange that we're seeing more than just 2 phenotypes!

<img width="1200" alt="Screen Shot 2019-11-11 at 4 47 24 PM" src="https://user-images.githubusercontent.com/1609449/68623732-2a0e9300-04a3-11ea-9070-30357f0b0b90.png">
<img width="698" alt="Screen Shot 2019-11-11 at 4 47 49 PM" src="https://user-images.githubusercontent.com/1609449/68623733-2aa72980-04a3-11ea-88bf-7599fb66e62b.png">

```
napari, 0.2.4+12.g6c5bb037
Qt, 5.13.1
NumPy, 1.17.3
SciPy, 1.3.1
VisPy, 0.6.1
scikit-image, 0.16.2

Platform: Darwin-18.7.0-x86_64-i386-64bit
Python:   3.7.3 | packaged by conda-forge | 
   (default, Jul  1 2019, 14:38:56)  [Clang 4.0.1 (tags/RELEASE_401/final)]
Backend:  PySide2
GL version:  '2.1 NVIDIA-12.0.24 355.11.10.50.10.103'
MAX_TEXTURE_SIZE: 16384
```

**Comment by sofroniewn** [comment]
looks like I'm on `PyQt5` by default - lol!

```bash
napari, 0.2.5+1.gbc92411
Qt, 5.12.3
NumPy, 1.17.2
SciPy, 1.2.1
VisPy, 0.6.3.dev7+g839ada88
scikit-image, 0.15.0

Platform: Darwin-18.5.0-x86_64-i386-64bit
Python:   3.7.3 (default, Mar 27 2019, 16:54:48)  [Clang 4.0.1 (tags/RELEASE_401/final)]
Backend:  PyQt5
GL version:  '2.1 INTEL-12.8.38'
MAX_TEXTURE_SIZE: 16384
```
so that maybe it ...

**Comment by sofroniewn** [comment]
Nope! It's not!!! No change for

```bash
Platform: Darwin-18.5.0-x86_64-i386-64bit
Python:   3.7.3 (default, Mar 27 2019, 16:54:48)  [Clang 4.0.1 (tags/RELEASE_401/final)]
Backend:  PySide2
GL version:  '2.1 INTEL-12.8.38'
MAX_TEXTURE_SIZE: 16384
```
still looks great on mine

**Comment by tlambert03** [comment]
couldn't be Qt 5.13 v 5.12?

**Comment by sofroniewn** [comment]
maybe it's Qt 5.13, I can try upgrading.

Also @jni @tlambert03 - if you overwrite the hardcoded default to be `light` here https://github.com/napari/napari/blob/6c5bb037e191bce3c05c5bf23f4f143ecc89a240/napari/components/viewer_model.py#L87

how does it look? i.e. is this about switching, or will it still look bad?

**Comment by sofroniewn** [comment]
upgraded my PySide2, but no change - bellow still works for me.

```
napari, 0.2.5+1.gbc92411
Qt, 5.13.2
NumPy, 1.17.2
SciPy, 1.2.1
VisPy, 0.6.3.dev7+g839ada88
scikit-image, 0.15.0
```

We should also print the PySide2 / PyQt5 version # in that top part too

**Comment by tlambert03** [comment]
yeah, it's the switching.  If I hard-code in the theme it looks fine, and here's what it looks like when I switch back (inverted problem from above).  so that should help narrow it down

<img width="928" alt="Screen Shot 2019-11-11 at 5 08 35 PM" src="https://user-images.githubusercontent.com/1609449/68625035-38aa7980-04a6-11ea-9640-c77a692f3f06.png">

note also: that the console button switched back to the darktheme after I clicked on it... but the other control buttons did not switch upon clicking

**Comment by sofroniewn** [comment]
Switching in Qt has some known problems - we often need to call these commands `polish` and `unpolish` to get around them, I imaging throwing a couple more of them in there will fix this, what is so strange to me is the difference between my machine and yours!!!

**Comment by sofroniewn** [comment]
In general our stylesheets are a bit of a mess right now (which is likely independent of this problem), but we should probably give organizing them some attention, it might also speed up the load time (though I don't know that)

**Comment by jni** [comment]
@sofroniewn perhaps whatever difference was causing your double title bar (which only happened on your machine iirc) is also causing this??? LOL

have you tried a pip install in a clean environment? I wonder if you have some artefacts in your working directory that somehow makes this behave nicely.
