### ISSUE TITLE
Add swap dims functionality to GUI

### ISSUE THREAD

**Issue by macromeer** [napari/napari#6691]
## 🚀 Feature
Add swap dims (axes) as layer option.

## Motivation

People load image data from all kinds of sources with different dim order. This adds difficulty to users who exclusively use the GUI. People then usually retract to Fiji. There you have the option Image > Hyperstacks > Re-order Hyperstack. It would be good to have a similar option in Napari.

**Comment by psobolewskiPhD** [comment]
Unless I am misunderstanding, this is already possible, by right-click on the roll dimensions viewer button, see:
https://napari.org/stable/tutorials/fundamentals/viewer.html#roll-dimensions

**Comment by psobolewskiPhD** [comment]
Is it clear? If not please feel free to provide some feedback and we can improve this!
❤️

**Comment by Czaki** [comment]
Did we document it somewhere?

**Comment by psobolewskiPhD** [comment]
I linked to the Viewer docs where it's documented. Do you think it should also be somewhere else?

**Comment by Czaki** [comment]
I think that we should name this section "re-order dimensions" instead "roll dimensions" to be more discoverable. And put more focus on right click menu. 

I need to double read to find this information.
