### ISSUE TITLE
Creating `DirectLabelColormap` with `dict` crashes

### ISSUE THREAD

**Issue by Modjular** [napari/napari#6714]
### 🐛 Bug Report

As of `4.19.post1`, we now get this warning when setting the `color` field of a `Layer.Labels`:

```
Labels.color is deprecated since 0.4.19 and will be removed in 0.5.0, please set Labels.colormap directly with an instance of napari.utils.colormaps.DirectLabelColormap instead.
```

I have a simple colormap dict. Its the same one I've used before:
```
mycolors = {1:[1.0,1.0,1.0], 99999:[0.0,0.0,1.0]}
```

But it raises when I try to pass that into `DirectLabelColormap`:

```
from napari.utils.colormaps import DirectLabelColormap

mycolors = {1:[1.0,1.0,1.0], 99999:[0.0,0.0,1.0]}
mycolormap = DirectLabelColormap(mycolors)  # raises
```
```
File ~/Documents/Github/brain-seeker/.venv/lib/python3.10/site-packages/napari/utils/colormaps/standardize_color.py:65, in transform_color(colors)
     34 """Transforms provided color(s) to an Nx4 array of RGBA np.float32
     35 values.
     36 
   (...)
     62     invalid inputs
     63 """
     64 colortype = type(colors)
---> 65 return _color_switch[colortype](colors)

KeyError: <class 'dict'>
```

### 💡 Steps to Reproduce

```python
from napari.utils.colormaps import DirectLabelColormap

mycolors = {1:[1.0,1.0,1.0], 99999:[0.0,0.0,1.0]}
DirectLabelColormap(mycolors)
```

### 💡 Expected Behavior

No crash

### 🌎 Environment

napari: 0.4.19.post1
Platform: macOS-12.6-arm64-arm-64bit
System: MacOS 12.6
Python: 3.10.3 (v3.10.3:a342a49189, Mar 16 2022, 09:34:18) [Clang 13.0.0 (clang-1300.0.29.30)]
Qt: 6.5.2
PyQt6: 
NumPy: 1.24.3
SciPy: 1.8.0
Dask: 2023.9.3
VisPy: 0.14.1
magicgui: 0.7.3
superqt: 0.6.1
in-n-out: 0.1.9
app-model: 0.2.2
npe2: 0.7.2

OpenGL:
- GL version: 2.1 Metal - 76.3
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1512x982, scale 2.0
- screen 2: resolution 1080x1920, scale 1.0
- screen 3: resolution 1920x1080, scale 1.0

### 💡 Additional Context

Happens on both Macos and a Windows VM. Did not happen before upgrading from `4.18`

**Comment by Czaki** [comment]
Please use:

```python
from napari.utils.colormaps import DirectLabelColormap

mycolors = {1:[1.0,1.0,1.0], 99999:[0.0,0.0,1.0], None: [0,0,0,1]}
DirectLabelColormap(color_dict=mycolors)
```

or 
```
from napari.utils.colormaps import direct_colormap
mycolors = {1:[1.0,1.0,1.0], 99999:[0.0,0.0,1.0], None: [0,0,0,1]}
direct_colormap(mycolors)
```
Where `None` is value used for color not present in dict. 


We need to provide better docstring/error message.

**Comment by Czaki** [comment]
I do not understand. why you ask about `_color_switch`?

**Comment by Modjular** [comment]
@Czaki my bad, I didn't see your reply. I was trying to provide more bug documentation

**Comment by Modjular** [comment]
> Where None is value used for color not present in dict.

This makes sense now
