### ISSUE TITLE
Adding multiple surfaces to 3D view causes error

### ISSUE THREAD

**Issue by jni** [napari/napari#672]
## 🐛 Bug

I wanted to add a grayscale surface for a 3D image (the allen brain atlas in this case), then overlay a surface with the label values. I got an "axis out of bounds error". 

## To Reproduce

Here's a reproducible example using binary blobs:

**Update:** Just using `ndisplay=3` is enough. The error happens when the viewer has ndisplay=3 and a surface is added. It doesn't have to be multiple surfaces.

```python
from skimage import data, measure
import napari

image = data.binary_blobs(128, n_dim=3)
verts, faces, normals, values = (
    measure.marching_cubes_lewiner(image.astype(float), level=0.7)
)

viewer = napari.view_surface((verts, faces, values), ndisplay=3)
```

Results in this error:

https://gist.github.com/jni/41e2d3686a6822a2748860413762fb43

The last few lines:

```pytb
/Volumes/Projects/napari/napari/_vispy/vispy_base_layer.py in <lambda>(e)
     44
     45         self.layer.events.refresh.connect(lambda e: self.node.update())
---> 46         self.layer.events.set_data.connect(lambda e: self._on_data_change())
     47
     48         self.layer.events.visible.connect(lambda e: self._on_visible_change())

/Volumes/Projects/napari/napari/_vispy/vispy_surface_layer.py in _on_data_change(self)
     47             )
     48         ):
---> 49             self._on_display_change()
     50
     51         if len(self.layer._data_view) == 0 or len(self.layer._view_faces) == 0:

/Volumes/Projects/napari/napari/_vispy/vispy_surface_layer.py in _on_display_change(self)
     32         self.reset()
     33         for b in range(self.layer.dims.ndisplay):
---> 34             self.node.bounds(b)
     35
     36     def _on_data_change(self):

/Volumes/Projects/vispy/vispy/visuals/visual.py in bounds(self, axis, view)
    249             view = self
    250         if axis not in self._vshare.bounds:
--> 251             self._vshare.bounds[axis] = self._compute_bounds(axis, view)
    252         return self._vshare.bounds[axis]
    253

/Volumes/Projects/vispy/vispy/visuals/mesh.py in _compute_bounds(self, axis, view)
    535         if self._bounds is None:
    536             return None
--> 537         return self._bounds[axis]

IndexError: list index out of range
```

suggest that there is an issue with the data bounds not being updated to have the correct dimensionality. Inspecting with `%debug` shows that `self._bounds` is a list containing just two len-2 lists of float.

Switching back and forth to 2D and 3D fixes the issue, albeit with some nasty tracebacks in the console.

## Expected behavior

The new surface should appear without issue.

**Comment by sofroniewn** [comment]
That's no good! I'll take a look - I'm also now getting the same error for

```python
viewer = Viewer(ndisplay=3)
layer = viewer.add_surface((verts, faces, values))
```
and I know that used to work, likely a regression after I removed some of the repeated `_on_data_change` calls a couple PRs back. Will need a fix and some better tests

**Comment by jni** [comment]
Ah, yes, just updated the issue based on further exploration. On the plus side, writing a test for this should be nice and easy, once fixed. =)
