### ISSUE TITLE
`QtViewerDockWidget.isVisible` does not seem to work in tests

### ISSUE THREAD

**Issue by lucyleeow** [napari/napari#6722]
`isVisible` does not seem to work in tests for `QtViewerDockWidget`s. Noticed when working on #4991

e.g., the following test:
```python
def test_toggle_or_get_widget(make_napari_viewer):
    viewer = make_napari_viewer()
    viewer.window.add_dock_widget(QWidget_example(viewer), name='test')
    widget = viewer.window._dock_widgets['test']
    print(widget.isVisible())
```
prints `False`.

When manually testing plugin menu toggling widget, it does work as expected.

Have discussed this with @DragaDoncila who has noted this not working inside tests.
Related ref: https://github.com/napari/napari/pull/4991#discussion_r1368056355

cc @Czaki

**Comment by DragaDoncila** [comment]
I've experienced this with other qt tests before, definitely with the `ActivityDialog` and possibly also with the `QtReaderDialog` although my memories of that are more vague. I'll note also that we've tried using `show=True` with `make_napari_viewer` and that does not address the issue in the cases I've seen.

**Comment by Czaki** [comment]
this should work:

```python
def test_toggle_or_get_widget(make_napari_viewer, qtbot):
    viewer = make_napari_viewer(show=True)
    viewer.window.add_dock_widget(QWidget_example(viewer), name='test')
    widget = viewer.window._dock_widgets['test']
    qtbot.wait_until(widget.isVisible)
    assert widget.isVisible()
```

Qt requires time to show something

**Comment by DragaDoncila** [comment]
Wow @Czaki if this works I'm gonna be so happy 😂 it would be great if we could start putting together a testing guide and adding tips like this to it

**Comment by lucyleeow** [comment]
Interesting, and also why do we need `show=True` ?

**Comment by lucyleeow** [comment]
And in cases where the widget is not visible, how long will `qtbot.wait_until(widget.isVisible)` wait for max? Do i need to take care when I use this?

**Comment by lucyleeow** [comment]
I also had problems with testing `isChecked`, I will test this approach there too.

**Comment by Czaki** [comment]
> Interesting, and also why do we need `show=True` ?

Because widget will not be visible if the parent object is not visible



> And in cases where the widget is not visible, how long will `qtbot.wait_until(widget.isVisible)` wait for max? Do i need to take care when I use this (in case i cause timeout problems)?

`wait_until` (same as [waitUntil](https://pytest-qt.readthedocs.io/en/latest/reference.html#pytestqt.qtbot.QtBot.waitUntil)) has a default 5 seconds timeout.  So you do not need to worry. If timeout is exceeded then the test will fail.

**Comment by dalthviz** [comment]
Hi there, just in case, some other methods/utilities that could be useful when checking widgets visibility when testing:

* `QWidget.isVisibleTo`: https://doc.qt.io/qt-6/qwidget.html#isVisibleTo
* `qtbot.waitExposed`: https://pytest-qt.readthedocs.io/en/latest/reference.html#pytestqt.qtbot.QtBot.waitExposed

**Comment by lucyleeow** [comment]
Thanks all, I will close this and open a PR in docs to add some of this info to our docs.
