### ISSUE TITLE
`QtViewer.viewer` type should be `Viewer` not `ViewerModel`

### ISSUE THREAD

**Issue by lucyleeow** [napari/napari#6742]
`QtViewer.viewer` is typed as `ViewerModel`:

https://github.com/napari/napari/blob/fa0c3b1a4ec1bfe9d66957e91fab55951cb09ee9/napari/_qt/qt_viewer.py#L179-L181

but looking at where it is used (in `_QtMainWindow.__init__` ):

https://github.com/napari/napari/blob/fa0c3b1a4ec1bfe9d66957e91fab55951cb09ee9/napari/_qt/qt_main_window.py#L119-L125

the `viewer` that is passed to `QtViewer` is typed `Viewer` and if we follow it back to where it is used in `Window.__init__`:

https://github.com/napari/napari/blob/fa0c3b1a4ec1bfe9d66957e91fab55951cb09ee9/napari/_qt/qt_main_window.py#L651

the `viewer` here is typed as `Viewer`, and if we follow it further back to `Viewer.__init__`:

https://github.com/napari/napari/blob/fa0c3b1a4ec1bfe9d66957e91fab55951cb09ee9/napari/viewer.py#L69

we can confirm the `viewer` passed down is `Viewer` NOT `ViewerModel` (I know `Viewer` inherits from `ViewerModel` but `Viewer` is more accurate).

cc @DragaDoncila @jni

**Comment by jni** [comment]
Hmm, it's a good Q. I think the type here should be as precise as it must be but no more. ie if a QtViewer *can* work with just a ViewerModel, then the type should be ViewerModel, but if it actually assumes a Viewer then it should be updated.

But I'm not that familiar with typing so I don't know if there are other considerations here.

@lucyleeow in what context did you run into this?

**Comment by Czaki** [comment]
`QtViewer` may work with `ViewerModel` (for example, in PartSeg I use it only with `ViewerModel`)

**Comment by lucyleeow** [comment]
Ah okay I did not realise this detail. I was just confused when looking at the types. I'll close this
