### ISSUE TITLE
[Points] Deselecting (and selecting too) a lot of points is very slow

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari/napari#6746]
### 🐛 Bug Report

Originally noticed here:
https://github.com/napari/napari/issues/6275#issuecomment-1939599691

If you make 1e6 points, selecting them all is a bit slow (with psygnal 0.10.2, with 0.9.5 it hangs the viewer) -- blocks the viewer for a few seconds.
*Deselecting them* blocks the viewer for >2 min (maybe as much as 5, it does complete).

### 💡 Steps to Reproduce

Use this script from #6275 to make a layer with 1e6 points:
```
import numpy as np
import napari

rng = np.random.default_rng(seed=0)
data = rng.random(size=(1_000_000, 2)) * 1000
viewer = napari.Viewer()
viewer.add_points(data)
napari.run()
```
Press `a` to select all points.
Deselect by using `a` again.

### 💡 Expected Behavior

Selection taking a few seconds is ok, but could be better, since it does block.
Deselection I'd expect to be very fast, instant even, but maybe this is unrealistic. Still, 2-5 min is not good.

### 🌎 Environment

napari: 0.5.0a2.dev558+g62861b84
Platform: macOS-14.2.1-arm64-arm-64bit
System: MacOS 14.2.1
Python: 3.11.7 | packaged by conda-forge | (main, Dec 23 2023, 14:38:07) [Clang 16.0.6 ]
Qt: 6.6.1
PyQt6: 
NumPy: 1.26.3
SciPy: 1.12.0
Dask: 2024.1.1
VisPy: 0.14.2
magicgui: 0.8.1
superqt: 0.6.1
in-n-out: 0.1.9
app-model: 0.2.4
npe2: 0.7.4

OpenGL:
  - GL version:  2.1 Metal - 88
  - MAX_TEXTURE_SIZE: 16384
  - GL_MAX_3D_TEXTURE_SIZE: 2048

Screens:
  - screen 1: resolution 2056x1329, scale 2.0
  - screen 2: resolution 1920x1200, scale 1.0

Settings path:
  - /Users/sobolp/Library/Application Support/napari/napari-dev_36963bf0846bfe99dcf4f566a2cc780b6a723afa/settings.yaml
Plugins:
  - napari: 0.5.0a2.dev533+gc6abeb5d (81 contributions)
  - napari-animation: 0.0.8.dev36+g921f872 (2 contributions)
  - napari-console: 0.0.9 (0 contributions)
  - napari-foobar: 0.0.1 (8 contributions)
  - napari-ome-zarr: 0.5.2 (2 contributions)
  - napari-svg: 0.1.10 (2 contributions)

**Comment by jni** [comment]
Ooof.

I agree with you, this should be much much faster. 1m is not even that big a number. tbh I expect there is some low hanging fruit here.

**Comment by psobolewskiPhD** [comment]
NB: turns out `a` actually toggles selection of all pts! Need to update the description IMO.

**Comment by psobolewskiPhD** [comment]
With 0.5.1 and 1e6 points, selecting still takes a couple seconds, but deselection is instant now! 🎉 
I think the behavior is quite acceptable so will close. 🎉
