### ISSUE TITLE
Easy method to mention the napari team from vispy issues

### ISSUE THREAD

**Issue by djhoese** [napari/napari#676]
I'm not sure if github allows for this, but I was thinking today it would be nice given the napari team's close relationship with vispy development, if there was a way the vispy team could mention core napari team members with a single mention. I was wondering if a `@napari/viz` team or something like that could be created for easily tagging the visualization-specific team members. Anyone know if GitHub allows for me (a non-napari member) to tag a napari team from a non-napari repository? And more importantly, is this something that seems like a good idea and you would agree to?

**Comment by jni** [comment]
We'd *love* to be contacted this way! =) Can you try tagging @napari/core in a relevant VisPy issue (whichever incited this post, maybe? 😉) to see if I get notified?

We don't have a vispy-specific team yet but I think @napari/core should be able to route requests as needed for now.

**Comment by djhoese** [comment]
I was going to mention napari in https://github.com/vispy/vispy/pull/1748 to point out that a new release with another small bug fix was coming out, then realized you didn't need to know about it but thought I'd still start this issue. I tried writing a new comment with @napari/core and preview shows that it isn't linked. I can't even do it here it seems. Is the team private?

**Comment by jni** [comment]
Wow, this is annoying... The only permission I see is "visible" and that means "A visible team can be seen and @mentioned by every member of this organization". I don't see a setting for "allow anyone to just spam us", which is what I would want here.... =\ So I think your suspicion might have been right that GitHub might not allow this right now.

Might as well just tag @sofroniewn and me if needed, for now. 🤷‍♂

**Comment by djhoese** [comment]
Sounds good and good point that you don't want just anyone to be able to tag a team.

**Comment by sofroniewn** [comment]
That would be great @djhoese - if you're going to be making a new release soon, do you mind also merging https://github.com/vispy/vispy/pull/1702, I think it's all done and good to go
