### ISSUE TITLE
napari + dask.distributed + ipython kills kernel

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#679]
## 🐛 Bug

I'm pulling this comment out of #467 by @stefanv for separate discussion:

> running dask-distributed concurrently with %gui=qt in IPython doesn't work. In his words, "I can very reliably kill the kernel when using napari and dask together". The gui_qt() context manager does not suffer from this.

We need to look into this more to understand, but I wanted to make sure it didn't get lost

**Comment by jni** [comment]
@stefanv any chance you could write a minimum example for this?

**Comment by stefanv** [comment]
I suspect this may have been fixed, because Napari now forces you to create a Qt event loop (98734a3ba3c9b44178c4ba0bce864533ba19b6d5).

**Comment by jni** [comment]
@stefanv we always forced you, it's just that before you would get a crap, confusing message from Qt, now you get a nice message. You were probably using IPython with %gui qt, in which case we haven't changed anything...

**Comment by jni** [comment]
(that I can remember)

**Comment by stefanv** [comment]
Either way, I cannot seem to replicate; so feel free to close.

**Comment by sofroniewn** [comment]
Will close, can always reopen if problem reappears! Thanks
