### ISSUE TITLE
`ImportError: lxml.html.clean module is now a separate project lxml_html_clean` over test suite (Ubuntu 20.04 and benchmarks)

### ISSUE THREAD

**Issue by dalthviz** [napari/napari#6798]
## 🧰 Task

Seems like the latest release of `lxml` (5.2.0) moved a module to be an independant package (`lxml.html.clean` -> new `lxml_html_clean` package)? See https://github.com/napari/napari/actions/runs/8510883283/job/23309875720?pr=6794#step:11:174 and https://github.com/napari/napari/actions/runs/8510883283/job/23309397479?pr=6794#step:8:144

**Comment by psobolewskiPhD** [comment]
I looked into this for a bit more context:
https://lxml.de/5.2/changes-5.2.0.html
> The lxml.html.clean implementation suffered from several (only if used) security issues in the past and was now extracted into a separate library:
https://github.com/fedora-python/lxml_html_clean
Projects that use lxml without "lxml.html.clean" will not notice any difference, except that they won't have potentially vulnerable code installed. The module is available as an "extra" setuptools dependency "lxml[html_clean]", so that Projects that need "lxml.html.clean" will need to switch their requirements from "lxml" to "lxml[html_clean]", or install the new library themselves.

Googling around, it looks like there is some folks looking into alternatives to html_clean:
https://github.com/psf/requests-html/issues/558
`nh3` seems promising:
https://github.com/messense/nh3

Maybe in the short term we should migrate to the html_clean package, just to silence the CI errors but then we may want to consider whether we should replace it?

**Comment by psobolewskiPhD** [comment]
I played with nh3, here's a branch using that instead of lxml:
https://github.com/psobolewskiPhD/napari/tree/use_nh3_html_sanitizer

The main difference is handling quotes, where `nh3.clean` doesn't escape quotes.

**Comment by adriens** [comment]
Currently facing this error on a planned Notebook too

**Comment by adriens** [comment]
Hi guys, how should we overcome this
![image](https://github.com/napari/napari/assets/5235127/5c4f8cd8-1599-42ee-8a4a-ecd19f84771f)

**Comment by adriens** [comment]
Currently patched to this : 

```python
!pip install --upgrade lxml_html_clean

import geograpy

url = 'https://en.wikipedia.org/wiki/2012_Summer_Olympics_torch_relay'
places = geograpy.get_geoPlace_context(url=url)
print(places)
```

![image](https://github.com/napari/napari/assets/5235127/c9c69fca-c941-4dee-9999-5e228950b454)

**Comment by adriens** [comment]
It perfectly worked : I could update [🥷 Neo4J Ninjas duckdb dataset 🦆](https://www.kaggle.com/datasets/adriensales/neo4j-ninjas-duckdb-dataset)

**Comment by psobolewskiPhD** [comment]
It's impossible to figure out what the issue is.
We'll need the **text** of the entire traceback. You can post it between sets of three backticks ` so it's formatted as code.

**Comment by jamesnq** [comment]
![photo_2024-05-15_10-23-13](https://github.com/napari/napari/assets/55906599/cb763467-67e1-4329-916e-4fb1a6e40218)

I am currently facing this error, are there any way to fix it? Thank you!

**Comment by melissawm** [comment]
@jamesnq are you using napari? There's no way to tell from your screenshot. Please post the entire traceback *as text*. Thanks!

**Comment by jamesnq** [comment]
> @jamesnq are you using napari? There's no way to tell from your screenshot. Please post the entire traceback _as text_. Thanks!

Thanks for your reply, I already fixed the error. I install the lxml_html_clean library and run with python 3.10 instead of 3.12 and it works!

**Comment by CamachoDejay** [comment]
I had a similar issue, I am running a python 3.10 env, to solve the problem had to do:
`conda update napari`
`pip install lxml[html_clean]`

**Comment by ehlui** [comment]
Try to 

`pip install lxml_html_clean `

It might do the trick. This worked for me

**Comment by jamesnq** [comment]
try to install lxml_html_clean with python 3.10

**Comment by claydugo** [comment]
```
from napari import utils
```

Is causing an import error for me. Was hoping to avoid having to install this package that seems to only be used for testing.

**Comment by jni** [comment]
It's not just testing, it's used when producing screenshots [here](https://github.com/napari/napari/blob/6d207bf470237fcabdb20ed36a046ff041f6f803/napari/utils/notebook_display.py#L77-L102). However, it's supposed to be optional — I see now that we should replace [this catch](https://github.com/napari/napari/blob/6d207bf470237fcabdb20ed36a046ff041f6f803/napari/utils/notebook_display.py#L12) with an `ImportError`.
