### ISSUE TITLE
Cannot save boolean arrays to tif

### ISSUE THREAD

**Issue by jules-vanaret** [napari/napari#6805]
### 🐛 Bug Report

When trying to save an image layer with boolean data to a .tif file, Napari fails with the following error message:
```python
NotImplementedError: cannot compress bilevel image
```

### 💡 Steps to Reproduce

1. Open a Napari window
2. Type `import numpy as np; viewer.add_image(np.zeros((10,10), dtype=bool))` in the console
3. Save (ctrl+S) the newly added layer as a .tif file 

### 🌎 Environment

napari: 0.4.19.post1
Platform: Linux-5.15.0-101-generic-x86_64-with-glibc2.31
System: Ubuntu 20.04.6 LTS
Python: 3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:45:18) [GCC 12.3.0]
Qt: 5.15.2
PyQt5: 5.15.10
NumPy: 1.26.4
SciPy: 1.13.0
Dask: 2024.4.0
VisPy: 0.14.2
magicgui: 0.8.2
superqt: 0.6.3
in-n-out: 0.2.0
app-model: 0.2.6
npe2: 0.7.5

OpenGL:
  - GL version:  4.6 (Compatibility Profile) Mesa 21.2.6
  - MAX_TEXTURE_SIZE: 16384

### 💡 Additional Context

This is due to the fact that the default `zlib` compression scheme in `napari/utils/io.py`
```python
if compression_instead_of_compress:
    # 'compression' scheme is more complex. See:
    # https://forum.image.sc/t/problem-saving-generated-labels-in-cellpose-napari/54892/8
    tifffile.imwrite(filename, data, compression=('zlib', 1))
```
does not work for boolean arrays. 
A simple check could solve the issue:
```python
if compression_instead_of_compress:
    # 'compression' scheme is more complex. See:
    # https://forum.image.sc/t/problem-saving-generated-labels-in-cellpose-napari/54892/8
    if data.dtype == bool: 
        tifffile.imwrite(filename, data)
    else:
        tifffile.imwrite(filename, data, compression=('zlib', 1))
```

**Comment by GenevieveBuckley** [comment]
Closed by https://github.com/napari/napari/pull/6807
