### ISSUE TITLE
How to adjust the Z-axis spacing?

### ISSUE THREAD

**Issue by duxuan11** [napari/napari#6822]
The input data 3d volume, but its Z-axis height seems to be equal to the number of images, rather than the real Z-axis maximum and minimum values, may I ask where can I input Z-axis data in order to look more accurate in 3d visualization.
![image](https://github.com/napari/napari/assets/64136561/4527a206-0846-4cf5-be9c-7353f06c4485)
I know that in imagej it has max and min representing the range of the z axis.

**Comment by psobolewskiPhD** [comment]
Are you trying to set the scale of the stack? 
The attached image is really hard to decipher, but:
If you have 52 inches over 62 slices, then you have .839 in/slice.
In napari you can set the scale of a layer using:
`viewer.layer['name of your layer'].scale = [.838, 1, 1]`
Here I set the z-scaling based on your post, while x and y are left as 1, so 1 in per pixel.
