### ISSUE TITLE
Test processors

### ISSUE THREAD

**Issue by lucyleeow** [napari/napari#6847]
There are currently minimal tests for processors (see `napari/_qt/_qapp_model/_tests/test_processors.py`

They should at the very least be run.

**Comment by dalthviz** [comment]
Hi there, just in case, I think the `napari/_qt/_qapp_model/_tests/test_processors.py` test file is currently being run. For example:

https://github.com/napari/napari/actions/runs/10906488388/job/30270858900?pr=7269#step:13:349

Is there something else to be done here or maybe this could be closed or maybe I missing something related with the test file execution on CI?

**Comment by DragaDoncila** [comment]
@dalthviz the file is being run, but there's only one processor being tested in there (`_add_layer_data_to_viewer`). Ideally all of the processors in `napari/_qt/_qapp_model/injection/_qprocessors.py` would be tested individually.

It **might** be nice to actually check that as well as the functions themselves being tested, we also test a round trip where we execute an `app-model` action that returns a value that one of these processors should respond to, and that the processor is called (even with a mock). Maybe that's moving too far into testing `app-model` itself though so not sure about that last bit.

**Comment by lucyleeow** [comment]
> Maybe that's moving too far into testing app-model itself though so not sure about that last bit.

Maybe you are right but it may help with picking up things happening downstream that affects us, e.g., https://github.com/napari/napari/issues/7129 ? Certainly, a test would have prevented a lot of debugging time in that issue! :sweat_smile:
