### ISSUE TITLE
[Points] When using `canvas_size_limits` highlight doesn't match the marker

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari/napari#6851]
### 🐛 Bug Report

Here's a vanilla viewer with size=10
I then use `canvas_size_limits = (100, 200)` and the point is visually larger, but the highlight is off:
<img width="1198" alt="image" src="https://github.com/napari/napari/assets/76622105/e68d6526-99d5-4940-9086-e5cecd86bb7f">

### 💡 Steps to Reproduce

Open napari and make an empty Points layer, click a point.
Open the console:
`viewer.layers[0].canvas_size_limits = (100, 200)`
Mouse over canvas.

### 💡 Expected Behavior

The highlight should match the Point.
Although maybe this is unrealistic with the OpenGL driver affecting size rendering?

### 🌎 Environment

napari: 0.5.0a2.dev649+g2d2cac676
Platform: macOS-13.3.1-arm64-arm-64bit
System: MacOS 13.3.1
Python: 3.12.2 | packaged by conda-forge | (main, Feb 16 2024, 20:54:21) [Clang 16.0.6 ]
Qt: 6.6.1
PyQt6: 
NumPy: 1.26.4
SciPy: 1.12.0
Dask: 2024.3.1
VisPy: 0.14.3.dev3
magicgui: 0.8.2
superqt: 0.6.2
in-n-out: 0.2.0
app-model: 0.2.5
npe2: 0.7.4

OpenGL:
- GL version: 2.1 Metal - 83.1
- MAX_TEXTURE_SIZE: 16384
- GL_MAX_3D_TEXTURE_SIZE: 2048

Screens:
- screen 1: resolution 1680x1050, scale 2.0

Optional:
- numba: 0.59.0
- triangle not installed

Settings path:
- /Users/piotrsobolewski/Library/Application Support/napari/napari-dev_a1eb8b76ba95fa16ad06e26097b46b8455dfbf0b/settings.yaml

**Comment by psobolewskiPhD** [comment]
CC: @brisvag

**Comment by brisvag** [comment]
Aaah, this! I misunderstood the issue when you mentioned it elsewhere. This shouldn't be hard to fix.

**Comment by psobolewskiPhD** [comment]
Eeep, this is a dupe of https://github.com/napari/napari/issues/6682 !
