### ISSUE TITLE
Transform mode of Labels layer pivots wrong when non-empty Shapes/Points present

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari/napari#6897]
### 🐛 Bug Report

If there is a non-empty Shapes or Points layer present and you use Transform mode on a Labels layer (activate using `7`), rotation pivots wrong: the bounding box desyncs the layer data.

https://github.com/napari/napari/assets/76622105/50193ca8-3fe3-4c89-8519-e2b1d7e69ae2

### 💡 Steps to Reproduce

1. Open napari
2. Make a Shapes or Points that is *not empty*
3. Make a labels layer and paint something
4. Activate Transform mode (`7`) and try to rotate the labels layer

### 💡 Expected Behavior

The transform box should match the layer data and remain functional.

### 🌎 Environment

napari: 0.5.0a2.dev649+g2d2cac676
Platform: macOS-13.3.1-arm64-arm-64bit
System: MacOS 13.3.1
Python: 3.12.2 | packaged by conda-forge | (main, Feb 16 2024, 20:54:21) [Clang 16.0.6 ]
Qt: 6.6.1
PyQt6: 
NumPy: 1.26.4
SciPy: 1.12.0
Dask: 2024.3.1
VisPy: 0.14.3.dev3
magicgui: 0.8.2
superqt: 0.6.2
in-n-out: 0.2.0
app-model: 0.2.5
npe2: 0.7.4

OpenGL:
- GL version: 2.1 Metal - 83.1
- MAX_TEXTURE_SIZE: 16384
- GL_MAX_3D_TEXTURE_SIZE: 2048

Screens:
- screen 1: resolution 1680x1050, scale 2.0

Optional:
- numba: 0.59.0
- triangle not installed

Settings path:
- /Users/piotrsobolewski/Library/Application Support/napari/napari-dev_a1eb8b76ba95fa16ad06e26097b46b8455dfbf0b/settings.yaml

**Comment by Czaki** [comment]
Ok. This is not a problem with the order of layer creation. It is a bug connected to translation. If you first create a shape or point layer, then labels layer will be created with negative translation. 

Minimum script is:

```python
import napari
import numpy as np


viewer = napari.Viewer()
labels = viewer.add_labels(np.ones((10, 10), dtype=np.uint8), translate=(10, 10))
labels.mode = "transform"

napari.run()
```

and try to manually rotate. 

I cannot trigger bug by code.

@brisvag it looks like we hit the same problem again...
@psobolewskiPhD could you update the description of issue to correctly point the problem?

**Comment by Czaki** [comment]
The problem is here:

https://github.com/napari/napari/blob/2102518cc89af553fb3143f8d5fca9eeed97dcd3/napari/_vispy/layers/base.py#L254

In general, for simple layer it should evaluate to `[0.5, 0.5]`, but does not. We need to describe it with equations and find a way to test it.

**Comment by dalthviz** [comment]
Maybe naive but seems like changing https://github.com/napari/napari/blob/2102518cc89af553fb3143f8d5fca9eeed97dcd3/napari/_vispy/layers/base.py#L246-L249 to be something like

```python
translate_child = (
    simplified_transform.translate[dims_displayed]
)[::-1] - offset[::-1]
```

Makes things work (at least when checking things from the GUI with the minimum reproducer script/code snippet):

![transform_box_ok_repro](https://github.com/napari/napari/assets/16781833/c6550bb6-a1df-439d-8f43-48f5bbc9471c)

Is there a reason to not use the simplified transform for the translate value in the same way that it's used to get the rotate and scale values?

**Comment by Czaki** [comment]
> Is there a reason to not use the simplified transform for the translate value in the same way that it's used to get the rotate and scale values?

I do not check it (Yes, I'm the author of this code too). Maybde it is enough, but I think that we should also find a way to test it and prepare excessive test coverage to validate all cases.

**Comment by brisvag** [comment]
This makes sense to me; agree that we need proper coverage here, but we don't even have proper agreements on the coordinate systems (https://github.com/napari/napari/issues/3783)...
