### ISSUE TITLE
Default to adding a newline for everything before the `extra_tooltip_text` when binding an action to a button

### ISSUE THREAD

**Issue by dalthviz** [Napari/napari#6907]
Follow up issue from the feedback at https://github.com/napari/napari/pull/6794#discussion_r1592792932

> Nice! Now wondering if we should default to adding a newline for everything before the `extra_tooltip_text`...

_Originally posted by @brisvag in https://github.com/napari/napari/pull/6794#discussion_r1595128310_

> That makes sense! From a quick check seems like the only other button that has some extra text is pan/zoom:
> 
> ![imagen](https://github.com/napari/napari/assets/16781833/be524560-9ccb-4565-896e-0e70e2e56e8c)
> 
> Maybe something like `Temporarily re-enable by holding Space` could be used as text in case the extra text is added always in a new line?
> 
> ![imagen](https://github.com/napari/napari/assets/16781833/0bf88973-1fef-4560-a55d-c1b4e4a7ef7f)
> 
> Also, should an issue be made to tackle that later or maybe is something worthy to be done here?

_Originally posted by @dalthviz in https://github.com/napari/napari/pull/6794#discussion_r1595648027_

> I mean I feel like the new line would be safe as a default...
> but I don't think I would change it in this PR--if at all. It's easy to add the new line, harder to remove it if someone does want a one-liner.

_Originally posted by @psobolewskiPhD in https://github.com/napari/napari/pull/6794#discussion_r1595982004_

**Comment by brisvag** [comment]
> It's easy to add the new line, harder to remove it if someone does want a one-liner.

I think if someone wants a oneliner, that means it should all live in the `tooltip_text` and not in the extra. It's also nice to have visual consistency between things.

**Comment by dalthviz** [comment]
Checking the detail on how the tooltip is defined

https://github.com/napari/napari/blob/26976b57af6a6dff5efc1c3c91bbd5fcee8a542c/napari/utils/action_manager.py#L231-L238

maybe for consistency, but also to give some flexibility, the tooltip could be changed to be a template with three elements instead of just two? So:

* Base text (which currently I think is related with the showing the button action name and action related shortcuts)
* Extension text for that base text, usually some short text (which is currently used to add to the pan/zoom button the text `(or hold Space)`)
* Extra info/description that could go in a new line and is a much longer text (which could be used for the transform button for the `Alt-Left mouse click to reset` text)

And then we could have for the tooltip a template in the following way:

```python
f'{base_text} {extra_tooltip_text}/n{new_line_extra_tooltip_text}'
```

However, I would say this approach will not help as much with visual consistency as just putting all the extra text in a new line :thinking:

**Comment by psobolewskiPhD** [comment]
I don't think there is a universal solution because it depends on the content of the tooltip.
A 2nd keybinding doesn't warrant a new line I don't think.
But the info about reseting transforms does?
So I think I would leave the status quo, where authors of tooltips add the `\n` as needed.

**Comment by dalthviz** [comment]
Awesome, thank you both for you input here! I'm closing this then :+1:
