### ISSUE TITLE
CI Ubuntu latest py 3.9, pyqt5, pyside 6 hash mismatch

### ISSUE THREAD

**Issue by lucyleeow** [napari/napari#6908]
### 🐛 Bug Report

Hash mis match when installing in 'Ubuntu latest py 3.9, pyqt5, pyside 6' CI. Seen in #6905

```
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    unknown package:
        Expected sha256 14f4171b15dbdd7d120dc125c84f2eca53bc197182295bfdfdb3bb95b58a46c7
```

### 💡 Steps to Reproduce

https://github.com/napari/napari/actions/runs/9012230873/job/24762142131?pr=6905#step:13:216

### 🌎 Environment

CI

**Comment by psobolewskiPhD** [comment]
I reran CI. Looks clear now.

**Comment by psobolewskiPhD** [comment]
https://github.com/napari/napari/actions/runs/9012230873

**Comment by Czaki** [comment]
It is a download error. It means that downloaded file has different hash than expect. It is protection for Man In the Middle (MIM) attack, but accidentally may be triggered by a bug in the download.  
It happens in the past. 
Proper solution is restart CI as @psobolewskiPhD done.

**Comment by lucyleeow** [comment]
Ah good to know in future, I guess unknown package means download did not complete?

**Comment by Czaki** [comment]
I think yes
