### ISSUE TITLE
Napari crashes with lazy segmentation

### ISSUE THREAD

**Issue by gboscagli** [napari/napari#6916]
Greetings all,
I’m fairly new to the field of computer vision for biological analyses.

I’m working with a 36000x36000 H&E image, in .ome.tiff format: actually, it’s the first slide of a .svs file extracted using `QuPath`. I’m trying to perform a watershed segmentation on `Squidpy`, a spatial omics framework that comes with a `Napari `plugin embedded. The image is lazily loaded into an ImageContainer object (an `xarray `dataset, under the hood) and then lazily segmented.

However, when I try to launch Napari plugin to see how the segmentation went, it crashes when I just select the segmentation layer. I tried to perform an eager segmentation on the same 36000x36000 image but, as expected, I get a `MemoryError `since I’m working locally. From [Napari Github 1](https://github.com/napari/napari/issues/318#issuecomment-499319603), I saw that the size limit for a single slide is 16000x16000, but the topic is 5 years old and I don’t know if it’s been incremented or not.

Is there a way to get around this problem without downsizing the image? Feel free to ask for some more details, if needed.

**Comment by Czaki** [comment]
In general, current workflow is:

1. Read texture limit from GPU
2. If the image is bigger than the texture limits, downsample image to fit in GPU limit
3. Send data to GPU. 

There is multiple place where something may crash. It may be bug in napari, it may be some limitation of you machine. 

So, please attach information about napari `napar --info` output or `Help > napari info` from the menu bar. Also, please attach information printed during the crash (Stacktrace etc).

**Comment by Czaki** [comment]
Based on your screenshot you are using napari in version 0.4.15, the latest version is 0.4.19post1. In the meantime, we drastically improved Labels layer. I know that in pre 0.4.19 there were problems with adding big labels layer. 

Best will be if you could save your labels as (u)int8 or 16. Then we will not allocate additional memory for rendering.

**Comment by gboscagli** [comment]
> Based on your screenshot you are using napari in version 0.4.15, the latest version is 0.4.19post1. In the meantime, we drastically improved Labels layer. I know that in pre 0.4.19 there were problems with adding big labels layer.

I uploaded Napari to the latest version, unfortunately the issue remains.

> Best will be if you could save your labels as (u)int8 or 16. Then we will not allocate additional memory for rendering.

Segmentation is performed by a Squidpy function and returns (u)int32, don't know if there is some way to convert it.

**Comment by Czaki** [comment]
Could you calculate `np.max(data)` over label data?

**Comment by gboscagli** [comment]
Is it what you asked for?
![image](https://github.com/napari/napari/assets/133790786/748c1a4b-ab62-4976-b827-3ee32e94b1dc)

**Comment by Czaki** [comment]
No. I try to guess if it could be converted to a smaller dtype. 
I will try to do problem reproduction with artificial data. Could you provide information about your GPU model and how many RAM you have?

**Comment by gboscagli** [comment]
I have 16GB of RAM and a NVIDIA GeForce GTX 950M GPU.
Thank you so much for the interest and for the patience, by the way.

**Comment by psobolewskiPhD** [comment]
@gboscagli 
It look like you have an array for the segmented data. Are you able to open that in napari without using the plugin? Maybe it's the plugin that is at fault?

If it's too big you can try something like:
`viewer.add_labels([labels_data, labels_data[::2,::2], labels_data[::4, ::4]])`

where `labels_data` is the segmentation data array.
Note this will make the data multiscale and will prevent painting into the labels.

**Comment by psobolewskiPhD** [comment]
Based on the related image.sc thread https://forum.image.sc/t/napari-crashes-with-lazy-segmentation/96429
I'm going to close this as resolved, as a plugin issue.
If you're still having issues, please let us.
