### ISSUE TITLE
Shapes layer: `3` keybinding to delete shape is not great and cannot be changed

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari/napari#6919]
_Originally posted by @seankmartin in https://github.com/napari/napari/issues/1382#issuecomment-2108017820_
            
Related to accidentally deleting shapes, is it possible that the keybinds for the shape layer could be changed?

For example, if I'm trying to quickly move around vertices for shapes, the default bindings are:
1. Remove a vertex
2. Insert a vertex
3. **Delete my current shape**
4. Select vertices

So if I accidentally press 3 during editing, it deletes my shape, and it's pretty easy to press by accident.

I also can't seem to remove the keybind to 3 deleting a shape easily in the preferences, because delete and backspace are also bound to delete the current shape, and take precedence over key 3 in the napari shortcuts menu

![image](https://github.com/napari/napari/assets/21295664/f8d54068-15a8-4a69-a934-5738b7cd1efc)

For what it is worth, I do have a workaround, so it is more of a general question:

```Python
layer = viewer.add_shapes(shapes, name=name, shape_type="polygon")

# Remove key 3 from deleting a shape
@layer.bind_key("3")
def _noop(event):
      pass
```

_Originally posted by @seankmartin in https://github.com/napari/napari/issues/1382#issuecomment-2108017820_

**Comment by psobolewskiPhD** [comment]
So there are 2 questions here: 
- the location of delete shape button -- which is why the keybind is 3
There is a PR to address this: https://github.com/napari/napari/pull/5021
I actually think we should try to get that in in 0.5.0 (along with addressing https://github.com/napari/napari/issues/6489)

- the inability to un-bind `3`. Looks like https://github.com/napari/napari/commit/4489e43c4d5162ddf3d3aa2eb73dc0cf9cfd6a79#diff-0af7555041504c4085acb506d63ac471693625427e902bdbb0149ea661f2bb79
added `3` as a **3rd keybinding** for shapes, but we only allow 2 to be edited, so the user cannot access that.
Looks like an attempt to work around delete/backspace -- maybe a mac/windows thing?

**Comment by psobolewskiPhD** [comment]
Also @seankmartin I'm suprised by your work around, because of: 
https://github.com/napari/napari/issues/6440
which is just:
https://github.com/napari/napari/issues/2799

Those made it seem like bind_key cannot overwrite a napari keybind (like `3`)
I'll have to retest those!

**Comment by Czaki** [comment]
> * the inability to un-bind `3`. Looks like [4489e43#diff-0af7555041504c4085acb506d63ac471693625427e902bdbb0149ea661f2bb79](https://github.com/napari/napari/commit/4489e43c4d5162ddf3d3aa2eb73dc0cf9cfd6a79#diff-0af7555041504c4085acb506d63ac471693625427e902bdbb0149ea661f2bb79)
>       added `3` as a **3rd keybinding** for shapes, but we only allow 2 to be edited, so the user cannot access that.

It is possible to workaround this, by first unbinding second shortcut, then 3 appears as an available shortcut and one could unbind.

**Comment by seankmartin** [comment]
> Also @seankmartin I'm suprised by your work around, because of: #6440 which is just: #2799
> 
> Those made it seem like bind_key cannot overwrite a napari keybind (like `3`) I'll have to retest those!

From what I can see @psobolewskiPhD, I seem to be able to overwrite layer specific keybinds, but not global ones

```Python
from napari import Viewer, run
import numpy as np

viewer = Viewer()

# Key two keeps functioning because this would be a global bind
@viewer.bind_key("2")
def _noop(event):
    pass

points = np.array([[100, 100], [200, 200], [300, 100]])
layer = viewer.add_points(points, name="2 works")

# Key two stops functioning on this specific layer
layer = viewer.add_points(points, name="2 does nothing")
@layer.bind_key("2")
def _noop(event):
    pass

run()
```

**Comment by seankmartin** [comment]
> > * the inability to un-bind `3`. Looks like [4489e43#diff-0af7555041504c4085acb506d63ac471693625427e902bdbb0149ea661f2bb79](https://github.com/napari/napari/commit/4489e43c4d5162ddf3d3aa2eb73dc0cf9cfd6a79#diff-0af7555041504c4085acb506d63ac471693625427e902bdbb0149ea661f2bb79)
> >   added `3` as a **3rd keybinding** for shapes, but we only allow 2 to be edited, so the user cannot access that.
> 
> It is possible to workaround this, by first unbinding second shortcut, then 3 appears as an available shortcut and one could unbind.

Aha, I didn't think of that, thanks @Czaki !

**Comment by psobolewskiPhD** [comment]
> From what I can see @psobolewskiPhD, I seem to be able to overwrite layer specific keybinds, but not global ones

Interesting! I never tested that. What I don't get is that `viewer.bind_key` is technically not global? Should be for that viewer instance named `viewer`
In contrast to something like `Points.bind_key` which is any points layer.
What's more interesting is that with `Points.bind_key` in your example I get the warning about needing to overwrite:
`ValueError: keybinding 2 already used! specify 'overwrite=True' to bypass this check`

**Comment by psobolewskiPhD** [comment]
@seankmartin I think a solution to the specific keybind issue here is to have `3` be the primary or secondary keybinding, and push either backspace or delete to the 3rd position. 
Then you could rebind/unbind it in the GUI.
I sort of think backspace is a really intuitive binding for this, so if that was 3rd it would be a de facto unchangeable default behavior? and then `3` and `delete` would be the two bindings that could be easily changed?

**Comment by seankmartin** [comment]
> I think a solution to the specific keybind issue here is to have `3` be the primary or secondary keybinding, and push either backspace or delete to the 3rd position.
> Then you could rebind/unbind it in the GUI.
> I sort of think backspace is a really intuitive binding for this, so if that was 3rd it would be a de facto unchangeable default behavior? and then `3` and `delete` would be the two bindings that could be easily changed?

@psobolewskiPhD - I think this is a great suggestion! I also find backspace the most intuitive and think it could be the de facto at 3rd position
