### ISSUE TITLE
`File -> Open Folder...` doesn't allow me to select a folder (Mac-OS)

### ISSUE THREAD

**Issue by DragaDoncila** [napari/napari#6934]
### 🐛 Bug Report

On `main`, if I try to open a folder using the `File` menu option, `File -> Open Folder...`, the built-in Mac-OS dialog doesn't let me select a folder i.e. when I click `Open` in the bottom right-hand corner with a folder selected, it just shows me the contents of the folder (as though I'd double-clicked it) rather than selecting it and reading it. This doesn't happen on `0.4.19.post1`. Drag 'n' drop still works fine on main.

### 💡 Steps to Reproduce

1. Check out 0.4.19.post1
2. Open a folder using `File -> Open Folder...`. 
3. The folder opens normally.
4. Check out main
5. Open a folder using `File -> Open Folder...`.
6. You can't.

### 💡 Expected Behavior

I expected the folder to open as usual.

### 🌎 Environment

```
napari: 0.5.0a2.dev712+ge29593cf
Platform: macOS-10.16-x86_64-i386-64bit
System: MacOS 14.5
Python: 3.10.14 (main, Mar 21 2024, 11:24:58) [Clang 14.0.6 ]
Qt: 5.15.11
PyQt5: 5.15.10
NumPy: 1.26.4
SciPy: 1.13.0
Dask: 2024.4.0
VisPy: 0.14.2
magicgui: 0.8.2
superqt: 0.6.3
in-n-out: 0.2.0
app-model: 0.2.6
npe2: 0.7.5

OpenGL:
- GL version: 2.1 INTEL-22.5.11
- MAX_TEXTURE_SIZE: 16384
- GL_MAX_3D_TEXTURE_SIZE: 2048

Screens:
- screen 1: resolution 1440x900, scale 2.0

Optional:
- numba: 0.59.1
- triangle: 20230923

Settings path:
- /Users/ddoncilapop/Library/Application Support/napari/napari-dev_4bf01cd15eaead7335b2c3834bd2061f518e1da7/settings.yaml
```

**Comment by DragaDoncila** [comment]
Fix incoming.

**Comment by psobolewskiPhD** [comment]
I sort of think the main behavior is "correct"? To open a folder, should use `open folder`?

**Comment by DragaDoncila** [comment]
@psobolewskiPhD I used the `File -> Open Folder` option in the menu bar, so it should allow me to select a folder

**Comment by psobolewskiPhD** [comment]
Yeah sorry i followed the repodrucer where it just says `open` and used `file open`

**Comment by DragaDoncila** [comment]
> Yeah sorry i followed the repodrucer where it just says open and used file open

Ooops, edited. Anyway, PR incoming
