### ISSUE TITLE
Move layer actions under Qt

### ISSUE THREAD

**Issue by lucyleeow** [napari/napari#6946]
All providers are 'Qt' providers - this includes the layer providers as they use `_provider_viewer` which uses Qt (they were moved in #6743).

This means that all layer actions which require layer, could technically be considered 'Qt/GUI' as they require a Qt provider.

Note that this is part of a larger discussion about whether 'headless' providers makes sense, e.g., when providing a viewer in GUI setting we provide the active viewer, but in headless we have no way of knowing which viewer is active - this also affects layers as we don't know which viewer's layers is wanted  (see #6917).

I propose we move all layer actions under Qt.

This was noticed after #6864.
cc @DragaDoncila @Czaki

**Comment by lucyleeow** [comment]
Noticed this issue after looking at: #7030

The layer actions (in [`_layer_actions.py`](https://github.com/napari/napari/blob/main/napari/layers/_layer_actions.py) - these appear to be private functions.

Are any of these actions potentially useful for users to use headless? Taking a quick look `_duplicate_layer`, `_project` may be, but e.g., for `_merge_stack`, they could just directly use the `stack_utils.merge_rgb` function.

If we are not interested in making these non-private, I think all these actions would fall under the 'defined only for purpose of living in menu' category. This combined with the layerlist provider being a qt provider would make me favour moving them.

WDYT @DragaDoncila @Czaki  ?

**Comment by Czaki** [comment]
We still have in plans alternatives napari frontends, like web frontend. Then layer actions still will be working, but a different provider will be required. 
Current qt actions will not be working. So I do not agree with considering layers actions as qt one.

**Comment by lucyleeow** [comment]
Ah again the same problem. We do not have a place that for items that are *GUI* specific but not QT specific (i.e. GUI_stuff / QT_stuff).

If we really want to support different frontends (which we have been saying for a while) we need to address this problem, as there are many things that are GUI but not Qt, that we have just put in Qt as we have no other place to put it.

I see no reason to be strict in *this* particular case when there are many GUI but not Qt items that live in Qt folder. However, moving this is not a huge issue so I am also okay with not moving.

**Comment by Czaki** [comment]
> If we really want to support different frontends (which we have been saying for a while) we need to address this problem, as there are many things that are GUI but not Qt, that we have just put in Qt as we have no other place to put it.

yes, but the code inside action is Qt specific. Another frontend will need alternative implementation. Current split based on "if action directly interact with qt object" is good.

**Comment by lucyleeow** [comment]
Hm true, this is a provider specific issue. Okay I'll close
