### ISSUE TITLE
Scale bar colored attribute causes scale bar to disappear after deselection

### ISSUE THREAD

**Issue by dalthviz** [napari/napari#6959]
### 🐛 Bug Report

After making the scale bar visible and colored, if you toggle again the colored attribute seems like the scale bar becomes invisible.

### 💡 Steps to Reproduce

1. Open an image
2. Make the scale bar visible (`View > Scale Bar > Scale Bar Visible`)
3. Make the scale bar colored (`View > Scale Bar > Scale Bar Colored`)
4. Disable the scale bar color (`View > Scale Bar > Scale Bar Colored` again)
5. Scale bar is not visible even when the `Scale Bar Visible` action is still toggled

![scale_bar_colored](https://github.com/napari/napari/assets/16781833/d4a1ca92-b819-4115-a34e-f1ff1330727c)

### 💡 Expected Behavior

To the scale bar to remain visible but without color or colored depending on the action toggled state

### 🌎 Environment

napari: 0.5.0a2.dev723+g1f4e8e73
Platform: Windows-10-10.0.19045-SP0
Python: 3.10.9 | packaged by conda-forge | (main, Jan 11 2023, 15:15:40) [MSC v.1916 64 bit (AMD64)]
Qt: 5.15.2
PyQt5: 5.15.10
NumPy: 1.25.2
SciPy: 1.9.3
Dask: 2023.10.1
VisPy: 0.14.1
magicgui: 0.7.3
superqt: 0.6.7.dev0+g0ec5cd3.d20240527
in-n-out: 0.2.0
app-model: 0.2.7
npe2: 0.7.5

OpenGL:
  - GL version:  4.5.0 - Build 25.20.100.6444
  - MAX_TEXTURE_SIZE: 16384
  - GL_MAX_3D_TEXTURE_SIZE: 2048

Screens:
  - screen 1: resolution 1366x768, scale 1.0
  - screen 2: resolution 1920x1080, scale 1.0

Optional:
  - numba: 0.58.1
  - triangle not installed

Settings path:
  - C:\Users\dalth\AppData\Local\napari\napari-dev_4454fdbf170edefe23827a4bf512389a6806af69\settings.yaml
Plugins:
  - napari: 0.5.0a2.dev723+g1f4e8e73 (81 contributions)
  - napari-assistant: 0.4.4 (4 contributions)
  - napari-console: 0.1.dev42+ge2a8d71.d20240315 (0 contributions)
  - napari-generic-SIMulator: 0.0.19 (2 contributions)
  - napari-ome-zarr: 0.5.2 (2 contributions)
  - napari-pyclesperanto-assistant: 0.22.1 (51 contributions)
  - napari-skimage-regionprops: 0.10.0 (2 contributions)
  - napari-svg: 0.1.10 (2 contributions)
  - napari-time-slicer: 0.4.9 (2 contributions)
  - napari-tools-menu: 0.1.19 (0 contributions)
  - napari-ui-tracer: 0.2.0.dev0 (2 contributions)

**Comment by psobolewskiPhD** [comment]
Thanks for opening the issue!
I think @jni  recently noticed the same was happening with `ticks`!

**Comment by psobolewskiPhD** [comment]
See also: https://github.com/napari/napari/issues/6961

**Comment by dalthviz** [comment]
Gave this a check and seems like using the scale bar overlay canvas parent node background color instead of the parent node background color itself fixes this. So at:

https://github.com/napari/napari/blob/5e8dc098cb213c5f963524e619f223ad4fe90be8/napari/_vispy/overlays/scale_bar.py#L145-L146

Changing things to look something like:

```python
if (
    self.node.parent is not None
    and self.node.parent.canvas.bgcolor
):
    background_color = self.node.parent.canvas.bgcolor.rgba
```

A preview of the behavior with the change:

![scale_bar_attrs](https://github.com/napari/napari/assets/16781833/b1568853-3157-4f3d-89c7-9fbcfa4a5749)

Here a branch with the change in case you want to check: https://github.com/dalthviz/napari/commit/d4d59552ce0fe118e1d6b4c93b0029044402b0d6

Let me know if that makes sense to open a PR!

**Comment by psobolewskiPhD** [comment]
This looks correct to me? I'd say if you have a chance, open a PR with that, then we can see if tests pass and consult the overlay guru Lorenzo.
