### ISSUE TITLE
We should allow dict and list input to Labels.colormap

### ISSUE THREAD

**Issue by jni** [napari/napari#6967]
## References

ome/napari-ome-zarr#109

## 🚀 Feature

When designing the new labels colormaps API (#6542), we inadvertently forgot about an early design goal of napari: inputs should never be *required* to be exotic objects. *Optional* exotic objects is ok! For example, it should be ok to extract metadata automatically from an xarray. *But* users should not be *required* to provide xarray objects instead of numpy arrays.

In #6542, the new Labels colormaps API requires colormaps to be wrapped in either a CyclicLabelColormap object or a DirectLabelColormap object. This is a problem because now plugins *must* depend on and import from napari in order to provide colormap information. Which I think is pretty terrible!

I propose that if users pass in `add_labels(data, colormap={1: 'red', 2: 'blue'})`, we should automatically construct a DirectLabelColormap for them, and if they do `add_labels(data, colormap=['red', 'blue'])`, we should construct a CyclicLabelColormap for them.

This is also a nice API improvement even when just working with napari directly.

**Comment by psobolewskiPhD** [comment]
I agree, I think this should get in before 0.5.0 so we don't break plugins that might return labels layers.
