### ISSUE TITLE
Add tests for scalebar visibility

### ISSUE THREAD

**Issue by jni** [napari/napari#6990]
## 🧰 Task

I tracked the bugs in #6959 and #6961 to #5432. It seems this part of the code is untested even though it was covered. So it would be good to add tests for it so our scale bars don't disappear again. 😅

**Comment by Czaki** [comment]
Best one will require to do screenshots. Some workaround may be to query computed color.

**Comment by jni** [comment]
I think that's a fine spot for it @dalthviz, thanks!

I'm curious about the "no ticks" test. 😂 I guess you could count the number of white pixels and check that they are reduced (but not zero) relative to the scale bar with ticks?

**Comment by Czaki** [comment]
> I'm curious about the "no ticks" test. 😂 I guess you could count the number of white pixels and check that they are reduced (but not zero) relative to the scale bar with ticks?

Calculate the bounding box of non-dark pixels and check if proportions are correct?

**Comment by jni** [comment]
If you have the bounding box you can check that there are *no* dark pixels when there's no ticks.

**Comment by dalthviz** [comment]
I ended up creating a test that just compares between screenshots to validate if there is a difference when changing the `viewer.scale_bar.ticks` attribute at #7006. If that is not sufficient I will give it a check to a possible validation involving the bounding box of the scale bar as mentioned here (checking proportions or dark pixels presence). Let me know!
