### ISSUE TITLE
channel_axis argument fails with dask.array

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#700]
## 🐛 Bug
Just wanted to post this here so I don't forget.
Dask arrays do not have a `take` method, so if you try to call `add/view_image` on a dask array with the `channel_axis` argument, you get: `AttributeError: 'Array' object has no attribute 'take'` at line 552 below:

https://github.com/napari/napari/blob/15deef08f1aea5e6a6951f7a83d4713f16070ed4/napari/components/viewer_model.py#L545-L552

```python
import napari
import numpy as np
import dask.array as da 

napari.view_image(np.random.random((2,10,10,10)), channel_axis=0)  # works
napari.view_image(da.random.random((2,10,10,10)), channel_axis=0)  # Attribute Error
```
Can't immediately think of an elegant fix, other than checking if `isinstance(data, da.Array)` and then calling `da.take`

**Comment by sofroniewn** [comment]
That's no good! I thought I had tried this with a dask array, but evidently not. Here is the dock string for [`da.take`](https://docs.dask.org/en/latest/array-api.html#dask.array.take). It looks like this can actually just be replaced by `np.take` and that will still return as dask array. i will make a short PR
