### ISSUE TITLE
[bug] render plane oblique: normal is incorrect if scale isn't 1s

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari/napari#7008]
### 🐛 Bug Report

If you have a 3D layer with scale not (1, 1, 1), then when using the `o`/`oblique` button, the plane normal isn't correctly set.
I think this is because camera.view_direction is in world coordinates:
https://github.com/napari/napari/blob/0e01840c9237489acf238aec1d5cdaf9201ed640/napari/components/camera.py#L58-L63
and `plane.normal` is in data coordinates, but the transformation used for the oblique feature uses `_world_to_displayed_data_ray` rather than transforming the normal:
https://github.com/napari/napari/blob/0e01840c9237489acf238aec1d5cdaf9201ed640/napari/layers/image/_image_key_bindings.py#L45-L58

See the implementation here in napari-threedee:
https://github.com/napari-threedee/napari-threedee/blob/6674afe70938724cbaffc0677d2dfd804993bdba/src/napari_threedee/utils/napari_utils.py#L222
And a helpful explanation:
https://www.scratchapixel.com/lessons/mathematics-physics-for-computer-graphics/geometry/transforming-normals.html

### 💡 Steps to Reproduce

```
import napari
from napari.layers.image._image_key_bindings import orient_plane_normal_along_view_direction_no_gen
from skimage import data
import numpy as np

cells = data.cells3d()

viewer, layer = napari.imshow(cells[:,1,...])
layer.scale = (4, 1, 1)
viewer.dims.ndisplay = 3
layer.depiction = 'plane'
layer.plane.position = (25, 170, 50)
layer.bounding_box.visible = True

viewer.camera.set_view_direction((0.98, 0, .21))
orient_plane_normal_along_view_direction_no_gen(layer)

viewer.update_console(locals())

napari.run()
```

![image](https://github.com/napari/napari/assets/76622105/55ebadb1-0973-49f4-90c2-7d06b9b2ab25)

### 💡 Expected Behavior

The proper plane orientation:
```
import napari
from napari.layers.image._image_key_bindings import orient_plane_normal_along_view_direction_no_gen
from skimage import data
import numpy as np

cells = data.cells3d()

viewer, layer = napari.imshow(cells[:,1,...])
layer.scale = (4, 1, 1)
viewer.dims.ndisplay = 3
layer.depiction = 'plane'
layer.plane.position = (25, 170, 50)
layer.bounding_box.visible = True

viewer.camera.set_view_direction((0.98, 0, .21))

# from napari-threedee
def world_to_data_normal(vector, layer):
    """Convert a normal vector defining an orientation from world coordinates to data coordinates.
    For example, this would be used to a plane normal.

    https://www.scratchapixel.com/lessons/mathematics-physics-for-computer-graphics/geometry/transforming-normals.html

    Parameters
    ----------
    vector : tuple, list, 1D array
        A vector in world coordinates.
    layer : napari.layers.BaseLayer
        The napari layer to get the transform from.

    Returns
    -------
    np.ndarray
        Transformed vector in data coordinates. This returns a unit vector.
    """
    unit_vector = np.asarray(vector) / np.linalg.norm(vector)

    # get the transform
    # the napari transform is from layer -> world.
    # We want the inverse of the world ->  layer, so we just take the napari transform
    inverse_transform = layer._transforms[1:].simplified.linear_matrix
    transpose_inverse_transform = inverse_transform.T

    # transform the vector
    transformed_vector = np.matmul(transpose_inverse_transform, unit_vector)

    return transformed_vector / np.linalg.norm(transformed_vector)

layer.plane.normal = world_to_data_normal(viewer.camera.view_direction, layer)

napari.run()
```

![image](https://github.com/napari/napari/assets/76622105/94f3e775-38a9-463d-b682-1f62e253f0eb)

### 🌎 Environment

napari: 0.5.0a2.dev694+g7b46a844
Platform: macOS-14.5-arm64-arm-64bit
System: MacOS 14.5
Python: 3.11.7 | packaged by conda-forge | (main, Dec 23 2023, 14:38:07) [Clang 16.0.6 ]
Qt: 6.6.0
PyQt6: 
NumPy: 1.26.4
SciPy: 1.12.0
Dask: 2024.1.1
VisPy: 0.14.3.dev15
magicgui: 0.8.1
superqt: 0.6.1
in-n-out: 0.1.9
app-model: 0.2.4
npe2: 0.7.4

OpenGL:
- GL version: 2.1 Metal - 88.1
- MAX_TEXTURE_SIZE: 16384
- GL_MAX_3D_TEXTURE_SIZE: 2048

Screens:
- screen 1: resolution 2056x1329, scale 2.0
- screen 2: resolution 3008x1692, scale 2.0

Optional:
- numba: 0.59.0
- triangle not installed

Settings path:
- /Users/sobolp/Library/Application Support/napari/napari-dev_36963bf0846bfe99dcf4f566a2cc780b6a723afa/settings.yaml

**Comment by psobolewskiPhD** [comment]
CC: @alisterburt @kevinyamauchi

**Comment by psobolewskiPhD** [comment]
Not sure if the fix belongs as a method on the layer as `_world_to_displayed_data_ray` et al. or as a function in:
https://github.com/napari/napari/blob/main/napari/utils/geometry.py
Any one have any thoughts?

**Comment by alisterburt** [comment]
@psobolewskiPhD looks like you've correctly diagnosed the issue, nice spelunking!

World to displayed data ray feels reasonable! If it gets bulky stick it in a util and call from there?
