### ISSUE TITLE
Change default value to False for "remember my preference" when selecting reader plugin?

### ISSUE THREAD

**Issue by jni** [napari/napari#7010]
## 🚀 Feature

Whenever I open e.g. a zarr file, I have to untick "remember this preference" every time, because zarr files are quite diverse and so are readers for them. I think this is true of other formats e.g. tiff or czi. In general, the plugin landscape evolves so much that it would be weird to commit to a particular plugin forever. 😂 

More importantly, it's not super easy to recover from accidentally leaving that ticked, whereas it is trivial to recover from forgetting to tick it — just tick it the next time you open that file type.

Therefore, I suggest that we make the default state *not* to remember.

Thoughts @DragaDoncila @psobolewskiPhD @Czaki?

**Comment by Czaki** [comment]
Maybe we should also add a third option, "No and do not ask again"?

**Comment by jni** [comment]
I've thought about that, but it complicates the dialog and complicates the settings. But, sure, I wouldn't necessarily be opposed to having a three-way select widget, "Remember this choice? Yes | No | Never".

... But what should the default be? 😜

**Comment by Czaki** [comment]
No should be default.

**Comment by psobolewskiPhD** [comment]
I don't understand what `never` would do? what if there are multiple options or I install a new plugin?
Would you just magic in a "use latest" or "use napari builtins"?.
I do agree that the default should be the box unchecked (so don't remember the choice).

**Comment by Czaki** [comment]
> I don't understand what `never` would do? what if there are multiple options or I install a new plugin?
> Would you just magic in a "use latest" or "use napari builtins"?.

That every time you open a file with this extension, the popup to select plugin will appear. But without asking to save selected plugin.

**Comment by psobolewskiPhD** [comment]
So that's just `False`, box unchecked, right?

**Comment by DragaDoncila** [comment]
Yeah I like this, leave unticked makes it a more explicit opt in to have the plugin associated

**Comment by jni** [comment]
Ok so the decision is, if the user unticks it, we remember that they unticked it? From an implementation perspective, this is much harder than just having the default be unticked

**Comment by psobolewskiPhD** [comment]
I trust the user to tick the box when they want to save the behavior. Unless you want to save dialogue state per file type...
