### ISSUE TITLE
Inconsistent behaviour when adding points (some options affect all points in layer, some don't)

### ISSUE THREAD

**Issue by VolkerH** [napari/napari#702]
## 🐛 Bug

Not sure whether the following is a bug. Maybe it is just behaviour as envisaged, then it is inconsistenst interaction.

When adding markers in a points layer, changing the symbol (e.g. from "disk" to "diamond") affects all points in the current points layer (including exisiting ones). 
When changing the marker color or size, existing markers stay the same subsequently added markers are affected.

So it is possible to create multiple markers with different colors and sizes in a single point layer, but it is not possible to create markers with different symbols. 
![image](https://user-images.githubusercontent.com/2210044/69011663-30c86900-09c1-11ea-8530-1ba86555f527.png)

## To Reproduce

1. Add a points layer
1. add a marker as "disk"
2. change marker type to "diamond"
3. add another marker

## Expected behavior

I would expect that marker symbols in a point layer behave like marker color and size, i.e.
that I can create markers with different symbols in a single point layer.

## Environment

napari, 0.2.5+12.g15deef0
Qt, 5.13.2
NumPy, 1.17.3
SciPy, 1.3.1
VisPy, 0.6.2
scikit-image, 0.16.2

Platform: Windows-10-10.0.18362-SP0
Python:   3.7.5 (default, Oct 31 2019, 15:18:51) [MSC v.1916 64 bit (AMD64)]
Backend:  PySide2
GL version:  '4.5.0 - Build 25.20.100.6472'
MAX_TEXTURE_SIZE: 16384

 - Any other relevant information:

**Comment by sofroniewn** [comment]
Ah yes - so this is a known issue that should at least be documented if not exposed better in the UI. Right now `symbol` and `opacity` in the points layer are global properties, while we could make opacity apply for each point (potentially at the cost of increasing latency), making symbol apply to each point would require some changes at the vispy level, and I'm not sure what performance hits we might take. In the mean time we should at least document this better as I have no doubt that it is confusing to people

**Comment by VolkerH** [comment]
Opacity (and blending mode) I didn't test as  intuitively I would always think of  opacity as a layer property, which would be consistent with the other layer types (same for blending mode BTW). 

Now that you mention it, this could of course also be a per-point property. However, in that case you would lose the ability to dial back the opacity for the whole layer.

My suggestion is to decide which properties affect a layer and which properties affect a point and separate this out in the GUI. Maybe a vertical alignment.

```
point properties
------ <hline> ------
layer properties
````

**Comment by sofroniewn** [comment]
@VolkerH that separation might be nice.

Right now we actually support opacity at the individual shape level for the `Shapes` layer, but maybe we want to drop that support and make it at the layer level for consistency as it is doubly strange that there is a difference between `Points` and `Shapes` there

**Comment by jni** [comment]
@VolkerH side note, a user on image.sc found a fix on Windows for the incorrect text size on the UI:
https://forum.image.sc/t/napari-issues-it-works-but-no-gpu-and-the-gui-is-all-squashed/31411/13

**Comment by liaprins-czi** [comment]
Related: [Layer controls relationships #19](https://github.com/napari/product-heuristics-2020/issues/19)

**Comment by psobolewskiPhD** [comment]
I believe that with https://github.com/napari/napari/pull/7137
this issue will be resolved. All point properties will be consistent: the UI elements in the layer controls do what their tooltips say: affect selected points and future points.

**Comment by jni** [comment]
Nice! I love closing 3-digit issues. 😃 I think [this comment](https://github.com/napari/napari/issues/702#issuecomment-555098444) is still a bit unresolved but is being dealt with in other design issues (e.g. #5358). Agreed?

**Comment by VolkerH** [comment]
I can't believe this is almost 5 years old. Thanks @psobolewskiPhD

**Comment by psobolewskiPhD** [comment]
Ah, good point @jni and I agree.
I think opacity and blending are layer controls that are inherently linked and affect the whole layer. Having them be next to each other makes a lot of sense.
Having Point size of Edge with "interrupt" them is odd.

I'd make the same argument for Image layer.
Would be a big change from the current.
<img width="273" alt="image" src="https://github.com/user-attachments/assets/88d4ffab-a6c5-4cc9-a712-e5ceab0d5b28">

Also why are tooltips so inconsistent? I have no idea what interpolation does for example.

**Comment by psobolewskiPhD** [comment]
Here's the new layout of the Points controls:
<img width="267" alt="image" src="https://github.com/user-attachments/assets/70360bed-3c8c-4713-b105-6600ee220188">

And all of the point-properties tooltips now say that they affect selected and any added afterwards.

So I'm going to close this. If any other Points UI issues remain that I've missed or pop up, I think it's best to make a new issue for clarity.
