### ISSUE TITLE
[main, [dev] install] WARNING: pydantic 2.7.4 does not provide the extra 'dotenv'

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari/napari#7029]
### 🐛 Bug Report

Made a fresh python 3.12 conda env.
Fresh main, pulled from upstream.
pip install -e .[dev]
Getting `WARNING: pydantic 2.7.4 does not provide the extra 'dotenv'` from pip.

### 💡 Steps to Reproduce

Made a fresh python 3.12 conda env.
Fresh main, pulled from upstream.
pip install -e .[dev]

### 💡 Expected Behavior

No warning.

### 🌎 Environment

napari: 0.5.0a2.dev760+g74ecc56c6
Platform: macOS-13.3.1-arm64-arm-64bit
System: MacOS 13.3.1
Python: 3.12.4 | packaged by conda-forge | (main, Jun 17 2024, 10:13:44) [Clang 16.0.6 ]
Qt: 6.7.1
PyQt6: 
NumPy: 2.0.0
SciPy: 1.14.0
Dask: 2024.6.2
VisPy: 0.14.3
magicgui: 0.8.3
superqt: 0.6.7
in-n-out: 0.2.1
app-model: 0.2.7
npe2: 0.7.6

OpenGL:
  - GL version:  2.1 Metal - 83.1
  - MAX_TEXTURE_SIZE: 16384
  - GL_MAX_3D_TEXTURE_SIZE: 2048

Screens:
  - screen 1: resolution 1680x1050, scale 2.0

Optional:
  - numba: 0.60.0
  - triangle not installed

Settings path:
  - /Users/piotrsobolewski/Library/Application Support/napari/napari-dev_a1eb8b76ba95fa16ad06e26097b46b8455dfbf0b/settings.yaml
Plugins:
  - napari: 0.5.0a2.dev760+g74ecc56c6 (81 contributions)
  - napari-console: 0.0.9 (0 contributions)
  - napari-svg: 0.2.0 (2 contributions)

**Comment by jni** [comment]
Looks like this dates back to Pydantic2 (see `====>` markers):

```
$ pip install "pydantic[dotenv]==2.0"
Collecting pydantic==2.0 (from pydantic[dotenv]==2.0)
  Downloading pydantic-2.0-py3-none-any.whl.metadata (117 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 118.0/118.0 kB 1.0 MB/s eta 0:00:00
Collecting annotated-types>=0.4.0 (from pydantic==2.0->pydantic[dotenv]==2.0)
  Using cached annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.0.1 (from pydantic==2.0->pydantic[dotenv]==2.0)
  Downloading pydantic_core-2.0.1-cp311-cp311-macosx_11_0_arm64.whl.metadata (5.2 kB)
Collecting typing-extensions>=4.6.1 (from pydantic==2.0->pydantic[dotenv]==2.0)
  Using cached typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)
====> WARNING: pydantic 2.0 does not provide the extra 'dotenv' <====
Downloading pydantic-2.0-py3-none-any.whl (355 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 355.6/355.6 kB 2.0 MB/s eta 0:00:00
Downloading pydantic_core-2.0.1-cp311-cp311-macosx_11_0_arm64.whl (1.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 2.7 MB/s eta 0:00:00
Using cached annotated_types-0.7.0-py3-none-any.whl (13 kB)
Using cached typing_extensions-4.12.2-py3-none-any.whl (37 kB)
Installing collected packages: typing-extensions, annotated-types, pydantic-core, pydantic
Successfully installed annotated-types-0.7.0 pydantic-2.0 pydantic-core-2.0.1 typing-extensions-4.12.2

$ pip install "pydantic[dotenv]==1.9"
Collecting pydantic==1.9 (from pydantic[dotenv]==1.9)
  Downloading pydantic-1.9.0-py3-none-any.whl.metadata (121 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.8/121.8 kB 890.4 kB/s eta 0:00:00
Requirement already satisfied: typing-extensions>=3.7.4.3 in /Users/jni/micromamba/envs/pydantic-test/lib/python3.11/site-packages (from pydantic==1.9->pydantic[dotenv]==1.9) (4.12.2)
Collecting python-dotenv>=0.10.4 (from pydantic[dotenv]==1.9)
  Downloading python_dotenv-1.0.1-py3-none-any.whl.metadata (23 kB)
Downloading pydantic-1.9.0-py3-none-any.whl (140 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.3/140.3 kB 1.7 MB/s eta 0:00:00
Downloading python_dotenv-1.0.1-py3-none-any.whl (19 kB)
Installing collected packages: python-dotenv, pydantic
  Attempting uninstall: pydantic
    Found existing installation: pydantic 2.0
    Uninstalling pydantic-2.0:
      Successfully uninstalled pydantic-2.0
Successfully installed pydantic-1.9.0 python-dotenv-1.0.1
```

Nothing seems to be broken, so I think this is just something that we can remove when we require pydantic >=2.

**Comment by psobolewskiPhD** [comment]
Looks like `pydantic-settings` handles this now?
https://docs.pydantic.dev/latest/concepts/pydantic_settings/#dotenv-env-support

But in the meantime we may want to just add `dotenv` to the dev settings:
https://github.com/napari/napari/blob/b87e9c7e430b5ff98225a86b92233ca913a95ff0/napari/utils/events/debugging.py#L20
