### ISSUE TITLE
strange file-specific 3D rendering (but works in fiji/clearvolume/spimagine)

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#703]
## 🐛❓  Buguestion

This may or may not be a napari bug... but it's very strange, and it seems limited to napari.  I have an image ([download here](https://www.dropbox.com/s/oeoyd4nurbck43c/weird_in_napari.tif?dl=0)) that gives me messed up visuals in napari's 3D rendering, the gif below pretty much sums it up, but here are the bullet points:

- looks/behaves fine in 2D
- in 3D, shows something that almost looks like a GL-type indexing error (see gif), I tried forcing `np.ascontiguousarray`, and other things, but nothing worked.
- strangely, if you roll the axes to ZX or YZ, it looks fine in both 2D and 3D.
- it renders fine in `spimagine` and `clearvolume`
- if you roll the axes enough while in 3D view, you eventually get a segmentation fault.
- i have tried opening and resaving multiple different ways, but it still looks weird in napari XY 3D volume view.

![ezgif-4-e7047efcf658](https://user-images.githubusercontent.com/1609449/69012934-e3101a00-0948-11ea-9bd7-8b7514362626.gif)

this is obviously very low priority... but it is mysterious and _may_ indicate an issue perhaps with our volume layer with certain data? (but of course could just be something about this image that doesn't seem to affect any other program?).  If anyone loads the file and has any thoughts, would be very curious to hear them!
FWIW, the image was processed with `pycudadecon` (my wrapper on the janelia cuda deconvolution library)

**Comment by sofroniewn** [comment]
@tlambert03 do you think this might be related to #576?

**Comment by jni** [comment]
@sofroniewn that was my thought as well.

**Comment by tlambert03** [comment]
oh, yep it's exactly the same.  Sorry I never downloaded @VolkerH's dataset and looked at the bug myself there, but I just did (side note: @VolkerH, that's a really fun image).  It's definitely the same thing, complete with the roll observation (works fine if you roll axes) and segfault from above.  I will close this comment, catch up on the discussion in #576 and try some of the debugging mentioned there.
