### ISSUE TITLE
Consider putting Open Sample in it's own block or in the top block

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari/napari#7068]
## 🧰 Task

With all the new options in the File menu, it's a bit harder to quickly find the Open Sample menu, which is super useful for demos or testing:

<img width="357" alt="image" src="https://github.com/napari/napari/assets/76622105/b292fbec-7a01-4e6e-8011-715c77718e15">

Maybe we should think about moving it to it's own block between the New... and Open... blocks?

**Comment by psobolewskiPhD** [comment]
cc: @DragaDoncila

**Comment by Czaki** [comment]
> Maybe we should think about moving it to it's own block between the New... and Open... blocks?

You think that people use drag'n'drop when opening files, not menu?

**Comment by psobolewskiPhD** [comment]
Not sure I follow?
I think people do use drag and drop, but we should support the menu.
My point is that Open Sample is now harder to spot and use, that's all. It's also a slightly different role than file IO.

**Comment by Czaki** [comment]
For a teacher, samples are useful. But for normal user, "Open" looks more useful and should be easier accessible.

**Comment by psobolewskiPhD** [comment]
Ok, then put Open Samples after the Open block, before Save.
I don't care 🤷

**Comment by DragaDoncila** [comment]
@psobolewskiPhD totally agree it gets a little lost now, I've had the same experience. What do you think about putting `IO Utilies` and `Acquire` in its own group? That way `Open Sample` gets "anchored" to the bottom of `Open`?

![image](https://github.com/napari/napari/assets/17995243/0d1921f0-48fb-4639-9024-e894a14d98f0)

**Comment by jni** [comment]
I like that @DragaDoncila, it's similar to how it was before this way.
