### ISSUE TITLE
Shape gets highlighted if hovered on loosing focus

### ISSUE THREAD

**Issue by OnionKiller** [napari/napari#7074]
### 🐛 Bug Report

When a Shape is hovered with the mouse, and the napari application looses focus, the Shape will be highlighted. This also emits a highlight event. 

### 💡 Steps to Reproduce

Add a `Shapes`  layer and hover over a shape.
Then loose the focus from the napari application with for example tabbing out.
The highlight event for the shapes layer will be emitted, and the shape will be visually highlighted.

[demonstraion video](https://www.loom.com/share/681186ebfb044d309f7a22b98610f0ce?sid=83305afc-42fb-4046-90dc-11197f892d4b)

### 💡 Expected Behavior

I would expect this not to happen.

### 🌎 Environment

napari: 0.1.dev3376+ga6882ad
Platform: Windows-10-10.0.19045-SP0
Python: 3.10.5 (tags/v3.10.5:f377153, Jun 6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)]
Qt: 5.15.2
PyQt5: 5.15.10
NumPy: 1.26.4
SciPy: 1.13.0
Dask: 2024.4.2
VisPy: 0.14.2
magicgui: 0.8.2
superqt: 0.6.4
in-n-out: 0.2.1
app-model: 0.2.6
npe2: 0.7.5

OpenGL:

GL version: 4.6.0 Compatibility Profile Context 24.3.1.240216
MAX_TEXTURE_SIZE: 16384
GL_MAX_3D_TEXTURE_SIZE: 2048
Screens:

screen 1: resolution 1920x1080, scale 1.0
Optional:

numba: 0.59.1
triangle not installed
Settings path:

C:\Users\tomi\AppData\Local\napari.venv_665327481d5ffa929bfcfc10d3499e5b2e1e735a\settings.yaml
Plugins:
napari: 0.1.dev3376+ga6882ad (81 contributions)
napari-console: 0.0.9 (0 contributions)
napari-svg: 0.1.10 (2 contributions)

### 💡 Additional Context

This issue was discovered together with @melonora.

**Comment by psobolewskiPhD** [comment]
Thanks for reporting this issue. I can reproduce when using Pan/Zoom mode or the shape drawing modes -- hover a shape in selection mode already does highlight --  and indeed it is a strange behavior!

**Comment by sheldonsebastianNIH** [comment]
any resolution on this? 
![image](https://github.com/user-attachments/assets/63afe89d-2bab-44f6-9850-50ef0bb38e59)

It shows up on the toy example here too: https://napari.org/dev/gallery/nD_shapes.html

**Comment by sheldonsebastianNIH** [comment]
Update: I found that 0.5.3 does not have the same issue, so I'm using that for now
