### ISSUE TITLE
Milestone checker should check whether the milestone is the next release

### ISSUE THREAD

**Issue by jni** [napari/napari#7079]
## 🧰 Task

Currently the label and milestone checker checks whether there is *a* milestone set for a PR. It should check whether it is the *next* milestone, because otherwise one could set a future milestone for a PR, and *merge* the PR, and but then the release notes process would not pick it up.

**Comment by Czaki** [comment]
How do you think we should decide which milestone is next?

**Comment by jni** [comment]
good question!

Idea 1: filter the milestones to those that can be broken down into a full versiontuple (0.5.0 is valid, 0.5 is invalid), then sort by versiontuple (0, 5, 0).

Idea 2: Make sure that the next milestone always has a due date in https://github.com/napari/napari/milestones, then sort by due date. (I just added one for 0.5.0)

**Comment by Czaki** [comment]
Idea 3. Create GitHub actions secret that will store information about the next milestone and check against it?

**Comment by jni** [comment]
that seems harder to maintain to me...

**Comment by Czaki** [comment]
Why?

**Comment by jni** [comment]
because not everyone has access to secrets and they are buried more deeply in the UX.

I was going to say also that once you set a secret you can't look at it, which would be annoying, *but* actually there's variables, including organisation variables, which are visible:

https://docs.github.com/en/actions/learn-github-actions/variables

Nevertheless I still think it's not so great compared to setting dates on the milestones — which is actually the metadata we want.
