### ISSUE TITLE
Allow Path object in `magic_read`

### ISSUE THREAD

**Issue by glyg** [napari/napari#708]
## Motivation
I tend to use `pahtlib.Path` objects a lot for path manipulation, and passing such an object to `io.magic_read` fails due to:
```py
    if len(filenames) == 0:
        return None
```

`Path` object should be accepted as input to `magic_read`

**Comment by sofroniewn** [comment]
Thanks for catching this @glyg! I think supporting a Path object here too makes a lot of sense. I saw you just opened up a PR for this and so will continue the conversation over there.
