### ISSUE TITLE
Converting image to labels breaks if `projection_mode='mean'`

### ISSUE THREAD

**Issue by brisvag** [napari/napari#7092]
### 🐛 Bug Report

Trying to convert an image to labels will break if the `projection_mode` set is not available for labels.

### 💡 Steps to Reproduce

```py
import napari
import numpy as np
v = napari.Viewer()
v.add_image(np.random.randint(0, 10, (10, 10)))
v.add_image(np.random.randint(0, 10, (10, 10)), projection_mode='mean')
```

Then try convert to labels both layers. The first succeeds, the second fails.

### 💡 Expected Behavior

Not sure what should happen here... I would probably expect for the projection mode to become `None` and move on without it, rather than failing the the layer disappearing forever ^^'

### 🌎 Environment

napari main

**Comment by andy-sweet** [comment]
> I would probably expect for the projection mode to become `None` and move on without it, rather than failing the the layer disappearing forever ^^'

Not disappearing forever is not a hard sell :D 

I'm good with changing the projection mode to `None` when it is incompatible with the target layer type. Ideally with a warning to inform the user that they lost some information (which I might expect from the conversion).

I'd also be good with erroring and keeping the existing layer (assuming that's easy enough with the conversion logic).

> `Layer.mode` is similar in that sense, and it's actually not even exposed via `get_state` at all... Which is somewhat weird.

Don't have strong opinions here, but projection mode determines how the layer is rendered on the canvas, whereas mode determines how the user can interact with the layer on the canvas, so while they have similar typing structure, they are a little different in spirit. But I also don't see why we couldn't apply the same logic we choose for projection mode, though maybe in a separate PR if there nasty details.

**Comment by brisvag** [comment]
> I'm good with changing the projection mode to `None` when it is incompatible with the target layer type. Ideally with a warning to inform the user that they lost some information (which I might expect from the conversion).

Just recently @psobolewskiPhD made the change to remove the old layer once converted since the conversion should be "reversible"... Should we no longer consider it reversible and leave the layer? I don't think losing the projection mode is a big deal, it's easy to re-set in case, so I would lean towards just falling back to none...

**Comment by jni** [comment]
I'm pro falling back to None.

**Comment by psobolewskiPhD** [comment]
> Just recently @psobolewskiPhD made the change to remove the old layer once converted since the conversion should be "reversible".
Just for the record, I implemented the opposite: preventing `pop` when the conversion isn't reversible. 😉

**Comment by brisvag** [comment]
Ah, right sorry :sweat_smile: I guess that's maybe an argument for never popping?
