### ISSUE TITLE
Make napari citable

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#711]
## 🚀 Feature
People are beginning to want to cite napari in their work - [see here](https://twitter.com/adamltyson/status/1196826551607799810) - from @adamltyson.

I suggest we mint a [DOI for the repo using zenodo](https://guides.github.com/activities/citable-code). You can also read more detail in this [guide](https://genr.eu/wp/cite/).

We have to tag a specific release when we make our first DOI - I suggest `0.2.5` - and the zendo will automatically make new DOIs everything we make a new release, though it understands how to link them together.

Thoughts everyone? @royerloic @jni?

I've done this before for a personal repo and can do it again today if people approve. We'll have to decide what we want to citation to look like, we could have named authors, we could have something like `napari team`, we could have a mix, I think we have that flexibility.

We can then add that detail into our README

**Comment by s-m-e** [comment]
Just in case you guys did not know: [JOSS](https://joss.theoj.org/)

**Comment by jni** [comment]
@royerloic and I have discussed a paper on a few occasions. We agreed that we would wait until the plugin system is online to publish one. In the meantime, a Zenodo stamp should work.

**Comment by sofroniewn** [comment]
Thanks for the suggestion @s-m-e, I agree with @jni that we're not quite ready for a full on paper, but when we are I think JOSS could be a great place to target.

**Comment by kevinyamauchi** [comment]
I think it would be great to have a DOI. zenodo seems like a nice option. We have a couple manuscripts in preparation will definitely cite `napari` :)

**Comment by sofroniewn** [comment]
Hi all, after todays discussion it seems like we will move forward on creating a DOI for the napari repo using the authors "napari team". We can then still have more formal publications with named authors etc, but at least this gives us a real DOI for the mean time.

**Comment by sofroniewn** [comment]
Ok - so turns out I was wrong, we don't need to specify anything like authors etc. when generating a DOI. We can set that when we ask people to cite us, which we'll have to add language about to our readme.

This repo is now configured such that the next time we make a release a DOI will automatically get made. We can discuss elsewhere the timing of the next release, and then once that has happened make a PR to the repo adding citation information and our DOI badge
