### ISSUE TITLE
Disabling a plugin in the manager prevents napari from re-luanching

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari/napari#7135]
### 🐛 Bug Report

I disabled napari-svg in the plugin manager (checkbox). After closing and reopening napari, it won't launch with a traceback:
```
Traceback (most recent call last):
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/napari-050/bin/napari", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/napari-050/lib/python3.12/site-packages/napari/__main__.py", line 584, in main
    _run()
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/napari-050/lib/python3.12/site-packages/napari/__main__.py", line 333, in _run
    viewer = Viewer()
             ^^^^^^^^
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/napari-050/lib/python3.12/site-packages/napari/viewer.py", line 64, in __init__
    _initialize_plugins()
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/napari-050/lib/python3.12/site-packages/napari/plugins/__init__.py", line 31, in _initialize_plugins
    _npe2pm.disable(p)
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/napari-050/lib/python3.12/site-packages/npe2/_plugin_manager.py", line 489, in disable
    self._command_menu_map.pop(plugin_name)
KeyError: 'napari-svg'
```

### 💡 Steps to Reproduce

1. Use the plugin manager to disable a plugin
2. Close and re-open napari

### 💡 Expected Behavior

Napery should launch, the plugin should be disabled.

### 🌎 Environment

napari: 0.5.0
Platform: macOS-14.5-arm64-arm-64bit
System: MacOS 14.5
Python: 3.12.4 | packaged by conda-forge | (main, Jun 17 2024, 10:13:44) [Clang 16.0.6 ]
Qt: 5.15.8
PyQt5: 5.15.9
NumPy: 2.0.0
SciPy: 1.14.0
Dask: 2024.7.0
VisPy: 0.14.3
magicgui: 0.8.3
superqt: 0.6.7
in-n-out: 0.2.1
app-model: 0.2.7
npe2: 0.7.6

OpenGL:
  - GL version:  2.1 Metal - 88.1
  - MAX_TEXTURE_SIZE: 16384
  - GL_MAX_3D_TEXTURE_SIZE: 2048

Screens:
  - screen 1: resolution 1680x1050, scale 2.0

Optional:
  - numba: 0.60.0
  - triangle not installed

Settings path:
  - /Users/piotrsobolewski/Library/Application Support/napari/napari-050_bdde1d8b2c9cd4dc4ee966f318a205a98b66b711/settings.yaml
Plugins:
  - napari: 0.5.0 (81 contributions)
  - napari-console: 0.0.9 (0 contributions)
  - napari-ome-zarr: 0.6.1 (2 contributions)
  - napari-svg: 0.2.0 (2 contributions)

### 💡 Additional Context

I was investigating https://github.com/napari/napari/issues/1238

**Comment by psobolewskiPhD** [comment]
Looks like the issue is that when the PluginManager is initialized, the `_command_menu_map` is basically empty:
https://github.com/napari/npe2/blob/eeeeaccfc4a2a56c906d40badd62a1f963197622/src/npe2/_plugin_manager.py#L239-L241

Meanwhile, we run disable right after instantiating it:
https://github.com/napari/napari/blob/5535c71a787a5a17dc1ab8147e23b3bd0eff3131/napari/plugins/__init__.py#L25-L31

Seems like maybe npe2 should check `_command_menu_map` before trying to pop?

**Comment by DragaDoncila** [comment]
Didn't mean to close this - let's keep it open until we release npe2 and can confirm napari installs aren't affected anymore

**Comment by psobolewskiPhD** [comment]
Fixed by https://github.com/napari/npe2/releases/tag/v0.7.7
So if someone hits this, make sure you update npe2!
