### ISSUE TITLE
Set scale bar width to fixed physical size

### ISSUE THREAD

**Issue by jo-mueller** [napari/napari#7164]
## 🚀 Feature: Scale bar of fixed physical size 📏

Add a parameter to set the width of the scale bar to a desired value of physical units. This behaviour would superseed the current automatic determination of the length of the scalebar

## Motivation

Follow-up of an [image.sc discussion](https://forum.image.sc/t/force-scale-bar-size/99916/2): For publication ready-figures that possibly include multiple views on the same object, it would be nice to set the scale bar width to a fixed width in physical units. Currently, in a figure consisting of multiple subfigures, each subfigure would need to be annotated separately - it would be great to be able to just say "Every scale bar refers to 50µm".

## Pitch

Add new properties to `viewer.scale_bar`:
- `viewer.scale_bar.width_physical`: The length of the scale bar in physical units
- `viewer.scale_bar._width`: The length of the scale bar in pixels

For reference, this could ultimately look like the nicely working Fiji scalebar, which responds to whether the scale of an image is set or not:

| With unitset | Without unit set |
| --- | --- |
| <img src="https://github.com/user-attachments/assets/e8dbb3e6-c4f9-497b-b399-32852e931e44" alt="with_units" width="200"> |<img src="https://github.com/user-attachments/assets/da7052f6-3b75-45b1-ae13-ef7121aa3712" alt="with_units" width="200">|

## Alternatives

A similar, yet different approach would be to provide only one parameter `viewer.scale_bar.width` that would refer to whatever is set as the `layer.scale` parameter. Thus, it would be up to the user to set the `scale` of the image accordingly to control the width of the bar and sdave ourselves of making sure that `width_physical` and `width` would always be in sync.

Let me know what you think :)

**Comment by brisvag** [comment]
I like the pitch! I would add a new optional field called `fixed_size` defaulting to `None` in here: https://github.com/napari/napari/blob/main/napari/components/overlays/scale_bar.py.

Then, hook it up here https://github.com/napari/napari/blob/975759073cf81ca2de419e931416d07926aaa8c4/napari/_vispy/overlays/scale_bar.py#L30-L38

and update this function so when `fixed_size is not None`, it uses that instead of calculating an optimal size https://github.com/napari/napari/blob/975759073cf81ca2de419e931416d07926aaa8c4/napari/_vispy/overlays/scale_bar.py#L101

@jo-mueller wanna give it a go? :)

**Comment by jo-mueller** [comment]
I think I'm on the right track here :)


https://github.com/user-attachments/assets/cd53ab86-e9f1-4ab9-a296-c7e8c74b0cfb

**Comment by brisvag** [comment]
Awesome! Yes, go ahead and PR, looks ready to go 💪
Re GUI: maybe it should leave in the scale bar menu like the rest, popping up as a widget. Should be in core IMO! But for a followup PR :P

**Comment by brisvag** [comment]
Awesome! Yes, go ahead and PR, looks ready to go 💪
Re GUI: maybe it should leave in the scale bar menu like the rest, popping up as a widget. Should be in core IMO! But for a followup PR :P

**Comment by psobolewskiPhD** [comment]
@brisvag I was thinking like "Scale bar settings..." and it would open a dock widget.

**Comment by jo-mueller** [comment]
@psobolewskiPhD @brisvag something along the lines of this? Would be cool to have something like a color palette, though 🤔 

```python
@magic_factory(
    color={'label': 'Color'},
    fixed_width={'label': 'Fixed Width [unit]'},
    unit={'label': 'Unit'},
    font_size={'label': 'Font Size'},
    position={'choices': ['bottom right', 'bottom left', 'top right', 'top left']},
    auto_call=True
)
def create_scalebar(color: str = 'white',
                    fixed_width: Optional[int] = None,
                    unit: Optional[str] = '',
                    font_size: Optional[int] = 12,
                    position: str = 'bottom right',
                    visible: bool = True):
    viewer.scale_bar.visible = visible
    viewer.scale_bar.color = color
    viewer.scale_bar.fixed_width = fixed_width
    viewer.scale_bar.unit = unit
    viewer.scale_bar.font_size = font_size
    viewer.scale_bar.position = position
    
```

**Comment by psobolewskiPhD** [comment]
Yeah, that's the gist of it! 
For the color, could use `from napari._qt.layer_controls.qt_colormap_combobox import QtColormapComboBox`
SuperQt has something similar too.
Nitpicking because it's me: do we need the `visible` tick? If this widget is to be accessed from `View > Scale Bar` menu where `visible` already lives? 
Finally, ideally for the `Fixed width` would have a checkbox to activate/deactivate the other widget.

**Comment by jni** [comment]
>  Nitpicking because it's me: do we need the visible tick? If this widget is to be accessed from View > Scale Bar menu where visible already lives? (for a napari feature, for a plugin it makes more sense?)

I think we should potentially remove the menu, or have it in both places. I think it makes more sense to have *all* editable attributes of the scale bar in a single place.

**Comment by psobolewskiPhD** [comment]
😬 I like the menu item for show, for most cases Show/Hide is all you need! 
I agree on the editable attributes, so the color, ticks, etc. I would put in the widget. But show/hide I would leave in the menu.

**Comment by jni** [comment]
Yup, agreed! But there's no reason for it to be in only one place — just like some items are in the layers menu and in the layer context menu, you could have scale bar visibility in both the scale bar "control center" and in the menu.

**Comment by jo-mueller** [comment]
Disucssion about that can continue in #7168 :) @jni I saw that you worked on adding a colorpicker to a magicgui widget [there](https://github.com/pyapp-kit/magicgui/issues/490) so I'd be very interested in hearing your opinion on that :)

**Comment by jni** [comment]
> you worked on adding a colorpicker to a magicgui widget https://github.com/pyapp-kit/magicgui/issues/490 so I'd be very interested in hearing your opinion on that :)

😬 you saw that I *intended* to work on it but didn't 😢
