### ISSUE TITLE
File -> Open image as stack broken from Napari 0.4.19 onwards.

### ISSUE THREAD

**Issue by Joseph-Garvey** [napari/napari#7165]
### 🐛 Bug Report

Expected images to open as a stack. Images opened on separate layers. Reverting to 0.4.19 fixes the issue. Tested with own images (jpeg, png and tiff) and Napari sample images. Napari sample images using a single 3D .tif file work fine.

### 💡 Steps to Reproduce

1. Click File -> Open Files as Stack
2. Observe images opening in separate layers rather than in the stack.

### 💡 Expected Behavior

Images would open as a stack

### 🌎 Environment

Recreated on Mac and Windows.
napari: 0.5.1
Platform: Windows-10-10.0.19045-SP0
Python: 3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:40:08) [MSC v.1938 64 bit (AMD64)]
Qt: 5.15.2
PyQt5: 5.15.11
NumPy: 1.26.4
SciPy: 1.14.0
Dask: 2024.8.0
VisPy: 0.14.3
magicgui: 0.9.1
superqt: 0.6.7
in-n-out: 0.2.1
app-model: 0.2.8
npe2: 0.7.7

OpenGL:
  - GL version:  4.6.14761 Compatibility Profile Context 21.30.02.01 30.0.13002.1001
  - MAX_TEXTURE_SIZE: 16384
  - GL_MAX_3D_TEXTURE_SIZE: 2048

Screens:
  - screen 1: resolution 1920x1080, scale 1.0
  - screen 2: resolution 2400x1350, scale 1.0

Optional:
  - numba: 0.60.0
  - triangle: 20230923
  - napari-plugin-manager: 0.1.0

Settings path:
  - C:\Users\josep\AppData\Local\napari\napari-env_c9b7736bcca0cbc8c73003efd88a2db25209893b\settings.yaml
Plugins:
  - bfio: 2.3.0 (4 contributions)
  - cavendish-particle-tracks: 0.1.dev170+g6e6a2bc (2 contributions)
  - napari: 0.5.1 (81 contributions)
  - napari-aicsimageio: 0.7.2 (2 contributions)
  - napari-console: 0.0.9 (0 contributions)
  - napari-skimage-regionprops: 0.10.1 (2 contributions)
  - napari-svg: 0.2.0 (2 contributions)
  - napari-tools-menu: 0.1.19 (0 contributions)
  - ome-types: 0.5.1.post1 (2 contributions)

**Comment by psobolewskiPhD** [comment]
Arg! Thanks for opening the issue @Joseph-Garvey 
One workaround is drag-and-drop:
- if it's a folder of images and nothing else it will be a stack
- if it's multiple images, hold Shift to get a stack -- this should be better documented!!
- Hold option to get the plugin chooser -- can hold both shift and option

**Comment by jni** [comment]
Why is there a for-loop at all? ie could the update not be to:

```python
 def _open_files_dialog(self, choose_plugin=False, stack=False): 
     """Add files from the menubar.""" 
     filenames = self._open_file_dialog_uni(trans._('Select file(s)...')) 
  
     if (filenames != []) and (filenames is not None): 
         self._qt_open( 
             filenames, 
             choose_plugin=choose_plugin, 
             stack=stack, 
         ) 
         update_open_history(filenames[0]) 
```

It feels like there's a bunch of APIs fighting each other here and we should harmonise them rather than pile on more code to work around every possibility at every level...

**Comment by DragaDoncila** [comment]
The I/O code has become increasingly spaghettified over time, so I would be hesitant to make big changes to it for 0.5.2 because chances of breaking other code paths are very high 😬

It would be good to pinpoint what actually broke this pathway between 0.4.19 and 0.5.0 (probably happened before 0.5.1 I'd say) so that we can be a bit more confident of a fix. @lucyleeow is it possible this is related to the menu work? I remember us having a similar issue with calling the wrong command.

Otherwise I would vote for the path of minimal intervention - revamping the I/O code entirely is on my list, but should come post npe1 deprecation.

**Comment by lucyleeow** [comment]
Is now a good time to learn to use git bisect? :grin:

**Comment by DragaDoncila** [comment]
@lucyleeow possibly, but we'd have to learn together cause I'm also not so good with my bisect-fu

**Comment by lucyleeow** [comment]
Yup that's a bad refactor there. I'll open a PR with a fix and try and add a test!
