### ISSUE TITLE
[0.5.2] Points selection tool graphic & Shapes drawing highlights are missing/bugged

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari/napari#7187]
### 🐛 Bug Report

When using the points selection tool, the rectangle selection isn't drawn.
The tool does appear to work, so it appears to be a graphical glitch.

https://github.com/user-attachments/assets/d07fb43c-6d3a-4c84-8bb5-725e1e5c938a

### 💡 Steps to Reproduce

1. Make a points layer
2. Add some points
3. Use the selection tool (`3`) and try to select them. See that it works, but no box is drawn.

### 💡 Expected Behavior

I expect to see the selection box graphic.

### 🌎 Environment

napari: 0.5.2.dev27+g3c7d1a463
Platform: macOS-14.5-arm64-arm-64bit
System: MacOS 14.5
Python: 3.12.5 | packaged by conda-forge | (main, Aug 8 2024, 18:32:50) [Clang 16.0.6 ]
Qt: 6.7.1
PyQt6: 
NumPy: 2.0.1
SciPy: 1.14.0
Dask: 2024.8.0
VisPy: 0.14.3
magicgui: 0.9.1
superqt: 0.6.7
in-n-out: 0.2.1
app-model: 0.2.8
npe2: 0.7.7

OpenGL:
- GL version: 2.1 Metal - 88.1
- MAX_TEXTURE_SIZE: 16384
- GL_MAX_3D_TEXTURE_SIZE: 2048

Screens:
- screen 1: resolution 1680x1050, scale 2.0

Optional:
- numba: 0.60.0
- triangle not installed
- napari-plugin-manager: 0.1.0

Settings path:
- /Users/piotrsobolewski/Library/Application Support/napari/napari-dev_a1eb8b76ba95fa16ad06e26097b46b8455dfbf0b/settings.yaml

**Comment by psobolewskiPhD** [comment]
Bisect points to: b7a8d00decfde0ee255d768ad195e2c18dd89902
https://github.com/napari/napari/pull/7162
Makes sense I guess, since that dealt with selection.

**Comment by Czaki** [comment]
Hm. I do not like this. It looks like `highlight` event is wrongly defined. If this is an event for "anything highlighted on layer" then it should be a private event.

Or at leat any Pr fixing this, should contain detailed update of docstrings

**Comment by psobolewskiPhD** [comment]
Eeep! This is way worse! It affects shapes drawing too, depending on your edge & face color and what you are annotating you can't see, especially with the polygon tool.

**Comment by psobolewskiPhD** [comment]
It's even worse, it also makes interacting with vertexes bugged:
![image](https://github.com/user-attachments/assets/3698754d-13d2-479b-ae11-c9c841017220)
And same with moving Shapes:
![image](https://github.com/user-attachments/assets/e3c476e0-9a67-4b30-acc2-09ea27eea316)
