### ISSUE TITLE
Add .. versionadded:: directives when modifying APIs

### ISSUE THREAD

**Issue by jni** [napari/napari#7192]
## 📚 Documentation

The versionadded directive is a really nice way to tell users when particular arguments or functions were added to an API (example [here](https://github.com/scikit-image/scikit-image/blob/8ba3bfffa79f24810e3be8e5f833ea7e0f954750/skimage/filters/_median.py#L31)). We haven't been using them in napari, which leads to some confusion about when particular APIs were added (who has time to read through a bunch of release notes?) and therefore what the minimum version of napari is to be able to use those APIs (ex: https://github.com/BiAPoL/napari-clusters-plotter/pull/308#issuecomment-2285460086).

**Comment by melissawm** [comment]
Do we want to do this retroactively, too?

**Comment by jni** [comment]
Um, in an ideal world with infinite resources, maybe, but I'm not sure it's a priority right now...
