### ISSUE TITLE
Saving large images to tiff fails

### ISSUE THREAD

**Issue by fstur** [napari/napari#7195]
### 🐛 Bug Report

When saving images larger than 4GB, I get an error: `error: argument out of range`. The saved file is then incomplete and has missing layers.

### 💡 Steps to Reproduce

1. Open napari
2. Create large image:  
```
data = np.random.randint(low=0, high=2**16, size=(128,4096,4096), dtype='uint16')
viewer.add_image(data)
```
3. Save it anywhere via "File" -> "Save Selected Layers" as data.tif

### 💡 Expected Behavior

I expect the file to be saved without raising an error.

### 🌎 Environment

napari: 0.5.2
Platform: Windows-10-10.0.17763-SP0
Python: 3.11.9 | packaged by Anaconda, Inc. | (main, Apr 19 2024, 16:40:41) [MSC v.1916 64 bit (AMD64)]
Qt: 5.15.2
PyQt5: 5.15.11
NumPy: 1.26.4
SciPy: 1.14.0
Dask: 2024.8.0
VisPy: 0.14.3
magicgui: 0.9.1
superqt: 0.6.7
in-n-out: 0.2.1
app-model: 0.2.8
npe2: 0.7.7

OpenGL:
- GL version: 4.6.0 NVIDIA 516.25
- MAX_TEXTURE_SIZE: 32768
- GL_MAX_3D_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1080, scale 1.0
- screen 2: resolution 1920x1080, scale 1.0
- screen 3: resolution 1920x1080, scale 1.0

Optional:
- numba: 0.60.0
- triangle: 20230923
- napari-plugin-manager: 0.1.0

Settings path:
- C:\Users\f.sturzenegger\AppData\Local\napari\fs_napari_d117e5226d23aaac275f4943339fe0c6b128e236\settings.yaml

### 💡 Additional Context

I suspect the issue is that the file is not saved as BigTiff:
The error is raised in `\napari\utils\io.py`, line 106: 
```
tifffile.imwrite(filename, data, compression=('zlib', 1))
```
When I try to export it myself with this line and adding `bigtiff=True`:
```
tifffile.imwrite(filename, data, compression=('zlib', 1), bigtiff=True)
```
it works as expected.

**Comment by Czaki** [comment]
tiff, without bigtiff extension, allows saving data up to 4GB. 
So fixing PR should calculate the size of the data array and pass `bigtiff=True` only then. 

Not all software support reading big tiff.

**Comment by jni** [comment]
>  So fixing PR should calculate the size of the data array and pass bigtiff=True only then.

Yes, I agree, that's the correct fix.

**Comment by jni** [comment]
We could be cute (no branching): 

```python
tifffile.imwrite(filename, data, ..., bigtiff=(data.nbytes > 2**32 - 1))
