### ISSUE TITLE
`ActionManager` shared between tests, can cause problems running several tests 

### ISSUE THREAD

**Issue by lucyleeow** [napari/napari#7219]
Noticed in #7052 (see: https://github.com/napari/napari/pull/7052#issuecomment-2306306688)

`ActionManager` is only created once (i.e., init only happens once) for all tests. It happens when pytest is running `conftest.py` (we import `LayerList`, which ultimately results in running `from napari.utils.action_manager import action_manager` in `layer_utils.py`). AFAICT this isn't currently a problem elsewhere (aside from in #7052) in our test suite, BUT it is not ideal/clean. Also it's not like our tests are very complete/exhaustive, so that's probably another reason this has not caused a problem elsewhere yet. 

The above in combination with the fact that [`Action.injected`](https://github.com/napari/napari/blob/35a99366f2a8ef5bcdbd6e1f874f5ca2a7572582/napari/utils/action_manager.py#L42) is cached, can cause problems when running several tests, in particular when a previous test uses the  `make_napari_viewer` fixture (note not a problem if the fixture is added as argument but not executed in the test) and a subsequent test wants to change the providers (or processors) registered. This causes the injection error (e.g., https://github.com/napari/napari/issues/5803#issuecomment-1553378607)

`make_napari_viewer` runs `Action.injected` on all the actions that have shortcuts (AFAICT the viewer and layer button actions). The call stack is:

1. During `QtViewer` init, [`self._bind_shortcuts()`](https://github.com/napari/napari/blob/35a99366f2a8ef5bcdbd6e1f874f5ca2a7572582/napari/_qt/qt_viewer.py#L255) is run
1. This 'resets' (unbinds then binds) shortcuts (AFAICT the only shortcuts are the ones associated with viewer and layer button actions)
https://github.com/napari/napari/blob/35a99366f2a8ef5bcdbd6e1f874f5ca2a7572582/napari/_qt/qt_viewer.py#L433-L438
1. During `action_manager.bind_shortcut` [`_update_shortcut_bindings`](https://github.com/napari/napari/blob/35a99366f2a8ef5bcdbd6e1f874f5ca2a7572582/napari/utils/action_manager.py#L167) is run which runs:
https://github.com/napari/napari/blob/35a99366f2a8ef5bcdbd6e1f874f5ca2a7572582/napari/utils/action_manager.py#L186
  `action.injected` is a `cached_property`:
  https://github.com/napari/napari/blob/35a99366f2a8ef5bcdbd6e1f874f5ca2a7572582/napari/utils/action_manager.py#L41-L51

This can cause problems when running a subsequent test, e.g., from #7052 we have a `test_transpose_rotate_button` which does not create a full viewer and tries to use it's own provider. However, if `Action.injected` has already been run, the new provider is not utilised as `injected` is not run again.

Note `test_transpose_rotate_button` will work when run in isolation as `Action.injected` is able to run.
(call stack `qtbot.mouseClick` calls `ActionManager._trigger` which calls `self._actions[name].injected()` which calls `Action.injected`)

If I comment out the `@cached_property`, both tests (a test using `make_napari_viewer` followed by `test_transpose_rotate_button`) can be run together.

~I think in a test setting it would be ideal if we could clear the cache for these shortcut actions at the end of `make_napari_viewer`.~ **I think for tests we should clean up `ActionManager` between tests.** The safest/cleanest way would be to instantiate a new `ActionManager`? Alternatively we can clear `ActionManager` properties (e.g, `_actions`) but this seems less clean?

cc @psobolewskiPhD @DragaDoncila

**Comment by DragaDoncila** [comment]
Thanks for the write-up @lucyleeow. I guess the question is how much time we want to spend making an `action_manager` fixture that is clean and robust if we're planning on deprecating it anyway? 😬 I know it's likely to still be around for a while but I just imagine there's going to be some complexity there given the interdependence between `make_napari_viewer` and `mock_app` and now `action_manager`. I also imagine having a clean `action_manager` for each test will slow down our suite, but maybe we can make the fixture explicit (so, not auto-used)? Or maybe we can give `make_napari_viewer` a clean `action_manager` so that `make_napari_viewer` tests are at least guaranteed some isolation?

**Comment by lucyleeow** [comment]
> but maybe we can make the fixture explicit (so, not auto-used)? Or maybe we can give make_napari_viewer a clean action_manager so that make_napari_viewer tests are at least guaranteed some isolation?

yup both these options seem reasonable to me. I am not sure what would be the best option here. I guess a `action_manager` fixture would be 'cleaner' (and more explicit) but is it more work/less performant?

**Comment by DragaDoncila** [comment]
Yeah I guess my first step would be to see whether using the fixture in [this file](https://github.com/napari/napari/blob/main/napari/utils/_tests/test_action_manager.py#L13) with the original tests that were breaking in #7052 fixes things. Would have to move the fixture to `conftest.py` I guess. I'm not sure whether we'd need to manually update the fixture to bind actions or whatever

**Comment by lucyleeow** [comment]
This is more complex than originally thought and I am considering a temporary band-aid fix until we deprecate action manager (or no change at all). I don't think this is a great use of time as we plan on deprecating action manager.

**Fixture that returns a new `action_manager`**

Patching action manager from `napari.utils.action_manager.action_manager` is not adequate as it seems that this action manager is alive early on in testing (AFAICT when we import `LayerList` in `conftest.py`, eventually leads to import of `action_manager`) so we would have to patch where it is used. In the `test_transpose_rotate_button` from #7052, this means patching `napari._qt.widgets.qt_viewer_buttons.action_manager`. It would be impractical and bad practice to make a fixture patching everywhere we import `action_manager` (especially as we import it in about 13 places in total).

We could add a `ActionManager` method that returns an instance of `ActionManager` and patch this (similar to what we do in [`mock_app`](https://github.com/napari/napari/blob/994b77b83c7e16363f7938130212790886f75177/napari/utils/_testsupport.py#L143).

The problem then, is that we would need to ensure that all the actions get registered in the new instance of `ActionManager` we create in the fixture. AFAICT, currently this also happens when we import `LayerList` in `conftest.py` (it eventually leads to import of e.g., `napari/layers/image/_image_key_bindings.py`, where we define functions with the `@register_image/viewer_action` decorator)

This is obviously the cleaner/better fix but it seems like a lot of code and a lot of work for something we will in the near-medium future, remove, when we deprecate action manager.

**Band-aid fix**

A temporary band-aid fix is to 'clear the cached property' in `make_napari_viewer` to ensure that `Action.trigger` will run `injected` (I'll open up a PR to show this).

**Do nothing**

It seems that action manager is not well tested and the current state of action manager (single instance shared amongst all tests), while not ideal, was not causing problems prior to #7052. And even in #7052 we found a workaround.

Thoughts welcome, cc @Czaki

**Comment by psobolewskiPhD** [comment]
I'm of the nothing or bandaid persuasion. With the bandaid will this make tests significantly slower? I need to look at the PR I guess.

**Comment by lucyleeow** [comment]
I'm totally okay with not doing anything. It's at least documented in this issue should we encounter the problem again...

**Comment by DragaDoncila** [comment]
> With the bandaid will this make tests significantly slower? 

This was one concern I had with the bandaid, what's the best way to check @psobolewskiPhD ?

**Comment by Czaki** [comment]
My main worry is that #7224 is to mask a potential problem. As we support use cases where we have multiple viewers opened at the same time, or there are several viewers opened and closed in one session. Even with plugins actions.

**Comment by lucyleeow** [comment]
To clarify, you are worried that #7224 will mask problems with future and/or existing tests?

I think I can understand the concern but thinking about it more:

* the only actions affected are ones that are registered with action manager, AFAICT I think this is now 'just' the viewer/layer actions. Plugin and menu actions should be run with app-model
* forcing `Action.injected` to 'always' run for each new test will only change in these two cases:
   * the provider/processors are changed in the test (e.g., a new provider added or existing provider deleted)
   * what we are injecting is changed, e.g., for your multiple viewer scenario, if we have a new viewer, then the currently active viewer would be injected.

Considering the above, I feel almost that this change would unveil problems with tests?

Again, I am also okay with doing nothing. The issue is documented here and we do intend on deprecating action manager, hopefully sooner than later (@dalthviz is a wizard, and has already done an amazing job in #7133)

**Comment by Czaki** [comment]
> the only actions affected are ones that are registered with action manager, AFAICT I think this is now 'just' the viewer/layer actions. Plugin and menu actions should be run with app-model

If I good understand, we plan to remove action manager at all? In such a situation, maybe YOLO and do not care about hiding problems and merge #7224 (with updated title)?

**Comment by lucyleeow** [comment]
We can also do nothing and leave as is.

Yes we plan to remove action manager completely

**Comment by DragaDoncila** [comment]
@lucyleeow I'm on the YOLO side. I'd rather merge as I think if someone was to add more viewer/layer actions, or want to add tests for existing ones, #7224 would make that easier. I'm also somewhat concerned about the (previously unknown to me) coupling between the app and the action-manager, so I'd rather have that cache cleared to ensure the most recent app is what's actually injecting stuff, while we still have this inbetween state.

If you update the title and description of #7224 I'll approve.

**Comment by lucyleeow** [comment]
Good points, will do it now.
