### ISSUE TITLE
[UX] Shape & Points selection status remains visible when another layer is selected 

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari/napari#7233]
When you draw a shape then it become selected when you finish (as of 0.5.0, https://github.com/napari/napari/pull/6640). This is great, because then you can change the Shape color, etc.
If you then switch the layer selection to an Image or Labels layer, the Shape continues to display the "selected" visual, even though it **cannot be interacted with**:
<img width="1198" alt="image" src="https://github.com/user-attachments/assets/b471d551-6fa6-4123-820c-dce9cb578e71">

I feel like this is misleading and can result in stray painting or whatnot if the user tries to interact with the Shape without the Shapes layer selected.
Ideally, the selection visual would drop if a different layer is selected, but, importantly, return when the Shapes layer is re-selected.

Note in 0.4.19 shapes were not selected after drawing, so this potentially confusing effect didn't occur.
Edit: And in 0.4.19 if you manually select a shape and switch to a different layer it becomes de-selected. However, it is not be re-selected upon switching back to the Shapes layer.

Edit2: I reverted https://github.com/napari/napari/pull/6640 locally and Shapes are no longer selected on completion, but if you manually select a shape and change layers the selection visual still persists, so it must be related to a different PR.

Edit3: Selection of Points also persists visually when changing to a different layer type.

**Comment by psobolewskiPhD** [comment]
Git bisect points to 2ff8417f6833b6cd8c12c5e81a8df28ef2244882
Before this commit, if a Shape was selected and the user selected a different layer, the selection would be lost. 
After it, Selection--and the visual that accompanies it--persists.

I feel like losing the selection is better than the current behavior where the visual persists. In an ideal world, the selection would be remembered when changing layers, but the visual would disappear -- IMO.

**Comment by psobolewskiPhD** [comment]
Ha! it's the combination of #5042 *and* #6640 that results in the changed behavior because pre-5042 it was _finish_drawing that was being called in Shapes via the removed event.

**Comment by jni** [comment]
Just spitballing, but maybe we hook up a function to layer list selection changes that turns any non-selected layers' highlights invisible and selected layers' highlights visible?

**Comment by psobolewskiPhD** [comment]
> Just spitballing, but maybe we hook up a function to layer list selection changes that turns any non-selected layers' highlights invisible and selected layers' highlights visible?

Seems reasonable.

**Comment by dalthviz** [comment]
Hi there, checking this following the idea to hide/show highlights following layer selection, something that could be done is to modify `ViewerModel._on_active_layer` adding a call similar as the one being done for the transform box. So changing https://github.com/napari/napari/blob/c2c929a518bfef65d0836a723e6df61e48a54639/napari/components/viewer_model.py#L478-L496

To be something like:

```python
    def _on_active_layer(self, event):
        """Update viewer state for a new active layer."""
        active_layer = event.value
        if active_layer is None:
            for layer in self.layers:
                layer.update_transform_box_visibility(False)
                layer.update_highlight_visibility(False)
            self.help = ''
            self.cursor.style = CursorStyle.STANDARD
        else:
            active_layer.update_transform_box_visibility(True)
            active_layer.update_highlight_visibility(True)
            for layer in self.layers:
                if layer != active_layer:
                    layer.update_transform_box_visibility(False)
                    layer.update_highlight_visibility(False)
            self.help = active_layer.help
            self.cursor.style = active_layer.cursor
            self.cursor.size = active_layer.cursor_size
            self.camera.mouse_pan = active_layer.mouse_pan
            self.camera.mouse_zoom = active_layer.mouse_zoom
            self.update_status_from_cursor()
```

While adding over the `Layer` definition something like:

```python
    def update_highlight_visibility(self, visible):
        self._highlight_visible = visible
        self._set_highlight(force=True)
```

Then, over the Shapes layer logic related with highlight computation, we could use the `self._highlight_visible` as flag to just return default values used when no selection is available. So I think the methods that would be changed are `_outline_shapes` and `_compute_vertices_and_box`. For example, `_outline_shapes`:

https://github.com/napari/napari/blob/c2c929a518bfef65d0836a723e6df61e48a54639/napari/layers/shapes/shapes.py#L2452-L2486

Would become:

```python
    def _outline_shapes(self):
        """Find outlines of any selected or hovered shapes.

        Returns
        -------
        vertices : None | np.ndarray
            Nx2 array of any vertices of outline or None
        triangles : None | np.ndarray
            Mx3 array of any indices of vertices for triangles of outline or
            None
        """
        if self._highlight_visible and self._value is not None and (
            self._value[0] is not None or len(self.selected_data) > 0
        ):
            if len(self.selected_data) > 0:
                index = list(self.selected_data)
                if self._value[0] is not None:
                    if self._value[0] in index:
                        pass
                    else:
                        index.append(self._value[0])
                index.sort()
            else:
                index = self._value[0]

            centers, offsets, triangles = self._data_view.outline(index)
            vertices = centers + (
                self._normalized_scale_factor * self._highlight_width * offsets
            )
            vertices = vertices[:, ::-1]
        else:
            vertices = None
            triangles = None

        return vertices, triangles
```

With that, you would be able to see the following behavior:

![shapes_highlight_active_layer](https://github.com/user-attachments/assets/11428f3d-ba72-4c36-8de3-5b5efcd2c0ab)

Also, seems like this affects not only the Shapes layer but also the Points layer (those are the only layers that have still a `_on_selection` method). Furthermore, should those `_on_selection` methods be removed? 🤔 

Let me know what you think and if a PR with the approach above would make sense!

**Comment by psobolewskiPhD** [comment]
@dalthviz That looks good to me, I think it would be worth a PR. And indeed you are right, Points also remain selected when switching layers. I will update the OP.

**Comment by jni** [comment]
👍 to PR. I like the changes.
