### ISSUE TITLE
It looks like a separated thread for reporting layer status is causing crashes in benchmarks and tests of another packages 

### ISSUE THREAD

**Issue by Czaki** [napari/napari#7236]
### 🐛 Bug Report

Sample failure:

https://github.com/scverse/napari-spatialdata/actions/runs/10651735292/job/29524660994
[75.00%] ···· /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/multiprocessing/resource_tracker.py:254: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown

Reported here:
https://github.com/scverse/napari-spatialdata/issues/308

I see this in other places but do not saved links

### 💡 Steps to Reproduce

see linked workflow

### 💡 Expected Behavior

Do not crash

### 🌎 Environment

0.5.3

**Comment by jni** [comment]
Ouch!

Do we want to have a way to force single-threaded mode...? Or are you thinking along other lines @Czaki? (Or more likely you need to think about it more than five seconds? 😅)
