### ISSUE TITLE
Plugins that return a layer data tuple with a `DeprecatingDict` fail

### ISSUE THREAD

**Issue by andy-sweet** [napari/napari#7249]
### 🐛 Bug Report

When a plugin returns a layer data tuple where the second element is a `DeprecatingDict` instead of a `dict`, the layer is not validated correctly and raises the following error message.

```
TypeError: Not a valid list of layer data tuples!
```

This exception is raised from `napari.utils.misc.ensure_layer_data_tuple`, which explicitly checks for a `dict`.

This error is most likely to occur when a plugin implementation calls `Layer.as_layer_data_tuple` to initialize the mapping of attributes, then modify that mapping, and return the modified mapping as part of a new tuple.

### 💡 Steps to Reproduce

Here is a test that can be added to `test_magicgui` to reproduce the error.

```python
def test_magicgui_from_layer_data_tuple(make_napari_viewer):
    viewer = make_napari_viewer()

    @magicgui
    def from_layer_data_tuple(image: Image) -> types.LayerDataTuple:
        return image.as_layer_data_tuple()

    viewer.window.add_dock_widget(from_layer_data_tuple)
    image = Image(data=np.zeros((10, 10)))

    from_layer_data_tuple(image)

    assert len(viewer.layers) == 1
    assert isinstance(viewer.layers[0], Image)
    assert viewer.layers[0].source.widget == from_layer_data_tuple
```

### 💡 Expected Behavior

I expect this to run without error.

### 🌎 Environment

napari: 0.4.17rc4.dev1063+ge1be2a723.d20240904
Platform: macOS-14.6.1-arm64-arm-64bit
System: MacOS 14.6.1
Python: 3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:51:49) [Clang 16.0.6 ]
Qt: 5.15.11
PyQt5: 5.15.10
NumPy: 2.0.0
SciPy: 1.14.0
Dask: 2024.6.2
VisPy: 0.14.3
magicgui: 0.8.3
superqt: 0.6.7
in-n-out: 0.2.1
app-model: 0.2.8
npe2: 0.7.6

OpenGL:
  - GL version:  2.1 Metal - 88.1
  - MAX_TEXTURE_SIZE: 16384
  - GL_MAX_3D_TEXTURE_SIZE: 2048

Screens:
  - screen 1: resolution 1512x982, scale 2.0

Optional:
  - numba: 0.60.0
  - triangle not installed
  - napari-plugin-manager: 0.1.0a2

Settings path:
  - /Users/asweet/Library/Application Support/napari/napari-dev_bed8b9b3d61b11a9560a577ec715d63283498f35/settings.yaml
Plugins:
  - napari: 0.4.17rc4.dev1063+ge1be2a723.d20240904 (81 contributions)
  - napari-console: 0.0.9 (0 contributions)
  - napari-svg: 0.2.0 (2 contributions)

### 💡 Additional Context

See the [original post on Zulip](https://napari.zulipchat.com/#narrow/stream/212875-general/topic/DeprecatingDict.20not.20accepted.20in.20LayerDataTuple)

**Comment by Czaki** [comment]
I think that we should just check if this element is an instance of `collections.abc.Mapping`
