### ISSUE TITLE
add play button next to dimensions label and slider

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#725]
## 🚀 Feature
To finish up the work done in #607 adding `play` functionality we need to add play / pause icons to next to the dimensions sliders. These can be the traditional triangle / parallel lines. To add icons one has to follow the instructions in our [contributing guide](https://github.com/napari/napari/blob/master/docs/CONTRIBUTING.md#building-the-icons).

We'll also probably want to make a widget for the whole row of elements at this point:
https://github.com/napari/napari/blob/09bf79ead28c80d879d76b80769aceecbfa28208/napari/_qt/qt_dims.py#L259
and then put the axis name, play button, and slider inside the QHBoxLayout of that widget and then keep that top widget in a list so that it we can call `show` / `hide` on the whole widget rather than all the components as is done here - https://github.com/napari/napari/blob/09bf79ead28c80d879d76b80769aceecbfa28208/napari/_qt/qt_dims.py#L216

For examples of how to toggle styles on button presses one can see how some of our other buttons like `QtNDisplayButton` are styled.

**Comment by sofroniewn** [comment]
This is now underway in #726

**Comment by tlambert03** [comment]
Hah, wow, I hadn’t even seen this.  Guess we were thinking the same thing

**Comment by sofroniewn** [comment]
This has been added in #726
