### ISSUE TITLE
Napari incorrectly adding 3D image as 2D RGBD to viewer

### ISSUE THREAD

**Issue by Karl5766** [napari/napari#7261]
### 🐛 Bug Report

When the last dimension of a 3d ndarray is of length 4, it is automatically inferred as RGBD data and displayed as 2d array even if colormap is explicitly set. The colormap can't seem to be changed to 'red' even after the layer is initialized.

### 💡 Steps to Reproduce

Should reproduce the issue:
```
import napari
import numpy as np

viewer = napari.Viewer()
viewer.add_image(np.ones((1, 4, 4), dtype=np.float32), colormap='red')
viewer.show(block=True)
```

### 💡 Expected Behavior

The image should be displayed as a 1 * 4 * 4 red heatmap instead of 1 * 4 RGBD image. At least there should be indication why this has happened (I encountered this issue when setting the 3d scale or translation in add_image() which leads to the confusing error of attempting to assigning array of shape (3,) to an array of shape (2,)).

### 🌎 Environment

napari: 0.5.4.dev10+g1c073a20 (main branch as of the time posted)
platform: Windows 11
python: 3.11.9

**Comment by Czaki** [comment]
You may specify `rgb=False` to prevent this behavior.

**Comment by jni** [comment]
I again regret including "magic" defaults in napari. 😅 Should we maybe:

1. Remove automatic RGB(A) inference; and
2. Add a right-click -> interpret last dimension as RGB(A) to the layer menu?

Possibly in the same PR? Then we would not have magic (= potentially confusing) behaviour, while still allowing users who want RGBA to get it easily.

An alternative is to go even *more* magical, and call something RGBA if the last dimension is 3/4 *and* much smaller than the preceding 2 dimensions.

**Comment by Czaki** [comment]
Adding requirement to have at least 30 in each dimension may be good.

**Comment by DragaDoncila** [comment]
I would strongly prefer to decrease the magic, not increase it. Why solve this with another if-statement rather than solving it by simplifying things and adding explicit options in the API and GUI?

**Comment by jni** [comment]
> Why solve this with another if-statement rather than solving it by simplifying things and adding explicit options in the API and GUI?

I totally get where you're coming from, but the answer is because I expect that as soon as we turn off the autodetection we'll get a bunch of issues from folks whose RGB images now get represented as a 1024x3 image with a slider with 1024 positions... And I must admit that this would be pretty nasty from a UX perspective.

**Comment by DragaDoncila** [comment]
@jni maybe worth a deprecation warning then?

**Comment by Czaki** [comment]
> @jni maybe worth a deprecation warning then?

We need to improve our readers and writers first to properly handle and save metadata. See https://github.com/napari/napari-tiff/issues/36

**Comment by psobolewskiPhD** [comment]
I think removing the existing magic would be painful...I know I rely on that all the time, especially via the new `New from clipboard` and drag and drop.  😬 
Could try to limit the magic to those while requiring the programmatic approach to be explit?

What would be nice is if it's easier to recover from these issues in the GUI -- this would help pave the way to removing the magic!
For example: if you load and get an RGB image, you can split it using the contextual menu -- sweet. You can merge those to get a 3 channel image... 
...but you cannot (easily) merge/convert a 3 channel image (or 3 layers)  into an RGB image that I've found 😢 

In the above case, I have no idea how to recover in the GUI and get back a (1, 4, 4) layer. Splitting and merging gives a (3, 1, 4).

**Comment by DragaDoncila** [comment]
I think keeping the existing magic is kinda okay. I just don't want to resolve this issue by adding **more** magic which is more inscrutable for the user when it goes wrong.
