### ISSUE TITLE
Stylistic question about signals & slots in napari

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#730]
## ❓ Stylistic Question

curious to hear your thoughts on something:
I've noticed a pattern in a few places in which a given `QWidget` is the only consumer of its own signals.  For instance, each signal in this stretch of QtDims (`update_axis`, `update_range`, etc...) is only consumed by `QtDims` itself; none are connected to any other widgets.
https://github.com/napari/napari/blob/09bf79ead28c80d879d76b80769aceecbfa28208/napari/_qt/qt_dims.py#L84-L111

That makes for a lot of extra boilerplate, as an external event is connected first to a listener, which then emits a signal, which is then connected to its own method.  Why not just connect to method directly given that no one else is listening?  Is it a longer term vision for providing hooks that others might use?

for instance:
```python
self.dims.events.axis_labels.connect(
    lambda ev: self._update_axis_labels(ev.axis)
)
```
instead of
```python
update_axis_labels = Signal(int)

def update_axis_labels_listener(event):
    self.update_axis_labels.emit(event.axis)

self.dims.events.axis_labels.connect(update_axis_labels_listener)
self.update_axis_labels.connect(self._update_axis_labels)
````

**Comment by sofroniewn** [comment]
Yup, so this heterogeneity in the code base relates a little to who wrote the particular piece of Qt code!! In this case this pattern within `QtDims` was written by @royerloic who put in those extra Signals, which I agree I'm not sure we need and it would be simpler to refactor and remove. There might though be some considerations around what thread code runs in (if there is a separate Qt thread from our main thread) but I'm actually not sure about that, and maybe @royerloic can weigh in on this design choice.

As to the long term vision though, we need to think about what we expect plugin developers to want to connect to and how that connection should be done. For example it's very natural to expect a plugin developer to want to trigger so functionality whenever the dimensions sliced change, but there I think they will connect to the event emitted from the dims model and be independent of our particular Qt stuff

**Comment by royerloic** [comment]
@tlambert03 Good catch. I think that the simplification you are calling for is warranted.
As long as there is no other thread than the Qt thread at the origin of any change event to 'self.dims.events.axis_labels' then everything  should be fine. I can't recall why I had it this particular way. I was very systematic and paranoid about having threading issues for sure...

**Comment by tlambert03** [comment]
Ok thanks for weighing in!  Really was just curious.  Will close this, and maybe cull some extra signals here and there when appropriate
