### ISSUE TITLE
Faces in 3d Label visualization look like a dim hollow

### ISSUE THREAD

**Issue by XiaopengZzh** [napari/napari#7323]
### 🐛 Bug Report

Faces rendering in 3d label visualization don't look consistent. See example below.

I just generate a 3d label mask with a rectangular part as label 1.
Rendering of all the 6 faces should look consistent but one of the faces looks like a hollow.

<img width="289" alt="rendering" src="https://github.com/user-attachments/assets/01edb2b8-ec4b-4074-9aff-05dd590f752c">

### 💡 Steps to Reproduce

`
import napari
import numpy as np

mask = np.zeros((45, 256, 256))
mask[4:60, 100:150, 100:150] = 1

viewer = napari.Viewer()
viewer.add_labels(mask, name='rectangular')
napari.run()
`

Then look at the face on the backside.

### 💡 Expected Behavior

Faces rendering should look consistent.

### 🌎 Environment

napari version : 0.4.18
macOS : Ventura 13.5

**Comment by Czaki** [comment]
This happens when the border of the label is the border of the image. You need to have 1-pixel of zeros on the border of labels data.

**Comment by XiaopengZzh** [comment]
I've tried what you said. It's correct. Thank you so much.
