### ISSUE TITLE
Error when emptying shapes list while a shape is selected

### ISSUE THREAD

**Issue by MosGeo** [napari/napari#7335]
### 🐛 Bug Report

An `IndexError: list index out of range` is triggered when data is cleared in the shapes layer (using code) while a shape is selected. I believe this is because the selection code is attempting to find the shape somehow. Also, I am not 100% sure but this might be a regression bug. I would have think that I tested this exact situation in the past and everything worked as expected.

The current workaround is to manually set the selection to empty before clearing.

### 💡 Steps to Reproduce

1. Add shapes layer and a shape in it.
2. Make sure one of the shapes is selected
3. Attempts to clear the data in the layer using `layer.data = []`

### 💡 Expected Behavior

Data is cleared normally (without error) without having manually (using code) to clear the selection.

### 🌎 Environment

- Windows 10 and 11 (64 bit)
- napari 5.4 (and also tested on the latest main branch)

**Comment by Czaki** [comment]
Thanks for reporting. There is PR #7332 to solve this problem
