### ISSUE TITLE
Core dump when running script alone but not when running from within Spyder

### ISSUE THREAD

**Issue by ialxn** [napari/napari#7350]
### 🐛 Bug Report

If I run the script below as stand-alone it core dumps

`$ ./display_in_napari.py`
`/private_share/alxneit/miniforge3/envs/napari/lib/python3.12/site-packages/pydantic/_migration.py:283: UserWarning:  'pydantic.error_wrappers:ValidationError' has been moved to 'pydantic:ValidationError'.`
` warnings.warn(f"'{import_path}' has been moved to '{new_location}'.")`
`SLF4J: No SLF4J providers were found.`
`SLF4J: Defaulting to no-operation (NOP) logger implementation`
`SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.`
`WARNING: QThread: Destroyed while thread is still running`
`Aborted (core dumped)`

If I run the same script from within Spyder's editor by pressing F5 all is fine.

`from glob import glob`
`import napari`
`from aicsimageio import AICSImage`
`from dask import delayed`
`import dask.array as da`

`def read_data(folder):`
`    filenames = glob(f"{folder}/**/*dm4", recursive=True)`
`    # sample used to determine shape and dtype`
`    sample = AICSImage(filenames[0])`

`    lazy_read = delayed(AICSImage)  # lazy reader`
`    lazy_arrays = [lazy_read(fn).data for fn in filenames]`

`    dask_arrays = [`
`        da.from_delayed(delayed_reader, shape=sample.shape, dtype=sample.dtype)`
`        for delayed_reader in lazy_arrays`
`        ]`

`    data = da.concatenate(dask_arrays, axis=2)`
`    return data.rechunk({0:-1, 1:-1, 2:10, 3:-1, 4:-1})`

`if __name__ == '__main__':

`    prefix = './0098_25k_100cm_SA2_CL1-b1/'`
`    data = read_data(prefix)`
`    data.compute_chunk_sizes()`

`    napari.view_image(data, contrast_limits=[0,20000], multiscale=False)`

### 💡 Steps to Reproduce

a) running as script (core dumping)
1) from within bash (ubuntu 20.04) run the script as: `./display_in_napary.py`
2) warnings are displayed (ignore)
3) data is loaded
4) napari viewer window shows (greyed out)
5) core dump

b) running withing Spyder (6.0.1)
1) load file in editor
2) press F5
3) data loads and is displayed in viewer

### 💡 Expected Behavior

In both cases either core-dumping, if I am doing something stupid, or running without a problem (the warning are no issues).

### 🌎 Environment

$ napari --info
napari: 0.5.4
Platform: Linux-5.4.0-200-generic-x86_64-with-glibc2.31
System: Ubuntu 20.04.6 LTS
Python: 3.12.7 | packaged by conda-forge | (main, Oct  4 2024, 16:05:46) [GCC 13.3.0]
Qt: 5.15.8
PyQt5: 5.15.9
NumPy: 2.0.2
SciPy: 1.14.1
Dask: 2024.10.0
VisPy: 0.14.3
magicgui: 0.8.3
superqt: 0.6.7
in-n-out: 0.2.1
app-model: 0.3.0
psygnal: 0.11.1
npe2: 0.7.7
pydantic: 2.9.2

OpenGL:
  - GL version:  4.6 (Compatibility Profile) Mesa 21.2.6
  - MAX_TEXTURE_SIZE: 16384
  - GL_MAX_3D_TEXTURE_SIZE: 2048

Screens:
  - screen 1: resolution 2560x1440, scale 1.0

Optional:
  - numba: 0.60.0
  - triangle not installed
  - napari-plugin-manager: 0.1.3

Settings path:
  - /home/alxneit/.config/napari/napari_3812f083a045a2f88f8bf7dbd95ff6816aaa11dc/settings.yaml
Plugins:
  - napari: 0.5.4 (81 contributions)
  - napari-aicsimageio: 0.7.2 (2 contributions)
  - napari-console: 0.1.0 (0 contributions)
  - napari-svg: 0.2.0 (2 contributions)
  - ome-types: 0.5.2 (2 contributions)

**Comment by ialxn** [comment]
Sorry, I was stupid. I did not start the event loop in the script. Adding `napari.run()` at the very end solves the issue.

**Comment by Czaki** [comment]
you need to add `napari.run()` at the end of `if __name__ == "__main__"` clause. 

When run from Snyder, the qt event loop is created by ipython console.

**Comment by jni** [comment]
@ialxn we've all been there 😅
