### ISSUE TITLE
Add documentation in the napari repo about the GitHub actions workflows and templates

### ISSUE THREAD

**Issue by willingc** [napari/napari#7364]
## 📚 Documentation

When debugging action workflow results, having some contributor/maintainer documentation in the `.github` directory is helpful.

Document the actionlint checks, constraints workflows, and info about automation to reduce manual toil.

**Comment by melissawm** [comment]
We should also point to that documentation from the [Core developer guide](https://napari.org/stable/developers/coredev/core_dev_guide.html)

**Comment by willingc** [comment]
After #7365 lands, I will loop back and add a mention in the the docs @melissawm. :sunny:
