### ISSUE TITLE
Skip then fix frequent CI test failures for test_qt_dock_widget on ubuntu-latest python 3.0

### ISSUE THREAD

**Issue by willingc** [napari/napari#7366]
### 🐛 Bug Report

Frequent failures on ubuntu-latest Python 3.9 pyqt5 pyside6

Related issue: #6665. Possible solution outlined by @Czaki [zulip message](https://napari.zulipchat.com/#narrow/channel/212875-general/topic/better.20docs.20on.20using.20make_napari_viewer.20safely.3F/near/421555725)

A bit curious that it is only happening for this configuration not others. There is evidence of pystack errors in the passing ubuntu versions with python 3.9 pyqt5.

### 💡 Steps to Reproduce

1. Run CI
2. Inspect logs https://github.com/napari/napari/actions/runs/11790129417/job/32840432168?pr=7365#logs

### 💡 Expected Behavior

Tests to pass and to teardown cleanly before starting next test.

### 🌎 Environment

CI; Ubuntu-latest python 3.9 pyqt5 pyside6

### 💡 Additional Context

<img width="676" alt="Screenshot 2024-11-12 at 8 25 04 AM" src="https://github.com/user-attachments/assets/3f94337f-9386-4d0a-a5b1-57c2dcbd29e1">

**Comment by Czaki** [comment]
PyStack errors are unrelated. It happens on every single linux job. 

It looks like the source of problems is this:

```python
  Traceback (most recent call last):
    File "/home/runner/work/napari/napari/napari/_qt/qt_main_window.py", line 329, in eventFilter
      return super().eventFilter(source, event)
  TypeError: 'PySide6.QtCore.QObject.eventFilter' called with wrong argument types:
    PySide6.QtCore.QObject.eventFilter(QWidgetItem, QEvent)
  Supported signatures:
    PySide6.QtCore.QObject.eventFilter(PySide6.QtCore.QObject, PySide6.QtCore.QEvent)
```

I do not understand it. QWidgetItem inherit from QObject.
