### ISSUE TITLE
pyStack error in CI during `test_plugin.py` execution

### ISSUE THREAD

**Issue by willingc** [napari/napari#7379]
### 🐛 Bug Report

```sh
 napari/_tests/test_pytest_plugin.py Process pystack_monitor:
  Traceback (most recent call last):
    File "/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
      self.run()
    File "/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/multiprocessing/process.py", line 108, in run
      self._target(*self._args, **self._kwargs)
    File "/home/runner/work/napari/napari/.tox/py39-linux-pyqt5-no_cov/lib/python3.9/site-packages/pytest_pystack/_monitor_process.py", line 57, in _run_monitor
      raise Exception(
  Exception: new test should not start before previous test finished
```

See #7378 Initial tests 3.9 CI run.

### 💡 Steps to Reproduce

Review #7378 CI log for Initial tests 3.9

### 💡 Expected Behavior

Test to have been fully cleaned up before new test started.

### 🌎 Environment

CI

**Comment by pablogsal** [comment]
> I even tried to ping @pablogsal in person, but it stuck in review.

Sorry for the delay @Czaki :( Unfortunately life got in the way and I have been quite swamped at work and in CPython with and after the 3.13 release so I couldn't get to this in time. I am reviewing this today

**Comment by willingc** [comment]
Thanks @pablogsal. Nice to see you in all the places :heart:

**Comment by willingc** [comment]
Cool @Czaki. We can leave this open until we update a revised pystack package 👍🏼

**Comment by pablogsal** [comment]
Release created and published: https://github.com/bloomberg/pytest-pystack/releases/tag/v1.0.2

**Comment by pablogsal** [comment]
https://pypi.org/project/pytest-pystack/1.0.2/#history

**Comment by willingc** [comment]
Thanks @pablogsal. All is running well with the new release. Thanks @Czaki for the patch too!
