### ISSUE TITLE
[Maint, CI] Rethink napari/utils/_tests/test_io.py::test_imsave_large_file -- it's very slow

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari/napari#7382]
## 🧰 Task

On CI test runs, `napari/utils/_tests/test_io.py::test_imsave_large_file` takes >1 min and on some runs >2 min, making it ~10-15% of total run time.

Currently the test is writing and reading a 4Gb tiff:
https://github.com/napari/napari/blob/b457880f2b8b33b3b966f4a8dcb074dbf87b04d0/napari/utils/_tests/test_io.py#L75-L93

I think we can trust that if `bigtiff=True` is passed to `tifffile.imwrite` that it really works...
maybe we leave the existing test and skip it on CI and add a test with a mock for CI?

**Comment by willingc** [comment]
@psobolewskiPhD #7383 has my local test configuration so that I can toggle on and off slow tests. By marking tests that are slow, we can run them on some matrix environments, instead of all, or highlight the time spent in an output report after tests run.

**Comment by willingc** [comment]
@jni I would perhaps run resource intensive tests against a nightly version instead of on every PR.

**Comment by Czaki** [comment]
> Re #7384 — it occurs to me that the monkeypatch approach violates (analogously) Hynek's "don't mock code you don't own" [principle](https://hynek.me/articles/what-to-mock-in-5-mins/). So I wonder whether we still should have a slow, resource intensive test that we skip on CI but that can be used to e.g. bisect the tifffile version when/if the error raised for big compressed data changes.

I do not agree. I think that this case fits in this exclusion from the article:

>The most common occasion when I break this principle is when I need to simulate errors that aren’t trivial to create organically: certain network conditions, timeouts, integrity errors, …

> @jni I would perhaps run resource intensive tests against a nightly version instead of on every PR.

Current practice is that if code is not executed on PR, the nightly tests do not trigger fixes. Sometimes someone have time for `--pre` tests. But we could use same approach as for examples. Instead of execute in on every OS/Python from CI we created a separate job for it.
