### ISSUE TITLE
Unable to  rename shapes layer.

### ISSUE THREAD

**Issue by liuxiawei** [napari/napari#7409]
### 🐛 Bug Report

Cannot rename shapes layer.  And point or label layer is right
I tried to create new conda env and directly run `napari` but still.
Same situation may happend  #https://github.com/scverse/napari-spatialdata/issues/319

### 💡 Steps to Reproduce

1. create new env 
```micromamba create -y -n napari-env -c conda-forge python=3.9                                                                                              ─╯
micromamba activate napari-env
python -m pip install "napari[all]"
```
2. run  napari in terminal and GUI popout `napari`
3. create new shape layer and tried to rename it 

### 🌎 Environment

napari: 0.5.4
Platform: Linux-6.1.0-27-amd64-x86_64-with-glibc2.36
System: Debian GNU/Linux 12 (bookworm)
Python: 3.9.20 | packaged by conda-forge | (main, Sep 30 2024, 17:49:10)  [GCC 13.3.0]
Qt: 5.15.14
PyQt5: 5.15.11
NumPy: 1.26.4
SciPy: 1.13.1
Dask: 2024.8.0
VisPy: 0.14.3
magicgui: 0.9.1
superqt: 0.6.7
in-n-out: 0.2.1
app-model: 0.3.1
psygnal: 0.11.1
npe2: 0.7.7
pydantic: 2.10.2

OpenGL:
  - GL version:  4.6 (Compatibility Profile) Mesa 22.3.6
  - MAX_TEXTURE_SIZE: 16384
  - GL_MAX_3D_TEXTURE_SIZE: 2048

Screens:
  - screen 1: resolution 1920x1080, scale 1.0

Optional:
  - numba: 0.60.0
  - triangle: 20230923
  - napari-plugin-manager: 0.1.3

Settings path:
  - /home/liuxiawei/.config/napari/napari-env_d75e59720379a693c12376a2b33ea7e497206041/settings.yaml
Plugins:
  - napari: 0.5.4 (81 contributions)
  - napari-console: 0.1.1 (0 contributions)
  - napari-svg: 0.2.0 (2 contributions)

**Comment by psobolewskiPhD** [comment]
Wowza! How odd. I can reproduce.
If you double click you get to edit the name, but then when you hit enter it switches back to Shapes again.
Points, Labels, Image all work fine.

**Comment by psobolewskiPhD** [comment]
And bisect points to... me!
6ba56c8363f0d2f42903f746d87fd1545f2d3dff
😬 
Looks like when I changed the complete shape shortcut, it now steals the Enter from the layer list.

**Comment by psobolewskiPhD** [comment]
well the idea was to match the behavior in Labels--interestingly Labels layer names are editable just fine, while having Enter bound.

**Comment by liuxiawei** [comment]
I test Shift+Enter  is work. Thanks for your work!
