### ISSUE TITLE
Consider removing the bug report form in favor of an old-school template

### ISSUE THREAD

**Issue by jni** [napari/napari#7414]
## 🧰 Task

The issue form is great for guiding newcomers, but it's super annoying when preparing a good report with a separate tool (say vim because I'm offline) — now you can't just copy paste into the issue, you have to grab individual sections one by one.

What do people think about going back to a single text field? Or maybe we create an "advanced" bug report that is a single text field? 🤔

**Comment by Czaki** [comment]
Did using `gh` for the opening issue do not solve this?

**Comment by jni** [comment]
<img width="417" alt="Screenshot 2024-12-03 at 3 31 48 pm" src="https://github.com/user-attachments/assets/d7ce97c7-4205-4608-9b1e-c40cae816b5d">

Interestingly, it is impossible to open a bug report using `gh`, only a blank issue. Which for me is another reason to drop the form, or offer an alternative.

**Comment by DragaDoncila** [comment]
I'm happy to create some separate blank or templated "advanced bug report", but I like the form and think we should keep it for general purposes and newcomers.

**Comment by melissawm** [comment]
Just as a note, you can always use the blank template here: 

<img width="1080" alt="Screenshot 2024-12-03 at 8 01 57 AM" src="https://github.com/user-attachments/assets/675bb510-e011-4db8-b6f4-45b3b0ca3be6">

**Comment by psobolewskiPhD** [comment]
The overall quality of bug reports is so much higher with the new template that I'd rather not switch back!

**Comment by jni** [comment]
yup yup, that's off the cards, the question is do we *also* add a different kind of bug report. But maybe the blank issue is indeed sufficient for my needs, I just feel weirdly guilty using it. 😂 Imma close this, thanks for the discussion all!

**Comment by Czaki** [comment]
This is an issue that you may want to trace https://github.com/cli/cli/issues/5865

**Comment by psobolewskiPhD** [comment]
If you're feeling lazy just use Task and make it "fix this thing " 😜
