### ISSUE TITLE
Add metadata event in Layer EmitterGroup

### ISSUE THREAD

**Issue by ClementCaporal** [napari/napari#7415]
Hello !

## 🚀 Feature
Add metadata event in Layer EmitterGroup

## Motivation

For a plugin I would like to check when the layer's metadata is changed. For that I think the simple way is to user `my_layer.events.metadata`. Maybe there is a reason it is not already the case that I didn't understand?

## Possible implementation

Adding an event here: https://github.com/napari/napari/blob/8ba709156721b9a7050b282114379963c94dc7ad/napari/layers/base/base.py#L455 called `metadata`

And using metadata setter to add `self.events.metadata()`
https://github.com/napari/napari/blob/8ba709156721b9a7050b282114379963c94dc7ad/napari/layers/base/base.py#L669-L672

Thank you!

**Comment by jni** [comment]
I think this is a good idea @ClementCaporal. Would you like to submit a PR to implement it?
