### ISSUE TITLE
Issues displaying RGB volume

### ISSUE THREAD

**Issue by Peter-Hogg** [napari/napari#742]
## 🐛 Bug

Only in-built colormaps are being displayed in the volume viewer but RGB colors are rendered correctly when displayed using the reduced dimensions view option

## To Reproduce

1.  Have an numpy array of a shape as [z, x, y,  3] where the final dimension encodes RGB values 
2.  Display the array using napari.view_image()
3. Toggle between the 2D and 3D views using the "Toggle number of displayed dimensions" button 
4.  The napari will  display the correct colors plane by plane but in the volume view only in-built color maps can be used 

## Expected behavior
Colors seen in the 2D view will be displayed also in 3D
## Environment

 - Please copy and paste the information at napari info option in help menubar here:

 - Any other relevant information:

**Comment by sofroniewn** [comment]
Hi @Peter-Hogg unfortunately the rendering library we're using under the hood - [vispy](https://github.com/vispy/vispy) doesn't support volumetric rgb to the best of my knowledge. I'm not quite sure why not, or how hard it would be to add. I can take a poke around their repo and report back.

For now though you could achieve rgb like functionality in 3D is this by having three separate layers each with their own colormap. Apologies if you are already trying this and it is not what you want.

If you havn't tried it yet, there is some convenience functionality to add data in this way
```python
napari.view_image(your_data, channel_axis=-1, colormap=['red', 'blue', 'green'], ndisplay=3)
```
Does that work for you?

If this isn't what you want, and you'd prefer true `rgb` rendering in 3D as opposed to this approach, I'm curious why. It's definitely something we can look into if there is a demand.

Hope this helps!

**Comment by Peter-Hogg** [comment]
That work around seemed to do the trick! I should have thought of putting the different colors on separate layers, I was doing something similar to visualize something else I was working on. 

Thanks! That helped a lot

**Comment by sofroniewn** [comment]
Great! Maybe we'll look into the 3D rgb at some point, but good to know that works for you for now!
