### ISSUE TITLE
Add tests for world to data normal vector transformation

### ISSUE THREAD

**Issue by jni** [napari/napari#7434]
## 🧰 Task

#7422 was merged without a proper regression test. It would be good to minimally check some reference values and test against that. See comment:

https://github.com/napari/napari/pull/7422#issuecomment-2511605560

**Comment by psobolewskiPhD** [comment]
Gah, you merged while I was working on the branch!

**Comment by jni** [comment]
Sorry, I couldn't tell, I had the impression (because you pushed a commit just merging in main) that you would get to it "someday"! 😂
