### ISSUE TITLE
Creating a Viewer without napari.run() causes a QThread warning on close

### ISSUE THREAD

**Issue by jni** [napari/napari#7446]
### 🐛 Bug Report

Initially reported by @will-moore [on image.sc](https://forum.image.sc/t/napari-viewer-crashes-napari/106176). Running anything that creates a napari Viewer without launching a QApplication causes a QThread warning and Abort trap, including a nasty "crashed application" report on macOS.

```
$ python napari-no-run.py
WARNING: QThread: Destroyed while thread is still running
[1]    46560 abort      python napari-no-run.py
```

### 💡 Steps to Reproduce

Run the following outside of an IPython/Jupyter context:

```python
import napari
viewer = napari.Viewer()
```

### 💡 Expected Behavior

Probably the QThread shouldn't be started, or we should find a way to close it cleanly when the application isn't running? CC @czak

### 🌎 Environment

```
napari: 0.5.5
Platform: macOS-15.1.1-arm64-arm-64bit
System: MacOS 15.1.1
Python: 3.11.10 | packaged by conda-forge | (main, Sep 30 2024, 17:58:42) [Clang 17.0.6 ]
Qt: 5.15.8
PyQt5: 5.15.9
NumPy: 1.26.4
SciPy: 1.14.1
Dask: 2024.9.1
VisPy: 0.14.3
magicgui: 0.10.0rc1
superqt: 0.6.7
in-n-out: 0.2.1
app-model: 0.3.0
psygnal: 0.11.1
npe2: 0.7.7
pydantic: 2.9.2

OpenGL:
  - GL version:  2.1 Metal - 89.3
  - MAX_TEXTURE_SIZE: 16384
  - GL_MAX_3D_TEXTURE_SIZE: 2048

Screens:
  - screen 1: resolution 1800x1169, scale 2.0

Optional:
  - numba: 0.60.0
  - triangle not installed
  - napari-plugin-manager: 0.1.3

Settings path:
  - /Users/jni/Library/Application Support/napari/all_f206df4881e2999baa22e6df448393db299c70d6/settings.yaml
Plugins:
  - affinder: 0.4.0 (10 contributions)
  - midi-app-controller: 0.0.13.dev6+g180a6ba (2 contributions)
  - napari: 0.5.5 (81 contributions)
  - napari-console: 0.1.1 (0 contributions)
  - napari-defdap: 0.1.dev30+gb77d57b.d20241204 (8 contributions)
  - napari-ome-zarr: 0.6.1 (2 contributions)
  - napari-signal-selector: 0.0.6 (10 contributions)
  - napari-svg: 0.2.0 (2 contributions)
  - skan: 0.12.1 (4 contributions)
  - zarpaint: 0.4.0 (19 contributions)
 ```

**Comment by Czaki** [comment]
The problem is caused by calling show

https://github.com/napari/napari/blob/b2edccd6e40e04467ccfeec0257c2160783f7187/napari/_qt/qt_main_window.py#-L707-L708 that starts also the timer.

**Comment by jni** [comment]
Should we gate show by the event loop existing?

**Comment by Czaki** [comment]
> Should we gate show by the event loop existing?

But the event loop exits. It is part of QApplication. It is not started yet

**Comment by jni** [comment]
ok the event loop having started LOL

**Comment by jni** [comment]
Let me make the question more general: do you have any ideas about how we could avoid this?

**Comment by Czaki** [comment]
Yes. But I need to test a little. 

There are few options. 
Check if the event loop is running, but then we need to find another event that we could hook on start of thread (maybe mouse enter canvas).

Update logic, and do not auto show if napari event loop is not running. Then trigger show in `napari.run()` call.  

Potentially something other.
