### ISSUE TITLE
nD-Shapes are selectable from any slice, despite not being visible

### ISSUE THREAD

**Issue by bsorre** [napari/napari#7458]
### 🐛 Bug Report

I have recently observed a change of behavior after updating to 0.5.5 (from ~0.4.17 I think) with the shapes layer :  I plot shapes on a Z stack and I want different shapes on each slice of the stack, just like in this example : https://napari.org/dev/gallery/nD_shapes.html
Before, on each slice the shape corresponding to the slice was appearing and could be edited, as wanted. with the new release, the shape in each slice also appears but it is not possible to select and edit it because all the other shapes from all the other slices also appear when I move the mouse over. The problem is visible in the n_Shapes example. Has the way shapes are handled changed? many thanks again

### 💡 Steps to Reproduce

with this example from napari website:
https://napari.org/dev/gallery/nD_shapes.html

shapes from all the z-slices are selectable in any slice, without being visible

### 💡 Expected Behavior

on previous version (~0.4.17) only the shape corresponding to the slice was visible/selectable/editable 

### 🌎 Environment

napari 0.5.5 python 3.10 windows10

**Comment by psobolewskiPhD** [comment]
Here's a screenshot of trying to select a shape:
![image](https://github.com/user-attachments/assets/b42dae5d-bd5d-4fd8-9512-f97b3a855a09)
