### ISSUE TITLE
Accounting for spatial gaps between slices while 3D rendering

### ISSUE THREAD

**Issue by pskeshu** [napari/napari#746]
I took a stack of DAPI stained nuclei images in diffraction limit, such that there are about 25 images in Z with a spacing of 0.2um between slices. 

When I use the 3D rendering option, the volume image looks like a flat brick, instead of the properly spaced 3D image of a nucleus, which is more of a sphere. 

I noticed that there is no obvious way to set spacing between slices before the 3D render is generated, which I think would have produced the desired results. Is there any easy solution to this, which I'm overlooking?

**Comment by tlambert03** [comment]
Hi @pskeshu,
The answer here depends on how you're adding images to napari.  If you're using python directly you can use the `scale` argument in `napari.view_image` or `viewer.add_image`:
```python
napari.view_image(data, scale=[zstep/pixel_size, 1, 1])
```

If you're dragging and dropping a file on napari, then currently you will have to adjust that scale variable after adding the file.  For instance in the napari console:
```python
viewer.layers[0].scale=[zstep/pixel_size, 1, 1]
```
@sofroniewn is working on the "Open images..." dialog (#616) that will let you specify the spacing at the time of import.

**Comment by sofroniewn** [comment]
@pskeshu has this worked for you? If so I'd like to close this issue

**Comment by sofroniewn** [comment]
I am closing now, but @pskeshu feel free to re-open if you have further problems. I will open an issue on our tutorials repo that this needs better documentation
