### ISSUE TITLE
Layer names should elide in the middle, not end

### ISSUE THREAD

**Issue by jni** [napari/napari#7460]
## 🚀 Feature

Layer names can often be long, and the distinguishing characteristic is as often at the end of the layer name as at the start. When a layer name is too long to display, we should therefore put the ellipsis in the middle of the layer name, rather than at the end.

This issue brought to you by [this toot](https://social.coop/@scottjenson/113676007029747942). 😊

**Comment by psobolewskiPhD** [comment]
💯

**Comment by Czaki** [comment]
As you wish. 
Maybe it should be configurable?

**Comment by psobolewskiPhD** [comment]
No, IMO, not everything needs to be configurable. It just gets overwhelming.
Some things can just be. If they are well thought out and logical then people will either love them or work with them.

**Comment by TimMonko** [comment]
I just changed the reader in my plugin to put the important info at the beginning of the layername instead of the end for this very reason 🤦

BUT! I like this idea way better...for many many reasons. 

Good timing!
