### ISSUE TITLE
Add "copy to clipboard" to version box in the "info" panel

### ISSUE THREAD

**Issue by jni** [napari/napari#752]
## 🚀 Feature

Reviewing #750, it occurred to me that it would be nice to be able to push a button to copy all the required information in the "info" box, rather than having to select it from the scroll box.

**Comment by sofroniewn** [comment]
Would love to see this. Maybe someone can claim issue and then add

**Comment by boonepeter** [comment]
I can give this a shot.

**Comment by sofroniewn** [comment]
That would be great @boonepeter you might want to look at the section of our [contributing guide on adding icons](https://github.com/napari/napari/blob/master/docs/CONTRIBUTING.md#building-the-icons) too as it might be nice to have a simple intuitive icon for the button too

**Comment by sofroniewn** [comment]
Something like the icon that github uses next to its branch names at the top of PRs will work fine, see the bottom right corner of this screen shot 
![image](https://user-images.githubusercontent.com/6531703/70821335-b4426380-1d8f-11ea-96ec-961dbdcdddca.png)
