### ISSUE TITLE
slow imports

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#758]
## 🐛 Bug

@cgohlke has identified some causes of the slowness of our vispy and other imports - see here https://github.com/vispy/vispy/issues/1779 and also this comment from @larsoner https://github.com/vispy/vispy/issues/1779#issuecomment-561305146 related to the use of `pkg_resources` and asking if we can maybe 

> nest the triangle, docutils, and sphinx imports

We should definitely look into doing what we can on our end to improve things too. We can collect ideas here.

**Comment by cgohlke** [comment]
The slow vispy import has been fixed. The numpydoc/sphinx bottleneck is being addressed at https://github.com/numpy/numpydoc/pull/248. On this Windows workstation, `import napari` decreased from ~5.8 s to 2.4 s after fixing vispy, triangle, and docutils.

Some other significant imports: 

* IPython: 0.42 s
* Eventlet through zarr: 0.36 s
* Scipy.signal through vispy -> skimage: 0.29 s

**Comment by tlambert03** [comment]
Awesome!  Way to go.  Thanks for digging into these!

**Comment by cgohlke** [comment]
Eventlet is no longer required by fasteners: https://github.com/harlowja/fasteners/pull/43

**Comment by larsoner** [comment]
Pushed a commit to https://github.com/vispy/vispy/pull/1781 to nest the `skimage` import

**Comment by sofroniewn** [comment]
Vispy `0.6.4` has now been release which contains these improvements. Maybe we should bump our minimum dependency, which I think will also provide a fix to #627. Maybe we can also find out if numpydoc can make an `0.9.2` release.

Unfortunately the PR to harlowja/fasteners#43 has not been responded to yet.

**Comment by sofroniewn** [comment]
numpydoc `0.9.2` has now been released, and I have made a PR #830 to bump our minimum dependency

**Comment by sofroniewn** [comment]
With the napari `0.2.10` release I think we can start thinking about closing this issue. We've bumped our dependencies around the main packages that were slow imports and have been sped up, `vispy`, and `numpydoc`, and we no longer explicitly depend on zarr so the eventlet import shouldn't matter either.

@cgohlke do you notice significant increases in start-up speed with `0.2.10` or do still see room for improvement? Thanks!

**Comment by cgohlke** [comment]
Importing napari 0.2.10 is down to ~1.8 s on my system. That is reasonable. About 30% is taken by importing `napari._qt.qt_console` which imports IPython. I don't know if that could be delayed until the IPython terminal is opened by the user.

**Comment by sofroniewn** [comment]
@cgohlke thanks for checking. Delaying the console import till the console is open sounds like a good idea, we need to refactor some code there anyway to fix things like #687 (ipywidgets related). I'll keep this issue open for now as a reminder and link to #787 where we discussed various console related issues

**Comment by cgohlke** [comment]
There's a regression at https://github.com/napari/napari/blob/24948427e2728ef2216e59f4904d568850db2df9/napari/_qt/dialogs/qt_plugin_dialog.py#L8

**Comment by cgohlke** [comment]
The slow startup issue due to `pkg_resource` is back (tested with napari-0.4.5). This time it comes from xarray, which is loaded on startup through some decorator (?, I guess):

https://github.com/pydata/xarray/blob/318816a8304cf637417e889e563eafe63fde7c12/xarray/__init__.py#L1
https://github.com/pydata/xarray/blob/318816a8304cf637417e889e563eafe63fde7c12/xarray/backends/plugins.py#L7
https://github.com/pydata/xarray/blob/318816a8304cf637417e889e563eafe63fde7c12/xarray/core/formatting_html.py#L6

Also, since napari registers as a pytest plugin, it affects all pytest runs.

**Comment by tlambert03** [comment]
hmmm... this seems tricky.  how would you propose we deal with third-party packages that have slow imports?  We only use xarray in our tests... isn't this just something that anyone using xarray has to deal with anyway?

**Comment by tlambert03** [comment]
(I guess we could take extra care not to check for xarray's existence until the last possible moment?)

**Comment by tlambert03** [comment]
if xarray is heavy, we should probably use a different check for whether something is an xarray here:

https://github.com/napari/napari/blob/68822f8f2ef618cc727442bc5c1a35e70198aa64/napari/utils/misc.py#L419-L425

that will get run all the time

**Comment by tlambert03** [comment]
I always hesitate to use `type(x).__name__ == ` ... but perhaps that's best here.

how about something like
`'xarray' in type_.__module__ and 'array' in type_.__name__.lower()`

```python
# here's what an xarray has:
In [21]: type(data)
Out[21]: xarray.core.dataarray.DataArray

In [22]: type(data).__module__
Out[22]: 'xarray.core.dataarray'

In [23]: type(data).__name__
Out[23]: 'DataArray'
```
