### ISSUE TITLE
Test both PySide2 and PyQt5

### ISSUE THREAD

**Issue by kne42** [napari/napari#768]
While we have chosen to ship with PySide2 rather than PyQt5 due to its more permissive license, we should still ensure that `napari` is compatible with PyQt5 (and any other Python bindings supported by `qtpy` where we can).

Does anyone have an opinion on whether we should run tests with both packages on only the CI or locally as well?

see #767 for an example of how not testing both packages has allowed bugs to slip through that break compatibility with one package

**Comment by tlambert03** [comment]
I agree, I have two dev environments that I check periodically, but I've thought it would be nice to have that on CI.  it'd be nice to keep local tests as speedy as possible, (maybe unless we start finding that they fail on CI a lot)

**Comment by kne42** [comment]
@tlambert03 makes sense. Besides, I don't think that there are enough differences between PySide2 and PyQt5 to warrant a 2x test slowdown.

**Comment by sofroniewn** [comment]
Good idea @kne42 - seems like CI is consensus. This will be even more important after we implement https://github.com/napari/napari/issues/704#issuecomment-555361517 which will make installing with just pyqt5 much easier
