### ISSUE TITLE
Behavior After Deleting All Layers

### ISSUE THREAD

**Issue by AhmetCanSolak** [napari/napari#77]
## ❓ Questions and Help
Once you delete all layers, various IndexErrors are thrown.
What is the expected behavior instead? accordingly we can plan to take a decision about it.
Please provide your understanding and the behavior you are expecting.

**Comment by sofroniewn** [comment]
Yes. I would like us to support deleting all layers, the vispy canvas going black, and then still be able to add in new layers and have everything work (which is not the case right now)

I'd also like us to support launching a new viewer with no image present and then be able to add layers to it. i.e.
```python
viewer = gui.imshow()
viewer.add_image(data, {})
```

or maybe `gui.create()` or something else equivalent

**Comment by sofroniewn** [comment]
This is somewhat possible now, but still might need further work with different layer types
