### ISSUE TITLE
Getting Clim Values From Layers

### ISSUE THREAD

**Issue by AhmetCanSolak** [napari/napari#78]
## ❓ Questions and Help
Hello to all `Napari` friends. 

I am currently trying to implement the clim slider feature.
To initialize the vertical range slider for clim, i need to get the minimum and maximum color values for all selected layers. Hence i am trying to reach to `viewer.layers._list` list and will be iterating over that list to find min and max color limits. However, we do not have the layers/layerlist in the context of `qt/_control.py`.
- Would you like me to pass layers to Controls contructor in `_viewer.py`?
- or are we considering to come up with a context management for separate qt widgets?

**Comment by sofroniewn** [comment]
I'd say for now "pass layers to Controls contructor in `_viewer.py`" sounds good, it is how we do it for other elements. But once this is done and we go to refactor we can revisit if we don't like it.

**Comment by kevinyamauchi** [comment]
I agree with Nick. Thanks, @AhmetCanSolak ! Looking forward to testing them out!

**Comment by AhmetCanSolak** [comment]
implemented in the way mentioned, you can check in #82 . Thank you guys.
