### ISSUE TITLE
Console refactoring / improvements / bug fixes

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#787]
## ❓ Questions and Help

Following some work from @shanaxel42 in #784 to better manage our console resources it is worth raising some additional questions around the expected behavior of the console in interactive environments like when napari is launched from IPython or Jupyter.

Right now if launched from IPython the button to open the console is there but pressing it does nothing and the console is not created. I think we should remove the button and stick with the principle that if launching from IPython you do not need a built-in console in napari. How does @jni feel about this?

Right now if launched from Jupyter we actually create a console and sync it with the jupyter notebook, but there is a weird issue where you now have to press shift-enter in the console to get things to execute. This is very confusing I think, and I'm not sure that we should provide a console in this case either. I propose we remove both the console and the console button when launching from jupyter.

Finally when launching from a script that contains two `napari.Viewer()` like calls strange things happen where both consoles get connected to the same kernal, typing in either though only makes output appear in the 2nd created one and the `viewer` variable gets overwritten so only the 2nd create Viewer is referred too. This is very strange, but I'm not sure how to improve it and very open to suggestions

In general there also might be an opportunity for @shanaxel42 to remove some unneeded code from `QtConsole` depending on how we resolve these questions, and potentially come up with a cleaner fix for #618 at the same time

**Comment by tlambert03** [comment]
for what it's worth, I agree with all these things.  no need for icon when launching from ipython or jupyter (or at the very least no shift-enter if possible when launching from jupyter... remove altogether if not possible).  and don't clober `viewer` variable, but do something like create a second variable name if `viewer` is in `globals()` and emit a warning...

**Comment by sofroniewn** [comment]
@jni proposed the following - drop console + button from IPython but keep for Jupyter and try and fix shift-enter.

We should allow a remote console to be attached in all cases including #801, at which point for IPython the button should appear

**Comment by sofroniewn** [comment]
We should also fix #687 which is related to our console

**Comment by sofroniewn** [comment]
There have been a couple places where the console has now come up and I think we want to make a couple changes right away

1. Have no IPython / console related imports unless the show console button is clicked by the user. It maybe hard to simultaneously make this possible and make the show console button invisible when launching from IPython - but it would be nice to delay the imports for startup time reasons - see https://github.com/napari/napari/issues/758#issuecomment-573787996 and it would be nice not to display the console button with ipython as we don't support a console. One option would be to keep the button and make it change focus from napari to Ipython, but not sure if that is a crazy Qt / cross platform nightmare or if people like @jni would like that.

2. We should superceed and finish #618 where we again have lazy imports that happen only if we are not in IPython land to prevent us breaking string coloring

3. We should either make sure not to break with ipywidgets #687 and matplotlib widgets #734 when using jupyter, and remove the need for shift enter to drive execution or just remove our jupyter support entirely. I see above @tlambert03 wrote:

> no need for icon when launching from ipython or jupyter (or at the very least no shift-enter if possible when launching from jupyter... remove altogether if not possible)

but I think @jni wanted to keep jupyter support for the console, arguing it was different from just another notebook cell. 

4. We should be more graceful when multiple notebooks are launched from the same viewer. @tlambert03 wrote.

> and don't clober viewer variable, but do something like create a second variable name if viewer is in globals() and emit a warning...

5. Personally I did like the idea of being able to connected to multiple python kernels, see #801, but I think @jni @tlambert03 were less clear on the need. I think before this refactor it might be good to talk about it once more, and then either decide to close #801 or incorporate those changes. (I am leaning towards closing too).

6. We should look at #696 again - addressing the button issue is (1.) - and the responsiveness in jupyter may related to the unintuitive need to press shift+enter to drive execution.

I think @shanaxel42 said she was willing to work on this issue, but we might have to clarify one or two things before she can get going.

**Comment by jni** [comment]
Thanks for keeping track of this issue! Yes this one should be a high priority to fix — the syntax highlighting issue is a pain.

> One option would be to keep the button and make it change focus from napari to Ipython, but not sure if that is a crazy Qt / cross platform nightmare or if people like @jni would like that.

This seems super hard and I think it's better to remove the button for now. There is no "ipython" process, there's terminals running IPython, and there could be many, and now you probably have to look at process IDs and parent processes and so on which are probably different on each platforms, then interact with the platform command for raising, which probably requires accessibility permission on macOS these days... All this for little gain since the terminal is an alt-tab or (in my case, because I have focus-follows-mouse turned on) a mouse slide away.

**Comment by sofroniewn** [comment]
Console loading has now been make lazy, but we still need to improve the default passing of the viewer to the console, and the clobbering that happens with multiple viewers - see https://github.com/napari/napari/pull/1055#discussion_r395432200

**Comment by sofroniewn** [comment]
The remaining work to still address in this issue is now captured by #1530 and #1531 and this issue can be closed
