### ISSUE TITLE
Problems Qt when launching Napari on Ubuntu server using X11

### ISSUE THREAD

**Issue by henrypinkard** [napari/napari#799]
## 🐛 Bug

I suspect this may have more to do with Qt/other dependencies than napari, but posting here in case any ideas of how to address this. I am trying to run napari on a remote server I created on Google Cloud Platform. Eventually, I would like to be able to use #654 to remotely view data using this setup, and I was testing to see if I could use X11 forwarding as suggested by @kne42 on #495 as a temporary workaround. However, I haven't been able to get the napari gui to successfully open. There appear to be several problems related to Qt. I've seen this with multiple versions of Ubuntu and versions of python now.

Most recently I ran this using a fresh install of Ubuntu 19.10 and python 3.7.5. Upon trying to import I get the following error:

```
>>> import napari
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/henry/.local/lib/python3.7/site-packages/napari/__init__.py", line 29, in <module>
    from .viewer import Viewer
  File "/home/henry/.local/lib/python3.7/site-packages/napari/viewer.py", line 1, in <module>
    from qtpy.QtWidgets import QApplication
  File "/home/henry/.local/lib/python3.7/site-packages/qtpy/QtWidgets.py", line 24, in <module>
    from PySide2.QtWidgets import *
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
```

If I follow this instructions on [this StackOverflow answer](https://stackoverflow.com/questions/47710022/import-matplotlib-pyplot-as-plt-importerror-libgl-so-1-cannot-open-shared-obj) and type 

```
sudo apt update
sudo apt install libgl1-mesa-glx
```

this error resolves but I get a new one:  

```
import napari
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/henry/.local/lib/python3.7/site-packages/napari/__init__.py", line 29, in <module>
    from .viewer import Viewer
  File "/home/henry/.local/lib/python3.7/site-packages/napari/viewer.py", line 4, in <module>
    from ._qt.qt_viewer import QtViewer
  File "/home/henry/.local/lib/python3.7/site-packages/napari/_qt/qt_viewer.py", line 11, in <module>
    from vispy.scene import SceneCanvas, PanZoomCamera, ArcballCamera
  File "/home/henry/.local/lib/python3.7/site-packages/vispy/__init__.py", line 30, in <module>
    from .util import config, set_log_level, keys, sys_info  # noqa
  File "/home/henry/.local/lib/python3.7/site-packages/vispy/util/__init__.py", line 14, in <module>
    from . import fonts       # noqa
  File "/home/henry/.local/lib/python3.7/site-packages/vispy/util/fonts/__init__.py", line 13, in <module>
    from ._triage import _load_glyph, list_fonts  # noqa, analysis:ignore
  File "/home/henry/.local/lib/python3.7/site-packages/vispy/util/fonts/_triage.py", line 11, in <module>
    from ._freetype import _load_glyph
  File "/home/henry/.local/lib/python3.7/site-packages/vispy/util/fonts/_freetype.py", line 16, in <module>
    from ...ext.fontconfig import find_font
  File "/home/henry/.local/lib/python3.7/site-packages/vispy/ext/fontconfig.py", line 12, in <module>
    raise ImportError('fontconfig not found')
ImportError: fontconfig not found
```

Next I install fontconfig:

```
sudo apt install fontconfig
```

Now I can import napari, but I try to launch the viewer with the astronaut demo image and I run into:

```
>>> import napari
>>> from skimage import data
>>> with napari.gui_qt():
...     viewer = napari.view_image(data.astronaut(), rgb=True)
...
WARNING: Could not load the Qt platform plugin "xcb" in "" even though it was found.
WARNING: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Aborted (core dumped)
```
And at this point, I get stuck and none of what I can find on Google seems to help. 

Any thoughts?

**Comment by tlambert03** [comment]
Hey @henrypinkard,
I came up against this [recently](https://github.com/napari/napari/pull/658#issuecomment-556553625) as well.  After digging into it a bit, I'm not too optimistic that napari/vispy is ever going to work over X11 (or at least it will be very difficult), given the heavy dependence on OpenGL.

FWIW, I think what you're seeing here is actually a different issue, just getting a valid Qt app instance on google cloud platform... but even if you _do_ get the app to start, I think all you're going to get is a blank screen, with an exception saying `QOpenGLWidget: Failed to create context` as described [here](https://stackoverflow.com/questions/58325757/qopenglwidget-failed-to-create-context).

From what I've able to gather [here](https://www.scm.com/doc/Installation/Remote_GUI.html#opengl-direct-or-indirect-rendering), [here](https://praveen-palanisamy.github.io/blog/2017/02/15/Running-OpenGL-Applications-Remotely), and [here](https://stackoverflow.com/questions/56647701/how-to-use-opengl-on-top-of-ssh), it sounds like using OpenGL over X11 typically defaults to _indirect_ rendering using the GLX protocol, which limits openGL to v1.4.  It's unclear to me whether it's even possible to use direct rendering (that first link above says "When using OpenGL over X11 with SSH, quite often direct rendering is not available").

After reading up on it, I'm personally hanging my hopes on #654 for any sort of remote usage (in that case the GL context would be local, and the viewer model would be passed instead).  If you are able to get the Qt app running on google cloud platform, I would recommend starting here to read more about OpenGL on X11: https://www.scm.com/doc/Installation/Remote_GUI.html

... and perhaps look into [VirtualGL](https://virtualgl.org/About/Introduction) to get around the indirect rendering issue.

**Comment by henrypinkard** [comment]
Thanks @tlambert03 ! Based on that, it sounds like X11 might be more trouble than it's worth, and waiting on progress fro #654 might be the best option.
