### ISSUE TITLE
Expected behavior of clims range slider

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#80]
## ❓ Questions and Help

I'm making this issue to discuss expected behavior of the clims range slider.

I think the slider should only interact with the top most selected visible image layer. If no image layers are selected and visible then the slider should be functionally disabled and visually greyedout. If multiple image layers are selected and visible changes of the slider will only affect the topmost one.

One question is when an image layer is selected what should the min value and the max value of the range slider should be pegged to? Options are

- [0, 1] if the image is a float
- [0, 255] if the image is uint8
- [0, 65,535] for uint16
- [0, 4,294,967,295] for unit32

As was pointed out in the meeting, little data uses that full range. Many cameras are 12-bit or 14-bit. So another option is to look at the max value of the image and set it to say the biggest power of 2 that is greater? Another option is to only use these values as defaults and instead allow the limits to be set in the meta data field when the image layer is created.

The clims slider can be then initialized to the min and max value of the image passed, but are then adjustable up to the ranges described above.

Thoughts @jni @royerloic @AhmetCanSolak ?

**Comment by AhmetCanSolak** [comment]
> I think the slider should only interact with the top most selected visible image layer. If no image layers are selected and visible then the slider should be functionally disabled and visually greyedout. If multiple image layers are selected and visible changes of the slider will only affect the topmost one.
> 
i think disabling such slider is a production level concern. Other than that it could affect only the top most selected image layer, no problem with that.


> One question is when an image layer is selected what should the min value and the max value of the range slider should be pegged to? Options are
> 
> * [0, 1] if the image is a float
> * [0, 255] if the image is uint8
> * [0, 65,535] for uint16
> * [0, 4,294,967,295] for unit32
> 
> As was pointed out in the meeting, little data uses that full range. Many cameras are 12-bit or 14-bit. So another option is to look at the max value of the image and set it to say the biggest power of 2 that is greater? Another option is to only use these values as defaults and instead allow the limits to be set in the meta data field when the image layer is created.
> 

I think this questions deservers a complicated solution in the long run. I would be happy to hear more about what we want to see initally.

**Comment by jni** [comment]
> I think the slider should only interact with the top most selected visible image layer.

Yes, but there's a lot to unpack here. Scenario:
- layer 0 is visible but alpha is 0.5
- layer 1 is visible under that
- layer 1 is selected

I think the sliders apply to Layer 1. Agreed?

Actually it would be good if the sliders showed the layer name on top.

Another scenario:
- layer 0 is visible, alpha is 1
- layer 1 is set to visible, but is occluded by layer 0
- layer 1 is selected

I presume you would argue that then the sliders should be disabled. But what if layer 1 is only partially occluded? It would be annoying for users to have to hide layer 0 then go back to the sliders, then unhide layer 0. My suggestion: if layer 1 is selected, then hovering the cursor over the sliders temporarily shows layer 1 over everything else with low alpha. If the user starts dragging on the slider, the alpha goes to 1, then back to 0.3 when the user releases. Hovering away hides the layer again.

Thoughts on that approach?

@AhmetCanSolak 
> i think disabling such slider is a production level concern

What does this mean? I think it's exactly the right approach.

> If multiple image layers are selected and visible changes of the slider will only affect the topmost one.

This I'm not sure about. I think I would argue that multiple selection also disables the slider. I would contemplate (but not advocate) an exception in the case where all the selected images have the same range (e.g. all uint8).

About the ranges:
- For uint8, 0-255 is a slam dunk
- For float, I would suggest [0, 1] unless the image range is outside of that *or* it spans less than 1/255 of that range (and thus would only display a single shade), in which case, we should use the image range, *with* the ability to change that, perhaps through a text field for the min and max values? (This field could be hidden behind a right-click/double-click if we think it would clutter the interface.)
- For uint16, I'd go for a similar approach, although your powers-of-2 approach sounds great too. An intermediate approach would be to assume 12-bit or 14-bit if the max is exactly 4,095 or 16,383. I'm ok with all of these options, but, if we offer editable ranges, then I would err on the side of displaying the image at close-to-full contrast (ie your powers-of-2 option).

**Comment by AhmetCanSolak** [comment]
> @AhmetCanSolak
> 
> > i think disabling such slider is a production level concern
> 
> What does this mean? I think it's exactly the right approach.
> 
I mean working on ranges and behavior according to selected layers should have more priority right now. Disabling slider can be handled later. To me, it makes more sense to first have a working functional unit then apply it in the way desired. IMHO work order for this feature should be:
`Ranges > Behavior with selected/unselected layers > disabling slider on some condition`.

**Comment by royerloic** [comment]
To start the clim should be applied to all image layers using the common min and max.
If the images are not comparable because on completely different ranges, we can have
a checkbox that let's one normalise all image layers between [0,1]. I instructed @AhmetCanSolak 
to start with that and we will see later how we refine this based on how it looks and feels...

**Comment by sofroniewn** [comment]
@royerloic I disagree with pegging the range of the clims to the max and min. I haven't found that useful personally, and seems unlikely to be sufficient. I often like to put the top clim value larger than the image max as otherwise the images appear almost saturated to me. I am currently doing this in a notebook when using Napari now :-)

I also disagree with applying the clim to all layers simultaneously -- am specifically concerned about the case of different channels of data acquired with dyes of different brightness. 

Would love to hear more about where you're coming from on this one!

**Comment by royerloic** [comment]
What we are planning to do with @AhmetCanSolak is to use:
[min-0.2*(max-min), max+0.2*(max-min)] where min and max are the min and max of all channels.
This assumes that the images are comparable (similar ranges).
If the images have completely different ranges we can toggle a switch to normalise
them all to a common range. We could have a 'brightness' slider per image layer to tune
individual layers brightness. But I still want to have a global setting that always applied.
 
We will start with this and see how it goes.

**Comment by royerloic** [comment]
for saturation, gamma is what you want... 
(remember, there is always a gamma because of screens,
so adjusting gamma is always desirable)

**Comment by sofroniewn** [comment]
Using a some function of the max/min seems like a reasonable place to start.

I don't like the idea of per image sliders / normalization.

Agreed adding gamma changes the game!

But agreed - we'll see how this feels and take it from there!!

**Comment by jni** [comment]
I'm very much with @sofroniewn here: I think global settings are not a great idea. As he says, I'm happy to see how it feels in common use, but e.g. for scikit-image workflows you will often have images in 0-255 and others in 0-1. Using the same range for both is killer to say the least. If you want to switch behaviour then the switch should be *into* the global mode, not away from it.

**Comment by AhmetCanSolak** [comment]
I think @royerloic 's will provide same functionality in the long run and can be preferable. With a normalization button on layers, all images can be mapped [0, 1]. Also without implementing the global clim, there are so many different corner cases handle. I love to decide on this matter after getting more feedback from various users and use cases. Currently we have global implementation in #82

**Comment by sofroniewn** [comment]
Agreed, this issue seems complex enough that getting a couple different implementations working and seeing what feels right seems like a good idea. With just one image in the viewer in #82 the range limits are working ok for me right now, though I'd still like to be able to set them myself, and I havn't played around with enough different types of images yet to get a good sense of them yet. Sometimes I feel like I using just a little bit of the slider range, sometimes a lot. Does anyone know what imageJ does as they have to solve this problem too?

Let me try and explain in a little more detail though why I don't like the global / normalizing option.

One reason is that I would not want to be forced to normalize or copy raw data that I may want to preserve in it's original form for operations by other algorithms. i.e. if as a user I have an algo that expects a 0-255, I don't want to have to be forced to add a conversion back step or have a duplicated copy of the raw data.

A more fundamental reason why i don't like only the global option is that often we may be looking at images that have the same field of view but radically different interpretations. For example it was very common for the community of scientists I was working with to generate a set of uint16 images corresponding to signal from some sample then do analysis on these images to get an r^2 value for each pixel that was between 0-1. We would then want to overlay the two signals on top of each other as they correspond to the same object in space, but there's no way for me to reason about how a global clims should be that simultaneously apply to the r^2 value and the raw signal measurement or what normalization could be done to bring them onto the same axis. Going even further we would sometimes make z-score calculations from the same data that would live in a range of [-2 to 2] say. Now I want to use a zero-meaned diverging colormap for this layer, again I don't see how a global clims can be used in concert with both the r^2 value and the original raw image which have very different colormaps.

For those users that are always looking at the same types of image a checkbox like "apply to all" or "apply to all selected" seems like a reasonable option that can meet all their needs and reproduce the global functionality. I'd propose that if the box is unchecked having the clims apply only to the top most selected visible layer. The examples juan gave above with different opacity values need to be considered, but they are addressable.

I'm happy to provide an example implementation of this if people want and then we can get a feel for the different behaviors and see what more people are interested in. How does this sound to everyone? Curious about @kevinyamauchi experience with this is too.

**Comment by sofroniewn** [comment]
I did some digging into imageJ and how they set look-up-table limits and deal with multiple channels.

Here’s some info from the docs
https://imagej.nih.gov/ij/docs/guide/146-28.html

For a single grayscale image they set the limits of the range to be the min and max of the image. Maybe this will work for most users and we should copy it. I guess I was wrong on this one above ;-)

The auto-button then sets the actual clim values based on a routine that allows a few pixels to be saturated. I’ve always thought it did a reasonable starting job. Also the set button allows users to type in values that may exceed the range of the current sliders (in which case they adjust appropriately), so you maintain a lot of flexibility if you need it. You can also select a default range like the ones I initially proposed (based on the different data types), but I guess they are used less.

<img src="https://user-images.githubusercontent.com/6531703/49476290-68e59480-f7ce-11e8-9d75-3745c7de3d26.png" width="400">

By default adjusting the sliders effect only the “selected / visible” channel. Adjusting while holding shift causes the changes to apply to all channels. We could copy this behavior with a checkbox or hotkey (or both).

**Comment by jni** [comment]
> For a single grayscale image they set the limits of the range to be the min and max of the image.

Wait, what? I've opened plenty of uint8 images with values in {0, 1} that looked totally black in Fiji. Indeed I just tested it and got the same result:

```python
In [1]: image = (np.random.random((512, 512)) * 4095).astype(np.uint16)
In [2]: io.imsave('test-16.png', image)
In [3]: image2 = (np.random.random((512, 512)) > 0.5).astype(np.uint8)
In [4]: io.imsave('test-8.png', image2)
```

`image` indeed displays correctly with the min and max, while `image2` appears all black. So it seems it only uses the image min and max for data types other than uint8.

**Comment by freeman-lab** [comment]
Just to weigh in here... took a look at the PR in https://github.com/Napari/napari-gui/pull/82 , and played around, super fun to see this functionality starting to take shape!

I actually strongly agree with @sofroniewn and @jni that the default should be to apply clims to the selected layer, rather than apply them globally. Totally appreciate that the normalize button per layer helps, but even with that, it still would not be possible to separately adjust the clims for different layers, i.e. adjusting the background image differently relative to some feature or statistical map overlaid on top, which is incredibly common! 

Making it a per-layer setting as default and making global adjustment an option, exactly as @jni suggests, seems much more natural to me.

Maybe this is a good topic for our next sync up meeting?

**Comment by sofroniewn** [comment]
We discussed this issue during our meeting. The conclusion was that we would support a clims slider that applied only to the layers selected, so if only one layer is selected it applies to only that layer, if multiple layers are selected it applies to all the layers forcing them to use the same clims. This may lead to some undesirable behaviours if the multiple selected layers are very different from each other, but that is on the user as they chose to have them all selected.

one thing to note though is this does not support a global operation that keeps the relative clims intact - i.e. an operation like make everything 10% brighter. A feature like this could be highly desirable, but it was not immediately clear how to implement. The decision was made to hold back on it for now, and that in the future it could be enabled with a checkbox / hotkey and we'd need to decide exactly how to do it. Maybe adjusting things according to percentile.

In order to proceed we decided the best option was to merge the global clims PR #82 and that I would then make a layer selection modification on top of this.

**Comment by sofroniewn** [comment]
We have now implemented a first pass at a clims rangebar including layer specific and global modifications. We're still missing the ability to make global changes that respect the relative intensities of different layers, but this behavior could be supported in future PRs if desired.
