### ISSUE TITLE
QSpinBox issue with QT 5.9.6

### ISSUE THREAD

**Issue by boonepeter** [napari/napari#802]
## 🐛 Bug

When trying to use napari on a Windows 10 machine with QT version 5.9.6 I get the following error:
`AttributeError: 'QtCustomDoubleSpinBox' object has no attribute 'setStepType'`. Looks like `setStepType` was [added in Qt 5.12](https://doc.qt.io/qt-5/qspinbox.html#setStepType). I can upgrade Qt and give this another go, but I wanted to document it here in case others run into the same issue.

1. clone from github
2. `pip install -r requirements.txt`
3. `pip install -e .`
4. `napari`

```
  File "C:\Users\Peter\Anaconda3\Scripts\napari-script.py", line 11, in <module>
    load_entry_point('napari', 'console_scripts', 'napari')()
  File "c:\users\peter\source\repos\napari\napari\__main__.py", line 54, in main
    v = Viewer()
  File "c:\users\peter\source\repos\napari\napari\viewer.py", line 61, in __init__
    qt_viewer = QtViewer(self)
  File "c:\users\peter\source\repos\napari\napari\_qt\qt_viewer.py", line 55, in __init__
    self.dims = QtDims(self.viewer.dims)
  File "c:\users\peter\source\repos\napari\napari\_qt\qt_dims.py", line 58, in __init__
    self._update_nsliders()
  File "c:\users\peter\source\repos\napari\napari\_qt\qt_dims.py", line 160, in _update_nsliders
    self._create_sliders(self.dims.ndim)
  File "c:\users\peter\source\repos\napari\napari\_qt\qt_dims.py", line 214, in _create_sliders
    slider_widget = QtDimSliderWidget(self, dim_axis)
  File "c:\users\peter\source\repos\napari\napari\_qt\qt_dims_slider.py", line 86, in __init__
    self._create_play_button_widget()
  File "c:\users\peter\source\repos\napari\napari\_qt\qt_dims_slider.py", line 145, in _create_play_button_widget
    self.play_button = QtPlayButton(self.qt_dims, self.axis)
  File "c:\users\peter\source\repos\napari\napari\_qt\qt_dims_slider.py", line 366, in __init__
    fpsspin.setStepType(QDoubleSpinBox.AdaptiveDecimalStepType)
AttributeError: 'QtCustomDoubleSpinBox' object has no attribute 'setStepType'
```

I appreciate that you mention QT versions on startup...this is helpful.

**Comment by tlambert03** [comment]
Thanks for reporting, I'll fix that.  I'm surprised, however, that when you `pip install requirements` you're getting qt 5.9.  Our requirements.txt specifies `PySide2>=5.12.3`... did you already have an environment setup?

**Comment by boonepeter** [comment]
When I have my base conda environment activated and i install requirements.txt, I can run `pip freeze` and see that PySide2 is 5.13.2.

Within that same environment I can check and see that QSpinBox has that method:
```
>>> from PySide2.QtWidgets import QSpinBox
>>> QSpinBox.setStepType
<method 'setStepType' of 'PySide2.QtWidgets.QSpinBox' objects>
```
So I am a little confused as well.

**Comment by tlambert03** [comment]
I definitely wouldn't recommend pip installing our requirements into your base conda environment.  Particularly pip installing qt into the conda base env can have some gnarly consequences...
if you go into the conda environment where you had previously installed the requirements (assuming it wasn't base), and run `conda list`, is qt installed by pip or by conda?
In any case, it should be fixed now when #803 merges.  Thanks again

**Comment by boonepeter** [comment]
Thanks for that. I'm trying a clean install using conda instead. qt was installed by pip in the previous environment

**Comment by boonepeter** [comment]
Just to follow up, this was an environment issue for me. Installing everything cleanly worked as expected.

**Comment by tlambert03** [comment]
thanks for letting us know!  I'm sure that incompatibility would have shown up at some point for us anyway.

**Comment by Zebrafish007** [comment]
I see the issue "QDoubleSpinBox' object has no attribute 'setStepType" still in Qt5.12.3. Will update to newer version see if its gone.

**Comment by tlambert03** [comment]
weird. [Qt docs](https://doc.qt.io/qt-5/qdoublespinbox.html#setStepType) say it was added in v5.12.  what backend are you using?
In any case, it shouldn't be an issue in the master branch, now that we check `if hasattr(obj, 'setStepType')`... are you seeing this bug in napari?  or just independently?

**Comment by Zebrafish007** [comment]
bugger.. you're quick in responding ;-) I'd removed my comment because I saw "conda list" spamming its 5.9.3 and linked that to above comments. Running the Conda update PyQt=5.12.3 but all froze isn't good enough as I see now. Fysio in 5min so thereafter I check what the status is about updating it to 5.12.3.

**Comment by Zebrafish007** [comment]
QT itself is 5.12.3. Checked.

**Comment by Zebrafish007** [comment]
PyQt=5.12.3 update issue solved via:

`conda config --set allow_conda_downgrades true`
`conda install conda=4.6.14`

and from there update via `conda install qt=5.12.5` to latest version. It auto-installs PyQt=5.12.3 and also the latest Conda version (4.8. in my case when this comment was written).

Problem solved.
