### ISSUE TITLE
Setup.py displays invalid command

### ISSUE THREAD

**Issue by RDIL** [napari/napari#812]
Not sure why, but setup.py says `pip install python==3.6` installs Python 3.6, which is not at all true?  pip is a dependency manager for Python, not a version manager like [RVM](https://rvm.io), I think you may be looking for Pyenv?

**Comment by kne42** [comment]
You're completely right, thanks for reporting this! If you'd like to remove these incorrect instructions, it'd be a pretty simple PR. Otherwise I can do this for you :)
