### ISSUE TITLE
Broken links in docs/CORE_DEV_GUIDE.md

### ISSUE THREAD

**Issue by GenevieveBuckley** [napari/napari#816]
## 📚 Documentation

I saw two broken links in the file `docs/CORE_DEV_GUIDE.md`

**Link 1**
"@napari/core-devs" points to https://github.com/orgs/napari/teams/core-devs, which does not exist. I'm not sure if there is a webpage for napari core dev team members, I wasn't able to find one easily on github.

**Link 2**
`[Merge Only Changes You Understand](#Merge Only Changes You Understand)` should be a link, but instead is rendered like plain text. I think the markdown anchor to the subheading is unhappy because it has spaces in it? This could help: https://gist.github.com/asabaylus/3071099

**Comment by tlambert03** [comment]
that second one is the one that I just pushed to your pr https://github.com/napari/napari/pull/815#issuecomment-567316498

**Comment by tlambert03** [comment]
looks like the teams/core-devs link only works if you're in the organization.
@sofroniewn, if it's only core-devs in the organization anyway, perhaps we should link to https://github.com/orgs/napari/people instead... (that link is always public), but then members will need to make their membership public to appear on that page

**Comment by sofroniewn** [comment]
Thanks for fixing the second one I just merged #815.

As to the first one, as @tlambert03 mentions it looks like right now teams are only visible to people within the org - [see here](https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/changing-team-visibility). I actually just filed a feature request with GitHub asking if they can support a 3rd `Public` option, but that will take a long time.

Right now we use both `napari/core-devs` and `napari/steering-council`. We could drop the links right now, but again not sure how helpful those sections are then. Linking to the people page could be good for now too. I'm not really sure what's best

**Comment by GenevieveBuckley** [comment]
If there's no easy fix, we could just decide this isn't a big deal and close this issue. That's fine too.

**Comment by liu-ziyang** [comment]
For this particular doc (CORE_DEV_GUIDE.md), I don't think this is an issue, because this doc is intended for onboarding newly added core_dev members, meaning they would be in the organization and would be able to see the link themselves when going through the doc.

That being said, I found the same link to core_dev/steering council in napari websites, etc. It can be an issue for people who would like to raise an issue but had no idea whom to reach out to, *and* was not able to get any response from any core dev proactively. In the unlikely event of these scenarios, I would think it is then reasonable to extend the responsibility of steeling council members in written to provide initial guidance.

**Comment by sofroniewn** [comment]
> That being said, I found the same link to core_dev/steering council in napari websites, etc. It can be an issue for people who would like to raise an issue but had no idea whom to reach out to, and was not able to get any response from any core dev proactively. In the unlikely event of these scenarios, I would think it is then reasonable to extend the responsibility of steeling council members in written to provide initial guidance.

Ok yeah hopefully once the napari website reorganizes we can just link to an about team page on the website with the necessary info

**Comment by liu-ziyang** [comment]
Thanks to @sofroniewn, I added another fix for broken link, but for napari.org page: https://github.com/napari/napari.github.io/pull/4.

In the meantime, I think we can close this issue
