### ISSUE TITLE
Pyside2 5.14 not finding correct version of Qt

### ISSUE THREAD

**Issue by gcadenazzi** [napari/napari#818]
## To Reproduce

1. conda create --name test-napari python=3.7
2. conda activate test-napari 
3. pip install napari
4. napari

Traceback (most recent call last):
  File "/home/guido/anaconda3/envs/test-napari/lib/python3.7/site-packages/qtpy/__init__.py", line 204, in <module>
    from PySide import __version__ as PYSIDE_VERSION  # analysis:ignore
ModuleNotFoundError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/guido/anaconda3/envs/test-napari/bin/napari", line 5, in <module>
    from napari.__main__ import main
  File "/home/guido/anaconda3/envs/test-napari/lib/python3.7/site-packages/napari/__init__.py", line 4, in <module>
    from qtpy import API_NAME
  File "/home/guido/anaconda3/envs/test-napari/lib/python3.7/site-packages/qtpy/__init__.py", line 210, in <module>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found
 

Initial import error found to be,

ImportError: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.14' not found (required by /home/guido/anaconda3/envs/test-napari/lib/python3.7/site-packages/PySide2/QtCore.abi3.so)
> /home/guido/anaconda3/envs/test-napari/lib/python3.7/site-packages/qtpy/__init__.py(159)<module>()
-> from PySide2.QtCore import __version__ as QT_VERSION  # analysis:ignore

**Comment by sofroniewn** [comment]
Hmm there seems to be something going wrong with the conda virtual environment not finding your Qt. I wonder if @kne42 or @jni has any suggestions here. I'm curious if you explicitly try and install `pip install pyside2` if that gets any better?

We should fix this regardless, but I'm also curious if you try `pip install pyqt5` if napari then works - napari can be run with either pyside2 or pyqt5.

**Comment by tlambert03** [comment]
can we get the output of `conda list` after running `pip install napari`?  and also the OS version?

**Comment by jni** [comment]
@jni is sitting right here and he has no idea. =P

**Comment by gcadenazzi** [comment]
ok so I issued the following command,

pip install pyqt5

napari

WARNING: Could not load the Qt platform plugin "xcb" in "" even though it was found.
WARNING: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Aborted (core dumped)

**Comment by jni** [comment]
Output of pip list:

```
 $ pip list
Package                       Version            
----------------------------- -------------------
alabaster                     0.7.12             
asciitree                     0.3.3              
Babel                         2.7.0              
backcall                      0.1.0              
certifi                       2019.11.28         
chardet                       3.0.4              
cycler                        0.10.0             
dask                          2.9.0              
decorator                     4.4.1              
docutils                      0.15.2             
fasteners                     0.15               
freetype-py                   2.1.0.post1        
fsspec                        0.6.2              
idna                          2.8                
imageio                       2.6.1              
imagesize                     1.1.0              
ipykernel                     5.1.3              
ipython                       7.10.2             
ipython-genutils              0.2.0              
jedi                          0.15.1             
Jinja2                        2.10.3             
jupyter-client                5.3.4              
jupyter-core                  4.6.1              
kiwisolver                    1.1.0              
MarkupSafe                    1.1.1              
matplotlib                    3.1.2              
monotonic                     1.5                
napari                        0.2.7              
networkx                      2.4                
numcodecs                     0.6.3              
numpy                         1.17.4             
numpydoc                      0.9.1              
packaging                     19.2               
parso                         0.5.2              
pexpect                       4.7.0              
pickleshare                   0.7.5              
Pillow                        6.2.1              
pip                           19.3.1             
prompt-toolkit                3.0.2              
ptyprocess                    0.6.0              
Pygments                      2.5.2              
PyOpenGL                      3.1.4              
pyparsing                     2.4.5              
PySide2                       5.14.0             
python-dateutil               2.8.1              
pytz                          2019.3             
PyWavelets                    1.1.1              
pyzmq                         18.1.1             
qtconsole                     4.6.0              
QtPy                          1.9.0              
requests                      2.22.0             
scikit-image                  0.16.2             
scipy                         1.4.1              
setuptools                    42.0.2.post20191203
shiboken2                     5.14.0             
six                           1.13.0             
snowballstemmer               2.0.0              
Sphinx                        2.3.0              
sphinxcontrib-applehelp       1.0.1              
sphinxcontrib-devhelp         1.0.1              
sphinxcontrib-htmlhelp        1.0.2              
sphinxcontrib-jsmath          1.0.1              
sphinxcontrib-qthelp          1.0.2              
sphinxcontrib-serializinghtml 1.1.3              
toolz                         0.10.0             
tornado                       6.0.3              
traitlets                     4.3.3              
urllib3                       1.25.7             
vispy                         0.6.4              
wcwidth                       0.1.7              
wheel                         0.33.6             
wrapt                         1.11.2             
zarr                          2.3.2              
```

The issue is not with PySide or PyQt but with finding libQt it seems. But I have not changed my Linux installation for a long time so I don't think I would have installed Qt 5.14 outside of conda/pip...

**Comment by gcadenazzi** [comment]
OS version is Ubuntu 18.04.3

**Comment by jni** [comment]
Downgrading to lower PyQt works btw.

**Comment by tlambert03** [comment]
We've since switched to shipping with pyqt5 instead of pyside2 by default, and a lot of other things have changed about the install.  I imagine this issue is either solved, or is machine specific at this point... but feel free to open again if you're still having installation issues.
