### ISSUE TITLE
dependabot?

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#833]
what do people think of adding a dependabot hook to the napari repo?  https://github.com/marketplace/dependabot-preview/
I don't think we would necessarily use it to actually merge the PRs (actually bumping our dependency requirements), but it would immediately trigger a CI test every-time something gets released (and problematic updates would immediately fail in a PR test).

**Comment by jni** [comment]
How would you use it? We don't really have a dependency update policy...?

**Comment by tlambert03** [comment]
it would just be to catch things like the numpy 1.18 update breaking tests and numcodecs breaking tests, so we could either fix the problems (as we did in the case of numpy) or pin the requirements.txt (in the case of numcodecs).  Given the high level of activity of napari PRs, we're likely to stumble upon these things pretty quickly anyway, so it's not a big deal... but it also doesn't come with much overhead or effort, this would just open up a new PR each time a dependency was released, we would make sure the tests pass, and then close the PR (or update accordingly if it didn't).  just a passing thought...

**Comment by sofroniewn** [comment]
I like this idea. It seems useful to explicitly test and catch these things and work on fixes rather than just wait for them to be detected organically, which can be confusing when also working on new features in PRs too.

What does @kne42 think?

**Comment by kne42** [comment]
On one hand, it would immediately point out different bugs/incompatibilities and make it easier to separate dependency bugs from bugs introduced in PRs. On the other hand, it might flood us with unnecessary PRs...

I think because it makes it easier to isolate dependency-related bugs, I'm overall in favour of it.

**Comment by tlambert03** [comment]
that's a good point... that could be kinda annoying.  I wonder if it might be better to create a fork that has dependabot active instead... something that won't clutter up the main repo PRs.  It might even be possible to get alerts on failed tests.  Will look into it

**Comment by tlambert03** [comment]
trying it out here: https://github.com/tlambert-forks/napari-dependabot/pulls
feel free to watch that repo if you want to see how the PRs work.  we'll see how useful/interesting it is.

**Comment by sofroniewn** [comment]
I'm curious about the philosophy of dependabot - am I correct that it makes PRs for us to be always == the latest release. Is that desirable? Another philosophy might be to be >= the oldest release we are still compatible with. Thoughts @jni? Would this just now force us to be incompatible for people who for whatever reason are pinned to old versions of libraries? What are the implications for plugin developers?

**Comment by tlambert03** [comment]
that was my immediate question as well after playing with it for a bit.  As you might have noticed, I ended up "cheating" to make it work by actually pinning all of our requirements to a specific version, so that when a new one comes out it will appear out of date and open a PR.  It might be aiming more for the crowd that generally pins requirements precisely, and needs to know about security and other updates (e.g. often in web development).  While it may be possible to still get it to open a PR every time a dependency updates _without_ changing our requirements.txt (or perhaps other similar services do that), I still don't think it's worth adding to all the tooling we've already got going on here.  With the frequency that our tests are run (and the fact that that fork there will also be running dependabot anyway), it's unlikely to add much.  So I'm now 👎on the idea.

**Comment by tlambert03** [comment]
> I'm curious about the philosophy of dependabot - am I correct that it makes PRs for us to be always == the latest release. Is that desirable?

also: no that's not desirable. the intention was never to merge the dependabot PRs... just to be immediately notified of a failing test (or close the PR otherwise).

**Comment by sofroniewn** [comment]
ah ok, yeah I'm probably 👎for now, but curious what others think. Definitely good to be aware of though (I wasn't before this)
