### ISSUE TITLE
make RangeSlider.setValues accept data values (not 0-1) 

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#842]
## 🚀 Feature
In working on #837, I find myself needing to duplicate the logic for setting the values of the contrast limits slider that are defined in the `qt_image_base_layer`:

https://github.com/napari/napari/blob/53d95988fee000f5fa0a1c5e567e09ea05d80635/napari/_qt/layers/qt_image_base_layer.py#L79-L91

That code is due to the fact that the sliders themselves pretty much always have a range from 0-1, and the underlying data needs to get converted to "slider space".  I propose moving that logic inside the range sliders, so that consumers of the RangeSlider can simply set the data as they see it, and the slider figures out how to render itself.  Any objections?  If not, I will probably just do it in #837

**Comment by sofroniewn** [comment]
That is fine with me. @AhmetCanSolak wrote the original range_slider, so he might have comments too.

**Comment by AhmetCanSolak** [comment]
Im glad @tlambert03 you changed this in #844 . I initially implemented with 0-1 input as it was the api logic we had back in time. Thank you!
