### ISSUE TITLE
More advanced 3D rendering

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#843]
## 🚀 Feature
Following up on https://github.com/napari/napari/pull/840#issuecomment-570379878 from @royerloic - right now for 3D arrays we have `translucent`, `mip`, `additive`, and `iso surface` rendering. @royerloic and @AhmetCanSolak mentioned another type of rendering that can be nicer than `mip` and that has one free parameter that you can use to control - i can't remember what it was though. If you could give the name / a link to the rendering equation then I can try implementing it as a new option, which should be easy now that we have a copy of the vispy volume shader code in our repo

**Comment by jni** [comment]
@sofroniewn it's attenuated max projection. Loic talks about it here: https://youtu.be/tSMRoW0-NFY?t=830 It's probably useful for 3D picking as well!

**Comment by sofroniewn** [comment]
Great video - that guy really looks like he knows what he's talking about - would be great if he could make a shader PR to napari ;-) ;-)

@royerloic do you have any links to the equations for this plot?

![image](https://user-images.githubusercontent.com/6531703/71702745-f86cc680-2d85-11ea-9406-cb792b8d8668.png)

One approach I that could imagine is you sum how much you've seen along the ray so far and then scale by something inversely proportional to that maybe `scale = exp(-lambda * sum(values_to_current_point))` so if nothing has been seen so far you have no scaling (`scale=1`) but then the more you see, the larger the sum, and the smaller the negative exponent. The lambda affects the severity of this scaling, so `lambda = 0` is just a normal max intensity projection

This should be pretty easy to implement, so I'll give it a go now. Happy to try other schemes too! I have some cryoEM data that I'd like to make look pretty!!

**Comment by royerloic** [comment]
hahaha... 
Yes, I think it is due time now that I dwelve into some shader code....
and make a nice PR... But I am afraid, @sofroniewn is probably going to get
this done by the time I finish to write this...

For reference, here is the good ol' ClearVolume shader code:

https://github.com/ClearVolume/clearvolume/blob/master/src/java/clearvolume/renderer/opencl/kernels/VolumeRender.cl

The interesting bit is here:
![image](https://user-images.githubusercontent.com/1870994/71703939-45539b80-2d8c-11ea-9a78-cfd6996797c5.png)

In fact, the _really_ interesting bit is this:
![image](https://user-images.githubusercontent.com/1870994/71703954-5a302f00-2d8c-11ea-89bb-0826eb27ed86.png)
Essentially what you described @sofroniewn 

Which can be 'ported' to the more complex shader infrastructure of vispy, and added to the actual volume shader code...

**Comment by royerloic** [comment]
One detail is to scale the decay_rate so that the effect does not overall depend on the number the length of the ray-marching step along the ray (tstep in the code)

**Comment by sofroniewn** [comment]
Thanks @royerloic - I've given this a go in #846, still a little to do, but already looking quite nice I think!

I think you have some offsets / do the mapping slightly differently than I did. I'm happy to adjust etc as needed, the basic effect is very cool though.
