### ISSUE TITLE
Make changing views non-blocking

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#845]
## 🚀 Feature

In https://github.com/napari/napari/issues/763#issuecomment-562552657 @jni wrote:

> Rearchitecting how we update the viewer so that changing views isn't blocking. Right now this last one is a big one, and could kind of happen independent of the transforms thing. Like, if I move the slider quickly and it's a slow process (e.g. Talley's live deconv example), we should be smart enough to toss out the intermediate tasks. The slider itself should never block waiting for the display. This might be reasonably straightforward to achieve with a task queue: rather than just calling np.array() on a dataset, add the call to np.array to a queue, and have that queue hold at most nlayers tasks. Then, as soon as a new event is triggered, drop running queue jobs and start again (unless the hash of the job hasn't changed).

This seems like a nice feature that should be relatively self contained. Curious if people have more thoughts on how / where it should be implemented. Might give us some big usability improvements for relatively little effort. @tlambert03 @jni?

**Comment by jni** [comment]
There's a bit of opportunity to make things generic here. We could build the queuing mechanism into the base layer, which takes as input three functions to do slicing, viewport cropping, and instantiating. These would vary between the layer types but all layer types would need to provide them (even if it's just an identity — which could be implemented in the base layer). Instantiating is `np.asarray` for Image layers, but `np.asarray(_raw_to_displayed())` for labels, etc. Slicing and viewport cropping are done by `__getitem__` and might include subsetting as we do now for big images, but for points it is done by selection.

All of the above would be done asynchronously and this would be managed in a single spot.

Additionally, after the framework is in place, the functions themselves could be made asynchronous, meaning they can yield results progressively as they compute them.

**Comment by sofroniewn** [comment]
I like that idea a lot, some stuff could go inside the `refresh` function https://github.com/napari/napari/blob/53d95988fee000f5fa0a1c5e567e09ea05d80635/napari/layers/base/base.py#L573 now on the base layer, by breaking apart `_set_view_slice` so it doesn't actually do the instantiation

**Comment by d-v-b** [comment]
Yall are probably already thinking this, but making a view change non-blocking is a special case / side effect of lazy tiled loading (#318), so hopefully resolving one of these issues helps resolve the other.

**Comment by mrocklin** [comment]
Does Napari use any sort of event loop, async/await functions, or background threads? Looking online at docs it seems like Qt might have its own thing here.  

In general advanced applications that use Dask for interaction have tended to prefer the [asynchronous API](https://distributed.dask.org/en/latest/asynchronous.html).  I'm not sure if there is a clear place to include that within Napari (assuming that your application isn't already using tornado or asyncio or something), but I thought I'd bring it up.

**Comment by AhmetCanSolak** [comment]
@mrocklin we have some convenience functions to provide async UI update with help of QThreadPool and QRunnable classes from Qt. Typically it is a run-and-forget type of background thread but with help of signals and slots we can easily provide async IO as well. What sort of architecture would be best for Dask interaction? Could you give more details?

**Comment by mrocklin** [comment]
Dask runs on a Tornado or Asyncio event loop.  So if other applications operate with one of those technologies (or anything that can interoperate with them) then you can use standard asyncio/tornado concurrency mechanisms to run things concurrently, cancel them, wait for them, and so on.

**Comment by ttung** [comment]
> Dask runs on a Tornado or Asyncio event loop. So if other applications operate with one of those technologies (or anything that can interoperate with them) then you can use standard asyncio/tornado concurrency mechanisms to run things concurrently, cancel them, wait for them, and so on.

This is only for dask.distributed right? Canceling a data fetch for a simple DaskArray is not supported, as far as I can tell?

**Comment by mrocklin** [comment]
Yes, this is assuming that you are using the dask.distributed scheduler rather than the local threaded scheduler.  

In principle I think that for an application like Napari this shouldn't be too much of an issue.  The lightest weight deployment of only threads in a single process should get pretty close to the lightweight nature of dask.local scheduler.

```python
from dask.distributed import Client
client = Client(processes=False)
```

**Comment by sofroniewn** [comment]
@pwinston you might also be interested in reading this thread about Qt Updates in different threads, particularly this comment from @tlambert03 https://github.com/napari/napari/issues/1110#issuecomment-609078376 who has been thinking about some of this too

**Comment by tlambert03** [comment]
see also some thoughts at #1210

**Comment by liu-ziyang** [comment]
any objection closing this to consolidate effort on async loading?
