### ISSUE TITLE
What is the best solution for cropping feature

### ISSUE THREAD

**Issue by hiroalchem** [napari/napari#848]
I want to crop the image with fixed size (e.g. (128x128)) and launch new viewer.
However I faced some problems.
First, I want to get the clicked coordinate in the image layer, however, I could not find the way to get the value of mouse clicked coordinate (I know I can get the point with point layer, but I want to get the coordinate directly from image layer)
Second, I want to run above function when I click the position with pressing specific key, however I could not figure it out how I can create this kinds of function.
Could I develop the function like this? or does napari already has crop function?
Thank you for your kind help!

**Comment by sofroniewn** [comment]
Hi @hiroalchem, napari doesn’t have crop functionality yet, but I’d like to add it soon, particularly for people doing 3d rendering who want to interactively see inside things.

You can get the coordinates of the last cursor position in the layer as
```python
np.round(layer.coordinates).astype(int)
```

You can also add custom mouse function callbacks with the api defined in #544 and visible in this [custom mouse function example](https://github.com/napari/napari/blob/master/examples/mouse_drag_callback.py). We haven’t added that to our documentation yet, and the interface my change slightly as we refine it, but I hope this can get you going.

Let me know if you are able to get something working for your use case. If not I can put a custom code snippet in here that does this. I can also keep this issue updated with our progress on cropping

**Comment by sofroniewn** [comment]
Here is an example that will crop a region centered on a mouse click and then print the max value in the cropped region - hope this gets you going further

```python
"""
Crop image after mouse click and print max value
"""
import numpy as np
import napari


with napari.gui_qt():
    viewer = napari.view_image(np.random.random((512, 512)))
    layer = viewer.layers[0]

    @layer.mouse_drag_callbacks.append
    def get_max_of_crop(layer, event):
        crop_size = 32
        cords = np.round(layer.coordinates).astype(int)
        min_vals = np.maximum([0]*len(cords), cords - crop_size // 2)
        max_vals = np.minimum(layer.data.shape, cords + crop_size // 2)
        crop = layer.data[tuple(slice(n, x) for n, x in zip(min_vals, max_vals))]
        print('Center coordinate:', cords,'Cropped shape:', crop.shape, ' Cropped max value:', np.max(crop))
```

**Comment by hiroalchem** [comment]
Thanks a lot! This is exactly what I wanted to develop! And it worked fine in my environment.
Furthermore, if it's possible, I would like to use this function with keybindings. For example, when 
 I click the point without pressing any keys, only print the coordinate, however,  clicking the point with pressing 'c', launch the new viewer with cropped image.
Could I make these kind of function?

**Comment by sofroniewn** [comment]
You can determine if modifier keys like `shift` are pressed during the mouse click by looking at the `event.modifiers` property and you can also bind callbacks to keypresses described near the bottom of our viewer tutorial - https://napari.org/tutorials/viewer - or in the [custom keybindings example](https://github.com/napari/napari/blob/master/examples/custom_key_bindings.py)

**Comment by hiroalchem** [comment]
Now I found the example for `event.modifiers`  here [https://github.com/napari/napari/blob/master/examples/custom_mouse_functions.py](https://github.com/napari/napari/blob/master/examples/custom_mouse_functions.py).
Thank you so much!

**Comment by chili-chiu** [comment]
See also [napari-crop plugin](https://www.napari-hub.org/plugins/napari-crop).
