### ISSUE TITLE
Refactor vispy canvas out of qt_viewer.py into own file

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#855]
## 🚀 Feature
After #854 goes in I'd like to refactor the vispy code out of `qt_viewer` into its own file maybe inside the `_vispy` folder or maybe called `QtCanvas` and still in the `_qt` folder.

The goal is to simplify the `QtViewer` code and make the vispy code more separated from the rest of the code.

Curious what @jni @tlambert03 thinks, and how this relates to organization in #823?

**Comment by GenevieveBuckley** [comment]
It looks like this has been addressed by https://github.com/napari/napari/pull/5432 @melonora can you confirm?

**Comment by melonora** [comment]
@GenevieveBuckley I can confirm:)
