### ISSUE TITLE
Generic colormap representation

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#862]
## 🚀 Feature
Right now in our model files we use the vispy colormap object. It would be nice to completely separate our model files from vispy as noted here https://github.com/napari/napari/pull/686#discussion_r363550535 in discussions around serializing the viewer and round-trips.

After #782 (which does a similar refactor but for colors) and #854 (which adds a camera model) both get merged our models will be vispy independent.

Note I'm not sure yet what this representation should be or if vispy colormaps are serializable as they are now, but am making this issue to discuss this.

**Comment by jni** [comment]
I'd love for this contribution to be to vispy or matplotlib, rather than creating yet another colormap representation...

**Comment by sofroniewn** [comment]
Agreed - I think if we use a tuple that is an Nx4 array of colors, an optional length N list of control points, and an interpolation mode string that is either `linear` or `zero` then we can recreate any vispy colormap simply from its API here - http://vispy.org/color.html#vispy.color.Colormap

We can revisit this once #782 lands and when we get further in discussion of #858

**Comment by tlambert03** [comment]
Just want to put a few thoughts here from our conversation yesterday... and hopefully we can do something with this to simplify the work on the models.

I don't totally mind the idea of a new object `(colors, controls, interpolation, name)`, but I am also sensitive to Juan's comment about creating "yet another colormap representation".  If the counter argument is that we don't want our users to need vispy installed to work with a colormap object, then I guess I feel like we have "bigger fish to fry" when it comes to extracting that dependency, and i wonder whether we aren't just making our lives harder by having a simpler `cmap` object that we have still to convert to-and-from internally whenever we need a "real" vispy object.

It sounds like you've got a pretty clear vision on this and feel strongly about it, so I'd be interested to see some examples of what you'd propose, along with your concerns and driving principles... so we can have some more concrete conversations about it.

**Comment by sofroniewn** [comment]
> It sounds like you've got a pretty clear vision on this and feel strongly about it, so I'd be interested to see some examples of what you'd propose, along with your concerns and driving principles... so we can have some more concrete conversations about it.

yup i totally recognize the burden here is on me to provide something concrete. I will give it a go, but it might not be till next week. I'm offline this weekend. I do feel pretty strongly about this one though so want to give it my best shot to convince everyone, recognizing your concerns too!!

**Comment by tlambert03** [comment]
> I'm offline this weekend.

that's fine!  nothing urgent.  look forward to your thoughts
