### ISSUE TITLE
Not a problem, just some positive feedback

### ISSUE THREAD

**Issue by itamarst** [napari/napari#863]
Just FYI, I recommended Napari to someone at a company visualizing large amounts of multi-channel 3-D data, and he says they've found it really useful; "game changing" was the phrase used.

**Comment by sofroniewn** [comment]
Thanks @itamarst, I think the whole @napari/core-devs team really appreciates that you took the time to tells us that, it means a lot!

Do reach out more if you have feature requests or anything we can help you with.

**Comment by royerloic** [comment]
Wow, awesome to hear!

**Comment by cudmore** [comment]
I agree, it is a game changer ...

**Comment by manzt** [comment]
Finally found an excuse to use napari (and a couple of my plugins) for work! Thanks for all the effort and thoughtful design. It's really a joy to use.

**Comment by sofroniewn** [comment]
> Finally found an excuse to use napari (and a couple of my plugins) for work! Thanks for all the effort and thoughtful design. It's really a joy to use.

Love that @manzt you should come by one of the dev meetings again and give us a demo! Would love to see what you're up too :-)
