### ISSUE TITLE
API documentation?

### ISSUE THREAD

**Issue by dstansby** [napari/napari#864]
## 📚 Documentation

I'm currently flicking through the tutorials, which look like a great place to start. I can't seem to find any API documentation anywhere though - I was wondering if it exists and I've missed something, or if it's still a work in progress?

**Comment by sofroniewn** [comment]
It's not so great right now - but here's a link https://napari.github.io/docs/dev/ (I think it's up to date / gets built automatically). We're going to be making a big big push around our API docs / tutorials / website over the next month or so - see #764 - so hopefully we'll get something more useful out to you soon!!

**Comment by dstansby** [comment]
Great! Have you thought about using https://readthedocs.org/ to automatically build/host the docs?

**Comment by kne42** [comment]
@dstansby Yes, we ultimately decided to build the docs ourselves and host it using GitHub pages since RTD has ads and we plan to build a full-fledged website that the docs will factor into (see #764).
