### ISSUE TITLE
Crash when trying the right click contrast limits slider popup 

### ISSUE THREAD

**Issue by ndefrancesco** [napari/napari#865]
Hi every one!
I was really excited with the new features of the last release. Unfortunately, I quickly run into an issue:  when trying the new right click feature on contrast limits, napari throws an error and ignores the click if launched from spyder (using `with napari.gui_qt():`), or throws the error and exits when launched as standalone from the conda prompt.

This is the error that it throws:
```
WARNING: Traceback (most recent call last):
  File "c:\users\nico\anaconda3\lib\site-packages\napari\_qt\layers\qt_image_base_layer.py", line 78, in _clim_mousepress
    self.clim_pop.show_at('top')
  File "c:\users\nico\anaconda3\lib\site-packages\napari\_qt\qt_modal.py", line 72, in show_at
    self.setGeometry(*xy.toTuple(), max(width, 20), max(height, 20))
AttributeError: 'QPoint' object has no attribute 'toTuple'
WARNING:vispy:Traceback (most recent call last):
  File "c:\users\nico\anaconda3\lib\site-packages\napari\_qt\layers\qt_image_base_layer.py", line 78, in _clim_mousepress
    self.clim_pop.show_at('top')
  File "c:\users\nico\anaconda3\lib\site-packages\napari\_qt\qt_modal.py", line 72, in show_at
    self.setGeometry(*xy.toTuple(), max(width, 20), max(height, 20))
AttributeError: 'QPoint' object has no attribute 'toTuple'
```
I am running python 3.7.4 on a conda install in Windows 10, with the latest qt version. Let me know if a can provide any other piece of information useful to debug this.

Thanks, and congatulations for this awesome piece of software!

Nico

**Comment by tlambert03** [comment]
Thanks for the report!  Will take a look ASAP

**Comment by kne42** [comment]
Thanks for the report @ndefrancesco! I can replicate this. It appears that we wrote some code that was incompatible with both PyQt5 and PySide2.
