### ISSUE TITLE
Testing a pip install doesn't work

### ISSUE THREAD

**Issue by jni** [napari/napari#875]
## 🐛 Bug

Running `pytest --pyargs napari` should run the napari test suite, but right now, this fails:

```pytb
 $ pytest --pyargs napari
============================= test session starts ==============================
platform darwin -- Python 3.7.6, pytest-5.3.2, py-1.8.1, pluggy-0.13.1
PySide2 5.14.0 -- Qt runtime 5.14.0 -- Qt compiled 5.14.0
rootdir: /Users/jni
plugins: ordering-0.6, qt-3.3.0, cov-2.8.1
collected 149 items / 4 errors / 145 selected

==================================== ERRORS ====================================
_ ERROR collecting conda/envs/napari-0.2.10/lib/python3.7/site-packages/napari/_qt/tests/test_qt_viewer.py _
ImportError while importing test module '/Users/jni/conda/envs/napari-0.2.10/lib/python3.7/site-packages/napari/_qt/tests/test_qt_viewer.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
conda/envs/napari-0.2.10/lib/python3.7/site-packages/napari/_qt/tests/test_qt_viewer.py:6: in <module>
    from napari.tests.utils import (
E   ModuleNotFoundError: No module named 'napari.tests'
_ ERROR collecting conda/envs/napari-0.2.10/lib/python3.7/site-packages/napari/layers/image/tests/test_big_image_timing.py _
ImportError while importing test module '/Users/jni/conda/envs/napari-0.2.10/lib/python3.7/site-packages/napari/layers/image/tests/test_big_image_timing.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
conda/envs/napari-0.2.10/lib/python3.7/site-packages/napari/layers/image/tests/test_big_image_timing.py:2: in <module>
    import zarr
E   ModuleNotFoundError: No module named 'zarr'
_ ERROR collecting conda/envs/napari-0.2.10/lib/python3.7/site-packages/napari/layers/image/tests/test_image.py _
ImportError while importing test module '/Users/jni/conda/envs/napari-0.2.10/lib/python3.7/site-packages/napari/layers/image/tests/test_image.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
conda/envs/napari-0.2.10/lib/python3.7/site-packages/napari/layers/image/tests/test_image.py:4: in <module>
    import xarray as xr
E   ModuleNotFoundError: No module named 'xarray'
_ ERROR collecting conda/envs/napari-0.2.10/lib/python3.7/site-packages/napari/layers/tests/test_serialize.py _
ImportError while importing test module '/Users/jni/conda/envs/napari-0.2.10/lib/python3.7/site-packages/napari/layers/tests/test_serialize.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
conda/envs/napari-0.2.10/lib/python3.7/site-packages/napari/layers/tests/test_serialize.py:4: in <module>
    from napari.tests.utils import layer_test_data
E   ModuleNotFoundError: No module named 'napari.tests'
```

## To Reproduce

```
conda create -y -n napari-0.2.10 python=3.7
conda activate napari-0.2.10
pip install --pre napari
pip install pytest pytest-cov pytest-ordering pytest-qt pytest-timeout
pytest --pyargs napari
```

Note also, in a related issue, that I think our tests should be able to run without our optional dependencies, zarr and xarray, ie, we should add pytest.skip or pytest.importorskip to the relevant tests (and they should be in their own files if the latter because that function only works for full files).

## Expected behavior

`pytest --pyargs napari` should run our complete test suite using the installed napari module. This makes it easier to test releases, among other things.

## Environment

```
napari: 0.2.10rc0
Platform: Darwin-19.2.0-x86_64-i386-64bit
Python: 3.7.6 (default, Jan  8 2020, 13:42:34)  [Clang 4.0.1 (tags/RELEASE_401/final)]
Qt: 5.14.0
PySide2: 5.14.0
VisPy: 0.6.4
NumPy: 1.18.1
SciPy: 1.4.1
scikit-image: 0.16.2
Dask: 2.9.1
```
 - Please copy and paste the information at napari info option in help menubar here:

 - Any other relevant information:

**Comment by sofroniewn** [comment]
@kne42 @ttung do either of you know why we might be getting the
```python-traceback
E   ModuleNotFoundError: No module named 'napari.tests'
```
error and how to fix? Is something not getting included in the manifest? Do we want to just import all our tests in some private way in the init? Any suggestions welcome

**Comment by ttung** [comment]
This is because `napari.tests` is not a package (no `__init__.py`), and as such, is not bundled into the napari package.

In my development environment, I run `pip install -e .` (or `python setup.py develop`), followed by `pytest --pyargs napari` and that works.

**Comment by ttung** [comment]
I strongly suspect that if you run `pytest --pyargs napari.utils.test`, everything would work, and that is because `napari.utils.test` is an actual package.

**Comment by sofroniewn** [comment]
@kne42 and I chatted about making all our tests available under `napari._tests`, she agreed that was a good approach

**Comment by jni** [comment]
Why? I haven't seen that used in any other scipy-ish packages... I think it's easier for navigation to place tests next to their respective packages.

**Comment by ttung** [comment]
> I think it's easier for navigation to place tests next to their respective packages.

We've done that (in starfish) and I think it's great.

**Comment by sofroniewn** [comment]
> Why? I haven't seen that used in any other scipy-ish packages... I think it's easier for navigation to place tests next to their respective packages.

Ah @jni if that is directed at me there was probably some misunderstanding as I was just trying to repeat something you had suggested in the zulip.

I feel like I may be just getting in the way here and @ttung @jni and @kne42 probably agree with each other on the best approach. My apologies.

It would be great though if one of you could claim the issue and then at least we know we have a plan for who will fix this.

**Comment by jni** [comment]
The only suggestion I remember making is to replace `napari.tests.utils` with `napari.utils._testing`, ie, never cross import from things in `tests` folders.

**Comment by ttung** [comment]
I agree that most tests, for ease of development, should reside alongside the source files, e.g., `napari/layers/tests` should contain the tests for `napari/layers`.

There will likely be some common test infrastructure, and if the installed package is to be testable, it would likely need to reside under `napari/tests/`.

There will also likely need to be a place for integration tests, and that would should also reside under `napari/tests/`.

# Proposal
- keep the tests where they are
- test infrastructure goes in `napari/tests/infra`
- integration tests go in `napari/tests/integration`

The PR I attached (#912) only solves the issue initially flagged and is not intended to match the proposal here.

**Comment by jni** [comment]
@ttung I don't think #912 / making `tests` a package is the right solution, because the testing infrastructure should not be part of the public API of napari. I think if you make `napari.tests` a package, doing `import napari; napari.<TAB>` will autocomplete with our test infrastructure, which is bad. So I still think the scikit-image solution of `_shared/testing.py` or `utils/_testing.py` is the right way. Integration tests can definitely go in `napari/tests/`, but they don't need to be a package.
