### ISSUE TITLE
contrast limits slider increment is static and too large for some images

### ISSUE THREAD

**Issue by berl** [napari/napari#882]
## 🐛 Bug

When I open images with intensities occupying the low end of [0,1] range, the contrast limits slider  increments of 0.01 are too large to be useful.  Like I only get 2-3 positions for some of my recent images.

## To Reproduce

1. open an image with intensity values _val_ s.t.   0 < _val_ < 0.05 
2. adjust the clims
3. frown

## Expected behavior
The user shouldn't see slider increments unless the underlying control is of something with a few discrete values. In this case, I suggest they should scale to ~5% of the range for the small sliders and < 1% for the big sliders.

## Environment
napari==0.2.10+4.gb45a26d

## In other news:

I like the expando-slider and support their further expansion across the landscape of napari!

**Comment by kevinyamauchi** [comment]
Hey @berl! Would being able to expand the slider and manually set the values help (see #837)? The behavior isn't super discoverable, but you can right click on the clim slider to get the expanded UI for setting values, ranges, etc.

**Comment by tlambert03** [comment]
unfortunately, the popup slider probably won't help in this case.  Try for example:
```python
import numpy as np
import napari                                                           

with napari.gui_qt(): 
    napari.view_image(np.random.rand(10,10,10)/20) 
```
I have an idea how this can be solved pretty easily and will submit a PR shortly

**Comment by tlambert03** [comment]
Hi @berl, hopefully #884 fixes this.  But feel free to re-open this if you have any additional issues!
