### ISSUE TITLE
Adding a keybinding should refresh "about keybindings" list

### ISSUE THREAD

**Issue by kevinyamauchi** [napari/napari#889]
## 🐛 Bug

Currently, the "about keybindings" UI does not update when a user adds the keybinding. To force the refresh, the user needs to change which layer is active (e.g., deselect and then select the layer in the layer list UI).

## To Reproduce

1. Run `custom_keybindings.py` example
2. Open the about keybindings UI (alt + cmd + / on Mac)
3. The custom keybindings aren't listed.
4. Close the keybindings UI
5. Deselect the image layer on the layer list and then reselect it.
6. Open the about keybindings UI (alt + cmd + / on Mac)
7. The custom keybindings are now listed.

## Expected behavior
Adding a keybinding should automatically update the about keybindings UI.

## Environment
napari: 0.2.10+6.ga10a88b
Platform: Darwin-16.7.0-x86_64-i386-64bit
Python: 3.6.8 (default, Oct 31 2019, 11:52:31) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
Qt: 5.13.1
PySide2: 5.13.1
VisPy: 0.6.4
NumPy: 1.17.3
SciPy: 1.3.1
scikit-image: 0.16.2
Dask: 2.6.0

GL version: 2.1 INTEL-10.25.24
MAX_TEXTURE_SIZE: 16384

**Comment by adamltyson** [comment]
This would be very useful for me too.

**Comment by liu-ziyang** [comment]
I am not able to reproduce this in the latest version, can someone confirm this is indeed resolved? or am I missing something here?

**Comment by sofroniewn** [comment]
So turns out this got fixed by @tlambert03 in #1014!! So I will close this now, thanks for looking in @ziyangczi
