### ISSUE TITLE
Refactor add_* methods in ViewerModel into mixin class

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#892]
## 🚀 Refactor

I'd like us to consider refactoring the `add_*` methods currently inside the [ViewerModel file](https://github.com/napari/napari/blob/master/napari/components/viewer_model.py#L393-L1001) into a mixin class `AddLayersMixin` in it's own file `add_layers.py`

The reason for this is I currently find the `ViewerModel` file very large and hard to find things in, and often we just have to update either the `add_*` methods or the actual `ViewerModel` stuff and they are a little different in nature. This organization would then mirror the existence of the [`view_layers.py` file](https://github.com/napari/napari/blob/master/napari/view_layers.py) and make things much easier to parse.

Note, that I'd leave the [`add_layer` method](https://github.com/napari/napari/blob/a10a88b2115160211863b47ee7d3012fc8c7beff/napari/components/viewer_model.py#L368) layer inside the main `ViewerModel` file, though I might make it private `_add_layer` as I don't imagine users explicitly making their own layers and adding them in this way.

Aside from that minor change the rest of this would be a completely backwards compatible refactor and only aid our internal organization of the codebase.

What do you think @jni @kne42?

**Comment by jni** [comment]
I defer to @kne42 here, but on first glance it seems like a good idea to me! =)

**Comment by kne42** [comment]
SGTM! One thing you should check out first is building the docs since I'm not sure if Sphinx will document inherited methods (e.g. they may not show up under the `Viewer` class).

WRT renaming `add_layer`, I'm in favor of it, although it may make it more difficult for someone who wants to transfer a layer between viewers, but I think that use case is very uncommon.
