### ISSUE TITLE
dbus_message_get_allow_interactive error after installation 

### ISSUE THREAD

**Issue by erjel** [napari/napari#896]
Hi,

I would like to use napari on a compute cluster for vizualisation purposes (Connection via noVNC browser Interface).

About the system:
conda version: 4.6.14
OS: SUSE Linux Enterprise Server 12 SP4

I installed napari as folllows:
```
conda create -n napari python=3.6
conda activate napari
pip install napari
```

When want to start napari from the terminal
```
$ napari
```
 I get the error message:
```
***${HOME}***/conda-envs/napari/bin/python: relocation error: ***${HOME}***/
conda-envs/napari/lib/python3.6/site-packages/PySide2/Qt/plugins/platforms/../..
/lib/libQt5DBus.so.5: symbol dbus_message_get_allow_interactive_authorization,
 version LIBDBUS_1_3 not defined in file libdbus-1.so.3 with link time reference
```

Have you ever seen this error before?

**Comment by kne42** [comment]
Hi @erjel!

No, I have not seen this before (I'm not a linux user). While you wait for one of our devs who are familiar with linux to respond, could you try installing the following packages?

```
$ apt-get install libgl1-mesa-glx libqt5x11extras5
```

**Comment by erjel** [comment]
Hi @kne42!

Wow, that was a fast reply! Thank you for your quick response.
Unfortunately I have no admin rights on the cluster, so I can not install any new packages.

In order to install other packages than the provided ones, I have to compile them myself in my user space, which I would like to avoid.

**Comment by kne42** [comment]
Ok! Hopefully one of the other devs will be able to resolve this for you :)

**Comment by erjel** [comment]
Hi,

I double checked with the support team of the cluster. They figured out a solution, which worked for me:

```
module load <anaconda environment>
pip install --user napari
```
This installed napari in $HOME

For starting napari I run
```
vglrun ~/.local/bin/napari
```

In order to remove napari:

```
module load <anaconda environment>
pip uninstall napari
```

tested with anaconda 3 (2019.03)

**Comment by tlambert03** [comment]
oh nice!  good to know about [VirtualGL](https://wiki.archlinux.org/index.php/VirtualGL).  we should check to see if that is a suitable workaround for some other remote access problems (like with X11 forwarding).  thanks for reporting back

**Comment by tlambert03** [comment]
just wanted to add that I was also able to get virtualGL working with ssh and X11 forwarding to use napari running remotely on Ubuntu from my mac laptop 🎉.  Will write up a tutorial soonish and post a PR to `napari-tutorials`

**Comment by ttung** [comment]
@tlambert03 does the VNC way work as well?

**Comment by tlambert03** [comment]
I haven't tried with VNC myself, but it states that it works in the docs.  Will write up what I've learned shortly... but in the meantime, here is the gist that I found most helpful:
https://gist.github.com/cyberang3l/422a77a47bdc15a0824d5cca47e64ba2
and docs
https://cdn.rawgit.com/VirtualGL/virtualgl/2.6.3/doc/index.html

**Comment by jni** [comment]
Brilliant stuff!!!
