### ISSUE TITLE
1D, 2D, 3D viewing

### ISSUE THREAD

**Issue by royerloic** [napari/napari#9]
The viewer should supports 3 modes:
1D: Using vispy plotting integrated in the scene graph
2D: current code
3D: Vispy volume renderer

The number of sliders is automatically adapted,
other types of objects (lines, points, etc..) should also be displayed
by simple projection in a straightforward manner.

**Comment by sofroniewn** [comment]
We've made good progress towards 3D rendering recently including #493 where we have merged support for 3D rendering with many of our layer types.

We haven't begun to address 1D rendering yet, but that could be a useful feature so I've made a new issue #516 to explicitly discuss 1D rendering and am closing this one.
