### ISSUE TITLE
adding >1 channel in napari.view_image

### ISSUE THREAD

**Issue by irahorecka** [napari/napari#905]
## ❓ Questions and Help

Hello, I am unsure if this is the right place to ask a question about features in napari, but here it is (if there is a better place to ask questions, I am all ears!):
I am wondering how I can view a 4D image using ```napari.view_image``` with two channels (something similar to ```napari.Viewer().add_image```). Here is what I am doing:

```
from dask_image.imread import imread
import napari

stacks0 = imread(f'{some_directory}\\*ch0*.tif')
stacks1 = imread(f'{some_directory}\\*ch1*.tif')

with napari.gui_qt():
    v = napari.view_image(stacks0,
                      contrast_limits=[90,1500],
                      is_pyramid=False,
                      scale=(3,1,1),
                      translate=(0,-150),
                      ndisplay=3
                     )
    # would love to add another layer (stacks1)
    v.window._qt_window.raise_()
```

Thanks!

**Comment by tlambert03** [comment]
Hi @irahorecka, this is a fine place to ask questions!  We also monitor https://forum.image.sc/ should you choose to post there instead.  Two ways to accomplish something like that:

1) use the `channel_axis` argument to [`view_image`](https://napari.github.io/docs/dev/napari.html#napari.view_layers.view_image):

    ```python
    with napari.gui_qt():
        v = napari.view_image(nd_array, channel_axis=0, ...)
    ```

2) call [`add_image`](https://napari.github.io/docs/dev/napari.components.html?highlight=add_image#napari.components.viewer_model.ViewerModel.add_image) on an existing `Viewer` instance (you also mentioned that, so maybe I'm missing the point of your question... but just in case).  Also, just for clarity in this example, I'm creating the viewer without any initial images (i.e. without using `view_image`):

    ```python
    with napari.gui_qt():
        v = napari.Viewer()
        layer1 = v.add_image(stacks0, name="first channel", ...)
        layer2 = v.add_image(stacks1, name="second channel", ...)
    ```

let me know if that's not what you were asking...

**Comment by irahorecka** [comment]
@tlambert03 Ok! Thank you, the second method worked excellently. For some reason, when I tried it this yesterday, the GUI was reporting 'Not Responding'. Today, it is working well. Thanks always for your quick and thorough response!
