### ISSUE TITLE
napari should not install "benchmarks" as a toplevel package

### ISSUE THREAD

**Issue by anntzer** [napari/napari#910]
## 🐛 Bug

pip-installing napari not only creates a toplevel "napari" importable package, but also a spurious "benchmarks" package.

## To Reproduce

In a clean venv, run `pip install napari`.  Check that "benchmarks" has been installed as a toplevel package with e.g. `python -c 'import benchmarks; print(benchmarks)'`

## Expected behavior

No such package installed.

## Environment

This occurs when installing napari==0.2.10.

**Comment by sofroniewn** [comment]
Thanks for flagging @anntzer, this reminds me of #875 and would be good to fix alongside our other install improvements
