### ISSUE TITLE
to_labels broken in nD_shapes.py

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#914]
>
> Hi Nicolas,
>
> Thanks for building such a great visualization tool for python!
>
> I have been trying to use (napari version `0.2.10+7.g47af135`) the `.to_labels` functionality on an image stack and not getting the behavior I expected. For example, if I add the line `print(np.unique(labels))` at line number 36 of the nD_shapes.py example, expecting this to reflect the labels of all unique shapes, the output that I get is `array([0])`, indicating no labels present.
>
> If I change line 34 to read:
`labels = layer.to_labels(labels_shape=(128, 128))`
I get an index for all 128 shapes, but of course they are now compressed into one image plane, but if line 34 reads:
`labels = layer.to_labels()`
I again get only zeros (but with shape `(127,128,128)`).
>
> It does seem that `to_labels` is meant to be compatible with n-dimensional images, am I expecting the wrong behavior, or otherwise misusing this functionality?
>
_Originally posted by @miketaormina in https://github.com/napari/napari-tutorials/issues/46#issuecomment-578882563_

**Comment by sofroniewn** [comment]
Sounds like a bug, I can look into it

**Comment by sofroniewn** [comment]
@kevinyamauchi if you have time and are interested can you take this one too? Will force you into the Shapes layer a bit :-) :-)

**Comment by kevinyamauchi** [comment]
No problem. On it!

**Comment by MalteMederacke** [comment]
Hi, 

Thanks for developing and maintaining such a nice software. 

Is my perception correct, that I cannot use the shape layer with shape_type = 'path' shapes to create a mask/label? I have a bunch of paths that I want to transform into a label, but the shapes.to_labels() throws either an error (if labels_shape = none) or gives a layer with shape (n_labels, labels_shape[0], labels_shape[1], labels_shape[2]) so I get a 4D image from a 3D shape layer, if I define labels_shape. So, as far as I can see only the endpoints of the paths are stored in the shape layer, so I should think about implementing something like the Bresenham algorithm in 3D? My implementation is currently to slow...


Any thoughts are appreciated! 

Best,

Malte

**Comment by psobolewskiPhD** [comment]
@MalteMederacke I can't get any 3D shapes to work using the GUI at least, so it seems like there may be an issue here. I also don't full understand your use case or the error. Could you open a new issue with a better description: maybe a screenshot, a traceback, and your `napari --info` to help us run down this problem? Thanks! 😊

**Comment by MalteMederacke** [comment]
@psobolewskiPhD 
Hi thanks for coming back to me! Done it at 

https://github.com/napari/napari/issues/5349

Thank you!
