### ISSUE TITLE
napari.gui_qt() 'play' button stalls and eventually corrupts program

### ISSUE THREAD

**Issue by irahorecka** [napari/napari#919]
I am having issues with the play button in ```napari.gui_qt()```.

When I open the ```napari.Viewer(ndisplay=3)``` with two overlaid channels, I can slide around the various image slices with minor latency. If I press the play button, a movie of my images will start. However, around image 6, the application will freeze and loop over images 1 - 6 again. This cycle happens 3 - 4 times before the application comes to a complete stop (i.e. Not Responding)

Here is the .ipynb code below:
```
%gui qt5

import warnings
warnings.filterwarnings('ignore')
import napari
from dask_image.imread import imread

stacks0 = imread(f'{tif_directory}\\*ch0*.tif')
stacks1 = imread(f'{tif_directory}\\*ch1*.tif')

with napari.gui_qt():
    viewer = napari.Viewer(ndisplay=3)
    layer0 = viewer.add_image(stacks0, is_pyramid=False)
    layer1 = viewer.add_image(stacks1, is_pyramid=False)
viewer.window._qt_window.raise_()
```

Also, when viewing the client dashboard from dask.distributed, I realized that [one of the eight tasks (#3)](https://i.imgur.com/e1rVodq.png) was bearing almost all of the CPU load when playing the movie (for lack of a better term). If you have insight on this, could you please elaborate on this phenomenon? Thank you!

**Comment by sofroniewn** [comment]
Hi @irahorecka, I'm sorry you're running into these problems, my guess is that we're triggering too many calls to dask, and although I think @tlambert03 put some machinery specifically into the play functionality to try and drop repeated calls we're not doing enough here.

We have some improvements planned around big data applications in #881 that I think will improve this, see for example dropping repeated calls actually at the level of the updating of the image, but they won't happen overnight. 

I'm not sure about why the one task was bearing all the load - maybe @tlambert03 can weigh in on that too.

I'll also add then when launching from a notebook you don't actually need to use the `with napari.gui_qt():` syntax and that it might lead to less desirable behavior. I want to flag for @napari/core-devs that we've seen this quite a bit lately so we probably need to improve our readme / tutorials to make that more clear. I'm curious @irahorecka which part of the documentation lead you to that.

**Comment by sofroniewn** [comment]
Ah I just realized @irahorecka you also raised #893 (which is where I saw the - `with napari.gui_qt()` syntax in the notebook) I'm curious if the proposed solutions there helped you too. Feel free to weigh in again directly on that issue if you can. Thanks!!

**Comment by irahorecka** [comment]
Hello @sofroniewn, thank you for the response. I omitted the ```with napari.gui_qt()``` syntax, but I still run into the same freezing issue. 
Nevertheless, I looked into the README and it seems like the syntax should only be used in script calls! I believe I was looking into some of @tlambert03 's notebooks for napari tricks and tips and kept the ```with napari.gui_qt()``` syntax...

**Comment by sofroniewn** [comment]
Note also discussion in https://github.com/napari/napari/issues/845#issuecomment-575286085 about canceling dask calls in the context of napari

**Comment by tlambert03** [comment]
hi @irahorecka, are you still experiencing this issue with recent versions of napari?

**Comment by irahorecka** [comment]
Hello, I have not tried the new version of napari, but because I have not experienced this since, I will close this issue
