### ISSUE TITLE
Shapes shape, range, and extent

### ISSUE THREAD

**Issue by kevinyamauchi** [napari/napari#922]
## ❓ Questions and Help

Hello everyone. While working on #920, I realized that I don't really understand how we use extent, range, and shape in the context of the dims, but I may have found a bug. In short, the shape calculation for the `Shapes` layer seems off by one.

## To Reproduce

For example, if I am making a `Shapes` layer with the following data (1 square each on z planes 0, 1, and 2):
```python
data = [
    [
        [0, 100, 100],
        [0, 100, 200],
        [0, 200, 200],
        [0, 200, 100]
    ],
    [
        [1, 125, 125],
        [1, 125, 175],
        [1, 175, 175],
        [1, 175, 125]
    ],
    [
        [2, 100, 100],
        [2, 100, 200],
        [2, 200, 200],
        [2, 200, 100]
    ],
]
layer = Shapes(np.array(data), shape_type='polygon')
```
I get the following:

```python
>>> layer.shape
(2, 100, 100)

>>> layer._get_range()
((0.0, 2.0, 1), (100.0, 200.0, 1), (100.0, 200.0, 1))

>>> layer._get_extent()
((0.0, 2.0, 1), (100.0, 200.0, 1), (100.0, 200.0, 1))
```
Further, when instantiating a viewer with just shapes (`napari.view_shapes(data, shape_type='polygon`), the z dim slider only has positions z=0 and z=1.

## Expected behavior
I am not sure what to expect for the range and extent, but I would have expected:
```python
>>> layer.shape
(3, 101, 101)
```
since there are 3 z slices and the squares are 101 pixels wide in z slices 0 and 1 (i.e., same as how numpy array shape works). I took a look at the `Image` layer and it looks like the shape is based on the shape of the image numpy array, which is consistent with my expectation.

## Environment
napari: 0.2.10+19.gfeb879f
Platform: Darwin-16.7.0-x86_64-i386-64bit
Python: 3.6.8 (default, Oct 31 2019, 11:52:31) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
Qt: 5.13.1
PySide2: 5.13.1
VisPy: 0.6.4
NumPy: 1.17.3
SciPy: 1.3.1
scikit-image: 0.16.2
Dask: 2.6.0

GL version: 2.1 INTEL-10.25.24
MAX_TEXTURE_SIZE: 16384

**Comment by kevinyamauchi** [comment]
@sofroniewn , would you mind giving a rundown on how shape, range, and extent should work for the `Shapes`layer?

**Comment by sofroniewn** [comment]
The z-shape definitely seems off. I will look into this more and write a longer response, but curious if the behaviour is the same for points? it might be simpler to agree on what we want for points and then make sure shapes is doing the same thing (which I think it should). I do remember this being a little tricky, especially when you have values like `10.3` around and you have to decide if you will round or not or `+1` or not etc. I wouldn't be surprised if though if the current behavior can be improved

**Comment by kevinyamauchi** [comment]
Thanks for the quick reply, @sofroniewn . I just took a look and the behavior is the same for `Points`. I agree that this is a tricky one. If we don't already have them, I think it would be good to start with definitions of `layer.shape` and the outputs of `layer._get_range()` and `layer._get_range()`. I definitely need to do some more thinking...maybe we can discuss on Thursday?

**Comment by sofroniewn** [comment]
@kevinyamauchi can you look into this again now that #1360 and #1539 have merged. I'd actually like us to remove the `layer.shape` property, but we want `layer._extent_data` to be accurate

**Comment by kevinyamauchi** [comment]
Will do. I'll take a look this weekend!

**Comment by kevinyamauchi** [comment]
@sofroniewn , I've been playing around with the shapes/points/tracks and I think there is some inconsistency with the `layer._extent_data` property. I've made a new issue since it pertains to multiple layers: #1686

Feel free to close this one if you think we should just move the conversation entirely over there.

**Comment by sofroniewn** [comment]
> @sofroniewn , I've been playing around with the shapes/points/tracks and I think there is some inconsistency with the layer._extent_data property. I've made a new issue since it pertains to multiple layers: #1686
>
> Feel free to close this one if you think we should just move the conversation entirely over there.

Ok, yeah, thanks for flagging. I will close this now and we can move the convo over there!!
