### ISSUE TITLE
Add reversed colormap(s)

### ISSUE THREAD

**Issue by GenevieveBuckley** [napari/napari#926]
## 🚀 Feature

I would like us to add some reversed colormaps to the list currently available in napari.

## Motivation

It's frustrating trying to use napari to look at image volumes with a high intensity background. When you try to look at the 3D volumes with the current colormap options, all you see is the blank background and you can't get a good look at your sample.

Examples of this type of image data include: histology slices where the background is white, and x-ray images since the sample absorbs photons. 

## Pitch

1. Add support for reversed versions of `gray` & `gray_trans`
2. (optional) discuss whether we need to add more non-gray reversed colormaps. This could be:
    * reversed versions of the primary/secondary colormaps (red, green blue, yellow, magenta, cyan).
    * suuport for the existing matplotlib reversed colormaps, see https://github.com/napari/napari/issues/899#issuecomment-580023370

## Alternatives

**Alternative 1:** Use a reversed colormap from matplotlib. All the matplotlib colormaps have a twin that is reversed if you add `_r` to the end of its name. Unfortunately napari doesn't support all matplotlib colormaps, so you have to use [the trick Juan suggests here](https://github.com/napari/napari/issues/899#issuecomment-577681428) *every time* you launch napari.

**Alternative 2:** Invert the image data with something like `skimage.util.invert(img)`. This is what I've been doing, but I don't like it because...
* it's fiddly to switch back to ipython and fiddle with code before I've even seen whether this image volume is one I want to keep working with, and
* I'm worried I'll forget that I've altered the pixel data content and it'll be a hassle later on to do quantative analysis.

**Alternative 3:** Change the napari canvas background from black to white. This won't be an effective solution once you have more than one image volume, and one looks better on black and another looks better on a white background.

**Comment by sofroniewn** [comment]
> Alternative 1: Use a reversed colormap from matplotlib. 

I think this makes lots of sense, as noted in #899 I think we just want to make sure the drop down menu doesn't become overwhelming and #268 could be an option

> Alternative 2: Invert the image data

Agreed - I don't like this option because it changes the data, and I don't think napari should be forcing people to do that to achieve the visualization they want

> Alternative 3: Change the napari canvas background from black to white.

This can be done in our themes / palettes right now, but it's not super easy - we could make this more easy if you wanted

**Comment by sofroniewn** [comment]
Now that we have our own colormap object (see #1523) we could add a simple flag `reverse` to reverse the colormap. Curious what people think?

**Comment by psobolewskiPhD** [comment]
@GenevieveBuckley Not sure you saw, but https://github.com/napari/napari/pull/4875 added minimum blending as well as 5 inverted colormaps from @cleterrier
I_Forest and I_Bordeaux
Inverted versions of OPF Purple and OPF Orange
Plus a Blue, that's sort of in-between the BOP Blue and pure Blue. It complements Bordeaux.

@sofroniewn programmatically generating such colormaps could work for sure. It just involves changing the start of the colormap from [0, 0, 0] to [1, 1, 1] — the end point stays the same. Not all look good when inverted though. Also napari has a number of colormaps that are not monotonic, so then this doesn't make sense—twilight, magma.
Here's how inverted Bordeaux is defined (I Bordeaux):
`I_Bordeaux = [[1, 1, 1], [204 / 255, 0, 51 / 255]]`
To get conventional Bordeaux you'd just use:
`Bordeaux = [[0, 0, 0], [204 / 255, 0, 51 / 255]]`
(but it might not be contrasty enough on black...)

**Comment by GenevieveBuckley** [comment]
The new `gray_r` colormap partially addresses this issue. 
Also, you can now do `layer.colormap = 'cubehelix_r'` for whichever matplotlib colormap you want.

FYI, the `I_Blue`, `I_Bordeaux`, `I_Forest`, `I_Orange` and `I_Purple` colormaps do not fix the problem described in this issue (especially for 3D viewing data).
