### ISSUE TITLE
Figure out best printing format for status bar

### ISSUE THREAD

**Issue by jni** [napari/napari#93]
Over in #90, @sofroniewn, @kne42, and I were discussing the formatting of numbers in the Napari status bar. No format string produces satisfactory results for all input types, so we need to write a function that picks the right format string for the right situation. See https://github.com/Napari/napari-gui/pull/90#discussion_r247782298

**Comment by sofroniewn** [comment]
As noted by @royerloic in #372 - when changing the dims sliders 

> The status bar should display something like:
> 
> [3, 5, :, :], layer_name, value ...
>
> where 3 or 5 are changing depending on the dim slider being moved.
the ':' are there because we are not hovering over a pixel, so in some sense
we have nothing relevant to give there.

**Comment by sofroniewn** [comment]
With #485 this has been dramatically improved. We now have a consolidated all our status formatting to one function inside the utils folder that can be tested / improved independently.
