### ISSUE TITLE
Adding points with properties / empty properties

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#930]
## 🐛 Bug

@kevinyamauchi I'm trying to create a basic demo where I load an empty points layer with a properties dict with an empty list - say named "class", which I can then populate as I add points - leveraging a combination of custom keybindings / mouse functions. The overall goal is to create a simple demo of how to annotate a movie for input into a tracking program like DeepLabCut. The reason I'm doing this is to try and learn about whether our Points / keybindings / mouse functions APIs are enabling real world use cases like that. I'm running into a couple problems though.

First is around initializing the empty points layer:

<details>

```python
"""
Displays empty points with properties
"""

import napari
import numpy as np


with napari.gui_qt():
    # create an empty viewer
    viewer = napari.Viewer()
    viewer.add_image(np.random.random((5, 400, 400)))

    # create properties for each point
    properties = {
        'class': np.array([]),
    }

    # define the color cycle for the face_color annotation
    face_color_cycle = ['red', 'blue', 'green', 'cyan', 'magenta', 'yellow']

    points_layer = viewer.add_points(
        properties=properties,
        size=10,
        edge_width=1,
        edge_color='white',
        face_color='class',
        face_color_cycle=face_color_cycle,
        name='points'
    )
```

```python-traceback
(base) czirwc1macos2701:image-demos nsofroniew$ python test-examples/points_properties_empty.py
Traceback (most recent call last):
  File "test-examples/points_properties_empty.py", line 29, in <module>
    name='points'
  File "/Users/nsofroniew/GitHub/napari/napari/components/add_layers_mixin.py", line 366, in add_points
    visible=visible,
  File "/Users/nsofroniew/GitHub/napari/napari/layers/points/points.py", line 336, in __init__
    self._current_face_color = self.face_color[-1]
IndexError: index -1 is out of bounds for axis 0 with size 0
```

The expected behavior is to be able to instantiate the layer.

</details>

The second error is around adding points when using properties

<details>

```python
"""
Displays points with properties
"""

import napari
import numpy as np


with napari.gui_qt():
    # create an empty viewer
    viewer = napari.Viewer()
    viewer.add_image(np.random.random((5, 400, 400)))

    points = np.array([[100, 100], [200, 200], [333, 111]])

    # create properties for each point
    properties = {
        'class': np.array([1, 2, 3]),
    }

    # define the color cycle for the face_color annotation
    face_color_cycle = ['red', 'blue', 'green', 'cyan', 'magenta', 'yellow']

    points_layer = viewer.add_points(
        points,
        properties=properties,
        size=10,
        edge_width=1,
        edge_color='white',
        face_color='class',
        face_color_cycle=face_color_cycle,
        name='points'
    )
```

If you now enter "add" mode and start clicking I then get the following error:

```python-traceback
Traceback (most recent call last):
  File "/Users/nsofroniew/GitHub/vispy/vispy/app/backends/_qt.py", line 447, in mousePressEvent
    modifiers=self._modifiers(ev),
  File "/Users/nsofroniew/GitHub/vispy/vispy/app/base.py", line 181, in _vispy_mouse_press
    ev = self._vispy_canvas.events.mouse_press(**kwargs)
  File "/Users/nsofroniew/GitHub/vispy/vispy/util/event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "/Users/nsofroniew/GitHub/vispy/vispy/util/event.py", line 475, in _invoke_callback
    self, cb_event=(cb, event))
  File "/Users/nsofroniew/GitHub/vispy/vispy/util/event.py", line 471, in _invoke_callback
    cb(event)
  File "/Users/nsofroniew/GitHub/napari/napari/_qt/qt_viewer.py", line 338, in on_mouse_press
    self.layer_to_visual[layer].on_mouse_press(event)
  File "/Users/nsofroniew/GitHub/napari/napari/_vispy/vispy_base_layer.py", line 189, in on_mouse_press
    self.layer.on_mouse_press(event)
  File "/Users/nsofroniew/GitHub/napari/napari/layers/points/points.py", line 1513, in on_mouse_press
    self.add(self.coordinates)
  File "/Users/nsofroniew/GitHub/napari/napari/layers/points/points.py", line 1334, in add
    self.data = np.append(self.data, [coord], axis=0)
  File "/Users/nsofroniew/GitHub/napari/napari/layers/points/points.py", line 427, in data
    ][0]
IndexError: invalid index to scalar variable.
```

Expected behaviour - I should be able to add points, and the properties should just extend with default values (say last one, or `None`). I havn't tried removing points but that should also work

</details>

## Environment

```
napari: 0.2.11
Platform: Darwin-19.3.0-x86_64-i386-64bit
Python: 3.7.4 (default, Aug 13 2019, 15:17:50)  [Clang 4.0.1 (tags/RELEASE_401/final)]
Qt: 5.13.2
PySide2: 5.13.2
VisPy: 0.6.5.dev2+g9e0822db
NumPy: 1.18.1
SciPy: 1.3.1
scikit-image: 0.16.2
Dask: 2.5.2

GL version:  2.1 INTEL-14.4.23
MAX_TEXTURE_SIZE: 16384
```

**Comment by sofroniewn** [comment]
Looks like the problematic line is `colors = self.face_color[self._indices_view]`, this maybe much easier to do after the new `_view` approach to properties. Note the issue is that we don't want all the face colors, we only want at most 1024 corresponding to the points that we randomly selected

**Comment by kevinyamauchi** [comment]
Dang it! Thanks for flagging these, @sofroniewn . 

I hadn't made a test for the use case where the properties is initiated with keys and empty arrays (as oppose to an empty dict), but it makes sense. For an empty points layer with properties, what do you think default `Points.current_properties` value be? Maybe `''`?

For the point adding bug, I've pushed a fix it and added a test (#933 ). In short, there was a bug in how I was initializing `Points.current_properties`, so adding points worked when selecting a point first (to update `Points.current_properties`), but did not work when just adding points straight away without selecting one first. I added a test to cover that case.

**Comment by sofroniewn** [comment]
Thanks for jumping on fixes so quickly. I'll do some thorough testing.

> default `Points.current_properties' value

I'm not sure - maybe the empty string, or None, or np.NaN? Curious what @jni thinks

**Comment by sofroniewn** [comment]
>  I'm trying to create a basic demo where I load an empty points layer with a properties dict with an empty list - say named "class", which I can then populate as I add points - leveraging a combination of custom keybindings / mouse functions. The overall goal is to create a simple demo of how to annotate a movie for input into a tracking program like DeepLabCut.

Separate to the bug fixes, I'd love it if we could make a nice gist with this working well. Do you think you can take a stab at that too? Could be a nice "applications" tutorial.

**Comment by kevinyamauchi** [comment]
> Separate to the bug fixes, I'd love it if we could make a nice gist with this working well. Do you think you can take a stab at that too? Could be a nice "applications" tutorial.

No problem! I will be traveling over the next week, so I will have less time, but I can work on that when I get back!

**Comment by sofroniewn** [comment]
> I totally agree. My plan was to get all of the features into the model and then figure out the best way to interact with them via the GUI. I was thinking along the same lines as you and I am definitely open to suggestions!

@kevinyamauchi we can also wait till this is done, as by then it might become trivial. Sounds like we are on the same page :-)

**Comment by kevinyamauchi** [comment]
@sofroniewn , I've started working on this (finally) and I am a little stuck on what should happen when the user attempts to add a point to a layer initialized without any data where a display property (e.g., `edge_color`) is set as a function of one of the properties.

That is, what should happen in this case:
```python
points_layer = viewer.add_points(
    properties={'label': np.empty(0)},
    edge_color='label',
)

points_layer.add([10, 10])
```
Should to `edge_color_mode` switch to direct and then set the edge color as the default? Should it not add a point and issue a warning? What are your thoughts?

**Comment by sofroniewn** [comment]
Hmm, I think you definitely want to be able to add points, but it's unclear what a default value should be - that's the problem right? Can you make in None? What will that do? I guess right now we don't have a nice way for people to change these properties from the GUI. Switching to direct mode seems less desirable as people will be using properties to avoid that. What are your thoughts?

**Comment by kevinyamauchi** [comment]
I agree that the ideal thing is to be able to add points. However, when the edge color is mapped to the `label` property, I am not sure how to assign the color. I think it's tricky because the model doesn't know what the valid `label` values are, so I don't know what a sensible default would be.

Perhaps we could somehow attach the valid values to the empty property array (I think pandas might do this with their categorical datatype). Alternatively, we could accept a default property values as an input argument. What do you think?

**Comment by sofroniewn** [comment]
> Perhaps we could somehow attach the valid values to the empty property array (I think pandas might do this with their categorical datatype). Alternatively, we could accept a default property values as an input argument. What do you think?

If possible this would be nice

**Comment by sofroniewn** [comment]
> I guess right now we don't have a nice way for people to change these properties from the GUI.

Do you have plans / ideas for this? It could help influence how we think about this. I think now that we have properties it might make sense to have some GUI for this, could be autogenerated. Maybe @tlambert03 has ideas?

**Comment by kevinyamauchi** [comment]
> Perhaps we could somehow attach the valid values to the empty property array (I think pandas might do this with their categorical datatype). Alternatively, we could accept a default property values as an input argument. What do you think?
>> If possible this would be nice

I think accepting a default property as an input argument is straightforward, but it does add to the increasingly large number API. That being said, both matplotlib and seaborn seem to have gone the route of lots of kwargs with sensible defaults, so maybe it's the best way to balance customizability with usability.

I will look into the pandas categorical dtype. Even if it's possible, we would have to take on pandas as a dependency and I'm not sure this is sufficient rationale. Also, I'm not sure if it would be compatible with other dataframes that would be nice to support in the future (e.g., dask DataFrame, cuDF).

> Do you have plans / ideas for this? It could help influence how we think about this. I think now that we have properties it might make sense to have some GUI for this, could be autogenerated. Maybe @tlambert03 has ideas?

My thought when adding the properties was that it would be nice to have a selector for face color and edge color that sets their respective color modes. We could then change the UI elements of the edge color and face color UI elements depending on the color mode:

- `ColorMode.DIRECT` would have the color drop down menu we currently have (eventually a color picker)
- `ColorMode.CYCLE` would have a dropdown to select the property and a dropdown to select the value from the existing values in the property. I thought it would be too much to include a way to add or modify an existing value.
- `ColorMode.MAP` would have a dropdown to select the property.

**Comment by sofroniewn** [comment]
> I think accepting a default property as an input argument is straightforward, but it does add to the increasingly large number API.

I prefer this option. I am less excited about "the pandas categorical dtype" for reasons you mention above.

> My thought when adding the properties was that it would be nice to have a selector for face color and edge color that sets their respective color modes.

Agreed

> I thought it would be too much to include a way to add or modify an existing value.

If there was a separate way to provide / edit a list of default values that makes even more sense. Maybe figuring that bit out is top priority

**Comment by kevinyamauchi** [comment]
Based on our conversation at the sync last night, I will be implementing the following:
- Introduce a property to store user-provided property values  (`Points.default_property_values` or `Points.preset_property_values` or something else?). The user provided values can serve as default values and also provide a list of valid values for each property. The property will store a dictionary where the keys match the keys in `Points.properties` and the values are numpy arrays with the user-provided values.
- Initially, we will use the property to have fall back values if a user adds a point to an empty layer without setting `layer.current_properties`.
- Eventually, we can use the property to look up the current properties and values to add/edit them via the GUI. I think the total valid list should be the union of the values in `Points.properties` and `Points.default_property_values` (or whatever we call it) rather than using `Points.default_property_values` as a registry. I think synchronizing `Points.properties` and `Points.default_property_values` would be a bit thorny (e.g., what happens to the elements in `Points.properties` if a particular in-use value is deleted from `Points.default_property_values`?).

Does this seem right, @sofroniewn ?
