### ISSUE TITLE
Log-scale slider

### ISSUE THREAD

**Issue by jni** [napari/napari#938]
## 🚀 Feature

In tutorials about e.g. image segmentation with scikit-image, I often advise students to first tune parameters (such as compactness for watershed or SLIC, or alpha and beta for active contours) on a log scale, before refining further if at all needed. For many plugins, this would be the right type of slider for floating point arguments by default.

Therefore, it would probably be good if we provided such a slider for developers to use.

**Comment by tlambert03** [comment]
In case it's useful to start with, I implemented something of a cheater log slider in the histogram widget here:
https://github.com/napari/napari/blob/0cbb95dedf71232a9841b12f125920496b0d56a7/napari/_qt/qt_histogram.py#L64-L75

would be great to have our own class though.

**Comment by GenevieveBuckley** [comment]
Would something like this work? Based on the DoubleSlider class in magicgui:

`napari/qt/qt_log_slider.py`
```python
"""A Slider with a natural logarithmic scale."""
from qtpy.QtCore import Qt
from qtpy.QtWidgets import QSlider


class QLogSlider(QSlider):
    """A Slider Widget with a natural logarithmic scale."""

    PRECISION = 1000

    def __init__(self, parent=None):
        super().__init__(Qt.Horizontal, parent=parent)
        self.setMaximum(10)

    def value(self):
        """Get the natural log slider value as a float."""
        return np.log(super().value() / self.PRECISION)

    def setValue(self, value):
        """Set integer slier position from float ``value``."""
        super().setValue(np.exp(value) * self.PRECISION)

    def setMaximum(self, value):
        """Set maximum position of slider in float units."""
        super().setMaximum(np.exp(value) * self.PRECISION)
```

**Comment by GenevieveBuckley** [comment]
We've made a few tweaks to the sketch above, and merged a QLogSlider class into the magicgui codebase. If we want this in napari as well, and figure out where it should live (where it should live is not clear to me), then it should be possible to reuse the code from here: https://github.com/napari/magicgui/pull/38/files

**Comment by dstansby** [comment]
Can this be closed now there's a log slider available in magicgui? As far as I can tell, this isn't a proposal to *use* it anywhere in napari, just to have it available for plugin developers.
