### ISSUE TITLE
to_svg() layer method does not work for RGB image skimage.data.astronaut()

### ISSUE THREAD

**Issue by GenevieveBuckley** [napari/napari#940]
## To Reproduce

```python
In [1]: import napari                                                              

In [2]: from skimage.data import astronaut                                         

In [3]: viewer = napari.Viewer()                                                   

In [4]: viewer.add_image(astronaut())                                              
Out[4]: <Image layer 'Image' at 0x7fd9e38b54d0>

In [5]: viewer.layers[0].to_svg('test-file.svg')   
```
```python-traceback                                
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-98042762781f> in <module>
----> 1 viewer.layers[0].to_svg('test-file.svg')

~/Documents/GitHub/napari/napari/layers/base/base.py in to_svg(self, file, canvas_shape)
    700         xml_transform = Element('g', transform=transform)
    701 
--> 702         xml_list = self.to_xml_list()
    703         for x in xml_list:
    704             xml_transform.append(x)

~/Documents/GitHub/napari/napari/layers/image/image.py in to_xml_list(self)
    617         mapped_image = self.colormap[1][image.ravel()]
    618         mapped_image = mapped_image.RGBA.reshape(image.shape + (4,))
--> 619         image_str = imwrite('<bytes>', mapped_image, format='png')
    620         image_str = "data:image/png;base64," + str(b64encode(image_str))[2:-1]
    621         props = {'xlink:href': image_str}

~/anaconda3/envs/napari-dev/lib/python3.7/site-packages/imageio/core/functions.py in imwrite(uri, im, format, **kwargs)
    297         pass
    298     else:
--> 299         raise ValueError("Image must be 2D (grayscale, RGB, or RGBA).")
    300 
    301     # Get writer and write first

ValueError: Image must be 2D (grayscale, RGB, or RGBA).
```

Note that `viewer.layers[0].rgb` returns True, so it's probably lost the idea of the image being RGB when it's passed to imageio. I bet the napari and imageio models for RGB data don't quite align or translate well between one another.

The example code above works well if you use the scikit-image "camera" example image (a 2D grayscale image).

## Expected behavior
I expected the svg file `test-filename.svg`  to be written to disk.

## Environment

napari: 0.2.3+128.g3e5dfba
Platform: Linux-5.0.0-37-generic-x86_64-with-debian-buster-sid
Python: 3.7.4 (default, Aug 13 2019, 20:35:49) [GCC 7.3.0]
Qt: 5.14.0
PySide2: 5.14.0
VisPy: 0.6.4
NumPy: 1.18.1
SciPy: 1.4.0.dev0+1566e8e
scikit-image: 0.16.2
Dask: 2.10.0

GL version: 4.6.0 NVIDIA 435.21
MAX_TEXTURE_SIZE: 32768

**Comment by sofroniewn** [comment]
> so it's probably lost the idea of the image being RGB when it's passed to imageio. I bet the napari and imageio models for RGB data don't quite align or translate well between one another.

It's probably something like that. I don't think it should be too hard to fix. Thanks for flagging

**Comment by sofroniewn** [comment]
With the creation of the new https://github.com/napari/napari-svg package and the merging of #1171 this has now been fixed - i.e. if you run `examples/add_image.py` which loads the astronaut and then `layer.save('my_file.svg')` the code works. I'm closing now and and future issues should be raised on the `napari-svg` plugin repo
