### ISSUE TITLE
Add names to vispy colormaps

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#95]
## 🚀 Feature

As described in #89 currently the vispy colormaps do not have a name field which is the string by which they can be created. It would be useful to have that name field so that we can reference it in the dropdown menu when the colormap is changed in the notebook or on launch.

We could either add this directly in vispy or make a wrapper ourselves. The former is probably slightly nicer, as acknowledged by @jni

**Comment by kne42** [comment]
Is this really useful outside of our specific use case? Why do you think that this is the best option over passing a name with the colormap or just calling it `custom`?

**Comment by sofroniewn** [comment]
I guess I just find it strange that in vispy you can do something like

```python
cmap = color.get_colormap('blues')
```

and then from `cmap` have no way of knowing that it corresponds to the string `blues`. Adding a `name` property would allow this in general and solve our specific use case.

**Comment by jni** [comment]
I'm going to go with the wrapper because this is something that we can do ourselves now. I suspect that making the change in vispy will take approximately forever.
