### ISSUE TITLE
Add 3D vector coordinates object to the viewer

### ISSUE THREAD

**Issue by HagaiHargil** [napari/napari#952]
## 🚀 Feature
It would be nice if the viewer could also show the current direction of each axis via a simple 3D vector triplet which can be found in many 3D viewing applications, like Blender ([example](https://en.wikibooks.org/wiki/Blender_3D:_Noob_to_Pro/Coordinate_Spaces_in_Blender)).

## Motivation

Having the current axis directions spelled out in the viewer may help with the general orientation of the object and the viewer. In addition, if the axes are labeled, the name of each dimension will also be shown on the tips of these arrows, which can be quite helpful. Additionally, if and when napari will have support for global and relative coordinates, these arrows will also help determining the viewer's perspective as well.

## Alternatives

napari's awesome regardless of this little pointing rotating object :)

**Comment by sofroniewn** [comment]
I'm fine with this as long as it is easy to turn on and off. Vispy has some machinery to make this super easy. I'd prefer to wait though until #885 goes in and we start thinking about scale bars and how we are going to overlay them. I see these visuals as more belonging to the viewer than any one particular layer, and we don't quite have that abstraction yet. It may come with some plans in #772
