### ISSUE TITLE
Documentation is AWOL

### ISSUE THREAD

**Issue by stefanv** [napari/napari#959]
https://napari.org/docs/ -> 404

(same for https://napari.org/napari-tutorials/)

**Comment by kne42** [comment]
Thanks for the report @stefanv!

> https://napari.org/docs/ -> 404

It seems that the following line properly copies the contents of `html` directly to the current folder on MacOS but not on linux (it shows up in https://napari.org/docs/html) 😒
 
https://github.com/napari/napari/blob/3950dba6ced8a7f477877149df1d920f3502a647/.cirrus.yml#L255

> (same for https://napari.org/napari-tutorials/)

This has been renamed to https://napari.org/tutorials. Do you think I should put in a redirect?

**Comment by jni** [comment]
@kne42 I guess the [homepage](https://napari.org/) needs updating also, as it links to both those addresses. Not sure exactly where it lives.
