### ISSUE TITLE
cmap vs colormap on a layer

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#96]
## ❓ Questions and Help

As initially posed in #89 - both `cmap` and `colormap` exist as properties on a layer, but have slightly different setters. It's not clear to me what the difference is or why we need both. If possible it would be nice to eliminate one. Maybe @kne42 has the answer?

**Comment by kne42** [comment]
`colormap` is simply an alias to `cmap` – since I'd assume that this is a pretty standard abbreviation we can just get rid of `colormap`

**Comment by sofroniewn** [comment]
i'm fine to get rid of `colormap` and just have `cmap`, can you make a PR @kne42?

**Comment by kne42** [comment]
Do we also want to rename `colormaps` to `cmaps` to be more consistent or is that fine?

**Comment by sofroniewn** [comment]
I would rename too
