### ISSUE TITLE
[0.2.11 regression] Adding more than 1024 3D points raises a ValueError

### ISSUE THREAD

**Issue by HagaiHargil** [napari/napari#966]
## 🐛 Bug

When trying to add more than 1024 points to the viewer napari returns an error, claiming that we gave it a 4D point array.

## To Reproduce

From a script or the integrated terminal:
```python
import numpy as np

num_points = 1025  # 1024 works
points = np.random.random((num_points, 3))
viewer.add_points(points)

# ValueError: shape mismatch: value array of shape (1025,4) could not be broadcast to indexing result of shape (1024,4)
```

## Expected behavior

napari <= 0.2.10 doesn't judge me regarding the number of points I add.

**Comment by kevinyamauchi** [comment]
Hey, @HagaiHargil ! Thanks making the issue. Is the error your received similar to the one in #932 ? If so, we merged a fix in #934. Does that fix the bug you’re encountering?

**Comment by HagaiHargil** [comment]
Hi,

Yes, it works. Not sure how I missed this issue, sorry about that.

**Comment by kevinyamauchi** [comment]
No worries, @HagaiHargil . Sorry about the bug!
