### ISSUE TITLE
change default zoom level

### ISSUE THREAD

**Issue by VolkerH** [napari/napari#986]
## 🐛 Bug

Rather than describing this with words I show a screen recording:

![shapes_opaque](https://user-images.githubusercontent.com/2210044/74895715-84928600-53e6-11ea-8479-b5ee8e71efea.gif)

## To Reproduce

1. add a shape layer
2. set blending mode to additive or opaque
3. choose some colors other than the background color for face and edge 
4. draw a polygon

I wonder whether during drawing inside and outside of the polygon are not clearly defined.

## Expected behavior

Simple polygon with selected input and output color showing up.

## Environment
napari: 0.2.11+27.gbd53848.dirty
Platform: Windows-10-10.0.18362-SP0
Python: 3.7.4 (default, Aug 9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]
Qt: 5.13.1
PyQt5: 5.13.1
VisPy: 0.6.4
NumPy: 1.16.6
SciPy: 1.3.1
scikit-image: 0.16.1
Dask: 2.5.2

GL version: 4.5.0 - Build 25.20.100.6472
MAX_TEXTURE_SIZE: 16384

## Additional context

I have been working a bit with the shape layer today and found several things that I don't understand (possibly bugs). Trying to reproduce them and file some more issues.

**Comment by VolkerH** [comment]
Just realized that this is also happening in translucent blending mode if the edge color is not black.

**Comment by VolkerH** [comment]
There seem to also be an issue with face color (which is 
completely ignored in blending mode translucent). Also, when drawing multiple shapes, only the first shape shows up when drawing in translucent:


![shapes_multiple](https://user-images.githubusercontent.com/2210044/74896640-e653ef80-53e8-11ea-8b4c-4e0eafd1ee26.gif)

**Comment by VolkerH** [comment]
The issue seems to go away when an image layer is added. 
Is the image layer required to establish a proper coordinate system ?

As can be seen in the recording the coordinates shown on the bottom left remain at [0 0] the whole time (rounded to the nearest integer?) when there is no image.

**Comment by VolkerH** [comment]
Talking of face and edge colors,  neither of the drop-down menus offers the option to select "no color" (or transparent). Sometimes I may not want  a face color.

**Comment by sofroniewn** [comment]
@VolkerH what i suspect is happening here has nothing to do with colors, and is not as much a bug in shapes but more a "bug" / "poor choice" about our default zoom level. 

When you open napari with no data I think you are zoomed into a field of view that is [0, 1] x [0, 1]. When you start drawing you have a default edge_width that is 1 and so it takes up the whole FOV. If you use to console to look at the coordinates of your polygon they are probably all `0.x`. If you make the edge_with `0.01` they might look good again.

When you add the image first it resets the zoom to contain the image and so you don't see this problem.

Clearly though this is super confusing and should be fixed. Curious if my explanation does actually match what you see or if something else is going on, and curious if it does if you have suggestions on how to improve things

**Comment by sofroniewn** [comment]
Also - we'll be adding `transparent` to shapes, possible in #898.  Agreed that will be useful

**Comment by sofroniewn** [comment]
For now the best solution to this will probably be to set our default zoom level to be `512 x 512` rather than `1 x 1`
