### ISSUE TITLE
visibility and selection behaviour of multiple polygons in a shape layer is bizarre (broken?)

### ISSUE THREAD

**Issue by VolkerH** [napari/napari#987]
## 🐛 Bug

When defining multiple polygons in a shape layer, they are not all visible in translucent mode although they are non-overlapping. Visibility sometimes stays on a newly created polygon, sometimes it immediately jumps back to a previously defined polygon.
When a polygon is selected and the mouse cursor is moved, visibility and selectability of polygons changes in a way that is inconsistent with the location of the mouse pointer.

This is possibly related to https://github.com/napari/napari/issues/986 (napari version etc is the same).

![visibility_and_selection_of_polygons](https://user-images.githubusercontent.com/2210044/74897164-5020c900-53ea-11ea-95c4-caf46767ad22.gif)

**Comment by VolkerH** [comment]
Just as with #986 the problems disappear if an image layer is added first.

**Comment by sofroniewn** [comment]
Yup, this is also about zoom - what is happening here is that the edge is so thick that you don't see any of the white interior, and so the black edge on the black background makes things look invisible. As with my comment in #986 we should definitely figure out a fix for this as I see how it is super confusing

**Comment by VolkerH** [comment]
Yes, that explanation makes perfect sense.

**Comment by sofroniewn** [comment]
Maybe the thing to do to fix #987 and #986 is just have the camera default to a 128 x 128 FOV or 512 x 512 FOV when there is no data present. We can make that better once we get #885 in too
