### ISSUE TITLE
add github handles to our release notes for contributors / reviewers

### ISSUE THREAD

**Issue by sofroniewn** [napari/napari#995]
## 📚 Documentation
I think it would be nice if we modified the [release generating script](https://github.com/napari/napari/blob/master/docs/release/generate_release_notes.py) so that not only did we put the names of our contributors and reviewers, but we also put their github handles - it might help bridge the gap between names and github handles in our community. See our release notes here https://github.com/napari/napari/releases

**Comment by ruhmamehek** [comment]
Hi, I have worked on this issue. Currently I am generating the output for authors and reviewers in the format: `Name, GitHub handle`

Can someone please guide me on what the preferred output format will be, and if I can also hyperlink the usernames with their corresponding GitHub profiles.

**Comment by sofroniewn** [comment]
Hi @ruhmamehek there's actually some work in #1043 that starts this process. Do you maybe want to look at progress there. Maybe you can help @boonepeter bring it to the finish line - though it looks like we're also waiting for @jni to weigh in over there too

**Comment by boonepeter** [comment]
Thanks @ruhmamehek, I should have mentioned here that I was working on it. The pull request I made works, it's just open in case anyone wants anything different.

**Comment by ruhmamehek** [comment]
Hi @sofroniewn and @boonepeter
Thanks a lot for letting me know! I'll look into other issues then.

**Comment by sofroniewn** [comment]
Closed by #1043
